Automattic/wp-calypso

client/lib/plans/constants.js
client/my-sites/theme/main.jsx
client/my-sites/themes/theme-options.js
client/my-sites/themes/themes-selection.jsx
client/state/themes/selectors.js
client/state/themes/test/selectors.js

Reverts Automattic/wp-calypso#11112

Revert "Premium Squared: Allow elligible premium themes to be activated."

---

client/components/domains/domain-search-results/index.jsx

Just compacts and breaks lines properly for translate calls. No side effects.

Domain Search: Compact translate calls

---

client/my-sites/plugins-wpcom/jetpack-plugins-panel.jsx

This new text better explains what Jetpack is and what it does for the user.
Before:
After:

Plugins: Updating Jetpack explanatory text

---

client/blocks/image-editor/style.scss

Image Editor: Set a minimum height for image editor toolbar

---

client/lib/cart-values/cart-items.js
client/lib/domains/index.js
client/lib/wpcom-undocumented/lib/undocumented.js
client/my-sites/upgrades/checkout/checkout.jsx
client/my-sites/upgrades/checkout/domain-details-form.jsx
client/my-sites/upgrades/checkout/style.scss
client/my-sites/upgrades/domain-management/email/index.jsx

This is the commit that was reverted on Friday (Due to unrelated domain registration issues).
The last commit adds the address fields back to the form.
Testing:
All testing for G Suite for mapped domains has been completed.
Just verify that the address fields are showing up correctly on the domain purchase form.

G Suite for mapped domains

---

client/blocks/image-editor/style.scss

Suggested by @drw158. This PR updates the border colour of the crop controller.

Image Editor: Update crop controller color

---

assets/stylesheets/shared/functions/_z-index.scss
client/blocks/reader-post-card/style.scss
client/reader/_style.scss
client/reader/controller.js
client/reader/following/main.jsx
client/reader/following/style.scss
client/reader/search-stream/style.scss
client/reader/team/main.jsx

Set localStorage.debug = 'calypso:abtests' in the console. You should see yourself being put into the readerSearchOnFollowing abtest, with either the hide or show variation
Also a couple css fixes

Reader: Put users into the abtest

---

client/reader/controller.js
client/reader/discover/controller.js
client/reader/discover/index.js
client/reader/following/controller.js
client/reader/following/index.js
client/reader/full-post/controller.js
client/reader/full-post/index.js
client/reader/index.js
client/reader/liked-stream/controller.js
client/reader/liked-stream/index.js
client/reader/list/controller.js
client/reader/list/index.js
client/reader/recommendations/controller.js
client/reader/recommendations/index.js
client/reader/search/controller.js
client/reader/search/index.js
client/reader/tag-stream/controller.js
client/reader/tag-stream/index.js
client/wordpress-com.js

This reverts commit 67902153b1ac5e5ba50b882f14fd925418374f78.
There is a problem with the Manifest. 
TBD

Revert "moving Reader to a single bundle (#11252)"

---

client/my-sites/site-settings/seo-settings/form.jsx

Removes unused variable from the SEO settings form.

SEO Settings: Removes unused variable from the SEO settings form.

---

client/my-sites/sharing/connections/connection.jsx

Fixes a bug where user queries would fail because the site id was not
set correctly.
Introduced in dc97c60f1465bf56222c0fd61710a35179cefd1d
To test:
Navigate to `/sharing/:site:` and connect a service. When opening the details pane of that service, the outgoing `/site/:site_id:/users` request should now return a result instead of an error.

Sharing: Set site ID before querying site users

---

client/blocks/eligibility-warnings/index.jsx

Editing text on the eligibility warning page.
cc @vindl

AT: update strings in eligibility warnings

---

client/state/posts/utils.js

This was the only thing using it. Should cut bundle size by a fair bit. Currently generating diff.

Posts: Remove usage of lodash/fp

---

client/reader/controller.js
client/reader/discover/controller.js
client/reader/following/controller.js
client/reader/full-post/controller.js
client/reader/list/controller.js
client/reader/search/controller.js
client/reader/tag-stream/controller.js

Async load most sections. To test, load each reader section, both by navigating to it using the sidebar and by loading it directly.

Reader: Async load most streams and following management

---

client/blocks/reader-avatar/style.scss

Currently transparent, which lets backgrounds bleed through.

Reader: Add a white background to avatars

---

client/signup/jetpack-connect/plans.jsx

JPC: Fix free plan

---

client/lib/wp/sync-handler/utils.js
npm-shrinkwrap.json
package.json

Cuts build by 7k after gzip
430257 before
423177 after
No functional changes

Build: Remove jshashes in favor of js-sha1

---

client/lib/post-normalizer/rule-content-detect-media.js
client/lib/posts/utils.js

Also, teach detectImages about natural height and width and about the magic data-orig-size attribute

Posts: Fix how we detect images in posts

---

config/desktop.json
config/production.json

Enables Medium importer in production and desktop environments.

Import: Enable Medium importer in production

---

client/lib/abtest/active-tests.js
client/my-sites/upgrades/checkout/domain-details-form.jsx

This patch removes the A/B test for PhoneInput and deploys it to all users.

Domains: Signup: Remove PhoneInput A/B Test

---

client/components/tinymce/README.md
client/components/tinymce/index.jsx
client/components/tinymce/plugins/wpcom-track-paste/plugin.js

This PR adds the ability to track paste events in Calypso editor.

Tracks paste events in Calypso editor

---

client/my-sites/plans/main.jsx
client/signup/jetpack-connect/plans-grid.jsx

jetpack plans are disabled, this fixed it:

Plans: Enable Jetpack Plans again

---

client/my-sites/theme/controller.jsx

Previously, the long description wasn't displayed in the server-rendered theme sheet because `description_long` wasn't normalized to `descriptionLong`.
Instead of adding `normalizeWpcomTheme` manually, it's way better to use `requestTheme` to avoid duplicating its implementation.
To test:
* Stop Calypso, enable server debugging (`export DEBUG="calypso:server-render"`), start Calypso.
* In logged-out mode, disable JavaScript and load a theme sheet. It should have the long description (instead of the short one).
* In the (node) Console, observe that caching still works.
props @seear for spotting this
Aside -- reducing this kind of manual futzing in the controllers is one of the motivations for #10988

SSR/Theme Sheet: Use requestTheme() in controller

---

client/lib/plans/constants.js
client/my-sites/posts/post-share.jsx
client/my-sites/posts/style.scss
client/state/sites/plans/selectors.js

This PR restricts republicize only for Premium / Business plans
1. Get a free site
2. Go to Post list
3. Click share
4. See Nudge
5. Get a premium site
6. Go to post list
7. Click share
8. See sharing menu
CC @gwwar @rralian @lamosty @gziolo @enejb

Republicize: Only for premium / business

---

client/my-sites/themes/themes-selection.jsx

`source` is undefined in logged out so we have to expand check to also check that.

Fix themes count in logged-out

---

client/components/emojify/README.md
client/components/emojify/docs/example.jsx
client/components/emojify/index.jsx
client/components/emojify/style.scss
client/devdocs/design/index.jsx
config/_shared.json
npm-shrinkwrap.json
package.json

Update the twemoji library to 2.2.5.
https://github.com/twitter/twemoji
Fixes #10028.

Upgrade to v2.2.5 of twemoji

---

config/desktop.json
config/horizon.json
config/production.json
config/stage.json
config/test.json

This releases republicize to all.

Republicize:Release

---

client/post-editor/editor-drawer/index.jsx

Reverts Automattic/wp-calypso#11476

Revert "Editor: Hide SEO description for private/hidden sites"

---

client/post-editor/media-modal/detail/detail-item.jsx

This PR enables the image-editor for those Jetpack sites which have a version greater or equal than `4.7-alpha`.
Try to edit an image for sites with different Jetpack versions. Depending on this, the `Edit Image` button should be shown or hidden. 
**Jetpack version greater or equal to `4-7-alpha`
**Not valid Jetpack site**
--------
_`updated: 2017-02-28` by @retrofox_

Image-Editor: Enable image-editor for Jetpack sites

---

client/components/button-group/index.jsx
client/components/popover/style.scss
client/my-sites/media-library/content.jsx
client/my-sites/media-library/content.scss
client/my-sites/media-library/header.jsx
client/my-sites/media-library/index.jsx
client/my-sites/media-library/scale.jsx
client/my-sites/media-library/style.scss
client/my-sites/media-library/upload-button.jsx
client/my-sites/media/main.jsx
client/post-editor/media-modal/index.jsx
client/post-editor/media-modal/secondary-actions.jsx

Closes task #10805
- Restyles buttons into more compact ones and uniform ones
- Removes secondary actions from the bottom of modal view
- Removes Disk space usage from secondary actions component
CC @iamtakashi @rralian @gwwar

Media section: Action bar buttons + card

---

client/lib/user/user.js

The user is always fresh when the client boots in production because user bootstrapping is enabled, but is always stale in development because the user object comes from local storage before it is fetched. This makes it possible for us to miss production-only bugs or spend time fixing development-only bugs.
For example, we have code that determines if we need to refetch `sites-list` before redirecting to the sitepicker if the user accesses a site that is missing from `sites-list` [here](https://github.com/Automattic/wp-calypso/blob/master/client/my-sites/controller.js#L285). We check if `sites-list` is missing a site by comparing its length to the `visible_site_count` property of the user. This is reliable in production, as the user object is provided in the page, but breaks in …

Framework: Stop caching the user in local storage

---

client/lib/user/user.js

Reverts Automattic/wp-calypso#11281

Revert "Framework: Stop caching the user in local storage"

---

client/post-editor/editor-html-toolbar/index.jsx

Enable drag and drop capability to the editor in HTML mode.
I've mostly used readily made code from both the **Media Library** and the **TinyMCE** drag and drop logic.
See:
- https://github.com/Automattic/wp-calypso/blob/master/client/my-sites/media-library/drop-zone.jsx
- https://github.com/Automattic/wp-calypso/blob/master/client/components/tinymce/plugins/media/drop-zone.jsx#L94-L122

Editor: Add drag and drop media to the HTML mode

---

client/extensions/wp-super-cache/index.js
client/extensions/wp-super-cache/package.json

This PR adds a placeholder section for WP Super Cache.

Add WP Super Cache extension

---

client/blocks/reader-featured-video/index.jsx

We were leaking this until this commit.

Reader: Unhook the FeaturedVideo resize listener on unmount

---

client/my-sites/theme/main.jsx
npm-shrinkwrap.json
package.json

Reverts Automattic/wp-calypso#10389
Third time's a charm :crossed_fingers:

Framework: Upgrade to react-redux v5, take 3

---

client/my-sites/theme/main.jsx
npm-shrinkwrap.json
package.json

Reverts Automattic/wp-calypso#10398
Just in case. cc @blowery

Revert "Framework: Upgrade to react-redux v5, take 3"

---

client/reader/stream/x-post.jsx

es6ifying the  Reader x-post component.
There should be no functional differences

Reader janitorial: es6ifying x-post

---

config/horizon.json

Add a feature flag to enable the editor HTML toolbar to Horizon.

Editor: enable the HTML toolbar to Horizon

---

client/state/themes/actions.js
client/state/themes/selectors.js
client/state/themes/test/actions.js

Reverts Automattic/wp-calypso#11516

Revert "Themes: Filter all received themes"

---

client/boot/index.js
client/layout/index.jsx

Reverts Automattic/wp-calypso#11714

Revert "Build: Async load HappyChat and network detection"

---

.gitignore
Makefile
assets/stylesheets/_components.scss
assets/stylesheets/directly.scss
assets/stylesheets/style.scss
client/lib/directly/style.scss

Creates customized styles for Directly's Real Time Messaging widget. The goal is to make the RTM widget feel more native to Calypso and more similar to the Happychat interface.
Due to the widget's architecture, a few extra steps are needed to view our custom CSS in development. **Please read the comment block at the top of [assets/stylesheets/directly.scss](https://github.com/Automattic/wp-calypso/pull/11600/files#diff-ace0466620b3191b23dec85ee11ecc08) for instructions to view the custom CSS in development.**
* Restart your local Calypso (to build the new CSS file)
* Install the Chrome extension [Switcharoo Redirector](https://chrome.google.com/webstore/detail/switcheroo-redirector/cnmciclhnghalnpfhhleggldniplelbg) and use it to redirect the URL …

Directly: Customize styles

---

client/my-sites/themes/theme-upload/index.jsx

PR #10434 that necessitated this fix has been reverted, so revert this fix as well.

Revert "Themes: Fix actions from uploaded theme confirmation (#11843)"

---

client/me/purchases/confirm-cancel-domain/index.jsx

Fixes #11811.
This PR updates `ConfirmCancelDomain` to remove the domain-only site from the two places we store sites when a domain purchase from a domain-only site is deleted, as this deletes the site as well. We made this change already in `RemovePurchase`, but did not add it to `ConfirmCancelDomain`, which is (I believe) because there was previously a bug in the REST API where domain-only purchases were not refundable, and `ConfirmCancelDomain` is only used during the refund window for domains.
**Testing**
- While logged out, visit `/start/domain-first?new=DOMAIN` where `DOMAIN` is an unregistered domain like `some-example-here.live`
- Select `Just a domain`.
- Proceed through signup, creating a new account.
- Purchase the domain in checkout.
- Visit `/purchases`.
- Click on the domain …

Purchases: Remove domain-only site from `sites-list` and `state.sites` in `ConfirmCancelDomain`

---

client/blocks/plan-storage/style.scss
client/my-sites/media-library/style.scss

Plan Storage: Minor style adjustments

---

client/my-sites/media-library/upload-url.jsx

This PR is part of a set of PRs. Take a look to https://github.com/Automattic/wp-calypso/issues/11804, Pull requests section, to know to right order to review.
This PR is targeting to `try/media-section-v2`.
---------
This PR is just for janitorial purposes. Re writes `upload-url` component in ES6, add `translate` helper, etc.

Media Library: upload-url janitorial

---

client/notifications/index.jsx

Just a cache bust for a version bump

Notifications: Bust cache corresponding to new updates

---

client/my-sites/site-settings/composing/after-the-deadline.jsx

This PR will disable the "After the Deadline" settings if the current Jetpack site is in development mode. Related with #11386.
Preview when disabled & collapsed:
Preview when disabled & expanded:
To test:
* Select one of your Jetpack sites and enable dev mode by adding this to your wp-config.php: `define( 'JETPACK_DEV_DEBUG', true );`
* Verify the "After the Deadline" settings in the Writing tab are disabled and can't be toggled.
* Disable the Dev mode by deleting the line we just added to wp-config.php.
* Verify the "After the Deadline" settings are now enabled and can be toggled.
/cc @rickybanister @MichaelArestad because I have the feeling that we need do something more in addition to just disabling the fields in that case (as also mentioned here: …

Site Settings: Disable After the Deadline when in Dev mode

---

client/components/search/style.scss
client/my-sites/themes/themes-magic-search-card/index.jsx
client/my-sites/themes/themes-magic-search-card/style.scss

This PR contains experiments for styling of the magic search component to find a combination that works given the technical restraints of the overlaid layers.

Themes: update magic search styling

---

client/me/help/help-contact/index.jsx

Add tracks for starting Happychat, uses same stat and
behavior as when starting an Olark chat.
Fixes: 164-gh-happychat

Happychat - add tracks for starting chat

---

client/notifications/index.jsx

Got my sequencing wrong - this is a redo to coordinate with the notifications commit

Notifications cache buster update

---

client/blocks/reader-combined-card/style.scss

Fixes design issues in #11913.
After:
cc @fraying

Reader: Fix combined cards styling

---

client/my-sites/themes/theme-upload/index.jsx

This PR fixes a small typo in #11673 that we picked up during translation
Just to do things by the book, @budzanowski Would you mind reviewing and merging this?

Fix typo in automated transfer guard

---

client/post-editor/editor-ground-control/index.jsx

Editor: do not trigger preview when it is disabled.

---

jsconfig.json

This teaches VS Code how to find code so it can build intellisense for calypso.

Tools: Add in a jsconfig.json for VSCode

---

client/lib/directly/README.md

No code here just README. Are these explanations clear?

Directly: Add a few gotchas to the README

---

client/lib/sites-list/docs/example.jsx

Site: add example of "compact" version in devdocs.

---

client/my-sites/themes/theme-upload/index.jsx

A redo of #11843, which was supposed to make it into #11885 but somehow got missed out.

Themes: Fix actions from uploaded theme confirmation

---

client/lib/reader-post-flux-adapter/index.js

Reader: Load minimal posts as well as missing posts

---

client/my-sites/plugins/plugin-information/style.scss
client/my-sites/plugins/plugin-meta/style.scss

Fixes: #12146 
Test:
- AT and non-AT sites
- mobile and desktop
- installed, not installed
Before:
After:

Plugins: fix overflowing actions

---

client/blocks/reader-post-card/byline.jsx
client/blocks/reader-post-card/style.scss
client/lib/abtest/active-tests.js

Also support an arbitrarily long set of tags and prevent the avatar from collapsing

Reader: Try out showing 3 tags max on stream cards

---

client/blocks/author-compact-profile/style.scss
client/blocks/follow-button/style.scss
client/blocks/reader-combined-card/style.scss
client/blocks/reader-post-card/style.scss
client/reader/search-stream/style.scss

This PR fixes #11979 by changing all blue links and buttons to $blue-medium and hovers to $blue-light.

Reader: Fix link/hover blues

---

client/blocks/reader-related-card-v2/style.scss
client/reader/stream/_style.scss

This PR:
* right align follow-button
* adjust vertical alignment of follow-button
Resolves: #12149

Reader: reposition follow-button

---

client/blocks/reader-combined-card/index.jsx
client/blocks/reader-combined-card/style.scss
client/reader/follow-button/follow-sources.jsx
client/reader/stream/index.jsx

Reader: add follow button to combined cards

---

client/lib/reader-post-flux-adapter/index.js

Teach the Flux Post Adapter that updating when props change is ok.

Reader: Fix keyboard selection of combo cards

---

client/my-sites/themes/theme-upload/index.jsx

Theme: Add error code to notice for unknown errors

---

client/blocks/reader-combined-card/style.scss
client/blocks/reader-post-card/style.scss

Reader: Try smaller title fonts in streams

---

client/components/suggestions/index.jsx
client/my-sites/themes/themes-magic-search-card/welcome.jsx

In MagicSearch suggestions start without default element chosen. This PR changes the behavior.
Now both welcome card and suggestions have a default( first on the list) element selected and ready for being picked with `Enter`
@folletto This is the idea I had for default pick - minimal code changes ( most is just a cleanup I did on the way )

MagicSearch: suggestions will have first option highlighted and ready.

---

client/lib/wp/browser.js
client/lib/wp/handlers/guest-sandbox-ticket.js
client/lib/wp/handlers/test/guest-sandbox-ticket.js

Requires D4451-code. More information about this change (and testing instructions) are available on that patch.

Checkout: Add `guest-sandbox-ticket`

---

client/lib/abtest/active-tests.js
client/signup/steps/theme-selection/signup-themes-list.jsx

This test was set to 10%, I'm just turning it off for now so it doesn't get confused with the AT flow.

AT: Remove theme-upload nux variant with the new AT capability

---

client/my-sites/post-share/index.jsx
config/development.json

props to @lamosty
- squash/reword

post-share: add isSchedulingEnabled() method

---

client/blocks/reader-post-card/style.scss

Reader: Adjust card title line-height

---

client/post-editor/editor-action-bar/index.jsx
client/post-editor/editor-visibility/index.jsx
client/post-editor/post-editor.jsx

This revers #12320 because publishing a post after entering a password is not working as expected

Revert "Editor: Reduxify EditorVisibility Component (#12320)"

---

config/desktop.json

(Tested using https://github.com/Automattic/wp-desktop/pull/275)

Themes: Enable Jetpack activation and upload in desktop app

---

client/extensions/wp-job-manager/index.js
client/extensions/wp-job-manager/package.json

This PR adds a placeholder section for WP Job Manager

Extensions: Adding WP Job Manager extension base

---

config/stage.json

Turn on theme showcase 'magic search' in staging environment.

Themes: Enable enhanced theme search on stage

---

config/desktop.json
config/horizon.json
config/production.json
config/stage.json
config/test.json

This PR enables Reader combined cards in all environments 🚀

Reader: enable combined cards in all environments

---

client/extensions/sensei/index.js
client/extensions/sensei/package.json

This PR adds a placeholder section for Sensei

Extensions: Adding Sensei extension base

---

client/my-sites/post-share/index.jsx

It adds just a preview button `<Button />` with a bound method. Let's leave the styles adjustments to @iamtakashi.

post-share: add `Preview` button

---

client/state/selectors/index.js
client/state/selectors/is-deleting-publicize-share-action.js
client/state/selectors/is-editing-publicize-share-post-action.js
client/state/selectors/is-fetching-publicize-share-actions.js
client/state/sharing/publicize/publicize-actions/actions.js
client/state/sharing/publicize/publicize-actions/reducer.js

- adds edit and delete actions
- fixes problem @retrofox pointed out with state tree naming
- adds full crud in redux of publicize scheduling

Publicize scheduling: Redux continue

---

client/post-editor/style.scss
server/pages/index.jade
server/pages/index.js

Server: add editor specific loading shell.

---

client/my-sites/post-share/style.scss

This PR updates RePublicize panel styling.

Sharing: Update RePublicize style

---

.github/CONTRIBUTING.md
client/devdocs/style.scss
docs/development-workflow.md
docs/install.md

CONTRIBUTING.md: Add tip for AnyBar integration

---

npm-shrinkwrap.json
package.json

Latest and greatest. Because we can.
...now that #11726 is fixed (thanks @mcsf!)
[ChangeLog](https://github.com/reactjs/react-redux/releases/tag/v5.0.3)

Framework: Upgrade react-redux to 5.0.3

---

client/my-sites/posts/post-share.jsx

Related: https://github.com/Automattic/wp-calypso/pull/12387#discussion_r107251827

Post share: replace dot dot dot with ellipsis character

---

client/components/popover/util.js
client/lib/importer/test/api-interaction.js
client/lib/interval/test/component.jsx
client/lib/perfmon/index.js
client/lib/viewport/index.js

Related: #8562
This pull request continues the crusade to upgrade all ESLint rules to errors by resolving remaining issues with [`brace-style` rule](http://eslint.org/docs/rules/brace-style).
**Testing Instructions:**
That CircleCI passes is indication that the changes included are working as intended.
Verify that no regressions have been introduced to affected sections.

Framework: Upgrade ESLint brace-style to error

---

client/my-sites/post-share/constants.js
client/my-sites/post-share/index.jsx
client/my-sites/post-share/publicize-actions-list.jsx

This PR splits up `<PostShare />` component creating a new `<PublicizeActionsList />`.
Test the whole post share section. Everything should be fine.

PostShare: split component

---

client/lib/auth-code-request-store/index.js
client/reader/following-edit/import-button.jsx
client/reader/following-edit/index.jsx

Related: #8562
This pull request continues the crusade to upgrade all ESLint rules to errors by resolving remaining issues with [`curly` rule](http://eslint.org/docs/rules/curly).
**Testing Instructions:**
That CircleCI passes is indication that the changes included are working as intended.
Verify that no regressions have been introduced to affected sections.

Framework: Upgrade ESLint curly to error

---

client/my-sites/upgrade-nudge/index.jsx

We had some problems with nudge showing when its not supposed to.
CC @rralian @lamosty

Nudge: double check for site object

---

client/layout/masterbar/drafts.jsx

We don't know the correct userId for the Jetpack site at this stage, so we can't use it.

Masterbar Drafts: do not use currentUser as author id for jetpack sites.

---

npm-shrinkwrap.json
package.json

This PR fix an issue linting big files.

Update eslines version

---

client/boot/index.js

Retry of https://github.com/Automattic/wp-calypso/pull/11110

Load: Async load olark

---

client/reader/search-stream/index.jsx
client/reader/search/controller.js

Add new tracks event and mc action for clicking on the selector pill
Update existing calypso_reader_search_performed to include sort.

Reader: Add stats for search sort

---

client/blocks/reader-post-options-menu/index.jsx

I'm currently on a crusade to get rid of SiteStore and FeedStore. 
This is composed of two commits:
1. es6ify
2. localize + connect (to get rid of SiteStore)

Connect reader-post-options-menu

---

client/blocks/reader-post-card/style.scss
client/reader/_style.scss
client/reader/list-gap/_style.scss
client/reader/list-stream/style.scss
client/reader/stream/_style.scss

We are consolidating some of reader colors and x-posts got forgotten.

Reader: darken x-post border bottom by 10%

---

client/post-editor/style.scss

Fixes #12553
Screenshot:
CC: @hoverduck

Editor: Fix issue where sidebar footer was hidden in the editor.

---

client/lib/happychat/connection.js
client/state/happychat/middleware.js
client/state/happychat/reducer.js
client/state/happychat/selectors.js
client/state/happychat/test/middleware.js

This reverts commit ab867471d827a97abf71462d1e74d7c3e08d15ba.

Revert "Send route events to happychat (#12180)"

---

client/reader/stream/_style.scss

Currently affects everything Reader.
Fixes #12563

Reader: Antialias fonts in the Reader

---

client/reader/stream/_style.scss

Refinement of earlier commit that applied antialiasing to all type in the streams. Makes UI elements a bit bolder.

Reader: Restrict antialias to user content in stream

---

client/controller/index.web.js

Reverts Automattic/wp-calypso#12610
Issue:
> Portfolio post type is not working.. if I click the Add button I can create a new project, but unable to view existing projects or testimonials from Calypso.

Revert "Framework: Remove renderSeparateTrees() Helper"

---

config/client.json

this json should now validate 🤖

Fix: add missing comma to config json

---

client/reader/stream/post-lifecycle.jsx

fixes https://github.com/Automattic/wp-calypso/issues/12642

Reader Fix: placeholders should render while fetching posts

---

client/blocks/reader-feed-header/index.jsx

Use the URL instead of the feed_URL, if present.
Fixes #12509

Reader: Fix how we link to the real site in the feed header

---

client/lib/sites-list/list.js
client/lib/wpcom-undocumented/lib/undocumented.js
client/state/jetpack-connect/actions.js
client/state/jetpack-connect/test/actions.js
client/state/sites/actions.js
client/state/sites/test/actions.js

We are treating domain only sites as regular ones, while this should've been parametrized. Update as we added the param for mobile.

Sites List: Add include_domain_only param

---

client/lib/resize-image-url/index.js

Reverts Automattic/wp-calypso#12672

Revert "Revert "Framework: make resize-url deal with missing hostnames""

---

client/blocks/reader-featured-image/style.scss
client/blocks/reader-related-card-v2/style.scss

This PR standardizes all image border colors in stream and full in post to the same value and fixes #12570.

Reader: Fix image border colors

---

client/post-editor/editor-featured-image/index.jsx
client/post-editor/editor-featured-image/style.scss

Fixes #12053 
- Follow steps in original issue (#12053), make sure the observed behavior is now the expected.
- Make sure that, overall, Featured Image still works and looks as usual.

Editor: Reduce Featured Image click area to image itself

---

client/components/tinymce/iframe.scss

This bumps the font size to 16px, as made necessary by the change to Noto Serif.
Feel free to merge in, @drw158, if you feel it looks right. Looks 👍 from me.

Editor: Bump font size

---

client/blocks/comments/comment-actions.jsx
client/blocks/comments/post-comment-list.jsx
client/blocks/comments/post-comment.jsx
client/blocks/comments/style.scss
client/my-sites/posts/post.jsx

Adds new properties to show the comment filters and moderation tools only on Posts.

Posts: hide comment moderation tools on the Reader

---

bin/run-lint

Make sure ESLint runs by breaking the build if we have any ESLint error.

Run eslint on CircleCI

---

server/bundler/extensions-loader.js

Some of the promise wrangling was redundant, so there was that to refactored. Aditionally, the semantics have changed slightly, reflecting an initial probing of available directories (see `pathExists`) and a final pass using `map( generateReducerRequireString )` — making `getReducersAsync` a little more symmetric to `getReducersSync`.
Build should occur with no hiccups. Calypso itself should run exactly the same. Extensions that have reducers (`/hello-dolly`) should continue to perform with state of their own; those with no reducers (e.g., `/extensions/wp-super-cache/:siteId`) should perform with no custom state.

Extensions: Loader: Refactor getReducersAsync

---

client/my-sites/plugins-wpcom/plugin-install-button.jsx

Tracking events parameters must be snake_case

AT: fix ineligibility event tracking 

---

client/blocks/reader-post-card/byline.jsx
client/lib/abtest/active-tests.js

Conclude the abtest, release the better variant.

Reader: Turn on 3 tags in stream for everyone

---

client/blocks/reader-post-card/byline.jsx
client/lib/abtest/active-tests.js

Reverts Automattic/wp-calypso#12824

Revert "Reader: Turn on 3 tags in stream for everyone"

---

client/reader/tag-stream/main.jsx

Fixes #12843
See the bug report for testing instructions.

Reader: Fix the tag events when following from the header

---

bin/run-lint
npm-shrinkwrap.json
package.json

Fixes https://github.com/Automattic/wp-calypso/issues/12797

Make eslines quiet: only report errors

---

client/lib/automated-transfer/index.js
config/development.json
config/horizon.json
config/production.json
config/stage.json
config/wpcalypso.json

This temporarily disables new transfers while we fix some things. Existing AT sites should still see AT features.

AT: temporarily disable new transfers

---

config/horizon.json
config/production.json
config/stage.json
config/wpcalypso.json

This PR enables new transfers for AT.

AT: renable new transfers

---

client/my-sites/themes/controller.jsx

We were previously avoiding caching urls with query params, but still rendering the themes list (because of the `loggedOut` middleware) on the server.
This is locking out the server event loop for little gain, so avoid SSR altogether for URLs with search queries.
For example `wordpress.com/design?s=fancy`
**To Test**
* In a logged-out browser window, hit a URL such as http://calypso.localhost:3000/design/free?s=blue
* Only the masterbar at the top should be rendered on the server
* This can be tested by turning off JS in the console
* Everything else should work as before

Themes: Don't server-render urls with query params

---

client/blocks/comments/style.scss
client/blocks/reader-combined-card/style.scss
client/blocks/reader-full-post/_content.scss
client/blocks/reader-post-card/style.scss
client/blocks/reader-related-card-v2/style.scss

This fixes: https://github.com/Automattic/wp-calypso/issues/12683

Reader: Update serif fonts by 1px

---

client/components/domains/register-domain-step/index.jsx
client/lib/abtest/active-tests.js

Show 'recommended' and 'best alternative' labels in domain suggestions as they increase domain and plan sales.

Domain Search: Add labels to domain suggestions

---

assets/stylesheets/shared/functions/_z-index.scss

Hi, 
Please let me know if this is not the correct way to fix. Though this works in local dev environment and billing date popover is now has higher z-index.

Fix z-index of Billing filter popover

---

client/blocks/login/index.jsx
client/blocks/login/style.scss
client/blocks/login/test/index.jsx
client/login/wp-login/index.js
client/login/wp-login/style.scss

This pull request updates the design of the login form based on the designs in p6qnuF-4lz-p2.
The designs don't match the mockups exactly, as I have tried to stick to existing Calypso colours where possible. @josemarques, can you review these difference and see what you think?
1. Run `git checkout update/login-design` and start your server, or open a [live branch](https://delphin.live/?branch=update/login-design)
2. Open the [`Login` page](http://calypso.localhost:3000/login)
3. Check that the design matches the mockup
There is more work to do with notices, but this PR is big enough already.
@Automattic/sdev-feed

Login: Update the login screen to match the mockups

---

client/state/terms/actions.js
client/state/terms/test/actions.js

Fixes #9943 - When deleting a category, all posts assigned to that category get assigned to a site's default category.  Currently when doing this action via the TaxonomyManager - the old post count on the default category is not updated until the page is refreshed, or an action triggers a new fetch via `QueryTerms`.
This proposed solution kind of feels a bit hackish to me, but was the better of my two hackish ideas.  So please bring other suggestions to to this problem if you can think of them!
__To Test__
- Setup a test site with at least 2 categories
- Publish a post into the non-default category
- Visit the Category Manager via Settings > Writing
- Note the (1) count next to the non-default category
- Delete the non-default category
- Verify the category deletes as expected, and the …

Taxonomy Manager: Trigger a term refresh after deleting item.

---

client/blocks/reader-post-card/style.scss

Reader: Fix Photo Card titles getting cut off

---

client/blocks/reader-combined-card/style.scss

**Before:**
**After:**
/cc @fraying

Reader: Fix Combined Cards titles/excerpts cropped in mobile

---

client/my-sites/customize/controller.js
client/my-sites/customize/index.js

Needed for https://github.com/Automattic/wp-calypso/pull/12998.
To test: Make sure that the customizer still works.

Customizer: ES6ify Controller and Route Defs

---

client/blocks/plan-thank-you-card/index.jsx
client/my-sites/upgrades/checkout-thank-you/jetpack-thank-you-card.jsx
client/my-sites/upgrades/checkout-thank-you/style.scss

We've got auto-config for Jetpack plans to a point where the UI looks good. We need to start working on the error messaging and edge cases. This PR is meant to start with that.

Plans: Show error notice when we can not update files

---

client/state/selectors/get-sites.js
client/state/selectors/index.js
client/state/selectors/test/get-sites.js

A product of #13094. Not used in code yet.

Selectors: Add getSites()

---

client/state/sites/actions.js

Pages: Fix setFrontPage to handle setting Blog Posts as homepage

---

client/state/reader/feeds/schema.js
client/state/reader/feeds/test/schema.js

Yes, tests for schema.
This was currently failing to validate feeds that have null names and URLs.

Reader: Fix the feed schema, add tests

---

client/extensions/wp-super-cache/main.jsx
client/extensions/wp-super-cache/preload-tab.jsx
client/extensions/wp-super-cache/style.scss
client/extensions/wp-super-cache/wrap-settings-form.jsx

Extensions: WP Super Cache - Introduce Preload Tab

---

client/components/search-card/index.jsx
client/components/search/index.jsx
client/components/search/style.scss
client/reader/following-manage/index.jsx
client/reader/following-manage/search-followed.jsx
client/reader/following-manage/style.scss
client/reader/following-manage/subscriptions.jsx

Adds the search box for searching existing feeds:
Part of #12960.

Reader Manage Following: add search followed sites UI

---

config/development.json

Reader: Add in a feature flag for sites in search

---

client/components/jetpack-logo/index.js
client/layout/sidebar/style.scss
client/my-sites/sidebar/sidebar.jsx

Add Jetpack logo as icon for plans.

---

client/me/purchases/controller.jsx
client/me/purchases/index.js
client/me/purchases/purchases-list/index.jsx
client/my-sites/controller.js

Me: remove sites-list from purchases list.

---

client/my-sites/upgrades/controller.jsx

This PR is a partial cleanup for sites-list usages in client/my-sites/upgrades/controller. We can't fully remove it in this section yet until some child components are refactored to not expect a SitesList prop.
See related #12943, #12804

Framework: clean up some controller usages of sites-list

---

client/extensions/wp-super-cache/caching.jsx
client/extensions/wp-super-cache/easy-tab.jsx

Reverts Automattic/wp-calypso#12926

Revert "WPSC: Update the caching label to be more descriptive"

---

client/extensions/wp-super-cache/caching.jsx
client/extensions/wp-super-cache/easy-tab.jsx

Change label to Enable Page Caching

---

client/lib/happychat/connection.js
client/state/happychat/middleware.js
client/state/happychat/reducer.js
client/state/happychat/selectors.js
client/state/happychat/test/middleware.js

Send user navigation events to happychat

---

client/me/help/controller.js

Fixes error when loading contact page.

Adds missing import statement

---

client/blocks/reader-avatar/index.jsx

Run siteIcon and feedIcon through safeImageUrl just to make sure they're coming in over https.
Fixes #13357

Reader: Make sure ReaderAvatar icons are safe

---

client/lib/post-normalizer/rule-content-remove-styles.js
client/lib/post-normalizer/rule-create-better-excerpt.js
client/lib/post-normalizer/test/index.js

Reader: Remove align attributes from excerpts

---

client/blocks/reader-combined-card/style.scss

Reader: Limit site titles to single line in Combined Cards

---

client/lib/analytics/index.js
client/lib/signup/step-actions.js
client/signup/main.jsx

Reverts Automattic/wp-calypso#11715

Revert "Signup: Alias anonUserId to WPCOM user id when user is created"

---

client/my-sites/plugins/plugin-information/style.scss

Plugins: remove flash of W on placeholder loading state of single plugin view

---

client/blocks/reader-post-card/byline.jsx

To test, load Discover
fixes #13616

Reader: Fix how we suppress author names

---

client/lib/post-normalizer/rule-content-make-embeds-safe.js
client/lib/post-normalizer/utils.js

Fixes https://wordpress.com/read/feeds/188407/posts/1444941409

Reader: Let TED embeds out of the sandbox

---

client/layout/masterbar/item.jsx
client/layout/masterbar/notifications.jsx
client/layout/masterbar/style.scss

@See #13581
Makes adjustments from master instead of integration branch for
notifications client.
cc: @vindl

Rebase of changes in #13581 against master

---

client/blocks/reader-related-card-v2/index.jsx
client/lib/post-normalizer/rule-content-make-embeds-safe.js
client/lib/post-normalizer/utils.js

Fixes some of the busted embeds listed found in internal testing. The remaining busted embeds require special script handling to work.

Reader: Fix various embeds

---

client/components/signup-form/index.jsx
client/lib/wpcom-undocumented/lib/undocumented.js
client/my-sites/people/controller.js
client/my-sites/people/invite-people/index.jsx
client/my-sites/people/invite-people/style.scss
client/my-sites/people/people-list-section-header/index.jsx
client/my-sites/sidebar/sidebar.jsx

This change requires that D5206 and a Jetpack patch be deployed first.
Testing instructions to come later.

Invites: First pass at invites for Jetpack sites

---

client/lib/abtest/active-tests.js
client/lib/automated-transfer/index.js
client/lib/plans/constants.js

Running some tests first, but this should open up AT to all business users.

AT: removes the abtest check, which opens AT to all biz owners

---

npm-shrinkwrap.json
package.json

This fixes #13707 a regression where the spinner styling was being clobbered by notifications-panel. ( https://github.com/Automattic/notifications-panel/pull/87 )
Other Fixes include:
* Fix transition between list and detail view: https://github.com/Automattic/notifications-panel/pull/89
* Fixing a border in notification-panel https://github.com/Automattic/notifications-panel/pull/88
- Spinner component looks correct in http://calypso.localhost:3000/devdocs/design/spinner and in the Notifications panel

Notes: update notifications-panel to 1.1.5

---

client/reader/following-manage/feed-search-results.jsx

Addresses https://github.com/Automattic/wp-calypso/issues/13722

Reader FeedSearch results: show 10

---

client/components/domains/domain-registration-suggestion/index.jsx

Add cctld "Testing only" tags

---

assets/stylesheets/_components.scss
client/blocks/reader-recommended-sites/docs/example.jsx
client/blocks/reader-recommended-sites/index.jsx
client/blocks/reader-recommended-sites/style.scss
client/blocks/reader-subscription-list-item/index.jsx
client/blocks/reader-subscription-list-item/style.scss
client/devdocs/design/blocks.jsx

This PR is just to create the new RecommendedSites block and add it to the devdocs.
**Wider viewports:**
**Narrow viewports:**
1. Go to https://calypso.live/devdocs/blocks/reader-recommended-sites?branch=add/reader/recommended-sites-block
2. resize like a madman and make sure it looks good at all breakpoints

Reader: add recommended sites block

---

client/lib/abtest/active-tests.js
client/signup/steps/theme-selection/index.jsx

We concluded a test on the theme step in our signup flow. The test introduced new copy but was unsuccessful in at improving conversions. This PR removes the test. 
cc @Automattic/marketing-dev

Removed signup theme step a/b test

---

client/signup/steps/design-type-with-store/domain-image.jsx
client/signup/steps/design-type-with-store/new-site-image.jsx
client/signup/steps/site-or-domain/choice.jsx
client/signup/steps/site-or-domain/index.jsx
client/signup/steps/site-or-domain/style.scss

- Localize strings in domain-first flow
- Make the whole boxes clickable
- Fix .jsx SVG for new-site/domain images

Tortuga: UX updates and proper localization

---

client/reader/following/intro.jsx
config/desktop.json
config/horizon.json
config/production.json
config/stage.json
config/test.json
config/wpcalypso.json

Releases the Reader Following Intro banner for new users on all environments 🎉

Reader: release following intro banner to everyone

---

client/components/embed-container/index.jsx

http://calypso.localhost:3000/read/feeds/25320833/posts/1454453490 vs https://wordpress.com/read/feeds/25320833/posts/1454453490
Fixes #1549

Reader: Add support for reddit embeds

---

client/extensions/wp-super-cache/wrap-settings-form.jsx

See https://github.com/reactjs/react-redux/blob/master/docs/api.md#connectmapstatetoprops-mapdispatchtoprops-mergeprops-options

Extensions: WPSC: WrappedSettingsForm: Use mapDispatchToProps shorthand

---

client/blocks/login/two-factor-authentication/waiting-notification-approval.jsx

This is a copy change on followup to #13742

Change loading message while redirecting

---

client/blocks/reader-avatar/index.jsx

Reader: If we prefer the blavatar, suppress the avatar entirely

---

client/reader/following-manage/feed-search-results.jsx
client/reader/following-manage/index.jsx
client/reader/following-manage/style.scss
client/reader/following-manage/subscriptions.jsx

Reader Feed Search Results: error handling

---

config/horizon.json
config/stage.json

We've started a call for testing for Search on Manage / the manage refresh. seems like a good time to put it in staging.

Reader Search on Manage: enable SoM in staging

---

client/blocks/reader-feed-header/style.scss

Reader: Fix clipped Back button mobile

---

client/blocks/reader-recommended-sites/style.scss
client/blocks/reader-subscription-list-item/style.scss

This fixes: https://github.com/Automattic/wp-calypso/issues/13942 and fixes `long-content-fade` which weren't showing up.

Reader: Fix rec sites fade and padding

---

npm-shrinkwrap.json
package.json

Framework: Switch over to named branch for prettier

---

client/my-sites/post-share/connection.jsx
client/my-sites/post-share/style.scss

Fixes #13992
Before:
With this PR:

Publicize: Style update for connected services

---

npm-shrinkwrap.json
package.json

This PR is a cherrypick of #14072 for the Desktop 2.5.0 release
- Open the editor. http://calypso.localhost:3000/post
- Select a site if prompted
- Open the notifications panel.
- Open a notification for a post or comment.
- Click somewhere else on the page, closing the notification panel.
- Click in the Title box.
- Press ‘l’.

Notes: unselect a note when the panel is closed

---

client/me/application-password-item/index.jsx
client/me/next-steps/next-steps-box.scss
client/me/next-steps/steps.js
client/me/notification-settings/settings-form/stream-header.jsx
client/me/profile-link/index.jsx
client/me/profile-link/style.scss
client/me/security-2fa-backup-codes-list/index.jsx
client/me/security-2fa-backup-codes-list/style.scss

This removes noticons in Me
affected areas:
- Security > Two-Step Authentication > Backup Codes
- Security > Two-Step Authentication > App Passwords
- My Profile > Profile Links
- Next Steps
- Notification Settings
I removed the usage of the ActionRemove component, so I think that component can be removed.
I'm pretty sure I formatted things wrong in the react files. Some help would be appreciated.

Me: remove noticons

---

client/my-sites/upgrades/checkout/privacy-protection.jsx
client/my-sites/upgrades/checkout/style.scss

Checkout: add missing i18n

---

client/my-sites/posts/post-controls.jsx
client/my-sites/posts/post.jsx
client/my-sites/posts/style.scss

This PR adds styles to `Share` option in the post controls bar.

Posts: Add active styles to Share option

---

client/my-sites/resume-editing/index.jsx

ResumeEditing: remove sites-list

---

client/my-sites/resume-editing/index.jsx

Reverts Automattic/wp-calypso#13270

Revert "ResumeEditing: remove sites-list"

---

client/layout/masterbar/drafts.jsx
client/my-sites/draft/index.jsx

Draft: remove sites-list.

---

client/blocks/reader-subscription-list-item/index.jsx
client/reader/following-manage/feed-search-results.jsx
client/reader/following-manage/sites-window-scroller.jsx

addresses: https://github.com/Automattic/wp-calypso/issues/14194

Reader: hide last updated date from search results

---

client/lib/abtest/active-tests.js
client/signup/jetpack-connect/plans-grid.jsx

- Replaces this test: #14091
- Kill variations #2 and #4
- Switch to 50/50 split

Jetpack: A/B test regarding headlines #3

---

client/reader/following-manage/index.jsx
client/state/data-layer/wpcom/read/feed/index.js
client/state/reader/feed-searches/actions.js

Reader: Limit size of feed search query, truncate query in error notice for feed searches

---

client/reader/following-manage/index.jsx
client/reader/following-manage/style.scss

Implements https://github.com/Automattic/wp-calypso/issues/13969

Reader: try showing both direct follow by url and search results

---

client/reader/stream/index.jsx

Fixes broken a8c streams in prod.

Reader: Fix missing localize on stream

---

config/development.json

Adds a flag for upcoming work on publish confirmation and post viewing and sharing after publishing. No functional changes.

Editor: add feature flag for delta-post-publish-flow

---

client/lib/abtest/active-tests.js
client/signup/jetpack-connect/plans-grid.jsx

Stops [this test](https://github.com/Automattic/wp-calypso/pull/14248) and reverts to original.
@sirreal -- can you review and merge if ok please?

Stop headlines test

---

client/blocks/reader-recommended-sites/index.jsx
client/blocks/reader-subscription-list-item/index.jsx
client/reader/following-manage/connected-subscription-list-item.jsx
client/reader/following-manage/feed-search-results.jsx
client/reader/following-manage/index.jsx
client/reader/following-manage/sites-window-scroller.jsx
client/reader/following-manage/subscriptions.jsx
client/reader/stats.js

Adds click tracking for:
- site results on following manage
- recommended sites on following manage
- existing follows
Adds traintracks render reporting for:
- site results on following manange
- site recommendations on following manage

Reader: Add tracking for various clicks on following manage

---

client/reader/following-manage/index.jsx

Fire tracks events (and mc actions) when the search query changes and we run a search.

Reader: Track search changes in following manage

---

client/blocks/comments/comment-likes.jsx
client/blocks/comments/post-comment-list.jsx
client/blocks/comments/post-comment.jsx
client/state/comments/actions.js
client/state/comments/reducer.js
client/state/comments/selectors.js
client/state/comments/test/actions.js
client/state/comments/test/reducer.js
client/state/comments/test/selectors.js
client/state/comments/test/utils.js
client/state/comments/utils.js

Removes Immutable.js from the comments state management.

Comments: Remove Immutable.js

---

client/lib/post-normalizer/utils.js

Fix problems with post content display, primarily due to missing video content. 
See #12190

Improve Reader fullpost display of blackamericaweb.com posts

---

client/extensions/woocommerce/state/wc-api/request.js

@DanReyLop This is the fix that you added to my commit.
This change is needed across the board so I thought it best to create a separate PR

Fix error in request module

---

client/extensions/woocommerce/app/settings/payments/style.scss

fixed busted style in https://github.com/Automattic/wp-calypso/pull/13982/files#diff-d025395b7a74ada43f2d6b3f70c2d3ad

Woo: Add closing } to fix scss

---

client/my-sites/plugins/plugin-meta/index.jsx
client/my-sites/plugins/plugin-meta/style.scss

This PR updates the plugin-meta/index.jsx so have #13648 doesn't contain any janitorial code in it. 
** To test**
To test
Go to single site & single plugin view
Go to multi site & single plugins view
Do you notice any js errors?
Are you able to update a plugin, install it, remove it, activate/deactivate it and set it to autoupdate?
Do the test pass?

Update/ janitorial plugin meta

---

client/blocks/reader-recommended-sites/style.scss
client/blocks/reader-subscription-list-item/style.scss

Reader: Correct minor alignment issues in Manage

---

npm-shrinkwrap.json
package.json

This adds support for all Unicode 10 and Emoji 5 emoji.
Static assets have already been updated on WP.com.

Update Twemoji to 2.3

---

client/signup/validation-fieldset/index.jsx
client/signup/validation-fieldset/test/index.jsx

This PR will:
- Replace `React.createClass` with ES6 class.
- Add test cases for the component.

Signup: Refactor ValidationFieldset component.

---

client/my-sites/posts/post-controls.jsx

This hides the sharing option on posts

temporarily  disable repbulicize

---

client/my-sites/posts/post-controls.jsx
client/my-sites/sharing/connections/service-action.jsx
client/my-sites/sidebar/sidebar.jsx
client/post-editor/editor-drawer/index.jsx

Publicize: restore sharing

---

client/me/purchases/cancel-privacy-protection/index.jsx
client/me/purchases/cancel-purchase/index.jsx
client/me/purchases/confirm-cancel-domain/index.jsx
client/me/purchases/credit-cards/credit-card-delete.jsx

I executed `./bin/codemods/i18n-mixin client/me/purchases/` to use `localize` HOC in all existing components with `localize` HOC.
1. Open  https://calypso.live/me/purchase?branch=update/purchases-migrate-localize.
2. Change language to anything but `en`.
3. Make sure it works as before and all pages are properly translated to a language you picked.

Purchases: Update to use localize HOC

---

npm-shrinkwrap.json
package.json

Updates to the notifications panel to version 1.1.14.

Notifications: Use `notifications-panel` v1.1.14.

---

client/blocks/login/index.jsx

We don't need or want to redirect to other domains.

Login: Restrict redirect after login to routes on the current domain

---

client/blocks/reader-full-post/_content.scss
client/lib/post-normalizer/test/utils.js
client/lib/post-normalizer/utils.js

Reader: Fix double images on boing boing

---

client/blocks/login/index.jsx

Refined regex for redirect path whitelist

---

client/lib/signup/themes-data.js

Instructions for testing:
Switch to this PR
Go to calypso.local:3000(?)/start/
Click "A grid of my latest posts"
Make sure Apostrophe 2 shows up instead of Apostrophe

Replace Apostrophe with Apostrophe 2 in signup

---

client/extensions/woocommerce/state/wc-api/request.js

As noted by @belcherj [here](https://github.com/Automattic/wp-calypso/pull/14607/files#diff-dbfaef8fb6820a166fe2b0f23e92faacR28), the current `request.js` implementation doesn't work for requests with body (`POST` and `PUT`). I've fixed it and done more exhaustive testing.

Fix the Request layer for requests with body (POST & PUT)

---

client/extensions/wp-super-cache/state/settings/schema.js
client/extensions/wp-super-cache/state/stats/schema.js

Now that the API has stabilized somewhat, this PR adds more detail to the settings and stats schemas.

Extensions: WPSC - Add more details to schemas

---

client/lib/abtest/active-tests.js

Format has changed in #13402, but I missed updating this test.

ABTests: fix current abtest property

---

client/components/upgrades/google-apps/google-apps-dialog/index.jsx
client/components/upgrades/google-apps/google-apps-dialog/users.jsx
client/lib/mixins/analytics/index.js
client/my-sites/upgrades/domain-management/email/add-google-apps-card.jsx
client/my-sites/upgrades/domain-management/email/style.scss

Refactoring gapps to make `lint` happy. Just maintenance pickup from https://github.com/Automattic/wp-calypso/pull/14478
Test:
- Go to Domain Management
- Click Email tab on top
- Try adding a Google Apps subscription
- Try adding multiple subscriptions for different domains
- Make sure all tracking events are fired
- Make sure checkout finished successfully

Maintenance: Refactor per code standards

---

assets/stylesheets/_components.scss
client/blocks/reader-recommended-sites/style.scss
client/blocks/reader-subscription-list-item/style.scss
client/components/reader-infinite-stream/index.js
client/components/reader-infinite-stream/style.scss
client/reader/search-stream/post-results.jsx
client/reader/search-stream/site-results.jsx
client/reader/search-stream/style.scss
client/reader/search-stream/with-sites.jsx
client/reader/search/controller.js
client/reader/stream/index.jsx

Mostly a proof of concept to get this rolling.
Requires a screen at least 1060px wide.

Reader: Site Result in Search

---

client/lib/sites-list/list.js
client/state/jetpack-connect/actions.js
client/state/sites/actions.js

Quick PR to fix https://github.com/Automattic/wp-calypso/issues/14853
See testing instructions there.

Sharing: Add sharing defaults back into sites requests

---

client/blocks/comment-detail/comment-detail-header.jsx
client/blocks/comment-detail/docs/comment-faker.jsx
client/blocks/comment-detail/index.jsx
client/my-sites/comments/comment-list/index.jsx
client/my-sites/comments/comment-navigation/index.jsx

Adds bulk actions to the Comment Management via the `CommentFaker` component.

Comments: Add bulk actions

---

client/lib/post-normalizer/utils.js
client/state/reader/posts/normalization-rules.js
client/state/reader/posts/test/normalization-rules.js

drops the featured image and gallery min size down to 100px wide (and 75px tall for features).

Reader: Try 100px x 75px as min feature size

---

client/lib/post-normalizer/rule-pick-canonical-media.js

We forgot to make changes to the `isImageLargeEnoughForFeature` function.

Reader: Try 100px x 75px as min feature size - Part 2

---

client/state/activity-log/activation/reducer.js
client/state/activity-log/activation/test/reducer.js
client/state/activity-log/log/reducer.js
client/state/activity-log/reducer.js
client/state/activity-log/restore/reducer.js
client/state/activity-log/restore/test/reducer.js
client/state/activity-log/rewind-status/reducer.js
client/state/activity-log/rewind-status/schema.js
client/state/activity-log/rewind-status/test/reducer.js
client/state/index.js

Another attempt at merging #14817, which broke the build when first merged:
`Build failed for image 1834266c1cd534cd319ff3913f06017553fd28ec (master) by seear`
See #14817 for previous code review.

Activity log: Add reducers (2nd attempt)

---

client/reader/search-stream/post-results.jsx

Addresses: https://github.com/Automattic/wp-calypso/issues/14893
Before:
After:

Reader: site placeholders for sites on search

---

client/lib/cart-values/cart-items.js

Reverts Automattic/wp-calypso#14947
Nothing renders on horizon when you try to add a domain, so I'm going to revert and investigate (stagings and wpcalypso are fine).

Revert "Fix cart items lint errors and ES6ify"

---

client/state/selectors/get-rewind-start-date.js
client/state/selectors/get-rewind-status-error.js
client/state/selectors/index.js
client/state/selectors/is-rewind-activating.js
client/state/selectors/is-rewind-active.js
client/state/selectors/test/get-rewind-start-date.js
client/state/selectors/test/get-rewind-status-error.js
client/state/selectors/test/is-rewind-activating.js
client/state/selectors/test/is-rewind-active.js

Add selectors for activity log state. Part of larger PR #10862.
Matches up with the reducers in #14817.
Fixes #14673
State design: p7rd6c-O9-p2

Activity Log: Selectors

---

client/components/web-preview/style.scss

Reported in #14958 thanks to our never-sleeping e2e tests that we should run locally more (blaming myself)
Follow steps from issue to confirm it's fixed

Preview: Bring back action buttons

---

client/signup/submit-step-button/index.jsx
client/signup/submit-step-button/test/index.jsx

- Replace `React.createClass` with ES6 class.
- Add test cases.

Signup: Refactor SubmitStepButton component and add tests for it.

---

npm-shrinkwrap.json
package.json

Updates the `notification-panel` [package](https://github.com/Automattic/notifications-panel) to v1.1.15.
**Highlights**
* Fix sync of read notes between browser sessions.
* Replace Noticons with Gridicons.
* Improved markup and event propagation.
* Smoother opening and closing animations.
**Testing**
* Restart Calypso.
cc/ @Automattic/lannister

Update `notifications-panel` to v1.1.15.

---

client/extensions/woocommerce/app/store-stats/index.js
client/extensions/woocommerce/components/table/README.md
client/extensions/woocommerce/components/table/docs/example.js
client/extensions/woocommerce/components/table/index.js
client/extensions/woocommerce/components/table/style.scss
client/extensions/woocommerce/components/table/table-item/index.js
client/extensions/woocommerce/components/table/table-row/index.js
client/extensions/woocommerce/style.scss

A dumb component that renders a table. 
Examples of usage 
* The first cell should handle long names with a white fade out
* contents of the cells can be strings, nodes, or any other component

Woo Connect Insights: Table Component

---

client/components/post-list-fetcher/index.jsx
client/lib/posts/actions.js
client/lib/posts/post-counts-store.js
client/lib/posts/post-list-cache-store.js
client/lib/posts/post-list-store.js
client/lib/posts/test/post-list-store.js
client/my-sites/pages/page-list.jsx
client/my-sites/posts/controller.js
client/my-sites/posts/post-list.jsx
client/my-sites/posts/posts-navigation.jsx
client/post-editor/editor-ground-control/index.jsx

Reverts Automattic/wp-calypso#14613

Revert "Update/ use blog id in api requests for posts and pages"

---

client/blocks/reader-related-card-v2/style.scss
client/reader/search-stream/style.scss

Mentioned by @bluefuton in: https://github.com/Automattic/wp-calypso/pull/14982#issuecomment-307803375
**Before:**
**After:**

Reader: Fix Search recs loading placeholders in IE

---

client/lib/abtest/active-tests.js
client/signup/steps/design-type/index.jsx
client/signup/steps/design-type/style.scss

Since the modified version beat the original in [the abtest](https://github.com/Automattic/wp-calypso/pull/14410), this PR clean up the test and implements the winner.
The test result can be found p5XAZ9-1t7-p2
cc: @fditrapani

Signup: Update copy in the step 1 of site creation flow.

---

client/components/post-list-fetcher/index.jsx
client/lib/posts/actions.js
client/lib/posts/post-counts-store.js
client/lib/posts/post-list-cache-store.js
client/lib/posts/post-list-store.js
client/lib/posts/test/post-list-store.js
client/my-sites/pages/page-list.jsx
client/my-sites/posts/controller.js
client/my-sites/posts/post-list.jsx
client/my-sites/posts/posts-navigation.jsx
client/post-editor/editor-ground-control/index.jsx

Take two of #14613, which is an approach towards fixing this one: #6779.

Update/ use blog id in api requests for posts and pages - take 2

---

client/components/upgrades/google-apps/google-apps-dialog/users-form.jsx
client/components/upgrades/google-apps/google-apps-dialog/users.jsx

Create a new component and pass the props so we're not binding handlers.
Test:
- Go to Domain Management
- Click Email tab on top
- Try adding a Google Apps subscription
- Try adding multiple subscriptions for different domains
- Make sure all tracking events are fired
- Make sure checkout finished successfully

Janitorial: Don't use bind in on* handlers

---

client/lib/media/actions.js

Refactor the `MediaActions.add` function so we have a generic `uploadFiles` function that takes an uploader object. `uploadFiles` is responsible for iterating over a set of files, and calling the uploader for each item, which handles the actual upload.
Splitting this apart allows new uploaders to be added. The intent is to use this for a Google Photos integration where a different method of copying an external image is needed.
Note this PR doesn't change functionality.
The existing media unit tests cover the change.
`npm run test-client client/lib/media/test`
Also manually verify that uploading a file and adding a URL still works.

Media: refactor media actions ‘add files for upload’

---

client/blocks/reader-subscription-list-item/style.scss
client/components/reader-infinite-stream/index.js
client/reader/search-stream/site-results.jsx
client/reader/search-stream/style.scss
client/reader/search-stream/with-sites.jsx

addresses https://github.com/Automattic/wp-calypso/issues/15119

Teach SiteResults about lastUpdatedDate

---

client/post-editor/editor-preview/index.jsx
client/post-editor/post-editor.jsx

EditorPreview: Add `revision` prop to keep Preview up-to-date

---

client/blocks/login/login-form.jsx
client/blocks/login/style.scss
client/login/magic-login/request-login-email-form.jsx
client/login/magic-login/style.scss
client/login/wp-login/style.scss
client/state/login/actions.js

This pull request fixes part of #15101 by updating some copy and designs.
- Separation between the log in form and the social buttons
- Changes to validation notices:
```Please be sure to enter your password. --> Don't forget to enter your password.```
```Oops, looks like that’s not the right password. Please try again! --> Oops, that’s not the right password. Please try again!```
- Darker footer links

Login: Copy and design updates

---

client/blocks/login/login-form.jsx
client/blocks/login/social.jsx

This fixes the issue @gziolo found here: https://github.com/Automattic/wp-calypso/pull/15117#issuecomment-309350113

Login: Move the social card inside the social signup config condition

---

config/wpcalypso.json

This will make testing easier.

Enable social signup on wpcalypso

---

client/lib/abtest/active-tests.js

Jetpack: bump new site test up to 50

---

client/reader/stats.js
client/state/data-layer/wpcom/read/following/mine/delete/index.js
client/state/data-layer/wpcom/read/following/mine/delete/test/index.js
client/state/data-layer/wpcom/read/following/mine/index.js
client/state/data-layer/wpcom/read/following/mine/new/index.js
client/state/data-layer/wpcom/read/following/mine/new/test/index.js
client/state/data-layer/wpcom/read/following/mine/test/index.js
client/state/data-layer/wpcom/read/following/mine/test/utils.js
client/state/data-layer/wpcom/read/following/mine/utils.js
client/state/reader/feeds/selectors.js
client/state/reader/sites/selectors.js

This show a success notification when a follow successfully returns. Auto-dismisses after 5 seconds.

Reader: Show a notice on follow success

---

client/blocks/post-share/style.scss

Publicize: Fix external icon in Republicize

---

client/my-sites/upgrades/paths.js

Reverts Automattic/wp-calypso#15252

Revert "Domain management: fix swapped domain/site in URLs"

---

client/blocks/reader-combined-card/style.scss
client/reader/search-stream/style.scss

Fixes: https://github.com/Automattic/wp-calypso/issues/15184
Example: https://wpcalypso.wordpress.com/read/search?q=Coachit&focus=1&sort=date
**Before:**
**After:**

Reader: Fix Combined Cards content exceeding container

---

npm-shrinkwrap.json
package.json

This bumps the `notifications-panel` package to the latest v1.1.16 (at https://github.com/Automattic/notifications-panel/commit/24f99cd34e7c3b7efa69f26622cfd8997274aff7).
Changes:
* Improve iframe width at narrower sizes.
* Code formatting.

Update the `notifications-panel` package to v1.1.16.

---

client/extensions/woocommerce/app/settings/payments/payment-method-item-placeholder.js
client/extensions/woocommerce/app/settings/payments/style.scss

To test go here: http://calypso.localhost:3000/store/settings/payments/{site}
Observe that loading state work properly.

Fix loading states on payment methods

---

client/extensions/woocommerce/app/settings/payments/style.scss

Improve typographical consistency

---

client/extensions/woocommerce/app/settings/payments/payments-location-currency.js

Fixes currency label

---

client/extensions/woocommerce/state/ui/payments/currency/reducer.js

To test:  http://calypso.localhost:3000/store/settings/payments/{site}
Observe no errors in dev console.

Fix currency state issue

---

config/development.json
npm-shrinkwrap.json
package.json
webpack.config.js
webpack.config.node.js

This PR branches off of https://github.com/Automattic/wp-calypso/pull/14786 and attempts to address the performance concerns even further.
Things to try:
cc @gwwar @ehg

Performance improvements to webpack2.x configuration

---

client/components/segmented-control/style.scss
client/extensions/woocommerce/app/store-stats/store-stats-chart/index.js
client/extensions/woocommerce/app/store-stats/store-stats-chart/style.scss
client/extensions/woocommerce/app/store-stats/store-stats-navigation/style.scss
client/extensions/woocommerce/components/delta/index.js
client/extensions/woocommerce/components/delta/style.scss
client/extensions/woocommerce/style.scss
client/my-sites/stats/stats-navigation/index.jsx
client/state/stats/lists/utils.js

Bring chart and tab styling in line with site stats and designs for store stats.
Fixes #14908

Woo-Connect Insights: Update Chart & Tab Styling

---

client/blocks/reader-post-card/index.jsx

Fixes #15139
Pass along the railcar on a post if it's present.

Reader: Pass along railcar if present on post

---

client/extensions/woocommerce/app/settings/payments/payments-location-currency.js
client/extensions/woocommerce/app/settings/payments/payments-off-site.js
client/extensions/woocommerce/app/settings/payments/payments-offline.js
client/extensions/woocommerce/app/settings/payments/payments-on-site.js

Updating payments page copy
Addresses that item in https://github.com/Automattic/wp-calypso/issues/15432

WooCommerce: Payments: update copy

---

client/extensions/woocommerce/app/dashboard/manage-no-orders-view.js
client/extensions/woocommerce/app/dashboard/manage-orders-view.js
client/extensions/woocommerce/app/dashboard/pre-setup-view.js
client/extensions/woocommerce/app/dashboard/setup-tasks-view.js
client/extensions/woocommerce/app/orders/orders-list.js
client/extensions/woocommerce/components/process-orders-widget/index.js

Updating copy on our various dashboards, including address step and EmptyContents. 
Addresses that item in #15432

WooCommerce: Dashboards: update copy

---

config/horizon.json
config/production.json
config/stage.json

Let it go.
New look and feel:
narrow posts
narrow sites
before

Reader: Release Sites in Search

---

client/extensions/woocommerce/app/store-stats/constants.js
client/extensions/woocommerce/app/store-stats/controller.js
client/extensions/woocommerce/app/store-stats/index.js
client/extensions/woocommerce/app/store-stats/listview.js
client/extensions/woocommerce/app/store-stats/store-stats-list/index.js
client/extensions/woocommerce/app/store-stats/store-stats-module/index.js
client/lib/wpcom-undocumented/lib/site.js
client/state/stats/lists/actions.js
client/state/stats/lists/utils.js

Added routes to listview for products, categories and coupons.
In progress.
fixes #14502 
fixes #14503

Woo-Connect Stats: Update store stats routes to include listview

---

client/extensions/wp-super-cache/package.json

We can already merge this, but it'll only show effect once that route is whitelisted on the systems side (see pMz3w-7bJ-p2).
To test -- nothing really 😄 Make sure things don't go up in flames, I guess.

Extensions: WPSC: Enable in stage environment

---

client/extensions/woocommerce/app/settings/shipping/shipping-header.js
client/extensions/woocommerce/app/settings/shipping/shipping-zone/index.js
client/extensions/woocommerce/app/settings/shipping/shipping-zone/shipping-zone-header.js
client/extensions/woocommerce/app/settings/shipping/shipping-zone/shipping-zone-name.js
client/extensions/woocommerce/app/settings/shipping/shipping-zone/style.scss

Adds a title control to the shipping zone page. Also adds proper breadcrumbs.
@kellychoffman @jameskoster

Added shipping zone title edit and breadcrumbs

---

client/lib/abtest/active-tests.js
client/signup/steps/theme-selection/signup-themes-list.jsx

It is a winner of the A/B test. See p5XAZ9-1sy-p2

Signup: reduce theme choices in the signup flow.

---

client/components/auto-direction/index.jsx
client/components/emojify/docs/example.jsx

After #15340 was merged, there were a few tweaks suggested. This PR fixes them.

Tweak Emojify and AutoDirection after #15340

---

client/extensions/woocommerce/app/settings/shipping/shipping-labels.js
client/extensions/woocommerce/app/settings/shipping/shipping-origin.js
client/extensions/woocommerce/app/settings/shipping/shipping-package-list.js
client/extensions/woocommerce/app/settings/shipping/shipping-zone-list.js
client/extensions/woocommerce/app/settings/shipping/shipping-zone/shipping-methods/utils.js
client/extensions/woocommerce/app/settings/shipping/shipping-zone/shipping-zone-locations.js
client/extensions/woocommerce/app/settings/shipping/shipping-zone/shipping-zone-method-list.js

Updating shipping page copy
Addresses that item in #15432

WooCommerce Shipping: update copy

---

client/extensions/woocommerce/app/dashboard/index.js
client/extensions/woocommerce/app/dashboard/required-plugins-install-view.js
client/extensions/woocommerce/app/dashboard/setup-header.js
client/state/plugins/installed/actions.js
client/state/plugins/installed/test/actions.js

To test:
Uninstall: woocommerce, stripe, services
Goto: http://calypso.localhost:3000/store/{site}
Watch progress bar install the plugins and then disappear.

Installing Store prerequisite plugins.

---

assets/stylesheets/_components.scss
client/blocks/site-icon/index.jsx
client/components/image/README.md
client/components/image/index.js
client/components/image/style.scss

Introduce a new Image component that hides itself when there's an error loading an image. Use the Image insite SiteIcon to hide broken site icons.
Fixes #15565

SiteIcon: Hide broken images

---

client/my-sites/stats/activity-log-item/index.jsx

To test:
* View the branch
* Look at theme activity
* Ensure there are no console errors/warnings
Includes #15567

Activity log: Add theme activity item props and styling

---

client/extensions/woocommerce/app/products/product-create.js
client/extensions/woocommerce/state/data-layer/action-list/index.js
client/extensions/woocommerce/state/data-layer/action-list/test/index.js
client/extensions/woocommerce/state/data-layer/product-categories/index.js
client/extensions/woocommerce/state/data-layer/product-categories/test/index.js
client/extensions/woocommerce/state/data-layer/products/index.js
client/extensions/woocommerce/state/data-layer/products/test/index.js
client/extensions/woocommerce/state/data-layer/request/index.js
client/extensions/woocommerce/state/data-layer/request/test/index.js
client/extensions/woocommerce/state/data-layer/ui/products/index.js
client/extensions/woocommerce/state/data-layer/ui/products/test/index.js
client/extensions/woocommerce/state/helpers.js
client/extensions/woocommerce/state/sites/product-categories/actions.js
client/extensions/woocommerce/state/sites/products/actions.js

_This PR pertains to the work in #15424._
This adds a test which carries data from one step in the action list to
the next step after it.
To Test: `npm test`

Woo: action-list, add test carrying data forward.

---

client/extensions/woocommerce/app/products/product-create.js
client/extensions/woocommerce/state/action-list/README.md
client/extensions/woocommerce/state/data-layer/action-list/index.js
client/extensions/woocommerce/state/data-layer/action-list/test/index.js
client/extensions/woocommerce/state/data-layer/product-categories/index.js
client/extensions/woocommerce/state/data-layer/product-categories/test/index.js
client/extensions/woocommerce/state/data-layer/products/index.js
client/extensions/woocommerce/state/data-layer/products/test/index.js
client/extensions/woocommerce/state/data-layer/request/index.js
client/extensions/woocommerce/state/data-layer/request/test/index.js
client/extensions/woocommerce/state/data-layer/ui/products/index.js
client/extensions/woocommerce/state/data-layer/ui/products/test/index.js
client/extensions/woocommerce/state/helpers.js
client/extensions/woocommerce/state/sites/product-categories/actions.js
client/extensions/woocommerce/state/sites/products/actions.js

_This PR belongs with #15424 and will be merged into it before merging to master._
This updates the readme for the action-list to explain how it will now
work with the refactor.
To Test: View the [resulting readme file](https://github.com/Automattic/wp-calypso/blob/update/woo-action-list-readme/client/extensions/woocommerce/state/action-list/README.md) and ensure it makes sense and contains no grammatical errors.

Woo: Update action-list readme for refactor.

---

client/reader/_style.scss

Reader: Remove top margin for no results in single-col

---

client/extensions/woocommerce/app/products/product-create.js
client/extensions/woocommerce/app/products/product-header.js
client/extensions/woocommerce/app/products/product-update.js
client/extensions/woocommerce/components/action-header/style.scss

Addresses #15214
This makes a few updates to the product page header.
1. Remove "trash" from new create page.
2. Add "view" to update page.
3. Add words to borderless buttons.
To Test:
1. `npm start`
2. Try the "Add Product" screen.
3. Try the "Edit Product" screen.

Woo: Update product header

---

client/extensions/woocommerce/app/products/product-create.js
client/extensions/woocommerce/app/products/product-form-categories-card.js
client/extensions/woocommerce/app/products/product-form-details-card.js
client/extensions/woocommerce/app/products/product-form-variations-card.js
client/extensions/woocommerce/app/products/product-form.js
client/extensions/woocommerce/app/products/product-header.js
client/extensions/woocommerce/app/products/product-update.js
client/extensions/woocommerce/components/action-header/style.scss
client/extensions/woocommerce/index.js

This adds the product update editing page.
To Test:
1. `npm start`
2. Visit `http://calypso.localhost:3000/store/products/<site_url>`
3. Select a product from the list.
4. Observe that the edit page shows up, populated with data from the product you selected.

Woo: Add product update page.

---

client/components/update-post-status/index.js
client/my-sites/posts/post.jsx

Continuation of #15160, which introduced the HoC and applied it to `Page`. This PR brings analogous changes to `Post`.
See §§ _Why_ & _Reviewing_ in #15160 for context.

Post: Replace update-post-status mixin with HoC

---

client/extensions/woocommerce/app/dashboard/required-plugins-install-view.js

To test:
* Set up a WPCOM sandbox that has the new `wc-api-dev` installation endpoint
* Point your `public-api.wordpress.com` to sandbox
* Uninstall: woocommerce, stripe, services, wc-api-dev
* Go to: http://calypso.localhost:3000/store/{site}
* Watch progress bar install the plugins and then disappear
* Verify all plugins are installed

Woo: Install API Dev plugin prerequisite

---

client/components/domains/domain-registration-suggestion/index.jsx

Append the 'New' label to TLDs coming soon

Domains: Add TLDs ready to be launched soon

---

config/development.json
config/wpcalypso.json

Lets enable them from everyone in development to make it easier for people to test things out.

WooCommerce Stats: Enable the Store Stats for everyone in development as they are pretty stable now

---

client/extensions/woocommerce/state/data-layer/ui/shipping-zones/index.js

Depends on #15770
When saving a zone, its `order` property now will be set accordingly. These are the rules:
* Zones with country + postcode range: Order 1
* Zones with states: Order 2
* Zones with countries: Order 3
* Zones with continents: Order 4
Since WooCommerce allows multiple zones with the ame order, this logic is enough.
Other existing zones could have an incorrect order, either because an error happened on a previous save operation, or because the user edited them in WP-Admin (while preserving a correct general order). So, when saving a zone, *all* zones will be checked and their order updated if needed.
To test, edit freely the shipping zones and the locations on each shipping zone. When saving them, the zones must end up in the correct order (you can check it both in Calypso …

Automatically orders all the shipping zones on save.

---

client/state/selectors/get-site-url.js
client/state/selectors/index.js
client/state/selectors/test/get-site-url.js

To test:
```
npm run test-client client/state/selectors/test/get-site-url.js
```
See it in action by testing #15786, which includes this.

Add getSiteUrl selector

---

client/my-sites/stats/activity-log-banner/success-banner.jsx

**To test:**
1. Show yourself a success banner:
```js
dispatch({ type: 'REWIND_RESTORE_UPDATE_PROGRESS', siteId: state.ui.selectedSiteId, timestamp: 1498168800000, restoreId: 123, errorCode: "", failureReason: "", message: "A message", percent: 100, status: "finished" })
```
1. Click the site link.
1. You should land on your site!
Part of #15260 
Includes #15785

Activity log: Add banner links

---

client/me/help/help-contact/index.jsx

Removes sites-list from help-contact.
To test:
Go to http://calypso.localhost:3000/help/contact on a user with more than one site and check that a form appears with a question  “Which site do you need help with?” and a site picker to answer. On a user with just one site, only the question “What are you trying to do?” appears.

Framework: Removed sites-list usage from help-contact.

---

client/extensions/woocommerce/app/settings/shipping/shipping-zone/index.js
client/extensions/woocommerce/app/settings/shipping/shipping-zone/shipping-zone-header.js
client/extensions/woocommerce/app/settings/shipping/shipping-zone/shipping-zone-location-dialog-settings.js
client/extensions/woocommerce/app/settings/shipping/shipping-zone/shipping-zone-name.js
client/extensions/woocommerce/app/settings/shipping/shipping-zone/style.scss

Fixes #15799
CC @jameskoster @kellychoffman

Shipping - moved zone name beneath other controls

---

client/extensions/woocommerce/state/data-layer/ui/products/test/index.js

This condenses the fixture data for several tests down into a single
rootState that can be further modified for each test as it runs.
To test: `npm test`

Woo: Condense product action-list test fixtures

---

client/extensions/woocommerce/lib/generate-variations/index.js
client/extensions/woocommerce/lib/generate-variations/test/index.js
client/extensions/woocommerce/state/data-layer/ui/products/test/index.js
client/extensions/woocommerce/state/ui/products/variations/edits-reducer.js

This updates generateVariations to take data from existing API data
where available when generating new variations based on variation types.
To test: `npm test`

Woo: Update generateVariations for existing data.

---

client/extensions/woocommerce/app/store-stats/constants.js
client/extensions/woocommerce/app/store-stats/index.js
client/extensions/woocommerce/app/store-stats/listview.js
client/extensions/woocommerce/app/store-stats/test/utils.js
client/extensions/woocommerce/app/store-stats/utils.js

Woo-Connect Insights: update and fix non-day units for products, categories and coupon pages

---

client/lib/plans/constants.js
client/my-sites/plan-features/index.jsx
client/my-sites/plans-features-main/index.jsx

The original PR for this [broke staging](https://github.com/Automattic/wp-calypso/pull/15826) when it got there. This new PR fixes the issue so this can be merged back into master. 
For all testing instructions refer to this: https://github.com/Automattic/wp-calypso/pull/15609
I'll point out the code with a comment that I've added to this PR which makes it different from the original.
cc @markryall @taggon

Jetpack plans test v2

---

client/components/tinymce/plugins/media/plugin.jsx
client/my-sites/plan-features/index.jsx
config/desktop.json

Merging back cherry picks made in the release branch into master. GitHub diffs show there being a change but given previous experience it's not actually changing anything in master. 🤷‍♂️

Merge Release/desktop/2.6.0 into master

---

config/development.json

Just adds the feature flag and sets it to true for dev. No functional changes.

Reader: Add the conversations feature flag

---

config/stage.json

Unless you know what you're doing 😀 
This will enable the activity log in the staging environment.

Activity log: Enable in staging

---

client/reader/conversations/controller.js
client/reader/conversations/index.js
client/reader/conversations/stream.js
client/reader/sidebar/index.jsx
client/wordpress-com.js

Links to a blank placeholder for now. Only appears if the feature flag is active.

Reader: Add Conversations sidebar item

---

client/state/stats/lists/utils.js

Moved to `deltasv2` and refactored, which significantly speeds up the normalizer for store stats.
Fixes #15944

Woo-Connect Insights: switch to new endpoint response for deltas + refactor

---

client/extensions/woocommerce/app/store-stats/store-stats-chart/index.js
client/extensions/woocommerce/app/store-stats/store-stats-widget-list/index.js

Woo-Connect Insights: include 3 letter currency in formatCurrency()

---

client/extensions/woocommerce/app/dashboard/required-plugins-install-view.js

- clear your stuff:  https://developer.wordpress.com/docs/api/console/  ----> POST
/sites/SITE_ID/calypso-preferences/woocommerce
- Uninstall your plugins in the wp-admin
- Refresh your page
- Observe progress bar that it is moving
- Once that screen clears goto to wp-admin to see if all (5) plugins are installed

Add timeout to rerun install if nothing happens in 5 seconds

---

client/extensions/woocommerce/app/store-stats/store-stats-chart/index.js
client/extensions/woocommerce/app/store-stats/store-stats-widget-list/index.js
client/extensions/woocommerce/components/delta/style.scss

I also tweaked the delta size to 20x20 so that it is standard across the page.
Fixes #15992

Woo-Connect Insights: use '-' for `is-undefined-increase` for growth from 0

---

config/horizon.json
config/production.json
config/stage.json
config/test.json

For some reason we forgot to launch this part.

Advanced Social Media: enable previews on prod

---

client/blocks/reader-related-card-v2/style.scss
client/reader/search-stream/style.scss

Reader: increase image height in post recs in Search

---

client/my-sites/stats/activity-log-item/index.jsx

Add menu and plugin icons
Modifies status logic
Adds `menu` propTypes

Activity log: Add icon and status styling

---

client/my-sites/stats/activity-log-item/activity-icon.jsx
client/my-sites/stats/activity-log-item/index.jsx
client/my-sites/stats/activity-log-item/style.scss

Separates icon from ActivityLogItem component.
**To test:**
* Visit https://calypso.live/stats/activity?branch=update/activitylog-separate-icon
* Compare with staging.
* Ensure the icon is correctly displayed with no changes.
Follow up from #15400

Activity log: Separate activity icon component

---

client/state/stats/lists/utils.js

Woo-Connect Insights: refactored deltasv2 back to deltas

---

client/extensions/woocommerce/app/store-stats/constants.js
client/extensions/woocommerce/app/store-stats/store-stats-chart/index.js
client/extensions/woocommerce/app/store-stats/store-stats-widget-list/index.js
client/extensions/woocommerce/components/delta/index.js
client/extensions/woocommerce/components/sparkline/index.js

Fixes #16101 
Fixes #16072 
Fixes #16135

Woo-Connect Insights: updated since and date formats for units

---

client/state/comments/actions.js
client/state/comments/constants.js
client/state/comments/from-api.js
client/state/comments/reducer.js
client/state/comments/selectors.js
client/state/comments/test/actions.js
client/state/comments/test/reducer.js
client/state/comments/test/selectors.js
client/state/data-layer/wpcom/comments/index.js
client/state/data-layer/wpcom/comments/test/index.js
client/state/data-layer/wpcom/sites/comments/index.js
client/state/data-layer/wpcom/sites/comments/likes/index.js
client/state/data-layer/wpcom/sites/comments/likes/mine/delete/index.js
client/state/data-layer/wpcom/sites/comments/likes/mine/delete/test/index.js
client/state/data-layer/wpcom/sites/comments/likes/new/index.js
client/state/data-layer/wpcom/sites/comments/likes/new/test/index.js
client/state/data-layer/wpcom/sites/comments/replies/new/index.js
client/state/data-layer/wpcom/sites/comments/replies/new/test/index.js
client/state/data-layer/wpcom/sites/comments/test/index.js

Commands ran: 
```bash
./node_modules/prettier/bin/prettier.js --write client/state/comments/*.js* 
./node_modules/prettier/bin/prettier.js --write client/state/comments/**/*.js
./node_modules/prettier/bin/prettier.js --write client/state/data-layer/wpcom/comments/*.js*
./node_modules/prettier/bin/prettier.js --write client/state/data-layer/wpcom/comments/**/*.js*
./node_modules/prettier/bin/prettier.js --write client/state/data-layer/wpcom/sites/comments/**/*.js*
```

Comments: prettify state + data-layer

---

client/my-sites/comments/comment-navigation/index.jsx
client/my-sites/comments/controller.js

Improve the readability of conditional properties and elements assignments, as explained in https://github.com/Automattic/wp-calypso/pull/15933#discussion_r127297463

Comments: Improve conditional properties and elements readability

---

client/state/stats/lists/test/utils.js
client/state/stats/lists/utils.js

Added tests for `parseOrdersChartData` and `parseOrderDeltas`.
Fixes #16188

Woo-Connect Insights: tests for parseOrdersChartData, parseOrderDeltas

---

client/my-sites/pages/page-list.jsx
client/my-sites/pages/placeholder.jsx
client/my-sites/pages/style.scss

In preparation of possible Reduxifcation.
To test: Make sure `/pages` still works as before (try both single-site and multi-site modes).

PageList: ES6ify

---

client/blocks/comment-detail/comment-detail-author.jsx

Fixes #16165
Remove `QuerySiteSettings` and the custom date/time formats from Comment Management.
Replace it with `convertDateToUserLocation`, as already [featured in the Post Editor drawer](https://github.com/Automattic/wp-calypso/blob/master/client/post-editor/edit-post-status/index.jsx#L121-L125).
The custom date/time formats are primarily intended for presentational purposes (i.e. to style frontend dates), and there's no guarantee they are readable or even complete enough for a "power tool" like the Comment Management.
`convertDateToUserLocation`, instead, feeds the user location (stored in the site options) to the  Moment.js own localization functions.
Furthermore, it's already used in a major location such as the Post Editor, so it's by itself more vetted than the custom date/time …

Comments: Replace site settings date format with convertDateToUserLocation

---

client/jetpack-connect/main.jsx

Change the JPC descriptions to better indicate what's in the plan.

More descriptive sub-headings of what JP plans contain

---

client/jetpack-connect/main.jsx

Change sub heading to be more descriptive of what Jetpack brings you.

Update JPC free description

---

client/lib/plans/constants.js

Change sub heading text to include latest features and match NUX on default plans page. (https://wordpress.com/jetpack/connect/store)

Update JP long plan descriptions

---

client/my-sites/stats/activity-log-day/style.scss
client/my-sites/stats/activity-log-item/style.scss
client/my-sites/stats/activity-log/style.scss

Refines Activity Log styles:
- Improves UI for smaller devices.
- Tighten events spacing and rhythm.
- Refines flexbox ratio between actor/content elements.
- Reposition event ID.
- Cleans up some styles.

Refine Activity Log styles

---

client/state/login/actions.js
client/state/login/reducer.js

Reverts Automattic/wp-calypso#16233

Revert "Login: Show a notice when we send the SMS code"

---

client/my-sites/pages/controller.js
client/my-sites/pages/page-list.jsx

Reverts Automattic/wp-calypso#16270
Testing on `stage`, this doesn't seem to load any results past the first 20, even when scrolling :slightly_frowning_face:

Revert "Pages: Reduxify PageList"

---

client/lib/signup/themes-data.js
client/my-sites/theme/themes-related-card/index.jsx

Replace the retired Intergalactic theme with Intergalactic 2

---

config/stage.json

Enable the video editor thumbnail functionality in the staging environment.

Media: Enable video editor in staging

---

client/lib/mixins/analytics/index.js
client/my-sites/domains/components/domain-warnings/index.jsx
client/my-sites/domains/components/domain-warnings/pending-gapps-tos-notice-multiple-domain-list-item.js
client/my-sites/domains/components/domain-warnings/pending-gapps-tos-notice.jsx

Avoid passing new functions every time.
Use Redux events for tracking.
Use ES6 classes.

Janitorial: Refactor Domain Warning components per code standards

---

client/my-sites/posts/post.jsx

No functional changes. Behavior around My Sites > Posts should be kept intact.

Post: Switch to React.Component; clean up

---

client/blocks/reader-related-card-v2/style.scss

Found in full-post recs on iPhone 5.
**Before:**
**After:**

Reader: Follow button pushed too far to right

---

client/my-sites/stats/stats-list/stats-list-item.jsx

Also f ix the handler so links still work.
See #16334, this is a much simpler change which I think fixes all the issues.

Fix the mis-named onClick handler attribute so it is correctly enabled

---

client/my-sites/sidebar/manage-menu.jsx

Fixes #16425
Remove Conversations from the All My Sites sidebar menu.
| --- | --- |
| <img width="309" alt="screen shot 2017-07-20 at 2 20 11 pm" src="https://user-images.githubusercontent.com/618551/28435179-9cf273d6-6d57-11e7-841d-bf1da42f45af.png"> | <img width="271" alt="screen shot 2017-07-24 at 12 57 02" src="https://user-images.githubusercontent.com/2070010/28522407-d4ed3b20-706f-11e7-950f-7b615fa13e4d.png"> |
cc @Automattic/lannister

Comments: Remove Conversations from All My Sites sidebar

---

client/my-sites/posts/post.jsx
client/my-sites/posts/style.scss

Posts: Fix title wrapping relative to post format icon

---

client/components/clipboard-button-input/README.md

Following the merge of #16329 I wanted to update the `readme.md` of this component, it passed me by while making the changes in that PR!
Nothing to test here, please just take a look over the `readme.md` & the code itself and make sure the docs are true :)

ClipboardButtonInput: update Readme with hideHttp prop

---

client/my-sites/domains/controller.jsx
client/my-sites/domains/domain-management/controller.jsx
client/my-sites/domains/domain-management/domain-management.jsx
client/my-sites/domains/domain-search/site-redirect-step.jsx
client/my-sites/domains/index.js
client/my-sites/domains/navigation.jsx
client/my-sites/domains/paths.js

- ES6 import/export
- Use Redux actions for notices for already refactored components
- `PlansNavigation` use `class ... extends` 
Test:
1. Check all of domains
2. Links
3. Navigation
4. No errors in console should suffice

Janitorial: Refactoring Domains Components

---

client/post-editor/editor-ground-control/index.jsx
client/post-editor/editor-ground-control/post-scheduler.jsx
client/post-editor/editor-ground-control/test/index.jsx

To test:
* Go to http://calypso.localhost:3000/posts/my/<yoursite>
* Click on any post's 'Edit' button.
* Make sure that `EditorGroundControl` still works. That's this component:
* In particular, make sure the `PostScheduler` still works. Check a future month for which you have scheduled a couple of posts. The scheduled dates should be highlighted (with little circles around the dates) in the scheduler:

Editor: Reduxify EditorGroundControl

---

client/blocks/comments/post-comment-list.jsx

Reader: make sure comment exists before checking for an error

---

client/lib/url/index.js
client/reader/follow-button/follow-sources.jsx
client/reader/search-stream/index.jsx
client/reader/search-stream/style.scss

Addresses: https://github.com/Automattic/wp-calypso/issues/16594
Image:

Reader: enable follow by url from sites search

---

client/lib/feed-stream-store/index.js
client/lib/wpcom-undocumented/lib/undocumented.js
client/reader/conversations/controller.js
client/reader/conversations/index.js
client/reader/sidebar/index.jsx

Adds a "A8C Conversations" sidebar item and stream. No pics.
You'll likely need to restart calypso after switching to this branch to pick up the configuration changes.

Reader: Add a8c conversations

---

client/components/tinymce/plugins/simple-payments/dialog/index.jsx

Extracted the code that sets the `isSubmitting` and `errorMessage` state to separate methods.
They will be soon used also in code other than `handleInsert`, like for deleting a button or
updating an edited one. We don't need to repeat the `this._isMounted` checks everywhere.
Also removed some code duplication from `handleInsert`. Use a `Promise.resolve` to unite
the code paths that are common for both tabs. Set `isSubmitting=false` only at one place
that is always executed both after success and error.

Simple Payments: cleanup the SimplePaymentsDialog.handleInsert method

---

client/lib/mixins/analytics/index.js
client/my-sites/domains/domain-management/primary-domain/index.jsx

- ES6ify
- Use redux actions for tracking

Janitorial: Refactor primary-domain component

---

client/my-sites/domains/domain-management/privacy-protection/card/add-button.jsx
client/my-sites/domains/domain-management/privacy-protection/card/content.jsx
client/my-sites/domains/domain-management/privacy-protection/index.jsx
client/my-sites/domains/domain-management/privacy-protection/privacy-protection-card/header.jsx

- ES6ify
- Small refactorings for readability

Janitorial: Refactor privacy-protection components

---

client/extensions/woocommerce/app/orders/style.scss
client/extensions/woocommerce/app/products/product-form.scss
client/extensions/woocommerce/app/settings/taxes/style.scss
client/extensions/woocommerce/app/settings/taxes/taxes-options.js
client/extensions/woocommerce/app/settings/taxes/taxes-rates.js
client/extensions/woocommerce/components/form-dimensions-input/style.scss

- Made new orders stand out more in orders list
- Made toggle label stay consistent no matter the status in taxes 
- Styled error notice in taxes
- Styled success message in taxes 
@jameskoster - add/fix anything you think we should style up before launch in this PR.

Store: Pre-launch style clean up

---

config/production.json

Enable Gravatar upload feature in production

---

npm-shrinkwrap.json
package.json

related feature: https://github.com/Automattic/notifications-panel/pull/171#event-1182266539

Notifications Panel: bump version for opening comments in reader

---

config/wpcalypso.json

change wpcalypso.json to enable conversations tool

Reader: Enable conversations tool for wpcalypso

---

client/components/button/style.scss

#15322 Buttons: Added space to icon in buttons

---

client/extensions/woocommerce/state/data-layer/ui/shipping-zones/index.js
client/extensions/woocommerce/state/ui/shipping/zones/locations/selectors.js

Fixes #16661
This was quite difficult to debug. Basically a memoized result of a function was modified directly which then affected the rest of the app.
I also added small tweaks in some of the selectors.
CC @kellychoffman @DanReyLop

Woo Shipping - Fixed multiple state select

---

client/components/forms/docs/example.jsx

#16744 wouldn't even compile :man_facepalming:

Form Components: Make displayName static

---

client/components/tinymce/plugins/simple-payments/dialog/form.jsx

Use compact toggle for one line toggle setting.

Simple Payment: Compact toggle for multi-buy toggle

---

client/components/forms/form-toggle/index.jsx
client/components/forms/form-toggle/test/index.jsx

Also, I'm pretty sure that `id` should go to into the `<input />`, not the `<span />`. Otherwise, that `<label />`'s `htmlFor` doesn't really make sense.

FormToggle: Use enzyme for remaining tests

---

client/components/forms/README.md

* Add missing components
* Wrap code sample in triple-apostrophes
* Make link to `MultiCheckbox` README relative (so it'll hopefully also work on npmjs.com)
* `s/var/const/g`

Form Components: Update README.md

---

config/stage.json

The test has run its course & we've gathered valuable feedback.

Session Restore: Disable in stage

---

config/stage.json

Enable reader linking in staging

Notifications: Promote reader links to staging

---

client/my-sites/domains/domain-management/contacts-privacy/card.jsx
client/my-sites/domains/domain-management/contacts-privacy/contact-display.jsx
client/my-sites/domains/domain-management/contacts-privacy/index.jsx

- ES6ify
- Use localize
Test:
- Calypso -> Domains -> Contacts & Privacy
- Make sure all works and no errors whatsoever

Janitorial: ES6ify Contacts Privacy

---

client/signup/steps/site-or-domain/index.jsx
client/state/products-list/schema.js
client/state/products-list/selectors.js
client/state/products-list/test/reducer.js

We're sending all products from back end, depends on D6603-code.
Add selector to filter only available.

Products: Update schema, add selectors

---

client/my-sites/domains/domain-management/dns/a-record.jsx
client/my-sites/domains/domain-management/dns/cname-record.jsx
client/my-sites/domains/domain-management/dns/delete-email-forwards-dialog.jsx
client/my-sites/domains/domain-management/dns/dns-add-new.jsx
client/my-sites/domains/domain-management/dns/dns-details.jsx
client/my-sites/domains/domain-management/dns/dns-list.jsx
client/my-sites/domains/domain-management/dns/dns-record.jsx
client/my-sites/domains/domain-management/dns/email-provider.jsx
client/my-sites/domains/domain-management/dns/index.jsx
client/my-sites/domains/domain-management/dns/mx-record.jsx
client/my-sites/domains/domain-management/dns/srv-record.jsx
client/my-sites/domains/domain-management/dns/txt-record.jsx

- Use redux actions for notices
- ES6ify
- Use localize
Test:
- Try adding new DNS records
- Deleting them
- Undo

Janitorial: ES6ify DNS components

---

client/my-sites/sidebar/sidebar.jsx

Fixes #16758 
This checks the user's domain registration address to verify that it is
in the US or Canada before allowing the "Store (BETA)" link to show in
the sidebar. This works because an existing atomic converted site is
required to use Store, and a custom domain is required to have an atomic
site.
To test hidden Store link:
1. Log in to WordPress.com with an atomic site with a domain that has been registered to an address *outside* of the US or Canada.
2. `npm start`
3. Visit `http://calypso.localhost:3000/stats/day/<your site url>`
4. Verify that you *do not* see the store link in the sidebar.
To test visible Store link:
1. Log in to WordPress.com with an atomic site with a domain that has been registered to an address *inside* the US or Canada.
3. Visit …

Store: Hide Store sidebar item for non US/CA

---

client/my-sites/domains/domain-management/dns/a-record.jsx
client/my-sites/domains/domain-management/dns/cname-record.jsx
client/my-sites/domains/domain-management/dns/delete-email-forwards-dialog.jsx
client/my-sites/domains/domain-management/dns/dns-add-new.jsx
client/my-sites/domains/domain-management/dns/dns-details.jsx
client/my-sites/domains/domain-management/dns/dns-list.jsx
client/my-sites/domains/domain-management/dns/dns-record.jsx
client/my-sites/domains/domain-management/dns/email-provider.jsx
client/my-sites/domains/domain-management/dns/index.jsx
client/my-sites/domains/domain-management/dns/mx-record.jsx
client/my-sites/domains/domain-management/dns/srv-record.jsx
client/my-sites/domains/domain-management/dns/txt-record.jsx

Reverts Automattic/wp-calypso#16797
Breaks DNS for mapped domains.

Revert "Janitorial: ES6ify DNS components"

---

client/components/tinymce/plugins/simple-payments/dialog/index.jsx

The code this feature needs is in JP 5.2 . Older JP versions will not work.
This disables UI if JP version is older than 5.2
@iamtakashi do you have some UI pointers?
- Test with 5.2 version of JP (AT has 5.2 already),You should get regular UI
- Test with older JP version. You should get notice
- Test with wpcom. It should work

Simple Payments: Disable feature for older JP sites

---

client/my-sites/sidebar/sidebar.jsx

Reverts Automattic/wp-calypso#16799

Revert "Store: Hide Store sidebar item for non US/CA"

---

npm-shrinkwrap.json
package.json

Before this PR we were pinned to a branch which is unsafe.
This PR pins us to a specific commit.

Prettier: pin dependency to a specific commit

---

client/my-sites/domains/domain-management/dns/a-record.jsx
client/my-sites/domains/domain-management/dns/cname-record.jsx
client/my-sites/domains/domain-management/dns/delete-email-forwards-dialog.jsx
client/my-sites/domains/domain-management/dns/dns-add-new.jsx
client/my-sites/domains/domain-management/dns/dns-details.jsx
client/my-sites/domains/domain-management/dns/dns-list.jsx
client/my-sites/domains/domain-management/dns/dns-record.jsx
client/my-sites/domains/domain-management/dns/email-provider.jsx
client/my-sites/domains/domain-management/dns/index.jsx
client/my-sites/domains/domain-management/dns/mx-record.jsx
client/my-sites/domains/domain-management/dns/srv-record.jsx
client/my-sites/domains/domain-management/dns/txt-record.jsx

- Use redux actions for notices
- ES6ify
- Use localize

Janitorial: ES6ify DNS components (try 2)

---

client/lib/mixins/analytics/index.js
client/my-sites/domains/domain-management/list/constants.js
client/my-sites/domains/domain-management/list/domain-list-notice.jsx
client/my-sites/domains/domain-management/list/index.jsx
client/my-sites/domains/domain-management/list/item-placeholder.jsx
client/my-sites/domains/domain-management/list/item.jsx

- ES6ify
- Use localize
- Use redux analytics actions
Test:
- Open Domains
- Change primary
- Click add domain
- go back from a domain edit
Make sure no errors in console and all working well.

Janitorial: Refactor Domains List component 

---

client/blocks/daily-post-button/index.jsx
client/blocks/daily-post-button/style.scss
client/blocks/daily-post-button/test/index.jsx
client/blocks/reader-full-post/index.jsx
client/blocks/reader-full-post/style.scss
client/blocks/reader-post-card/index.jsx
client/blocks/reader-post-card/style.scss

This fixes: https://github.com/Automattic/wp-calypso/issues/16810
Updated in stream and fullpost.
**Before:**
**After:**

Reader: Match Daily Post button with Following

---

client/notifications/index.jsx

tracks added:
am i missing anything? is this enough to accomplish what we want @aaronyan ?

Reader/Notifications: add tracks for open post/comment/site

---

client/components/domains/registrant-extra-info/fr-form.jsx

AFNIC stopped requiring the birth data last year, and we poked OpenSRS to reflect that a few weeks ago. Huzzah!
Props @yoavf.

Domains: remove .fr individual birth data fields

---

config/production.json

Its been on staging for a week, time to let this out

Notifications/Reader: Enable permalinks in production

---

client/components/tinymce/plugins/simple-payments/dialog/index.jsx

Resolves https://github.com/Automattic/wp-calypso/pull/16966
In #16875 I didn't check if plan is previously loaded.
Because of that, we had a following bug:
1. Pick a premium / business site
1. Go do post editor
1. Reload page
1. Open simple payments dialog
1. Nudge is there even if it shouldnt be
Go through above steps, see if problem is gone.
Go through this steps for free / personal site and observe loading indicators before showing a nudge.

Simple Payments: Fix upgrade nudge misfire

---

client/notifications/index.jsx

i didn't realize we couldn't make tracks with camelCase props.
this pr camelcases the names.

Reader/Notifications: fix tracks props to snake_case

---

client/layout/guided-tours/tours/editor-basics-tour.js

To review make sure the new image URL works.

Editor: make editor basics tour use CDN for image

---

client/my-sites/post-relative-time-status/index.jsx

As @aduth suggested in https://github.com/Automattic/wp-calypso/pull/16861#discussion_r131732580

Remove details to avoid duplicate paragraph

---

client/my-sites/preview/main.jsx
client/post-editor/editor-preview/index.jsx

Site & Editor Previews: Grammar fix

---

client/components/tinymce/plugins/simple-payments/dialog/form.jsx

Checks Product Price against:
- Negative value
- Decimal places > 2
- Invalid format
Test Plan:
1. Create or edit a payment button.
2. Try invalid prices.
3. Error messages should be displayed when values is invalid.

Simple Payments: Price Validation

---

client/signup/processing-screen/index.jsx

It's exactly the same as described in the title.
Create a new site and follow the steps then you should be able to see the processing screen like the below screenshot.

Signup: Convert SignupProcessingScreen class into ES6 version.

---

client/components/tinymce/plugins/simple-payments/dialog/index.jsx

This adds stats to relevant simple payments actions
1. enable logging of stats `localStorage.setItem('debug', 'calypso:analytics:*');`
2. perform following actions and you should see stats calls in console:
- open dialog
- create new button
- delete button
- insert button to post

Simply Payments: Add stats

---

client/components/site-selector/add-site.jsx
client/components/site-selector/index.jsx

I'm working with SiteSelector on #17087, and wanted to prettify it separately before making other alterations. I've also switched it to use the new PropTypes package.
As a user with one or more sites, pull up Reader and click 'Share' on a post. Make sure the share process works correctly.

Components: prettify site selector

---

client/components/domains/registrant-extra-info/fr-form.jsx
client/my-sites/checkout/checkout/domain-details-form.jsx

I missed some birth data detritus on that first pass.

Domains: followup fr extra registration form cleanup from #16941

---

config/horizon.json
config/production.json

This enables Simple Payments in production and horizon.
cc @Automattic/stark

Simple Payments: enable feature in production/horizon

---

config/stage.json

Enable Simple Payments on stage

Simple Payments: enable on staging

---

client/blocks/comments/style.scss

**Before:**
Mobile:
**After:**
Mobile:

Fix misaligned trackbacks in comments

---

.dockerignore
Dockerfile

Based on @dmsnell's #8603.
Related: pMz3w-7rt-p2
To test: Follow FG instructions to build and run a local Docker image of Calypso.

Framework: Base Docker image on node base image

---

client/my-sites/media-library/index.jsx

Reverts Automattic/wp-calypso#17169

Revert "Media: fixes context bug after ES6ifying the media library"

---

client/my-sites/media-library/content.jsx
client/my-sites/media-library/filter-bar.jsx
client/my-sites/media-library/index.jsx

Reverts Automattic/wp-calypso#17083

Revert "Media library: ES6ify the index file"

---

client/signup/steps/jpo-contact-form/index.jsx
client/signup/steps/jpo-homepage/index.jsx
client/signup/steps/jpo-site-title/index.jsx
client/signup/steps/jpo-site-type/index.jsx
client/signup/steps/jpo-summary/index.jsx

- fix blocking error when trying to access businessPersonal but jpoSiteType is undefined
- fix functionality and path in summary links to steps that haven't been completed
- write strings to be translated in proper notation and fix typos

JPO: summary links and paths, translations and titles

---

client/my-sites/pages/controller.js
client/my-sites/sidebar/manage-menu.jsx

Renaming Pages to Site Pages and moving it above Blog Posts in the publish menu.
Before:
After:

Renaming Pages and move it to the top.

---

client/blocks/login/index.jsx

Fix eslint error for unused var in login

---

client/me/purchases/confirm-cancel-domain/cancellation-reasons.js

Link leads to: https://support.wordpress.com/transfer-domain-registration
Fixes #17124

Domains: improve transfer-desired-when-cancel verification copy

---

client/components/tinymce/plugins/simple-payments/dialog/form.jsx
client/components/tinymce/plugins/simple-payments/dialog/index.jsx

When editing an existing button, use the `currency` (`spay_currency`) field that it already has set instead of using the user's defaults. The defaults should be used only for creating new buttons, nothing else.
We no longer need to pass the `currencyDefaults` prop to `ProductForm`, as the currency code is already in the form's `values.currency` field.
A small drive-by change: the price placeholder value depends on the currency's `precision` field: it's either '0', '0.0' or '0.00' etc.
Implementation note: the `getCurrencyDefaults` function always returns a sensible default (USD) no matter what the argument is, so we don't need to check its return value.
To test:
1. Let's have two authors on a blog where each of them has a different currency set (i.e., EUR and USD).
2. Let each of the …

Simple Payments: use the product's stored currency when editing it

---

client/components/tinymce/plugins/simple-payments/dialog/index.jsx

When editing a button, there is now only a "Done" button that replaces the previous "Cancel" and "Save" ones.
When user tries to navigate away from the changed form, either by clicking on "<- Payment Buttons" or by clicking outside the modal, the form is saved first and only after save the navigation transition proceeds -- either by switching a tab or by closing the modal.
If the save fails, e.g., because of network error, the navigation is cancelled and the form remains displayed -- with an error notice.
There is one loophole in the current implementation: if the edited form is invalid, then the form won't be saved, the navigation proceeds and the data are lost. I'll close the loophole before merging, if we decide that this PR is the right way to go.
This PR makes it impossible to …

SimplePaymentsDialog: check for unsaved changes in the form on navigation transition

---

client/lib/post-normalizer/utils.js

Songs!
To test, try http://calypso.localhost:3000/read/feeds/25320833/posts/1561266515 vs prod.

Reader: Whitelist radiopublic embeds

---

client/lib/abtest/active-tests.js
client/lib/plans/constants.js
client/my-sites/plan-features/header.jsx
client/my-sites/plan-features/index.jsx
client/my-sites/plan-features/style.scss
client/my-sites/plan-price/index.jsx
client/my-sites/plans-features-main/index.jsx

Reverts Automattic/wp-calypso#16693

Revert "Remove/plans signup test"

---

client/extensions/wp-super-cache/package.json

To open it up to wider testing.

WPSC: Enable in horizon environment

---

client/post-editor/media-modal/index.jsx

React.PropTypes is deprecated.

Use PropTypes in media modal

---

client/extensions/wp-super-cache/app/constants.js
client/extensions/wp-super-cache/app/main.jsx
client/extensions/wp-super-cache/components/navigation/index.jsx
client/extensions/wp-super-cache/index.js

For better legibility & maintainability.
To test -- make sure WPSC's navigation tabs still work fine.

WPSC: Simplify Routing

---

client/extensions/wp-super-cache/app/constants.js

WPSC: Fix 'Easy' tab label

---

client/my-sites/domain-tip/index.jsx
client/my-sites/upgrade-nudge/docs/example.jsx
client/my-sites/upgrade-nudge/index.jsx

Use `extends React.Component`
Localize
Use `prop-types`
Destructure `props` for easier readability

ES6ify Upgrade Nudge and Domain Tip

---

client/blocks/post-item/docs/example.jsx
client/blocks/reader-post-card/docs/example.jsx

Currently breaking all of blocks.

Reader: Fix devdocs/blocks reader-post-card usage

---

config/horizon.json
config/production.json
config/test.json

Reverts Automattic/wp-calypso#17381

Revert "Enable social signup in production"

---

client/signup/steps/jpo-site-type/select-business-personal.jsx
client/signup/steps/jpo-site-type/select-genre.jsx
client/signup/steps/jpo-site-type/style.scss

JPO: fix mobile styles lost during markup update

---

config/horizon.json
config/production.json
config/test.json

Reverts Automattic/wp-calypso#17395

Revert "Revert "Enable social signup in production""

---

client/my-sites/checkout/checkout-thank-you/rebrand-cities-thank-you.jsx

This PR updates the typeform URL for the Rebrand Cities signup flow.

Updated typeform URL

---

client/my-sites/media-library/content.jsx

* Change your account to a translated lang other than English.
* Disconnect your google account. Open the media library and choose Googlo source: check that message promting you to connect is translated.
* Try to upload a file not supported (or a video to a non-premium site). Check that message is translated.

Fix i18n-no-this-translate rule

---

client/signup/steps/jpo-summary/index.jsx
client/signup/steps/jpo-summary/style.scss

* fixed icon color and size to match Calypso standard sizes
* adjusted mobile wrapping
* adjusted wording
* added links to the second column
* aligned text across two columns

JPO - Step 5 (summary) style adjustments

---

client/jetpack-connect/auth-logged-in-form.jsx
client/jetpack-connect/auth-logged-out-form.jsx
client/jetpack-connect/authorize-form.jsx
client/jetpack-connect/plans-landing.jsx

This PR reverts https://github.com/Automattic/wp-calypso/pull/16995, which is likely causing some bugs

JPC: Revert #16995

---

client/extensions/wp-super-cache/package.json

WPSC: Enable in Production

---

client/blocks/product-purchase-features/product-purchase-features-list/jetpack-anti-spam.jsx
client/blocks/product-purchase-features/product-purchase-features-list/jetpack-backup-security.jsx
client/blocks/product-purchase-features/product-purchase-features-list/jetpack-return-to-dashboard.jsx
client/blocks/product-purchase-features/product-purchase-features-list/jetpack-wordpress-com.jsx

Simplifying various text blocks.

Copy updates to My Plan (Jetpack)

---

client/blocks/login/login-form.jsx
client/boot/app.js
client/boot/common.js
client/components/signup-form/README.md
client/components/signup-form/index.jsx
client/jetpack-connect/auth-logged-out-form.jsx
client/lib/signup/step-actions.js
client/my-sites/invites/invite-accept-logged-out/index.jsx
client/signup/config/flows.js
client/signup/config/step-components.js
client/signup/config/steps.js
client/signup/main.jsx
client/signup/processing-screen/index.jsx
client/signup/steps/user/index.jsx

This is a new attempt at merging https://github.com/Automattic/wp-calypso/pull/12810
This PR was [reverted](https://github.com/Automattic/wp-calypso/pull/17523) due to an error happening in signup.
- Follow instructions on https://github.com/Automattic/wp-calypso/pull/12810
- Also check that normal signup works properly

Signup: Add a new WPCC flow to accept signups coming from DOPS (take 3) 

---

client/my-sites/current-site/notice.jsx

The Notice component was being used incorrectly and all the buttons were misaligned.
Before:
After:

Janitorial: Fix styling for site notices

---

client/my-sites/controller.js

Sometimes a user with one visible site and no selected site gets placed into an infinite redirect loop with the `/undefined` string concatenated to the url until the browser crashes.
Thanks @jeremysawesome for the screenshot gif, very helpful.
For some reason, the primary site is not found and an attempt to access `primary.slug` results in the addition of `/undefined` string on a redirect. Code here.
https://github.com/Automattic/wp-calypso/blob/master/client/my-sites/controller.js#L278
Still in progress: Checking for existence of `primary` before redirecting is a bandaid that works. Next, I will look into why it can't find the primary site.
Fixes https://github.com/Automattic/wp-calypso/issues/16864

MySites: Fix undefined path loop

---

client/my-sites/controller.js

Reverts Automattic/wp-calypso#17512

Revert "MySites: Fix undefined path loop"

---

client/lib/abtest/active-tests.js
client/lib/signup/step-actions.js
client/my-sites/checkout/checkout/domain-details-form.jsx
client/my-sites/checkout/checkout/privacy-protection.jsx
client/my-sites/checkout/checkout/style.scss
client/my-sites/domains/domain-search/domain-search.jsx

Reverts Automattic/wp-calypso#17475

Revert "A/B Test: Privacy protection auto added"

---

client/my-sites/plugins/disconnect-jetpack/disconnect-jetpack-button.jsx

Just a quick refactor of a section that I came across that had room for some formatting fixes/improvements.
The main change that I made was inlining some items in to the JSX (props & translation) - I did this to make reading the code a little more straight forward.
No logic/behaviour should change.
Follow the test plan laid out in #15433 - there should be no change to the behaviour.

Refactor disconnect-jetpack-button render method

---

config/stage.json

This PR disables plugin upload on staging, as discussed recently.

Config: Disable plugin upload on staging

---

client/signup/steps/jpo-contact-form/index.jsx
client/signup/steps/jpo-contact-form/style.scss
client/signup/steps/jpo-homepage/style.scss

- centering the single card at large breakpoint
- adding margins for the smaller breakpoint
- breaking the card down into divs to match the other cards
- keeping the button style & illustration in place across small and large breakpoints since this step only has one card
- (improving the button style quickly for the homepage/step 3)

Cherry pick changes from 6a22b8b in 17416 - JPO: Updates to Step 4 styles

---

client/my-sites/checkout/checkout/privacy-protection.jsx

Domains: Fix copy for radio button privacy variation

---

client/components/forms/form-phone-media-input/index.jsx
client/components/phone-input/index.jsx

Reverts Automattic/wp-calypso#17595

Revert "Add focus to FormPhoneMediaInput."

---

assets/stylesheets/_components.scss
client/blocks/color-scheme-picker/README.md
client/blocks/color-scheme-picker/constants.js
client/blocks/color-scheme-picker/docs/example.jsx
client/blocks/color-scheme-picker/index.jsx
client/blocks/color-scheme-picker/style.scss
client/components/forms/docs/example.jsx
client/devdocs/design/blocks.jsx
client/state/preferences/constants.js
client/state/preferences/schema.js
public/images/color-schemes/color-scheme-thumbnail-dark.svg
public/images/color-schemes/color-scheme-thumbnail-default.svg
public/images/color-schemes/color-scheme-thumbnail-light.svg

This PR is identical to PR #17200 which we, unfortunately, merged into another feature branch rather than master. So opening this new PR to merge PR #17200 changes into master (this time already rebased against master).

Color Schemes: Add Color Scheme Picker II

---

client/my-sites/post-relative-time-status/index.jsx

I know small fix, but might help when greping for similiar vars :)

Fix variable typo

---

client/components/phone-input/index.jsx

While I was working oh this component, I thought I would updated it to use `prop-types` and move anonymous function out of props in `render()`.

Janitorial: update PhoneInput component

---

client/my-sites/media/main.jsx
client/post-editor/media-modal/index.jsx
client/post-editor/media-modal/test/index.jsx

Enhances #10982  message by clarifying that deleted media items cannot be recovered.
This PR comes from here: #15438 but I did something wrong when rebasing that PR and created another PR instead 💃 💃 💃 💃

Changing wording to make the delete media message scarier

---

npm-shrinkwrap.json
package.json

- Fixes a translation issue in the filter bar
- Includes more support for deep-linking
**Testing**
Open in the live branch or in local dev and make sure notifications don't blow up.
Make sure to test clicking on links for sites, posts, and comments.
**Notes**
It seems like the unread filter is still not translating properly but I don't think that should
stand in the way of merging this PR.

Notifications: Version bump to 1.2.3

---

client/blocks/comments/post-comment.jsx
client/blocks/comments/utils.jsx
client/blocks/conversation-caterpillar/docs/example.jsx
client/blocks/conversation-caterpillar/docs/fixtures.js
client/blocks/conversation-caterpillar/index.jsx
client/blocks/conversation-caterpillar/style.scss
client/blocks/conversations/docs/example.jsx
client/blocks/conversations/list.jsx
client/state/comments/reducer.js
client/state/comments/selectors.js
client/state/comments/test/reducer.js

Lets get some 🐛s on convos
currently based from ~~[this branch](https://github.com/Automattic/wp-calypso/pull/17589)~~ master.
To Do:

Convos Caterpillar: connective tissue

---

client/state/purchases/test/actions.js

While investigation why a failed purchase removal is not displaying an error in the UI, I created this test. The test passes, as it should (this doesn't expose the bug I've stumbled on).
But it's still useful to have this test too.

Purchases: Add test for purchase removal failure

---

npm-shrinkwrap.json

Fixes an omission from #17688.

Add express-useragent to shrinkwrap

---

client/me/help/help-contact-closed/index.jsx
client/me/help/help-contact/index.jsx

This PR addresses 408-gh-hg. Please see that issue for testing details.

Update support closure messaging to accommodate GM 2017 reduced support

---

client/my-sites/plugins/plugins-browser/index.jsx

If the site is not Jetpack and does not have Business plan already, show upgrade nudge for the Business plan:
Spinoff from the #17537 feature branch for Plugins improvements project.
**Testing instructions:**
1. Go to `/plugins/browse` page (all sites selected). Verify that the nudge is not there.
2. Switch to a Jetpack site. Verify the nudge is not there.
3. Switch to an Atomic site with a Business plan. Verify the nudge is not there.
4. Switch to a Simple site with Free or Premium plan. Verify the nudge *is* there.

Plugins: add upgrade nudge to the plugins browser page

---

client/blocks/comment-button/style.scss
client/blocks/post-edit-button/style.scss
client/blocks/reader-post-card/style.scss

Fixes: https://github.com/Automattic/wp-calypso/issues/17706
Also moved Share icon down a bit.
Before:
After:
Also moved Edit icon up a bit.
Before:
After:

Reader: Fix Comment and Like alignment

---

server/lib/analytics/index.js

We weren't actually sending the pixel request because I didn't know how superagent works 😬

Fix for sending pixel request on nostats

---

server/boot/index.js

Change blocked stats event name for tracks compat

---

client/my-sites/stats/activity-log-item/activity-actor.jsx
client/my-sites/stats/activity-log-item/index.jsx
client/my-sites/stats/activity-log-item/style.scss
client/state/activity-log/log/schema.js
client/state/activity-log/log/test/reducer.js
client/state/data-layer/wpcom/sites/activity/from-api.js
client/state/data-layer/wpcom/sites/activity/test/from-api.js

Special handling for the `Jetpack`/`Application` (`actor.name` / `actor.type`) actor.
1. Visit https://calypso.live/stats/activity?branch=add/activity-log/handle-jetpack-actor
1. Look at Jetpack events

Activity log: Special handling for Jetpack actor

---

client/state/happychat/test/middleware.js

Preserve and restore global properties instead of global object.

Keep and restore global object properties

---

client/blocks/comments/post-comment.jsx
client/blocks/conversation-caterpillar/index.jsx
client/blocks/conversations/list.jsx
client/lib/with-dimensions/index.jsx
client/state/comments/actions.js

@bluefuton feel free to use this as a jumping off point to ask me questions about how caterpillars work.
This PR represents an effort to improve the documentation surrounding caterpillars + PostComments in general.

Reader Documentation: explain caterpillars and withDimensions

---

client/blocks/conversation-caterpillar/index.jsx
client/blocks/conversation-caterpillar/style.scss

Implement Show All button as described in: https://github.com/Automattic/wp-calypso/issues/17663

Reader Caterpillars: Show All Comments Button

---

client/me/help/help-contact-closed/index.jsx

This PR updates the closure notice from "Limited Support This Week" to "Limited Support Sep 11-18" to avoid further confusion.

Update the closure title to avoid further confusion.

---

client/blocks/login/login-form.jsx
client/components/signup-form/index.jsx
client/jetpack-connect/auth-logged-out-form.jsx
client/lib/paths/login/index.js
client/lib/paths/login/test/index.js

For configurations without native login, the email autofill wasn't working.

Use proper params on email redirect

---

client/post-editor/post-editor.jsx

Fix for https://github.com/Automattic/wp-calypso/issues/17930

Editor: Fix mode switching in Safari

---

client/lib/post-normalizer/rule-decode-entities.js
client/state/selectors/get-post-revision-changes.js
client/state/selectors/test/get-post-revision-changes.js
client/state/selectors/utils/revisions/index.js

Fixes #17448 
(ignore the incorrect branch name; too late now ¯\\_(ツ)_/¯)

Editor: Revisions: Decode HTML entities in diff viewer

---

client/me/help/help-contact/index.jsx

This fixes the behavior for support closures during the 2017 GM. See testing instructions at 408-gh-hg.

Implement GM 2017 support closure behavior

---

client/state/jetpack-connect/actions.js

This PR combines two things:
- removes analytics during Jetpack Connect from setTimeout call, since it could be causing race conditions and no longer seems to be necessary
- moves the JPC auth success metric to after the sites refresh, so that if sites refresh starts to fail (as it was) it shows up in our funnels :)
cc @johnHackworth

Remove setTimeout from tracking trigger; Move authorize success logging

---

.github/SUPPORT.md
CODE-OF-CONDUCT.md
client/components/token-field/README.md
server/devdocs/README.md
server/pages/browsehappy.jade

Update external links to all use HTTPS instead of HTTP
No functional changes

Update external links to use HTTPS

---

client/lib/phone-validation/index.jsx

There were a bunch of eslint violations in this file.  It also used require instead of es6 module syntax.

Updates phone-validation to meet eslint rules

---

client/components/date-picker/events-tooltip.jsx
client/components/date-picker/index.jsx

Fixing PropTypes import in Date Picker.

import PropTypes from prop-types

---

client/components/close-on-escape/index.jsx

Clean up ESLint errors for the close-on-escape component

ESLint cleanup of close-on-escape

---

client/components/card/compact.jsx
client/components/card/index.jsx

import CreateClass and PropTypes separately.

Change CreateClass and PropTypes

---

client/my-sites/posts/post-list.jsx

Preparatory work for reduxification. To test: Verify `/posts` still works as before (single-page and multi-page mode, queries, etc).

PostList: Run Codemods

---

client/components/clipboard-button-input/index.jsx

Updated to address ES6 syntax issues.

updates to the clipboard-button-input component for ES6 syntax issues

---

assets/stylesheets/_components.scss
client/components/sorted-grid/index.jsx
client/components/sorted-grid/label.jsx
client/components/sorted-grid/style.scss

This PR adds a `SortedGrid` component that wraps around an `InfiniteList` component and allows for grouping items by displaying appropriate labels ( see image below ).  
This is meant to be used to display dates above media library items.
Not wired yet.

Components: Add SortedGrid component

---

client/components/timezone/index.jsx

This PR updates the Timezone component to use the data layer. 
~In progress, we need to land #18018 first.~
#18018 has been merged.
1. ~Wait until #18018 is merged.. (or cherry-pick the single commit on this PR onto #18018's branch).~
1. Get to `/settings/general/:site` (for one of your .com sites)
1. Expect to see the timezones select contain all of the timezone items as expected.

Components: Update Timezone component to use data layer

---

client/components/card/compact.jsx
client/components/card/index.jsx

Fixing casing of create class since it is a function not a class

Fix case of createClass

---

bin/codemods/i18n-mixin
bin/codemods/src/i18n-mixin-to-localize.js

The i18n codemod was not checking for or fixing `this.moment` or `this.numberFormat` usage. This PR adresses that.
Testing
* Run the codemod one offending files

Codemods: Check moment and numberFormat usage in i18n fixes

---

client/account-recovery/reset-password-form/index.jsx

Ran `./bin/runmods.sh client/account-recovery` and it applied one codemod to one file 😄 
@gwwar could you please sanity check this for me? I think it's good to 🚢

Apply codemods to `client/account-recovery`

---

client/blocks/login/login-form.jsx

Remove reference to unused variable

---

client/components/external-link/docs/example.jsx
client/components/external-link/index.jsx
client/components/external-link/style.scss
client/components/external-link/test/index.js

Test using this page:  /devdocs/design/external-link
Ensure that external link looks correct and functions correctly.

Update external link with tests and class syntax

---

client/blocks/reader-combined-card/style.scss
client/blocks/reader-related-card-v2/style.scss

Addresses https://github.com/Automattic/wp-calypso/issues/17992

Reader CombinedCards and Recs: increase font-weight of byline

---

client/extensions/woocommerce/woocommerce-services/lib/utils/tree.js
client/extensions/woocommerce/woocommerce-services/state/shipping-label/actions.js
client/extensions/woocommerce/woocommerce-services/state/shipping-label/reducer.js
client/extensions/woocommerce/woocommerce-services/views/shipping-label/label-purchase-modal/address-step/fields.js
client/extensions/woocommerce/woocommerce-services/views/shipping-label/label-purchase-modal/address-step/index.js
client/extensions/woocommerce/woocommerce-services/views/shipping-label/label-purchase-modal/address-step/suggestion.js
client/extensions/woocommerce/woocommerce-services/views/shipping-label/label-purchase-modal/packages-step/add-item.js
client/extensions/woocommerce/woocommerce-services/views/shipping-label/label-purchase-modal/packages-step/get-package-descriptions.js
client/extensions/woocommerce/woocommerce-services/views/shipping-label/label-purchase-modal/packages-step/package-info.js
client/extensions/woocommerce/woocommerce-services/views/shipping-label/label-purchase-modal/rates-step/index.js
client/extensions/woocommerce/woocommerce-services/views/shipping-label/label-purchase-modal/rates-step/list.js

Fixes the lodash imports for the code copied from WCS

WooCommerce Services - fixed lodash imports

---

client/jetpack-connect/controller.js
client/jetpack-connect/main.jsx

Update Jetpack Connect via codemods.
The only significant change was updating `require`s to hoisted `imports`.

Jetpack Connect: Run codemods

---

client/my-sites/site-settings/search.jsx
client/my-sites/site-settings/settings-traffic/main.jsx

Enable the new Jetpack search module toggle.
see: https://github.com/Automattic/jetpack/pull/7829

Enable Jetpack search module UI

---

client/components/social-icons/facebook.jsx
client/components/social-icons/google.jsx

change PropTypes.boolean to PropTypes.bool.

change PropTypes.boolean to PropTypes.bool.

---

client/jetpack-connect/plans.jsx

Future proof against other plan slugs etc.
cc @bubel

Rationalize plan selection events

---

client/my-sites/site-settings/search.jsx

Dont show search checkbox for atomic sites

---

docs/coding-guidelines/javascript.md

A nice simple one :)
The referenced link above is already updated to use the new library so doesn't need to be updated.

ReadMe: update PropTypes reference

---

client/lib/abtest/active-tests.js
client/signup/config/flows.js
client/signup/config/steps.js
client/signup/steps/design-type-with-store/index.jsx
client/signup/steps/design-type/index.jsx
client/signup/utils.js

This PR removes the code in charge of adding the Skip Themes Selection Modal A/B test.

Remove `skipThemeSelectionModal` A/B test code.

---

docs/install.md

Added emphasis to which versions of node and npm to install.

Install docs: emphasize node version requirement

---

client/lib/abtest/active-tests.js
client/lib/plans/constants.js
client/my-sites/plan-features/index.jsx

Stopping copy test and translating strings so that it can be available to all users.

Stop test and translate new strings

---

client/my-sites/invites/utils.js

Calypso fails when accepting an invite for a custom role.
https://github.com/Automattic/jetpack/issues/7812

Invites: Add default case to handle custom roles

---

client/sections-preload.js

resolved typo error

---

client/my-sites/checkout/checkout/new-card-form.jsx
client/my-sites/checkout/checkout/style.scss

Takes care of: import, exports, proptypes, i18n, css namespace
Not that we need a reason to do those updates, but this is needed for #18286 
For testing, add a product to cart and checkout, and check that the credit card form is there as expected. If you already have existing cards stored, click on `Use a New Credit/Debit Card`

New Card Form: update and run codmemods 

---

client/jetpack-connect/plans.jsx

Fix invalid event on plan submit

---

client/lib/products-values/index.js
client/my-sites/site-settings/search.jsx

Turns out VIP Go sites render their plans in unusual ways.

Show Traffic/Search settings for VIP Go sites

---

client/blocks/image-editor/image-editor-toolbar.jsx
client/components/chart/bar.jsx
client/components/empty-content/index.jsx
client/components/infinite-list/scroll-helper.js
client/components/post-schedule/clock.jsx
client/components/post-schedule/docs/example.jsx
client/components/resizable-iframe/index.jsx

Update condition as per JavaScript documentation:
https://github.com/Automattic/wp-calypso/blob/master/docs/coding-guidelines/javascript.md

Update condition as per JavaScript documentation.

---

client/blocks/conversation-caterpillar/index.jsx
client/state/data-layer/wpcom/comments/index.js
client/state/data-layer/wpcom/comments/test/index.js

fixes: https://github.com/Automattic/wp-calypso/issues/17812
To Test:
1. find a where the last commenter has entities in his name. I used: http://calypso.localhost:3000/read/blogs/109468251/posts/4705
2. check that this branch doesn't have HTML Entities in the caterpillar

Reader Caterpillar author: decodeEntities

---

client/lib/feature-detection/index.js

This PR just proposes a slight tweak to part of #17310 - I'm making them this way while @frontdevde is busy smashing tickets :)
Following the original test plan of #17310 should suffice to test these changes.
** Note the base branch is the original PR branch, not master. **

Color Schemes: Use recommended method for assert window global exists

---

client/extensions/woocommerce/app/reviews/review-reply.js
client/extensions/woocommerce/app/reviews/style.scss

Adds styling for review replies in Store

---

client/lib/formatting/index.js
client/lib/post-normalizer/index.js
client/lib/post-normalizer/rule-content-make-links-safe.js
client/lib/post-normalizer/rule-make-links-safe.js
client/lib/post-normalizer/test/index.js
client/lib/post-normalizer/utils.js
client/state/reader/feeds/reducer.js
client/state/reader/feeds/test/reducer.js
client/state/reader/posts/normalization-rules.js

Ensure they have a valid protocol (http or https) before allowing them through the normalizer.

Reader: Make post links and links in content safe

---

client/lib/store-transactions/index.js
client/my-sites/checkout/checkout/checkout.jsx
client/my-sites/checkout/checkout/credit-card-payment-box.jsx
client/my-sites/checkout/checkout/pay-button.jsx

Broken by #18359, reported by @lamosty in Slack.

Checkout: Fix Transaction Steps imports

---

client/post-editor/editor-discussion/index.jsx
client/post-editor/editor-location/index.jsx

Broken by #18359, reported by @rachelmcr in Slack.
>When I change the discussion settings (on a post) I get `Uncaught TypeError: Cannot read property 'recordStat' of undefined`

Post Editor: Fix stats imports

---

client/components/token-field/index.jsx
client/devdocs/controller.js
client/lib/network-connection/index.js
client/lib/service-worker/service-worker.js

Prettier: Fix some unused var errors

---

client/blocks/comments/form.jsx
client/blocks/comments/style.scss
client/blocks/conversations/style.scss
client/blocks/reader-related-card-v2/style.scss

This addresses: https://github.com/Automattic/wp-calypso/issues/18542
**Before:**
Conversations:
Fullpost:
**After:**

Reader: Update Comments Closed style

---

client/blocks/upgrade-nudge-expanded/README.md
client/components/dialog/README.md
client/components/purchase-detail/README.md
client/components/section-header/README.md
client/lib/abtest/README.md
client/me/purchases/components/loading-placeholder/README.md
client/my-sites/jetpack-manage-error-page/README.md
client/my-sites/plugins/plugin-action/README.md
client/my-sites/plugins/plugins-browser-list/README.md
client/my-sites/plugins/plugins-list/README.md
client/my-sites/welcome/README.md
docs/our-approach-to-data.md

Docs: Replace this.translate() with this.props.translate()

---

client/components/tinymce/plugins/contact-form/style.scss

@rickybanister 
Create a new post and drop in a contact form. Make a really long form to test scrolling. Take a look at the form's settings tab as well.

Contact Form - fixed busted spacing and added rounded corners

---

client/blocks/login/index.jsx
client/blocks/login/social.jsx

Reverts Automattic/wp-calypso#18693

Revert "Fix redirectTo value used after login"

---

client/my-sites/checkout/checkout-thank-you/jetpack-thank-you-card.jsx

Removes unused method `renderErrorDetails()` from `client/my-sites/checkout/checkout-thank-you/jetpack-thank-you-card.jsx`.
1. Just verify that the method is no longer used in that same component.

Jetpack Thank You Card: Remove unnecessary method from JetpackThankYouCard component

---

client/layout/guided-tours/tours/simple-payments-tour.js

It's a minor edit, but I thought adding some popular use cases of Simple Payments might inspire and motivate the customers.
cc @Automattic/editorial for the copy review or better suggestions :) Thanks in advance!
Before:
After:

Guided Tours: Update copy in Simple Payments tour.

---

client/blocks/conversation-caterpillar/docs/example.jsx
client/blocks/conversation-caterpillar/index.jsx
client/blocks/conversation-caterpillar/style.scss

We decided to remove the show all button for both ux and technical reasons.
To Test
-------
1. fire up conversations and interact with the caterpillar

Reader Conversations: remove show all

---

client/my-sites/sidebar/manage-menu.jsx

Small janitorial PR that removes the feature flag check for the _Media_ and _Comments_ menu items, since they are enabled on all environments.

Sidebar: removes feature flag checks for Media and Comments on My Sites

---

client/extensions/woocommerce/state/sites/settings/email/queryLists.jsx
client/extensions/woocommerce/state/sites/settings/email/querySettings.jsx
client/extensions/woocommerce/state/sites/settings/email/querySyncStatus.jsx

This is a part of #17434 PR that represents Query components used in MailChimp integration code.
This is provided for review as a separate PR because the original (spike) PR is too big for the review to be comfortable.
To test these elements in action please refer to #17434.

MailChimp integration query components.

---

client/extensions/woocommerce/app/settings/email/mailchimp/setup-steps/log-into-mailchimp.js

This is a part of #17434 PR that represents log into MailChimp UI view. This is the first step of the setup procedure.
To test this component in action please refer to #17434.

MailChimp setup log into MailChimp.com step.

---

client/blocks/conversations/docs/example.jsx
client/components/drop-zone/docs/example.jsx
client/components/input-chrono/docs/example.jsx
client/components/post-schedule/docs/example.jsx

Probably broken by #18590.
The error is visible at https://wpcalypso.wordpress.com/devdocs/design:
In addition to that error, this PR fixes the title displayed in devdocs (currently "Localized(InputChrono)").
To test:
* Visit http://calypso.localhost:3000/devdocs/design/input-chrono
* Verify that there are no errors in the console.

InputChrono: Fix devdocs example

---

client/extensions/woocommerce/app/settings/email/mailchimp/setup-steps/store-info.js

This is a part of #17434 PR that represents MailChimp Store Informations UI view. This is the third step of the setup procedure.
To test this component in action please refer to #17434.
Card needs some styling.

MailChimp store info card.

---

client/extensions/woocommerce/app/settings/email/mailchimp/setup-steps/newsletter-settings.js

This is a part of #17434 PR that represents MailChimp Store Informations UI view. This is the fourth step of the setup procedure.
To test this component in action please refer to #17434.

MailChimp newsletter settings UI component.

---

client/my-sites/plugins/disconnect-jetpack/disconnect-jetpack-button.jsx

Restore GA action

---

client/blocks/comment-detail/index.jsx

Closes #15455 (M4 Task)
Currently missing post titles are simply replaced by "Untitled", as we don't necessarily have any other information about the post loaded in state.
This PR adds a `QueryPosts` component that only requests the post if:
- The post title included in the comment object is missing.
- And the post is not yet loaded in state.
Then, uses the post excerpt instead of the title.
| --- | --- |
| <img width="633" alt="screen shot 2017-10-16 at 17 27 45" src="https://user-images.githubusercontent.com/2070010/31624252-f98aa032-b299-11e7-94dd-aed028229d05.png"> | <img width="632" alt="screen shot 2017-10-16 at 17 27 52" src="https://user-images.githubusercontent.com/2070010/31624261-ff8a9e74-b299-11e7-8286-aae2cb1fb7cb.png"><br /><br /><img width="631" …

Comments: When post is missing a title use excerpt

---

client/extensions/woocommerce/app/settings/email/mailchimp/setup-steps/campaign-defaults.js

This is a part of #17434 PR that represents MailChimp Campaign Defaults UI view. This is the step number of the setup procedure.
To test this component in action please refer to #17434.

Mailchimp Campaign Defaults UI component.

---

client/extensions/woocommerce/app/settings/email/index.js
client/extensions/woocommerce/app/settings/email/mailchimp/index.js
client/extensions/woocommerce/app/settings/email/mailchimp/setup-mailchimp.js

This is a part of #17434 PR that represents MailChimp Calypso entry point and code that is responsible for carrying out the setup procedure. 
This is **WIP** - suggestions are highly welcome as they will help to speed up the deployment process.
To test these elements in action please refer to #17434.

MailChimp Setup and entry point.

---

client/my-sites/site-settings/disconnect-site/too-expensive.jsx

See https://github.com/Automattic/wp-calypso/pull/18749#issuecomment-337964565.

Disconnect Flow: Minor Copy Fix

---

client/blocks/comments/helper.jsx

Or at least don't disallow them. :)

Reader: Turn on jetpack comments.

---

config/stage.json

Enables the WooCommerce Services plugin UI in staging.

WooCommerce - enable WCS in staging

---

client/components/happiness-support/index.jsx

A comma with a purpose is a comma filled with joy.

HappinessSupport - This comma unlocks maximum happy potential

---

npm-shrinkwrap.json
package.json

Companion PR to https://github.com/Automattic/gridicons/pull/260

Framework: Bump Gridicons to 2.1.0

---

client/lib/feed-post-store/post-fetcher.js
client/lib/feed-post-store/test/post-fetcher.js

No functional changes
To test, load up the reader in the past (http://calypso.localhost:3000/?at=2017-09-15T00:00:00Z), wait for the update pill to appear, accept updates. You should see new posts load in one by one.

Reader: Remove immutable usage from feed-post-store

---

npm-shrinkwrap.json
package.json

**Testing**
* Restart Calypso.
* Check that `package.json` in `node_modules/notifications-panel` shows v1.2.7.
* Smoke-test that nothing seems broken in the UI.

Notifications: Update the `notifications-panel` package to v1.2.7.

---

client/extensions/woocommerce/app/settings/email/mailchimp/mailchimp_dashboard.js

MailChimp sync UI on the dashboard was trying to show sync status before it had all the data.
This resulted in following undefined state:
This was fixed by adding placeholder element that indicates that we are waiting:

Store: MailChimp sync tab indicates loading state.

---

assets/stylesheets/_components.scss
client/my-sites/comments/comment/comment-author-more-info.jsx
client/my-sites/comments/comment/comment-author.jsx
client/my-sites/comments/comment/comment-header.jsx
client/my-sites/comments/comment/index.jsx
client/my-sites/comments/comment/style.scss
client/my-sites/comments/comment/utils.js

Context: p3fqKv-5W1-p2, p7jreA-11f-p2
This PR is meant as an example of what a full refactor of `CommentDetail` could be.
Following the new design iteration, I've highlighted what seem to me the next container components, and what they will contain.
There is a lot of stuff going on in this PR, but mostly I'd like to point out:
- The new components names, and their new directory: dropped the `detail` part, which is unnecessary now that we're in `CommentList` context.
`Comment` is imho plenty enough.
- It's Reduxified as much as possible without introducing new selectors. Though, the `utils.js` file (copypasted straight off #18406) contains many functions that could be converted into selectors.
- The `CommentHeader` is extremely simpler than before, thanks to the actions moved elsewhere. …

Comments: Redesign the component (Part 1)

---

client/extensions/woocommerce/app/settings/email/index.js
client/extensions/woocommerce/app/settings/email/mailchimp/mailchimp_dashboard.js
client/extensions/woocommerce/app/settings/email/mailchimp/style.scss

Branched of #19069
Move MailChimp save button from Dashboard to `ActionHeader` component. 
This uses redux elements from #19069 to allow communication between components.

Move MailChimp save button to proper location.

---

client/extensions/woocommerce/app/settings/email/mailchimp/mailchimp_dashboard.js
client/extensions/woocommerce/app/settings/email/mailchimp/style.scss

Truncate long list name to provide better visual experience:
In other PR there will be a tooltip added to show full list name.

Store: MailChimp sync status ellipsis

---

client/extensions/woocommerce/app/settings/email/mailchimp/mailchimp_dashboard.js

Move Resync link below the list name, making more place for the list name.

Store: MailChimp, move resync button to better place.

---

client/extensions/woocommerce/app/settings/email/mailchimp/setup-mailchimp.js
client/extensions/woocommerce/state/sites/settings/email/selectors.js
client/extensions/woocommerce/state/sites/settings/email/test/selectors.js

Campaign Defaults step was obfuscating the UX. Because we had all the required information
to create default values we can pass them in REST request without user interaction.

Remove MailChimp campaign defaults step.

---

client/extensions/woocommerce/app/settings/email/mailchimp/mailchimp_dashboard.js
client/extensions/woocommerce/app/settings/email/mailchimp/style.scss

Use loading state to indicate visually that list is being loaded.

Store: MailChimp loading sync notice

---

client/state/data-layer/wpcom-http/README.md

Just some documentation updates

Data Layer: Add docs for `fromApi()` in data layer guide

---

client/extensions/woocommerce/app/dashboard/index.js
client/extensions/woocommerce/app/settings/email/mailchimp/index.js

Change MailChimp sync request to request settings for store dashboard. This change is introduced to improve Store dashboard load time. Additionally, QueryJetpackPlugins was removed that should further improve dashboard performance.
@timmyc Could you verify if the change brings improvement. I think it does but I would love your opinion on this.

Store: MailChimp use settings endpoint for dashboard.

---

client/extensions/woocommerce/woocommerce-services/state/shipping-label/actions.js

When purchasing the labels, after the initial purchase request ha been made, the client polls for the label status by sending a request per individual label. If any of the requests fail, for example due to a timeout, the whole purchase will fail but the user will still be charged.
This mitigates the problem. Each label poll request will be retried up to 3 times on timeout, and only then it will show an error to the user.
To test:
I used this plugin to trigger occasional timeouts (can be modified to always cause a timeout):
```
function delay_label_purchase( $r, $url ) {
if ( false !== strpos( $url, 'get_refund=true' ) ) {
sleep( rand( 3, 5 ) );
}
return $r;
}
add_filter( 'http_request_args', 'delay_label_purchase', 10, 2 );
```

WooCommerce - Handling the label status poll timeouts

---

client/layout/guided-tours/config.js
client/layout/guided-tours/tours/activity-log-tour.js

Fixes https://github.com/Automattic/jpop-issues/issues/1141
This tour can be seen by going to 
http://calypso.localhost:3000/stats/activity/URCOOLSITE.TLD?tour=activityLogTour

Activity Log: add guided tour

---

config/production.json

This enables MailChimp integration in production.
Big **Thank You**:
@kellychoffman, @timmyc, @justinshreve, @allendav, @jameskoster 
I hope that I have not forgotten anyone :)

Store: Enable MailChimp in production.

---

config/stage.json

Let's keep this handy since we'll need it soon.

Disconnect Survey: Enable in staging

---

config/production.json

Enables the WooCommerce Services plugin UI in production.

WooCommerce - enabled WCS in prod

---

client/blocks/comment-detail/comment-detail-header.jsx
client/blocks/comment-detail/index.jsx

Fixes #18973 
This PR fixes the relative time calculations to use the user's timezone.
| --- | --- |
| ![screen shot 2017-10-30 at 13 12 25](https://user-images.githubusercontent.com/233601/32181952-5a8b513a-bd74-11e7-8ce9-fcf2d70bc0b0.png) | ![screen shot 2017-10-30 at 13 13 04](https://user-images.githubusercontent.com/233601/32181961-61544440-bd74-11e7-9596-31a3b8561b40.png) |

Comments: the relative date calculations now uses the user timezone.

---

config/production.json

Store: Enable Stripe Connect on production

---

client/lib/accept/dialog.jsx

See https://github.com/Automattic/wp-calypso/pull/19000#discussion_r148317032 for details.
Going to fix part of #18926.

Components: Remove isMounted() from `lib/accept`

---

bin/codemods/README.md

- Instructs where to put new codemod files
- Gives a stub to start with
- Links to brilliant [astexplorer.net](http://astexplorer.net/) (kudos @ockham ✨ )
I've been working on a codemod and found AST explorer to be especially useful. 💯  Everyone should know about it.

Codemods: add howto instructions to readme

---

client/my-sites/site-settings/disconnect-site/disconnect-survey.jsx
client/my-sites/site-settings/disconnect-site/index.jsx
client/my-sites/site-settings/disconnect-site/missing-feature.jsx

Addresses @rachelmcr's feedback at p7rd6c-15q-p2#comment-1799.
This is part one, with trivial (and hopefully uncontroversial) fixes.

Jetpack Disconnect: Small fixes

---

client/my-sites/stats/activity-log-day/index.jsx

In #19314 we updated the rendering logic to split apart the act of
classifying events from the act of rendering those events.
In that PR we split the list into three parts: those events occurring
long before a rewind dialog might be open, the event immediately above
the dialog, and those events after the dialog.
This model ended up not being a perfect fit since we're adding in the
download link dialog for when people want to grab a backup file for
their site.
In this PR we're thus altering the model such that the classifier
function is returning a bit more information about the events and
instead of encoding the data implicitly (in the shape of three sublists)
we're returning each log item in a _tagged list_ where the first item in
each pair (each list item) is the tag specifying any …

Rewind: Refactor activity log event classifier

---

docs/guide/hello-world.md

I was going through the hello world tutorial to start familiarizing, and noticed this -- a tiny thing, but since the rest of the middleware is described, it seemed confusing to omit a brief description of what's happening with `controller.navigation` as well.
cc @mtias

Hello World: Clarification

---

client/state/selectors/get-privacy-policy-by-entity.js
client/state/selectors/index.js

This PR adds a simple state-selector related with the Privacy Policy implementation. Please take a look to #18980 for more information about this.

PrivacyPolicy-TOS: add state selector

---

client/my-sites/stats/activity-log/index.jsx

Previously in the `<ActivityLog />` we were both disptching app-actions
on things like dialog button clicks and also analytics actions, even
though those actions were intrinsically linked to the Redux actions.
In this PR I have extracted the analytics code into `connect()` so that
it can remain an ancillary detail to the UI instead of an intrinsic
detail of it.
There should be no functional or visual changes with this PR.
**Testing**
Open up a site with activity log items (Pressable site) and navigate
to **My Sites** > **Stats** > **Activity**. Testing is for metrics related
to the rewind dialog. One tracker should go out for opening the rewind
dialog, closing it, and confirming a restore operation.
You should see a call to `t.gif` at pixel.wp.com for the tracking. Verify
that the …

Rewind: Move analytics calls into connect()

---

npm-shrinkwrap.json
package.json

Reverts Automattic/wp-calypso#19366

Revert "i18n-calypso: upgrade i18n-calypso for React 16 compat (#19358) take2"

---

client/blocks/post-item/style.scss
client/my-sites/post-type-list/post-type-post-author/style.scss
client/my-sites/post-type-list/post-type-site-info/style.scss

This PR is behind a feature flag for the posts list (`posts/post-type-list`), will affect live code for custom post types, and is part of a larger epic (p8F9tW-vh-p2).
| Scenario | Before | After |
|--|--|--|
| Small viewport | ![post-item-styling-small-before](https://user-images.githubusercontent.com/227022/32480627-b09ca82e-c3ca-11e7-80a4-650a87f69fc7.png) | ![post-item-styling-small-after](https://user-images.githubusercontent.com/227022/32480626-b058c8ca-c3ca-11e7-851d-91bc3570713e.png) |
| Large viewport | ![post-item-styling-large-before](https://user-images.githubusercontent.com/227022/32480624-afb5a37a-c3ca-11e7-80da-bf15a9b31bcc.png) | ![post-item-styling-large-after](https://user-images.githubusercontent.com/227022/32480625-b013ea84-c3ca-11e7-8b07-dbf032899e4c.png) |

PostTypeList: Improve display of long site titles and author names

---

client/components/happychat/composer.jsx

Fixes https://github.com/Automattic/happychat/issues/923

Throttle typing action

---

client/my-sites/stats/activity-log-day/index.jsx

This PR decouples tracking code from UI interactions.
Keep Redux extension visible in Dev Tools and expand a day.
An `ANALYTICS_EVENT_RECORD ` action should be fired.

Activity Log: move tracking to connect

---

client/state/activity-log/actions.js

Should need no real review or testing here - just updating a typo in docs

Fix typo in @typedef

---

client/components/domains/transfer-domain-step/index.jsx
client/components/domains/transfer-domain-step/style.scss

Style the Transfer Step per designs:

Domains: Transfer-In Step styling

---

client/my-sites/comments/comment-list/comment-list-header.jsx
client/my-sites/comments/style.scss

Fixes #19586
Update the post view header from the simple post title to "Comments on ${ postTitle }", and style the post title in serif font.

Comments: Update post view header copy and style

---

client/layout/guided-tours/tours/simple-payments-end-of-year-guide.js

This addresses a concern expressed here: https://github.com/Automattic/wp-calypso/pull/19465#issuecomment-343829655

Simple Payments: Update copy for the end-of-year guided tour

---

config/production.json

Waiting for #19295.
This PR releases Just In Time Messages to Production

Release JITMs to Production

---

client/components/pagination/pagination-page.jsx
client/components/pagination/style.scss
client/extensions/woocommerce/style.scss

Also removes Store-specific styling which is no longer required.
SegmentedControl:
Pagination:

Update pagination styling to match SegmentedControl

---

client/components/domains/transfer-domain-step/index.jsx
client/lib/domains/index.js
client/my-sites/domains/domain-management/controller.jsx
client/my-sites/domains/domain-management/domain-management.jsx
client/my-sites/domains/domain-management/edit/transfer-in.jsx.js
client/my-sites/domains/domain-management/list/index.jsx
client/my-sites/domains/index.js
client/my-sites/domains/paths.js

We want to make sure both mapping and transfer functions properly
if we have a domain mapped and someone is now transferring it to us.
Test:
- Map a domain
- create a transfer-in
- Make sure both are displayed
- Make sure both show the proper screen when clicked

Domains: Show both transfer/mapping subs in domain management 

---

config/production.json

Checkout: Launch Giropay and Bancontact in production

---

client/my-sites/domains/components/domain-warnings/index.jsx

Use proper link for transfer in notices.

Domains: Fix the transfer warning link

---

npm-shrinkwrap.json
package.json

Changelog: https://github.com/moment/moment/blob/develop/CHANGELOG.md
To test:
* Verify that tests pass
* Try some parts of Calypso that depend on `moment.js`, e.g. setting post date, and verify that they still work as before.

Framework: Update moment.js to 2.19.2

---

config/stage.json

This PR enables Store NUX on staging for the second time. First time, we ran into some issues. They were fixed in the last weeks #19668 #19570 #19669.

Store NUX: enable on staging

---

client/blocks/post-item/index.jsx
client/extensions/woocommerce/app/order/order-create/style.scss
client/extensions/woocommerce/app/order/order-details/style.scss
client/layout/guided-tours/tours/simple-payments-end-of-year-guide.js
client/my-sites/post-type-list/post-actions-ellipsis-menu/trash.jsx
client/my-sites/post-type-list/post-actions-ellipsis-menu/view.jsx
client/my-sites/posts/post-list-wrapper.jsx
client/my-sites/types/main.jsx

Results from running `npm run reformat-files`.
Time to do something about these as I keep seeing them popping up when running codemods. :-)
Well, just confirm Prettify transformed whitespace and brackets correctly. :-)

Prettier some files

---

server/api/index.js
server/api/oauth.js
server/boot/index.js
server/build/index.js
server/bundler/babel/babel-loader-cache-identifier/index.js
server/bundler/babel/babel-plugin-transform-wpcalypso-async/index.js
server/bundler/css-hot-reload.js
server/bundler/extensions-loader.js
server/bundler/hot-reloader.js
server/bundler/index.js
server/bundler/loader.js
server/bundler/utils.js
server/config/index.js
server/config/parser.js
server/config/test/__mocks__/fs.js
server/config/validate-config-keys.js
server/devdocs/index.js
server/devdocs/selectors/index.js
server/isomorphic-routing/index.js
server/isomorphic-routing/loader.js
server/lib/analytics/index.js
server/pages/analytics.js
server/render/index.js
server/sanitize/index.js
server/state-cache/index.js
server/user-bootstrap/index.js
server/user-bootstrap/shared-utils.js

PR was created by:
1. `./node_modules/.bin/prettier --write server/**/*.js`
2. using find/replace to separate out format from dependency docblocks
3. few manual fixes
each of those steps is a separate commit

autoformat server files

---

server/api/oauth.js
server/isomorphic-routing/loader.js

Fixes a few linting errors seemingly introduced by prettier being run on server @ #18726 :)

Server: Fix linting issues

---

docs/troubleshooting.md

Add troubleshooting documentation about ENOSPC build error.

Add ENOSPC solution.

---

client/components/domains/domain-suggestion/index.jsx
client/components/domains/domain-suggestion/style.scss

This is a testcase for this https://github.com/Automattic/wp-calypso/pull/19999#issuecomment-346285918

[WIP] Make domain name suggestions tabbable (#19194)

---

client/me/help/help-contact-closed/index.jsx
client/me/help/help-contact/index.jsx

Does what it says on the tin. The closure notice is on now and will expire on Nov 24th at 00:00 UTC.

Update support closure notice to show Thanksgiving closures

---

assets/stylesheets/_components.scss
client/my-sites/checklist/checklist-show/index.jsx
client/my-sites/checklist/checklist-show/style.scss
client/my-sites/checklist/controller/index.jsx
client/my-sites/checklist/onboardingChecklist.js
client/my-sites/checklist/show/index.jsx

Browse to `/checklist/[site slug]`

Add checklist component to checklist route

---

client/extensions/woocommerce/woocommerce-services/views/shipping-label/label-purchase-modal/address-step/suggestion.js
client/extensions/woocommerce/woocommerce-services/views/shipping-label/label-purchase-modal/style.scss
client/extensions/woocommerce/woocommerce-services/views/shipping-label/style.scss

Switched the notice style to informational rather than a warning. Seems more appropriate to me.

Store - Fix label printing notice styles

---

client/components/update-post-status/index.js
client/lib/posts/actions.js
client/lib/posts/test/actions.js
client/my-sites/draft/index.jsx
client/post-editor/controller.js
client/post-editor/editor-delete-post/index.jsx
client/post-editor/post-editor.jsx

Reverts Automattic/wp-calypso#16017

Revert "Framework: Removed sites-list dependency from lib/posts/actions.js"

---

client/signup/steps/about/index.jsx
client/signup/steps/about/style.scss
client/signup/utils.js

I accidentally merged https://github.com/Automattic/wp-calypso/pull/20165 into an old branch instead of merging it into master. This is a duplication of that branch. 
cc @markryall

Process values from site goals V2

---

client/layout/guided-tours/tours/activity-log-tour.js

Updated the Guided Tour copy after a review from @michelleweber (Thanks! 👋 )

Activity Log: update guided tour copy

---

client/extensions/woocommerce/woocommerce-services/state/shipping-label/actions.js

To reproduce:
* open the labels modal
* ensure "Mark the order as fulfilled" checkbox is checked
* purchase the label
* view the console:
This started appearing after the reducer started listening for order update actions and resetting the state.
In this PR, the order fulfilment action is dispatched as the very last. Before, some actions were still dispatched after it, so the reducer and the views were expecting a non-empty state.

WooCommerce Labels - fixed a console error appearing after purchase

---

client/login/controller.js
client/login/magic-login/handle-emailed-link-form.jsx
client/state/login/magic-login/actions.js

This pull request updates the magic login flow to accommodate for a change in the API, which no longer returns the token time.
1. Run `git checkout update/magic-login` and start your server, or open a [live branch](https://calypso.live/?branch=update/magic-login)
2. See D7903-code for additional instructions

Login: Remove now unnecessary token time parameter from magic login flow

---

assets/stylesheets/_components.scss
client/components/share-button/docs/example.jsx
client/components/share-button/index.jsx
client/components/share-button/services.js
client/components/share-button/style.scss
client/devdocs/design/index.jsx

This component helps user share messages on social media.
1. Move to `/devdocs/design` and find `ShareButton` component.
2. Click on any icon.
3. A share window will show up as follows:
cc @markryall @fditrapani

Component: Add ShareButton component.

---

client/post-editor/post-editor.jsx
client/post-editor/test/post-editor.jsx

This pull request seeks to cancel pending autosaves and raw content saves when their effects are otherwise fulfilled. For example, if the user explicitly clicks Save, or Update, or a post explicitly triggers its autosave behavior (i.e. iframe preview), then any pending autosave should be canceled. Similarly, if the user switches editor modes which immediate saves raw content, any pending raw content saves should be canceled.
This may help remedy symptoms of autosaves falsely flagging a post as dirty (#9833), such as the case described at https://github.com/Automattic/wp-calypso/issues/9833#issuecomment-327226158. While it's sensible that these pending actions be canceled to prevent unintended consequences, the autosave behavior itself should be [shortcutting itself …

Editor: Cancel pending actions when fulfilled

---

client/blocks/privacy-policy-banner/privacy-policy-dialog.jsx
client/blocks/privacy-policy-banner/style.scss
config/horizon.json
config/stage.json
config/wpcalypso.json

This patch just enables the privacy policy banner on stage environment.

PrivacyPolicy: enable in stage

---

config/production.json

Closes #20332
To test: N/A ( see #19888 )

Store: Enable enhanced ecommerce google analytics on production

---

client/extensions/README.md

I've added a paragraph that links to a new page on developer.wordpress.com indicating that large plugin authors can get in touch with us for assistance with extension development.

Update Extensions README.md

---

client/components/domains/transfer-domain-step/index.jsx
client/components/domains/transfer-domain-step/transfer-domain-precheck.jsx
client/lib/cart-values/cart-items.js
client/my-sites/checkout/checkout/domain-details-form.jsx
client/my-sites/domains/transfer-domain/index.jsx

Make sure we aren;'t showing the privacy card on domain details form if all domains don't support it.
Dependency: D8558-code

Domains: Use supports_privacy availability response

---

client/my-sites/checkout/checkout-thank-you/header.jsx
client/my-sites/checkout/checkout-thank-you/index.jsx

THank you page is broken if you only buy a non-primary purchase, as we call them. Unbreak, so you still see the thank you page and can go back to your site.

Checkout: If you only bought domain privacy thank you is broken

---

client/login/controller.js
client/login/index.node.js
client/login/index.web.js

To test:
* Verify that on `master` or in `production`, `/log-in/index.php` gives a 500.
* Verify that with this branch, it gives a 404.
* Verify that on this branch, `/log-in/de` gives you a login form in German.

Login: Add Languages Whitelist to Route Definition

---

client/lib/like-store/utils.js

@see #18838
In this PR the like store is updated to use proper module export and
import syntax.
There should be no functional or visual changes with this change.

Update: Use proper exports for like store

---

client/layout/guided-tours/config.js

Activity Log: remove tour until we can ensure the needed elements are in the page

---

client/components/notes-formatted-block/index.jsx

In this change we're adding support for a few
additional types of formatted text.

Notes Formatted Block: Add some additional styling

---

client/components/notes-formatted-block/index.jsx

Just adds a few more styles to the `notes-formatted-blcok`

Notes: Add additional styling to notes-formatted block

---

client/me/notification-settings/reader-subscriptions/index.jsx

This PR refactors `NotificationSubscriptions` to:
* Use Redux analytics instead of `eventRecorder`.
* Remove the `eventRecorder` mixin from this class.
This PR should not introduce any visual changes.
Part of #20053.
To test:
* Go to http://calypso.localhost:3000/me/notifications/subscriptions
* Verify you can observe the right analytics actions being dispatched when:
* Clicking "Use the Reader" link
* Focusing the "Default Email Delivery" field
* Toggling the "Jabber Subscription Delivery" checkbox
* Focusing the "Email Delivery Format" field
* Focusing the "Email Delivery Window" day field
* Focusing the "Email Delivery Window" time field
* Toggling the "Block Emails" checkbox
* Clicking the "Save Notification Settings" button
* Verify everything else on the page …

Me: Use Redux analytics in NotificationSubscriptions

---

client/components/wizard/index.jsx

This PR updates the `Wizard` component to pass the `getBackUrl` and `getForwardUrl` methods to the step components.
This is pretty useful for being able to navigate back/forward within a wizard from within the step itself.
To test:
* You can use #20360 (it contains this PR) and follow its test instructions.

Components: Provide methods for retrieving back/forward URL to Wizard

---

client/my-sites/site-settings/jetpack-credentials/credentials-configured/index.jsx
client/my-sites/site-settings/jetpack-credentials/index.jsx

Remove Restore references in Activity Log settings

---

client/jetpack-connect/controller.js
client/jetpack-connect/index.js

Export named functions rather than an object literal containing them.
1. Ensure the handlers continue to work correctly.
1. Try to find other files importing the controller. I don't believe there are any other than the route definitions (index).

Jetpack Connect: Use named exports from Jetpack Connect controller

---

client/components/domains/domain-search-results/index.jsx

Store NUX: remove possibility to add domain mapping – take 2

---

client/me/account/main.jsx

- is part of a series of PRs aiming to provide support for Color Schemes in Calypso.
- focuses on adding analytics to the color scheme picker on Account settings
The suggested approach in this PR adds tracking for two types of events:
1. `calypso_color_schemes_select` is tracked when the user clicks/browses through the different color schemes. This will allow us to see which color schemes grab the most/least attention, how many color schemes a user views prior to choosing one and more importantly to see how often users view color schemes without actually choosing a new one.
2. `calypso_color_schemes_save` is tracked when the user decides on a new color scheme and saves it as the new default. This will allow us to see which color schemes are most popular and how many users actually choose …

Color Schemes: Add Analytics

---

client/components/domains/domain-transfer-suggestion/index.jsx
client/components/domains/transfer-domain-step/index.jsx
client/components/domains/transfer-domain-step/style.scss
client/components/domains/transfer-domain-step/transfer-domain-precheck.jsx

Updating some copy to clarify a few things around the process and differences/benefits of transfer vs. mapping a domain. Fixes #20346
* `Domains -> Add`
* `Use a domain I own`
* Confirm the screen looks like the screenshot above

Domains: Update copy for incoming transfers

---

client/my-sites/post-type-list/index.jsx

After an update, `PostTypeList` checks scroll position to decide if maybe it should load next page. Do this check asynchronously using `afterLayoutFlush` helper to avoid synchronous layout reflows in the middle of a big React update.
Should result in some performance improvement when displaying a new page of posts.
This PR is very similar to #20016 -- have a look at the discussion there to learn more about this kind of  fix works and how to test it.
1. Set the AB test `condensedPostList` to `condensedPosts`.
2. Go to `/posts/site.slug` for some site with many posts and scroll down to load more pages.
3. Record a profile in Chrome before and after the patch.
Before this patch, you'll find a synchronous reflow inside the React update that happens when a REST API response …

PostTypeList: avoid synchronous reflow when checking scroll position

---

config/production.json

Launch Reader Conversations to everyone.

Reader: launch the reader/conversations feature in production

---

client/lib/cart-values/index.js

Exports were broken for /domains flow.

Cart: Quick export fix for now

---

assets/stylesheets/_components.scss
client/my-sites/comment/main.jsx
client/my-sites/comments/comment-list/index.jsx
client/my-sites/comments/comment-replies-list/index.jsx
client/my-sites/comments/comment-replies-list/style.scss
client/my-sites/comments/comment/index.jsx
client/my-sites/comments/comment/style.scss
client/state/selectors/get-site-comment-parent-depth.js
client/state/selectors/get-site-comment-replies-tree.js
config/development.json
config/wpcalypso.json

Start Calypso with:
```
ENABLE_FEATURES=comments/management/threaded-view npm start
```

Comment: Threaded View experiment

---

npm-shrinkwrap.json
package.json

Update `notifications-panel` to v2.1.2. This adds the checkmark icon and vertical centering for images within notifications.

Notifications: Update `notifications-panel` to v2.1.2.

---

client/lib/abtest/active-tests.js
client/signup/processing-screen/index.jsx

As the variation wins, the A/B test #19618 is closed and the winner is exposed to 100% users.
For more details of the test result, See p9jf6J-3w-p2#comment-125

Signup: button color change on the post signup landing screen

---

client/lib/signup/step-actions.js

The `fetchSitesAndUser` function now only fetches sites into Redux state and stop using `sites-list` at all.
Also adds the `reduxStore` parameter to `createSite`, so that the flows that include the `site` step (`developer` etc) don't stop working.
Can be reviewed and tested now, but we should postpone merging until all places where `sites-list` is read from (at this moment, plugins and posts) are migrated.
Test the signup flow -- does the new site always get created at the end, without hanging during checkout etc?
Test also the `/start/developer` flow and others with the `site` step -- I had to do an extra fix to make them work.

Signup Steps: remove sites-list from fetchSitesAndUser, fetch only into Redux

---

config/wpcalypso.json

For easier testing, as discussed in Slack.

JP Onboarding: Enable in wpcalypso

---

client/state/jetpack-connect/actions.js

Adding a tracks event. Trying to collect some data to make decisions around #20406.

Jetpack Connect: Add tracks event to site request failure

---

npm-shrinkwrap.json
package.json

Updates the `notifications-panel` package to the latest 2.1.3, which includes bug fixes for mentions handling.

Notifications: Update `notifications-panel` to v2.1.3.

---

client/my-sites/checkout/checkout-thank-you/jetpack-thank-you-card.jsx

The `JetpackSite` is a part of the `sites-list` module and will be removed soon. Its functionality can be replaced by:
1. computed attributes returned by the `getSite` selector,i.e., `canManage` property instead of the `canManage()` method.
2. Redux selectors (i.e., `getJetpackSiteRemoteManagementUrl` selector instead of the `getRemoteManagementURL()` method.
Connect a Jetpack site and purchase a paid plan in the process. You will be shown a Jetpack
thank you page:
Verify that everything on this page still works as expected.

Remove JetpackSite class from JetpackThankYouCard

---

config/horizon.json

Enable the Revisions feature in the Post / Page Editor in the Horizon environment.

Editor: Revisions: Activate for Horizon

---

config/production.json

Editor: Revisions: Enable in Production

---

client/components/domains/transfer-domain-step/index.jsx

Show button in busy state when checking availability.
Test:
- Domains -> Add -> User your own domain
- Input something: 'andrija.me'
- Click button/press Enter
- Make sure you see the button in busy state, so it's obvious it's still processing

Domains: Add feedback to transfer step button

---

assets/stylesheets/_components.scss
client/my-sites/checklist/checklist-show/index.jsx
client/my-sites/checklist/checklist-show/style.scss
client/my-sites/checklist/style.scss

When a checklist is complete, we're not showing the sharing message on the checklist screen.
1. Create a new website.
2. Move to `/checklist/NEW_SITE`.
3. Complete all tasks and you should be able to see the congrats message and sharing options as below:
**Tip** If you have React Devtools, you can complete all tasks by checking the items in`siteChecklist/tasks` prop of `ChecklistShow` component.
cc @fditrapani @markryall

Checklist: Show congrats message and sharing options when all tasks completed.

---

client/my-sites/domains/domain-management/edit/index.jsx

When transfer TLD in maintenance, show splash screen.
Test:
- Get a TLD in maintenance
- Start a transfer in for a domain with that TLD
- Open it in Domain Management
- See splash screen for TLD Maintenance.

Domains: Maintenance for transfers

---

client/layout/guided-tours/config.js
client/layout/guided-tours/docs/TUTORIAL.md
client/layout/guided-tours/docs/examples/README.md
client/layout/guided-tours/docs/examples/simple-payments-end-of-year-guide.js
client/state/ui/guided-tours/contexts.js

Deactivate the Simple Payments EOY Guided Tour. 
To test:
- make sure you cannot trigger the Simple Payments EOY Guided Tour anymore
*Note*: please don't merge before Monday, Dec 18 2017. 
/cc @iamtakashi

Simple Payments: deactivate EOY Guided Tour

---

client/lib/abtest/active-tests.js
client/my-sites/checkout/checkout/checkout.jsx

This will affect users in Germany and Belgium.

Checkout: Wrap up ab test and launch Giropay and Bancontact

---

client/components/checklist/checklist-task.jsx
client/components/checklist/style.scss

Every time I look at a task title I want to click on it because it's blue and the phrase is a command. This PR makes the task title clickable and directs user to the same location as the do it button.
* Create a new site
* Visit the checklist by going to the stats and clicking on the view checklist link
* Click on a task title and compare it it's accompanying do it button
@taggon @markryall

Make task title clickable

---

client/blocks/product-purchase-features/product-purchase-features-list/jetpack-backup-security.jsx

Currently we wrongly send user to the VaultPress Dashboard when they don't have access to it.

Plans Page: Fix url for to take users to the activity log instead of VP Dashboard

---

client/state/data-layer/wpcom/sites/jitm/index.js

Sometimes actions are missing a site id -- to investigate later...

JITMs: Bandaid fix for when an action is missing a site id

---

client/state/utils.js

When part of the state tree is deserialized but does not match its schema, some warning messages are shown.  These messages are not very intuitive:  they don't make it easy to tell what part of the state tree is invalid.  Using Chrome, here is the current way to do this:
> <img src="https://user-images.githubusercontent.com/227022/34235960-19a0a220-e5c3-11e7-8c30-778c888efd26.png" width="579">
It would be nice if we could show the full path to the part of the state tree that is failing validation.  However, the state validation mechanism is usually [called from within `createReducer`](https://github.com/Automattic/wp-calypso/blob/f751e73/client/state/utils.js#L206) which only operates on a specific branch of the state tree.  I'm not aware of a way to get Redux to tell us which part of the …

Framework: Improve state validation error messages

---

client/jetpack-connect/authorize-form.jsx
client/jetpack-connect/test/__snapshots__/auth-logged-out-form.js.snap
client/jetpack-connect/test/__snapshots__/authorize-form.js.snap
client/jetpack-connect/test/lib/authorize-form.js
client/jetpack-connect/utils.js

This functionality is not currently implemented tracks-side. Remove it.
See p1513846376000312-slack-nosara-tracks /cc @bperson
/cc @AnnaMag 
Supersedes #20471

Remove anonymous tracks from Jetpack Connect

---

client/my-sites/comments/comment/comment-author.jsx
client/my-sites/comments/comment/comment-content.jsx
client/my-sites/comments/index.js
config/desktop.json
config/development.json
config/horizon.json
config/production.json
config/stage.json
config/wpcalypso.json

Depends on #20972.
This PR removes the single comment view feature flag and related code.

Comments: remove comment view feature flag.

---

client/me/purchases/cancel-purchase/index.jsx

If domain transfer is not canelable with refund send user to manage purchase screen, where they can remove the purchase.
Finally tracked this sucker down. 
Test:
- Buy a transfer bundled with plan
- Go to transfer
- Click Cancel Transfer
Before: you'd see this 
After:
- Should end up at manage purchase screen

Domains: Redirect to manage purchase if domain transfer not refundable

---

client/my-sites/site-settings/theme-setup-dialog/index.jsx

Theme setup dialog: fix typo

---

config/desktop.json
config/production.json

This is the soft launch of the free photo library.

Free photo library: enable on production and desktop

---

client/blocks/post-likes/README.md
client/blocks/post-likes/index.jsx
client/blocks/post-likes/style.scss
client/state/posts/likes/reducer.js
client/state/posts/likes/test/reducer.js

Reverts Automattic/wp-calypso#21082

Revert "Post likes popover: link to Reader"

---

client/me/purchases/purchase-item/index.jsx

It turns into an annual subscription once complete.

Purchases: Remove "Never Expires" for transfers

---

client/lib/products-values/index.js

Needed to add a dependency for the transfer product, so the privacy gets auto removed.
Test:
- Add a transfer with privacy to cart
- Remove transfer
- Make sure privacy removed as well

Domains: Remove privacy for transfer when transfer removed

---

client/blocks/post-item/index.jsx
client/blocks/post-item/style.scss
client/my-sites/post-type-list/post-thumbnail.jsx
client/my-sites/post-type-list/post-type-post-author/style.scss
client/my-sites/post-type-list/post-type-site-info/style.scss
client/my-sites/post-type-list/style.scss

Reverts Automattic/wp-calypso#21294

Revert "Post List: increase click-ability of post item"

---

client/components/chart/index.jsx

The stats chart and its children account for much of the performance
bottlenecks we have seen in Calypso in the past few months. These
bottlenecks are larelgy related to a number of things which can be hard
to track down including garbage collection churn and layout reflows.
Garbage collection churn is a result of creating too many copies of data
in memory when rendering and layout reflows are due to calculating
properties like `clientWidth` on specific DOM nodes.
In this patch we're choosing to only update data passed to the `Chart`
component when that data (or the browser width) changes. Previously this
was done on every render but now it's done in response to the external
changes only with the values stored in state.
http://iscalypsofastyet.com/branch?branch=update/stats-chart-component …

Stat Chart: Introduce optimizations

---

client/state/test/utils.js
client/state/utils.js
npm-shrinkwrap.json
package.json

This PR improves messaging produced by state schema violations. These changes are only applied when _not in_ production environment.
1. Use `greedy` mode to continue validation after an error is encountered. This may produce several violations at once.
1. Use `verbose` mode to get `schemaPath`, allowing us to point to the specific rule violated.
1. Some formatting updates.
Example message (from console test output):
```
State validation failed.
State: { jank: 'y', isAuthorizing: 'maybe' }
data.timestamp is required
Found: { jank: 'y', isAuthorizing: 'maybe' }
data has additional properties
Found: 'data.jank'
data.isAuthorizing must be an enum value
Found: 'maybe'
Violates rule: { type: 'string', enum: [ 'a', 'b', [length]: 2 ] }
```
* Create a schema violation and observe it in the …

State: Improve schema violation warning

---

client/components/site-title/docs/example.jsx
client/devdocs/design/index.jsx

To increase visibility.
To test:
Navigate to http://calypso.localhost:3000/devdocs/design/site-title-control, enter some text in both fields.

SiteTitleControl: Add to Devdocs

---

.github/stale.yml

There are some issues that we'll want to keep open without auto-closing. Use `[Status] Keep Open` for that.
/hat tip @gibrown

Add a stalebot exception for `[Status] Keep Open`

---

client/my-sites/controller.js

When a single-site user navigates to the `/stats/day` page, the `siteSelection` handler is supposed to redirect to `/stats/day/primary.site.slug`. "All Sites" views are not shown for single-site users.
This works when the sites data is already available in Redux state and the redirect is performed synchronously.
It's broken, however, when the sites data is still loading (can be simulated by clearing local storage and navigating to `/stats/day`). Then the redirect is supposed to be scheduled asynchronously using the `SITES_ONCE_CHANGED` action. But it redirects first to `/stats/day/undefined` and then to `/stats/day/undefined/primary.site.slug`, showing an empty screen instead of the desired stats.
Why? Because the `redirectToPrimary` function uses the `primary` value from the closure and …

Fix redirect to primary site for single-site user

---

client/components/site-title/README.md

This space intentionally left blank.

SiteTitleControl: Add README.md

---

client/extensions/woocommerce/app/dashboard/index.js
client/extensions/woocommerce/app/dashboard/required-plugins-install-view.js
client/extensions/woocommerce/app/dashboard/setup-footer.js
client/extensions/woocommerce/app/dashboard/store-location-setup-view.js
client/extensions/woocommerce/components/address-view/index.js
client/extensions/woocommerce/components/form-location-select/states.js
client/extensions/woocommerce/components/query-locations/index.js
client/extensions/woocommerce/lib/countries/index.js
client/extensions/woocommerce/state/sites/locations/selectors.js
client/extensions/woocommerce/state/sites/locations/test/selectors.js
client/extensions/woocommerce/state/sites/settings/actions.js

Fixes #20877 
Work in progress

Store: Support nonUS nonCA store setup and redirect to WooCommerce Setup Wizard

---

.github/stale.yml

There are some issues that we'll want to keep open without auto-closing—adding `OSS Citizen` to that list. /hat tip @bazza
Also, fixed a typo in the message. /hat tip @jeremeylduvall

Add a stalebot exception for `OSS Citizen`

---

client/components/domains/registrant-extra-info/test/index.js
client/components/domains/registrant-extra-info/test/uk-form.js
client/components/domains/registrant-extra-info/test/with-contact-details-validation.js
client/components/domains/registrant-extra-info/uk-form.jsx
client/components/domains/registrant-extra-info/uk-schema.json
client/components/domains/registrant-extra-info/with-contact-details-validation.jsx
client/lib/wpcom-undocumented/lib/undocumented.js
package.json

This PR adds validation for the uk tld form, using a JSON Schema added to Calypso (for now).
Stacked on https://github.com/Automattic/wp-calypso/pull/20750

[WIP] Add uk validation

---

client/state/reader/feeds/schema.js

This PR fixes an invalid schema currently in use.
The invalid schema was exposed by #21125
Previously, invalid schemas were silently permitted with undefined behavior.
I have corrected the schema, but have no knowledge about its usage or correctness. Review is requested based on history to verify that the valid schema works as expected.
Related: #21044 and #21020

Schema: Fix invalid reader/feeds schema

---

docs/testing/component-tests.md
docs/testing/testing-overview.md

I noticed one type and one section that can be moved to the related document when reviewing #21212.

Docs: Add small tweaks to the existing testing docs

---

client/jetpack-connect/main.jsx

In the mobile app connection flow, if a site is already connected, redirect back to the mobile app immediately instead of the plans page. Purchase pages should never be shown in mobile app webviews.
For more info on the jetpack connect mobile app flow, see #20955.
* Connect a dotorg site at http://calypso.localhost:3000/jetpack/connect
* Set debug in browser console: `localStorage.setItem( 'debug', 'calypso:jetpack-connect:*' )`
* Start the jetpack connection flow, passing the arg `mobile_redirect` for example:
`http://calypso.localhost:3000/jetpack/connect?mobile_redirect=wordpress://jetpack-connection`
* Attempt to connect the same site as in the first step
* Alternatively, pass the original site in the url, like:
`http://calypso.localhost:3000/jetpack/connect?mobile_redirect=wordpress:/ …

Jetpack connect: Redirect back to app if site already connected

---

client/jetpack-onboarding/steps/summary.jsx

This PR updates the Summary step to display accurate completion information for each of the steps. 
Note that we still don't fetch the actual state from the site, so this will currently only rely on what the user sets in the current session. Work to retrieve the current onboarding state is in progress in #21013, https://github.com/Automattic/jetpack/pull/8497, https://github.com/Automattic/jetpack/pull/8461 and D9099-code, and after these land, we'll need to create a query component and load it when we start the onboarding flow. 
Uses a new selector from #21438.
Preview:
To test:
1. Checkout this branch on your local Calypso.
1. Make sure your JP sandbox is running the latest Jetpack master.
1. Go to https://YourJetpackSandbox.com/wp-admin/admin.php?page=jetpack&action=onboard&calypso_env= …

Jetpack Onboarding: Dynamic step progress in Summary step

---

client/extensions/woocommerce/app/settings/email/email-settings/index.js
client/extensions/woocommerce/app/settings/email/index.js

This adds email settings under the not saved settings umbrella.
Go to settings/email make some change, do not click Save button, try to leave the settings page.

Warn user when un-saved changes exist.

---

client/state/privacy-policy/schema.js

This PR fixes an invalid schema currently in use.
The invalid schema was exposed by #21125
Previously, invalid schemas were silently permitted with undefined behavior.
I have corrected the schema, but have no knowledge about its usage or correctness. Review is requested based on history to verify that the valid schema works as expected.
Related: #21044 and #21020

Schema: Fix invalid privacy-policy schema

---

client/state/signup/dependency-store/schema.js

This PR fixes an invalid schema currently in use.
The invalid schema was exposed by #21125
Previously, invalid schemas were silently permitted with undefined behavior.
I have corrected the schema, but have no knowledge about its usage or correctness. Review is requested based on history to verify that the valid schema works as expected.
Related: #21044 and #21020

Schema: Fix invalid dependency-store schema

---

client/my-sites/importer/importing-pane.jsx

With our work on improving the import experience, we've reduced the amount of time imports take. 
The message needs to be updated to better represent that.

Imports: Improve message about how long an import might take

---

client/my-sites/people/controller.js
client/my-sites/people/index.js
client/my-sites/people/people-invites/index.jsx
client/my-sites/people/people-section-nav/index.jsx
config/development.json

This PR creates a new subsection for invites in the people section. The section is behind a feature-flag and is intentionally incomplete.
See: p3Ex-32O-p2

Invites: Add new Invites subsection to People

---

client/components/site-title/README.md
client/components/site-title/index.jsx

Required for #21598.
To test: Verify that http://calypso.localhost:3000/devdocs/design/site-title-control still works

Site Title Control: Add disabled prop

---

client/blocks/post-share/index.jsx
client/post-editor/editor-sharing/publicize-message.jsx
client/post-editor/editor-sharing/publicize-options.jsx

Closes #19630
Also fixes https://github.com/Automattic/jetpack/issues/8134
Suggestions are welcome :)

increased twitter length to 280

---

config/horizon.json
config/stage.json
config/test.json

This PR enables the Jetpack Onboarding flow in all testing and staging environments.

Jetpack Onboading: Enable in test and staging envs

---

client/layout/masterbar/notifications.jsx

http://iscalypsofastyet.com/branch?branch=try/async-notifications

Make notifications load async

---

client/blocks/reader-feed-header/style.scss
client/blocks/reader-site-notification-settings/index.jsx
client/blocks/reader-site-notification-settings/style.scss

This PR:
- Adds bell icon to Post Notifications.
- Adds dividers between popover options.
- Fixes Settings button minor misalignment.
Fixes #19091.
**Before:**
**After:**

Reader: Update Post Notifications popover UI

---

client/state/data-layer/wpcom/sites/rewind/schema.js

This PR fixes an invalid schema detected by a method proposed #21509.
1. Visit https://www.jsonschemavalidator.net/
1. Copy the draft-04 schema and paste it into the left (the validation schema): https://raw.githubusercontent.com/json-schema-org/json-schema-spec/d4c5b3a2924370c51b710c8bfd81d3644a92766e/schema.json
1. Paste the modified schema from this PR into the right (data to be validated, see below).
1. Validation should pass
1. Verify that the schema behaves as expected. Behavior with invalid schemas in undefined.
The schema in this PR is "deconstructed", which is nice clean JavaScript, but it must be "reconstructed" into a complete JSON schema in order to be used. The following is the reconstructed version:
```
{
"oneOf": [
{
"type": "object",
"properties": {
"state": {
"type": …
```

Fix invalid rewind schema

---

client/lib/purchases/assembler.js

Fixes #20892 (see that for testing instructions)
**Before:** 
**After:**

My Purchases: fix display of CC number with leading zeros

---

client/me/concierge/README.md

Add readme to document concierge flows. More context in 482-hg-gh
Code review only.

Add readme

---

client/lib/analytics/ad-tracking.js

Changed value from 36622 to 195308.
That's all.

Analytics: updated linkedInPartnerId value

---

config/desktop.json
config/production.json
config/stage.json

Now featuring the New Post notifications toggle and some microcopy

Reader: Release the new post notifications toggle to production

---

client/lib/support/support-user/localstorage-bypass.js
client/lib/user/support-user-interop.js

This PR prevents support token to be cleared on refresh. More information, testing instructions and security concerns here: p7jreA-1sg-p2

Support: support token survives refresh

---

client/blocks/payment-methods/index.jsx
client/lib/abtest/active-tests.js

The test is successful, launching for everybody.

Plans: Wrap up the test on payment methods display

---

client/lib/plans/constants.js

Adds the new Jetpack Search feature to the list of signup plans for Jetpack Professional/Business.

Add search to Professional plan features list

---

client/my-sites/site-settings/search.jsx

Fixes #21711
Show Search options for Atomic and VIP Go sites on Business or Enterprise plans, as well as Jetpack sites on a Professional plan.

Show Search options for Atomic sites

---

client/my-sites/controller.js

Temporary fix for pbg9X-cvt-p2#comment-51126

Sites: filter out recent sites if we do not own them

---

client/state/data-layer/wpcom/activity-log/rewind/to/index.js
client/state/data-layer/wpcom/sites/rewind/index.js

This will keep our local copy of the "State machine" up to date and help
us to see the progress of running Rewind operations.

Rewind: Poll for updates to `/rewind` when running a Rewind operation

---

client/components/data/query-site-stats/index.jsx

When loading the `/stats/day` page, Calypso sends two duplicate requests to the `sites/:site_id/stats/country-views` endpoint. That's because we're rendering `QuerySiteStats` twice with the same query: once in `<StatsModule statType=""statsCountryViews"/> and a second time in `<GeoChart>` inside it.
That should be prevented by the `if ( ! requesting )` check in `QuerySiteStats`, but it isn't.
The sequence of events is:
1. `mapStateToProps` of the 1st component is called, `requesting` is false
2. `mapStateToProps` of the 2nd component is called, `requesting` is also false
3. `cmpDidMount` of the 1st component is called, `this.props.requesting` is false, therefore starts to dispatch request action
4. the `requesting` flag in Redux state is set to `true`, `mapStateToProps` of both query …

Avoid duplicate stats requests by refactoring the QuerySiteStats component

---

client/components/rewind-credentials-form/index.jsx

This PR updates this label so it describes better what should user enter in this field.

Rewind: reword Upload Path label

---

server/pages/index.pug

Followup to #21963
Use whatever w.js using to generate the random token for `load_id`

Update random load id generation to use whatever w.js using

---

client/components/button/docs/example.jsx
client/components/button/style.scss

Button - added primary styles for borderless buttons

---

client/me/purchases/remove-purchase/index.jsx

This allows us to segment plan cancelations for Atomic sites

Atomic: add isAtomic to plan removal stats

---

client/me/purchases/remove-purchase/index.jsx

Convert to snake case so tracks will accept the stat

Atomic: update isAtomic stats prop

---

config/stage.json

This enables the onboarding checklist in the staging environment

enable checklist in staging

---

config/production.json

This PR will enable the onboarding checklist feature on wordpress.com

Enable onboarding checklist in production

---

.github/stale.yml

Update message to include information about how to keep an issue alive.
/hat tip @akirk and @benhuberman

stale[bot] - update stalebot message

---

client/extensions/zoninator/package.json

This PR enables the Zoninator extension on production.  
Depends on #21869.

Extensions: Zoninator - Enable Zoninator extension on production

---

client/my-sites/checkout/checkout/checkout.jsx

In some edge cases, the G Suite upsell shows twice in a domain purchase flow. This PR will check the domain registration context in the cart to solve the problem.
1. Set the `gsuiteUpsellV2` test to `show`.
**The all below process should end within 30 mins to get the accurate test result.**
2. Create a new website on the free plan.
3. Move to `/domains/manage/YOUR_SITE_DOMAIN` and buy a new custom domain.
4. When you complete the checkout transaction, the G Suite upsell should *NOT* show up.
cc @fditrapani @klimeryk

Signup: Fix: Prevent the G Suite upsell from showing twice.

---

client/me/concierge/index.js
config/development.json
config/stage.json

**Do not merge this until we launch the concierge project**
This removes the concierge feature flag and also points the all the environments to the production schedule.
**More context 561-gh-gh**
Only code review.

Enable concierge in all environments and point production schedule

---

client/components/notice/notice-action.jsx

See: https://dev.to/ben/the-targetblank-vulnerability-by-example
Props @debhal.

Notices: add noopener noreferrer anti-phishing to notice actions

---

client/components/translatable/test/proptype.js

Adding some working example tests to support #21917

Translatable: PropType for "translatable strings" unit tests

---

client/components/rewind-credentials-form/index.jsx
client/my-sites/site-settings/jetpack-credentials/credentials-configured/index.jsx
client/state/data-layer/wpcom/sites/rewind/schema.js

There's no support in the transport server for sftp, so we probably don't need it as a selectable option

Remove SFTP as an option when configuring backup creds

---

client/my-sites/stats/activity-log-switch/index.jsx
client/my-sites/stats/activity-log-switch/style.scss

Rewind: update flow initiator styling to match WordPress.com thank you page

---

client/components/domains/example-domain-suggestions/index.jsx
client/components/domains/register-domain-step/index.jsx

If transfer in allowed, use transfer in link.

Domains: Already own domain suggestion link

---

client/components/domains/domain-search-results/index.jsx
client/components/domains/register-domain-step/index.jsx
client/lib/abtest/active-tests.js

This is a mirror of the test run on tortuga here:
p8kIbR-c9-p2

Domain Suggestions: Add signup ab test

---

client/components/domains/domain-search-results/index.jsx
client/components/domains/register-domain-step/index.jsx
client/lib/abtest/active-tests.js

Updated this code to only hide the exact match box when the domain is available and will be in the results data set.

Domain search ab test

---

npm-shrinkwrap.json
package.json

Update to the newest notifications release, [v2.1.5](https://github.com/Automattic/notifications-panel/releases/tag/2.1.5), which is only some style fixes.
**Testing**
- Load this branch, and restart Calypso.
- Make sure there are no related errors in the console, and that [new post notifications look correct](https://github.com/Automattic/notifications-panel/pull/224).

Update `notifications-panel` to v2.1.5.

---

client/state/data-layer/wpcom/sites/rewind/schema.js

Previously the arrangement of `oneOf` and the associated state
schemas was leaving us with no context when `is-my-json-valid`
parsed an invalid payload because none of the top-level `oneOf`
items validated.
In this rearrangement we're doing some seemingly wacky things
to invert the logic and end up with better messaging: namely
that we will get the branch it was trying to validate when
it failed.
For instance, if the `last_updated` value is invalid but
everything else in the `active` state is valid then before
this change all we would know is that the entire payload
is invalid. After this change we'll be able to know that
it was parsing the `active` state when we failed and that
helps us narrow down the debugging.
Props to @deBhal for the advice to flip `oneOf` to `anyOf`
with the …

Rewind: Rearrange `/rewind` schema for better parse failure errors

---

client/lib/two-step-authorization/index.js

In order to investigate better issues related to expired 2FA, more data is required.

Analytics: track 2fa events in tracks as well

---

client/lib/abtest/active-tests.js
client/my-sites/checkout/checkout/checkout.jsx

As the modified version wins [the A/B test](https://github.com/Automattic/wp-calypso/pull/21068), this PR will roll out the winner to all users.
Follow [the instruction](https://github.com/Automattic/wp-calypso/pull/19134) except for the first step. You don't need to activate any tests.
cc @fditrapani

Signup: Roll out the G Suite upsell to all users.

---

.github/stale.yml

Whoops. Fix the formatting in the message so bulleted lists and paragraphs display correctly.

stale[bot] - fix stalebot message formatting

---

client/state/reader/streams/test/reducer.js

This patch improves the part of the test that checks the reducer persistence behavior. The persistence really works only on the combined reducer returned from `combineReducers`. The individual reducers don't do any schema validation on their own -- they only have a `schema` property that `combineReducers` uses.
I updated the test to work with the real implementation of the full reducer, not with some other one where we can only hope that it matches exactly the real one.
Remove the `withSchemaValidation` calls from the tests and test the full reducer instead.
My main motivation for this change was that I'd like to stop supporting a `null` schema argument to `withSchemaValidation` -- and this patch enables that option. (`selected.schema` is undefined)
The change is …

Improve test of Reader streams reducer

---

client/my-sites/checkout/checkout-thank-you/header.jsx
client/my-sites/checkout/checkout-thank-you/index.jsx

Domains: Update Thank You Pages copy for transfers

---

client/state/post-types/reducer.js
client/state/post-types/test/reducer.js

Use the HoR wrapper instead of manually implementing the DESERIALIZE handler.

Rewrite the postTypes reducer to use withSchemaValidation

---

assets/stylesheets/shared/_color-schemes.scss
client/layout/sidebar/style.scss

Sidebar: Increase contrast of icons, labels, and buttons

---

client/my-sites/checkout/checkout-thank-you/header.jsx
client/my-sites/checkout/checkout-thank-you/index.jsx
client/state/domains/actions.js

Add tracking for NUX transfers to thank you pages.

Domains: Add tracking for NUX transfers

---

client/components/domains/domain-search-results/index.jsx
client/components/domains/register-domain-step/index.jsx
client/lib/abtest/active-tests.js

this depends on D10221-code to work.

Add a new test group to the domain search test

---

assets/stylesheets/shared/_color-schemes.scss
client/layout/sidebar/style.scss

Sidebar: Increase general contrast

---

client/state/utils.js

80% of JSON schema validations when deserializing state from Indexed DB check a value that's just serialized initial state of the reducer. In this case, we can take a shortcut and make the deserialization on initial load 2.5 times faster.
This PR is the final one in the series of recent schema validation refactorings. Their goal was to move all schema validation to function `withSchemaValidation`. And this function is now being optimized.
Before we started this project, there were 181 JSON schema validations during persisted state load, and the load took 152ms: 
That's quite a big percentage of JS execution time during initial load, as the total time to evaluate the `build` chunk and do the initial render is ~650ms.
Then it was partially optimized as the schema validations were moved to …

Schema validation on deserialize: take a shortcut when equal to initial state

---

config/README.md

See p4TIVU-7YE-p2
Add instructions on how to test feature flags on any environments via query parameters.

Config: Update the docs with info about testing flags via query parameters

---

client/state/selectors/test/get-jetpack-remote-install-error.js

No visual or functional differences.
Missed commit from #22555.

JP Remote Install: Minor unit test tweak

---

client/my-sites/themes/theme-showcase.jsx
client/my-sites/themes/themes-banner/random-themes-banner.jsx

This PR implements the Small Business and Photo Blog banners.
To test, go to _My Sites > Themes_. The banner is shown above the search bar.
See #21983

Implement Theme Showcase Banners

---

client/blocks/reader-full-post/index.jsx
client/reader/stats.js

currently breaking on site_ID: 1.
**testing instructions**
go to: http://calypso.localhost:3000/read/feeds/77164643/posts/1724351807

Reader Stats: pageViewForPost should be safe

---

client/jetpack-onboarding/main.jsx
client/jetpack-onboarding/steps/business-address.jsx
client/jetpack-onboarding/steps/contact-form.jsx
client/jetpack-onboarding/steps/homepage.jsx
client/jetpack-onboarding/steps/site-title.jsx
client/jetpack-onboarding/steps/site-type.jsx
client/jetpack-onboarding/steps/stats.jsx
client/jetpack-onboarding/steps/woocommerce.jsx

Needed for #22775 -- will make things a lot easier there.
To test: Verify that JPO still works.

JP Onboarding: Pass saveJetpackOnboardingSettings action prop from Main

---

client/lib/cart-values/cart-items.js
client/lib/signup/step-actions.js

Reverts Automattic/wp-calypso#22600

Revert "Domains: Check for privacy support before adding subscription to cart."

---

client/components/tinymce/plugins/contact-form/style.scss

Fixes: #22445 
Replaced fixed offsets with dynamic height.
This button looks to be the only one that uses this class.

Vertically center edit icon at different heights

---

config/README.md

Some corrections.  Follow-up to #22590.

Config: Update docs for `?flags=` parameter

---

client/my-sites/plan-features/summary.jsx

gurantee > guarantee
Props @markx2

Fix spelling

---

client/state/selectors/test/get-jetpack-onboarding-pending-steps.js

Broken by #22775. Let's merge this before anyone notices 😛

JP Onboarding: Fix failing getJetpackOnboardingPendingSteps() unit test

---

client/me/reauth-required/index.jsx

This PR refactors `ReauthRequired` to use Redux analytics instead of `eventRecorder`.
This PR should not introduce any visual or behavioral changes.
Part of #20053.
To test:
* Make sure your ga debug is enabled: `localStorage.debug = 'calypso:analytics:ga,calypso:analytics:utils'`
* Using Chrome, in the developer tools, go to Application > Cookies and delete the `twostep_auth` cookie for the `public-api.wordpress.com` domain.
* Go to http://calypso.localhost:3000/me/security/two-step or any other page that may require a fresh 2fa token and you'll be presented with the reauth dialog.
* Verify the right event is being dispatched when:
* Clicking the **Not You? Sign Out** link.
* Focusing the **Verification Code** field.
* Toggling the **Remember for 30 days** …

Me: Update ReauthRequired to use Redux analytics

---

client/reader/sidebar/_style.scss

Reader: Update sidebar tags/lists colors

---

assets/stylesheets/shared/functions/_z-index.scss
client/components/list-end/index.js
client/components/list-end/style.scss
client/reader/_style.scss

List End: Replace Noticon with Gridicon

---

client/reader/sidebar/_style.scss

Reader: Align delete icon in Tags

---

npm-shrinkwrap.json
package.json

Updates the moment library from 2.19.2 to 2.21.0
Full regression test to make sure everything still works

Framework: upgrade moment library to 2.21.0

---

client/my-sites/draft/index.jsx

After the post actions UI was removed from the Draft component in #20652, there remains a lot of unneeded code that was used to implement these actions, maintain the popover menu state, display errors etc. This PR removes all that.
Among others, it removes usages of `lib/posts/actions` module that we plan to remove soon (because it's Flux).
Have a site with a few drafts and open the drafts popover from the masterbar (the "count" marker inside the "Write" button). Does it still work as before?

Remove unneeded code from the my-sites/drafts component

---

README.md

The existing graphic on the readme file was very outdated. This updates the graphic to something that represents Calypso as it currently exists today.

Update README.md to include new graphic

---

client/my-sites/themes/themes-magic-search-card/index.jsx

See #22251 fixes #22251
Users aren't comfortable with the current placeholder text b/c they don't know what type of theme they're looking for. This change should help that.

Change the search field placeholder text
