client/my-sites/people/people-list-item/index.jsx
client/my-sites/people/people-list-item/style.scss
client/my-sites/people/people-profile/style.scss

This PR intends to update the outdated style left in people profile.
Before:
After:

People: Updated style for people profile

---

client/components/keyed-suggestions/style.scss
client/my-sites/themes/themes-magic-search-card/index.jsx
client/my-sites/themes/themes-magic-search-card/style.scss

Show search filters by default. Fixes #22228

Show search filters by default

---

client/components/chart/index.jsx

Stats: Chart: fix proptype error

---

server/pages/index.js
server/render/index.js

This PR is part of the on-going work of splitting #23025 into smaller, shippable pieces and it's based on #23152 . In this PR, we introduce locale variants to the server side.

i18n: add locale variants to the server side

---

client/jetpack-onboarding/style.scss

Jetpack Onboarding: Revert primary buttons back to blue

---

client/lib/products-list/index.js

Followup to #22983 , localStorage handles only strings, so we need to serialize.

Add serialization to products list

---

client/my-sites/themes/theme-showcase.jsx
client/my-sites/themes/themes-banner/random-themes-banner.jsx

Make sure banners are not displayed for active themes.
#23122

Hide Showcase Banners for Active Themes

---

client/components/happychat/connection.jsx
client/my-sites/plans-features-main/index.jsx
client/my-sites/plans-features-main/style.scss

Reverts Automattic/wp-calypso#22988

Revert "Plans: Add Happychat to sites plans page"

---

client/components/search/index.jsx

This reverts commit 8b370e99b25fb78f3ea7aa93579146ca513d2020 #23531.
As @blowery found, this broke theme search filters, see #23561
client/my-sites/themes/themes-magic-search-card/index.jsx uses the refs of the search component which are no longer available.
https://github.com/Automattic/wp-calypso/blob/master/client/my-sites/themes/themes-magic-search-card/index.jsx#L102

Revert "Search: small changes on the Search component to remove outdated patterns (#23531)

---

client/blocks/like-button/index.jsx
client/blocks/post-likes/index.jsx
client/components/data/query-post-likes/index.jsx
client/lib/interval/index.js
client/state/posts/likes/reducer.js
client/state/posts/likes/schema.js
client/state/posts/likes/test/reducer.js
client/state/reader/posts/actions.js
client/state/selectors/get-post-like-count.js
client/state/selectors/get-post-like-last-updated.js
client/state/selectors/is-liked-post.js

To test, pull up the following stream and full post view in Reader and try to like and unlike posts.

LikeButton: Move to redux

---

client/layout/guided-tours/docs/API.md
client/layout/guided-tours/docs/DEBUGGING.md

As the Guided Tours framework has evolved, capabilities have been added and new insights gained. Those have not always documented, though. This PR tweaks the Guided Tours documentation a bit. 
To test: read the changes and evaluate whether they make enough sense.

Guided Tours: a few tweaks to the documentation

---

client/my-sites/stats/activity-log/index.jsx
client/my-sites/stats/controller.jsx
client/my-sites/stats/overview.jsx
client/my-sites/stats/site.jsx
client/my-sites/stats/stats-insights/index.jsx

Part of #22869 
I've just copy-pasted how it's done elsewhere in this file. I'm not familiar enough with how things work to know how to use `DocumentHead` as suggested :)
This is probably mergeable, but we should figure out and replace all similar instances with `DocumentHead` throughout this file.

Activity Log: Put a page title on this page to match others.

---

client/components/badge/style.scss
client/devdocs/style.scss

This PR incorporates feedback from the previous one here:
https://github.com/Automattic/wp-calypso/pull/23582
Test plan is the same as in the PR listed above

Badge component janitorial updates

---

client/blocks/README.md
client/components/README.md
docs/components.md

This small pull request is a follow-up of p1521140291000512-calypso-design which updates the documentation about components in an attempt to clarify the different types used in Calypso.

Docs: Update components documentation

---

client/state/reader/posts/actions.js

The fetchPost action in state/reader/posts isn't using the data layer yet, so we have to manually dedupe inflight requests.
This adds that deduping. Eventually, we should move this work to the data layer.

Reader: Prevent multiple inflight requests for the same post

---

client/me/account/main.jsx
client/my-sites/site-settings/form-general.jsx

Not sure how to test this.
Related patch: D11172-code
cc @dereksmart @eliorivero

Site Settings: Winter is not coming.

---

client/jetpack-onboarding/index.js
config/development.json
config/horizon.json
config/stage.json
config/test.json
config/wpcalypso.json

Don't merge yet. But soon 😄 
To test: Verify that no instances of the `jetpack/onboarding` feature flag are left in the code.

JP Onboarding: Enable in Production

---

client/my-sites/checkout/checkout/privacy-protection.jsx
client/my-sites/current-site/index.jsx

If for some reason the productsList was loaded but w/o the private_whois product it would fatal.

Checkout: Add safeguards to privacy protection component

---

client/components/data/query-billing-transaction/README.md
client/components/data/query-billing-transaction/index.jsx

Adds individual receipts query component extracted from #22442
Depends on #23498
Test instructions:
* the code should have no issues
* #23500 puts all the individual receipts PRs together - the specifications listed there should be met

Individual receipts - added a query component for single receipts

---

client/state/data-layer/wpcom/jetpack/settings/index.js
client/state/data-layer/wpcom/jetpack/settings/test/index.js

Use existing utils to do so. Prep for #23393.
To test: Verify that JPO still works.

JP Settings Data Layer: Normalize and Sanitize

---

client/state/data-layer/wpcom/jetpack/settings/index.js
client/state/data-layer/wpcom/jetpack/settings/test/index.js

JP Settings: Drop pointless toApi() unit test

---

client/extensions/woocommerce/state/sites/orders/activity-log/selectors.js
client/extensions/woocommerce/state/sites/orders/activity-log/test/selectors.js
client/extensions/woocommerce/woocommerce-services/views/shipping-label/label-details-modal.js
client/extensions/woocommerce/woocommerce-services/views/shipping-label/style.scss

This reverts commit 41aea1ebce7ccb1941f5fa6a6a145aee9474d5e1.

Revert "Store Servies - added label receipt links (#22766)"

---

client/components/domains/contact-details-form-fields/index.jsx
client/components/domains/contact-details-form-fields/test/__snapshots__/index.js.snap
client/lib/form-state/index.js
client/my-sites/domains/components/form/input.jsx

This reverts commit 4510866e9ef2df1378acb0953e5930d43aa943f1.

Revert "Form State: Option to skip validate/sanitize on field change"

---

client/jetpack-connect/controller.js
client/state/data-layer/wpcom/jetpack/settings/test/index.js
client/state/jetpack-onboarding/actions.js
client/state/jetpack-onboarding/reducer.js
client/state/jetpack-onboarding/schema.js
client/state/jetpack-onboarding/test/actions.js
client/state/jetpack-onboarding/test/reducer.js
client/state/jetpack/onboarding/actions.js
client/state/jetpack/onboarding/reducer.js
client/state/jetpack/onboarding/schema.js
client/state/jetpack/onboarding/test/actions.js
client/state/jetpack/onboarding/test/reducer.js
client/state/jetpack/reducer.js
client/state/selectors/get-unconnected-site-id-by-slug.js
client/state/selectors/get-unconnected-site.js
client/state/selectors/test/get-jpo-user-hash.js
client/state/selectors/test/get-unconnected-site-id-by-slug.js
client/state/selectors/test/get-unconnected-site-url.js
client/state/selectors/test/get-unconnected-site.js

Prep for #23797. So much code for so little change 🙄 
To test: Verify that JPO still works (try all combinations, logged out and in, connected and not)

Jetpack Onboarding: Move Credentials State to jetpack/onboarding

---

config/stage.json

Jetpack connect: Enable Google signup on staging

---

client/components/global-notices/README.md
client/components/jetpack-colophon/README.md
client/components/jetpack-logo/README.md
client/components/list-end/README.md
client/components/notice/README.md
client/components/ribbon/README.md
client/components/screen-reader-text/README.md
client/components/share-button/README.md
client/components/suggestions/README.md
client/components/text-diff/README.md
client/components/tinymce/plugins/embed/README.md
client/components/wizard/README.md
client/devdocs/design/index.jsx
client/devdocs/wizard-component/index.jsx

As raised in #24058 quite a few components don't have README.md files. This PR adds many missing ones. This might require a shared approach to review as different people know about different components.
To test, check out this branch than then click on different components in UI components in DevDocs and check that they all have documentation (except CheckList, Gridicons and SocialLogos)

DevDocs: Add README.md files for those components that don't have them

---

client/state/happychat/test/utils.js

Promise tests should return a promise.
Changed in #23540, tests may not behave as expected.
Tests should pass and fail as expected. All should pass on this branch.

Happychat: Await promise test results

---

client/my-sites/stats/activity-log-item/index.jsx

Previously, if a backup failed due to invalid credentials and it was logged, a button was shown so user could fix them. This was like this even after the creds were valid, thus becoming confusing for users.
This PR will now hide the button if Rewind is now active, and will update the text with the suggestion provided by Krista in https://github.com/Automattic/wp-calypso/pull/24048#issuecomment-380230967. This is done here because ActivityStream events can't be updated once they're logged.

Activity Log: hide Fix credentials button and update text on failed backup events

---

assets/stylesheets/sections/devdocs.scss
client/devdocs/controller.js
client/devdocs/design/playground.jsx
client/devdocs/design/style.scss
client/devdocs/design/syntax.scss
client/devdocs/index.js
client/devdocs/sidebar.jsx
client/devdocs/style.scss
package.json

A new take on #8284 and #23446
cc: @MichaelArestad

Devdocs: Add Code Playground - Preview of all components. 

---

client/jetpack-connect/signup.js
config/development.json
config/stage.json
config/test.json

Remove the feature flag and feature check.
1. Tests should pass (no change in test env).
1. Verify Google sign up is visible via JPC on calypso.live (perviously not available in this env). See #23483 for test flow.

Enable Jetpack connect Google sign up in all envs

---

npm-shrinkwrap.json
package.json

This small update has <a href="https://github.com/Automattic/notifications-panel/pull/245">some fine-tuning of icons within content</a>, and <a href="https://github.com/Automattic/notifications-panel/pull/253">better links for empty filter lists</a>.
**Testing**
* Apply this branch and restart Calypso.
* Ensure notifications open and behave as expected.

Notifications: Update to `notifications-panel` v2.1.9.

---

bin/version-check.js

Make some tweaks to the version check script based on https://github.com/Automattic/wp-calypso/pull/22237#pullrequestreview-95611152

chore: Tidy up version check string creation

---

docs/guide/design-patterns.md
docs/guide/glossary.md
docs/guide/index.md
docs/guide/information-architecture.md
docs/guide/tech-behind-calypso.md

DevDocs: Add higher-level design patterns to the guide.

---

client/my-sites/stats/activity-log-item/activity-actor.jsx

If applied this PR will render a Happiness Engineer actor based on the event received from the API.

Activity Log: detect and render a Happiness Engineer actor

---

client/devdocs/sidebar.jsx

See #24132
Testing:
* Load this PR
* Navigate to DevDocs
* Check for the presence of Accessibility item in sidebar
* Check to make sure clicking the item goes to the correct page

Add Accessibility to DevDocs sidebar for better visibility. 

---

.github/CONTRIBUTING.md
docs/components.md
docs/new-component-checklist.md

This creates a checklist for people who want to create a new UI component.
Please test all links in the doc!
I want to also include a readme file requirement for adding new components, and a template example readme file.
fixes #24066

DevDocs: add doc for creating new components

---

client/blocks/inline-help/popover.jsx
client/me/help/help-contact/index.jsx
client/me/help/main.jsx

Previously https://github.com/Automattic/wp-calypso/pull/24313
Adding a link to automatticstatus.com.

Atomic: Update outage message

---

client/blocks/inline-help/popover.jsx
client/me/help/help-contact/index.jsx
client/me/help/main.jsx

DO NOT MERGE. STAGING PR FOR WHEN OUTAGE IS RESOLVED.
Reverts #24313, #24316

Atomic: Revert outage message

---

client/components/plans/plans-skip-button/README.md
client/components/plans/plans-skip-button/docs/example.js
client/devdocs/design/index.jsx

Follow-up to #24312.
Visit http://calypso.localhost:3000/devdocs/design/plans-skip-button and make sure that nothing breaks.
If you click the 'Start with Free' button, you'll see a console message.

Components: Add Docs and Example to PlansSkipButton

---

client/extensions/woocommerce/app/order/create.js

Fixes #23559 
To test:
* Set the currency under Settings > Payments to something other than USD
* Start creating a new order under Orders > New
* Make sure the order currency is correct and that you can save the order, abandon creation, etc.
* Repeat for other currencies including USD

Store: Set currency for a new order using the site's settings

---

client/components/button/docs/example.jsx

Set Display Names for Button so that it can load in DevDocs

---

client/my-sites/importer/importing-pane.jsx

This PR updates the wording of the import complete message to be a bit more encouraging about the import results. 
To test:
1. Checkout branch or use Calypso.live link
2. Go to imports and import something ( Should be valid for any type of import )
3. On the success screen, verify the Import complete message was updated.
4. Verify no errors or strange behaviour was observed during the import.

Imports: Update wording on import complete message

---

client/state/ui/test/reducer.js

Fixes a failing test
1. run `npm run test-client client/state/ui` 
2. We expect everything to pass now!

Fix Failing State UI Reducer Test

---

client/components/domains/featured-domain-suggestions/index.jsx

This PR fixes an invalid boolean comparison.

[Domains] Fix featured domain name text size bug

---

client/layout/index.jsx

This PR resolves #24434 issue.

Marketing: Disable NPS survey for e2e tests

---

client/blocks/subscription-length-picker/style.scss

A minor CSS Update to make discounted prices more readable
This is all under a feature flag ATM, and this PR is so simple there is no test plan.

Make old prices more readable with a CSS update

---

client/components/data/domain-management/email/index.jsx
client/components/data/domain-management/index.jsx
client/components/data/query-products-list/index.jsx
client/components/upgrades/google-apps/README.md
client/components/upgrades/google-apps/google-apps-dialog/index.jsx
client/components/upgrades/google-apps/index.jsx
client/lib/cart/store/index.js
client/lib/products-list/README.md
client/lib/products-list/index.js
client/lib/signup/cart.js
client/lib/signup/step-actions.js
client/lib/upgrades/actions/free-trials.js
client/lib/upgrades/actions/index.js
client/my-sites/domains/controller.jsx
client/my-sites/domains/domain-management/controller.jsx
client/signup/steps/domains/index.jsx
client/state/products-list/reducer.js
client/state/products-list/schema.js
client/state/products-list/selectors.js
client/state/products-list/test/reducer.js

This reverts commit c308744e376351f3261168278a158056c561705e. Reverting because of incorrect REST API request when adding a plan to cart from Plans page.

Revert "Reduxification: replace productsList with Redux counterpart (#23104)"

---

client/components/back-button/README.md
client/components/back-button/docs/example.jsx

Update BackButton so that the README.md conforms to the guidelines and appears in the component playground.

DevDocs: Update BackButton

---

client/lib/analytics/ad-tracking.js

After this commit, we will start recording the purchase events to Nanigans. The event is fired once the purchase is completed, by submitting the entire cart contents.
The events are implementing using an Array, which is later transformed into a Naningans object when the script is loaded.
Example from the reference:
```
NaN_api = [
[12345, 'user1234'],
['purchase', 'main', [600, 1500], { // value is in cents, and is qty * value for individual product
'sku': ['apple', 'orange'],
'qty': [2, 3],
'unique': 'transaction_id1234'
}]
];
```
https://trello.com/c/Isp8jpFN/348-setup-nanigans-tracking
1.  Make sure you load the right branch: https://calypso.live/?branch=add/nanigans-tracking-pixel&flags=ad-tracking
2. Open console and enable debugging `localStorage.setItem( 'debug', …

Ad Tracking: Introduce the Nanigans tracking for purchases

---

client/lib/analytics/ad-tracking.js

Before this change, each product on the order (the plan, the domain) was sent to FB separately, with its own parameter.
After this change, the order will be tracked only once, with the total cart price. The product_slug parameter will concatenate the products that are contained in the order.
Testing
----------
*Preparation*
1) Enable debugging for ad tracking `localStorage.setItem( 'debug', 'calypso:analytics:*' );` and open the browser console.
2) Make sure you have enough credits and purchase 2-3 plans for one of your sites.
3) Make sure you access the pages using ?flags=ad-tracking parameter, because tracking is disabled in development or on calypso.live. https://calypso.live/?branch=add/tracking-fb-one-event-only&flags=ad-tracking . If you test locally, you may also launch Calypso …

Ad Tracking: Facebook - track once per order, not per product

---

client/lib/abtest/active-tests.js

Increasing segment of users exposed to 2 year plans from 10% to 20%

Launch 2-year plans to 20% of users

---

client/my-sites/checklist/checklist-show/index.jsx

**Before**
**After**
The checklist feature is not available for Jetpack and Atomic sites. Previously at /checklist/{site} we have been displaying a placeholder for these sites. Instead, show the `<EmptyContent />` component with a message.
* Go to https://calypso.live/checklist?branch=update/checklist-empty-content
* Choose a Jetpack or Atomic site
* You should see the new message
* Choose a wpcom site
* You should see the working checklist as normal

Checklist: Show 'not available' message instead of placeholder for sites with no checklist

---

client/lib/abtest/active-tests.js

A final update of test allocation - make each user group 50% 
Test plan: None

Update 2 year plans allocation to 50/50

---

client/state/data-layer/http-data/index.js

Before the `getHttpData()` middleware is injected into the Redux
store it cannot dispatch any actions. In the first draft of this
code the actions were overlooked. In this update we are queueing
actions until the dispatcher becomes available then flushing out
all the actions after a small delay after the enhancer loads up.
**Testing**
Mainly review the code. This is still dormant code.
Verify that you like the design and API and
that you see no obvious or subtle flaws.

Framework: `getHttpData` use dispatch queue until initialized

---

client/components/animate/docs/example.jsx
client/components/badge/docs/example.jsx
client/components/textarea-autosize/docs/example.jsx
client/components/vertical-nav/docs/example.jsx

These devdocs are broken on wpcalypso.

Add displayNames to fix DevDocs in wpcalypso

---

client/components/foldable-card/docs/example.jsx
client/components/foldable-card/index.jsx
client/devdocs/design/playground-utils.js
client/devdocs/design/playground.jsx
client/devdocs/design/search-collection.jsx

This adds FoldableCard to the DevDocs playground. It involves some changes in the way the playground works which are a little hacky.

Add FoldableCard to the playground

---

client/blocks/signup-form/README.md

The README for `SignupForm` doesn't mention the required prop `suggestedUsername` - I've added a reference.
cc @scruffian

DevDocs: Add required prop  to SignupForm README.md

---

client/state/test/utils.js

Remove sinon spies, use Jest spies.
Remove chai expect, use Jest expect.
Make Promise tests a bit nicer with async/await.
1. Tests pass?

Tests: Update state utils tests to jest

---

client/blocks/user-mentions/README.md
client/blocks/user-mentions/docs/example-input.jsx
client/devdocs/design/blocks.jsx
client/devdocs/style.scss

Add documentation for the new user mentions block.
Visit http://calypso.localhost:3000/devdocs/blocks/user-mentions and have a read 👀

User mentions: add README

---

client/blocks/user-mentions/add.jsx

This PR improves the experience when editing an existing word to include an @ mention. For example:
It now:
- presents the correct matches for the word following the @
- will not duplicate the username if it matches the text after the @ exactly
- moves the caret to the end of the inserted username
Fixes #24521.

User mentions: improve behaviour when working with an existing word

---

config/horizon.json
config/stage.json
config/wpcalypso.json

Pending review and merge of #24721, #24744 and #24745.

Enable user mentions on wpcalypso, staging and horizon

---

client/components/split-button/index.jsx

See #24818
While hunting for a performance issue I stumbled upon
a few components that could use some updating. This is
one of them.
- replace custom constructor with simpler initial state assignment
- use arrow-functions for lexical binding instead of manual binding
- replace `ref` usage with `createRef()`
- replace statement-oriented functions with expressions
**Testing**
I think that this is only being used in the Activity Log. Manually
verify that it works as expected. Please audit the code for mistakes.

Components: Code update for `<SplitButton />`

---

client/components/notice/README.md

Update the layout of the Notice readme file. See #24282.

Update the Notice readme file

---

client/components/pagination/README.md

Update the Pagination readme file to new layout. See #24282.

DevDocs: Update the Pagination readme file

---

client/components/card/README.md
client/components/card/docs/example.jsx
client/devdocs/design/playground-scope.js
client/devdocs/style.scss
docs/component-readme-template.md

Updating the readme file to match layout of other component readme files. See #24282

Update Card readme file

---

config/stage.json
config/test.json
config/wpcalypso.json

Enable the new Account Closure features in Staging for testing.
Preparing this so that we can do this when we are ready for internal tester

Account Closure: Enable in Staging.

---

client/components/foldable-card/README.md

Updating the Foldable-card readme file with new layout. See #24282.

DevDocs: Update the Foldable-card readme file

---

client/my-sites/domains/domain-management/components/email-verification/index.jsx

They are currently disabled on Tucows side, so let's show some semi-helpful message to users.

Domains: Show a maintenance notice for verification emails

---

client/components/feature-example/README.md

The name on the import function was wrong, this fixes it.

Documentation: fix FeatureExample component name

---

client/my-sites/people/people-invite-details/index.jsx

This PR fixes an English spelling error.
N/A

Invites: Update revoking invitation text 

---

.gitignore
assets/stylesheets/emergent-paywall.scss
package.json

The Emergent Paywall (see #24675) loads in an iframe, so we can't adjust its internal styles with the primary Calypso stylesheet. This creates a separate CSS file to be linked from inside the iframe.
Needed for backend: D13666-code
Tweak `getCurrentUserPaymentMethods` in `client/state/selectors/get-current-user-payment-methods.js` by hardcoding `IN` as the countryCode for `paymentMethods.byCountry[ countryCode ] ||`.
To see local CSS changes you'll need to
make your browser rewrite those CSS URLs to the local version:
`https://wpcalypso.wordpress.com/calypso/emergent-paywall.css` => `http://calypso.localhost:3000/calypso/emergent-paywall.css`
You can accomplish this using a browser extension such as Switcharoo Redirector
for Chrome: …

Checkout: Emergent Paywall custom css

---

client/components/domains/domain-product-price/style.scss
client/components/domains/domain-suggestion/style.scss

I add `padding-right: 2em` on `client/components/domains/domain-suggestion/style.scss`
To fix this issue :  #25146

Domain: Fix suggestion title spacing on narrow screens

---

client/lib/abtest/active-tests.js

As in the description.
No test plan

Update the timestamp on multiyearSubscriptions test

---

client/state/data-layer/wpcom/theme-filters/index.js

@seear and @blowery: This change was accidentally reverted in #25204 and Dennis is AFK. I'm not very familiar with the original change, but could you help me make sure that this revert-of-revert achieves what #25125 intended?
Thank you!

Framework: Undo accidental revert of #25125

---

client/my-sites/domains/domain-management/components/email-verification/index.jsx

Temporary changes were made during Tucows rollout of GDPR that affected these emails.

Revert #25091 after temporary changes for GDPR.

---

client/my-sites/site-settings/site-icon-setting/index.jsx

Settings: fix change button obfuscated by prompt

---

client/lib/analytics/ad-tracking.js

- Changes FB pixel tracking so that we are now using [`trackSingle` and `trackSingleCustom`](https://developers.facebook.com/ads/blog/post/2017/11/28/event-tracking-with-multiple-pixels-tracksingle/). This allows for a single FB pixel ID to be associated with a specific event. Whereas the normal `track` function fires an event against all initialized FB pixel IDs.
- When Jetpack is being purchased, fire the FB pixel ID for Jetpack.com instead of the default FB pixel ID. This allows us to track Jetpack conversions against the FB pixel ID for Jetpack.com.
These additional changes were required:
- Disable pushState tracking in Facebook pixels, in favor of `only_retarget()`, which is already in Calypso. This allows us to send `PageView` events appropriately; i.e., only for the WP.com FB pixel …

Ad Tracking: Fire Jetpack FB pixel ID when appropriate

---

npm-shrinkwrap.json
package.json

Closes #25102 
See #25102 for details on the upgrade.

chore(package): update eslint-plugin-jest to version 21.17.0

---

renovate.json

They're overwhelming the test runners.

Disable adding review labels to renovate PRs for now

---

client/signup/steps/clone-point/index.jsx

Currently, we dump all activity log events into the clone point step. This is too much information for one screen. This PR aims to solve that problem by paginating the logs similar to how they are paginated in the actual activity log.
**Testing**
Step through the clone site flow and test the pagination on the `clone-point` step. You should be able to navigate through the pages seamlessly, and there should be no gaps in the items from page to page. Ensure you can select a clone point and the rest of the flow is not modified in any way.

Rewind: Paginate the activity log in the clone point step in site clone flow

---

client/components/external-link/style.scss

Component: adjusting margin on External Link component

---

client/post-editor/editor-more-options/slug.jsx

Updated the slug description in post settings following issue #22676 
Fixes #22676

Editor: updated the slug description in post settings

---

client/components/line-chart/README.md
client/devdocs/design/index.jsx

This adds a README to the line charts component

Add README to line charts graph

---

client/me/help/main.jsx
client/me/help/test/main.jsx

- Use `some()` over `!! find()`
- Leverage library function `isWpComBusinessPlan`
- Add tests
- Sort imports 
1. Tests pass?

Me: Simplify help/me main component

---

client/document/support-user.jsx
server/pages/index.js

This PR allows for the support user to be redirected to a specified path.
See testing instructions on D15165-code.

Support-User: Adds support for specifying a path

---

client/lib/discounts/active-discounts.js
client/state/selectors/get-active-discount.js
client/state/selectors/test/get-active-discount.js

This PR adds a promotion for the last week of June.
It needs to be tested in combination with the active promotion.

Add June 2018 promotion

---

client/me/purchases/controller.jsx
client/me/purchases/index.js
client/me/purchases/manage-purchase/index.jsx
client/me/purchases/manage-purchase/plan-details/index.jsx
client/me/purchases/manage-purchase/purchase-meta.jsx
client/me/purchases/purchase-item/index.jsx
client/me/purchases/purchases-site/index.jsx
client/me/purchases/purchases-site/reconnect-notice.jsx
client/me/purchases/remove-purchase/index.jsx

Reverts Automattic/wp-calypso#25473
Additional testing on staging shows that some backend work will be required before this is ready to land.

Revert "Purchases: Manage for disconnected sites"

---

client/signup/steps/about/index.jsx

Fixes #25794 
1. Visit https://calypso.live/start?branch=fix/about-screen-search-regex
2. Enter a regular expression character (\, [ etc) in the "What will your site be about?" field
3. Observe no crash

Signup: Escape Reg Exp on About Search

---

client/me/concierge/constants.js
client/state/data-layer/wpcom/concierge/schedules/appointments/book/index.js
npm-shrinkwrap.json

Uses the error code introduced in `D15174-code` to display a specific meaningful message to a user who attempts to book a second appointment when they already have one pending.
**Testing**
1. Apply `D15174-code`.
2. Book an appointment at `/me/concierge`.
3. Attempt to book a second appointment. This should fail and give you the error message added in this PR.
cc @nb

Concierge: Add second appointment error message

---

client/state/login/actions.js

Avoid finally, since not all browsers support it

Avoid finally

---

client/my-sites/feature-upsell/controller.js
client/my-sites/feature-upsell/index.js
client/my-sites/feature-upsell/main.jsx
client/my-sites/feature-upsell/plugins-upsell.jsx
client/my-sites/feature-upsell/store-upsell.jsx
client/my-sites/feature-upsell/style.scss

This adds a plugin feature upsell page for the business plan.
It is a work in progress and adds an unused page behind a feature flag.

Add plugins upsell page

---

client/my-sites/feature-upsell/ads-upsell.jsx
client/my-sites/feature-upsell/store-upsell.jsx

This PR updates a copy to reflect suggestions from the editorial team. Related post: p9jf6J-Hl-p2
Test plan:
1. Go to /feature/ads and /feature/store and confirm the copy is clear and reads well

[nudge-a-palooza] Copy updates as suggested by the editorial team

---

client/my-sites/feature-upsell/ads-upsell.jsx
client/my-sites/feature-upsell/plugins-upsell.jsx
client/my-sites/feature-upsell/store-upsell.jsx
client/my-sites/feature-upsell/style.scss
client/my-sites/feature-upsell/themes-upsell.jsx

This PR adjusts CSS of nudge-a-palooza Landing Pages to make them more pretty. Related post: p9jf6J-Hl-p2
Test plan:
1. Go to the following URLs and confirm they look good on all screen sizes:
* /feature/ads 
* /feature/store  
* /feature/plugins 
* /feature/themes
Specifically no text should touch screen edge on movile and features lists with checkmarks should be centered on desktop.

Update CSS on landing pages to address latest feedback

---

client/my-sites/stats/activity-log/index.jsx
client/my-sites/stats/activity-log/style.scss

This PR adds a top pagination to the Activity log and corresponding styles.

Activity: add top pagination

---

client/my-sites/customize/main.jsx

Accept a navigateTo command via postMessage from the customizer for navigating to specific Calypso pages.
---------------
**Test Plan**
See D16268-code

Navigate to a specific Calypso page from the Customizer

---

client/my-sites/plan-features/item.jsx

fix(Plan): fix popover to showing on the left side instead on the top

---

client/me/help/help-contact/readme.md

When starting to work with the `HelpContact` component I found the component a little confusing, as it renders a different variation depending on the conditions of the user.
This readme aims to add a little clarification by stating the different variations that might be shown and pointing the reader in the right direction for intervening and forcing a particular view to be shown (by modifying `getSupportVariation`.

Me: Add readme for HelpContact component

---

client/components/payment-country-select/index.jsx

closes #25863 
**Note:** I could use some feedback especially for the selector part.
The `countryList` prop isn't filled at the time of mounting the `PaymentCountrySelect` component. Which means the check in `componentDidMount` will always return an empty `countryCode` to the `onCountrySelected` callback on first mount. However, we do use the country code we receive from the state to pre-select it anyways regardless of it's invalid state. 
Move the check whether a country code is valid from `componentDidMount` to the selector for the country code. Additionally we only use this one `countryCode` prop to report back to the `onCountrySelected` callback. I added a callback invocation in `componentDidUpdate` to cover the case where the state gets updated after the first mount and the change …

PaymentCountrySelect: only pre-select valid country codes

---

npm-shrinkwrap.json
package.json

Updates the Notifications panel to version 2.2.2.
- Smoke test notifications.
- https://github.com/Automattic/notifications-panel/pull/285 testing steps.

Notifications: update panel to version 2.2.2

---

client/my-sites/stats/activity-log/unavailability-notice.jsx

Activity Log: fix defect in unavailability notice

---

config/production.json
config/stage.json

Project nudge-a-palooza (p9jf6J-Hl-p2) is ready to ship, let's release it for all our users.
Test plan:
It's not possible to test this before merging

[nudge-a-palooza] Enable nudge-a-palooza for everyone

---

client/post-editor/editor-sharing/publicize-connection.jsx

Add Warning to Publicize Connections to Facebook Profiles

---

client/blocks/reader-combined-card/index.jsx

@blowery Not entirely sure how things are working with the error.

Fix a logic error introduced in #26499.

---

server/render/index.js

The Calypso ASCII art is beautiful, this would make it also useful.

Add `work-with-us` link to Calypso ASCII art

---

client/my-sites/upgrade-nudge/index.jsx

Reverts Automattic/wp-calypso#24039

Revert "Upgrade Nudge: removes nudge for non admin users"

---

client/my-sites/plugins/plugin-meta/index.jsx

Update incompatible plugin list with changes reported as of 2018-07-09.

Atomic: Update incompatible plugin list

---

client/lib/abtest/active-tests.js
client/signup/steps/domains/index.jsx

Update A/B test and move the abtest() variation assignment after checking conditions.

NUX: Show .blog subdomain based on the about step

---

.circleci/config.yml

Follow up to #26716 
Just verify CircleCI tests pass.

Update CircleCI Node to 10.9.0

---

client/my-sites/checkout/cart/cart-coupon.jsx

These ids are used in the e2e tests for entering and applying the coupon code. 
Related to https://github.com/Automattic/wp-e2e-tests/issues/1303
Blocks https://github.com/Automattic/wp-e2e-tests/pull/1410

Included ids in coupon cart form

---

client/extensions/woocommerce/app/dashboard/setup/tasks.js
client/my-sites/checklist/checklist-show/index.jsx
client/my-sites/plans/current-plan/jetpack-checklist/index.js

Remove HotJar from checklists, added in #22480 
Is this still in use and required?

Checklist: Remove HotJar from checklists

---

client/my-sites/stats/activity-log-tasklist/index.jsx

This PR refactors code so that it is a bit more readable and make it so that if someone does change the constant the expected result happens instead of a bug. 
Go to a site that has updates. 
Note that the updates are able to expand. Nothing should change from how things work right now. 
cc: @eliorivero

Activity Log: make constant and fix hard coded code

---

client/lib/discounts/active-discounts.js

This promo got delayed a few weeks.
Updating dates to make it active now.

Extend start and end date of nudge for upcoming promo

---

client/signup/steps/import-url/index.jsx

This change set adjusts the way in which we handle input changes and the debounced server check for the URL input in the nux import flow.
With the changes proposed we can keep the url value in state. Right now that's held in component state but the next step will be to move that in to redux state.
There should be no noticeable change to behaviour. Follow the behaviour in #26502, turn on debugging too to show the debounced server checks and their results:
```js
localStorage.setItem('debug', 'calypso:signup-step-import-url');
```
* Needs D17199-code & a patched API sandbox for now
* Run this branch locally
* Visit http://calypso.localhost:3000/start/from-site
* It should redirect to http://calypso.localhost:3000/start/from-site/import-from-url & you should see a new step with a form to …

ImportNUX: Change debouncing strategy to allow controlled input

---

client/components/domains/register-domain-step/index.jsx
client/lib/abtest/active-tests.js

Back-end providers changed some weights, so we're rerunning it.

Domains: New Kracken test iteration

---

client/blocks/eligibility-warnings/index.jsx
client/lib/abtest/active-tests.js
client/my-sites/plugins/plugin-meta/index.jsx
client/my-sites/plugins/plugin-upload/index.jsx
client/my-sites/plugins/plugins-browser/index.jsx
client/my-sites/themes/theme-upload/index.jsx

This PR replaces test group `customPluginAndThemeLandingPages` of `nudgeAPalooza` with two separate A/B tests. Instead of allocating entire traffic to a test group, these new tests will only allocate users after they click on a certain button.
Test plan:
1. Choose a free site in calypso
1. Go to `/plugins`
1. Go to `/plugins/woocommerce`
1. Go to `/plugins/upload`
1. Refresh and confirm you are not assigned to any group of `pluginsUpsellLandingPage` test
1. Go to `/plugins`
1. Click on the upsell banner saying that you need a business plan
1. Confirm you are now assigned to a group of `pluginsUpsellLandingPage` test
1. Assign yourself to a `test` group of `pluginsUpsellLandingPage` test
1. Go to `/plugins`
1. Click on the upsell banner saying that you need a business plan
1. Confirm you …

Replace customPluginAndThemeLandingPages with two separate A/B tests

---

config/desktop-development.json
config/desktop.json
config/development.json
config/horizon.json
config/production.json
config/stage.json
config/test.json
config/wpcalypso.json

Related to p9jf6J-Sn-p2
This is a first PR for a blogger plan, all it does is it adds a feature flag for further development.
Test plan:
None

Add blogger-plan feature flag

---

client/lib/plans/constants.js
client/lib/plans/index.js
client/lib/plans/test/plan-lookups.js
client/my-sites/plans-features-main/index.jsx

Related to p9jf6J-Sn-p2
This PR adds required plan constants for blogger plan to `plans/constants.js`.
**Test plan:**
Make sure tests pass

Add constants and helpers for blogger plan

---

client/me/help/help-search/test/index.js

Removes empty mock.
Thanks to @sirreal for [seeing the unseen](https://github.com/Automattic/wp-calypso/pull/26077#pullrequestreview-153680812).

Help: Removed unused mock

---

client/components/date-picker/index.jsx
client/my-sites/activity/activity-log/index.jsx
client/my-sites/activity/filterbar/date-range-selector.jsx
client/my-sites/activity/filterbar/index.jsx
client/my-sites/activity/filterbar/style.scss
client/state/data-getters/index.js

This PR adds the skeleton and the range picker to the current activity log filterbar. p9rlnk-vb-p2

Activity Log: Add Range Selecting to the Filterbar

---

client/my-sites/plan-features/index.jsx

Test plan:
1. Go to /plans as a user of any paid plan
1. Make sure you are assigned to the "test" group of `showPlanCreditsApplied` test
1. Confirm the copy that's displayed on the page is the same as in this PR:

Update copy explaining upgrade credits

---

client/blocks/inline-help/index.jsx
client/blocks/inline-help/popover.jsx
client/blocks/inline-help/style.scss

Reverts Automattic/wp-calypso#26808 as build failed.

Revert "Inline Help: Adds a checklist button with progress bar and notification"

---

client/components/domains/domain-search-results/index.jsx
client/components/domains/featured-domain-suggestions/index.jsx
client/components/domains/register-domain-step/index.jsx

Add more context to the fetch algo.
The /domains/search prefix will help narrow down these events, and the date on the end will show what test its for.

Domain Suggestions: Add more context to the tracking

---

client/my-sites/activity/filterbar/action-type-selector.jsx
client/my-sites/activity/filterbar/date-range-selector.jsx
client/my-sites/activity/filterbar/style.scss

Here we have the 3 new states, 
Initial view:
Try this out and see if this makes sense. 
I didn't pay to much attention to the styling here. 
But the idea would be that it looks like the Date Range selector.

Activity Log: Filterbar add deselect and select all buttons

---

client/my-sites/activity/activity-log-example/index.jsx

Props to @shaunandrews for catching this awkward wording.

Activity Log: update copy on the empty content component

---

npm-shrinkwrap.json
package.json

Reverts Automattic/wp-calypso#27389

Revert "Update dependency he to v1.2.0"

---

client/reader/following/main.jsx
client/reader/following/style.scss

A bunch of open issues here:
- can we limit who this is shown to by country?
- should we configure the messaging to change over time
- how does this work if the reader intro banner is already displayed

Reader: add a TurboVote banner

---

client/my-sites/activity/activity-log/index.jsx
config/development.json
config/production.json
config/stage.json
config/test.json
config/wpcalypso.json

Flips the `activity-filterbar` feature flag in production.

Activity Log: Enable filterbar in production.

---

client/gutenberg/editor/api-middleware/index.js

This fixes #27438 and partially fixes #27253 to support media uploads in some browsers. In Calypso we use one of 2 auth methods: the first uses an iframe proxy and the second uses oauth. This is abstracted out in the `lib/wp` module [here](https://github.com/Automattic/wp-calypso/blob/3beded84b34a069320b9649c0a9ce790688291cb/client/lib/wp/browser.js#L24) under the `oauth` flag.
- Checkout this branch
- Visit /gutenberg and select a site
- autosave and other text edits work
- media may be uploaded in FF/Safari, but is immediately cancelled in Chrome ( ✨ for whomever wants to help debug that) CORS maybe?
- Note that oembeds are still broken and will be fixed in #27486.

Gutenberg: use lib/wp instead of wpcom-proxy-request to account for iframe and oauth auth methods

---

assets/stylesheets/_components.scss
client/components/animate/index.jsx

* Migrate Animate styles to JS import
* Navigate to: http://calypso.localhost:3000/devdocs/design/animate
* Observe that the p tag animates in on page refresh
#27515

Migrate Animate styles to JS import

---

assets/stylesheets/_components.scss
client/components/back-button/index.jsx

* Migrate Back Button styles to JS import
* Goto: http://calypso.localhost:3000/devdocs/design/back-button
* Do styles look okay?
#27515

Migrate Back Button styles to JS import

---

client/my-sites/controller.js

* Remove lib/user usage from page.js handlers in my-sites/controller.
* Because @jsnajdr told me to do so. ;)
* Unit tests.
* Smoke test My Sites and make sure things aren't exploding.
Fixes #27516

My Sites: remove lib/user from page.js handlers in my-sites/controller

---

client/my-sites/controller.js

Reverts Automattic/wp-calypso#27529
Make sure logged out theme pages work

Revert "My Sites: remove lib/user from page.js handlers in my-sites/controller"

---

.circleci/config.yml
bin/icfy-analyze.js

* Build ICFY stats.json and chart.json
Inspect the artifacts in the icfy-analyze job

Build icfy assets

---

client/gutenberg/extensions/presets/jetpack/README.md
client/gutenberg/extensions/presets/jetpack/package.json
lerna.json

Set up [`@automattic/jetpack-blocks`](https://www.npmjs.com/package/@automattic/jetpack-blocks) for publishing.
```bash
npm publish --tag next
```
☝️ from the Jetpack preset directory

Jetpack Blocks: Use lerna to publish

---

assets/stylesheets/_components.scss
client/blocks/blog-stickers/index.jsx

* Migrate Blog Stickers styles to JS import
* Not sure how to test this
#27515

Migrate Blog Stickers styles to JS import

---

client/components/domains/register-domain-step/index.jsx
client/lib/abtest/active-tests.js

Testing different .blog suggestion providers.
Turn off old, start new test on Friday. 
None, really.

A/B Tests: Iterate on the dotblog subdomains test

---

client/me/purchases/manage-purchase/index.jsx

fix(/me/purchases) Update domain description message

---

client/my-sites/activity/activity-log-item/activity-actor-icon.jsx
client/my-sites/activity/activity-log-item/activity-actor.jsx
client/my-sites/activity/activity-log-item/aggregated.jsx
client/my-sites/activity/activity-log-item/style.scss
client/state/data-layer/wpcom/sites/activity/from-api.js

IN PROGRESS
Before:
After:
*
*
Fixes #

Activity Log: Add Multiple Actors Icons

---

client/blocks/app-banner/index.jsx

* Updating the links from each app banner
* Make sure the app banners go to the correct link

Updating app banner to handle different sections of the app

---

client/signup/steps/site-or-domain/index.jsx

This reverts commit bfebbd251d6889c69597191249b967f0f167b139.
Make sure `/start/domain` works.

Revert "Domains: Skip new site/just domain step if user is logged out"

---

client/my-sites/sharing/connections/mailchimp-settings.jsx

This adds a notice when no MC list is selected.

Mailchimp: please select a list notice.

---

assets/stylesheets/_components.scss
client/components/tinymce/index.jsx

*Migrate Tinymce  styles to JS import
* Create new post
* Observe Tiny MCE styles load
#27515

Migrate Tinymce  styles to JS import

---

client/my-sites/sharing/connections/mailchimp-settings.jsx
client/state/mailchimp/lists/reducer.js

This fixes disappearing notice about lists being not connected.
Again.

Mailchimp: no lists notice

---

client/my-sites/importer/style.scss
client/my-sites/importer/uploading-pane.jsx
npm-shrinkwrap.json
package.json

Reverting because of reported issues with media uploads on Safari 10.

Revert "Upgrade wpcom-proxy-request to 5.0.1 to work around a Chrome bug (#28079)"

---

client/lib/plans/constants.js

@see p6TEKc-2mI-p2
* Update the Jetpack Essentials Features description with info about the Site Accelerator (#27944) and the activity log.
* Head to http://calypso.localhost:3000/plans/
* Make sure the copy is correct.

Jetpack Description: update with Site Accelerator / Activity Log

---

npm-shrinkwrap.json

Somehow it got out of sync. This fixes the npm ERR acorn-dynamic-import not accessible from webpack

Fix broken shrinkwrap.

---

config/desktop-development.json
config/desktop.json
config/development.json
config/horizon.json
config/stage.json
config/wpcalypso.json

This adds a `signup/ecommerce-flow` feature flag. 
The flag is set to true in development only
Make sure it builds

Plans: Add ecommerce feature flag

---

client/signup/steps/domains/index.jsx

We are testing whether just sending searches from /domains to NUX would result in higher conversion.
In D20073-code.
Depends on: D20073-code

Domains: Treat specific queries from /domains as a search

---

client/gutenberg/editor/controller.js

* In the Gutenberg controller, force `await`ing for the `selectedSiteId` to be set before attempting to render the editor.
This is roughly the same approach we took with the Post Editor controller in #28305.
* Open Calypso disabling the `calypsoify/gutenberg` feature flag: http://calypso.localhost:3000/posts/?flags=-calypsoify/gutenberg
* Opt out of gutenberg by entering `dispatch( { type: 'EDITOR_TYPE_SET', siteId: state.ui.selectedSiteId, editor: 'classic' } )` in the browser console.
* Open a post editor and opt in to Gutenberg through the sidebar prompt or the bottom notice.
* Make sure the Gutenberg editor is rendered.
* Open again the posts list (http://calypso.localhost:3000/posts/?flags=-calypsoify/gutenberg -- note: the Close button might not work as expected!), and edit a post. …

Gutenberg: Prevent race condition between Redux subscribe and Page routing

---

client/lib/automated-transfer/index.js
client/lib/automated-transfer/test/index.js

* Gives `/lib/automated-transfer` ecommerce plan awareness
* Automated tests

Update ecommerce in /lib

---

client/lib/plans/constants.js
client/lib/plans/test/plan-lookups.js
client/lib/products-values/index.js

Adds constants necessary for the possible introduction of a monthly option for the business plan.
Tests added in #28082

Prepare for for monthly business plan - add constants

---

client/me/purchases/manage-purchase/plan-details/billing-period.jsx
client/me/purchases/purchase-item/index.jsx

These may not exist in some cases.

Safeguard method calls on moment objects

---

client/blocks/plan-storage/docs/example.jsx
client/blocks/plan-storage/test/bar.jsx
client/blocks/plan-storage/test/plan-storage.jsx
client/blocks/post-share/test/nudges.jsx
client/blocks/product-purchase-features-list/index.jsx
client/blocks/product-purchase-features-list/test/product-purchase-features-list.jsx
client/blocks/product-purchase-features-list/test/video-audio-posts.jsx
client/blocks/product-purchase-features-list/video-audio-posts.jsx

* Adds ecommerce plan checks to `/blocks`.
* Automated tests

Make /blocks aware of ecommerce plan

---

client/lib/domains/registration/availability-messages.js

Fixes a typo.
- Mock suggestions endpoint to return a maintenance
- Check message

Domains: Update typo in purchases disabled message

---

.circleci/config.yml
bin/get-circle-artifact-url.js
bin/get-circle-string-artifact-url
bin/get-jetpack-blocks-artifacts.js
bin/integration/get-jetpack-blocks-artifact-url.js

* Add `jetpack-blocks` bundle fetching from CircleCI build artifacts
* Add integretion test for bundle fetching
Try running locally:
```sh
node bin/get-jetpack-blocks-artifacts.js
```
You should see output like:
```
https://131196-45936895-gh.circle-artifacts.com/0/tmp/artifacts/jetpack-blocks/block-manifest.json
https://131196-45936895-gh.circle-artifacts.com/0/tmp/artifacts/jetpack-blocks/editor-beta.css
https://131196-45936895-gh.circle-artifacts.com/0/tmp/artifacts/jetpack-blocks/editor-beta.js
https://131196-45936895-gh.circle-artifacts.com/0/tmp/artifacts/jetpack-blocks/editor-beta.rtl.css
https://131196-45936895-gh.circle-artifacts.com/0/tmp/artifacts/jetpack-blocks/editor.css
https://131196-45936895-gh.circle-artifacts.com/0/tmp/artifacts/jetpack-blocks/editor.js …
```

Build: Get CircleCI jetpack-blocks artifacts

---

client/lib/signup/step-actions.js

Note: We should land this in conjunction w/ the account activation change proposed in D20847-code. 
* Set the `public` param to `-1` when the flow name is `import` & a URL is provided
* Unnest the logic for setting new site params so it's easier to read
* `prettier` changes d/t the unnesting
* Run this branch
* Complete an import via `/start/import`
* Confirm the new site is private and unlaunched
* Confirm the site is only launchable when account is verified

Import in Signup: Set the site to private by default

---

client/lib/signup/step-actions.js

Removes private by default while we sort out some issues. See p58i-7n2-p2.

remove private by default

---

client/gutenberg/extensions/presets/jetpack/package.json

Jetpack blocks: Bump to v10

---

client/gutenberg/extensions/publicize/connection.jsx
client/gutenberg/extensions/publicize/form-unwrapped.jsx

See title
Verify that the extension works as before.

 Publicize Gutenblock: Pass individual props to Connection component

---

client/blocks/inline-help/popover.jsx
client/blocks/inline-help/style.scss

Reverts Automattic/wp-calypso#28413

Revert "Gutenberg: Add Switch to Classic Editor button in Help popover"

---

client/lib/plans/constants.js
client/my-sites/plans-features-main/index.jsx
client/signup/steps/plans-atomic-store/index.jsx

* Adds features for eCommerce plan
* Try adding an eCommerce plan

Update eCommerce copy

---

client/my-sites/plans-features-main/index.jsx

* Removes ecommerce from plan lineup
* Check if plan is gone from lineup

Remove ecommerce from plan lineup

---

client/blocks/app-banner/utils.js

* Updates Strings in the Mobile App Banner, per @SylvesterWilmott's comments in https://github.com/Automattic/wp-calypso/pull/28440
Viewing the changes in the code should be sufficient.

Update App Banner Copy

---

client/gutenberg/extensions/tiled-gallery/edit.jsx

* Move initial state out of constructor
* No regressions in the block

Move state initialization out of constructor

---

client/lib/abtest/active-tests.js

We want to check how the vendor behaves when
changing the # of users.
Nothing to test really. Check the code.

Domains: Bump suggestions test distribution

---

packages/babel-plugin-i18n-calypso/package.json
packages/tree-select/package.json

This was the result of running:
```
git fetch
git checkout master
git reset --hard origin/master
git checkout -b publish/three
npx lerna version
#choose new verison numbers
NPM_CONFIG_OTP=12345 npx lerna publish from-git
```

Test publishing versions of tree-select and babel translation finder

---

client/components/checklist/style.scss
client/components/checklist/task.js
client/my-sites/checklist/wpcom-checklist/component.jsx
client/my-sites/checklist/wpcom-checklist/wpcom-task-list.js
config/desktop-development.json
config/desktop.json
config/development.json
config/horizon.json
config/production.json
config/stage.json
config/test.json
config/wpcalypso.json

This PR adds the first version of an email setup task to the onboarding checklist. For details on the task see p4CBkD-JE-p2 and p9j7e4-oo-p2. For corresponding server code, see D20607-code.
This task is behind a feature flag and is currently only enabled in development.json.
Make sure you have D20607-code patched on to your sandbox or that it is merged.
Note that on some sites, particularly old ones, the checklist will not render by default. To get around this, set the `shouldRender` prop on the `WpcomChecklist` component to `true`.
To test, begin by make a site that satisfies domain and email settings for each of these cases, then go to `https://wordpress.com/checklist/<site_slug>`, and verify that you see the described task behavior.
| Domain                                       | …

Onboarding Checklist: Add email setup task to the onboarding checklist

---

client/gutenberg/extensions/publicize/panel.jsx
client/gutenberg/extensions/publicize/settings-button.jsx

* Improve the copy above the Pubicize connections form.
* Improve the connect account button copy.
**Before**
**After**
* Start a new site from this link: `gutenpack-jn`.
* Connect the site, activate recommended features.
* Start a new post, add a title.
* Click the "Publish" button.
* Verify the new copy looks good.
Fixes #28845

Gutenberg: Improve Publicize copy

---

client/components/checklist/task.js
client/my-sites/checklist/wpcom-checklist/component.jsx

* Verify there is a first incomplete task before using it.
* Create site with a fresh WP.com user.
* Finish the checklist to 100%.
* Click "My SIte"
* Verify everything works well and WP.com doesn't error out.
cc @juliasydnor @katiebethbrown @kriskarkoski

Checklist: Check for first incomplete task before using it

---

client/lib/abtest/active-tests.js

Update the a/b test distribution.
/

Domains: Test non-en vendors

---

client/lib/signup/step-actions.js
client/signup/config/flows-pure.js
client/signup/config/steps-pure.js
client/signup/steps/site-information/index.jsx

* Readd the domains step as it breaks the flow.
* Go through the onboarding flow and confirm that it works
Reverts https://github.com/Automattic/wp-calypso/pull/28954

readd domains step

---

client/components/select-dropdown/README.md
client/components/select-dropdown/docs/example.jsx
client/components/select-dropdown/index.jsx
client/components/select-dropdown/style.scss
client/components/select-dropdown/test/index.js

Adds the ability to set the `SelectDropdown` component to be in a disabled state. Also updates doc examples.

SelectDropdown component - adds `disabled` state

---

packages/tree-select/package.json

Credit @samouri – https://github.com/Automattic/wp-calypso/pull/27627#discussion_r236013653
Update license – https://github.com/Automattic/wp-calypso/pull/29154#discussion_r239798754

Tree select: Update package info

---

assets/stylesheets/shared/_color-schemes.scss
client/components/card/style.scss

Update the border colors used by cards

Use border colors in cards

---

assets/stylesheets/shared/_color-schemes.scss

* fix color values where light & dark values were switched
* make sure lower values mean lighter and higher values mean darker colors (one possibility to check this is [color-studio](https://automattic.github.io/color-studio))

fix(color-schemes): switched colors light & dark

---

client/components/badge/style.scss

* Update `<Badge />` component styles to use CSS custom properties
* fix: switch light/dark success color for Classic Bright
* Have a look at `/devdocs/design/badge` to see if everything looks as expected
related to #28748

badge: update styles to use css custom properties

---

client/me/account/main.jsx

As reported on slack
fix for #29413

Fix missing bumpStat call

---

client/components/banner/style.scss

* Use CSS to define colors for the `<Banner />` component
* Open up [calypso.live deployment devdocs design banner component]
* design: review colors used for this component
related #28748

banner: update colors to use updated colors and css vars

---

client/gutenberg/editor/components/post-preview-button/index.jsx

P2 posts require a frame nonce to work, otherwise they throw a CORS error.
* Add the frame nonce to the preview link.
* Also make sure the preview link's `revisions` query param works like the [Classic editor version](https://github.com/Automattic/wp-calypso/blob/master/client/post-editor/post-editor.jsx#L391) (this doesn't seem to have any visible effects though? 🤔 ).
* Also disable the Preview button when the post `isCleanNew` (the preview wouldn't load in that state).
* Try previewing a P2 post, and make sure it works on both new and old posts, and on both it previews unsaved changes too.
* Try creating a new post, and make sure the Preview button is disabled until the content is changed.
Fixes #29540

Gutenlypso: Fix broken previews on P2

---

assets/stylesheets/directly.scss
assets/stylesheets/emergent-paywall.scss
client/components/forms/form-range/style.scss
client/devdocs/style.scss
client/extensions/woocommerce/app/order/order-activity-log/style.scss
client/extensions/woocommerce/app/products/product-form.scss
client/extensions/woocommerce/app/reviews/style.scss
client/extensions/woocommerce/components/bulk-select/style.scss
client/extensions/woocommerce/components/table/style.scss
client/extensions/woocommerce/woocommerce-services/components/checkbox/style.scss
client/extensions/woocommerce/woocommerce-services/views/shipping-label/label-purchase-modal/address-step/style.scss
client/jetpack-connect/style.scss
client/login/magic-login/style.scss
client/my-sites/checkout/concierge-session-nudge/style.scss
client/signup/steps/import-url/style.scss
client/signup/steps/survey/style.scss

This covers all of the easy ones.

Update plain blue-medium to color-primary

---

client/components/upgrades/google-apps/google-apps-dialog/users.jsx
client/my-sites/domains/domain-management/add-google-apps/add-email-addresses-card.jsx

Reverts:  https://github.com/Automattic/wp-calypso/pull/29460

Revert "Pre-populate Add G Suite fields for first user"

---

client/layout/sidebar/style.scss
client/reader/discover/style.scss
client/reader/following-manage/style.scss
client/reader/following/style.scss
client/reader/list-stream/style.scss
client/reader/search-stream/style.scss
client/reader/sidebar/_style.scss
client/reader/update-notice/_style.scss

Removes usages of --color-accent in the sidebar hover states and in the Reader in general.

Mostly remove accent color from reader and sidebar

---

client/gutenberg/editor/main.jsx

This PR adds _Page Templates_ to the _Page Attributes_ sidebar panel.
| - | - |
| ![screen shot 2018-12-18 at 18 37 02](https://user-images.githubusercontent.com/233601/50184488-01facc00-02f4-11e9-810c-f264ab16275e.png) | ![screen shot 2018-12-18 at 18 35 26](https://user-images.githubusercontent.com/233601/50184427-d972d200-02f3-11e9-8d85-7f098e747962.png) |
* Activate a Theme that supports _Page Templates_ on any of your sites.
* Tested on [`Dara`](https://wordpress.com/theme/dara) and [`Sela`](https://wordpress.com/theme/sela).
* Click on _Site Pages_ > _Add_ to create a new page.
* On Gutenlypso's sidebar, open the _Page Attributes_ panel.
* Verify that the _Template_ drop down includes the theme's templates.
Fixes #29542 
Fixes #28808

Gutenlypso: Adds support for page templates

---

client/signup/steps/site-topic/index.jsx
client/signup/steps/site-topic/style.scss
client/signup/style.scss

Trying out some of the ideas from the prototype to see how things feel:
@Automattic/onboarding-design @Automattic/onboarding-dev

Signup: Simplify `site-topic` step

---

client/blocks/site-address-changer/style.scss
client/components/email-verification/email-verification-dialog/style.scss
client/components/first-view/style.scss
client/components/formatted-header/style.scss
client/components/forms/form-label/style.scss
client/components/tinymce/iframe.scss
client/components/wizard/style.scss
client/extensions/woocommerce/woocommerce-services/components/settings-group-card/style.scss
client/mailing-lists/style.scss
client/my-sites/comments/comment/style.scss
client/my-sites/draft/style.scss
client/my-sites/theme/style.scss
client/reader/_style.scss
client/reader/post-excerpt-link/style.scss
client/reader/stream/_style.scss
client/signup/steps/design-type-with-store/style.scss
client/signup/steps/design-type/style.scss
client/signup/steps/reader-landing/style.scss

* Replace any occurrence of `darken( $gray, 20%? )` with `--color-neutral-500` 
* code: make sure those replacements are correct and each occurrence is replaced correctly
related #28748 
**Note:** stacked upon #29675

color-schemes: replace 'darken( $gray, 20 )' with '--color-neutral-500'

---

client/blocks/site-address-changer/style.scss
client/components/email-verification/email-verification-dialog/style.scss
client/components/first-view/style.scss
client/components/formatted-header/style.scss
client/components/forms/form-label/style.scss
client/components/tinymce/iframe.scss
client/components/wizard/style.scss
client/extensions/woocommerce/woocommerce-services/components/settings-group-card/style.scss
client/extensions/woocommerce/woocommerce-services/views/service-settings/shipping-services/style.scss
client/mailing-lists/style.scss
client/my-sites/comments/comment/style.scss
client/my-sites/draft/style.scss
client/my-sites/sharing/style.scss
client/my-sites/theme/style.scss
client/notifications/src/panel/boot/stylesheets/shared/buttons.scss
client/reader/_style.scss
client/reader/post-excerpt-link/style.scss
client/reader/stream/_style.scss
client/signup/steps/design-type-with-store/style.scss
client/signup/steps/design-type/style.scss
client/signup/steps/reader-landing/style.scss

* Replace any occurrence of `darken( $gray, 10%? )` with `--color-neutral-400` 
* code: make sure those replacements are correct and each occurrence is replaced correctly
related #28748 
**Note:** stacked upon #29673

color-schemes: replace 'darken( $gray, 10 )' with '--color-neutral-400'

---

client/gutenberg/extensions/simple-payments/edit.js
client/gutenberg/extensions/simple-payments/editor.scss
client/gutenberg/extensions/simple-payments/featured-media.js
client/gutenberg/extensions/simple-payments/index.js
client/gutenberg/extensions/simple-payments/product-placeholder.jsx
client/gutenberg/extensions/simple-payments/product-placeholder.scss

| Inital Empty State | Edit Product | Deselected View |
| - | - | - |
| ![inital state](https://user-images.githubusercontent.com/233601/49377199-424d2e00-f6e8-11e8-83cc-f259f64ac54e.png) | ![edit](https://user-images.githubusercontent.com/233601/49377238-63158380-f6e8-11e8-8ac7-256cc533e343.png) | ![screen shot 2018-12-03 at 10 27 29](https://user-images.githubusercontent.com/233601/49377252-6f99dc00-f6e8-11e8-95f1-eb56fe5608e8.png) |
| Gutenlypso | Jetpack / WP-Admin |
| - | - |
| ![gutenlypso](https://user-images.githubusercontent.com/233601/49378149-a96be200-f6ea-11e8-9906-98aeecc1c1ec.gif) | ![jetpack](https://user-images.githubusercontent.com/233601/49381096-f2736480-f6f1-11e8-98f7-a6455007ca01.gif) |
| Drag & Drop | Upload | Select from the Media Library | Edit | Remove |
| - | - | …

Gutenberg: Adds support for the media library to the Simple Payments block.

---

assets/stylesheets/shared/_color-schemes.scss
client/my-sites/activity/activity-log-banner/style.scss
client/my-sites/activity/activity-log-confirm-dialog/style.scss
client/my-sites/activity/activity-log-item/style.scss
client/my-sites/activity/activity-log/style.scss

Fix the grays in activity log.
Fixes #29688

Update colors for activity log

---

client/blocks/upwork-stats-nudge/index.js

Fixes tracks event name

---

client/lib/checkout/ebanx.js
client/lib/checkout/test/validation.js
client/lib/checkout/validation.js

This reverts commit a14b1422f56533f9d5a2da3f17d6e748659ddcef (#29350).
Seems like this was causing more issues that it was preventing
- Set currency to BRL
- In the checkout/credit card form, choose "Brazil" as your country.
- Enter valid and invalid phone numbers and submit the form. Examples of valid numbers: (85) 2284-7035, 31 7719-5565

Revert "Checkout: validate phone number for ebanx card details (#29350)"

---

client/gutenberg/extensions/tiled-gallery/constants.js
client/gutenberg/extensions/tiled-gallery/gallery-image/edit.js
client/gutenberg/extensions/tiled-gallery/gallery-image/save.js
client/gutenberg/extensions/tiled-gallery/layout/index.js
client/gutenberg/extensions/tiled-gallery/view.scss

Cleanup @TODO comments and move a constant to constants file.
* Just cleanup
* No regressions

Tiled gallery: Remove complete TODOs

---

client/gutenberg/extensions/tiled-gallery/constants.js
client/gutenberg/extensions/tiled-gallery/layout/mosaic/resize.js

* Moves a constant into shared constants file
* No regressions in mosaic layout

Tiled gallery: Move margin constant to constants

---

client/my-sites/domains/domain-management/add-google-apps/add-email-addresses-card.jsx
client/signup/navigation-link/index.jsx

* Just runs Prettier on two files.  These changes are cluttering up a PR moving changes here.
* No testing needed, just prettier formats

Prettier formatting changes

---

client/signup/steps/site-type/index.jsx
client/signup/steps/site-type/style.scss
client/signup/style.scss

Signup: Update site-type CSS

---

client/my-sites/themes/themes-banner/upwork.jsx

Edit upwork endpoint

---

client/my-sites/importer/importer-header/start-button.jsx

Use a normal button instead of a primary button when starting an import

---

assets/stylesheets/shared/_color-schemes.scss

Adds brand colours to colour schemes (should be no visual changes). 
1. Did I do this right? :sweat_smile: 
2. Do all values correspond and are they named appropriately? 
3. Are there typos?
(cc @flootr, @drw158, @blowery) 
Resolves #30052

Colour Scheming: Add Brand Colours

---

client/lib/abtest/active-tests.js

* This launches private by default to 50% of users

Launch private by default to 50%

---

client/my-sites/domains/domain-management/gsuite/gsuite-add-users/add-users.jsx

* Fixed typos
* Look at text changes

Fix typos in G Suite tracking

---

client/lib/abtest/active-tests.js
client/signup/config/steps-pure.js
client/signup/config/steps.js

* This removes the hide username test
See p5XAZ9-239-p2
- Open this branch in a new incognito window
- Check that you see a username field in signup
- Look at localStorage.ABTests in the console and check there's nothing for hideUsername

Remove the hide username test

---

config/development.json

* Enable the async-payments feature flag under development environments.
* N/A

Enable async payments in development

---

client/lib/abtest/active-tests.js

* Change concierge session upsell tests to 50/50
* Make sure tests pass

Change concierge upsell tests to 50/50

---

Dockerfile

May fix some hanging builds we're seeing?

Try limiting lerna bootstrap concurrency to 1 in docker

---

assets/stylesheets/_main.scss
assets/stylesheets/directly.scss
assets/stylesheets/emergent-paywall.scss
assets/stylesheets/shared/_colors.scss
assets/stylesheets/shared/mixins/_dropdown-menu.scss
client/blocks/edit-gravatar/style.scss
client/devdocs/design/typography.jsx
client/devdocs/style.scss
client/extensions/woocommerce/app/products/product-form.scss
client/extensions/woocommerce/components/table/style.scss
client/layout/sidebar/style.scss
client/my-sites/checkout/checkout-thank-you/style.scss
client/my-sites/domains/domain-management/gsuite/gsuite-purchase-cta/style.scss
client/my-sites/media-library/list-item.scss
client/my-sites/plan-features/style.scss
client/my-sites/sharing/style.scss
client/my-sites/themes/themes-banner/style.scss
client/notifications/src/panel/boot/stylesheets/main.scss
client/post-editor/editor-ground-control/style.scss
client/post-editor/media-modal/detail/style.scss

* Replace all plain occurrences of $gray-dark with CSS variables
* ~~Disable stylelint selector-max-id rule on _main.scss~~
* Navigate the calypso.live link and check if everything matches the current staging/production environments

Replace all plain occurrences of $gray-dark with CSS variables

---

client/lib/abtest/active-tests.js

Updates G Suite Plan AB Test Variations Weights

Updates G Suite Plan AB Test Variations Weights

---

client/lib/abtest/active-tests.js

Update dotbuilder A/B test variations weights.

Update dotbuilder A/B test variations

---

client/lib/analytics/ad-tracking.js

* add `value` and `transaction_id` to Donuts Gtag if available
* some naming conventions cleanup
To test this PR, you will need to buy a Donuts domain and watch the console for relevant log messages and Chrome's Network tab for the respective requests to Google. 
* start at a URL like https://hash-ec8cb2c01bcbcccf471b5eb550b9bdad89b657cd.calypso.live/start/domain-first?new=randomstring201901251653.business — it's important to use a TLD that is offered by Donuts such as `.business`
- open Chrome's inspector, enter `localStorage.debug = 'calypso:analytics:ad-tracking';`, and generally watch for console errors
- also make sure to accept the cookie banner should you be presented with it
- click "just buy a domain" when prompted
- on the pre-checkout screen (where you choose privacy protection …

Ad Tracking: add value and transaction_id to Donuts Gtag where available

---

config/stage.json

This PR adds the partial restore interface that has been tested in the wpcalypso environment to Staging.
Boot calypso dev, it should work. Review the one line code change for errors.

Rewind: Enable partial restores in staging

---

client/components/ribbon/style.scss

Fix ribbon accent colors

---

client/lib/abtest/active-tests.js
client/lib/signup/test/progress-store.js

Restrict the new onboarding experience test just to english audience
Eyeballing should suffice

Restrict onboarding test just to english audience for now

---

assets/stylesheets/directly.scss
assets/stylesheets/emergent-paywall.scss
client/components/button-group/style.scss
client/components/button/style.scss
client/components/diff-viewer/style.scss
client/components/forms/form-text-input-with-action/style.scss
client/components/marked-lines/style.scss
client/components/text-diff/style.scss
client/extensions/woocommerce/components/order-status/style.scss
client/my-sites/comments/comment/style.scss
client/my-sites/plugins/plugin-list-header/style.scss
client/my-sites/site-settings/jetpack-credentials/credentials-configured/style.scss
client/my-sites/stats/stats-list/style.scss
client/notifications/src/panel/boot/stylesheets/shared/buttons.scss
client/notifications/src/panel/boot/stylesheets/shared/colors.scss
client/post-editor/media-modal/index.scss

* Update remaining plain usages of `$alert-red`
* review color assignments and make sure they're correct
* make sure there's not typos for the new color names
**Note:** This merges into #30339

replace (some) of $alert-red with --color-error 

---

assets/stylesheets/shared/functions/_z-index.scss
client/gutenberg/editor/calypsoify-iframe.jsx
client/gutenberg/editor/controller.js
client/gutenberg/editor/style.scss
config/desktop-development.json
config/desktop.json
config/development.json
config/horizon.json
config/production.json
config/stage.json
config/test.json
config/wpcalypso.json

* Alternative take at https://github.com/Automattic/wp-calypso/pull/30307 which utilizes feature flags. If needed this will allow us for easier distribution of tasks and testing. To make this easier to grok, I tried to keep the amount of changes to a minimum, and avoided refactoring of existing flags for now.
- Same as https://github.com/Automattic/wp-calypso/pull/30307

Gutenberg: alternative take at Calypsoify iframe

---

client/lib/domains/dns/index.js
client/lib/domains/dns/test/data/index.js
client/lib/domains/dns/test/reducer.js

If no NS records, add default wp.com ones.
Follow D23395-code.

Domains: Add default wp.com NS records

---

client/lib/abtest/active-tests.js

Due to poor performance we'll be changing the price of the concierge session and restarting the upsell test.
* Restart the concierge session upsell test
* Make sure tests pass

Restart the concierge session upsell test

---

client/gutenberg/extensions/mailchimp/index.js

Updating strings suggested in https://github.com/Automattic/jetpack/issues/11297#issuecomment-461391754
Closes https://github.com/Automattic/jetpack/issues/11297
1. Add the block
1. Are the texts correctly updated?

MailChimp block: Update texts

---

client/gutenberg/extensions/wordads/edit.js
client/gutenberg/extensions/wordads/editor.scss
client/gutenberg/extensions/wordads/index.js

This PR intents to fix alignment issues found in the current WordAds block. 
The new block looks like this.
TBD...
Fixes #30623 
Fixes #30625

WordAds: Fix alignment issues

---

client/lib/abtest/active-tests.js
client/lib/signup/step-actions.js

This makes the private by default flow live for all users.
* Create a new site from http://calypso.localhost:3000/start
* Check that the site is private and has a launch banner

Launch Private by default to all users

---

client/components/upgrades/gsuite/gsuite-dialog/index.jsx
client/lib/abtest/active-tests.js

* Removes business plan AB test
* Go through new domain flow and add G Suite
* Can you checkout?

Removes G Suite Business Plan Ab Test

---

client/extensions/woocommerce/app/products/product-form-details-card.js

A bug was reported in p9F6qB-2xO-p2 which was resulting in the product edit pages from properly loading in Store.
- Open up Store on a test site
- Open a product to edit, confirm the page renders and you can update the product

Store: Use localize HOC in product details form

---

client/gutenberg/editor/calypsoify-iframe.jsx

Please see D24370-code for more details.
Testing instructions available in D24370-code.
Fixes https://github.com/Automattic/wp-calypso/issues/30774

Gutenframe: allow loading the editor in SU session

---

client/my-sites/checklist/wpcom-checklist/component.jsx

Fixed a couple of typos. 
* Nide work --> Nice work
* Excercise --> Exercise

Checklist: update typos in component.jsx

---

assets/stylesheets/directly.scss
assets/stylesheets/emergent-paywall.scss
assets/stylesheets/shared/_color-schemes.scss
assets/stylesheets/shared/_colors.scss
assets/stylesheets/shared/_forms.scss
client/components/spinner-line/style.scss
client/my-sites/plan-features/style.scss

* Remove remaining occurrences of `$gray-lighten-10` and replace it with `--color-neutral-200` CSS custom prop
* Make sure each variable is replaced with their equivalent CSS custom prop
* Make sure there's no occurrence of `$gray-lighten-10` left

color-schemes: remove remaining occurrences of $gray-lighten-10

---

assets/stylesheets/directly.scss
assets/stylesheets/shared/_animation.scss
assets/stylesheets/shared/_colors.scss
client/components/button-group/style.scss
client/components/dialog/style.scss
client/extensions/woocommerce/app/settings/email/mailchimp/style.scss
client/gutenberg/extensions/related-posts/style.scss
client/my-sites/checkout/checkout-thank-you/style.scss
client/post-editor/editor-gutenberg-opt-in-sidebar/style.scss
client/post-editor/style.scss
client/reader/list-gap/style.scss

* Remove remaining occurrences of `$gray-lighten-30` and replace it with `--color-neutral-0` CSS custom prop
* Make sure each variable is replaced with their equivalent CSS custom prop
* Make sure there's no occurrence of `$gray-lighten-30` left

color-schemes: remove $gray-lighten-30

---

client/gutenberg/extensions/slideshow/create-swiper.js
client/gutenberg/extensions/slideshow/edit.js
client/gutenberg/extensions/slideshow/slideshow.js
client/gutenberg/extensions/slideshow/style.scss
client/gutenberg/extensions/slideshow/swiper-apply-aria.js
client/gutenberg/extensions/slideshow/swiper-callbacks.js
client/gutenberg/extensions/slideshow/swiper-resize.js
client/gutenberg/extensions/slideshow/view.js

This PR will contain a series of accessibility improvements based on p1HpG7-6jw-p2. 
Changes so far:
JN link: https://jurassic.ninja/create/?gutenpack&calypsobranch=try/slideshow-a11y

Slideshow: Accessibility Improvements

---

client/gutenberg/extensions/business-hours/index.js

Split from #30996
* Adds a block description
* Add the block, select it, and open the sidebar. You'll see the description.

Business Hours Block: add a description

---

assets/stylesheets/shared/_color-schemes.scss
client/blocks/color-scheme-picker/constants.js
client/blocks/color-scheme-picker/style.scss
client/state/preferences/schema.js
config/development.json
config/wpcalypso.json
public/images/color-schemes/color-scheme-thumbnail-nightfall.svg

* Adds a new color scheme to the admin, "Nightfall"
*

Color Schemes: Add Nightfall color scheme

---

client/lib/domains/gsuite/test/index.js

* Adds test to G Suite lib
* Run tests:  `npm run test-client -- --testPathPattern client/lib/domains/gsuite/`

Adds tests to G Suite lib

---

client/my-sites/sharing/connections/mailchimp-settings.jsx
client/my-sites/sharing/style.scss

This explains what to next post connection
1. Connect mailchimp
2. Choose a list
3. See instructions

Mailchimp: Explain what to do next

---

client/gutenberg/extensions/contact-info/email/save.js

In this PR we imorive email validation by using the well used email validation function. 
1. Add the contact info block
2. Does email appear as expected in the email block.

Contact Info Block: Improve email validation

---

client/gutenberg/extensions/business-hours/components/day.jsx
client/gutenberg/extensions/business-hours/editor.scss

Small visual tweaks to improve the overall experience of the block whilst editing
__Before__
__After__

Business Hours: Update editor styles for consistency with UI elements

---

assets/stylesheets/shared/_color-schemes.scss
assets/stylesheets/shared/_colors.scss
client/components/happychat/style.scss
client/components/theme/style.scss
client/components/upgrades/gsuite/gsuite-dialog/style.scss
client/devdocs/style.scss
client/jetpack-connect/jetpack-new-site/style.scss
client/my-sites/domains/domain-management/style.scss
client/my-sites/plan-compare-card/style.scss
client/my-sites/plan-features/style.scss
client/my-sites/theme/style.scss

Revert "color-schemes: remove $gray-dark"

---

assets/stylesheets/shared/_color-schemes.scss
client/blocks/color-scheme-picker/constants.js
client/blocks/color-scheme-picker/style.scss
client/state/preferences/schema.js
config/development.json
config/wpcalypso.json
public/images/color-schemes/color-scheme-thumbnail-sakura.svg

* Adds a new color scheme, Sakura, to Calypso.
* TBD

Color Schemes: Add Sakura color scheme

---

config/horizon.json

This PR turns on the Gutenframe feature flag for Horizon.
Not much to test here. If something breaks it'll be pretty evident.

Gutenframe: sets the gutenframe feature flag on for Horizon.

---

assets/stylesheets/_components.scss
client/me/reauth-required/index.jsx

Migrate the Reauth Required, part of #27515. 
Trigger the reauth required pop-up (you can visit the `/me` route with 2FA on). Do those styles look okay? 
cc @jsnajdr

Migrate Reauth Required Styling Imports

---

client/lib/domains/email-forwarding/index.js
client/lib/domains/email-forwarding/test/index.js

* Fixes logic for `getEligibleEmailForwardingDomain`
* Run tests

Fixes getEligibleEmailForwardingDomain logic

---

assets/stylesheets/shared/_colors.scss
assets/stylesheets/shared/_extends.scss
assets/stylesheets/shared/_welcome.scss
assets/stylesheets/shared/functions/_overflow-gradient.scss
client/blocks/inline-help/style.scss
client/blocks/login/style.scss
client/blocks/reader-share/style.scss
client/components/keyed-suggestions/style.scss
client/components/section-nav/style.scss
client/components/site-title-example/style.scss
client/components/theme/style.scss
client/components/upgrades/gsuite/gsuite-dialog/style.scss
client/components/web-preview/style.scss
client/extensions/woocommerce/app/promotions/fields/style.scss
client/extensions/woocommerce/app/settings/email/mailchimp/style.scss
client/extensions/woocommerce/components/table/style.scss
client/my-sites/exporter/style.scss
client/my-sites/pages/style.scss
client/my-sites/stats/stats-list/style.scss
client/my-sites/theme/style.scss
client/my-sites/themes/themes-magic-search-card/style.scss
client/post-editor/editor-gutenberg-opt-in-dialog/style.scss
client/post-editor/media-modal/dialog.scss
client/reader/style.scss
client/signup/steps/clone-point/style.scss

* Remove remaining usages of `$gray-light`
**code**:
- make sure each assignment is correct and there are no typos
- make sure there are no occurrences left of `$gray-light` in Calypso code
**visually:**:
- smoke test Calypso and make sure none of the new gray usages look wrong

color-schemes: remove $gray-light

---

client/gutenberg/extensions/presets/jetpack/package.json

* Update blocks to a new version for the 7.1.1 release
* See https://www.npmjs.com/package/@automattic/jetpack-blocks

Jetpack Blocks: update for Jetpack 7.1.1 release

---

client/layout/masterbar/style.scss
packages/calypso-color-schemes/src/shared/_colors.scss

Remove jazzy orange :jazz

---

client/lib/media/constants.js
client/my-sites/media-library/list-item-image.jsx
client/my-sites/media-library/list-item-video.jsx
client/my-sites/media-library/list-item.jsx
client/my-sites/media-library/test/list-item-image.jsx
client/my-sites/media-library/test/list-item-video.jsx

Fixes #27446
---
Not entirely sure how to test. Removing the references and compiling doesn't seem to have any impact on a local compile. 
---
Let me know if you'd like me to change/look at anything else 🙏

Removed MEDIA_IMAGE_PHOTON References from codebase

---

assets/stylesheets/_components.scss
client/me/social-login/index.jsx

Migrate the Social Login styling as part of #27515.
Load the `me/security/social-login` route, does everything look the same? cc @jsnajdr

Migrate Social Login Styling Imports

---

.eslintrc.js
test/e2e/config/default.json
test/e2e/lib/driver-helper.js
test/e2e/lib/driver-manager.js
test/e2e/lib/mocha-hooks.js
test/e2e/lib/override-abtest.js
test/e2e/specs/wp-signup-spec.js

*Pulling in latest from wp-e2e-tests repo
Ensure CircleCI jobs pass

Pull recent test changes from wp-e2e-tests

---

.circleci/config.yml
test/e2e/lib/video-recorder.js
test/e2e/run.sh

* This moves the e2e test assets to the correct location after the tests completes.
Ensure artifacts for e2e reports and screenshots(if applicable) are shown in CircleCI

Try to fix e2e artifacts

---

client/lib/domains/email-forwarding/index.js

* Fixes logic to ensure selected site is used if valid.
* Have a non-primary site that does not have G Suite
* Goto domains -> domain -> email
* Is link to Email Forwarding correct.

Fixes forwarding domain logic

---

client/lib/cart-values/cart-items.js
client/lib/cart-values/index.js
client/lib/domains/constants.js
client/lib/products-values/index.js
client/my-sites/checkout/cart/cart-item.jsx
client/my-sites/checkout/checkout/test/domain-details-form.js
client/signup/steps/plans-atomic-store/test/index.jsx
client/signup/steps/plans/test/index.jsx
test/e2e/lib/components/secure-payment-component.js

We've removed privacy completely, and now the code
needs a nice cleanup. :)
Run tests.
Grok/search.
👀

Domains: Remove domain privacy helper functions

---

client/lib/purchases/assembler.js
client/lib/purchases/index.js
client/my-sites/domains/domain-management/transfer/transfer-out/locked.jsx
client/my-sites/domains/domain-management/transfer/transfer-out/unlocked.jsx
client/state/purchases/test/selectors.js
client/state/sites/domains/README.md
client/state/sites/domains/assembler.js
client/state/sites/domains/schema.js
client/state/sites/domains/test/fixture/index.js

Not being used anymore. Removing, in both
domains and purchases.
Run tests.
Grok/search.
👀

Domains: Cleanup hasPrivacyProtection variable

---

client/gutenberg/editor/calypsoify-iframe.jsx

Related: D24770-code
When the block editor opens the Calypso media modal from within its
iframe we have been sending back media selections through the same
channel as we use to signal control flow: that is, we say "use this
image" in the same place we say "open the media modal."
In an attempt to separate out types of messages and remove some manual
accounting I have started sending a new purpose-built `MessageChannel`
in D24770-code which is used only once and only for selecting the media
item from the Calypso media modal.
With that patch applied we should be able to see this communicating
separately from the main information stream.
**Testing**
With D24770-code applied, make sure that things continue to operate
as expected with the media modal.

Block Editor Media Modal: Use new custom MessageChannel for selection

---

test/e2e/lib/pages/settings/importer-page.js
test/e2e/specs/wp-theme-switch-spec.js

*This updates a selector that was changed
* Ensure that the test `Verify Import Option` passes in full suite of tests and when run locally

Fix failing import test

---

assets/stylesheets/_components.scss
bin/categorize-component-styles.js

Adds a little utility that tries to score remaining component styles to migrate.

Add a component style categorizer

---

client/me/help/main.jsx
client/my-sites/themes/theme-showcase.jsx

Changes source params on Upwork banners

Update Source params

---

client/my-sites/importer/importer-action-buttons/action-button.jsx
client/my-sites/importer/site-importer/site-importer-site-preview.jsx
test/e2e/lib/pages/import-page.js

This PR seeks to fix a failing e2e test, caused by class name changes in #31364

e2e Tests: Fix failure introduced in #31364

---

.circleci/config.yml

* This disables the scheduled Jetpack test runs until the tests can be fixed

Disabling Jetpack e2e test runs

---

client/lib/abtest/active-tests.js
test/e2e/config/default.json
test/e2e/specs/wp-signup-spec.js

* Set improved onboarding test to 100% for all English users. See p5XAZ9-2cl-p2 for more detail.
* Clear abtest assignment to ensure updated variation applies.
```
localStorage.removeItem('ABTests'); // run this in browser console
```
* Create a website from `/start`.
* You should be involved in the improved onbording flow. The first step will look as below.

Signup: roll out improved onboarding test to all English users

---

.circleci/config.yml

* This adds the slack orb to provide status for e2e builds in appropriate slack channels
* Build in circleCI and look for messages from 'e2e-status'

Try Reporting e2e results to proper slack channel

---

packages/calypso-build/webpack/file-loader.js
webpack.config.js

Extract the file loader into a shard
Confirm Calypso runs/builds
Fixes #31505

Extract the file loader into a shard

---

client/my-sites/domains/components/domain-warnings/index.jsx

* Fixes linting issue by adding block to scope const declaration
* Get a domain into transferStatus === PENDING_OWNER
* Observe domain warning is correct

Fixes linting issue

---

packages/calypso-build/package.json
packages/format-currency/package.json

Prepping packages for initial publish.
CC: @Automattic/gutenpack

Update package versions for release

---

packages/format-currency/package.json

Make it public

---

client/my-sites/sharing/connections/service-action.jsx
client/my-sites/sharing/style.scss

We are waiting for the link to put in the form

Mailchimp: signup button

---

client/signup/steps/about/style.scss
client/signup/style.scss

Signup: Update card design on `/start/about`

---

client/blocks/product-purchase-features-list/index.jsx
client/my-sites/plans/current-plan/header.jsx
client/my-sites/plans/current-plan/style.scss

* My Plan: reorder plan feature cards to highlight focus on security and performance
* Fixes #31357 
1. Create a [new Jurassic Ninja site](https://jurassic.ninja/create/?shortlived).
1. Start the connection and select the Free plan.
1. Spin up this PR or use the calypso.live link below.
1. Go to `/plans/my-plan/SITE_URL`.
1. Make sure everything looks good and works on that page.
1. Repeat steps 5 and 6 for all plans: Personal, Premium, Professional.

My Plan: reorder plan feature cards to highlight focus on security and performance

---

client/layout/masterbar/oauth-client.scss

The intention of this PR is to make the WooCommerce connect screen on mobile devices, well, something more than what it currently is...which is a bit of a mess. 
I'm not too certain about the specific design sought, so I've tried to keep it simple and what looks best to me. This ultimately is just intended to be an improvement from current. 
Try the flow when clicking "Get started" on woocommerce.com. Does it look good, at least better than current, on mobile devices? Does the code look good? Unfortunately, word break also causes issues breaking the URL so avoiding that in favour of font size. 
**Current:**
**Proposed:**
Fixes #31048

WooCommerce Signup: Add Responsiveness

---

client/state/data-getters/index.js

No longer used, removing so we don't encourage client side tax math.
* Removes `requestTaxRate`
* N/A, method shouldn't be used anywhere

Remove tax rate request method

---

client/blocks/inline-help/index.jsx
client/my-sites/checklist/wpcom-checklist/component.jsx
client/state/inline-help/reducer.js

Reverts Automattic/wp-calypso#31792

Revert "Persist inline help when it is re-opened"

---

client/signup/steps/site-information/index.jsx
client/signup/steps/site-information/style.scss
client/signup/steps/site-information/test/__snapshots__/index.js.snap
client/signup/steps/site-topic/form.jsx
client/signup/steps/site-topic/style.scss

Signup: Try using a Gridicon in place of the "Continue" label

---

client/gutenberg/editor/calypsoify-iframe.jsx

We have been using the general iframe communications channel for
communicating selected revisions.
In this patch we're using a new custom `MessageChannel` to separate
and isolate the communication to fall in line with the way the other
extensions in the iframe bridge work.
**Testing**
1. Sandbox a site and load the block editor.
2. Apply D26217-code to sandbox.
3. Open the post revisions from within the editor.
4. Confirm that it opens the Calypso revisions dialog
5. Stop sandboxing site and repeat tests to confirm that this works without the backend patch applied.

Block Editor: Use custom `MessageChannel` for post revisions

---

client/components/checklist/README.md
client/components/checklist/docs/example.jsx
client/components/checklist/style.scss
client/components/checklist/task.js

* Introduce an in-progress state to checklist tasks.
We need this for the Jetpack checklist project, see p5XAZ9-2c7-p2 for more details.
* Checkout this branch and build Calypso.
* Go to http://calypso.localhost:3000/devdocs/design/checklist
* Verify the new third task looks and works well.
* Verify the existing 2 tasks still look and work well, too.
* Test the checklist in an existing site, and verify it still works well and unchanged.

Components: Add in-progress state to checklist tasks

---

client/my-sites/checklist/wpcom-checklist/component.jsx

* Opens G Suite ToS flow dialog instead of directly linking out to Google login.
* Have account with G Suite that has not accepted ToS
* Goto Stats page
* Goto Checklist
* Click 'You set up email for your site'
* Observe ToS flow dialog

G Suite: Checklist item open dialog not direct to login

---

client/lib/abtest/active-tests.js
client/lib/signup/page-builder.js
config/development.json
config/stage.json

Reverts Automattic/wp-calypso#31981

Revert "Signup: enable page builder mvp test"

---

client/lib/abtest/active-tests.js
client/lib/signup/page-builder.js
config/development.json
config/stage.json

This will merge the changes from #31981 again, except allowing existing users this time.

Signup: enable page builder mvp test (take two)

---

packages/wordpress-external-dependencies-plugin/package.json

WP Webpack deps: Publish package

---

client/my-sites/checkout/concierge-session-nudge/index.jsx

* There was a suggestion from Happiness to improve one sentence in this page for clarification.
You can access the page directly at `https://wordpress.com/checkout/YOURSITE/add-support-session` - just swap out the site for your own.

Copy fix for Concierge upsell offer.

---

client/extensions/woocommerce/app/settings/email/mailchimp/getting-started.js
client/extensions/woocommerce/app/settings/email/mailchimp/setup-steps/log-into-mailchimp.js
client/extensions/woocommerce/app/settings/email/mailchimp/setup-steps/store-info.js
client/my-sites/feature-upsell/plugins-upsell.jsx
client/my-sites/feature-upsell/themes-upsell.jsx
client/my-sites/sharing/connections/service-description.jsx
client/my-sites/sharing/connections/service-examples.jsx

* This is just a text change from MailChimp to Mailchimp.
* I'm not sure of all the places this is used
Fixes #31522

Update MailChimp casing to Mailchimp

---

packages/calypso-build/package.json

* Needed so we can release a new version of the package to include #32024, which is needed for https://github.com/Automattic/jetpack/pull/11949.
Nothing to see here.

Packages: Bump calypso-build to 1.0.0-alpha.4

---

client/my-sites/site-settings/jetpack-credentials/credentials-setup-flow/index.jsx

This PR is an attempt to fix failing tests in https://github.com/Automattic/wp-calypso/pull/29945 . Please refer to that PR for testing instructions. Already tested/reviewed/approved over there.

Rewind Credentials: Re add the credentials-setup-flow component styles

---

client/state/data-getters/index.js

* Remove unnecessary Gutenlypso functions from data-getters
@enejb, @ockham: I've included you in the reviewers because you added the `requestGutenbergBlockAvailability` function for Jetpack Blocks.
I haven't found any uses for that as well so I've removed it, but I'd like a confirmation from you first.
* Not sure? None of those functions are called anywhere else...

Remove Gutenlypso data-getters leftovers

---

client/my-sites/people/index.js
client/my-sites/people/invite-people/index.jsx

* Add a /sent path after a user invites a new user
* Load HotJar code
* Have dev tools open
* Goto site
* In left menu next to People click Add
* Add a user
* Observe '/sent' is added to end of path
* Observe hotjar-*.js is loaded in network panel

After inviting user change path

---

client/my-sites/site-settings/controller.js

Currently, we pull all query arguments out of the URL when browsing to the import section and put them into the state tree via context.  This is an artifact of the way we use the hybrid flux / redux setup to determine which screen to show.
A side-effect of this is that we clobber other query args that do not relate to importers directly.  A particularly problematic one is the `flags` param.  This is preventing us from enabling flags directly on importer URLs we send around to test features in development.
* Only call `page.replace` if extracted args are present
* Allow "unextracted" args to remain
* Clarify the comment
* Make sure you don't have an import "in progress"
* Directly browse to `http://calypso.localhost:3000/settings/import/<yourtestsite.wordpress.com>?engine=wix&flags=+test-im …

Importers: Allow non-importer query args to remain if present

---

client/lib/abtest/active-tests.js
client/lib/google-apps/index.js
client/my-sites/email/gsuite-purchase-cta/index.jsx
client/my-sites/email/gsuite-purchase-cta/sku-info.jsx
client/my-sites/email/gsuite-purchase-cta/style.scss
client/my-sites/email/gsuite-purchase-cta/test/__snapshots__/index.js.snap
client/my-sites/email/gsuite-purchase-cta/test/__snapshots__/sku-info.js.snap
client/my-sites/email/gsuite-purchase-cta/test/index.js
client/my-sites/email/gsuite-purchase-cta/test/sku-info.js

* Create Four Variations of the G Suite Purchase CTA for customers using `USD`
* Hide G Suite Business - No Monthly Prices ( Current/Control )
* Show G Suite Business - No Monthly Prices
* Hide G Suite Business - Show Monthly Prices
* Show G Suite Business - Show Monthly Prices
Screenshots:
**Hide G Suite Business - No Monthly Prices ( Current/Control )**
**Show G Suite Business - No Monthly Prices**
**Hide G Suite Business - Show Monthly Prices**
**Show G Suite Business - Show Monthly Prices**
**TIP:** IF you are having issues with the abtests info can be printed to console by running `localStorage.setItem( 'debug', 'calypso:abtests' )`
1. Make sure you use a test account using `USD`
1. Navigate to Navigate to `/email/:domain/manage/:siteSlug` for a domain and site without G Suite
1. …

G Suite CTA A/B Test

---

client/signup/config/flows-pure.js
client/signup/config/flows.js

I'm not convinced this is the best approach. I think the server returns the redirect value so we should use that... Still investigating...
*
*
Fixes #

Clean up the OAuth signup flow

---

client/lib/gsuite/index.js
client/me/purchases/product-link/index.jsx

* Adds function comments to G Suite lib function
* Renames one function from Google Apps
* Flip around G Suite views and ensure everything looks normal.

Add function comments to lib/gsuite

---

client/me/help/help-contact/index.jsx

* Adjust notice closure hours per Happiness.

Live Chat: adjust closure notice for Easter 2019

---

client/my-sites/email/gsuite-purchase-cta/index.jsx
client/my-sites/email/gsuite-purchase-cta/test/index.js

* Mergin PRs out of order introduced a missing variable, fix that
1. Confirm `npm run test-client` passes below

Fix G Suite Component

---

config/production.json

Turn on the nav drawer feature flag in production.

Toggle nav drawer feature flag in production.

---

client/components/domains/domain-registration-suggestion/index.jsx
client/components/domains/domain-suggestion/style.scss
client/components/info-popover/index.jsx
client/lib/domains/index.js
client/lib/url/support.js
client/my-sites/checkout/checkout/checkout-terms.jsx
client/my-sites/checkout/checkout/domain-registration-hsts.jsx
client/my-sites/checkout/checkout/style.scss

We're onboarding new TLDs soon, and they require some
UI changes. Show notice for HSTS requirement now.
- Hack `isHstsMandatory` to `return true;` for a specific TLD
- Check domain search results
- Check for all screen sizes
Dependency: D27031-code

Domains: Add notice for specific TLDs requiring HSTS

---

test/e2e/lib/pages/accept-invite-page.js

* Fixes invites tests broken by #32473 
* Ensure invites e2e tests pass

Fix broken invites e2e tests

---

client/components/head/index.jsx
client/components/head/test/__snapshots__/index.jsx.snap

For accessibility reasons we shouldn't prevent scaling. See #2003.
* Open the http://calypso.localhost:3000 in chrome, (or a mobile browser)
* Open up the mobile simulator
* Check that you can now zoom the page

Remove the maximum scale limitation

---

client/my-sites/marketing/tools/index.tsx

* Adds Looka Marketing Tools card
* Go to Marketing tools page an observe Looka card.
* Make sure it clicks out to Looka.

Add Looka card to the Marketing Tools page

---

client/my-sites/customize/main.jsx

* Listen for a `saved` command via postMessage bus
* move the `requestSite` from the `goBack` function to a function attached to the above
* See D27525-code

Customizer: Listen for saved event & fetch site

---

client/lib/abtest/active-tests.js
client/lib/plans/plans-list.js

This test was launched 2 years ago and slipped between the cracks perhaps because it was inconclusive. It looks to me that relatively minor changes rarely have a measurable impact and choices should be made based on things other than revenue and conversion metrics.
Remove an old test
Go to logged in /plans
See if the plan descriptions are visible and make sense
Fixes #

End an old A/B Test

---

client/my-sites/sites/index.jsx

* Correct inline comments that should have been updated as part of https://github.com/Automattic/wp-calypso/pull/32733.
* Smoke test for regressions, if you really want to?..

Site Selector: Update stale inline comments.

---

client/my-sites/checklist/wpcom-checklist/component.jsx

* Fixes a string concat introduced #30213 which makes it impossible for some languages (like French or Spanish) to display a good translation.
* See #30213, make sure the title text stays the same

Checklist: Replace string concat with whole sentences

---

apps/wpcom-block-editor/src/common/rich-text.js

It seems only one `formatType` at a time can register itself for controlling a bare `span` element. Since `core/underline` is keyboard-only, we unregister it once we see it become available (using `setInterval` because there does not appear to be an appropriate hook point).
* Unregister `core/underline` before registering our `wpcom/underline` button
* sandbox `widgets.wp.com` and a WP.com Simple site
* Apply D27908-code and D27605-code to your sandbox
* Open the editor on a WP.com Simple site. Verify that the console error below is not shown and that the underline button appears when editing the paragraph block 
* Test for the same on a Jetpack site, using Jetpack master and either WP 5.2 RC2 or the latest Gutenberg release.
Fixes #32747

Block Editor: unregister `core/underline` before registering our own

---

config/desktop-development.json
config/production.json
config/stage.json

Reverts Automattic/wp-calypso#32860

Revert "Gutenframe: Add Gutenframe to production and the desktop development environments."

---

test/e2e/specs-i18n/search-wordpress-on-google.js

* Google is blocking us on this check, so we will just disable the test see p1557031833102500-slack-acquisition-sem
cc @akirk
* Nothing to test just make sure the skip is there

Skip i18n google tests since they are blocking us

---

client/lib/abtest/active-tests.js

* Set `allowExistingUsers: true` & `localeTargets: 'any'` for the `improvedOnboarding` test.
* Reasonableness check
* The directives should be specified properly according to design plans
* The staging behavior should match expectations pre-deploy

Signup: Open improvedOnboarding to existing & non-en-locale users

---

config/desktop-development.json
config/production.json
config/stage.json

* Deploy Gutenframe to production (staging and desktop development as well).
See: p3fqKv-6Hh-p2 (phase 2)

Gutenframe: Activate Gutenframe in production.

---

client/blocks/product-purchase-features-list/mobile-apps.jsx

Minor improvement to copy. I considered removing "all", but then thought it added context, so I add the word "of" to help the sentence flow better.

Minor copy update on plans page

---

client/my-sites/checkout/checkout-thank-you/google-voucher/terms-and-conditions.jsx

* Updates the date for the Google AdWords credits ToS
* Have site with business plan that doesn't have adwords credits
* Goto plan features screen
* Click generate
* Observe date in ToS

Update Google AdWords Expiry Date

---

packages/load-script/package.json

* Adds dependencies I forgot to include.
* Not sure? Run `npm install` and make sure everything works ok?

Add dependencies for load-script

---

client/components/purchase-detail/style.scss
client/my-sites/marketing/controller.js
client/my-sites/marketing/index.js
client/my-sites/marketing/main.jsx
config/development.json
config/wpcalypso.json

* Removes config flag for Marketing Tools thus publishing the tab.
* Goto a site
* In the left menu click tools->marketing
* does the page appear?
* Refresh
* does the page appear?

Show marketing tools page

---

config/desktop-development.json
config/desktop.json
config/horizon.json
config/production.json
config/stage.json
test/e2e/specs-jetpack-calypso/wp-jetpack-connect-spec.js

* Switch Jetpack checklist to production in all environments.
* Disable some Woo-Jetpack tests that were failing prior to this PR already. p1558593446013600-slack-e2e-testing-discuss
E2E CI passes?

Jetpack checklist: enable

---

client/my-sites/plans/current-plan/current-plan-thank-you-card/free-plan-thank-you-card.js

Fix showing continue button for free sites on jetpack connect-flow

---

apps/full-site-editing/full-site-editing-plugin/starter-page-templates/class-starter-page-templates.php
apps/full-site-editing/full-site-editing-plugin/starter-page-templates/page-template-modal/styles/starter-page-templates-editor.scss

Ensure layout of Template selector modal is appropriate across all viewport sizes.
* Create new Page
* Resize viewport to ensure Modal looks ok across various screen sizes
Note that more Templates have been added to better simulate the true number of Templates we'll ultimatelty be dealing with.

Fixes Template selection modal on small viewports

---

client/lib/abtest/active-tests.js
client/my-sites/checkout/checkout/index.jsx

* Removing old unused test definition.

Removing unused test

---

apps/full-site-editing/full-site-editing-plugin/starter-page-templates/class-starter-page-templates.php

- adds updated generic visual indicators for page templates.

Update visual indicators

---

apps/full-site-editing/full-site-editing-plugin/readme.txt

Adds a readme.txt file in order to be able to submit this plugin to the directory.
See #33349.

FSE: Get plugin ready for directory submission

---

client/components/purchase-detail/index.jsx
client/components/purchase-detail/style.scss
client/components/purchase-detail/test/index.jsx
client/lib/abtest/active-tests.js
client/my-sites/checkout/checkout-thank-you/business-plan-details.jsx
client/my-sites/checkout/checkout-thank-you/domain-registration-details.jsx
client/my-sites/checkout/checkout-thank-you/ecommerce-plan-details.jsx
client/my-sites/checkout/checkout-thank-you/index.jsx
client/my-sites/checkout/checkout-thank-you/personal-plan-details.jsx
client/my-sites/checkout/checkout-thank-you/premium-plan-details.jsx
client/my-sites/checkout/checkout-thank-you/style.scss

* Removes this abtest https://github.com/Automattic/wp-calypso/pull/30677
* Follow instructions in original test

Removes G Suite post checkout AB Test

---

client/components/domains/registrant-extra-info/ca-form.jsx

Links change, so we update.
- Try to register a .ca domain
- Fill in the domain contact info
- Continue
- Click the `CIRA Registrant Agreement` and make sure it resolves

Domains: Update .ca registrant agreement

---

apps/full-site-editing/full-site-editing-plugin/full-site-editing-plugin.php

Brings plugin header in line with the current version in the Plugin Directory.

FSE: Update plugin header to reflect repo plugin

---

client/me/memberships/main.jsx
client/me/memberships/subscription.jsx
client/me/purchases/index.js
client/me/purchases/paths.js
client/me/purchases/purchases-list/header/index.jsx

https://wordpress.com/me/purchases/pending
**BEFORE**
**AFTER**
We're changing the name of this feature from "Memberships" to "Recurring Payments". We need to upgrade a few screens accordingly.

Updates to "My Memberships" tab

---

config/development.json
config/horizon.json
config/production.json
config/stage.json
config/test.json
config/wpcalypso.json

This releases Recurring Payments earn section (/earn/payments) to all environments
- build
- you shoult see in /earn :

Recurring Payments: Release

---

client/components/tinymce/index.jsx
client/components/tinymce/plugins/insert-menu/menu-items.jsx
client/components/tinymce/plugins/simple-payments/shortcode-utils.js

This should have been a part of #33518
The flag has booted up the old code used in previous tinymce approach and we don't want that.
This PR removes this old approach so tinymce does not fatal
[replace with your site]
Go to http://calypso.localhost:3000/post/artpitesting102com.wordpress.com?set-editor=classic
Should work.
Currently on staging it wont.

Recurring payments: Remove memberships support

---

assets/stylesheets/_components.scss
client/my-sites/plans-features-main/index.jsx

* Migrate plan-features-main
* Make sure the plans features list on the plans page  still looks good

CSS Migration - plans-features-main

---

assets/stylesheets/_components.scss
client/my-sites/plan-interval-discount/index.js

* Update plan-interval-discount for CSS migration
* Check plans page while connecting Jetpack and and ensure the styling still looks good

CSS Migration - plan-interval-discount

---

client/my-sites/earn/memberships/products.jsx
client/state/data-layer/wpcom/sites/memberships/index.js

1. Allow for changing "ALlow multiple"
2. Fix aggressive error msg
3. Copy

Recurring payments: Edit flow

---

assets/stylesheets/_components.scss
client/blocks/video-editor/index.jsx
client/blocks/video-editor/style.scss

* Migrate Video Editor css
* Go to media, select a video, and edit thumbnail. Make sure the modal is looks correct

CSS: migrate video editor

---

apps/full-site-editing/full-site-editing-plugin/starter-page-templates/class-starter-page-templates.php

Adds a locale parameter when requesting page templates.
See #33490.

FSE: Pass locale when requesting templates

---

client/blocks/app-promo/style.scss

Updated style.scss for fixing margin on desktop app promo banner

---

client/jetpack-connect/style.scss

Deploy changes from https://github.com/Automattic/wp-calypso/pull/32456  by @torres126  (already reviewed + accepted).
These commits specifically: https://github.com/Automattic/wp-calypso/pull/32456/commits/a9f350cebaa7020dd3ad90c8a5f4f89acd5016b5 https://github.com/Automattic/wp-calypso/pull/32456/commits/fdb0efc450d01b07b37dbfb3b63bafc404981c57
That PR is from remote origin not owned by me and I borged the rebase. Instead of fixing, this is just a quick deploy. 🤷‍♂ 
Fixes https://github.com/Automattic/wp-calypso/issues/32447
Closes https://github.com/Automattic/wp-calypso/pull/32456

Jetpack Connect: Centre Plan Pill

---

client/my-sites/checklist/wpcom-checklist/component.jsx

* Add a mapping from task slug `front_page_updated` to:
* the render function
* a destination URL
* Add the rendering function `renderFrontPageUpdatedTask`
* See D29075-code

Checklist: Handle new `front_page_updated` task from server

---

apps/full-site-editing/full-site-editing-plugin/full-site-editing-plugin.php
apps/full-site-editing/full-site-editing-plugin/full-site-editing/blocks/navigation-menu/index.php
apps/full-site-editing/full-site-editing-plugin/full-site-editing/class-full-site-editing.php
apps/full-site-editing/full-site-editing-plugin/full-site-editing/utils/class-a8c-wp-template.php
apps/full-site-editing/full-site-editing-plugin/full-site-editing/utils/replace-template-parts.php
apps/full-site-editing/full-site-editing-plugin/lib/feature-flags/class-a8c-full-site-editing-feature-flags.php

* Making `phpcs` happy.
* Smoke test the plugin and make sure that everything still works.

Full Site Editing: comply with coding standards

---

client/lib/signup/site-type.js

Related to Improved Onboarding phase 2. More context available on paObgF-b3-p2.
Let's give the blogger sites a modern-business theme.
1. Choose "Blogger" in the segmentation step.
2. Go through the entire signup flow
3. Confirm the final site looks like on the "a8cvm2" site

Change Blog segment theme to pub/modern-business

---

apps/full-site-editing/full-site-editing-plugin/full-site-editing/index.js
apps/full-site-editing/full-site-editing-plugin/full-site-editing/plugins/template-update-confirmation/button.js
apps/full-site-editing/full-site-editing-plugin/full-site-editing/plugins/template-update-confirmation/index.js
apps/full-site-editing/full-site-editing-plugin/full-site-editing/plugins/template-update-confirmation/panel.js
apps/full-site-editing/package-lock.json

* Add a post-update confirmation when updating a template part
* load an existing Template Part post
* update it
* ensure that a confirmation panel appears after clicking the button
* since the button is hacked into place atop the "real" update button, try it at various screen sizes, devices, etc
Fixes #33629

Full Site Editing: confirm changes to template parts

---

client/blocks/reader-feed-header/index.jsx
client/reader/controller-helper.js
client/reader/feed-stream/index.jsx
client/reader/following-manage/index.jsx
client/reader/following-manage/subscriptions.jsx
client/reader/liked-stream/main.jsx
client/reader/list-stream/index.jsx
client/reader/search-stream/index.jsx
client/reader/site-blocked/index.jsx
client/reader/site-stream/index.jsx
client/reader/tag-stream/main.jsx
client/reader/update-notice/index.jsx

Add translator notes where a variable has been used but not explained. 
I discovered these by using the excellent internal i18n developer dashboard.
Make sure the comments added describe the translation variables clearly.

Reader: add translator notes for variables

---

client/lib/abtest/active-tests.js
client/my-sites/plans-features-main/index.jsx

There's a bug with the assignment unrelated to this test. It will have to be restarted once the bug is fixed.
This will end the test and keep the change in the abtest library that allows non-en tests as it will be useful in the future.
1. As a logged out user, signup with a new user. The plans section should work with Blogger plan clearly visible.
2. Log in. Go to /plans. It should work with Blogger plan being available to purchase.
*
Fixes #

End the Blogger plan non-en retest

---

apps/full-site-editing/full-site-editing-plugin/starter-page-templates/class-starter-page-templates.php

Limits tracking to the Atomic environment.

(5P) FSE: Remove tracking code from plugin

---

apps/full-site-editing/full-site-editing-plugin/full-site-editing-plugin.php
apps/full-site-editing/full-site-editing-plugin/readme.txt

Updates contributor list to include all three teams + designers.

FSE: Pre-release version bump

---

client/components/signup-site-preview/iframe.jsx

Fix site title preview

---

client/me/purchases/manage-purchase/auto-renew-toggle/index.jsx

_This PR is part of the attempt of adding a self-serving plan subscription autorenewal toggle. For more details, please refer to p2-p9jf6J-1GZ_
This PR adds a new Tracks event: `calypso_purchases_manage_purchase_toggle_auto_renew` for tracking the toggle usage.
https://github.com/Automattic/wp-calypso/pull/33568
1. Open your web console and run `localStorage.setItem( 'debug', 'calypso:analytics:*' );` so that the Tracks event dispatching is visible.
1. Go to the purchase management page, `/me/purchases`.
1. Pick any purchase that is either a plan or a domain registration.
1. Toggle the auto-renewal toggle, and you should see ` `calypso_purchases_manage_purchase_toggle_auto_renew` be dispatched as expected.

Auto-renewal Toggle: Add a Tracks event.

---

client/lib/abtest/active-tests.js
client/signup/steps/domains/index.jsx

We need to rerun the test.
:eyes: code.

Rerun the A/B test

---

apps/full-site-editing/full-site-editing-plugin/full-site-editing/blocks/site-description/index.php
apps/full-site-editing/full-site-editing-plugin/full-site-editing/blocks/site-logo/index.php
apps/full-site-editing/full-site-editing-plugin/full-site-editing/blocks/site-title/index.php
apps/full-site-editing/full-site-editing-plugin/full-site-editing/class-full-site-editing.php
apps/full-site-editing/full-site-editing-plugin/full-site-editing/page-fse.php
apps/full-site-editing/full-site-editing-plugin/full-site-editing/utils/class-a8c-wp-template.php
apps/full-site-editing/full-site-editing-plugin/starter-page-templates/class-starter-page-templates.php

* This PR cleans up recent linting issues that have crept in.
* Smoke test any and all of FSE for regressions.

FSE: Clean up PHPCS linting issues.

---

client/my-sites/email/gsuite-add-users/index.jsx

Currently when adding users to an existing G Suite account the form allows you to chose an arbitrary  set of your existing domains as the domains of the new G Suite User:
**Current**
However since the context in this screen is already a pre selected domain ( see the red circle in the above screenshot ) let's lock it down to that domain:
**Proposed**
1. Navigate to `/email/:siteSlug` for a site with 2 or more domains with g Suite
2. Click the "Add G Suite User" Button for one
3. Verify that the domain is lock in the "Add G Suite" Form
4. Add a user to the cart and verify the info in the cart is correct
5. repeat step 2 - 5 for a different domain

Lock the GSuiteAddUsers component to a single domain

---

client/my-sites/site-settings/subscriptions.jsx

Before:
After:
Jetpack:
Bring Calypso and Jetpack in sync.
* Go to: /settings/discussion/domain.com
* Verify copy changes
Fixes #34227

Update subscription setting copy

---

client/my-sites/site-settings/comment-display-settings/index.jsx

Before:
After:
Jetpack:
* Goto Settings > Discussion
* Verify copy changes
Fixes #34224

Update comment form copy to match Jetpack

---

client/my-sites/checkout/checkout-thank-you/blogger-plan-details.jsx
client/my-sites/checkout/checkout-thank-you/custom-domain-purchase-detail.jsx
client/my-sites/checkout/checkout-thank-you/index.jsx

We recently restarted the Blogger Plan hide test. There is, however, a small problem with the Blogger plan that might've impacted the results. This plan does not have a proper thank you screen.
Before this change:
After this change:
1. Buy a Blogger plan
2. Make sure the Thank You screen looks okay

Add Blogger Plan Thank You screen

---

client/components/signup-site-preview/iframe.jsx
client/components/signup-site-preview/utils.js
client/signup/site-mockup/index.jsx

paWIov-4K-p2#comment-73
* `/start`
* Choose any segment that shows preview
* When choosing a site title, the title changes appear in the preview

Signup: Site preview param changes

---

client/signup/test/utils.js
client/signup/utils.js

* Revert #34356 due to issues flagged in #34403
* From logged out, go to http://calypso.localhost:3000/start/
* Select `blog` site type and complete creating a free site
* You should not see the error messages in #34403

Revert #34356 due to issues flagged in #34403

---

config/horizon.json

* Enable the flag in horizon
* Syntax check
See discussion: p1562180937380500-slack-CCS1W9QVA & p1562182855295000-slack-C02DQP0FP

Onboarding Checklist: Enable flag in horizon

---

client/blocks/reader-list-item/connected.jsx
client/blocks/reader-list-item/docs/example.jsx
client/blocks/reader-list-item/index.jsx
client/blocks/reader-list-item/placeholder.jsx
client/blocks/reader-list-item/style.scss
client/blocks/reader-recommended-sites/index.jsx
client/blocks/reader-recommended-sites/style.scss

Updated design for Recommendations in Reader
Created a new block called ReaderListItem based on SubscriptionListItem for increased future flexibility within Recommendations and clearer separation from the list of subscribed sites vs recommended sites. 
Before:
After:
1. Checkout this branch or open the calypso.live link
2. Navigate to https://wordpress.com/following/manage
3. Look at the recommendations 
Fixes #
#32231

Fix Reader Recommended

---

client/my-sites/plugins/plugin-meta/index.jsx

Unblock Anywhere Elementor and Anywhere Elementor Pro.
Details: p9F6qB-2I5-p2 #comment-17351
Slug: anywhere-elementor and anywhere-elementor-pro
Associated file names: anywhere-elementor.php and anywhere-elementor-pro.php

Atomic: Unblock anywhere-elementor and anywhere-elementor-pro

---

client/lib/gsuite/README.md
client/lib/gsuite/new-users.ts

* Add a little bit of explanation to G Suite New Users Lib
* Read Documentation

Add G Suite New Users Library Documentation

---

apps/full-site-editing/full-site-editing-plugin/full-site-editing-plugin.php
apps/full-site-editing/full-site-editing-plugin/readme.txt

Bumps version numbers across the plugin in preparation for the next update.

FSE: Update to v0.3

---

client/me/purchases/manage-purchase/index.jsx
client/me/purchases/manage-purchase/notices.jsx
client/me/purchases/manage-purchase/purchase-meta.jsx
config/development.json
config/horizon.json
config/wpcalypso.json

This PR removes the blocks from the `autorenewal-toggle` feature flag so the functionality is exposed in all environments.
1. Mainly code review, to see if the equivalence of having the feature flag on always. All the unreachable code after that should be removed.
1. Test if the toggle work as expected.

Auto-renewal Toggle: Public launch

---

client/my-sites/site-settings/theme-enhancements.jsx

* Brings copy for the theme enhancements setting panel in sync with Jetpack. These particular changes will roll out with Jetpack 7.6
* Goto settings -> writing -> theme enhancements
* Verify copy changes
Before:
After:
Jetpack:
Fixes #34235

Copy Sync: Infinite Scroll / Jetpack mobile theme

---

client/lib/url/index.ts
client/my-sites/marketing/tools/index.tsx
client/types.ts

Types: lib/url

---

client/lib/build-url/index.ts

Really small, just adding some types. No functional changes.
No functional changes, this should not impact the production bundle _in any way_.

Types: Type build-url lib

---

client/lib/discounts/active-discounts.js

* Add new promo nudge and banner for upcoming May sale. 
More information here: p9jf6J-1QE

Adding July sale banner

---

apps/full-site-editing/full-site-editing-plugin/full-site-editing-plugin.php
apps/full-site-editing/full-site-editing-plugin/readme.txt

* Updates the version to 0.4 to prepare for the next release.
I'll use this PR as a reference to pull its CircleCI artifacts to Dotcom. After some pending fixes have been merged, I'll rebase it against master.

Full Site Editing: bump plugin version to 0.4

---

client/my-sites/activity/activity-log/rewind-alerts.jsx
client/state/selectors/get-site-threats.js

Hook up the rewind fixers to the UI, so that we can display the threats found by the Rewind security scanner in the Activity Log and let the user take actions, such as fix or ignore them. Right now the backend part is done and the frontend (Calypso) is partially completed.
There are different use cases that will be supported as this PR progresses, so this description will be updated accordingly. Only fixable alerts are supported at the moment.
a) Vulnerable extensions alerts
Upload a known vulnerable plugin. I'm using the infamous facebook_for_woocommerce Version 1.9.12, get it from .org. There seems to be some (automated?) cleanup process in Atomic V2 that would eliminate any vulnerable plugin as soon as it's uploaded, so I've tested it on my own Pressable test site.
Trigger a backup. …

Hook up the rewind fixers to the Activity Log UI

---

client/my-sites/activity/activity-log/threat-alert.jsx

Implement proper Fixing and Ignoring mechanisms from the UI, spinner on processing and refreshing on complete.

Rewind Alerts: hook up buttons to Redux actions

---

apps/wpcom-block-editor/src/calypso/iframe-bridge-server.js

This PR prevents the possibility of a hard post delete. If trash is enabled on a site, moving a post to trash and hard deleting it are triggered by the same API call. Calling the endpoint once moves a post to trash and calling it a second time will hard-delete it.
This PR overrides the 'core/editor' `trashPost` action into a no-op, and allows the Calypso post list to perform the trash action. In core, clicking on the button would trigger a delete API call
https://github.com/WordPress/gutenberg/blob/1ca616a456a9d9c5ab4698bf67589a99e1802fff/packages/editor/src/store/actions.js#L664
From the report if the editor trashPost managed to fire AND the post-list trash fired, we'd have an accidental hard delete.
- Apply D30745-code and sandbox widgets.wp.com
- On a any site visit …

Block Editor: Prevent possibility of post hard delete in Block Editor integration

---

client/lib/abtest/active-tests.js
client/my-sites/plans-features-main/index.jsx

This change reverts #34172
1. With a new user, go to /plans
2. Make sure there's no hideBloggerPlan2 test
3. Make sure the Blogger plan is visible

End the hideBloggerPlan2 test

---

client/my-sites/earn/index.js
client/my-sites/earn/main.jsx
config/development.json
config/stage.json
config/wpcalypso.json

* removes the config flag and the conditions checking it so the Earn page is fully live for all users
* ensure the Earn page works as expected. Flag particularly modified the page visibility and the tabs

Earn: remove config flag and go live

---

config/development.json
config/stage.json
config/wpcalypso.json

* introduce a new flag `customer-home` in development, staging, and Calypso live, for the upcoming development of the Customer Home section.
* check for typos

Config: add customer-home flag

---

client/my-sites/checkout/checkout/secure-payment-form.jsx

* mv logic to new class method: `maybeSetSiteToPublic`
* call in `submitTransaction` instead of `finishIfLastStep`
* See test plan in #35003

Private by Default: Set atomic sites public on transaction submit instead of last step

---

client/my-sites/site-settings/masterbar.jsx

Corrected a typo reported in 
#2261574-zen
Minor typo correction
*
Fixes #

Correct a typo - notifcations to notifications

---

client/lib/signup/private-by-default.ts
config/development.json
config/test.json
config/wpcalypso.json

NOTE: Targeting branch in #34193 -- retarget on master before landing.
* Pull out `add/private-by-default--send-it` flag & config settings
* 🕵️‍♀️🕵️‍♂️++

Private by Default: Launch in all environments

---

apps/full-site-editing/full-site-editing-plugin/full-site-editing-plugin.php
apps/full-site-editing/full-site-editing-plugin/readme.txt

Updates FSE to 0.6.
1. Smoke test the plugin.

Full Site Editing: bump version to 0.6

---

client/jetpack-connect/plans.jsx
client/my-sites/checkout/checkout-thank-you/index.jsx
client/my-sites/checkout/checkout/index.jsx

Reverts Automattic/wp-calypso#35471

Revert "Remove Jetpack product install on checkout"

---

client/my-sites/importer/section-import.jsx

* Add Tracks events for changes in importer state.
* Set `debug` in `localStorage` so that you can see Tracks events in your console: `localStorage.setItem( 'debug', 'calypso:analytics:tracks' )`.
* Checkout this PR locally and start an import for a site from `/start`.
* Verify that the events in `stateToEventNameMap` are triggered as you progress through the import flow.
Fixes #35878

Importer: Log Tracks events for importer state changes

---

apps/full-site-editing/full-site-editing-plugin/full-site-editing-plugin.php
apps/full-site-editing/full-site-editing-plugin/readme.txt
apps/full-site-editing/package.json

Also added myself as a plugin contributor :)
Let me know if anything else should be added to the changelog!

Update FSE plugin version to 0.7

---

client/lib/importer/importer-config.js

#36068 introduced a bug in that we linked to a non-existent page.
* Correct the link to the Blogger support article
* Follow the test instructions from #36068, but make sure that the link points to the correct article.

Blogger Importer: Link to the correct support article

---

client/my-sites/post-type-filter/index.jsx

Fixes #36122
See #36122 for details to reproduce.

Post search: open the search bar on page load if there's a "s=..." in the URL

---

packages/calypso-ui/CHANGELOG.md
packages/calypso-ui/package.json

Prep calypso-ui release

---

client/extensions/woocommerce/app/dashboard/required-plugins-install-view.js
client/extensions/woocommerce/app/dashboard/setup/style.scss
client/my-sites/sidebar/index.jsx
client/my-sites/sidebar/test/sidebar.js

Reverting due to #36247 while I investigate.
- Go to any business simple site on wordpress.com
- Ensure the sidenav doesn't include the store link
cc @kriskarkoski thanks for reporting

Revert "Show store link in sidenav by default if user has a business plan"

---

apps/full-site-editing/full-site-editing-plugin/starter-page-templates/page-template-modal/index.js
apps/full-site-editing/full-site-editing-plugin/starter-page-templates/page-template-modal/styles/starter-page-templates-editor.scss

This PR changes the icon of the close button and fixes some styles.
Apply these changes
1) Start to create a new page
2) Close the modal
Fixes #6397

SPT: Modal close button enhancements

---

apps/full-site-editing/full-site-editing-plugin/full-site-editing-plugin.php
apps/full-site-editing/full-site-editing-plugin/readme.txt

* Updates the plugin version to `0.9`. To be rebased and merged after the other blocking updates.
1. Smoke test the plugin.

FSE: bump version to 0.9

---

apps/full-site-editing/full-site-editing-plugin/starter-page-templates/page-template-modal/styles/starter-page-templates-editor.scss

It fixes the bug shown below:
1) Try to reproduce the bug
2) Apply the patch
3) Confirm it works as expected

SPT: fix modal header position bug

---

apps/full-site-editing/full-site-editing-plugin/starter-page-templates/page-template-modal/components/preview-template-title.js
apps/full-site-editing/full-site-editing-plugin/starter-page-templates/page-template-modal/components/template-selector-preview.js
apps/full-site-editing/full-site-editing-plugin/starter-page-templates/page-template-modal/styles/starter-page-templates-editor.scss

This PR changes the way of setting the template title scale.
Applies the patch. Check the template title is rightly scaled.

SPT: fix setting position of template title

---

client/lib/abtest/active-tests.js

* The test was first launched in #35750 
* It was then disabled due to an issue in #36213 
* The issue was then fixed in #36541 
see #35750

Checkout: relaunch the phone number field test

---

packages/calypso-ui/src/progress-bar/index.tsx

* Using `tsx`
- Progress bar works well? Test live: https://calypso.live/devdocs/design/progress-bar?branch=add/progress-bar-typescript

TypeScript for ProgressBar

---

apps/full-site-editing/full-site-editing-plugin/full-site-editing-plugin.php
apps/full-site-editing/full-site-editing-plugin/readme.txt

Get ready ship SPT updates.
See #36501 for prior art.

FSE: Prep v0.10

---

client/my-sites/site-settings/delete-site/index.jsx

Changed "...once your delete this site." to "...once you delete this site."
*
*
Fixes #

Fixed a small typo

---

apps/full-site-editing/full-site-editing-plugin/full-site-editing-plugin.php
apps/full-site-editing/full-site-editing-plugin/readme.txt
apps/full-site-editing/package.json

* Bump plugin version to 0.12.
1. Smoke test the plugin.

FSE: bump version to 0.12

---

client/lib/oauth-store/actions.js

Fix headers, async code, and error message reporting.
This PR should solve the issues, but I'm unable to fully test due to an apparent problem with my wordpress.com developer settings.
The issue was introduced in #34809.
* Fix HTTP request generation and handling in `oauth-store`
* Build the desktop app using this PR's branch
* Attempt to log in with the wrong password
* Confirm an appropriate error message is displayed
* Attempt to log in with the correct password
* Confirm login works successfully

Fix issues with oauth-store HTTP requests.

---

client/my-sites/stats/stats-module/availability-warning.tsx

Types: Gridicon size should be number

---

apps/full-site-editing/full-site-editing-plugin/full-site-editing-plugin.php
apps/full-site-editing/full-site-editing-plugin/readme.txt
apps/full-site-editing/package.json

* Prepare 0.13 release of the plugin.
* Smoke test the plugin locally.
* See D34664-code for more testing instructions.

FSE: bump version to 0.13

---

config/horizon.json

* Turn on the new hosting feature in Horizon to allow for wider testing.
* NA
Fixes #37188

Toggle on the new hosting feature for the Horizon env

---

client/my-sites/hosting/sftp-card/index.js

This PR updates the URL displayed to the user for SFTP access in the atomic Hosting Panel.
<hr>
* Testing isn't necessary as this is display-only.

Hosting Panel: Update URL for SFTP access

---

client/landing/gutenboarding/components/header/index.tsx
client/landing/gutenboarding/components/header/style.scss
client/landing/gutenboarding/onboarding-block/edit.tsx
client/landing/gutenboarding/onboarding-block/style.scss
client/landing/gutenboarding/store/actions.ts
client/landing/gutenboarding/store/reducer.ts
client/landing/gutenboarding/store/types.ts

* Update header component; styling and add empty state
* Default `siteType` to empty
* Switch select input to `input[type=radio]` buttons for site type question
* Add "skip question" to site title question; only functionality is that it hides when you type in the title :-) 
* Updated styling for questions & answers
- Open `/gutenboarding`
- Test clicking around questions, observe header

Gutenboarding: updates to question styles

---

client/landing/gutenboarding/onboarding-block/edit.tsx
client/landing/gutenboarding/onboarding-block/style.scss
client/landing/gutenboarding/store/selectors.ts

WIP Adds autocomplete vertical selection

Gutenboarding: Vertical autocomplete

---

client/my-sites/plans-features-main/index.jsx

This PR enables the Jetpack Backups purchase UI only for Jetpack sites that run the latest Jetpack 7.9 (alpha or newer). An exception is the Jetpack connect store page, which doesn't have a Jetpack site in the context so it always has to display the UI.
* Plans: Enable Jetpack Backups only on Jetpack >= `7.9alpha`
* Verify you **can** see the Jetpack Backups product purchase UI in all the following cases:
* Visiting http://calypso.localhost:3000/plans/:site where `:site` is a Jetpack site with the latest Jetpack beta.
* Visiting http://calypso.localhost:3000/jetpack/connect/store
* Verify you **can't** see the Jetpack Backups product purchase UI in all the following cases:
* Visiting http://calypso.localhost:3000/jetpack/connect/store?flags=-plans/jetpack-backup
* …

Plans: Enable Jetpack Backups only on Jetpack >= 7.9alpha

---

client/blocks/product-selector/index.jsx

This PR does a couple of minor changes to the `ProductSelector` block:
* Get rid of the `getShortPlanName` helper in favor of the `getTitle()` plan object method.
* Include the "plan" word in the "Included in the PLAN_NAME plan" clickable link.
Before:
After:
* Go to http://calypso.localhost:3000/plans/:site where `:site` is a Jetpack site with a Personal or Premium plan.
* Verify the "Included in PLAN_NAME plan" section has the "plan" word also as part of the link.
* Verify that link still works like it did before.
* Play with different cases (site with a product, site without a plan) and verify we're still using the short product names (`Personal` instead of `Jetpack Personal`) - there should be no changes to the existing behavior (compare with wpcalypso to …

Blocks: Product Selector - Update included link, handle plan names better

---

client/lib/stripe/index.js

When confirming a Stripe Setup Intent by using
`stripe.handleCardSetup()` we throw any returned error as a custom
`StripeSetupIntentError` object so that it can be handled appropriately
by the calling form component. Specifically, we don't want to display
the raw error on the page, instead displaying a generic failure message.
`handleCardSetup()` typically returns its errors as part of the response
object, but sometimes it will throw itself, which circumvents the
process above.
In this PR we wrap the `handleCardSetup()` call in a try/catch so that
any thrown errors are also converted into `StripeSetupIntentError`
objects.
This follows on #35315
1. Sandbox the store.
1. Apply D35152-code which will break the setup intent creation.
1. Visit …

Checkout: wrap stripe.handleCardSetup errors in StripeSetupIntentError

---

client/landing/gutenboarding/components/header/index.tsx
client/landing/gutenboarding/components/header/style.scss

Extracted some header cleanup from #37403.
- /gutenboarding header is improved

Gutenboarding: Improve header

---

client/components/marketing-survey/cancel-purchase-form/index.jsx

Fixes the following error.
* Go though the cancel plans flow. Do you notice any errors in your console.log.

CancelPurchaseForm: Update class => className

---

packages/composite-checkout/README.md
packages/composite-checkout/src/components/billing-fields.js
packages/composite-checkout/src/components/button.js
packages/composite-checkout/src/components/checkout-payment-methods.js
packages/composite-checkout/src/components/checkout-provider.js
packages/composite-checkout/src/components/credit-card-fields.js
packages/composite-checkout/src/components/field.js
packages/composite-checkout/src/components/stripe-credit-card-fields.js
packages/composite-checkout/src/lib/payment-methods/apple-pay.js
packages/composite-checkout/src/lib/payment-methods/credit-card.js
packages/composite-checkout/src/lib/payment-methods/paypal.js
packages/composite-checkout/src/lib/styled-components/summary-details.js
packages/composite-checkout/test/components/checkout.js

This PR updates the payment summary to reflect the details from the payment step in checkout.
Same as https://github.com/Automattic/wp-calypso/pull/37013

Display payment summary

---

client/landing/gutenboarding/onboarding-block/edit.tsx
client/landing/gutenboarding/onboarding-block/style.scss
client/landing/gutenboarding/onboarding-block/vertical-select/index.tsx
client/landing/gutenboarding/onboarding-block/vertical-select/style.scss
client/landing/gutenboarding/store/types.ts

This PR adds a bunch of styles and interactions to reflect the original design we are based on. 
Go to http://calypso.localhost:3000/gutenboarding and have fun

Gutenboarding: Eyecandy for acquire intent

---

client/lib/email-followers/store.js
client/lib/followers/store.js
client/lib/users/store.js

lint errors surfaced in #37506
There are all replacing `let` with `const` as directed by the linter.
* App builds, e2e passes.

Fix lint errors

---

client/landing/gutenboarding/stores/onboard/index.ts

- `/gutenboarding`
- Pick stuff
- Refresh
- It's persisted

Gutenboarding: Add persistence

---

client/components/domains/register-domain-step/index.jsx
client/lib/signup/site-type.js

This PR builds on top of the domain-copy A/B test introduced as a feature flag in #37546.
* Placeholder text for the domain search box is tailored per the site type chosen in the signup flow.
* Go to /start and put yourself in the variant variantShowUpdates of the domainStepCopyUpdates A/B test.
* The domain search box placeholder text should show the new copy:
If site type is "blog" : `Enter your blog's name or a few words that describe it, like "photography" or "travel"`
If site type is "business" : `Enter your business's name or a few words that describe it, like "photography" or "travel"`
If site type is "professional" : `Enter your site's name or a few words that describe it, like "photography" or "travel"`
If site type is "store" : `Enter your store's name or a few words that …

Domain step test: tailored placeholder text

---

client/landing/gutenboarding/stores/domain-suggestions/types.ts
client/landing/gutenboarding/stores/onboard/resolvers.ts
client/landing/gutenboarding/stores/onboard/types.ts

Small change to update vertical types based on API results.

Gutenboarding: Fix vertical types

---

client/landing/gutenboarding/components/domain-picker/button.tsx
client/landing/gutenboarding/stores/domain-suggestions/types.ts
client/landing/gutenboarding/stores/onboard/index.ts

- Partition domain suggestions free/paid
- Simplify `persist` setting (cleanup).
Does the domain picker work like in #37664 
- /gutenboarding
- Play with the domain picker

Gutenboarding: Partition domain results on is_free

---

packages/composite-checkout/src/components/grid-row.js
packages/composite-checkout/src/lib/payment-methods/credit-card-fields.js
packages/composite-checkout/src/lib/payment-methods/stripe-credit-card-fields.js
packages/composite-checkout/src/lib/styled-components/ie-fallback.js
packages/composite-checkout/src/wpcom/grid-row.js
packages/composite-checkout/src/wpcom/wp-contact-form.js

This PR adds grid support for IE. 
**Before**
**After**
* Get checkout up and running on your local machine.
* If you have a Virtual Box, or anyway to test in IE, visit checkout with IE.
* Check other browsers to make sure nothing looks different.

Composite checkout: Add grid support for IE

---

packages/composite-checkout/src/components/radio-button.js
packages/composite-checkout/src/lib/payment-methods/apple-pay.js
packages/composite-checkout/src/lib/payment-methods/credit-card-fields.js
packages/composite-checkout/src/lib/payment-methods/credit-card.js
packages/composite-checkout/src/lib/payment-methods/paypal.js
packages/composite-checkout/src/lib/payment-methods/stripe-credit-card-fields.js
packages/composite-checkout/src/theme.js
packages/composite-checkout/src/wpcom/wp-checkout-order-summary.js

This PR makes a number of small tweaks to adapt the design for small screens. 
**Before**
**After**
* Get checkout up and running with these instructions
* Use chrome dev tools to simulate the iPhone 5

Composite checkout: mobile fixes

---

client/my-sites/hosting/controller.js

Ensures the current site's plan is set on the state before `canSiteViewAtomicHosting` is executed. 
Otherwise, [`isSiteOnAtomicPlan`](https://github.com/Automattic/wp-calypso/blob/54ce88c41b7d3e419e388ba8035e3553287ebe9e/client/state/selectors/can-site-view-atomic-hosting.js#L37) can return false when the plan has not been retrieved yet (i.e. loading `/hosting-admin/:site` directly on the browser).
* Spin up a local Calypso running `master`.
* Try to access the hosting section by typing `calypso.localhost:3000/hosting-admin/:site` directly in the browser (do not use the sidebar).
* Note how it redirects to `/stats/day`.
* Try to access again the hosting section using the URL and not the sidebar.
* Make sure it loads the hosting section.

Atomic Hosting: Wait for data before denying access

---

client/lib/signup/step-actions.js

* Pass the current flow to the site creation API.
* See D35723-code.
Fixes #37780

Pass the current flow to the site creation API

---

client/landing/gutenboarding/onboarding-block/question/index.tsx
client/landing/gutenboarding/onboarding-block/site-title.tsx
client/landing/gutenboarding/onboarding-block/vertical-select/index.tsx

Improve focus handling in Gutenborarding capture intent step.
Closes #37846
Fixes part of #37854

Gutenboarding: Improve focus handling

---

packages/composite-checkout/README.md

Link to review order screenshot was broken, fixing it here.
Check the 'rich' preview of the file to verify that the image is now shown.

Docs: Update Composite Checkout README link

---

apps/full-site-editing/full-site-editing-plugin/full-site-editing-plugin.php
apps/full-site-editing/full-site-editing-plugin/readme.txt
apps/full-site-editing/package-lock.json
apps/full-site-editing/package.json

Updates the FSE plugin to version 0.16.
Testing instructions will be provided in the sync diff

FSE: update version to 0.16

---

client/auth/auth-code-button.jsx

* Add missing content type to SMS code request.
See steps in https://github.com/Automattic/wp-desktop/issues/701
Fixes https://github.com/Automattic/wp-desktop/issues/701

Add missing content type to SMS code request.

---

config/desktop.json
config/production.json
config/stage.json
config/test.json
config/wpcalypso.json

* Toggles the sftp/phpmyadmin feature flag to turn on this feature.
Should only be merged once the go ahead is given to release this new feature.

Hosting: Turn on sftp/phpmyadmin feature for Atomic sites.

---

client/landing/gutenboarding/components/domain-picker/button.tsx
client/landing/gutenboarding/controller.tsx
client/landing/gutenboarding/index.ts
client/landing/gutenboarding/onboarding-block/vertical-select/index.tsx
client/types.ts

Fixes several type issues. Prep for #37945.
`npm run typecheck -- -p client/landing/gutenboarding` shows fewer errors than on `master`. 4 at the moment.

Gutenboarding: Fix minor type issues

---

client/my-sites/activity/activity-log-item/index.jsx

* We've updated our support doc URL. The old URL still redirects to the new one, but let's save folks one redirect and use the new URL instead.
* Not much to test here, the change is fairly small.

Jetpack Backup: update support doc URL.

---

apps/full-site-editing/full-site-editing-plugin/full-site-editing-plugin.php
apps/full-site-editing/full-site-editing-plugin/readme.txt
apps/full-site-editing/package-lock.json
apps/full-site-editing/package.json

FSE: 0.16.1 release

---

client/my-sites/migrate/section-migrate.jsx
client/my-sites/migrate/section-migrate.scss

Try branch based on #38053 that uses `Spinner` component for the active progress item.
To test, follow the instructions from #38053.

Migration: Try using spinner for active item

---

apps/full-site-editing/full-site-editing-plugin/global-styles/class-global-styles.php

This fixes a bug by which the styles in the front-end won't load for logged-out users.

Load front-end styles for logged out users

---

apps/full-site-editing/full-site-editing-plugin/full-site-editing-plugin.php
apps/full-site-editing/full-site-editing-plugin/readme.txt
apps/full-site-editing/package.json

Bumps version and documents changes.

Bump FSE to 0.16.2

---

client/state/hosting/test/reducer.js

Fix test data.
All tests pass.

Hosting: Add phpVersion to default reducer state

---

apps/full-site-editing/full-site-editing-plugin/blog-posts-block/index.php
apps/full-site-editing/full-site-editing-plugin/blog-posts-block/newspack-homepage-articles/blocks/homepage-articles/class-wp-rest-newspack-articles-controller.php
apps/full-site-editing/full-site-editing-plugin/blog-posts-block/newspack-homepage-articles/blocks/homepage-articles/edit.js
apps/full-site-editing/full-site-editing-plugin/blog-posts-block/newspack-homepage-articles/blocks/homepage-articles/templates/article.php
apps/full-site-editing/full-site-editing-plugin/blog-posts-block/newspack-homepage-articles/blocks/homepage-articles/view.js
apps/full-site-editing/full-site-editing-plugin/blog-posts-block/newspack-homepage-articles/blocks/homepage-articles/view.php

* Sync with newspack-blocks master to include More button functionality.

Blog Posts: Update to include More button

---

apps/full-site-editing/full-site-editing-plugin/blog-posts-block/newspack-homepage-articles/blocks/homepage-articles/view.js
apps/full-site-editing/full-site-editing-plugin/blog-posts-block/newspack-homepage-articles/blocks/homepage-articles/view.php

* Pulls in latest changes from newspack-blocks to replace apiFetch.
See https://github.com/Automattic/newspack-blocks/pull/264

FSE: Replace apiFetch

---

apps/full-site-editing/README.md
apps/full-site-editing/full-site-editing-plugin/full-site-editing-plugin.php
apps/full-site-editing/full-site-editing-plugin/readme.txt
apps/full-site-editing/package-lock.json
apps/full-site-editing/package.json

* Bumps version and documents changes.

Bump FSE to 0.17

---

client/my-sites/checkout/checkout-thank-you/header.jsx

Fixes breaking imports caused by not rebasing prior to deploy for #38185

Checkout Thank You: Fix imports

---

apps/full-site-editing/full-site-editing-plugin/blog-posts-block/newspack-homepage-articles/blocks/homepage-articles/edit.js
apps/full-site-editing/full-site-editing-plugin/blog-posts-block/newspack-homepage-articles/blocks/homepage-articles/templates/article.php
apps/full-site-editing/full-site-editing-plugin/blog-posts-block/newspack-homepage-articles/blocks/homepage-articles/templates/articles-list.php
apps/full-site-editing/full-site-editing-plugin/blog-posts-block/newspack-homepage-articles/blocks/homepage-articles/templates/articles-loop.php
apps/full-site-editing/full-site-editing-plugin/blog-posts-block/newspack-homepage-articles/blocks/homepage-articles/view.php
apps/full-site-editing/full-site-editing-plugin/blog-posts-block/newspack-homepage-articles/class-newspack-blocks-api.php

See https://github.com/Automattic/newspack-blocks/pull/271

FSE: Sync TC fixes

---

client/components/timeline/README.md
client/components/timeline/docs/example.jsx
client/components/timeline/index.jsx
client/components/timeline/style.scss
client/components/timeline/timeline-event.jsx
client/components/timeline/timeline-item.jsx
client/devdocs/design/component-examples.js
client/devdocs/design/index.jsx
client/devdocs/design/playground-scope.js

* Add a new timeline component for use with domains and other upgrades
Screenshot:
* Review the code
* Make sure the example code works
* Make sure the instructions in the README.md file make sense

Add timeline component

---

client/components/timeline/README.md
client/components/timeline/docs/example.jsx
client/components/timeline/index.jsx
client/components/timeline/style.scss
client/components/timeline/timeline-event.jsx
client/devdocs/design/component-examples.js
client/devdocs/design/index.jsx
client/devdocs/design/playground-scope.js

Take 2 of #38278 - take 1 was reverted.

Add timeline component - take 2

---

client/lib/plans/plans-list.js

Someone forgot the extended forwards limit. :)

Atomic: Add extended forwards limit to eCommerce

---

apps/full-site-editing/full-site-editing-plugin/blog-posts-block/newspack-homepage-articles/class-newspack-blocks-api.php

See https://github.com/Automattic/newspack-blocks/pull/274

Add rest fields only to edit context

---

client/blocks/product-selector/index.jsx
client/components/product-card/index.jsx
client/components/product-card/style.scss
client/jetpack-connect/style.scss

As part of the work related to p1HpG7-87V-p2, this PR removes the price group from the Jetpack Backup product card.
Also, some minor visual issues are fixed in the `ProductCard` header area, especially in the Jetpack Connect flow.
**Calypso - before**
**Calypso - after**
**Jetpack Connect - before**
**Jetpack Connect - after**
* Remove a price group from the Jetpack Backup product card header
* Fix minor CSS issues in the product card header
* Go to http://calypso.localhost:3000/plans/ and select a Jetpack site having no Jetpack Backup product
* Confirm that there is no price group displayed in the product card header and that the title is centered
* Purchase one of the Jetpack Backup products and confirm that there's no regression, i.e. that the title is left-aligned and a subheading …

Remove price group from Jetpack Backup product card and fix CSS issues

---

apps/full-site-editing/full-site-editing-plugin/blog-posts-block/README.md

* Add more verbose explanation of files connecting BPB with its parent plugin

FSE: Explain files connecting Blog Posts Block

---

apps/full-site-editing/full-site-editing-plugin/event-countdown-block/blocks/event-countdown.js
apps/full-site-editing/full-site-editing-plugin/event-countdown-block/blocks/event-countdown.php
apps/full-site-editing/full-site-editing-plugin/event-countdown-block/editor.css
apps/full-site-editing/full-site-editing-plugin/event-countdown-block/index.asset.php
apps/full-site-editing/full-site-editing-plugin/event-countdown-block/index.js
apps/full-site-editing/full-site-editing-plugin/event-countdown-block/index.php
apps/full-site-editing/full-site-editing-plugin/event-countdown-block/license.txt
apps/full-site-editing/full-site-editing-plugin/event-countdown-block/style.css
apps/full-site-editing/full-site-editing-plugin/full-site-editing-plugin.php
apps/full-site-editing/full-site-editing-plugin/jetpack-timeline/blocks/timeline.php
apps/full-site-editing/full-site-editing-plugin/jetpack-timeline/editor.css
apps/full-site-editing/full-site-editing-plugin/jetpack-timeline/index.asset.php
apps/full-site-editing/full-site-editing-plugin/jetpack-timeline/index.js
apps/full-site-editing/full-site-editing-plugin/jetpack-timeline/index.php
apps/full-site-editing/full-site-editing-plugin/jetpack-timeline/style.css

Adds two additional blocks to FSE plugin. These are being included here for distribution purposes and will move to Jetpack when ready the proper block categorization exists there. See https://github.com/Automattic/jetpack/pull/14104
Note: Do not deploy to WPCOM without disabling existing blocks there first, same diff commit would be ideal.
* Build Full Site Editing Plugin
* Check you can add Event Countdown block
* Check you can add Timeline block

Add Event Countdown and Timeline blocks

---

apps/full-site-editing/full-site-editing-plugin/full-site-editing/blocks/site-credit/index.js
client/my-sites/controller.js

Typo corrections on plugin install code and site credit block.
NA
Came across them when supporting users. Feel free to merge on my behalf, thank you!

Typo corrections on plugin install code and site credit block

---

apps/full-site-editing/full-site-editing-plugin/blog-posts-block/index.php
apps/full-site-editing/full-site-editing-plugin/blog-posts-block/newspack-homepage-articles/blocks/homepage-articles/block.json
apps/full-site-editing/full-site-editing-plugin/blog-posts-block/newspack-homepage-articles/blocks/homepage-articles/class-wp-rest-newspack-articles-controller.php
apps/full-site-editing/full-site-editing-plugin/blog-posts-block/newspack-homepage-articles/blocks/homepage-articles/edit.js
apps/full-site-editing/full-site-editing-plugin/blog-posts-block/newspack-homepage-articles/blocks/homepage-articles/templates/article.php
apps/full-site-editing/full-site-editing-plugin/blog-posts-block/newspack-homepage-articles/blocks/homepage-articles/view.js
apps/full-site-editing/full-site-editing-plugin/blog-posts-block/newspack-homepage-articles/blocks/homepage-articles/view.php
apps/full-site-editing/full-site-editing-plugin/blog-posts-block/newspack-homepage-articles/blocks/homepage-articles/view.scss
apps/full-site-editing/full-site-editing-plugin/blog-posts-block/newspack-homepage-articles/class-newspack-blocks-api.php
apps/full-site-editing/full-site-editing-plugin/blog-posts-block/newspack-homepage-articles/class-newspack-blocks.php
apps/full-site-editing/full-site-editing-plugin/blog-posts-block/newspack-homepage-articles/components/query-controls.js

Sync Newspack Blocks to the 1.0.0-alpha.20 release (https://github.com/Automattic/newspack-blocks/releases/tag/1.0.0-alpha.20)

Sync Newspack Blocks Release 1.0.0-alpha.20

---

apps/full-site-editing/full-site-editing-plugin/full-site-editing-plugin.php
apps/full-site-editing/full-site-editing-plugin/readme.txt
apps/full-site-editing/package.json

Bump Full Site Editing version to 0.18

Full Site Editing: Bump Version to 0.18

---

client/my-sites/plan-features/index.jsx

* Move click handler for the "Continue" button to an `onClose`
* If action is not `continue` (e.g. "Cancel" was clicked):
* Reset the state as the previous `onClose` function did
* return
* If "Continue" was clicked:
* Record the tracks event as before
* Set the site public
* If setting the site public failed, record that in a tracks event
* Redirect to the checkout page
* Create a free plan site (it should be private by default)
* Browse to `/plans`
* Click "Business Sites and Online Stores" (if the eCommerce plan isn't visible)
* Click `Upgrade` for the eCommerce plan
* You should see a `Site Privacy` dialog
* `Cancel` should take you back to the plans screen & the site should remain private
* `Let's do it!` should make the site public and take you to the checkout screen
See discussion …

eCommerce Upgrade: Set site public on dialog confirmation

---

packages/composite-checkout/src/components/radio-button.js
packages/composite-checkout/src/lib/payment-methods/existing-credit-card.js
packages/composite-checkout/src/lib/payment-methods/payment-logo.js
packages/composite-checkout/src/lib/payment-methods/stripe-credit-card-fields.js

This PR updates the styles for existing cards on file. 
**Before**
**After**
Follow the instructions here https://github.com/Automattic/wp-calypso/pull/38637

Composite checkout: Update styles for existing credit card

---

packages/calypso-build/CHANGELOG.md
packages/calypso-build/webpack/util.js

Replaces #33498. Add `punycode` to the list of transpiled deps.

Build: add Punycode to the list of transpiled NPM deps

---

client/my-sites/checkout/checkout/composite-checkout.js

* For testing we need to be able to pass in a custom country list. This PR adds a custom react hook to conditionally allow this.
Go through checkout and verify that the country drop down menu works as expected (contact form loads, country menu is populated)

composite-checkout: Add custom hook to fetch country list

---

config/horizon.json

This enables the new composite-checkout checkout form for the Horizon testing environment.
None.

Enable composite-checkout for horizon

---

client/my-sites/migrate/components/import-type-choice/index.jsx
client/my-sites/migrate/components/import-type-choice/style.scss
client/my-sites/migrate/helpers/index.js
client/my-sites/migrate/migrate-button.jsx
client/my-sites/migrate/section-migrate.jsx
client/my-sites/migrate/section-migrate.scss
client/my-sites/migrate/step-import-or-migrate.jsx

* Upgrade the UI to show choice between "Everything" and "Content only" when migrating
* Update other UI according to design
* Go to the migration screen
* Choose a site to migrate from
* See the new UI

Site Migration: Update migration confirmation UI

---

client/landing/gutenboarding/components/header/index.tsx
client/landing/gutenboarding/gutenboard.tsx
client/landing/gutenboarding/onboarding-block/design-selector/index.tsx
client/landing/gutenboarding/onboarding-block/design-selector/style.scss
client/landing/gutenboarding/steps.ts

Go frankenflow 🚀🧟‍♀️
Makes "Create my site" link go to the frankenflow.
* [`/gutenboarding`](https://calypso.live/gutenboarding?branch=gutenboarding/go-frankenflow)
* Finish the flow
* Click "Create my site"
* You go to `/start/frankenflow?theme=THEME_SLUG&siteTitle=OPTIONAL_TITLE&domainName=OPTIONAL_DOMAIN_NAME` 🙌

Gutenboarding: Connect to frankenflow

---

config/wpcalypso.json

This PR enables `coming-soon` feature flag on wpcalypso so we can thoroughly test every aspec of it before making a public release.
Not really testable, just eyeball if this diff looks good.

[Coming Soon] Enable coming-soon feature flag on wpcalypso

---

apps/full-site-editing/full-site-editing-plugin/full-site-editing-plugin.php
apps/full-site-editing/full-site-editing-plugin/readme.txt
apps/full-site-editing/package.json

Updates the FSE plugin to version 0.19.
Testing instructions will be provided in the sync diff

FSE: bump version to 0.19

---

client/lib/abtest/active-tests.js
client/my-sites/checkout/checkout/index.jsx

* This PR wraps up the Premium bump test. More info here p8Eqe3-11h
* Signup for a new account from `/start`
* Add a Personal plan with a domain to cart and complete the purchase.
* Verify the following:
- That you are shown the GSuite upsell.
This should be the same for new account, new site or upgrading an existing site.

Wrapup Premium bump test

---

client/my-sites/migrate/components/sites-block/index.jsx
client/my-sites/migrate/controller.js
client/my-sites/migrate/migrate-button.jsx
client/my-sites/migrate/section-migrate.jsx
client/my-sites/migrate/step-confirm-migration.jsx
client/my-sites/migrate/step-import-or-migrate.jsx
client/my-sites/migrate/step-source-select.jsx

* This PR adds localization to the Site Migration components 
Unsure at the moment.

Site Migration: Localize the Site Migration components

---

client/lib/abtest/active-tests.js
client/my-sites/checkout/checkout/checkout-system-decider.js

This disables the abtest that was added in #39419
None

Disable composite-checkout abtest

---

client/my-sites/themes/single-site-jetpack.jsx

Fixes 4781-gh-jpop-issues
Folks with a partner plan cannot upgrade from one plan (Premium) to the next (Professional).
It is consequently not that useful to display a banner inviting them to upgrade.
Let's check what plan they have, see if that's a partner plan, and if it is do not display the banner.
* Check this branch and head over to `/themes` for a site. 
* A site using Jetpack Free should see this banner:
* A site using a Jetpack Partner plan should not.

Themes: do not display upsell banner for sites using partner plan

---

client/my-sites/importer/section-import.jsx
client/my-sites/migrate/helpers/index.js
client/my-sites/migrate/section-migrate.jsx
client/my-sites/migrate/step-import-or-migrate.jsx
client/my-sites/migrate/step-source-select.jsx
client/my-sites/sidebar/tools-menu.jsx

Reverts Automattic/wp-calypso#39544

Revert "Importing: Enable WordPress importing for WordPress.com Business sites."

---

client/my-sites/importer/section-import.jsx
client/my-sites/migrate/helpers/index.js
client/my-sites/migrate/section-migrate.jsx
client/my-sites/migrate/step-import-or-migrate.jsx
client/my-sites/migrate/step-source-select.jsx
client/my-sites/sidebar/tools-menu.jsx

Reverts Automattic/wp-calypso#39583
Second attempt at merge.

Revert "Revert "Importing: Enable WordPress importing for WordPress.com Business sites.""

---

config/wpcalypso.json

* Enables the Migration feature in wp-calypso
* Confidence check
* Check the calypso.live link to verify that Migration is enabled (it uses the wpcalypso config)

Migration: Enable feature in wpcalypso

---

apps/full-site-editing/full-site-editing-plugin/blog-posts-block/index.php
apps/full-site-editing/full-site-editing-plugin/blog-posts-block/newspack-homepage-articles/blocks/homepage-articles/block.json
apps/full-site-editing/full-site-editing-plugin/blog-posts-block/newspack-homepage-articles/blocks/homepage-articles/class-wp-rest-newspack-articles-controller.php
apps/full-site-editing/full-site-editing-plugin/blog-posts-block/newspack-homepage-articles/blocks/homepage-articles/edit.js
apps/full-site-editing/full-site-editing-plugin/blog-posts-block/newspack-homepage-articles/blocks/homepage-articles/editor.js
apps/full-site-editing/full-site-editing-plugin/blog-posts-block/newspack-homepage-articles/blocks/homepage-articles/editor.scss
apps/full-site-editing/full-site-editing-plugin/blog-posts-block/newspack-homepage-articles/blocks/homepage-articles/store.js
apps/full-site-editing/full-site-editing-plugin/blog-posts-block/newspack-homepage-articles/blocks/homepage-articles/templates/article.php
apps/full-site-editing/full-site-editing-plugin/blog-posts-block/newspack-homepage-articles/blocks/homepage-articles/utils.js
apps/full-site-editing/full-site-editing-plugin/blog-posts-block/newspack-homepage-articles/blocks/homepage-articles/view.js
apps/full-site-editing/full-site-editing-plugin/blog-posts-block/newspack-homepage-articles/blocks/homepage-articles/view.php
apps/full-site-editing/full-site-editing-plugin/blog-posts-block/newspack-homepage-articles/blocks/homepage-articles/view.scss
apps/full-site-editing/full-site-editing-plugin/blog-posts-block/newspack-homepage-articles/class-newspack-blocks-api.php
apps/full-site-editing/full-site-editing-plugin/blog-posts-block/newspack-homepage-articles/class-newspack-blocks.php
apps/full-site-editing/full-site-editing-plugin/blog-posts-block/newspack-homepage-articles/components/autocomplete-tokenfield.js
apps/full-site-editing/full-site-editing-plugin/blog-posts-block/newspack-homepage-articles/components/autocomplete-tokenfield.scss
apps/full-site-editing/full-site-editing-plugin/blog-posts-block/newspack-homepage-articles/components/query-controls.js
apps/full-site-editing/full-site-editing-plugin/blog-posts-block/newspack-homepage-articles/shared/sass/_mixins.scss
apps/full-site-editing/full-site-editing-plugin/blog-posts-block/newspack-homepage-articles/shared/sass/_placeholder.scss
apps/full-site-editing/full-site-editing-plugin/blog-posts-block/newspack-homepage-articles/shared/sass/_variables.scss

Updates FSE with the latest Blog Posts Blog changes.
Fixes #39251, #39212, #39509.

FSE: Merge Blog Posts block with latest from newspacks-blocks

---

.github/workflows/full-site-editing-plugin.yml
apps/full-site-editing/full-site-editing-plugin/dotcom-fse/class-full-site-editing.php

Only trigger FSE build when the PR is opened or edited.
TBD.

FSE: don't trigger build on push events

---

apps/full-site-editing/full-site-editing-plugin/blog-posts-block/newspack-homepage-articles/blocks/homepage-articles/store.js

In trying to commit #39712 to WPCOM, I ran into some lint issues.
I submitted a fix for them over in Newspack here: https://github.com/Automattic/newspack-blocks/pull/386
This PR includes the same lint fixes.

Fix lint issues with Newspack

---

client/my-sites/migrate/section-migrate.jsx
client/my-sites/migrate/section-migrate.scss

* Updates the styling a bit, according to #39582
* Use Calypso.live link
* Start a migration
* "Fail" the migration by issuing a fail migration command or updating the record in the database. 
Fixes #39582

Site Migration: Fix Failed import styling

---

client/my-sites/domains/domain-management/dns/dns-details.jsx

* Fix DNS records Learn more link to open in new window
* Open the DNS editor and click on the "Learn more" link -> should open in new tab.

Fix DNS records Learn more link to open in new window

---

config/horizon.json

* Enable the feature flag for the new domain status screens on horizon
* I guess just test the domains screens on horizon

Domains: Enable new domain status screen

---

client/components/promo-section/index.tsx
client/components/promo-section/promo-card/cta.tsx
client/components/promo-section/promo-card/index.tsx
client/lib/abtest/active-tests.js
client/lib/wpcom-undocumented/lib/me.js
client/my-sites/earn/home.tsx
client/my-sites/earn/main.jsx

* Add Peer Referral Link to Earn section.
- Go to the Earn section and confirm working.
- Visit your peer referral link and confirm that it loads up.
---
---
---

Initial peer referral link work.

---

client/lib/cart-values/index.js
client/lib/checkout/validation.js
client/my-sites/checkout/checkout/redirect-payment-box.jsx

Ahead of some bigger changes to these files, I'm committing some lint fixes: 
* fix jsdoc issues in cart-values and checkout validation
* lint fix: use window.location instead of just location
* To test the redirect-payment-box, use either an account set to USD with a Chinese IP address or a an account set to EUR with a Polish/Belgian/Dutch/German ip address. 
You'll then be able to test an Alipay/P24/Bancontat/Ideal/Giropay payment
* The only part that changed is actually redirecting to the payment method - it isn't necessary to test beyond that.

Fix some minor issues in cart/checkout

---

apps/full-site-editing/full-site-editing-plugin/full-site-editing-plugin.php
apps/full-site-editing/full-site-editing-plugin/readme.txt
apps/full-site-editing/package.json

* Bump version
* Release details in the changelog attached (in readme.txt)

FSE: Update to 0.22

---

apps/notifications/src/index.ejs
apps/notifications/src/standalone/root.html
packages/calypso-analytics/src/tracks.ts

This picks up a cookie domain exclusion change.

Bump w.js version to 61.

---

apps/full-site-editing/full-site-editing-plugin/full-site-editing-plugin.php
apps/full-site-editing/full-site-editing-plugin/readme.txt
apps/full-site-editing/package.json

* Update FSE plugin to 0.23.
1. Apply the generated diff to your sandbox and smoke test the changes.

FSE: release version 0.23

---

client/landing/jetpack-cloud/components/backup-delta/index.jsx
client/landing/jetpack-cloud/components/backup-delta/style.scss
client/landing/jetpack-cloud/sections/backups/main.jsx

* This PR adds the realtime backup points in the BackupDelta component.
* Ensure that a site with realtime backups shows the realtime backup points.
* Ensure that a site with daily backups does not show the realtime backup points.

Jetpack Cloud: Improve BackupDelta component for realtime backups

---

client/my-sites/checkout/checkout/test/composite-checkout-thank-you.js

* The changes introduced in https://github.com/Automattic/wp-calypso/pull/39926 causes a test to fail. This PR fixes it.
* Tests should pass

Fix failing tests for the premium bump offer

---

client/my-sites/site-settings/seo-settings/form.jsx

Updates copy on SEO settings page to reflect Coming Soon mode whenever it's set.
1. Go to calypso.localhost:3000 (don't test on calypso.live as the feature flag is not enabled there)
1. Go to SEO settings on Private site, confirm the copy makes sense and says "Private"
1. Go to SEO settings on Coming Soon site, confirm the copy makes sense and says "Coming Soon"

[Coming Soon] Update copy in SEO settings

---

client/my-sites/post-type-filter/style.scss

Started with #39332 courtesy of @millerf 
**Before:**
**After:**
Fixes #16921

Posts Filters: add better styles for small screens

---

client/lib/abtest/active-tests.js
client/my-sites/earn/home.tsx

* Visit Earn section using calypso.live link below.
* Confirm Affiliate card is gone.
* Confirm peer referral card is shown.

Remove affiliate program card, and remove holdout on peer referral card.

---

client/landing/gutenboarding/onboarding-block/design-selector/style.scss

* Fix scroll not working in design selector.
* Go to `/gutenboarding` and get to the design selection stage.
* Scroll. It should scroll.
Fixes #40200.

Gutenboarding: Fix scroll not working in design selector.

---

config/production.json
config/stage.json

* This PR enables Site Migration for the staging and production environment
* Not sure what a good test would be for those. Generally needs a sanity check.

Site migration: Enable Site Migration flag on production and staging environments

---

client/landing/jetpack-cloud/components/daily-backup-status/index.jsx

Translate all the text strings inside the DailyBackupStatus component
- Check if all the text are translated or be ready to be translated
- Bonus: check if the texts are translated into other languages.

Translate all the text strings in DailyBackupStatus component

---

client/landing/jetpack-cloud/components/backup-delta/index.jsx

Translate all the text strings inside the BackupDelta component
- Check if all the text strings in the component are ready to be translated

Translate all the text strings in BackupDelta component

---

static/page-templates/page-templates.json

More theme definitions. This file changes were missing in my last PR, I'm going to merge it straight away, since it doesn't affect anything in production and it's just static content

Complete list of themes

---

client/landing/gutenboarding/onboarding-block/style-preview/preview.tsx
client/landing/gutenboarding/onboarding-block/style-preview/style.scss

Load rendered preview with fonts and dynamically update fonts.
Closes #40010.
Visit `/gutenboarding` in development and play with design previews and font selectors. Only **Rockfield** design is fully implemented.

Gutenboarding: Preview fonts

---

apps/full-site-editing/full-site-editing-plugin/full-site-editing-plugin.php
apps/full-site-editing/full-site-editing-plugin/readme.txt
apps/full-site-editing/package.json

* Make sure that G2 compatibility is working.
* Go through this list and make sure stuff works: https://github.com/Automattic/wp-calypso/commits/master/apps/full-site-editing.
We will rebase this PR as more changes are merged. (✅ rebased)
~Blocked by #40404~

Update FSE to version 0.25

---

client/landing/jetpack-cloud/sections/backups/rewind-flow/style.scss

* Remove accidental global `<p/>` and `<a/>` styling rules
N/A

Fix Jetpack Cloud CSS Bug

---

client/post-editor/editor-gutenberg-dialogs/index.tsx

This is a follow-up to https://github.com/Automattic/wp-calypso/pull/40122. It turns out that opt-in dialogs may be disabled entirely, so we can't assume one of them will be always displayed. This PR adds a redirection to wp-admin when they shouldn't be shown.
Start with creating a new private atomic site using a8c account and calypso.localhost:3000 (start with simple site then go atomic - it should stay private).
Let's test a few scenarios:
**Existing behavior keeps working**
Follow the test plan in https://github.com/Automattic/wp-calypso/pull/40122
**New behavior kicks in**
* Opt-in to Gutenberg on your private atomic site
* Go to wp-admin > plugins and install classic editor plugin
* Go back to Calypso
* Create a post, save it, in three dots menu select "Switch to classic editor"
* …

[Private sites] When opt-in dialogs are disabled, let's redirect straight to wp-admin

---

client/landing/gutenboarding/onboarding-block/style-preview/style.scss

* Make color darker by default and only change border on hover

Minor changes to font color on hover state

---

static/page-templates/defaults/bowen/en.json

Missing static file from my last PR

Gutenboarding: missing template defaults

---

client/my-sites/pages/main.jsx
client/my-sites/pages/page-card-info/index.jsx
client/my-sites/pages/page-list.jsx
client/my-sites/pages/page/index.js

This is a rebased version of this PR: [#40148](https://github.com/Automattic/wp-calypso/pull/40148)
Test were failing previously and we wanted to test if they are passing after a rebase on master.
cc @DavidRothstein @gwwar

Search across all pages

---

config/stage.json

* Adds the search plan purchase flows onto staging
* Try purchasing in staging

Jetpack Search: Search plan to staging for testing the full flow.

---

client/blocks/login/continue-as-user.jsx
client/blocks/login/continue-as-user.scss

* Follow up of https://github.com/Automattic/wp-calypso/pull/40125 to update text so that it matches the design
* Stay logged-in
* Open `/log-in`, change locale (eg: `/log-in/es`) and check if all strings are translated
Fixes #39988

Update text on the login screen for logged in user

---

client/landing/gutenboarding/onboarding-block/acquire-intent/style.scss
client/landing/gutenboarding/onboarding-block/colors.scss

* Case insensitive match exact vertical strings
* Remove transition delay
* Faster transition duration (set by variable for easy tweaking.
* Use `ease-in-out` for all timing functions.
* Check `/gutenboarding` result.

Gutenbaording: Fix background transitions and matching

---

client/landing/gutenboarding/onboarding-block/acquire-intent/arrow.tsx
client/landing/gutenboarding/onboarding-block/acquire-intent/vertical-select/index.tsx

5 mins review.
1. Remove the dot after the vertical name
2. Only show the vertical-field arrow for 3+ characters
3. Keep the layout stable when the arrow appears or disappears
- **Case 1**: Fill the vertical name and site title, the dot shouldn't appear.
- **Case 2**: Fill the vertical name, verify that the arrow only appears 3 characters in.
- **Case 3**: When the vertical name is filled the transition from 2 to 3 characters (arrow appearing) shouldn't change the layout at all.

Minor visual fixes for #40321

---

client/landing/gutenboarding/components/titles.scss
client/landing/gutenboarding/mixins.scss
client/landing/gutenboarding/onboarding-block/design-selector/style.scss
client/landing/gutenboarding/onboarding-block/style-preview/style.scss
client/landing/gutenboarding/variables.scss

* Adding padding to header and content
Run locally and visit:
- http://calypso.localhost:3000/gutenboarding/style
- http://calypso.localhost:3000/gutenboarding/design
Fixes #40605

Gutenboarding: Fixing spacing for page heading and content

---

client/landing/gutenboarding/stores/onboard/actions.ts

Send design _template_ as the template rather than the design as the template 🤷‍♂ 
Make D41188-code work better!
Test with D41188-code if you like.
Landing this on its own should introduce no behavioral changes without D41188-code.

Gutenboarding: Use template not design slug

---

client/my-sites/customer-home/locations/primary/index.jsx
client/my-sites/customer-home/main.jsx

Reverts Automattic/wp-calypso#40669
False alarm

Revert "Revert "My Home: Use the layout API results to render primary cards.""

---

client/landing/gutenboarding/stores/onboard/actions.ts

Remove a fallback value for a template that never existed.
* /gutenboarding
* Follow flow through to site creation.
* Selected template should be correctly sent in site creation network
request.

Gutenboarding: Remove twentytwenty template fallback

---

client/landing/gutenboarding/onboarding-block/design-selector/index.tsx
client/landing/gutenboarding/onboarding-block/design-selector/style.scss

* Design template image has smoother animation and box-shadow
* Change design template label font
Navigate to `/gutenboarding/design`
Fixes #40705

Gutenboarding: Change label style and image animations

---

client/landing/gutenboarding/onboarding-block/acquire-intent/vertical-select/index.tsx

* Speeding up the typer animation
* Changing text values that animate in
Navigate to /gutenboarding

Sped up typer animation speed and edited the text values

---

client/landing/gutenboarding/onboarding-block/acquire-intent/style.scss
client/landing/gutenboarding/onboarding-block/acquire-intent/vertical-select/index.tsx
client/landing/gutenboarding/onboarding-block/acquire-intent/vertical-select/style.scss

* Increase horizontal and top padding for intent capture screen
* Update next/skip button letter-spacing
* Remove grey border then input is empty and vertical typer is active
* go to /gutenboarding
* test the above changes that should match the prototype

Gutenboarding: Update intent capture style

---

client/blocks/product-selector/index.jsx

This PR Fixes #40771 .
* Jetpack Search requires a site to determine the pricing. 
We introduced a regression where we never place the Product selector into a placeholder mode since the jetpack/connect/store flow doesn't show have any Site attached to it yet. 
Before:
After:
* Go to http://calypso.localhost:3000/jetpack/connect/store/monthly and http://calypso.localhost:3000/jetpack/connect/store
Notice that the purchase buttons appear again. 
* Go to http://calypso.localhost:3000/plans/example.com the plans and solution show up just as you would expect

Jetpack Connection Store: make it possible to purchase Jetpack Backup in the initial connection

---

client/my-sites/customer-home/cards/notices/celebrate-notice/index.jsx
client/my-sites/customer-home/main.jsx

This PR updates some text content on suggestion by @kristastevens on #40773 .
* On this branch, cherry-pick f732bc7b1e5de7be2130251e2f321fde70d771d7 if it hasn't been merged yet (#40773 ).
* Create a new site, and verify the new content in the image above.

My Home: Update some header and notice text.

---

config/horizon.json
config/production.json

Push Search Product out to production.

Jetpack Search: Add Jetpack Search Product Plan to production.

---

client/landing/gutenboarding/onboarding-block/colors.scss

* Changing the vertical colors
* Navigate to /gutenboarding and type in any of the suggestions that animates in

Gutenboarding: Updated vertical colors before testing

---

client/my-sites/plan-features/scroller.jsx
client/my-sites/plans-features-main/gutenboarding-header/index.jsx
client/my-sites/plans-features-main/gutenboarding-header/style.scss
client/my-sites/plans-features-main/index.jsx
client/signup/config/steps-pure.js
client/signup/steps/plans/index.jsx
client/signup/style.scss

Gutenboarding: update plans grid header

---

client/my-sites/domains/domain-management/edit/navigation/enhanced.jsx

* I've commited a few placeholder strings that should not be translated. So here's a PR to remove them from the translation queue
* Open a domain management screen and verify that it still works and the new navigation is there (it's visible only in your dev environment)

Remove unnecessary string translations

---

client/landing/gutenboarding/components/close-button/index.tsx
client/landing/gutenboarding/components/domain-picker/index.tsx
client/landing/gutenboarding/components/domain-picker/suggestion-item.tsx
client/landing/gutenboarding/components/domain-picker/suggestion-none.tsx
client/landing/gutenboarding/components/header/index.tsx
client/landing/gutenboarding/components/login-form/enter-password/index.tsx
client/landing/gutenboarding/components/login-form/enter-username-or-email/index.tsx
client/landing/gutenboarding/components/login-form/index.tsx
client/landing/gutenboarding/components/signup-form/header.tsx
client/landing/gutenboarding/components/signup-form/index.tsx
client/landing/gutenboarding/gutenboard.tsx
client/landing/gutenboarding/onboarding-block/acquire-intent/index.tsx
client/landing/gutenboarding/onboarding-block/acquire-intent/site-title.tsx
client/landing/gutenboarding/onboarding-block/acquire-intent/vertical-select/index.tsx
client/landing/gutenboarding/onboarding-block/create-site/index.tsx
client/landing/gutenboarding/onboarding-block/design-selector/index.tsx
client/landing/gutenboarding/onboarding-block/index.ts
client/landing/gutenboarding/onboarding-block/style-preview/font-select.tsx
client/landing/gutenboarding/onboarding-block/style-preview/index.tsx
client/landing/gutenboarding/onboarding-block/style-preview/viewport-select.tsx

Remove the `NO` prefix from translation functions.
This likely had no impact as these translation functions were not extracted anyways.
- App builds and translation functions continue to work as before.
- Test the TOS link in the signup form
- Test the "Step X of Y" text in site creation

Gutenboarding: Remove NO translation prefix

---

client/landing/gutenboarding/components/domain-picker-button/index.tsx
client/landing/gutenboarding/components/header/index.tsx

Fixes the Gutenboarding flow when the user doesn't select any domain and they still got redirected to plans page.

Gutenboarding: Update condition for redirecting to plans page

---

client/landing/gutenboarding/onboarding-block/acquire-intent/style.scss

**Steps to reproduce**
1. Start fresh /new.
2. Enter a suggestion.
3. Try to click the 2nd and 3rd suggestion.
Fixes #40903

Gutenboarding: fix suggestions dropdown not clickable

---

apps/full-site-editing/full-site-editing-plugin/event-countdown-block/blocks/src/style.scss

* Adds some prefix to CSS keyframes and colors in scss to avoid any potential conflict since it can be included in the global CSS scope
* Add an expiring (or already expired) Event Countdown and confirm on the front end at the end of its countdown the fireworks display properly.

Update Event Countdown CSS to avoid potential conflict

---

client/my-sites/site-settings/settings-security/main.jsx

Currently in the Settings -> Security menu, server credentials can only be input for sites that subscribe to Jetpack Backup, either individually or as part of a bundle. This PR extends existing functionality, such that server credentials can be added for sites that subscribe to Jetpack Scan without also being subscribed to Backup.
* Add logic to the `SiteSettingsSecurity` component that checks to see if a site has Jetpack Scan purchased; if so, allow the `JetpackCredentials` component to be shown, unless the site has managed credentials.
* Create a site and purchase Jetpack Premium or Professional. Check Site Settings -> Security menu to verify server credentials form is shown.
* Create a site and purchase *only* Jetpack Scan as an individual product. Check Site Settings -> Security menu …

Site Settings: Show server creds input form for sites with Jetpack Scan

---

client/gutenberg/editor/calypsoify-iframe.tsx

Reverts Automattic/wp-calypso#40946

Revert "Fix: Wait longer for the iFrame to load for IE"

---

client/landing/gutenboarding/components/domain-picker/index.tsx

Autofocus on input in Gutenboarding's domain picker

---

packages/effective-module-tree/package.json

* Bump version of `@automattic/effective-module-tree`, preparing it for a release.
Nothing

Update effective-module-tree version

---

client/assets/stylesheets/shared/_typography.scss
client/components/formatted-header/style.scss
client/my-sites/customer-home/style.scss

Reverts Automattic/wp-calypso#41102

Revert "Use Recoleta on all page headings"

---

packages/calypso-analytics/README.md

Let's update the instructions with the available methods as we work on Gutenboarding.
👀 👓

Calypso analytics README update instructions

---

client/components/web-preview/content.jsx

Fixes: #41118
**To test:**
- logged-out, visit calypso.localhost:3000/theme/alves
- click 'open live demo' button
- verify that the preview modal opens and the Alves demo site is loaded

Theme Showcase: check if selected site exists before accessing URL

---

docs/development-workflow.md
docs/fallback-development-workflow.md

* Documents the `npm run start-fallback` script
* Adds tips for debugging in IE

Docs: Add docs for `npm run start-fallback` script

---

client/landing/gutenboarding/onboarding-block/design-selector/index.tsx

* Changing string from _Start over_ to _Go back_
* Navigate to /new/design

Gutenboarding: Updating the previous step button string

---

client/lib/abtest/active-tests.js

This is related to Private Atomic sites project p7DVsv-8qy-p2
This PR makes the feature available for 5% of users.
Visual testing should be enough

Enable private atomic sites for 5% of new users

---

apps/full-site-editing/full-site-editing-plugin/wpcom-block-editor-nux/src/wpcom-nux.js
client/landing/gutenboarding/components/signup-form/index.tsx
client/landing/gutenboarding/onboarding-block/acquire-intent/site-title.tsx
client/landing/gutenboarding/onboarding-block/design-selector/index.tsx
client/landing/gutenboarding/onboarding-block/style-preview/index.tsx

- Use copy suggested in p58i-8QA-p2#comment-45974
- Use period at the end of subtitles.
- Use period at the end of site title input when there is a non-empty value.
* go to `/new`
* check the copy/punctuation updates mentioned above
* Editor welcome modal changes can be reviewed by following FSE development guide: PCYsg-ly5-p2

Gutenboarding: update copy and punctuation

---

apps/full-site-editing/full-site-editing-plugin/block-patterns/patterns/call-to-action-02.php
apps/full-site-editing/full-site-editing-plugin/block-patterns/patterns/food-menu.php
apps/full-site-editing/full-site-editing-plugin/block-patterns/patterns/headline.php

This PR should add two new patterns and correct the text in the headline pattern so it doesn't appear to be a block with "Featured Post" functionality.
cc @iamtakashi @alaczek @obenland @davemart-in

FSE Plugin: Two new patterns, one pattern fix

---

client/my-sites/checkout/composite-checkout/test/composite-checkout.js
client/my-sites/checkout/composite-checkout/wpcom/components/wp-checkout-order-review.js
client/my-sites/checkout/composite-checkout/wpcom/components/wp-checkout-order-summary.js
client/my-sites/checkout/composite-checkout/wpcom/components/wp-checkout.js
client/my-sites/checkout/composite-checkout/wpcom/components/wp-order-review-line-items.js
packages/composite-checkout/README.md
packages/composite-checkout/demo/index.js
packages/composite-checkout/src/components/checkout-order-summary.js
packages/composite-checkout/src/components/checkout-steps.js
packages/composite-checkout/src/components/default-steps.js
packages/composite-checkout/src/components/loading-content.js
packages/composite-checkout/src/components/shared-icons.js
packages/composite-checkout/src/lib/line-items.js
packages/composite-checkout/src/public-api.js
packages/composite-checkout/src/theme.js

Reverts Automattic/wp-calypso#41063

Revert "New Checkout: split purchase details into second column"

---

apps/full-site-editing/full-site-editing-plugin/full-site-editing-plugin.php
apps/full-site-editing/full-site-editing-plugin/readme.txt
apps/full-site-editing/package.json

* Updates FSE plugin version to 1.1
* Use the generated diff to test the latests updates from changelog on you sandbox.
* Use the generated archive to test on Atomic sites.

FSE: Bump plugin version to 1.1

---

client/me/help/help-contact/index.jsx

Addresses 51-gh-happops
Changes the Contact Form confirmation message to note the delay we're having in responses.
Submit a help request, see the new message.

Contact: Add delay message to contact form confirmation

---

client/landing/jetpack-cloud/components/activity-card/index.jsx
client/landing/jetpack-cloud/components/activity-card/style.scss
client/landing/jetpack-cloud/components/backup-delta/index.jsx
client/landing/jetpack-cloud/components/daily-backup-status/index.jsx
client/landing/jetpack-cloud/sections/backups/main.jsx

Fix BackupStatus show the correct backup. Also, it improves the Activity Card to support streams inside of the card.
Activity card with streams
- Check if the issue disappeared (go to yesterday and again to today)
- Check the selected date on the URL if it matches with the Backup Status date
- Check if the activity card streams show as expected by the design

Fix BackupStatus show the correct backup + improve activity card with streams

---

client/landing/jetpack-cloud/sections/backups/backup-activity-log/index.tsx
client/landing/jetpack-cloud/sections/backups/detail/index.jsx
client/landing/jetpack-cloud/sections/backups/main.jsx
client/landing/jetpack-cloud/sections/scan/history/index.jsx
client/landing/jetpack-cloud/sections/scan/main.tsx
client/landing/jetpack-cloud/sections/scan/upsell.jsx
client/landing/jetpack-cloud/sections/settings/main.jsx

* Track page views in every Jetpack Cloud page.
* Should we track this page as well?
https://github.com/Automattic/wp-calypso/blob/master/client/landing/jetpack-cloud/sections/backups/rewind-flow/index.tsx#L72
* Should we track the Scan UpSell page? 
https://github.com/Automattic/wp-calypso/blob/master/client/landing/jetpack-cloud/sections/scan/upsell.jsx#L26
* Go to http://jetpack.cloud.localhost:3000/
* Select a site that has Backup and Scan
* Go to Backup > Status
* Verify the following action was dispatched
```
{
type: 'ANALYTICS_PAGE_VIEW_RECORD',
payload: {
service: 'default',
url: '/backups/:site',
title: 'Backups',
site_type: 'jetpack',
site: <YOUR_SITE_SLUG>
}
}
```
* Select any Backup details
* Verify the following action was dispatched
```
{
type: 'ANALYTICS_PAGE_VIEW_RECORD', …
```

Jetpack Cloud: track page views in Jetpack Cloud

---

client/landing/jetpack-cloud/components/masterbar/index.jsx
client/landing/jetpack-cloud/components/masterbar/style.scss
client/landing/jetpack-cloud/sections/backups/style.scss
client/landing/jetpack-cloud/style.scss

* Redesign the Jetpack Cloud Masterbar
1. Observe the Jetpack Cloud Masterbar across several different pages and browser widths

Jetpack Cloud: Redesign Masterbar

---

client/my-sites/activity/filterbar/style.scss

1. Navigate to `/activity-log`
2. Verify the "Date Range" button matches the after screenshot above while selecting dates

Fix Activity Log Filterbar Selection

---

client/my-sites/site-settings/form-general.jsx

* Now Earth Day is over, this simply reverses #41275 
* The interface included in this code doesn't show any more anyway because it's time and date windowed, so there should be no visible changes.

Remove Earth Day Live setting

---

config/stage.json

This PR enables `use-translation-chunks` feature for stage environment.
N/A

i18n: Enable translation chunks for stage

---

client/state/lasagna/middleware.js

* Add jwtType param to Lasagna middleware to match backend changes of D42651-code.

Lasagna: add jwtType param to fetcher fn

---

client/landing/gutenboarding/components/domain-categories/index.tsx
client/landing/gutenboarding/components/domain-categories/style.scss
client/landing/gutenboarding/components/domain-picker-modal/style.scss
client/landing/gutenboarding/components/domain-picker/style.scss

* Dropdown domain category for mobile view.
* Go to `/new` and then to domain picker modal.
* Resize the browser window until the domain category dropdown appears.
* Test the functionality of the domain category dropdown.

Gutenboarding: Added domain category dropdown for mobile view.

---

apps/full-site-editing/full-site-editing-plugin/full-site-editing-plugin.php
apps/full-site-editing/full-site-editing-plugin/readme.txt
apps/full-site-editing/package.json

* Make sure that G2 compatibility is working.
* Go through this list and make sure stuff works: https://github.com/Automattic/wp-calypso/commits/master/apps/full-site-editing.
We will rebase this PR as more changes are merged.

Update FSE to version 1.2

---

client/my-sites/plans-features-main/wpcom-faq.jsx

* Minor grammar fix for changes in #34722 
* Adds oxford comma to list of items

Plan Features FAQ: minor grammar update after #34722

---

apps/full-site-editing/full-site-editing-plugin/block-patterns/patterns/contact-02.php
apps/full-site-editing/full-site-editing-plugin/block-patterns/patterns/contact-03.php
apps/full-site-editing/full-site-editing-plugin/block-patterns/patterns/contact.php
apps/full-site-editing/full-site-editing-plugin/block-patterns/patterns/headline-02.php
apps/full-site-editing/full-site-editing-plugin/block-patterns/patterns/image-and-text.php
apps/full-site-editing/full-site-editing-plugin/block-patterns/patterns/numbers.php
apps/full-site-editing/full-site-editing-plugin/block-patterns/patterns/recent-posts-02.php
apps/full-site-editing/full-site-editing-plugin/block-patterns/patterns/recent-posts.php
apps/full-site-editing/full-site-editing-plugin/block-patterns/patterns/three-columns-and-image.php

This PR adds eight new patterns to the FSE Plugin and corrects one minor typo.
cc @johnHackworth @iamtakashi @obenland

FSE Plugin: new patterns, fix minor typo

---

client/landing/jetpack-cloud/components/activity-card/style.scss

* add word-wrap rule to `ActivityCardDescription` to clean up appearance
1. navigate to `/backups/activity`
2. find a offending card, or just paste into one of the elements my concerted Lorem Ipsum:
```
Loremipsumdolorsitamet,consecteturadipiscingelit.Sedsemperelitacodioauctoreleifend.Quisqueconguevelitturpis,eumaximusnisitinciduntsed.Nullamnecliberosem.Morbiidtortoretduieuismodtristiqueaindiam.Duisegestasaugueegettelluscommodofringilla.Fusceturpisaugue,pulvinaregetpretiumeu,dictuminmetus.Inidgravidarisus.Donecnullaest,dignissimposuereornarenon,imperdietinnibh.Etiamfinibustellusaturpisscelerisquefinibusinsedmetus.Utatposuereex.Seddignissimnisilorem,atsuscipitloremscelerisqueut.Sednonfermentumnisi.
Praesentaliquetmaximustempor.Pellentesquelaoreettellussedaccumsanpretium.Vestibulumornareesti …
```

Jetpack Cloud: Fix Activity Card Description Overflow

---

apps/full-site-editing/full-site-editing-plugin/full-site-editing-plugin.php
apps/full-site-editing/full-site-editing-plugin/readme.txt
apps/full-site-editing/package.json

Deploys fixes for #41380 and #41793
* Updated "Tested up to" field to 5.4, since that's what we'll be testing this against.
Not a big list of changes, but still keen to deploy so #41793 can be fixed before the soft launch of gutenboarding.
Instructions for deploying changes to sandbox and atomic: PCYsg-ly5-p2
Test that fixes are present #41380 and #41793

Update FSE to version 1.3

---

client/landing/jetpack-cloud/sections/backups/style.scss

It's a quick fix of the issue introduced recently in another PR. It shows always the vertical scrollbar. The fix 
- Check if the scrollbar doesn't show up now.

JP Cloud: Quick fix removing the vertical scrollbar from desktop views

---

config/horizon.json
config/production.json
config/stage.json
config/wpcalypso.json

Open the gates for plans grid in gutenboarding

Use plans grid in gutenboarding

---

client/landing/gutenboarding/components/header/style.scss

Gutenboarding: fix header whitespace

---

client/signup/controller.js

fixes the gutenboarding launch bug. Merging right away

fix redirect bug in gutenboarding

---

client/components/domains/contact-details-form-fields/custom-form-fieldsets/region-address-fieldsets.jsx
client/components/domains/contact-details-form-fields/index.jsx
client/components/domains/contact-details-form-fields/test/index.js
client/lib/form-state/index.js
client/my-sites/checkout/composite-checkout/composite-checkout.js
client/my-sites/domains/components/form/country-select.jsx
client/my-sites/domains/components/form/state-select.jsx

Reverts Automattic/wp-calypso#41723
Users report some odd behavior in the contact form of regular checkout - reverting so we can figure out what is going on.

Revert "Add managed mode to ContactDetailsFormFields"

---

apps/full-site-editing/full-site-editing-plugin/full-site-editing-plugin.php
apps/full-site-editing/full-site-editing-plugin/readme.txt
apps/full-site-editing/package.json

* Version bump and changelog.
Remaining PRs for this release:
* Apply this build, test changes since the last release found at: https://github.com/Automattic/wp-calypso/commits/master/apps/full-site-editing.
*  Test on atomic sites as well as outlined here: PCYsg-ly5-p2
We can rebase this PR as more changes are merged if necessary.

Update FSE to version 1.4

---

config/production.json

This PR enables translation chunks for production environment.
N/A

i18n: Enable translation chunks for production

---

client/landing/jetpack-cloud/components/daily-backup-status/backup-changes.jsx

* Don't Assume the Existence of ActivityMedia in `BackupChanges`
* N/A

Jetpack Cloud: Don't Assume the Existence of ActivityMedia

---

client/landing/jetpack-cloud/components/activity-card-list/index.jsx

* Fixes an error where checking Array.includes on a non-array.
* TBD
Fixes #

Jetpack Cloud: Fix error using includes on a non-array in ActivityCardList

---

client/landing/gutenboarding/stores/plans/plans-data.ts

* All of the plans have incorrect list of features.
* Just make sure those crossed out in the screenshot below is not there anymore.

Gutenboarding: Fix incorrect set of features on plans.

---

client/landing/jetpack-cloud/components/backup-date-picker/index.jsx
client/landing/jetpack-cloud/components/backup-date-picker/style.scss
client/landing/jetpack-cloud/sections/backups/style.scss

Update the style to match with the design for desktop view:
**Asana card:** 1142395350490785-as-1173708377241817
- Check if it matches the expected design, for desktop and mobile.

Update DatePicker styles to match the design

---

client/landing/gutenboarding/components/plans/plans-table/index.tsx
client/landing/gutenboarding/components/plans/plans-table/plan-item.tsx
client/landing/gutenboarding/stores/plans/plans-data.ts

Remove "per month, billed yearly" from the free plan. And use "Free forever" instead.

Small but important: free plans aren't billed

---

client/my-sites/plugins/plugin-compatibility.js

Don't block plugin anymore.
Plugin was updated to work with Calypso/Media Library:
https://plugins.trac.wordpress.org/changeset/2301400/
- Create a site
- Buy business plan
- Go to plugins
- Search for `armember`
Before:
After:

Atomic: Unblock armembership-memberships plugin

---

config/test.json

* Adds the experimentation platform to the test environment

Enable experimentation platform in test environment

---

client/landing/gutenboarding/components/domain-picker-modal/index.tsx
client/landing/gutenboarding/components/domain-picker-popover/style.scss

* Fixed popover fixed footer not working.
* Fixed popover unintended 1px border-top.
* Fixed domain modal header margin's cut off by window scrollbar when opened.
* Ensure the 3 items above are as described.
**Fixed popover fixed footer not working.**
---
**Fixed popover unintended 1px border-top.**
---
**Fixed domain modal header margin's cut off by window scrollbar when opened.**
---

Gutenboarding: Domain picker minor issues.

---

config/production.json

* This turns on the experimentation platform in production
Merge #42209 first.

Turn on experimentation platform in production

---

client/package.json

* Update lasagna.js client 0.4.0
1. Open Calypso Reader.
2. Verify websocket connection established (`101`) successfully.

Update lasagna.js client to 0.4.0

---

client/landing/jetpack-cloud/components/daily-backup-status/style.scss
client/landing/jetpack-cloud/components/fix-all-threats-dialog/index.tsx
client/landing/jetpack-cloud/components/fix-all-threats-dialog/style.scss
client/landing/jetpack-cloud/components/scan-threats/index.tsx
client/landing/jetpack-cloud/components/server-credentials-wizard-dialog/index.tsx
client/landing/jetpack-cloud/components/server-credentials-wizard-dialog/style.scss
client/landing/jetpack-cloud/components/threat-dialog/index.tsx
client/landing/jetpack-cloud/components/threat-dialog/style.scss
client/state/selectors/get-jetpack-credentials.js

* Ask for server credentials on the fix single threat and fix all threat dialogs (if we don't have them).
I created a component called `ServerCredentialsWizardDialog` that before displaying its content, will verify if we have the server credentials of the user. If there are no server credentials, the user will have to enter them before proceeding to the next step. Basically, I abstracted what we were already doing in the "Fix all threats" dialog so we can use it in the "Fix/Ignore threat" dialog.
* What should be the title of the dialog on the fix/ignore single threat case? The fix case looks fine to me, but the ignore case doesn't. See screenshots at the bottom.
* The server credentials form has a copy that fits well in the "Fix all threats" flow, but doesn't look great on the other …

Jetpack Cloud: prompt for server credentials on the fix/ignore single threat

---

client/my-sites/customer-home/cards/notices/celebrate-notice/index.jsx
client/my-sites/customer-home/cards/notices/celebrate-site-creation/index.jsx
client/my-sites/customer-home/cards/notices/celebrate-site-launch/index.jsx
client/my-sites/customer-home/cards/notices/celebrate-site-migration/index.jsx
client/my-sites/customer-home/cards/notices/celebrate-site-setup-complete/index.jsx
client/my-sites/customer-home/locations/primary/index.jsx

This PR drops the `-v2` notation from the notices since there are no more versions after removing the legacy ones in #42255.

My Home: Rename notices folders

---

apps/full-site-editing/full-site-editing-plugin/global-styles/class-global-styles.php
apps/full-site-editing/full-site-editing-plugin/global-styles/includes/class-data-point-theme.php

Fixes https://github.com/Automattic/wp-calypso/issues/42225

Fix array offset

---

client/landing/jetpack-cloud/components/with-server-credentials-form/test/index.js

Quick fix: Comment the test that causes the issue
**To-do:** review the test and fix the code or the test itself
- Does it pass the tests?

JCloud: Temporal fix of a test with an issue on Calypso Deploy

---

client/my-sites/plugins/plugin-compatibility.js

HEs tested the plugin after devs contacted
them. It's working fine and not breaking anything.
- Add a new site
- Buy Business plan
- Search for `under-construction-page`
- Make sure it's not blocked

Atomic: Unblock under-construction-page

---

apps/full-site-editing/full-site-editing-plugin/full-site-editing-plugin.php
apps/full-site-editing/full-site-editing-plugin/readme.txt
apps/full-site-editing/package.json

* Version bump and changelog.
Remaining PRs for this release:
* Apply this build, test changes since the last release found at: https://github.com/Automattic/wp-calypso/commits/master/apps/full-site-editing.
*  Test on atomic sites as well as outlined here: PCYsg-ly5-p2
We can rebase this PR as more changes are merged if necessary.

FSE Plugin: Update to v1.5

---

client/blocks/login/index.jsx
client/blocks/login/two-factor-authentication/two-factor-content.jsx

Reverts Automattic/wp-calypso#42500
This didn't fix the issue, bringing it back.

Revert "Revert "Async load 2FA login code (attempt #2)""

---

client/state/login/actions/push/package.json
client/state/login/init.js

* Pull in the 2fa data layer as part of login state init
* May make polling for updates work
*
Fixes #

Pull in the 2fa data layer as part of login state init

---

client/landing/jetpack-cloud/sections/backups/backup-activity-log/index.tsx
client/landing/jetpack-cloud/sections/backups/index.js
client/landing/jetpack-cloud/sections/backups/main.jsx
client/landing/jetpack-cloud/sections/backups/paths.ts
client/landing/jetpack-cloud/sections/home.tsx
client/sections.js

Update the slug for the backup section to "backup" from "backups"
* Load up this PR. 
* Does the url direct you to "backup" does it work as expected for the different urls that are possible?

Jetpack Cloud: Update backups to backup slug

---

config/jetpack-cloud-horizon.json

* Add config file for `jetpack-cloud-horizon`
N/A

Jetpack Cloud: Add Horizon Config

---

client/my-sites/domains/domain-management/edit/domain-types/site-redirect-type.jsx
client/my-sites/domains/domain-management/edit/index.jsx
client/my-sites/domains/domain-management/edit/navigation/enhanced.jsx
client/my-sites/domains/domain-management/edit/navigation/index.jsx

This PR updates the settings for Site Redirects to use the new site design
* Visit the domain settings page for a site redirect 
* Confirm that the new design is being used and looks like this:

Upgrade site redirect settings to use the new design

---

client/landing/gutenboarding/onboarding-block/design-selector/style.scss

* 2 column design selector on > mobile viewport.
* Resize browser until design selector becomes 2 column.
Fixes #42397

Gutenboarding: 2 column design selector on > mobile viewport.

---

client/devdocs/sidebar.jsx
docs/i18n.md
docs/translation-chunks.md

Adds documentation for translation chunks.
https://wpcalypso.wordpress.com/devdocs/docs/translation-chunks.md

Docs: Translation Chunks

---

client/landing/jetpack-cloud/sections/auth/controller.tsx
client/landing/jetpack-cloud/sections/auth/get-token/index.tsx
client/landing/jetpack-cloud/sections/auth/get-token/style.scss
client/landing/jetpack-cloud/sections/auth/index.ts
client/landing/jetpack-cloud/sections/auth/paths.ts

* Clean up Authentication Route
* Add a touch of style to briefly seen `GetToken` component
Make sure you can still authenticate with Jetpack Cloud

Jetpack Cloud: Cleanup auth section

---

client/my-sites/checkout/checkout-system-decider.js

the `isJetpackSite` selector returns true for Atomic sites too, thus sites are precluded from using composite checkout (even after AB assignment) if they've installed a theme or plugin. This adds the `isAutomatedTransferSite` selector to the checkout decider logic.
**To Test:**
- create an atomic site by installing a plugin or theme on a site with a business plan
- add a domain to your cart
- verify that you can visit composite checkout with `?flags=composite-checkout-testing``

Checkout: allow Atomic sites to use composite checkout

---

docs/troubleshooting.md

As. a new contributor I experienced some issues during building the project. More details on this at https://github.com/Automattic/wp-calypso/issues/42242. I'm not sure if this issue is prevalent, however, adding it and it's solution to troubleshooting docs seems valuable for other beginners. 
* Update troubleshooting.md with problem  `Command failed with exit code 127` encountered during build and its solution. 
I'll be happy to hear any feedback and make changes as necessary. Thanks @Aurorum for suggesting the fix.

Update troubleshooting.md with new problem

---

client/components/site-selector/index.jsx
client/landing/jetpack-cloud/components/backup-date-picker/index.jsx
client/landing/jetpack-cloud/components/masterbar/index.jsx
client/landing/jetpack-cloud/sections/backups/controller.js
client/state/navigation/middleware.js

* Finishing changing up backups to backup route
1. Make sure Jetpack Cloud works as expected

Jetpack Cloud: Finish `backups` => `backup` Route

---

client/landing/gutenboarding/components/plans/plans-table/style.scss
client/landing/gutenboarding/components/titles.scss
client/landing/gutenboarding/mixins.scss

* Adding another title size for tablet sized devices
* Go to /new and resize the browser and see the title change size between mobile and wide (>1200px)

Gutenboarding: Adding another breakpoint for size of title

---

client/landing/jetpack-cloud/components/activity-card/index.jsx
client/landing/jetpack-cloud/components/backup-date-picker/index.jsx
client/landing/jetpack-cloud/components/daily-backup-status/index.jsx
client/landing/jetpack-cloud/components/scan-threats/index.tsx
client/landing/jetpack-cloud/components/sidebar/index.jsx
client/landing/jetpack-cloud/lib/trigger-scan-run.ts
client/landing/jetpack-cloud/lib/use-threats.ts
client/landing/jetpack-cloud/sections/backups/backup-upsell/index.tsx
client/landing/jetpack-cloud/sections/backups/main.jsx
client/landing/jetpack-cloud/sections/scan/history/index.jsx
client/landing/jetpack-cloud/sections/scan/main.tsx
client/landing/jetpack-cloud/sections/scan/upsell.jsx

* Alters all existing tracks events to use the `jetpack_cloud_` source and context
* Adds several other tracks events using the proper source and context
* Load up all screens within Jetpack Cloud. Check for console errors or warnings.
* Feel free to run through the entire testing process for tracks events.
Fixes #

Jetpack Cloud: Tracks event alterations and additions for launch

---

config/desktop-development.json
config/desktop.json
config/horizon.json
config/production.json
config/stage.json
config/test.json

* Enables Upcoming Renewals Notifications (see internal master thread pbOQVh-8o-p2 )

Purchases: Turn on upcoming renewal notifications in all environments

---

client/landing/jetpack-cloud/components/sidebar/index.jsx

* Update the **Manage site** sidebar link text and icon to point to **WP Admin**, similar as in Calypso.
Fixes `1169345694087188-as-1176908000483289`
* Open Jetpack Cloud for any Jetpack-connected site
* Verify that in both mobile and desktop layouts, the bottom link in the sidebar shows the WordPress icon, the link text says "WP Admin," and that we display the "external link" icon since we're redirecting to an external site.
Mobile:
Desktop:
Mobile:
Desktop:

Jetpack Cloud: Change 'Manage site' sidebar link to 'WP Admin'

---

config/production.json

* Enable Lasagna in Calypso prod.
Manual testing via staging right now.

Lasagna: enable in Calypso prod

---

client/my-sites/checkout/composite-checkout/use-get-thank-you-url.js

This adds considerable debug lines to `getThankYouPageUrl()` so we can better understand why it makes the decisions it does.
None; if tests pass this is just adding debugging.

composite-checkout: Add debugging to getThankYouPageUrl

---

client/my-sites/checkout/checkout-system-decider.js

This adds logging in the `CheckoutSystemDecider` to track products that aren't supported in Composite Checkout when added as part of a special URL.
**To Test:**
- Visit calypso and enable debug logging by typing in your console: `localStorage.setItem('debug', 'calypso:checkout-system-decider')` and reloading the page.
- Attempt to add an unsupported product to Checkout via url: `http://calypso.localhost:3000/checkout/{site}/foo`
- Make sure the product isn't added to your cart (an empty cart will be redirected back to the plans page).
- Verify that the console.log debug shows `calypso:checkout-system-decider: shouldShowCompositeCheckout false because product does not match list of allowed products`
- Visit logstash and verify that a single error is reported for the failed product: …

Checkout: add logging for system decider failures

---

client/my-sites/sidebar/index.jsx

* Checks if a given site has Backup or Scan enabled with Cloud, and shows links in the sidebar.
* On a site with Scan, Backup, or both, open Tools in the sidebar in My Sites area.
* If the site is eligible for Cloud, links should display:
Fixes 1169345694087188-as-1164157450632314.

Adds Backup and Scan link to sidebar when Cloud is enabled

---

client/blocks/product-purchase-features-list/business-onboarding.jsx
client/blocks/product-purchase-features-list/index.jsx
client/me/concierge/book/info-step.js
client/me/concierge/main.js
client/me/concierge/shared/no-available-times.js
client/me/concierge/shared/primary-header.js
client/state/selectors/is-site-white-glove.js
client/state/selectors/test/is-site-white-glove.js
client/state/sites/constants.js

* Adds a selector to extract information whether a given site has the `is_white_glove` property set.
* Verify no JS errors and the selector tests pass.

White glove: Add selector to identify a white glove site

---

apps/full-site-editing/README.md

* Update the full site editing plugin README to reflect new structure for newspack blocks
* N/A

Add information about newspack blocks

---

client/my-sites/sidebar/index.jsx
config/desktop-development.json
config/desktop.json
config/development.json
config/horizon.json
config/production.json
config/stage.json
config/test.json
config/wpcalypso.json

* Add Feature Flag for new Jetpack Section
TBD

Add Jetpack section feature flag

---

client/post-editor/controller.js

* Wait for the selection of a new editor preference to complete before proceeding to determine which editor should be loaded. This allows for us to redirect to Calypso and opt-in to Gutenberg.
1. Fire up local Calypso 
2. Site a site to use the Classic Editor
3. Visit http://calypso.localhost:3000/post/:site/:post_id?set-editor=gutenberg
4. You should be presented with the Block Editor 
5. Check that without the query param you now get redirected to Block Editor
http://calypso.localhost:3000/post/:site/:post_id
6. Add the query string param again but this time set it to classic
http://calypso.localhost:3000/post/:site/:post_id?set-editor=classic
7. Ensure that you are given the Classic Editor as before this update

Editor: Wait for editor selection before deciding editor to load

---

apps/full-site-editing/full-site-editing-plugin/mailerlite/subscriber-popup.php

* Fix undefined variable lint error
The lint error is making it difficult to commit the FSE change to svn.
* Apply D44778-code
* Run lint checks
* Test Mailerlite widget works as expected (instructions in #42885)

Fix undefined variable lint error

---

client/signup/controller.js

the crowdsignal exclusion from gutenboarding has been deleted someway. This restores it

Gutenboarding: exclude crowdsignal from the test

---

client/landing/gutenboarding/onboarding-block/plans/index.tsx
client/landing/gutenboarding/onboarding-block/style-preview/style.scss
packages/data-stores/src/plans/plans-data.ts
packages/plans-grid/src/plans-grid/index.tsx
packages/plans-grid/src/plans-table/index.tsx
packages/plans-grid/src/plans-table/plan-item.tsx
packages/plans-grid/src/plans-table/style.scss

1. Shows the selected domain in the plans' grid.
2. Matches the design of the plans' grid with the spec 1:1.
1. Navigate to [/new](https://hash-100cb81cfcdb272ce27471683a4e15ef45c78625.calypso.live/new).
2. Compare the design with the proposed designs in pbAok1-11X-p2.

Plans grid design changes

---

client/lib/signup/step-actions/index.js
client/signup/steps/p2-site/index.jsx

Reverts Automattic/wp-calypso#43333

Revert "P2 signup: use .p2.blog domain"

---

client/lib/signup/step-actions/index.js
client/signup/steps/p2-site/index.jsx

The same as #43333 but now for real!

P2 signup: use .p2.blog domain — 2nd try

---

apps/full-site-editing/full-site-editing-plugin/block-patterns/patterns/call-to-action-03.php
apps/full-site-editing/full-site-editing-plugin/block-patterns/patterns/images-with-titles.php
apps/full-site-editing/full-site-editing-plugin/block-patterns/patterns/two-column-text-and-image.php
apps/full-site-editing/full-site-editing-plugin/dotcom-fse/blocks/navigation-menu/index.php
apps/full-site-editing/full-site-editing-plugin/dotcom-fse/class-full-site-editing.php
apps/full-site-editing/full-site-editing-plugin/dotcom-fse/helpers.php
apps/full-site-editing/full-site-editing-plugin/dotcom-fse/templates/class-template-image-inserter.php
apps/full-site-editing/full-site-editing-plugin/dotcom-fse/templates/class-wp-template-inserter.php
apps/full-site-editing/full-site-editing-plugin/dotcom-fse/templates/class-wp-template.php
apps/full-site-editing/full-site-editing-plugin/global-styles/includes/class-data-point-option.php
apps/full-site-editing/full-site-editing-plugin/global-styles/includes/class-data-set.php
apps/full-site-editing/full-site-editing-plugin/global-styles/includes/class-json-endpoint.php
apps/full-site-editing/full-site-editing-plugin/newspack-blocks/index.php
apps/full-site-editing/full-site-editing-plugin/premium-content/subscription-service/class-wpcom-offline-subscription-service.php
apps/full-site-editing/full-site-editing-plugin/starter-page-templates/class-starter-page-templates.php
apps/full-site-editing/full-site-editing-plugin/starter-page-templates/class-wp-rest-sideload-image-controller.php

* Run `phpcbf` on the FSE plugin. Kept almost all changes (except for one or two which didn't look right.)
Make sure that changes look as expected and that the plugin still works.

Run phpcbf on fse plugin

---

apps/full-site-editing/full-site-editing-plugin/block-patterns/patterns/call-to-action-03.php
apps/full-site-editing/full-site-editing-plugin/block-patterns/patterns/coming-soon.php
apps/full-site-editing/full-site-editing-plugin/block-patterns/patterns/contact-04.php
apps/full-site-editing/full-site-editing-plugin/block-patterns/patterns/images-with-titles.php
apps/full-site-editing/full-site-editing-plugin/block-patterns/patterns/list.php
apps/full-site-editing/full-site-editing-plugin/block-patterns/patterns/numbered-list.php
apps/full-site-editing/full-site-editing-plugin/block-patterns/patterns/portraits-and-text.php
apps/full-site-editing/full-site-editing-plugin/block-patterns/patterns/two-column-text-and-image.php

When trying to deploy the FSE plugin to WP.com, SVN's pre-commit hooks complained about a number of lints. This PR fixes them.
As a follow-up, we should make sure that these get caught earlier -- ideally all of the following stages should run checks:
- Locally: on a pre-commit git hook
- Calypso: in CI
- TeamCity
Run PHPCS on the `patterns` subdir.

FSE: Fix lint errors flagged by PHPCS

---

client/lib/abtest/active-tests.js
client/my-sites/checkout/checkout-system-decider.js
client/my-sites/checkout/checkout/checkout-container.jsx
client/my-sites/checkout/checkout/index.jsx
client/my-sites/checkout/composite-checkout/composite-checkout.js
client/my-sites/checkout/composite-checkout/test/composite-checkout-thank-you.js
client/my-sites/checkout/composite-checkout/use-get-thank-you-url.js
client/my-sites/checkout/controller.jsx
client/my-sites/checkout/upsell-nudge/index.jsx
client/my-sites/checkout/upsell-nudge/plan-upgrade-upsell/index.jsx
client/my-sites/checkout/upsell-nudge/plan-upgrade-upsell/style.scss

Reverts Automattic/wp-calypso#43199
When folks attempt this again, please verify that tests pass before merging. We'll also need to bump the AB test date.

Revert "AB Test for Business bump offer"

---

apps/full-site-editing/full-site-editing-plugin/full-site-editing-plugin.php
apps/full-site-editing/full-site-editing-plugin/readme.txt
apps/full-site-editing/package.json

* Go through this list and make sure stuff works: https://github.com/Automattic/wp-calypso/commits/master/apps/full-site-editing.
We will rebase this PR as more changes are merged.

Update FSE to version 1.10.0

---

client/lib/abtest/active-tests.js
client/my-sites/checkout/checkout-system-decider.js
client/my-sites/checkout/checkout/checkout-container.jsx
client/my-sites/checkout/checkout/index.jsx
client/my-sites/checkout/composite-checkout/composite-checkout.js
client/my-sites/checkout/composite-checkout/test/composite-checkout-thank-you.js
client/my-sites/checkout/composite-checkout/use-get-thank-you-url.js
client/my-sites/checkout/controller.jsx
client/my-sites/checkout/upsell-nudge/index.jsx
client/my-sites/checkout/upsell-nudge/plan-upgrade-upsell/index.jsx
client/my-sites/checkout/upsell-nudge/plan-upgrade-upsell/style.scss

This implements the bump offer from https://github.com/Automattic/wp-calypso/pull/43199 and fixes a few tests that were failing.

AB Test for Business bump offer - take two

---

client/gutenberg/editor/calypsoify-iframe.tsx

Fixes a regression in e2e tests caused by #43301.

fix: restore default publish window behavior

---

client/server/pages/test/index.js

Simple typo discovered when working on #43324 😊

Fix a typo in server/pages/test

---

client/components/jetpack/wpcom-business-at/index.tsx

* No functional changes, just adds a comment for i18n.
N/A.

Jetpack Section: Adds a comment for translators

---

client/lib/abtest/active-tests.js

* Pausing AB test. More info here pbxNRc-m0-p2
* Go through the Signup flow. User step should be the first step in the flow.
Pauses https://github.com/Automattic/wp-calypso/pull/43061

Pausing AB test

---

desktop/bin/github/review-actions.js

Ensures CI notifications are _not_ triggered for non-PR jobs.
The logic merged in #43837 assumes the `CIRCLE_PULL_REQUEST` var is available. Except it's not available in jobs triggered directly off the master branch (of course). So when the `desktop-notify-github-success` is triggered, it fails, which also triggers `desktop-notify-github-failure`. This was observed in a  job that actually completed successfully: [link](https://app.circleci.com/pipelines/github/Automattic/wp-calypso/65858/workflows/afc680eb-d63e-431e-b35c-8ee56e1f9b7c/jobs/795145/steps)
To test these changes locally:
```
> export CIRCLE_PULL_REQUEST=
> cd desktop
> yarn run ci:github:add-review
> yarn run ci:github:dismiss-review
// expected output
> PR # is null (not in a pull request), exiting...

don't add/dismiss reviews for non-PR jobs

---

client/lib/post-normalizer/rule-content-detect-media.js
client/lib/post-normalizer/rule-content-make-embeds-safe.js
client/lib/post-normalizer/rule-content-remove-styles.js
client/lib/post-normalizer/test/index.js
client/lib/post-normalizer/utils/iframe-is-allowed.js
client/lib/post-normalizer/utils/index.js

* Rename `iframeIsWhitelisted` to `iframeIsAllowed`
* Rename `whitelistSelector` to `allowedMarkupSelector`
* Ensure all unit tests pass
Addresses part of #43395

Post Normalizer: Remove problematic "whitelist" language #43395

---

test/e2e/lib/gutenberg/gutenberg-editor-component.js
test/e2e/specs/wp-calypso-gutenberg-coblocks-spec.js
test/e2e/specs/wp-calypso-gutenberg-page-editor-spec.js
test/e2e/specs/wp-calypso-gutenberg-post-editor-spec.js

* This PR changes the name of the simple payment block to get the tests passing
* Cleans up the coblocks tests. There was a hack in place and I noticed that the tests weren't actually checking that the block was showing on the post, but instead it was probably just seeing the block in the editor still
* Ensure all tests pass in CI.

e2e: Fix payment block tests

---

client/my-sites/domains/domain-management/list/list-all.jsx

Uses a lazy loading component to ensure that only visible domain items fetch their associated site data and details.
* Visit the `domains/manage` page.
* Ensure that only visible items load data in the background. Use the browser development console to confirm that initially invisible items are loaded as placeholders.

Implements lazy loading of domain items in the all domains list

---

client/signup/controller.js

Our previous experiment `domain_step_plan_step_swap ` was started before #43675 was merged. Suggesting to change this to a new experiment name `signup_domain_plan_step_swap`.

Change experiment and variation names

---

.eslintrc.js
client/landing/gutenboarding/onboarding-block/acquire-intent/site-title.tsx
client/my-sites/plans/current-plan/jetpack-product-install/index.tsx
client/state/jetpack/settings/utils.js
packages/wpcom.js/test-need-complete-access-origin/test.wpcom.site.settings.js

* Add terms we are unable to currently change to remove problematic language and document the blocker
* Pick up 2 stragglers from the whitelist/blacklist cleanup that I missed
* Ensure unit tests pass
Part of #43395

ESLint: Allow specific whitelist terms and fix stragglers

---

packages/plans-grid/src/mixins.scss
packages/plans-grid/src/plans-grid/style.scss

This PR fixes the hidden CTA button in plans grid on mobiles. 
**Before:**
<kbd>
</kbd>
**After:**
<kbd>
</kbd>

Fix plans details margining on mobile

---

client/lib/media/actions.js
client/lib/media/test/actions.js

* Remove `MediaActions.update`
* Ensure all unit tests pass
* Ensure `MediaActions.update` isn't used anywhere throughout Calypso
part of #44001

media state: remove `MediaActions.update`

---

.eslintrc.js
static/page-templates/page-templates.json

* Rename Gutenboarding page template property to remove problematic language
* Property isn't used so no way to test
Fixes #43996

Gutenboarding: Rename problematic page template property

---

client/my-sites/checkout/checkout/index.jsx

* Jetpack Search is not yet implemented for private sites. Here, we redirect away from checkout to avoid purchases.
* Attempt to purchase Jetpack Search for a private sites
* When checkout renders, the user should be redirected to /plans
Fixes https://github.com/Automattic/wp-calypso/issues/44006

Jetpack Search: disable checkout step for private sites.

---

client/my-sites/customer-home/main.jsx

* There's no functional changes, only removing the A/A experiment component
Ensure user home doesn't change.

Revert the A/A experiment

---

client/my-sites/checkout/checkout/index.jsx

* Search is not yet ready to be released for private sites.
- purchase Search for a variety of sites

Jetpack Search: disable Search purchase for private sites

---

client/lib/post-normalizer/rule-content-detect-polls.js

* Fixes error thrown when given an invalid poll URL. If the regex does not return any matches it will throw an error because (null)[2].
* Ping belcherj for a post with Poll that causes failure.

Fixes poll detection on invalid poll url

---

client/devdocs/controller.js

* location should be window.location, while both work location is not allowed as a global.
* Be logged out.
* Goto: http://calypso.localhost:3000/devdocs/start
* Can you login?
* Goto: http://calypso.localhost:3000/devdocs/start
* Does it redirect to: http://calypso.localhost:3000/devdocs/welcome

Fix linting issue in devdocs controller

---

client/server/sanitize/index.js

* Fixes a regression introduced in https://github.com/Automattic/wp-calypso/commit/c685ff323dd110bc49b02e4790969c09b31aeb27#diff-0e096fa3c60b94b408181748ed14486fL47

Fix invalid regex.

---

client/lib/post-normalizer/test/index.js
client/lib/post-normalizer/utils/max-width-photonish-url.js

* Fix scheme-relative images in post normalizer
* Add tests to prevent future regressions
* Ensure the unit tests pass correctly

Fix scheme-relative images in post normalizer

---

test/e2e/lib/gutenberg/blocks/image-block-component.js

* Something changed with the image picker selectors so I had to make some changes to fix the tests
* Ensure all tests pass in CI

e2e: Update test image picker flow

---

apps/notifications/index.jsx
apps/notifications/package.json

`@yarnpkg/doctor` found a bunch of undeclared dependencies and missing peer dependencies:
```
➤ YN0000: ┌ /Users/sergio/src/automattic/wp-calypso2/apps/notifications/package.json
➤ YN0000: │ User scripts prefixed with "pre" or "post" (like "prebuild") will not be called in sequence anymore; prefer calling prologues and epilogues explicitly
➤ YN0000: │ /Users/sergio/src/automattic/wp-calypso2/apps/notifications/index.jsx:17:1: Undeclared dependency on react
➤ YN0000: │ /Users/sergio/src/automattic/wp-calypso2/apps/notifications/index.jsx:18:1: Undeclared dependency on classnames
➤ YN0000: │ /Users/sergio/src/automattic/wp-calypso2/apps/notifications/index.jsx:19:1: Undeclared dependency on page
➤ YN0000: │ /Users/sergio/src/automattic/wp-calypso2/apps/notifications/index.jsx:20:1: …
```

Declare missing dependencies for app/notifications

---

apps/full-site-editing/full-site-editing-plugin/full-site-editing-plugin.php
apps/full-site-editing/full-site-editing-plugin/readme.txt
apps/full-site-editing/package.json

* Bumps version number to 1.14
* Update release notes
Included in this release
- #44336 
- #44379
- #44323 (CI changes, didn't include a release note)
- #44069 (no release note needed as mentioned in the PR description)
Also added a missing entry to the 1.13 release notes for #44357
* Check I did write good the release notes :)
* Apply D46844-code 
* Sandbox your favourite test site
* Smoke test the editor and test that the included features work as expected
* Instructions for testing on Atomic: PCYsg-ly5-p2#atomic-testing

Update FSE to version 1.14

---

client/my-sites/checkout/composite-checkout/wpcom/components/wp-contact-form.js

Reverts Automattic/wp-calypso#44468
See pNPgK-5a9-p2

Revert "Checkout: Do not display contact details form if the cart is only renewals (2)"

---

client/layout/index.jsx

Add to the comment section the availability to receive Anti-Spam JITMs.
- Apply this patch in your sandbox: D46734-code
- Point `public-api.wordpress.com` to your sandbox 
- Create a new JN site or get one with a Free plan and without Anti-Spam
- Go to the Comment section and see the expected JITM

Add to the comment section the availability to receive JITMs.

---

.github/workflows/editing-toolkit-plugin.yml
apps/full-site-editing/README.md

1. Change workflow filename
2. Change workflow name
3. Change workflow comments
4. Change archive & app name (companion diff: D47220-code)
Workflow should continue working. The sync step will start working after diff is deployed.

Change FSE plugin GH workflow to editing toolkit

---

apps/full-site-editing/README.md

Remove test text that I accidentally committed to `main` in f3041c9.

Remove test text that was accidentally committed

---

client/my-sites/checkout/composite-checkout/composite-checkout.js

Reverts Automattic/wp-calypso#44564

Revert "Composite checkout: fix purchase link in duplicate notice"

---

client/my-sites/checkout/checkout-thank-you/business-plan-details.jsx
client/my-sites/checkout/checkout-thank-you/index.jsx

This PR changes **Get personalized help** copy to include the price of the Quick Start session.
See pbBQWj-eI-p2 for more details.
* Purchase a new Business plan or upgrade.
* On the Thank You pages which appears after Checkout
* The section **Get personalised help** should include the price of the Quick Start session.

Mention the price for the Quick Start session

---

apps/full-site-editing/README.md

* Add some notes to help devs who may not be familiar with `docker` and `wp-env`
No code changes, just check out the README

FSE: Add a few notes to help with wp-env (and docker)

---

client/my-sites/checkout/composite-checkout/wpcom/components/wp-checkout.js

Reverts Automattic/wp-calypso#44690

Revert "Checkout: show full domain contact details when invalid cached details exist"

---

client/components/jetpack/card/jetpack-product-card/fixture/index.ts

Update the data that populates the `JetpackProductCard` component in the dev docs example to make it consistent and avoid confusion.
- Visit `/devdocs/design/jetpack-product-card`
- Check that just the copy changed

Product card: update example copy

---

packages/wp-babel-makepot/utils/concat-pot.js

* Changes translation extraction scripts to work then there are no translations.

Fix makepot error

---

client/signup/steps/p2-site/index.jsx

We've been seeing several P2 signup form validation failures (like the infamous "A" error). However, we have not been able to repro these errors locally. Let's add logstash logging so we can diagnose the issues better.
Apply D47645-code and sandbox public-api. Go to `/start/p2` and cause validation failures. Open Kibana/logstash and look for the `feature:calypso_wp_for_teams` entries under `log2logstash-*` index pattern. You should find your error.
Should we log anything else? Is this enough?

P2: add logstash logging for signup form validation failure

---

client/landing/gutenboarding/lib/analytics/index.ts
client/landing/gutenboarding/onboarding-block/acquire-intent/acquire-intent-text-input/index.tsx
client/landing/gutenboarding/onboarding-block/acquire-intent/acquire-intent-text-input/style.scss
client/landing/gutenboarding/onboarding-block/acquire-intent/index.tsx
client/landing/gutenboarding/onboarding-block/acquire-intent/site-title.tsx
client/landing/gutenboarding/onboarding-block/acquire-intent/style.scss
client/landing/gutenboarding/onboarding-block/acquire-intent/vertical-select/index.tsx
client/landing/gutenboarding/onboarding-block/acquire-intent/vertical-select/style.scss
client/landing/gutenboarding/stores/onboard/actions.ts
client/landing/gutenboarding/stores/onboard/index.ts
client/landing/gutenboarding/stores/onboard/reducer.ts
client/landing/gutenboarding/stores/onboard/selectors.ts
client/landing/gutenboarding/variables.scss
packages/onboarding/styles/z-index.scss

This PR re-adds the vertical input to the intent capture.
When the user presses "I don't know" to the vertical, I couldn't figure out how the UI should behave, and it's not spec'd in the design.
Please test as many as possible scenarios of site vertical and site title variations. If you could test on your phone it would be nice too.

Re-add vertical input to intent capture

---

client/lib/abtest/active-tests.js
client/signup/controller.js

Add A/B test for vertical input in Gutenboarding.

Gutenboarding: Add verticals a/b testing.

---

client/signup/config/flows-pure.js

Adding a missed flow in #44786 please look in that PR for more details.
1. Go to the url https://${host}/start/account. For example for the main flow in production go to the.
2. Reach the user step in the relevant flow.
3. Check if the "reCaptcha" icon is available in the bottom right corner.

Added recaptcha for the account flow

---

client/landing/gutenboarding/stores/domain-suggestions/index.ts
client/lib/domains/suggestions/index.js
client/signup/steps/domains/index.jsx
config/development.json
config/wpcalypso.json

* Add feature flag for premium domains
* Refactor the `getSuggestionsVendor` to support options and return the new variation for premium domains
* Depends on D48013-code

Adds premium domain suggestions support

---

docs/code-reviews.md

* Unnecessary comma before "and" needs to be removed.
* Repetition of "then" needs to be removed.
Fixes:

Corrected some grammatical errors.

---

client/my-sites/plans-v2/utils.ts

This PR changes the case of the button label in the product card.
Optionally, check the changes live.

Update product card label to respect sentence case

---

client/my-sites/checkout/composite-checkout/components/wp-order-review-line-items.js

Reverts Automattic/wp-calypso#44651
There is a failing test, so reverting till a fix is in place.

Revert "Checkout: Remove cart message for PWPO users"

---

client/my-sites/plans-v2/README.md
client/my-sites/plans-v2/utils.ts

* This is mostly a text update to better outline the flow of data now that things have settled down.
* Also includes a minor fix with code as the TS was being very sad at me.
* Read the new copy and ensure it is clear.
* Ensure the one line fix doesn't cause any regression issues.
Fixes 1169247016322522-as-1188698065630113.

Offer Reset: Update Readme

---

test/e2e/lib/gutenberg/gutenberg-editor-component.js
test/e2e/specs/wp-calypso-gutenberg-coblocks-spec.js

Updates e2e tests so they work with v2.2.

CoBlocks: Fix e2e for v2.2

---

test/e2e/lib/gutenberg/gutenberg-editor-component.js
test/e2e/specs/wp-calypso-gutenberg-coblocks-spec.js
test/e2e/specs/wp-calypso-gutenberg-post-editor-spec.js

Reverts Automattic/wp-calypso#45345

Revert "[E2E] Embed block fixes"

---

desktop/package.json

This is part of the release process for the desktop app

Merge release 6.0.3

---

client/landing/jetpack-cloud/sections/settings/host-selection/index.tsx

Fixes a typo in the English text of #45371

Fix typo in Jetpack Settings Host Detection

---

packages/calypso-build/CHANGELOG.md
packages/calypso-build/package.json

Bump `calypso-build` to `6.3.0`

Calypso Build: Bump to v6.3.0

---

client/landing/jetpack-cloud/sections/pricing/jpcom-masterbar/style.scss
client/my-sites/plans-v2/style.scss

Reverts Automattic/wp-calypso#45510

Revert "Minor style updates to cloud pricing page on mobile"

---

client/landing/jetpack-cloud/sections/pricing/jpcom-masterbar/style.scss
client/my-sites/plans-v2/style.scss

Reverts Automattic/wp-calypso#45527

Minor style updates to cloud pricing page on mobile

---

apps/editing-toolkit/package.json

Reverts Automattic/wp-calypso#45502

Revert "Editing Toolkit: Add ES5 check"

---

apps/editing-toolkit/package.json

Reverts Automattic/wp-calypso#45550

Revert "Revert "Editing Toolkit: Add ES5 check""

---

client/my-sites/plans-v2/upsell.tsx

Reverts Automattic/wp-calypso#45592

Revert "Offer Reset: Move the header into the Upsell component"

---

client/webpack.config.desktop.js

Reverts Automattic/wp-calypso#45569

Revert "Adds support for importing `calypso` package in Desktop source"

---

client/components/domains/domain-product-price/index.jsx
client/components/domains/domain-product-price/style.scss
client/components/domains/domain-registration-suggestion/index.jsx
client/components/domains/domain-search-results/index.jsx
client/components/domains/domain-suggestion/index.jsx
client/components/domains/featured-domain-suggestions/index.jsx
client/components/domains/register-domain-step/index.jsx
client/lib/abtest/active-tests.js
client/lib/signup/site-type.js
client/signup/config/steps-pure.js
client/signup/main.jsx
client/signup/steps/domains/index.jsx
client/state/signup/preview/selectors.js

Reverts Automattic/wp-calypso#44961

Revert "Remove variables and references to variables of the AB test parameter isEligibleVariantForDomainTest"

---

client/my-sites/plans-features-main/jetpack-faq.jsx

* Our current FAQ section below the plans grid is not up to date so the purpose of this PR is to update the copy of every question.
* Run this PR with `yarn start`. 
* Visit `jetpack/connect/store`.
* Go to the bottom of the page and verify that there are 5 questions.
* Verify that links work as expected.
* Verify that the copy is correct (the link to the document is the ticket).
Fixes 1169247016322522-as-1193401773801897

Plans: update FAQ section

---

client/lib/abtest/active-tests.js

* Open up the Offer Reset AB experiment for everyone.
* Make sure the changes make sense regarding the goal of this PR.
Fixes 1169247016322522-as-1193407870775793

Offer Reset: Launch!

---

config/jetpack-cloud-production.json

* Include the Pricing page in Calypso Green's production build process.
*  Make sure the changes make sense regarding the goal of this PR.
Fixes 1169247016322522-as-1193407870775795

Offer Reset: Include the Pricing page in production's build

---

client/lib/plans/plans-list.js
client/state/selectors/is-site-google-my-business-eligible.js
client/state/selectors/test/is-site-google-my-business-eligible.js

In this PR, we remove Google My Business from the list of features proposed by Jetpack plans.
Code review should be sufficient.

Remove Google My Business feature from Jetpack

---

client/my-sites/plan-features/header.jsx

There's an error in the signup when currentSitePlan is nuull
1. Sign up
2. Make sure the signup step shows no errors
Fixes #

currentSitePlan can be null

---

client/my-sites/checkout/composite-checkout/components/wp-order-review-line-items.js

Take 2 of https://github.com/Automattic/wp-calypso/pull/44651 that was reverted due to a failing test.

Checkout: Remove cart message for PWPO users - take 2

---

test/e2e/lib/gutenberg/gutenberg-editor-component.js

Prepare e2e tests for Gutenberg 9.1 compatibility.

Gutenberg: 9.1 e2e tests

---

client/my-sites/scan/main.tsx

Fixes `1164141197617539-as-1190430272654996`.
* Suppress the loading placeholder on `ScanPage` for the `scanning` and `provisioning` states while a status update request is in progress.
* Move code around to help simplify boolean logic and nesting
**Prerequisite:** Testing this pull request requires access to a site that has Jetpack Scan, as well as an admin or owner to scan the site.
**Tip:** Try testing this pull request with your network speed throttled (see the Network panel in your browser's console).
* In either Jetpack Cloud or Calypso, load the **Scan** page.
* Click **Scan now**.
* Verify that the loading placeholder does not appear at any point during the Scan.
* Verify that the scan states follow a logical progression (e.g., 'okay' -> 'preparing' -> 'scanning' -> [ 'success' | …

Scan: Suppress loading placeholder when a Scan is in progress

---

client/jetpack-cloud/sections/settings/advanced-credentials/credentials-form/index.tsx
client/jetpack-cloud/sections/settings/advanced-credentials/credentials-form/inline-info.tsx
client/jetpack-cloud/sections/settings/advanced-credentials/credentials-form/style.scss
client/jetpack-cloud/sections/settings/advanced-credentials/form.ts
client/jetpack-cloud/sections/settings/advanced-credentials/host-info.ts
client/jetpack-cloud/sections/settings/advanced-credentials/host-selection/index.tsx
client/jetpack-cloud/sections/settings/advanced-credentials/host-selection/style.scss
client/jetpack-cloud/sections/settings/advanced-credentials/index.tsx
client/jetpack-cloud/sections/settings/advanced-credentials/verification/index.tsx
client/jetpack-cloud/sections/settings/controller.tsx

Jetpack Cloud: Update New Credentials Route & Style

---

client/components/activity-card/activity-actor.tsx
client/components/activity-card/style.scss
client/components/jetpack/backup-delta/style.scss
client/components/jetpack/daily-backup-status/action-buttons.jsx
client/components/jetpack/daily-backup-status/status-card/backup-successful.jsx
client/components/jetpack/daily-backup-status/status-card/style.scss

Same PR as #46165, with passing checks.

Upgrade Backup successful state design (successful checks)

---

client/jetpack-cloud/sections/settings/advanced-credentials/credentials-form/index.tsx
client/jetpack-cloud/sections/settings/advanced-credentials/credentials-form/inline-info.tsx
client/jetpack-cloud/sections/settings/advanced-credentials/host-selection/index.tsx
client/jetpack-cloud/sections/settings/advanced-credentials/index.tsx
client/jetpack-cloud/sections/settings/controller.tsx

* Add Tracks Events to new Host-Specific Flow
* Refactor state logic of Advanced Credentials Flow
**TBD**

Jetpack Cloud: Add Tracks Events to Host-Specific Flow

---

client/jetpack-cloud/sections/settings/advanced-credentials/credentials-form/index.tsx
client/jetpack-cloud/sections/settings/advanced-credentials/host-info.ts

Jetpack Cloud: Update Host Info for top hosts

---

client/lib/plans/plans-list.js

The PR updates some of the copy for Jetpack Complete on the plans page.
1. Load the plans page.
2. Verify that the copy for Jetpack Complete is updated.
Fixes #1196341175636977-as-1198173394037033

Plans: Update Jetpack Complete Copy

---

client/components/jetpack/card/jetpack-product-card-alt/index.tsx
client/components/jetpack/card/jetpack-product-card-alt/style.scss

* Update alternative Jetpack Plans page to better align the features expansions
1. Check the `Show/Hide Features` toggle at various screen widths. Make sure the toggles are never misaligned in a row.

Jetpack Plans Page: Align Features Toggle

---

client/components/step-progress/README.md
client/components/step-progress/docs/example.tsx
client/components/step-progress/index.tsx
client/components/step-progress/style.scss
client/jetpack-cloud/sections/settings/advanced-credentials/style.scss

* Update `StepProgress` Component based on design
1. Navigate to `/devdocs/design/step-progress` on branch
2. Verify clicking the step numbers ( 1, 2, etc ) navigate to the correct step

Update Step Progress Component

---

client/my-sites/checkout/composite-checkout/use-create-payment-methods.js

* Minor refactor of the useCreateApplePay hook for clarity
This requires testing an apple pay purchase.
I tried to make the commits make sense in order for review.

Refactor useCreateApplePay hook

---

.circleci/config.yml

* This PR moves the CHROME_VERSION variable directly in to the config so that is doesn't block OSS PRs
* Make sure it passes in CI

Add the CHROME_VERSION variable directly to the config.

---

client/lib/titan/has-titan-mail-with-us.js
client/state/sites/domains/assembler.js
client/state/sites/domains/schema.js
client/state/sites/domains/test/fixture/index.js

This PR updates the Titan subscription check function to use the data returned from the backend.
See D51192-code

Email: Update Titan subscription checker

---

client/my-sites/email/email-management/index.jsx

This launches the Titan MVP to all.
Verify the flag is no longer required 👀

Email: Launch Titan MVP

---

client/layout/utils.ts

* Add typescript typing to `handleScroll` function
* Same as #46689

Add React.UIEvent type to handleScroll function

---

client/components/jetpack/threat-item/utils.ts

* Add a description for a new type of fixer that will edit a file.
* Create a Jurassic Ninja site at https://jurassic.ninja/create/?shortlived
* Change your wp-config file to have the default placeholder strings as below:
```
define( 'AUTH_KEY',          'put your unique phrase here' );
define( 'SECURE_AUTH_KEY',   'put your unique phrase here' );
define( 'LOGGED_IN_KEY',     'put your unique phrase here' );
define( 'NONCE_KEY',         'put your unique phrase here' );
define( 'AUTH_SALT',         'put your unique phrase here' );
define( 'SECURE_AUTH_SALT',  'put your unique phrase here' );
define( 'LOGGED_IN_SALT',    'put your unique phrase here' );
define( 'NONCE_SALT',        'put your unique phrase here' );
define( 'WP_CACHE_KEY_SALT', 'put your unique phrase here' );
```
* Connect …

Add description for the new type of 'edit' fixers

---

client/state/experiments/hooks.ts
client/state/experiments/selectors.ts
client/state/experiments/test/hooks.ts

* Add React hooks so we can use the selectors eaiser in functional components.
* Also refactor the selectors to have more specific types.
* The related test suites should be passed.
```
$ yarn test-client client/state/experiments/test/hooks.ts
```

ExPlat: Add hooks

---

client/components/jetpack/server-credentials-form/index.jsx

Small copy change to clarify what an encrypted key is.
**Before:**
**After:**
cc @coder-karen 
* Pull this PR
* Enter the Jetpack cloud UI
* Check the settings screen (SSH/SFTP route) for updated copy below key form as per above screenshots

Jetpack Cloud: Explain that encrypted keys are those with a passphrase

---

test/e2e/lib/gutenberg/gutenberg-editor-component.js

* This PR fixes the recently broken pricing table tests
* make sure the e2e tests pass in CI

e2e: Fix the pricing table block tests

---

config/stage.json

Enables Reader list management for staging.

Reader Lists: Enable list management for staging

---

.teamcity/settings.kts

* Run Desktop tests automatically on every branch.
* Verify any TeamCity build for this branch passes. That means I didn't make a syntax error on the config.
* The actual behaviour (run tests automatically) can't be tested until merged.

Run desktop e2e on every branch

---

client/my-sites/people/role-select/index.jsx

* Add the contributor back
* Go to Manage -> People -> Invite
* The Contributor role should be available
Fixes 1364-gh-p2

Add contributor role back

---

packages/data-stores/src/site/actions.ts
packages/data-stores/src/site/reducer.ts
packages/data-stores/src/site/resolvers.ts
packages/data-stores/src/site/selectors.ts
packages/data-stores/src/site/test/resolvers.ts
packages/launch/src/hooks/use-domain-search.ts
packages/launch/src/hooks/use-site.ts
packages/launch/src/hooks/use-title.ts

* Add a new selector on `Site` data store.

Add isFetchingSiteDetails selector to Site data-store

---

test/e2e/specs/wp-gutenboarding-spec.js

This is a test to get familiar w/ reverting failing commits.

Simulate E2E failure (part of onboarding process)

---

client/landing/gutenboarding/stores/domain-suggestions/index.ts

This is just a PR to simulate stacking.

Linting a comment (stacking simulation PR).

---

client/my-sites/checkout/index.js
config/jetpack-cloud-development.json
config/jetpack-cloud-horizon.json
config/jetpack-cloud-stage.json

* This is an experiment to test adding the checkout page to Jetpack.com. It should not be merged.
* TBD
Fixes 1199166334111093-as-1199211705978607

Experiment: Add Checkout to Jetpack
