client/reader/stream/post-lifecycle.jsx
via https://github.com/Automattic/wp-calypso/pull/37804#discussion_r348965248
* Replace shouldComponentUpdate with react-redux `areOwnPropsEqual` option.
* No behavioral changes
* Ensure the reader stream does not have increased rerenders
=> Reader: Replace shouldComponentUpdate with react-redux option

client/landing/gutenboarding/components/domain-picker/button.tsx, client/landing/gutenboarding/components/domain-picker/list.tsx, client/landing/gutenboarding/components/domain-picker/style.scss
* use 'Select' as link text for free domain
* 'Upgrade' link redirects to another flow
Visit http://calypso.localhost:3000/gutenboarding and search for a domain.
Clicking on 'Upgrade' link next to a paid domain should open an external page.
=> Gutenboarding: domain picker display free and paid domains

client/components/domains/use-your-domain-step/style.scss
* The illustrations on the "Use a domain I own" step take up a lot of vertical real estate on narrow screens, and don't add much clarity to the experience.
* This PR hides them on small screens, which helps give the primary action more prominence.
* The illustrations remain on screens > 660px wide.
**Before**
**After**
* Navigate to `/start` and sign up for a new site 
* At the domains step, click "Use a domain I own"
* View the screen on both mobile and desktop devices. Desktop devices should have illustrations, mobile should not.
* The same should apply if you go to Manage -> Domains, search for a new domain, and click "Use a domain I own"
=> Domains/Signup: Hide illustrations on mapping/transfer on small screens

client/landing/gutenboarding/components/domain-picker/button.tsx
Gutenboarding: Add missing i18n import
In https://github.com/Automattic/wp-calypso/pull/37821#discussion_r349090356, I wrapped an untranslated string in a `NO__()` call, but forgot to actually import that symbol. My bad :confused: 
Props @johnHackworth for discovering.
Restart Calypso. Is http://calypso.localhost:3000/gutenboarding building and running?
=> Gutenboarding: Add missing i18n import

client/landing/gutenboarding/stores/onboard/actions.ts, client/landing/gutenboarding/stores/onboard/reducer.ts
Gutenboarding: Fix DomainName type imports
Other options @sirreal and I discussed are:
- Define `DomainName` separately in `client/landing/gutenboarding/stores/onboard/types.ts`, see https://github.com/Automattic/wp-calypso/pull/37820/files#r349096785
- Remove the `DomainName` type alias altogether, just use `string` everywhere
Happy to go with the latter instead of this PR; not a big fan of the former. We can discuss on this PR.
No functional changes, but `npm run typecheck -- --project tsconfig/gutenboarding.json` should produce 2 errors less than on `master`.
=> Gutenboarding: Fix DomainName type imports

client/my-sites/domains/domain-management/dns/index.jsx, client/my-sites/domains/domain-management/dns/style.scss
* We show the page title twice, both in the SectionNav and in a SectionHeader. This PR removes the SectionHeader to reduce redundancy.
* Also changes the styling on the explanatory copy above the settings to be easier to read; increase contrast and font size.
* Fixing the Flows will also be adding proper headings to all Calypso pages, so this will become even more redundant soon.
**Before**
**After**
* Navigate to Manage -> Domains
* Click on a custom domain name to view its settings
* Click DNS Records
* Check to see that there is a title present on both desktop and mobile devices.
* Also check to make sure there are no visual bugs as a result of removing the SectionHeader.
=> Domains: Remove redundant DNS Records SectionHeader

client/my-sites/domains/domain-management/list/index.jsx
* "Domains" as a title is repeated three times on mobile devices.
* We're in the process of adding page headings to all Calypso pages, including Domains. This renders the SectionHeader title redundant, and we already display the title elsewhere on this page as part of the SectionNav and in the site title area on mobile.
**Before**
**After**
* Navigate to Manage -> Domains
* You should no longer see a `SectionHeader` label. 
* Make sure there are no visual bugs as a result of removing the label.
=> Domains: Remove redundant SectionHeader label

packages/composite-checkout/src/theme.js, packages/composite-checkout/src/wpcom/wp-order-review-line-items.js
This PR stubs in the term duration for the plan product.
* Get checkout up and running locally with these instructions: https://github.com/Automattic/wp-calypso/pull/37013
* Make your way to the review section and "checkout" the new options.
=> Composite checkout: Add term duration

packages/composite-checkout/src/lib/payment-methods/apple-pay.js, packages/composite-checkout/src/lib/payment-methods/credit-card.js, packages/composite-checkout/src/lib/payment-methods/paypal.js, packages/composite-checkout/src/lib/styled-components/payment-method-logos.js
This PR fixes a layout issue in ie11. The flex property `justify-content: space-between;` is not recognized in ie so I found a different way to deliver the same outcome. 
**Before**
**After**
* Get checkout up and running on your local machine.
* If you have a virtualbox, or anyway to test in IE, visit checkout with IE.
* Check other browsers to make sure nothing looks different.
=> Composite checkout: Fix payment logo layout for ie11

client/my-sites/plan-features/scroller.jsx
On narrow viewports where the calculated cell width of the plan cards would be lower than the minimum cell width, the cell width would be calculated against a zero visible count resulting in a divide by zero, resulting in a cellWidth of Infinity, which threw an error and rendered the plans step incorrectly (screenshot below).
This change only runs the cellWidth calculation while the visible count is at least 1, fixing the error on narrow viewports.
Example devices at narrow 320px widths include iPhone 5 / SE. Larger screenwidths, where the cell width was greater than the minimum cell width don't have the same issue.
* In `computeStyleVars` only recalculate the `cellWidth` with a `visibleCount` of at least 1.
* Set your device viewport to 320px / iphone 5 / SE resolution
* Complete signup …
=> Fix error updating cell widths on plans step in narrow viewports (e.g 320px)

client/blocks/signup-form/passwordless.jsx, client/lib/signup/step-actions.js, client/lib/wpcom-undocumented/lib/undocumented.js
* Allow passwordless signup to use sandboxed signups by saving the user step with the `signup_sandbox_username` if it exists in the response from the server
* Remove no-longer used `createUserAccountFromEmailAddress` functions (no longer needed due to: https://github.com/Automattic/wp-calypso/pull/37502
* Set sandbox to use sandboxed signups with an existing account
* Go to `/start` and select the `passwordless` variant of the `passwordlessSignup` A/B test
* Complete signup and create a site
* The site should be created (and not stuck on the `Awesome...` loading screen)
* The site should be added to your existing user account
---
* Ensure that you are not sandboxed
* Go to `/start` and select the `passwordless` variant of the `passwordlessSignup` A/B test
* Complete signup and create a …
=> Allow passwordless signup to work for sandboxed signups

client/lib/url/support.js
I need to add this specific link because I need to use it to fix this GitHub issue: https://github.com/Automattic/wp-calypso/issues/37811 
This is the Support guide link: MAP_SUBDOMAIN_CHANGE_NAME_SERVERS: https://en.support.wordpress.com/domains/map-existing-domain/#change-your-domains-name-servers which I have added.
=> Update support.js to add Domain Mapping support guide link to a specific section.

client/landing/gutenboarding/components/domain-picker/button.tsx, client/landing/gutenboarding/components/domain-picker/list.tsx, client/landing/gutenboarding/components/domain-picker/style.scss, client/landing/gutenboarding/components/header/index.tsx, client/landing/gutenboarding/constants.ts, client/landing/gutenboarding/stores/domain-suggestions/selectors.ts, client/landing/gutenboarding/stores/domain-suggestions/types.ts
- Reorganize the domain picker internals, the selection happens closer to where it's required.
- Isolate the DomainPicker from onboarding store.
- The contents of the DomainPicker button is now passed as `children`.
- Only show the domain picker if we have a domain already selected or a site title.
- `/gutenboarding` domains picker works well
- Domains picker appears when appropriate (have site title) and responds to changes to site title appropriately
- Domains picker searches correctly when a term is entered.
=> Gutenboarding: Separate DomainPicker and onboarding concerns

client/components/domains/free-domain-explainer/index.jsx, client/signup/steps/domains/index.jsx
* For the domain step test introduced by #37546, add a Tracks event for the cta on the free-domain textbox.
* Go to /start
* Type `localStorage.setItem('debug', 'calypso:analytics:tracks');` in your browser console and refresh page.
* Assign yourself to the variant group in the `domainStepCopyUpdates` A/B test.
* Go through the signup flow. In the domain step, click the "Review our plans to get started >>" link and verify that the Tracks event is fired.
* Verify that you can then complete the signup flow and create a new site.
=> Add a tracks event for the skip button in domain step test

client/landing/gutenboarding/components/domain-picker/button.tsx, client/landing/gutenboarding/components/domain-picker/list.tsx, client/landing/gutenboarding/components/header/index.tsx, client/landing/gutenboarding/stores/onboard/actions.ts, client/landing/gutenboarding/stores/onboard/reducer.ts
- Add `onDomainSelect` to `DomainPickerButton`
- Modify `domain` onboarding store state to store a DomainSuggestion
- Store selected domain when clicked.
- Display selected `domain` in header.
- `/gutenboarding`
- Search for a domain and click on in the list. It should be visible in the header when selected.
=> Store selected domain suggestion

client/blocks/product-selector/index.jsx
* Blocks: Fix missing prices in ProductCard when on a free plan without a Backup product.
Before:
After:
* Go to http://calypso.localhost:3000/plans/:site where `:site` is a Jetpack site with a Free plan and no backup product.
* Verify you can see the right prices on the top right side of the card.
* Buy a product. 
* Verify you can see the "Purchased on {DATE}" in that same area of the card.
* Buy a plan and cancel the product. 
* Verify you can see the "Included in {PLAN NAME}" in that same area of the card.
=> Blocks: Fix missing prices in ProductCard

client/my-sites/plans-features-main/index.jsx
* Jetpack Connect: Update plan headings/subheadings to align with the fact that we offer Backups
Before:
After:
* Go to http://calypso.localhost:3000/jetpack/connect/store
* Verify you can see the new strings.
=> Jetpack Connect: Update plan subheading

client/signup/config/steps-pure.js
This PR builds on top of the domain-copy A/B test introduced as a feature flag in #37546. Check the What next? section in that PR on how to review this and other PRs as part of this A/B test.
* This is a bug fix for the ecommerce flow. The bug is that if in the variant group of the `domainStepCopyUpdates` test, then the following sequence:
selecting Online Store in site type step --> click "Review our plans to get started »" in domain step
gives an error that shouldHideFreePlan dependency is unspecified.
* In https://github.com/Automattic/wp-calypso/pull/37554, we introduced a new signup dependency for the domain step. The fix for this error is to define that dependency for the domain step that is used in the ecommerce-onboarding flow.
* This PR also excludes the domain only flow from the …
=> Domain step test: define dependency for the ecommerce flow

client/landing/gutenboarding/onboarding-block/question/style.scss
* Questions are really text inputs, use the text cursor
* Test questions as `/gutenboarding`
=> Gutenboarding: Use text cursor for madlibs

client/signup/config/flows-pure.js
* Check p1574424650365900-slack-CCS1W9QVA.
* Fixes failed redirect after Business plan purchase on the eCommerce flow
* The issue was that after Business plan purchase via the ecommerce-onboarding flow, the following error shows on console and the page is stuck on the checkout page:
* Begin at /start
* Select "Online Store" as site type
* Verify you can complete purchase of a Business plan and that you are taken to checklist.
=> Fix: Redirect after Business plan purchase fails on the ecommerce flow

client/signup/config/flows-pure.js
* This is a follow up to https://github.com/Automattic/wp-calypso/pull/37862. Read that PR for further details on the issue and the slack convo linked there.
* Go through launch flow
* Purchase a plan
* Verify that you are taken to checklist
=> Fix: Redirect after plan purchase fails in the launch flow

client/landing/gutenboarding/components/domain-picker/button.tsx
Close the domain picker when it loses focus.
Part of #37856
Todo:
* Enter site title
* Click the DomainPicker to open
* Click outside - it should close
* 🐛 Click the toggle button to open and close - it should close and stay closed
=> Gutenboarding: Close domain picker when unfocused

client/components/badge/index.jsx, client/components/badge/style.scss, client/components/badge/test/index.js, client/components/domains/domain-registration-suggestion/index.jsx, client/components/domains/featured-domain-suggestions/style.scss, client/lib/abtest/active-tests.js, client/signup/config/steps-pure.js, client/signup/steps/domains/index.jsx, config/development.json, config/wpcalypso.json
* Launch the domain step copy update test `domainStepCopyUpdates` to 50% users and remove feature flag( introduced in #37546)
* The copy updates will only be seen in the signup flow, and not in launch flow or in the "Add domain" page.
**Web**
**Mobile**
* If you are assigned to the `control` group of the `domainStepCopyUpdates` test, then verify the following:
- The domain step UI and copy remains the same as before
- Complete signup and check the launch flow steps - they should remain unchanged
* If you are assigned to the `variantShowUpdates` group, then verify the following:
- The UI and copy for the domain step should match the screenshots above
- Selecting the "Review plan options" cta should show the plan page with _free site option hidden_.
- …
=> Launch the domain step test

client/state/selectors/get-checkout-upgrade-intent.js, config/development.json, config/horizon.json, config/test.json, config/wpcalypso.json
#37641 added new strings & we don't want to show them untranslated, so it was gated behind a feature flag.
Since both strings are [now showing 16 translations](https://translate.wordpress.com/localci/status/automattic/wp-calypso/update/checkout-thank-you-cta), this change removes that gate & launches the feature!
* This reverts commit d2aa822949982d85b17d2adaf209908314219c9e.
* Remove flag `checkout-upgrade-intent`
* Remove consultation of the flag in the `getCheckoutUpgradeIntent` selector
Follow test plan in #37641
Fixes https://github.com/Automattic/zelda-private/issues/252
=> Checkout: Enable returning customers to pre-upgrade-intended activity

client/my-sites/migrate/section-migrate.js, client/my-sites/migrate/section-migrate.scss
Note: This change is behind a feature-flag and is part of an in-progress larger project. This PR is intentionally incomplete. For context, see pbkcP4-8-p2.
Updates the designs for the site-selection and site-confirmation screens of migration.
Note: the site-names / addresses have been partially-removed from the screenshots
* Check out this pull request and run Calypso locally, or view it on calypso.live with the flag `tools/migrate.`
* Viewing calypso.localhost:3000/migrate/, you should see a `SiteSelector` component allowing you to choose a site to migrate a Jetpack site into.
* When you select a site, you should see another `SiteSelector` component, listing all the Jetpack sites your account has access to.
* Selecting one of those sites should take you to a confirmation screen.
=> Migration: Update the design for the site-selection and confirmation screens

packages/composite-checkout-wpcom/src/components/checkout.jsx, packages/composite-checkout/README.md, packages/composite-checkout/demo/index.js, packages/composite-checkout/src/components/button.js, packages/composite-checkout/src/components/checkout-next-step-button.js, packages/composite-checkout/src/components/checkout-order-summary.js, packages/composite-checkout/src/components/checkout-payment-methods.js, packages/composite-checkout/src/components/checkout-provider.js, packages/composite-checkout/src/components/checkout-review-order.js, packages/composite-checkout/src/components/checkout-step.js, packages/composite-checkout/src/components/checkout-submit-button.js, packages/composite-checkout/src/components/checkout.js, packages/composite-checkout/src/components/default-steps.js, packages/composite-checkout/src/lib/active-step.js, packages/composite-checkout/src/lib/payment-methods/credit-card-fields.js, packages/composite-checkout/src/lib/payment-methods/credit-card.js, packages/composite-checkout/src/lib/payment-methods/paypal.js, packages/composite-checkout/src/lib/payment-methods/stripe-credit-card-fields.js, packages/composite-checkout/src/lib/registry.js, packages/composite-checkout/src/lib/validation.js, packages/composite-checkout/src/public-api.js, packages/composite-checkout/src/wpcom/index.js, packages/composite-checkout/src/wpcom/wp-checkout-order-review.js, packages/composite-checkout/src/wpcom/wp-checkout-order-summary.js, packages/composite-checkout/src/wpcom/wp-contact-form.js, packages/composite-checkout/test/components/checkout.js
A great deal of the `Checkout` form is now provided by customization slots, including the first step (`OrderSummary`), the contact form (`ContactSlot`), and the last step (`ReviewContent`). This is appropriate, but it does highlight an evolving need: the host page wants to control the contents of the form more directly. Using slots means that we have to expect every situation that the host page might want to do and add a slot for it. There is nothing wrong with this approach but it restricts what can be done without changing the checkout component itself.
This PR modifies the `Checkout` component so that instead of taking a series of components that it injects into slots in the steps, it takes an array of _steps_ to display. 
Each _step_ is an object with a particular schema that includes …
=> composite-checkout: Inject steps as arguments

client/my-sites/domains/domain-management/edit/card/header/index.jsx, client/my-sites/domains/domain-management/edit/transfer.jsx
* Other, similar notices (including a compact one on the same page) use the `is-warning` Notice component style.
* Remove the smaller "Transfer in progress" flag since we've combined it into the main notice at the top of the screen.
**Before**
**After**
* Navigate to Manage -> Domains and transfer a domain to WordPress.com. (I don't know of a better way to test this, unfortunately.)
* While the transfer is in progress, click on the domain name you've transferred.
* The notice at the top of the screen should be yellow instead of pink, and you should no longer see the "Transfer in progress" flag next to the domain name.
Fixes #36479
=> Domains: Remove smaller Notice component on single domain screen

packages/composite-checkout/src/components/checkout-step.js
This PR fixes a bug in ie11 where the stepper numbers and checkmarks were misbehaving. The media queries ensure the code only runs on IE.
**Before**
**After**
* Get checkout running locally with the following instructions:
* Complete steps and ensure the numbers and checkmarks are showing at the appropriate times — if you can do this on IE11 that's a bonus too :)
=> Composit checkout: fix ie11 stepper issue

client/signup/steps/domains/index.jsx
* In the `domainStepCopyUpdates` test, when in the variant group, the following bug exists:
- Select a custom domain (you will then be taken to the plans page)
- Hit the back navigation for the plan page and go back to the domain page
- Now click the skip option i.e "Review our plans to get started"
- Now select a paid plan and go to checkout page
- You will notice the previously selected domain is still in cart.
* The bug is caused because the search suggestions are not cleared when the skip button is clicked. This PR fixes the issue.
* Repeat the steps described above. Verify that the custom domain is not in cart In the checkout page.
* Run through the signup flow in both control group and variant group and verify that the signup completes without any issues.
=> Domain step test: Remove domain suggestions from store on skip

packages/composite-checkout/src/components/checkout.js
This PR adds the disabled appearance to disabled buttons.
**Before**
**After**
* Get checkout running locally by following these instructions: https://github.com/Automattic/wp-calypso/pull/37013
* Press continue on the first step, the next continue button should be disabled.
=> Composite checkout: Add disabled button state

client/my-sites/checkout/checkout/composite-checkout-container.js, packages/composite-checkout-wpcom/src/components/checkout.jsx, packages/composite-checkout/README.md, packages/composite-checkout/src/components/checkout-payment-methods.js
Currently there's only the Paypal payment method listed in the version of composite-checkout used in Calypso. This adds the Stripe and Apple Pay payment methods as well.
- Run calypso with the `composite-checkout-wpcom` flag and verify that the form works as expected and you see the Stripe payment method. You won't see the Apple Pay one unless you are using Safari.
=> composite-checkout: Add stripe/apple-pay to calypso version

apps/full-site-editing/full-site-editing-plugin/full-site-editing/plugins/close-button-override/index.js, apps/wpcom-block-editor/src/calypso/iframe-bridge-server.js
I accidentally tried to use the FSE global object when it didn't exist in #37749. This fixes that.
* Use calypsoify global object instead of FSE object for back label override
* Use default calypsoify globals if they exist instead of the FSE global.
1. Sync the iFrame bridge server to your sandbox and sandbox `widgets.wp.com` as well as your test site.
2. Verify that for a non-FSE site, you see no 'fullSiteEditing is undefined errors' in the console when editing a post/page in gutenberg.
3. For an FSE site, sync these FSE changes to your sandbox and make sure the back button label still matches the page you come from.
=> Fix small back button errors

client/post-editor/controller.js, client/state/selectors/get-last-non-editor-route.js
* If we are trying to access a route like `page`, but need to redirect to `block-editor`, use `page` to handle the redirect so we don't loose the entire Calypso context in the process.
* Add `page` and `posts` as routes to match for the last non-editor route.
0. Run calypso.localhost with this branch.
1. On a site which has customer home, make sure you have completed the entire checklist.
2. Click "Add a page" from customer home.
3. It should take you to the block editor. After choosing a page layout, click the back button. It should take you to customer home. **Note: the label will be incorrect, but that will be fixed at the next FSE plugin release**
4. Test the create page flow again, this time clicking the back button from the SPT selector. Make sure it still goes to home before …
=> Fix back button from creating new pages/posts

client/signup/config/flows-pure.js
Full site editing allows the user to change their site title directly in the editor, making the Signup step irrelevant. This removes the step from the FSE testing flow.
Fixes #37893.
- as a new user, visit `/start/test-fse/`
- Signup steps should be: user, domains, plans
- verify that after signup up, you can edit your site title from the editor
=> Signup: remove site title step from FSE testing flow

apps/full-site-editing/full-site-editing-plugin/full-site-editing/plugins/close-button-override/index.js
We tried to reference the global declaration even though it was undefined.
To fix, we reference it directly from the window object, which declares the variable and sets its value to undefined. Previously, the entire variable was undefined, causing the runtime error.
Props to @Addison-Stavlo for finding this!
Test that the "Back" button shows up in your local install when editing an FSE page. This bug does not happen with gutenframe since the global object exists there.
=> Fix an error where calypsoifyGutenberg global object was undefined

client/blocks/signup-form/index.jsx, client/lib/signup/flow-controller.ts
This PR is split out from #37565 
Update the `test-fse` signup flow to use the passwordless signup form instead of the default form for the `user` step.
* Updates the `test-fse` flow to use the passwordless signup form by:
- Checking for the `test-fse` flow name in the SignupForm component
* Removes A/B test and flow name checks from the `isPasswordlessSignupForm` step property check in the flow controller. This ensures that if a passwordless signup form has been submitted, the `apiFunction` call will definitely be skipped in the flow controller's `_processStep` method — this way we can safely use the passwordless signup outside of the `onboarding` flow and A/B tests where we choose to, without accidentally breaking the flow controller.
Before each of the following steps, ensure you are …
=> Use passwordless signup in test-fse flow

client/my-sites/plans/current-plan/style.scss
* Adjust spacing of plan features title
<table>
<tr>
<td>Before:
<br><br>
</td>
<td>After:
<br><br>
</td>
</tr>
</table>
* Go to `/plans/my-plan/`
* The headlines `Personal plan features`, `Premium plan features`, `Business plan features` and `eCommerce plan features` use the same space above and below the headline, see attached screenshots above.
Fixes #37657
=> Plans: Adjust plan features title

client/state/selectors/is-eligible-for-free-to-paid-upsell.js, client/state/selectors/test/is-eligible-for-free-to-paid-upsell.js
This PR adds Jetpack sites list of sites that are not eligable for free to Paid Upsells. 
* On a Jetpack site do you see the Free Domain upsell?
* Do you still see the upsell on the regular free plan?
=> Remove Jetpack sites from the Free to Paid Upsells

client/components/data/query-gsuite-users/index.jsx, client/state/selectors/get-gsuite-users.js, client/state/selectors/has-loaded-gsuite-users.js, client/state/selectors/is-requesting-gsuite-users.js
This pull request seeks to fix a race condition with the `Email` page:
It indeed seems that navigating between the `Email` page and the `Domain Settings` page sometimes results in displaying what we call an empty page:
This pull requests fixes an invalid property used, and refine some selectors.
1. Run `git checkout fix/gsuite-empty-page` and start your server, or open a [live branch](https://calypso.live/?branch=fix/gsuite-empty-page)
2. Log in to an account that has a site with a domain but without G Suite
3. Open the [`Domains` page](http://calypso.localhost:3000/domains)
4. Click the domain to access the corresponding `Domain Settings` page
5. Click the `Email` option to access the `Email` page for that domain
6. Assert that you are presented with the option to purchase G Suite
7. …
=> G Suite: Fix empty page displayed when navigating back to Email page

client/components/gsuite/gsuite-price/index.jsx, client/components/gsuite/gsuite-price/test/__snapshots__/index.js.snap, client/components/gsuite/gsuite-price/test/index.js, client/components/upgrades/gsuite/gsuite-upsell-card/index.jsx, client/components/upgrades/gsuite/gsuite-upsell-card/product-details.jsx, client/components/upgrades/gsuite/index.jsx, client/my-sites/checkout/gsuite-nudge/index.jsx, client/my-sites/email/gsuite-purchase-cta/index.jsx, client/my-sites/email/gsuite-purchase-cta/test/__snapshots__/index.js.snap, client/my-sites/email/gsuite-purchase-cta/test/index.js, client/state/products-list/selectors.js
This pull request is a preliminary step to adding discount support for G Suite. It removes the option to display yearly prices that was introduced to A/B test monthly versus yearly prices. Since we know that we want to display both now, there is no need to keep that code around.
This pull request also introduces a new selector to retrieve a store product by slug. Finally, it refactors G Suite components to simplify the data that is passed down the components tree, and updates the component in charge of displaying prices to accept a product instead of just a cost. In the future, this product will contain the necessary information to display the discount.
1. Run `git checkout add/gsuite-discount-support` and start your server, or open a [live …
=> G Suite: Update price component to support discount

apps/full-site-editing/full-site-editing-plugin/full-site-editing/editor/style.scss
* Update a block editor editor CSS class name that was changed in a recent Gutenberg update.
Note: this must be deployed **AFTER** Gutenberg 7.0.0 lands on WPCOM (see p7DVsv-7Ks-p2).
* This must be tested on a FSE site with an updated Gutenberg, or on Horizon.
* Open the page editor and make sure the FSE frame is visible.
* Add blocks with different widths (regular, wide, full), and check if they adapt to the frame width instead of the full editor width.
* Repeat the previous tests in the template part editor.
Fixes #37837
=> Full Site Editing: Fix editor frame after a Gutenberg update

client/components/promo-section/index.tsx, client/components/promo-section/promo-card/index.tsx, client/components/promo-section/promo-card/style.scss, client/my-sites/earn/home.tsx, client/my-sites/sidebar/index.jsx
See previous discussion in p8hgLy-2d2-p2  - per @davemart-in  design:
* Introduce "new" badge to this new feature in Earn sidebar button
* Introduce "new" badge inside the earn section
* Go to Earn section http://calypso.localhost:3000/earn/
* See fabulous "NEW" badges
=> Recurring Payments: "New" badge in Earn section

client/jetpack-connect/style.scss
There's a margin added to the normal Jetpack logo on mobile views. This PR removes it when used on the new WooCommerce Onboarding + Jetpack flow.
Before
After
This flow is reachable through WooCommerce Admin. 
* Install WooCommerce
* Install WooCommerce Admin from GitHub
* Enable `WP_DEBUG`
* Go to `WooCommerce > Settings > Help > Setup Wizard` and connect via the Jetpack flow
* Shrink your screen below 660 and notice the margin is gone
=> Fix mobile margin on the Jetpack + WooCommerce connection flow

client/signup/steps/plans/index.jsx
* removes the Sales Team Widget from the the Plans page in signup
* go through the signup flow
* (especially on the Plans page,) ensure that the Sales Team Widget script and style files are not requested in the Network tab
=> Plans: remove sales team widget from Plans page in signup

client/landing/gutenboarding/components/domain-picker/button.tsx, client/landing/gutenboarding/components/domain-picker/list.tsx, client/landing/gutenboarding/components/header/index.tsx, client/landing/gutenboarding/components/header/style.scss
Restructure the domain picker button and header to include more and increase the picker size.
Closes #37851
Use the domain picker (via mouse and keyboard) at `/gutenboarding`
=> Gutenboarding: Increase domain picker size

client/blocks/eligibility-warnings/index.jsx, client/my-sites/checkout/checkout/secure-payment-form.jsx, client/my-sites/plan-features/index.jsx
Since Business sites do not go Atomic until a specific action is performed (a plugin or theme is installed, for example), there's no need to gate the upgrade with a prompt or to set the site to public at upgrade time.  This change removes that behavior for Business plan upgrades, but keeps it for Online Store / eCommerce upgrades (because those are taken Atomic immediately).
We want to improve the UI for the post-upgrade pre-install plugin / theme screen, but that work is decoupled from this in #37868.
* Only show the Site Privacy Dialog for eCommerce plan Upgrades. No longer show it for Business Upgrades.
|Before|After|
|---|---|
|![unlaunched-biz-plan-upgrade-before](https://user-images.githubusercontent.com/1587282/69438947-f7bb2c00-0d13-11ea-827a-2c139b18c315.gif)|![unlaunched-biz-plan …
=> Plans: Improve flows for upgrading private sites to the Business plan

client/my-sites/hosting/sftp-card/index.js
* Switches the Reset Password feature to use a busy button prop instead of the loading spinner to indicate busy state
* Apply this PR to your local calyspo dev environment
* Go to hosting section for an eligible Atomic site
* Click the reset password button and check that the busy button indicator shows instead of the loading indicator
* Reload the page and check that the loading indicator still shows when sftp details loading
* Open an Atomic site with no sftp user and click the 'Enable' button, and make sure the loading indicator displays as the new user is loading
Before:
After:
The faint grey loading bars don't show in above gif unfortunately, but they are there :-)
Fixes #37580
=> Hosting: Replace loading spinner with busy button when resetting password

config/production.json
* Config: Enable Jetpack Backups in Production
* No testing needed. If you wish, smoke test Jetpack Backups on staging.
=> Config: Enable Jetpack Backups in Production

client/blocks/comments/form-textarea.jsx, client/lib/paste-to-link/index.jsx, config/development.json, config/stage.json, config/test.json, config/wpcalypso.json
In #25113 we added paste-to-link functionality to the comments component.
Paste-to-Link is a higher-order component (HOC) that adds special paste behaviour to the wrapped component.
If the clipboard contains a URL and some text is selected, pasting will wrap the selected text in an
<a> element with the href set to the URL in the clipboard.
This functionality was launched as far as staging for internal users but not released to production.
This PR removes the feature flag and launches it for everyone.
Open a Reader full post like:
http://calypso.localhost:3000/read/feeds/82926118/posts/1864180970
Copy a URL to your clipboard, type and highlight some text in the comments, and then paste.
Ensure that:
- @ user mentions still work
- copying a non-URL to your clipboard does not change the …
=> Paste to link functionality: remove feature flag and ship to production

apps/wpcom-block-editor/src/calypso/iframe-bridge-server.js, client/gutenberg/editor/calypsoify-iframe.tsx, client/gutenberg/editor/controller.js
1. Stop destroying the calypso navigation context when we navigate to/from the template part. This caused a bug where you would always be taken back to the "all pages" list, even if you started elsewhere, like customer home. This happened as long as you went into the template editor.
2. Improve performance. We are no longer loading all of calypso every time we transition between the page editor and template parts, just the stuff inside the iFrame.
3. A great accidental result here is that it should be more obvious what the code does, and simpler to work on in the future.
* Add a `key` prop to the Iframe so that it resets if we start editing a different post.
* Remove code which updates the hrefs of the header/footer links.
* Remove code which does a server-side navigation if navigating …
=> Keep Calypso alive while navigating to template parts

client/blocks/jetpack-backup-creds-banner/index.jsx, client/my-sites/activity/activity-log/index.jsx, client/my-sites/site-settings/main.jsx, client/my-sites/site-settings/section-general.jsx, client/my-sites/stats/site.jsx
* Create a new jurassic ninja site.
* Connect Jetpack and purchase one of the new backup-only products.
* Go to the Activity Log, Settings (general), and Stats pages for the new site on this branch.
**EXPECTED**:
* You should see the new wording on the banner.
* The banner should link to the security settings page showing a form to enter site credentials.
* After credential entry, the banner should disappear.
=> Update Jetpack Backup credentials nudge banner

packages/composite-checkout/demo/index.js
When the WPCOM contact form was extracted in #37838, the contact form was left empty. This change adds a basic country field so that the contact form in the demo page works again.
- Add a file called `packages/composite-checkout/demo/private.js` and inside it put the following: `export const stripeKey = 'TEST KEY HERE'`;
- Verify that the form works as expected, particularly the contact form. The "continue" button should be disabled until the country field is filled in.
=> composite-checkout: Fill in demo contact form

packages/composite-checkout-wpcom/src/components/wp-order-review-line-items.js, packages/composite-checkout/src/components/checkout-step.js
This PR makes some enhancements so that our checkout reads better for screen readers. Here are some of the tweaks:
* Stop rendering the step number if it's 0 so that it reads "You are all set to checkout" vs. "ZERO.. Your are all set to checkout"
* Updated the remove from cart button title so that it reads "Remove [product] from the cart"
* Updated the items in the review step so that they're a list. 
* Get checkout up and running with these instructions: https://github.com/Automattic/wp-calypso/pull/37013
* Setup voice commands: https://webaim.org/articles/voiceover
* Walk through the interface with the screen reader.
=> Composite checkout: screen reader enhancements

client/blocks/signup-form/index.jsx
* The signup form can sometimes show a blank screen if the email or username field has an unexpected character.
* This PR fixes the issue reported in https://github.com/Automattic/wp-calypso/issues/37908
Why we see a blank screen:
The sanitize function's onComplete callback expects to be sent all the form values, whereas it is being sent only the email and username field values. Thus the password field gets an `undefined` value, thus giving an error [when the length property is used on an undefined value](https://github.com/Automattic/wp-calypso/blob/master/client/blocks/signup-form/index.jsx#L355).
* Try the scenarios described in the bug report and verify that none of them lead to a blank screen or console error:
- email value with a capitalized letter
- username with a single space
- …
=> Fix blank screen on signup form 

client/blocks/inline-help/contextual-help.js
* Adds some contextual inline help links for the new hosting section
* Checkout this PR and open Hosting Configuration Section for an eligible Atomic site
* Click on the inline help button at bottom right
* Check that the help popup shows links for SFTP Credential and Database Access
Before:
After:
Fixes #37899
=> Hosting: Add contextual inline help

client/state/domains/dns/reducer.js
Fixes regression introduced in #37907 where `removeDuplicateWpcomRecords` wouldn't remove default WPCOM A records when adding a custom one. Because we didn't import `find` from Lodash in the module, the function used `window.find` that searches for a string inside the window's HTML 🤦‍♂ Not exactly what we wanted.
As a followup, let's disable the ESLint behavior that allows variable references that are `window` properties.
Add a custom A record for your domain. Verify that the default A record (_Handled by WordPress.com_) is removed. When removing the custom A record, the default WPCOM record should be added back.
=> Domains: fix removing default WPCOM records when adding custom A record

client/my-sites/plans/current-plan/my-plan-card/index.jsx
Under some conditions the loading of the My Plan Card looks off. This PR fixes it by making sure that we load the whole card before we show the icon.
Before:
After:
I tested this by forcing the isPlaceholder on the My Products section to always return true. 
This way I don't have to make meet the condition in a different way.
=> My Plan Card: Don't show the icon if we are still displaying the placeholder

client/my-sites/plans/current-plan/jetpack-checklist/header.js, client/my-sites/plans/current-plan/jetpack-checklist/style.scss
Update the design of the My plans page to include more padding as per design. 
Before:
After:
I force the notice to show up. By faking the error. 
* Visit my plans page for jetpack site. 
* Does everything still look as expected.
=> Jetpack Checklist: Add My checklist heading

client/my-sites/hosting/php-version-card/index.js
- Hide button if it's the version running on the site
- Don't refetch php version
- Make an Atomic site
- Go to Hosting Configuration
- Make sure button isn't seen until you switch version in the dropdown
- When you update, make sure the button is gone and no php version refetch happens
=> Atomic: PHP Switcher UI Update

client/components/data/query-site-purchases/index.jsx
Currently, in the `QuerySitePurchases` we'll check if the site purchases are being requested, but only when we switch the site. This means that we don't check when we mount, and this results in a new request on every mount. Currently, on the plans page, we have 3. This PR fixes the check so it happens in both cases.
* Components: Fix requesting state in QuerySitePurchases
* Open your network tab.
* Go to http://calypso.localhost:3000/plans/:site where `:site` is a Jetpack site.
* Verify you get 1 request to the site purchases, and not 3.
* Switch to another site.
* Verify you get 1 request to the site purchases for that site ID.
=> Components: Fix requesting state in QuerySitePurchases

apps/full-site-editing/full-site-editing-plugin/full-site-editing/blocks/navigation-menu/index.js, apps/full-site-editing/package-lock.json
cc @Copons 
Add right/left alignment to the nav block. This lets us put the block beside other blocks.
The theme styles are still rough, but as you can see the nav block shows inline with the social links block. I just had to "align" it right. Otherwise, it is impossible to align the nav block with that block in the editor.
=> Add right/left alignment to nav block

client/my-sites/stats/wordads/index.jsx
I think this is just a typo introduced in #37343, but the Formatted Header for ads stats is centred, which is an odd jump when clicking through the stats labels.
Visit `/stats/ads/day/site` on a WordAds site.
**Before:**
**After:**
cc @danhauk
=> Ads Stats: Fix Formatted Header Alignment

client/blocks/jetpack-backup-creds-banner/index.jsx
Fixup prop types of `JetpackBackupCredsBanner` introduced in #37730. `PropTypes.function` is not a valid prop type. The right one is `PropTypes.func`.
Fixes a React console warning about prop type being `undefined` rather than having one of the supported values.
=> JetpackBackupCredsBanner: fixup proptypes

apps/full-site-editing/full-site-editing-plugin/full-site-editing-plugin.php
This PR makes Global Styles available to all sites whose theme supports it (at the moment, all of Template-First Themes).
In https://github.com/Automattic/wp-calypso/pull/36288 we introduced Global Styles, a way to customize fonts from the block editor. Although it doesn't depend on FSE, it was gated as such (to people whose site was eligible for FSE) as a way to soft-launch and test the waters. Testing didn't surface any issues, so this can now be opened.
* Copy the modified file to your sandbox within the latest version of the FSE plugin.
* Sandboxed, load a site whose [theme supports global styles](https://wordpress.com/themes/filter/global-styles) - hint: any of the Template-First Themes.
* Open the block editor and verify that the Global Styles button is shown in the top-right.
* …
=> Open Global Styles to every site with theme support

packages/composite-checkout-wpcom/src/components/button.js, packages/composite-checkout/src/components/button.js, packages/composite-checkout/src/lib/payment-methods/apple-pay.js, packages/composite-checkout/src/lib/payment-methods/credit-card.js, packages/composite-checkout/src/lib/payment-methods/paypal.js, packages/composite-checkout/src/lib/payment-methods/stripe-credit-card-fields.js
When the checkout form is incomplete, the payment method's submit button component is passed the `disabled` attribute. However, that attribute was not being used by any of the payment methods. This change passes that attribute along to each payment method's submit button.
- Add a file called `packages/composite-checkout/demo/private.js` and inside it put the following: `export const stripeKey = 'TEST KEY HERE'`;
- Try clicking the submit button and be sure it is disabled (its UI may not look disabled, but this is a separate issue). Try it with each payment method.
=> composite-checkout: Disable submit button when form is incomplete

packages/composite-checkout-wpcom/src/components/wp-contact-form.js
This PR cleans up some ghost markup showing up in the billing summary. 
**Before**
**After**
* Get calypso running locally and make your way to checkout
* Append the checkout flag (`?flags=composite-checkout-wpcom`) to the end of your url and refresh
* Complete the billing step and ensure no extra markup is showing.
=> Composite checkout: Remove ghost markup

client/my-sites/marketing/connections/service.jsx, client/state/sharing/keyring/selectors.js, client/state/sharing/keyring/test/selectors.js
This PR adds the code necessary to make it possible to reconnect broken keyring connections. Calypso looks for the keyring_connection_ID key, which we don't have for keyring connections, so when a keyring connection breaks the reconnect button doesn't work.
This PR changes the way we look for broken connections to use the `ID` for non publicize connections.
To test:
- Go to http://calypso.localhost:3000/marketing/connections/%site%s
- Find a broken connection (you might need to change this on the server)
- Go through the reconnection flow
- Confirm that connection is restored
=> Fix broken reconnection flow

client/my-sites/plans/current-plan/purchases-listing.jsx
Before:
After:
Visit my plans page for a jetpack site that has the backup product.
=> My Plans: Rename Products => Solutions

client/state/domains/dns/reducer.js
The initial state of the reducer should be `{}` rather than the `initialState` value.
The state is keyed by domain name. It's the values that correspond to these keys that
should use the `initialState` constant.
=> Domains: fixup initial state of the DNS reducer

client/components/formatted-header/README.md, client/components/formatted-header/index.jsx, client/my-sites/plans-features-main/index.jsx
This PR fixes the formatted header on the plans page by adding the isSecondary attribute. Which lets us set the html of the component to be an H2 instead of an H1. 
This lets us use the H2 tag on pages that already have the H1 tag. 
No visual change should be present on that page.
Go to the plans page. Using the web inspector notice that the Plans and Solutions are now rendered using the H2 tag.
=> Add isSecondary attribute to Formatted Header

client/blocks/product-selector/index.jsx
This PR removes the link to the Jetpack Backup landing page on the Jetpack Connect page.
* Jetpack Connect: Hide Backup landing page links
Before:
After:
* Go to http://calypso.localhost:3000/jetpack/connect/store
* Verify you no longer see the link.
* Go to http://calypso.localhost:3000/plans/:site where `:site` is a Jetpack site on a free plan without any backup products purchased.
* Verify you can still see the link.
=> Jetpack Connect: Hide Backup landing page links

client/components/gsuite/gsuite-price/index.jsx, client/components/gsuite/gsuite-price/style.scss, client/components/gsuite/gsuite-price/test/__snapshots__/index.js.snap, client/lib/abtest/active-tests.js, client/lib/gsuite/index.js, client/lib/gsuite/test/index.js, client/my-sites/email/gsuite-purchase-cta/style.scss, client/my-sites/email/gsuite-purchase-cta/test/__snapshots__/index.js.snap
This pull request is a follow-up of https://github.com/Automattic/wp-calypso/pull/37776 which adds support for **discounts** provided via **sales coupon** to the G Suite Upsell and `Email` pages. It introduces this feature behind an A/B test that acts as a feature gate, thus allowing us to declare all the strings that need to be translated before deploying the change to all users. Ultimately, the display of the price will be driven by the sales coupon provided by the API, and which is only valid for a certain duration.
Old (control) | New (without discount) | New (with discount)
------ | ----- | -----
> Note you can select a variation of the `gsuitePrice` A/B test from the development environment badge (see p4TIVU-3pQ-p2 for more information). You will have to apply the server-side patch …
=> G Suite: Add discount support via sales coupons

client/lib/plans/plans-list.js, client/my-sites/plans/current-plan/purchases-listing.jsx
The Free plan tagline on My Plan page is always the same - no matter if the user already purchased one of the Jetpack Backup options. This can be confusing since the default tagline prompts the user to purchase a paid plan in order to get backups while the user might already have a separate Jetpack Backup product.
This PR resolves this issue. The Free plan tagline is now different depending if the user has one of the Jetpack Backup options or no additional product.
**Before**
**After - without Jetpack Backup**
**After - with Jetpack Backup Daily**
**After - with Jetpack Backup Real-Time**
* Make the Free plan tagline on My Plan page dependant on Backup product
* Go to http://calypso.localhost:3000/plans/my-plan and select a Jetpack site on the Free plan
* Confirm that the tagline is …
=> Make the Free plan tagline on My Plan page dependant on Backup product

packages/composite-checkout-wpcom/src/components/wp-contact-form.js
This PR updates the copy in the domain registration contact info section based on p99Zz8-Ql-p2.
We won't be able to test this until we merge https://github.com/Automattic/wp-calypso/pull/37881. For now, we'll just need to review the code.
=> Composite checkout: Update domain contact info messaging

packages/composite-checkout-wpcom/src/components/wp-checkout-order-summary.js
This PR stubs in the domain to the order summary.
* Get calypso up and running locally. 
* Add a product to your cart and checkout.
* Add `?flags=composite-checkout-wpcom` to your url to see the new checkout.
=> Composite checkout: Stub domain in order summary

apps/full-site-editing/full-site-editing-plugin/full-site-editing-plugin.php
* Use template inserter class by itself instead of with the FSE class. This way we avoid hooking into all of the WordPress actions if the theme is unsupported.
1. Sync to sandbox. Sandbox a FSE site URL and the API.
2. Watch the error log on the sandbox. Look out for `Uncaught Error: Class 'A8C\FSE\WP_Template' not found`.
3. Activate maywood from the themes page. Click edit homepage and then back out of the editor after it loads.
4. Activate a non-FSE theme from the themes page. Immediately click edit homepage. **This is where the error happened before.**
5. Also test that template parts are still inserted correctly at these times:
a) Site creation (via horizon.wordpress.com/start/test-fse).
b) Activating a new theme (Exford or Shawburn)
=> Fix undefined template class on unsupported theme activation

apps/full-site-editing/full-site-editing-plugin/full-site-editing/blocks/template/edit.js, apps/full-site-editing/full-site-editing-plugin/full-site-editing/blocks/template/style.scss
cc @apeatling to see if we want to include this change. We discussed it in the user testing today, and it's a simple change.
* Clicking anywhere on the template block will navigate to the header/footer editor.
* Remove the delay to show the button. My subjective opinion is that it looked laggy. I also remember a user not seeing the button because it didn't show up immediately and she moved the mouse outside of the block too quickly. Let me know what you think @Copons 
1. Test locally and on wpcom
2. Make sure that there is no delay for seeing the edit header button
3. Make sure you can click anywhere on the header and footer to go to the template editor
4. Make sure navigation around the template editor works clicking anywhere on the header/footer. (like the back button etc)
=> FSE Click anywhere on template block to navigate

client/gutenberg/editor/controller.js, client/signup/config/flows-pure.js, client/signup/config/flows.js, client/state/selectors/get-editor-close-config.js, client/state/selectors/test/get-editor-close-config.js
This redirects a user to their homepage editor after Signup is completed for the `/test-fse/` flow. It also updates the Gutenberg back button for that instance to return the user to the Customer Home.
**To Test:**
- visit `/start/test-fse/`
- create a new site
- verify that you're redirected to the editor for the site's homepage
- verify that the back button in the Editor is labeled "Home" and should takes the user back to the Customer Home
=> Signup: redirect user to editor after Signup

client/blocks/signup-form/index.jsx
p1574695487447600-slack-onboarding-exp
Because we aren't sure yet that we want to roll out passwordless signup, this PR hides the passwordless signup behind the A/B in the `test-fse` flow, to match the behaviour on the main onboarding flow.
* Switch passwordless signup for the `test-fse` flow to only be enabled when the user is in the `passwordlessSignup` A/B test variant
* Go to `/start` and the user step should display the _passwordful_ (normal) account creation form
* Switch to the `passwordless` variant of the `passwordlessSignup` A/B test
* The form should display as the passwordless form
* Switch back to the `default` (control) variant of the `passwordlessSignup` A/B test
* Go to `/start/test-fse` and you should see the normal _passwordful_ account creation form
* Switch back to the …
=> Switch passwordless signup on test-fse to only display if the user is in the A/B test

client/signup/config/flows-pure.js, client/signup/steps/theme-selection/index.jsx
* Adds theme picking step to `test-fse` flow
* Update theme step header text to match figma
* Skipping theme selection will start the user with Maywood
Using Maywood as the default theme so that they will have a theme that supports FSE.
Part of #37870 task.
See Milestone 2 figma here paObgF-Jt-p2
* Checkout branch (`test-fse` flow only available in dev and horizon)
* Signed out, create site starting from `/start/test-fse`
* Choose one of the template first themes, check header text matches figma
* Complete signup, site should be headstarted with theme content
* Stay logged in and start again at `/start/test-fse`
* Skip theme selection (skip button is at bottom of step), header text makes sense p1574893200104900-slack-CCS1W9QVA
* Complete signup, site should have a fse compatible theme
=> Add template-first-themes step to test-fse flow

client/blocks/reader-post-card/style.scss
I've recently switched to Firefox as my primary browser and have noticed that lowercase descenders get clipped (typically 'g') in post excerpts:
A small tweak to line height so that descenders aren't clipped.
Visit your feed at http://calypso.localhost:3000/ in Firefox. Check that no letters are clipped on the last line of the post excerpt.
Visit your feed in other browsers. Check the line height still looks sensible.
@Aurorum would you mind giving this one a look? 👀
=> Reader: fix clipped descenders in post excerpt on Firefox

client/signup/config/flows-pure.js, client/signup/steps/site-type/index.jsx
This PR resolves an issue in https://github.com/Automattic/wp-calypso/pull/36825 where the `design-first` flow would switch to the `ecommerce-onboarding` flow at the site type step, if a user selects the `Online store` site type. This would then result in the user creating a site with the theme set by the `site-type` step, instead of the one they selected in the `design-first` flow, which is _not_ overridden by the `site-type-with-theme` step.
I went with the approach of adding an additional ecommerce flow, because this seemed clearer and more explicit than writing some awkward code to treat `site-type` and `site-type-with-theme` as though they're the same step — it also felt a bit safer not to mess with the Signup framework behaviour for this one case of a particular flow that had an …
=> Add ecommerce-design-first flow and condition to switch to it in SiteType

apps/full-site-editing/full-site-editing-plugin/starter-page-templates/page-template-modal/components/sidebar-modal-opener.js, apps/full-site-editing/full-site-editing-plugin/starter-page-templates/page-template-modal/index.js
Both the `PageTemplateModal` and `SidebarModalOpener` components were found to directly rely on globals variables, rather than using the existing pattern of passing those globals as props into those components, to preserve some level of encapsulation.
This PR shouldn't change any functionality.
Required for p7rd6c-295-p2. Partial fix for #37998.
Preparatory step for moving [this](https://github.com/Automattic/wp-calypso/blob/02d3db2380ff3532fb636823ec683f29ce13eff8/apps/full-site-editing/full-site-editing-plugin/starter-page-templates/page-template-modal/index.js#L30-L40) to a separate file.
Verify that the the Starter Page Templates Modal works as before.
=> SPT: No globals in components

apps/full-site-editing/full-site-editing-plugin/starter-page-templates/index.js, apps/full-site-editing/full-site-editing-plugin/starter-page-templates/page-template-modal/index.js
Move use of the `window.starterPageTemplatesConfig` global from `apps/full-site-editing/full-site-editing-plugin/starter-page-templates/page-template-modal/index.js` to `apps/full-site-editing/full-site-editing-plugin/starter-page-templates/index.js`. Also move Gutenberg plugin registration to that file, as it relies on that global.
I think that the latter file is the only entrypoint for the SPT modal, so this separation of concerns should make sense. AFAICS, it also breaks a circular dependency between `apps/full-site-editing/full-site-editing-plugin/starter-page-templates/page-template-modal/index.js` and `apps/full-site-editing/full-site-editing-plugin/starter-page-templates/page-template-modal/components/sidebar-modal-opener.js`.
Required for p7rd6c-295-p2.
Verify that Starter Page …
=> SPT: Isolate `window` global

packages/composite-checkout/src/components/checkout.js
This PR fixes the pay button to the bottom of the screen when all the steps are completed. I debated whether to fix it there the entire time and then just change the state of the button when the states are all completed but decided to only fix it at the end so people have the entire screen to work on the previous steps. 
* Get calypso up and running locally.
* Add a product to your cart and checkout.
* Add ?flags=composite-checkout-wpcom to your url to see the new checkout.
* Complete all the steps until the pay button becomes active
* Resize your screen to see the pay button fix to the bottom of the screen on smaller devices and not do anything on larger screens.
* Try resize the browser vertically to make sure you can scroll to the bottom of the screen.
=> Composite checkout: Fix buy button to the screen on mobile

client/lib/products-values/constants.js
Currently the post-purchase description of the Jetpack Daily Backup contains an upsell message:
Since there's no way in the current implementation to upgrade to Real-Time option, it doesn't make sense to have such a message in the `ProductCard`.
This PR changes the description as follows:
* Update the post-purchase Jetpack Daily Backup description in `ProductCard`
* Go to http://calypso.localhost:3000/plans/ and select a Jetpack site with Daily Backup
* Confirm the description in the `ProductCard` is now updated
Fixes n/a
=> Update the post-purchase Jetpack Daily Backup description in ProductCard

client/blocks/eligibility-warnings/index.jsx, client/my-sites/hosting/controller.js, client/my-sites/hosting/hosting-activate.js, client/my-sites/hosting/index.js, client/my-sites/hosting/main.js, client/my-sites/hosting/php-version-card/index.js, client/my-sites/hosting/style.scss, client/state/selectors/can-site-view-atomic-hosting.js, client/state/themes/actions.js, client/state/themes/test/actions.js, config/desktop.json, config/development.json, config/horizon.json, config/production.json, config/stage.json, config/test.json, config/wpcalypso.json
- Add the Hosting Configuration activation flow for Atomic.
- Refactor PHP Version card to display properly only when site is actually Atomic.
- Create a site
- buy a business plan
- Got to hosting config
- Activate
- Proceed
- Wait, make sure all looks good
=> Atomic: Hosting Configuration Activate

client/blocks/product-selector/index.jsx, client/components/product-card/README.md, client/components/product-card/index.jsx
**Before**
**After**
* Change the product card action button label to "Manage Product"
* Go to http://calypso.localhost:3000/plans/
* Select a Jetpack site that has one of the Jetpack Backup products
* Confirm that the action button inside the product card is now labelled: "Manage Product"
Fixes n/a
=> Change the product card action button label to "Manage Product"

client/state/selectors/get-last-non-editor-route.js, client/state/selectors/test/get-last-non-editor-route.js
This fixes a bug exposed in #36382 where opening a page or post from `/pages` or `/posts` in Calypso sets the back button in the editor to redirect to `/home`, but in these cases the button should go back to their respective parts of Calypso (Pages or Posts).
* Update the regex in `getLastNonEditorRoute` so that it'll match against `/page` or `/post` but _not_ against `/pages` or `/posts`.
* Add test coverage for the `getLastNonEditorRoute` selector.
* Open up an existing site in Calypso that has posts (or create one)
* Go to the Site > Posts page in Calypso `/posts` and open one of the posts in the editor
* The back button at the top left of the editor window should redirect you back to the Posts page
* Go to the Site > Pages page in Calypso `/pages` and open one of the pages in the …
=> Fix regex in getLastNonEditorRoute so that /pages and /posts routes are not excluded

client/blocks/product-selector/index.jsx, client/components/product-card/style.scss
* On the "My Plan" page, we display full dates. On the "Plans" page, we should use a similar date format.
Related discussion:
p8oabR-qW-p2#comment-3635
Matching Jetpack PR:
https://github.com/Automattic/jetpack/pull/14150
**Note**: this should only be a temporary solution. Ideally, we'd want to modify this further, to change the date we display depending on the date and your renewal settings. I think we could also aim to use the date format used by WordPress on the whole site.
* Go to Jetpack > Dashboard > Plans and follow the CTA to buy a Jetpack Backup.
* After your purchase, head to "Plans". 
* The date in the Jetpack Backup card should match the date format used in "My Plan".
=> Admin Page: update date format of Backup card to be consistent

client/my-sites/hosting/sftp-card/index.js
This PR updates the "What is FTP?" content in the hosting section's SFTP card.
See: p1575057401495900-slack-serenity
* On Horizon, load an Atomic site with no existing SFTP credentials, and go to the Hosting section.
* Verify the new text in the SFTP card, under the "What is SFTP?" accordion.
=> Atomic Hosting: Add definition of SFTP to the "what is SFTP?" text.

client/reader/conversations/stream.scss
Similar to https://github.com/Automattic/wp-calypso/pull/38014. I've recently switched to Firefox as my primary browser and have noticed that lowercase descenders get slightly clipped (typically 'g') in conversation post titles:
Visit your conversations at http://calypso.localhost:3000/read/conversations in Firefox. Check that no letters are clipped in the post title.
Visit your feed in other browsers. Check the line height still looks sensible.
=> Reader Conversations: fix clipping of descenders in Firefox on title

client/my-sites/plans-features-main/index.jsx
* Jetpack Backup does not support Multisite yet, so let's not show the product card on sites that are part of a Multisite network.
Internal reference: p8oabR-qW-p2#comment-3724
Matching Jetpack PR:
https://github.com/Automattic/jetpack/pull/14153
* Start with 2 Jetpack sites, not yet connected to WordPress.com. One of them must be a single site, the other must be part of a Multisite network. Here are 2 handy links to get you started with both (those sites will also be running the matching Jetpack PR's branch, so you can test both PRs at once):
- [Single site](https://href.li/?https://jurassic.ninja/create?jetpack-beta&branch=update/hide-jetpack-backup-multisite&wp-debug-log)
- [Multisite](https://href.li/?https://jurassic.ninja/create?jetpack-beta&branch=update/hide-jetpack-backup-multisit …
=> Jetpack Backup: do not show card when site is a multisite site.

client/my-sites/hosting/sftp-card/index.js
Shows the "Create SFTP credentials" state when the hosting features have not been activated yet (aka site is not Atomic). This will match what users see once the activation has been completed.
|---|---|
| ![image](https://user-images.githubusercontent.com/1233880/69864001-62cdab00-129e-11ea-999c-8eded3c4ce96.png) | ![image](https://user-images.githubusercontent.com/1233880/69864016-69f4b900-129e-11ea-8d81-72fa9ebdd889.png) |
* Create a site.
* Buy a business plan.
* Go to Hosting Configuration.
* Make sure the "Create SFTP credentials" button is displayed, and no credentials are displayed.
* Activate the hosting features and wait.
* Click on the SFTP credentials.
* Make sure the SFTP credentials are created as expected.
=> Hosting: Prepare SFTP/phpMyAdmin cards for activation flow

client/components/section-nav/tabs.jsx
While the width of the group was only being retrieved at appropriate times (after a layout flush), the individual tab refs were running immediately, regardless of timing.
It appears @jsnajdr had fixed this in the past, but subsequent work brought the issue back.
* Delay retrieval of individual tab widths until an appropriate time.
To test functionality:
* Ensure the tabs at the top of a nav section (e.g. Stats) continue to work correctly.
To test performance:
* Ensure you have React DevTools installed
* Open Chrome DevTools and open the Performance tab
* Open "My Sites"
* Switch between stats and another section (e.g. Plans) a few times, ending with the other section
* Start recording
* Hover over Stats in the side bar and wait a few seconds
* Click it and don't move your mouse for …
=> Avoid layout recalcs on mount in section-nav tabs.

packages/composite-checkout/README.md, packages/composite-checkout/src/components/checkout.js, packages/composite-checkout/src/components/default-steps.js, packages/composite-checkout/src/lib/payment-methods/stripe-credit-card-fields.js
This modifies the payment methods (default) step so that its `isCompleteCallback` calls the payment method's `isCompleteCallback` (optional, added in this PR) to determine if the step is complete.
For the stripe payment method, we examine the cardholderName field and the three stripe elements fields, to make sure each is valid and not empty before marking the step as complete. To do this, we have to move the errors state to the 'stripe' store and add an additional state in the store for each field's completeness.
Finally, in order to make sure the `isCompleteCallback` is called each time the 'stripe' store (only used in the stripe payment method) is updated, we have to subscribe the `Checkout` component to _all_ store updates in the checkout registry. I don't think that will have too much …
=> composite-checkout: Only enable continue if stripe fields are complete

client/components/checklist/style.scss, client/components/checklist/task.js, client/my-sites/checklist/wpcom-checklist/component.jsx
* User testing has shown the ability to "complete" a task using the checklist circles doesn't work as expected and leads to confusion, since it doesn't actually complete the task. It's easy to click these accidentally, dismissing the checklist task without the ability to get it back. 
* This PR removes the focusable component from the checkboxes and styles them with a slightly lighter border, making them a visual decoration rather than a button.
* This does not appear to affect the Jetpack checklist on the Plans -> My Plan page, but it should be tested again to make sure.
**Before**
**After**
* Switch to this PR, start a new site from `/start/test-fse`
* Finish signup and land on Customer Home
* Note the checklist; you should not be able to click on the checklist circles to dismiss tasks. …
=> Checklist: Remove checklist dismiss actions

client/my-sites/checkout/checkout/composite-checkout-container.js, packages/composite-checkout-wpcom/src/components/wp-checkout-wrapper.js, packages/composite-checkout-wpcom/test/wp-checkout-wrapper.js
This modifies the `onSuccess`/`onFailure` handlers to be injected with Calypso's `notices.success`/`notices.error` functions.
Do not sandbox the store. Start calypso and load checkout with the `composite-checkout-wpcom` flag. You should see an error that the Stripe fields require HTTPS, but that error should appear using Calypso's native notification system, rather than a browser alert.
=> composite-checkout: Set onSuccess/onFailure to use calypso notices

client/my-sites/themes/recommended-themes.jsx, client/my-sites/themes/theme-showcase.jsx
* alternative solution to PR #38086
* Run this branch with `npm start`
* Navigate to `calypso.localhost:3000/themes` while logged in.
* Open the "More Themes" Section and apply a search critera.
* Verify Recommended Themes section disappears.
* Reload the browser window.
* Verify that the All Themes search section is open and that the page auto scrolls to this area.
* Clear the search criteria rom the input.
* Reload the browser and confirm that Recommended Themes and the "More Themes" button are present.
* Test this same process with a site selected through the my-sites/themes section.
Fixes #38061
=> Hide recommended themes when query present.

client/signup/config/flows-pure.js
* Update flow destination for `test-fse` to point to the customer home
* Note that the `getEditorDestination` function is retained in `flows.js` because we will be using it again in Milestone 3 of the 0-FSE work.
* Go to `/start/test-fse` and complete signup with a free plan, double check that you are redirected to the Customer Home after signup, and that the header says "Your site has been created!"
* Go to `/start/test-fse` and complete signup with a paid plan (e.g. Personal plan), and check that you are redirected to the Customer Home after completing the checkout, and that the header says "Thank you for your purchase!"
Fixes #38057
=> Update flow destination for test-fse to redirect to customer home

client/reader/sidebar/index.jsx, client/reader/sidebar/reader-sidebar-nudges/index.jsx, client/reader/sidebar/reader-sidebar-nudges/style.scss
* Add an upsell nudge to the Reader sidebar
See pbm1bU-4i-p2 for more details.
* _For reviewers who don't live in the US:_
Since the nudge is available only for the US, you may need to provide a country code as below:
```
// in browser console
window.userCountryCode = 'US';
```
* _For US residents:_
Please make sure this PR works for you without mocking country code.
1. Create a new user with a free plan site. Your language should be set to English.
1. Visit the Reader page.
1. **The upsell nudge should show up in the sidebar because you're the person who has only one site.**
1. Click on "Upgrade" link in the nudge. You should be taken to the plans page of your site.
1. Create a new site.
1. Go to the Reader page again.
1. **The upsell nudge should not appear this time.**
1. Delete a site …
=> Add an upsell nudge to Reader sidebar

client/landing/gutenboarding/components/header/index.tsx, client/landing/gutenboarding/onboarding-block/edit.tsx, client/landing/gutenboarding/onboarding-block/vertical-select/index.tsx, client/landing/gutenboarding/stores/onboard/reducer.ts, client/landing/gutenboarding/stores/onboard/types.ts
I'm starting to think we're doing a bit too much ceremony for our `EMPTY_FORM_VALUE` handling.
Consider the shape of any form value object:
This means that our type information is no longer just an added layer that's removed when transpiling to JS, but we're actually carrying it over there, and I think it could lead to some confusion.
Furthermore, it seems to possibly cause more problems than it solves. Consider this type error:
```
client/landing/gutenboarding/stores/onboard/types.ts:25:57 - error TS2345: Argument of type 'FormValue<T>' is not assignable to parameter of type 'object | ArrayLike<any>'.
Type 'T' is not assignable to type 'object | ArrayLike<any>'.
Type 'T' is not assignable to type 'ArrayLike<any>'.
25  return value !== EMPTY_FORM_VALUE && ! isShallowEqual( value, …
```
=> Gutenboarding: Drop EMPTY_FORM_VALUE and friends

packages/composite-checkout/src/components/checkout-step.js, packages/composite-checkout/src/components/checkout.js, packages/composite-checkout/src/components/shared-icons.js
While running an accessibility report, it came to my attention that we had a duplicate id being used on the checkmark. This PR updates the check icon component to prevent the duplication.
* Get checkout running with the `composite-checkout-wpcom` flag. 
* Go through the steps and check the id for each checkmark to make sure they're unique.
=> Composite checkout: update duplicate ID

packages/composite-checkout/src/components/field.js, packages/composite-checkout/src/lib/payment-methods/stripe-credit-card-fields.js
This PR updates the styles of our composite checkout fields to prevent leakage from calypso.
**Before**
**After**
Visit checkout with the store sandboxed. Add the `composite-checkout-wpcom` flag. Keep an eye on the fields as they load. You shouldn't see any flickering.
=> Composite checkout: fix style leaks on stripe fields

client/my-sites/customer-home/main.jsx
* Only show upgrade nudges (like GSuite) when a site is greater than two days old.
* This only affects Customer Home, not the visibility of the StatsBanners on the Stats page.
Site older than 2 days:
Site just created:
* Create a new site from `/start/test-fse`
* Go to Customer Home at `/home/`
* You should not see any upgrade nudges above the checklist.
* Check Customer Home for an established site > 2 days old. If you haven't already dismissed them, you should see the upgrade nudges above the checklist.
Fixes #37273
=> Customer Home: Only show upgrade nudges (StatsBanners) for sites > 2 days

apps/full-site-editing/full-site-editing-plugin/full-site-editing/class-full-site-editing.php, apps/full-site-editing/full-site-editing-plugin/full-site-editing/plugins/close-button-override/index.js, client/state/selectors/get-editor-close-config.js
* Consistent back button style for template parts
* New label per @olaolusoga's suggestion.
* Fix some bugs with going back from template parts when there is no parent post in the query param.
1. Run this change on your sandbox.
2. Go to the FSE page editor **via customer home**, and edit the header.
3. The back button should look consistent and the label should say "< Page Layout"
4. Click the back button and it should work.
5. Edit the footer.
6. The back button behave the same as step 3.
7. Now, remove the `?fse_parent_post` query param from the URL and go to that URL.
7. The back button should say "< Home" and clicking it should take you to customer home.
Feel free to also test this in your local WordPress setup, making sure that navigation works properly to and from template parts …
=> FSE: Make Template Part back button consistent with page back button

client/my-sites/migrate/controller.js, client/my-sites/migrate/index.js, client/my-sites/migrate/section-migrate.js
Note: This change is behind a feature-flag and is part of an in-progress larger project. For context, see pbkcP4-8-p2.
Prior to this PR, the path for source-site selection for migration was `/migrate/:targetSiteSlug`. Upon selecting the target site, the path would update for confirmation of the selected source site to `/migrate/:sourceSiteId/:targetSiteSlug`. This had a few problems. One, if the sites list wasn't fully hydrated, `redirectWithoutSite` would cause a redirection to `/migrate/:sourceSiteId?site=:targetSiteSlug`. Since `/migrate/:sourceSiteId` resembled the `/migrate/:targetSiteSlug` path, that path was rendered, displaying a selector for the target site. Two, the combination of ID and slug in the URL doesn't look as nice as using slug for both the source and target site.
This …
=> Migration: resolve confirmation path ambiguity

client/components/checklist/task.js, client/my-sites/checklist/wpcom-checklist/component.jsx
* Improve the copy on the CTA buttons inside the checklist instead of generic "Start" actions. This is better for usability and accessibility.
* Change description text on the completed `update homepage` task so it makes sense in the context of the completed state.
* This also removed the estimated time on a completed task as it's no longer relevant for completed tasks.
Update homepage before | Update homepage after
----- | -----
Create tagline before | Create tagline after
----- | -----
Homepage updated before | Homepage updated after
----- | -----
Tagline Completed Before | Tagline completed After
* Create a new site or visit `My Home` on a site that has checklist tasks
* Make sure incomplete tasks have a descriptive button label (not just `Start`)
* …
=> Checklist: update copy on CTA buttons to be more descriptive

client/my-sites/hosting/main.js
To get a better idea of the Hosting features' performance, let's open up eligible Atomic sites back to November 28, 2018 (currently, only sites since October 31, 2019 have been eligible).
* Apply this branch, and go to `http://calypso.localhost:3000/hosting-config/`.
* Select an Atomic site created before Nov 28, 2018, and verify the Hosting section is not available (you should be redirected to the stats page).
* Select an Atomic site created after Nov 28, 2018, and verify the Hosting section is displayed.
Fixes #38148
=> Hosting: Allow sites dating back a year to be eligible.

client/components/site-selector/style.scss
* Fixes the pill that appears for private sites in some schemes (notably Classic Blue and Sunset) on hover
**Before:**
**After:**
* Visit `/me` and scroll to the Primary Site dropdown on an account with multiple sites
* Hover over a private site (Note: I couldn't actually get the hover shade in the original issue to appear, you might need to manually add the `is-selected` class to `.site`)
* Verify the colours are visible
cc @carinapilar & @sixhours - if I recall correctly, you were involved with this design
Fixes #37024
=> Site Selector: Fix Private Badge Colours

client/my-sites/hosting/sftp-card/index.js, client/my-sites/hosting/sftp-card/test/index.js
Adds some basic unit tests checking the SFTP card component, as there are a few places where we could easily get a regression with this component, so this will hopefully help to pick these up.
Originally added by @glendaviesnz in #38045 but moved to a separate PR to help unblocking the initial SFTP/phpMyAdmin rollout. 
Check the tests passed on CircleCI.
=> Hosting: Add unit tests for the SFTP card UI

client/my-sites/migrate/section-migrate.scss
Note: This change is behind a feature-flag and is part of an in-progress larger project. This PR is intentionally incomplete. For context, see pbkcP4-8-p2.
Updates the text colors for the site-confirmation screen of migration so that the arrow and the "A Business Plan" text at the bottom of the screen are now more accessible.
Before:
After:
Note: the site-names / addresses have been partially-removed from the screenshots
* Check out this pull request and run Calypso locally, or view it on calypso.live with the flag `tools/migrate.`
* Viewing calypso.localhost:3000/migrate/, you should see a `SiteSelector` component allowing you to choose a site to migrate a Jetpack site into.
* When you select a site, you should see another `SiteSelector` component, listing all the Jetpack sites your …
=> Update text colors on migration confirmation screen

client/components/data/query-site-checklist/index.js, client/my-sites/current-site/domain-warnings.jsx, client/my-sites/domains/components/domain-warnings/index.jsx, client/my-sites/domains/components/domain-warnings/test/index.js, client/state/checklist/actions.js, client/state/data-layer/wpcom/checklist/index.js, client/state/selectors/is-site-eligible-for-full-site-editing.js, client/state/selectors/test/is-site-eligible-for-full-site-editing.js, client/state/sites/constants.js, config/development.json, config/horizon.json
Part of https://github.com/Automattic/wp-calypso/issues/37867
Replaces horizon feature flag check with FSE flag check for conditionally showing the domain verification checklist step and hiding the domain verification nudge from the sidebar.
Original Pull Request where horizon flag was introduced https://github.com/Automattic/wp-calypso/pull/37510
* Gate the checklist-driven domain verification behind a check for a new `is_fse_eligible` flag (implemented in D36164-code ) so that the FSE check is correct immediately after signup
* Remove `experience/domain-verification-in-checklist` config flag checks
See https://github.com/Automattic/wp-calypso/pull/37510
Test for FSE and non-FSE users
A site created through the main onboarding flow where a domain is purchased will have the domain …
=> Enable checklist-driven domain verification for FSE sites

client/my-sites/checklist/wpcom-checklist/component.jsx
Context: p9OQAC-lY-p2
This PR is a follow up to https://github.com/Automattic/wp-calypso/pull/37721
It takes the mobile app task and adds a "skip" button.
Before:
After:
This PR updates dead code that's going to be tested separately as part of D36171-code. For this reason just eyeballing should be enough.
=> Make mobile app task skippable

apps/full-site-editing/full-site-editing-plugin/full-site-editing/blocks/template/style.scss, apps/full-site-editing/full-site-editing-plugin/full-site-editing/editor/style.scss
These changes only affect the Template Part preview, which is when they are rendered inside the page editor.
Template Part editor and front end are unaffected.
* Delete the `margin: 0` affecting blocks inside the Template Part preview.
* Remove the vertical paddings on the Template Part preview.
| Theme | Page Editor (old) | Page Editor (new) | Template Part (unchanged) |
| - | - | - | - | 
| Alves | <img width="1333" alt="alves-page-old" src="https://user-images.githubusercontent.com/2070010/70159438-ceee4b80-16b0-11ea-8479-0159ba55b9c1.png"> | <img width="1185" alt="alves-page" src="https://user-images.githubusercontent.com/2070010/70159463-d9a8e080-16b0-11ea-81e3-56cb6ded593d.png"> | <img width="1197" alt="alves-template" src="https://user-images.githubusercontent.com/2070010/70159473-d …
=> Full Site Editing: Update margins and paddings in the Template Part preview

client/signup/config/steps-pure.js
* Show 6 themes in signup selection step instead of 7.
Follow up to https://github.com/Automattic/wp-calypso/pull/38163.
1. Navigate to http://calypso.localhost:3000/start/test-fse/fse-themes
2. Verify that you can see 6 of the newly supported FSE themes.
3. It should be a random sampling from the following set: Alves, Maywood, Morden, Stow, Hever, Exford, Shawburn.
=> FSE: limit FSE themes in signup to 6

client/components/tinymce/plugins/wpcom-autoresize/plugin.js
This PR fixes an issue in which the height of the TinyMCE iFrame in the Classic Editor was set to 100px on iOS devices. The autoresize plugin was set to be disabled for iOS environments. Turning off that check fixes the problem, and seems to not cause other issues.
* Spin up a local Calypso development environment
* Open a Classic Editor and ensure that your browser is set to emulate an iOS device
* Ensure that the height of the Classic Editor fills the screen
Fixes #36763
=> Classic Editor: Enable autoresize TinyMCE plugin for iOS

client/components/checklist/style.scss, client/my-sites/checklist/wpcom-checklist/component.jsx
The mobile app nudge was recently reintroduced to the Checklist. This updates the button label to be more in line with the changes from #38149.
**To test:**
- create a new website
- verify that the checklist has a mobile app item
- verify that the button for the item reads "Download mobile app"
=> Checklist: update mobile app button label

client/my-sites/customer-home/main.jsx, client/signup/config/flows-pure.js, client/signup/config/flows.js
* Post signup, if a site is unlaunched or Atomic, the heading will show a "thank you" message for 30 mins (this is the same functionality, but now restricted to unlaunched sites to avoid confusion documented in #37930).
* After completing the launch flow, the heading will show a "congrats" message, using a query arg passed from the launch flow site destination.
* Outside these cases, the heading will show the standard "My Home" text.
**Before**
A site, just launched, with the incorrect header text and no acknowledgement of the launch.
**After**
A site, just launched.
* Switch to this PR, create a new site through `/start/test-fse`
* You should see a Thank You message in the header; this will persist for 30 minutes after site creation, or until the site is launched, whichever comes first. …
=> Customer Home: Update heading logic

client/components/keyed-suggestions/index.jsx, client/components/themes-list/index.jsx, client/my-sites/themes/theme-options.js, client/my-sites/themes/themes-magic-search-card/style.scss, client/my-sites/themes/themes-magic-search-card/welcome.jsx
* Fix a crash when an empty theme is returned from the API.
* Make the Theme filter names transatable.
Before:
After:
=> Theme Showcase: Add Translatabilty

client/my-sites/checkout/checkout/index.jsx, client/my-sites/checkout/controller.jsx, client/my-sites/checkout/gsuite-nudge/index.jsx, client/my-sites/checkout/gsuite-nudge/style.scss, client/state/selectors/is-eligible-for-signup-destination.js
* Wrap the GSuite Nudge component in `<CheckoutContainer>`, so that clicking the Skip button on the nudge will use `handleCheckoutCompleteRedirect()` to take the user to signup destination. Presently, the Skip button action is hardcoded to a checklist destination for all scenarios.
Fixes #
https://github.com/Automattic/wp-calypso/issues/35406
**Scenario 1**
* Go through the signup flow and add a plan(other than eCommerce) and domain to cart.
* Verify that you see the GSuite nudge and are able to complete the purchase.
* You should then be taken to flow destination.
**Scenario 2**
* On an existing account, add a new domain and GSuite subscription, and complete checkout. Verify the purchase completes. You should see the following thank you page:
**Scenario 3**
* Verify that …
=> GSuite nudge purchase/skip flow to respect destination

apps/full-site-editing/full-site-editing-plugin/posts-list-block/blocks/posts-list/editor.scss, apps/full-site-editing/full-site-editing-plugin/posts-list-block/blocks/posts-list/index.js, apps/full-site-editing/full-site-editing-plugin/posts-list-block/blocks/posts-list/transforms.js
If Blog Posts Listing detects a presence of Homepage Posts block, it shows a UI that makes it easy to transform itself into the new block
* Test Blog Posts Listing on its own - add to editor, configuration should work and on frontend, it shows posts
* Install [Newspack Blocks](https://github.com/automattic/newspack-blocks) plugin (don't forget `npm run build`)
* Refresh the editor with Blog Posts Listing - it should now show the option to Upgrade
- shows normal block functionality
- activates Newspack Blocks
- shows upgrade nudge
- uses it
Click to play:
<a href="https://cloudup.com/ceHa_H_reFg"><img width="318" alt="Screenshot 2019-11-29 at 16 12 35" src="https://user-images.githubusercontent.com/156676/69877672-15176980-12c3-11ea-8292-0c538aa8f35f.png"></a>
=> FSE: Add upgrade nudge to Blog Posts Listing block

client/my-sites/checkout/checkout/index.jsx
* Checkout: Disallow Atomic sites from adding add Jetpack Backup to cart
* Go to http://calypso.localhost:3000/checkout/jetpack_backup_daily_monthly/:site where `:site` is an Atomic site. 
* Verify your cart remains empty and you're redirected to the plans page.
* Go to http://calypso.localhost:3000/checkout/jetpack_backup_daily_monthly/:site where `:site` is a Jetpack site on a free plan without any backup products purchased. 
* Verify that after your cart loads, it has a Jetpack Backup product.
* Verify you can purchase it.
=> Checkout: Disallow Atomic to add Jetpack Backup to cart

client/lib/abtest/active-tests.js
* For the domain step improvements A/B test launched in https://github.com/Automattic/wp-calypso/pull/37661, we are increasing the variation to be shown to 90% of users as per discussions in p8Eqe3-Yc#comment-2850-p2.
* Follow the Test Plan given in https://github.com/Automattic/wp-calypso/pull/37661.
=> Domain step test: Increase variation to 90%

client/lib/signup/themes-data.js
Follow up fix to https://github.com/Automattic/wp-calypso/pull/38163 and https://github.com/Automattic/wp-calypso/pull/38163#issuecomment-561903230.
Bring back the Alves, Morden, Stow, and Hever themes to the `design-first` flow.
Props @p-jackson for pointing this out.
1. View the themes selection screen in the `design-first` flow.
2. Verify that Alves, Morden, Stow, and Hever themes appear there.
=> Signup: bring back template first themes to signup step

client/my-sites/plan-features/index.jsx, client/my-sites/plans-features-main/index.jsx, client/my-sites/plans-features-main/test/index.jsx, client/my-sites/plans/controller.jsx, client/my-sites/plans/main.jsx
Related to Private by Default interim fix: https://github.com/Automattic/wp-calypso/pull/38139
Adds support for `redirect_to` querystring argument on /plans page. Anything that's passed as such, will be passed to `/checkout` if user decides to upgrade.
* Go to /plans, press "Upgrade" a couple of times and confirm it works as usual including tabs navigation
* Repeat for Jetpack site
* Repeat for Signup
* Go to `/plans/<siteSlug>?redirect_to=/stats`
* Confirm that every time you click "Upgrade", you're redirected to /checkout?redirect_to=/stats
* This should work even if you switch active tab a couple of times (Personal vs Business plans tabs)
=> Add support for redirect_to query string argument on /plans

config/desktop-development.json
After #38000 landed, we forgot to remove an obsolete feature flag. This PR removes it.
* Config: Remove unused Jetpack onboarding flag
* Verify the removed feature flag is indeed not used anywhere.
* Further testing not needed
=> Config: Remove unused Jetpack onboarding flag

client/my-sites/sites/index.jsx
**This PR relies on #38155 being merged first.**
When directly accessing the `/hosting-config/` path, the site selector is displayed; however, currently all of a user's sites are available, regardless of their eligibility for hosting features. This PR filters the list of sites in the selector, removing both VIP and Jetpack sites (the two types of ineligible sites).
* Fire up #38155 locally and cherry-pick this PR's commit: `git cherry-pick ba69d2b9e7c74cd7da181177ff90ff9c0e224bd7`.
* Load https://calypso.localhost/hosting-config/.
* Search for both a VIP and a Jetpack site; ensure they are not found.
* Search for both a Simple and an Atomic site; ensure they are found.
Fixes #38127 .
=> Hosting: Show only eligible sites in the site selector.

client/components/data/query-site-selected-editor/index.jsx
* Add a check to verify siteId is set before dispatching the requestSelectedEditor action
With the change to useEffect in #37521, the action was being dispatched with every prop change, some of which included a null siteId
* Before checking out this PR load local calypso with network panel open and filtered to `/v3/sites`. You should see a number of requests to /v3/sites/null/gutenberg?_envelope=1
* Check out this PR and you should then only see requests with valid site ids
Before:
After:
Fixes #38220
=> Check that siteId is set before dispatching the requestSelectedEditor action

client/my-sites/sites/index.jsx
#38184 introduced filtering of the sites selector for the `/hosting-config` path, but it failed to consider the `hosting/all-sites` flag when evaluating Simple sites. This PR corrects this oversight.
* On `master` or production, load the `/hosting-config` path directly and notice all Simple sites are still available.
* Switch to this PR, and load the same path; notice Simple sites are no longer available (you should only see Atomic sites listed).
* Load the path with the `hosting/all-sites` flag enabled (`/hosting-config?flags=hosting/all-sites`), and ensure Simple sites are available again.
=> Hosting: Only expose Simple sites when behind the all-sites flag.

client/my-sites/hosting/sftp-card/index.js
The current message displayed on the hosting section for resetting the SFTP password seems cut off, so this PR aims to improve a little bit the copy.
|---|---|
| <img width="428" alt="Screenshot 2019-12-06 at 15 17 23" src="https://user-images.githubusercontent.com/1233880/70329739-5b794500-183c-11ea-8455-5e2de702f5f0.png"> | <img width="428" alt="Screenshot 2019-12-06 at 15 24 20" src="https://user-images.githubusercontent.com/1233880/70330005-efe3a780-183c-11ea-9f2e-9d15a448fe8a.png"> |
| <img width="649" alt="Screenshot 2019-12-06 at 15 17 35" src="https://user-images.githubusercontent.com/1233880/70329758-616f2600-183c-11ea-90f2-1fabec7bcd0c.png"> | <img width="646" alt="Screenshot 2019-12-06 at 15 24 27" src="https://user-images.githubusercontent.com/1233880/7033002 …
=> Hosting: Improve reset SFTP password copy

packages/composite-checkout/.gitignore, packages/composite-checkout/demo/index.js
Since apparently the test Stripe key does not need to be kept secure, this adds it directly to the demo so that the demo can be run more easily.
- Verify that the form works as expected.
=> composite-checkout: Add stripe test key to demo

client/lib/purchases/index.js
After making mappings free and always included with a plan, we broke the ability to remove them without removing the plan first. This PR addresses that.
Have a site with a paid plan. Add one or more mappings. Check in `/me/purchases` that you can remove them without removing the plan. There should be no refund (they were $0), but the subscription should be properly removed.
Go to a site with a paid plan and a bundled domain _registration_. Make sure there is no regression in that case (and any other you can think of).
=> Allow removing domain mappings included with a plan

apps/full-site-editing/full-site-editing-plugin/starter-page-templates/page-template-modal/index.js
Spun off from #37995.
For Gutenboarding, we want to pass a `templates` prop to the page template modal that's coming from a `@wordpress/data` store, rather than a `window.` global.
However, there's a problem with `PageTemplateModal`'s state handling, which expects the `templates` prop to be available in its constructor (and sets e.g. its `isOpen` state accordingly, which determines the modal's visibility).
That doesn't work with a selector that returns `undefined` when first called, and only returns something after its corresponding resolver runs :roll_eyes: As a consequence, this PR refactors `PageTemplateModal` so it no longer relies on that assumption, but treats `templates` as a prop that might at first be `undefined` and only later get a meaningful value.
This necessitates a whole …
=> SPT: Allow later passing of `templates` prop

client/my-sites/plans/current-plan/index.jsx
* Plans: Asyncload ProductPurchaseFeaturesList as this makes the My Plan page load a bit faster.
* Go to http://calypso.localhost:3000/plans/my-plan/:site where `:site` is a WP.com site.
* Verify it still loads the plan features at the bottom correctly and it looks well.
* Go to http://calypso.localhost:3000/plans/my-plan/:site where `:site` is a Jetpack site.
* Verify it still loads the plan features at the bottom correctly and it looks well.
=> Plans: Asyncload ProductPurchaseFeaturesList

client/me/purchases/manage-purchase/index.jsx, client/my-sites/plans-features-main/index.jsx, config/desktop-development.json, config/desktop.json, config/development.json, config/horizon.json, config/production.json, config/stage.json, config/test.json, config/wpcalypso.json
We're no longer using the Jetpack Backup feature flag as it's been in production for a while now. It's time to cleanup and remove the unnecessary feature flag.
* Config: Remove Jetpack Backup feature flag
* Go to http://calypso.localhost:3000/plans/:site where `:site` is a Jetpack site slug.
* Verify Jetpack Backup purchase UI is still displayed.
* Go to http://calypso.localhost:3000/plans/my-plan/:site where `:site` is a Jetpack site slug of a site that has both a Backup product and a plan. If you don't have such site, you can get one by buying the product first, and then the plan.
* Click "Manage Plan" or "Manage Product".
* Verify you can still see the overlap notices.
=> Config: Remove Jetpack Backup feature flag

client/me/purchases/manage-purchase/index.jsx, client/me/purchases/purchases-site/index.jsx, client/my-sites/plans-features-main/index.jsx
This PR updates the overlap notices to be loaded asynchronously, as they are not really needed on the initial page load. That helps remove some of the burden on the pages that they are loaded on.
**Note: this relies on #38244 so it has to be rebased after it lands.**
* Plans: AsyncLoad ProductPlanOverlapNotices
* Go to http://calypso.localhost:3000/plans/:site where `:site` is a Jetpack site slug of a site that has both a Backup product and a plan. If you don't have such site, you can get one by buying the product first, and then the plan.
* Verify the overlap notice appears.
* Click "Manage Plan" or "Manage Product".
* Verify you can still see the overlap notices.
* Go to http://calypso.localhost:3000/me/purchases 
* Verify you can still see the overlap notice for …
=> Plans: AsyncLoad ProductPlanOverlapNotices

client/my-sites/checkout/checkout-thank-you/header.jsx, client/my-sites/checkout/checkout-thank-you/index.jsx, client/my-sites/checkout/checkout-thank-you/style.scss, client/my-sites/checkout/checkout-thank-you/test/header.js, client/my-sites/checkout/checkout-thank-you/test/index.js, client/my-sites/checkout/controller.jsx
This PR is part of the PBD interim fix (https://github.com/Automattic/wp-calypso/issues/38110).
it's a subset of a super large https://github.com/Automattic/wp-calypso/pull/38139
It adds support for an alternate, "simplified" mode of showing things on checkout "thank you" page. It doesn't actually enable it for anyone yet.
**Before:**
**After:**
1. Upgrade to personal/premium/business/ecommerce from both signup and /plans, confirm you see the **Before** page
1. Create a free/personal/premium site
1. Go to /plugins and click on the business plan upgrade nudge (both on plugins list and specific plugin's page)
1. Upgrade to business
1. Confirm the thank you page still looks like **Before** screenshot above
1. Append the following query string args and confirm it looks like the **After** …
=> [PBD interim fix] Add cleaned up version of checkout thank you page

config/production.json, config/stage.json
Part of #3055. This PR enables our special WooCommerce onboarding flows for Jetpack and the WooCommerce.com OAuth connection flow in the `production` and `stage` environments.
These flows are only active when a certain query string is present (`?from=woocommerce-onboarding` for Jetpack or `?wccom-from=onboarding` for OAuth).
In WooCommerce 3.9 (beta releasing soon), we will be exposing users publicly to the new WooCommerce Core onboarding experience with uses both of these Calypso flows.
Nothing specific to test, but if you want to optionally try out the flows, you can access them via WooCommerce Admin.
* Install WooCommerce
* Install WooCommerce Admin from GitHub
* Enable WP_DEBUG
* Go to WooCommerce > Settings > Help > Setup Wizard and connect via the Jetpack flow
* Go to WooCommerce > …
=> Enable the new WooCommerce onboarding flow in production and staging

packages/composite-checkout/README.md, packages/composite-checkout/src/components/checkout-payment-methods.js, packages/composite-checkout/src/components/checkout-submit-button.js, packages/composite-checkout/src/lib/payment-methods/apple-pay.js, packages/composite-checkout/src/lib/payment-methods/credit-card.js, packages/composite-checkout/src/lib/payment-methods/paypal.js, packages/composite-checkout/src/lib/payment-methods/stripe-credit-card-fields.js, packages/composite-checkout/src/lib/validation.js, packages/composite-checkout/test/components/checkout.js
The Payment Method object contains several properties which it will use to display the behavior of that component. Currently those properties require React component _types_, that is, a reference to a component itself. This is a pretty uncommon pattern in the React ecosystem and since most of these components use hooks to decide on their behavior we no longer really need to render them inside their containers directly.
This PR changes most of the properties into React nodes instead, which is a very common pattern and should be easier for future developers to understand. The only one not changed is the `CheckoutWrapper`, which must be rendered by its container because it is passed children (there are other ways to do this but for now this seems an acceptable trade-off).
Before:
```js
{
id: …
```
=> composite-checkout: Refactor payment method components as React nodes

client/my-sites/hosting/main.js
Allow sites of any age to be eligible for Hosting features. 
Part of #38258 .
* Start this branch locally with `hosting/all-sites` enabled: `ENABLE_FEATURES=hosting/all-sites npm start`.
* Visit `https://calypso.localhost:3000/hosting-config` and select any site older than a year.
* Verify that the hosting section loads.
=> Hosting: Allow sites of any age.

apps/full-site-editing/full-site-editing-plugin/posts-list-block/blocks/posts-list/editor.scss, apps/full-site-editing/full-site-editing-plugin/posts-list-block/blocks/posts-list/index.js
* Uses the proper `Notice` component instead of winging it.
* Add a posts list block in your editor
* hit the Upgrade button and make sure it converts to Blog Posts block.
=> Posts List: Use Notice component for nudge

client/components/infinite-list/index.jsx, client/my-sites/people/delete-user/index.jsx
* Fix the replacement author selection flow when removing a user from a site
* Also make the Infinite List behave better when unmounting. Cancel the scroll update triggered in componentDidUpdate
* Try to remove a user with posts from a multiuser site. Choose to replace the author with another author. Does the picker work?
* Try scrolling posts in the Reader. Does it work as expected?
The bug occurred because a `<label>` is surrounding the `<Popover>` that shows the author list. The label ends up redirecting the click event on the chevron to the radio that the label contains. You can see this by setting a break in the onClose event on the popover and walk up the stack to inspect the event that triggered the close. I'm not entirely sure _why_ this is happening, it's not behavior I've seen …
=> Fix author selector on user deletion flow

config/desktop-development.json, config/desktop.json, config/development.json, config/horizon.json, config/production.json, config/stage.json, config/test.json, config/wpcalypso.json
In #38244 @delawski suggested that we remove the `plans/jetpack-scan` feature flag too, as we're not using that anywhere. This PR gets rid of it.
* Config: Remove unused scan feature flag
* Verify there are no usages of `plans/jetpack-scan` in the codebase.
=> Config: Remove unused scan feature flag

client/my-sites/checkout/checkout-thank-you/header.jsx
I missed this one while reviewing https://github.com/Automattic/wp-calypso/pull/38199, the upgrade intent should be the singular `install_theme` to match how the `isSimplified` prop is determined: https://github.com/automattic/wp-calypso/blob/05ea6bad5f05738690bf8e8922e4e1a1c3d6a3fd/client/my-sites/checkout/checkout-thank-you/index.jsx#L650
* Update the upgrade intent check for `install_themes` to be `install_theme`
* Follow the steps in https://github.com/Automattic/wp-calypso/pull/38199 (however since this isn't currently visible to a user, it likely doesn't need to be tested exhaustively)
=> Fix typo in upgrade intent for install_theme

client/my-sites/plan-features/index.jsx
* In /plans page, the pro-rated credits banner does not show for Atomic sites on a Business plan:
**BEFORE**:
**AFTER**
**Scenario 1**
* For a site on a free plan, verify no banner is shown.
* Upgrade to Premium -verify banner is shown
* Upgrade to eCommerce - verify banner is not shown(because we are on the highest tier already, so there's nothing more to upgrade too).
**Scenario 2**
* For a site on a Business plan, verify banner is shown
* Install a plugin on the site so that it goes atomic while continuing to be on the Business plan
* Verify that the banner still shows(without this patch it wouldn't have shown).
=> Fix: Pro-rated credits banner does not show for Atomic sites

client/components/domains/search-filters/style.scss, client/components/domains/search-filters/tld-filter-bar.jsx
The TLD Filter bar was ordered backwards for some reason - so instead of `.com/.net/.org/.blog/.club` we show `.club/.blog/.org/.net/.com`. I've updated how the buttons are displayed and fixed the filter buttons order too so that they're all consistent (primary button is first and then secondary). We'll stop reordering the TLDs based on the domain search terms so we need to make sure that the TLD Filter bar is displayed correctly.
@fditrapani I'm shamelessly pulling you in this 🙏 
* change the order of the TLD Filter buttons
* change the order of the filters Apply/Reset buttons too
Before:
After:
Before:
After (ignore the max chars and dashes - they're feature flagged). Just check the buttons:
* add a domain to an existing site and verify that the order of the TLD Filter buttons matches …
=> Domains: Fix how the TLD Filter bar is ordered

client/my-sites/migrate/section-migrate.jsx
* Prior to this PR, if you navigated to the migration section for an active migration (via the sidebar, or direct navigation), the migration progress page would be shown, but the source site would be undefined. This PR populates the source-site via a redirect to the `/from/:sourceSiteSlug/to/:targetSiteSlug` path when the source site returned from the API differs from the local source site (if any). This depends on D36498-code
(Note: most of these instructions are general instructions for testing migration. The **bolded** steps are the ones specific to this change)
* Check out this pull request and run Calypso locally, or view it on calypso.live with the flag …
=> Migration: redirect to the active migration when it's in progress

apps/full-site-editing/full-site-editing-plugin/posts-list-block/blocks/posts-list/index.js
* Hide Posts List block from the inserter
* Make sure it's hidden from the inserter but the functionality of already inserted blocks has not been affected. 
Easy way to test the functionality (if you don't have the block somewhere already inserted before hiding it) is to switch Gutenberg from Visual into the Code mode and insert the block markup there (paste ``) and after switching back to the visual mode, you should see the block working. 
If you preview such page, the block should also keep working on the frontend and show you some posts.
=> FSE: Hide Posts List block from the inserter

apps/full-site-editing/full-site-editing-plugin/posts-list-block/blocks/posts-list/index.js
Update nudge text to remove mentions of upgrading which are more than often connected with some sort of payment or a paid plan change. 
* Connect FSE to your WP dev env
* Build FSE `lerna run build --scope='@automattic/full-site-editing' --stream`
* In the editor, insert "Blog Posts Listing" block and observe the blue Notice
* It should no longer say "Upgrade" anywhere
=> FSE: Update block switch nudge text

client/components/keyed-suggestions/index.jsx
* Update Theme search card "show all" to work again.
This component was getting objects where it had expected arrays, causing errors and breaking functionality at use of array methods like `indexOf` etc.
Regex declarations have been moved above the if/else statement for use in both conditions.
* Run this PR.
* Navigate to `Themes` section of calypso.
* Scroll down and open "More Themes"
* Select a filter type such as "Subject"
* Click "Show all" in the top right of the suggestions.
* Verify all filters of this type are now shown.
* Type a filter term such as "ed" (in the example of subject the search input should now say `subject:ed`
* Verify that results appear ordered by relevance in the list.
ex)
Fixes #38272
=> Themes - Fix "show all" link for search card filters.

apps/full-site-editing/full-site-editing-plugin/full-site-editing-plugin.php
Use `switch_theme` instead of `after_switch_theme` for template part population. The `after_switch_theme` hook runs the callback on the **next request**, which means that population does not happen instantly. As you can imagine, this is problematic since FSE is not active if the template parts do not exist. Without this change there are weird periods where we expect FSE to be active, but it is not (see the bugs this fixes for more details).
1. Load this to your wpcom sandbox and sandbox the API.
2. On a **logged-in** WordPress.com account, go to https://horizon.wordpress.com/start/test-fse. Go through the flow selecting any theme.
1. Once you land in Calypso, wait a few seconds. Make sure that the "Customizer" item in the sidebar does not exist and that it does not suddenly appear after a …
=> Use switch_theme hook for template part population

client/state/signup/steps/site-vertical/reducer.js, client/state/signup/steps/site-vertical/schema.js
Since we added `suggestedTheme` [to the site vertical object](https://github.com/Automattic/wp-calypso/commit/3195870a615e185e85ed1a89321669058556ff64), its corresponding schema definition object is whining.
Let's silence it.
In this PR, we're adding a default property `suggestedTheme` to the siteVertical step state reducer.
Furthermore,  we'll add it to the schema definition object.
1. Fire up http://calypso.localhost:3000/, and preserve your browser console logs!
2. Create a **Business > Real Estate Agent** site, or another combo that doesn't return a suggested theme.
SILENCE!
=> [SIGNUP]: Add default value for suggestedTheme in site vertical reducer

client/signup/main.jsx
After the signup flow is complete, we redirect the user to the final destination based on their login state. 
If the signup progress state is not cleared, then any attempt to create a new site will result in the user seeing the site creation loading page.
This is _no bueno_.
On new signups, the app doesn't know if the user is logged in until after they've created a site and arrived at the destination. That's why the `isLoggedIn` check fails.
This patch resets the controller under all conditions. Specifically it resets the controller when the user isn't logged in and the login method is not `oauth` (regular login).
Related PR: #36047
1. Sign up for a new account at https://wordpress.com/start, ending up at URL: https://wordpress.com/home/SITE_ADDRESS
2. In the sidebar, select "Add new …
=> [SIGNUP]: clear progress state after flow completion

client/components/gsuite/gsuite-features/index.jsx, client/components/gsuite/gsuite-features/test/compact.js, client/components/gsuite/gsuite-features/test/index.js, client/components/upgrades/gsuite/gsuite-upsell-card/index.jsx, client/components/upgrades/gsuite/gsuite-upsell-card/product-details.jsx, client/components/upgrades/gsuite/index.jsx, client/lib/cart-values/cart-items.js, client/lib/gsuite/constants.js, client/lib/gsuite/index.js, client/lib/products-values/index.js, client/my-sites/checkout/cart/cart-item.jsx, client/my-sites/checkout/cart/style.scss, client/my-sites/checkout/gsuite-nudge/index.jsx, client/my-sites/email/gsuite-add-users/index.jsx, client/my-sites/email/gsuite-purchase-cta/index.jsx
This pull request displays and formats the price in the shopping cart when a G Suite discount is applied. It also displays a short text next to the price:
Popup | Checkout 
------ | -----
Finally, it introduces constants to avoid referring to slugs directly, and to take ease future refactoring.
1. Apply 2332e-pb to your sandbox to simulate a discount to the frontend
2. Apply D36169-code to to your sandbox to help differentiate between different discounts.
3. Point `public-api.wordpress.com` to your sandbox
4. Run `git checkout add/gsuite-discount-shopping-cart` and start your development server
5. Log in to an account that has a site without G Suite
6. Open the [`Email` page](http://calypso.localhost:3000/email), then click the `Add G Suite` button
7. Fill in the form, and click the …
=> G Suite: Display discount in shopping cart

client/my-sites/migrate/section-migrate.jsx, client/my-sites/migrate/section-migrate.scss
* Stores migration start time in localStorage, and shows it during a migration.
* The design for this view had the time string worded as "Migration started on Nov 15, 2019 at 12:38 pm". This is a US-style date format, but having a preposition between date and time doesn't lend itself to translation. It's also more efficient to store the timestamp as one string, so I've done it as shown.
* **Check out D36604-code and follow the test instructions for that patch.**
* Check out this pull request and run Calypso locally.
* Viewing …
=> Site migration: progress view add start time

apps/full-site-editing/full-site-editing-plugin/global-styles/class-global-styles.php
This filter out the system fonts from being requested at Google Fonts.
* Build the Full Site Editing plugin and copy it within the `wp-content/plugins` directory of a test site.
* In the `functions.php` file of your active theme, add:
```php
add_theme_support(
'jetpack-global-styles',
[
'enqueue_experimental_styles' => true,
'enable_theme_default' => true,
'font_base' => 'serif',
'font_headings' => 'sans-serif',
]
);
```
* Activate the FSE plugin and go to the block editor. You should see the Global Styles sidebar's button in the right-top corner.
* Go to the front of your site and check that the request at `fonts.googleapis.com` triggers a 400 error. [1]
* Apply this patch.
* Go to the front end of your site and check that the request status at `fonts.googleapis.com` is 200. Check also …
=> Filter out system font from Google Font requests

apps/full-site-editing/full-site-editing-plugin/full-site-editing-plugin.php, apps/full-site-editing/full-site-editing-plugin/full-site-editing/helpers.php
This moves FSE-specific functions into the `full-site-editing` function and out of the main plugin function. Since we are including more and more features in our plugin (and possibly renaming it), it makes sense to remove FSE-specific files out of the function to improve code quality. Plus, this file was getting pretty big anyways :)
Do you have feedback on the filename or location?
Essentially, smoke test everything to do with FSE locally and on your sandbox, paying close attention to template population and the `is_fse_active` stuff.
=> Move FSE-specific functions outside of main plugin file

client/my-sites/migrate/controller.js, client/my-sites/migrate/index.js
* Redirects the `/migrate` path to `/` when the feature-flag `tools/migrate` is disabled
* Verify that navigating to `/migrate?flags=+tools/migrate` renders the site selector
* Verify that navigating to `/migrate?flags=-tools/migrate` redirects you to `/`
* Verify that navigating to any other `/migrate/*` path with the feature-flag disabled also redirects you to `/`
=> Migration: Redirect migrate path to root when disabled

apps/full-site-editing/full-site-editing-plugin/full-site-editing/plugins/close-button-override/style.scss
* Subtract some margin from the left of the dashicon to horizontally balance the close button.
Alternatively, we could add margin to the right of the label.  However this way we don't take up more space than we need to.  If others feel the button looks a bit "cramped," we can look at the alternate approach.
* Run this PR in the FSE Plugin.
* Navigate to the editor.
* Verify the button is "centered"
**BEFORE**
**AFTER**
Fixes #37741
=> FSE - Fix close button centration. 

client/my-sites/themes/theme-showcase.jsx, client/state/themes/selectors.js
* Added `tier` to the various query checks for Themes Showcase conditions.
This will allow users to load `wordpress.com/themes/free` without having the results hidden below Recommended Themes and behind the "More Themes" button.
* Run this PR.
* Load to `calypso.localhost:3000/themes/free` and `calypso.localhost:3000/themes/premium`
* Verify that Recommended Themes are not visible and that the tier results are visible by default.
* Smoke test search functionality and reloading behavior around my-sites/themes.
Fixes #38327
=> Fix Themes Showcase loading on selected tiers.

client/blocks/product-selector/README.md, client/blocks/product-selector/docs/example.jsx, client/blocks/product-selector/index.jsx, client/jetpack-connect/style.scss, client/lib/products-values/constants.js, client/my-sites/plans-features-main/header.jsx, client/my-sites/plans-features-main/index.jsx, client/my-sites/plans-features-main/products-header.jsx
As part of the work related to p1HpG7-87V-p2, this PR moves the link to Jetpack Backup landing page from `ProductSelector` to `FormattedHeader`.
**Before**
**After**
* Move Jetpack Backup landing page link from selector to formatted header
* Go to http://calypso.localhost:3000/plans/ and select a Jetpack site having no Jetpack Backup product
* Confirm that the link to the landing page is now located in the header and not inside the products selector.
* Purchase one of the Backup products and confirm that there's no link displayed on 
http://calypso.localhost:3000/plans/ for the Jetpack site.
* Remove the previously purchased Backup product and purchase one of the paid plans. Confirm that there's still no link displayed on http://calypso.localhost:3000/plans/ for the Jetpack site.
Fixes …
=> Move Jetpack Backup landing page link from selector to formatted header

client/components/product-card/style.scss, client/lib/products-values/constants.js
As part of the work related to p1HpG7-87V-p2, this PR centers the `ProductCard` options heading, updates its wording and removes the bottom border.
Also, a vertical separator between options is added as part of this PR.
Lastly, some minor padding/margin adjustments in the options area are made here so that it all looks good.
**Calypso - before**
**Calypso - after**
**Jetpack Connect - before**
**Jetpack Connect - after**
Those updates apply to Jetpack Connect flow as well.
* Update product card options alignment, wording and appearance
* Go to http://calypso.localhost:3000/plans/ and select a Jetpack site having no Jetpack Backup product
* Confirm that the changes mentioned in this PR description are done and there are no regressions. 
* Go to Jetpack Connect flow: …
=> Update product card options alignment and appearance

client/my-sites/activity/activity-log-banner/intro-banner.jsx, client/my-sites/activity/activity-log/index.jsx, client/state/purchases/selectors.js, client/state/purchases/test/selectors.js
Currently, when displaying the Activity Log intro banner, we will check if the user is on a free plan or not, but we don't consider if a user has purchased a backup product. So in the case where a user has purchased a Backup product but is on free plan, we'll display the banner as if the AL is limited to 20 entries (when really it's not).
This PR fixes this issue by altering the logic to consider the products, too.
* State: Introduce a `siteHasBackupProductPurchase` selector with tests.
* Activity Log: Update Intro banner to take Backup product into consideration
* Activity Log: Use siteHasBackupProductPurchase selector instead of the obsolete `hasBackupProduct` helper (cc @seear - this can be considered a follow-up of this suggestion - …
=> Activity Log: Consider Backup products when displaying intro banner

client/my-sites/domains/domain-management/components/header/index.jsx, client/my-sites/email/email-management/index.jsx
This PR adds a page title to the domains child pages. 
**Before**
**After**
* Visit a site with a custom domain: `/domains/manage/[site-url]`
* Click the custom domain to go to the domain settings screen.
* Verify the `Domains` title appears at the top of the page.
* Click on all the sub pages (Email, Name servers and DNS, Contacts and Privacy, Transfer Domains).
* Verify the Domains title appears at the top of the page. 
* Now go to `/plans/my-plan/[site-url]`
* Click on the `Email` tab.
* Verify that the page title is email and not domains.
cc @danhauk, @sixhours
=> Add domains title to domains screens

client/landing/gutenboarding/components/header/index.tsx
* remove WordPress logo from header
W logo should no longer be displayed in header
=> Gutenboarding: Remove logo from header

client/components/gsuite/gsuite-price/index.jsx, client/components/gsuite/gsuite-price/test/__snapshots__/index.js.snap, client/lib/abtest/active-tests.js, client/my-sites/email/gsuite-purchase-cta/test/__snapshots__/index.js.snap
This pull request removes the A/B test introduced in https://github.com/Automattic/wp-calypso/pull/37919. We no longer need it since the new strings have been translated, and coupons are handled server-side. Here is how the `Email` page should look like now:
Without discount | With discount
----- | -----
1. Run `git checkout remove/gsuite-discount-test` and start your server, or open a [live branch](https://calypso.live/?branch=remove/gsuite-discount-test)
2. Log in to an account that has a site with a domain but without G Suite
3. Open the [`Email` page](http://calypso.localhost:3000/email)
4. Assert that the pricing block is displayed as in the screenshots above
5. Sandbox the store to access a valid coupon
6. Refresh the page
7. Assert that the pricing block is displayed as in the …
=> G Suite: Remove A/B test introduced for discount

packages/components/src/card/index.jsx
Extracted from #38175.
Calculate the class in the Card render function. It's always calculated anyways, nothing is gained by extracting it to a function.
Compare:
* https://calypso.live/devdocs/design/card?branch=update/card-component-refactor
* https://wpcalypso.wordpress.com/devdocs/design/card
No regressions.
=> Component: Simplify Card className

apps/full-site-editing/full-site-editing-plugin/starter-page-templates/index.js
* Remove Icon from SPT Sidebar Plugin in editor.
* Run this PR and FSE.
* Navigate to page editor.
* Verify SPT document sidebar panel has no icon.
**BEFORE**
**AFTER**
Fixes #38358
=> removed icon from spt sidebar panel

client/reader/sidebar/index.jsx
Hi interesting people!
A while back in https://github.com/Automattic/wp-calypso/pull/37547 we updated Reader links from `/` to `/read`.
For context see:
p58i-89H-p2
EPIC Issue: Automattic/zelda-private#173
Calypso PR: Automattic/wp-calypso#37547
This PR updates a further Reader link in the Reader **Streams** menu to `/read`
1. Fire up the branch and head to http://calypso.localhost:3000/read
2. Check that the **Followed Sites** link in the left-hand-side **Streams** menu links to `/read`
3. Check that you're getting the best deal from your energy provider. You could save $100s!
=> Reader: update the reader link from `/` to `/read`

client/landing/gutenboarding/gutenboard.tsx
Ensure the onboarding block is stable (`useRef` over `useMemo`).
Update attributes via store.
See https://github.com/Automattic/wp-calypso/pull/38282/files#r357422845.
* No regressions from #38282
=> Use ref over memo for stable onboardBlock

client/lib/analytics/index.js
_superProps is a function, not an object.
Fixes: p4qSXL-3kr-p2
Open calypso.live link and run these in console to enable analytics:
https://calypso.live/?branch=fix/superprops
```
document.cookie = 'flags=gdpr-banner,google-analytics,ad-tracking; path=/; domain=.' + document.location.hostname.split( '.' ).slice( -2 ).join( '.' );
document.cookie = 'sensitive_pixel_option=yes; path=/; domain=.' + document.location.hostname.split( '.' ).slice( -2 ).join( '.' );
```
Now refresh page and filter Network tab by `calypso_page_view`.
- Confirm these props exist:
=> Fix `_superProps` in Tracks events.

apps/full-site-editing/full-site-editing-plugin/blog-posts-block/editor.js
Disable "multiple" support for the Blog Posts block.
1. Check-out this branch,
2. Build FSE plugin (`npx lerna run dev --scope='@automattic/full-site-editing' --stream`),
3. Activate it,
4. In the editor add a Blog Posts block,
5. You should not be able to add another one (it should be greyed-out).
Fixes #38404
=> Disable "multiple" support for the Blog Posts block

client/my-sites/customer-home/style.scss
* The large, hollow circle icons looked like clickable checkboxes on a checklist. This PR turns them into smaller, closed circles, to act more like bullet points.
* This should not have an effect on the Jetpack checklist, since the styles live in Customer Home's SCSS
**Before**
**After**
* Create a new site from `/start`; finish signup and you'll land on Customer Home
* Note the new styles; check for visual bugs, make sure you can still complete tasks and launch your site.
=> Customer Home: Update checklist bullets to look less clickable

packages/composite-checkout/src/lib/payment-methods/credit-card.js, packages/composite-checkout/src/lib/payment-methods/paypal.js, packages/composite-checkout/src/lib/payment-methods/stripe-credit-card-fields.js
This reverts the changes made to composite-checkout by #38308 which
accidentally replaced the local Button component imports with the Button
component from `@automattic/components`.
- Verify that the buttons in the form work as expected, notably the "Continue" buttons and the "Pay" button for Paypal and the second Credit Card payment method.
=> composite-checkout: Restore Button imports

apps/wpcom-block-editor/README.md, apps/wpcom-block-editor/src/common/fix-block-invalidation-errors.js, apps/wpcom-block-editor/src/common/index.js
Part of https://github.com/Automattic/wp-calypso/issues/37230
This PR attempts to auto-fix block-invalidation errors once on load.
When a block parses HTML markup, it also tries to validate the data by re-serializing and comparing the result. Unfortunately blocks currently compare with an _exact_ string match. Even a small whitespace for change for completely equivalent markup/styling, is enough to cause the following scary error:
Traditionally WP allows manipulation of content from a variety of filters/customizations from 3rd party code, so this is a very easy case to fall into, especially if older customizations are not Gutenberg aware.
Most folks don't understand what this warning means, so let's try auto-applying the most common want, which is block-recovery. Or just make my blocks …
=> Gutenberg: autofix block validation issues on editor load

client/me/security/controller.js
Instead of showing a transient notification, make the password change notification persistent and require the user to dismiss it. This allows the notification to show up immediately after the page load.
=> fix(security): Make the password change success notification persistent

client/my-sites/themes/themes-selection.jsx
* Add an `incrementPage` request on `componentDidMount` for the themes-selection component.
This change is intended to create a larger "buffer" of themes in the window making it more difficult to "overscroll" too early and bug out the pagination component from requesting more pages.  Some more notes on this bug can be found on the issue #38410.  
* Run this PR.
* Navigate to the Themes Showcase.
* Scroll down and click "More Themes".
* Scroll down more immediately.
* Verify pagination requests continue as expected.
NOTE:  This may be a bit difficult to test as the original issue is hard to consistently recreate in a reasonable manner.  These changes intend to make this even more difficult to recreate, however this bug can always be triggered through scrolling too far down while pagination …
=> Themes Showcase - Fix bug stopping pagination requests.

apps/full-site-editing/full-site-editing-plugin/starter-page-templates/page-template-modal/components/template-selector-control.js, apps/full-site-editing/full-site-editing-plugin/starter-page-templates/page-template-modal/components/template-selector-item.js, apps/full-site-editing/full-site-editing-plugin/starter-page-templates/page-template-modal/index.js, client/landing/gutenboarding/onboarding-block/design-selector/index.tsx
`handleTemplateConfirmation` is a somewhat redundant prop on both `TemplateSelectorControl` and `TemplateSelectorItem`, since there's already `onSelect`. Furthermore, the current check in `TemplateSelectorItem` (whether to invoke it or not upon template selection) relies on `window` and thus breaks encapsulation.
This PR moves aforementioned logic to the 'consumer' component, `PageTemplateModal`. This should also make it easier to isolate `TemplateSelectorControl` (see #38378).
Test Starter Page Templates on a screen that's less wide than 660px. Verify that clicking on one of the templates readily creates a new page, based on that template (rather than just highlighting it as selected).
=> SPT: Move handleTemplateConfirmation up the component hierarchy

client/components/gsuite/gsuite-features/style.scss, client/components/gsuite/gsuite-price/style.scss, client/components/upgrades/gsuite/gsuite-upsell-card/product-details.jsx, client/components/upgrades/gsuite/gsuite-upsell-card/style.scss
This pull request seeks to fix alignment issues on the `Upsell` pages in certain languages where prices and discount would be displayed on more than two lines:
Before | After
------ | -----
You should test those changes in different languages, and browser widths:
1. Run `git checkout fix/gsuite-discount-display` and start your server, or open a [live branch](https://calypso.live/?branch=fix/gsuite-discount-display)
2. Sandbox the store to enable the discount
3. Log into an account that has a site with a domain but not G Suite
4. Open the [`Email` page](http://calypso.localhost:3000/me/email)
5. Asserts that everything looks like before
6. Navigate to the [`Domain Search` page](http://calypso.localhost:3000/domains/add)
7. Select a domain to access the `Upsell` page
8. Asserts that the …
=> G Suite: Prevent prices and discount from wrapping

apps/full-site-editing/full-site-editing-plugin/starter-page-templates/page-template-modal/components/preview-template-title.js, apps/full-site-editing/full-site-editing-plugin/starter-page-templates/page-template-modal/components/template-selector-preview.js, apps/full-site-editing/full-site-editing-plugin/starter-page-templates/page-template-modal/components/test/__snapshots__/template-selector-preview-test.js.snap, apps/full-site-editing/full-site-editing-plugin/starter-page-templates/page-template-modal/styles/starter-page-templates-editor.scss
This is a replacement of #37744.
* Restructure the SPT selector modal.
* The modal is now less dependant from the WP sidebar state (expanded, collapsed, hidden).
* The modal z-index is now below the wp-admin admin bar and sidebar.
* The template selector and preview are fully now responsive (roughly filling a 30/70 of the screen).
* The template preview doesn't scale more than if it was rendered in a 960px viewport. This means that: it shrinks down when the preview is <960px wide, and simply remains at the same size (filling the available space responsively) when >960px.
* The template preview title uses the same scale value of the content.
* The preview re-renders on window resize and, if in wp-admin, also on sidebar toggle.
https://cloudup.com/cjjFwMPrG2o
- When changing layout (edit …
=> Starter Page Templates: Update the selector look and feel

client/blocks/site-address-changer/dialog.jsx, client/blocks/site-address-changer/index.jsx, client/blocks/site-address-changer/style.scss, client/my-sites/domains/domain-management/change-site-address/index.jsx, client/my-sites/domains/domain-management/controller.jsx, client/my-sites/domains/domain-management/edit/wpcom-domain.jsx, client/my-sites/domains/domain-management/index.jsx, client/my-sites/domains/index.js, client/my-sites/domains/paths.js
* Adds a new page for Change Site Address, linked from the domain settings screen.
* Adds a link with tracking to redirect folks to add a new domain, in case they've mistaken "Change Site Address" for wanting a custom domain.
* Adds a label to the text input for accessibility.
* Simplify copy to make it more concise.
* Simplify and standardize visual styles to match other Domains sections.
* Switch to this PR and go to Manage -> Domains on a *.wordpress.com or *.*.blog site
* Click on the *.wordpress.com site address to edit it.
* Click Change Site Address
* Try to change your site address. Put in a URL you know you can't use, and one you can. Make sure the proper notifications show up.
Fixes #36737
=> Domains: Move Change Site Address tool to its own page

client/components/domains/map-domain-step/index.jsx, client/components/domains/register-domain-step/index.jsx
* For domains that have a mappable status of `mapped_domain`, we should always show the notice that the domain is already mapped even if the domain is transferable.
Hack the back end to return the following:
```
domain_name: "your-examnple-domain-name.com"
mappable: "mapped_domain"
status: "transferrable"
supports_privacy: true
```
Go to the mapping page (ex.: http://calypso.localhost:3000/domains/add/mapping/a8ctest.com)
Type in a domain and make sure that you see the error notice saying: "This domain is already mapped to a WordPress.com site."
Make sure that mapping still works for un-mapped, registered domains that are both transferrable and non-transferrable.
Also make sure that you see the mapped notice from the domain search page:
And make sure that when you see the mapped notice …
=> Show mapped domain notice when status is reported as transferrable.

packages/composite-checkout-wpcom/src/components/wp-order-review-line-items.js
This PR fixes a spacing issue in the order review of the new checkout.
**Before**
**After**
* Get calypso running locally.
* Add a product to cart and go to checkout
* Add `?flags=composite-checkout-wpcom` to the url when you're in checkout. 
* Make your way to the review step and ensure the spacing doesn't look off.
=> Composite checkout: Fix spacing

client/my-sites/sites/index.jsx, client/state/selectors/can-site-view-atomic-hosting.js
This PR removes the feature flag shielding the Hosting Configuration section from Simple sites.
<hr>
To recap expected states:
**Hosting Panel when access is activated on an Atomic site:**
**Hosting Panel with upgrade banner on a Simple site:**
<hr>
This should not change any functionality, besides removing the development flag and no longer encapsulating the existing Upgrade banner/visibility to Simple Sites for the panel.
*  Startup a local Calypso development environment with this branch and  `npm start` without setting any feature flags.
* Make sure that you can view the Hosting Configuration section using a Simple Site.
* Ensure there are no regressions.
<hr>
This is a followup to #36489 in preparation to flip the switch.
=> Hosting: Remove feature flag for hosting/all-sites

client/components/checklist/checklist.js, client/my-sites/checklist/wpcom-checklist/component.jsx, client/my-sites/checklist/wpcom-checklist/wpcom-task-list.js, client/my-sites/customer-home/main.jsx, client/my-sites/plans/current-plan/jetpack-checklist/index.tsx, client/state/data-layer/wpcom/checklist/index.js, client/state/selectors/get-site-task-list.js, client/state/selectors/is-eligible-for-dotcom-checklist.js, client/state/selectors/test/is-eligible-for-dotcom-checklist.js
* Remove the `isAtomic` restriction from the Customer Home component
* Excise references to `phase2`
* Apply `phase2` behavior for all! Remove `getTasks` wrapper function and just use tasks from the server
* Short `React.Fragment` syntax
* Fixup jsDoc & import syntax for `isEligibleForDotcomChecklist`
* Enable dotcom checklist for Atomic sites in the client (even in ecommerce -- Let the server decide if tasks are provided)
* Add tests for `isEligibleForDotcomChecklist` selector
* Verify test behavior coverage & `npm run test-client client/state/selectors/test/is-eligible-for-dotcom-checklist.js`
* Apply D36492-code & sandbox the API
* Visit `/home` for a newish simple site
* The checklist should be displayed & functional
* Visit `/home` for a newish Atomic site without the WooCommerce …
=> Checklist: Remove isAtomic restriction

packages/composite-checkout/src/lib/stripe.js
Previously, the useStripeJs hook had three different states: the stripe
object, the loading state, and a saved error.
Because multiple calls to setState in an async function are not batched,
this will result in multiple re-renders of the component using this hook.
Because these states are dependent on each other, we can combine them
into one state, which this change does. This also results in a much
simpler useEffect call.
- Verify that the stripe form (the second credit card form) works as expected.
=> composite-checkout: Change useStripeJs to use reducer

client/my-sites/customer-home/main.jsx
In #38289, we enabled the Onboarding Checklist for Atomic sites (in practice, just for Business sites).
Unfortunately, if sites go Atomic prior to completing the "Update Your Homepage" task, it becomes impossible to complete.
See D36812-code for more info.
* Set the `displayChecklist` prop to false when the selected site is Atomic
* Browse to `/home` for a new Business site that's gone Atomic
* You should not see the checklist
* Browse to `/home` for a new WPCOM simple site
* You should see the checklist
=> Checklist: Temporarily disable for Atomic sites

client/me/concierge/shared/closure-notice.js, client/me/concierge/shared/primary-header.js
_For additional context, check p58i-8mZ-p2_.
* Displays a closure notice banner on the Quick Start schedule session page for the upcoming Xmas and New Year holidays.
* On an account that has a Business plan, head to /me/concierge and select the Business plan site. 
* You should not be seeing any notices now
* Change your computer's date and time settings to the following and observe the effects:
- Before 17th Dec 2019 00:00 UTC, you should not see any banner
- Between 17th Dec 2019 00:00 UTC and 24th Dec 2019 00:00 UTC, you should see the following banner:
- Between 24th Dec 2019 00:00 UTC and 26th Dec 2019 07:00 UTC, you should see the banner below:
* Between 26th Dec 2019 07:00 UTC and 31st Dec 2019 00:00 UTC, you should see:
* Between 31st Dec 2019 00:00 UTC and 2nd Jan 2020 07:00 UTC, …
=> 2019 Quick Start closure notice for Xmas and New Year

client/me/help/help-contact/index.jsx, client/me/help/live-chat-closure-notice/index.jsx
_For additional context, please check p58i-8mZ-p2._
* Displays a closure notice banner on the /help/contact page and live chat interface for the upcoming Xmas and New Year holidays.
* On an account on a free plan, verify that the notice does not show in the inline help widget or /help/contact
* On any account that has a paid plan, verify the following on both the inline help widget and the /help/contact page by modifying your system's date/time settings:
- Before 17th Dec 2019 00:00 UTC, you should not see any banner
- Between 17th Dec 2019 00:00 UTC and 24th Dec 2019 00:00 UTC, you should see the following banner:
- Between 24th Dec 2019 00:00 UTC and 26th Dec 2019 07:00 UTC, you should see the banner below:
- Between 26th Dec 2019 07:00 UTC and 31st Dec 2019 00:00 UTC, you should see:
- …
=> 2019 Live Chat closure notice for Xmas and New Year

client/my-sites/plan-features/header.jsx, client/my-sites/plan-features/test/header.jsx, client/my-sites/plan-features/test/index.jsx
* In `/plans/{SITE_SLUG}` page, the "Credit applied" badge does not show for an atomic site on the Business plan. 
* This is a follow-up to https://github.com/Automattic/wp-calypso/pull/38247, which fixed the missing pro-rated credits banner on atomic sites.
**BEFORE**(Missing "Credit applied" badge on atomic site)
**AFTER**
Verify all the following on the plans page at `/plans/{SITE_SLUG}`:
**Scenario 1**
* For a site on a free plan, verify the badge is not shown.
* Upgrade to Premium -verify badge is shown on all higher plans
* Upgrade to eCommerce - verify badge is not shown on any plan(because we are on the highest tier already, so there's nothing more to upgrade too).
**Scenario 2**
* For a site on a Business plan, verify badge is shown on the eCommerce plan
* Install a plugin on the …
=> Fix: Missing "Credit applied" badge on atomic sites

client/landing/gutenboarding/onboarding-block/edit.tsx
* Change "Don't know yet" to "next" when a site title is provided
* Visit `/guetnboarding`, pick a vertical and add a title. When the title is filled, the text at the bottom should say "next"
Fixes #
=> Gutenboarding: "next" when siteTitle is set

client/landing/gutenboarding/components/card/README.md, client/landing/gutenboarding/components/card/body.js, client/landing/gutenboarding/components/card/context.js, client/landing/gutenboarding/components/card/divider.js, client/landing/gutenboarding/components/card/footer.js, client/landing/gutenboarding/components/card/header.js, client/landing/gutenboarding/components/card/index.js, client/landing/gutenboarding/components/card/media.js, client/landing/gutenboarding/components/card/styles/card-styles.js, client/landing/gutenboarding/gutenboard.tsx, client/landing/gutenboarding/onboarding-block/design-selector/index.tsx, client/landing/gutenboarding/onboarding-block/design-selector/style.scss, client/landing/gutenboarding/style.scss
* Removes dependence on sibling monorepo app's components (FSE plugin)
* Pulls in unpublished `Card` from `@wordpress/components` (mostly simple copy)
* Fixes an issue where a `position: fixed` from Gutenberg styles breaks the block editor's overflow (no scrolling)
* Uses simple grid layout from #38403 (props @ockham)
* Implements very simple list layout designs from API + `MediaCard` component.
* Adds simple selected design visual feedback for demonstration
Closes #38403 (supersedes)
* Go to `/gutenboarding` on (calypso.live or dev branch)
* Pass the first screen (select a vertical and site title) and click "Next"
* Play with the design picker ✨
=> Gutenboarding: Drop FSE reuse/use MediaCard

apps/wpcom-block-editor/src/common/style.scss
https://github.com/WordPress/gutenberg/pull/18686 changed how the editor is positioned on mobile.
In Core the admin bar is always visible, even in fullscreen mode.
In WPCOM, instead, the admin bar is never visible, so we don't need the `top` offset for it.
This PR sets `top: 0` to the elements affected by the changes in Gutenberg 7.1.0 (at least those that I've noticed).
I've also removed a couple of rules that aren't applicable anymore, as `.edit-post-layout__content` has been recently removed.
| - | - |
| <img width="403" alt="Screenshot 2019-12-12 at 18 36 04" src="https://user-images.githubusercontent.com/2070010/70739653-3dfe1c80-1d0f-11ea-89bc-871dc798adcb.png"> | <img width="400" alt="Screenshot 2019-12-12 at 18 36 14" …
=> WPCOM Block Editor: Fix incorrect editor position on mobile

apps/full-site-editing/full-site-editing-plugin/starter-page-templates/page-template-modal/components/template-selector-control.js, client/landing/gutenboarding/onboarding-block/edit.tsx, client/landing/gutenboarding/onboarding-block/site-title.tsx, client/landing/gutenboarding/onboarding-block/stepper-wizard.tsx, client/landing/gutenboarding/onboarding-block/vertical-select/index.tsx, client/landing/gutenboarding/stores/domain-suggestions/resolvers.ts
* Add types to TemplateSelectorControls via JSDoc
* Squash/silence the rest of the type errors.
Required for #37945 
* No regressions at `/gutenboarding`
* `npm run typecheck -- --project client/landing/gutenboarding` - no errors 🎉
=> Gutenboarding: Squash type errors

packages/composite-checkout-wpcom/src/components/button.js, packages/composite-checkout/src/components/checkout-modal.js
This PR fixes a colour issue with the delete button icon and makes a minor tweak to the line-height of the modal title. 
Before:
After:
* Get calypso running locally or use the calypso live link.
* Make your way to checkout and then add this query string at the end `?flags=composite-checkout-wpcom`
* switch to the paypal payment method (verify that the paypal logo looks disabled)
* Continue through to the review step and hover over the trashcan icon to confirm that it turns red.
=> Composite checkout: fix delete button opacity

client/my-sites/themes/themes-selection.jsx
* Restricts changes from last weeks PR #38419 to only take place on empty query.
This empty query check makes sense in the context that the pagination bug we were fixing is primarily triggered through opening "More Themes".  Since the showcase is open by default when query params are present, we do not need this 'fix' to run when that is the case.
* Run this PR.
* Navigate to themes showcase.
* Open the "more themes" section, verify pagination works as expected on scrolling.
* Search a specific theme name like 'Maywood'
* Click to view info.
* Click "back" to return to the showcase.
* Verify the showcase is not blinking and acting 'crazy'
Fixes #38478
=> Themes Showcase - gate incrementPage pagination 'fix' behind empty query requirement

client/me/billing-history/style.scss
* Remove the `BlinkMacSystemFont` from the list of fonts on the body when printing. 
Using Chrome browser:
1. Go to Me > Manage Purchases > Billing History
2. Pick a recent purchase and click on “View Receipt”
3. Click on 'Print Receipt'.  Without this patch you should see strange characters all over the page, with the fix applied you should see the nicely formatted receipt.
Fixes #37549
=> Purchases: Add print media query for receipts

client/my-sites/sidebar/index.jsx
Based on feedback from @artpi [this badge is no longer needed](https://github.com/Automattic/wp-calypso/pull/38440#issuecomment-566457633).
**Before**
**After**
Fixes #38293
Removes the need for #38440 (cc @Aurorum)
=> Remove "New" badge from Earn link in sidebar

client/my-sites/site-settings/form-writing.jsx, client/my-sites/site-settings/style.scss, client/my-sites/site-settings/theme-enhancements.jsx
Fixes #36404
Matching Jetpack PR: 
https://github.com/Automattic/jetpack/pull/14101
* Internal references:
- p1HpG7-84F-p2
- p6TEKc-3iM-p2
- p6TEKc-3jj-p2
- p6TEKc-3l7-p2
The Mobile theme was developed 8 years ago, back when responsive themes weren't a thing. It isn't as useful today, and can even be harmful when one enables it on their site without realizing the consequences, as outlined in https://github.com/Automattic/jetpack/issues/7602.
*****
This PR comes as a first step to deprecate the Mobile Theme feature. We'll start by greying out Mobile Theme Settings from the Writing Settings UI when the feature is not active. Folks that still use the feature can access its settings and disable it. Folks who do not use it cannot turn it on via the UI.
In addition to those changes, we'll …
=> Writing Settings: disable Mobile Theme UI when feature isn't active

packages/composite-checkout/src/components/checkout.js
This PR adds a url hash for each step in the checkout form (eg: `/checkout/#step2`). When the page loads or when this hash changes, the form will display the appropriate step. This allows for the browser's back button to navigate between steps.
**Question for reviewers:** when might we want to override this behavior? If you reload the form, all the fields will be empty and the steps will therefore be invalid. Should we still remain on the current step? Perhaps we should only allow jumping to a step if all the previous steps are marked as complete?
- Visit the demo site and begin completing the form.
- When you get to step 3, press the back button in your browser. Verify that you are returned to step 2.
- Press the forward button in the browser and …
=> composite-checkout: Sync url to step number

client/my-sites/checkout/checkout/composite-checkout.js, packages/composite-checkout-wpcom/src/hooks/use-shopping-cart.ts, packages/composite-checkout/README.md, packages/composite-checkout/demo/index.js, packages/composite-checkout/src/components/checkout-provider.js, packages/composite-checkout/src/components/checkout.js, packages/composite-checkout/src/components/loading-content.js, packages/composite-checkout/src/components/payment-request-button.js, packages/composite-checkout/src/lib/form-status.js, packages/composite-checkout/src/lib/payment-methods/paypal.js, packages/composite-checkout/src/lib/payment-methods/stripe-credit-card-fields.js
This PR adds a new state to the checkout form which keeps the current "form status", which is one of `loading`, `ready`, or `submitting`. That status is then used to replace the form with a loading indicator, to display the form normally, or to display a disabled form that reads "Processing..." respectively.
Note: Right now the loading state looks quite poor. This will be replaced in a future PR (cc @fditrapani).
- Visit the demo form and verify that it shows a loading state for 1.5 seconds before displaying the form.
- Choose the credit card payment method. Fill out the form using the Stripe test card `4242 4242 4242 4242`. Press the "Pay" button. Verify that the button becomes disabled and now reads "Processing".
- Reload the form and repeat the …
=> composite-checkout: Add form status

client/my-sites/plan-features/header.jsx, client/my-sites/plan-features/test/header.jsx
* As described in https://github.com/Automattic/wp-calypso/issues/36712#issuecomment-544423842, the "Your Plan" badge appears in the plans step of the signup flow if the user goes through "Add new site" while another site on his account is on a paid plan. This PR removes that label. 
* Technical details:
`renderPlansHeader()` is used to render /plans page in Calypso.
`renderPlansHeaderNoTabs()` is used to render the plans step in signup flow /start/plans
In this PR, we remove the "Your Plan" badge rendering line from `renderPlansHeaderNoTabs()`. 
* Go through signup flow and verify that in the plans step, "Popular" badge is shown. 
* On an existing site on a paid plan, click "Add new site" and go through the signup flow. Verify that "Your Plan" badge does not show in the plans step of the …
=> Do not show "Your Plan" badge in the plans step of signup flow

client/components/data/query-gsuite-users/index.jsx
Summary
-
This is a fix for the [Email](https://wordpress.com/emails) page, where there is an infinite set of GET API requests made to the [/google-apps](/sites/:site-id/google-apps) endpoint to fetch the set of available G Suite users for the site.
Additionally Redux's `connect` is ditched in favour of Redux's hooks that work with functional components. 
* Startup your dev server i.e. http://calypso.localhost:3000
* Ensure that you have eligible G Suite domains
- At least one domain with users
- At least one domain without users
* Nagivate to the `Email` page: http://calypso.localhost:3000/email
* Bring up/activate your browser's **Dev console** so that you can observe console logs
* Enable debug for requests  by running : `localStorage.setItem('debug','wpcom-proxy-request')`. You may …
=> G Suite: Fix infinite API calls made when account users are requested

client/components/social-buttons/google.js
* This adds an onFocus and onBlur event to the social login button for accessibility reasons.
* The easiest way to test this is to break social login by changing the client ID on line 102 (to anything)
* Then when you hover over, or focus on, the button, the error message should show
* When you take your mouse off the button, or tab away from it, the error message should hide.
This came up in https://github.com/Automattic/wp-calypso/pull/33155 but I wanted to fix it in a different PR, to keep it easier to review
=> Fix accessiblity for the social log in button

packages/composite-checkout-wpcom/src/components/coupon.js, packages/composite-checkout-wpcom/src/components/wp-checkout-order-summary.js
This PR adds events to measure user coupon field interactions. 
* Get calypso running locally.
* Add a product to the cart and go to checkout. 
* Add `?flags=composite-checkout-wpcom` to the checkout URL.
* Click on the "Add a coupon" button to make sure the coupon field displays. 
* Enter "Add" and click apply to make sure the form submits. (The field should disappear after you submit the form)
=> Composite checkout: Add coupon field events

packages/composite-checkout/src/lib/payment-methods/stripe-credit-card-fields.js
This PR adds events to measure stripe errors.
* Get Calypso running locally.
* Add a product to the cart and go to checkout. 
* Add `?flags=composite-checkout-wpcom` to the checkout URL.
* Add data to the stripe checkout to ensure nothing is broken.
=> Composite checkout: Add events for tracking stripe errors

client/components/domains/register-domain-step/index.jsx, client/lib/abtest/active-tests.js, client/signup/steps/domains/index.jsx
* This PR introduces a new Domain step test. You can find more information here p8Eqe3-ZD
* If you are assigned to the `control` group of the `domainStepCopyUpdates` test, it means you're in the Holdout group, so you should not see the `domainStepCopyUpdates` from https://github.com/Automattic/wp-calypso/pull/37661 or this PR's `domainStepMoveParagraph` test either. Verify the following:
- The domain step UI and copy remains the same as before (no copy updates, no explanation paragraph).
- Complete signup and check the launch flow steps - they should remain unchanged
* If you are assigned to the `variantShowUpdates` group of the `domainStepCopyUpdates` test, you're eligible for this PR's `domainStepMoveParagraph` test.
- If you're assigned to the …
=> Adding Domain move paragraph test

client/blocks/product-selector/index.jsx, client/components/product-expiration/README.md, client/components/product-expiration/docs/example.tsx, client/components/product-expiration/index.tsx, client/components/product-expiration/test/index.js, client/devdocs/design/index.jsx, client/lib/purchases/assembler.js, client/my-sites/plans/current-plan/my-plan-card/index.jsx, client/my-sites/plans/current-plan/purchases-listing.jsx, client/state/purchases/test/selectors.js
* Centralizes display of product expiration in component
* Buy JP Backup for a site
* Visit the site plan page and view product expiration
* Click on Plans and view product expiration
* Adjust product data to be refundable and watch text change
Should show purchase date when still refundable, and expiration otherwise.
Fixes 1143508703416848-as-1151698080758463
My Plan (expires)
My Plan (still refundable)
Plans (expires)
Plans (still refundable)
=> Creates Product Expiration component

client/my-sites/customer-home/style.scss
* When you complete the checklist *after* site launch by skipping the mobile apps download step, you get an inline notice about having completed the checklist. The placement of this notice was broken when I shipped #38121 
* This PR aligns that notice correctly with the rest of the grid.
**Before**
**After**
* Create a new site with a new user account from `/start`
* Confirm your email address and launch your site
* Complete all other checklist tasks *except* the mobile apps download step
* "Skip" the mobile apps download
* Note the notice that appears at the top of the page; it should look like the After step above.
=> Customer Home: Fix positioning of checklist complete notice

client/me/concierge/shared/appointment-info.js
* A couple of strings are missing the translate() call, so this PR just wraps those strings to be translatable.
Screenshots:
* Book a Quick Start session and visit your session dashboard at /me/concierge/{SITE_SLUG}
* Verify that the dashboard renders in en locale, and in non-en locales with appropriate translations of all strings.
=> Quick Start session dashboard: Wrap strings in translate()

client/landing/gutenboarding/gutenboard.tsx
Leftover from #38282. Obsolete as of #38456.
Verify that Gutenboarding still works.
=> Gutenboarding: Remove stray style import

client/my-sites/checkout/checkout/index.jsx
* Show the concierge upsell nudge if a redirect payment type such as Giropay was used.
* In https://github.com/Automattic/wp-calypso/pull/37349, we added a condition to check for failed_purchases in `stepResult` - this was to ensure that if payment failed, then we don't assign the user to the plan bump A/B test. However, the conditional prevented concierge upsell nudges from being shown. This PR fixes the issue.
* Verify that the Test Plan from https://github.com/Automattic/wp-calypso/pull/37349 works.
* Go through signup flow while you are proxied through Europe. Pay for a Personal plan through Giropay and verify that you see the Concierge nudge. Also verify that typing `localstorage.ABTests` in your browser console should not show the `showPlanUpsellConcierge ` test in the list of …
=> Concierge upsell: Show for redirect payment types

client/components/domains/domain-product-price/index.jsx, client/components/domains/domain-registration-suggestion/index.jsx, client/components/domains/free-domain-explainer/index.jsx, client/components/domains/register-domain-step/index.jsx, client/lib/abtest/active-tests.js, client/lib/signup/site-type.js, client/signup/steps/domains/index.jsx
* The domain step test introduced in https://github.com/Automattic/wp-calypso/pull/37661 is declared a winner, so this PR submits all the english language strings for translation. 
* The A/B test is opened to all locales except `en`.
Screenshots:
* Follow the test plan in https://github.com/Automattic/wp-calypso/pull/37661
* Verify that all strings introduced as part of the domain step test appear translated(go through the signup flow in any non-en locale while you are assigned to the variation). 
* If you go through the signup flow in `en` you should not get assigned to the `nonEnglishDomainStepCopyUpdates` test.
=> Domain step test: Wrap all strings in translate()

apps/wpcom-block-editor/src/calypso/features/iframe-bridge-server.js, apps/wpcom-block-editor/src/calypso/features/tinymce.js, apps/wpcom-block-editor/src/utils.js, apps/wpcom-block-editor/src/wpcom/features/fix-block-invalidation-errors.js
Seems we cannot rely on `getCurrentPost` for determining if the editor has been initialized and blocks has been added, so the convert to blocks dialog was not being displayed when a post has been created with the classic editor 
This PR replaces that check in favor of `isCleanNewPost` + `getBlocks` which apparently is more reliable.
* Apply D36950-code and sandbox `widgets.wp.com`.
* Switch to the classic editor.
* Publish a post.
* Switch to the block editor.
* Make sure the convert to blocks dialog is displayed when loading the previous post.
* Verify invalid blocks are still autofixed on editor loaded (https://github.com/Automattic/wp-calypso/pull/38397) 
Fixes #38489
=> Wait for blocks when triggering the conversion prompt

client/landing/gutenboarding/onboarding-block/style.scss, client/landing/gutenboarding/onboarding-block/vertical-background.tsx
A small visual tweak to soften an abrupt background color change.
* Visit `/gutenboarding` and pick a vertical.
=> Gutenboarding: Transition bg color

client/assets/stylesheets/_main.scss, client/assets/stylesheets/gutenboarding.scss, client/assets/stylesheets/shared/_loading.scss, client/assets/stylesheets/style.scss
* Copied `.wpcom-site__logo` styles from Calypso main stylesheet to shared location
* Hide `.masterbar` which is shown only during the loading stage
* Apply different color to loading logo in Gutenboarding than in elsewhere
**Before**
**After**
- Open `/gutenboarding` and observe different loading logo color than rest of Calypso and no masterbar visible while loading 
- Ensure rest of onboarding flow works just fine
- Open `/` and ensure everything stays the same
=> Gutenboarding: improve loading  styles

client/signup/steps/domains/index.jsx
* For users who go through the plan specific flows - `/start/personal`, `/start/premium`, `/start/business` and `/start/ecommerce` - we will exclude these users from the domain step test that was introduced with https://github.com/Automattic/wp-calypso/pull/37661.
* In `en` locale, go through the following flows and verify that you don't get assigned to the `domainStepCopyUpdates` test(by checking `localstorage.ABTests;` in your browser console when you're in the domain step):
/start/personal 
/start/premium
/start/business
/start/ecommerce
* In `en` locale, go through the main signup flow /start and verify things work normally i.e you should get assigned to the `domainStepCopyUpdates` test.
Fixes https://github.com/Automattic/wp-calypso/issues/38495
=> Fix: Domain step test should exclude users who are going through the /start/{PLAN} flows

client/lib/abtest/active-tests.js, client/lib/domains/suggestions/index.js, client/signup/steps/domains/index.jsx
We want to test how well domain suggestions compare when we pass hints to the suggestion provider vs. when not doing that. In order to do that I've introduced three new vendor variants - `variation3_front`, `variation4_front` and `variation5_front` and added an abtest called `domainSuggestionsWithHints` that is active only in NUX.
depends on: D36842-code
see: p99Zz8-Ps-p2
* introduce a new abtest
* start from `/start`, then check if using different variations will pass different `vendor` down the `/domains/suggestions` REST API endpoint.
=> Domains: Add abtest for domain suggestions using hints vs. not using hints

client/my-sites/checkout/checkout/composite-checkout.js, packages/composite-checkout-wpcom/src/hooks/wpcom-store.js
This PR adds event tracking every time an error is thrown on a billing detail field. 
* Get Calypso running locally. 
* Add a product to your cart and make your way to checkout. 
* Add the following query string to your url: `?flags=composite-checkout-wpcom`
* Enable debugging mode by typing this in your DevTools console and refreshing the screen `localStorage.setItem('debug', 'calypso:composite-checkout')`.
* Pick a payment method
* Enter something into one of the billing fields and then remove it. 
* You should see an event pop up in the console called `a8c_checkout_error` with the type `Field error` in the payload.
=> Composite checkout: add events for billing field errors

client/me/concierge/shared/closure-notice.js, client/me/concierge/shared/primary-header.js, client/me/help/help-contact/index.jsx, client/me/help/live-chat-closure-notice/index.jsx
* Follow up to https://github.com/Automattic/wp-calypso/pull/38448, before the closure date, the live chat interface's header says that live chat is closed, when in fact it should say that the closure date is in the future.
* WIP
Fixes #
=> Live chat closure: Header to indicate the upcoming closure

client/components/marketing-survey/cancel-purchase-form/index.jsx, client/components/marketing-survey/cancel-purchase-form/steps-for-product-and-survey.js
The Plan Downgrades are embedded in the marketing cancellation survey. There are two flows that trigger the same survey and they don't use the same code or the same approach. The remove
flow doesn't have the downgradeClick callback available.
I'm disabling the downgrades in that flow. Fixing it would require a significant refactoring that I may be able to do during the next planned iteration of downgrades and seems to be a relatively low priority given the difficulty to reproduce the error.
In order to see the remove plan button, a user has to:
- Have an expiring Premium subscription
- The auto-renew needs to be turned off
1. With the Store Sandbox enabled, buy a Premium plan
2. With Store Admin, change the expiration to be in the next 2-3 days and turn off the Auto-renew
3. Hardcode on …
=> Disable Plan Downgrades in Remove Plan Flow

client/blocks/eligibility-warnings/index.tsx
Tracking was slightly off in https://github.com/Automattic/wp-calypso/pull/38277 - clicking on Upgrade CTA would always record themes-related event. This PR makes it context-dependent (as it used to be).
On a free public site, go to each of these pages, click "Upgrade and continue" button, and confirm that `calypso_banner_cta_click` tracks event was logged with corresponding `cta_name`:
* `/plugins/upload/` - `calypso-plugin-eligibility-upgrade-nudge`
* `/themes/upload/` - `calypso-theme-eligibility-upgrade-nudge`
* `/hosting-config/activate/` - `calypso-hosting-eligibility-upgrade-nudge`
=> Record contextual cta_name when user wants to upgrade

client/blocks/eligibility-warnings/hold-list.tsx
This changes a single word in a heading copy for Eligibility warnings component. It should say "themes" and now it says "plugins"
* On a free, public site go to `/themes/upload/`, confirm the header says `To install themes you'll need to:`
=> Change word "plugins" to "themes" in heading copy

client/login/magic-login/handle-emailed-link-form.jsx
* Update the CTA button label in `HandleEmailedLinkForm` to say `Continue` instead of `Finish Login` — p7DVsv-71C-p2#comment-23545
The button below previously said "Finish Login"
Testing this is a little bit fiddly, but can be done with the following:
* Go to `http://calypso.localhost:3000/log-in/link` to request a log in link
* Open up your email and copy the URL for the `Log in to WordPress.com` CTA from your login email.
* From that URL, just take the string following `redirect_to=` and before you get to the `&sr=`. Take that string, and in a JavaScript console run `unescape( 'put-the-string-here' );`
* In the unescaped string, replace `https://wordpress.com/` with `http://calypso.localhost:3000/` and pop that into your browser window, and you should be taken to a page beginning with …
=> Update CTA button label in HandleEmailedLinkForm to say 'Continue'

client/landing/gutenboarding/onboarding-block/design-selector/design-card.tsx
* Rename local component variable name from `DeisgnCard` to `DesignCard`
* No behavior changes expected
=> DesignCard: Fix typo in local component name

client/landing/gutenboarding/onboarding-block/design-selector/style.scss, client/landing/gutenboarding/onboarding-block/edit.tsx, client/landing/gutenboarding/onboarding-block/style.scss, client/landing/gutenboarding/onboarding-block/vertical-background.tsx
Vertical background was only shown on acquire intent step. Apply the background to the design selector as well.
- Better isolation of acquire-intent and design-selector components
* Visit `/gutenboarding`
* No regressions
* Vertical background persists and looks appropriate on design selection
=> Gutenboarding: persist vertical background

client/my-sites/checkout/checkout/secure-payment-form.jsx
* A failed purchase of a Business or eCommerce plan still sets the site "public".
* Checking Tracks trends for `calypso_cart_unrecognized_payment_method` shows a large number of these everyday. Similarly, we have a large number of `calypso_checkout_payment_error` events too. So, it's possible that a number of these users end up with a public site even though they didn't purchase a biz/eCom site due to a failed purchase.
**Note for translators**
The new string to be translated is an error notification that looks like this:
* Go through the signup flow and add a Business plan to cart
* Add an invalid credit card number. I used `4716965652794729 `
* This will fire a `calypso_checkout_payment_error` Tracks event. 
* On another tab, open http://calypso.localhost:3000/ and verify that your new …
=> Fix: Set site Public only on successful purchase

client/landing/gutenboarding/onboarding-block/edit.tsx, client/landing/gutenboarding/onboarding-block/vertical-background.tsx
In #38577, the `VerticalBackground` component was changed to fetch the user's selected site vertical from the `automattic/onboard` store, rather than using the `id` prop passed to it. However, the `id` prop was still being passed at `VerticalBackground`'s only callsite. This went undetected since `id` also wasn't removed from `VerticalBackground`'s props interface definition.
This PR fixes both oversights.
Documented here: https://github.com/Automattic/wp-calypso/pull/38577/files#r361384432
Verify that Gutenboarding still works -- particularly the vertical background.
=> Gutenboarding: Don't pass id prop to VerticalBackground

client/me/concierge/shared/upsell.js
* When a user is not qualified to book an appointment - either because they used up their concierge session, or on an ineligible plan - we show an upsell page as shown in the image below.
This PR adds a Tracks event for that page.
* Login to an account that does not have a purchased or included concierge session.
* In your browser console, type: `localStorage.setItem('debug', 'calypso:analytics:tracks');`
* Navigate to `/me/concierge` and you should see the upsell page as shown in the screenshot above
* Check in your browser console that the Tracks event for this page is getting fired `calypso_concierge_book_upsell_step `
=> Concierge: Add tracks event for the Business plan upsell page view

client/landing/gutenboarding/components/domain-picker-button/index.tsx, client/landing/gutenboarding/components/domain-picker-button/style.scss, client/landing/gutenboarding/components/domain-picker/index.ts, client/landing/gutenboarding/components/domain-picker/index.tsx, client/landing/gutenboarding/components/domain-picker/list.tsx, client/landing/gutenboarding/components/domain-picker/style.scss, client/landing/gutenboarding/components/header/index.tsx, client/landing/gutenboarding/components/header/style.scss
Add loading state placheolders to the domain picker button and list.
Fixes #37848.
- Go to `http://calypso.localhost:3000/gutenboarding` (either in an incognito window, or run `localStorage.removeItem('WP_DATA')` in your browser console and reload)
- Enter a site vertical and title
- Observe the domain picker's behavior -- it should match the screencast ^
- Open the domain picker and search for a different domain
- Observe loading placeholders again
=> Gutenboarding: Add loading placeholders for domain picker

apps/full-site-editing/full-site-editing-plugin/starter-page-templates/page-template-modal/index.js
SPT is currently dispatching a `disableTips` action for disabling the welcome guide when the page layout selector is displayed, but `@wordpress/nux` will be deprecated and not imported by default in Gutenberg 7.2.0 (https://github.com/WordPress/gutenberg/pull/18981). That means that `disableTips` will not be available and will break the editor:
This PR handles that deprecation by hiding the welcome guide using `isFeatureActive( 'welcomeGuide' )`/`toggleFeature( 'welcomeGuide' )` (available since Gutenberg 7.1.0) and defers to `disableTips` only when the action is available (Gutenberg 7.0.0 and below).
* Generate a new build of the FSE plugin and upload it to a WP.org test site.
* Make sure you're running a custom build of the Gutenberg plugin based on master (so the NUX package is …
=> SPT: Handle NUX deprecation

client/my-sites/checkout/checkout/composite-checkout-container.js, packages/composite-checkout/README.md, packages/composite-checkout/demo/complete.html, packages/composite-checkout/demo/index.js, packages/composite-checkout/src/components/checkout-provider.js, packages/composite-checkout/src/components/checkout.js, packages/composite-checkout/src/components/payment-request-button.js, packages/composite-checkout/src/components/provisioning-content.js, packages/composite-checkout/src/lib/form-status.js, packages/composite-checkout/src/lib/line-items.js, packages/composite-checkout/src/lib/localize.js, packages/composite-checkout/src/lib/payment-methods/apple-pay.js, packages/composite-checkout/src/lib/payment-methods/paypal.js, packages/composite-checkout/src/lib/payment-methods/stripe-credit-card-fields.js, packages/composite-checkout/src/public-api.js
This PR modifies checkout to add an additional form status. Previously there was `loading`, `ready`, and `submitting`. This adds `complete`. It also removes `usePaymentComplete` from the public API. Instead of calling `onPaymentComplete` directly when a Payment Method object finishes, it now changes the form status to `complete`. This will automatically trigger the `onPaymentComplete` callback.
Using this technique, this PR redirects to a "complete" page when the purchase is successful.
It also modifies the "jump-to-step" behavior added in #38493 so that it only jumps when all previous steps are complete.
First test the demo.
- Complete the form using the Credit card payment method (use the Stripe test card of `4242424242424242`) and press "Pay".
- …
=> composite-checkout: Add redirect when payment complete

packages/composite-checkout/README.md, packages/composite-checkout/jest.config.js, packages/composite-checkout/src/components/checkout-provider.js, packages/composite-checkout/src/components/checkout.js, packages/composite-checkout/test/checkout-provider.js, packages/composite-checkout/test/checkout-step.js, packages/composite-checkout/test/checkout.js, packages/composite-checkout/test/join-classes.js, packages/composite-checkout/test/line-items.js, packages/composite-checkout/test/localize.js
This is a follow-up to #38525
The concepts of form status and the `onPaymentComplete` callback all
exist at the level of the `CheckoutProvider`. Since the `Checkout`
component could, by design, be substituted for a different form, it
shouldn't have to hold the responsibility of calling `onPaymentComplete`
when the form status becomes complete.
This PR moves that responsibility up to the `CheckoutProvider` instead.
In addition, this means that the `onPaymentComplete` callback never has
to leave the `CheckoutProvider` and becomes tied directly to the form
status.
This PR should not actually change any behavior, but the behavior should be tested regardless.
First test the demo.
- Complete the form using the Credit card payment method (use the Stripe …
=> composite-checkout: Move onPaymentComplete call to CheckoutProvider

packages/components/src/dialog/style.scss
* Fix dialog backdrop card style
Before:
After:
* Go to http://calypso.localhost:3000/plans/my-plan/:site?thank-you= where `:site` is a Jetpack site slug.
* Verify you can see the background overlay on the full screen as shown on the "After" screenshot
Note: this issue is not reproducible locally. If it looks unchanged after this change locally, it should be good.
Fixes #38617
=> Components: Fix dialog backdrop card style

client/my-sites/migrate/migrate-button.jsx, client/my-sites/migrate/section-migrate.jsx
* Only poll the endpoint for changes on the progress screen
* Set error locally when the API to start migration returns an error
* Create a `MigrateButton` component, which is busy until the result of the API request is shown
* Update the status from the API when the `targetSiteId` prop changes
* Reset local error when resetting migration
* Setup source and target sites using the instructions found on pbkcP4-6z-p2
* Open your network inspector
* Start a migration from `/migrate`, and verify that before pressing "Migrate site" the endpoint for migration status isn't polled. It should be hit once, initially, when the component loads, and then again every 10 seconds after …
=> Migration: Move polling to progress page; update error handling

client/lib/abtest/active-tests.js, client/reader/sidebar/reader-sidebar-nudges/index.jsx
* Add an a/b test for the reader sidebar upsell nudge. English speaking US users are not included in the test though they can see the nudge.
* You should be a user who has only one free plan dotcom site.
* Go to the Reader page.
1. If you are an English US user, you should be able to see the nudge in the sidebar but you should not be assigned to any group of the `readerFreeToPaidPlanNudge` test.
2. If you are a non EN user or non US user, you should be assigned to a group of the `readerFreeToPaidPlanNudge` test. If you are in `display` group, the nudge should appear in the sidebar.
3. If you have two sites or more, the nudge should not appear.
4. If the only site you have is on a paid plan, the nudge should not appear.
_Note_: In dev env, you can change your country as follows.
```
// in …
```
=> Marketing: A/B test reader sidebar upsell nudge

apps/full-site-editing/full-site-editing-plugin/full-site-editing-plugin.php, apps/full-site-editing/full-site-editing-plugin/readme.txt, apps/full-site-editing/package-lock.json, apps/full-site-editing/package.json
* Bump FSE to 0.18.2, which introduces the changes added in https://github.com/Automattic/wp-calypso/pull/38611.
Copypasting from https://github.com/Automattic/wp-calypso/pull/38611:
* Generate a new build of the FSE plugin and upload it to a WP.org test site.
* Make sure you're running a custom build of the Gutenberg plugin based on master (so the NUX package is deprecated).
* Clear your browser's persisted state by running `localStorage.clear()` in DevTools.
* Go to Pages > Add New.
* Verify the page layout selector is displayed without the welcome guide.
* Deactivate the Gutenberg plugin (so WP loads the block editor bundled in core where the NUX package is not deprecated yet).
* Clear your browser's persisted state by running `localStorage.clear()` in DevTools.
* Go to Pages > Add …
=> Bump FSE to 0.18.2

client/lib/abtest/active-tests.js, client/my-sites/checkout/checkout/index.jsx
* Following the success of the plan bump test introduced in https://github.com/Automattic/wp-calypso/pull/37349 and https://github.com/Automattic/wp-calypso/pull/36655 which tests an offer to upgrade to Premium against an offer to buy a concierge session for users who purchase a Personal plan, we have decided to launch the variant as control.
* For more context, check the discussion in p8Eqe3-EW-p2#comment-2984.
**Scenario 1** _(Test that the plan bump offer is shown for Personal plan purchase)_
* Signup for a new account from http://calypso.localhost:3000/start.
* Add a Personal plan to cart and complete the purchase
* Verify that you are shown the premium upgrade upsell.
* Clicking the `No thanks ...` button should take you to the checklist page.
* Clicking the `Yes, I'd love to try …
=> Plan bump test: Launch the variant as control

client/blocks/eligibility-warnings/hold-list.tsx
There were a couple of places where we were attempting to render the return value of `hasLocalizedText` instead of `translate`, so the messages were not being displayed.
|Before|After|
|---|---|
|<img width="776" alt="screen_shot_2020-01-02_at_2 28 10_pm" src="https://user-images.githubusercontent.com/1587282/71747795-9c19ad80-2e3e-11ea-8c7b-30cdc1b42413.png">|<img width="757" alt="Screen Shot 2020-01-03 at 3 22 33 PM" src="https://user-images.githubusercontent.com/1587282/71747802-a20f8e80-2e3e-11ea-9ab9-09b216531b6c.png">|
It's also worth noting that this section is in the process of a redesign, so this is not its final form.  Also, these strings should be fully localized by now, so I'll follow up with a PR to pull out the conditionals, but wanted to get this in to fix the broken …
=> Eligibility Warnings: Fix a couple of conditional strings in the "hold list"

client/assets/stylesheets/shared/functions/_z-index.scss, client/components/checklist/style.scss
* This PR brings back a z-index value for the icons on the checklist. This ensures the icons are in front of the vertical line.
* This was introduced in https://github.com/Automattic/wp-calypso/pull/34130 and later removed in https://github.com/Automattic/wp-calypso/pull/37809 in what seems to be a regression? cc @sixhours
* Create a [new JN site](https://jurassic.ninja/create/).
* Connect the site and purchase a plan.
* When dropped on the checklist, ensure all icons are in front of the vertical line.
Fixes #38643
=> Checklist: make sure icons are in front of vertical line

client/my-sites/migrate/migrate-button.jsx, client/my-sites/migrate/section-migrate.jsx, client/my-sites/migrate/section-migrate.scss
This PR is based on https://github.com/Automattic/wp-calypso/pull/38523 – we should merge that one first.
* Adds illustration and some formatting tweaks to error view.
* Changes "migrate" to "import" in texts displayed to the user in line with our decision to present migration as a form of import.
* Check out this pull request and run Calypso locally, or use calypso.live.
* Viewing calypso.localhost:3000/migrate/, you should see a SiteSelector component allowing you to choose a site to migrate a Jetpack site into.
* **Select a Simple …
=> Site migration: error view

client/my-sites/migrate/migrate-button.jsx, client/my-sites/migrate/section-migrate.jsx
* Shows a confirm modal when the user clicks the "Start migration" button. 
* I have made the modal's cancel button simply dismiss the modal for now: it's the same behaviour as clicking outside the modal, and simpler than redirecting to some other page.
* The confirm component doesn't support a heading, so I've gone with a single block of text.
* Check out this pull request and run Calypso locally.
* Viewing calypso.localhost:3000/migrate/, you should see a SiteSelector component allowing you to choose a site to migrate a Jetpack site …
=> Site migration: add confirm before starting migration

client/my-sites/checkout/checkout/composite-checkout-container.js, packages/composite-checkout-wpcom/src/components/wp-checkout.js, packages/composite-checkout-wpcom/src/components/wp-contact-form.js, packages/composite-checkout-wpcom/src/hooks/has-domains.js, packages/composite-checkout-wpcom/src/hooks/wpcom-store.js
The design for the Calypso checkout form contact step when a domain was in the cart included a checkbox which allowed displaying a separate set of fields for domain details. However, the contact fields are not shown at all if there is no domain, so the contact fields _are_ the domain details.
This PR removes the checkbox and the unnecessary fields.
- Add a plan (not a domain) to your cart.
- Verify that the contact details step (step 2) displays the country, postal code, and phone number fields.
- Verify that typing in the fields works and that the "Continue" button is only enabled when the fields are all filled.
- Go back and add a domain to your cart.
- Verify that the contact …
=> composite-checkout: Remove extraneous domain fields

client/lib/i18n-utils/switch-locale.js, client/lib/i18n-utils/utils.js, client/lib/url/index.ts, client/lib/url/url-parts.ts
Reverts Automattic/wp-calypso#38560 until we can address #38668.
To test:
- Go to https://wordpress.com/log-in/pt-br
- Ensure the forgot password link ("Perdeu a senha?") URL does not include the non-sensical port number of 0 (https://br.wordpress.com:0/wp-login.php?action=lostpassword)
=> Revert "Remove node's url from lib/i18n-utils."

client/my-sites/checkout/checkout/composite-checkout-container.js, packages/composite-checkout/README.md, packages/composite-checkout/src/components/checkout-payment-methods.js, packages/composite-checkout/src/lib/payment-methods/existing-credit-card.js, packages/composite-checkout/src/lib/payment-methods/index.js, packages/composite-checkout/src/public-api.js
This PR adds payment methods for existing credit cards to composite checkout.
When the checkout form in Calypso is first loaded, it fetches the existing cards from the REST API and then creates a new Payment Method Object for each one using the new `createExistingCardMethod()` function that's part of composite-checkout's public API.
The payment method label and inactive content are not currently styled, but that can come in a later PR.
- Using calypso master, add a saved credit card to your account. It can be a Stripe test card, eg: `4242 4242 4242 4242`.
- Verify that you see a payment method in the list for your existing card.
- Select the existing …
=> composite-checkout: Add existing card payment method

client/my-sites/checkout/checkout/composite-checkout-container.js, packages/composite-checkout/README.md, packages/composite-checkout/demo/index.js, packages/composite-checkout/src/lib/payment-methods/stripe-credit-card-fields.js
The `createStripeMethod()` factory function which creates the Stripe Credit Card payment method requires certain callback functions which it uses to fill in the data needed to submit to the endpoint. However, much of that data is dependent on a WPCOM host, like site id and domain details.
Since the host page is already the one gathering that data, this PR removes those callbacks from the payment method and injects them when the host submits the data instead. This will make the payment method more flexible so it will work across hosts more easily that don't have information like site id.
We cannot easily do the same for the country, postal code, phone number, and subdivision code because they must also be submitted to Stripe directly when creating the Stripe Payment Method.
- Run `npm run …
=> composite-checkout: Remove WPCOM-specific code from stripe payment method

client/components/site-selector/index.jsx, client/me/account-close/main.jsx, client/me/account-close/style.scss, client/state/selectors/get-account-closure-sites.js, client/state/selectors/test/get-account-closure-sites.js
This lists all sites that get deleted when an account is closed (I believe it's all sites except Jetpack ones? Please correct me if I'm wrong!). There's also a dropdown to hide them, just in case someone has a lot of sites.
Visit `/me/account/close` on an account that can automatically be closed, and verify that the sites display and the toggle works.
**Where no sites will be deleted:**
**Where sites will be deleted:**
cc @bluefuton 
Fixes #24939
=> Account Closure: List Sites to be Deleted

client/lib/human-date/test/index.js
I was just running the test suite for an unrelated reason and noticed this test fails for me at 6pm Pacific, which is the next day in UTC. Adding `moment` and running the `Date()` through `moment.utc()` does fix this issue, but I'm not sure if this exposes an underlying problem with `human-date` (AKA, should `human-date` be loading up a passed Date with `moment.utc()` rather than simply `moment()`, which assumes local time)?
This test was added in #37337 along with some other changes to `moment`.
* Be in a timezone where it's a different day in UTC than local time
* Run `npm run test-client client/lib/human-date/` and verify it all passes
* Be in a timezone where it's the same day in UTC
* Ditto
=> lib/human-date: fix tests if your current timezone is a different date than UTC

client/my-sites/plans-features-main/index.jsx
* Move new Backups product prompt below plans grid
* Connect a Jetpack site that is eligible for single-purpose products
* In the signup flow, on the plans page, observe that the plans "grid" with Jetpack's bundles is above the Backups product prompt.
Before:
After:
* On a Jetpack site that is eligible to install Jetpack backups, go to /plans/(site-domain)
* Observe that plans grid order is above single purpose Backups product
Before:
After:
=> Move single purpose products below plans grid for now

client/landing/gutenboarding/onboarding-block/design-selector/index.tsx, client/landing/gutenboarding/onboarding-block/vertical-background.tsx, client/landing/gutenboarding/onboarding-block/vertical-select/index.tsx, client/landing/gutenboarding/stores/onboard/types.ts
Allow the user to specify their own (free-form) vertical, rather than restricting them to the list.
This also allows us to persist a free-form vertical when the input loses focus.
Fixes #37854.
- Go to `http://calypso.localhost:3000/gutenboarding`
- Verify that if you enter the free-form vertical (but don't select it from the suggestions list) and then focus on a different control, the free-form vertical will still be present in the vertical field.
- Verify that you can enter a free-form vertical, and that you can select it from the list.
- We need to change the endpoint to return a list of templates if no vertical is specified.
- We might want to debounce, so the (costly) suggestions search isn't run on every keystroke.
- Theoretically, we could get rid of `inputValue` component state …
=> Gutenboarding: Allow user-specified vertical

apps/full-site-editing/bin/sync-blog-posts-block.sh, apps/full-site-editing/full-site-editing-plugin/blog-posts-block/README.md
This PR adds a `path` mode to the FSE bin script in order to sync NHA with BPB locally.
You need the [Newspack Blocks repository](https://github.com/Automattic/newspack-blocks) cloned locally.
1) Edit some files of NHA in your local repository
2) Run the following code in order to sync FSE with these changes. For instance, in my local env, I run
```cli
> npm run sync:blog-posts-block --path=/Users/retrofox/lab/newspack-blocks/
```
Also, test with the `release` and `branch` mode in order to ensure it doesn't break the current behavior.
```
> npm run sync:blog-posts-block --branch=master
```
```
> npm run sync:blog-posts-block --release=1.0.0-alpha.18
```
=> BPB: Add `path` mode in bin sync script

client/lib/i18n-utils/switch-locale.js, client/lib/i18n-utils/utils.js, client/lib/url/index.ts, client/lib/url/test/url-parts.js, client/lib/url/url-parts.ts
Retry of #38560 with a workaround for the following Safari bug (see #38668).
```js
result = new URL( 'http://__domain__.invalid' );
result.port = '';
console.log( result.port )
```
Safari 13.0.4 returns: `"0"`, all other browsers return `""`.
This is an invalid implementation in Safari (almost 6 year old [Webkit bug 127958](https://bugs.webkit.org/show_bug.cgi?id=127958)) since [the spec says](https://url.spec.whatwg.org/#dom-url-port):
> If the given value is the empty string, then set context object's url's port to null.
The workaround it to simply only assign changed values, and not re-assign equal ones.
=> Retry: Remove node's url from lib/i18n-utils

client/my-sites/activity/activity-log-item/style.scss
* Fixes the actor column width, which prevents layout breakage in certain scenarios.
* Visit the Activity on a very active site, such as jetpack.com `/activity-log/jetpack.com`.
* Ensure the actor column looks tidy and consistent across the entire page.
=> Activity: fix actor column width

client/my-sites/customer-home/main.jsx
* The current purchase flow for a new site ends on Customer Home with the heading "Thank you for your purchase!" and "Next, use this quick list of setup tasks to get it ready to share."
* It's unclear what "it" refers to in this case, and "get your purchase ready to share" doesn't make sense. This PR updates it to "get your site ready to share".
**Before**
**After**
* Create a new site from `/start/`; use a free account.
* Land on Customer Home and note the heading and description.
* Create another new site from `/start`, this time with a paid plan. 
* Once again, land on Customer Home and check the heading and description for language tweaks.
=> Customer Home: Update language to be clearer after purchase.

client/my-sites/migrate/section-migrate.jsx, client/state/selectors/is-site-migration-in-progress.js
* Sets the `migrationStatus` state to `backing-up` as soon as the user clicks the "Start Migration" button, so the UI locks before we make a request to the migration status endpoint.
* Includes `done` among the statuses indicating that a migration is not in progress, so the UI unlocks at the end of a migration without the user needing to dismiss the success message.
* Check out this pull request and run Calypso locally, or run it on `calypso.live`.
* Viewing `calypso.localhost:3000/migrate/`, you should see a SiteSelector component …
=> Site migration: lock the UI immediately the migration starts

client/my-sites/checkout/checkout/composite-checkout-container.js, client/my-sites/checkout/checkout/test/composite-checkout.js, packages/composite-checkout/README.md, packages/composite-checkout/demo/index.js, packages/composite-checkout/src/lib/payment-methods/paypal.js
This hooks up PayPal transactions in much the same way that #38095 hooks up Stripe transactions.
First make sure you have a sandboxed PayPal account. It must be using an `@automattic.com` email address. [Instructions for creating one are here](https://developer.paypal.com/docs/classic/lifecycle/sandbox/accounts/#create-and-manage-sandbox-accounts).
- Run calypso with `ENABLE_FEATURES=composite-checkout-wpcom npm start`
- Choose the "PayPal" payment method and fill out the form.
- Press "Pay".
- Verify that you are redirected to a PayPal page. The URL should begin with `sandbox.paypal`.
- Log in to PayPal and pay for the purchase using your special sandboxed account.
- Verify that you are redirected to a "thank you" page …
=> composite-checkout: Hook up paypal transactions

packages/composite-checkout-wpcom/src/components/wp-checkout.js, packages/composite-checkout/README.md, packages/composite-checkout/src/components/checkout-payment-methods.js, packages/composite-checkout/src/components/checkout.js, packages/composite-checkout/src/lib/active-step.js, packages/composite-checkout/src/public-api.js, packages/composite-checkout/test/checkout.js
The `useActiveStep` custom React hook provides a component (within a step) with access to the currently active step object. There are also additional dynamic properties added to that object: the step's visible number and its index in the step array. This change adds a third dynamic property: the result of calling `isCompleteCallback` for that step. In addition, this change documents these dynamic properties and adds tests to prove they exist.
This PR also adds a new public API hook called `useIsStepComplete()` which will return true if the current step (not necessarily the active step) is complete as defined by that step's `isCompleteCallback` function.
Finally, this PR uses `useIsStepComplete` in the default payment method step and the Calypso contact step to change the step's title …
=> composite-checkout: Change step titles when step is complete

client/components/badge/style.scss
* Address this feedback https://github.com/Automattic/wp-calypso/issues/38661
* Vertically align text in badges.
* Inspect badges on the domain search page https://wordpress.com/start/domains-with-preview.
* Test in FF, safari, chrome, edge, and ie11
* Test on mobile sized screen
* The external height of the badge remains 18px+4px so it's unlikely to affect other pages
Fixes #38661
I used `line-height: 17px` because it best vertically centers the text in the badge (boxes are added to show spacing).
=> tweak vertical centering of text inside badges

client/my-sites/checkout/checkout/composite-checkout-container.js, packages/composite-checkout-wpcom/src/components/wp-contact-form.js
When attempting to purchase a domain with composite checkout, we weren't sending the domain name at all with the product ID, and the domain contact data was incorrect. This PR fixes both of those issues.
- Add a plan _and a domain_ to your cart. Choose a `.live` domain, since the store sandbox will simulate that purchase rather than actually purchasing it.
- Complete the checkout process using a credit card payment (new or existing).
- The State and Country fields will need to be in two-letter format (eg: `CA` and `US` rather than `California` and `United States`).
- The phone number will need to be in this format: `+1.6032223432`.
- Press the button to Pay.
- Verify that the …
=> composite-checkout: Allow purchasing domains

client/my-sites/current-site/notice.jsx
We no longer use the sidebar for this kind of notification.
=> Remove Jetpack plugin setup notice from sidebar

packages/composite-checkout/src/components/checkout.js
In #38493, we set up the checkout form to save the current step to the URL, pushing it on to the history so that the browser's back button allows going backwards through the steps. This works well, but it also changes the URL for the first step; the result of which is that when pressing the back button on the first step, we go back to the same form without the step in the URL, and the step is immediately added back in. To the user this may appear that you cannot go back from the first step to whatever page was before it.
In this PR, we avoid changing the URL for the first step, and if we go back to the first step, we treat it as the bare URL without a step number.
- Visit the demo site and verify that the URL does not contain a "step1" hash.
- …
=> composite-checkout: Don't save URL if step number is 1

packages/components/tsconfig.json, packages/composite-checkout-wpcom/src/mock/cart-endpoint.ts, packages/composite-checkout-wpcom/tsconfig.json, packages/data-stores/tsconfig.json
Automatically including type definitions can be problematic. Only
include imported types.
See tsconfig types documentation:
https://www.typescriptlang.org/docs/handbook/tsconfig-json.html#types-typeroots-and-types
```
> @automattic/data-stores@1.0.0-alpha.0 prepare …/packages/data-stores
> tsc --project ./tsconfig.json && tsc --project ./tsconfig-cjs.json
../../node_modules/@types/node/globals.d.ts(139,11): error TS2320: Interface 'NodeRequire' cannot simultaneously extend types 'Require' and 'RequireFunction'.
Named property 'cache' of types 'Require' and 'RequireFunction' are not identical.
../../node_modules/@types/node/globals.d.ts(139,11): error TS2320: Interface 'NodeRequire' cannot simultaneously extend types 'Require' and 'RequireFunction'.
Named property 'resolve' of types …
```
=> Data Stores: Disable automatic type inclusion

client/my-sites/checkout/checkout/composite-checkout-container.js, client/my-sites/checkout/checkout/composite-checkout.js, client/my-sites/checkout/checkout/test/composite-checkout.js, packages/composite-checkout/README.md, packages/composite-checkout/demo/index.js, packages/composite-checkout/src/components/checkout-provider.js, packages/composite-checkout/src/lib/payment-methods/existing-credit-card.js, packages/composite-checkout/src/lib/payment-methods/paypal.js, packages/composite-checkout/src/lib/payment-methods/stripe-credit-card-fields.js, packages/composite-checkout/src/public-api.js, packages/composite-checkout/test/checkout-provider.js, packages/composite-checkout/test/checkout.js
When the public API of `CheckoutProvider` was first designed, there was the idea that payment methods would require success/failure handlers, and because some payment methods might be redirects instead, we'd need similar success/failure redirect URLs. By providing them to the `CheckoutProvider`, they could be made available anywhere that might need them.
However, as the code has evolved, the success/failure handlers have been replaced by a single `onPaymentComplete` function and three notification functions. There's also the possibility that different redirect payment methods might want to have different, or dynamically generated, redirect URLs. Together, this makes storing redirect URLs in the `CheckoutProvider` seem to me to be the wrong abstraction.
Instead, if payment methods require …
=> composite-checkout: Remove global redirects

client/lib/i18n-utils/node.js, client/lib/i18n-utils/test/utils.js, client/lib/i18n-utils/utils.js
As an alternative implementation of #38565 and #38566, we add a utility function that developers can use to see whether (new) text can already be used for this language.
**Problem:** (see #38565)
* When user has locale set to default locale...
* ... and `hasTranslation` is called...
* ....it returns false, even though passing the input through `translate()` would return a valid result (the input itself)
New: Instead of modifying the i18n-calypso API, we try an user side implementation.
=> i18n-utils: Add translationExists function

client/components/language-picker/test/index.jsx
Add test confirming the language picker supports non latin charsets
`npm run test-client client/components/language-picker`
=> Add test confirming the language picker supports non latin charsets

client/blocks/inline-help/contextual-help.js, client/my-sites/hosting/controller.js, client/my-sites/hosting/main.js, client/my-sites/sites/index.jsx, client/state/selectors/can-site-view-atomic-hosting.js, config/desktop.json, config/development.json, config/horizon.json, config/production.json, config/stage.json, config/test.json, config/wpcalypso.json
* Removes all the client logic from `canSiteViewAtomicHosting` in favor of a `view_hosting` capability check added in D37177-code that indicates if the user can access the hosting section.
* Changes the redirect performed when loading invalid sites at `/hosting-config/:invalid-site` to the site selector (`/hosting-config`).
* Cleans up all the features flags since the section is now stable and visible in all envs.
* Apply D37177-code and sandbox the API.
* Verify the hosting section is not viewable for the following cases from both from the sidebar or visiting directly the `/hosting-config/:site` URL.:
* VIP sites.
* Jetpack sites.
* Sites with a `blocked-from-atomic-transfer` blog sticker.
* Non-admin users.
* Verify the hosting section is viewable for the rest of cases.
Fixes #38484
=> Hosting: Check new manage_hosting capability for access

client/lib/abtest/active-tests.js, client/lib/plans/index.js
* We launched a test for showing "Popular" badge on the Business plan in https://github.com/Automattic/wp-calypso/pull/38334. This test [has a dependency](https://github.com/Automattic/wp-calypso/blob/master/client/lib/plans/index.js#L467) on `nonEnglishDomainStepCopyUpdates` - only users in the control group of nonEnglishDomainStepCopyUpdates test are eligible for the popular badge test.
* This dependency was needed to reduce interference since both `nonEnglishDomainStepCopyUpdates` and `showBusinessPlanPopular` are running in parallel. Now that we have declared a winner for nonEnglishDomainStepCopyUpdates test and wrapping it up, we can use the new control group and remove dependency. 
* The test plan in https://github.com/Automattic/wp-calypso/pull/38334 should pass
=> Popular badge test: Remove test dependency on the nonEnglishDomainStepCopyUpdates test

client/lib/i18n-utils/utils.js
* In #38711 I introduced a warning at `npm start`, this removes it
```
WARNING in ./client/lib/i18n-utils/utils.js 89:40-54
"export 'hasTranslation' was not found in 'i18n-calypso'
```
* Run `npm start`, the warning should no longer appear.
=> i18n-utils: Address hasTranslation warning

client/my-sites/marketing/connections/services/eventbrite.js
This PR uses `deleteStoredKeyringConnection` to properly delete Eventbrite's Keyring connection on disconnect. Up to now, it's only been removing the connection from app state.
* Be sure to have an Eventbrite connection under `marketing/connections/:site`. Ping me for credentials if you're not able to create a new connection yourself.
* On production, disconnect, and reload the page. Notice that the connection is there again.
* On this branch, disconnect.
* Refresh the page, and verify that the disconnected account is not showing.
Fixes #38723 .
=> Eventbrite: Properly remove the Keyring connection on disconnect.

client/my-sites/marketing/connections/service-action.jsx
Eventbrite has shut down an endpoint relied upon by our integration. Existing connections will continue to work until Feb 20, 2020, but no new accounts have been able to use the endpoint since December 2019. Let's just block users from creating any new connections at this point by disabling the Connect button.
* Go to `/marketing/connections/:site` on a site with no existing Eventbrite connection.
* Verify the Connect button is disabled, and does nothing when clicked.
* Check a site with an existing connection; verify an active Disconnect button is displayed. If you do not have a site with an existing connection, DM me for credentials and create a connection in production.
=> Eventbrite: Don't allow any more new connections.

client/blocks/reader-full-post/_content.scss, client/blocks/reader-full-post/gutenberg-gallery.scss
This PR updates Reader's Gutenberg gallery block styles to include the recently-added `blocks-gallery-grid` class. This fixes the tiling of smaller image galleries, which were previously displayed vertically rather than filling the available horizontal space.
Head to http://calypso.localhost:3000/read/blogs/82798297/posts/132 and confirm that the three images appear in a row.
Compare with the existing version http://wordpress.com/read/blogs/82798297/posts/132, where the images appear above one another.
Before:
After:
=> Reader: update Gutenberg gallery styles to include blocks-gallery-grid

packages/components/README.md
There's probably a lot that will need to be said in the `@automattic/components` README about design decisions and other high level things, but I didn't want that to be a hurdle to getting some docs started. Since I just had to figure out how to get Storybook going I thought get the ball rolling.
@jameslnewell wanted to make sure you're aware that I'm adding this, and also to ask if there's a nicer way that you're running Storybook at the moment?
* Add README to `@automattic/components`
* Add brief instructions for getting Storybook started
=> Add storybook instructions for @automattic/components

client/lib/importer/importer-config.js, client/my-sites/importer/file-importer.jsx
* If the Migration option is enabled, when a user clicks on the WordPress importer in the imports screen, they will be sent to the migration screen instead. 
* Apply diff
* Enable the `tools/migration` option, either via query parameter or via cookies
* Go to a WordPress.com site that doesn't have a Business plan (at the moment)
* Go to Import
* Click WordPress 
* You should be sent to the migration screen
* Clicking on any other importer should still show their respective UIs and they should work.
* This PR essentially disables the WordPress importer, but as it's only working when a flag is enabled, it should be fine, as we'll handle the updated flow in subsequent PRs.
=> WP Migration: Redirect WordPress importer to the migration screen if migration is enabled

client/lib/abtest/active-tests.js, client/my-sites/checkout/checkout/index.jsx
* Adds a new A/B test for testing the plan bump offer against the GSuite offer in signup.
* Presently, only users who purchase a domain along with a plan are shown the GSuite offer. This test will show only to those users who purchase a Personal plan and domain. 
**Scenario 1** (Test that the A/B test assignment works)
1. Begin at /start and purchase and purchase a domain and Personal plan
2. Verify that after purchase transaction is complete:
- you should see the GSuite upsell offer if in the _control_ group of the _showPlanBumpVsGsuite_ test
- you should see the Premium plan bump offer if in the `variantShowPlanBumpOffer` group of the _showPlanBumpVsGsuite_ test
**Scenario 2** (_Verify that you are not assigned to the test if purchasing a Personal plan without custom domain_)
1. Begin …
=> A/B test the plan bump offer against GSuite offer

client/lib/abtest/active-tests.js, client/signup/steps/domains/index.jsx
* The non-EN domain step test launched in https://github.com/Automattic/wp-calypso/pull/38233 has found the variant to be a winner. For more context, check p8Eqe3-10k-p2.
* This PR launches the variant for all non-EN users. `en` locale users will continue to get assigned to the `domainStepCopyUpdates` test, while non-EN users will see the variant without getting assigned to the test.
* Go through the signup flow in any non-EN locale - for example, use the link /start/fr. In the domain step, you should see the new domain step version(i.e the variant version of `domainStepCopyUpdates` ). 
* Now verify that you are not assigned to the `domainStepCopyUpdates` test. In your browser console, type `localstorage.ABTests();` - the object displayed should not contain domainStepCopyUpdates. 
_Test …
=> non-EN domain test: Launch the variant as winner

client/landing/gutenboarding/onboarding-block/design-selector/page-layout-selector.tsx, client/landing/gutenboarding/onboarding-block/design-selector/style.scss
Add the template title
Current state of this PR:
- `http://calypso.localhost:3000/gutenboarding`
- Follow onboarding steps
- Verify that page templates have captions.
Fixes #38742
=> Gutenboarding: Add Template Title in Page Selector

client/lib/abtest/active-tests.js, client/lib/domains/suggestions/index.js, client/signup/steps/domains/index.jsx
We'll stop the abtest till we decide if/how to restart those
* remove the `domainSuggestionsWithHints` abtest
* go through NUX and verify that variation2_front is used for domain suggestions
=> Stop the `domainSuggestionsWithHints` abtest

client/jetpack-connect/authorize.js, client/jetpack-connect/install-instructions.jsx, client/jetpack-connect/jetpack-new-site/index.jsx, client/jetpack-connect/main.jsx, client/jetpack-connect/plans-landing.jsx, client/jetpack-connect/plans.jsx, client/jetpack-connect/remote-credentials.js, client/jetpack-connect/signup.js, client/jetpack-connect/site-topic.js, client/jetpack-connect/site-type.js, client/jetpack-connect/sso.jsx, client/jetpack-connect/user-type/index.js
We made a decision not to use HotJar during Jetpack connect.
See: p1HpG7-8ga-p2
* Remove hotjar from the Jetpack connect flow
* Connect Jetpack with the Chrome debugger open
* You should not see any requests to *.hotjar.com in the network inspector
=> Remove HotJar during the Jetpack connect flow

client/landing/gutenboarding/onboarding-block/design-selector/index.tsx, client/landing/gutenboarding/onboarding-block/design-selector/style.scss
Add design title and description to the page selector.
Note that this doesn't look good in dark mode, which will be removed for now (#38587).
Closes #38748
* Visit `/gutenboarding` and try the design selector.
* The design name and a "lorm ipsum" text should slide up next to the selected design when it's selected.
=> Gutenboarding: Add description to design-selector

client/landing/gutenboarding/onboarding-block/design-selector/style.scss, client/landing/gutenboarding/onboarding-block/edit.tsx, client/landing/gutenboarding/onboarding-block/style.scss, client/landing/gutenboarding/onboarding-block/vertical-background.tsx
Remove the dark theme. It's only partially designed and implemented and is slowing us down.
Part of #38587
Before (prefer dark):
After (prefer dark):
- Vist `/gutenboarding`
- Pick a vertical
- Toggle between dark/light mode. We should always have light theme. _Settings_ -> _General_ on macOS:
=> Gutenboarding: Remove dark theme

client/landing/gutenboarding/onboarding-block/style.scss
Improves the skip button styling
* Visit `/gutenboarding` and hover/focus the continue button
=> Gutenboarding: Improve skip button styles

client/my-sites/checkout/checkout/composite-checkout-payment-methods.js, client/my-sites/checkout/checkout/composite-checkout.js, packages/composite-checkout-wpcom/src/hooks/use-shopping-cart.ts
The shopping cart endpoint makes some decisions about what payment methods can be safely displayed to the user (the server sends an `allowed_payment_methods` array of strings). Currently that data is transformed by `useShoppingCart` into an `allowedPaymentMethods` array on the `WPCOMCart` object but is then not added to the response value of the hook and is ignored in the UI. The `CompositeCheckout` component does have its own `allowedPaymentMethods` prop, but it is used only for testing.
This PR adds the array to the response value of `useShoppingCart` and changes the behavior of the `CompositeCheckout` component in Calypso to use the shopping cart's `allowedPaymentMethods` array if the prop by that name is undefined (which preserves its use for testing). It also renames the string keys …
=> composite-checkout: Use allowed payment methods from cart

packages/composite-checkout-wpcom/src/components/wp-checkout-order-review.js, packages/composite-checkout-wpcom/src/components/wp-order-review-line-items.js
When paying with partial credits for a purchase, the credits show up in the checkout review as a line item. Currently all line items except for the `tax` type include a button which allows deleting that line item.
This PR removes the button for WordPress.com credits so they cannot be deleted.
- Add credits to your test account, but not enough to purchase a full plan.
- Add a plan to your cart that costs more than you have credits to spend.
- Visit checkout and complete the steps to get to the review step.
- Verify that the step shows a delete button for the plan but not for the credits.
=> composite-checkout: Prevent deleting wpcom credits

client/lib/post-normalizer/rule-decode-entities.js
Sometimes in Reader we see undecoded entities like this in post titles (often x-post titles):
This happens when the entity has been double-encoded, and the first pass of `decodeEntities` didn't do the trick.
This PR adds a second pass of `decodeEntities` for the post title only.
(Ultimately it would be nice to fix this in the API, but this is an effective band-aid for now.)
Ensure all post titles display without undecoded entities in your Reader feed:
Fixes https://github.com/Automattic/wp-calypso/issues/37829.
=> Reader: fix double-encoded entities in post title

client/components/marketing-survey/cancel-auto-renewal-form/index.jsx
This PR implements the randomization of the auto-renewal cancellation survey to mitigate the selection tendency caused by the fixed order.
1. Go to the purchase management page of a subscription.
1. Turn off the auto-renewal toggle.
1. Click "Confirm cancellation"
1. The survey should show up.
1. Turn the auto-renewal back on and refresh the page. Refreshing is necessary here since the survey won't show up twice without navigating away.
1. Perform the same steps to reach the survey and note the order again. The order 
might or might not be the same as the previous run due to the nature of randomization. If it is still the same, please just redo the same steps.
=> Randomize the auto-renewal cancellation survey options.

client/my-sites/people/people-invites/index.jsx
This is an alternative take on https://github.com/Automattic/wp-calypso/pull/38753. 
There are two cases to consider here - site with pending invites, and sites without pending invites. When a site has pending invites we show the invite button above the pending invites like this:
And then the accepted invites section doesn't have an invite button, like this:
But if the site has no pending invites and only accepted invites, you see this:
Fixes #35504
=> People: Only show the invite button when there are no pending invites

packages/composite-checkout/src/components/loading-content.js
This PR adds a loading placeholder animation while checkout is in its loading state. 
* Get calypso running locally
* Add a product to your cart and go to checkout
* Add the following query string to the URL: `flags=composite-checkout-wpcom`
* Reload the page to see the loader.
=> Composite checkout: add loading animation

config/development.json, config/production.json, config/stage.json, config/wpcalypso.json
* Adds feature flags for allowing us to use`UpsellNudge`, a new component in development in #38537
* Confirm that `upsell/nudge-component` is present as a feature in the config files (we don't currently have an active implementation running yet)
* `https://calypso.localhost:3000/?flags=upsell/nudge-component` should show the `upsell/nudge-component` as true in development and wpcalypso, false in production and stage.
=> Upsell Nudges: Add a feature flag for the new component

client/my-sites/migrate/section-migrate.jsx, client/my-sites/migrate/section-migrate.scss
* When the target site doesn't have a plan that allows the uploading of themes and plugins, redirect the user to a cart containing a Business Plan. On purchase of the plan, redirect them back to the migration view and start the migration.
* Adds a height to the illustration on the migration progress page, to avoid jumps in the page when the illustration loads.
* Check out this pull request and run Calypso locally, or run it on `calypso.live`.
* Viewing `calypso.localhost:3000/migrate/`, you should see a SiteSelector component allowing …
=> Site migration: go to cart when target site doesn't have a supported plan

packages/composite-checkout-wpcom/src/components/coupon.js, packages/composite-checkout-wpcom/src/components/wp-checkout-order-review.js, packages/composite-checkout-wpcom/src/components/wp-checkout-order-summary.js, packages/composite-checkout-wpcom/src/components/wp-order-review-line-items.js, packages/composite-checkout/src/components/checkout.js, packages/composite-checkout/test/checkout.js
This PR modifies the form so that the "Edit" buttons on any editable steps are not shown if the form is currently not in a "ready" status (meaning it is either loading, submitting, or complete).
This will not disable other additions to the form, so any custom buttons or fields added by the host page must be explicitly disabled as well. Therefore this PR also modifies the coupon fields, the add coupon button, and the delete item buttons so that they are also disabled when the form is not ready.
First apply the following patch to break form submission:
```js
--- a/packages/composite-checkout/src/lib/payment-methods/paypal.js
+++ b/packages/composite-checkout/src/lib/payment-methods/paypal.js
@@ -22,11 +22,7 @@ export function createPayPalMethod( { registerStore, submitTransaction, successU …
```
=> composite-checkout: Disable form controls when form status is not ready

client/my-sites/checkout/checkout/composite-checkout.js, packages/composite-checkout-wpcom/src/components/wp-checkout-order-summary.js, packages/composite-checkout-wpcom/src/components/wp-checkout.js, packages/composite-checkout-wpcom/src/hooks/has-domains.js
This fills in the `DomainURL` component in the summary step (which previously contained a placeholder) so that it contains either the first domain name in the cart, if one is present, or the current site's slug otherwise.
It also hides taxes and credits from the summary step.
- Add a plan to your cart, but not a domain.
- Visit checkout and verify that you see the site's current domain name in the summary step (just below the words "You are all set to check out").
- Go back and add a domain to your cart.
- Visit checkout and verify that you see the new domain name in the summary step (just below the words "You are all set to check out").
Before:
After:
=> composite-checkout: Fill in site name or domain name in summary

packages/composite-checkout/src/components/checkout.js
The submit button, at small screen widths, has a fixed position at the bottom of the window. However, once you click the button to submit the form, the button becomes relatively positioned instead and (if the window is not scrolled to the bottom) jumps out of view. This is not intentional behavior and appears jarring as well as making it unclear what the status of the form is since the "submitting" text is on the button itself.
This PR removes the `isCheckoutInProgress` condition which is a little ambiguous and instead makes each place it was used more explicit about what conditions should matter. Notably, the submit button should be disabled when the form is submitting, but it should still be in a fixed position.
First apply the following patch to break form submission:
```js
--- …
```
=> composite-checkout: Keep submit button fixed when submitting form

client/lib/signup/site-type.js, client/lib/signup/step-actions.js, client/state/selectors/get-new-site-public-setting.ts, client/state/selectors/should-new-site-be-private-by-default.ts, client/state/selectors/test/get-new-site-public-setting.js, client/state/selectors/test/should-new-site-be-private-by-default.js
Reverts Automattic/wp-calypso#38372
Reinstates the variable new site `blog_public` setting as per #35320 (& #34193 prior).
See discussion: p1579016110098700-slack-CCS1W9QVA
If eCommerce sites are created private, there's a chance that they'll be blocked from going Atomic when the upgrade succeeds. 
For now, let's just continue creating sites that select the eCommerce plan during signup as public.
`npm run test-client client/state/selectors/test/should-new-site-be-private-by-default.js client/state/selectors/test/get-new-site-public-setting.js`
* Run this branch
* Create a new site from `/start` with the eCommerce plan selected (don't complete the purchase yet)
* It should be created as public
* Complete the purchase
* It should be taken Atomic
* Create a new site from `/start` with any …
=> Revert "Fix: Sites created through the ecommerce flow should be private"

client/landing/gutenboarding/onboarding-block/design-selector/index.tsx, client/landing/gutenboarding/onboarding-block/design-selector/style.scss
Added vertical space around the design selector heading.
The space around the heading is intended to be 48px (see https://github.com/Automattic/wp-calypso/issues/38741#issuecomment-572707554) however the Gutenberg editor adds 50px above the heading, so I've used that below as well.
The vertical space wasn't maintained when the heading text wrapped (mobile view or after text is translated). I couldn't think of a CSS only solution to this, so I'm using JavaScript to measure the height of the heading once. The transition is still performed by CSS.
* Add padding below around design selector heading
* Removed fixed heading height so space is maintained between heading and grid when text wraps
* Use JavaScript to measure how far design selector should move during transition
* Add gap at bottom …
=> Add vertical space around design grid

client/landing/gutenboarding/onboarding-block/design-selector/style.scss
Design selector description should be hidden when no design is selected.
**Fixes**
=> Gutenboarding: Fix design selector description always visible

client/components/banner/README.md, client/components/banner/docs/example.jsx, client/components/banner/index.jsx, client/components/banner/style.scss, client/components/banner/test/index.jsx
We're planning to use the `Banner` component as a base for the new `UpsellNudge` block. See #38537 for more information.
This PR makes a few minor changes to make that possible:
* Adds an `isCompact` prop and class name so we can use a smaller version of the banner in the sidebar (or other tight spaces)
* Adds some default styles for compact Banners
* Adds three props for impression, click, and dismiss Tracks events, so we can override these as necessary, with defaults so existing uses of `Banner` won't be affected.
* Adds Tracks event properties for impression, click, and dismiss events from the parent.
* Don't display an icon by default; if no icon is set, none is shown
**Regular**
**Compact**
* TBD
=> Banner: Allow for more customization from parent instances

client/state/selectors/is-site-coming-soon.js, client/state/selectors/test/is-site-coming-soon.js
This PR adds a new selector `isSiteComingSoon` that's going to be used to determine whether or not given site is in Coming Soon mode.
Just confirm the tests are passing.
=> [Coming Soon] Add isSiteComingSoon selector

client/my-sites/activity/activity-log/index.jsx, client/my-sites/site-settings/jetpack-credentials/credentials-configured/index.jsx, client/state/selectors/site-supports-realtime-backup.js, client/state/selectors/test/site-supports-realtime-backup.js
Previously, we were saying "in real time" in both the AL and the credentials screen. However, if the user has a daily backup product, this is no longer accurate. This PR is fixing the wording to reflect the currently supported product/plan.
* Introduce a new `siteSupportsRealtimeBackup` selector with tests.
* Activity Log: Fix wording depending on the supported backup.
* Settings: Fix credentials wording depending on the supported backup.
Activity Log - with a Daily Backup product
Activity Log - with a Realtime Backup product
Security Settings - with a Daily Backup product
Security Settings - with a Realtime Backup product
* Create 2 JN sites and connect them. Let's call them site X and site Y.
* Buy a daily backup for site X, buy a realtime backup for site Y.
* …
=> Jetpack Backup: Fix Credentials and AL wording based on currently supported product

packages/composite-checkout-wpcom/src/components/wp-order-review-line-items.js
This PR fixes an issue with the position of the delete buttons in the review step of checkout.
**Before**
**After**
* Get calypso up and running
* Add a plan and domain to your cart.
* Visit checkout and add this flag to the url: `?flags=composite-checkout-wpcom`
=> Composite checkout: fix delete button position

apps/notifications/README.md
The README was out of date for the notifications panel.
In this patch we're making a few overdue updates:
- Mention that Calypso consumes the panel directly (vs. using an iframe)
- Describe most basic build steps and redirect to Field Guide for full instructions
- Small formatting updates
As this only updates a README there's not much testing to perform.
=> Notifications: Update README

client/lib/i18n-utils/test/utils.js, client/lib/i18n-utils/utils.js
A follow up to #38711. Calling `translationExists` worked in jest because `hasTranslation` was mocked, but in the actual browser it resulted in an error:
```
i18n.js:138 Uncaught TypeError: Cannot read property 'state' of null
at getTranslation (i18n.js:138)
at I18N.hasTranslation (i18n.js:365)
at translationExists (utils.js:108)
```
That error was caused by `null` being used as `this` in call to `hasTranslation.apply()`. This PR ensures proper `this` is used, and improves the way we mock things in tests so that the original `hasTranslation` is used.
1. Try `translationExists` in the browser
2. Confirm the tests are working
=> Use proper `this` when calling i18n.hasTranslation

client/my-sites/checkout/checkout/composite-checkout.js
This adds a hook to `CompositeCheckout` such that when the cart has items and then becomes empty, it redirects away from checkout to the plans page, which appears to be where the current checkout sends you in that situation.
We did it this way rather than just if the cart is empty because during a normal checkout the cart may be empty temporarily (for several render cycles) when a new product is about to be added to the cart (see `useAddProductToCart()`).
- Complete checkout and get to the final step.
- Click the trash icon to remove the plan from the cart.
- Verify that you are redirected to the plans page for your site.
=> composite-checkout: Redirect if the cart becomes empty

client/blocks/upsell-nudge/README.md, client/blocks/upsell-nudge/index.jsx, client/blocks/upsell-nudge/style.scss, client/my-sites/current-site/notice.jsx
* Add an `UpsellNudge` block to replace the use of `SidebarBanner` and `Notice` components in the sidebar.
* This is a wrapper for `Banner`, to restyle it to match the new nudges we're proposing for the sidebar. See #38733 for changes made to `Banner` to add support for a new compact style.
* Eventually we hope to consolidate all upsell nudges to use this block.
Example implementation:
* Check to make sure the new block does not break anything. It isn't implemented yet, but it should not break existing uses of `Banner`.
=> UpsellNudge: Add UpsellNudge block to unify upsell nudges going forward

client/blocks/upsell-nudge/docs/example.jsx, client/devdocs/design/blocks.jsx
* DO NOT MERGE until #38537 is deployed.
* Adds `UpsellNudge` examples to `/devdocs` for design reference.
* See #38537 for the nudge implementation.
* Wait for #38537 to be merged. :)
* Switch to this PR.
* Navigate to `/devdocs/blocks/upsell-nudge` and make sure the page exists, and that the designs look right.
=> UpsellNudge: Add UpsellNudge block examples to devdocs

client/landing/gutenboarding/onboarding-block/design-selector/page-layout-selector.tsx, client/landing/gutenboarding/onboarding-block/design-selector/style.scss
Addresses #38762 (partially?)
Sets a fixed height of 280px to the imgs passed to the card media.
In page selector section:
CC @dwolfe
=> Gutenboarding: fix height of card media/img

client/my-sites/checkout/checkout/composite-checkout-payment-methods.js, packages/composite-checkout-wpcom/src/components/coupon.js, packages/composite-checkout-wpcom/src/components/wp-checkout-order-review.js, packages/composite-checkout-wpcom/src/components/wp-checkout-order-summary.js, packages/composite-checkout/README.md, packages/composite-checkout/src/components/checkout-provider.js, packages/composite-checkout/src/lib/payment-methods/apple-pay.js, packages/composite-checkout/src/lib/payment-methods/existing-credit-card.js, packages/composite-checkout/src/lib/payment-methods/stripe-credit-card-fields.js, packages/composite-checkout/src/lib/stripe.js
When paying with a credit card that requires 3DS authentication, Stripe's library will display a modal to perform the authentication and then tell the page if the auth completed or failed.
This PR hooks up the response from the modal to the rest of the form, so that `onPaymentComplete` will be called when the authentication completes for both new and existing cards.
Additionally, this fixes a regression introduced in #38759 which caused the stripe form to never finish loading. This happened because the payment methods were being recreated twice; the first time the stripe payment method went and fetched the stripe configuration, but then the second time the configuration was no longer present and the hook did not try fetching it again. The cause of this double-rendering was that the …
=> composite-checkout: Enable 3DS for Stripe payment method

client/my-sites/checkout/checkout/composite-checkout.js, packages/composite-checkout-wpcom/src/components/form-field-annotation.tsx, packages/composite-checkout-wpcom/src/components/wp-checkout.js, packages/composite-checkout-wpcom/src/components/wp-contact-form.js, packages/composite-checkout-wpcom/src/hooks/wpcom-store.js, packages/composite-checkout-wpcom/src/index.js, packages/composite-checkout-wpcom/test/form-field-annotation.js
This PR is a follow-up to #38481 (this one currently also contains that one).
Here we add a drop-down field for state and a controlled field input for phone number.
* Sandbox the store.
* Start local calypso with composite checkout enabled: `ENABLE_FEATURES=composite-checkout-wpcom npm start`
* Complete the form.
* Test the behavior of the state field and phone number input.
* Complete the purchase and verify that the receipt is correct.
* Repeat the above test with a .live domain.
=> composite-checkout: Add phone and state custom fields to contact form

client/my-sites/theme/main.jsx, client/my-sites/theme/style.scss
* Add Jitms in the expected section of the page. 
1. Add the following path on your .com sandbox. D37843-code
2. Sandbox public-api.wordpress.com and add JETPACK__SANDBOX_DOMAIN on the jetpack site that is being used to test this. 
3. Visit http://calypso.localhost:3000/theme/barnsbury/example.com
4. Notice the JITM shows up and it works as expect.
=> Jitm: Add theme jitm section

client/components/domains/contact-details-form-fields/README.md, client/components/domains/contact-details-form-fields/index.jsx, client/components/domains/contact-details-form-fields/test/index.js
* The `ContactDetailsFormFields` component has a required callback prop `onSubmit`. Composite checkout needs to use this component for consistency, but manages its own state and submission. This PR makes `onSubmit` optional and prevents rendering the submit button if the prop is not present.
* `npm run test-client client/components/domains/contact-details-form-fields`
=> Make onSubmit prop optional in contact details form fields component

client/my-sites/customer-home/main.jsx
Part of #38861
* Moves to the top the "Go Mobile" card in the customer home when viewed in mobile viewports.
* Displays the store button according to the user's OS rather than display both buttons.
iPhone | Android | Other OS
--- | --- | ---
* Go to `/home/:site`.
* Verify the "Go Mobile" card is still at the end of the right column when viewed in a desktop viewport.
* In the Chrome DevTools toggle the device toolbar. 
* Select any iPhone from the top toolbar.
* Reload the page.
* Make sure the "Go Mobile" card is displayed now at the top of the screen, the link to App Store is visible and there is no link to Google Play.
* Select now an Android device such as Galaxy or Pixel.
* Reload the page.
* Make sure the "Go Mobile" card is displayed now at the top of the screen, the link to Google …
=> Customer Home: Move "Go Mobile" to top on mobile viewports

client/blocks/get-apps/apps-badge.scss, client/my-sites/customer-home/main.jsx, client/my-sites/customer-home/style.scss
Part of #38907 
Follows up #38905
The Google Play badge image has some transparent space around it which causes some [alignment issues](https://github.com/Automattic/wp-calypso/pull/38905#issuecomment-575667863) when using it along with the App Store bade image (since this one doesn't have any transparent space).
Google Play | App Store
--- | ---
[Link to image](http://play.google.com/intl/en_us/badges/images/generic/en_badge_web_generic.png) | [Link to image](https://linkmaker.itunes.apple.com/assets/shared/badges/en-us/appstore-lrg.svg)
This PR includes a CSS hack that crops the Google Play image in order to have a size-equivalent image to the App Store one in order to prevent those alignment issues.
That allowed to align the banner to the right when we display one single store button …
=> Mobile Apps: Crop Google Play badge image

apps/notifications/src/panel/boot/stylesheets/main.scss, apps/notifications/src/panel/boot/stylesheets/shared/sizes.scss, apps/notifications/src/panel/templates/summary-in-list.jsx
This PR updates the notifications panel styles to match upcoming updates to the app styles.
The primary changes are:
* Remove all italic text and use bold instead (for post titles, etc.)
* Make user and action type icons slightly smaller
* Header text slightly larger, excerpt text slightly smaller
* A bit more padding within the notes panel
* Use a slightly darker gray for the dividers
See pauD4L-z9-p2 for context
Before:
After:
* Check the notifications panel with various sorts of notifications and make sure the styles look consistent
=> Notifications: Update styles

client/my-sites/migrate/controller.js, client/my-sites/migrate/index.js, client/my-sites/migrate/section-migrate.jsx, client/my-sites/migrate/section-migrate.scss, client/my-sites/migrate/step-import-or-migrate.jsx, client/my-sites/migrate/step-source-select.jsx
* Remove site-selector from initial migration page
* Add free-form url field
* Call existing `is-site-importable` endpoint to verify url is importable
* Adds a new route for "import or migrate" step
* Navigate to `/migrate` with the `tools/import` feature-flag enabled.
* Select the site that you want to import into.
* You should see a URL-field and a continue button. The styling of these new elements is incomplete and will be completed in a future PR.
* Enter a Jetpack-connected URL into the input field. The non-happy-path is incomplete and will be completed in a future PR.
* Click "Continue".
* You should see the stub of a page with "What do you want to import?". This …
=> Migration: allow for free-form entry of site url

client/my-sites/checkout/checkout/composite-checkout.js, client/my-sites/checkout/checkout/style.scss
This PR adds a warning card to the top of the checkout form so that anyone using it is explicitly aware that this is a new and still in-testing feature.
- Verify the banner is visible and looks good at different window widths; particularly above 700px and below 700px.
=> composite-checkout: Add TestingBanner to CompositeCheckout to warn about testing

client/my-sites/checkout/checkout/composite-checkout-payment-methods.js, packages/composite-checkout/README.md, packages/composite-checkout/demo/index.js, packages/composite-checkout/src/components/payment-request-button.js, packages/composite-checkout/src/lib/payment-methods/apple-pay.js
Apple Pay has been prepared for a while, but this PR hooks it up to the transactions endpoint so that it can complete purchases.
- Using Mac OS Safari, visit WordPress.com and log in. This is required because once we proxy, you will not be able to log in.
- Enable Charles proxy to spoof WordPress.com. This is required because Apple Pay will only work on SSL and on a production domain. The details of how to do this are beyond the scope of this PR. Contact me if you have any issues.
- Using Mac OS Safari, reload WordPress.com and be sure you see the "dev" badge in the lower-right.
- Select "Apple Pay" from the available payment methods.
- Complete the …
=> composite-checkout: Enable apple pay

client/blocks/jitm/templates/default.jsx, client/components/banner/README.md, client/components/banner/docs/example.jsx, client/components/banner/index.jsx, client/components/banner/style.scss, client/components/banner/test/index.jsx
JITMs in Calypso had no support for Jetpack messages. This PR adds a support for this kind of messages. For the icon a `JetpackLogo` is used and the border color is set to Jetpack green. Also, the layout of the `Banner` is set to `horizontal`, so that it matches the design.
* Add a `jetpack` prop to the `Banner` component
* Add a `horizontal` prop to the `Banner` component
* Add a support for Jetpack banners in JITM
* Go to http://calypso.localhost:3000/devdocs/design/banner
* Confirm that a horizontal Jetpack banner is rendered as a last example
* Once #38859 is merged, you should also see Jetpack Backup JITMs (if you're on a free plan) in Calypso when installing a new theme or plugin.
Fixes n/a
=> JITMs: Add support for Jetpack JITM banners

client/my-sites/email/email-management/index.jsx, client/my-sites/stats/stats-banners/index.jsx
This fixes a scenario where error notifications are displayed with either `Failed to retrieve G Suite Users`  and `Failed to retrieve email forwarding records for <domain>. Please try again or contact support.` when capabilities are not enough for managing a site with a custom domain. 
Fetching forwarding data | Fetching G Suite data 
---|---
This essentially happens when Calypso attempts to fetch G Suite and/or forwarding data for a site for which you are less than an administrator.
**Setup** 
- You need two test WPcom users 
- User **UserA** who owns a site **SiteA** 
- User **UserB** ( does not need own site for this test )
- Two browsers, or a browser with private/incognito mode
- A development instance of Calypso accessible at http://calypso.localhost:3000/
**Steps**
Users **UserA** …
=> G Suite: Put the Stats & Email Management page behind a capability check

client/lib/domains/suggestions/index.js, client/signup/steps/domains/index.jsx
We've decided to go with `variation4_front` that uses the selected vertical for surfacing different TLDs up the suggestions results.
* use `variation4_front` as suggestion vendor in NUX
* go to `/start` and select some vertical (for example photography) - then verify that we're using `variation4_front` as suggestion vendor and that relevant TLDs are surfaced in the suggestion results.
=> Domains: Update the domain suggestion vendor in NUX to use selected vertical as hint

client/my-sites/checkout/checkout/composite-checkout-payment-methods.js, packages/composite-checkout-wpcom/src/lib/translate-cart.ts, packages/composite-checkout-wpcom/src/mock/cart-endpoint.ts, packages/composite-checkout-wpcom/src/types/backend/shopping-cart-endpoint.ts, packages/composite-checkout-wpcom/src/types/checkout-cart.ts, packages/composite-checkout-wpcom/test/translate-cart.js
When submitting products to the various transaction endpoints for most payment methods, we may need to include extra meta-data. Notably, the GSuite product may include a `volume` greater than 1, and may need a list of users. All this data has already been added to the cart by the time we get to checkout but it is ignored by the cart data in `useShoppingCart` and is therefore not sent to the server again.
It's unclear to me if we _must_ resubmit this data to the server, but it seems like a good idea. This PR adds `volume` and the `extra` object to the product data created handled by `translateWpcomCartItemToCheckoutCartItem()` and included in the transaction submissions through `createCartFromLineItems()`.
- Run calypso with `ENABLE_FEATURES=composite-checkout-wpcom …
=> composite-checkout: Add GSuite meta to cart during submit

client/components/domains/contact-details-form-fields/index.jsx
* #38835 made the `onSubmit` prop of this component optional, and if not provided does not render the submit button. That leaves behind an empty form footer, which renders with an unnecessary border. This PR detects when neither the Submit button nor the Cancel button is rendered and does not render the form footer in this case.
`npm run test-client client/components/domains/contact-details-form-fields`
=> domains/contact-details-form-fields: Do not render form footer if no action buttons are rendered

client/my-sites/site-settings/form-general.jsx
Update the footer credit upgrade banner, removing the reference to Google Analytics in the Business plan
Google Analytics was added to the Premium plan in #36367 , so should not be referenced as a feature when upgrading from Premium to Business plans.
* Visit `/settings/general/{site}` on a site with Premium plan or below
* Verify new text for upsell banner under the Footer Credit setting
=> Settings: Update footer credit upgrade banner

client/my-sites/checkout/checkout/composite-checkout.js
This removes the text `and select "Checkout Redesign" in the project sidebar` from the testing banner in the composite checkout form. This was supposed to be part of #38910 but I forgot to include it.
Visit checkout and be sure the banner displays correctly.
Before:
After:
=> composite-checkout: Remove mention of sidebar in banner

client/extensions/zoninator/components/search-autocomplete/style.scss, client/landing/gutenboarding/onboarding-block/vertical-select/style.scss, client/signup/steps/site-topic/style.scss, client/signup/style.scss, packages/components/src/suggestions/index.jsx, packages/components/src/suggestions/style.scss, packages/components/src/suggestions/test/__snapshots__/index.js.snap
Allows passing an optional component/container class to the suggestions dropdown.
Make sure suggestions work as normal. Try https://wpcalypso.wordpress.com/gutenboarding/
Also see https://github.com/Automattic/wp-calypso/pull/38716 for use.
-- Guess there are other/many ways to do this (or avoid I guess) - but it's one way.
=> Suggestions: Pass optional container class

client/landing/gutenboarding/onboarding-block/design-selector/style.scss
* Design selector now uses pointer cursor.
* Page layout selector now uses pointer cursor.
1. Go to https://calypso.live/gutenboarding?branch=fix/gutenboarding-pointer-for-template-grids
2. When hovering over a design, the cursor should be a pointer.
2. When hovering over a page layout, the cursor should be pointer.
Design Selector
Page Layout Selector
* Fixes #38846
=> Gutenboarding: Use pointer cursor for design selector and page layout selector.

client/me/purchases/remove-purchase/remove-domain-dialog/index.jsx
- Remove prompt to contact support for domains that are not refundable in the refund window
Using Store Sandbox:
- Purchase a test domain with credits
- Go to /me/purchases
- Find the domain you registered, and click it
- Click the remove domain button
- You should not see the prompt to contact support
- Existing functionality of the remove dialog should not break
=> Domains: Remove prompt to contact support

packages/composite-checkout-wpcom/src/components/wp-checkout-order-review.js, packages/composite-checkout-wpcom/src/components/wp-checkout.js, packages/composite-checkout-wpcom/src/components/wp-terms-and-conditions.js
The links in the TOS were colored to look like the text and the domain name wasn't actually there. This fixes both issues.
Fixes #38994 and #38993
Before:
After:
- Add a domain and plan to the cart and visit checkout. 
- Complete all the steps. 
- Verify that the TOS at the bottom has colored links and that the domain in the cart is listed there.
=> composite-checkout: Fix TOS links and placeholder domain

client/landing/gutenboarding/onboarding-block/question/index.tsx
This PR removes scaling transitions of questions after initial activation.  It was proposed that we could completely remove the scaling effects from the onboarding questions on #38681.  Before completely removing the transition and animations that have been put into place, this PR suggests that we continue to use the initial scale-up when a question is activated but to not scale-down once the question is deactivated.  This will allow us to retain the nice feel of load-in animation for questions without causing further issues with selecting the 'Continue' button.
To do this I have added `useState` and `useEffect` to set and keep track of a `hasActivated` variable within the Question component.  `hasActivated` starts as `false` and is then set to `true` once `isActive` becomes `true`. …
=> Fix "Continue" button not working due to scaling transitions.

client/my-sites/migrate/controller.js, client/my-sites/migrate/index.js, client/my-sites/migrate/section-migrate.jsx, client/my-sites/migrate/step-confirm-migration.jsx, client/my-sites/migrate/step-upgrade.jsx
This is a partial change behind a feature-flag
* Adds the stub of the plan confirmation step
* Moves migration confirmation into its own step
* Adds new route for the plan confirmation step
* Refactors how step is determined from context/route
* Make sure that you're able to complete a migration flow by starting from `/import`. Many of the screens are stubbed right now.
=> Migration: Add upgrade confirmation step

client/my-sites/migrate/step-confirm-migration.jsx
* Fixes an issue introduced in #39006 on the migration confirmation screen when starting a migration if you already have purchased the business plan
* Start at `/import` on a site where you already have a business plan
* When you get to the confirmation screen, you should be taken to the migration status view after starting a migration (prior to this change, you received an error in the console)
=> Migration: fix migration start on confirmation step

client/landing/gutenboarding/onboarding-block/design-selector/style.scss
This PR fixes a size fluttering issue on the page selector cards during hover states, due to the discrepancies between the width of the borders and new absolute positioning of the card content.
Now, content is re-positioned behind the hover/focus/selected state border by half of the difference in width between the neutral state border, and stretched by the full difference.
<hr>
* Spin up calypso local dev environment and hit `/gutenboarding`.
* Get to the step requiring you to select a page. Make sure that the content size doesn't fluctuate based  on hover/focus/selected states.
* Ensure there are no regressions.
<hr>
Fixes #38895
=> Gutenboarding: Fix page selector card hover

client/signup/config/flows-pure.js
part of https://github.com/Automattic/wp-calypso/issues/38934
* use `domains` and `plans` steps + `user` for new users
* use custom `pageTitle`
* Go to http://calypso.localhost:3000/start/frankenflow
* Page title should be 'Launch your site' instead of 'Create your site'
* If logged in, first step rendered should be `/domains` and the next one `/plans`
* Customize steps content and header according to design 
* `destination` (the redirect after completing the flow) should be Calypso home instead of block-editor
=> Gutenboarding: add custom pre-launch signup flow

client/blocks/gsuite-stats-nudge/index.js, client/components/upgrades/gsuite/gsuite-upsell-card/index.jsx
This updates the copy on the G Suite stats nudge to remove "click here" in the heading. Changes `Customers can’t reach you at contact@%s - click here to add a mailbox` -> `Customers can’t reach you at contact@%s. Add a mailbox.`
It looks like there was an A/B test in #31328 that settled on this copy. However, using "click here" for this heading is not great language.
* This text is not actually clickable, so "click here" doesn't apply. Even if it was a link, [using "click here" in links is poor usability anyway](https://medium.com/@heyoka/dont-use-click-here-f32f445d1021)).
* "Click here" removes some of the human element and personality we should strive for in our copy. It reads more like a marketing click campaign.
This copy is only a suggestion. Pinging @Automattic/editorial and …
=> G Suite: Update copy on stats nudge to remove 'click here' language

client/my-sites/customer-home/go-mobile-card/index.jsx, client/my-sites/customer-home/go-mobile-card/style.scss, client/my-sites/customer-home/main.jsx, client/my-sites/customer-home/style.scss
Alternative to https://github.com/Automattic/wp-calypso/pull/38949 and fixes https://github.com/Automattic/wp-calypso/issues/38861. Note that I'm avoiding SMS for now until p3btAN-1c0-p2 is resolved.
Folks are welcome to modify styles directly in this branch if folks had any suggestions/tweaks for the various viewports.
This moves the GoMobile card into it's own component, and also adds a button that will email an app download link and magic login link.
| Desktop |
| -------------|
|  ![Jan-22-2020 09-34-21](https://user-images.githubusercontent.com/1270189/72918481-9820d300-3cfa-11ea-90f9-2434a691f4d0.gif) |
| Large Desktop Viewport  | Small Desktop Viewport | IPhone | Android |
| ------------- | ------------- |------------- | ------------- |
| <img width="324" alt="Screen Shot …
=> Customer Home: Add Email Me A Login Link Button to Go Mobile Card 

client/landing/gutenboarding/components/domain-picker/style.scss
* Increase specificity of `.domain-picker__panel-row` and `.domain-picker__suggestion-item` to fix styling regression caused by the incorrect load ordering of css, where gutenboarding stylesheet is loaded first, then wordpress/components stylesheet is loaded later. See https://github.com/Automattic/wp-calypso/issues/38834#issuecomment-577634784
1. Go to http://calypso.localhost:3000/gutenboarding
2. Enter a site name and click Continue.
3. Click on the domain picker button on the upper left corner.
4. Domain picker popover should look like the screenshot below.
**Before:**
**After:**
* Fixes #38834
* See also: https://github.com/Automattic/wp-calypso/pull/38554/commits/e1f9673bcfd9eaa6469a0cfecda9b915a520961a
* See also: https://github.com/WordPress/gutenberg/pull/19535
=> Gutenboarding: Fix domain picker styling regression.

client/my-sites/customer-home/main.jsx, client/my-sites/customer-home/stats-card/index.jsx, client/my-sites/customer-home/stats-card/style.scss
Adds a simple stats card to the Customer Home that displays the current week views and visitors of the site.
For sites that don't reach 10 visits, we show insights indicating the most popular day and hour:
The card is not displayed in the below scenarios:
- When the site is unlaunched.
- When the site is a Jetpack or Atomic site with the Stats module disabled.
- When the site has not received any visit yet (i.e. new created sites), since there is no popular day and time recorded.
- Go to `/home/:site`.
- Verify there is a new "Stats at a glance" in the top of the right column.
- If your site has 10 visits or more for the current week, you should see the number of views and visitors. Make sure numbers match stats displayed in `/stats/week/:site`.
- If your site has less than 10 visits for …
=> Customer Home: Add stats card

client/my-sites/customer-home/go-mobile-card/style.scss
After hiding the "email download link" button on mobile devices in https://github.com/Automattic/wp-calypso/pull/38960, I noted there is an extra margin at the bottom we missed to remove (since that margin is intended for separating the badges from the button).
This PR removes the margin the card is displayed on mobile devices.
Mobile device | Before | After
--- | --- | ---
iPhone / Android | <img width="407" alt="Screenshot 2020-01-23 at 13 59 22" src="https://user-images.githubusercontent.com/1233880/72986908-8c600a00-3de9-11ea-8f02-497a60adddeb.png"> | <img width="404" alt="Screenshot 2020-01-23 at 13 59 51" src="https://user-images.githubusercontent.com/1233880/72986925-941fae80-3de9-11ea-90e6-8d0c1fad8938.png">
Other | <img width="417" alt="Screenshot 2020-01-23 at 14 00 59" …
=> Customer Home: Remove margin bottom of "Go Mobile" card on mobile devices

client/my-sites/checkout/checkout/composite-checkout.js, client/my-sites/checkout/checkout/types/transaction-endpoint.ts, client/my-sites/checkout/controller.jsx, packages/composite-checkout-wpcom/src/hooks/use-shopping-cart.ts
Previously we assumed that there was always a selected site when making a purchase. This PR changes the code to avoid that assumption.
Fixes #38983
- Visit http://calypso.localhost:3000/domains
- Pick a domain
- Select "Just a domain"
- Verify that checkout loads and that the cart includes the domain you chose
- Complete the form and purchase the domain
- Verify that the domain was successfully purchased
=> composite-checkout: Allow loading checkout without selectedSite

packages/data-stores/global.d.ts, packages/data-stores/src/utils/wpcom-wrapper.ts
**GIT**: What's this PR for?
**ME**: We have to add [reloadProxy()](https://github.com/Automattic/wpcom-proxy-request/blob/master/index.js#L463) to `wpcom-wrapper`.
**GIT**: Why? 
**ME**: So we can make authenticated API requests without having to refresh the browser. We'll need it for https://github.com/Automattic/wp-calypso/issues/38707 and, presumably, other tasks.
**GIT**: Fine. 
N/A
The true test will be when we start making authenticated API calls after a user creates an account 👍
=> [Gutenboarding]: Add reloadProxy to our wpcom wrapper

client/signup/config/flows-pure.js
Send users to Customer Home after completing the signup flow.
Fixes #38937
* [`/start/frankenflow`](https://calypso.live/start/frankenflow?branch=gutenboarding/frankenflow-customer-home)
* Follow the steps and you should land at customer home `/home/SITE_SLUG` when the flow is complete.
=> Gutenboarding: Send customers to home after frankenflow

client/my-sites/site-indicator/style.scss
* Fixes the red on dark red hover colour in the Site Indicator in the Sidebar.
1. Start at your Calypso dashboard on a Jetpack site which cannot be accessed (eg. a Jurassic Ninja site which has passed its lifetime) 
2. Hover over the link in the error
3. Verify it is no longer a dark red which doesn't blend well with the background.
**Before:**
**After:**
This is the only colour in Colour Studio which passes colour contrast requirements for the red background, but the hover status is indicated by the cursor.
Fixes #38628
=> Sidebar: Fix Site Indicator Disconnect Link Colour on Hover

client/assets/stylesheets/_calypso-color-scheme-jetpack-cloud.scss, client/assets/stylesheets/jetpack-cloud.scss
This PR adds a basic Jetpack Cloud styles and Calypso color scheme.
It's best to test it out after #39011 is merged so that the sidebar has some structure:
* Add basic Jetpack Cloud styles
* Add Calypso color scheme for Jetpack Cloud
It's best to test after #39011 is merged. Optionally, you can rebase locally in order to see the Jetpack Cloud sidebar.
* Go to http://calypso.localhost:3000/jetpack-cloud
* Confirm that some basic styles are used on the page (custom fonts, Cloud color scheme, etc.)
Fixes n/a
=> Jetpack Cloud: add basic styles

client/lib/plans/constants.js, client/lib/plans/features-list.js, client/lib/plans/plans-list.js
* Implement copy updates to the plan features tooltip seen in `/plans/{SITE_SLUG}` page while logged in. Check paObgF-Iu-p2 for context.
* Check the tooltip for each feature in /plans and verify that the relevant copy updates are in place.
=> Plan features tooltip copy updates

client/state/jetpack-sync/selectors.js, client/state/jetpack-sync/test/reducer.js, client/state/jetpack-sync/test/selectors.js, client/state/jetpack-sync/utils.js
* Ensures that the full sync UI in Settings -> Manage Site Connections works with the newly designed full sync.
* Get this branch running locally at calypso.localhost:3000
* Ensure you get progress updates when you run a full sync for a Jetpack site
* Find this UI in Settings -> General -> Manage Your Connection
* Try with both a Jetpack site running latest stable, and a Jetpack site running bleeding edge
=> Jetpack: fix full sync UI

client/state/jetpack-sync/reducer.js, client/state/jetpack-sync/test/reducer.js
Currently if a site doesn't have a lot of content to sync the progress bar never updates as it is stuck in initiating state. 
Update the sync status check so that when checking for status updates it can toggle to the progress bar if the sync requested has already finished.
* Connect a Site via Jetpack with a small amount of content, (A new site with default content works
* Go to Settings > General > Site Tools > Manage Your Connection
* Click on "initiate a full sync"
* Progress bar will display "Full sync will begin shortly" and not progress further
Apply Patch 
* Click on "initiate a full sync"
* Progress bar will display "Full sync will begin shortly" 
* Progress bar will update to "Full sync in progress"
* Progress bar will update to "Last fully synced a few seconds ago"
=> Update Jetpack Sync Status to handle fast completes

client/my-sites/migrate/components/sites-block/index.jsx, client/my-sites/migrate/components/sites-block/style.scss, client/my-sites/migrate/section-migrate.jsx, client/my-sites/migrate/section-migrate.scss, client/my-sites/migrate/step-import-or-migrate.jsx, client/my-sites/migrate/step-source-select.jsx
* This PR introduces a single Site Information component that can is reused in multiple views in the flow, instead of ad-hoc implementations for the site information view.
* Go to Migrate
* Enter Site URL
* Continue
* Confirm that you want to perform a migration
* Take notice of the source and destination site information in the views. It should be updated properly between steps.
=> Site Migration: Unify Site information Component between views

client/components/domains/register-domain-step/index.jsx, client/lib/abtest/active-tests.js, client/signup/steps/domains/index.jsx
* This PR removes an AB test. You can find more information here p8Eqe3-ZD
* The AB test definition `domainStepMoveParagraph` should not appear in the AB tests menu.
* Go to the Domains step and before typing anything, verify that the design looks like this:
* Type anything in the search form. 
* If you are assigned to the `control` group of the `domainStepCopyUpdates` test, it means you're in the Holdout group, so you should not see the `domainStepCopyUpdates` from https://github.com/Automattic/wp-calypso/pull/37661. Verify the following:
- The domain step UI and copy remain the same as before (no copy updates, no explanation paragraph).
- Complete signup and check the launch flow steps - they should remain unchanged
* If you are assigned to the …
=> Removing Domain move paragraph test

client/blocks/upsell-nudge/style.scss
* With a medium length title, call to action, and dismiss action, the compact nudge gets crowded. This adds some margin between the title and the button to prevent that.
**Before**
**After**
* Add an `UpsellNudge` in the sidebar in the render function of `/client/current-site/notice.jsx`
* Enable the `dismissPreferenceName`, `callToAction`, and add a medium or long-length `title` as component properties.
* Check visual appearance on multiple screen widths.
=> UpsellNudge: Fix for spacing in narrow display areas

client/lib/signup/step-actions.js, client/signup/config/flows-pure.js, client/signup/config/step-components.js, client/signup/config/steps-pure.js
Part of #38937 
* Update frankenflow to get `theme` and `siteTitle` as query params and use them when creating a site.
* While being already logged in, go to http://calypso.localhost:3000/start/frankenflow?theme=stratford&siteTitle=mywebsite
* After ending the flow and landing in Home check the theme and site title to be as expected.
=> Frankenflow: get theme and site title from query

client/my-sites/stats/site.jsx
Fixes https://github.com/Automattic/wp-calypso/issues/14253 where we'd see infinite loaders for a Jetpack site that has the stats module disabled. Changes here will display a prompt to enable stats.
Folks are welcome to commit directly to this branch if work here is of any interest.
- With a Jetpack or Atomic Site disable stats in Marketing > Traffic
- Visit /stats
- Instead of infinite loaders we should see a prompt to enable the stats module
- Switching a site to a simple site or site with enabled modules should not display this prompt (Please also try on a fresh indexedDB cache )
- Clicking on Enable Stats will update the module setting, and display stats.
We also fire a related tracks event:
=> Stats: display prompt to enable stats when stats module is disabled

packages/composite-checkout-wpcom/src/components/wp-terms-and-conditions.js
Fixes: https://github.com/Automattic/wp-calypso/issues/38968
**Before:**
**After:**
* Get Calypso up and running locally or via Calypso.live
* Add a product to the cart and make your way to checkout
* Add the following query string to your url: `?flags=composite-checkout-wpcom`
* Make your way to the end of checkout. 
* See if the TOS is visible on desktop and mobile layouts.
=> Composite checkout: fix scroll issue on mobile

client/blocks/upsell-nudge/style.scss
* Ran into an issue while deploying #38881 where sometimes the text of the UpsellNudge would turn dark gray upon visiting the call to action. It appears to be Banner's SCSS overwriting UpsellNudge; making this rule more specific should fix it.
**Before**
**After**
* Visit a site on a free plan, no domain attached, with A/B test `sidebarUpsellNudgeUnification` set to `variantShowUnifiedUpsells`
* You should see an UpsellNudge like the above in the sidebar. 
* Click the UpsellNudge call to action. 
* Verify the text remains white and legible.
=> UpsellNudge: Make SCSS more specific to override Banner properties

apps/notifications/src/panel/boot/stylesheets/main.scss, apps/notifications/src/panel/boot/stylesheets/shared/sizes.scss
This is a follow-up to #38647 due to feedback that increasing the title font size to 16px was too big. As per @osullivanchris this reverts it to 14px and adjusts the line height to 1.4.
See p9zg7s-5h-p2
**Before:**
**After:**
* Check the notifications panel with various sorts of notifications and make sure the styles look consistent
* Particularly look for any issues with height overflow in long post titles
=> Notifications panel: Revert title size back to 14px

client/landing/jetpack-cloud/index.js, client/landing/jetpack-cloud/routes.js, client/landing/jetpack-cloud/section.js, client/landing/jetpack-cloud/sidebar.jsx, client/server/pages/index.js, config/jetpack-cloud-development.json, config/jetpack-cloud-production.json, config/jetpack-cloud-stage.json
This PR is an experiment to make the Jetpack Cloud work as a separate development and production instance by taking advantage of new Calypso environments. Here we're introducing 3 new environments:
* `jetpack-cloud-development` - Local, development environment. This is the Jetpack Cloud version of the regular Calypso development environment.
* `jetpack-cloud-stage` - Staging environment. This is the Jetpack Cloud version of the regular Calypso staging environment, which is close to the production one but used for testing (when proxied) before deploying to production.
* `jetpack-cloud-production` - Production environment. This is the Jetpack Cloud version of the regular Calypso production environment. 
Those will be accessible in their corresponding domains, as follows:
* …
=> Jetpack Cloud: Use separate environments

packages/composite-checkout-wpcom/src/components/form-field-annotation.tsx, packages/composite-checkout-wpcom/src/components/wp-contact-form.js
Fixes: https://github.com/Automattic/wp-calypso/issues/38969
Before:
After:
* Get checkout running locally or use Calypso.live
* Add a plan + domain to your cart
* Check the field in Safari's Developer > Responsive mode to make sure the field doesn't expand out of view.
=> Fix select drop down

client/components/foldable-card/index.jsx, client/my-sites/customer-home/main.jsx, client/my-sites/customer-home/style.scss
* This replaces the Card used for the Site Tools with a Foldable Card, so that on mobile, it can be collapsed
On desktop, things shouldn't change. It shouldn't be possible to collapse the column.
However, on mobile, it should be possible to collapse the tools.
This is how it should look like after the card has been expanded, following the design in the original issue.
Fixes #39005
=> Customer Home: Collapse Site Tools on Mobile

client/components/foldable-card/README.md, client/components/foldable-card/docs/example.jsx, client/components/foldable-card/index.jsx
* This adds a `highlight` prop to the `FoldableCard` component. This passes this prop to the container component.
* Run Calypso with `npm start`.
* Navigate to http://calypso.localhost:3000/devdocs/design/foldable-card.
* Examine card in devdocs.
Screenshot:
Related ticket: 1156570014567299-as-1159067512361665.
=> Adds highlight for FoldableCard component

client/me/purchases/remove-purchase/index.jsx
Related to https://github.com/Automattic/wp-calypso/pull/38266
As confirmed there, it's OK now to remove domain registrations on Atomic sites. It should also be OK to remove domain mappings now - it's driving a lot of support requests right now.
Try to remove a domain mapping on your Atomic site - verify that it's still working afterwards!
=> Domains: Allow users to remove domain mapping from Atomic sites

client/my-sites/sites/index.jsx, client/state/sites/selectors/can-current-user-use-customer-home.js, client/state/sites/test/selectors.js
This PR makes sure that Customer Home will not load for VIP sites for now.
- Try visiting /home with a new VIP site or with an older VIP site with the date check in `/client/state/sites/selectors/can-current-user-use-customer-home.js` commented out
- Verify that the section does not load and redirects to stats
=> Customer Home: explicitly exclude VIP sites from loading Customer Home

client/my-sites/customer-home/main.jsx, client/state/sites/selectors/can-current-user-use-customer-home.js, client/state/sites/test/selectors.js, config/desktop.json, config/development.json, config/horizon.json, config/production.json, config/stage.json, config/test.json, config/wpcalypso.json
Fixes https://github.com/Automattic/wp-calypso/issues/38999 
This PR adds a new feature flag `home/all` enabled in `development` and `horizon`, that skips the site age check if the flag is set to true and also fixes a small bug where an empty checklist would render for sites created before Aug 19th.
- Should we include VIP sites? I can update logic to filter them out. **Answer:** We'll exclude VIP sites for now.
p9GBOq-1A2-p2
- Create a new site on WordPress.com
- Checkout this branch, verify that "My Home" is visible in sidebar and that a checklist renders in the page
- Switch sites to a site created before Aug 2019. The checklist should not render and instead we should see Site tools
- Customer Home should not be visible to Jetpack or VIP sites
=> Try Enabling Customer Home for all Simple and Atomic Sites

client/components/web-preview/content.jsx
* Hide the URL in the Calypso site preview on smaller breakpoints. This gives everything room to breathe on smaller devices.
**375px Before**
**375px After**
**768px Before**
**768px After**
* Checkout this branch locally or using the calypso.live link
* Click the site card in the sidebar to view the site preview
* Resize the browser window
* Make sure the URL is hidden below `960px` and shows on higher breakpoints
Fixes #38099
=> Calypso Site Preview: Simplify site preview toolbar by hiding URL on smaller breakpoints

client/my-sites/migrate/components/import-type-choice/index.jsx, client/my-sites/migrate/components/import-type-choice/style.scss, client/my-sites/migrate/components/sites-block/index.jsx, client/my-sites/migrate/components/sites-block/style.scss, client/my-sites/migrate/section-migrate.scss, client/my-sites/migrate/step-import-or-migrate.jsx, client/my-sites/migrate/step-source-select.jsx
* Polish the styles for the migrate section
* Use proper form components for accessibility
* Fix a loading state bug when submitting the source site URL
* These styles do not affect mobile viewports yet since this is still behind a feature flag
Before | After
* Visit `/migrate/{site}` with the `tools/migrate` feature flag enabled
* Make sure the styles look like the screenshot above
=> Migrate: Polish up the visual styles

apps/full-site-editing/full-site-editing-plugin/starter-page-templates/page-template-modal/styles/starter-page-templates-editor.scss
Reverts Automattic/wp-calypso#39002 since this doesn't seem to be having the desired effect in production.
=> Revert "Starter Page Templates: fix preview style override specificity"

client/my-sites/customer-home/main.jsx
This makes the change suggested by @kwight in #39075: 
> I'm wondering about the component being conditional on is_mobile() (eg. if mobile, display FoldableCard, otherwise, display Card)? It would be more verbose, but magical whitespace values are a little harder to reason about when reading the code.
This should be the same as #39075, as there should really be no visible changes. It may also be worth confirming that the still buttons work.
=> Customer Home: Make Site Tools Card Conditional

client/blocks/upwork-banner/style.scss, client/my-sites/themes/theme-showcase.scss
Fixes https://github.com/Automattic/wp-calypso/issues/38048 reported by @arunsathiya.
The Upwork banner has invisible button text when displayed on the Themes page:
This PR fixes it.
1. Choose one of your sites (either Jetpack or Atomic) and go to `/themes`. 
2. Scroll down and click the 'Show all themes' button.
3. Look for the Upwork banner. If you don't see it, you might need to add yourself to the `builderReferralThemesBanner` A/B test like so:
Ensure that the button text is legible.
After:
=> Upwork: fix invisible button text in Themes

client/my-sites/stats/stats-list/action-spam.jsx, client/my-sites/stats/stats-list/style.scss
Prefixes the "Spam" text with "Mark as" for clarity in stats
Visit the Stats page and look at the Referrers column. On a referral with an ellipses Gridicon next to it, click it and compare the text.
**Before:**
**After:**
Then mark the item as spam, and hover over it again to see the other label change.
Fixes #38875
=> Stats: Improve Clarity of Marking Spam Text

client/lib/signup/step-actions.js, client/my-sites/checkout/checkout/secure-payment-form.jsx, client/state/selectors/get-new-site-coming-soon-setting.ts
This diff makes sure the `wpcom_coming_soon` option is set for all new sites. For now just behind a feature flag.
1. Apply D38260-code
1. Open calypso.localhost 
1. Create a new site
1. Confirm it has `wpcom_coming_soon` option set to 1
1. Try this diff on calypso.live
1. Create a new site
1. Confirm it does **not** have the `wpcom_coming_soon` option at all
=> [Coming soon] Set wpcom_coming_soon option for new sites

apps/full-site-editing/full-site-editing-plugin/full-site-editing/blocks/template/edit.js, apps/full-site-editing/full-site-editing-plugin/full-site-editing/blocks/template/style.scss
*  Updates styles for FSE template part in editor.
**Before**
**After**
Note - In the time between click and release to load the template part editor, the block toolbar shows up in the top left of the template part as seen below:
It seems that this used to be hidden by nesting the toolbar's `display: none;` inside the  `.template__block-container` ruleset.  With recent changes it seems that this toolbar is no longer a child of the block that triggers it, making it difficult to hide this toolbar without also hiding the toolbars for other blocks in the FSE editor.  Given that this is only visible for a very brief time in practice and that this editor is being phased-out, it is probably best to allow this brief period of visibility.
1. Checkout this PR.
2. Sync the changes to your sandbox. …
=> Fix FSE template part styles.

client/server/pages/index.js
* Add a redirect for the production cloud.jetpack.com to be redirected to jetpack.com
1. Run npm start. 
2. Make sure that everything still works as expected. 
3. If everything looks good shut down calyspo
4. Run CALYPSO_ENV=jetpack-cloud-production npm start
5. Your browser should get redirected to jetpack.com
=> Jetpack Cloud: Add Jetpack Cloud Production redirect

client/landing/gutenboarding/onboarding-block/signup-form/index.tsx
* Remove TypeScript hack that's no longer needed now that DefinitelyTyped/DefinitelyTyped#41800 has shipped.
* Run CI
* Modal should still appear at `/gutenboarding/signup`
=> Remove TypeScript hack for <Modal> that's no longer needed

client/landing/gutenboarding/components/header/index.tsx, client/landing/gutenboarding/stores/onboard/actions.ts, client/landing/gutenboarding/tsconfig.json, client/landing/gutenboarding/utils.ts, client/lib/signup/step-actions.js, client/signup/config/flows-pure.js, client/signup/config/step-components.js, client/signup/config/steps-pure.js
Fix #39101 
Part of #37329 by creating the site in which we open the `block-editor`
* Using domain name, site title and design from Gutenboarding we are creating a site for a logged in user (or for a passwordless sign up using http://calypso.localhost:3000/gutenboarding/signup
* The user lands in block-editor of the newly created site where https://github.com/Automattic/wp-calypso/pull/39048 will add the Launch button that redirects to `start/frankenflow` for launch.
* Until https://github.com/Automattic/wp-calypso/issues/38904 is done, a user could manually access the frankenflow launch flow by going to `/start/frankenflow?siteSlug=DOMAIN_NAME` after the site has been created.
* With a logged in user, go through Gutenboarding and press Create my site.
* [Optional] In a clean browser …
=> Gutenboarding: add site creation and frankenflow launch

client/my-sites/customer-home/main.jsx
Originally reported by @andrewserong in p1580270924269500-slack-dotcom-manage
Fixes a regression that was included in https://github.com/Automattic/wp-calypso/pull/39071 causing the checklist to be displayed even if it is completed.
Before | After
--- | ---
* Create a new site.
* Complete the checklist.
* Make sure the Site Tools are displayed when the checklist has been completed.
=> Customer Home: Show Site Tools when checklist is complete

client/lib/url/support.js, client/my-sites/domains/domain-management/transfer/transfer-out/unlocked.jsx
As part of a small usability fixes we're working on for the domain management screens this will change where the "Learn more" link sends you
* Update the Learn More link on the unlocked domain screen to point to the relevant support doc section
* Unlock a domain and click on the "Learn more" link
=> Domains: Fix the transfer out support link to point to the correct section

client/my-sites/plan-features/index.jsx
Before:
After:
On mobile after:
* Login as an admin to a site that you didn't pay for the plan for. 
http://calypso.localhost:3000/plans/example.com
=> Plans: update the plans page copy for users that are not the main plan owner.

client/landing/jetpack-cloud/layout.js, client/server/pages/index.js
* This adds logic for 404 and 500 error pages for Jetpack Cloud. These pages are loaded using the same component as Calypso pages, but load the Jetpack Cloud CSS instead.
* Build Jetpack Cloud via `CALYPSO_ENV=jetpack-cloud-development npm start`.
* Go to route that doesn't exist.
* Observe error page.
* Build Calypso and smoke test.
Fixes 1156570014567299-as-1159128713000441
=> Jetpack Cloud error pages

client/my-sites/site-settings/site-tools/index.jsx, config/development.json, config/horizon.json, config/stage.json, config/wpcalypso.json
This PR eliminates the `rewind/site-cloning` feature flag and makes the `Clone` option available in all Calypso environments.
Navigate to Manage > Settings and scroll to the bottom. You should see the clone option available in the Site Tools section, and clicking it should link to the cloning flow.
=> Jetpack Backups: Enable site cloning for all Calypso environments

client/blocks/upsell-nudge/style.scss
I'm in the process of applying `UpsellNudge` to different use cases to see how well it fits. Some CSS changes may be necessary to "tailor" it to our existing nudges if this is design we choose.
* Adjust border width on larger size nudges from 3px to 8px;
* Make nudge description slightly darker to stand out from the title.
The result should look something like this:
But the sidebar nudges should not be affected, since they're compact:
* Make sure you're using the `variantShowUnifiedUpsells` variation of the `sidebarUpsellNudgeUnification` A/B test
* Make sure the sidebar nudge design is visually unaffected
* For bonus points, implement an UpsellNudge (not the compact version) and check its visual styling.
=> UpsellNudge: Style tweaks for non-compact nudges

apps/full-site-editing/full-site-editing-plugin/full-site-editing/editor/style.scss
* Align full width blocks to the edge of the editor border. Something must have broken the styles in the last update.
**Before: Template Part Block.**
**After: Template Part Block.**
**Before: full width image**
**After: full width image**
I also verified that wide-width blocks work as expected.
* Build this and sync to your sandbox. Sandbox the site you'll test against.
* Open the FSE editor and verify that full width blocks are aligned to the editor frame. (Also double check a full-width block inside of the template part block.
=> FSE: Fix full width blocks in the editor

client/components/domains/register-domain-step/index.jsx
Since we introduced the "Best match" and "Best alternative" labels we're technically reordering the results from the suggestion endpoint. This leads to some unexpected results because we surface as "Best alternative" a result wich does not match exactly in the SLD part. However that shows up hyphenated result as second suggestion and we don't want that. Also it is reordering the results from the suggestion endpoint and we don't want to do that either since the suggestion provider should give us the best order. So this diff will stop reordering the suggestions.
* Don't reorder the suggestion results based on the SLD match
* Search for some unique domain name and make sure that the results are displayed in the same order they were in the suggestion endpoint results
=> Domains: Don't reorder the suggestion results

apps/wpcom-block-editor/src/calypso/editor.js, apps/wpcom-block-editor/src/calypso/features/gutenboarding-editor-overrides.js, apps/wpcom-block-editor/src/calypso/features/gutenboarding-editor-overrides.scss, apps/wpcom-block-editor/src/calypso/features/iframe-bridge-server.js, apps/wpcom-block-editor/src/calypso/features/launch-button-override.js, apps/wpcom-block-editor/src/calypso/features/launch-button-override.scss, client/gutenberg/editor/calypsoify-iframe.tsx
Adds an optional override to update the wpcom-block-editor for gutenboarding purposes.
Currently, this override will happen if both of two conditions are `true`:
1.  `config.isEnabled( 'gutenboarding' )` - Which is currently true only in development and wpcalypso (calypso.live) environments.
2. `is-gutenboarding` query param is present.
When enabled, the settings bar in the top right of the editor is changed from:
To:
* The "Save" button is currently a re-styling of the original "Update" or "Publish" button.
* The "Launch" button is wrapped in an <a> tag leading to the frankenflow.
* Run this PR on calypso.
* Build and Sync wpcom-block-editor to your sandbox.  You can patch `D38314` or alternatively run `./bin/calypso/build-wpcom-block-editor.sh 583382` on your sandbox, where '583382' …
=> Gutenboarding - Add editor overrides + "Launch" Button

client/my-sites/customer-home/main.jsx
"My Site" provides a link to edit the homepage which is already part of the checklist, and "Grow & Earn" are likely premature steps before users finish setting up their sites.
In order to save some space, this PR hides the "My Site" and "Grow & Earn" cards from the Customer Home until after the checklist has been completed. 
* Create a new site.
* Launch it.
* Make sure the "My Site" and "Grow & Earn" cards are not visible in `/home/:site`.
* Complete the checklist.
* Make sure the "My Site" and "Grow & Earn" cards are visible now.
Part of #39119
=> Customer Home: Hide "My Site" and "Grow & Earn" cards if checklist is uncompleted

client/my-sites/domains/domain-management/list/index.jsx, client/my-sites/domains/domain-management/list/style.scss
Since we shoul the nudge both in the navigation and in the domain management screen @fditrapani suggested that:
* we should use the same style (color and icon) for both nudges
* we should hide the nudge on desktop and only show it in the mobile so that we don't have 2 versions of the same nudge on screen
* get a plan for a site but without a domain
* open the Manage > Domains screen - you should only see one nudge in the navigation. If you go in the mobile version you should see the nudge in the navigation menu and in Manage > Domains
=> Domains: Unify the free domain nudge in the domain management screen

apps/wpcom-block-editor/src/calypso/features/gutenboarding-editor-overrides.js
Fixes #39167
Apply D38314-code.
- Sandbox `widgets.wp.com` and your site's WordPress.com URL.
- Visit a URL like the following: https://wpcalypso.wordpress.com/block-editor/post/SITE_SLUG?is-gutenboarding
- You should see "Launch" in the header with HTML like the following:
```html
<a href="https://wpcalypso.wordpress.com/start/frankenflow?siteSlug=XXXX" target="_top" class="gutenboarding-editor-overrides__launch-button components-button is-primary">Launch</a>
```
=> Block editor: Remove wrapped Launch a > button

client/landing/jetpack-cloud/components/log-item/docs/example.tsx, client/landing/jetpack-cloud/components/log-item/index.tsx, client/landing/jetpack-cloud/components/log-item/style.scss, client/landing/jetpack-cloud/controller.js
* This adds a new component to Jetpack Cloud, `LogItem`, used to display log entry items.
* Build and run Calypso with `npm start`.
* Navigate to http://calypso.localhost:3000/jetpack-cloud.
* Examine landing page for log entries.
Related ticket: 1156570014567299-as-1159067512361665.
Relies on #39093 to display highlight. Note that highlight colors aren't quite as expected, so will need to resolve that with a separate PR.
=> Creates LogItem component for Cloud logs

client/landing/gutenboarding/onboarding-block/design-selector/style.scss
After taking a look at Issue #38665 created by @razvanpapadopol, I thought I would spin up a quick branch with the style rules for hover / focus that were being recommended.  
I don't think these are necessarily better than what is currently in place, but figured I could open up a PR to share.
If we were to keep going down this route, I would think we should:
1 - get rid of the 1px of white border interior to the blue border on the focus style.
2 - ~set focus for items on hover, so the focus outline doesn't seem so odd by staying on the last selected card while hovering others.~   This can be handled with `lib/accessible-focus` as seen on #39156
* Run this PR on Calypso and nitpick at the hover/focus styles in gutenboarding page selection.
Fixes #38665 ?
=> Gutenboarding - update design picker focus hover

client/my-sites/checkout/checkout/secure-payment-form.jsx
As private sites support becomes available on Atomic platform, this PR makes sure we don't switch atomic sites to `blog_public=1` on upgrade.
This PR is not testable yet, it depends on a few other PRs. I will update this description once we're ready to test it.
1. On calypso.localhost:
1. Create a new site on a free plan, make sure it's a private+coming soon site
1. Upgrade to business
1. Install a plugin
1. Confirm your site is still private+coming soon
=> [Coming Soon] Stop launching atomic sites on upgrade

client/my-sites/customer-home/style.scss
* When there's a fair amount of text in a two-column button, like "Write Blog Post", the button might wrap to two lines, which looks messy.
* This bumps up the breakpoint for two-column buttons from 1280px to 1400px to give the text some room.
* This should also help for languages that trend toward longer words.
**Before**
1280-1323px "Write Blog Post" breaks to two lines
**After**
Less than 1400px but greater than 1040px
Greater than 1400px
* Open a site with Customer Home that has:
- Launched
- The front page set to the Blog Posts page; go to Customizer -> Homepage Settings -> Check Your latest posts
* You should see "Write Blog Post" as the primary action of the site
* Check the page at multiple screen sizes to verify the action button text doesn't break to two …
=> Customer Home: Make the breakpoint for two-column buttons under My Site wider

client/components/environment-badge/style.scss, client/server/pages/index.js
* Adds an environment badge for Jetpack environments.
* Build Jetpack Cloud via `CALYPSO_ENV=jetpack-cloud-development npm start`.
* Let it build, then visit the dashboard page. See environment badge!
* Build Jetpack Cloud staging.
* Start it and visit the dashboard page. See the environment badge.
Screenshots:
Fixes 1156570014567299-as-1159371543675235.
=> Adds Jetpack Cloud environment badges

client/my-sites/activity/activity-log/threat-alert.jsx
* Update split menu to highlight support first on non-fixable threats.
* Moves `Get help` to the splitMenu face and hides `Ignore threat` inside the menu.
* See p6TEKc-3qn-p2 for more context.
* Open the Activity log with a site that contains active non-fixable threats.
* Ensure the menu has the right order and that all actions work as expected.
Would love to add tracking to the `Get help` option, any takers?
=> Activity log: highlight support first on non-fixable threats

client/signup/config/flows-pure.js
#39145 removed the `rewind/site-cloning` to fully enable the feature, but there is a place left that still checks for the flag. Remove that flag check to fix the flow.
For a dotorg site that has Jetpack Backup enabled and valid site server credentials, go to Settings->general. Clicking on "Clone" should lead to the clone flow, not `https://wordpress.com/start/site-type`
=> Fix the Jetpack "Clone" site tool

client/my-sites/domains/domain-management/edit/wpcom-domain.jsx, client/my-sites/domains/paths.js
* add "Pick a Custom Domain" in the WPCOM domain vertical navigation
* Open any wpcom domain and check if the "Pick a Custom Domain" vertical navigation item is there
* Verify that it works the same way for .blog subdomains and for wpcomstaging subdomains
=> Domains: Add "Pick Custom Domain" link in domain management for WPCOM domains

client/me/purchases/remove-purchase/index.jsx
Related to https://github.com/Automattic/wp-calypso/pull/39084
As reported on p2MSmN-7Hr-p2, looks like we missed the domain transfer-in case. So let's lift the restriction on that too.
After the patch, canceling a Domain Transfer should be possible from `/me/purchases`:
=> Domains: Allow cancellation of domain transfer ins on Atomic sites

client/landing/gutenboarding/index.tsx, client/landing/gutenboarding/onboarding-block/design-selector/style.scss
* Adds `accessible-focus` to gutenboarding.
* Refactors design selector CSS to nest focus styles inside the `.accessible-focus` class.
**Notes** . `accessible-focus` adds the `.accessible-focus` class to the html element on the document when keyboard commands are used, and removes this when mouse clicks are detected.  Focus effects that we do not want present in a non-accessibility use setting can now be nested under the `.accessible-focus` class to prevent them from appearing in standard use.
* Run this PR in Calypso.
* Navigate to the Gutenboarding page selectors.
* Verify focus styles do not show up until keyboard triggers (tab) are used.
* Verify clicking selections does not leave focus styles once un-hovered.
Fixes #39138
=> Gutenboarding - add accessible focus

client/my-sites/migrate/step-source-select.jsx
* Replace a duplicate usage with already existing method that was created based on the code being replaced.
* Go to a WPCOM simple site
* Go to Migration
* Try to migrate a Blogger site
* You should land on the Blogger importer
* There should be no JS errors
=> Site Importer: Simplify/unify duplicate logic in code

client/components/purchase-detail/style.scss
* Noticed this while I was testing another PR; on the Plans page cards, the button text on mobile devices is left aligned, which is unexpected for a full-width button. This PR centers the button text for small screens.
**Before**
**After**
* Navigate to `/plans/my-plan/` on a small screen or mobile device < 480px wide.
* Scroll to view the cards; the button for each should have centered text.
=> Plans: Fix button text alignment on small screens

apps/full-site-editing/full-site-editing-plugin/starter-page-templates/page-template-modal/components/template-selector-item.js, apps/full-site-editing/full-site-editing-plugin/starter-page-templates/page-template-modal/index.js, apps/full-site-editing/full-site-editing-plugin/starter-page-templates/page-template-modal/styles/starter-page-templates-editor.scss
This PR will address the changes needed in https://github.com/Automattic/wp-calypso/issues/38811.
* Update the template selector modal to support categorization of page templates that have more than one template for a category.
Companion diff: ~D38317-code~ (deployed)
1. Check out this branch and build a copy of the FSE plugin
2. Apply D38317 on your sandbox and make sure public-api.wordpress.com is pointing there
3. Run and activate the FSE plugin and Gutenberg plugin on a WordPress install
4. Add a new page and confirm you see the equivalent to https://github.com/Automattic/wp-calypso/pull/39120#issuecomment-579899372
5. Confirm that templates are all selectable and insert correctly.
Fixes #38811
=> SPTs: Add new templates and template organization

apps/full-site-editing/full-site-editing-plugin/full-site-editing/blocks/template/style.scss, apps/full-site-editing/full-site-editing-plugin/full-site-editing/editor/style.scss, apps/full-site-editing/full-site-editing-plugin/full-site-editing/plugins/editor-template-classes/index.js, apps/full-site-editing/full-site-editing-plugin/starter-page-templates/page-template-modal/styles/starter-page-templates-editor.scss
Continuation of https://github.com/Automattic/wp-calypso/pull/39035. (See some context there)
I also audited all uses of `.editor-` classnames and have fixed everything which has changed on the current Gutenberg master branch.
* Fixes whitespace at the bottom of the page/template editor
* Fixes case where template block toolbar would display
* Fixes case where template block outline would display
* Renames all `.editor-` classnames to the `.block-editor-` equivalents.  (excluding newspack articles block)
* Fixes an issue where our template editor classNames were not applied to the correct parent div. This was causing the dotcom FSE nav block to not be targeted by the theme CSS, which looked really ugly.
- Run this locally and make sure that SPT and FSE editors have correct styles, …
=> FSE: Update styles to reference new changes in Gutenberg

client/state/sharing/services/selectors.js
* Changes the google drive service name to match a recent change to this on the server end.
* Apply this patch on your local calypso install and also set google-drive to false in config/development.json
* Go to /marketing/connections/{site-name} and make sure Googe Drive does not appear as one of the connection options
=> Change google drive service name to match changes on server

client/lib/i18n-utils/switch-locale.js
To determine the locale slug to set as the `<html lang>` attribute, use the special translation string `html_lang_attribute` that WordPress translation files provide.
Removes the need to retrieve that info from the list in the `client/languages.js` module. The translations files should be the preferred source of truth of all things i18n.
The `client/languages` module should be eventually used only by the Language Picker UI and should be removed from the entrypoint JS chunks (another little win for bundle size).
Choose one of the languages where the HTML lang attribute will be different from the language slug. I.e., `sr_latin`, `de_formal` or `es-mx`.
To test this even better, find some language where the translation file has different values for `html_lang_attribute` and …
=> i18n: get the value of HTML lang attribute from a special translation string

client/landing/gutenboarding/onboarding-block/design-selector/index.tsx, client/landing/gutenboarding/onboarding-block/edit.tsx, client/landing/gutenboarding/steps.ts
- When user enters page selection, the url should be `/gutenboarding/pages`.
- `isPageSelectorOpen` state should be replaced with `showPageSelection` prop to be able to control this routing behaviour.
**Test Case 1: Ensure that the `/gutenboarding/pages` route is pushed:**
1. Go to gutenboarding page `/gutenboarding`.
2. Pick a site name & pick a design.
3. Now you're in page selector page, the url on the address bar should be `/gutenboarding/pages`.
**Test Case 2: Ensure that route is changed when exiting page selection:**.
1. When in page selection mode, try the following to exit page selection: 
- Press <kbd>ESC</kbd>.
- Click outside of the page selection modal.
- Click the browser's Back button.
2. The url on the address bar should be `/gutenboarding/design`.
**Test Case 3: Ensure …
=> Gutenboarding: Route for page selection.

client/me/purchases/confirm-cancel-domain/index.jsx, client/me/purchases/confirm-cancel-domain/style.scss
* Instead of using `SelectDropdown` component we can use a regular `FormSelect` control for the domain cancelation drop down
* Purchase a domain and then go and cancel it within the refund period
* You should see a "Please let us know why you wish to cancel" drop down
* Test that it works as it was working before the PR
=> Domains: Replace the domain cancellation drop down with a regular control

client/components/domains/contact-details-form-fields/style.scss, client/my-sites/domains/domain-management/components/designated-agent-notice/style.scss, client/my-sites/domains/domain-management/edit-contact-info/form-card.jsx
We fixed some small issues with the domain contact screen usability.
* don't show the cancel button
* return to previous page on successful update
* remove unnecessary padding at the bottom
* Open "Contacts and Privacy" and click on "Edit Contact Info"
* Verify that the "60 days transfer lock text" is readable
* Verify that there is no extra padding below the form button
* Verify that there is no Cancel button
* Verify that when contacts are successfully updated you're redirected back to the "Contacts and Privacy" screen
=> Domains: Fix contact edit screen usability

apps/full-site-editing/full-site-editing-plugin/full-site-editing-plugin.php
* Disables block when in WP CLI mode
* Disables block when request indicates the newspack-blocks plugins is being activated.
* Have the Full Site Editing plugin active on your test site.
* Activate Newspack Blocks plugin from plugins screen.
* Plugin should be activated and not show fatal errors from activation sandbox.
* Activate Newspack Blocks plugin from WP CLI
* Success message should be returned, no fatal errors.
Fixes https://github.com/Automattic/newspack-blocks/issues/324
=> Blog Posts Block: Disable for CLI and plugin activation

client/state/selectors/is-eligible-for-dotcom-checklist.js, client/state/selectors/test/is-eligible-for-dotcom-checklist.js
Fixes https://github.com/Automattic/wp-calypso/issues/39191
Until we add full Atomic support this hides the display of the site setup checklist until we add Atomic support.
=> Customer Home: Atomic Sites are not eligible for checklist until full support is added

client/me/purchases/remove-purchase/index.jsx
Atomic sites were not able to cancel their G Suite accounts without reaching out to support. Attempting to do so will prompt this dialog.
The restriction is removed so that G Suite can be canceled without support or HEs.
* Create an Atomic site (i.e. create or upgrade your WP.com account to the **Business** plan or higher ).
Ensure your site is launched/public, and that the hosting configuration is activated. 
* Create or access a  G Suite account in **Manage Purchases**
* Confirm that you are presented with the dialog when you attempt to remove the account
* Confirm that a subsequent attempt to remove the account is successful and that the dialog is no longer presented to you.
=> G Suite: Enable customers with Atomic Sites to self-cancel their G Suite account

client/lib/gsuite/index.js, client/me/purchases/product-link/index.jsx
The `G Suite Settings` link situated in the `Manage Purchases` section points to the external G Suite management URL. To create a better experience and provide consistency, the settings link is renamed to `Email Settings` and points to the corresponding `Email` page similar to the situation for domains.
Before | After
---|---
* Checkout this branch in a development server
* Visit the [manage purchases](http://calypso.localhost:3000/me/purchases) page
* Click on a G Suite subscription 
* Confirm that the `G Suite Settings` title now reads `Email Settings`
* Confirm that the link takes you to the corresponding `Email` page for the site/domain
=> G Suite: Change the G Suite Settings link title to Email Settings and the link URL to the corresponding page

client/landing/gutenboarding/onboarding-block/site-title.tsx
Pressing 'Enter' / 'Return' on site-title will now advance the flow to the next step.
This was achieved by:
*  Wrapping the site-title in a <form> tag instead of empty fragment.
*  Set the form's `onSubmit` function to push history to the next step in the Gutenboarding flow (design selection).
Alternatively, we could have negated adding the <form> tag by applying a function to `onKeyDown` of the input element to listen for the 'enter' keyCode.  I figured form submit may allow for more robust usage across browsers and custom accessibility settings, but if there are other downsides to this that I did not think of we can look into the other approach.
* Run this PR, start Gutenboarding.
* Verify pressing 'Enter' on the site-title input advances to the next step of Gutenboarding.
Fixes #39245
=> Gutenboarding - pressing 'Enter' on site-title to advance flow.

client/my-sites/migrate/components/sites-block/index.jsx, client/my-sites/migrate/components/sites-block/style.scss
* This PR adds a spinner in place of the Site Icon while the request to get information from the API is ongoing
* Go to migration
* Enter Site URL
* Press Continue
* You should see a spinner at the center of the dashed box.
=> Site migration: Add a spinner in the site icon when loading a site

client/blocks/login/social.jsx, client/blocks/signup-form/social.jsx
https://developers.google.com/identity/sign-in/web/reference#googleusergetauthresponseincludeauthorizationdata
props @ramonjd for noticing Zi != uc
* Replace transient `response.Zi` usage w/ `response.getAuthResponse()`
Context: pbAok1-gf-p2
* Sign in with Google
* Create an account with Google signon
=> Replace transient Zi usage w/ getAuthResponse

client/me/purchases/purchases-site/style.scss
* The concierge banner shown in /me/purchases page has an alignment issue in Safari, though it works well in Chrome / Firefox / Edge. This PR fixes the alignment issue.
* The issue appears to be due to Safari trying to take up the entire viewport height for the image in the concierge banner in a flexbox. I explored the option of using the css property `height:intrinsic` for the image on the concierge banner, but this property is still experimental(and not supported in other browsers). So, I've instead opted to go for an alignment fix. 
In Safari:
* On a site that has a Business plan, open /me/purchases page in Safari browser. 
* Verify that the concierge banner appears in normal size as shown in the Before/After image above.
* Verify that the banner appears in normal size in Chrome / FF / …
=> Concierge banner: Fix alignment in Safari browser

apps/full-site-editing/full-site-editing-plugin/starter-page-templates/page-template-modal/index.js
Fixes #39174
* On an existing page with a layout already selected, using the sidebar to change the selected layout to "Blank" will empty out the editor. Previously when selecting blank and returning to the editor the blocks from the existing layout remained.
* Create a new page and select a layout other than blank.
* Using the document sidebar in Gutenberg, select the "Change Layout" button.
* Select the "Blank" layout in the selector, and insert it.
* Confirm that all blocks from the previous template have been removed in the editor.
=> Layout Selector: Fix blank layout selection on existing page

client/lib/abtest/active-tests.js, client/lib/plans/test/get-popular-plan-spec.js
* The A/B test `nonEnglishDomainStepCopyUpdates` was removed in #38746 but was re-instated erroneously(due to a merge issue) in #38747. This PR removes all references to the A/B test since it's no longer running.
Fixes 188-gh-martech
This PR should have no effect since we are only removing unused code.
* Begin signup in a non-EN locale, for example at `http://calypso.localhost:3000/start/fr` and verify that you are shown the new domain step version(as per the screenshot in #38746).
=> Remove all usages of nonEnglishDomainStepCopyUpdates

client/my-sites/migrate/components/sites-block/index.jsx, client/my-sites/migrate/step-source-select.jsx
* This PR adds the option to submit the URL input field with the Enter key. Previously we were only able to do that with the Continue button
* Go to Migration
* Enter URL
* Press enter
* The form should procceed
=> Site Migration: Add option to submit the URL input with Enter key

client/lib/analytics/ad-tracking.js
Adding orderId was requested
1. In the config/development.json, turn on `ad-tracking` and `gdpr-banner`
2. Enable debug logs
```
localStorage.setItem( 'debug', 'calypso:analytics:*' );
```
3. Make sure GDPR doesn't block tracking
```
document.cookie = 'sensitive_pixel_option=yes;'
```
4. Reload
5. Click Preserve Logs in the console
6. Enable the store sandbox
7. Buy a plan
8. In the console, filter by Pinterest
9. Make sure order_id is present, according [to the documentation](https://developers.pinterest.com/docs/ad-tools/conversion-tag/?)
Fixes #
=> Add orderId to the Pinterest pixel

client/my-sites/migrate/step-source-select.jsx
* Add functionality to show errors when an unsupported site is entered in the URL box.
Note: The code contains reference to WordPress.com sites, but this is not working at the moment as it requires an API change. 
* Checkout branch or use Calypso.live branch 
* Go to migration
* Enter a site that's not a WordPress site. 
* See an error that this is not a WordPress site.
This PR is based off #39257
=> Site Migration: Add support for showing errors when a customer enters an unsupported URL

client/my-sites/sidebar/index.jsx
Back in #9764, filtering was added so that new users after September 7, 2015 would not be given a WP Admin sidebar item for their Simple sites. This PR removes this filtering, now that it is no longer considered beneficial; the link should show for all sites of any user.
- With a user created before Sept 7, 2015, ensure the WP Admin link is present with all site types (Simple, Jetpack, Atomic, VIP).
- Go through signup (https://wordpress.com/start/) in an Incognito window and create a new user and site.
- Add that user to one of each site type.
- Verify the WP Admin link is present for that user for all site types.
Fixes #36241.
=> Sidebar: Display the WP Admin menu item for all users.

client/my-sites/migrate/components/sites-block/index.jsx, client/my-sites/migrate/migrate-button.jsx, client/my-sites/migrate/section-migrate.jsx, client/my-sites/migrate/section-migrate.scss, client/my-sites/migrate/step-confirm-migration.jsx, client/my-sites/migrate/step-import-or-migrate.jsx, client/my-sites/migrate/step-upgrade.jsx
* Refactors `MigrateButton` to use `children` instead of having a fixed label
* Removes `MigrateButton` (with `confirm` prompt) from import or migrate step and replaces it with a standard button (as the confirmation isn't needed on that step)
* Adds `MigrateButton` to upgrade step unconditionally (as the confirm will always be required on that step)
* Conditionally used `MigrateButton` on confirmation step, as the confirm dialog should only be shown on the step immediately before migration begins or the cart is navigated to.
* Refactors `SitesBlock` to accept either `sourceSiteInfo`, or `sourceSite`.
* Updates all prior uses of `sourceSite` (which was really just the info, not the site object) to `sourceSiteInfo`.
* Adds `MigrateButton` and checklist to confirmation page.
* Refactors the …
=> Site Migration: Update the confirmation page and move the confirmation prompt to final pre-migration step

client/landing/gutenboarding/devtools.ts, packages/data-stores/src/index.ts, packages/data-stores/src/site/actions.ts, packages/data-stores/src/site/constants.ts, packages/data-stores/src/site/controls.ts, packages/data-stores/src/site/index.ts, packages/data-stores/src/site/reducer.ts, packages/data-stores/src/site/selectors.ts, packages/data-stores/src/site/types.ts, packages/data-stores/src/utils/wpcom-wrapper.ts
This PR adds a Site data store, responsible for making API calls to create a new site using the `sites/new` endpoint. It follows the same basic pattern as the User store added in https://github.com/Automattic/wp-calypso/pull/38823.
* Add a Site data store to fire off requests to create a new site via the `sites/new` endpoint
* Store information about the created site
* Support passing in a bearer token to create the site (allowing site creation after a new user is created but before they're logged in / before they've reloaded the page)
Make sure you're in an incognito browser / you are not already logged in to WP.com. Also ensure that you do not reload the page while doing the following steps, to test that it works without requiring a page reload.
1. Create a new user at: …
=> Add Site data store to be used by Gutenboarding

client/my-sites/site-settings/form-general.jsx, client/state/sites/reducer.js
This PR makes sure that:
* A correct privacy setting is preselected in privacy picker when it's first opened
* Saving privacy settings would update the sidebar badge
* On wpcalypso.wordpress.com, create a new site, go atomic, launch your site.
* Go to site settings, choose Private and save settings. Without navigating away, choose coming soon, and confirm the sidebar badge was updated from Private to Coming soon.
* Try saving different privacy options, confirm the badge is updated right when you save the form.
* Confirm that your choice remains selected after refreshing the page - especially private and coming soon
=> [Coming soon] Privacy picker fix

client/my-sites/plan-features/index.jsx, client/state/selectors/should-new-site-be-private-by-default.ts
At the moment, we strip privacy of all sites on upgrade to e-commerce plan. This PR removes this restriction so that every site going e-commerce remains private/coming soon.
Specifically, this PR makes sure all new e-commerce sites are marked as private+coming soon and also that the following warning is no longer displayed:
All of the above is added behind a feature flag and shouldn't affect any existing users.
1. Open calypso in local dev environment to ensure appropriate feature flag is enabled
1. Create a new e-commerce site, confirm it's "Coming Soon"
1. Create a new free site
1. Upgrade to e-commerce plan
1. Confirm privacy warning was not displayed
1. Confirm the site is still "Coming Soon"
1. Disable …
=> [Coming soon] Add support for ecommerce plan

client/landing/gutenboarding/index.tsx, client/landing/gutenboarding/stores/onboard/index.ts, client/landing/gutenboarding/stores/onboard/persist.ts
This PR adds smoother handling for persisted data in the `onboard` data stores. Specifically:
<hr>
This is fun because there's not exactly a smooth nor clear solution.
The persistence plugin alone is not quite a quick solution here. Predominately, because creating a new storage implementation involves rewriting the default storage option that already exists for `localStorage` - albeit, encapsulated and untouchable - and serializing/re-serializing data twice (this is handled at a higher layer within the plugin and not exposed, so data handling requires a second transform), to ultimately end up doing almost the same thing. Seems like the persistence plugin was more intended for different storage implementations, like `sessionStorage`, rather than overt data handling.
Ultimately, I went with …
=> Gutenboarding: Persisted data should expire and be conditional

client/my-sites/checkout/checkout/composite-checkout-payment-methods.tsx, client/my-sites/checkout/checkout/composite-checkout.js, packages/composite-checkout-wpcom/src/hooks/use-shopping-cart.ts, packages/composite-checkout-wpcom/src/index.js, packages/composite-checkout-wpcom/src/lib/translate-cart.ts, packages/composite-checkout-wpcom/src/mock/cart-endpoint.ts, packages/composite-checkout-wpcom/src/types.ts, packages/composite-checkout-wpcom/src/types/backend/shopping-cart-endpoint.ts, packages/composite-checkout-wpcom/src/types/checkout-cart.ts
Currently, the shopping cart response includes `total_cost` which represents the total amount that the customer must pay after taxes, coupons, discounts, etc. 
The decision to display the full credits payment method is currently based on comparing the amount of credits to the total. This works in a full credits situation because of an inconsistent behavior of the endpoint documented more fully in D38606-code.
It is sometimes incorrect for partial credits, though; for example, if the user has $50 in credits and the cost of a plan is $70, the `total_cost` is $20, and since 50 > 20 we display the full credits method. It would be correct if the user only had $5 in credits, since 5 < 65.
This PR adds the `sub_total` property returned by the shopping card endpoint to the data returned by …
=> composite-checkout: Fix full credits calculation

client/lib/abtest/active-tests.js, client/signup/steps/domains/index.jsx, config/development.json, config/wpcalypso.json
* This PR creates a new A/B test for the domain copy updates changes as described in pbAok1-7N-p2.
* There's nothing more happening here other than enabling the config flag and the A/B test. 
**What next**
Subsequent UI updates will be built on top of this. Check back later to see the referenced PRs below(scroll right down to the bottom) to see all the smaller tasks that build each piece of the UI update. When all the smaller pieces are finished, then a new PR that removes the feature flag will be deployed.
* This PR introduces no UI changes, so everything should work just as before. Only change is that in `dev` and `wpcalypso` environments, user will get assigned to a new AB test when they reach the domain step in signup flow. 
**In dev or wpcalypso environments**
Use …
=> Enable domain step design update test for test environments

client/blocks/reader-full-post/style.scss
* Added a special SCSS case for .latex images. Images . in Reader full article have a 12px margin bottom (not really sure why). But I removed the margin for `.latex` images.
URL is `read/blogs/171811648/posts/120`
Before:
After:
*
Fixes #39329
cc @zdenys
=> Reader: fix margin-bottom for latex images

client/my-sites/checkout/checkout/composite-checkout.js, client/my-sites/checkout/checkout/test/composite-checkout.js, packages/composite-checkout-wpcom/src/components/coupon.js, packages/composite-checkout-wpcom/src/components/wp-checkout-order-review.js, packages/composite-checkout-wpcom/src/components/wp-checkout-order-summary.js, packages/composite-checkout-wpcom/src/components/wp-checkout.js, packages/composite-checkout-wpcom/src/components/wp-order-review-line-items.js, packages/composite-checkout-wpcom/src/hooks/use-coupon-field-state.ts, packages/composite-checkout-wpcom/src/hooks/use-shopping-cart.ts, packages/composite-checkout-wpcom/src/lib/translate-cart.ts, packages/composite-checkout-wpcom/src/mock/cart-endpoint.ts, packages/composite-checkout-wpcom/src/types/backend/shopping-cart-endpoint.ts, packages/composite-checkout-wpcom/src/types/checkout-cart.ts, packages/composite-checkout-wpcom/test/translate-cart.js
I recommend looking at the commits in order. Depends on ~D38431~ and ~D38473~.
* This PR updates composite checkout in wpcom to pass coupons to the cart endpoint and display a notice when the coupon is added successfully.
To do:
```
npm run test-packages composite-checkout-wpcom
```
Manual steps to test basic behavior:
1. Do _not_ sandbox the store.
2. Enter checkout with some products and proceed to the 'review order' step.
3. Try to apply an invalid coupon; that is, a string not consisting only of alphanumeric characters, '-', and '_'. Verify that the coupon field is unhappy.
4. Try to apply a valid but not active coupon such as 'blahtestcoupon'. Verify that you see a field error and that your item and total prices do not change.
5. Try to apply an active coupon. (Check with me or the …
=> composite-checkout: Hook up coupon field

client/my-sites/activity/activity-log/threat-alert.jsx
* Removes prop to ensure activity log threat alerts aren't visually broken.
* Create a security issue (see Pa0RFL-m9-p2 for instructions).
* Check Activity Log for visual glitch.
=> Resolves duplicate highlight for Activity threat alerts

client/blocks/credit-card-form/helpers.js
In c/zUTr0lu1-tr it became apparent that messaging which encourages renewal ("your subscription hasn't renewed yet" + "Renew Now") was originally intended to show only when the customer was actually close to renewal. There have been cases of confusion due in part to this message showing up early.
* Only show this message when the 90 days away from renewal.
* Update the payment method on a product that will be renewing more than 90 days from now. You should see a message that simply says your credit card details were updated.
* Update the payment method on a product that will be renewing less than 90 days from now. You should see a message encouraging you to renew with a "Renew Now" button.
* When clicking the "Renew Now" button, ensure it renews as expected.
=> Encourage renewing when close to renewal

client/my-sites/checkout/checkout/types/transaction-endpoint.ts, packages/composite-checkout-wpcom/src/index.js, packages/composite-checkout-wpcom/src/lib/translate-cart.ts
* Activating coupons exposed a bug in how we prepare data for the transaction endpoint. This PR ensures that the non-product items (taxes, coupons, etc.) are filtered out.
Attempt to complete a purchase with a coupon in your cart; without this patch it should fail with a notification.
=> composite-checkout: Filter non-product cart items before making transaction request

client/jetpack-connect/authorize.js, client/state/jetpack-connect/actions.js
Fixes #39003 
Please see the bug above for the full background on this proposed fix, but TL;DR;
When an Jetpack Connect auth flow fails, the `retryAuth()` action does not utilize the `redirectAfterAuth` argument that is passed in from the connecting flow. This bug was discovered during the testing of the new WooCommerce onboarding flow that is now live in WooCommerce 3.9 for 10% of users.
This one is a bit difficult to test because the auth fail doesn't always happen, and I haven't been able to figure out a way to always make it break. As such I ended up hacking a bit in the the auth action to dispatch a connection error. To setup for the test, I borrowed these instructions from a prior PR by @ebinnion 
- Check out this patch
- npm start in Calypso
- On a fresh Jetpack site, perhaps using …
=> Jetpack Connect: Respect redirect url on retryAuth

client/components/domains/register-domain-step/index.jsx, client/components/domains/search-filters/style.scss, client/components/domains/search-filters/tld-filter-bar.jsx
This PR:
* Replaces the buttons in the TLD filter bar with checkboxes.
**With items checked**
* Begin a fresh signup at /start or click "Add new site". You need to be in the _variantShowUpdates_ variant of **domainStepCopyUpdates** test and _variantDesignUpdates_ variant of **domainStepDesignUpdates**.
* At the domain step, verify the following:
- After typing a search query, the checkbox filters should show up and the UI should match the sketch shown in pbAok1-7N-p2.
- Selecting any of the TLD checkboxes should reload the results and show the filtered results. For example, checking .com and and .net should only show results having …
=> Domain step test: Add checkboxes for the tld filter bar

client/state/data-layer/wpcom/legal/index.js
Registers a `calypso_tos_accept` track event when a user accepts the current ToS.
* Make sure you don't have ToS marked as accepted. See D38262-code for instructions on how to reset ToS acceptance.
* Enable the analytics debug by running `localStorage.debug='calypso:analytics:*` in the browser console.
* Load any Calypso page.
* ToS update banner should appear.
* Click on Accept.
* Make sure a `calypso_tos_accept` track event is registered.
=> ToS: Add Tracks event for successful ToS acceptance

client/components/jetpack-logo/README.md, client/components/jetpack-logo/docs/example.js, client/components/jetpack-logo/index.jsx
In the Jetpack Cloud `Masterbar` a monochrome Jetpack logo is needed. This PR adds a support for a monochrome logo in the `JetpackLogo` component.
- Add `monochrome` prop to the component
- Use existing SVG paths as a base for the SVG mask
- Update props description and default values in the readme
- Remove unrelated note about 'underlying Button' from the readme
* Go to https://hash-8e0781d268fc0ced5fd6e7feb04c3ee8fe181b1d.calypso.live/devdocs/design/jetpack-logo
* Confirm that a new `monochrome` logo example is displayed as a last item
* Confirm there are no regressions in the other logo versions compared to `wpcalypso` environment
Fixes 1156570014567299-as-1161366493888073
=> Add support for a monochrome Jetpack logo

client/blocks/app-banner/index.jsx, client/state/selectors/should-display-tos-update-banner.js
Follows up #39297 
The ToS update banner is displayed in the same position as the mobile app banner. Since the ToS update has higher priority, we repress all other non-essential sticky banners like the "open in app" one if the ToS update banner needs to be displayed.
Before | After
--- | ---
* Make sure you don't have ToS marked as accepted. See D38262-code for instructions on how to reset ToS acceptance.
* If you've dismissed the mobile app banner in the past, bring it back by running the following line in your browser console:
```js
dispatch( { type: 'PREFERENCES_SET', key: 'appBannerDismissTimes', value: null } );
````
* Toggle the device toolbar in your browser devtools and select "Responsive". Adjust the width to less than 300px.
* Open the network conditions tab (it is under the …
=> Hide mobile app banner if ToS update banner is shown

client/assets/stylesheets/_calypso-color-scheme-jetpack-cloud.scss, client/landing/jetpack-cloud/components/masterbar/index.jsx, client/landing/jetpack-cloud/components/masterbar/style.scss, client/landing/jetpack-cloud/layout.js, client/landing/jetpack-cloud/masterbar.jsx
This PR add a simple Masterbar foundation for Jetpack Cloud. It's based off of default Calypso Masterbar.
**Please note that the masterbar looks as expected with a monochrome Jetpack logo proposed in #39384**
- Create new component directory and move files there
- Use Calypso layout elements to build out a Masterbar foundation
- Add necessary styles for masterbar along with color scheme swatches
* Go to http://jetpack.cloud.localhost:3000/
* Confirm that a simple masterbar is rendered there along with the Jetpack logo (if #39384 has not been merged yet, you'll see a full-color logo; if you rebase, you should see a correct white logo)
Fixes 1156570014567299-as-1157678527369059
=> Add Jetpack Cloud Masterbar component

client/components/domains/search-filters/style.scss
This PR:
* Shows at least one checkbox filter(implemented in https://github.com/Automattic/wp-calypso/pull/39346) in mobile view
**Before**
**After**
* Verify that the UI in mobile view works as described.
=> Domain step test: Show at least one checkbox filter in mobile view

client/blocks/eligibility-warnings/warning-list.tsx
Fixes https://github.com/Automattic/wp-calypso/issues/39256 where we warn about a subdomain. This PR updates copy here to note that this is a site change rather than a loss of a feature.
Before:
After Singular
| Themes | Plugins | Hosting |
| ------------- | ------------- |------------- |
| <img width="791" alt="Screen Shot 2020-02-11 at 4 38 34 PM" src="https://user-images.githubusercontent.com/1270189/74292967-48786a80-4cee-11ea-8384-332ffc1656dc.png"> | <img width="802" alt="Screen Shot 2020-02-11 at 4 38 24 PM" src="https://user-images.githubusercontent.com/1270189/74292950-3b5b7b80-4cee-11ea-9c5b-65e079f2433d.png"> | <img width="864" alt="Screen Shot 2020-02-11 at 4 39 14 PM" src="https://user-images.githubusercontent.com/1270189/74292986-55955980-4cee-11ea-9f40-f954094464c6.png"> | …
=> AT: update warnings to note site changes instead of lost functionality

client/components/domains/domain-registration-suggestion/index.jsx, client/components/domains/featured-domain-suggestions/style.scss
This PR:
* Switches the order of the "Recommended" and "Best Alternative" tags to appear right below the domain.
* Changes the "Recommended" and "Best Alternative" tags to a "pill" UI instead of a "badge" UI.
**Web**
**Mobile**
* Begin a fresh signup at /start or click "Add new site". You need to be in the _variantShowUpdates_ variant of **domainStepCopyUpdates** test and _variantDesignUpdates_ variant of **domainStepDesignUpdates**.
* At the domain step, verify the following:
- The "Recommended" and "Best Alternative" tags UI should match the sketch shown in pbAok1-7N-p2.
- Verify in both web and mobile.
**Verify that control group …
=> Domain step test: Convert recommended badge to plan-pill

client/components/domains/domain-search-results/index.jsx, client/components/domains/domain-transfer-suggestion/index.jsx, client/components/domains/register-domain-step/index.jsx, client/components/domains/register-domain-step/style.scss
This PR:
* Moves "Already own a domain" out of search results list, and adds it below the search results.
**Web**
**Mobile**
* Begin a fresh signup at /start or click "Add new site". You need to be in the _variantShowUpdates_ variant of **domainStepCopyUpdates** test and _variantDesignUpdates_ variant of **domainStepDesignUpdates**.
* At the domain step, verify the following:
- The "Already own a domain" UI should match the sketch in pbAok1-7N-p2.
- Click the link and verify that it takes you to the Transfer domain page
**Verify that control group UI is unchanged**
Scenario 1
* Go through signup flow from /start while in …
=> Move the use your domain option below Show More

client/my-sites/site-settings/form-general.jsx
This PR updates site visibility picker. Instead of 3 radio buttons for each value of `blog_public` site option, it exposes a checkbox under `Public` for "site = hidden" (`blog_public = 0`). This makes more sense - this choice only has SEO implications and doesn't really "Hide" a site other than changing what's inside robots.txt.
More context available here: paObgF-MY-p2
*Before:*
*After:*
1. Try selecting different options in the picker and confirm they're properly stored AND reflected in the form after saving.
2. Repeat for Atomic site
=> Make `blog_public=0` a checkbox instead of a separate option in the Privacy picker

client/landing/gutenboarding/stores/onboard/persist.ts
This PR no longer just searches for a substring in the URL and instead looks for the "fresh" query parameter as a whole. The 'fresh' parameter is used to control data persistence for the Gutenboarding flow. [Prior PR introducing variable persistence data handling.](#39310)
<hr>
* Spin this up locally and go to `/gutenboarding`.
* Pick a vertical and enter a site title, then refresh the page. Ensure that the site title and vertical are still filled out correctly.
* Add the `?fresh` param to the URL.
* Load the page and ensure that no data is persisted.
* Enter more data in the site title. Add a `?fresh-test` URL param.
* Ensure that the data is persisted.
<hr>
Fixes #39370
=> Gutenboarding: Tighten 'fresh' URL param for data persistence

client/signup/config/flows-pure.js
Remove the domain step from frankenflow.
* [`/gutenboarding`](https://calypso.live/gutenboarding?branch=gutenboarding/frankenflow-no-domain)
* Complete the flow.
* After creating your site, you should not be presented with a plans view before launching your site.
* You should be able to complete plan selection and arrive at your new site's home.
=> Gutenboarding: Remove domain from flow

client/my-sites/migrate/components/sites-block/style.scss
* This PR hides the default site badges, like `Private` or `Coming Soon` from the custom site block we use in the migration steps. This is done to reduce possible confusion for customers who go through the flow.
* Create a new site and make it either Private or Coming soon
* Check without this PR, you should see both Private/Coming Soon and the `This Site` badge
* Now check on the Calypso.live link or checkout the PR locally
* The Private/Coming Soon badge should be hidden.
=> Site Migration: Hide default side badges from the custom Site Block component

client/my-sites/migrate/step-source-select.jsx
* This PR fix a bug where the Site URL input would be unpopulated when returning to the input stage.
* Go to Site Migration
* Enter a valid URL for migration. The importer should take you to the screen offering you a choice between "Everything" or "Content Only".
* Press back or Cancel
* Make sure the URL you entered is persisted on the input screen
=> Site Migration: Persist the Site URL when going back to the URL input screen

client/my-sites/importer/file-importer.jsx, client/my-sites/migrate/step-import-or-migrate.jsx, client/my-sites/migrate/step-source-select.jsx
* This PR adds event tracking for some of the UI actions in Site Migration
* Included are two events:
* `calypso_importer_wordpress_select` - when a user clicks the continue button on the Import type screen (Content only or Everything)
* `calypso_importer_wordpress_enter_url` - when a site URL is submitted
* Go to Migration
* Try a WPCOM site
* Try a Jetpack connected site
* Try a random site (non-wp)
* Make sure the events are being sent with correct data 
* Continue to next step with a valid WP site
* Choose Content Only
* Choose Everything
* Make sure events are being sent with correct data
=> Site Migration: Add event tracking to some UI actions

client/components/domains/free-domain-explainer/index.jsx, client/components/domains/register-domain-step/index.jsx, client/signup/steps/domains/index.jsx, client/state/signup/progress/reducer.js
As discussed in p99Zz8-VK-p2 - let's start showing _both_ a WPCOM subdomain suggestion and a .blog subdomain suggestion in the Blog segment.
(please ignore the quality of results - they are dependent on the verticals selected in the previous steps, etc.)
Go to wordpress.com/start and select the `Blog` segment. Without the patch, you should only have one free .blog subdomain in the domains step. With the patch, you should have both a .blog subdomain _and_ a WPCOM subdomain. Always one of each, always .blog first, WPCOM second.
Check also other segments and make sure that there are no regressions (or .blog subdomains...) showing there. Check `/domains` and if everything works as expected as you (re)start the flow from - first from `/domains` then from `/start` and vice versa.
Fixes #38952
=> Domains: Include WPCOM and .blog subdomain suggestions for Blog segment

client/landing/jetpack-cloud/components/masterbar/index.jsx, client/landing/jetpack-cloud/components/sidebar/index.jsx
* Use `i18n-calypso` HoC and hook in Masterbar and Sidebar
* Go to https://wordpress.com/me/account
* Switch the language to something else than EN (e.g. DE) and save
* Go to http://jetpack.cloud.localhost:3000/
* Confirm that the menu items in the sidebar are translated
Please note that if using any other language than EN, a console error message is thrown:
It seems it's caused because of the fact that the `<Layout />` is not wrapped with a `<MomentProvider />`, even though we are not making any use of `moment` just yet.
I tried fixing the issue, however it seems we first need a Redux store to be added to the app since `<MomentProvider />` relies on it. Because the problem is more complex than I initially thought, it will get fixed in another PR.
Fixes …
=> Add support for i18n to Jetpack Cloud masterbar and sidebar

client/my-sites/checkout/checkout/composite-checkout.js, packages/composite-checkout-wpcom/src/hooks/use-coupon-field-state.ts, packages/composite-checkout/src/lib/payment-methods/stripe-credit-card-fields.js
The `composite-checkout` package supports a custom hook called `useEvents` that returns a function for recording analytics. This PR hooks up the Calypso implementation of the package to send those analytics to Tracks.
- Visit checkout with the `composite-checkout-wpcom` flag enabled.
- Click continue on the first step.
- Search in Tracks for the event `calypso_checkout_composite_step_changed` and be sure it was recorded correctly with the property `step` and the step number `2`.
=> composite-checkout: Record events to Tracks

client/blocks/signup-form/index.jsx, client/blocks/signup-form/passwordless.jsx, client/blocks/signup-form/style.scss, client/lib/abtest/active-tests.js, client/lib/analytics/recaptcha.js, client/lib/signup/step-actions.js, client/signup/config/flows-pure.js, client/signup/steps/user/index.jsx, config/_shared.json, config/desktop.json, config/development.json, config/horizon.json, config/production.json, config/stage.json, config/test.json, config/wpcalypso.json
* Reverts 77318c9b32568459aeb80639f8e01a137b3a5ee1 (thus re-adding recaptcha code)
* Remove the `userStepRecaptcha` AB test (which was part of the code we just reverted) and show all users the `show` variation
* Add a new `showRecaptcha` flow config to `flows-pure.js` so it's easier to enable/disable for other flows.
Fixes #39267 
Need to test that the correct recaptcha properties appear in tracks events for the onboarding flow i.e. signup will record a `wpcom_recaptcha_response_verified` event with `recaptcha_likely_good` and `recaptcha_score` properties.
Also need to test the case where users have blocked the Google script.
To test blocking the Google script I used a the ScriptBlock extension. After navigating to `/start/user` for the first time you need to click the extension's icon in …
=> [reCaptcha v3]: recaptcha in signup

packages/composite-checkout-wpcom/src/components/wp-order-review-line-items.js, packages/composite-checkout-wpcom/src/types/backend/shopping-cart-endpoint.ts
* Only show plan length options on signup. Allowing this on renewals and upgrades is possible but requires a lot of math, which we can implement and test at a later time.
* Enter checkout with a new plan; verify that you have the option to choose between one and two year subscriptions
* Enter checkout with a plan renewal or upgrade; verify that you don't have the option to change the term length
=> composite-checkout: Hide variant options for non-signups

client/components/domains/domain-product-price/index.jsx, client/components/domains/domain-product-price/style.scss, client/components/domains/domain-registration-suggestion/index.jsx, client/components/domains/domain-suggestion/index.jsx, client/components/domains/domain-suggestion/style.scss, client/components/domains/featured-domain-suggestions/index.jsx, client/components/domains/featured-domain-suggestions/style.scss, client/components/domains/free-domain-explainer/index.jsx, client/components/domains/free-domain-explainer/style.scss, client/components/domains/register-domain-step/index.jsx, client/components/domains/register-domain-step/style.scss, client/components/domains/search-filters/style.scss
The next domain step test is being implemented in #39276.
This PR:
* Updates the alignment of the pricing text as described in the issue https://github.com/Automattic/wp-calypso/issues/39393
* Updates the search results UI to match the screen shared in pbAok1-7N-p2.
**Desktop screen size**
**Mobile screen size**
* Begin a fresh signup at /start or click "Add new site". You need to be in the _variantShowUpdates_ variant of **domainStepCopyUpdates** test and _variantDesignUpdates_ variant of **domainStepDesignUpdates**.
* At the domain step, verify the following:
- The pricing copy and tooltip matches the UI sketch in https://github.com/Automattic/wp-calypso/issues/39393
-  Verify in desktop and mobile screen sizes
**Verify that control group UI is unchanged**
Scenario 1
* Go through signup …
=> Domain step test: Right align the pricing text

client/lib/abtest/active-tests.js, client/my-sites/checkout/checkout/checkout-system-decider.js, client/my-sites/checkout/checkout/composite-checkout.js, client/my-sites/checkout/controller.jsx, config/horizon.json
This PR modifies the checkout route so that Composite Checkout is loaded for everyone if all of the following are true, or the `composite-checkout-wpcom` config flag is enabled:
- Cart contains no domain registrations
- Cart contains no Jetpack products
- User has EN language
- User has US geolocation
- User is placed in `showCompositeCheckout` abtest (10%).
This PR also removes the "testing" banner from Composite Checkout and removes the `composite-checkout-wpcom` config flag from the horizon environment (so that environment will behave as all the others).
- Start calypso _without_ the `composite-checkout-wpcom` flag.
- Use the local environment badge in the lower-right to enable the `showCompositeCheckout` test.
- Visit checkout with a wpcom plan in the cart when you are in the US and …
=> composite-checkout: Add abtest for phase 1 launch

packages/composite-checkout/src/components/checkout-payment-methods.js, packages/composite-checkout/src/components/checkout-provider.js
When I refactored payment method creation in the thank-you PR, I caused the payment methods array to be re-created on every render. This means that the useEffect in the provider which sets the active payment method to the first one when the payment methods change gets called on every render.
This PR only resets the active method if the length of the payment methods array changes. It's not perfect - there are cases where that would have a false positive - but it's much better.
Choose PayPal as a payment method and make sure it "sticks" through the whole checkout process.
=> composite-checkout: Prevent resetting active payment method when PM list is the same

client/my-sites/checkout/checkout/composite-checkout.js, packages/composite-checkout/src/lib/payment-methods/apple-pay.js, packages/composite-checkout/src/lib/payment-methods/existing-credit-card.js, packages/composite-checkout/src/lib/payment-methods/full-credits.js, packages/composite-checkout/src/lib/payment-methods/paypal.js, packages/composite-checkout/src/lib/payment-methods/stripe-credit-card-fields.js
This adds analytics for all the payment methods when the method begins submission and when there is an error.
- Enable the debug logs by putting this in your JS console: `localStorage.setItem('debug', 'calypso:*')`
- Try submitting a credit card transaction and verify that the Tracks event was submitted by watching the debug logs.
- Repeat the above step with paypal, existing cards, full credits, and apple pay.
=> composite-checkout: Add analytics events for all payment methods

client/my-sites/checkout/checkout/composite-checkout.js
This just adds a special error message to Tracks if we try to record an action we don't recognize.
Fixes #39469
None.
=> composite-checkout: Record unknown error types to Tracks also

client/my-sites/migrate/section-migrate.jsx, client/my-sites/migrate/section-migrate.scss, client/my-sites/migrate/step-upgrade.jsx
* Updates the Migration confirmation step
* Adds a list of themes and plugins
* Apply the PR and run Calypso locally, or use `calypso.live`.
* Do a migration into a site without a Business plan.
* After clicking "Import everything" on the confirm page, you should see the new style of upgrade step page:
* On purchasing a plan and following the other steps the migration should complete.
=> Migration: Show plan price, themes, and plugins in the flow on upgrade step

client/my-sites/checkout/checkout/checkout-system-decider.js, client/my-sites/checkout/checkout/composite-checkout.js, packages/composite-checkout-wpcom/src/hooks/use-shopping-cart.ts
This PR does several things. Firstly, if the URL contains a product slug to add to the cart, we add it automatically when first initializing the cart to prevent a possible race condition.
Secondly, this adds additional guards to `CheckoutSystemDecider` to prevent jetpack plans and other non-wpcom-plan products from causing Composite Checkout to be displayed, even if those products are just slugs in the URL waiting to be added.
First, click the buttons to add various Jetpack products to the cart (plans, especially "premium" which has the same URL slug as wpcom's plan, and backup products); then verify that you always see the old checkout.
Second, do the same thing for WordPress.com plans; verify that you always see the new checkout, _and_ that the plan you added has successfully been added …
=> composite-checkout: Prevent race condition when adding product to cart

client/my-sites/checkout/checkout/checkout-system-decider.js, client/my-sites/checkout/checkout/composite-checkout.js
This adds the `PageViewTracker` component to `CompositeCheckout` so that it records the same analytics as the `Checkout` component from the existing checkout. The code to construct the path and props is copied directly from `Checkout`.
- Run calypso with `ENABLE_FEATURES=composite-checkout-wpcom npm start` or add `?flags=composite-checkout-wpcom` to the query string when you get to checkout.
- In the console on your local environment, enable debug logs with `localStorage.setItem('debug', 'calypso:analytics*')` and reload the page.
- Visit checkout with a plan in your cart.
- Verify that you see in the debug logs, `Recording event "calypso_page_view" with actual props`. Verify the props object looks correct, particularly the `path` property.
=> composite-checkout: Add PageViewTracker

packages/data-stores/src/site/reducer.ts, packages/data-stores/src/site/types.ts
Hi, 
In Gutenboarding, we do a [bit of fiddling about](https://github.com/Automattic/wp-calypso/blob/master/client/landing/gutenboarding/utils.ts#L57) to parse a new site's url to turn it from this:
`https://aaaaa.ccc/`
to this
`aaaaa.ccc`
So in D38739-code we're adding a new property to the `blog_details` object in the success response for `sites/new`, containing this already-edited value.
The new property is called `site_slug`.
This PR prepares our types for the new property.
It also consolidates the `NewSite` and `NewSiteSuccessResponseBlogDetails` interfaces as they represent the same structure.
We hope you like it. 
Fire up the branch and create a site via Gutenboarding. (`/gutenboarding`) 
There should be no type errors.
Now apply D38739-code and create a site via Gutenboarding. …
=> [Sites]: update type interface to accept new `site_slug` property.

client/my-sites/migrate/section-migrate.jsx, client/state/selectors/get-site-migration-status.js, client/state/sites/actions.js, client/state/sites/constants.js, client/state/sites/reducer.js
* This PR helps prepare Calypso to show the Home screen for sites which have recently been migrated into.
* In D38929-code, we are saving basic metadata about the latest site migration in a `site_migration_meta` option and returning this data from the `/me/sites` endpoint.
* This PR adapts the site migration logic to use the new `site_migration` object instead of the previous `migration_status` string.
* Test this in conjunction with D38929-code - follow the test instructions there to enable the new object.
* Check out this PR and run Calypso locally, or use calypso.live.
* Go to `http://calypso.localhost:3000/migrate/[ TARGET SITE DOMAIN ]`.
* Check the state for the selected site. It should contain a `site_migration` object with the values returned from the `/me/sites` endpoint.
* Start …
=> Site migration: use `site_migration` data instead of `migration_status` value

client/my-sites/sidebar/index.jsx, client/my-sites/sidebar/tools-menu.jsx
* Remove the "Migrate" menu-item from sidebar
* Highlight the "Import" item for `/migrate` paths
Before:
After: 
* Verify that "Migrate" is missing from the sidebar.
* Make sure the `tools/migrate` feature-flag is enabled.
* Select "Import" from the sidebar on a simple-site.
* Select "WordPress". You should be taken to a `/migrate` path, but "Import" should remain selected in the sidebare.
=> Migration: Remove from tools sidebar

client/my-sites/checkout/checkout/composite-checkout.js, packages/composite-checkout-wpcom/src/hooks/use-shopping-cart.ts, packages/composite-checkout-wpcom/src/index.js, packages/composite-checkout-wpcom/src/lib/translate-cart.ts, packages/composite-checkout-wpcom/src/types.ts, packages/composite-checkout-wpcom/src/types/backend/payment-method.ts, packages/composite-checkout-wpcom/src/types/checkout-cart.ts, packages/composite-checkout/README.md, packages/composite-checkout/src/components/checkout-provider.js
This records a second event, `calypso_checkout_payment_success`, which is
also used in the regular checkout, when calling `onPaymentComplete`. The existing success event, `calypso_checkout_composite_payment_complete`, will still be recorded and will be provided with some additional properties to match those recorded by the new event.
We have to do some minor refactoring to get the data that the new event needs. You should be able to read the commits one-at-a-time to see what each change means.
- Run calypso with `ENABLE_FEATURES=composite-checkout-wpcom npm start` or add `?flags=composite-checkout-wpcom` to the query string when you get to checkout.
- In the console on your local environment, enable debug logs with `localStorage.setItem('debug', 'calypso:analytics*')` and reload the page. …
=> composite-checkout: Add `calypso_checkout_payment_success` event

client/my-sites/migrate/step-import-or-migrate.jsx
* When a compatible plan already exists on the target site, remove the upgrade badge from the import or migrate step
Before:
After: 
* Start with a simple site that has a business plan
* Visit the import section
* Select "WordPress"
* Enter the URL for a connected Jetpack site and continue
* Verify, that because you already have a business plan, the upgrade badge isn't shown
* Repeat the above for a site without a plan, and verify that the upgrade badge still appears
=> Migration: Don't show import type step upgrade badge when unneeded

client/me/privacy/main.jsx, client/me/privacy/style.scss
A Data Processing Addendum (DPA) allows web sites and companies to assure customers, vendors, and partners that their data handling complies with the law. This PR adds updates the `/me/privacy` view to allow customers to request one on their own, without contacting support.
=> Add DPA request UI to /me/privacy

client/my-sites/checkout/checkout/composite-checkout.js, packages/composite-checkout-wpcom/src/components/wp-contact-form.js, packages/composite-checkout/src/lib/payment-methods/stripe-credit-card-fields.js
* For continuity of data, includes the existing transaction analytics events in composite checkout.
- Attempt a PayPal purchase and verify that a `calypso_checkout_form_redirect` tracks event is fired.
- Attempt a purchase with any payment method and verify that a `calypso_checkout_form_submit` event is fired.
- Enter checkout with a domain, complete the contact details form, and proceed to the review step. Verify that a `calypso_checkout_form_submit` tracks event is fired.
- Attempt to complete checkout with a failing payment method (e.g. card number `4000000000000002`) and verify that a `calypso_checkout_payment_error` tracks event is fired.
=> composite-checkout: Add transaction analytics

client/components/domains/domain-product-price/index.jsx, client/components/domains/domain-registration-suggestion/index.jsx, client/components/domains/domain-suggestion/index.jsx
* Update tooltip text for the free subdomain URL as mentioned in the comment https://github.com/Automattic/wp-calypso/issues/39393#issuecomment-586909676
* Also fixes a bug wherein clicking the "Learn More" link in the tooltip would also add the domain to cart.
* Go through the signup flow /start - assign yourself to _variantShowUpdates_ of _domainStepCopyUpdates_ and _variantDesignUpdates_ of _domainStepDesignUpdates_.
* Verify that for the free .blog and .wordpres.com domains, the tooltip text matches the recommendations in https://github.com/Automattic/wp-calypso/issues/39393#issuecomment-586909676:
- For .wordpress.com, we will say `Every WordPress.com site comes with a free WordPress.com address.`
- For .blog, we will say: `Every WordPress.com blog comes with a free .blog address.`
* …
=> Domain step text: Modify text for the free subdomain tooltip

client/my-sites/migrate/section-migrate.jsx
* This PR fixes a bug that persisted the old start time of the previous migration when starting a new migration. Now the start time is reset when the migration starts, so there's no old data to show to the customer. 
* Complete a migration (note the start time)
* At the end of the migration (without refreshing the page) press Start Over
* Start the new migration
* Make sure the Import started time is correct for the current migration
=> Site Migration: Don't persist start time of previous migration

client/my-sites/domains/domain-management/edit/card/subscription-settings/index.jsx, client/my-sites/domains/domain-management/edit/domain-types/registered-domain-type.jsx, client/my-sites/domains/domain-management/edit/style.scss
* Move the Payment Settings button to the expiry row - it'll take a lot less space.
Before:
After:
* open the new domain status page and verify that the "Payment Settings" button is on the right side of the domain expiration date
=> Move the Payment Settings button to the expiry row

client/my-sites/customer-home/main.jsx, client/my-sites/customer-home/style.scss
This makes a variety of changes, all of which are the ones mentioned in #39182.
Note the addition of the banner instead of the confetti illustration
Note the change of boxes
Note the change of boxes
Other changes made, as mentioned in the initial issue:
- Site Tools replaced with Quick Links
- "View Site" button at the top right of the screen
- Formatted header at the top now always appears
As a result of this, the My Site card has now been removed. It was never being displayed before the site was launched, and the initial issue states that the things above are what is needed to remove it post-launch. Here was the logic for that, by the way.
https://github.com/Automattic/wp-calypso/blob/25d2ca0bf9148864d430e99304688a6019439b99/client/my-sites/customer-home/main.jsx#L512-L515
Verify that …
=> Customer Home: Replace My Site Card

client/lib/abtest/active-tests.js, client/reader/sidebar/reader-sidebar-nudges/index.jsx
* Remove `readerFreeToPaidPlanNudge` a/b test which is implemented with #38619.
* You should be a user who has only one free plan dotcom site.
* Go to the Reader page.
* If you are an English US user, you should be able to see the nudge in the sidebar.
* If you are neither an EN user nor an US user, the nudge shouldn't display for you.
_Note: In dev env, you can change your country as follows._
```
// in browser console
window.userCountryCode = 'US';
```
=> Marketing: Remove `readerFreeToPaidPlanNudge` a/b test.

client/components/domains/search-filters/style.scss, client/components/domains/search-filters/tld-filter-bar.jsx
* This PR fixes the issue described in https://github.com/Automattic/wp-calypso/issues/39414
* ~The "More Extensions" button will be showed in a pressed state only if the selected TLD filter is NOT visible in the filter bar. If you select a TLD checkbox or button from the visible filter area, then the button will not show in a pressed state.~ Per https://github.com/Automattic/wp-calypso/issues/39414#issuecomment-587923987, the "More Extensions" button will show in a magenta text colour if the selected TLD is NOT visible in the filter bar. If you select a TLD checkbox or button from the visible filter area,  then the More Extensions …
=> Domain step: Show 'More Extensions' in a pressed state only if tld is not in filter bar

client/components/domains/domain-suggestion/style.scss, client/components/domains/register-domain-step/index.jsx, client/components/domains/register-domain-step/style.scss
* Change the "Use your domain" button to a link(first implemented in https://github.com/Automattic/wp-calypso/pull/39366), to match it with existing UI patterns in the signup 
flow
* Fixes https://github.com/Automattic/wp-calypso/issues/39525
**BEFORE**
**AFTER**
* Go through the signup flow /start - assign yourself to _variantShowUpdates_ of **domainStepCopyUpdates** and _variantDesignUpdates_ of **domainStepDesignUpdates**.
* Verify that "use your domain" shows as a link
* Verify that clicking the link fires the Tracks event `calypso_domain_search_results_use_my_domain_button_click` (type `localStorage.setItem( 'debug', …
=> Domain step test: Change "use your domain" to a link

client/my-sites/checkout/checkout/composite-checkout.js, client/my-sites/checkout/checkout/types/paypal-express.ts
* Return the PayPal redirect promise from `submitTransaction`
Run calypso with composite checkout enabled using
```
ENABLE_FEATURES=composite-checkout-wpcom npm start
```
and attempt to make a purchase using PayPal. Without this PR applied, instead of redirecting to complete the payment, calypso reloads to `/checkout/undefined` because the redirect URL never arrives.
=> composite-checkout: Fix PayPal redirect

client/blocks/product-plan-overlap-notices/index.jsx, client/lib/products-values/constants.js, client/lib/products-values/index.js, client/lib/products-values/test/index.js, client/lib/purchases/index.js, client/my-sites/plans-features-main/index.jsx
In some cases, no translations are displayed in e.g. ProductsSelector even though the respective strings are already translated.
It turns out that the `translate` function inside the `client/lib/products-values/constants.js` file is executed *before* translations are loaded via `localize` HoC. The constants are imported directly to the file that consumes them and so the `translate` function is executed once, right after the app is booted.
To overcome this issue, the `translate` function calls are now wrapped with anonymous functions. This way the `translate` function call gets deferred. It's executed when localization is already available since consumers use `localize` HoC themselves. 
* Defer `translate` calls for Jetpack products
* Go to https://wordpress.com/me/account and change the …
=> Change the way translations are used in Jetpack products

apps/full-site-editing/full-site-editing-plugin/starter-page-templates/class-starter-page-templates.php
* Adds `pt-br` to the list of valid sub-locales for wp.com
* On your local test site, have the FSE plugin enabled.
* Set the content locale to Brazilian Portuguese.
* Create a new page and check if the templates are in Portuguese.
=> SPT: Add Brazilian Portuguese to the list of sub locales

client/my-sites/checkout/checkout/composite-checkout.js, packages/composite-checkout-wpcom/src/hooks/use-shopping-cart.ts, packages/composite-checkout-wpcom/src/types/backend/shopping-cart-endpoint.ts
This adds a call to `analytics.recordPurchase()` to the event handler for the `PAYMENT_COMPLETE` event that gets triggered by `onPaymentComplete()`. This function is used by Marketing to track all sorts of purchase-related data.
In order to do this we need to expose the raw `ResponseCart` object stored in the shopping cart manager.
To trigger the call, follow these steps:
- Run calypso with `ENABLE_FEATURES=composite-checkout-wpcom npm start` or by adding `?flags=composite-checkout-wpcom` to the URL when you visit the checkout page.
- Add a plan to your chart and visit checkout.
- Complete checkout and pay; you can do this with credits (although then it's possible it won't do anything because of logic in `recordPurchase`) or with a test card like `4242 4242 4242 4242` (if you've sandboxed …
=> composite-checkout: Call analytics.recordPurchase when purchase complete

client/lib/abtest/active-tests.js, client/my-sites/checkout/checkout/checkout-system-decider.js
The abtest was originally added in #39419 and then was previously disabled in #39468 which this PR reverts. This also updates the datestamp.
The race condition that caused the previous test to be disabled should be taken care of by #39472
The internal launch post about this is p58i-8zB-p2
- Start calypso _without_ the `composite-checkout-wpcom` flag.
- Use the local environment badge in the lower-right to set the `showCompositeCheckout` test to `composite` for your user.
- Visit checkout with a wpcom plan in the cart when you are in the US and have your language set to English. Verify that you see composite checkout.
- Visit checkout with a wpcom plan in the cart when you are not in the US. Verify that you see the regular checkout.
- Visit checkout with a wpcom plan in the cart when you …
=> Re-enable composite-checkout abtest

config/horizon.json
This re-adds the `composite-checkout-wpcom` flag to Horizon, which was originally enabled in #38958 and then disabled in #39419.
None.
=> Enable composite-checkout for Horizon

packages/composite-checkout/src/components/checkout.js
This is a small change that prevents trying to change the current checkout step if the step number has not changed. The practical benefit of this is mainly fewer Tracks stats for `calypso_checkout_composite_step_changed` when the step hasn't actually changed (eg: when first loading the form).
- Visit checkout with just a plan in your cart and be sure you are in the abtest group by running this in your console: `localStorage.ABTests = '{"showCompositeCheckout_20200219":"composite"}'`
- Verify that changing steps works correctly.
=> composite-checkout: Don't change the step if it is unchanged

apps/full-site-editing/full-site-editing-plugin/starter-page-templates/class-starter-page-templates.php
Locale works a little differently on wp.com. When we're in wp-admin the standard content local gets set to the user locale. To get the content locale, we'll have to use `get_blog_lang_code()`.
* Uses `get_blog_lang_code()` if available `get_locale()` as a fallback.
* Manually apply this diff on dotcom and test with a sandboxed site.
* With a non-a11n account, set your site language to a non-English locale, set your account language to a _different_ non-English locale.
* Open the template selector and make sure the templates are in the content locale.
Fixes #38198
=> SPT: Make sure to get blog locale, not user locale.

client/my-sites/checkout/checkout/composite-checkout.js
* This is not really a "form submit" event, and doesn't happen in production yet anyway. Removing this for now.
Attempt to complete a purchase in composite checkout.
=> composite-checkout: Remove form submit tracks event for domain contact validation

client/my-sites/checkout/checkout/composite-checkout.js, packages/composite-checkout-wpcom/src/types/backend/payment-method.ts
Use translateCheckoutPaymentMethodToWpcomPaymentMethod for the `calypso_checkout_composite_payment_complete` Tracks event.
This will record a card as `WPCOM_Billing_Stripe_Payment_Method` instead of `card` as we do now. More importantly, this will report existing card payment methods, which have a unique ID like `exitingCard-2342434343`, as `WPCOM_Billing_Stripe_Payment_Method` instead of the unique ID itself.
Complete a checkout using composite checkout using an existing card and verify that the event in Tracks has the `payment_method` property in the backend format.
=> composite-checkout: Translate payment_method to backend version in complete stat

client/my-sites/checkout/checkout/checkout-system-decider.js
Domain mapping products sometimes have a 0 cost. Composite Checkout was not designed to handle that situation; you cannot submit a purchase with 0 cost.
To give us time to solve this issue, this PR disables CompositeCheckout if the cart contains a product with the word `domain` in the slug, which should cover domain mapping (slug: `domain_map`).
Make sure you are in the composite checkout test and then visit the URL https://wordpress.com/domains/add/mapping/your-site-here
Search for a domain and click "Add".
Verify that you do not end up in Composite Checkout.
=> composite-checkout: Disable CompositeCheckout in CheckoutSystemDecider for mapping

client/landing/gutenboarding/onboarding-block/signup-form/index.tsx, client/landing/gutenboarding/onboarding-block/signup-form/style.scss
Adds the most basic client-side validation to the email address and displays errors from server in a `<Notice>`
I couldn't find any prior art for how to show that a text input is invalid in Gutenberg. I was sort of hoping `<TextControl>` would have an `error` prop or something.
I copied the error message copy from the existing passwordless signup control in calypso.
* Add `required` attribute to email input
* Remove JSON dump of error response from the modal (the JSON dump of the success object is being removed in #39360)
* Show error messages from server in red `<Notice>`
* Open the signup modal in gutenboarding
* Should get an error when submitting an empty field
* Should get an error when submitting an invalid email
* Should get an error (in a red notice) when submitting an existing …
=> Show signup errors to user in Gutenboarding

client/my-sites/checkout/checkout/composite-checkout.js, packages/composite-checkout-wpcom/src/hooks/use-shopping-cart.ts
This adds a redirect (currently to the plans page) if checkout has loaded and the cart is empty.
Previously we added a redirect in #38841 which would trigger if the cart contained at least one product and then became empty. However, there are many situations that doesn't cover; the largest is if you manually (or via the back button) visit checkout with an empty cart and the URL does not contain an item to add.
This PR adds an additional redirect that will trigger if the cart is empty at all, except while the initial cart is loading (which includes adding initial items).
It also disables the form (keeps it in the "loading" state) if the cart is empty so you won't see a flash of the enabled form before the redirect happens.
Make sure your cart is empty (visit checkout and remove any items …
=> composite-checkout: redirect if not loading and cart is empty

client/lib/abtest/active-tests.js, client/lib/plans/index.js, client/lib/plans/test/get-popular-plan-spec.js, client/my-sites/plans-features-main/index.jsx, client/my-sites/plans-features-main/test/index.jsx, client/signup/steps/plans/index.jsx
* Wrap of the A/B test launched in https://github.com/Automattic/wp-calypso/pull/38334
* We will launch the control version to all users, as per p8Eqe3-Zs#comment-3116
**Scenario 1**
* Go through the signup flow and select either `Business` or `Online Store` as site type.
* Verify in Plans step that the Business plan is highlighted as Popular.
**Scenario 2**
* Go through the signup flow and select either `Blog` or `Professional` as site type.
* Verify in Plans step that the Premium plan is highlighted as Popular.
**Scenario 3**
* Log in to an account and check /plans page. 
* Verify that on the `Blogs and Personal sites` tab, the Premium plan is highlighted as Popular, and on the `Business sites and Online Stores` tab, the Business plan is highlighted as popular.
**Scenario 4**
* Log in …
=> Wrap up the popular badge on Business plan test

client/my-sites/checkout/checkout/composite-checkout-thank-you.ts, client/my-sites/checkout/checkout/composite-checkout.js, client/my-sites/checkout/checkout/test/composite-checkout-thank-you.js
This changes the generic thank-you page from `/` (as it is in production checkout) to `/checkout/thank-you/siteSlug`. This should make paypal redirects work.
Try to complete a paypal purchase with composite checkout and be sure it works.
=> composite-checkout: Set generic thank-you page to be the default for getThankYouPageUrl

client/lib/abtest/active-tests.js, client/signup/steps/domains/index.jsx, config/development.json, config/wpcalypso.json
* We created a new A/B test for the domain step UI updates in https://github.com/Automattic/wp-calypso/pull/39276 and it was hidden behind a feature flag.
* All UI pieces for the new test are now complete, so we will remove the feature flag and launch to users.
* Go through the signup flow beginning at /start. - assign yourself to _variantShowUpdates_ of _domainStepCopyUpdates_ and _variantDesignUpdates_ of _domainStepDesignUpdates_.
* At the domain step, verify the UI matches the screens shared in pbAok1-7N-p2.
=> Domain step test: Launch the test by removing the feature flag

client/my-sites/migrate/step-confirm-migration.jsx, client/my-sites/migrate/step-import-or-migrate.jsx
* This PR adds two more Tracks events for the confirmation screen
* Apply diff or use Calypso.live link
* Star a migration on a Simple Site
* When you get to the migration confirmation screen (after you choose the everything/content only type) 
* Verify the `calypso_site_migration_confirm_viewed` event is sent
* Click `Import Everything`
* Verify the `calypso_site_migration_confirm_clicked` event was sent.
=> Site Migration: Add more tracking events for the confirmation screen

client/my-sites/migrate/section-migrate.scss, client/my-sites/migrate/step-source-select.jsx
* This PR fixes the UI on the Site Migration URL input screen. 
* It's still not very optimal and design-reviewed, but it's better than what we had previously.
* Also clears out the error when the URL value is changed
* Go to Site Migration
* Ensure there's no empty space between the site input section and the continue button
* Enter a WordPress.com site to trigger an error
* Make sure the error message shows in red color
* Change the URL (start typing in the box) - the error should disappear.
=> Improve error UI on the site input screen

client/my-sites/migrate/section-migrate.scss, client/my-sites/migrate/step-source-select.jsx
* Adds underline to the link for uploading a file.
* Corrects an issue with a missing space in the wrapped string text.
* Replaces the `<p>` tag that was used for error with a `<Notice>`.
* Conditionally shows the notice (previously, the `<p>` was always shown, and looked awkward).
Before:
After:
Before error:
After error:
* Ensure that `tools/migrate` feature flag is enabled.
* Visit Import for your site.
* Select "WordPress".
* Verify that the upload link is now underlined.
* Verify that the spacing of the text is now correct.
* Verify that there is no blank space where an error would be displayed.
* Attempt to continue to the next step without entering a URL. Verify that the error message is displayed as a notice.
Fixes #
=> Migration: cleanup for the source selection page

client/my-sites/domains/domain-management/transfer/transfer-to-other-site/confirmation-dialog.jsx, client/my-sites/domains/domain-management/transfer/transfer-to-other-site/index.jsx
* We're using the targetSite `name` in transfer-to-other-site messages which is not working properly if your site has no Site Title set. Counterintuitively we should use the `title` attribute which actually is populated with your site address in case the Site Title is empty :)
* Try to transfer a domain to a site that has empty Site Title - with this PR you should see the site address (without it shows buggy message)
=> Domains: Use site title instead of site name for domain transfer messages

client/my-sites/domains/domain-management/name-servers/custom-nameservers-form.jsx, client/my-sites/domains/domain-management/name-servers/index.jsx
* Move the notice above and outside the card.
* Change the input placeholders to "eg: ns1.example.com" and "eg: ns2.example.com".
* Make the field label bold
Use custom nameservers (before):
Use custom nameservers (after):
* Open "Name Servers and DNS" and disable the "Use WordPress.com Name Servers" toggle
* verify that the notice is outside the card, the placeholders are updated and the label is bold
=> Domains: Fix some usability issues with the custom nameservers controls

client/my-sites/site-settings/theme-enhancements.jsx
The Jetpack Mobile Theme will be completely removed from the upcoming version of Jetpack, 8.3. (https://github.com/Automattic/jetpack/pull/14714)
This PR aims to remove the Mobile Theme section for all Jetpack sites that run a version of Jetpack that does not include the mobile theme anymore.
Internal reference: p1HpG7-85q-p2
* Start with 2 Jetpack sites, one running the latest stable (8.2.1), and one running bleeding edge (8.3-alpha).
* Go to Settings > Writing for both sites.
* When on latest stable, you should see the following message and greyed out Mobile Theme settings:
> Note: The Jetpack mobile theme is not supported anymore. It will be removed when you update to the most recent version of the plugin.
* When on bleeding edge, the whole section should be gone.
=> Mobile Theme: do not display settings in newer versions of Jetpack

client/my-sites/customer-home/controller.jsx, client/my-sites/customer-home/main.jsx, client/my-sites/customer-home/style.scss, client/my-sites/migrate/section-migrate.jsx, client/my-sites/migrate/step-upgrade.jsx, client/state/selectors/is-site-recently-migrated.js
* When a migration is complete we reset it and redirect to the Customer Home.
* If a site has been the target of a successful migration in the last two days, we show a custom header on the Customer Home.
The design also calls for a customised checklist on the Home – we'll look at that in a separate PR.
* Apply the PR and run Calypso locally, or use calypso.live (for the latter, add `?flags=tools/migrate` to the end of the URL to enable the feature flag).
* Do a migration: go to the import section of a Simple site, enter the URL of a Jetpack site and follow the steps you're presented with. (If you're migrating to a site you've migrated to whose `done` status hasn't been cleared yet, you may need to reset the migration first with a request to the `reset-migration` endpoint.)
* When the …
=> Site migration. Redirect to homepage when migration is complete.

client/my-sites/checkout/checkout/composite-checkout-payment-methods.tsx, client/my-sites/checkout/checkout/composite-checkout.js, packages/composite-checkout-wpcom/src/components/wp-checkout.js, packages/composite-checkout-wpcom/src/hooks/has-domains.js, packages/composite-checkout-wpcom/src/types/backend/payment-method.ts, packages/composite-checkout-wpcom/src/types/checkout-payment-method-slug.ts, packages/composite-checkout/src/lib/payment-methods/free-purchase.js, packages/composite-checkout/src/lib/payment-methods/index.js, packages/composite-checkout/src/public-api.js
This adds a "free" payment method for when the cart total is 0.
- Run calypso with `ENABLE_FEATURES=composite-checkout-wpcom npm start` or use the `?flags=composite-checkout-wpcom` query string when you get to checkout.
- Purchase a plan if you don't have one already (I think this part is required?).
- Add _only_ a domain mapping product to your cart. You can do this by visiting http://calypso.localhost:3000/domains/add/mapping/your-site-here
- Visit checkout and verify that the only payment method you see is "Woohoo! You don't owe us anything!".
- Complete checkout and be sure your purchase is successful.
- Verify that the Tracks events for the purchase look correct; notably `calypso_checkout_composite_free_purchase_submit_clicked`, and the `payment_method` property of …
=> composite-checkout: Add "free" payment method

client/my-sites/domains/domain-management/contacts-privacy/card.jsx, client/my-sites/domains/domain-management/contacts-privacy/contact-display.jsx, client/my-sites/domains/domain-management/contacts-privacy/style.scss, client/my-sites/domains/domain-management/edit-contact-info/form-card.jsx, client/my-sites/domains/domain-management/edit-contact-info/index.jsx, client/my-sites/domains/domain-management/edit-contact-info/style.scss
* Remove the "Domain Contacts" card title.
* Add a new paragraph of copy that reads "Your domain contact information"
* Remove the contact information title above the contact information. 
* Move the Privacy protection toggle under the contact information (Make sure there's some space between the two).
* Edit the help text so that it only reads "Learn more about private registration and GDPR protection."
* Add a space between the edit contact info and the card like on our other screens.
* Move the "Domain owners are required to provide correct contact information." copy to the edit contact info screen
Contacts and Privacy (before):
Contacts and Privacy (after):
Edit Contact Info (before):
Edit Contact Info (after):
* Open Contacts and Privacy and Edit Contact Info and verify that things …
=> Domains: Usability fixes for the edit domain contact screens

client/my-sites/customer-home/style.scss
* Removes instances of `font-weight:300` in the banner and buttons for better readability and consistency.
* This may be a very minor nitpick, but it stuck out to me as I was reviewing #39564; we don't use 300 weights very often, so it looked out of place. Other designers are welcome to overrule me on it, though. :)
**Before**
**After**
* Create a new site from `/start` and navigate to Customer Home at `/home`, then launch your site
* The welcome banner at the top should show the subtext in 400 weight
=> Customer Home: Update font weights to use 400 weight

client/blocks/jitm/templates/sidebar-banner.jsx, client/blocks/upsell-nudge/style.scss, client/lib/abtest/active-tests.js, client/my-sites/current-site/notice.jsx, client/reader/sidebar/reader-sidebar-nudges/index.jsx
* Adds `forceHref` prop to UpsellNudges in the sidebar A/B test to make the whole banner click-able
* Hides chevron on compact UpsellNudges that are linked to conserve space
* Update test date to start on Friday (tentative)
* Also cleans up styles to avoid using `&` feature in SCSS for easier search-ability
One question: 
* Wrapping a `button` or `div` element with an anchor tag is invalid XHTML. Is this is a blocker? We're already doing this in the `Banner` component when `forceHref` is used with a call to action. I'm hesitant to refactor `Banner` to avoid stepping on existing nudges' toes.
* Open a free site; you should see the existing JITM in the sidebar.
* Switch to the `variantShowUnifiedUpsells` for the `sidebarUpsellNudgeUnification` test
* You should be able …
=> UpsellNudge: Set forceHref to true for UpsellNudges in sidebar A/B test

client/my-sites/migrate/section-migrate.scss, client/my-sites/migrate/step-upgrade.jsx
* This PR fixes an issue in the Site Migration upgrade screen where all text was replaced with ellipsis for longer items.
* Run a site migration for a site that has a longer plugin name.
* Make sure on the confirmation screen the plugin name is visible and it's cut with an ellipsis
* Make sure the UI is not broken in other ways.
=> Site Migration: Fix longer theme/plugin names not being visible on the upgrade plan confirmation screen

client/my-sites/importer/section-import.jsx, client/my-sites/migrate/helpers/index.js, client/my-sites/migrate/section-migrate.jsx, client/my-sites/migrate/step-import-or-migrate.jsx, client/my-sites/migrate/step-source-select.jsx, client/my-sites/sidebar/tools-menu.jsx
* This PR enables the import section for WordPress.com Business sites. Now we're just linking to the Import section in WP-Admin. With the updated Site Migration work we're doing, it makes sense to integrate this for WordPress.com Business sites as the functionality works well for them too.
* Non-WordPress.com Business sites should have their import experience working correctly for WordPress imports. 
* WordPress.com Business sites should have only the WordPress importer enabled.
* Content Only imports should link to WP-Admin version for WordPress.com Business sites.
* Test with and without `tools/migrate` flag enabled, to make sure the sidebar link is working appropriately. If the `tools/migrate` flag is not enabled, the link should point to WP-Admin. If it's enabled, it should open the …
=> Importing: Enable WordPress importing for WordPress.com Business sites.

client/landing/gutenboarding/onboarding-block/signup-form/index.tsx, client/landing/gutenboarding/path.ts
The current signup framework sets the language of new accounts using the language of the signup page. Seems like good behaviour to copy to me.
* Created a new `useLangRouteParam` hook by refactoring the necessary pieces out of `usePath`
* Adds the `locale` param to the `/users/new` endpoint request
* Go to `/gutenboarding/about/es` in an incognito window (UI is still in English)
* Complete signup flow
* Check network tab and see that request to `/users/new` includes the `locale=es` param
* After landing in the editor the UI should be Spanish
* Check that navigating to `/gutenboarding/about/xyz` doesn't send a bogus `xyz` locale to the new user endpoint
* Check that no `locale` param is sent if no language is specified in the url
=> Gutenboarding: Create account using the correct locale

client/landing/gutenboarding/onboarding-block/signup-form/index.tsx, packages/data-stores/src/user/types.ts
If the user has entered a site title or vertical in the intent gathering phase, then it will be used as a suggestion to the backend code that generates the username.
e.g. If site vertical is "Fashion Designer" then the username might be "fashiondesigner48238"
It prioritises the site title first and falls back to the vertical.
Originally requested by @johnHackworth and wraps up work that started in D37924-code.
* Create new accounts using `/gutenboarding`:
* Pick a vertical from the list and don't enter a site title
* Type a custom vertical and don't enter a site title
* Enter anything in the vertical field and enter a site title
* Check the generated username is what you expect.
=> Gutenboarding: create account using hints from the title and vertical (if available)

client/landing/gutenboarding/onboarding-block/signup-form/index.tsx
This patch prevents the `<Modal />` from focussing on itself, and instead forces focus on the email input field.
❓What do folks think about the trade off in relation to accessibility? Would a better description in the label mitigate this?
Trigger the signup modal in Gutenboarding.
Stare at the cursor as it blinks at you incessantly from within the email input field. Subtly mocking you. Daring you to blur it into oblivion.
=> [Gutenboarding]: add autofocus to account creation email input field

client/landing/gutenboarding/index.tsx, client/landing/gutenboarding/onboarding-block/edit.tsx, client/landing/gutenboarding/path.ts
Gutenboarding: Retain language fragment across steps, and drop the `/about` route (moving the initial step back to `/gutenboarding`).
This fixes an issue that @sirreal pointed out here: https://github.com/Automattic/wp-calypso/pull/39312#pullrequestreview-360945408
> When entering the flow at `/gutenboarding/es`, we're redirected to `/gutenboarding/about` and the locale is lost. Functionality that implemented this was added and removed from this PR, but I feel pretty strongly that this should work (redirect to `/gutenboarding/about/es`).
Also mentioned by @andrewserong at https://github.com/Automattic/wp-calypso/pull/39560#pullrequestreview-361665052.
To that end, I've also decided to move the initial step back to `/gutenboarding` (rather than `/about`). I think it makes conceptually …
=> Gutenboarding: Retain language fragment across steps, drop `/about`

client/my-sites/checkout/checkout/checkout-container.jsx, client/my-sites/checkout/checkout/checkout-system-decider.js, client/my-sites/checkout/checkout/index.jsx, client/my-sites/checkout/controller.jsx, client/signup/config/flows.js, client/signup/config/steps-pure.js, client/signup/steps/launch-site/index.jsx
* Enable checkout customisation when coming from Frankenflow by adding `preLaunch=1` as query argument to the URL.
* Don't redirect to upsell nudge when coming from Frankenflow and buying a Personal or Premium plan
* Go to `/start/frankenflow?siteSlug=SITE_SLUG` for a non-launched site
* Choose a paid plan and on the checkout page, the URL should include `preLaunch=1`
* Purchase the _Personal_ plan and you'll be redirected directly to home (no upsell nudge)
* When launching a site using the 'Launch site' button from home, nothing should change
* We can now customize checkout step https://github.com/Automattic/wp-calypso/issues/38936 - PR: https://github.com/Automattic/wp-calypso/pull/39447
Fixes #39197
=> Frankenflow: Hide up-selling nudge

packages/data-stores/global.d.ts, packages/data-stores/tsconfig.json
Removes the workaround target `ES2015` that introduced in https://github.com/Automattic/wp-calypso/pull/38503. There was a compatibility issue that was fixed in https://github.com/WordPress/gutenberg/pull/19666.
Blocked on:
There was an issue that would result in a console error message and failure to send API requests from the data-stores package:
https://github.com/Automattic/wp-calypso/pull/38503#issuecomment-568381810
That problem should not be present.
=> data-stores: Compile target es5 

client/landing/gutenboarding/index.tsx, client/landing/gutenboarding/path.ts, client/lib/i18n-utils/switch-locale.js
- Use the locale from the path to determine the locale.
- Switch stylesheets if RTL locale is detected.
Closes #39505 
1. Your user language (if logged in) or English https://calypso.live/gutenboarding/about?branch=gutenboarding/locale-from-path
1. Spanish https://calypso.live/gutenboarding/about/es?branch=gutenboarding/locale-from-path
1. Arabic https://calypso.live/gutenboarding/about/ar?branch=gutenboarding/locale-from-path ~(needs RTL work)~
Look at `document.styleSheets` for `.rtl` versions of the stylesheets to verify RTL stylesheets are loaded.
=> Gutenboarding: Use locale path for i18n

client/my-sites/importer/section-import.jsx
This PR fixes some state issues that were appearing in the import screen when trying to upload a file.
The importer section has a lot of expectations of how it's used and when accessing an importer directly, we don't save enough data in the state to keep for later. This makes several components down the line to fail and not being able to load the respective data they need to operate.
This PR adds a "temporary" (😊) hack to make sure we're always passing the right data down the chain of components. 
Ideally this should be fixed by reworking how the data storage works and how the import events are triggered (start, current steps, etc.)
This PR only fixes part of the bigger state issue the section has - it would just load the data initially. If you refresh the page on any of the steps that …
=> Imports: Fix state issues

client/my-sites/migrate/section-migrate.jsx, client/my-sites/migrate/section-migrate.scss
* This PR adds some styling to the migration flow's error page. The CSS should've been included with https://github.com/Automattic/wp-calypso/pull/39564.
* Apply the PR and run Calypso locally, or use calypso.live (for the latter, add `?flags=tools/migrate` to the end of the URL to enable the feature flag).
* Do a migration that will cause an error: go to the import section of a Simple site that is private, enter the URL of a Jetpack site and follow the steps you're presented with. 
* Alternatively, force the error page by changing `switch ( this.state.migrationStatus ) {` on line 540 of `my-sites/migrate/section-migrate.jsx` to `switch ( 'error' ) {`.
* The error you see should be styled like this:
=> Site migration: improve styling of migration error message

client/landing/jetpack-cloud/controller.js, client/landing/jetpack-cloud/routes.js, client/landing/jetpack-cloud/section.js, client/landing/jetpack-cloud/sections/backup-detail/controller.js, client/landing/jetpack-cloud/sections/backup-detail/main.jsx, client/landing/jetpack-cloud/sections/backup-download/controller.js, client/landing/jetpack-cloud/sections/backup-download/main.jsx, client/landing/jetpack-cloud/sections/backup-restore/controller.js, client/landing/jetpack-cloud/sections/backup-restore/main.jsx, client/landing/jetpack-cloud/sections/backups/controller.js, client/landing/jetpack-cloud/sections/backups/main.jsx, client/landing/jetpack-cloud/sections/dashboard/controller.js, client/landing/jetpack-cloud/sections/dashboard/main.jsx, client/landing/jetpack-cloud/sections/scan-history/controller.js, client/landing/jetpack-cloud/sections/scan-history/main.jsx, client/landing/jetpack-cloud/sections/scan/controller.js, client/landing/jetpack-cloud/sections/scan/main.jsx, client/landing/jetpack-cloud/sections/settings/controller.js, client/landing/jetpack-cloud/sections/settings/main.jsx
* Created appropriate routes for each of the pages that we'll have initially
* Reorganized page-level components into `sections` folder
* Connected page-level components to app state
* General cleanup of root controller (more to come)
Visit the following pages, with your own jetpack test site slug substituted. Each should load its respective page with correctly resolved blog ID (and in some cases, download/backup/restore ID).
- `jetpack.cloud.localhost:3000/dashboard`
- `jetpack.cloud.localhost:3000/backups/{siteSlug}`
- `jetpack.cloud.localhost:3000/backups/{siteSlug}/details/12345678`
- `jetpack.cloud.localhost:3000/backups/{siteSlug}/download/12345678`
- `jetpack.cloud.localhost:3000/backups/{siteSlug}/restore/123455678`
- `jetpack.cloud.localhost:3000/scan/{siteSlug}`
- …
=> Jetpack Cloud: Create and organize routes, sections, and root page components

client/lib/abtest/active-tests.js
This restarts the test of the composite checkout so that it becomes a 50/50 split instead of the 90% control, 10% test group that we had used for our initial soft launch.
None.
=> Restart the showCompositeCheckout test at 50/50

apps/full-site-editing/full-site-editing-plugin/starter-page-templates/page-template-modal/components/template-selector-item.js, apps/full-site-editing/full-site-editing-plugin/starter-page-templates/page-template-modal/components/test/__snapshots__/template-selector-control.test.js.snap
Addresses some a11y feedback in https://github.com/Automattic/wp-calypso/issues/33405.
* Changes `<div>` inside a `<button>` to a `<span>` to make it valid HTML
Using the FSE Plugin:
- Add a new page to show the Starter Templates
- View the HTML on a starter template button (such as Blank or About)
- See that there are only `<span>`s and no `<div>`s inside of the button
Fixes a small part of #33405
=> FSE: Changed div to span on template select button inner HTML

client/my-sites/customer-home/style.scss
Buttons with line breaks in their text look disorienting, and our mobile views of Customer Home can display the View Site button in this way. This PR ensures the button text does not wrap.
**Before**
**After**
- Load this branch and go to a newer test site that has Customer Home.
- View http://calypso.localhost:3000/home/:site on a mobile view.
- Verify the View Site button has no line breaks.
=> Home: Don't allow line breaks in the View Site button text.

client/my-sites/customer-home/main.jsx, client/my-sites/customer-home/style.scss, client/my-sites/customer-home/welcome-banner.jsx
Add a welcoming banner to Customer Home, so that users that have never been redirected there before can understand why they're there and how the page can help them.
Fixes #39178 
* Load this branch and select a site's Customer Home ("My Home") page.
* Enable logging for Tracks in the console with `localStorage.debug = 'calypso:analytics:*'`.
* Open DevTools' Network tab.
* Click the `X` to close.
* Verify a successful POST call to `/me/preferences` was made.
* Confirm in the console that the Tracks event fired.
* To retest, use the WP.com API console to POST to `/me/preferences` with `{"dismissible-card-home-welcome-banner-dismissed":null}` in the `calypso_preferences` body.
=> Customer Home: Add a welcome banner.

client/my-sites/checklist/wpcom-checklist/component.jsx
* The original mobile app and email verification completed copy was confusing, suggesting the task had not actually been completed. Let's update it to make that clearer.
* /cc @obi2020 and others for feedback/suggestions, my copy in this PR is probably not rock solid. Suggestions welcome!
**Before**
**After**
* Switch to this PR, create a new site, and navigate to Customer Home
* Complete email verification and downloading the mobile app
* You should see the tasks in the completed list, with updated copy
Fixes #39416
=> Customer Home: Add better copy for completed email and mobile app tasks

client/my-sites/checkout/checkout/composite-checkout.js
This adds some new analytics events for composite checkout. The new events are `calypso_checkout_composite_form_submit` and `calypso_checkout_composite_payment_error` and match the existing `calypso_checkout_form_submit` and `calypso_checkout_payment_error` events but are specific to composite checkout and so should help us track them more easily.
- Enable debug by putting this in your console: `localStorage.setItem('debug', 'calypso:analytics:*')`
- Submit a transaction through composite checkout and be sure that the new events appear in the debug logs.
=> composite-checkout: Add generic submit/error events for payment methods

client/my-sites/checkout/checkout/composite-checkout.js, packages/composite-checkout-wpcom/src/hooks/use-shopping-cart.ts
This modifies the `calypso_checkout_composite_cart_error` analytics event to include the actual error message itself.
Somehow you need to cause `getServerCart()` to fail. Probably the easiest thing to do is to modify `packages/composite-checkout-wpcom/src/hooks/use-shopping-cart.ts` and add this change: 
```diff
--- a/packages/composite-checkout-wpcom/src/hooks/use-shopping-cart.ts
+++ b/packages/composite-checkout-wpcom/src/hooks/use-shopping-cart.ts
@@ -505,6 +505,9 @@ function useInitializeCartFromServer(
debug( `initializing the cart; cacheStatus is ${ cacheStatus }` );
getServerCart()
+                       .then( () => {
+                               throw new Error( 'testing error' );
+                       } )
.then( response => {
if ( productToAdd ) {
debug(
```
Next enable …
=> composite-checkout: Include error message in cart error

client/my-sites/customer-home/main.jsx
Custom Home banner logic is a little convoluted; it can result in banners being displayed, then replaced by others as state updates. This PR eliminates the most common causes, but a proper fix after A/B testing would involve at least refactoring and more likely moving this logic server-side.
* Go to https://wordpress.com/home and make sure the welcome banner displays with your current user.
* Create a new site. Notice the welcome banner will flash then be replaced by "your site has been created".
* Launch the site. Watch the welcome banner be replaced by "your site has been created" be replaced by "you launched your site".
* Switch to this branch with the same user.
* Repeat the process, and verify only one banner gets rendered in each situation.
=> Home: Don't display banners that will be superseded by others.

client/lib/abtest/active-tests.js, client/me/help/help-courses/test/index.jsx, client/state/sites/selectors/can-current-user-use-customer-home.js, config/desktop.json, config/development.json, config/horizon.json, config/production.json, config/stage.json, config/test.json, config/wpcalypso.json
This PR removes the 'home/all' feature flag, and adds a 'customerHomeAll' A/B test set to 90% control, 10% active test. If a user rolls the `control` variant, display of Customer Home in the sidebar for a Simple or Atomic site is determined by if the site was created after Aug 2019.
| Control  | showCustomerHome |
| <img width="1235" alt="Screen Shot 2020-02-04 at 1 32 21 PM" src="https://user-images.githubusercontent.com/1270189/73789392-8e17bf00-4753-11ea-955a-58df9f8e44a2.png"> | <img width="1238" alt="Screen Shot 2020-02-04 at 1 32 52 PM" src="https://user-images.githubusercontent.com/1270189/73789416-966ffa00-4753-11ea-9dea-2728b6d3efab.png"> |
Do Not Merge Until
- On a Simple Site created before Aug 2019, verify that Customer Home appears with …
=> Customer Home: Show All 90/10 A/B Test

client/my-sites/checkout/checkout/composite-checkout.js, packages/composite-checkout/src/components/checkout.js
In addition to the current step number recorded by the Tracks event `calypso_checkout_composite_step_changed`, this also records the current step object's id.
It also adds a new event, `calypso_checkout_composite_first_step_complete`, which is called after
the first (payment method) step is completed. The event records the currently active payment method.
- Enable debug by putting this in your console: `localStorage.setItem('debug', 'calypso:analytics')`
- Submit a transaction through composite checkout and be sure that the new events and event properties appear in the debug logs.
=> composite-checkout: Improve step change analytics events

client/assets/stylesheets/shared/mixins/_heading.scss, client/components/action-panel/style.scss, client/components/date-picker/style.scss, client/components/empty-content/style.scss, client/components/faq/style.scss, client/components/forms/form-section-heading/style.scss, client/components/gsuite/gsuite-price/style.scss, client/components/post-schedule/style.scss, client/components/sidebar-navigation/style.scss, client/components/web-preview/style.scss, client/devdocs/style.scss
Removes instances of `font-weight: 300` across SCSS typography mixin and components. 
`*` = I wasn't able to find the associated style with a corresponding class name in the markup, which may mean these selectors can be removed entirely.
Examples (there are many areas to check, so I won't add all the screenshots here, although I do have a library full of 'em if it would be helpful):
**Before**
**After**
Visually test the following areas and component instances:
* /devdocs sidebar title
* Stats heading, throughout stats, but most noticeably on the front page with the "Stats for [date]" heading
* ActionPanel component, heading
* DatePicker component, table caption with month and year
* EmptyContent component, heading and text
* FAQ component, heading
* FormSectionHeading …
=> Typography: Remove font-weight: 300

client/lib/abtest/active-tests.js, client/signup/steps/plans/index.jsx, config/development.json, config/wpcalypso.json
We have a new AB test for updating the copy on the plans step in signup. Please read more on the testing post at p8Eqe3-144-p2.
* Enable the new plan step AB test for dev and wpcalypso environment
* Change the plans step header text for the variant, as shown in pbBQWj-T-p2#comment-36
_Note: The other UI pieces of the variant will be built in separate PRs on top of this PR._ 
**Control**
**Variant**
**In dev or wpcalypso environments**
Use http://calypso.localhost:3000/ URL for **dev** environment or https://calypso.live/?branch=add/create-plan-step-abtest for **wpcalypso** environment.
* Go through the signup flow from /start.
* Verify that on any step before the plans step, you are not assigned to the new AB test. You can verify this by typing `localStorage.ABTests;` in your browser …
=> Enable plans step AB test for test environments

packages/calypso-build/CHANGELOG.md, packages/calypso-build/package.json
Bump package version and publish 6.1.0.
=> calypso-build: add missing changelog entry and publish 6.1.0

client/components/domains/domain-registration-suggestion/index.jsx, client/my-sites/checkout/checkout/domain-registration-hsts.jsx
All domains ending in .dev require an SSL certificate to host a website. When you host this domain at WordPress.com an SSL certificate is included in your paid plan.
The last part does not apply to me, since I'm a non-DWPO user and does not have to have a paid plan with domain.
Suggestion: remove "in your paid plan" - then it applies to everyone.
Go to Domains -> Add domain and search for a random `.dev` domain.
You should see the updated copy when you click on the `i` icon:
When you reach the end of checkout (just before paying), you should see the updated copy as well:
=> Domains: Adjust SSL copy for Google domains

apps/full-site-editing/full-site-editing-plugin/blog-posts-block/editor.js
The [recently synced version of Newspack Articles block](https://github.com/Automattic/wp-calypso/pull/39270) introduced the QueryStore in the editor. We're defining our own `editor.js` here, so apart from syncing the code, we also need to register our own QueryStore (originally added in https://github.com/Automattic/wp-calypso/pull/39509). Without it, the block doesn't work and shows the following errors:
Adding Blog Posts block should now not throw any errors and render the block correctly. Compare with `master` to see the errors.
=> Blog Posts Block: Add missing QueryStore registration

client/landing/jetpack-cloud/components/current-site/index.tsx, client/landing/jetpack-cloud/components/current-site/style.scss, client/landing/jetpack-cloud/components/sidebar/index.jsx
* Add Current Site Indicator if a site is selected
1. Navigate to `/backups` and verify that there is no current site indicator
2. Navigate to `/backups/:siteSlug` for a valid `siteSlug` and confirm that the page matches the screenshot above
=> Jetpack Cloud: Add Current Site Indicator

client/my-sites/migrate/components/sites-block/index.jsx
* Auto-focus the URL input in the migration flow
* Ensure the `tools/migrate` feature-flag is enabled.
* Select "Import" for a simple site from the sidebar.
* Select "WordPress".
* Verify that the URL input field is focused when it loads into view.
=> Migration: Auto focus URL input in migration flow

client/my-sites/customer-home/go-mobile-card/index.jsx
[The desktop app has issues](https://github.com/Automattic/wp-desktop/issues/777#issuecomment-590390781) with the endpoints that provide the email download link, such that this button's API request will never pass authentication checks. This PR removes the button in the Go Mobile card to avoid confusion for desktop app users.
|<img width="1221" alt="Screen Shot 2020-02-24 at 1 06 18 PM" src="https://user-images.githubusercontent.com/349751/75191591-7787d680-5707-11ea-8e8d-fb65284c17ed.png">|<img width="1193" alt="Screen Shot 2020-02-24 at 12 59 01 PM" src="https://user-images.githubusercontent.com/349751/75191614-81113e80-5707-11ea-98c2-6d5b544a9f68.png">| 
* In your local desktop dev setup, change your working directory to the …
=> Customer Home: Remove broken "email download link" button from the desktop app.

client/landing/jetpack-cloud/controller.js
* Loads in `<MomentProvider />` to Cloud layouts.
* Add component wrapped with `withLocalizedMoment` HOC.
* Examine props of component.
=> Adds MomentProvider component to Cloud

client/my-sites/checkout/cart/cart-free-user-plan-upsell.jsx
In domain-only checkout, no site is selected, so the existing logic didn't work. I've disabled the upsell for this case in the short term. It shouldn't be live for users yet anyway.
* Fix the logic so that we handle a null `selectedSite` - the underlying bug was introduced in #39610.
1. Go to `/domains/` and search for a domain.
2. Select a domain and move forward with the flow.
3. When you're presented with the options for how to use your domain, click on "Just buy a domain".
4. You should be redirected to the domain registrant workflow in checkout and should not see a plan upsell. (Before this change, you'd only see a blank screen.)
=> Hot fix for a bug affecting domain-only site checkout

apps/full-site-editing/full-site-editing-plugin/starter-page-templates/page-template-modal/components/template-selector-preview.js, apps/full-site-editing/full-site-editing-plugin/starter-page-templates/page-template-modal/components/test/__snapshots__/template-selector-preview.test.js.snap
Closes https://github.com/Automattic/wp-calypso/issues/39343
As [identified in the Issue](https://github.com/Automattic/wp-calypso/issues/39343#issuecomment-590837057) the **block preview** component was missing a class within it's cascade that Core Blocks relied upon in order to apply particular styles. This issue was not in evidence within the Post Editor - only in the Block Previews.
The missing class is `.block-editor`. This is probably used by a number of Core Blocks to apply styles. 
This PR introduces this class on the **top level of the Block Preview component**. This ensures selectors that rely on this class name are applied.
In our specific case we are addressing the Issue where borders are shown on Contact Page Template's form input fields due to the [missing Core …
=> Adds `block-editor` class to cascade to ensure Core classes are applied

apps/full-site-editing/full-site-editing-plugin/starter-page-templates/page-template-modal/styles/starter-page-templates-editor.scss
This PR aims to provide a pragmatic solution to the issue reported in https://github.com/Automattic/wp-calypso/issues/39351. With this PR in place, fixed background images on the cover block should fill the entire block in the SPT preview.
For further details please see this [in-depth comment](https://github.com/Automattic/wp-calypso/issues/39351#issuecomment-590954987).
* Check out this PR locally and run `npx lerna run dev --scope='@automattic/full-site-editing' --stream` from Calypso root 
* Navigate to `Pages` > `Add New` to create a new page
* In the page template selector, scroll down to `Home Pages`
* Select the `Rockfield` page template (the one with cook's hands on it)
* Verify that the result you see matches the After state below
**Before:** 
**After:**
Fixes …
=> SPT: Make cover block images fill entire block in SPT preview

client/my-sites/guided-transfer/issues-notices.jsx, client/my-sites/guided-transfer/transfer-unavailable-card.jsx
This PR removes unnecessary whitespace from translations and replaces template literals since they are no longer needed.
- Check if tests pass
- Open http://calypso.localhost:3000/export/guided/{site}
- Check if text renders as expected
=> Remove unnecessary whitespaces from translations

client/components/domains/search-filters/tld-filter-bar.jsx
* Adds a unique key so that we no longer see the following warning message in console for the domain step in signup(when in _variantDesignUpdates_ of "domainStepDesignUpdates" test).
```
backend.js:6 Warning: Each child in a list should have a unique "key" prop.
Check the render method of `TldFilterBar`.
```
Fixes issue reported in https://github.com/Automattic/wp-calypso/pull/39346#discussion_r383823091
* Go through signup flow at /start. Assign yourself to _variantDesignUpdates_ of "domainStepDesignUpdates" test.
* At the domain step, verify that you no longer see the warning message in browser console.
=> Domain step: Add unique key to each child in list

apps/full-site-editing/README.md, apps/full-site-editing/package.json
Currently the FSE `README.md` has little or no guidance on
* Running tests
* Writing tests
This PR aims to rectify this by documenting how to run tests and also providing an insight into the recommended style of the tests.
As an additional improvement, the PR also introduces a dedicated command for updating snapshots (a common requirement that can be difficult to undertake given the additional abstraction of `lerna`).
```shell
npx lerna run test:js:update-snapshots --scope='@automattic/full-site-editing' --stream
```
* Read the changes to the `README`.
* Check spelling and grammer.
* Check it makes sense.
* Follow the instructions running each command in turn and verifying the output is as expected based on the guidance in the README.
=> FSE: add unit testing instructions to README

client/my-sites/checkout/checkout-thank-you/domain-registration-details.jsx
This PR adds a plan upsell card after the purchase of a domain by free users as part of this test: p99Zz8-10j-p2
Recommended to use Store Sandbox:
* Select a site that is on a free plan
* Purchase a domain
* Right after the purchase, in the Thank You page, you should see this card among others:
Also verify that the functionality works, and that clicking the button takes you to the right page.
=> Checkout: Add plan upsell when non primary domain is purchased

client/lib/stripe/index.js, client/my-sites/checkout/checkout/checkout-system-decider.js, client/my-sites/checkout/checkout/composite-checkout-payment-methods.tsx, client/my-sites/checkout/checkout/composite-checkout.js, client/my-sites/checkout/checkout/test/composite-checkout.js, packages/composite-checkout/README.md, packages/composite-checkout/demo/index.js, packages/composite-checkout/src/components/checkout-provider.js, packages/composite-checkout/src/lib/payment-methods/apple-pay.js, packages/composite-checkout/src/lib/payment-methods/existing-credit-card.js, packages/composite-checkout/src/lib/payment-methods/stripe-credit-card-fields.js, packages/composite-checkout/src/lib/stripe.js
This PR changes how payment methods load Stripe.js by forcing the host page to load it rather than handling the loading themselves. The motivation was so that we can check for Apple Pay availability before loading any payment methods, but it has the added advantage of simplifying the API of payment methods. 
Previously each payment method object could have a `checkoutWrapper` property which would be used to wrap the entirety of the checkout form. Although this could have other applications the intent was to make it possible for payment methods that required a shared stripe context to create one in state that was shared between sibling components in the form.
With this PR, we remove the concept of a `checkoutWrapper` and instead simply make it a requirement of stripe payment methods …
=> composite-checkout: Move stripe wrapper to host page

client/my-sites/checkout/checkout/composite-checkout.js, packages/composite-checkout/src/lib/payment-methods/apple-pay.js
This adds a new tracks error when Apple Pay fails to load. The error uses the existing `calypso_checkout_composite_apple_pay_error` event but includes the `is_loading_error` property.
There are two checks for loading apple pay. The first is to see if Apple Pay is supported by the browser. This check is performed before showing the Apple Pay method at all. However, once we decide to try and display it, we actually contact Apple to make it appear. This can fail in certain circumstances, for example if the domain the button is hosted on is not correctly registered with Apple, or if the device is not a real Apple device.
This PR allows us to track how often this second case occurs in the wild (hopefully never).
Using composite checkout in Safari, enable debug logs for Tracks by putting this …
=> composite-checkout: Add tracks event for when apple pay fails to load

client/landing/jetpack-cloud/components/sidebar/index.jsx, client/landing/jetpack-cloud/routes.js, config/jetpack-cloud-development.json, config/jetpack-cloud-production.json, config/jetpack-cloud-stage.json
This PR adds support for feature flags to Jetpack Cloud. 
* Add Jetpack Cloud feature flags in config
* Set up routes and render sidebar menu items based on feature flags
* Try disabling some of the Jetpack Cloud sections in `config/jetpack-cloud-development.json`
* Restart your local environment with `npm run start-jetpack-cloud`
* Go to http://jetpack.cloud.localhost:3000/ and confirm the disabled section is no longer listed in the sidebar
Fixes 1156570014567299-as-1157678527369092
=> Add support for features flags in Jetpack Cloud

client/my-sites/plans-features-main/products-header.jsx
* Resolves typo with Jetpack Connect landing page.
* Try to connect site to Jetpack.
* Scroll down to backup product promo area.
* Examine header.
Screenshot:
Fixes 1142395350490785-as-1157925867453225.
=> Fixes typo with Jetpack connect landing page

apps/full-site-editing/full-site-editing-plugin/full-site-editing-plugin.php, apps/full-site-editing/full-site-editing-plugin/readme.txt, apps/full-site-editing/package.json
- Bumps FSE plugin to version 0.20
- Updates for i18n changes in Event Countdown and Timeline
Related: #39554
=> Bump FSE to 0.20

client/my-sites/plans/main.jsx
* Add props to the `calypso_plans_view` when we display the "Your plan is managed by $x" message.
* To support ^, defer the `calypso_plans_view` event that occurs in the render method until we have the `purchase` object and are able to decide whether the purchase is managed by a hosting partner.
* Go to http://calypso.localhost:3000/plans/$site where $site is a domain that does not have a partner plan
* In the console, run`localStorage.setItem( 'debug', 'calypso:analytics:TrackComponentView' );`
* Refresh the page
* Ensure that the `calypso_plans_view` tracks event fires
* Switch to a site that has a partner managed plan and ensure that the `calypso_plans_view` tracks event fires
* Wait for the tracks events to come through and ensure that the second view had `partner_managed` and …
=> Plans: Defer page view until we get the purchase object

client/lib/plans/plans-list.js, client/my-sites/plan-features/actions.jsx, client/my-sites/plan-features/header.jsx, client/my-sites/plan-features/index.jsx, client/my-sites/plan-features/style.scss, client/my-sites/plan-price/index.jsx, client/my-sites/plan-price/style.scss, client/my-sites/plans-features-main/index.jsx, client/signup/steps/plans/index.jsx
The new plan step AB test is enabled in #39600. Individual pieces of the UI will be built in separate PRs and finally merged together.
* Update the plan features box with the latest UI proposed in p8Eqe3-144-p2.
**BEFORE**
**AFTER**
**Mobile view**
**SUMMARY OF CHANGES**
* Changed plan header from "Personal", "Business" etc. to "Personal plan", "Business plan" etc.
* Plan sub-header changed for each plan - "WordPress essentials ...", "Powerful tools at a great value", ...
* Plan price changed from $4 to $4 per month, currency symbol in the new UI is aligned to top of the price text.
* Below the plan price, showing annual price in the new UI "Billed at $96 per year."
* Update plan descriptions copy
* Updated CTA button text and placed it below the plan description.
**Scenario 1**
* Go …
=> Plan step test: Update the plan features list UI and copy

apps/full-site-editing/full-site-editing-plugin/starter-page-templates/page-template-modal/index.js, apps/full-site-editing/full-site-editing-plugin/starter-page-templates/page-template-modal/utils/map-blocks-recursively.js, apps/full-site-editing/full-site-editing-plugin/starter-page-templates/page-template-modal/utils/modify-blocks.js
Closes https://github.com/Automattic/wp-calypso/issues/39663
The JP contact form Block has a "placeholder" settings view which is shown to guide the user toward filling in the necessaey fields. However, this doesn't look good in the SPT template preview window.
This PR will:
The key things to check are:
* The Contact form block doesn't show the settings placeholder **in the preview**.
* The form block _does_ show the settings placeholder once the template has been inserted into the Editor.
This requires the FSE Plugin to be active on your WP install. You can find guidance for this at `PaYJgx-sW-p2`. You can test on local WP instance or WPCom (assuming you have sandbox syncing setup).
* Activate FSE Plugin.
* Create new Page.
* See SPT selector.
* Click "Contact" template to show the …
=> FSE: Refactor SPT template block parsing to hide Jetpack Contact Form block "placeholder"

client/my-sites/plan-features/index.jsx, client/my-sites/plan-testimonials/index.jsx, client/my-sites/plan-testimonials/style.scss, client/my-sites/plans-features-main/index.jsx
The new plan step AB test is enabled in #39600. Individual pieces of the UI will be built in separate PRs and finally merged together.
* Adds the testimonial section to the plans page.
**Desktop**
**Mobile**
* Go through the signup flow after assigning yourself to _variantShowUpdates_ of _planStepCopyUpdates_ test.
* In the Plans step, verify that the testimonial section matches the UI as per the P2 post p8Eqe3-144-p2.
* Desktop and mobile sceeen sizes should look okay
=> Plan step test: Add testimonial section below plan features

client/my-sites/plans-features-main/index.jsx
* In the plan step test, we show testimonials below the plan features as implemented in #39630. This section needs to be shown only to eligible users.
* Go through the signup flow while in control group of _planStepCopyUpdates_ test and verify that you are not shown the testimonial section.
* Go through the variant while in dev or wpcalypso environment and verify that you are shown the testimonial section.
=> Plan step test: Show testimonial section only for eligible users

client/landing/jetpack-cloud/components/activity-list/docs/example.tsx, client/landing/jetpack-cloud/components/activity-list/index.tsx, client/landing/jetpack-cloud/components/activity-list/types.ts, client/landing/jetpack-cloud/components/log-item/index.tsx, client/landing/jetpack-cloud/sections/backups/main.jsx
This creates a new `<ActivityList>` component which displays Rewind entries from the activity log.
* Adds new `<ActivityList>` component.
* Wires activity log data to new component.
1. Visit jetpack.cloud.localhost:3000/backups/[site].
2. View activity log entries.
Screenshot:
Fixes 1156570014567299-as-1163126197389644.
=> Connects to activity log and displays backup entries

client/my-sites/domains/domain-management/edit/card/renew-button/index.jsx, client/my-sites/domains/domain-management/edit/card/renew-button/style.scss, client/my-sites/domains/domain-management/edit/domain-types/registered-domain-type.jsx, client/my-sites/domains/domain-management/edit/style.scss
* Add a "Renew for X" button on the domain status screen
D39372-code - in order to properly show WWD domains in ARGP
Active domain:
Expires soon:
Expires very soon:
Expired renewable:
Expired redeemable:
* best way is to check a domain in every of the possible states and verify if the "Renew for $XX" button is visible. You can use the following instructions - 24083-pb
* verify that other currencies also work properly
* verify that the reactivate button for domains in redemption is showing the correct amount
=> Add renew button on the domain status screen

apps/full-site-editing/full-site-editing-plugin/starter-page-templates/page-template-modal/styles/starter-page-templates-editor.scss
This updates the confirmation button alignment to something a bit more familiar. 
1. Select some page content
2. Open Page Layout in the sidebar, and click "Change Layout"
3. Verify that the modal's buttons now look more consistent with the style used elsewhere throughout WordPress
**Before:**
**After:**
Fixes #38146
=> FSE: Improve Confirmation Modal Button Alignment

client/my-sites/migrate/migrate-button.jsx
* Update the confirmation modal to include a header
Before: 
After:
* Click on "Import" in the sidebar while a Simple (or Atomic) site is selected.
* Select "WordPress".
* Enter the URL to a Jetpack-connected WordPress site.
* Select "Import Everything".
* Continue through the flow until you see the confirmation dialog.
Fixes #39580
=> Migration: add header to confirmation dialog

client/blocks/product-selector/index.jsx, client/jetpack-connect/controller.js, client/jetpack-connect/plans-landing.jsx, client/jetpack-connect/plans.jsx, client/jetpack-connect/test/__snapshots__/plans.js.snap, client/my-sites/plans-features-main/index.jsx
See p1HpG7-8CV-p2 for a discussion of the issue
* Fix Jetpack store flow so that user can arrive on the checkout page with a Backup product
1. In a fresh private window, navigate to `/jetpack/connect/store`
2.  Make note of the selected product ( Daily vs Real-Time )  then click the "Get Real-Time Backups" button near the bottom
3. Confirm you are taken to a Jetpack-branded page `/jetpack/connect`
4. proceed through the flow with a test Jetpack site and WordPress.com user, until you reach the checkout page
5. Confirm you have the backup product that corresponds to what you chose in step 2
=> Fix Flow For Jetpack Backups from `jetpack/connect`

client/my-sites/migrate/section-migrate.scss, client/my-sites/migrate/step-source-select.jsx
This PR moves the error notice in the Site Migration screen above the content card.
* Apply diff or use Calypso.live link
* Go to Import -> WordPress
* Type an invalid URL or a WordPress.com site address
* Check where and how the error appears
Fixes #39579
=> Site Migration: Move the error notice above the content card

packages/calypso-color-schemes/src/shared/color-schemes/_classic-blue.scss
This fixes the notification dot colour with the Classic Blue scheme so that it uses its own accent colour (at the same shade as most the others)
Trigger a notification (which can be done by making a comment on a blog post that needs approval) and verify the dot is now orange.
Fixes #39660
=> Notification Bubble: Fix Colour with Classic Blue

client/my-sites/migrate/components/sites-block/index.jsx, client/my-sites/migrate/components/sites-block/style.scss, client/my-sites/migrate/step-source-select.jsx
* Simplifies the UI during the source selection step of migration on small viewports to give the URL input more room and make it more usable.
* Apply the PR and run Calypso locally, or use `calypso.live` (for the latter, add `?flags=tools/migrate` to the end of the URL to enable the feature flag).
* Start a migration: go to the import section of a Simple site and choose the WordPress importer.
* On the next page, on mobile viewports you should see a URL input. On bigger viewports, the input should have a second element next to it to indicate where the migration will go.
* Enter the URL of a Jetpack site and click the "Continue" button. The "from" and "to" elements of the UI should be visible at the top of the page in all viewports.
=> Site migration: hide part of UI on mobile to make URL input more usable

client/my-sites/activity/filterbar/date-range-selector.jsx
Set the start date to the start of the day (00:00:00).
**Context**
By default, the start date is set to YYYY-MM-DD 12:00:00. Because of this, we may be inadvertently filtering out entries of things that occurred before 12:00:00 on the selected date.
- Go to Calypso
- Select a site
- Open the Activity Log section
- Select a date in which there are log entries before 12:00:00
- Entries should be missing from the selected date
**Screenshot**
With filtering
Filtering (one entry is missing)
=> DateRangeSelector: Set the start date to the start of the day (00:00:00)

client/my-sites/migrate/section-migrate.scss, client/my-sites/migrate/step-upgrade.jsx
* This PR changes a bit the layout and styling on the upsell step of site migration to make it a bit better looking on mobile
* More information in #39576
* Use Calypso.live link
* Start migration on a WordPress.com Simple site
* Reach the upsell page where you have to buy the Business plan
* Change the page width to less than 800px
* Make sure it looks well
* Try switching to different device screens in developers tools (Chrome or Firefox) 
* Again make sure it looks good on both small screens and desktop sizes.
Fixes #39576
=> Site Migration: Fixes the upsell as proposed by design

client/lib/analytics/ad-tracking.js
* Upon purchase we now pass the transaction id to Floodlight via the `u8` param.
Note:` u6` and `u7` prarams after further inspection did not need any fixing.
Visit: https://calypso.live/?branch=fix/pass_transaction_id_to_floodlight_u8
Enable tracking and logging via JS console:
```
document.cookie = 'flags=gdpr-banner,google-analytics,ad-tracking; path=/; domain=.' + document.location.hostname.split( '.' ).slice( -2 ).join( '.' );
localStorage.setItem( 'debug', 'calypso:analytics:*' );
```
Reload browser ♻️ 
The JS console should now show various lines with: (filter by `isAdTrackingAllowed`)
```
calypso:analytics:utils isAdTrackingAllowed: true
```
Purchase a plan for a test website using free credits.
In your JS log you should see the `u8` parameter being passed in the dataLayer:
and …
=> Pass orderId to DCM u8 parameter

client/lib/analytics/ad-tracking.js
Disable AdRoll and IconMedia analytics.
Visit: https://calypso.live/?branch=update/disable-adroll-iconmedia-analytics
Enable tracking and logging via JS console:
```
document.cookie = 'flags=gdpr-banner,google-analytics,ad-tracking; path=/; domain=.' + document.location.hostname.split( '.' ).slice( -2 ).join( '.' );
localStorage.setItem( 'debug', 'calypso:analytics:*' );
```
Reload browser ♻️ 
The JS console should now show various lines with: (filter by `isAdTrackingAllowed`)
```
calypso:analytics:utils isAdTrackingAllowed: true
```
Now that the above trackers don't fire anymore searching for the following in the Network activity in Chrome's Dev Tools should not return any entry: `adroll.com` ,`w55c.net` - while these entries are present in the live site (remember to enable tracking).
=> Disable AdRoll and IconMedia analytics

client/my-sites/plans-features-main/jetpack-faq.jsx
* This updates the text in the FAQ for Jetpack to indicate Jetpack works for multisite except for backups.
* Visit the plans page in Calypso and examine FAQ.
New text:
Fixes 1142395350490785-as-1153599598600715.
=> Updates FAQ text for Jetpack plans

apps/full-site-editing/full-site-editing-plugin/full-site-editing-plugin.php, apps/full-site-editing/full-site-editing-plugin/readme.txt, apps/full-site-editing/package.json
Since the latest FSE update on dotcom (D39601-code) didn't bump the constant versions of the plugin, we need to:
1. Get those versions on .com
2. Make sure the code on .com includes the latest changes in FSE (since it is possible the update happened with code on a stale branch).
1. Test the attached diff
2. Deploy to dotcom
3. Deploy to dotorg
4 Merge this PR
=> FSE: Update to 0.21

client/blocks/login/login-form.jsx, client/components/forms/form-input-validation/index.jsx
When testing Jetpack's signup flow, I felt it was awkward if I tried to log in with a previously unknown email:
- the link to create an account is not very prominent, and possibly below the fold on mobile devices
- the error doesn't contain an action the user can take, e.g. creating a new account
* Prompt user to create an account if they try to log in with an unknown email
... then after clicking the link...
* Connect a Jetpack site
* Attempt to log in using a previously-unregistered email
* You should be prompted to "create a new account" in the error message
* Clicking to create an account should take you to the correct screen to do so
=> Prompt the user to create an account if they try to log in with an unknown email

client/state/data-layer/wpcom/sites/jitm/index.js, client/state/data-layer/wpcom/sites/jitm/schema.json
* Add `isDismissible` value to the JITMs state tree.
* You may need to install [Redux devtools](https://github.com/reduxjs/redux-devtools).
* Open the Redux devtools and go to stats page of your free site.
* When `Free domain with a plan` banner appears in the sidebar, filter `JITM` actions.
* You should be able to `isDismissible` in the raw state.
=> JITM: JITMs accept is_dismissible value

client/my-sites/domains/domain-management/list/item.jsx, client/my-sites/domains/domain-management/list/style.scss
* simplify the site domain list and use only one onClick handle on the CompactCard component so that the whole row is clickable
* remove unnecessary button and label tags
* fix up the CSS so that the item row looks good and the spinner during primary domain change looks okay
Setting primary domain before:
Setting primary domain after:
* go in manage > domains on site with more than 1 domain and click on the `Change Primary` button
* click on any row and verify that the whole row is clickable
* verify that the spinner and the text shown during the change is not misplaced
* test the mobile version too
=> Usability fixes for the site domain list and setting the primary domain

apps/full-site-editing/full-site-editing-plugin/starter-page-templates/page-template-modal/styles/starter-page-templates-editor.scss
* Sets margin top/bottom to `0` on `core/block` in the editor preview. This is only noticeable when there are two full-width backgrounds with color or photo above one another.
Before:
After: 
* Have FSE installed locally. See existing documentation on how to get this running.
* Add a new page
* Check that previews look correct, specifically Stratford (in the home page templates.
* There should be no gap between full-width group blocks with backgrounds
* There should be no regressions in templates where there should still be a gap
=> Fix spacing on full-width group blocks on iframed SPT previews

apps/full-site-editing/package.json
Based on #39806, adds color output to e2e tests as well.
Before:
After:
Run `npx lerna run test:e2e --scope='@automattic/full-site-editing' --stream` and look at the colors :)
=> Add color output to FSE e2e tests

client/blocks/get-apps/apps-badge.jsx
* Use https instead of http to load app store badge in different locales than English.
Fixes https://github.com/Automattic/wp-calypso/issues/39810
I haven't actually confirmed this fixes it, just seemed obvious when reading the code.
See https://github.com/Automattic/wp-calypso/issues/39810
=> Play store badge: load from https instead of http

client/my-sites/domains/domain-management/edit/card/domain-status/index.jsx, client/my-sites/domains/domain-management/edit/style.scss
* Add border and padding between multiple domain status messages
* Scale the font size of the domain if it's longer
* Open a domain with multiple messages - for example expiring soon and unverified and check if there is a grey line with proper padding
* Open a long domain name and check that it is shown with smaller font size and is not overflowing from the container
The separating line looks like this:
And here are some examples of short and long domain names and how they show up on desktop and mobile:
=> New domain status design tweaks

packages/components/src/dialog/style.scss
This PR adjusts the line height of h1 in Dialog, so that things look better.
Before:
After:
* Run branch
* Go to a part of the UI where a Dialog is shown with an h1 heading, such the confirmation modal in the WP Import migration flow
* Verify that the dialog's style is updated and looks better
Fixes #39748
=> Dialog: Improve line height of h1

client/lib/purchases/index.js, client/my-sites/domains/domain-management/edit/card/renew-button/index.jsx, client/my-sites/domains/domain-management/edit/domain-types/registered-domain-type.jsx
* We've added some additional properties for the renew action on the new domain status screen. We want to verify how often those buttons would be used.
* Open the new domain status screen and click on the Renew for XXX button. In your browser dev tools verify in the Network tab that a call is made to the tracks pixel including both `source` and `domain_status` properties
=> Add better tracking for the Renew button in the new domain status screen

client/my-sites/migrate/section-migrate.jsx, client/my-sites/migrate/step-upgrade.jsx
* Adds `backHref` to the `HeaderCake` on the business plan page
* On a simple site, click "Import" in the sidebar.
* Select "WordPress".
* Enter a URL and continue in the flow until you arrive at the business plan page.
* Click the back button in the header cake. Verify that you are taken to the previous page.
Fixes #39574
=> Migration: Set backHref for HeaderCake on business plan page

client/landing/gutenboarding/devtools.ts, packages/data-stores/.eslintrc.js, packages/data-stores/jest.config.js, packages/data-stores/src/auth/actions.ts, packages/data-stores/src/auth/controls.ts, packages/data-stores/src/auth/index.ts, packages/data-stores/src/auth/reducer.ts, packages/data-stores/src/auth/selectors.ts, packages/data-stores/src/auth/test/actions.ts, packages/data-stores/src/auth/test/flows.ts, packages/data-stores/src/auth/test/reducer.ts
* Handle errors that come up in the standard username/password flow
* Add `getErrors()` and `getFirstError()` selectors to get the lastest error code and message returned by the server
* Don't expose actions in the public api that users of the store shouldn't use e.g. `receiveWpLogin()`
* Switch to `nock` for mocking fetch calls
* Update `no-extraneous-dependencies` lint rule for test files (they're allowed to use dev dependencies from the root of the repo
I couldn't figure out how to use `nock` to mock the calls made using `wpcom-proxy-request`, probably something to do with it making an iframe under the hood instead of sending an xhr. I see other examples in the codebase doing it though.
* Go to `/gutenboarding` and open network tab and console
* Use the following to test the auth …
=> Gutenboarding: Add error handling for password flow to auth store

client/blocks/jitm/index.jsx, client/blocks/jitm/templates/notice.jsx
* Update notice template to render UpsellNudge instead of Notice.
* Go to `/stats/day` of your site.
* In ~~dev mode~~ local Calypso, run the following command to add a JITM for the section.
```js
_jitm.insert(
'calypso:stats-day:admin_notices', [ {
"message": "Howdy!",
"description": "",
"classes": "",
"icon": "info-outline",
"CTA":{
"message":"Click here!",
"link": "https://wordpress.com"
},
"tracks": {
"display": {
"name": "calypso_upgrade_nudge_impression",
"props": {}
},
"click": {
"name": "calypso_upgrade_nudge_impression",
"props": {},
},
"display": {
"name": "calypso_upgrade_nudge_impression",
"props": {},
}
},
"template":"notice",
"id":"wpcom_calypso_testing",
"feature_class":"dotcom-welcome",
"isDismissible": true
} ]
);
```
* Make sure a nudge appears on the top of the page.
=> JITM: Update notice template to render UpsellNudge

packages/media-library/package.json, packages/media-library/tsconfig.json
Move generated type output to dist/types, following convention in other packages.
Add TypeScript build caching.
=> Media library: Output types to dist/types

client/my-sites/plan-testimonials/index.jsx
* This PR updates the plan selection page's phrasing of "WordPress powers 35%" to "WordPress powers 36%". 
* Launch Calypso.live, create a new site, and on the plans chooser ensure the string has been updated.
=> Plans: update "WordPress powers ..." phrase to 36% from 35%

client/my-sites/earn/memberships/index.jsx, client/state/memberships/subscribers/actions.js, client/state/memberships/subscribers/reducer.js, client/state/memberships/subscriptions/actions.js
* This is going to add a `Cancel Subscription` option to the Subscriber actions menu.
* This will allow a client to cancel their subscribers subscriptions from Calypso, rather than having to do it from the Stripe dashboard
* Apply the [patch](https://code.a8c.com/D39519) to add the cancel subscription endpoint
* Sandbox the store on a test site
* Upgrade your test account to a Personal (if not already)
* Create a post with a recurring payment block
* Test the recurring payment block with test card details by purchasing a subscription
* Go to http://calypso.localhost:3000/earn/payments/{site}
* Click on the `...` menu next to the subscription (listed under Subscribers)
* Click on the `Cancel Subscription` option
* Confirm that the subscription has been cancelled and behaviour is as …
=> Add cancel subscription option to subscriber actions menu

client/my-sites/customer-home/main.jsx
Migrate static image regression to file-loader.
#38356 migrated this image to webpack file loader. #39642 restored the
image to prevent possible 404s, #39632 introduced a legacy static URL.
Use file-loader to allow removal in #39643.
cc: @Aurorum 
- Ensure the affected image is correctly displayed on the customer home page. See #39632
=> Images: Use webpack loader for fireworks

apps/full-site-editing/full-site-editing-plugin/starter-page-templates/page-template-modal/components/block-iframe-preview.js, apps/full-site-editing/full-site-editing-plugin/starter-page-templates/page-template-modal/components/block-preview.js, apps/full-site-editing/full-site-editing-plugin/starter-page-templates/page-template-modal/components/template-selector-preview.js, apps/full-site-editing/full-site-editing-plugin/starter-page-templates/page-template-modal/index.js, apps/full-site-editing/full-site-editing-plugin/starter-page-templates/page-template-modal/styles/starter-page-templates-editor.scss
This PR improves how the template title is rendered into the preview. Now, it's a core/heading h1 block. What this PR proposes is to use the `<PostTitle />` core editor component.
The only tricky part to deal is that this component gets the title from the post data. This is why we've created this PR in the core. In the meanwhile, however, we can go ahead in setting the template title using DOM manipulation. Once the core PR is ready 🤞, we can update and simplify the current approach.
1) Apply the patch
2) Check how the title is rendered in the large preview box
3) Compare with editor-canvas
4) Test in different themes in order to detect format variations such as alignment, font-size, etc
5) Compare with `master` branch
**before**
**after**
Fixes …
=> SPT: Set template title in large preview

client/landing/jetpack-cloud/components/date-picker/index.jsx, client/landing/jetpack-cloud/components/date-picker/style.scss, client/landing/jetpack-cloud/sections/backups/main.jsx, client/my-sites/activity/filterbar/date-range-selector.jsx
The shape of this component could be different depending on which design we're referring to. This PR puts the most of the needed logic in place for any of the designs, and we can go back and update the design of this component if needed.
* Adds the `DatePicker` component, which contains buttons for shuttling left/right, the currently selected date, and the `DateRangeSelector` component from the activity log.
* Modifies the DateRangeSelector component with optional `customLabel` prop, to allow us to use an icon in place of the regular text. Defaults to the text used on the activity log.
* Renders our new `DatePicker` components on the `Backups` page, and consume the date change event via Backups page.
1. Check the activity log in a normal Calypso context. The DateRangeSelector should show …
=> Jetpack Cloud: Add DatePicker component

client/lib/abtest/active-tests.js
* The results for the domain step design update test, introduced in https://github.com/Automattic/wp-calypso/pull/39276, have come in. The control group remains the winner, analysis is in p8Eqe3-15t-p2.
* The test is being reverted in https://github.com/Automattic/wp-calypso/pull/39832. As an interim measure, we will set the control to 100% and assign test to a future date so that users will no longer be assigned to the test.
* Go through the signup flow at /start.
* At the domain step, verify that you are not assigned to `domainStepDesignUpdates` test.
* Verify that you can complete signup.
=> Domain step test: Set variant allocation to zero

client/lib/products-values/index.js, client/lib/products-values/products-list.ts, client/lib/products-values/schema.json, client/me/purchases/manage-purchase/purchase-meta.jsx
* This resolves a bug where text showed yearly when it was a monthly purchase.
* Purchase a monthly backup solution.
* Go to Manage Purchases screen.
* Examine product cost text.
Screenshot:
Fixes 1142395350490785-as-1162348084744889.
=> Fixes purchase time period to work for products

client/lib/plans/plans-list.js
* Adjusting wording to remove reference to backups if product is purchased.
* Get a Jetpack site with a Free plan.
* View My Plan.
* Purchase a backup solution.
* View My Plan again.
Should say backups is an option if backups isn't present, otherwise strike references.
Screens:
Fixes #38035.
=> Removes reference to backups when purchased

client/my-sites/marketing/buttons/options.jsx
German needs a different translation here (_Beiträgen_):
But if this is changed here, it also changes it here which is wrong:
=> Marketing Button Options: Update contexts to allow for different translations

client/my-sites/checkout/checkout/types/transaction-endpoint.ts, packages/composite-checkout-wpcom/src/types/checkout-cart.ts, packages/composite-checkout/src/components/checkout-steps.js
React.Children functions include all children, including `null` and `false` which will render as empty. This causes issues with the special children handling of `CheckoutSteps` which counts children and uses the number of the child to render it with its index.
This PR filters out falsey values before having `CheckoutSteps` do the indexing and rendering work.
Before:
After:
Visit composite checkout with a 100% free purchase. One way to do this is to use a coupon code that provides a 100% discount (see also #39855 which allows removing coupons). Make sure that you can progress through checkout as you'd expect and you can get to the final step successfully. Notably make sure that the step numbers are correct (1, 2 rather than 1, 3).
If you've added the coupon during checkout, also try …
=> composite-checkout: Filter out falsey values in CheckoutSteps

packages/composite-checkout/src/components/button.js, packages/composite-checkout/src/components/checkout-steps.js, packages/composite-checkout/src/lib/payment-methods/existing-credit-card.js, packages/composite-checkout/src/lib/payment-methods/free-purchase.js, packages/composite-checkout/src/lib/payment-methods/full-credits.js, packages/composite-checkout/src/lib/payment-methods/paypal.js, packages/composite-checkout/src/lib/payment-methods/stripe-credit-card-fields.js, packages/composite-checkout/src/theme.js
In order to show the user that the form (or step) is currently validating or submitting, this adds an `isBusy` prop to the button component with an animation similar to Calypso and WordPress core busy buttons.
We should look into using Core's button component in a future PR.
**To Test:**
- `npm run composite-checkout-demo`
- visit http://localhost:3000/
- submit the country step and verify that while validating, the button reads "Please wait..." with a busy button animation
- submit the form and verify that while submitting, the form button reads "Processing..." with a busy button animation
=> Composite Checkout: add busy button

client/landing/jetpack-cloud/components/daily-backup-status/index.jsx, client/landing/jetpack-cloud/components/daily-backup-status/style.scss, client/landing/jetpack-cloud/sections/backups/main.jsx, client/landing/jetpack-cloud/sections/backups/utils.js, packages/media-library/types/index.d.ts
This PR adds the DailyBackupStatus component to Jetpack Cloud components, and utilizes it on the Backup page under the date picker.
PLEASE NOTE: The styles are intentionally left bare, and the restore/download buttons are intentionally left disconnected at this time. We'll fix all that in a subsequent PR.
* Load up this PR and make sure the component appears for each day that can be selected, and that there are no console errors related to this component
* Ensure that shuttling back and forth with the date picker changes the date for the backup status component, and that dates with missing backups explain what went wrong in the error message.
=> Jetpack Cloud: Daily backup status component

client/my-sites/activity/activity-log-banner/error-banner.jsx
The above error banner displays when there has been some error generating a downloadable archive of a backup. Previously, clicking the X would dismiss the banner, but the error would remain on the back-end, meaning the error would display on subsequent page loads, forever.
This PR hooks up the X to the existing action to clear the error on the back-end.
From a VaultPress sandbox, generate an archive for a test site that will fail by supplying an invalid timestamp:
`node bbin/prepare-download.js -s 256285 --types uploads --timestamp 6453`
On this branch, go to the Activity Log for the site and click the X on the download error banner. You should see an network request, and reloading the page will not bring back the error banner.
=> Make backup download error dismissal permanent

client/lib/route/path.ts, client/lib/route/test/index.js
Simplify JITM message path for `/stats` sections, so it won't contain subsection. This PR reduces number of JITM requests called in `/stats` section.
This doesn't need any test plan. Just make sure all test passed.
=> JITM: Simplify message path for stats section

client/my-sites/domains/domain-management/edit/card/renew-button/index.jsx, client/my-sites/domains/domain-management/edit/domain-types/mapped-domain-type.jsx
This is a follow up for https://github.com/Automattic/wp-calypso/pull/39701 and @klimeryk comments in there.
* Don't show renew/payment settings button if there is not subscriptionId
* Use UTC to format the expiry date
* Display "Expires: Never" if the expiry date is empty
* Don't duplicate some rendered code
So for VIP users mapped domains would look like this:
* Test that everything works as it was for normal users
* Test with a VIP user mapped domain
=> New domain mapping status refactoring

client/blocks/jitm/templates/sidebar-banner.jsx, client/my-sites/current-site/notice.jsx
* Wraps longer strings in `preventWidows` to prevent ugly line breakage.
* Consolidates a couple duplicated string instances into constants to be reused for UpsellNudge A/B test instances.
Question for devs: Is there any concern with applying `preventWidows` to the sidebar-banner JITM template when we don't know for sure what type of input we'll get from `message`? Wondering if it would be smarter to apply `widont` on the server side...
**Before**
**After**
* Check out the following UpsellNudge instances and check the inspector for the `&nbsp;` between the last two words of the message string to ensure `preventWidows` is working as intended:
=> Sidebar Notices: preventWidows on upsell nudges in the sidebar

packages/composite-checkout/src/components/checkout-steps.js
This PR updates the checkout button so that it doesn't sit under the help icon. This was tested in Chrome, Firefox, and Safari. I will test IE with Calypso.live after this PR is created.
**Before**
**After**
**After: desktop initial steps**
**After: desktop on last step**
* Add any product to your cart and make your way to checkout
* Add `flags=composite-checkout-wpcom` to the url to show the new checkout
* make your way to the last step and confirm the pay button works on desktop and mobile, and that on mobile, the help icon isn't overlapping the pay button.
Fixes #
=> Composite checkout: update button width

apps/full-site-editing/full-site-editing-plugin/starter-page-templates/page-template-modal/index.js, apps/full-site-editing/full-site-editing-plugin/starter-page-templates/page-template-modal/utils/tracking.js
* Adds a new prop `source` to the tracks event `a8c_full_site_editing_template_selector_view` with possible values:
- `add-page` - automatically shown when adding a brand new page (original behavior)
- `sidebar` - triggered from the post editing sidebar (feature added later)
I have tested this on local WP + FSE setup. Since tracking is intentionally disabled on WP installs outside WordPress.com Simple or Atomic, I recommend adding this snippet:
```
console.log( 'trackView', { segment_id, vertical_id, source } );
```
as the very first line inside `trackView` function in `apps/full-site-editing/full-site-editing-plugin/starter-page-templates/page-template-modal/utils/tracking.js`
Rebuild code. 
Use the `--sync` param of the build as described in PCYsg-ly5-p2 and test on your real wpcom …
=> SPT: Track source of opening the selector

client/my-sites/checkout/checkout-thank-you/custom-domain-purchase-detail.jsx
This PR emphasizes the ability to set a domain as primary under plan benefits after upgrading, as part of this test: p99Zz8-10j-p2
* Purchase a plan for a site
* Make sure the card is not shown before purchasing a domain
* Claim your free domain
* Click Plan on your sidebar
* Verify that the card is shown like in the screenshot above after you register the domain under plan features, and that the button sends you to the right place
* Make sure that the card is not shown if a custom domain is set as primary
* Verify that nothing gets broken
=> Plans: Show ability to set custom domain as primary under plan benefits

apps/full-site-editing/full-site-editing-plugin/full-site-editing-plugin.php, apps/full-site-editing/full-site-editing-plugin/site-editor/index.php
An experiment that attempts to enable and initialize core FSE editor for Dotcom sites via FSE plugin.
Alternative take at https://github.com/Automattic/wp-calypso/pull/39713
1. Sync the FSE plugin to your site.
2. Sandbox the API and your test site.
3. Apply D39899-code to your sandbox.
4. Add `core-site-editor-experiment` sticker to your test site.
3. Navigate to `wp-admin/admin.php?page=gutenberg-edit-site` and verify that the editor loads on your simple site.
=> Site Editor: initialize core FSE on Dotcom sites

client/landing/jetpack-cloud/components/stats-footer/index.tsx, client/landing/jetpack-cloud/components/stats-footer/style.scss, client/landing/jetpack-cloud/sections/scan/main.jsx
* Adds footer to Jetpack Scan page. This has static data only as API is not implemented.
See 1151678672052943-as-1164621024668349.
* View Scan page and verify that component matches comps.
Desktop:
Mobile:
=> Adds scan footer

client/my-sites/checkout/checkout/composite-checkout.js, packages/composite-checkout-wpcom/src/hooks/use-shopping-cart.ts
Just as `CompositeCheckout` can have a `product` provided as an initial product to add to the cart on first load, this adds the `couponCode` prop which adds a coupon to the initial cart.
This enables the behavior (which already exists in the old checkout) that a coupon code can be specified using the URL query string `?coupon=CODEHERE`
- First load composite checkout with just a plan and be sure the cart loads as expected.
- Next load composite checkout with the URL `/checkout/example.wordpress.com/planslughere` and be sure the cart loads with that plan added (use a different plan than the one you added in the first step).
- Finally load composite checkout again with a `coupon=COUPONCODEHERE` in the URL and be sure the cart loads with that coupon applied.
Some valid plan slugs are …
=> composite-checkout: Send coupon from URL to initial cart

client/blocks/upsell-nudge/style.scss, client/components/banner/style.scss
* @rickybanister noticed the last change to Banner/UpsellNudge messed up the alignment of the call to action on compact nudges when displayed with a dismiss icon. This PR fixes that bug.
**Before**
**After**
* Navigate to a site that has the "Add another domain" nudge, which is found on sites that already have a custom domain.
* Alternatively, you can open `/client/my-site/current-sites/notice.jsx` locally and make one of the existing `UpsellNudge`s dismissable by adding `showDismiss` and `dismissPreferenceName="testing"` props to it.
* You should see an improvement in the placement of the CTA :)
=> Banner: Fix position of CTA when used with a dismiss icon in a compact style

client/my-sites/customer-home/main.jsx
* Changes the document head/title to "My Home" from "Customer Home" to match the labels in the heading and the sidebar.
* We shouldn't need to worry about string freeze here since we're already using "My Home" elsewhere in the app.
**Before**
**After**
* Switch to this PR and navigate to a site with Customer Home active
* Note the document title in your browser tab/window; it should read "My Home" rather than "Customer Home"
=> My Home: Update  doc title to "My Home" for consistency

client/gutenberg/editor/calypsoify-iframe.tsx, client/gutenberg/editor/controller.js
Replaces the document title with specific titles when using the block editor rather than keeping the title of the previous page (which was causing some confusing labels such as "Customer Home" when opening the block editor from "My Home", as originally reported by @amamujee in p1583412425219600-slack-manage).
Before | After
--- | ---
It reuses the existing `EditorDocumentHead` component, so titles handle new/existing post and different post types:
Load the block editor from different sections (Site > Posts, Site > Pages, My Home, Tools > Activity) and make sure it uses a document title that's aligned with the post status (new/existing) and type (post, page, portfolio, ...).
=> Block editor: Add document titles

client/landing/jetpack-cloud/components/backup-delta/index.jsx, client/landing/jetpack-cloud/components/backup-delta/style.scss, client/landing/jetpack-cloud/sections/backups/main.jsx, client/landing/jetpack-cloud/sections/backups/utils.js
This PR adds details about the contents of a daily backup, below the Daily Backup Status component, per the figma designs. It pulls a list of uploaded media, created/deleted posts, and backup meta, and adds them to the section.
Make sure no console errors arise while shuttling days in a variety of states (has backups, no backups, backup errors, different days with different events).
View the backups section for a date that has changes in the form of created posts, deleted posts, and/or uploaded media. You should see those actions represented on that day's backup page. It should look similar to the following screenshot, depending on what the actions were:
As is customary this week, this PR is lacking most styles, pending further foundation work. Please review for function only.
=> Jetpack Cloud: Daily backup deltas component

client/my-sites/domains/domain-management/edit/domain-types/mapped-domain-type.jsx, client/my-sites/domains/domain-management/edit/domain-types/registered-domain-type.jsx, client/my-sites/domains/domain-management/edit/style.scss
* Update "You domain mapping has not been set up. You need to update your name servers at the company where you purchased the domain to:"
* Update: "Learn all about mapping an existing domain in our support docs."
* setup -> set up
* For each status that has an action required, can we highlight what state the domain is in. ie: "**Your domain has expired** and is no longer active"
* I updated the font-size for the secondary message "Please note that it can take up to 72 hours..." message
* Verify that the texts are updated for domain mappings and expired domains
* Verify that the mapping not pointing to us secondary message has smaller font-size
=> Domain status copy updates after internal testing
