Automattic/wp-calypso

- packages/composite-checkout/src/lib/payment-methods/stripe-credit-card-fields.js
This adds a missing `cc-name` attribute to the Stripe cardholder name field, but due to the way Stripe fields are embedded within iframes and browsers parse those fields, autofill will still only work for the CC number and expiration date. 
Adding the attribute in case this is fixed in the future.
Discussion: https://github.com/stripe/react-stripe-elements/issues/199#issuecomment-513280766
Broken example in Stripe Elements docs: https://stripe.dev/elements-examples/
> Composite Checkout: add autofill attribute to Stripe cardholder name

- client/my-sites/checkout/checkout/composite-checkout.js
- packages/composite-checkout-wpcom/src/components/wp-order-review-line-items.js
This PR adds a tracks event to measure when people remove products from our cart. I have an event for people that click the button and then another one for when the product is removed.
* Get calypso running locally or visit the calypso.live link
* Open the console and enter this command: "localStorage.setItem( 'debug', 'calypso:analytics*' );"
* See that you have events tracking in the console.
* Add a product to the cart
* Visit the checkout and append the following string to the end of your url: "?flags=composite-checkout-wpcom"
* Make your way to the review step and see if the events fire when you press the trash icon to remove the product and after you delete the product.
> Composite checkout: Add delete product event

- client/signup/config/steps-pure.js
- client/signup/steps/domains/index.jsx
* In the `with-theme` flow i.e signup flow at /start/with-theme, the selected theme's annotation should be applied to the headstarted site instead of the default annotation.
* We send the selected theme as a query param to the domain step, e.g. : `https://wordpress.com/start/with-theme/domains-theme-preselected?ref=calypshowcase&theme=twentytwenty` 
If the theme is present as a query prop, then we should force the theme annotation during headstart.
**Scenario 1**
* Check the normal signup flow - begin signup at /start and verify that you are able to complete signup.
* Verify that your site gets the Hever theme and a default starter content that matches https://qq1455758.wordpress.com/.
**Scenario 2**
Check the `with-theme` flow:
* While logged out of wpcom, go to …
> Force theme annotation when theme is sent as a query prop

- apps/full-site-editing/full-site-editing-plugin/starter-page-templates/page-template-modal/index.js
- apps/full-site-editing/full-site-editing-plugin/starter-page-templates/page-template-modal/utils/contains-missing-block.js
Short term solution for https://github.com/Automattic/wp-calypso/issues/39293 whilst we work on [improved longer term solutions](https://github.com/Automattic/wp-calypso/issues/39293#issuecomment-595147085).
[Recent Issues](https://github.com/Automattic/wp-calypso/issues/39293) have shown that users are seeing missing block messages in Templates when these Templates are using blocks that are not registered.
The missing blocks are likely due to certain blocks being used which are not directly a part of the FSE plugin (eg: [`layout-grid`](https://github.com/Automattic/wp-calypso/issues/39293)).
This PR proposes a solution whereby we dynamically remove any Templates from SPT which contain unsupported Blocks. 
You will need to be able to build and then sync the FSE Plugin over to a WP …
> FSE: filter out templates that have missing Blocks

- client/landing/jetpack-cloud/sections/scan/main.jsx
This adds the header and first paragraph content to the Scan Threats page.
Overall design:
Part added by this PR:
Note that the design shows the number of threats being spelled out, i.e. "two" instead of "2". Due to the technical difficulties of doing that in an I18N environment the number value is displayed instead.
1. Checkout the branch and start Calypso with `CALYPSO_ENV=jetpack-cloud-development npm start`.
2. Visit `http://calypso.localhost:3000/scan/$site_slug?scan-state=threats`.
3. Verify that the design of the header and paragraph content matches the Figma file.
> Jetpack Cloud: Add header and paragraph content for the Scan Threats page

- client/my-sites/domains/domain-management/edit/domain-types/registered-domain-type.jsx
* Add the DomainWarnings component since we're not handling some of the cases and specificaly - `pendingGSuiteTosAcceptanceDomains`, `pendingTransfer`, `newTransfersWrongNS` and `pendingConsent`
The notifications look like those:
* I have no idea how to test the above cases but I've short-circuited the component to show other warnings and it worked so I assume it'll work with the above too
> Add missing warnings component for the new domain status screen

- client/my-sites/domains/domain-management/edit/domain-types/registered-domain-type.jsx
- client/my-sites/domains/domain-management/edit/style.scss
* update the expiring/expired messages for non-owners
* don't show the renew and payment settings buttons for non-owners
* You'll need to set up a second account as administrator for a site with multiple domains in different statuses
Active domain viewed by another user:
Expiring soon domain viewed by another user:
> Update the new domain status messages for non-owners

- client/my-sites/checkout/checkout/style.scss
Not sure how long this has been the case, but the checkout form for most of our non-standard payment methods looks bad (notice the lack of padding):
This fixes it for all redirect type methods + wechat. Examples:
To get access to the payment methods, use the matching currency and IP address:
* Wechat/Alipay: USD, CN
* Bancontact: EUR, BE
* iDEAL: EUR, NL
* Giropay: EUR, DE
You can override the IP detection in the backend, look for `get_allowed_payment_methods()` in the shopping-cart.
> Old checkout: fix layout in non-standard payment methods

- client/me/purchases/concierge-banner/index.jsx
- client/me/purchases/purchases-list/index.jsx
* Fixes the following warning message shown in browser console on the /me/purchases page in Calypso:
```
Failed prop type: Invalid prop `bannerType` of value `placeholder` supplied to `ConciergeBanner`, expected one of ["has-upcoming-appointment","has-available-included-session","has-available-purchased-session","suggest-purchase-concierge"].
```
* Login to an account and open /me/purchases page.
* Check in your browser console that you don't see any Warning messages.
> Concierge banner: Fix prop warning shown in console

- client/lib/media/actions.js
The overlap of the `MediaActions` type name was causing `tsc` to error with the following cryptic message:
```
…/wp-calypso/node_modules/typescript/lib/tsc.js:78602
throw e;
^
Error: Debug Failure. Unexpected node.
Node 75 was unexpected.
at getDeclarationSpaces
…
```
Fix the error (and the `typecheck` job/script) by renaming the _type_ to `IMediaActions`.
Introduced in #39057 / #39048
* `typecheck` job works on CI (has type errors as before, but finishes and reports)
* `npm run typecheck` has the same behavior as the job - type errors but completes and reports
> Types: Fix bad type

- client/landing/gutenboarding/components/header/index.tsx
- client/landing/gutenboarding/components/header/style.scss
* Follow-ups to #39950
* Visit [`/gutenboarding`](https://calypso.live/gutenboarding?branch=update/gutenboarding-icon-color)
* Verify the WordPress (W) logo in the header looks correct.
> Gutenboarding: Use color variables, remove unused styles

- client/my-sites/current-site/index.jsx
- client/my-sites/current-site/notice.jsx
* Site notices and other urgent requests should come before any type of upsell. This moves the domain warnings and site redirect notice above JITMs/other sidebar upsells.
* Originally brought up by @amamujee in Slack: p1583516414300400-slack-dotcom-manage
**Before**
**After**
* Test on a site that has multiple notices/warnings/upsells displaying in the sidebar at once
* Any site configuration notices should appear above any upsells
> Sidebar: Move site notices above promotions/upsells

- config/production.json
- config/wpcalypso.json
* Enable the new domain status design feature flag on production.
We've tested this on horizon, made some small updates and we're now launching the new domain status designs for everyone.
All details are in p99Zz8-UK-p2
* Check that visiting a registered domain or mapped domain shows the new design on production
> Enable the new domain status design feature flag on production

- client/components/domains/contact-details-form-fields/README.md
- client/components/domains/contact-details-form-fields/custom-form-fieldsets/constants.js
- client/components/domains/contact-details-form-fields/custom-form-fieldsets/eu-address-fieldset.jsx
- client/components/domains/contact-details-form-fields/custom-form-fieldsets/region-address-fieldsets.jsx
- client/components/domains/contact-details-form-fields/custom-form-fieldsets/uk-address-fieldset.jsx
- client/components/domains/contact-details-form-fields/custom-form-fieldsets/us-address-fieldset.jsx
- client/components/domains/contact-details-form-fields/index.jsx
* In composite-checkout we are using `ContactDetailsFormFields` as a managed component. This patch adds an optional prop, `contactDetailsErrors`, which can be used to pass in per-field errors through props. These errors have lower precedence than those triggered by the existing validation logic.
* On its own this PR should have no visible effects on the contact details form. Verify that this is the case by interacting with the form in checkout. **Since this touches a shared component you'll need to verify this behavior in both composite checkout and old checkout.**
> ContactDetailsFormFields: add optional error message prop

- config/stage.json
* Enable the new domain status feature flag on staging too ( forgot to do that in https://github.com/Automattic/wp-calypso/pull/39958 )
We've tested this on horizon, made some small updates and we're now launching the new domain status designs for everyone.
All details are in p99Zz8-UK-p2
* Verify that the new domain status screens are visible on staging too
> Enable the new domain status feature flag on staging too

- client/my-sites/plans/main.jsx
Reverts Automattic/wp-calypso#39714
In #39714, we ended up deferring the page `calypso_plans_view` event until we had the `purchase` object so that we could add props to the `calypso_plans_view` event. But, that had the effect of significantly dropping the numbers for `calypso_plans_view`. 
At this point, we've already been able to get enough information from the change that it makes sense to just revert this PR so that the stats rebound back to where they were previously.
-Go to http://calypso.localhost:3000/plans/$site
- In the console, run `localStorage.setItem( 'debug', 'calypso:analytics:TrackComponentView' );`
- Refresh the page
- Ensure that the `calypso_plans_view` tracks event fires
> Plans: Revert page view defer after it dropped stats significantly

- client/blocks/inline-help/contextual-help.js
- client/blocks/inline-help/popover.jsx
From user testing Checkout, we've seen that customers want more information about our plans, refund policy, and subscriptions. This adds links to relevant support docs to the inline-help bubble.
There's room for 1 or 2 more links if we want them. Maybe G-suite or domains?
**To Test:**
- visit any route with `/checkout/`
- click the inline help button
- check the link and clickthrough explanation copy
- clicking "learn more" should open an inline help modal with the correct documentation
> Checkout: add contextual help links

- client/my-sites/customer-home/style.scss
* Always show Quick Links in two columns on screens > 480px, rather than going back and forth between single and two column layouts as the screen narrows. There will be a lot of variation depending on translations, of course.
Video demo of how the quick links scale with this PR on resize: https://cloudup.com/coEXQS8T5rJ
**Before**
**After**
* Navigate to a site with Customer Home that shows quick links (or complete the site's checklist)
* Check the display of the quick links at various screen sizes; look for visual bugs.
Fixes #39918
> My Home: Show Quick Links in two columns for all screens > 480px

- client/blocks/disconnect-jetpack/style.scss
When disconnecting Jetpack, I noticed the colour variable used is `--color-neutral-40`. This doesn't pass colour contrast requirements, so a while ago, a whole bunch of these were updated to `--color-text-subtle`. I guess this one was missed.
Visit `/settings/disconnect-site/confirm/site` on a Jetpack site and compare the title.
**Before:**
**After:**
cc @tyxla
> Disconnect Jetpack Highlight: Fix Colour Contrast

- client/my-sites/themes/themes-selection.jsx
Temporary Fix for https://github.com/Automattic/wp-calypso/issues/39898
Theme search counts don't appear accurate so as a first step let's stop displaying theme counts until we get to the root cause.
**Logged in** WordPress.com/themes
| Before  | After |
| <img width="1331" alt="Screen Shot 2020-03-09 at 3 48 45 PM" src="https://user-images.githubusercontent.com/1270189/76264312-a4b3a900-621e-11ea-8c5e-947495e41714.png"> | <img width="1331" alt="Screen Shot 2020-03-09 at 3 49 19 PM" src="https://user-images.githubusercontent.com/1270189/76264327-b1d09800-621e-11ea-8d9d-9de35d24e3ac.png"> |
**Logged out** WordPress.com/themes
| Before  | After |
| <img width="1449" alt="Screen Shot 2020-03-09 at 3 46 30 PM" …
> Themes: do not display search counts, until counts are correct

- client/my-sites/media-library/media-image.tsx
- client/my-sites/media-library/proxied-image.tsx
- client/post-editor/media-modal/detail/detail-preview-image.jsx
This PR is related to [private atomic sites project](https://wp.me/paObgF-Ui). It add support for remote private images to Media library preview modal.
* https://github.com/Automattic/wp-calypso/pull/39616
* Visit `/media` for a Private Atomic site, select an image, click "edit", confirm the preview modal is displayed correctly.
* Visit `/media` for a regular non-atomic site, select an image, click "edit", confirm the preview modal is displayed correctly. Play with editing image and restoring the original version, confirm the UX is the same as currently in production.
> [Private media files] Support media library preview modal

- client/my-sites/post-type-list/post-thumbnail.jsx
This PR is related to [private atomic sites project](https://wp.me/paObgF-Ui). It add support for private remote post thumbnails.
**Before**
**After**
* Test locally as calypso.live won't work for this patch
* Go to one of your private atomic sites, make it public, upload a media image, make it private again
* Create a new post and use the image you just uploaded as featured image, save the post
* Go to posts list, confirm the thumbnail shows and it's src is `blob: <identifier>` instead of an actual URL
* Checkout master branch, refresh, confirm the thumbnail src is an actual URL
> [Private media files] Use <MediaImage /> component to display post thumbnails

- packages/data-stores/src/auth/actions.ts
- packages/data-stores/src/auth/controls.ts
- packages/data-stores/src/auth/reducer.ts
- packages/data-stores/src/auth/test/flows.ts
- packages/data-stores/src/auth/types.ts
* Handle cases where the user has a passwordless account
* Doesn't handle errors yet, that's being added in #39819
* Go to `/gutenboarding` and open network tab and console
* Use the following to test the auth store. State transitions and errors will be printed to the console
* `wp.auth.submitUsernameOrEmail('')`
* `wp.auth.submitPassword('')`
* `wp.reset()`
* Test using a passwordless account (you can make one at `/gutenboarding/signup`)
* Check inbox for the login email
> Gutenboarding: auth store sends login email when use logs in with passwordless account

- client/assets/stylesheets/_calypso-color-scheme-jetpack-cloud.scss
- client/landing/jetpack-cloud/components/log-item/index.tsx
- client/landing/jetpack-cloud/components/scan-history-item/index.jsx
- client/landing/jetpack-cloud/components/scan-history-item/style.scss
- client/landing/jetpack-cloud/routes.js
- client/landing/jetpack-cloud/sections/scan/history/index.jsx
- client/landing/jetpack-cloud/sections/scan/history/style.scss
- The goal of this is to create the iteration of the UI of the History section. At this point, we don't know if we will have an APIs ready to work with.
See 1151678672052943-as-1164658985934865.
- View Scan page and verify that component matches comps.
**Screenshots**
**Desktop**
**Mobile**
> Create the History section of JP Scan

- client/my-sites/activity/activity-log-item/index.jsx
* Adds contextual popover menu item to add site credentials in backup events on the site activity.
* Adds new `calypso_activitylog_event_add_credentials` tracks event for this new item.
We’re currently disabling the “Restore to this point” option on the site activity without explaining why, and I’d assume people would not co-relate the banner at the top telling them to add server credentials and the fact that restores are not available.
* Fire up this PR locally or using jurassic.ninja.
* Connect Jetpack.
* Go to your site activity in Calypso; e.g.: `http://calypso.localhost:3000/activity-log/SITE_URL`.
* Ensure you see the new option and that it sends you to the correct place to set up site credentials.
* Validate that the option isn't visible once you've added working credentials.
> Site Activity: adds contextual popover menu item to add site credentials

- apps/full-site-editing/full-site-editing-plugin/full-site-editing-plugin.php
Running the Dotcom custom welcome guide caused the editor to crash on sites that don't have Gutenberg plugin enabled. Let's keep it off by default and only enable it in environments where we know that the required Gutenberg plugin version is running - these activation filters will be added in separate repos and PRs afterwards.
paYE8P-lx-p2
1. Run this PR in your local wp-env environment.
2. Make sure that the editor nux code is no longer being required by default.
3. Deactivate Gutenberg plugin on your test site.
4. Load the editor and verify that it's no longer crashing.
> FSE: add filter for enabling Dotcom editor nux

- client/assets/stylesheets/jetpack-cloud.scss
- client/landing/jetpack-cloud/components/stats-footer/style.scss
- client/landing/jetpack-cloud/sections/scan/main.jsx
- client/landing/jetpack-cloud/sections/scan/style.scss
* This adjusts the styles and markup of Jetpack Cloud to ensure the footer is stuck to the bottom of the page.
* Go to scan section.
* Verify footer position, changing screen width to test various devices.
* Add content to ensure footer is pushed down appropriately.
Screen:
Fixes 1151678672052943-as-1165205423871162.
> Fixes footer to bottom of window

- apps/full-site-editing/full-site-editing-plugin/starter-page-templates/page-template-modal/styles/starter-page-templates-editor.scss
Safari has a severe overlapping layout issue in iframe previews: https://github.com/Automattic/wp-calypso/issues/39874
This PR adds a small CSS override to fix layout previews in Safari.
- Open Safari
- Set-up your FSE dev environment
- Got go Page -> Add New
- Select the effected layouts, such as Menu, Dalton Homepage, 2020 Homepage, etc.
- Test these layouts in Chrome, Firefox to make sure there isn't a regression
> SPT: Fix Safari Overlapping Layout Issue

- packages/composite-checkout/package.json
This makes it match the version we are using in Calypso. There is no
need for the upgraded version here.
- Verify that the credit card fields load correctly.
> Downgrade react-stripe-elements in composite-checkout

- packages/data-stores/src/auth/actions.ts
- packages/data-stores/src/auth/controls.ts
- packages/data-stores/src/auth/test/actions.ts
Logging in at `/log-in` logs into a number of services (depending on your account) e.g. `jetpack.com`, `gravatar.com`, etc.
This PR ensures that logging in with the auth store also logs into these services.
Code was copied from `client/state/login.js`, particularly `makeRemoteLoginRequest()`
* Open network tab and console
* `wp.auth.submitUsernameOrPassword('validuser')`
* `wp.auth.submitPassword('correctpassword')`
* Look in network tab for request to `https://jetpack.com/remote-login.php` and see it responds with lots of precious precious cookies 🍪 
You should notice that the `remote-login.php` request is a iframe/subdocument request.
> Auth store logs into remote services

- client/landing/gutenboarding/devtools.ts
- packages/data-stores/src/auth/README.md
- packages/data-stores/src/auth/controls.ts
- packages/data-stores/src/auth/index.ts
- packages/data-stores/src/auth/test/controls.ts
- packages/data-stores/src/auth/test/flows.ts
* Add `loadCookiesAfterLogin` config flag to auth store
* Reloads proxy iframe after successful login if `loadCookiesAfterLogin`
See changes to `README.md` for more details.
For gutenboarding `loadCookiesAfterLogin` should be `true`. If on `/log-in` then it should be `false`, because the entire page is about to reload anyway.
Making the boolean part of the config doesn't feel very natrual. I think it'd be nicer if it were like: `submitPassword('p@ssw0rd', { loadCookies: true })`. But there's lots of ways the user could be logged in. It might not even be in response to an action being sent.
This config flag doesn't work very well if sometimes we should get the iframe to reload and sometimes we don't. I guess we'll cross that bridge when we get to it.
Alternative idea: don't do this in the …
> Gutenboarding: auth store can reload proxy after login

- client/landing/gutenboarding/components/confirm-purchase-modal/index.tsx
- client/landing/gutenboarding/components/confirm-purchase-modal/style.scss
- client/landing/gutenboarding/components/domain-picker-button/index.tsx
- client/landing/gutenboarding/components/domain-picker/index.tsx
- client/landing/gutenboarding/components/domain-picker/style.scss
- client/landing/gutenboarding/components/header/index.tsx
This PR re-introduce paid domains in the gutenboarding domain picker, linking them to a sub-flow that actually ask the user to create an account, creates the site, and send them through the calypso checkout so they can pay for a personal plan before they are redirected back to the design section of gutenboarding. 
How to test:
--------------
1. Go to http://calypso.localhost:3000/gutenboarding (or https://calypso.live/gutenboarding?branch=update/gutenboarding-domains-flow )
1. Select a vertical and enter a site title: you should get a domain showing up in the top bar
1. Click it and choose one of the paid domains in the list (or look for a new term and choose one) 
1. You should see a modal dialog telling you what happens next. Make sure you can close it by clicking 'do it later' or …
> Gutenboarding: Update the domains picker to make domain upgrades available

- client/my-sites/checkout/checkout/composite-checkout-thank-you.ts
- client/my-sites/checkout/checkout/index.jsx
* Stopping the Premium bump offer for qualified Personal plan customers and showing the QuickStart one instead. More info here pNEWy-cIg.
* Signup for an account and purchase a Personal plan (without domain).
* After completing payment, verify that you are always shown the Quick Start/Concierge upsell offer.
Fixes 295-gh-martech
> Stopping Premium bump offer for Personal plan customers

- client/jetpack-connect/controller.js
- client/jetpack-connect/index.js
* Add jetpack backup so that it can be purchased thought the remote install. 
* Visit calypso.localhost:3000/jetpack/connect/backup
Enter a domain that doesn't have jetpack yet. 
Notice that the flow installs/activates jetpack and sends you to the purchase flow for backup yearly
Also test
* Visit calypso.localhost:3000/jetpack/connect/realtimebackup
* Visit calypso.localhost:3000/jetpack/connect/realtimebackup/monthly
* Visit calypso.localhost:3000/jetpack/connect/backup/monthly
> Add jetpack backup to be remote purchased

- client/blocks/site-icon/index.jsx
- client/my-sites/media-library/media-image.tsx
- client/my-sites/media-library/proxied-image.tsx
This PR is related to [private atomic sites project](https://wp.me/paObgF-Ui). It add support for remote private images to <SiteIcon /> component.
* Test on calypso.localhost
* Create a new store site
* Go to Calypso > Store
* Make the site public
* Upload a new site icon
* Make the site private
* Refresh calypso
* Inspect the site icon in the sidebar, confirm the `src` is set to `blob: <identifier>`
* Confirm the images are being displayed properly
> [Private media files] Support SiteIcon

- client/extensions/woocommerce/app/product-categories/form.js
- client/extensions/woocommerce/app/products/product-form-images.js
- client/extensions/woocommerce/app/products/product-form-variations-row.js
- client/extensions/woocommerce/components/image-thumb/index.js
This PR is related to [private atomic sites project](https://wp.me/paObgF-Ui). It add support for remote private images to Woocommerce extension.
* Test on calypso.localhost
* Create a new store site
* Go to Calypso > Store
* Make the site public
* Create a new product, upload an image, save it
* Make the site private in another tab
* Go to products list, inspect thumbnails, confirm the `src` is set to `blob: <identifier>`
* Edit the product, inspect images, confirm the `src` is set to `blob: <identifier>`
* Confirm the images are being displayed properly
> [Private media files] Support woocommerce extension

- client/my-sites/checkout/checkout/composite-checkout.js
- packages/composite-checkout-wpcom/src/components/wp-contact-form.js
- packages/composite-checkout-wpcom/src/hooks/wpcom-store.ts
- packages/composite-checkout-wpcom/src/types/wpcom-store-state.ts
* Pulls the existing domain contact details cache into composite checkout to prepopulate the contact fields.
Proceed to checkout with a domain in your cart and with a full contact details cache (Note- I assume this is filled if your user account already has at least one domain, but am not sure.)
Check that at the "billing details" step the fields are prepopulated with sensible data, and that you can proceed to the review order step.
> composite-checkout: Prepopulate contact details with cached data

- client/my-sites/migrate/section-migrate.jsx
This PR updates the wording on the migration progress screen.
* Perform a migration
* Verify that text on progress screen is updated
> Update text on migration progress screen

- apps/full-site-editing/full-site-editing-plugin/starter-page-templates/page-template-modal/components/block-iframe-preview.js
* Adds `block-editor__container` class to iframe body. Themes seem to rely on it for styling.
* In a local install, have the latest Variable and Maywood themes installed with Maywood activated.
* Checkout the PR and build FSE with `$ npx lerna run dev --scope='@automattic/full-site-editing' --stream --no-prefix`
* Publish a new post with a featured image wider than 700px or add a picture like that to an existing post.
* Create a new page and select the blog template in the template selector.
* Make sure the featured image doesn't overflow the content area.
Fixes #39278.
> SPT: Accommodate Varia styles

- apps/wpcom-block-editor/src/wpcom/features/tracking.js
This allows us to see how often users see errors on their site.
This is part of the work to figure out what is causing p9F6qB-4PJ-p2. (i.e. track it to see if we can detect any common threads.)
See deployment diff at D40149-code.
* Add handler for `createErrorNotice` in the core/notices store.
0. First, apply D40149-code to your sandbox. Also sandbox a test site and `widgets.wp.com`.
1. In the JS console for a post, change the context to the iFrame (`post.php`) instead of the Calypso page. (screenshot shows how to do this for Firefox)
2. In the console, execute `localStorage = "wpcom-block-editor:tracking"`
3. Reload the page, and do step 1 again. You should see some messages in the console saying "wpcom-block-editor:tracking registering tracking handlers".
This means that the debugger is …
> Gutenberg: Add tracking for error notices

- client/my-sites/checkout/checkout/checkout-system-decider.js
* Post checkout upsells - Premium plan bump offer and the Quick Start offer - are not shown when user is in the composite checkout flow. This PR fixes the issue.
**With a Personal plan in cart**
**BEFORE**
**AFTER**
* Proxy through a US IP address and have your browser language set to `en`. Assign yourself to the `composite` variation of `showCompositeCheckout` AB test. 
* In the signup flow, add a Personal plan to cart, complete payment, and verify that you see the Premium plan bump offer.
* In the signup flow, add a Premium plan to cart, complete payment, and verify that you see the Quick Start offer.
* Purchase an eCommerce plan and verify that the store gets provisioned
> Fix: Post checkout upsell not shown + eCommerce site not setup in the new checkout flow

- client/my-sites/checkout/checkout/style.scss
A recent change to fix redirect-type payment methods (#39893) created layout issues with country-specific fields (India and Brazil) - they now overflow.
This CSS change makes sure that country fields in redirect type payment methods don't get the double padding which causes them to overflow.
**India Net banking**
**Brazil bank transfer:**
**Brazil CC (not broken but added for reference):**
**India Net banking**
**Brazil bank transfer:**
**Brazil CC:**
For Brazil CC fields: 
- Use a user with the BRL currency, and select Brazil in the CC country dropdown
For Brazil Bank transfer fields: 
- Use a user with the BRL currency, and a Brazillian IP address (or overwrite the GEO country check at the top of `Store_Shopping_Cart::get_allowed_payment_methods` in the backend)
For India Net banking …
> Old Checkout: fix layout of country specific fields in checkout form

- client/lib/abtest/active-tests.js
- client/signup/steps/plans/index.jsx
- config/development.json
- config/wpcalypso.json
* The new plan step AB test was enabled in #39600 with a feature flag restriction. Individual pieces of the UI were built in separate PRs https://github.com/Automattic/wp-calypso/pull/39630 and https://github.com/Automattic/wp-calypso/pull/39621.
* This PR removes the feature flag restriction and launches the PR with a 50/50 allocation.
**Desktop**
**Mobile screen size**
* Go through the signup flow at /start.
* When in the control group of the `planStepCopyUpdates` test, verify that you see the unchanged plan step UI version
* When in the variant group, verify that you see the updated UI that matches with p8Eqe3-144-p2.
* Verify that the plans page in Calypso /plans, and the plans step shown in launch flow of private sites both do not show the new UI.
> Plan step test: Launch the test

- client/landing/gutenboarding/components/header/index.tsx
When selecting a paid domain from the domain picker, add it to the cart before sending the user to checkout.
* [`/gutenboarding`](https://calypso.live/gutenboarding?branch=gutenboarding/domain-purchase)
* Enter a vertical and title.
* Click the domain dropdown and select a paid domain.
* Continue from the modal.
* Your site should be created, then you'll be sent to checkout with a plan and a domain in the cart ready for checkout.
> Gutenboarding: Add paid domain to cart

- client/lib/media/utils.js
- client/my-sites/media-library/media-file.tsx
- client/my-sites/media-library/media-image.tsx
- client/post-editor/media-modal/detail/detail-preview-audio.jsx
- client/post-editor/media-modal/detail/detail-preview-video.jsx
This PR is related to [private atomic sites project](https://wp.me/paObgF-Ui). It add support for remote private video and audio files
**Known limitations:**
Currently this uses XHR and downloads the entire file before presenting it. This is less than perfect, ideally we'd switch to `fetch` whenever `responseType="blob"` is requested, and use a blob based on `ReadableStream` as soon as it's available (see https://developer.mozilla.org/en-US/docs/Web/API/Streams_API/Using_readable_streams)
* Test on calypso.localhost
* Create a new private atomic site
* Go to wp admin > media and upload a video and audio file
* Go to media in Calypso, select both files, click edit, confirm you get proper preview
* Confirm simple sites don't …
> [Private media files] Support audio and video files

- client/components/social-buttons/apple.js
* Fix a crash on IE11 loading Jetpack connect login screen
* Connect a Jetpack site in  IE11
* Debugger prompt comes up when login form displays
* With this patch, there should be no debugger prompt
> Polyfill CustomEvent on IE 11 for Apple login

- client/me/purchases/product-link/index.jsx
Instead of linking to the general Compare Plans view from a plan purchase, link to the My Plan tab instead.
* Find a plan purchase under `/me/purchases`.
* Click the View Plan Features link.
* Verify you are sent to the My Plans tab (`/plans/my-plan/:site`, instead of `/plans/:site`).
Fixes #38076
> Plans: Link to My Plan from plan purchases.

- client/my-sites/sidebar/index.jsx
- client/state/selectors/get-site-editor-url.js
- client/state/selectors/is-site-using-core-site-editor.js
- client/state/sites/constants.js
Adds a 'Site Editor' button in place of the 'customizer' button when the 'core-site-editor-enabled' blog sticker is present on a site (dependent on D40145).  
This button redirects to the wp-admin site editor, and future plans (follow-up PRs) are to bring this into an iframe.
* Patch D40145
* Run this PR on calypso.
* Verify the 'Customize' button becomes a 'Site Editor' button when using a site with the `core-site-editor-enabled` sticker.
* Verify button leads to wp-admin site editor screen.
First step in addressing #39886
> Add Site Editor to calypso sidebar

- client/me/purchases/manage-purchase/style.scss
When clicking the View Plan Features link on `/me/purchases`, the incoming stylesheet can make the plan description title jump as it becomes `display: block` from its browser default of `inline`. By setting an explicit style for the title on the Manage Purchase page, we can avoid the visual glitch.
* Find a plan purchase under `/me/purchases`.
* Click the View Plan Features link, and verify the plan description content doesn't jump from the title becoming `display: block`.
* Click the browser Back button, and verify the description title is still inline.
Fixes #40100
> Purchases: Stop description text from jumping on page transition.

- client/landing/gutenboarding/onboarding-block/design-selector/index.tsx
- client/landing/gutenboarding/onboarding-block/edit.tsx
- client/landing/gutenboarding/onboarding-block/vertical-select/index.tsx
- client/landing/gutenboarding/path.ts
- client/landing/gutenboarding/tsconfig.json
Removes unused code after from page selector removal in https://github.com/Automattic/wp-calypso/pull/39972
- [`/gutenboarding`](https://calypso.live/gutenboarding?branch=remove/gutenboarding-page-selector-leftovers) flow should work as expected.
> Gutenboarding: Cleanup page selector removal

- client/landing/gutenboarding/onboarding-block/vertical-select/index.tsx
* Hide vertical suggestion dropdown when there is only 1 suggestion and it is identical to user input.
1. Go to acquire intent `/gutenboarding` page.
2. Enter "American Restaurant" on the vertical input.
3. It should now show a dropdown suggestion.
Fixes #40042
> Gutenboarding: Hide vertical suggestion dropdown when there is only 1 suggestion and it is identical to user input.

- client/my-sites/site-settings/podcasting-details/index.jsx
- client/my-sites/site-settings/podcasting-details/private-site.tsx
Updates copy on SEO settings page to reflect Coming Soon mode whenever it's set.
1. Go to calypso.localhost:3000 (don't test on calypso.live as the feature flag is not enabled there)
1. Go to podcasting settings on Private site, confirm the copy makes sense and says "Private"
1. Go to podcasting settings on Coming Soon site, confirm the copy makes sense and says "Coming Soon"
> [Coming Soon] Update copy in podcasting settings

- client/landing/gutenboarding/onboarding-block/design-selector/index.tsx
- client/landing/gutenboarding/onboarding-block/edit.tsx
- client/landing/gutenboarding/onboarding-block/style-preview/index.tsx
- client/landing/gutenboarding/path.ts
- config/development.json
Add `gutenboarding/style-preview` feature flag and enable it in development.
Add style-preview step with simple placeholder.
- No change in other environments ([calypso.live](https://calypso.live/gutenboarding?branch=gutenboarding/add-styles-step)).
- In development, after selecting a design you move to another placeholder step.
> Gutenboarding: Add style-preview step (feat-flag)

- apps/full-site-editing/full-site-editing-plugin/global-styles/class-global-styles.php
*  Adds `Raleway` font to the list
Extracted from https://github.com/Automattic/wp-calypso/pull/38896
Install the FSE plugin locally:
* `npm install`
* `npx lerna run build --scope='@automattic/full-site-editing'`
* Move the `<local-path-to-calypso>/apps/full-site-editing/full-site-editing-plugin/` under  `wp-content/plugins` in your local WordPress install.
Install a theme that uses Global Styles:
* Clone the [themes](https://github.com/automattic/themes) repo locally.
* `cd varia`
* `npm install`
* `npm run build`
* Move `<local-path-to-themes>/varia` under `wp-content/themes` in your local WordPress install.
Test:
* Activate the Full Site Editing plugin and the Varia theme
* Go to a post.
* Open the Global Styles sidebar and verify that fonts work.
> Global styles: add Raleway font

- apps/full-site-editing/full-site-editing-plugin/full-site-editing-plugin.php
- apps/full-site-editing/full-site-editing-plugin/readme.txt
Updates the FSE plugin to version 0.16, which includes two changes:
- Adds a new font to Global Styles https://github.com/Automattic/wp-calypso/pull/40087
- Fixes an overflow issue with features images in the blog SPT template https://github.com/Automattic/wp-calypso/pull/39944
- Have the Maywood theme active (use latest release).
- Have FSE active (this PR).
Global Styles change:
- Go to a post, open the Global Styles sidebar and check that the Raleway font is present.
- Select Raleway for base or heading and publish styles.
- Go to the front end and make sure the fonts are properly set.
SPT change:
- Go to a post, and add a featured image larger than 700px. Publish.
- Enable Jetpack and under "Settings > Discussion" …
> FSE: update version to 0.24

- client/state/data-layer/wpcom/activity-log/update-credentials/index.js
* Add tracks event when attempting to add server credentials.
* `calypso_rewind_creds_update_attempt`
* Add tracks event when successfully adding server credentials.
* `calypso_rewind_creds_update_success`
* Fire off this PR.
* Open Calypso and enter `localStorage.setItem( 'debug', 'calypso:analytics*' );` on your console.
* Select a Jetpack site and head to `Settings > Security > Backups and security scans`.
* Add correct server credentials and ensure both events are fired correctly.
> Rewind: add tracking events to server credentials updates

- client/my-sites/checkout/checkout/composite-checkout.js
- packages/composite-checkout-wpcom/src/hooks/use-shopping-cart.ts
- packages/composite-checkout-wpcom/src/types/backend/shopping-cart-endpoint.ts
This makes it so that composite checkout will empty the cart and redirect to the plans page if a plan that is bundled with a domain is removed from the cart. This is because when that happens the shopping cart backend will automatically add a premium plan to the cart, which is a terrible UX.
Fixes #38979
- Apply D40211-code and sandbox the store.
- Add a plan and a domain to your cart.
- Visit composite checkout.
- In the review step, click to remove _just_ the plan. 
- Verify that you are redirected to the plans page and that your cart is empty (you will not see the red "2" icon on the "cart" button in the upper right of the plans page).
- Add a plan and a domain to your cart again.
- Visit composite checkout.
- In the review step, click to remove _just_ the domain.
- Verify that that's …
> composite-checkout: Redirect to plans page if bundled plan is removed

- client/me/concierge/style.scss
* This improves the responsive design for the Concierge booking page. 
On a site that can book a Concierge session, visit `/me/concierge/site/book` and try looking at the page at different screen widths.
**Before:**
**After:**
Fixes #35505
> Concierge Booking Page: Improve Responsive Design

- apps/full-site-editing/full-site-editing-plugin/full-site-editing-plugin.php
- apps/full-site-editing/full-site-editing-plugin/wpcom-block-editor-nux/src/wpcom-nux.js
A potential solution for bringing this back into atomic.  Essentially we only register the nux plugin if the experimental function is available.  This is the most recent addition to the dependencies in this file so if it is available, everything should be.  Similarly, if this function name gets changed as it gets determined to be a full feature and not an experiment, we will have a back up check to prevent this from breaking on simple sites as well.
* Run this FSE build on Atomic development sites.
* Test loading the editor with and without gutenberg enabled.
Fixes #
> Fix dotcom Welcome Guide to be safe for atomic.

- client/state/sites/launch/actions.js
Temporary patch until signup regression is found. This PR skips the domain upsell step when trying to launch a site.
- Create a new site
- Follow Site Setup List in My Home
- Click on Launch Site. We should launch the site directly instead of going to a domain upsell.
> Site Launch: skip upsell until regression is found

- client/landing/gutenboarding/onboarding-block/design-selector/index.tsx
- client/landing/gutenboarding/onboarding-block/design-selector/style.scss
Fixes https://github.com/Automattic/wp-calypso/issues/40006.
* Add StartOver button on design selector page.
* Go to `/gutenboarding`, set vertical & site name and click continue.
* Now you've reached the design selector page, click **Start Over** button right to the header title.
* It should:
* Reset vertical & site title.
* Display the acquire intent page.
> Gutenboarding: Add "Start Over" button on design selector page.

- client/my-sites/migrate/step-source-select.jsx
* Fixes a small typo in the error message `This is site is`.
* Apply the PR or use Calypso.live.
* Go to `import/[ site ]`, select WordPress and enter the URL of a site that's already hosted on WordPress.com.
* You should see the corrected error message.
> Site migration: fix typo in error for WordPress.com hosted source sites

- client/my-sites/checkout/upsell-nudge/plan-upgrade-upsell/index.jsx
- client/my-sites/feature-upsell/plugins-upsell.jsx
- client/my-sites/themes/single-site-jetpack.jsx
Fix a few references to avoid using exact hard-coded numbers for premium themes. Using instead words that indicate a collection and group instead of precise numbers.
Full context the issue below.
Fixes #40152
> Premium themes: update references to remove exact count

- client/components/domains/register-domain-step/index.jsx
- client/my-sites/domains/domain-search/index.jsx
- client/state/sites/launch/actions.js
Reverts Automattic/wp-calypso#40129 
Context: p7DVsv-8aJ-p2#comment-27280
The regression was introduced in https://github.com/Automattic/wp-calypso/pull/39664. See p99Zz8-12M-p2 for more context.
The offending line was this: https://github.com/Automattic/wp-calypso/pull/39664/files#diff-37d2382dc9dbc34da496b1cc4c40d0f2L191
I did not realize that we were injecting a selectedSite in a signup step, since, by nature, signup is for signing up for a new site. But seems that it was repurposed for launching private sites as well. As a result the fix was quite simple: 344a11a
Follow the ones from https://github.com/Automattic/wp-calypso/pull/39664 to make sure there are no regressions there (so meta).
Create a new, free site, without domains. It should be in unlaunched state. Try launching it from …
> Revert "Site Launch: skip upsell until regression is found"

- client/my-sites/feature-upsell/themes-upsell.jsx
* Removes the hard-coded number referring to the premium theme count.
I'm not sured where it's used, but checking the phrasing should be enough. cc @lancewillett 
Fixes #40152
> Themes Upsell: Remove Exact Premium Theme Count

- client/components/social-buttons/apple.js
- packages/calypso-polyfills/browser-fallback.js
* Move CustomEvent polyfill for IE11 to Calypso Polyfills lib as requested by @sgomes and @simison 
* Use connect flow in IE 11
* Should no longer see an exception caused by lack of CustomEvent class
Fixes https://github.com/Automattic/wp-calypso/pull/40075#issuecomment-598371778
> Add fallback CustomEvent polyfill for IE11

- client/my-sites/migrate/section-migrate.jsx
* This PR adds a polling mechanism triggered on each migration status API update to request an update to the site object
* This will refresh the site as soon as it's upgraded to WordPress.com Business plan and update the visible site address in Calypso.
* Start with a WordPress.com Simple site
* Start a migration
* Look at the site addresses shown in the sidebar and on the migration screen and see if they will update when the site is upgraded to WordPress.com Business.
* Check the network logs and make sure there are no additional refresh updates after the site information is updated. 
* Make sure the site title in the sidebar is updated when the migration finishes.
> Site Migration: Automatically update site address when the site is upgraded to WordPress.com Business plan

- client/my-sites/checkout/checkout-thank-you/style.scss
Change font-weight from 300 to 400 for the following SCSS files as mentioned in #39596:
- Go to http://calypso.localhost:3000/plans/
- Select a site that is upgradable
- Click on `Upgrade` to upgrade to a higher plan
- Proceed with payment, e.g. using free credits
- Check `font-weight` of header and success message texts
<table>
<tr>
<td>Before:
<br><br>
</td>
<td>After:
<br><br>
</td>
</tr>
</table>
> Typography: Change font-weight of /checkout/thank-you

- client/me/account-close/closed.scss
- client/me/account-close/confirm-dialog.scss
- client/me/account-close/style.scss
Change font-weight from 300 to 400 for the following SCSS files as mentioned in #39596:
- Go to http://calypso.localhost:3000/me/account/close
- Check headline `Close account`
- Click on `Close acccount`
- Check headline `Confirm account closure`
- Confirm deletion and click on `Close your account`
- Check spinner text `Your account is being deleted`
<table>
<tr>
<td>Before:
<br><br>
</td>
<td>After:
<br><br>
</td>
</tr>
</table>
<table>
<tr>
<td>Before:
<br><br>
</td>
<td>After:
<br><br>
</td>
</tr>
</table>
<table>
<tr>
<td>Before:
<br><br>
</td>
<td>After:
<br><br>
</td>
</tr>
</table>
> Typography: Change font-weight of /me/account/close

- packages/composite-checkout-wpcom/src/hooks/use-coupon-field-state.ts
This allows coupons to be submitted with leading or trailing whitespace. Fixes #39991.
**To test:**
- visit the new Checkout
- add a coupon with whitespace
- verify that the trimmed coupon value is sent to the /shopping-cart/ endpoint and properly applied to the cart
> Composite Checkout: trim whitespace from coupon value before validating

- packages/composite-checkout-wpcom/src/components/wp-checkout-order-review.js
- packages/composite-checkout-wpcom/src/components/wp-checkout-order-summary.js
- packages/composite-checkout-wpcom/src/components/wp-order-review-line-items.js
- packages/composite-checkout/src/components/checkout-steps.js
This fixes some styling issues uncovered from adding domain support to Checkout.
**Included:**
- prevent fixed submit button from overlapping domain TOS
- allow for wrapping of long domains in order summary, pricing line item, and domain TOS
- small visual tweaks to TOS
Before | After
**To test:**
- add multiple domains of varying lengths (with and without hyphens) to your site
- visit checkout
- verify that the styling looks like the screenshots, there aren't any broken wrapping elements, etc.
> Composite Checkout: UI updates for domains

- client/my-sites/checkout/checkout/checkout-system-decider.js
- config/development.json
- config/horizon.json
In production, composite checkout is displayed if a user passes all the product guards (checks for products that composite checkout does not yet support) and is assigned as part of the abtest. We have a config flag, `composite-checkout-wpcom`, which skips all the product guards and the abtest if enabled, but while this makes it easy to test the behavior on products that would be excluded by the guards, it makes it hard to test new upcoming changes to those guards like the upcoming support for domains.
This PR adds a new flag, `composite-checkout-testing`, which replaces the other flag that's enabled on Horizon. The new flag can be used to conditionally enable certain features for testing to larger audiences. This PR also uses the flag to simulate the upcoming domains release.
In order to …
> composite-checkout: add new composite checkout flag for testing domains

- client/my-sites/sidebar/index.jsx
Fixes #40058
* When viewing an Atomic or Jetpack-connected site — change the sidebar menu label from "Activity" to "Activity & Backups".
* The link goes to the same page, yet auto-loads the filter for backups rather than all activity
1. Log in, navigate to My Sites, find an Atomic or Jetpack-connected site
2. View the sidebar, verify the label and link destination are changed from current production environment
Jetpack-connected Atomic site — updated label:
WordPress.com  Simple site — no label change:
Two small-screen views, Jetpack-connected site (to see how it flows):
> Sidebar: add “Activity & Backups” menu option for Atomic and Jetpack-connected sites

- client/jetpack-connect/remote-credentials.js
- client/jetpack-connect/style.scss
* Updates the copy and styles on the remote install self hosted credentials page.
Before:
After:
* Start Calypso `npm start`
* Visit http://calypso.localhost:3000/jetpack/connect/install
* Type in a wordpress site such as `https://cool-beaver.jurassic.ninja`
* Notice that there are no errors on that page and you can proceed to the nest step. 
* Type in a wrong username and password. The error message is what you expected. 
Fixes https://github.com/Automattic/wp-calypso/issues/40091
> Jetpack Remote Install: Update copy and style on remote credentials page

- client/my-sites/domains/components/domain-warnings/index.jsx
- client/my-sites/domains/components/domain-warnings/test/index.js
The changes proposed are meant to improve the domain mapping message that we display in Calypso at the moment. It is linked to a guide which doesn't help our users much and they have to contact us. Also improved it to make it clear that there is an action required on their part. This is to try and match the text that we send in the automated email too.
Steps to Test:
- Go to Manage -> Domains -> Add domain and map an existing domain.
**Before Change**: 
Message: 
Linked support guide: https://en.support.wordpress.com/domain-helper/?host=erricgunawan.com
**After change**:
Message:
Link to support guide: https://en.support.wordpress.com/domains/map-existing-domain/#change-your-domains-name-servers
*
Fixes  https://github.com/Automattic/wp-calypso/issues/37811
> Update: index.jsx to improve Domain Mapping message in Calypso dashboard to make it more informative.

- client/my-sites/checkout/checkout/checkout-system-decider.js
For our initial launch of supporting domains in composite checkout, we are going to exclude TLDs which require special contact forms. These include .fr, .ca, and *.uk. This PR adds a guard for those products in `CheckoutSystemDecider`.
- Add a domain using a gTLD without special contact fields (eg: .blog) to your cart.
- Add the `?flags=composite-checkout-testing` to your URL to simulate the domain launch.
- Verify that you see composite checkout.
- Add a domain using a ccTLD without special contact fields (eg: .tv) to your cart and return to checkout _with the same flag_.
- Verify that you still see composite checkout.
- Add a domain using a TLD that has special contact fields (eg: .co.uk) to your cart and return to checkout _with the same flag_.
- Verify that you see …
> Disable composite checkout for TLDs with special contact forms

- client/my-sites/customer-home/main.jsx
Fixes https://github.com/Automattic/wp-calypso/issues/40108 where attempting to edit the homepage would instead create a new page when the classic editor was selected.
When the classic editor is set as the default preference, we should see the following for page/post editing options:
| Classic  | Block-Editor |
| <img width="1019" alt="Screen Shot 2020-03-13 at 2 18 01 PM" src="https://user-images.githubusercontent.com/1270189/76660389-0da86300-6536-11ea-9f82-87d67bb01799.png"> | <img width="1023" alt="Screen Shot 2020-03-13 at 2 17 33 PM" src="https://user-images.githubusercontent.com/1270189/76660412-1ac55200-6536-11ea-9be8-e8fa87c0403a.png"> |
- With a user account created before December 16, 2019, click on "Switch to Classic Editor"
- Verify that …
> Quick Links: Make post options aware of editor preferences

- client/my-sites/checkout/checkout/checkout-system-decider.js
This PR modifies `CheckoutSystemDecider`, which determines which checkout to show (regular or composite checkout) based on various factors, so that it will allow domains and domain related products (domain mapping, domain transfers). Users will still have to pass the `abtest` config or enable the `composite-checkout-testing` flag (which remains enabled on Horizon).
Note that _adding_ domain products via URL (I think this only applies to domain mapping with a path like `/checkout/example.com/domain-mapping:example.com`) is _not_ enabled by this change; such paths will still redirect to regular checkout. That change will need to be done separately because we need to be absolutely sure that we handle all possible product adding paths and we are still verifying that logic.
- Add a domain …
> Allow domains and domain products to composite checkout abtest

- client/my-sites/checkout/checkout/checkout-system-decider.js
Reverts #40181
- Add a domain using a gTLD without special contact fields (eg: .blog) to your cart.
- Verify that you see regular checkout.
- Add a domain using a ccTLD without special contact fields (eg: .tv) to your cart and return to checkout.
- Verify that you still see regular checkout.
- Add a domain using a TLD that has special contact fields (eg: .co.uk) to your cart and return to checkout.
- Verify that you see regular checkout.
> Disable domains and domain products in composite checkout

- apps/wpcom-block-editor/README.md
It was difficult to understand wpcom-gutenberg's directory structure. Hopefully this clarifies things a bit.
> Clarify directory structure of wpcom-gutenberg

- client/my-sites/importer/jetpack-importer.jsx
- client/my-sites/migrate/section-migrate.jsx
- config/development.json
* If migration is navigated to for sites that don't support it (non-Atomic Jetpack sites), redirect to the `/import` page for that site.
* Remove an unused feature-flag, `manage/import-to-jetpack`, so that the Import experience is consistent across all environments for non-Atomic Jetpack sites:
* Navigate directly to `/migrate/:siteSlug`, where `:siteSlug` is the slug for a non-Atomic Jetpack site. Verify that you are redirected to `/import/:siteSlug` and that the message about visiting wp-admin is displayed.
* Navigate to a migration page for a supported site. Use the site-selector to switch to a non-Atomic Jetpack site. Verify the redirection mentioned above occurs.
> Site Migration: Show wp-admin link for non-atomic Jetpack sites

- client/my-sites/migrate/step-import-or-migrate.jsx
- client/my-sites/migrate/step-source-select.jsx
* This PR slightly changes the wording in two steps of the site migration flow. The link to the Jetpack install is given an explicit "Install Jetpack" call to action to make it clearer what it does. The text about uploading WordPress imports is changed to refer to a "WordPress export file" to communicate the fact that we're expecting a WXR file.
* Apply the PR or use `calypso.live`.
* Go to `/import/[ SITE ]` in a Simple or Atomic site, and click on WordPress.
* Note the new wording on the "What WordPress site do you want to import?" page.
* Enter the URL of a WordPress site without a Jetpack connection, like `lost-skink.jurassic.ninja`.
* Note the new position and wording of the "Install Jetpack" link.
> Site migration: change wording of Jetpack install link and text about WordPress content imports

- client/my-sites/current-site/notice.jsx
- client/my-sites/navigation/index.jsx
This PR makes so that the sidebar coponent gets loaded async for both calypso and jetpack cloud.
* Load calypso. Notice that the sidebar on sites looks as expected and works like that as well. 
* Load jetpack cloud with `npm run start-jetpack-cloud` notice that the sidebar looks and works as before. 
You shouldn't notice any different in loading as a user.
> Update: Async load the sidebar on the cloud and calypso

- client/components/badge/README.md
- client/components/badge/docs/example.jsx
- client/components/badge/index.jsx
- client/components/badge/style.scss
- client/components/badge/test/index.js
* Adds a new error style to the badge component. 
New designs.
Notice when you switch between the different colour scheme that the badge colours don't change. 
* Checkout the dev docs. http://calypso.localhost:3000/devdocs/design/badge
> Add:  Error style to badge component

- client/landing/gutenboarding/constants.ts
- client/landing/gutenboarding/gutenboard.tsx
- client/landing/gutenboarding/onboarding-block/acquire-intent.tsx
- client/landing/gutenboarding/onboarding-block/colors.scss
- client/landing/gutenboarding/onboarding-block/design-selector/index.tsx
- client/landing/gutenboarding/onboarding-block/edit.tsx
- client/landing/gutenboarding/onboarding-block/style-preview/font-select.tsx
- client/landing/gutenboarding/onboarding-block/style-preview/index.tsx
- client/landing/gutenboarding/onboarding-block/style-preview/preview.tsx
- client/landing/gutenboarding/onboarding-block/style-preview/style.scss
- client/landing/gutenboarding/onboarding-block/style-preview/viewport-select.tsx
- Reworks slightly to make them available for other steps.
- Fixed, although  #40201 is a pain point.
~This slightly regresses the designs (some colors are applied unecessarily) and highlights the need for iteration on the color system (#40201). For example, the title should not be blue here:~
- Adds style for the preview frame
- Loads fonts for the font picker buttons
- Style and layout for the font-picker buttons
This is slightly outdated. The title colors in design and font selection steps are now black as before.
* Visit gutenboarding in dev environment [`/gutenboarding`](http://calypso.localhost:3000/gutenboarding)
> Gutenboarding: Color and style updates

- client/assets/stylesheets/_calypso-color-scheme-jetpack-cloud.scss
- client/landing/jetpack-cloud/components/log-item/index.tsx
- client/landing/jetpack-cloud/components/scan-history-item/index.jsx
- client/landing/jetpack-cloud/components/scan-history-item/style.scss
- client/landing/jetpack-cloud/components/threat-description/README.md
- client/landing/jetpack-cloud/components/threat-description/index.jsx
- client/landing/jetpack-cloud/components/threat-description/index.tsx
- client/landing/jetpack-cloud/components/threat-item/README.md
- client/landing/jetpack-cloud/components/threat-item/index.jsx
- client/landing/jetpack-cloud/components/threat-item/style.scss
- client/landing/jetpack-cloud/sections/scan/history/style.scss
- client/landing/jetpack-cloud/sections/scan/main.jsx
- client/landing/jetpack-cloud/sections/scan/style.scss
- The goal of this is to create the Threat Card used on the main screen when threats are found.
- Navigate to http://jetpack.cloud.localhost:3000/scan/<yourSiteSlug>?scan-state=threats
- You should see two threat cards
- Compare it with the designs
See 1151678672052943-as-1165217655856094.
> Create the ThreatItem component

- client/components/rewind-credentials-form/index.jsx
- client/landing/jetpack-cloud/sections/settings/main.jsx
- client/landing/jetpack-cloud/sections/settings/style.scss
**_Please remember, this is a minimal changeset that brings in the foundation of this page. It merely  sets the stage for a MVP, and is not yet meant to be an MVP. Additions, fixes, can/should be added as future PRs._**
* Modifies the `RewindCredentialsForm` component to accept a `notices` boolean, allows us to disable the legal text notices
* Adds a connection status module to the top of the settings page (let's make this it's own component at a later date, perhaps for use on the dashboard as well)
* Adds a contextualized `RewindCredentialsForm` to the settings page
* Adds basic styling for large screens throughout (mobile styles need discussion)
* Test the settings page for a site with valid credentials.
* Test the settings page for a site without credentials. Test adding working …
> Jetpack Cloud: Add settings page

- client/landing/jetpack-cloud/components/sidebar/index.jsx
- client/landing/jetpack-cloud/components/sidebar/style.scss
- client/landing/jetpack-cloud/index.js
* Adds history and scanner to the jetpack cloud sidebar. 
* Makes the sidebar work like calypso with the expandable component.
* Update the url of the history view to be more in line with calypso.
Before:
After:
* Load up jetpack cloud 
* Click on the scan section. Does it work like you would expect?
> Jetpack Cloud: Update Scan Section Sidebar

- config/horizon.json
This allows adding domains in the Horizon testing environment.
None, but once this is enabled, visit https://horizon.wordpress.com/domains/manage/example.com (for your site address) and verify that you see a "Add domain" button.
> Enable `upgrades/domain-search` flag in horizon

- client/my-sites/checkout/checkout/composite-checkout.js
- packages/composite-checkout-wpcom/src/components/wp-contact-form.js
This modifies the contact step form in composite checkout so that the form fields are disabled when the form is not ready (eg: during submit) or when the contact step is not active.
This should not have any noticeable effect, but will prevent the unlikely case that the fields are edited when they should not be.
- Visit composite checkout without a domain and verify that the contact fields are editable as expected.
- Visit composite checkout again with a domain (and the query string `?flags=composite-checkout-testing`) and verify that the contact fields are editable as expected. Click to go to the next step and verify that when the step is pending, the fields are disabled.
> composite-checkout: Disable contact fields when form is not ready

- client/my-sites/customer-home/main.jsx
* With this PR, the banner congratulating the user for completing every item in their checklist should never appear at the same time as the "Your site has been imported!" banner.
* Apply the PR, or use `calypso.live`.
* Have a new Simple site you've completed all the checklist items on.
* Open the site in Calypso, go to `/import/[ SITE ]` and click WordPress.
* Enter the URL of a Jetpack site to import from.
* Follow the steps and complete the migration.
* At the end of the process you should be redirected to the customer home. You should only see the "Your site has been imported!" banner, not the banner congratulating you for completing every item in your checklist.
> Site migration: don't show checklist completed banner if we're showing site recently migrated banner

- packages/composite-checkout-wpcom/src/components/wp-checkout.js
The contact details step currently is not displayed if the cart costs 0 currency, for ease of use.
This change modifies composite checkout so that it will also display the contact step if the domain fields are needed (if there is a domain in the cart).
- Visit composite checkout with a plan, but no domain, in the cart. Verify that the (postal and country code only) contact step is shown.
- Add a coupon code that provides a 100% discount (ask me if you cannot get one yourself) or make sure you have a plan with an unused domain credit available and use a domain in the cart with the `?flags=composite-checkout-testing` query string. 
- Visit composite checkout and verify that the contact step is _not_ shown.
- Add a domain to your cart and visit checkout with the …
> composite-checkout: Show contact step if domain fields are needed

- client/my-sites/domains/domain-management/list/item.jsx
Fixes an issue where the cart button and the domains filter button do not appear as they should, due to how the `Button` was imported.
Before applying the fix, to reproduce the issue, choose a site -> go to Domains -> Click on Add Domain, and then search for something.
On the top right, the cart button and the filter button will appear like in the screenshot below:
Then, apply the fix, and follow the same steps as before. The buttons should now appear as they should, as shown below:
> Domains: Fix button style import issue

- client/blocks/product-selector/index.jsx
- client/lib/products-values/constants.js
- client/lib/products-values/products-list.ts
- client/my-sites/plans-features-main/index.jsx
- client/my-sites/plans-features-main/style.scss
- config/development.json
Partially addressees #39858. Design is not final and will be iterated upon.
* Add support for showing Jetpack Search product in `/plans` via a feature gate.
1. Spin up this branch locally.
2. Navigate to `/plans` and select a Jetpack site without any plan subscriptions. You should see something like this at the bottom:
3. Navigate to `/plans` and select a Jetpack site with a plan that includes Jetpack Backups. You should see something like this:
4. Navigate to [`/plans` in wp-calypso](https://calypso.live/?branch=add/jetpack-search-plans-part-1) for a Jetpack site without any Jetpack plans. Alternatively, you can add a `flags=-jetpack/search-product` query string to the URL. You should see something like this:
5. Repeat step 4 for a Jetpack site with a Jetpack plan that includes Backups. …
> Jetpack Search: Display in plans page

- client/landing/gutenboarding/components/domain-picker/index.tsx
Fixes https://github.com/Automattic/wp-calypso/issues/40159
* Prefill domain picker's search input with site title entered by user.
1. Go to `/gutenboarding`.
2. Enter your site vertical and site title.
3. Click on the domain picker dropdown.
4. The domain search input field should be prefilled with what you entered on your site title.
1. Once user has selected a domain from the domain picker, changing the site title again would cause another new domain to be automatically suggested, discarding what the domain that the user originally chose. We need to introduce another state to store what domain user has explicitly chosen, and maintain that domain. We could fix this in another PR, or we could do it in this PR. Please discuss what to do in comments of this PR! Thanks!
> Gutenboarding: Prefill domain search input from user entered site title.

- client/my-sites/migrate/section-migrate.jsx
* Add a delay of 30 seconds after a migration is started from the cart before polling results in an update.
* Start a migration on a site without a business plan.
* Complete the purchase of the business plan in the migration flow.
* After migration starts, reset the migration.
* Verify that the status of the migration updates.
> Site Migrations: Don't refresh migration status for first 30 seconds

- apps/full-site-editing/full-site-editing-plugin/blog-posts-block/index.php
* This allows the translations to actually be loaded for the Blog Posts block.
* Activate the Full Site Editing plugin on a self-hosted site.
* Change your UI language to something else than English (a popular one, like German, for example).
* Make sure to download the latest language packs (you can verify this in languages/plugins/full-site-editing-*)
* Create a new post in Gutenberg and add a Blog Posts block and observe translated text.
See D39116-code for this, it's already live on WordPress.com.
> Full Site Editing: Add missing wp_set_script_translations call

- client/me/purchases/manage-purchase/purchase-meta.jsx
Traditionally customers with domains and plans can access the renewal auto-toggle in related product purchase pages, enabling them to turn off, or on the auto-renewal status of the product.
Customers with G Suite products see this instead:
* The logic to display the auto-toggle is adjusted to include G Suite products as well.
NOTE: You may need to add a payment method in the production instance as you may not be able to properly add payment methods in purchases page of the dev server.
* Checkout this branch in your development instance, likely http://calypso.localhost:3000
* Ensure you have a valid G Suite subscription 
* Ensure you have a valid payment method associated with that subscription
* Access the related purchase page starting from …
> Enable customers turn off/on auto-renewal on their G Suite subscriptions 

- client/state/selectors/is-site-recently-migrated.js
* Updates the `isSiteRecentlyMigrated` selector for the API change in D40459-code.
* Follow test instructions from D40459-code.
> Site Migration: Update isSiteRecentlyMigrated selector to use API change

- client/landing/jetpack-cloud/components/masterbar/index.jsx
- client/landing/jetpack-cloud/components/masterbar/style.scss
* Update the logo in the masterbar. 
Before:
After:
Load up the jetpack Cloud. 
Notice the  new jetpack logo in the masterbar does it look like expected?
> Update the jetpack logo in the masterbar for jetpack cloud.

- client/landing/jetpack-cloud/components/security-icon/images/error.svg
- client/landing/jetpack-cloud/components/security-icon/index.tsx
- client/landing/jetpack-cloud/sections/scan/main.jsx
- client/landing/jetpack-cloud/sections/scan/style.scss
* This PR adds a basic Scan error page. 
See:
* Load up jetpack cloud with `npm run start-jetpack-cloud`
* Go to http://jetpack.cloud.localhost:3000/scan/{siteSlug}?scan-state=error
* Does the page look lke you would expect. 
This page doesn't take into account the if threats are already found.
> Jetpack Cloud: Add Scan Error Page

- client/my-sites/checkout/checkout/composite-checkout.js
- packages/composite-checkout-wpcom/src/hooks/has-domains.js
- packages/composite-checkout-wpcom/src/lib/translate-cart.ts
This treats Domain Transfers as domains for the purposes of showing the extra contact fields and other behaviors which rely on identifying domains.
- Visit composite checkout with a domain transfer in your cart. (You'll need to add `?flags=composite-checkout-testing` as the query string.)
- You can select any payment method in the first step.
- Verify that the second step displays the full contact details form (name, address, etc.)
- (Bonus) Verify that purchasing the domain transfer is successful. Only do this if you are ok transferring a domain!
> composite-checkout: Treat domain transfers as domains

- client/my-sites/migrate/section-migrate.jsx
Prior to this PR, the state would flicker when starting a migration from checkout from "Backed up" to "Backing up", eventually to "Backed up" again. This was because `new` was treated as `restoring` for `renderProgressItem` for the backup progress item.
* Apply PR.
* Do a migration with a simple site.
* Pay attention to the status items immediately when migration starts. They should not flicker from backed up to backing up to backed up.
> Migration: Fix progress-item handling for new state

- client/my-sites/hosting/sftp-card/style.scss
It can be hard to distinguish the characters (i.e. `Il10O`) in the SFTP credential fields when using a proportional font-family. This updates the fields to use a monospaced font.
Before | After
**To test:**
- on an Atomic site, visit Manage > Hosting Configuration
- verify that the field values under SFTP Credentials are monospaced
> Hosting Settings: use monospaced font for SFTP credentials

- client/my-sites/customer-home/free-photo-library-card/index.jsx
- client/state/inline-support-article/actions.js
Janitorial follow up to @Aurorum's https://github.com/Automattic/wp-calypso/pull/40157
This updates the open support dialog dispatch to a single redux action, instead of two calls for open/tracking metrics. Changes here also remove the unnecessary `SUPPORT_ARTICLE_DIALOG_OPEN` action thunk (function) in favor of returning a plain action.
- In console `localStorage.debug='calypso:analytics*'` to enable analytics logging
- Refresh calypso.localhost:3000 to have settings take effect
- Navigate to My Home
- Click on "Learn More"
- Verify that `calypso_customer_home_free_photo_library_video_support_page_view` is fired
- No regressions in dialog behavior
- Verify that other support page opens work as expected.
> Support: prefer plain action over thunk and decorate free video support article open

- client/gutenberg/editor/calypsoify-iframe.tsx
- client/gutenberg/editor/controller.js
- client/gutenberg/editor/index.js
- client/sections.js
- client/state/selectors/get-site-editor-url.js
Loads the Site Editor through an Iframe instead of directing to wp-admin.  
Must be used along with - D40421 
* Run this PR on Calypso and patch D40421 to your sandbox.
* Select a site with the `core-site-editor-enabled` sticker (may also require `gutenberg-edge` sticker to be enabled).
* Click the "Site Editor" button and ensure this is now loaded in an iframe.
* Smoke test the standard Page / Posts editors.
Fixes #39886
> Site Editor iframe integration

- client/signup/steps/domains/index.jsx
- config/development.json
* When the domain step in signup is skipped, the `suggestion` prop value is set to `undefined` so that it overwrites any earlier values assigned to the prop. This will ensure that we do not get a false positive since the suggestion prop value is used to determine if we should show the "Start with free" option in the plans step(we do not show this option if a custom domain has been chosen).
* This issue was originally reported in the slack conversation p1581446007071000-slack-onboarding-exp.
**Scenario 1**
1. Begin at /start and go through the signup flow. 
2. At the domain step, try the following scenarios:
- Select a custom domain -> you should not see the "Start with free" in plans step -> select a plan and verify that the selected domain and plan were added to cart
- Select a free …
> Fixes the issue of missing "Continue with your free site" option in site launch flow

- client/my-sites/media-library/proxied-image.tsx
Removes effect dependency on `imageObjectUrl`. It's redundant and causes unnecessary reruns of the effect.
Same as in https://github.com/Automattic/wp-calypso/pull/39616
> [Private sites] Remove redundant dependency on imageObjectUrl

- client/my-sites/checkout/cart/style.scss
This makes sure that nominally long prices are not split into two lines in the cart total:
The easiest way to test long numbers would be with an account using the HUF currency.
Here are some before and after screenshots.
**DESKTOP**
**HU/HUF** - before
**HU/HUF** - after
**ID/IDR** - before
**ID/IDR** - after
**DE/EUR** - before
**DE/EUR** - after
**Mobile** (shown when clicking on the "Show order details" link)
**HU/HUF** - before
**HU/HUF** - after
**DE/EUR** - before
**DE/EUR** - after
> Old checkout: fix cart total display when nominal price is high

- client/my-sites/migrate/section-migrate.jsx
* This PR fixes a very obtrusive flickering that happens when starting a migration from a WordPress.com Simple site.
* The issue is that we were updating the site status until it became WordPress.com Business site, but due to the nature of how the API responds, we were causing state issues and the UI flickered between locked and unlocked states until the site was upgraded succesfully.
* Apply D40543-code to your sandbox
* Sandbox the API
* Use the Calypso.live link or test on local Calypso
* Create a new WordPress.com Simple site
* Start migration
* Notice reduced lock/unlock flickering
Known issue: There's still some initial flickering that's happening, but will be investigated in a separate PR.
> Site Migration: Don't update the Site instance in Calypso until the site becomes WordPress.com Business

- client/landing/jetpack-cloud/components/sidebar/index.jsx
* This PR adds menu items for `Status` and `Activity Log` under the Backups menu item.
* Load up Jetpack Cloud. Do all the menu items for Backups function as they should?
Note, we have no route for `/activity` yet, I'll add that in a different PR shortly. For now the 404 is okay.
> Jetpack Cloud: Add proper sidebar items for Backup section

- client/jetpack-connect/style.scss
- client/lib/plans/plans-list.js
* Updates Jetpack plans tables according to the latest pattern in Calypso; adds audience highlight.
* Updates pricing section in signup plans tables.
* Visit `http://calypso.localhost:3000/plans/SITE_URL` and ensure the audience highlight is visible (on both mobile and desktop).
* Visit `http://calypso.localhost:3000/jetpack/connect/store/` and ensure the pricing section looks good on desktop (mobile is unchanged).
> Plans: Update descriptions and pricing styling for Jetpack

- client/me/purchases/manage-purchase/index.jsx
Fixes https://github.com/Automattic/wp-calypso/issues/40267 
This PR takes the loading of domains out of the account if the purchase isn't a domain. 
The reason why the pages shows the placeholder is because the user isn't part of the site any more and the request for domains (`/sites/(siteID)/domains`) returns access denied error. Since the user is not part of that site any more. 
This PR fixes the page by skipping the loading of placeholder if the purchase is not a domain. 
Since in those cases we don't care how the domains endpoint reacts. 
cc: @eltongo 
Since this regression was introduced in https://github.com/Automattic/wp-calypso/commit/5b9461014fe11939933ef247fadc5a58f2b99ad9#diff-e2b8265ef22dd8af459ffe058b1b3b08R455 
Does the solution make sense or is it breaking something else? …
> Manage Plans: Fix placeholder loading on plans and product purchases

- client/my-sites/post-type-list/index.jsx
* Use JS to change "Add new post" label from Title Case to Sentence case to match changes made throughout Calypso in #40120 and #39692 
**Before**
**After**
* Navigate to /posts
* Note the "Add new post" button text.
Fixes #40027
> Posts list: Use JS to Sentence case "Add new post" label

- client/state/sharing/services/selectors.js
* Don't display the Instagram Basic Display connection, as this isn't supported yet
* Apply the patch D40423 and sandbox the REST API
* Go to http://wordpress.com/marketing/connections/[site]
* Check that you can see the Instagram Basic Display connection
* Go to http://calypso.localhost:3000/marketing/connections/[site]
* Check that you can't see the Instagram Basic Display connection
> Exclude Instagram Basic Display from the list of connections

- packages/composite-checkout-wpcom/src/components/wp-order-review-line-items.js
This adds the `domain_redemption` item type (the domain redemption one-time fee) to the list of items that shouldn't show a delete icon in the new Checkout.
Fixes #40292 
**To test:**
- on an account with a domain that is both expired and in redemption
- visit Manage Purchases and click "renew" for the domain
- if you're redirected to the plans page (unrelated bug) click the cart item in the top right and visit checkout
- use the `?flags=composite-checkout-force` flag to force new checkout
- verify that the domain redemption fee doesn't have a trash can icon beside it
> New Checkout: don't show remove button for domain redemption cart items.

- client/state/sharing/services/selectors.js
* Don't display the Instagram Basic Display connection, as this isn't supported yet
* Apply the patch D40423 and sandbox the REST API
* Go to http://wordpress.com/marketing/connections/[site]
* Check that you can see the Instagram Basic Display connection
* Go to http://calypso.localhost:3000/marketing/connections/[site]
* Check that you can't see the Instagram Basic Display connection
> change to kebab case

- packages/composite-checkout/src/components/checkout-modal.js
When a user removes an item from the cart in the new Checkout, we display a modal with a body style of `overflow: hidden` but don't remove it, breaking scroll on subsequent pages. This removes the style after the modal is closed.
Fixes: #40293 
**To test:**
- add a plan to your cart
- visit the new checkout (using `?flags=composite-checkout-force`)
- from the third step, empty the cart, click "continue", and leave checkout
- verify that you can scroll the subsequent page
> New Checkout: remove body overflow style after modal closes.

- client/lib/signup/step-actions/index.js
Currently, when we create sites, they get a time zone of "UTC+0." instead of their current locale.  The settings page then shows a guess using the mechanism used in this PR:
This change seeks to guess the time zone under the supposition that it will be what our customers expect more often than the current behavior.
Discussion: p1579203203144700-slackCCS1W9QVA
* Send the result of `moment.tz.guess()` to the site creation endpoint via `options.timezone_string` during signup
* Apply D37828-code (Update: I (@ramonjd) couldn't get it to work without adding the option update to Headstart. Please try D40358-code, which updates the option via Headstart if you're experiencing similar issues. )
* Sandbox `public-api.wordpress.com`
* Run this branch
* Create a new site via `/start`
* The site's time …
> Site Creation: Send "guessed" browser timezone string for new sites

- client/landing/jetpack-cloud/components/sidebar/index.jsx
- client/landing/jetpack-cloud/sections/scan/main.jsx
This PR adds links to the jepack.com/support to the jetpack cloud. 
After:
* Go to http://jetpack.cloud.localhost:3000/scan/{example.com}?scan-state=error
Notice that the links take you to contact support pages as you would expect.
> Jetpack Cloud: Update support links

- client/landing/jetpack-cloud/components/scan-threats/index.tsx
- client/landing/jetpack-cloud/components/scan-threats/style.scss
- client/landing/jetpack-cloud/components/threat-dialog/index.tsx
- client/landing/jetpack-cloud/components/threat-item/index.jsx
- client/landing/jetpack-cloud/components/threat-item/index.tsx
- client/landing/jetpack-cloud/components/threat-item/style.scss
- client/landing/jetpack-cloud/components/threat-item/types.tsx
- client/landing/jetpack-cloud/sections/scan/main.jsx
- client/landing/jetpack-cloud/sections/scan/style.scss
- Currently, the only way to display the ThreatDialog component is by clicking one of the dummy buttons we have in the Scan main screen. Therefore, the goal is to make the Fix/Ignore threat buttons of a ThreatItem component display a ThreatDialog component.
- Navigate to http://jetpack.cloud.localhost:3000/scan/<yourSiteSlug>?scan=threats
- Click the "Fix threat" button
- You should see the "Fix threat" dialog
See 1151678672052943-as-1167257479032409.
> Jetpack Cloud: Add/connect threat dialog to threat cards

- client/my-sites/migrate/section-migrate.jsx
In this PR, we treat the migration status "new" the same as "backing-up" to eliminate a momentary flash of the wrong progress UI at the beginning of a migration to a Simple site, after the user has bought a Business plan.
When we first insert the DB record for a migration, we give it the status "new". Almost immediately afterward, it gets the status "backing-up".
When you migrate to a Simple site without a Business plan, after you've paid for the plan, we redirect from the cart back to the migration section. When it mounts, the migration component sets the local migration status to "backing-up". On redirection, the page makes a request to the `sites` endpoint. Depending on the timing, this can return `site_migration` meta for the current site with the status "new". This status should be …
> Site migration: show proper progress elements when migration has the status "new"

- client/my-sites/customer-home/main.jsx
- client/my-sites/customer-home/quick-links/action-box.jsx
- client/my-sites/customer-home/quick-links/index.jsx
- client/my-sites/customer-home/quick-links/style.scss
- client/my-sites/customer-home/style.scss
This PR moves QuickLinks in the Home section from main to its own component file.
Folks are welcome to hop into this if y'all are interested
I expanded out the `trackAction`, so we can do a proper string search for analytics events. Same thing applies for being verbose for SASS `&__` rules. It makes it much easier to refactor and debug when we can find related code with a simple search.
> Home: Move Quick Links into its own component

- client/my-sites/importer/file-importer.jsx
- client/my-sites/migrate/migrate-button.jsx
- client/my-sites/migrate/section-migrate.jsx
- client/my-sites/migrate/step-import-or-migrate.jsx
- client/my-sites/migrate/step-source-select.jsx
- client/my-sites/migrate/step-upgrade.jsx
This PR adds Tracks events for the following:
- When WordPress is clicked in the list of importers
----
- When "What WordPress site..." screen is viewed
----
- When type of WordPress import selection screen is viewed
----
- When Business Plan screen is shown
- When "Upgrade and import" is clicked
----
- When "Import and overwrite is clicked"
----
- When migration is started
> WP Migration: Add missing Tracks events for migration

- client/me/concierge/shared/appointment-info.js
* ~Removing time zone indicator for the concierge appointment time to support localized formats that do not use timezone indicators. Since the time of the appointment is shown in the user's browser local time, a timezone indicator is not needed. ~
* The timezone indicator on the session dashboard is based on the timezone in which the appointmetn is booked.
* Change this to make the timezone based on the browser local time. So if a user booked their session for 8 AM EST, and if they are currently in GMT timezone, the session time should shown in GMT.
* Fixes 56-gh-concierge-admin
In the images below, the session appointment begins at 8 AM EDT. So, in my timezone(Indian Standard Time), it is 17:30. 
**Before:**
**Timezone incorrectly shown to be EST, though the time of the appointment is …
> Session dashboard: Add timezone indicator based on browser local time

- client/landing/gutenboarding/components/titles.scss
- client/landing/gutenboarding/onboarding-block/design-selector/style.scss
- client/landing/gutenboarding/onboarding-block/style-preview/preview.tsx
- client/landing/gutenboarding/onboarding-block/style-preview/style.scss
Major layout improvements to the style (font) step as well as several visual improvements e.g. subtitle font color:
The design selection step is also affected:
Part of  #40160
Boot calypso in local development and visit http://calypso.localhost:3000/gutenboarding. Run through and check the changes on the design and style steps.
> Gutenboarding: Layout style step

- client/landing/gutenboarding/onboarding-block/style-preview/preview.tsx
- client/landing/gutenboarding/onboarding-block/style-preview/style.scss
- Render browser chrome for tablet and mobile viewports
- Size tablet and mobile viewports
The sizes will surely need to be tweaked. Currently, no preview is rendered in the frame, that will be handled by #40227 
There didn't seem to be designs for tablet, so I grabbed a size and added the mobile chrome.
**We need to consider how to handle this tablet view** it will force scrolling on many viewports.
* Boot up this branch locally and navigate to http://calypso.localhost:3000/gutenboarding
* Use the viewport switcher
Fixes #
> Gutenboarding: Style preview size & chrome

- client/landing/domains/index.jsx
Fixes https://github.com/Automattic/wp-calypso/issues/40328
Introduced by https://github.com/Automattic/wp-calypso/pull/38313
Similar to https://github.com/Automattic/wp-calypso/pull/38551
Go to https://wordpress.com/domain-services/registrant-verification in different browsers - especially Edge 44 on Windows or old(er) versions of Safari. The page should look like this:
Make sure there are no critical errors in the console.
> Domains: Add polyfill to domains-landing

- client/my-sites/stats/site.jsx
- client/my-sites/stats/stats-banners/index.jsx
* Removes the GSuite upsell banner and checklist progress banner from Stats. These have moved to Customer Home.
* Wondering if we should just remove `StatsBanners` entirely, since they're only shown when Customer Home is not active?
https://github.com/Automattic/wp-calypso/blob/9820c2fa70292fda1db438deca943ce1b29f0faa/client/my-sites/stats/site.jsx#L172-L174
**Before**
(You shouldn't see this if you have Customer Home enabled on your site, but this will give you an idea of what the banner would look like.)
**After**
* Navigate to Stats with a bunch of different types of sites (Free, Personal, Premium, Business, ECommerce, etc.) to ensure you don't see the GSuite upsell or the checklist progress banners.
> Stats: Remove StatsBanners

- client/my-sites/checkout/checkout/composite-checkout.js
- packages/composite-checkout-wpcom/src/hooks/use-shopping-cart.ts
This adds a new analytics event, `calypso_checkout_composite_cart_loaded`, which is triggered when checkout first downloads the cart from the shopping cart endpoint. It includes a list of the products from that cart as a comma-separated string of product slugs.
- Run `localStorage.setItem( 'debug', 'calypso:analytics*' );` in your console and refresh the page.
- Complete a purchase using composite checkout. 
- Verify that you see the above properties in the debug log for that event.
> composite-checkout: Record products from cart after first load

- client/landing/jetpack-cloud/components/masterbar/index.jsx
- client/landing/jetpack-cloud/components/masterbar/style.scss
* Update the masterbar to include the title. 
Before:
After:
Load up jetpack cloud. Dos the styling look of the master as you would expect?
Try different screen widths.
> Jetpack Cloud: Add title to the masterbar.

- client/landing/jetpack-cloud/components/stats-footer/style.scss
- client/landing/jetpack-cloud/sections/scan/history/index.jsx
- client/landing/jetpack-cloud/sections/scan/history/style.scss
- client/landing/jetpack-cloud/sections/scan/main.jsx
- client/landing/jetpack-cloud/sections/scan/style.scss
* Cleans up some of the Jetpack Cloud Scan section styles. 
Before:
After:
* Load up Jetpack Cloud
* Checkout the Scan section, scanner and history. 
Does it look like as expected. 
Check both Desktop and mobile.
> Jetpack Cloud: Scan section fix styles

- client/my-sites/customer-home/main.jsx
- client/my-sites/stats/stats-banners/index.jsx
This PR removes the G Suite nudge from My Home page.
Right now this upsell appears in the My Home page:
Make sure that after the changes, it no longer appears.
> GSuite: Hide G Suite nudge from My Home

- client/landing/gutenboarding/onboarding-block/style-preview/style.scss
This improves the font picker buttons overall to be closer to the designs in their size as well as fixes an issue with the font alignment.
Fixes #40206
Design | Branch
--- | ---
Checkout and run locally. Visit `http://calypso.localhost:3000/gutenboarding` and proceed to this step.
> Gutenboarding: Font button style/size

- client/lib/importer/importer-config.js
This adds the missing support document links for GoDaddy and Wix (the documents already exist), and ensures that all of the importers use the Support Article Dialog to display the documents in-Calypso first.
Check the links for each Importer (they're typically in the description near the Importer's name) and verify that the correct support document is displayed.
cc @lancewillett and @jonathansadowski
Fixes #33391
> Importer: Utilise Support Article Dialog & Add Missing Links

- client/components/domains/domain-product-price/index.jsx
- client/components/domains/domain-product-price/style.scss
- client/components/domains/domain-registration-suggestion/index.jsx
- client/components/domains/domain-search-results/index.jsx
- client/components/domains/domain-suggestion/index.jsx
- client/components/domains/domain-suggestion/style.scss
- client/components/domains/domain-transfer-suggestion/index.jsx
- client/components/domains/featured-domain-suggestions/index.jsx
- client/components/domains/featured-domain-suggestions/style.scss
- client/components/domains/free-domain-explainer/index.jsx
- client/components/domains/free-domain-explainer/style.scss
- client/components/domains/register-domain-step/index.jsx
- client/components/domains/register-domain-step/style.scss
- client/components/domains/search-filters/dropdown-filters.jsx
- client/components/domains/search-filters/style.scss
- client/components/domains/search-filters/tld-filter-bar.jsx
- client/lib/abtest/active-tests.js
- client/signup/steps/domains/index.jsx
* The domain step test introduced in https://github.com/Automattic/wp-calypso/pull/39276 is being reverted since the variant lost to control. This PR removes all the new code introduced as part of the domains step test.
* Assign yourself to _control_ and _variantShowUpdates_ of **domainStepCopyUpdates** test. Verify that the UI for the domain step in both cases is unaffected by this PR. The best way to test this is to compare the domain step UI at https://wordpress.com with the UI in this PR.
* Verify everything works and that you can complete signup.
> Domain step test: Revert to control

- client/lib/wpcom-undocumented/lib/undocumented.js
- client/my-sites/media-library/media-file.tsx
- client/my-sites/media-library/proxied-image.tsx
- client/post-editor/media-modal/detail/detail-preview-audio.jsx
- client/post-editor/media-modal/detail/detail-preview-media-file.tsx
- client/post-editor/media-modal/detail/detail-preview-video.jsx
- client/post-editor/media-modal/detail/style.scss
On private atomic sites we use media proxy endpoint to pull private media files. Streaming is not supported yet and so an entire media file needs to be downloaded in order to display it. For large files it's not a good user experience - this PRs sets a limit to 20MB.
* Test locally, calypso.live won't work
* Create a new private atomic site using a8c account
* Upload two video files (in /wp-admin !) - larger than 20mb and smaller than 20mb
* Go to media in calypso and edit both
* The smaller one should be displayed
* The larger one shouldn't be displayed, instead you should see a direct link to that file
> [Private sites] Don't attempt to display preview for media files larger than 20MB

- client/post-editor/controller.js
- client/post-editor/editor-gutenberg-blocks-warning-dialog/index.jsx
- client/post-editor/editor-gutenberg-dialogs/index.tsx
- client/post-editor/editor-gutenberg-opt-in-dialog/index.jsx
- client/post-editor/editor-sidebar/index.jsx
- client/post-editor/post-editor.jsx
- client/state/selectors/get-wp-admin-classic-editor-redirection-url.ts
- client/state/selectors/is-private-site.ts
**Problem**
Classic editor in calypso does not support displaying private media files because of CORS issues. Adding a support would be super complex and probably not worth it, especially considering that we're phasing out the classic editor altogether. Classic editor in wp-admin handles private files out of the box so we're redirecting all private+atomic+classic editor users from calypso to wp-admin with `?classic_editor` attached to URL.
**Proposed solution**
We do have some dialog windows in place when user uses classic editor in Calypso:
Gutenberg content warning:
Gutenberg opt-in:
My proposal is that for v1 we:
* Ensure that private+atomic user always sees one of these two modals when visiting classic editor. If no Gutenberg blocks are found in post content, let's display opt-in …
> [Private sites] Redirect private atomic users to wp admin classic editor (from modal)

- client/landing/jetpack-cloud/components/activity-card/index.jsx
- client/landing/jetpack-cloud/components/activity-card/style.scss
- client/landing/jetpack-cloud/components/backup-delta/index.jsx
- client/landing/jetpack-cloud/sections/backups/main.jsx
- client/landing/jetpack-cloud/sections/backups/style.scss
- client/my-sites/activity/filterbar/index.jsx
* When a date range is selected on the backup page, switch to the "Activity Log view" and show a list of appropriate events, along with working filtering and pagination.
* Break out `ActivityCard` into it's own component, retrofit into `BackupDelta` and use in the Activity Log view of the Backup page.
* A few misc improvements/fixes/advancements over a few other related areas.
As usual, **this is not pretty**, but in theory it should be fully functional.
* View the backups page as a daily site, ensure the view still works as expected.
* View the backups page as a realtime site, ensure the view still works as expected.
* Click the calendar icon at the top of the backups page, select a date range. Ensure that the proper data is displayed, that further filtering works, that pagination works, …
> Jetpack Cloud: Add backup search view to backups page

- client/components/domains/register-domain-step/index.jsx
This PR updates the arguments sent to the domain search endpoint when searching for subdomains, so that only free subdomains are suggested.
* Go to calypso.localhost:3000/start
* Enter a search query which contains a blacklisted term
* Ensure you get valid suggestions, and free subdomain suggestions have no price attached
Fixes #40198
> Domains: Send correct arguments when searching for subdomains

- client/lib/purchases/index.js
When pressing the "renew" buttons on products in the purchases section
of Calypso, the intended action is to add the renewal product to the
cart, and then redirect to the checkout pages.
However, these two actions can cause race conditions since the redirect
does not wait for the cart modification to be complete. (Nor can it, in
any easy way, since modifying the cart is an async dispatched action
with no response.)
This commit removes the code that adds the product to the cart and
instead modifies the redirect URL so that it includes the product to be
renewed, thus allowing checkout itself to add the product to the cart
while it loads.
Fixes #40260 
We'll need to test every type of product that can be renewed (at least, those that renew via the `handleRenewNowClick` function) and make …
> Purchases: Make renew buttons use checkout URL rather than addItems

- client/landing/gutenboarding/components/header/index.tsx
* The "creating site" animation is replaced in browser history by the next step in the flow
* Create a site and sign up for an account
* Get taken to the block editor
* Click the browser back
* Don't go back to the animation (you actually be taken back to the start of gutenboarding because the data store has been cleared)
We should also test the domain purchase flow too, but it's currently broken on `master`. But the idea is that clicking back from the checkout shouldn't take you to the animation.
> Replace site creation animation in browser history

- client/my-sites/checkout/checkout/composite-checkout.js
- client/my-sites/checkout/checkout/index.jsx
It wasn't possible to do that before, since the way the shopping cart code works, Jetpack products need to be hardcoded in.
Connect a Jetpack site to WordPress.com, then go to `plans/[site]` and make sure you can add a Jetpack Search product by clicking "Get Search".
> Allow Jetpack Search products to be added to the shopping cart from the plans page

- client/blocks/plan-storage/index.jsx
- client/blocks/plan-storage/test/bar.jsx
- client/blocks/plan-storage/test/plan-storage.jsx
- client/lib/plans/constants.js
- client/lib/plans/features-list.js
- client/lib/plans/plans-list.js
Currently, Business and eCommerce plans do not show users how much of their allotted quota they have used in the media library.
This change will now show that info by updating the features in those plans to use a new `FEATURE_200GB_STORAGE` constant, instead of `FEATURE_UNLIMITED_STORAGE`, which no longer makes sense since they don't have unlimited storage.
This should work for both Simple and Atomic sites.
[Previously we had just updated the copy](https://github.com/Automattic/wp-calypso/commit/9083014a8c07b16449f1b961d28c25b2f74ae020) that's displayed for the unlimited space feature to show 200GB. This change makes the storage space feature for Business and eCommerce more inline with the other plans.
Relies on API endpoint update here: D40523-code
More info: pau2Xa-Xd-p2
Fixes #35965 …
> Media Library: show 200 GB storage limit for Business and eCommerce sites

- client/landing/gutenboarding/components/header/index.tsx
- client/landing/gutenboarding/components/signup-form/index.tsx
- client/landing/gutenboarding/hooks/use-free-domain-suggestion.ts
- client/landing/gutenboarding/onboarding-block/create-site/create-and-redirect.tsx
- client/landing/gutenboarding/onboarding-block/create-site/index.tsx
- client/landing/gutenboarding/onboarding-block/edit.tsx
- client/landing/gutenboarding/path.ts
- client/landing/gutenboarding/stores/domain-suggestions/index.ts
- client/landing/gutenboarding/stores/onboard/actions.ts
- packages/data-stores/src/site/actions.ts
Add a link to use the existing `/log-in` page for gutenboarding. This allows a way for existing users to log in (regardless of what log in methods they use) while we flesh out an embedded login UI.
Video: https://d.pr/v/8EFkfL
* Add "(experimental login)" link to open existing gutenboarding-based login UI
* Change login link to go to `/log-in`, with a redirect url to return back to gutenboarding when done
* Add `?new` query param to `/create-site` route that creates a site when you land on it
* Redirecting from `/create-site?new` to `/create-site` **replaces** it in the history; if the user clicks the back button we don't create another site
* Refactor site creation code into `createSite()` action and `useFreeDomainSuggestion()` hook so it can be shared
* Tidy unused type definition
Known …
> Gutenboarding: Add login link to use existing `/log-in` for the time being

- client/landing/jetpack-cloud/components/date-picker/index.jsx
- client/landing/jetpack-cloud/components/date-picker/style.scss
- client/landing/jetpack-cloud/sections/backups/main.jsx
The goal is to improve the manipulation of the dates using a`Date` object instead of a text format, as the ActivityLog component does in Calypso. 
* Keep the component neutral, working directly with the `Date` object
* Show the appropriate date format, Today or Yesterday and if a date is in the last year, show the year.
* Applied the expected date selection behavior. Show the previous and the next date from the current selected date: < previous  [current date]  next >. If today is Mar 11, the previous date would be Mar 10 and the next date would be Mar 12.
**Note:** The existing code has been commented intentionally to allow the review of this PR. In the next PR will be uncommented.
Notes: This PR is only to check the functionality, no styles applied.
1. Go to `/backups/:siteSlug` for a …
> Improving the DatePicker component to match the specification

- apps/full-site-editing/full-site-editing-plugin/starter-page-templates/index.js
- apps/full-site-editing/full-site-editing-plugin/starter-page-templates/page-template-modal/components/sidebar-modal-opener.js
- apps/full-site-editing/full-site-editing-plugin/starter-page-templates/page-template-modal/index.js
- apps/full-site-editing/full-site-editing-plugin/starter-page-templates/store.js
- apps/full-site-editing/full-site-editing-plugin/wpcom-block-editor-nux/src/wpcom-nux.js
1. Refactor the `isOpen` part of the SPT modal into a wp data-store for SPT.
2. Use that value to hide the wpcom NUX.
1. Sandbox a test site and the public API.
2. Test that existing SPT behavior works in the following cases (please try to break it or get into a state that breaks it)
a. Creating a new page
b. Changing the layout of an existing page
c. Creating a new page and then changing the layout of that new page.
d. Doing the above steps in different orders and multiple times in a row, sometimes canceling the action.
3. Next, enable the wpcom NUX on the site by selecting "welcome guide" from the "more" menu
4. Before you do anything with the modal, go back to the pages list and create a new page.
5. Before this change, the modal should have appeared on top of SPT at this point. Verify …
> Hide WPCOM Gutenberg NUX if SPT is open

- client/my-sites/earn/index.js
- client/my-sites/earn/main.jsx
- client/my-sites/earn/refer-a-friend/index.tsx
- client/my-sites/earn/refer-a-friend/style.scss
* Adds a stand-alone peer referral page with tracking link.
Use calypso.live link below, or locally, open:
http://calypso.localhost:3000/earn/refer-a-friend
- `/earn/refer-a-friend`
- `/earn/refer-a-friend/[site]`
NOTE: This will only be used for US traffic right now.
> Add stand-alone peer referral page for US traffic.

- apps/full-site-editing/full-site-editing-plugin/blog-posts-block/editor.js
* Allows for multiple instances of the Blog Posts Block.
This was fixed on the Newspack side a while ago, but it looks like we missed removing this restriction on our side.
* Checkout this PR and build the blocks with `$ npx lerna run dev --scope='@automattic/full-site-editing' --stream --no-prefix` from the `/apps/full-site-editing` folder.
* In a new or existing post or page, attempt to insert more than one Blog Posts block.
Fixes #39251
> BPB: Allow for multiple instances

- client/blocks/dismissible-card/index.jsx
- client/my-sites/customer-home/notices/celebrate-notice/index.jsx
- client/my-sites/customer-home/notices/site-created-card/index.jsx
- client/my-sites/customer-home/notices/site-launched-card/index.jsx
- client/my-sites/customer-home/notices/site-migrated-card/index.jsx
- client/my-sites/customer-home/notices/site-setup-complete-card/index.jsx
Follows up https://github.com/Automattic/wp-calypso/pull/40299.
Adds the ability to dismiss the celebratory notices displayed on My Home.
* Repeat testing instructions from https://github.com/Automattic/wp-calypso/pull/40299.
* Make sure all congratulatory notices can be dismissed.
* Reload the page and make sure the notices don't show up again.
* Make sure the notices are dismissed per site: 
* Switch to a different site.
* Make sure the notices show up (unless they have been dismissed for that site).
> Home: Add dismissal support to celebratory notices

- client/my-sites/theme/main.jsx
- client/my-sites/theme/style.scss
- client/my-sites/themes/single-site-wpcom.jsx
- client/my-sites/themes/theme-showcase.scss
This is more a suggestion I'm proposing than a done deal, so please speak up if you don't agree.
* Use a light color scheme to match other upsell nudges in the main content area of Calypso. The audit Jan worked on shows this is the only upsell that uses a dark color scheme.
* Also use a light color scheme on the single theme page upsell, and prevent widows on the button and copy for a cleaner look.
**Before**
**After**
* Navigate to `/themes` when logged in, with a site on a Free plan
* You'll see an upsell nudge when you click the Advanced Themes button at the bottom
* Click on one of the premium themes in the showcase; you'll see another upsell nudge at the top of the screen.
> Theme Showcase: Remove dark upsell banner styles on theme showcase

- client/my-sites/checkout/checkout/index.jsx
- client/my-sites/plans/current-plan/controller.jsx
- client/my-sites/plans/current-plan/current-plan-thank-you/search-thank-you.js
- client/my-sites/plans/current-plan/index.jsx
* enabling the Thank you note for the Jetpack Search
* add its content
* go to `/plans` for a JP site on a non-Professional plan
* purchase Jetpack Search, pass the checkout step
* verify that the Thank you modal appears
To do in a sequel: adapt the copy and redirect
> Jetpack Search: enable and add the Thank you modal

- packages/composite-checkout-wpcom/src/components/item-variation-picker.tsx
- packages/composite-checkout-wpcom/src/components/radio-button.js
- packages/composite-checkout-wpcom/src/components/wp-order-review-line-items.js
This disables the plan length picker and the item delete buttons in the review step of composite checkout when the form is not in a "ready" state (when it is loading, submitting, or validating).
- Enter composite checkout from signup (otherwise the plan length picker will not display).
- Click through to the last step.
- Click to submit the form (it's ok if the submission fails). Verify that the plan length picker is disabled while the form is submitting.
> composite-checkout: Disable plan length picker and delete button when form not ready

- client/landing/gutenboarding/components/domain-picker-button/index.tsx
- client/landing/gutenboarding/components/domain-picker/index.tsx
- client/landing/gutenboarding/components/domain-picker/style.scss
- client/landing/gutenboarding/components/domain-picker/suggestion-item-placeholder.tsx
- client/landing/gutenboarding/components/domain-picker/suggestion-item.tsx
- client/landing/gutenboarding/components/domain-picker/suggestion-none.tsx
- packages/data-stores/src/domain-suggestions/selectors.ts
- packages/data-stores/src/domain-suggestions/types.ts
* Redesign of domain picker.
* Recommended domain badge is introduced. This is determined by picking domain suggestions with exact-match with highest relevance score. This only appears if there is a domain with exact match. Feel free to discuss change of algorithm.
* (Not from the figma prototype.) A selected domain badge is introduced. I'm only introducing that because I needed to do something with the `currentDomain` prop that was introduced in the DomainPIcker component which was unused.
Here are some things you can test:
- Clicking on domain picker dropdown button should display the domain picker.
- When domain picker appears initially, it should display list of suggestion items as placeholders.
- Entering a value on the domain search input should update the suggestion list with new …
> Gutenboarding: New domain picker design

- client/landing/gutenboarding/components/header/index.tsx
- client/landing/gutenboarding/components/header/style.scss
- client/landing/gutenboarding/style.scss
- client/landing/gutenboarding/variables.scss
Part of addressing #40321
- Header title `.gutenboarding__site-title` should be `font-weight: 600`
- Padding left on WordPress logo to the edge of the screen should be `24px` not `18px`
- Header height should be `64px`
Also aligns the WP logo a little better with the rest:
**before**
**after**
> Gutenboarding: Header adjustments

- apps/full-site-editing/full-site-editing-plugin/dotcom-fse/editor/style.scss
* Fix dotcom-fse editor classnames for Gutenberg 7.7.1
* On an edge-stickered site, test that the dotcom-fse frame appears on an FSE site. Test that the frame still appears for non-G2 versions like 7.3 as well.
Related to #40078
> Fix editor frame classnames for 7.7.1

- client/landing/jetpack-cloud/sections/scan/controller.js
- client/landing/jetpack-cloud/sections/scan/history/index.jsx
- client/landing/jetpack-cloud/sections/scan/index.js
* This uses page navigation to set the correct filter instead of relying on the state. 
* Load Jetpack Cloud.
* Navigate to Scan, and select your site.
* Click History.
* Filter scan history events.
Expected result: Changing scan history updates UI and alters current URL. Reloading the page sets the state as expected.
Fixes 1151678672052943-as-1165787355206373.
> Alters scan history to have filter state in route

- client/components/domains/contact-details-form-fields/custom-form-fieldsets/eu-address-fieldset.jsx
- client/components/domains/contact-details-form-fields/index.jsx
This adds inline errors for the optional "organization" field and European-style "city" field in the full domain contact form.
Fixes #40416 
**To test:**
- add a domain to your cart
- force composite checkout for domains with `?flags=composite-checkout-testing`
- use invalid content (`! == 'a-z A-Z 0-9 . , ( ) @ & ' - [space]'`) for the organization field under "contact details"
- select a European country
- use invalid content (`! == 'a-z A-Z 0-9 . , ( ) @ & ' - [space]'`) for the city field
- try to submit the step and verify that inline validation errors are shown for each field
> Composite Checkout: fix inline errors for organizations and EU cities.

- client/lib/gsuite/index.js
- client/lib/gsuite/test/index.js
This pull request enables G Suite for `.in` domains. G Suite should indeed be available to Indian users as well as for any domain except subdomains.
1. Start your server, or open a [live branch](https://calypso.live/?branch=update/allow-in-domains-for-gsuite)
2. Open the [`Domain Search` page](http://calypso.localhost:3000/domains/add)
3. Purchase a `.in` domain
4. Navigate to the [`Email` page](http://calypso.localhost:3000/email)
5. Assert that you can purchase G Suite for this domain
The code changed in this pull request actually duplicates part of the logic that is already available server-side. We should really remove it at some point as this is just a recipe for problems such as this one.
> G Suite: Allow purchases for .in domains

- client/landing/gutenboarding/onboarding-block/question/style.scss
- client/landing/gutenboarding/onboarding-block/style.scss
- client/landing/gutenboarding/onboarding-block/vertical-select/style.scss
Part of addressing #40321
- [Spacing on bottom border on input fields](https://d.pr/i/iYa8lQ) (when filled out) should be `12px` from the letter to the top of the border. It's currently around 27px.
- Button font-size should be `14px` not 16px. And font-weight 500
- Button border-radius should be `4px` not 3px
- `suggestions__label` should be `var(--studio-gray-30)` and not gray-20
**before**
**after**
http://calypso.localhost:3000/gutenboarding?fresh
> Gutenboarding: Intent gather visual fixes

- apps/full-site-editing/full-site-editing-plugin/starter-page-templates/page-template-modal/styles/starter-page-templates-editor.scss
See: https://github.com/Automattic/wp-calypso/issues/40078
Gutenberg has [modified the component button with a smidgen of extra padding](https://github.com/WordPress/gutenberg/pull/19344/files#diff-169503e5275f964f8bd036a7bfcd8f7cR15) (from `padding: 0 8px;` to `padding: 6px 12px;`)
This pushes the text down in the button.
**Current:**
**On Edge-stickered sites (7.7.1):**
We now therefore no longer need the extra line height override.
**Result:**
You could fire up this PR locally, and sync it using the FG instructions about **FSE Plugin Development**
Test using an Edge-stickered site: `/block-editor/page/[EDGE_STICKERED_SITE].wordpress.com`
Or you could just remove the offending line of CSS in the browser console :)
> [Gutenberg 7.7.1]: remove extra button line height on page starter site

- apps/full-site-editing/full-site-editing-plugin/dotcom-fse/plugins/close-button-override/style.scss
- apps/wpcom-block-editor/src/calypso/features/iframe-bridge-server.scss
* Fixed margin-left issue on **Block Insert Button**.
* Fixed missing margin-left on **Close/Back Button** dotcom-fse non-gutenberg edge page editor.
When opening the editor in post or page / fse or non-fse / wp-admin or wp-calypso, the block inserter button should look like this:
> [Gutenberg 7.7] Fix margin on block inserter button.

- apps/full-site-editing/full-site-editing-plugin/starter-page-templates/page-template-modal/components/block-iframe-preview.js
It fixes an IE issue when it creates the body and head elements of the iFrame content page. Issue: https://github.com/Automattic/wp-calypso/issues/40433. Props to @sgomes!!!
Test the templates selector using IE11 and confirm that it fixes the bug.
Fixes https://github.com/Automattic/wp-calypso/issues/40433
> SPT: fix IE issue when creating fragment

- client/my-sites/checkout/checkout/checkout-system-decider.js
The `CheckoutSystemDecider` uses old checkout for most URLs which add a product to the shopping cart, except for the products which have support for adding.
Previously, we made that decision by using `product.includes(allowedProduct)`, but this could create a false positive when `product` contains a dynamic string (eg: a domain name or a theme name) that might include one of the allowed strings.
This PR changes the decision to be `product === allowedProduct` so that the slug must match explicitly.
- Click the buttons on the Plans page to add a plan to your cart. You should see the URL will look something like `/checkout/example.com/personal`.
- Verify that you see composite checkout, and that the item you chose is in the cart.
- Click a button elsewhere in calypso that adds a renewal to …
> Disable composite checkout for slugs not strictly allowed

- client/my-sites/checklist/wpcom-checklist/component.jsx
With D40692-code, we're bringing back the site title step to My Home (since setting the site title was recently removed from signup). This PR updates the completed text for the step, to be less confusing.
**Before**
**After**
* If it hasn't been deployed yet, sandbox the API and apply D40692-code.
* Create a new Simple site.
* Complete the site title checklist step.
* Go back to My Home, click the "you updated your site title" dropdown, and verify the text is correct.
> My Home: Update the completed description for the site title step.

- client/my-sites/checkout/checkout/composite-checkout.js
Composite checkout uses its own function to fetch data from the shopping cart endpoint, but in order for certain features to work (eg: thank-you page generation), it also currently has access to the cart object from the `CartStore`. A common behavior is for a page in Calypso to emit an event to request changes to the cart, and then redirect to checkout. The `CartStore` then asynchronously applies these changes. This can result in a race condition wherein a product added to the cart has not yet reached the cart on the server by the time that composite checkout fetches the cart.
In theory this shouldn't be a problem because when the `CartStore` finishes updating, it will re-render all of checkout, but composite checkout will not re-fetch the cart when it is re-rendered, meaning it will …
> composite-checkout: Prevent loading cart if CartStore is loading

- packages/composite-checkout-wpcom/src/components/wp-order-review-line-items.js
This modifies domain products (registrations, transfers, mapping, and redirects) so that instead of just displaying the product name or just the domain name, we display both.
**Before**
**After**
- Try adding a domain registration, a domain transfer, a domain mapping, and a site redirect to your cart (or test each one individually).
- Visit composite checkout.
- Click through to the review step (step 3).
- Verify that you see both the product name and the domain name.
> composite-checkout: Display both title and domain for domain products

- client/my-sites/checkout/checkout/checkout-system-decider.js
This is a reprise of #40181 which was reverted in #40188
This PR modifies `CheckoutSystemDecider`, which determines which checkout to show (regular or composite checkout) based on various factors, so that it will allow domains and domain related products (domain mapping, domain transfers). Users will still have to pass the `abtest` config or enable the `composite-checkout-testing` flag (which remains enabled on Horizon).
Note that _adding_ domain products via URL (I think this only applies to domain mapping with a path like `/checkout/example.com/domain-mapping:example.com`) is _not_ enabled by this change; such paths will still redirect to regular checkout. That change will need to be done separately because we need to be absolutely sure that we handle all possible product adding paths …
> Allow domains, domain products in the cart for composite checkout

- client/landing/jetpack-cloud/components/date-picker/index.jsx
- client/landing/jetpack-cloud/sections/backups/main.jsx
Add the ability to limit the browse to previous dates passing to the DatePicker component the oldest date available.
Other minor improvements.
- Check that everything works as before
- Check that we can't browse more than March 1st (date hardcoded for testing purpose)
> Add the ability limit the browse to previous dates on DatePicker

- client/landing/gutenboarding/onboarding-block/style-preview/index.tsx
- config/wpcalypso.json
This is a quick first pass to enable the style picker. We should remove the style-picker specific feature flag entirely.
Anyone, feel free to rebase this often to keep it up to date. It's a handy way to preview the style pickers via calypso.live.
* Enable Gutenboarding style picker.
* [`/gutenboarding`](https://calypso.live/gutenboarding?branch=update/enable-gutenboarding-style-picker)
* After picking a design, you'll be presented with the font preview screen on [calypso.live](https://calypso.live/gutenboarding?branch=update/enable-gutenboarding-style-picker).
> Gutenboarding: Enable style picker

- client/landing/gutenboarding/onboarding-block/design-selector/index.tsx
- client/landing/gutenboarding/onboarding-block/design-selector/style.scss
* Use CSS grid for layout.
* Animate with `react-spring`.
* Remove that outline
* Remove selected design styling. When style picker is enabled, we'd proceed to that step.
(no focus style)
* [`/gutenboarding`](https://calypso.live/gutenboarding?branch=fix/40320-gutenboarding-design-outline)
* Go to the design picker step
* It's beautiful 💅 
* Hover tab works well 
Fixes #40320
> Gutenboarding: Rework design picker styling

- client/assets/stylesheets/shared/functions/_z-index.scss
- client/blocks/inline-help/index.jsx
- client/blocks/inline-help/style.scss
This updates the position of Inline Help to the one suggested by @dwolfe:
> Could we just position this window as we do on desktop, just above the help button with a caret pointing to the button? That would be an ergonomic improvement, and also create a stronger association with its trigger.
Verify that Inline Help still loads correctly in a similar fashion to how it does on desktop devices.
**Before:**
**After:**
cc @sixhours, @spen  
Fixes #38092
> Inline Help: Lower Position on Mobile

- apps/full-site-editing/full-site-editing-plugin/site-editor/index.php
Exposes Site Editor as top level wp-admin menu item and allows it to boot in that context.
Local testing:
1. Change the filter [here](https://github.com/Automattic/wp-calypso/blob/c017679608b650cd12e529e4947148e252b819fb/apps/full-site-editing/full-site-editing-plugin/site-editor/index.php#L96) to return true, since Site Editor is disabled by default.
2. Verify that the Site Editor item is present in the menu and that the editor loads.
Sandbox testing:
1. Sync plugin changes to your sandbox.
2. Make sure that the test site has `gutenberg-edge` sticker applied.
3. Verify that the Site Editor item is present in the menu and that the editor loads.
> Site Editor: move to top level menu item

- client/landing/gutenboarding/components/signup-form/index.tsx
- packages/data-stores/src/user/actions.ts
- packages/data-stores/src/user/reducer.ts
- packages/data-stores/src/user/test/actions.ts
- packages/data-stores/src/user/test/reducer.ts
- packages/data-stores/src/user/test/resolvers.ts
- packages/data-stores/src/user/types.ts
Previously, in Gutenboarding if you go to create a new user, receive an error message, and then close the modal, when you re-open the modal, the old error message still exists even though the form is empty.
This PR clears the error messages when the form is closed, and adds in tests for the user data store. Here's an example of it working (please ignore the unrelated error in the preview in the `style` step):
* Clear the `newUserError` state when the signup form is closed
* Add test coverage to the user data store to cover the main actions, resolver and reducers.
You probably don't need to run these manually since they're already run by CI, however you can run them from the terminal with:
```
npm run test-packages ./packages/data-stores/src/user/test/
```
In a fresh or incognito / private …
> Gutenboarding: clear errors when signup form is closed, add tests to user data store

- client/landing/gutenboarding/components/header/index.tsx
- client/landing/gutenboarding/stores/onboard/actions.ts
- client/landing/gutenboarding/stores/onboard/index.ts
- client/landing/gutenboarding/stores/onboard/reducer.ts
- packages/data-stores/src/auth/actions.ts
- packages/data-stores/src/auth/controls.ts
- packages/data-stores/src/user/actions.ts
- packages/data-stores/src/user/test/actions.ts
- packages/data-stores/src/wpcom-request-controls/index.ts
The domain flow (creating a site by choosing a premium domain from the domain picker) is broken. The site gets created the subsequent calls to the shopping cart API fail.
Changes:
* Reload proxy after signing up with a new account
We had been getting away using the bearer token returned in the signup response to make API calls, however the calls to the shopping cart API in the domain flow are using cookie authentication, and reloading the proxy gets the required cookies
* Re-request access to all blogs after reloading the proxy
The token given to the proxy isn't "global", it doesn't have access to all the users sites. This was blocking the domain flow from getting info about the shopping cart for the newly created site
* Move `isDomainFlow` state to store to persist in local storage
If …
> Gutenboarding: fix domain flow, request all blog access after reloading proxy

- client/sections-filter.js
- client/state/sites/selectors/is-site-previewable.js
*  This PR disables the view site page in for the Jetpack Cloud unless the preview section is enabled. 
* Load up calypso `npm start` notice that view page for .com sites takes you to 
`/view/siteSlug`
* Load up Jetpack Cloud notice that view Site takes you to the site url. 
Fixes the broken flow that leads to a 404 page now.
> Jetpack Cloud: Disabled is-site previewable

- client/assets/stylesheets/shared/functions/_z-index.scss
- client/components/chart/bar.jsx
- client/components/chart/index.jsx
- client/components/chart/style.scss
- client/my-sites/stats/stats-chart-tabs/index.jsx
Hi there! This is just micro PR to get me familiar with Calypso and the development process. 
1. To use CSS `transform` to adjust the chart bars instead of `top` and `height`. Using `transform` prop usually isolates the element into another rendering layer, allowing it to re-render without reflowing the rest of the DOM => much faster. Although this is up to each browser.
2. This gives the ability to add a transition since transitioning is now efficient enough.
3. Not 100% sure about this one. But since height is 100% now, I don't think a spacer element is needed. Unless it had another purpose. 
4. Make bars start from 0% as opposed to 100%. This solves the ugly intermediate state seen [here](https://d.pr/i/PgXChH).
1. Video before: https://d.pr/v/3bMGUS
2. Video after: …
> Animate Chart: use CSS transform instead of top/height combination for better performance

- packages/composite-checkout-wpcom/src/components/summary-details.js
- packages/composite-checkout-wpcom/src/components/wp-contact-form.js
This adds the optional contact form fields for domains (organization, address2, alternate email) and phone number to the contact details summary.
Fixes #40448 
Before | After
**To test:**
- add a domain to your cart
- visit Checkout (with `?flags=composite-checkout-testing`)
- under "Contact information" fill out all of the fields
- submit the step
- verify that all submitted fields are displayed in the step summary
> New Checkout: add missing fields to contact information summary

- client/state/checklist/reducer.js
Photon feature toggles are always showing an error when used, even though they actually issued a working API request:
This PR fixes that so that you can use them again:
1. Get a Business plan site, install a plugin
1. Go to settings > performance and confirm photon toggles are functional
> [Jetpack] Don't show an error after successfully toggling photon features

- client/lib/abtest/active-tests.js
Requires:  #40380
This bumps the test date for the `showCompositeCheckout` test, now that domains support has been added to Composite Checkout in #40380.
Fixes: #40222 
**To Test:**
A visual check that the date matches the current date should suffice. The test is already active for non-domain purchases and the gating is being updated in #40380.
> AB Test: bump `showCompositeCheckout` test date

- client/landing/jetpack-cloud/components/fix-all-threats-dialog/index.tsx
- client/landing/jetpack-cloud/components/fix-all-threats-dialog/style.scss
- client/landing/jetpack-cloud/components/scan-threats/index.tsx
- client/landing/jetpack-cloud/components/scan-threats/style.scss
- client/landing/jetpack-cloud/components/server-credentials-form/index.jsx
- client/landing/jetpack-cloud/components/server-credentials-form/style.scss
- client/landing/jetpack-cloud/components/threat-item/index.tsx
- client/landing/jetpack-cloud/components/with-server-credentials-form/index.jsx
- client/landing/jetpack-cloud/components/with-server-credentials-form/test/index.js
- client/landing/jetpack-cloud/sections/scan/main.jsx
- client/landing/jetpack-cloud/sections/scan/style.scss
- The goal of this is to create the Threat Card used on the main screen when threats are found.
We are not checking if the provided credentials are valid. We move the user to next step in the progress regardless of the result. This is for testing purposes only.
- Navigate to http://jetpack.cloud.localhost:3000/scan/<yourSiteSlug>?scan-state=threats
- Click the "Open Fix All Threats Dialog" button
See 1151678672052943-as-1165787355206381.
> Jetpack Cloud: Create Fix all threats - add credentials modal

- client/lib/abtest/active-tests.js
- client/lib/plans/plans-list.js
- client/my-sites/plan-features/style.scss
* Restarting a test with a minor copy modification.
*  Go through the signup flow at /start.
* When in the control group of the `planStepCopyUpdates` test, verify that you see the unchanged plan step UI version
* When in the variant group, verify that you see the updated UI that matches with the screenshot above, particularly the "billed anually" part.
* Verify that the plans page in Calypso /plans, and the plans step shown in launch flow of private sites both do not show the new UI.
> Restarting Plan step test

- client/my-sites/customer-home/cards/features/grow-earn/index.jsx
- client/my-sites/customer-home/cards/features/grow-earn/style.scss
- client/my-sites/customer-home/main.jsx
- client/my-sites/customer-home/style.scss
This PR moves the Grow & Earn card to its own component, in preparation for cards being displayed according to server-side logic. This continues the work in #40368 . No visual or behavioural changes should occur.
*  Load this branch, and go to `/home/:site` for a site that is launched and has a complete checklist.
* Verify it visually looks the same in production (load the same route on `wordpress.com`).
* Check the card links, and verify that stats fire.
> My Home: Refactor Grow and Earn into its own component.

- client/my-sites/domains/components/domain-warnings/index.jsx
* Average user probably doesn't know what DNS means right off. We can make this language more user-friendly with a quick copy update.
**Before**
**After**
* Switch to this PR.
* Add a subdomain to a domain that is not yet set up properly. You can add any random domain to an account to do this (and just don't set up any DNS for it).
* Note the copy changes.
Fixes #39939
> Domains: Update DNS setup required language to be more user-friendly

- client/landing/jetpack-cloud/components/backup-delta/index.jsx
- client/landing/jetpack-cloud/components/backup-delta/style.scss
- client/landing/jetpack-cloud/sections/backups/main.jsx
- client/landing/jetpack-cloud/sections/backups/utils.js
* Brings the BackupDelta component into functional spec
* Brings the BackupDelta component into rough design spec (will improve CSS methodologies later if needed)
Note: These changes are only for  **daily** backup views.
Load up the backups page for a date/site which has various types of changes, including post creation/deletion, media upload/deletion, plugin installation/removal, theme installation/removal.
**Some general things to look at:**
* The entire BackupDelta section should only appear for days that have a change of some sort.
* Media changes should look sensible and reflect what happened on the site, including an accurate count in the "bubble" below the media.
* Edited/deleted posts should appear in the list
* Themes/plugins that were installed/deleted should appear in the list, …
> Jetpack Cloud: Update styling and functionality of the BackupDelta component

- apps/wpcom-block-editor/src/calypso/features/iframe-bridge-server.js
- client/state/selectors/get-editor-close-config.js
- client/state/selectors/test/get-editor-close-config.js
* The site editor close button in the iframe currently leads to wp-admin, lets make this go back to calypso!
With this change, the close button will follow the priority of conditions as found in `get-editor-close-config.js` listed in the changed files here.  That is, if we opened the site editor from being on the checklist, home, or themes page, then we will return to those pages respecively.  If the site editor is opened from none of the above, its default is now `/view/$siteSlug`.
Perhaps there is a better default for the site editor to return to than the "veiw" screen, but the current default before this change would be `/$postType/$siteSlug` which for the site editor would be `/undefined/$siteSlug` since postType DNE in the context of the Site Editor.
* Run this PR on local calypso …
> Fix url for iframed Site Editor close button.

- apps/wpcom-block-editor/src/wpcom/features/fix-block-invalidation-errors.js
In pbAok1-u4-p2, we discussed how certain invalid blocks can make the block auto-fix mechanism replace several blocks with empty content. This PR fixes that by checking for block content in certain commonly used blocks.
Since we don't have a way to check if an arbitrary block has content, we are simply fixing this for some common cases -- particularly the paragraph block, which is the biggest offender.
1. Apply D40869-code to your sandbox and then sandbox widgets.wp.com and a test site.
2. Paste the following content into the "code editor" of the test site
```
<p>test paragraph 1</p>
<p>
</p>
<p>test paragraph 2</p>
<p>
</p>
<figure class="wp-block-image size-large"><img src="https://www.cbronline.com/wp-content/uploads/2016/06/what-is-URL-770x503.jpg" alt=""/></figure>
<p>
</p> …
```
> Only autofix blocks which have content

- client/my-sites/customer-home/cards/features/launch-site/index.jsx
- client/my-sites/customer-home/cards/features/launch-site/style.scss
- client/my-sites/customer-home/main.jsx
- client/my-sites/customer-home/style.scss
This PR moves the Launch Site card to its own component, in preparation for cards being displayed according to server-side logic. This continues the work in #40368 . No visual or behavioural changes should occur.
*  Load this branch, and go to `/home/:site` for a site that has not been launched (or just create a new site).
* Verify it visually looks the same in production (load the same route on `wordpress.com`).
* CLick the Launch Site button, and verify it works as expected.
> My Home: Refactor Launch Site card.

- client/my-sites/pages/page-list.jsx
- client/my-sites/pages/page/index.js
- client/state/posts/utils/normalize-post-for-display.js
- config/development.json
- config/stage.json
This PR adds an option to the page list dropdown that allows you to export the page as a json file, in the same format that core allows to export reusable blocks. 
This will make it much easier for page template creators to save them as files we can use.
How to test
======
0. Pick any of your sites, go to your pages list
1.In any of the pages, click on the ellipsis menu and then 'export'
2. You should get a json file with this format:
```
{
__file: 'wp_template',
language: 'en',
title: page.title,
content: page.content,
}
```
> Page exports

- apps/full-site-editing/bin/sync-blog-posts-block.sh
On macos, `sed -i` requires a backup file parameter: `sed -i ""`. However, on linux platforms, `sed -i ""` fails (the syntax for specifying that parameter is different). On linux, it needs to be `sed -i`. Since the script failed on Linux, the `npm ci` command which happens in the docker build fails, since docker is using a linux image under the hood. This was not detected because this script was not being automatically run during `npm ci` until #39196. Everyone who ran it locally must have been using macOS.
See p1585149819004800-slack
Adds a compatibility check for the sed command so that the script works on both platforms. (see https://stackoverflow.com/a/51060063)
1. Delete the `apps/full-site-editing/full-site-editing-plugin/blog-posts-block/newspack-homepage-articles` directory.
2. …
> Fix BPB sync script compatibility

- apps/full-site-editing/full-site-editing-plugin/full-site-editing-plugin.php
- apps/full-site-editing/full-site-editing-plugin/readme.txt
- apps/full-site-editing/package.json
* FSE version bump.
* Update FSE Changelog.
* Make sure that G2 compatibility is working.
* Go through [this list](https://github.com/Automattic/wp-calypso/commits/master/apps/full-site-editing) and make sure stuff works.
> Update FSE to version 0.26

- apps/full-site-editing/full-site-editing-plugin/site-editor/index.php
* New sites created result in a blank screen for the Site Editor as noted in #40497 .  This is due to the option not being initialized.
* Create a new WP.com test site.
* Add `gutenberg-edge` (we need v7.8.0) and `core-site-editor-enabled` stickers to it.
* Sync FSE plugin from this PR.
* Navigate to test site's wp-admin or Calypso.
* Verify the Site Editor loads properly.
Fixes #40497
> Site Editor: changed to pre_option hook

- client/landing/gutenboarding/devtools.ts
- packages/data-stores/src/auth/actions.ts
- packages/data-stores/src/auth/constants.ts
- packages/data-stores/src/auth/controls.ts
- packages/data-stores/src/auth/reducer.ts
- packages/data-stores/src/auth/selectors.ts
- packages/data-stores/src/auth/test/actions.ts
- packages/data-stores/src/auth/test/flows.ts
- packages/data-stores/src/auth/types.ts
- packages/data-stores/src/auth/utils.ts
- packages/data-stores/src/wpcom-request-controls/index.ts
- packages/data-stores/tsconfig.json
* Add support for "push" 2nd login factor
* Polls ever 5 seconds to see if push notification has been handed (this is the poll time currently used by `/log-in`)
* Add `downlevelIteration` to TS config so we can use `yield*` in generator functions
* Every time we poll update the nonce that we'll use for the next time we poll
"Push" means when we send a push notification to the WordPress app during login, and you click the button in the app to approve the login. Not the one where you have to end a code for the 2nd factor.
* Checkout branch locally
* Install WordPress app on phone (I found I needed to enable notifications for the app, can always disable later 😄)
* In console:
* `wp.auth.submitUsernameOrEmail('username')` using an account that's logged into the mobile app
* …
> Gutenboarding: Add push 2fa support to auth store

- client/landing/gutenboarding/components/header/index.tsx
- client/landing/gutenboarding/components/signup-form/index.tsx
- client/landing/gutenboarding/devtools.ts
For now we're going to rely on the frankenflow login UI. That means we no longer need the login UI that's embedded in gutenboarding (for now). The
* Remove the "(experimental login)" link from the signup form
* Remove code that links in the login UI so it's no longer included in the bundle
* Remove auth store from devtools so it's no longer included in the dev bundle
* Choose site vertical and title
* Open domain picker and choose a premium domain
* Click "Create your site and register your new domain"
* See that "(experimental login)" link is gone
* Close modal and complete gutenboarding flow
* In the "save your progress" modal at the end see that the "(experimental login)" link is gone
> Gutenboarding: Remove experimental login link from signup form

- client/landing/gutenboarding/components/confirm-purchase-modal/index.tsx
* The confirm purchase modal for domain registration incorrectly displayed the `Create an account` line if you were logged in, and not if you aren't logged in.
* Go to `http://calypso.localhost:3000/gutenboarding` while ***logged out***, enter a topic and a title and select a paid domain.
* In the modal, confirm you can see the `Create an account` line as below:
* Go to `http://calypso.localhost:3000/gutenboarding` while ***logged in***, enter a topic and a title and select a paid domain.
* In the modal, confirm that the `Create an account` line is not present.
> [Gutenboarding] Fix display of create account item to only show when not logged in

- client/my-sites/site-settings/settings-performance/main.jsx
- client/my-sites/site-settings/speed-up-site-settings.jsx
- client/state/selectors/is-jetpack-module-active.js
VideoPress files are public so it makes sense to make VideoPress unavailable when the site is Private:
**Before**:
**After**:
1. Test locally, this won't work on calypso.live.
1. Create a new site and go atomic - it's going to be private by default.
1. Don't launch it.
1. Go to `/settings/performance/` and confirm it looks like on the *first* screen above.
1. Click the "Continue" button, confirm the photon and videopress are now available. 
1. Make the site private again.
1. Go to `/settings/performance/` and confirm it looks like on the *second* screen above.
1. Try with Jetpack and Simple sites. Confirm the eligibility gate is never displayed for these.
1. Follow the test plan on #39527 and confirm it keeps working
1. Create a new site, go Plugins -> Upload, confirm the eligibility gate …
> [Private sites] Hide VideoPress switch on private atomic sites

- client/my-sites/customer-home/cards/education/free-photo-library/style.scss
The video was moved into the support document in #40257, so the separate video styles are no longer necessary (or having any effect)
Verify the `free-photo-library__demonstration-video` class isn't present anywhere: https://github.com/Automattic/wp-calypso/search?q=free-photo-library__demonstration-video&unscoped_q=free-photo-library__demonstration-video
cc @kwight, @gwwar
> Customer Home: Removed Unused Photo Library Card Styling

- client/my-sites/checkout/cart/cart-item.jsx
The original cost displayed in the checkout (i.e. cost before the coupon is applied) is juxtaposed against the actual cost (i.e. cost after the discount is applied, and volume of licences) to highlight the discount.
The volume is not integrated into the original cost, making the checkout display confusing to customers when the number of licences exceed one.
* The volume of licences is multiplied by the cost before the coupon is applied, to produce a figure that is appropriately comparable to the actual total cost.
*Before*
* Add a G Suite product into the cart with multiple licenses
* Observe that the original cost isn't a multiple of the number of licences
*After*
* Checkout this branch i.e. [`fix/gsuite-wrong-display-of-discount-in-checkout-for-multiple-licenses`](fix/gsuite-wrong-displa …
> G Suite: Fix the checkout display by integrating the number of licenses into the original product cost for comparison against the discount

- client/my-sites/customer-home/cards/features/support/index.jsx
- client/my-sites/customer-home/cards/features/support/style.scss
- client/my-sites/customer-home/main.jsx
- client/my-sites/customer-home/style.scss
This PR moves the Support card to its own component, in preparation for cards being displayed according to server-side logic. This continues the work in #40368 . No visual or behavioural changes should occur.
- Load this branch, and go to `/home/:site`.
- Verify it visually looks the same in production (load the same route on wordpress.com).
- Check the card links, and verify that stats fire.
> My Home: Move Support into its own component

- client/my-sites/customer-home/locations/upsells/index.jsx
- client/my-sites/customer-home/locations/upsells/style.scss
- client/my-sites/customer-home/main.jsx
- client/my-sites/customer-home/style.scss
This PR moves the upsells location to its own component, in preparation for cards being displayed according to server-side logic. This continues the work in #40368. 
This location only contains one card (the stats banners) which is already in a separated component, so this PR doesn't move any card, just the location.
No visual or behavioural changes should occur.
- Load this branch, and go to `/home/:site` for a business site that was created more than 2 days ago and without a Google My Business connection currently active.
- Verify it visually looks the same in production (load the same route on wordpress.com).
- Note that the CTA button could use the default styling locally but the primary one in production. This is unrelated to this PR and caused by the `StatsBanner` not being …
> Home: Move upsells location into its own component

- client/landing/gutenboarding/onboarding-block/design-selector/available-designs.json
- client/landing/gutenboarding/onboarding-block/design-selector/index.tsx
- client/landing/gutenboarding/onboarding-block/style-preview/preview.tsx
- client/landing/gutenboarding/onboarding-block/style-preview/style.scss
- client/landing/gutenboarding/stores/onboard/types.ts
This PR updates the metadata of the designs available for gutenboarding and changes the design picker and the style preview steps to work with that format.
How to test:
========
0. Go to calypso.localhost:3000/gutenboarding
1. Enter a vertical and a site title
2. In the design selector screen, you should see 10 different designs
3. Once you are in the preview step, the design should be visible
4. Check the mobile & tablet versions: The scroll bars shouldn't be visible there
> Gutenboarding: Use new designs, fix previews

- client/my-sites/domains/domain-management/edit/domain-types/mapped-domain-type.jsx
- client/my-sites/domains/domain-management/edit/style.scss
This PR fixes a spacing issue on the domain mapping status message.
**Before**
**After**
- Get calypso running locally or visit calypso.live
- Find a mapped domain that hasn't updated it's name servers to point to us.
- Append this string to the end of the url: "?flags=domains/new-status-design"
- Confirm the space under the list matches the space above it.
> Fix spacing on name server list

- client/blocks/upgrade-nudge/style.scss
- client/blocks/upsell-nudge/style.scss
* Adds a border and box shadow hover effect on UpgradeNudges (without calls to action) to match Banners.
* This came up in #40300 and I'm splitting it into a separate PR to keep that one simpler in case we have to revert it.
**Before**
**After**
* Switch to this PR on a Free site
* Navigate to the Marketing screen. Hover over the upsell nudge to see the effect.
* Check other pages to look at examples of the same component: Media -> Audio, Media -> Video, Settings -> Writing -> Podcasting Setup, and probably many more!
> Upgrade Nudge: Add hover effect like Banners for consistency

- client/my-sites/theme/main.jsx
This hides the misleading upsell banner for retired themes
There is a wider question being addressed in #40310 on whether or not they should be advertised; technically, yes, purchasing a Premium plan would allow retired themes to be accessed in WP-admin. But as @lancewillett puts it:
> We should do everything we can to hide them and discourage their use.
* Visit the page of a retired theme (eg. `/theme/ladder`) and verify the upsell banner no longer appears.
cc @mendezcode, @sixhours 
Fixes #40475
> Themes: Hide Upsell Banner for Retired Themes

- client/my-sites/plans/current-plan/current-plan-thank-you/search-thank-you.js
- client/my-sites/plans/current-plan/current-plan-thank-you/style.scss
- client/my-sites/plans/current-plan/current-plan-thank-you/thank-you.js
- client/my-sites/plans/current-plan/index.jsx
* Adapt a copy and redirects within the Thank you modal displayed in the post-checkout step of the Jetpack Search product purchase.
* go to `/plans` for a JP connected site on a non-Professional plan
* purchase Jetpack Search, pass the checkout step
* verify that the Thank you modal appears and the copy is correct
* verify the redirects to the customizer and Jetpack dashboard within `WP-Admin`
Fixes https://github.com/Automattic/wp-calypso/issues/40434 
Sequel: add tracking
> Jetpack Search: adapt post-checkout modals

- client/landing/jetpack-cloud/components/daily-backup-status/index.jsx
- client/landing/jetpack-cloud/components/date-picker/index.jsx
- client/landing/jetpack-cloud/sections/backups/main.jsx
- client/landing/jetpack-cloud/sections/backups/utils.js
Adapt the DailyBackupStatus to use the backup for the selected date passed from BackupsPage. We apply the time zone of the site to the backup date and also the right format according to design.
**Note:** No styles applied.
(see the animation attached)
1. Check if the display backup date-time is the expected on the site time zone
2. Set another time zone for your site and check again (1) if the backup date-time matches with the selected time zone.
Bonus:
1. If you don't have backup performed from today, check the expected copy
2. If you have a day with a failed backup, check the expected copy
> Update DailyBackupStatus to use the backup from date selected + timezone

- client/lib/media/test/utils.js
- client/lib/media/utils.js
- client/my-sites/media-library/media-file.tsx
While new files are being uploaded, we attempt to display their preview using `blob:<ID>` URL. At the moment this URL is getting passed to `<ProxiedImage />` which isn't meant to handle blobs. This diff makes sure blobs are rendered as regular unproxied images. 
On private atomic site go to /media and upload a large image. Confirm the preview is visible during the upload. Confirm in network tab that browser didn't request an endpoint like `/atomic-auth-proxy/filehttps://wordpress.com/<blob id>`
> [Private files] Don't use proxy with blobs

- client/blocks/upsell-nudge/style.scss
* At some point while I was working on this, I thought UpsellNudge might use the same dark background color scheme as it uses in the sidebar/compact style. That's not the case, so this makes the CSS more specific, so dark colors only apply to the compact/sidebar nudge.
**Before**
**After**
* Navigate to a site with an active JITM (this one appears when you have an account with a CA country code)
* You should see the corrected nudge styles.
> Upsell Nudge: Only use darker color scheme for sidebar nudges.

- client/landing/gutenboarding/onboarding-block/acquire-intent/site-title.tsx
- client/landing/gutenboarding/onboarding-block/acquire-intent/vertical-select/index.tsx
This PR makes the arrow only appear in the clean-slate state. If you have any input in the vertical or in the site title, a dot will appear instead. 
See the live link below. The arrow should only appear during the first entry of the site vertical.
Fixes part of #40321
> Simplify vertical-selection arrow appearance conditions

- client/me/purchases/manage-purchase/plan-details/billing-period.jsx
- client/me/purchases/manage-purchase/plan-details/index.jsx
- client/me/purchases/manage-purchase/plan-details/test/billing-period.jsx
- client/me/purchases/manage-purchase/plan-details/test/index.jsx
Reported in 3876-gh-jpop-issues
* When the user has a monthly plan but Jetpack is disconnected, the button to upgrade to a Yearly plan will be hidden and a text asking the user to reconnect will appear
* Connect a Jetpack site to your account using a monthly plan
* Go to the Site Settings and disconnect the site
* Go to /me/purchases and click on your Jetpack Plan
* The "Upgrade to yearly billing" button will appear
* Click the button and you will be redirected to the Site Selector, since the Jetpack site was disconnected.
* The legend "Billed monthly" will appear, with no buttons next to it.
* The message "To manage your plan, please reconnect your site." with a link to Jetpack support will be displayed below.
* Connect a Jetpack site to your account using a monthly plan
* Go to …
> Manage Plans: Hide billing period changes on disconnected sites

- client/blocks/upgrade-nudge/style.scss
- client/components/banner/index.jsx
- client/components/banner/style.scss
Globally update upsell nudges (no matter their underlying component) to use a static color and icon for consistency.
* Swap out individual plan colors for the primary accent color across all color schemes
* Swap out plan icons for the star icon, and make star the default icon
* Update `UpsellNudge` to reflect these changes as well.
**Before** (a sampling, not every instance)
**After**
* Switch to this PR 
* Using a Free site, navigate around Calypso and look at upsell nudges. There are lots, so here are some of the best performing nudges to test:
- Media library: Upload video
- Media library: Upload audio
- Stats: Insights tab, halfway down the page
- Old editor (non Gutenberg): Add a Simple Payments button
- Podcasting settings
- Domains page: Banner to personal nudge
* I know of more …
> Upsell Nudge: Swap plan colors for accent color, swap info icon for star icon

- client/jetpack-connect/constants.js
- client/jetpack-connect/controller.js
- client/jetpack-connect/main.jsx
- client/jetpack-connect/test/__snapshots__/main.js.snap
* This adds a query param to force a remote installation of Jetpack when it is not connected.
Linked to https://github.com/Automattic/jetpack/pull/15124.
* Create a Jetpack site that is not connected.
* Navigate to `/jetpack/connect?url=[sitename]&forceInstall=1`
Observe Calypso query site and jump to remote install screen.
Fixes 1164141197617539-as-1164522491999689.
> Adds query param to force a remote installation

- client/lib/cart-values/cart-items.js
- client/lib/cart-values/test/cart-items.js
* Jetpack Backup plans can't be renewed directly within the Manage Purchases page. This PR will fix this issue for both Jetpack Backup and Jetpack Search.
* Buy a Jetpack Backup plan for a site.
* Go to the Manage Purchases page
* Click on the Jetpack Backup product.
* Click on "Renew Now"
* Nothing happens, if you open the Developer Console an error ("This product cannot be renewed") is logged each time you click the button.
* You are redirected to the Checkout page, the Jetpack Backup product will appear in your Order Summary.
* Complete the purchase and you will see that the expiration will be increased successfully.
> Manage Plans: fix Renew Now button for Jetpack products

- client/landing/gutenboarding/components/modal-submit-button/style.scss
- client/landing/gutenboarding/components/signup-form/header.tsx
- client/landing/gutenboarding/components/signup-form/index.tsx
- client/landing/gutenboarding/components/signup-form/style.scss
- client/landing/gutenboarding/mixins.scss
* Restyle signup form in Gutenboarding to match current Figma
* Add additional mixins to cover most of the common text sizes
Note: it is yet to be determined whether or not a password field is required, so I've left it off for the time being and just focused on styling in this PR.
Also note, that due to how the Modal component works, I've had to use `display:none` on the standard header that's included in the modal, and add our own custom header component. This is slightly hacky because there are technically two header components being mounted. My hope is that `display:none` is a suitable workaround to avoid writing our own modal from scratch, since the `wordpress/components` has some nice affordances.
* From a logged out session, go to `http://calypso.localhost:3000/gutenboarding and …
> [WIP] Gutenboarding: restyle SignupForm to match current designs

- client/landing/gutenboarding/components/header/index.tsx
- client/landing/gutenboarding/components/header/style.scss
Some more header cleanup, also matches the figma a little better.
**before**
**after**
http://calypso.localhost:3000/gutenboarding
> Gutenboarding: Some more header/style adjustments

- client/landing/jetpack-cloud/components/date-picker/index.jsx
- client/landing/jetpack-cloud/sections/backups/main.jsx
When we switch the section and return again to BackupsPage, the backup on the selected date (today) is not in the correct state. To fix it we:
- Removed the backupOnSelectedDate state. It wasn't necessary, we can get it from the props through a method.
- Applied the time zone to some of the dates that should have it applied.
- Ensure that we always work with Moment to preserve the time zone.
- If you have a backup from today (you should see it), switch to another section (like Scan) and switch again to the Backup section, you should see the backup of today again.
- Check if everything works as before (navigating through the dates)
> Fix error when we switch the section, remove backupOnSelectedDate state

- client/landing/gutenboarding/constants.ts
- client/landing/gutenboarding/gutenboard.tsx
- client/landing/gutenboarding/onboarding-block/style-preview/font-select.tsx
- client/landing/gutenboarding/onboarding-block/style-preview/index.tsx
- client/landing/gutenboarding/onboarding-block/style-preview/preview.tsx
- client/landing/gutenboarding/stores/onboard/actions.ts
- client/landing/gutenboarding/stores/onboard/index.ts
- client/landing/gutenboarding/stores/onboard/reducer.ts
- packages/data-stores/src/site/types.ts
* Send `template` (duplicated from design at the moment), `font_headings` and `font_base` in the site creation API request.
Includes #40591
Part of #40513
* [`/gutenboarding`](https://calypso.live/gutenboarding?branch=gutenboarding/include-font-in-api)
* Follow the flow and pick a custom font pair
* Open the network debug tab and ensure that `font_headings` and `font_base` are included in the request.
* Ensure that with no custom font pair, the flow continues to work well and the site creation request works as expected (don't send font_* in request)
> Gutenboarding: Create site with fonts

- client/server/pages/index.js
* In D33549-code, we are redirecting all en.wordpress.com URLs to wordpress.com, as part of a larger effort described in pau2Xa-fv-p2.
* Without the change in this PR, visiting https://wordpress.com/tag/a8cgm will redirect to https://en.wordpress.com/tag/a8cgm (from [this line](https://github.com/Automattic/wp-calypso/blob/a1465c083a1d20f9f7c563ed71f306367d39bd98/client/server/pages/index.js#L726)), then again redirect from en.wordpress.com to wordpress.com from the changes in the D33549-code, and an infinite redirect loop gets established. 
* Verify code looks okay.
> Remove redirect to en.wordpress.com to prevent an infinite redirect loop

- apps/full-site-editing/full-site-editing-plugin/global-styles/index.js
- apps/full-site-editing/full-site-editing-plugin/global-styles/src/dom-updater.js
- apps/full-site-editing/full-site-editing-plugin/global-styles/src/store.js
Currently, when a user selects a different Global Style, the changes are not immediately reflected in the Block Example and Block Patterns previews.
This is caused by the relevant Global Styles styles being applied inline in the editor. This way they only apply to the main editor instance but not the preview instances. The solution suggested in this PR is to still scope the styles to the same selector but instead of adding them inline adding them to a stylesheet. This way the styles apply to all editor instances including previews.
Fixes https://github.com/Automattic/wp-calypso/issues/40467 and https://github.com/Automattic/wp-calypso/issues/40353
(- Select a Varia based theme)
- Create a new post
- Check the visual style of Block Example for Headline and visual style of Block Patterns
- …
> Global Styles: fix previews not showing global styles

- client/my-sites/activity/activity-log-tasklist/index.jsx
- client/my-sites/activity/activity-log-tasklist/update.jsx
* Decode plugin/theme name on the Activity Log update cards
* Also decode them on a updating, successful or failure update notification
- Install an **older version** (you can get it on the plugin's advanced view list on dotorg repo) plugin that has a character like `&`. Example: [Coming soon](https://wordpress.org/plugins/coming-soon/advanced/).
- Visit your Activity Log - https://wordpress.com/activity-log using the Calypso live branch below
- Ensure that `&` appears as is. It must not be encoded.
Here are a few screenshots of how they look with the fix:
Fixes https://github.com/Automattic/wp-calypso/issues/35667
> Decode names in Activity Log updates

- client/lib/abtest/active-tests.js
- client/lib/signup/step-actions/index.js
- client/my-sites/checkout/checkout/secure-payment-form.jsx
- client/my-sites/plan-features/index.jsx
- client/my-sites/site-settings/form-general.jsx
- client/state/selectors/should-new-site-be-private-by-default.ts
- config/development.json
- config/stage.json
- config/wpcalypso.json
**Description**
Current way of having this feature enabled only in certain environments is making it harder to test as certain links will always redirect to root WordPress.com site. This PR makes it easy to enable and disable the feature by using A/B test picker.
**Test plan**
1. Assign yourself to variant of ATPrivacy
1. Create a new simple site
1. Go to plugin installation screen and check eligibility warnings
1. Go to settings, confirm there were no errors
1. Go atomic, confirm it worked, 
1. Repeat steps 3 and 4
1. Assign yourself to control
1. Repeat steps 2-6
> Coming Soon: use A/B test for gating

- client/my-sites/checkout/checkout-thank-you/domain-registration-details.jsx
- client/my-sites/domains/components/domain-warnings/index.jsx
- client/my-sites/domains/components/domain-warnings/test/index.js
- client/my-sites/domains/domain-management/list/domain-only.jsx
- client/my-sites/domains/domain-management/list/index.jsx
This PR updates messaging for new domain registrations, to indicate that domains may be unreliable for 30 minutes, instead of the previous 72 hour period.
Sample screenshots:
Verify that the correct message (30 minutes) is displayed in the domain settings for each of the scenarios listed below:
- Two or more newly purchased domains
- Primary domain is a new domain
- Primary domain is an old domain, or the default free subdomain
- Only one newly purchased domain
- Primary domain is the new domain
- Primary domain is an old domain, or the default free subdomain
- Domain only purchase
Also ensure the message won't be displayed for domains purchased more than 30 minutes ago, and that the correct message is displayed in the post checkout page.
> Domains: Update messaging and timing for new domains setup period

- client/landing/gutenboarding/gutenboard.tsx
- client/landing/gutenboarding/onboarding-block/acquire-intent/style.scss
- client/landing/gutenboarding/onboarding-block/style.scss
- client/landing/gutenboarding/style.scss
- set margins for desktop (88px) and mobile (20px) as specified in design
- set margins for acquire intent screen as specified (120px)
- left align acquire intent content
- fix acquire intent positioning issues
Screenshots on a 4k screen: [acquire intent](https://cloudup.com/igCTfkhgOzU), [design picker](https://cloudup.com/iLQE-kporYd), [template preview](https://cloudup.com/iWc0Crm5x1i)
* Go to /gutenboarding and checkout the flow
* On larger screens (including 1920px and above), the content should cover the full width of the screen
Fixes #40566
> Gutenboading: remove container max-width

- client/landing/gutenboarding/onboarding-block/style-preview/font-select.tsx
- client/landing/gutenboarding/onboarding-block/style-preview/style.scss
Fixes font alignment in the style picker in Firefox. 
Before / After
* Style picker buttons look good in various browsers
Fixes #40559
> Gutenboarding: Fix style picker font alignment (FF)

- client/lib/products-values/constants.js
- client/my-sites/site-settings/search.jsx
- client/my-sites/site-settings/settings-performance/main.jsx
Fixes #40450, but doesn't add an Instant Search toggle. 
* Adds Search product purchase detection in determining eligibility.
* Using a Jetpack site on a non-Professional plan without a Search product purchase, navigate to http://calypso.localhost:3000/settings/performance/. Ensure that you see the upgrade nudge as before.
* Using a Jetpack site on a non-Professional plan with a Search product purchase, navigate to http://calypso.localhost:3000/settings/performance/. Ensure that you see the configuration panel.
* Using a Jetpack site on a Professional plan, navigate to http://calypso.localhost:3000/settings/performance/. Ensure that you see the configuration panel as before.
* Using a WordPress.com site on a non-Business plan, navigate to …
> Jetpack Search: Detect eligibility in performance setting page

- config/wpcalypso.json
* Enables the Jetpack Search product for purchase in the `/plans` page.
* Open up these changes in a live calypso branch.
* Ensure that you can purchase a Jetpack Search product in `/plans`.
> Enable Search product on wpcalypso

- client/landing/gutenboarding/onboarding-block/style-preview/style.scss
2 mins review.
It highlights selected fonts buttons property. Before, when you selected fonts, the button remained black until you blur (focus out of it). This PR highlights the selected fonts button in blue even in focus and hover states.
> Highlight selected fonts button even when focused and hovered

- client/my-sites/checkout/checkout/composite-checkout.js
- packages/composite-checkout/demo/index.js
- packages/composite-checkout/src/lib/payment-methods/stripe-credit-card-fields.js
- packages/composite-checkout/src/public-api.js
This refactor helps make it less risky to create payment methods within a component.
Creating payment method objects requires passing in a bunch of callbacks which themselves have many dependencies. If the dependencies are dynamic, the payment methods must be created inside a component. However, since the payment methods each include their own internal data store, if they are recreated it can result in unexpected behavior. We can use memoization to only create each payment method once, but this may cause stale data issues because the dependencies might change. Trying to keep the dependencies (which may have their own dependencies) static can be an extremely hard challenge.
This PR helps to address this issue by splitting payment methods into two parts (in this PR, just the Stripe one to …
> composite-checkout: Use default registry for Stripe payment method

- client/lib/domains/index.js
* Invalidate emails in the site redirection input field
- Visit the Calypso live branch below.
- Visit `/domains/add/site-redirect/{domain}` on that branch. Replace `domain` with one of your site's primary domain
- Enter an email in the site redirection input field. Example: `example@example.com`
- Ensure that you get an error notification that reads `... does not appear to be a valid domain`.
Here is how the error must look:
Fixes https://github.com/Automattic/wp-calypso/issues/38548
> Invalidate emails in site redirection input field

- client/components/product-card/options.jsx
- client/components/product-card/style.scss
- client/lib/products-values/constants.js
- Update pricing and tier information UI according to what was proposed by @keoshi .
- Navigate to http://calypso.localhost:3000
- Go to the Plan -> Plans
- You should see the new buttons in Jetpack Backup/Search/Scan products.
See 1151678672052943-as-1168017254149561.
> Jetpack Cloud: update pricing and tier information UI

- client/landing/gutenboarding/onboarding-block/design-selector/index.tsx
Addresses https://github.com/Automattic/wp-calypso/issues/40562
* Remove vertical info from thumbnail URL to make them more stable, so that we wouldn't see "generating previews" each time different vertical is chosen.
**Less this:**
**More this, please:**
We can solve this problem differently a little later once we know we'll have vertical content. See https://github.com/Automattic/wp-calypso/issues/40562 for ideas.
- Observe how designs are always loaded right away no matter if you change to different verticals
> Gutenboarding: remove vertical parameter in thumbnail URL

- client/components/forms/form-toggle/compact.scss
- client/components/forms/form-toggle/style.scss
- client/me/purchases/manage-purchase/auto-renew-toggle/index.jsx
When a `Toggle` or `CompactToggle` component has the `toggling` prop enabled it doesn't really seem like anything is happening. And if the toggle fires a slow network request it seems like nothing is happening. So I decided it makes sense to add a fading animation to the toggle.
With optimistic toggling and label fading:
Previous try (just fading animation):
* I guess you can just enable/disable privacy for a domain or just render the `Toggle` component with `toggling={true}`
I'm not sure who should review this since it's a calypso-wide thing
> Add animation to Toggle when they're toggling

- apps/full-site-editing/bin/sync-blog-posts-block.sh
Follow-up to #39554, we need to replace the wrong text-domain also in the PHP files. See also D41162-code.
> FSE: Also update text-domains of PHP files in the BPB sync script

- client/me/purchases/manage-purchase/auto-renew-toggle/index.jsx
* When toggling the auto-renew toggle on the domain status screen there is no way to tell that anything is happening besides the toggle being disabled. This PR changes the text description so that it is clear we're in between states.
It looks like this:
* Open the new domain status screen with auto-renew toggle enabled (on dev environment) and click on the auto-renew toggle. You should see the ellipsis while the auto-renew status is updating.
> Change the auto-renew toggle text during toggling

- client/my-sites/feature-upsell/style.scss
- client/my-sites/guided-transfer/style.scss
- client/my-sites/invites/invite-accept-logged-in/style.scss
- client/my-sites/invites/invite-form-header/style.scss
- client/my-sites/marketing/connections/account-dialog-account.scss
- client/my-sites/marketing/style.scss
- client/my-sites/plans/current-plan/my-plan-card/style.scss
- client/my-sites/plans/current-plan/style.scss
- client/my-sites/site-settings/delete-site/style.scss
- client/my-sites/stats/post-trends/style.scss
- client/my-sites/stats/stats-module/style.scss
* See #39596 
* I wasn't able to find a few of these instances: Feature upsell, guided transfer, marketing account dialog, post trends, stats module. Given the relatively benign nature of this PR I don't think that's an issue, though.
**Before**
**After**
* Invite your account to a site and open the invitation when that account is not logged in; the heading on the invite accept screen should be font-weight 400.
* Do the same as above, but open the invitation on the account when it is already logged in, and check the heading font weight on that screen.
* Go to Marketing -> Sharing and look at the "One person likes this" text underneath the sharing buttons preview.
* Go to Plans -> My Plan and check the font weight on the subheader under the plan name in the first card. …
> Typography: Replace font-weight: 300 with 400

- client/my-sites/checkout/checkout/checkout-system-decider.js
- client/my-sites/checkout/checkout/composite-checkout.js
- client/my-sites/checkout/checkout/test/composite-checkout-thank-you.js
- client/my-sites/checkout/checkout/test/composite-checkout.js
This adds support for adding products of the form `domain-mapping:example.com` directly from the URL. Note that `domain-mapping` is not a real product slug, but rather a special alias used by calypso URLs for the product `domain_map` (another already-supported example is the alias `premium` for `value_bundle`).
Regular checkout already supports this feature, and with this change, composite checkout will also support it. So that it gets used, this change also modifies `CheckoutSystemDecider` so that it routes requests like `/checkout/YOURSITEHERE/domain-mapping:example.com` to composite checkout.
- Make sure your cart in calypso is empty.
- Visit http://calypso.localhost:3000/checkout/YOURSITEHERE/premium
- Verify that you are directed to composite checkout and that the plan product has …
> Allow adding domain mapping via url using composite checkout

- client/landing/gutenboarding/onboarding-block/acquire-intent/vertical-select/index.tsx
- client/landing/gutenboarding/stores/onboard/actions.ts
- client/landing/gutenboarding/stores/onboard/types.ts
- packages/data-stores/src/site/types.ts
- packages/data-stores/src/verticals/types.ts
This PR introduced two changes:
1. Sends the correct theme name to the `sites/new` endpoint as defined in [available-designs.json](https://github.com/Automattic/wp-calypso/blob/0413b99/client/landing/gutenboarding/available-designs.json)
So, after creating a site, instead of this:
We'll see this:
2. Passes `site_vertical_slug` to the `sites/new` endpoint in options. 
`site_vertical_slug` is the untranslated version of the site vertical name. 
We need the site vertical slug because the template mill pulls files from [/static/page-templates/verticals](https://github.com/Automattic/wp-calypso/tree/master/static/page-templates/verticals), in which there are directories labelled in English. 
If we use the vertical name, there is the possibility it might be translated and therefore won't build …
> Gutenboarding: pass theme and vertical slugs to sites/new 

- client/blocks/login/index.jsx
- client/blocks/login/login-form.jsx
- client/login/wp-login/login-links.jsx
I broke the gutenboarding theme'd login page (at `/log-in/gutenboarding`) when doing local development. Seems like it's only broken when the route _doesn't_ include a locale parameter.
A couple of components on the login page are server-side rendered, but I added a reference to `window`.
* Removes reference to `window` in `<LoginForm>` so it can still be SSR'd
* Removes reference to `window` in `<LoginLinks>` so it can still be SSR'd
* Fixed React warning about `class` vs. `className` while I was on that page.
* Check out branch
* `calypso.localhost:3000/log-in/gutenboarding` should load now
* `calypso.localhost:3000/log-in/gutenboarding/ja` still works
> Gutenboarding: Fix gutenboarding theme'd login page for local development

- client/landing/gutenboarding/onboarding-block/design-selector/style.scss
_10 seconds review._
Underline start-over button on Gutenboarding styles page.
See point 1 of https://github.com/Automattic/wp-calypso/issues/40394.
> Underline start-over button

- client/my-sites/domains/domain-management/edit/domain-types/helpers.jsx
- client/my-sites/domains/domain-management/edit/domain-types/mapped-domain-type.jsx
- client/my-sites/domains/domain-management/edit/domain-types/registered-domain-type.jsx
- client/my-sites/domains/domain-management/edit/style.scss
* We need to wrap the payment settings button to a new line on small displays.
* Test with `domains/new-status-design/auto-renew` flag disabled and enabled - both should work when you go below 800px the button/auto-rene toggle should wrap on a separate line
Fixes #40182
> Wrap the payment settings/auto-renew if on mobile

- client/landing/gutenboarding/onboarding-block/style-preview/font-select.tsx
- client/landing/gutenboarding/stores/onboard/index.ts
- client/landing/gutenboarding/stores/onboard/reducer.ts
- Add `selectedFonts` to persisted state.
- Fix the font selector to use `isShallowEqual` rather than `===` to compare font pairing _objects_ (cough).
- Clear `selectedFonts` state upon `RESET_ONBOARD_STORE`.
To reproduce the issue:
- Go to https://wpcalypso.wordpress.com/gutenboarding/
- In the browser console, type `localStorage.removeItem('WP_ONBOARD')`
- Reload
- Go through the onboarding flow until you're prompted to select a font pairing.
- Select a font pairing :)
- Close the tab. Open a new one, and start at https://wpcalypso.wordpress.com/gutenboarding/style again.
- Go through the onboarding flow again, picking the same design again
- You'll see that your font pairing choice hasn't been persisted.
To reproduce the fix:
- Follow the same steps as above for this branch (locally on …
> Gutenboarding: Persist selected fonts

- client/me/purchases/manage-purchase/auto-renew-toggle/index.jsx
- client/me/purchases/manage-purchase/purchase-meta.jsx
- client/my-sites/domains/domain-management/edit/domain-types/mapped-domain-type.jsx
- client/my-sites/domains/domain-management/edit/domain-types/registered-domain-type.jsx
* We want to check if the auto-renew toggle is used from the new domain status screens or from the purchases page so I had to add a new property to the tracking code
* Enable/disable auto-renew for a domain and verify that it's sending the `toggle_source` property to the tracks event
> Track where the auto-renew toggle is used from

- client/lib/i18n-utils/test/utils.js
- client/lib/i18n-utils/utils.js
Follow-up to #40602 where it shows that some links are double `localizeUrl`ed, resulting in wrong URLs (that still work), for example:
```
localizeUrl( localizeUrl( 'https://en.support.wordpress.com/all-about-domains/' ) )
=>'https://de.wordpress.com/de/support/all-about-domains/'
```
This fixes that double-localizing:
```
localizeUrl( localizeUrl( 'https://en.support.wordpress.com/all-about-domains/' ) )
=>'https://wordpress.com/de/support/all-about-domains/'
```
> localizeUrl: Handle double calls better

- client/landing/gutenboarding/components/domain-picker/style.scss
- client/landing/gutenboarding/components/header/index.tsx
- client/landing/gutenboarding/components/titles.scss
- client/landing/gutenboarding/onboarding-block/design-selector/style.scss
- client/landing/gutenboarding/onboarding-block/style-preview/index.tsx
- client/landing/gutenboarding/onboarding-block/style-preview/style.scss
- client/landing/gutenboarding/style.scss
Fixes most points of #40569.
1. [x] The device buttons are spaced a bit too far apart. The buttons should be `56px` high. Desktop should be `56px` wide, `48px` tablet , and `40px` mobile.
2. [ ] The _Choose another design_ button should be styled according to designs (`font-size; 14px`, and `text-decoration: underline`).
3. [x] The _Choose another design_ button should be aligned right to the container and centered vertically with the text.
4. [x] The font buttons should be `blue 40` when selected.
5. [x] Button, _Create my site_, in top right shouldn't be there. Instead, see the screenshot below.
> Gutenboarding: Visual fixes for #40569

- client/landing/jetpack-cloud/sections/backups/rewind-flow/download.tsx
- client/landing/jetpack-cloud/sections/backups/rewind-flow/index.tsx
Update the BackupDownloadFlow component to use the date of the backup in the correct time zone. The component should show up when the site settings are loaded because the user could see the date on UTC for a moment before it changes to the correct time zone.
- Apply these changes
- Select a backup and click on Backup backup
- Check if the date/time is correct on the site time zone and you don't see the time in GMT.
> Update BackupDownloadFlow to use date of backup in the correct timezone

- client/landing/gutenboarding/onboarding-block/design-selector/index.tsx
- client/landing/gutenboarding/stores/onboard/actions.ts
- client/landing/gutenboarding/stores/onboard/reducer.ts
The [rationale](https://github.com/Automattic/wp-calypso/issues/40649#issuecomment-607177429) for this change is:
> [...] if the previews on the Design step will show the theme default fonts, we should show the font defaults selected on the Fonts step too.
Steps to replicate:
- Choose design
- Change font pairing in font picker to something custom
- Go back to design picker
- Choose another design
- Font pairing has been reset to design's default
Compare that to wpcalypso, where a previously made font selection is carried over when selecting a different design.
Fixes #40649
> Gutenboarding: Reset font pairing when selecting new design

- client/landing/gutenboarding/available-designs.json
* Correct template name in available designs json 
Can't really test this before it's merged, but as you can observe, this works:
https://public-api.wordpress.com/rest/v1/template/demo/coutoire/bowen/
this doesn't:
https://public-api.wordpress.com/rest/v1/template/demo/coutoire/coutoire/
> Gutenboarding: fix correct template matching coutoire theme

- client/blocks/product-selector/index.jsx
- client/components/product-card/style.scss
- client/lib/products-values/constants.js
* Update copy for single products.
* Hide promo nudge for products without discounted prices.
* Reordered the cards to show Backup, Search, Scan.
* Go to WordPress.com and open Plans (`/plans/`) with a Jetpack site.
* Ensure all single product cards have:
* The correct copy on each.
* That the promo nudge only appears for Search.
* Visually look good. For this one, bear in mind the product variation design refresh is being worked on https://github.com/Automattic/wp-calypso/pull/40583
Fixes https://github.com/Automattic/wp-calypso/issues/40551
> Jetpack: update single product cards

- client/jetpack-connect/test/__snapshots__/plans.js.snap
- client/jetpack-connect/test/lib/plans.js
- client/state/selectors/is-site-wpforteams.js
- client/state/selectors/test/is-site-wpforteams.js
- client/state/sites/constants.js
In this PR, we add a selector `isSiteWPforteams` to distinguish between a standard WP.com site and a WP for Teams one.
Tests should pass. Code review.
> WP for Teams: add selector

- client/landing/jetpack-cloud/components/daily-backup-status/index.jsx
- Removed the copy on Non-backup on today to match the new design of Backup Status
- Removed the footer copies on days without backups, below the buttons (asked to design team)
- Change the time format to 0-23
- Add the external links to the copies (for now with _blank target)
- Extracted the button actions as a component
**Note:** No styles applied
- Apply these changes
- Select a day with backup, check if the new time format is okay, 0-23 (set another TZ if it's necessary)
- Check the external links on a failed backup (behavior: the link will open on a new tab)
- Check the action buttons behavior:
- Success backup: both buttons are enabled (except if we don't have credentials, the Restore button should be disabled)
- No backups: both buttons are disabled
> BackupStatus: Change copies + time format to match the design + add external links

- client/my-sites/customer-home/locations/primary/index.jsx
- client/my-sites/customer-home/main.jsx
Reverts Automattic/wp-calypso#40537
> Revert "My Home: Use the layout API results to render primary cards."

- client/my-sites/customer-home/locations/primary/index.jsx
To guard against any situation that might leave us with an empty `primary` location array in the Home API response, let's add a fallback to the Quick Links component. This PR also adds a check against invalid card names that could cause fatals.
* Sandbox the API and force it to return an empty primary location array.
* Go to `/home/:site` on this branch.
* Verify the call to the `layout` API endpoint returned your expected empty `primary` array, and that the Quick Links are displayed on the Home page.
> My Home: Ensure the primary location always has content.

- client/my-sites/customer-home/locations/secondary/index.jsx
- client/my-sites/customer-home/main.jsx
**Requires #40537.**
In #40172 we wired in the Home layout API; this PR uses those results to determine which cards to render in the secondary location. No visual or functional changes should happen between this PR and production.
* Load My Home on this branch at `https://calypso.localhost:3000/home/:site`.
* Verify the secondary column loads properly, and doesn't have more than three cards.
* Check other different sites (Atomic, Simple, Business plan) and see if you hit any errors.
> My Home: Populate secondary cards with the layout API.

- client/my-sites/checkout/checkout/secure-payment-form.jsx
A wrong comparison was introduced in this condition in #40590, this PR restores the correct one.
First, let's test without this PR applied:
1. Assign yourself to `control` of ATPrivacy AB test
1. Using a8c account create a new site and choose e-commerce plan in signup
1. Confirm that after the checkout the site is public as it should be, even though the code branch from this PR did not kick in
Now, with this PR applied:
1. Assign yourself to `variant` of ATPrivacy AB test
1. Using a8c account create a new site and choose e-commerce plan in signup
1. Confirm that the site is still private after the checkout
1. Assign yourself to `control` of ATPrivacy AB test
1. Using a8c account create a new site and choose e-commerce plan in signup
1. Confirm that the site is public after the checkout
> [Private sites] Adjust the condition keeps the e-commerce site private during checkout

- client/landing/gutenboarding/onboarding-block/acquire-intent/index.tsx
- client/landing/gutenboarding/onboarding-block/acquire-intent/site-title.tsx
- client/landing/gutenboarding/onboarding-block/acquire-intent/style.scss
- client/landing/gutenboarding/onboarding-block/acquire-intent/vertical-select/index.tsx
- client/landing/gutenboarding/onboarding-block/acquire-intent/vertical-select/style.scss
* vertical select input and site title are now inline (using `contenteditable`) so they can be wrapped if longer and on smaller screens like regular texts
* prevent the inputs from going off-screen
* prevent full-width underline for both inputs
* prevent displaying an underline when site title input is empty
* prevent jumping of the inputs when new step (and next button) appears as mentioned in https://github.com/Automattic/wp-calypso/issues/40474#issuecomment-607161116
* the next arrow is always displayed next to the vertical input field
* other small fixes from #40321
* support for further i18n (input can be in the middle of the text)
* added back full stop at the end of vertical input since now the period wraps correctly to the next line: https://cloudup.com/chpR7hnwYht
* Go to …
> Gutenboarding: Improve acquire intent UI and experience

- client/blocks/disconnect-jetpack/style.scss
- client/jetpack-connect/jetpack-new-site/style.scss
- client/jetpack-connect/style.scss
- client/my-sites/themes/auto-loading-homepage-modal.scss
- client/my-sites/themes/thanks-modal.scss
- client/my-sites/themes/themes-site-selector-modal.scss
- client/signup/site-mockup/style.scss
- client/signup/steps/creds-complete/style.scss
- client/signup/steps/creds-confirm/style.scss
- client/signup/steps/import-url-onboarding/style.scss
- client/signup/steps/rewind-migrate/style.scss
* Swap out `font-weight:300` for `font-weight:400`. See #39596
* I couldn't find several of these, but I'm OK with shipping this update as the changes are minimal.
| ------- | ------|
| <img width="481" alt="Screen Shot 2020-04-01 at 11 10 18 AM" src="https://user-images.githubusercontent.com/2124984/78154228-00cab100-740a-11ea-9373-27575b96ad74.png"> | <img width="512" alt="Screen Shot 2020-04-01 at 11 09 39 AM" src="https://user-images.githubusercontent.com/2124984/78154230-01634780-740a-11ea-8190-a7f87db08775.png"> |
| <img width="330" alt="Screen Shot 2020-04-01 at 11 09 22 AM" src="https://user-images.githubusercontent.com/2124984/78154170-f0b2d180-7409-11ea-858f-99713a726a95.png"> | <img width="323" alt="Screen Shot 2020-04-01 at 11 11 12 AM" …
> Update font weights across Calypso from 300 to 400

- client/state/selectors/test/is-unlaunched-site.js
Brings the tests over from https://github.com/Automattic/wp-calypso/pull/37868 by @jblz . They are slightly updated to pass without modifying the actual selector. A follow-up PR should be issued to fix the inconsistencies and ensure the selector always returns either true or false.
Confirm CI tests passed
> [Private sites] Add tests for isUnlaunchedSite

- client/extensions/woocommerce/woocommerce-services/views/shipping-label/label-purchase-modal/index.js
In the create shipping label modal, after the label has been purchased,
when the modal is closed, an unhandled Javascript error is thrown and breaks the
app.
Checks presence of an object before accessing one of its properties.
1. Open an order in the store from: http://calypso.localhost:3000/store/orders/your.site.com
2. Purchase a label.
3. When the label is purchased, close the window by clicking out of the modal.
4. Without this patch, an error will be thrown and the app's execution will stop.
> Fix an error in WooCommerce Services modal

- client/my-sites/checkout/checkout/index.jsx
- client/my-sites/plans/current-plan/current-plan-thank-you/scan-thank-you.js
- client/my-sites/plans/current-plan/current-plan-thank-you/style.scss
- client/my-sites/plans/current-plan/current-plan-thank-you/thank-you.js
- client/my-sites/plans/current-plan/index.jsx
- We need to add a "Thank you" note after purchasing Jetpack Scan.
It is still unclear what should the CTA do. Right now, it brings the user to the checklist tour. This seems reasonable since Scan requires the server credentials to work and we could add that requirement to the checklist.
- Navigate to http://calypso.localhost:3000/plans/
- Purchase Jetpack Scan
- You should see the "Thank you" note and the end of the URL should look like `?thank-you=&product=jetpack_scan`
See 1151678672052943-as-1168017254149561.
> Jetpack Cloud: Add thank you note to JP Scan purchases

- client/jetpack-connect/index.js
* Point the routes:
https://wordpress.com/jetpack/connect/jetpack_search
https://wordpress.com/jetpack/connect/jetpack_search/monthly
to the Jetpack Connect Flow.
- start Calypso with this change
- visit the above urls and confirm the first screen of JPC
Note: the change also works for 
https://wordpress.com/jetpack/connect/jetpack_search/yearly
Fixes https://github.com/Automattic/wp-calypso/issues/40627
> Jetpack Search: Include Search in the route of the JPC flow

- client/my-sites/customer-home/locations/upsells/index.jsx
- client/my-sites/customer-home/main.jsx
This PR uses the results from the Home layout API to determine cards to display in the `upsells` location. Because the only card at the moment is a legacy stats component requiring a bunch of props, I'm not even convinced this PR is worth the effort – others can decide 🙃
* On this branch, go to a business site older than two days (that has not already dismissed the banner).
* Verify the banner displays.
> My Home: Display upsells according to the Home API.

- client/my-sites/checkout/checkout/test/composite-checkout.js
- packages/composite-checkout-wpcom/src/mock/cart-endpoint.ts
This PR adds some additional unit tests for the checkout form in calypso, including:
- the display of payment methods normally vs. with free purchase vs. with full credit vs. partial credit.
- the display of the contact form normally vs. with domain vs. with specific country.
- the empty cart redirect normally vs. with urls that add products.
- adding products via urls that add plans or domain mapping or coupon codes.
- race conditions with regular cart.
`npm install && npm run test-client client/my-sites/checkout/checkout/test/composite-checkout`
> Add more unit tests for composite checkout in calypso

- client/components/banner/style.scss
- client/components/tinymce/plugins/simple-payments/dialog/index.jsx
- client/components/tinymce/plugins/simple-payments/style.scss
- client/my-sites/earn/memberships/index.jsx
- client/my-sites/marketing/main.jsx
- client/my-sites/media-library/list-plan-upgrade-nudge.jsx
- client/my-sites/media-library/style.scss
- client/my-sites/plugins/plugins-browser/index.jsx
- client/my-sites/plugins/plugins-browser/test/index.jsx
- client/my-sites/post-type-list/index.jsx
- client/my-sites/post-type-list/style.scss
- client/my-sites/site-settings/podcasting-details/index.jsx
- client/my-sites/stats/stats-module/index.jsx
- client/my-sites/stats/stats-module/style.scss
* Standardizing upsell nudges from the component end, this replaces all instances of `UpgradeNudge` with `UpsellNudge`
* The nudges should be visually the same, and tracks events should remain the same
| Visuals | |
| ------- | ------- |
| <img width="736" alt="Screen Shot 2020-03-31 at 4 03 37 PM" src="https://user-images.githubusercontent.com/2124984/78070269-7f234680-7369-11ea-90f1-3ba61c017831.png"> | <img width="776" alt="Screen Shot 2020-03-31 at 4 03 30 PM" src="https://user-images.githubusercontent.com/2124984/78070273-7fbbdd00-7369-11ea-972e-7777ccb70c44.png"> |
| <img width="1081" alt="Screen Shot 2020-03-31 at 3 32 21 PM" src="https://user-images.githubusercontent.com/2124984/78070275-80547380-7369-11ea-8ec0-3cdd02e72c53.png"> | <img width="1088" alt="Screen Shot 2020-03-31 at …
> UpgradeNudge: Swap UpgradeNudge for UpsellNudge

- client/landing/gutenboarding/onboarding-block/acquire-intent/vertical-select/index.tsx
In the Vertical Select component, we were previously only prepending a user-supplied vertical to our suggestions list if it wasn't found in the suggestions list. This caused an issue with _known_ verticals (see #40715). This PR fixes that issue by also prepending a _known_ vertical to the suggestions list.
Note that this also makes for a more consistent transition from entering a partial string to a recognized vertical:
Before:
After:
See #40715, and verify that it is fixed.
Fixes #40715
> Gutenboarding: Fix Vertical Select to put exact match first

- apps/full-site-editing/full-site-editing-plugin/global-styles/src/dom-updater.js
#40489 broke global styles inside the iFrame (changing a font did not change the font inside the preview). This fixes that.
The root cause is that the `<style />` element we dynamically update for Global Styles was not appended at the end of the other `<style />` elements. I'm not quite sure why, but it seems that this script can begin executing before all the style elements have been loaded. So the fix is to wait some time to add the style element. I chose the `isEditorReady` selector for this, but there could be a better heuristic. At any rate, this fixes the issue for me.
1. Sync to dotcom. Changing the font selection in Global Styles should update the editor.
2. Test the same on a self hosted site
3. Test that changes in #40489 still work correctly
> Fix Global Styles on wpcom

- client/components/data/query-home-layout/index.js
- client/my-sites/customer-home/main.jsx
- client/state/data-layer/wpcom/sites/home/layout/index.js
- client/state/home/actions.js
To allow us to keep logic for the "you launched your site" notice server-side, this PR adds the new `is_now_launched` param to the `layout` API call.
When launching a site, Calypso currently relies on a `?d=launched` query param to trigger display of the "launched" notice. If this param is present, we'll add the `?is_now_launched=true` param to the layout API call, ensuring proper handling server-side in the library (which is added in D41310-code).
* Apply D41310-code and sandbox the API.
* Go to any established site's Home, and make sure it loads content. The API call to `layout` should not show any query params.
* Reload after adding `?d=launched` to the browser URL.
* Verify the "you launched your site!" notice is displayed (it's highest priority notice for established views).
> My Home: Pass the `is_now_launched` param to the `layout` call.

- client/landing/gutenboarding/components/domain-picker/suggestion-item.tsx
- packages/data-stores/src/domain-suggestions/index.ts
- packages/data-stores/src/domain-suggestions/resolvers.ts
Domain picker showing the real price.
* Changed price from per month to per year, because that's what the API returns
* Show price from domain suggestion API in domain picker
* Load domain suggestions using request-proxy, so if the user is logged in the price will be in the user's currency
* Visit `/gutenboarding` in incognito
* Search for domains
* Domain picker shows annual cost in a reasonably auto-detected currency
* Visit `/gutenboarding` while logged in
* Search for domains
* Domain picker shows annual cost in the user's currency
> Gutenboarding: Show domain price from API response in domain picker

- apps/full-site-editing/full-site-editing-plugin/full-site-editing-plugin.php
- apps/full-site-editing/full-site-editing-plugin/readme.txt
- apps/full-site-editing/package.json
Updates FSE plugin version to 1.0.
1. Use the generated diff to test the latests updates from changelog on you sandbox.
2. Use the generated archive to test on Atomic sites.
> FSE: bump plugin version to 1.0

- client/landing/gutenboarding/components/signup-form/header.tsx
- client/landing/gutenboarding/components/signup-form/index.tsx
- client/landing/gutenboarding/components/signup-form/style.scss
- client/landing/gutenboarding/mixins.scss
This PR implements feedback on previous PRs regarding [error messages styling](https://github.com/Automattic/wp-calypso/pull/40558#issuecomment-606508009) and the position of [the signup form's title moving](https://github.com/Automattic/wp-calypso/pull/40599#issuecomment-606935988) when an error message is added to the DOM.
* No longer centre the signup form vertically, instead set it to an approximate height so that when error messages are added to the DOM, the title, etc, remain in place
* Style the error messages as centred red text, instead of the default Gutenberg Notice styling
* Move Log in link to the body of the form as in the Figma.
* Move TOS line below the create account button
(Note the Create account button is not hidden when the error message is about an existing login — I …
> Update Gutenboarding signup styling (error messages and positioning)

- client/landing/gutenboarding/components/domain-picker-button/index.tsx
- client/landing/gutenboarding/components/domain-picker/index.tsx
- client/landing/gutenboarding/components/header/index.tsx
- client/landing/gutenboarding/constants.ts
- client/landing/gutenboarding/hooks/use-domain-suggestions.ts
- client/landing/gutenboarding/stores/onboard/actions.ts
- client/landing/gutenboarding/stores/onboard/reducer.ts
- client/landing/gutenboarding/utils/domain-suggestions.ts
* In Gutenboarding, update the domain in the header to be the recommended paid domain, instead of the selected free domain. (This necessarily involved doing a bigger suggestions query than a single result so that we can get a proper suggested domain)
* Add `useDomainSuggestions` hook to group together calls to get domain suggestions from the header and the domain picker so that they're using the same call — this is to prevent any discrepancy between the two as they should both be working with the same set of results.
* That said, allow a `searchOverride` parameter to fix the results of the suggestion to the site title in the header, so that it doesn't constantly keep updating while the user is searching.
* Fix issue where it was possible to search for a domain, select a sub-domain, then …
> Gutenboarding: Update domain in header to be recommended paid domain

- client/blocks/login/index.jsx
- client/blocks/login/login-form.jsx
- client/blocks/login/two-factor-authentication/two-factor-actions.jsx
- client/blocks/login/two-factor-authentication/verification-code-form.jsx
- client/blocks/login/two-factor-authentication/waiting-notification-approval.jsx
- client/lib/paths/login/index.js
- client/login/index.web.js
- client/login/wp-login/login-links.jsx
Adds gutenboarding theming to the 2fa screens of log in.
Works in a similar way to Jetpack's theming of these screens.
* Add gutenboarding styling to login screens for:
* SMS
* 3rd party authenticator app
* Push (using the WordPress app)
* Backup codes
Builds on styling already shipped in #40557 
Doesn't including theming of magic link login screens. That'll be in another PR.
Known issue:
- The locale isn't persisted between some of the login screens (e.g. navigating from entering password to entering SMS code), but this is also broken in production #23126. I think we should fix this in another PR.
* `/log-in/gutenboarding`
* Log in using accounts with various sorts of 2nd factor options
* Test that you can navigate between different auth types while keeping the gutenboarding theming e.g. …
> Gutenboarding: Add gutenboarding styling to 2fa login screens

- client/login/index.web.js
- client/login/magic-login/emailed-login-link-successfully.jsx
- client/login/magic-login/index.jsx
- client/login/magic-login/style.scss
- client/login/wp-login/login-links.jsx
* Create `/log-in/gutenboarding/link` route
* Change card borders, heading font, button colours to match gutenboarding
* Fix up back button links
* Add WordPress logo in top-left
Not in this PR:
- 2FA screens, that's #40637 
- The login screens after clicking the link in your inbox is still unstyled. Jetpack hasn't even addressed this, so I don't know if we should attempt that as part of the CfT.
* Test flow starting from `/log-in/gutenboarding` and click "Email me a login link"
* Test flow starting from `/log-in/gutenboarding` and entering a passwordless username/email into the field
* Test flow starting from `/gutenboarding`, log in with existing account, ask for magic link, click link in your inbox, at the end of the whole flow you should be taken back to gutenboarding and you site …
> Gutenboarding: gutenboarding theming for magic link login

- client/landing/gutenboarding/components/header/style.scss
* Go to /gutenboarding
* Enter site title in intent capture step
* Site title in header (top-left) should not be bold
> Gutenboarding: header side title should not be bold

- client/landing/gutenboarding/mixins.scss
- client/landing/gutenboarding/onboarding-block/design-selector/index.tsx
- client/landing/gutenboarding/onboarding-block/design-selector/style.scss
- client/landing/gutenboarding/variables.scss
* Update design picker grid gaps to a fixed value (64px)
* Update heading padding variables (on desktop: 64px top and 80px bottom
* Design frame hover. To align with gutenberg, we should move away from drop shadow, and frame size increase animation to a fixed size, and border color change
* go to /gutenboarding
* test the above style changes on design selection step
> Gutenboarding: update design selector style

- client/blocks/product-selector/index.jsx
- client/lib/products-values/constants.js
- client/my-sites/plans-features-main/products-header.jsx
* Updates copy.
* Removes “Which backup option is best for me?” link from the products header.
* Updates products constants to add link properties.
* Adds links to single product cards.
* Complementary to https://github.com/Automattic/jetpack/pull/15237
* Fire up this PR
* Go to `http://calypso.localhost:3000/plans/SITE_URL`.
* Ensure: 
* All single product cards look good.
* Both have links that redirect to their respective LPs.
* Tracking works.
Fixes #15183 along with https://github.com/Automattic/jetpack/pull/15237
> Jetpack: update links on single products

- client/landing/gutenboarding/components/header/index.tsx
- client/landing/gutenboarding/stores/onboard/actions.ts
_1-minute review_
When the user picks a domain in the domain picker, it should appear on the button instead of keeping the suggestion stuck.
1. Pick a domain. You should see it on the button.
2. Refresh the page. Your choice should persist and the button should reflect that.
Fixes https://github.com/Automattic/wp-calypso/issues/40747
> Gutenboarding: Show user-picked domain when user picks one

- client/lib/wpcom-undocumented/lib/undocumented.js
Requesting media files using path, such as `/sites/<ID>/atomic-auth-proxy/file/image.jpg` is problematic from http caching point of view (see D41345-code for details). This PR replaces the path with query argument.
Go to media library on private atomic site and confirm your images are loaded correctly. Don't test on calypso.live
> [Private media] Request media files using query string

- packages/babel-plugin-i18n-calypso/package.json
This PR removes the `prepare` script from babel-plugin-i18n-calypso as it's obsolete and causes publishing with lerna to fail.
N/A
> Remove prepare script form babel-plugin-i18n-calypso

- client/blocks/product-plan-overlap-notices/README.md
- client/blocks/product-plan-overlap-notices/docs/example.jsx
- client/blocks/product-plan-overlap-notices/index.jsx
- client/blocks/product-plan-overlap-notices/style.scss
- client/me/purchases/manage-purchase/index.jsx
- client/me/purchases/purchases-site/index.jsx
* Updates `< ProductPlanOverlapNotices />` block to accommodate more than one conflict.
* Changes references to just backups to use all Jetpack products.
* Create a Jetpack site with a plan with two or more conflicting products. For example, Jetpack Professional and Scan and Daily Backups.
* Check notices in plans (`/plans/[site]`).
* Check notices in purchases (`/me/purchases`).
* Check notices in site purchases (`/me/purchases/[site]/[purchase]`).
Fixes 1151678672052943-as-1168265713258996.
> Updates plan conflict notice to accommodate more than one conflict

- client/my-sites/customer-home/locations/notices/index.jsx
- client/my-sites/customer-home/main.jsx
In #40172 we wired in the Home layout API; this PR uses those results to determine which cards to render in the `notices` location. No visual or functional changes should happen between this PR and production.
* On this branch, create a brand-new site and verify the "Your site has been created!" notice is displayed (once you've landed on `/home/:site`).
* Launch the site, and verify the "You launched your site!" notice is displayed.
* Complete the checklist, and verify the "You've completed each item in your checklist" notice is displayed.
* Go to Tools > Import, select "WordPress", and proceed to import everything from a Jetpack site (create a new Jurassic Ninja site if needed; you'll also need to upgrade the destination site's plan).
* Verify the "Your site has …
> My Home: Use the layout API results to render notice cards.

- client/landing/jetpack-cloud/components/date-picker/index.jsx
- client/landing/jetpack-cloud/components/date-picker/style.scss
- client/landing/jetpack-cloud/sections/backups/main.jsx
* Add a search icon that redirects the user to the Activity Log
* Pass the `siteSlug` prop into the DatePicker component so we can redirect
* Apply styles to the date picker, including the search icon
* Load in mobile and desktop format, ensuring styles look correct
* Click search icon to ensure user is redirected to Activity Log URL (page not yet implemented)
> Jetpack Cloud: Apply styles to date-picker component

- client/my-sites/checkout/checkout-thank-you/header.jsx
- client/my-sites/checkout/checkout-thank-you/index.jsx
* Move "Go to my site" button to the bottom in order to add some more importance to the rest of the page content. 
I used `props.children` of `CheckoutThankYouHeader`. I am not sure if this is the best approach, but it is definitely the simplest...
* Link website to your own domain
Fixes #39127
Before:
After:
> Move the "Go to my site" button after the content

- client/my-sites/customer-home/main.jsx
This PR quiets a warning about `<Home />`'s `layout` prop being required, but can be `null` (while waiting for a response from the layout API call.
* Sandbox the API (this is often enough to trigger the warning).
* Load the Home page of any site, notice (or sometimes not) the warning in the console.
* Apply this branch, and reload.
* Ensure the warning is not displayed.
> My Home: Silence required prop warning.

- config/wpcalypso.json
After uploading the new templates, with updated names, the pre-rendered screenshots links are broken, so I'm updating the flags to use mshots until we generate them again
> Gutenboarding: Activate flag to use mshots

- client/blocks/login/continue-as-user.jsx
- client/blocks/login/continue-as-user.scss
Address the following design feedback from @olaolusoga #40556
- Bump down the gravatar width/height to 110px—it's currently at 200px.
- Add 1px border to gravatar. Border color: #A7AAAD
- Gravatar should be clickable—it isn't at the moment.
- Can we make sure everything is center.
- Remove username from button, and add below gravatar image (see mock)
- Update copy from "Not [username]? Login in with a different account" to "Not you?
- Log in with another account" (see screenshot)
- Stay logged-in
- Open /log-in
- Observe design changes
- Whole avatar should now be clickable
Fixes #40556
> address design feedback on login page

- client/my-sites/marketing/connections/service-description.jsx
* Change text from "news feed" to "Facebook page".
Fixes #40709
> Sharing: update text for Facebook sharing message

- client/lib/domains/index.js
- client/my-sites/domains/domain-management/edit/index.jsx
* Update header title to help people distinguish different domain types
Before:
After:
* Check the domain settings page for registered domain, mapped domain, wpcom domain or incoming transfer
> Show the domain type in the domain settings header title

- client/landing/gutenboarding/onboarding-block/style-preview/preview.tsx
- client/landing/gutenboarding/onboarding-block/style-preview/style.scss
Use CSS to adjust the preview size and constrain it to fit the viewport with some exceptions.
- Desktop fits in reasonably sized viewports
- Tablet and mobile views adjust to an aspect ratio relative to the width, with a max width as shown in the preview. This noticeably improves the tablet on most viewports.
Tablet and mobile only adjust their width, height will still cause overflow on some screens.
Big props to @alshakero who drove a lot of the direction of this change.
Progress on #40568
Alternative to #40729
| Before | After | 
| --- | --- |
| ![Screen Shot 2020-04-03 at 17 36 43](https://user-images.githubusercontent.com/841763/78379599-ea238600-75d2-11ea-9fa5-10364cdc6d28.png) | ![Screen Shot 2020-04-03 at 17 37 42](https://user-images.githubusercontent.com/841763/78379602-ebed4980-7 …
> Gutenboarding: Preview sizing

- client/landing/gutenboarding/components/header/index.tsx
- client/landing/gutenboarding/hooks/use-domain-suggestions.ts
- client/landing/gutenboarding/path.ts
For the domain suggestion, fall back to the vertical set by the user if no sitle has been entered.
- Go to http://calypso.localhost:3000/gutenboarding
- Enter a vertical and confirm with Enter
- Notice that the domain picker makes a suggestion based on the vertical
- Enter a site title. The domain picker will change to a suggestion based on the site title.
Fixes part of #40748.
> Gutenboarding: Fall back to vertical for domain suggestion

- client/landing/jetpack-cloud/components/activity-card/index.jsx
- client/landing/jetpack-cloud/components/backup-delta/index.jsx
- client/landing/jetpack-cloud/sections/backups/main.jsx
pass the props `ActivityCard` component will need to apply the correct site time zone. We pass the site TZ and the GMT offset to `ActivityCard` to apply it to the activity time.
Also, we refactor the props `siteTimezone` and `siteGmtOffset` on `BackupsPage` component to  `timezone` and `gmtOffset`to facilitate the use of the destructuring assignments.
- Find a date with a backup with real-time changes (to see the Activity Card component in action)
- Check that nothing has changed vs master
> Apply on the ActivityCard component the correct site time zone

- client/blocks/inline-help/popover.jsx
In inline help popover, currently the "Switch To Block/Classic Editor" button is showing everywhere, this button should only show when user is in the block editor or classic editor page.
Accessing the following urls should show the  "Switch To Block/Classic Editor" button in the inline help popover:
- /block-editor/page/yoursitehere.wordpress.com
- /block-editor/post/yoursitehere.wordpress.com
- /page/yoursitehere.wordpress.com
- /post/yoursitehere.wordpress.com
Accessing other pages should not show this button, including these pages which shows you which WordPress site to switch to:
- /block-editor
- /page
- /post
- ... and all other pages.
Fixes #40383
> Only show switch editor button in inline help popover when in block editor or classic editor route.

- client/blocks/upsell-nudge/index.jsx
* This matches functionality found in `UpgradeNudge` that was missed when I committed #40626 
* Originally reported in p9jf6J-2rd-p2
* It would be good to get Marketing's eyes on this to make sure these upsells are showing in the right places/not showing when they shouldn't.
| Visuals | |
| ------- | ------- |
| <img width="736" alt="Screen Shot 2020-03-31 at 4 03 37 PM" src="https://user-images.githubusercontent.com/2124984/78070269-7f234680-7369-11ea-90f1-3ba61c017831.png"> | <img width="776" alt="Screen Shot 2020-03-31 at 4 03 30 PM" src="https://user-images.githubusercontent.com/2124984/78070273-7fbbdd00-7369-11ea-972e-7777ccb70c44.png"> |
| <img width="1081" alt="Screen Shot 2020-03-31 at 3 32 21 PM" src="https://user-images.githubusercontent.com/2124984/78070275-80547380-7369-11ea-8e …
> UpsellNudge: Add some logic to determine when upsells should not show

- client/extensions/hello-dolly/hello-dolly-page.js
- client/landing/domains/content-card/style.scss
- client/my-sites/feature-upsell/style.scss
* A few stragglers came in after deploying the other sets. :) See #39596 
* I could not find one of these; it appears to be associated with a component that's not active at this time.
| ------ | ------ |
| <img width="760" alt="Screen Shot 2020-04-03 at 3 22 02 PM" src="https://user-images.githubusercontent.com/2124984/78397382-1fbe7400-75bf-11ea-8598-13c407bb7bc8.png"> | <img width="752" alt="Screen Shot 2020-04-03 at 3 21 43 PM" src="https://user-images.githubusercontent.com/2124984/78397390-23ea9180-75bf-11ea-82e8-0100dd4bded9.png"> 
| <img width="768" alt="Screen Shot 2020-04-03 at 3 38 36 PM" src="https://user-images.githubusercontent.com/2124984/78398581-51d0d580-75c1-11ea-95fb-ec201472327e.png"> | <img width="751" alt="Screen Shot 2020-04-03 at 3 38 43 PM" …
> Typography: More font weight updates 300 -> 400

- client/my-sites/plans/current-plan/current-plan-thank-you/thank-you.js
* Track the redirects from the Thank you Jetpack Search post-purchase modal.
* Purchase Jetpack Search plan
* Choose `Customizer` or `My site` from the `Thank You` modal 
* verify that the event
`calypso_jetpack_product_thankyou` fires with the correct property.
part of https://github.com/Automattic/jetpack/issues/15151
> Jetpack Search: add tracking to the post-purchse Thank you note

- client/landing/gutenboarding/onboarding-block/style-preview/style.scss
- client/landing/gutenboarding/onboarding-block/style-preview/viewport-select.tsx
Remove click-initiated focus style on buttons.
If buttons are focused by keyboard navigation, maintain focus style.
Part of #40757
* [`/gutenboarding`](/https://calypso.live/gutenboarding?branch=gutenboarding/remove-viewport-active-border)
* Proceed to style step
* Click different viewports
* On hover they should have a box
* The last clicked (focused) button should not
* If focused via keyboard navigation, it should have focus styles regardless (has box)
> Gutenboarding: Remove click-focus style from viewports

- client/landing/gutenboarding/onboarding-block/style-preview/preview.tsx
- config/wpcalypso.json
_2 mins review._ 
This is to fix the Bowen theme preview. 
This PR hides sending verticals in the preview page behind a flag (`gutenboarding/style-preview-verticals`). 
Go to `gutenboarding/style` after you select Bowen theme. You should see it fully-rendered.
Fixes p1586180166028500-slack-gutenboarding
> Gutenboarding: hide verticals support in previews behind a flag

- client/my-sites/customer-home/locations/notices/index.jsx
- client/my-sites/customer-home/main.jsx
[Observed](https://github.com/Automattic/wp-calypso/pull/40634#issuecomment-607345928) by @jancavan :
> I also noticed that our success message is incorrect for certain use cases; it keeps mentioning Quick Links even though it hasn't even shown up yet.
The specific Home Notice components only provide the title text to `<CelebrateNotice />` – it in turn uses the value of `displayChecklist` to determine the second line of descriptive text. When we refactored in #40368, we stopped passing down `displayChecklist`; this PR restores it to correct the logic of that second line display.
This will be followed up with more notice refactoring; they really should be 100% responsible for all content passed to `<CelebrateNotice />`, so that we can get rid of this sort of logic, and also remove the …
> My Home: Have notices correctly refer to the quick links or checklist.

- client/lib/analytics/ad-tracking/constants.js
- client/lib/analytics/ad-tracking/record-order.js
- client/my-sites/checkout/checkout/composite-checkout.js
Add Google Analytics Enhanced Ecommerce tracking for Calypso purchases.
```
// TODO:
// - should we only send value in usd?
// - product.cost instead of product.item_total?
// - are there existing constants for brand?
// - do we differentiate by brand in GA in that way?
```
* Install the [Google Analytics Debugger](https://chrome.google.com/webstore/detail/google-analytics-debugger/jnkmfdileelhofjcijamephohjechhna?hl=en) in Chrome.
* Setup your browser to show debug info and send tracking info. In the console, run the folllowing (might require a refresh after):
```
localStorage.setItem( 'debug', 'calypso:analytics*' );
document.cookie = 'flags=a8c-analytics.on,gdpr-banner,google-analytics,ad-tracking; path=/; domain=.' + document.location.hostname.split( '.' ).slice( -2 ).join( '.' ); …
```
> Add Google Analytics Enhanced Ecommerce purchase tracking

- client/landing/gutenboarding/components/header/index.tsx
- client/landing/gutenboarding/components/signup-form/index.tsx
- client/landing/gutenboarding/components/signup-form/style.scss
- client/landing/gutenboarding/index.tsx
- client/landing/gutenboarding/path.ts
- client/login/controller.js
- client/login/wp-login/index.jsx
- client/login/wp-login/login-links.jsx
- client/login/wp-login/style.scss
Getting the signup and login forms into reasonable shape according to the tips in https://github.com/Automattic/wp-calypso/issues/40769 (As much as we can):
- tweaking spacing and colours of text and form controls
- ensuring that _"Create account"_ on the the login page triggers the signup modal. 
We might not get all this stuff 100% before the call to testing. Let's keep what we've missed in mind for the next iteration.
1. Power up this branch and head over to `/gutenboarding`
2. Visit the signup form
3. Now visit the login page (username, password and 2fa)
4. It shouldn't look like 70s wallpaper, but sorta like Gutenboarding.
5. Now, click on **Already have an account? Log in** 
6. Then click on **Create a new account**
7. You should return to Gutenboarding and the signup modal will …
> Gutenboarding: Signup/Login design fixes

- client/landing/gutenboarding/components/close-button/index.tsx
- client/landing/gutenboarding/components/domain-picker-button/index.tsx
- client/landing/gutenboarding/components/domain-picker-button/style.scss
- client/landing/gutenboarding/components/domain-picker/index.tsx
- client/landing/gutenboarding/components/domain-picker/style.scss
- client/landing/gutenboarding/components/domain-picker/suggestion-item.tsx
Quoting https://github.com/Automattic/wp-calypso/pull/40742#issuecomment-609659426:
> ![image](https://user-images.githubusercontent.com/14988353/78539535-12f78580-7836-11ea-87f8-82fb2cb169e9.png)
> 
> Update from today. I've done the following:
> 
> * [x] Restyled the suggestion items as radio input fields, with checked, focus, and hover states
> * [x] Updated the domain form to use `onDomainSelect` when selecting a paid domain instead of `onDomainPurchase` (this will require the rest of the domain flow to be in place as it means cutting off the current domain flow), but it ensures that selecting a domain works as expected
> * [x] Add a popover container so that the popover can be fixed in position matching the positioning in the Figma — this ensures that the popover doesn't move around …
> Gutenboarding: update domain picker styling

- client/landing/gutenboarding/onboarding-block/design-selector/index.tsx
- client/landing/gutenboarding/onboarding-block/style-preview/viewport-select.tsx
Part of #40757
* Add accessible text to viewport selectors (previously only icons).
* Rather than a redundant `alt` attribute, use `aria-labelledby` to indicate the text label for design images.
See [`aria-labelledby` docs](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_aria-labelledby_attribute).
* [`/gutenboarding`](https://calypso.live/gutenboarding?branch=gutenboarding/a11y-texts)
* Check design image previews and viewport icons
* Visually identical
* Design images have `aria-labelledby` that points to the right element.
* Viewport selectors have a hidden `<span>` with a good text description.
> Gutenboarding: Improve design/preview accessibility

- client/landing/gutenboarding/components/domain-picker-button/index.tsx
- client/landing/gutenboarding/components/domain-picker/index.tsx
- client/landing/gutenboarding/components/header/index.tsx
- client/landing/gutenboarding/stores/onboard/actions.ts
- client/landing/gutenboarding/stores/onboard/index.ts
- client/landing/gutenboarding/stores/onboard/reducer.ts
**Merge only after #40742!**
Follow-up to #40742.
Removes the `onDomainPurchase` prop from the domain picker, and some related helpers.
This is meant to reconcile #40742 with #40813.
cc @razvanpapadopol 
- http://calypso.localhost:3000/gutenboarding
- Verify that the domain picker works as before.
- Test the entire flow up until site creation, with both a paid and a free domain.
> Gutenboarding: Drop onDomainPurchase and friends

- client/my-sites/plans/current-plan/purchases-listing.jsx
* Add support for all jetpack product purchases on the My Plans page. 
After:
* Buy a jetpack product other then jetpack Backup. This is currently only possible in calypso dev.
* Notice that the my-plans page looks as expected. 
Fixes #
> My Plan: Add support for all Jetpack Products not just Backup

- client/my-sites/media-library/list-item-video.jsx
- client/my-sites/media-library/test/list-item-video.jsx
This PR makes `list-item-video.jsx` use `<MediaImage/>` component to display video thumbnails
I think video thumbnails are only generated when using VideoPress, which means they're also available publicly. Therefore the only way to test this PR is to:
1. Get a public AT site, enable Videopress
1. Upload a video in /media and confirm it got processed using VideoPress
1. Wait until it's encoded (progress visible in preview)
1. Refresh the page
1. Confirm the thumbnail is displayed correctly
1. Make the site private
1. Confirm the thumbnail is still displayed correctly
> [Private sites] Use <MediaFile /> to display video thumbnails

- client/landing/gutenboarding/onboarding-block/acquire-intent/style.scss
- client/landing/gutenboarding/onboarding-block/acquire-intent/vertical-select/index.tsx
- client/landing/gutenboarding/onboarding-block/acquire-intent/vertical-select/style.scss
- client/landing/gutenboarding/onboarding-block/style-preview/style.scss
This PR takes React out of the empty-input state management and uses CSS `:empty` pseudo-selector instead. This results in instantaneous (read: glitch-free) changes to the UI when the state changes from empty <-> not-empty.
Please visit [here](https://hash-9183e9931350194d95486f280bef00a6673e0544.calypso.live/gutenboarding), test against each of the issues mentioned above and check whatever passes.
> Visual fixes for #40757

- client/jetpack-connect/plans.jsx
- client/my-sites/checkout/checkout/index.jsx
- client/my-sites/plans/current-plan/controller.jsx
- client/my-sites/plans/current-plan/index.jsx
This PR applies to all Jetpack Product, thus pinging for reviews out friends from Backups and Scan, thank you!
* display product info in the route at checkout:, e.g. `/checkout/:site/jetpack_scan` 
* correct the Thank You modal type displayed after purchasing products and plans during the Jetpack Connect flow, without which we show the Free plan modal. The change determines the url directly, including product information as opposed to reading it from the cookies, which is tricky due to the many redirects that happen during the Jetpack connection flow. 
* Start at `/jetpack/connect/plans/:site`,
* purchase a product
* verify that the checkout url contains product info
* verify the relevance of the Thank you note
Fixes https://github.com/Automattic/wp-calypso/issues/40753
> Jetpack Connect: adapt the post-checkout Thank you modal to specific Products

- client/jetpack-connect/plans.jsx
- client/my-sites/checkout/checkout/index.jsx
- client/my-sites/plans/current-plan/controller.jsx
- client/my-sites/plans/current-plan/index.jsx
Reverts Automattic/wp-calypso#40794
Think it was breaking the connect purchase flow... buttons not working.
> Revert "Jetpack Connect: adapt the post-checkout Thank you modal to specific Products"

- client/me/profile-links/index.jsx
Removes the ListEnd at the end of `/me`
Scroll to the bottom of Profile Links and verify that it's no longer there.
**Before:**
**After:**
cc @jancavan, @gwwar 
Fixes #40686
> Me: Remove List End

- client/components/happiness-engineers-tray/style.scss
* Specify `align-items: flex-start;` so support Gravatars do not stretch to fill the height of the container.
**Before**
**After**
* On a Business site, go to Hosting Configuration
* The support card Gravatars should appear as circles. Resize the screen to ensure they stay circles at multiple screen sizes.
* These also appear on the support card at `/help`
Fixes #40825
> Support Card: Prevent items from stretching

- client/extensions/woocommerce/app/store-stats/referrers/chart/style.scss
- client/extensions/woocommerce/app/store-stats/store-stats-orders-chart/style.scss
- client/extensions/woocommerce/components/delta/style.scss
* See #39596 -- auditing and replacing uses of font-weight: 300 with 400 for better readability throughout Calypso
**Before**
**After**
* Open a site that has WooCommerce installed
* Go to the Store tab and note percentages in stats. They should be using 400-weight font rather than 300 now.
> WooCommerce: Update font weights to avoid using font-weight 300

- client/landing/jetpack-cloud/components/site-offset/README.md
- client/landing/jetpack-cloud/components/site-offset/context.tsx
- client/landing/jetpack-cloud/components/site-offset/index.tsx
- client/landing/jetpack-cloud/sections/backups/controller.js
- client/landing/jetpack-cloud/sections/backups/index.js
- client/landing/jetpack-cloud/sections/backups/rewind-flow/index.tsx
* We need site offsets a lot in various places since we are splitting up backup/activity log functions across many different components
* Adds a Context Provider to easily access an `applySiteOffset` function that has already had the correct information loaded
1. On a test site that has a different timezone than your own
2. Navigate to the start of the download or restore flow on the branch
3. Navigate to `cloud.jetpack.com` with the same path as from step 2
4. Verify both display the dates the same in the same timezone
> Add Jetpack Cloud ApplySiteOffset Context Provider

- client/landing/gutenboarding/onboarding-block/create-site/index.tsx
- client/landing/gutenboarding/onboarding-block/create-site/style.scss
Very, very, very, very, very first iteration of Loady McLoadface
- There is a flash of blue: the current signup backend before we're shipped off to the plans page.
- Yes, the progress is fake
- Blue or brown for the progress bar color? 💊 
This PR doesn't work that well right now, but you can still test by creating a site.
Even better, you can [comment out the line](https://github.com/Automattic/wp-calypso/pull/40831/files#diff-25ff1d094074b9d9d1f5a148c6f7c363R59)
`{ shouldCreateAndRedirect && <CreateAndRedirect /> }`
to work/view the screen.
Fixes #39287
> Gutenboarding: site creation progress/loading page

- client/landing/gutenboarding/onboarding-block/design-selector/style.scss
Requested in p1586295444204100-slack-gutenboarding so that the border is more legible, particularly against dark layouts.
* Update border of designs in the design selector grid in Gutenboarding to be 2px
* Go to http://calypso.localhost:3000/new/ and proceed to the design selector step.
* Check that the grey and blue hover state border of the designs is now 2px
Fixes #
> Gutenboarding: Update border of designs in design selector grid to be 2px

- client/landing/gutenboarding/onboarding-block/design-selector/style.scss
* Add `float` based styles for the design selector for older browsers that don't support grid properly (IE11) (approach based on [this MDN article](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Grid_Layout/CSS_Grid_and_Progressive_Enhancement))
* Use a feature query for grid sizing
Before in IE11:
After:
* Go to https://calypso.live/?branch=update/gutenboarding-design-selector-to-support-ie-11 and navigate to `/new` and fill out the intent gathering step so that you get to the design selector at `/new/design`
* Make sure that the layout matches what is currently in wpcalypso / staging in Chrome, FF, Safari.
* Test across a range of window sizes (small should be 2 column, large 3 column, and very wide 4 column)
* Test in IE11 (or Browserstack IE11) and make sure that the layout …
> Gutenboarding: Adapt grid layout in design selection step to floats to support IE 11

- client/lib/wpcom-undocumented/lib/undocumented.js
- client/my-sites/media-library/proxied-image.tsx
This is related to Coming Soon/Private atomic sites project (paObgF-Ui-p2). The rationale for this change is described in D41360-code.
This PR is a Calypso counterpart of D41360-code that makes sure we use a customized retry policy for private media files, if the request returned HTTP status 429.
1. Create a new private atomic site (p58i-8OX-p2)
1. Go to /media
1. Confirm the files are being correctly loaded
1. If you see some gray squares instead of actual thumbnails, confirm they're loaded properly after refreshing the page (that's an API issue fixed in another diff)
> [Private media] Use exponential backoff when API returns error 429

- client/landing/gutenboarding/components/domain-picker-button/index.tsx
- client/landing/gutenboarding/components/domain-picker-button/style.scss
- client/landing/gutenboarding/components/header/style.scss
* Updated the WordPress logo to be black
* Shrunk the arrow on the domain picker
* Navigate to /new/design
> Gutenboarding: Updating color of WordPress logo and dropdown arrow fixes

- client/devdocs/design/typography.jsx
* This specifies font weights of 400 or greater to ensure we're no longer using too-thin fonts for better readability.
* See #39596 
Visual ref:
* Navigate to `/devdocs/typography` and note the text changes.
> Devdocs: Update Typography to specify font weights of 400 or greater

- client/landing/jetpack-cloud/components/daily-backup-status/index.jsx
- client/landing/jetpack-cloud/components/date-picker/index.jsx
- client/landing/jetpack-cloud/sections/backups/main.jsx
**[ Small review ]**
Update the time format on DailyBackupStatus to match the user locale 'LT', and also, update the DatePicker to use today date with the site time zone applied to always work in the same time zone.
Fixed a minor issue (avoid to add am/pm, 'LT' format add it automatically). Before:
After:
- Check that everything works as before, the backup time shows up in its correct locale format (Except on the Backup Scheduled view, the scheduled and last backup date/time are fake)
> Update the time format to match the user locale 'LT' and update DatePicker today TZ

- client/blocks/product-plan-overlap-notices/index.jsx
* Adds tracking for managing purchases on product overlap notice.
* Set up a connected Jetpack site with a conflicting purchase.
* When the conflict notice appears, click one of the links.
* Observe the tracking event.
Fixes 1151678672052943-as-1169766089949081.
> Adds tracking to viewing purchase on product overlap notice

- client/my-sites/checkout/checkout/checkout-container.jsx
- client/my-sites/checkout/checkout/style.scss
In the checkout screen, drop the specific treatment of the Gutenboarding flow, and rely on the existing logic for the old signup.
This allows both fixing #40827 dropping some duplicated logic, rather than adding more duplicated logic to fix that issue.
Furthermore, the pre-existing signup flow had a somewhat more complex handling of the header (depending on payment state). I think it makes sense to apply the same treatment to the header regardless of whether the user is coming from the 'old' signup flow, or from Gutenboarding.
If there are any styling differences for the checkout header between Gutenboarding and the old signup flow (other than maybe the Back button), I'd argue that we should probably consider them circumstantial -- I don't think there's a strong argument why the copy and …
> Checkout: Re-use existing signup header for Gutenboarding

- apps/full-site-editing/full-site-editing-plugin/wpcom-block-editor-nux/class-wpcom-block-editor-nux.php
Follow-up/hotfix to #40828 :man_facepalming: 
Noticed when trying to commit the corresponding diff (D41466-code). :roll_eyes: 
Weird that our commit hooks didn't catch this :confused:  
Already fixed on WP.com (as part of D41466-code).
N/A
> Block Editor: Fix trailing comma

- client/jetpack-connect/controller.js
- client/jetpack-connect/plans.jsx
- client/state/jetpack-connect/constants.js
* This change facilitates personalized UX flow when purchasing Search via Jetpack Connect e.g from. the LP. 
The sequence is as follows: chose Search on the LP -> connect your site -> checkout focused on Search. It skips the canonical (connection) plans page or redirect to `/plans` in Calypso.
* go to `jetpack.com/upgrade/search`
* after being redirected to JPC, input site url (change WP.com to local build in the url)
* verify redirect to checkout with Search in cart ( annual option).
Try sites with and without paid plans and without Jetpack installed and/or activated. 
Also, verify that the Backup experience is not broken (start from `jetpack.com/upgrade/backup`)
Verify Tracks being recorded: `recordPageView(  "/jetpack/connect/jetpack_search", "Jetpack Connect" ]`
Note: it will work for …
> Jetpack Connect: enable redirect to checkout for preselected Jetpack Search product

- client/landing/gutenboarding/components/signup-form/style.scss
- client/login/wp-login/style.scss
A few tweaks to get the signup and login forms looking better in mobile:
- spacing between text in signup
- width of continue button in login for mobile
Fixes #40907
> Gutenboarding: tweak account creation UI for mobile

- client/landing/gutenboarding/onboarding-block/style-preview/style.scss
***Note: This layout is still a bit broken on <1000px width viewports.*** Mobile and smaller screen layouts can be left to later PRs.
* Update CSS grid used on the style step in Gutenboarding to fallback to floats on browsers that don't support grid (IE 11)
* Replace flexbox with relative / absolute positioned elements in the font buttons to fix vertical alignment in IE11
Before:
After:
Note: the buttons aren't _quite_ right at the left in the IE11 version, but it's much closer now.
* Go to /new and proceed to the font selection step. Double-check that it looks the same as in master in FF, Chrome, Safari, and looks as close as possible to it in IE11.
Fixes #
> Gutenboarding: Update font selection styling to support IE 11

- client/signup/config/flows.js
Part of https://github.com/Automattic/wp-calypso/issues/40646
The current signup flows still use the old `/checklist` route as destination path which ends up [redirecting to `/home`](https://github.com/Automattic/wp-calypso/blob/a4616438bcb848e97b784fa6d55ba4e9c5cb3d21/client/my-sites/checklist/controller.jsx#L29-L32) since all sites created during signup are currently eligible for My Home (it is now enabled for all WP.com sites).
This PR updates the destination URL of the signup flows to `/home` so there is less code pointing to the legacy checklist section (which we aim to remove completely once we finish deleting existing code using it).
- Create a site using any of the signup flows modified by this PR:
- `/start/business`
- `/start/premium`
- `/start/personal`
- `/start/free`
- …
> Redirect to My Home after completing signup

- client/my-sites/checklist/wpcom-checklist/component.jsx
Part of https://github.com/Automattic/wp-calypso/issues/40646
While auditing where we are still using the legacy checklist section, I noted the checklist is setting a `/checklist/:site` path in [the `backToCheckList` function](https://github.com/Automattic/wp-calypso/blob/c9a8c341f663cd1bebd0bd3459a1edae734db0f3/client/my-sites/checklist/wpcom-checklist/component.jsx#L190-L192) which is later passed as a prop when rendering the `Task` component ([example](https://github.com/Automattic/wp-calypso/blob/c9a8c341f663cd1bebd0bd3459a1edae734db0f3/client/my-sites/checklist/wpcom-checklist/component.jsx#L762)).
However, seems [the `Task` component](https://github.com/Automattic/wp-calypso/blob/c9a8c341f663cd1bebd0bd3459a1edae734db0f3/client/components/checklist/task.js) does not use that prop at …
> Remove unused backToChecklist function

- client/landing/gutenboarding/components/signup-form/style.scss
Fix the bottom spacing issue of signup form on Safari browser
Fixes #40865
> Gutenboarding: fix signup form spacing on Safari

- client/landing/gutenboarding/components/domain-picker/index.tsx
- client/landing/gutenboarding/components/domain-picker/style.scss
* Domain search input:
* Should have a gray background.
* Search icon should be on the right.
* Placeholder text color should be black
* When focused, it should have a 2px blue border.
* The text **Free for the first year with any paid plan** should appear under the header title.
* **Recommended** badge should have a 2px border radius.
* **Free** text should have green color, but only on paid domains.
* The rest are whitespace/margin adjustments to closely match the design specs.
Note: Blue-color TLD will be a separate PR.
* Open up `/gutenboarding`.
* Ensure the domain picker now reflects the changes as listed above and matches closely to the current design specs.
In comparison to the design specs:
> Gutenboarding: Updated domain picker styling.

- client/blocks/support-article-dialog/dialog.jsx
This PR updates the Support Article Dialog to a functional component and also adds support to scroll to an anchor point if specified in the postUrl. 
So for example: 
| Without Anchor | Support Page with Anchor |
| ![Apr-08-2020 14-45-20](https://user-images.githubusercontent.com/1270189/78836766-9b496800-79a7-11ea-82f6-d95917bd2909.gif)  | ![Apr-08-2020 14-42-48](https://user-images.githubusercontent.com/1270189/78836579-3d1c8500-79a7-11ea-9b31-ac971fb4468a.gif) |
- Spin up the branch
- In console ```dispatch( { type: 'SUPPORT_ARTICLE_DIALOG_OPEN', postId: 145498, postUrl: 'https://support.wordpress.com/free-photo-library/' } )``` opens the support dialog to the top of the page content.
- In console ```dispatch( { type: 'SUPPORT_ARTICLE_DIALOG_OPEN', …
```
> Support Article Dialog: add support to scroll to anchor and refactor to functional component

- client/my-sites/checkout/checkout-thank-you/header.jsx
* The Manage Domain button was missing from the thank you page after purchase on atomic site. Turned out that we're just skipping any jetpack site so here's a fix for it.
* Purchase a domain (or something) for an Atomic site. Without this PR the Manage Domain button would be missing.
> Show the manage button on thank you pages for Atomic sites

- apps/wpcom-block-editor/src/wpcom/features/tracking.js
When you remove for example "Columns" block right now, we only fire a single event for removing the Columns block.
* This PR now fires an event for all inner blocks recursively. If you for example remove Columns, you will get events for:
- Columns
- Column (fired for every column present)
- Possibly other deeper blocks, like Paragraph or Image inside one of the Column blocks
- We already track block insertions this way (recursively) so it makes sense to apply it for removals too to get an accurate view on insertions/removals
* Test in D41587-code, which is generated from this PR and has detailed testing instructions.
Fixes #40498
> wpcom-block-editor: track block removals recursively

- client/blocks/reader-site-notification-settings/index.jsx
- client/blocks/reader-site-notification-settings/style.scss
* Tidies up the look of the Reader settings by swapping regular form toggles for compact, and moving them to the left of the labels.
* Also removes the notification Gridicon, since it added visual cruft.
* Adds `FormLabel`s around each label with IDs for accessibility. I'm not sure how effective these are, however, as they don't trigger the toggle with a click the way a normal HTML checkbox would. But hopefully this at least helps connect the label text to the toggle itself.
**Before**
**After**
* Navigate to `/following/manage` and click the Settings menu next to one of your followed blogs.
* Note the changes in the settings screen.
Fixes #40668
> Reader: Fix settings toggles

- client/my-sites/checkout/composite-checkout/composite-checkout.js
This causes the error message that is displayed (in composite checkout) when domain contact details validation fails to disappear after 5 seconds.
Fixes #40220
- Add a domain to your cart in calypso and visit composite checkout.
- Proceed to the contact details step.
- Leave at least some contact fields empty.
- Press "Continue" on the step.
- Verify that you see the "We could not validate your contact information. Please review and update all the highlighted fields." error message appear.
- Verify that the message disappears after 5 seconds.
> composite-checkout: Hide contact validation error message after delay

- client/blocks/inline-help/inline-help-search-card.jsx
Fixes https://github.com/Automattic/wp-calypso/issues/40938
Most native mobile devices will not let the soft keyboard appear without an explicit user tap. Previously when clicking on inline help, the autofocus would trigger the soft keyboard to appear for a moment before disappearing on Chrome/Pixel4 causing a visually distracting jank.
This PR removes autofocus since mobile users will need to tap on the search bar anyway.
- On a native device, click on inline help at WordPress.com. Verify that the search input flashes, causing the soft keyboard to (maybe visually flash) before disappearing
- Use the calypso.live link https://calypso.live/?branch=fix/inline-help-focus and click on inline help using a native device
- The search bar should no longer autofocus (no jank from the keyboard …
> Inline Help: remove unfriendly autofocus from search box

- client/lib/purchases/index.js
In #40270, I modified all renewal links to use a URL rather than adding
a product to the cart directly; this puts the responsibility of adding
the product in the hands on checkout itself.
Unfortunately, there's a product with a slug of
`no-adverts/no-adverts.php`, which, if put in the URL, causes a calypso
routing error and the user will see a blank page.
The cart code is already set up to handle this thanks to a condition
added in #15043, so we just need to make sure to encode the product slug
`no-adverts/no-adverts.php` as `no-ads`. This PR makes that change.
Props to @sandymcfadden for noticing this regression!
- Use the admin to add a "No Ads" upgrade to a site.
- Visit http://calypso.localhost:3000/me/purchases
- Click "No Ads" and then click "Renew now".
- Verify that you are …
> Encode no-ads product slug for renewal links

- client/landing/jetpack-cloud/components/sidebar/index.jsx
- client/landing/jetpack-cloud/sections/backups/backup-activity-log/index.tsx
- client/landing/jetpack-cloud/sections/backups/controller.js
- client/landing/jetpack-cloud/sections/backups/index.js
- client/landing/jetpack-cloud/sections/backups/paths.ts
* Add basic route support for `/backups/activity` and placeholder page
2. Verify site selector appears, you are taken to placeholder page `/backups/activity/:siteSlug`
3. Reload page, verify route with site slug works
4. From a different section ( scan, backup status, etc. ) verify that Backup > Activity Log in the sidebar works as well
> Add basic Jetpack Cloud Activity Log route and placeholder page

- client/me/concierge/shared/primary-header.js
- client/me/help/contact-form-notice/live-chat-closure.jsx
- client/me/help/help-contact/index.jsx
Shows Easter closure notices in Live Chat and Quick Start.
Go to http://calypso.localhost:3000/help/contact:
- The existing "Limited chat availability" notice should show
- Set your computer's clock to April 12 at 0:00 UTC — the "Live chat will be closed for Easter" notice should show
- Set your computer's clock to April 12 at 6:00 UTC — the "Live chat closed for Easter" notice should show
- Set your computer's clock to April 13 at 6:00 UTC — the "Limited chat availability" notice should be back up
Go to http://calypso.localhost:3000/me/concierge and pick a site:
- The "**Note**: Quick Start sessions will be closed for Easter..." notice should show
- Set your computer's clock to April 12 at 6:00 UTC — the "**Note**: Quick Start sessions are closed for Easter..." notice should show
- Set …
> Add Easter closure notices for Chat and Quick Start

- client/landing/jetpack-cloud/components/activity-card-list/index.jsx
- client/landing/jetpack-cloud/components/activity-card-list/style.scss
- client/landing/jetpack-cloud/sections/backups/main.jsx
- client/landing/jetpack-cloud/sections/backups/style.scss
* This PR creates a new component to replace the Activity List on the main backups page. The new component is easily reusable and will be integrated into several other places that this list is utilized.
* Also ... translate a few strings that were not done earlier
* Load up the main backups page, and click the calendar icon at the top to select a date range. Once you select a range, the view should switch to a list of activity cards.
* Play with the filterbar. Does everything work as expected? Great!
> Jetpack Cloud: Create ActivityCardList component and integrate into backups

- apps/wpcom-block-editor/src/wpcom/features/tracking/track-record-event.js
This PR picks up the user locale property from the window object and populates the event with this value when it's recorded
**Test in a Simple site**
* Apply these changes in your testing site
* Edit a posy
* start to insert a block from blocks list inserter
* generate a no-results event
Confirm that the user locale is propagated in the event object.
> Tracking: Populate events with user locale

- client/gutenberg/editor/calypsoify-iframe.tsx
`<CalypsoifyIframe>` waits for the `WindowActions.Loaded` message to be sent by the child window before marking the iframe as loaded. And if this hasn't happened by the time the `<iframe>`'s load event has fired, then that counts as a failure and we abandon the iframe editor approach.
We've found that IE was always falling back to the wp-admin editor, and that's because the `WindowActions.Loaded` message was being sent _after_ the `<iframe>` load event is fired.
This change spends some time polling for the flag set by `WindowActions.Loaded` if it isn't set by the time the `<iframe>` says it's loaded. This seems reasonable to me because it seems like a race condition to me whether the JS that posts the message in the child window will get to it in time.
This PR also re-enables IE e2e tests …
> Fix: Wait longer for the iFrame to load for IE

- client/landing/gutenboarding/components/domain-picker/style.scss
- client/landing/gutenboarding/components/domain-picker/suggestion-item.tsx
* Highlight domain tld.
Well, not exactly TLD, if it's a subdomain like `.wordpress.com`, the whole domain and tld gets highlighted. So, I don't know how to name the variables, but I tried. :)
* Open the domain picker on `/new`. Domain TLDs should be highlighted.
> Gutenboarding: Highlight domain TLD.

- client/landing/jetpack-cloud/sections/backups/main.jsx
* This PR sends site capabilities into the component from redux, instead of checking for the capability slug in the connect function. The previous method was causing trouble in certain circumstances.
* Also, use lodash `includes` for a bit of added type safety.
* Also, update the other usage of `includes` in main.jsx.
* Load up backups page. There should be no effect and everything should look/work normally, unless the site was broken previously.
> Jetpack Cloud: Do not use includes in connect

- client/landing/jetpack-cloud/sections/backups/rewind-flow/style.scss
- client/landing/jetpack-cloud/sections/backups/style.scss
Currently, after switching away to a different section, and back to backups, the page styles will change and the `main` will lose it's `margin-left: auto`, and slide to the left of the page.
This PR fixes the left margin of the `main` element for the backups page, and the restore/download pages. 
* Load up backup section for an active site. Click on scanner, then click back to backups. The alignment of the page should remain the same as it was before navigating away.
* Test the same thing for the restore page, and the download page _initial styles_.
**BAD:**
**GOOD:**
> Jetpack Cloud: Fix alignment of main element for backups, restores, downloads

- client/components/web-preview/content.jsx
This is a PR complementary to Automattic/wpcomsh#447
Problem: Calypso users may or may not be not authenticated against the remote. If they're not, they won't see the site preview. This PR provides bare minimum "no dead ends" user experience for that case - the user will see a customized error message and a login button as on the screenshot below.
This certainly isn't perfect, but at least makes the preview functional and is a good starting point for future iterations.
Follow the test plan in Automattic/wpcomsh#447
> [Private sites] Add support for in-preview authorization

- client/my-sites/site-settings/form-general.jsx
- client/my-sites/site-settings/seo-settings/form.jsx
This PR improves the copy related to private sites.
**Settings page**
With this PR, it should provide an intuitive copy that distinct between the private and coming soon modes.
**SEO settings page**
Before this PR, it always displays the Coming Soon copy, even if the site is just private:
With this PR it displays appropriate copy:
> [Private sites] Copy updates

- client/components/product-card/style.scss
- client/jetpack-connect/style.scss
- client/my-sites/plans-features-main/style.scss
This ensures that the Solutions cards during Jetpack Connect break exactly like the Plans ones do.
Follow the Jetpack Connect route to the Plans stage: `/jetpack/connect/plans/monthly/site`
At this point, verify that no issues occur with the columns, no matter how you resize the screen or how many there are. They should stack when the content is too small to fit in columns, but otherwise appear like this.
cc @keoshi, @tyxla, @simison 
Fixes #40679
> Jetpack Connect: Arrange Solution Cards Side-by-Side

- client/landing/jetpack-cloud/components/daily-backup-status/index.jsx
- client/landing/jetpack-cloud/components/daily-backup-status/style.scss
- client/landing/jetpack-cloud/sections/backups/main.jsx
Update the backup status views when:
- We don't have a backup on the selected date
- The backup from today is scheduled (it calculates the next expected time plus 3 hours of safety margin)
- Some styles applied.
Backup scheduled:
Failed backup (copy updated):
No Backup:
- Apply these changes
- Check the copies for the different views: Backup Failed, No Backup, Scheduled Backup
- Check the expected time (the remaining hours) if you have a scheduled backup for today
You need to have a Jetpack site with a backup subscription (or a plan with it). To have a:
- **Failed Backup scenario:** disconnect the site for one, so you'll get a failed backup. Also, you can modify the props of the component, change `rewind__backup_complete_full` by `rewind__backup_error`
- **No Backup scenario:** cancel …
> Update backup status views: no backup, failed backup, scheduled backup

- client/components/site-selector/index.jsx
* add special handling for the backups download, restore, and detail paths so switching sites sets the path back to `/backups`
1. Navigate to a backup download page( `/backups/:site/download/:rewindId` )
2. Switch to a different site
3. Verify you are taken back to `/backups/:newSite`
4. repeat steps 1-3 for restore and detail
> Fix switching sites from Jetpack Cloud backups download, restore, or detail

- client/state/document-head/selectors.js
- config/_shared.json
- config/jetpack-cloud-development.json
- config/jetpack-cloud-production.json
- config/jetpack-cloud-stage.json
* Updates site name to be controlled by config, to allow Jetpack Cloud to display Jetpack.com.
* Build a Calypso env (`yarn start`).
* Load `calypso.localhost:3000` and view site title.
* Build a Jetpack Cloud env (`CALYPSO_ENV=jetpack-cloud-development yarn start`).
* Load `http://jetpack.cloud.localhost:3000` and view site title.
Site title should be `WordPress.com` on all environments except Cloud, which has `Jetpack.com`.
Fixes 1156570014567299-as-1164112743175977.
> Makes site name controlled by config

- client/my-sites/checkout/composite-checkout/record-analytics.js
- client/my-sites/checkout/composite-checkout/wpcom/hooks/wpcom-store.ts
- packages/composite-checkout/src/lib/payment-methods/stripe-credit-card-fields.js
The internal `a8c_checkout_error` event (resulting in the `calypso_checkout_composite_error` Tracks event) is used for two different events: a stripe field validation error and a contact field validation error (the latter of which is actually never called). In addition, the event's name is not very descriptive, making it hard to triage these errors in Tracks.
This change modifies the events to be unique and descriptive instead, replacing `calypso_checkout_composite_error` with `calypso_checkout_composite_stripe_field_invalid_error` and and removing the unused instance.
- Sandbox the store so that you can load the credit card form.
- Load calypso and run `localStorage.setItem('debug', 'calypso:analytics')` in your browser console. Then reload the page.
- Visit composite checkout, enter an …
> composite-checkout: Make unique Tracks events for stripe/contact field validation errors

- config/horizon.json
- config/production.json
- config/stage.json
* We've been working on the auto-renew toggle for a while now and it is good enough to enable on production now
Here are all PRs related to the auto-renew toggle thus far:
* https://github.com/Automattic/wp-calypso/pull/40012
* https://github.com/Automattic/wp-calypso/pull/40514
* https://github.com/Automattic/wp-calypso/pull/40519
* https://github.com/Automattic/wp-calypso/pull/40522
* https://github.com/Automattic/wp-calypso/pull/40527
* https://github.com/Automattic/wp-calypso/pull/40660
* Verify that on the stage/horizon/production environment there is auto-renew toggle in the domain settings screen
> Enable auto-renew toggle in domain settings screen

- client/my-sites/post-relative-time-status/index.jsx
This ensures that the scheduled time clearly states when the post is due to be released.
A few things to check:
- when the post is due to be released within a week, it shouldn't give the full date, but it should give the time (I would find this very helpful as someone who tries to schedule posts weekly at the same time, so I'm sure many others would too)
- when the post is due to be released after a week, it should give the full date
- "scheduled in" should be replaced with "scheduled for" (the latter gave the impression that was when the "Schedule" button was actually clicked, when that isn't what it conveys)
**Before:**
**After:**
Note: I made a few changes so that it displays the date and then "at" (eg. `27 April 2020 at 02:00`) so that it's consistent with the wording for a post due …
> Posts: Improve Clarity of Scheduled Time

- client/me/purchases/manage-purchase/index.jsx
- client/me/purchases/purchase-item/index.jsx
* Load up Calypso. 
* Buy Scan and Search Products. 
Visit http://calypso.localhost:3000/me/purchases 
navigate to the scan and search purchase. 
Notice the new icons. 
Fixes https://github.com/Automattic/wp-calypso/issues/40550
> Purchases: Add icons to purchase pages

- client/my-sites/checkout/composite-checkout/contact-validation.js
* Adjust the logic in the contact validation callback in composite checkout to ensure that if the request to the endpoint fails, we do not allow checkout to proceed. (I'm not totally sure why the current logic doesn't block this.)
The best way I can think of to test this is locally. To see the bug using the following steps it may be necessary to apply D41243-code to your sandbox, since that diff introduces max version numbers to the validation endpoint. (The max version number is what exposed the bug, but it would occur with any HTTP failure code.)
1. Run calypso with `ENABLE_FEATURES=composite-checkout-force npm start`
2. Do not apply the PR -- first let's see the buggy behavior.
3. To break validation on purpose make the following edit in …
> Composite checkout: Do not validate contact details if the endpoint call fails

- client/landing/jetpack-cloud/components/date-picker/index.jsx
- client/landing/jetpack-cloud/sections/backups/controller.js
- client/landing/jetpack-cloud/sections/backups/main.jsx
- client/landing/jetpack-cloud/sections/backups/paths.ts
We need to keep the history when we are browsing through the backup dates, for example, if we have on the Backup Status page and we go to the Download/Restore section of that backup and then we go back, we didn't have the history. We also couldn't copy or share the link if we needed to. With this change, we can go through the dates of the backups and keep the history.
- The first time, we don't have a selected date, so we see the today backup status
- If we navigate through the dates, we can see in the URL the query parameter `date` with the selected date with this format `YYYYMMDD`
- If we change the parameter for another valid date (with the expected format), the Backup Status page loads the backup of this date.
- If we change the parameter for an invalid date …
> Jetpack Cloud: add url query parameter to Backup section with the selected date

- client/my-sites/checkout/composite-checkout/wpcom/hooks/has-domains.js
* In preparation for adding ccTLD forms to composite checkout, we need this hook for getting the domain names in the cart.
This should have no observable effect on checkout.
> Composite checkout: Add useDomainNamesInCart hook

- apps/wpcom-block-editor/src/wpcom/features/tracking/wpcom-block-picker-search-term-handler.js
This PR avoids recording the same event simply typing special keys such as arrows keys, F1, F2, ... SHIRT, etc, in the Blocks List inserter with the only exception the `ENTER` key.
1) Update your testing site with these changes (SB)
2) In your testing site, open the client dev console and set up the debug
```
> localStorage.setItem( 'debug', 'wpcom-block-editor*' )
```
A hard refresh is needed.
3) Open the Blocks List Inserter
4) Start to type until getting the no-results message
5) Look at the debug logs.
6) type special keys such as arrows key, `SHIFT`, `OPTION`, etc
7) Confirm that it avoids recording the event:
8) Confirm the exception when pressing the `ENTER` key.
https://github.com/Automattic/wp-calypso/issues/40978
D41759-code
> Tracking: avoiding record duplicated no-results events when typing

- client/landing/gutenboarding/onboarding-block/style-preview/index.tsx
- client/landing/gutenboarding/onboarding-block/style-preview/style.scss
- client/landing/gutenboarding/onboarding-block/style.scss
***WIP: Note this is a work in progress, and needs lots of tidying up and dealing with intricacies of the design!***
Attempting to style this step for mobile brings up lots of questions about how the design should be decomposed from the desktop layout through to mobile, across smaller screen sizes (a variety of tablet sizes, small laptop sizes, and people just not having their window maximised, like me 😄)
Here's a short GIF of where this PR currently sits:
This raises some questions:
* Add additional small breakpoint for the onboarding block to use `44px` horizontal margin at smaller screen sizes — gives a bit more wriggle room between mobile and small tablet sizes.
* Add an additional set of action buttons for mobile only on the style step (this is a bit hacky, but I couldn't think of a …
> Gutenboarding: Style font selection step for mobile

- client/lib/plans/plans-list.js
Fixes https://github.com/Automattic/wp-calypso/issues/38026
* Change "All free features" to "Dozens of free themes" for the Personal plan
* Go through signup flow and verify that on the plans step, you can see the dozens of free themes feature for the Personal plan.
* Click the tooltiip for the free themes feature and verify that it renders the right content
* Verify the feature changes for both control and variant of the planStepCopyUpdates test.
* Verify that there is no change to the feature list in Calypso /plans page while logged in.
> Signup: Change feature in Personal plan column

- client/landing/gutenboarding/components/signup-form/index.tsx
- client/login/wp-login/login-links.jsx
The Gutenboarding section was renamed from `gutenboarding` to `new` in https://github.com/Automattic/wp-calypso/pull/40810, and it looks like there were a couple of stray links that needed to be updated.
In `/log-in`:
* Update the `Email me a login link` to point to `new/link` instead of `gutenboarding/link` (fix 404 error)
* Update the fallback URL of the `Create a new account` button to `new/link`
* Update `loginRedirectUrl` to point to the last step that the user was previously working on, instead of automatically creating a site. This enables a fallback so that if a user uses the "Email me a login link" feature (or they have a passwordless account) and they open the email in a different browser context to the one they signed up with, they'll be redirected back to the beginning of the …
> Update Email me a login link URL for Gutenboarding

- client/my-sites/customer-home/style.scss
Loads the Recoleta font when visiting the "My Home" section and uses it on the header.
It fallbacks to the default Calypso serif font ([Noto serif](https://github.com/Automattic/wp-calypso/blob/d5304d75958d699394b47648d325eec3c2b72064/client/assets/stylesheets/shared/_typography.scss#L8)) on unsupported languages.
Note that we use a `font-display: swap` option in order to render all texts at the same time (this seems to be the [preferred method in other areas](https://github.com/Automattic/wp-calypso/search?q=font-display%3A+swap&unscoped_q=font-display%3A+swap)):
This introduces the first precedent of a header using a different font family than the rest of the Calypso pages, so I wonder if we should be consistent and use the font across all pages headers.
- Go to "My Home" and make sure …
> My Home: Add Recoleta font

- client/assets/stylesheets/shared/mixins/_placeholder.scss
- client/landing/gutenboarding/components/domain-picker/style.scss
- client/landing/gutenboarding/components/domain-picker/suggestion-item-placeholder.tsx
- client/landing/gutenboarding/components/domain-picker/suggestion-item.tsx
* Long domain text should wrap to the next line nicely.
* Radio button and price should vertical align to the top.
* Line height should match design.
* Don't break the TLD names.
* Break domain names using hyphens if any.
Also, some additional findings:
1. Domains API automatically trim long domain names.
2. Long TLD (visually, not based on char count from fixed-width font) are `.photography`, `.management` & `.apartment` on WP's offerings. See https://wordpress.com/support/domains/domain-pricing-and-available-tlds/
1. Open up `/new`.
2. Enter a long domain name in the domain picker.
3. See the suggestions wrap while TLD names don't break.
4. If a domain suggestion contains hyphen it should be used for breaking.
Fixes #40395
> Gutenboarding: Long domain text should wrap to next line nicely.

- client/landing/gutenboarding/components/close-button/index.tsx
- client/landing/gutenboarding/components/domain-picker-button/index.tsx
- client/landing/gutenboarding/components/domain-picker/index.tsx
* Auto-focus search input when domain picker is open.
* Also fixes clicking outside of domain picker not closing the domain picker.
Both fixes are in this PR because they are related to each other. See: https://github.com/Automattic/wp-calypso/issues/40890#issuecomment-611579912
1. Open `/new`.
2. Click on domain picker.
3. The search input should be automatically focused.
4. Clicking outside of the domain picker should close the domain picker.
Tabbing flow might be weird, because after tabbing out from search input focuses on close button instead of the list of domains. When testing this, I also noticed the list of domain options are not tabbable, a11y is not a priority right now so we'll have another round of PRs for accessibility fixes when its time to look into that.
Fixes #40395 …
> Gutenboarding: Auto-focus search input when domain picker is open.

- client/my-sites/site-settings/form-general.jsx
- client/my-sites/site-settings/wrap-settings-form.jsx
Private atomic sites feature should be disabled for users in `control` group of `ATPrivacy` test. This means their sites should not have the `wpcom_coming_soon` option. Unfortunately, it's getting stored if they save their settings while still using a simple site. This PR ensures that `wpcom_coming_soon` never gets sent if user does not belong to a proper test group.
1. Apply this PR
1. Create a simple site and launch it
1. While in `control` group of ATPrivacy, go to settings/general and save the form. Inspect POST request and confirm that `wpcom_coming_soon` was sent through
1. While in `test` group of ATPrivacy, go to settings/general and save the form. Inspect POST request and confirm that `wpcom_coming_soon` was **not** sent through
> [Private sites] Do not send wpcom_coming_soon value to the API for users in control group

- client/landing/gutenboarding/onboarding-block/design-selector/style.scss
This PR tweaks the CSS to make it responsive enough to work on mobiles. 
1. Navigate to up to [/new/design](https://hash-ec9724dd62caca8e181210b56eb47a70766a3e9a.calypso.live/new/design).
2. Then emulate a mobile phone using Chrome DevTools. Or better yet, visit using your phone. 
Fixes #40898
> Gutenboarding: implement design picker mobile layout

- apps/wpcom-block-editor/src/wpcom/features/tracking/track-record-event.js
- apps/wpcom-block-editor/src/wpcom/features/tracking/wpcom-block-picker-search-term-handler.js
This PR populates the recorded event with the `selected_block` property, which contains the block name if there is a selected block in the editor.
1) Update your testing site with these changes (SB)
2) In your testing site, open the client dev console and setup the debug
```
> localStorage.setItem( 'debug', 'wpcom-block-editor*' )
```
A hard refresh is needed.
3) Open the Blocks List Inserter
4) Start to type until getting the no-results message
5) Look at the debug logs.
6) Inspect the `wpcom_block_picker_no_results` event:
2') Repeat the same steps but before `(3)` selects a block
7) Confirm that there is a `selected_block` property among the other event properties.
8) Confirm that the `selected_block` property only appears when the user searches the block using the inserter menu.
Fixes …
> Tracking: enrich recorded event with selected_block

- client/landing/gutenboarding/onboarding-block/acquire-intent/index.tsx
- client/landing/gutenboarding/onboarding-block/create-site/index.tsx
- client/landing/gutenboarding/onboarding-block/design-selector/index.tsx
- client/landing/gutenboarding/onboarding-block/edit.tsx
- client/landing/gutenboarding/onboarding-block/style-preview/index.tsx
- client/landing/gutenboarding/onboarding-block/style.scss
- client/landing/gutenboarding/style.scss
This makes navigation between pages smoother and more seamless. 
Just move around the flow from start to finish with the occasional back button to see. 
These transitions are pure CSS, they can be disabled/altered on mobiles using media queries without much effort.
Fixes p1586419553461200-slack-luna.
> Gutenboarding: add transitions on page landing

- client/my-sites/site-settings/form-general.jsx
- client/my-sites/site-settings/wrap-settings-form.jsx
This PR ensures that every user with a privacy-enabled site will see the correct **New privacy picker**. Technically, we add a an interim `private_sites_enabled` flag that makes it possible to decide server-side which users/sites see the old privacy pickers, and which ones see the new one. The flag will be removed after 100% rollout
See D41819-code for rationale.
**Old picker**
**New picker**
1. Apply D41819-code
1. Assign yourself to `control` group of `ATPrivacy` test
1. Create a new simple site, launch it
1. Go to settings > general, and confirm you see the **Old Picker**
1. Make the site private
1. Go to settings > general, and confirm you see the **Old Picker**
1. Assign yourself to `variant` group of `ATPrivacy` test
1. Go to settings > general, and confirm you see the **New …
> [Private sites] Enable the new privacy picker UI when private_sites_enabled flag is detected

- client/my-sites/customer-home/cards/actions/wp-for-teams-quick-links/index.jsx
- client/my-sites/customer-home/cards/education/free-photo-library/index.jsx
- client/my-sites/customer-home/cards/features/grow-earn/index.jsx
- client/my-sites/customer-home/locations/primary/index.jsx
D41814-code adds a new view to the Home layout API that is targeted for WP for Teams sites:
- It doesn't return the Grow & Earn or the Free Photo Library cards.
- Returns a new quick links card (`home-action-wp-for-teams-quick-links`) so we can display a different set of quick links without affecting the current quick links card for Simple/Atomic sites.
That way we can rely on the API on what to render and remove all the visibility checks we added in #40723.
- Apply D41814-code and sandbox the API.
- Launch Calypso running this branch.
- Create a WP for Teams site in `/start/wp-for-teams`.
- Go to My Home.
- Make sure the layout renders the following cards:
- A celebration notice for the site creation.
- Quick links on the primary location (left).
- Stats (if the site had any visit), …
> My Home: Handle new view for WP for Teams sites

- client/signup/steps/wp-for-teams-site/style.scss
In this PR, we fix the first signup step of the `start/wp-for-teams` signup flow. There was a tiny issue with margins as css specificity was not enough when css resources were minified and compiled.
First, add `signup/wpforteams` under the `features` prop in `config/production` file. Then, run Calypso with `CALYPSO_ENV=production npm start` so that it runs as on production. Open a new incognito window and navigate to `start/wp-for-teams`. There should be a proper margin on the site creation step now.
> WP for Teams: fix signup styling

- client/my-sites/plans-features-main/gutenboarding-header/index.jsx
- client/my-sites/plans-features-main/gutenboarding-header/style.scss
- client/my-sites/plans-features-main/index.jsx
- client/signup/config/steps-pure.js
- client/signup/steps/plans/index.jsx
- client/signup/style.scss
* Update launch flow to re-use the [plans grid header](https://github.com/Automattic/wp-calypso/pull/40860) from Gutenboarding site creation; Fix p58i-8QA-p2#comment-45907
* Increase heading font size to match design.
* Add some mobile tweaks to the plans grid header and align with the rest of Gutenboarding.
* Create a site from Gutenboarding then press the Launch button.
* Everything should stay the same except the header style.
> Gutenboarding: update plans header for launch flow + mobile

- client/landing/jetpack-cloud/components/sidebar/index.jsx
- client/landing/jetpack-cloud/index.js
- Import "global" Jetpack Cloud styles from the sidebar section.
In stage and production, sections are loaded in the demand, which means that styles might not get loaded if the user doesn't visit the section from where they are being loaded. This doesn't happen in development, because in there we always load all sections.
- 
See 1151678672052943-as-1171201428833121.
> Import global styles from the sidebar section

- client/landing/jetpack-cloud/sections/backups/main.jsx
- client/landing/jetpack-cloud/sections/backups/style.scss
**Very small PR**
Remove the "Loading backups..." message from the Backup Status page and replace it by a block with a pulse effect.
- Load the Backups section and see a gray block with a pulse effect while the backups are loading.
> Remove "Loading backups" and replace it by a pulse loading block

- client/landing/jetpack-cloud/components/daily-backup-status/index.jsx
- client/landing/jetpack-cloud/components/daily-backup-status/style.scss
Currently I'm seeing a failure to load the Backups page on Jetpack Cloud when I select a new site that has no backups available. This looks like it's because we're missing a null check on `renderNoBackupToday`, so I switched some logic around to account for this case.
I also inverted the Boolean logic in `renderBackupStatus` a bit, with the intent to keep things readable since I added another condition. (This style is something I borrowed from the Go community; I'm 100% open to adapting it if it's not in tune with _our_ community's coding style.)
I cribbed my verbiage here from the other backup "states," but I feel like it might still be able to be improved.
* Create a new WordPress site and connect it to Jetpack.
* Go to Jetpack Cloud and select your new site.
* Ensure that the Backups …
> Jetpack Cloud: Show 'No backups exist' for sites that have no backups

- client/components/domains/register-domain-step/index.jsx
Reverts the change from https://github.com/Automattic/wp-calypso/pull/40318
Along with D41668-code this should fix the issue mentioned in https://github.com/Automattic/wp-calypso/issues/40164#issuecomment-611714867
Apply D41668-code to your sandbox and test this PR.
Go to https://wordpress.com/start/
Search for some queries.
You should always get WPCOM subdomain results, even with blacklisted terms like `wordpress`. Try, for example, `demo.wordpress`.
> Domains: Send correct CORRECT arguments when searching for subdomains

- client/my-sites/checkout/checkout-system-decider.js
- client/my-sites/checkout/composite-checkout/composite-checkout.js
- client/my-sites/checkout/composite-checkout/test/composite-checkout.js
- client/my-sites/checkout/composite-checkout/use-prepare-product-for-cart.js
- client/my-sites/checkout/composite-checkout/wpcom/hooks/use-shopping-cart.ts
Renewal URLs contain both product slugs and purchase Ids and must be handled in a particular way; notably, unlike "new product" URLs, they use real product slugs. They were originally added in #15043. This PR adds support for such URLs to composite checkout.
Renewal URLs look something like `checkout/dotblog_domain:example.com,domain_map:example.com/renew/12345,54321/example.com`
- Verify that your cart is empty.
- Use the flag `composite-checkout-testing` to ensure you are in the AB test.
- Click a "renew" link in Calypso for a product and visit checkout.
- Verify that you see composite checkout.
- Verify that the renewed product is in your cart.
- Check out and verify that the product is successfully renewed.
- Repeat the above steps with different types of products (eg: plans, domains, …
> composite-checkout: support adding renewal products to cart via url

- client/blocks/jitm/templates/sidebar-banner.jsx
- client/my-sites/current-site/notice.jsx
* When the logic to show/hide upsells depending on plans and multiple other conditions was added in #40762, it hid the upsells for sites that were not on the free plan and did not include a `feature` prop. 
* This only appears to have affected the sidebar nudge to claim a free domain for existing plan users, not new upgrades/purchases.
* **Why did this happen?** Because we're juggling logic for nudge displays in multiple places. 🙃 Sometimes it's done on the JITM side, sometimes it's done before the nudge is called (as in the sidebar notices), and sometimes it's done from within `UpsellNudge` itself.
* Setting the sidebar and sidebar JITM upsells to `forceDisplay={ true }` overrides the logic within `UpsellNudge` itself. Sidebars and JITMs use their own logic to determine whether they …
> Upsells: Update sidebar nudges to force display

- client/landing/gutenboarding/components/domain-picker/index.tsx
- client/landing/gutenboarding/components/header/index.tsx
- client/landing/gutenboarding/hooks/use-domain-suggestions.ts
- packages/data-stores/src/domain-suggestions/types.ts
Long and pointless battles have been waged over whose system of decimal separators and other currency punctuation marks make more sense. 
Who can forget the wake of destruction left by the epic combat between `1.000,00` and `1,000.00`?
Rather than continue this senseless conflict, we have capitulated.
In this PR, we pass `i18nLocale` in an object to `useDomainSuggestions()` so the domains suggestions endpoint can return the correct pricing format, e.g., `0.00` for 'en' and `0,00` for 'es/fr' and so on.
Go here:
http://calypso.localhost:3000/new/style/
See this:
Now go here:
http://calypso.localhost:3000/new/style/fr
See that:
Fixes #40733
> Gutenboarding: localize domain suggestion price format

- client/blocks/signup-form/passwordless.jsx
- client/lib/analytics/signup.js
- client/lib/signup/step-actions/index.js
This is a rewrite based on the updated analytics code of https://github.com/Automattic/wp-calypso/pull/37410. I think I have addressed all the issues reported there in this PR.
The one thing I'm not quite sure how to test is the Apple signup.
* Unify `calypso_user_registration_complete`, `calypso_user_registration_passwordless_complete`, `calypso_user_registration_complete` into one single `calypso_user_registration_complete`.
* Adds a `type` prop in `calypso_user_registration_complete` set to `default`, `social`, `passwordless`.
* Calls Tracks `identifyUser()` before calling Tracks and GA `calypso_user_registration_complete` this way making sure it is de-anonymized promptly.
* `identifyUser()` is called from inside `recordRegistration()` making sure it will be called in the future when …
> Unify calypso_user_registration_complete event

- client/blocks/upsell-nudge/index.jsx
Follow up to https://github.com/Automattic/wp-calypso/pull/41002
This fixes any sidebar JITMs CTA action paths. We previously weren't passing through the href, and so it would fallback to `/plans/siteslug`
* In console set `localStorage.debug = 'calypso:jitm*'`
* Verify that any JITM sidebar upsell we see use the correct CTA.link instead of /plans/siteslug
* For example on a free site, "A free domain with plan" should take us to `http://calypso.localhost:3000/domains/add/siteslug` instead of /plans/siteslug
> Nudges: pass through href from UpsellNudge to Banner

- client/landing/gutenboarding/hooks/use-domain-suggestions.ts
This is a fix for #41042 — because of the modular nature of the intent gathering step, I couldn't work out a way to infer whether or not the domain suggestions query should use the vertical without making it aware of steps in the flow. This mightn't be the cleanest way to do it, but was simpler than refactoring how the site title is set (an alternative to this PR would be to delay the call to `setSiteTitle` until after someone completes the intent gathering step, but that would also affect the header behaviour).
* Update the `useDomainSuggestions` hook to be aware of the current step
* Only use vertical fallback for domain suggestions if not on the intent capture step
* Watch the demo in issue #41042 so that you know what to look out for!
* On the Intent Gathering step `/new` select a …
> Gutenboarding: Only use vertical for domain suggestion on non intent gathering steps

- client/lib/abtest/active-tests.js
- client/my-sites/checkout/checkout-system-decider.js
- client/my-sites/checkout/checkout/checkout-container.jsx
- client/my-sites/checkout/checkout/index.jsx
- client/my-sites/checkout/composite-checkout/composite-checkout.js
- client/my-sites/checkout/composite-checkout/test/composite-checkout-thank-you.js
- client/my-sites/checkout/composite-checkout/use-get-thank-you-url.js
- client/my-sites/checkout/controller.jsx
- client/my-sites/checkout/upsell-nudge/index.jsx
- client/my-sites/checkout/upsell-nudge/plan-upgrade-upsell/index.jsx
* Testing the updated Premium bump offer for qualified Personal plan customers. More info here pNEWy-cIg.
* Make sure that the test plan in https://github.com/Automattic/wp-calypso/pull/38286 passes for all cases. 
* Signup for an account and purchase a Personal plan.
* Put yourself in `control` group for `showPremiumPlanBump` test:
* After completing payment, verify you're shown the Concierge/Quick Start upsell after purchase.
* Put yourself in `variantShowPlanBump` for `showPremiumPlanBump` test:
* After completing payment, verify that you are shown the Premium plan bump offer.
**Test in the new checkout flow**
* Where relevant, repeat all the cases listed above for the new checkout flow - proxy through a US IP and assign yourself to `composite` variation of `showCompositeCheckout` …
> AB test for updated Premium plan bump offer

- client/assets/stylesheets/shared/_typography.scss
- client/components/formatted-header/style.scss
- client/my-sites/customer-home/style.scss
In order to bring font consistency across all page headings, this PR updates to Recoleta the font-family used in the title of the `FormattedHeader` component, so it is not only used in My Home.
- Navigate through all pages in Calypso and make sure all headings use the Recoleta font.
- Watch out for other `FormattedHeader` instances not used in page headings and make sure the Recoleta font looks good on them (I'm happy to audit this tomorrow and update the testing instructions with the exact places).
Fixes #41090
> Use Recoleta on all page headings

- client/landing/gutenboarding/components/domain-picker-button/index.tsx
- client/landing/gutenboarding/components/domain-picker/index.tsx
- client/landing/gutenboarding/components/domain-picker/style.scss
* Sticky footer on mobile view.
* Scrollable picker content on mobile view.
* Do not autofocus search input on mobile view.
* Go to `/new`.
* Click on domain picker (and enter a domain if needed).
* Resize browser width until domain picker goes full screen.
* Resize browser height until scrollbar appears.
* Search input should not be in focused when dropdown picker appears.
I'm waiting for these 2 PRs to rollout first then I'll rebase this PR as there may be conflicting changes.
- https://github.com/Automattic/wp-calypso/pull/41007
- https://github.com/Automattic/wp-calypso/pull/40959
Fixes #40949
> Mobile support for domain picker - fixed footer & scrollable content.

- client/blocks/upsell-nudge/index.jsx
* Fixes Jetpack conditionals on the Upsell Nudge component.
* Fire up this PR
* Ensure the `isJetpack` variable outputs `true` if it's a Jetpack site, `false` otherwise.
Fixes issue reported in https://github.com/Automattic/wp-calypso/pull/40721#issuecomment-612926288 cc @sixhours
> Upsell nudge: fix missing Jetpack conditions

- client/my-sites/activity/activity-log-banner/upgrade-banner.jsx
* Force display the upsell nudge on Activity log for non-Jetpack sites.
* Complementary to https://github.com/Automattic/wp-calypso/pull/41047
* Open the Activity log with a non-Jetpack site on a free plan.
* Make sure you can see the upgrade banner.
Fixes issue reported in https://github.com/Automattic/wp-calypso/pull/40721#issuecomment-612926288 cc @sixhours
> Activity log: force display the upsell nudge for non-Jetpack sites

- apps/wpcom-block-editor/src/wpcom/features/tracking/delegate-event-tracking.js
- apps/wpcom-block-editor/src/wpcom/features/tracking/wpcom-autocomplete-block-search-term.js
- apps/wpcom-block-editor/src/wpcom/features/tracking/wpcom-block-picker-search-term-handler.js
- apps/wpcom-block-editor/src/wpcom/features/tracking/wpcom-inserter-inline-search-term.js
This PR adds a new event tracker in order to record events when the user opens the autocomplete block to add a block into the editor.
It complements the data what currently collected from Inserter Menu.
| Inserter Menu | Inserter Inline |
|---------------|----------------------|
| ![image](https://user-images.githubusercontent.com/77539/79127435-47a89700-7d78-11ea-8720-1b45b553f5e1.png) | ![image](https://user-images.githubusercontent.com/77539/79127467-568f4980-7d78-11ea-83ae-496a4f86dae9.png) |
It allows [delegating the task to define if the target is valid](https://github.com/Automattic/wp-calypso/pull/41022/files#diff-104bf6942a8f026eeed7ad1e4f66a261R38-R40) to the tracker module.
This selector performs verification steps before to return a valid target. The first one if exists a …
> Tracking: Register blocks search results from Autocompleter

- client/my-sites/checkout/composite-checkout/wpcom/types.ts
- client/my-sites/checkout/composite-checkout/wpcom/types/backend/domain-contact-details-components.ts
- client/my-sites/checkout/composite-checkout/wpcom/types/wpcom-store-state.ts
In preparation for adding the extra tld contact fields, we need to separate out three different kinds of contact details objects with slightly different semantics:
1. The data expected by the contact form component in calypso (and the data returned by it)
2. The data expected by the validation endpoint,
3. The data stored by composite-checkout.
In a better world than the one we have now, these could be unified.
This PR deals with case 1 by pulling this data type out of `wpcom-store-state` and adding extra fields related to ccTLDs.
This should have no observable effect on composite checkout -- make sure this is the case by going through checkout looking for errors.
> composite-checkout: Move DomainContactDetails to separate file and add ccTLD data

- client/landing/jetpack-cloud/sections/scan/main.jsx
* Updates some minor copy.
* Set up Cloud.
* Navigate to a site with Scan enabled.
* Examine footer and click link in text.
Screenshot:
Fixes 1151678672052943-as-1171360976928737.
> Updates link and copy in scan page footer

- client/my-sites/plugins/plugin-meta/index.jsx
- client/my-sites/plugins/plugins-browser/index.jsx
* Ensures the Plugins upsell appears for Personal & Premium plan sites
There's two places to verify where the nudge appears. Firstly, on the Plugin search page.
And then on an individual plugin page.
But also verify that the nudge still doesn't appear for the Business or eCommerce Plan. :) 
cc @sixhours 
Fixes #41046
> Plugins: Let Upsell Appear for Personal & Premium Sites

- client/my-sites/checkout/composite-checkout/contact-validation.js
- client/my-sites/checkout/composite-checkout/wpcom/components/wp-checkout.js
- client/my-sites/checkout/composite-checkout/wpcom/index.js
- client/my-sites/checkout/composite-checkout/wpcom/types.ts
- client/my-sites/checkout/composite-checkout/wpcom/types/backend/domain-contact-validation-endpoint.ts
- client/my-sites/checkout/composite-checkout/wpcom/types/wpcom-store-state.ts
* This PR makes the request and response types of the domain contact details validation endpoint explicit, introduces conversion functions to and from the internal type, and uses these in the endpoint wrapper for composite checkout. It also bumps the api version number on the request to trigger the new behavior implemented in D41243-code and #41033.
This patch refactors domain contact validation in composite checkout. To test it, enter checkout with a domain in your cart and jerk test the contact details step. Things to watch for:
- If your data is complete, can you proceed to the next checkout step?
- If your data is incomplete or incorrectly formatted, do you see errors (a notice and field errors) when submitting?
- Look for errors in the JS console
- Keep an eye on the network traffic …
> composite-checkout: Add domain-contact-validation-endpoint types and use them

- apps/wpcom-block-editor/src/wpcom/features/tracking.js
* Use underscore for event properties. (oof)
Follow https://github.com/Automattic/wp-calypso/pull/40035. Only difference is to use this diff (D41949-code) for testing instead of the one there. (And to make sure the error properties are the new ones)
> Fix Gutenberg Error Notice logging

- client/landing/gutenboarding/onboarding-block/acquire-intent/vertical-select/index.tsx
The suggestions list will always display at least one item even if it's an exact match of the user query. 
We decided to optimize for the first run, rather than the coming back scenario. See https://github.com/Automattic/wp-calypso/issues/41121#issuecomment-613875006
So we are reverting #40110
* Starting at URL: [/new](https://hash-6f173afe6310cc98f9b899863027513b673ac275.calypso.live/new)
* After typing _baker_ you see 2 results in the Suggestions list: _baker_ and _Bakery_.
* When pressing the final letter y the list should contain 1 item: _Bakery_.
Fixes #41121
> Gutenboarding: optimize vertical selector for the first run

- client/components/inline-support-link/README.md
- client/components/inline-support-link/index.jsx
- client/my-sites/customer-home/cards/education/mastering-gutenberg/index.jsx
- client/my-sites/customer-home/cards/education/mastering-gutenberg/style.scss
- client/my-sites/customer-home/locations/primary/index.jsx
This PR updates:
*  Styling for "Master the Block Editor" to better match existing cards
* Adds some missing analytics events to the card
* Enhances the InlineSupportLink to accept tracks and stats analytics
| Before  | After |
|  <img width="722" alt="78721460-81644280-791f-11ea-9e82-0d510b209245" src="https://user-images.githubusercontent.com/1270189/79397773-c3027800-7f33-11ea-9ed6-d7bf8ed299d4.png"> | <img width="695" alt="Screen Shot 2020-04-15 at 4 12 41 PM" src="https://user-images.githubusercontent.com/1270189/79397906-29879600-7f34-11ea-896f-96f378763fbf.png"> |
| Open Article  |
| ------------- |
| <img width="1134" alt="Screen Shot 2020-04-15 at 4 02 15 PM" src="https://user-images.githubusercontent.com/1270189/79397800-d7df0b80-7f33-11ea-973a-3 …
> My Home: update styling for Block-Editor card and add analytics

- client/landing/jetpack-cloud/components/sidebar/index.jsx
- client/state/selectors/get-jetpack-scan-threats.js
- client/state/selectors/get-site-scan-threats.js
- Create a Query Component to fetch the Scan History data and load it into the store.
- Make the sidebar display the real number of found threats.
- Go to http://jetpack.cloud.localhost:3000/scan/<SITE_SLUG>?scan-state=threats.
- If <SITE_SLUG> has threats, you should see a badge with the number of them on the sidebar.
- If <SITE_SLUG> doesn't have threats, you should not see the badge.
See 1151678672052943-as-1171292173815057.
> Jetpack Cloud: display the real number of threats in the sidebar

- client/lib/abtest/active-tests.js
- client/my-sites/checkout/checkout-system-decider.js
- client/my-sites/checkout/checkout/checkout-container.jsx
- client/my-sites/checkout/checkout/index.jsx
- client/my-sites/checkout/composite-checkout/composite-checkout.js
- client/my-sites/checkout/composite-checkout/test/composite-checkout-thank-you.js
- client/my-sites/checkout/composite-checkout/use-get-thank-you-url.js
- client/my-sites/checkout/controller.jsx
- client/my-sites/checkout/upsell-nudge/index.jsx
- client/my-sites/checkout/upsell-nudge/plan-upgrade-upsell/index.jsx
Reverts Automattic/wp-calypso#40826
As per the discussion in pbxNRc-fI-p2/#comment-207, we would like to revert the premium plan bump test.
1. Go through the signup flow at wordpress.com/start
2. Add a Personal plan to cart and complete payment in the checkout page.
3. Verify that you are always shown the Quick Start upsell offer. You should not be assigned to the `showPremiumPlanBump ` test since we are removing it. 
- Verify that clicking "Yes" on the offer takes you to checkout and that you are able to complete purchase
- Verify that clicking "No" on the offer takes you to Home page.
4. Test the same steps 1-3 in the new checkout flow. For this, you need to proxy via a US IP address and assign yourself to the `composite` variation of `showCompositeCheckout` A/B …
> Revert "AB test for updated Premium plan bump offer"

- client/lib/checkout/constants.js
- client/lib/checkout/processor-specific.js
- client/lib/checkout/validation.js
- client/my-sites/checkout/checkout/country-specific-payment-fields.jsx
- client/my-sites/checkout/checkout/style.scss
Businesses in India need to include their GSTIN number for tax purposes when paying locally.
This adds an additional optional field next to the PAN number when paying with Netbanking, with simple regex-based validation (no checksum check)
This will only be merged after the payment gateway adds support for the API param, but can already be tested for frontend only validation.
**Setup to show the netbaking payment method**
- The account you're using must have INR set as its currency (a8c/sandbox only).
- You need to use an Indian IP address, or change the geolocation on top of `\Store_Shopping_Cart::get_allowed_payment_methods` to `IN`.
- You can use AAAPL1234C as your PAN
**Validation tests**
- Test an empty GSTIN - no issue
- Test an invalid GSTIN - a validation error should be shown on …
> Old Checkout: Add GSTIN field for local payments in India

- client/landing/gutenboarding/style.scss
* Remove the [blue border around the whole container](https://d.pr/i/AW6pdA) visible on design step and on [style step](https://d.pr/i/72M7cI) when focused.
* Go to [/new](https://calypso.live/new?branch=fix/gutenboarding-border-around-container)
* Check if the border has been removed
Fixes part of #41138
> Gutenboarding: Hide unwanted border on container

- client/landing/jetpack-cloud/components/daily-backup-status/style.scss
- client/landing/jetpack-cloud/style.scss
**Very small**
Use the correct style when a non-primary button is disabled. Before, if you move the cursor over it you see a green background, and it should stay white.
Before (mouse is over the "Download backup" button)
After (mouse is over the "Download backup" button):
- Go to the Backup section and to the Backup Scheduled view (today), move the cursor over the buttons "Download backup" and "Restore to this point" and see that the colors don't change. If you have a backup from today, move your time zone.
> Fix the styles in the buttons when they are disabled

- client/components/main/style.scss
- client/my-sites/activity/activity-log/index.jsx
- client/my-sites/plans/main.jsx
Second attempt to try bringing font consistency across all page headings.
We tried this first in #41102 but decided to revert it since it was updating the font to Recoleta in more places than page headings. On this attempt, we're adding a more targeted update, so only `FormattedHeader` used in page headings are updated, leaving other instances with the current font.
- Navigate through all pages in Calypso and make sure all headings use the Recoleta font.
- Watch out for other `FormattedHeader` instances not used in page headings and make sure they don't use the Recoleta font (i.e. `/start` or `/jetpack/new`).
Fixes #41090
> Use Recoleta on all page headings (take 2)

- client/my-sites/checkout/composite-checkout/composite-checkout.js
- client/my-sites/checkout/composite-checkout/wpcom/components/wp-checkout.js
- client/my-sites/checkout/composite-checkout/wpcom/components/wp-contact-form.js
- client/my-sites/checkout/composite-checkout/wpcom/hooks/wpcom-store.ts
- client/my-sites/checkout/composite-checkout/wpcom/types/wpcom-store-state.ts
To do:
This PR does a little cleanup of the ManagedContactDetailsUpdaters and its consumers:
* Replace `updateDomainFields` by `updateDomainContactFields`, which includes the ccTLD data and uses the `updateManagedContactDetailsShape` utility
* Refactor `renderContactDetails` to a component so we can directly use hooks rather than passing in updaters, and remove these from props where we can
This should have no observable effects but touches a core part of the contact details state management. Jerk test the contact form in composite checkout, both with and without a domain, keeping an eye out for fields that behave weirdly, validation that doesn't work as expected, and errors in the console.
> composite-checkout: Refactor contact details updater

- client/signup/steps/wp-for-teams-site/index.jsx
- client/signup/steps/wp-for-teams-site/style.scss
Addresses https://github.com/Automattic/wp-for-teams/issues/141.
In this PR, we make the form labels of the WP for Teams signup flow clickable.
Navigate to `start/wp-for-teams`. Click on form labels on the first Site step. Cursor should change to a pointer and the input for the label should get focused.
> WP for Teams signup: make form labels clickable

- client/landing/jetpack-cloud/sections/backups/main.jsx
Remove the selectedDate state from the BackupStatus component and use the selected date from the URL, if it exists or automatically selects today. Also, the navigation history is tracked and we can browse through the dates using the back/forward buttons
- The first time, we don't have a selected date, so we see the today backup status
- If we navigate through the dates, we can see in the URL the query parameter date with the selected date with this format YYYYMMDD
- If we change the parameter for another valid date (with the expected format), the Backup Status page loads the backup of this date.
- If we change the parameter for an invalid date (future date, date before the oldest backup, or any text string), the Backup Status page loads today's backup status.
- …
> Remove the selectedDate state from BackupStatus and use the date from

- client/landing/jetpack-cloud/components/daily-backup-status/index.jsx
Change all the onClick callbacks by links wherever it makes sense.
**Some links don't work until this https://github.com/Automattic/wp-calypso/pull/41080 is merged**
- Check the follow links: 
- The Yesterday link on Backup Scheduled view
- The "Download" and "Restore to this point" buttons work with a normal backup. Also, check that these buttons don't work if they are disabled. (Note that the Download button has a style issue in this case)
- Now, if you go to the "Download backup" or to the "Restore to this point" flow, we can go back to the backup status view on the correct date.
> Replace the function calls with a link with the date to go.

- client/landing/jetpack-cloud/components/activity-card-list/index.jsx
- client/landing/jetpack-cloud/components/activity-card-list/style.scss
- client/landing/jetpack-cloud/components/site-offset/context.tsx
- client/landing/jetpack-cloud/components/site-offset/index.tsx
- client/landing/jetpack-cloud/sections/backups/backup-activity-log/index.tsx
- client/landing/jetpack-cloud/sections/backups/backup-activity-log/style.scss
- client/landing/jetpack-cloud/sections/backups/rewind-flow/index.tsx
* Add date separators to `ActivityCardList` an optional parameters to control if they are used.
2. Inspect the rendered list vs the network request for activity or another source of the activity log. Make sure the dates separators are being rendered in the correct places.
> Add Date Separators to ActivityCardList

- .github/workflows/full-site-editing-plugin.yml
- apps/README.md
- apps/full-site-editing/README.md
- apps/full-site-editing/bin/setup-env.sh
- apps/full-site-editing/full-site-editing-plugin/readme.txt
- apps/notifications/README.md
- apps/o2-blocks/README.md
- apps/wpcom-block-editor/README.md
* Calypso apps documentation references yarn instead of npm
* Remove (most) references to lerna, which isn't needed any more. It's too verbose, a bit slow to use, and overall not worth recommending.
You can still use lerna if you need to run the `build` command across all packages at the same time, but like... that's an extremely rare use case.
Make sure there are no typos in the documentation
> Update Calypso apps documentation for yarn 🎉

- docs/development-workflow.md
- docs/fallback-development-workflow.md
* Updates more markdown docs to use yarn build command, specifically the IE dev workflow docs that just got added.
* Check typos
> Docs: Update more `npm run ...` commands in docs to `yarn`

- client/my-sites/plugins/plugin-site-jetpack/index.jsx
- client/my-sites/plugins/plugin-site-jetpack/style.scss
- Replace plugin update indicator with plugin settings link on an individual plugin page. (example: https://wordpress.com/plugins/woocommerce)
- The link is shown only if available; in a case where it's not available the button does not display. More on that below. ⬇️
Plugins can define action links as outlined by [this filter](https://codex.wordpress.org/Plugin_API/Filter_Reference/plugin_action_links_(plugin_file_name)). There are a few plugins that define `Settings` action link in addition to other action links, like `About`, `Contact us` (leading to their own customer support page), etc. In such cases, we are interested only in the one that reads `Settings`. 
This PR attempts to show a button only for that action link, and all other links are ignored.
- Visit the Calypso live branch …
> Replace plugin update indicator with plugin settings link

- client/blocks/upsell-nudge/README.md
- client/blocks/upsell-nudge/index.jsx
- client/components/seo/preview-upgrade-nudge/index.jsx
- client/components/seo/preview-upgrade-nudge/test/index.jsx
This makes the Upsell Nudge compatible for cases where non-admins are advised to contact someone who can upgrade, and updates a usage of this which I noticed in #41044. It'll also the nudge to benefit from any changes in that PR.
Visit `/view/site` and toggle the dropdown at the top left to "Search & Social".
**As an admin:**
**As a non-admin:**
As a non-admin, you shouldn't be able to click the nudge, but you should be able to as an admin!
cc @mmtr, @sixhours
> Search & Social: Replace Banner with Upsell Nudge

- client/my-sites/marketing/connections/service-description.jsx
- client/my-sites/marketing/connections/service-examples.jsx
- client/my-sites/marketing/connections/service.jsx
- client/my-sites/marketing/connections/services-group.jsx
- client/my-sites/marketing/connections/services/index.js
- client/my-sites/marketing/connections/services/instagram.jsx
- client/my-sites/marketing/style.scss
- client/state/sharing/services/selectors.js
As part of the Instagram API upgrade that's used by the Instagram widget
and the upcoming Instagram Gallery block, we need to add the service to
the connections list, so that it can be managed from within Calypso.
This change adds the Instagram service to the `/marketing/connections` section.
* Sandbox the API and apply ~~D41054-code~~ D41937-code if it hasn't been merged. 
* Go to the `marketing/connections` page and test connecting and disconnecting an Instagram account.
> Marketing Connections: Add an Instagram connection

- client/landing/gutenboarding/onboarding-block/acquire-intent/index.tsx
- client/landing/gutenboarding/onboarding-block/acquire-intent/site-title.tsx
- client/landing/gutenboarding/onboarding-block/acquire-intent/style.scss
- client/landing/gutenboarding/onboarding-block/acquire-intent/vertical-select/index.tsx
- client/landing/gutenboarding/onboarding-block/acquire-intent/vertical-select/style.scss
- client/landing/gutenboarding/variables.scss
* Display Vertical Select or Site Title on mobile as different steps.
* Vertical suggestions list is covering full height of the screen on mobile.
* Vertical input is transitioned vertically from center to top of the screen when suggestions are displayed.
* Add back arrow on mobile on Site Title step.
* Display _Choose a design_ / _Don't know yet_ button and only on Site Title step.
* Go to [/new](https://calypso.live/new?branch=update/gutenboarding-intent-capture-mobile) on mobile.
* No matter what data is stored in the app, only [Vertical Select step](https://user-images.githubusercontent.com/87168/78777078-94b7f200-79a1-11ea-92a1-c78f1a06465b.png) should be displayed.
* After selecting a vertical, pressing the arrow next to it should hide Vertical Select step and display [Site Title …
> Gutenboarding: intent capture for mobile

- client/landing/gutenboarding/components/domain-picker-modal/style.scss
This bug was introduced in #41212 and prevents ICFY builds (as well as `yarn analyze-bundles` and `yarn whybundled`) from working correctly. See e.g. [this run](https://github.com/Automattic/wp-calypso/runs/595694428).
I believe it may also be resulting  in invalid CSS being output, at least going by [what Sassmeister tells me](https://www.sassmeister.com/gist/09206c405fc60d8c6ecde1f988de0e09).
* Fix escaping bug in `domain-picker-modal/style.scss`
Ensure that the ICFY build completes successfully and doesn't error out like in #41212.
> Fix Sass bug in gutenboarding domain picker modal

- client/blocks/upsell-nudge/index.jsx
* Following up on Kerry's work in #41115, this passes through all props from `UpsellNudge` to be used by `Banner`, and removes the use of `...props`.
Switch to this PR and follow testing instructions for upsells in these PRs:
#40721
#40626
Make sure you test with a Jetpack site as well as a WordPress.com site, and verify that upsells only show when it makes sense (ie. upsell for the Premium plan should not show when on a Premium or Business plan).
> UpsellNudge: Pass props to Banner explicitly

- client/my-sites/checkout/composite-checkout/wpcom/types/wpcom-store-state.ts
When validating contact fields, composite checkout has two separate systems: when a domain product is in the cart, the form uses the `validate` endpoint on the server to determine if the data is valid; when there is no domain, the form uses a relatively simple check for required empty fields or for existing errors.
If the cart changes during checkout, it's possible to switch from the validate endpoint to the simple check. In this case, the (empty) extra field data from the larger domain form is still present, with `undefined` as the `errors` property for each field. The simple check, when looking for any errors, has the condition `arg.errors?.length <= 0`, but if `errors` is undefined for these extra fields, this becomes `undefined <= 0`, which evaluates to `false`. The result is that the …
> composite-checkout: Make contact fields valid when errors is undefined

- client/lib/user/shared-utils.js
- client/state/current-user/reducer.js
- client/state/current-user/schema.js
- client/state/current-user/selectors.js
- client/state/current-user/test/reducer.js
- client/state/lasagna/middleware.js
- client/state/lasagna/socket.js
- client/state/reader/full-view/reducer.js
- config/_shared.json
- config/development.json
- config/wpcalypso.json
The Lasagna service is moving to [JWKS](https://tools.ietf.org/html/rfc7517) to manage auth concerns more nimbly than its initial Calypso-coupled implementation. 
* Switch Lasagna websocket connect to a preloaded JWT sidecar'd in the `/me` response.
* Move to keying socket connect/disconnect events off `ROUTE_SET`, as `SECTION_SET` spams us on hard refreshes in Reader full post view, conversations.
* Point the Calypso `development` (active) and `horizon` (currently disabled with feature flag) environments at the Lasagna `horizon` environment. Lasagna `horizon` is the only environment that gets CD of `master` at the moment. (And likely into the future.)
1. Apply D41855-code.
2. Boot this branch locally.
3. Verify you see a successful websocket connection when you go to Reader.
> Lasagna: switch socket connect to preloaded JWT

- client/me/help/help-contact/index.jsx
Fixes https://github.com/Automattic/hg/issues/786
0. Use an account with live chat access (pro, etc).
1. Set computer date before 2020-04-18 00:00Z. Chat should be available.
2. Set computer after 2020-04-18 00:00Z. Banner should show.
3. Set computer after 2020-04-20 06:00Z. Chat should be available.
> Live chat: add closure for this weekend

- client/my-sites/customer-home/cards/tasks/connect-accounts.jsx
This just makes the change suggested here: https://github.com/Automattic/wp-calypso/pull/41018#discussion_r411120993
cc @akirk 
Check that the Connect Accounts Task (details in #41018 on how to display it) still shows "3 minutes" as the timestamp.
> Customer Home: Updating Timing of Connect Accounts Task

- client/components/domains/domain-registration-suggestion/index.jsx
- client/components/domains/domain-search-results/index.jsx
- client/components/domains/featured-domain-suggestions/index.jsx
This change ensures that we have a positional suffix for the TrainTracks data we log for domain suggestions.
* Navigate to `/start/domains` and open the network inspector of your browser.
* Enter a search term for a domain.
* Verify that we make logging requests for each of the suggestion items with a form of `<uuid>-domain-suggestion-<n>`, where <n> is a digit starting from 0.
* Select one of the rows in the table, and verify that we log an event with the 0-indexed position of that item as the suffix after `domain-suggestion-`. (Note that the recommended and alternative options are in positions 0 and 1.)
Repeat the steps above from within the main Calypso UI at `/domains/add/<your-site-slug>/`.
> Add suffix to railcar identifier

- client/jetpack-connect/controller.js
- client/jetpack-connect/index.js
This PR adds the ability for Jetpack to purchase Jetpack Scan via the URL when the site is not connected yet. 
Load up this PR. 
1. Go to http://calypso.localhost:3000/jetpack/connect/scan
2. Enter a url of a connected site. 
3. notice that you end up on the correct checkout page (scan yearly)
1. Go to http://calypso.localhost:3000/jetpack/connect/scan/monthly
2. Enter a url of a connected site. 
3. notice that you end up on the correct checkout page (scan monthly)
> Jetpack: Add scan to the connect page

- client/lib/site/utils.js
- client/my-sites/domains/domain-management/edit/navigation/enhanced.jsx
* Show the destination of a domain - does it point to WordPress.com site or is external.
It looks like this:
* Open the new domain section and check the "Change your name servers and DNS records" menu for domains with/without our name servers
> Show the destination in the domains navigation item for name servers and DNS

- client/landing/jetpack-cloud/components/log-item/index.tsx
- client/landing/jetpack-cloud/components/scan-threats/index.tsx
- client/landing/jetpack-cloud/components/threat-description/index.tsx
- client/landing/jetpack-cloud/components/threat-description/style.scss
- client/landing/jetpack-cloud/components/threat-item/index.tsx
- client/landing/jetpack-cloud/components/threat-item/style.scss
- client/landing/jetpack-cloud/components/threat-item/threat.ts
- client/landing/jetpack-cloud/components/threat-item/types.tsx
- client/landing/jetpack-cloud/sections/scan/main.jsx
This PR attempts to render the treats as best as it can. 
We should move most of the treats details to the api vs figuring here. 
I reused quite a bit of code from treats-alert.jsx component to figure out nicer nameing etc. 
After:
Bonus part here is that treat ignoring works as expected 🥳 for the treat that I ignored. 
* On a site that has treats visit 
http://jetpack.cloud.localhost:3000/scan/{example.com}
Notice the sections renders real threats.
> Jetpack Cloud: Scanner display threats

- client/my-sites/site-settings/form-general.jsx
This PR introduces a new temporary setting for controlling the Earth Day Live banner.
With both the API and plugin in place and your site and the API sandboxed, you can test this PR on any WordPress.com site. The setting will not show for Jetpack sites which can install the [plugin directly](https://wordpress.org/plugins/earth-day-live-wp/).
- Go to My Sites > Manage > Settings on a WordPress.com site and confirm that the setting is available under the general tab, and that toggling it activates and deactivates the Earth Day Live banner on the front-end of the site.
D42135-code
> Add Earth Day Live setting

- client/my-sites/checkout/composite-checkout/wpcom/types/wpcom-store-state.ts
* In #41058 we refactored the managed contact details to include the extra ccTLD data. Here we include this when converting to DomainContactDetails and DomainContactDetailsErrors.
This should have no observable effect on checkout. Make sure this is the case by jerk testing checkout, keeping an eye on the contact validation step when domains are in the cart.
> composite-checkout: Add ccTLD data to prepareDomainContactDetails

- client/my-sites/customer-home/main.jsx
We currently display a button for viewing a site within My Home only when a site is launched making hard for new users to view their sites while they are building it.
This PR ensures the button is always visible, despite the site status.
Before | After
--- | ---
- Create a new site.
- Make sure the "View my site" button is visible when you land in My Home.
Fixes #41280
> My Home: Make "View my site" button always visible

- client/landing/jetpack-cloud/components/activity-card-list/index.jsx
- client/landing/jetpack-cloud/components/activity-card-list/style.scss
- client/landing/jetpack-cloud/components/activity-card/index.jsx
- client/landing/jetpack-cloud/components/activity-card/style.scss
- client/state/data-layer/wpcom/sites/activity/from-api.js
* Add primary color emphasis to the left of Activity Cards that are backups
* Move over non-backup cards and add connecting lines
2. Inspect page and various widths and compare to design
> Add Jetpack Cloud Activity Lines

- client/my-sites/invites/controller.js
- client/my-sites/invites/invite-accept/index.jsx
- client/my-sites/invites/utils.js
Fixes https://github.com/Automattic/wp-for-teams/issues/174.
In this PR, we modify the redirect after accepting an invitation to a WP for Teams site so that you land on the site's homepage instead of in Calypso.
Create a new WP for Teams site through the wp.com/start/wp-for-teams signup flow (or select one if you already have one). In the Invite section, invite some other email (using a 10 min email for example). When you receive the invitation link, copy the link and change its first part from `wordpress.com` to `calypso.localhost:3000` so that you use the local code changes. Load the invitation url and create a new WP.com account when prompted. You should be redirected to the site's homepage instead of Calypso.
Do the same but for a non WP for Teams site to verify the old behavior still …
> WP for Teams: redirect to homepage after invite

- client/my-sites/exporter/export-media-card/index.js
This removes the "Export media library" section from the Exporter when no media files are available.
1. Start on a site with no media files
2. Head to the Exporter and verify you can't export your Media Library
3. Upload a file
4. Verify the Exporter works as usual 
cc @arunsathiya, @creativecoder, @southp 
Fixes #32109
> Export Media: Hide when No Files are Present

- client/lib/abtest/active-tests.js
- client/my-sites/checkout/checkout/index.jsx
- client/my-sites/checkout/composite-checkout/test/composite-checkout-thank-you.js
- client/my-sites/checkout/composite-checkout/use-get-thank-you-url.js
* Per the request in pau2Xa-1bk-p2, we are dialling down the concierge upsell offers. It will now be shown only to 50% of EN users.
* Go through the signup flow at /start and purchase a Personal or Premium plan.
* When in the "offer" variation, you should be shown the concierge upsell. When in "noOffer" variation, you should not be shown the upsell. 
* For non-EN locale, you should not be assigned to the AB test and not shown the concierge upsell.
* Make sure that you test all of the above steps in both the old checkout and new checkout flow. For the new checkout flow, you need to have a US IP address and assign yourself to the `composite` variation of the showCompositeCheckout AB test.
> Dial down concierge upsell offer

- apps/wpcom-block-editor/src/calypso/features/gutenboarding-editor-overrides.js
After CfT we received some feedback regarding this button label (eg: p1586430673306700-slack-gutenboarding) which currently suggest an immediate _launch_ action which isn't actually happening when clicking on it. 
The suggestion to change it to "Complete Setup" is coming from p58i-8UC-p2#comment-46048
With the change deployed to wpblock-editor-plugin, when landing in the Editor after creating a site in Gutenboarding, the header should look like this:
> Gutenboarding pre-launch: Update CTA button label in the editor

- client/landing/gutenboarding/onboarding-block/edit.tsx
* Scroll the window to top when the route changes in Gutenboarding.
* On mobile, go to /design and tap on a design. 
* When landed on Font selector you should see the header
* Press "Choose another design" link at the bottom of the page
* On design page you should see the header. 
Fixes part of #41138
> Gutenboarding: Scroll to top on route change

- client/blocks/upsell-nudge/index.jsx
- client/components/banner/style.scss
- client/my-sites/marketing/main.jsx
- client/my-sites/site-settings/form-analytics.jsx
- client/my-sites/site-settings/jetpack-ads.jsx
- client/my-sites/site-settings/media-settings-performance.jsx
- client/my-sites/site-settings/search.jsx
- client/my-sites/site-settings/seo-settings/form.jsx
- client/my-sites/site-settings/seo-settings/test/form.jsx
- client/my-sites/site-settings/spam-filtering-settings.jsx
- client/my-sites/site-settings/test/form-analytics.jsx
* This PR migrates instances of `Banner` to `UpsellNudge` for consistency, while keeping all Tracks events (impression and click) the same. See #38778
* Also fixes a bug where the JP icon and colors weren't showing up for Jetpack ads.
| ------- | ------ |
| <img width="1107" alt="Screen Shot 2020-04-09 at 2 41 09 PM" src="https://user-images.githubusercontent.com/2124984/78929874-22aede00-7a71-11ea-96fc-519c49c0cba0.png"> | <img width="1110" alt="Screen Shot 2020-04-09 at 2 41 02 PM" src="https://user-images.githubusercontent.com/2124984/78929888-28a4bf00-7a71-11ea-9272-5c4ada4c1fdf.png"> |
| <img width="768" alt="Screen Shot 2020-04-09 at 2 46 42 PM" src="https://user-images.githubusercontent.com/2124984/78929913-31959080-7a71-11ea-8942-ba3218e0d8f9.png"> | <img …
> Upsell Nudges: Replace site settings Banners with UpsellNudge

- client/landing/gutenboarding/onboarding-block/style-preview/style.scss
This does maintain an accessible focus style with blue (default) outlines when tab navigation occurs. You can see it at the end of this gif:
* [`/new`](https://calypso.live/new?branch=gutenboarding/41214-latest-g7g-fixes)
> Gutenboarding: Fix viewport selector colors

- client/landing/gutenboarding/onboarding-block/style-preview/style.scss
From #41214
- The hover and click state for the font buttons. Hover state should be black text and outline and click state should be the same as active state or hover state.
You can see <kbd>tab</kbd> keyboard navigation focus styles at the end of the gif.
* [`/new`](https://calypso.live/new?branch=gutenboarding/41214-font-button-g7g-fix)
> Gutenboarding: Fix font-select Gutenberg style regressions

- packages/composite-checkout/src/lib/payment-methods/apple-pay.js
- packages/composite-checkout/src/lib/payment-methods/existing-credit-card.js
- packages/composite-checkout/src/lib/payment-methods/free-purchase.js
- packages/composite-checkout/src/lib/payment-methods/full-credits.js
- packages/composite-checkout/src/lib/payment-methods/paypal.js
- packages/composite-checkout/src/lib/payment-methods/stripe-credit-card-fields.js
When catching `Error` objects and then displaying them to the user, we currently just use the raw `Error`, which causes its `toString` method to be called, merging the `name` property with the `message` property.
However, this is not really what we want the user to see, as typically the `name` property is the name of the `Error` object "class". Instead they should just see the `message`.
This PR changes the behavior so that we always pass the `message` property on to be displayed.
**Before**
**After**
This changes each of the error handlers in all the payment methods, so to be thorough, there's quite a lot of things to try. We'll start with the most basic and the most common instance, however.
- Sandbox the store so you can load the stripe fields.
- Visit composite checkout and choose the …
> composite-checkout: Only display message property of caught payment Errors (1)

- client/landing/jetpack-cloud/components/activity-card-list/index.jsx
* Fix Detail, Download, and Restore links on `/backups/activity`
2. Verify the action buttons and content detail links to you to each type of page
> Fixes links from Activity Cards on Activity Log Page

- client/components/pagination/pagination-page.jsx
- client/components/pagination/style.scss
- client/landing/jetpack-cloud/components/activity-card-list/index.jsx
- client/landing/jetpack-cloud/components/activity-card-list/style.scss
- client/landing/jetpack-cloud/sections/backups/backup-activity-log/index.tsx
- client/landing/jetpack-cloud/sections/backups/controller.js
- client/my-sites/activity/filterbar/style.scss
* Update the `Pagination` component with more specific button styles ( so they don't get overridden by the Jetpack Cloud overall buttons styles )
*  Add rules to Jetpack Cloud `ActivityCardList` to match pagination with design.
* Add a little tweak to `Filterbar` to make the button styles more specific
2. Verify pagination matches design and works
* Arrows are correct color, disabled are the end of range
* Selected page is correct color
> Fix Jetpack Cloud Activity Log Styles

- client/landing/jetpack-cloud/components/activity-card/index.jsx
- client/landing/jetpack-cloud/components/activity-card/style.scss
- client/landing/jetpack-cloud/components/backup-delta/index.jsx
- client/landing/jetpack-cloud/components/daily-backup-status/index.jsx
- client/landing/jetpack-cloud/components/daily-backup-status/style.scss
- client/landing/jetpack-cloud/components/date-picker/style.scss
- client/landing/jetpack-cloud/sections/backups/main.jsx
- client/landing/jetpack-cloud/sections/backups/utils.js
This PR is a remake of https://github.com/Automattic/wp-calypso/pull/41193 with hopefully less rebase drama :-) Please see that PR for history.
- Process streams inside of events in order to enumerate rewindable events for realtime backups
- Fix display of realtime backups on main backups page
- Fix a few various (related) styling issues throughout
-Load up the backups page for a site with realtime backups. Do your restorable events appear in the proper chronological order?
-Include testing a day with streams. You can reproduce this by uploading several images at one time, and ensuring they appear as separate events on the backup page.
> Jetpack Cloud: Fix realtime backups display on main page

- client/landing/jetpack-cloud/components/date-picker/index.jsx
- client/landing/jetpack-cloud/components/date-picker/style.scss
* Change link URL in date picker component from `/activity/{site}` to `/backups/activity/{site}`
* Update CSS to give pointer cursor when hovering over the magnifying glass
Load backups page for any site. Ensure you can get to the activity log by clicking the magnifying glass at the top. Ensure the cursor is `pointer` when hovering.
> Jetpack Cloud: Fix link to activity log from date picker

- client/my-sites/sidebar/index.jsx
- client/my-sites/sidebar/test/sidebar.js
* Hide Earn menu item in "My Sites" sidebar when in an "All My Sites" view as we do not have an aggregated view.
1. Visit a page that has an "All My Sites" view, like `https://wordpress.com/stats/day`
2. Confirm Earn item is not under Tools.
3. Switch to a site on which the current user can earn.
4. Re-visit page from step one and confirm Earn menu item is present.
Menu Before:
Menu After:
Fixes: #41278
> My Sites: Hide sidebar earn menu when in All My Sites view

- client/my-sites/invites/invite-accept-logged-out/index.jsx
Addresses https://github.com/Automattic/wp-for-teams/issues/180.
In this PR, we assign the `signup_flow_name` to `wp-for-teams` for brand new wpcom users who were invited to a WP for Teams site.
Use a 10 minute email provider to get a new email address. Go to a WP for Teams site and invite your new email in an incognito window. Finish the signup process. You should not receive the WP.com Welcome email after signup (only the activation one).
> WP for Teams: assign custom signup flow name to new invited user

- config/horizon.json
This PR enabled `use-translation-chunks` feature flag in Horizon's config. Since we cannot test them using a `?flags` parameter on production, we'll test this on horizon.
N/A
> i18n: Enable use-translation-chunks config in horizon

- client/landing/jetpack-cloud/style.scss
Since the Jetpack Cloud section only gets loaded via the sidebar.
These styles should not be bleeding into calypso so we can make them less jetpack cloud specific. Which will make them easier to overwrite.
Before: 
After:
* Remove the specificity around links, and h3, h2, and paragraphs. 
Load up jetpack cloud does it still look like before? As expected?
Load up wpcalypso does it still look like as before? As exected?
> Jetpack Cloud: Make the button, and text style less specific.

- client/landing/gutenboarding/onboarding-block/acquire-intent/index.tsx
- client/landing/gutenboarding/onboarding-block/acquire-intent/site-title.tsx
* The vertical and site name are displayed on a separate line on mobile according to designs. In #41146 we removed period from Vertical Select step. It should also be removed for site name.
* Go to [/new](https://calypso.live/new?branch=update/gutenboarding-remove-site-name-period) on mobile. Fill in a vertical and a site title. 
* There should be no period displayed below the input.
> Gutenboarding: remove site name period on mobile

- client/landing/gutenboarding/onboarding-block/acquire-intent/vertical-select/index.tsx
* Scroll the window to top when vertical suggestions are rendered on mobile. In this way we prevent this bug on iOS: https://d.pr/v/11OyBC
* Go to [/new](https://calypso.live/new?branch=fix/gutenboarding-vertical-select-ios) on iOS.
* When typing to enter a vertical and suggestions list becomes visible, I should also see what I'm typing without having to scroll.
Follow up of #41146, addressing https://github.com/Automattic/wp-calypso/pull/41146#pullrequestreview-395237653
> Gutenboarding: fix vertical selector on iOS

- client/landing/jetpack-cloud/components/threat-item/style.scss
* Move the "Fix threat" and "Ignore threat" buttons down, so they're below the threat details.
* Center-align the button(s) horizontally.
* Add 5px of inline/left-right margin to these buttons so they don't sit against each other on mobile
* Do we want to center-align the buttons, or is there a better/more conventional alignment we should use?
* On mobile, do we want the outside edge of each button to align with the edge of the content? In this PR, currently, they are set inward by 5px.
* Load Jetpack Cloud for a site with a threat. Expand the threat details.
* On desktops, ensure that the "Ignore threat" button is positioned below the threat details.
* On mobile devices, ensure that both the "Fix threat" and "Ignore threat" buttons are positioned below the threat details.
* On mobile …
> Jetpack Cloud: Position fix/ignore buttons below threat details

- client/landing/jetpack-cloud/components/daily-backup-status/index.jsx
- client/landing/jetpack-cloud/components/scan-threats/index.tsx
- client/landing/jetpack-cloud/lib/contact-support-url.js
- client/landing/jetpack-cloud/sections/backups/main.jsx
- client/landing/jetpack-cloud/sections/backups/rewind-flow/download.tsx
- client/landing/jetpack-cloud/sections/backups/rewind-flow/index.tsx
- client/landing/jetpack-cloud/sections/backups/rewind-flow/restore.tsx
- client/landing/jetpack-cloud/sections/scan/main.jsx
* Add a query parameter `site` to every "Contact Support"-type link in Jetpack Cloud, which indicates the currently selected site.
* Ensure that all 'contact support' link URLs contain a query parameter of the form `?site=<site url>`. This includes (but may not be limited to) the following places:
* **Daily Backup Status**: "Contact support" button (when a backup failed for a specific day, no backup exists for a specific day, or if no backups are available at all)
* **Main Scan page**: "Contact support" button (when scan encountered an error)
* **Threats**: (when threats are found) "Please review them below and take action. We are `here to help` ..."
* **Download backup**: "Contact support" button (when an error occurs creating the download)
* **Restore backup**: "Contact support" button …
> Jetpack Cloud: Add site URL to all 'contact support' links

- client/landing/gutenboarding/onboarding-block/create-site/index.tsx
- client/landing/gutenboarding/onboarding-block/create-site/style.scss
- client/lib/interval/use-interval.ts
Closes #40884 
Applies all changes:
- Remove the vertical text animation. It should just swap instantly between the text like in the prototype.
- Let's add a `--studio-gray-10` background behind the loading bar. See screenshot.
- Change the height of the loading bar from 7px to 6px
- Remove "Getting your domain" unless they actually got a paid domain
* [`/new`](https://calypso.live/new?branch=gutenboarding/40884-create-site-loader-tweak)
* Go through the flow without selecting a domain - there should be 2 steps (no domain).
* Go through the flow selecting a WordPress.com subdomain - there should be 2 steps (no domain)
* Go through the flow selecting a paid domain - there should be 3 steps (including domain)
> Gutenboarding: Site creation tweaks

- client/landing/jetpack-cloud/components/scan-badge/index.tsx
- client/landing/jetpack-cloud/components/sidebar/index.jsx
- client/landing/jetpack-cloud/components/sidebar/style.scss
- client/state/selectors/get-site-scan-progress.js
* This PR queries the scan api endpoint and displays 2 different states. 
Scan Alerts:
Scan Progress:
* Load up this PR. 
* Load any section in the Jetpack Cloud for a site and notice that the sidebar looks as expected. 
* If there is a Threat found and the site support scan you should see a threat. 
* If you starts a scan (This part I tested by modifying the progress) you should see the sidebar update with the progress.
> Jetpack Cloud: Add Scan Alert and scan progress in the sidebar all the time.

- client/landing/jetpack-cloud/components/scan-threats/index.tsx
- client/landing/jetpack-cloud/components/sidebar/index.jsx
- client/landing/jetpack-cloud/components/threat-item/style.scss
- client/landing/jetpack-cloud/sections/scan/history/index.jsx
- client/landing/jetpack-cloud/sections/scan/main.jsx
- packages/calypso-analytics/src/tracks.ts
- Add analytics to Jetpack Scan by tracking main UI events.
- It's open for discussion if we should prefix our events with `calyspso` as the rest of the events of the platform are or if we should create a new prefix for Jetpack Cloud. Depending on that, the name of the events may change accordingly.
I have separated the testing instructions by sections to make them easier to understand. The sections affected by this PR are: sidebar, Scan -> Scanner, and Scan -> History.
- Go to http://jetpack.cloud.localhost:3000
- Select a site
- Click on Backup -> Activity Log menu item
- Verify that the `ANALYTICS_EVENT_RECORD` action was dispatched with the following payload
```
{
service: 'tracks',
name: 'calypso_jetpack_cloud_sidebar_menuitem_click',
properties: {
menu_item: 'Jetpack Cloud Backup / …
```
> Jetpack Cloud: track events in Scan (analytics)

- apps/full-site-editing/full-site-editing-plugin/event-countdown-block/index.php
- apps/full-site-editing/full-site-editing-plugin/jetpack-timeline/index.php
Update Event Countdown and Timeline blocks to move the asset loading to `render_callback`
This also requires rendering the content out of PHP.
* Prior to applying change: create a post with the Event Countdown and Timeline blocks.
* Confirm when loading this post, the assets event-countdown.js, event-countdown-block.css, and jetpack-timeline.css all load. Also confirm that these assets load when viewing any post on the site.
* Apply this change, its just PHP, so no build required.
* Reload the post with the Event Countdown and Timeline blocks. Confirm it looks fine, and the js and css assets load properly. View any other posts and confirm the assets do not load there.
* Confirm properly loading on index and other pages the block may show up.
Related; #40987
> Move asset loading to render_callback for Event Countdown and Timeline blocks

- apps/wpcom-block-editor/src/wpcom/editor.js
- apps/wpcom-block-editor/src/wpcom/features/tracking/wpcom-inserter-menu-search-term.js
This PR fixes an issue that occurs in Atomic sites. It's produced because of the client plugin version is `undefined` for these sites, which records the same `no-results` search term twice.
**Confirm the issue.**
You need to sandbox `widgets.wp.com` and apply these changes to your sandbox
Also, open the client dev console and set up the debug
```
> localStorage.setItem( 'debug', 'wpcom-block-editor*' )
```
A hard refresh is needed.
In your Atomic site, start to type a term in the Inserter Menu.
Confirm that it records two `wpcom_block_picker_no_results` register for the same event.
(Disable cache for the requests)
With this patch, it should be recorded once. Also, I've improved a little bit the log lines, adding the `unknown_version`
Next improvement is to expose the Gutenberg version …
> Tracking: fix inserter-menu issue in Atomic sites

- client/lib/purchases/index.js
This updates the `isRemovable()` logic to allow for removing non-refundable domain subscriptions that have `expiryStatus === 'autoRenewing'`. This is a highly uncommon status, as it only applies to a small number of TLDs that don't support explicit renewals, and is only set when the corresponding store subscription is set to auto-renew.
The core issue is that in some cases, we don't show an option to cancel or remove the domain, when we should always show exactly one of those two items. The issue definitely applies to cases where the domain is bought entirely using credits, but may also apply to situations where the domain purchase is no longer refundable.
Register a new `.jp` domain using credits.
Using an unpatched Calypso UI, verify that if you navigate to the domain settings for the …
> Support removal of autorenewing domain registrations

- client/me/help/help-contact/index.jsx
Add back the "Limited chat availability" notice, which was accidentally removed when we [put up a closure notice last weekend](https://github.com/Automattic/wp-calypso/pull/41236).
"Limited chat availability" notice should appear on Inline Help and Contact page.
> Contact: "Re-add Limited chat availability" notice

- client/my-sites/checkout/composite-checkout/test/composite-checkout.js
- client/my-sites/checkout/composite-checkout/wpcom/components/wp-checkout-order-review.js
- client/my-sites/checkout/composite-checkout/wpcom/components/wp-checkout-order-summary.js
- client/my-sites/checkout/composite-checkout/wpcom/components/wp-checkout.js
- client/my-sites/checkout/composite-checkout/wpcom/components/wp-order-review-line-items.js
- packages/composite-checkout/README.md
- packages/composite-checkout/demo/index.js
- packages/composite-checkout/src/components/checkout-order-summary.js
- packages/composite-checkout/src/components/checkout-steps.js
- packages/composite-checkout/src/components/default-steps.js
- packages/composite-checkout/src/components/loading-content.js
- packages/composite-checkout/src/components/shared-icons.js
- packages/composite-checkout/src/lib/line-items.js
- packages/composite-checkout/src/public-api.js
- packages/composite-checkout/src/theme.js
- packages/composite-checkout/test/checkout.js
Originally attempted in #41063 and reverted in #41363 
This does a few things with the ultimate goal of splitting out a summary into a separate column on desktop screens.
- adds the floated `CheckoutSummary` component to composite-checkout (package, demo, documentation)
- add `CheckoutStepArea` component to handle styling of `CheckoutSteps` + `CheckoutStepBody`
- uses `CheckoutSummary` in WPcom's implementation of composite-checkout
- moves the current site's address to the review step
- adds a default set of purchase features to the summary (per-product features coming in a future PR)
- hides `CheckoutSummary` on mobile screens (collapse mobile toggle coming in future PR)
Before | After
Fixes: #41088
**To test:**
- it might help to step through the PR, commit …
> New Checkout: split layout (take 2)

- docs/coding-guidelines/typescript.md
* Fixes variable names that are declared all caps but then used lowercase.
> Fix incorrectly capitalized variable in example

- client/my-sites/pages/page/index.js
* Hides the "Copy Pages" option if the module in Jetpack is disabled.
Start by disabling the module in Jetpack: `/wp-admin/admin.php?page=jetpack#/writing`
Then verify that after clicking the ellipses next to pages, "Copy page" disappears. It should re-appear once the module is enabled, or if you're using a WordPress.com site.
cc @lancewillett 
Fixes #40995
> Copy Pages: Hide if Jetpack Module is Disabled

- client/components/marketing-survey/cancel-purchase-form/step-components/downgrade-step.jsx
- client/me/purchases/cancel-purchase/refund-information.jsx
Make it clearer to users that downgrading a subscription will come into effect immediately. Relates to #37982
This will add a downgrade warning message to:
* First step of the cancellation process
* Downgrade selection step
Example of original text:
> When you cancel your subscription, you'll be able to use WordPress.com Premium until your subscription expires. Once it expires, it will be automatically removed from your site.
* Must be a simple site (not Atomic)
* Needs to have at least Premium plan upgrade
* Auto-renewal must be enabled
1. Visit URL: https://wordpress.com/me/purchases
2. Select the Business or Premium plan to be downgraded.
3. Choose "Cancel Subscription".
4. Check the cancellation information includes downgrade warning.
5. Click the "Cancel Subscription" button.
6. …
> Downgrades: Make text clear that downgrades occur immediately

- client/landing/gutenboarding/components/header/index.tsx
- client/landing/gutenboarding/onboarding-block/create-site/index.tsx
- client/landing/gutenboarding/stores/onboard/selectors.ts
* Adds `hasPaidDomain` selector to the Gutenboarding store.
* No changes in behavior.
* [`/new`]() flow works as expected with and without selecting a paid domain. 
Closes #41357
> Gutenboarding: Add and use hasPaidDomain selector

- client/landing/gutenboarding/onboarding-block/style-preview/style.scss
Remove a bottom margin from the font preview that caused vertical overflow and scroll.
If this was necessary for some reason, it should be included in this calc:
https://github.com/Automattic/wp-calypso/blob/9b56310d9f0beb9b54aaf347a654d90cff619daa/client/landing/gutenboarding/onboarding-block/style-preview/style.scss#L7
* [`/new`](https://calypso.live/new?branch=gutenboarding/fix-41324-preview-scroll)
* Design picker step desktop view does not have any vertical scrolling, it adapts to the viewport size.
Fixes #41324
> Gutenboarding: Fix preview scrolling

- client/landing/gutenboarding/components/domain-picker-button/style.scss
- client/landing/gutenboarding/components/header/style.scss
- client/landing/gutenboarding/onboarding-block/style-preview/style.scss
- Domain picker. Hover state should be 1px solid --studio-gray-100 instead of the 2px solid blue
- Domain picker. When clicking the domain picker and clicking it again to close it it gets this blue border. Lets remove that
* [`/new`](https://calypso.live/new?branch=gutenboarding/41214-domain-picker-style)
* Check the domain picker styling.
Fixes #41214
> Gutenboarding: Fix domain picker styling

- client/components/marked-lines/index.jsx
This Pr fixes an error found in the Marklines component.
This PR fixes this issue by making sure that each of the keys is unique. 
* Load up this PR in jetpack cloud. 
* Go to the /scan page where a site has a threat. Open up the threat. Nice that the error is not there any more.
> Marklines: Fixe React error where the same key is being used.

- client/landing/jetpack-cloud/components/activity-card-list/index.jsx
- client/landing/jetpack-cloud/index.js
- client/landing/jetpack-cloud/sections/home.tsx
- client/state/selectors/get-primary-site-is-jetpack.js
- client/state/selectors/get-rewind-capabilities.js
* Updates routing logic for Jetpack landing page to direct users to primary site.
Expected results:
* With a primary site of WP.com: Redirect to site picker for backups.
* With a primary site of JP:
* Redirect to backups for site if backups purchased.
* Redirect to scan for site if scan and **not** backups purchased.
* Redirect to site picker for backups if neither purchased.
Fixes 1156570014567299-as-1170686186292217.
> Adds Jetpack routing for homepage

- client/blocks/upsell-nudge/index.jsx
- client/my-sites/theme/main.jsx
- client/my-sites/themes/single-site-jetpack.jsx
- client/my-sites/themes/single-site-wpcom.jsx
* Migrating instances of `Banner` to `UpsellNudge` to consolidate components. See #38778
**Visual References**
* Go to `/themes` on a _Jetpack site_ with a free plan; note the upsell at the top of the screen. Ensure Tracks values are the same and the visuals match production. Make sure the nudge does *not* show when viewing with a Premium or higher plan.
* Go to `/themes` on a WordPress.com site with a free plan; scroll to the bottom and click on "Show all themes" and scroll past the search to see another upsell. Make sure the Tracks events and visuals match production. This should *not* show when viewing on a site with a Premium or higher plan.
* Go to a single premium theme page like Ovation: https://wordpress.com/theme/ovation on a _WordPress.com site_ with a free plan; note the upsell …
> UpsellNudge: Migrate Banners to UpsellNudge

- client/landing/jetpack-cloud/components/activity-card/index.jsx
- client/landing/jetpack-cloud/components/activity-card/style.scss
Add ActivityMedia blocks to the ActivityCards where available.
* View the backups page for a realtime backups site, or the Activity Log section for any site. Ensure that image uploads/attachments display the actual image, full-width, per Figma.
* Please note, there are further revisions that will be done to grouped/stream events. That is not up for review here.
> Jetpack Cloud: Add images to activity cards

- client/landing/jetpack-cloud/style.scss
Set the Universal Text Styles introduced by Caleb more specific, so let's move it inside of `.theme-jetpack-cloud` class. Currently, they don't work well because is less specific in the inheritance of CSS.
- Apply changes
- Now you can use the text styles `h2`, `h3` and `p` without problems
> Set Universal Text Styles more specific. Move it into .theme-jetpack-cloud

- client/jetpack-connect/authorize.js
Required by https://github.com/Automattic/jetpack/pull/15470
* Add a new condition to the Jetpack Connect authorization flow: if the request has a `from=jetpack-block-editor` query parameter, redirect to the provided `redirect_uri` once the authorization is complete.
* Checkout this PR and `yarn start` Calypso.
* On a Jetpack site, checkout [`update/instagram-gallery-disconnected-users`](https://github.com/Automattic/jetpack/pull/15470), and run `yarn build-extensions`.
* Create a secondary user (author or above), and then connect the site to Jetpack.
* Open a **guest window** of the browser to simplify testing with secondary accounts of both the JP site and WPCOM. Make sure it's **not incognito**, since you'll need cookies.
* Log in to the site with the secondary account.
* Head to the …
> Jetpack Connect: Add a new condition to force redirect to wp-admin

- client/landing/jetpack-cloud/components/activity-card-list/index.jsx
- client/landing/jetpack-cloud/components/activity-card-list/style.scss
- client/landing/jetpack-cloud/components/activity-card/index.jsx
- client/landing/jetpack-cloud/components/activity-card/style.scss
- client/landing/jetpack-cloud/sections/backups/backup-activity-log/index.tsx
* control activity card rendering content links and action buttons
* add more content orbs 
1. Navigate to `backups/activity`
2. Verify that the "changes in this backup" link is hidden for backups with no content
3. See that the pagination orbs appear when content rolls over to the next page ( you may need to adjust the pageSize variable in activity log to summon the orbs )
> Jetpack Cloud: Conditionally Hide Activity Card Content Link

- client/state/data-layer/wpcom/wordads/settings/index.js
The WordAds settings form won't save if the PayPal field isn't set. This will alert the user that they need to enter a valid PayPal email.
* Gives descriptive error for missing PayPal email.
* Go to `Tools -> Earn -> Ad Dashboard -> Settings`.
* Delete any entry in PayPal field and try to save.
* Notice `Please enter a valid PayPal email address.` should show.
* Enter valid email address and save -> should be successful.
> WordAds Settings: Add better error notice for missing PayPal

- client/me/social-login/action-button.jsx
* Replace transient Zi usage w/ getAuthResponse similar to https://github.com/Automattic/wp-calypso/pull/39291
1. Starting at URL: https://wordpress.com/me/security/social-login
2. Select "Connect" next to Google, to connect a Google account to your existing WordPress.com account.
3. Login/select your Google account in the pop-up window that appears.
4. Verify you are now connected or disconnected
Fixes #39459 CC @rachelmcr
> Me: Social Login, replace transient Zi usage w/ getAuthResponse

- client/blocks/product-selector/index.jsx
* Include "Manage Product" on the Jetpack product cards in Plans tab for both monthly and yearly toggle.
* purchase monthly or yearly Jetpack Search (or Scan)
* go to `/plans` in Calypso
* verify that the Manage Product CTA appears under both monthly and yearly options
Fixes https://github.com/Automattic/wp-calypso/issues/40549
> Plans: display "Manage Product" CTA irrespective of payment frequency in JP product cards.

- client/jetpack-connect/connection-notice-types.js
- client/jetpack-connect/jetpack-connect-notices.jsx
- client/jetpack-connect/main.jsx
Atm, Search is a Jetpack product, but it will become available for WP.com sites in the future. 
* Here,  we add a notice when users arrive at the connection step following Search purchase flow and input their WP.com site address. 
* start at the url input form of the JPC flow: `/jetpack/connect/jetpack_search`  (try with parameters e.g. being redirected from the LP `?cta_id=landing-page-search-primary-cta&cta_from=upgrade_search`
* input a WP.com site
* verify that the notice appears:
> Jetpack Connect: add a separate notice for WP.com sites purchasing Search

- apps/wpcom-block-editor/src/calypso/features/gutenboarding-editor-overrides.js
- client/gutenberg/editor/calypsoify-iframe.tsx
- client/landing/gutenboarding/components/header/index.tsx
- client/signup/config/flows-pure.js
- client/signup/config/flows.js
- client/state/sites/constants.js
This PR makes sure the context of the block editor is always 'gutenboarding' for new _created-via-the-gutenboarding-flow_ sites **until they are launched**.
We're doing this by:
- Ensuring that we're returning the `site_creation_option` for me/sites
- Sending `isGutenboarding === true` to the wpcom block editor iframe only when a site:
- has been created by Gutenboarding and
- the site is unlaunched
Apply D42191-code
Create a new site at http://calypso.localhost:3000/new
You'll land on
http://calypso.localhost:3000/block-editor/page/{your_new_site_url}/home
In the `post.php` context, take a look at `window.calypsoifyGutenberg`. 
`isGutenboarding` should be `true`
Make note of the header buttons
And CSS classes
Launch your site, and return to …
> Gutenboarding: 'Sticky' launch Button 

- client/my-sites/hosting/main.js
This should ensure the upsell nudge appears on the Hosting page for Personal & Premium sites.
Verify that the upsell appears for sites on the Personal & Premium plan, but not any higher plans. 
Note: I've not tested with the Premium plan as I don't have access to such a site, but this should work with it 
cc @sixhours 
Fixes #41416
> Hosting: Let Upsell Appear for Personal & Premium Sites

- client/landing/jetpack-cloud/components/scan-threats/index.tsx
- client/landing/jetpack-cloud/components/threat-item/index.tsx
- client/state/selectors/get-jetpack-credentials.js
* This PR removes the fix all threat button if there is no threats to fix. 
* It also make sure that we only try to fix only the threats that are fixable. 
* It also removed the ... button since it s not used yet. cc @keoshi what should happen when you click on that button?
* It removed how we get the credentials form. It shouldn't be there if the credentials are set. 
* It also updates the contact us links. 
Before:
After:
* On a site that only has threats that can't be fixed. Do not show the "Fix all button"
* Notice that the button is still there if a site needs has items that needs fixing. 
* Notice that the Credentials form is not displayed if the correct credentials are shown. 
* Notice that the contact us link in the item description that for the treat we can't fix contains the …
> Jetpack Cloud: Remove fix all threat button if there is nothing to fix

- client/landing/gutenboarding/gutenboard.tsx
Looks like this legacy import is no longer needed.
This was severely impacting Gutenboarding entry point size, inflating it by ~670KB uncompressed, or ~140KB gzipped!! (two exclamation marks required)
It was pulling in a number of large components and dependencies, e.g. date picking stuff.
Local testing seems to indicate everything works fine after removal, as I was able to complete the creation process up until the full editor popped up.
* Remove unnecessary `@wordpress/editor` import
Ensure that Gutenboarding continues to work normally. Team Luna will know a lot better than me exactly what that entails 🙂
> Remove editor import in gutenboard

- client/my-sites/checkout/checkout/index.jsx
Sequel to https://github.com/Automattic/wp-calypso/pull/41123
* Including  daily, early and real-time plans.
-   Start at /jetpack/connect/plans/:site, for a CONNECTED site (else we cannot reach that url)
-  purchase a product
-  verify that the checkout url contains product info
- verify the relevance of the Thank you note
Verify that the upsell flow works for the WP.com sites.
> Checkout: expand the definition of Jetpack Products redirected to the checklist/Thank You modal

- client/landing/jetpack-cloud/components/date-picker/index.jsx
- client/landing/jetpack-cloud/components/date-picker/style.scss
- client/landing/jetpack-cloud/sections/backups/main.jsx
Improve the styles to match with Figma design (mobile view):
- Search icon should match the expected color and the size 24x24px
- The chevron icons should be color gray-70 and the size 24px
- Next display text should be gray-10 if the selected date is today
- Calendar icon should be centered with a size of 24x24px
- Font size should be 16px
- Add a link to the search icon with the Activity log path
**Figma design:**
**Our previous design:**
**Now:**
*Desktop view must be improved in general
- Apply these change
- Check if the styles match the design specification
> Fix the DatePicker styles to match the design

- client/landing/jetpack-cloud/components/scan-history-item/index.tsx
- client/landing/jetpack-cloud/components/scan-threats/index.tsx
- client/landing/jetpack-cloud/components/threat-item/types.tsx
- client/landing/jetpack-cloud/sections/scan/main.tsx
- client/landing/jetpack-cloud/sections/scan/types.tsx
- client/state/data-layer/wpcom/sites/scan/history/index.js
- client/state/data-layer/wpcom/sites/scan/index.js
- client/state/selectors/get-site-scan-progress.js
- Update the Scan main section to make it handle the states provided by the latest version of the API.
I took the opportunity to fix snake case keys and string dates at the data-layer for Scan and Scan History endpoints. For this to work, I had to update the Threat type and the Scan type.
- Run this PR
- Go to http://jetpack.cloud.localhost:3000/
- Select a site that has Jetpack Scan which has threats and the Scan is reporting an error (one can force this in the code or editing the ScanThreats component props)
- Verify you see the normal Threats state and there is card that notifies you that an error happened
- Select a site that has Jetpack Scan and its state is `unavailable` ([read this to understand of the Scan can be in that state](https://github.com/Automattic/wp-calypso/pull/41344#di …
> Jetpack Cloud: Update Scan UI to match the API states 

- client/components/data/query-jetpack-scan/index.tsx
- client/components/data/query-jetpack-scan/test/index.js
- client/landing/jetpack-cloud/components/scan-threats/index.tsx
- client/state/data-layer/wpcom/sites/alerts/fix.js
- client/state/data-layer/wpcom/sites/alerts/ignore.js
- client/state/data-layer/wpcom/sites/scan/index.js
- client/state/data-layer/wpcom/sites/scan/test/index.js
- client/state/jetpack-scan/actions.js
- client/state/jetpack/site-alerts/actions.js
This PR has 3 goals:
1. Request the state of the Scan every time a user visits the Scanner section.
2. Request the state of the Scan after ignoring or fixing a threat.
3. Request the state of the Scan if the current state is `'scanning'` until it finishes.
- I renamed the action creator `requestJetpackScanStatus` to `requestScanStatus`. 
- I made optional the behavior of requesting the state of the Scan after ignoring/fixing a threat. This so to preserve the behavior of other parts of the app that use the same action creators we use.
- The pooling mechanism, required by goal #3, was implemented at the data-layer level. It can be opted out by setting the `pooling` prop to `false` in the action object. So, for instance, ignoring/fixing a threat dispatch this action with `pooling` set to …
> Jetpack Cloud: add events that trigger a request for the Scan state

- client/blocks/upsell-nudge/docs/example.jsx
- client/blocks/upsell-nudge/index.jsx
Adds a few more upsell nudges to Devdocs for clarity, including a Jetpack-styled nudge.
**Before**
**After**
* Switch to this PR, navigate to `/devdocs`
* Go to Blocks -> Search for `UpsellNudge`
* Note the added nudges, look for visual or console errors
> DevDocs: Add more comprehensive UpsellNudge examples

- client/landing/jetpack-cloud/components/upsell-switch/README.md
- client/landing/jetpack-cloud/components/upsell-switch/index.tsx
- client/landing/jetpack-cloud/sections/scan/controller.js
- client/landing/jetpack-cloud/sections/scan/index.js
- client/state/selectors/get-rewind-capabilities.js
* This changes the scan upsell logic to use a new flexible upsell component.
* In Jetpack, load a site _with_ Scan and observe if it loads.
* Check Scan History as well.
* Load site without Scan and see if upsell displays.
Fixes 1151678672052943-as-1172451663334993.
> Refactors upsell to use state machine API

- client/my-sites/domains/domain-management/edit/navigation/enhanced.jsx
* As discussed in #41019 I'm changing the destination text for when a domain doesn't point to WordPress.com site. I chose "external service" as I believe all other options could generate some confusion.
It looks like this:
I'll also commit this now so that we don't send confusing strings for translation next Monday
* Open a domain that doesn't point to a WordPress.com site and check the "Change your name servers & DNS records" nav item
> Update destination text for when domain is not pointing to WordPress.com site

- apps/wpcom-block-editor/src/calypso/features/iframe-bridge-server.scss
This removes the left margin override on the block inserter in the header within the editor (The big plus button), which should return the alignment to match what's in core, and also resolve a mobile styling issue with this button.
* Remove margin-left override on `. block-editor-inserter__toggle` in wpcom-block-editor as requested in https://github.com/Automattic/wp-calypso/pull/40361#issuecomment-617685289
* Build and sync to your sandbox, or sandbox D42316-code (a pre-generated build)
* Sandbox your test site and widgets.wp.com
* Go to your test site in the block editor in Calypso, e.g. https://wordpress.com/block-editor/post/andysgutenbergedgetestsite.wordpress.com/243 and ensure the spacing looks like in the screenshots above (a little more margin for the plus button in the header)
* …
> Remove margin-left override on block-editor-inserter__toggle in wpcom-block-editor

- client/my-sites/customer-home/cards/education/educational-content/index.jsx
This PR fixes a console warning about missing keys for the education content links.
* Open devtools, then load My Home for the upcoming i1 with the needed flag: http://calypso.localhost:3000/home/:site?flags=home/experimental-layout
* Notice the above console warning.
* Load again, and verify the message is not displayed.
> My Home: Add missing keys to educational content links.

- client/lib/i18n-utils/switch-locale.js
This PR adds switch locale handling in runtime when translation chunks feature is enabled.
1. Boot Calypso with `ENABLE_FEATURES=use-translation-chunks yarn start`
2. Open http://calypso.localhost:3000/start/user/pt-br
3. Use the links in the language suggestion box above the form to switch the locale
> i18n: Handle switch locale in runtime with translation chunks

- client/landing/gutenboarding/onboarding-block/design-selector/index.tsx
* Keep user entered information when pressing 'Go back' button.
* Go to [/new](https://calypso.live/new?branch=update/gutenboarding-keep-intent-capture-info)
* Fill in one or both inputs and advance to Design picker step.
* Press _Go back_ button.
* Now your previously entered information should be still visible.
Fixes #41303
> Gutenboarding: Keep Intent capture user information

- client/landing/gutenboarding/components/domain-picker-popover/index.tsx
- client/landing/gutenboarding/components/header/index.tsx
- client/landing/gutenboarding/components/header/style.scss
- client/landing/gutenboarding/components/plans-button/index.tsx
- client/landing/gutenboarding/components/plans-button/style.scss
* Display current pre-selected plan (free / personal) in header while on Design picker and Style picker steps.
* We currently display it as a disabled button (without interaction) to serve as a hint for users that their domain selection triggered also a plan upgrade. This will prepare them for the plans page we’re displaying immediately after site creation.
* Go to /new
* Fill in both inputs (vertical and site name).
* Open domain picker and select a paid domain.
* While still on Intent Capture step, the plans button shouldn't be visible.
* When advancing to Design picker step, Personal Plan should be displayed in header (top-right).
* After selecting a free domain or if no domain is selected, Free Plan label is displayed.
* On mobile, just the Jetpack logo should be displayed.
Fixes …
> Gutenboarding: add plans component to header

- client/my-sites/plans/current-plan/current-plan-thank-you/thank-you.js
* Removes wp-admin dashboard link.
* Rewords link to the customizer.
* Go to `/plans/my-plan/:site?thank-you=&product=jetpack_search` for a connected JP site
* Verify the change in copy:
Fixes https://github.com/Automattic/wp-calypso/issues/41029
> Post-checkout: adapt the buttons in the Search Thank you modal

- client/landing/jetpack-cloud/components/scan-badge/index.tsx
- client/state/selectors/get-site-scan-progress.js
* Display in the sidebar, the current Scan progress when the Scan is in the `scanning` state.
* I made the `getSiteScanProgress` selector return the progress only when the Scan is in the `scanning` state. It returns undefined in any other case. I can't see a case in which we would need the progress when the Scan is not running.
* I made the `ScanBadge` component prioritize showing the current progress over the number of threats. This will happen only when the Scan is in the `scanning` state as it was explained in the previous point.
- Run this PR
- Go to `http://jetpack.cloud.localhost:3000/`
- Select a site that has Jetpack Scan
- Trigger a Scan execution (I triggered a Backup from VaultPress)
- Refresh the browser until you see the UI for the `scanning` state
- Verify the current …
> Jetpack Cloud: show the Scan progress in the sidebar when scanning

- apps/full-site-editing/full-site-editing-plugin/global-styles/class-global-styles.php
- apps/full-site-editing/full-site-editing-plugin/global-styles/static/blank.css
Switch enqueue to use false in register script that still allows hooking into for wp_add_inline_script but does not require an actual file to be loaded. Enqueue will then simply print to screen.
This removes loading an empty blank.css file.
See core global styles for reference usage:
https://github.com/WordPress/gutenberg/blob/master/lib/global-styles.php#L222
* Base: Load global styles on a page and confirm the global styles `blank.css` loads. Search in source for `global-styles` css handle.
* Apply PR and confirm the styles still show as expected, you should see the same CSS written out to the source, but no `blank.css` file
**Testing Note:** You can load global styles on a page by using a theme that supports global styles such as Varia, and then setting a style using the right-column …
> Remove loading of blank.css for Global Styles

- client/landing/jetpack-cloud/sections/scan/main.tsx
* Removes stats from Scan footer while data is unavailable.
* Visit scan page.
* Look for plugin/theme/file stats in footer.
Fixes 1143508703416848-as-1173050013652923.
> Hides scan stats

- apps/full-site-editing/bin/setup-env.sh
Currently, if any of wp-calypso ancestor dirs has a whitespace in its name the script fails. 
Assuming wp-calypso lives in `/some/we have a white space/wp-calypso`. Then 
```sh
dir_path=`pwd`
cur_dir=`basename "$dir_path"` # -> we
```
Adding double quotes fixes the issue.
> Support whitespaces in wp-calypso path in FSE setup script

- config/_shared.json
This reverts a small change made in #40542 that broke Sibyl / Q and A since April 10, which was deflecting ~1,000 support contacts a week. After this change, Sibly was only serving support page suggestions for sites with a Jetpack plan.
That PR updated `wpcom_support_blog` to the new support site because the URL for support pages has recently changed — but this config value is not used to generate URLs, it's actually only used right now for Sibyl. The underlying blog is still `en.support.wordpress.com`, so this should have stayed as-is.
/cc @arunsathiya — your commit was massive and this was easy to miss, but just worth double-checking the usage of things like config vars to see what they're wired to before changing them.
Before: 
- Pick a site of yours that has no Jetpack plan
- Go to …
> Sibyl: Make it show again for all sites

- client/my-sites/customer-home/cards/tasks/domains/index.jsx
- client/my-sites/customer-home/cards/tasks/find-domain/index.jsx
- client/my-sites/customer-home/locations/primary/index.jsx
This PR adds a "Look more professional" task card, prompting the user to find a domain for their site.
* Sandbox the API and apply D42369-code.
* On this branch, load `http://calypso.localhost:3000/home/:site?flags=home/experimental-layout` with a launched site that has a Premium or higher plan that hasn't used its domain credit yet.
* Verify the card appears.
* Use the "free domain available" upsell in the sidebar to attach a domain to the site.
* reload Home, and verify the card does not appear.
* Verify the card does not appear for sites without plans, nor sites that already have a domain attached.
Fixes https://github.com/Automattic/dotcom-private/issues/39
> My Home: Add a Find Domain task card for i1.

- client/my-sites/checkout/composite-checkout/wpcom/components/wp-checkout-order-summary.js
This adds the `coupon` line item to the `CheckoutSummary` when a coupon has been added to the cart.
**To test:**
- add a plan and/or domain to your cart and visit Checkout with `?flags=composite-checkout-force`
- verify that the checkout summary only displays features and the total (and maybe taxes if previously computed)
- add a coupon
- verify that the checkout summary now includes the coupon line item
> Checkout: add savings to CheckoutSummary

- packages/composite-checkout/README.md
- packages/composite-checkout/src/components/checkout-provider.js
- packages/composite-checkout/src/lib/form-status.js
This PR updates `CheckoutProvider` in the composite-checkout package to add an optional `isValidating` prop. If set, this prop will set the form's status to 'validating' and can be used to disable the form for situations like when the cart items are being updated.
This should have no effect on composite checkout and is split off from #41456 
Verify that you can load composite checkout without any issues, that the pulsing "loading" page is displayed briefly before we see the actual checkout form, and that changing steps works as expected.
> composite-checkout: Add isValidating prop to CheckoutProvider

- client/landing/jetpack-cloud/sections/backups/main.jsx
2. Change the filter
3. Click `Backup -> Status` in the sidebar
4. Notice that `/backups` renders with the filter enabled, clearing it returns the page to normal
* clear the filter upon loading `/backups/status`
Try to replicate issue on branch, verify the backups status page now loads instead
> Clear filter when navigating to jetpack backup main page

- apps/full-site-editing/full-site-editing-plugin/common/index.php
No longer load common module assets on views where they are not required.
Context: p55Cj4-Ty-p2
1. Sync this PR to your sandbox using `yarn dev --sync`
2. Activate a Varia child theme and in the Customizer, make sure the homepage title is set to hidden.
3. Verify that in the homepage editor, the title is hidden. (This verifies that the assets are loaded when needed.)
4. In a non-homepage editor, verify the assets are _not_ loaded
5. On the front end of your site, both on the homepage or any other page/post, the assets should _not_ be loaded.
I was able to tell when the assets were loaded by using the debugger in Firefox:
_with common assets:_
_without:_
> FSE Plugin: Only load common module assets if they are required

- client/my-sites/activity/filterbar/style.scss
* Fixes the selection of the activity log componet styles to look again as expected. 
Before:
jetpack cloud:
.com
After:
jetpack cloud:
.com
* Open up the Activity Log. 
* Does it look as expected when you select the a date and a activity type.
> Activity Log: Remove the is-boderless class selector

- client/my-sites/activity/filterbar/style.scss
Fix the close button by adding more css specificity.
In https://github.com/Automattic/wp-calypso/pull/41523 we tried to fix the same issue but it turns out that the specificity wasn't high enought on the fix the issue on jetpack cloud staging.
Before: 
After:
Use the new jetpack calypso live link. 
https://jetpack-hash-77fddec7ce2f16df4951a341f2e0d4c3afebda47.calypso.live
Does it look as expected?
> Activity Log: Add more specificity to the close borderless button

- client/gutenberg/editor/calypsoify-iframe.tsx
- client/signup/config/flows-pure.js
- client/signup/config/flows.js
- client/state/sites/launch/actions.js
The scope of this PR is just to align post-Gutenboarding launch flow steps, entry points and redirects. Design updates (domains, plans, and purchase) will be implemented separately.
* Add domain step to Gutenboarding launch flow.
* Use Gutenboarding styled launch when launching from customer home a site previously created in Gutenboarding.
* Redirect back to Block Editor after launching a site starting from there.
**Scenario 1**
* Create a site starting from [/new](https://calypso.live/new?branch=update/gutenboarding-launch-flow).
* When landing in the editor press [Update button](https://cloudup.com/cU4SXhyKCg3) to launch the site. 
* After launching you should land back to the editor.
**Scenario 2**
* Create a new site starting from …
> Gutenboarding: update launch flow

- apps/wpcom-block-editor/src/calypso/features/gutenboarding-editor-overrides.scss
Fixes https://github.com/Automattic/wp-calypso/issues/41288
* Add back preview button in gutenboarding flow:
Before
After
- Read [how to build this to right place in sandbox](https://github.com/Automattic/wp-calypso/tree/5a704a23f746595eb7d6fc2b82120d2d323d4a44/apps/wpcom-block-editor#build)
- Create a site via Gutenboarding and confirm it works
- Have a regular site and confirm they also work
> Gutenboarding: add back preview button

- apps/wpcom-block-editor/src/calypso/features/gutenboarding-editor-overrides.js
Reverts Automattic/wp-calypso#41211
> Revert "Gutenboarding pre-launch: Update CTA button label in the editor"

- apps/full-site-editing/bin/sync-newspack-blocks.sh
- apps/full-site-editing/package.json
Initially, the bash script was implemented to be executed via `npm`. Now, it's being executed via `yarn`.The way to get command variables isn't working with `yarn`, for instance
```
> yarn run sync:newspack-blocks --branch=master
```
`--branch` and `master` aren't properly gotten.
This PR attempts that the bash script is agnostic of the running-command, at least in terms of getting arguments.
Sync the newspack-blocks using the following commands:
```
> yarn run sync:newspack-blocks --branch=master
```
```
> yarn run sync:newspack-blocks --release=v1.3.0
```
```
> yarn run sync:newspack-blocks --nodemodules
```
> FSE: sync-bash script agonistic from running-command.

- client/my-sites/activity/filterbar/style.scss
* This PR fixes the hover state on Jetpack Cloud to match the activity log in calypso. When you hover over the selected filter. The fix increase the specificity of the selector in the activity log. 
Before:
After:
* Load up the calypso live link.
* Does it look like you would expect?
> Jetpack Cloud: fix activity log selecteion on hover

- client/state/data-layer/wpcom/sites/scan/index.js
This PR fixes a bug where a site can end up in limbo (permanenet placeholder state) 
because the jetpack scan api doesn't always return the 'most_recent' parameter. 
This PR fixes this by making sure that the value is always set. 
* Visit Jetpack Cloud scan section for exotic-wasps.jurassic.ninja. 
* Notice that the correct view shoes up.
> Jetpack Cloud: Scan, fix response when jetpack scan api doesn't return most_recent

- client/my-sites/checkout/composite-checkout/types/paypal-express.ts
- client/my-sites/checkout/composite-checkout/types/transaction-endpoint.ts
- client/my-sites/checkout/composite-checkout/wpcom/components/form-field-annotation.tsx
- client/my-sites/checkout/composite-checkout/wpcom/components/item-variation-picker.tsx
- client/my-sites/checkout/composite-checkout/wpcom/hooks/use-coupon-field-state.ts
- client/my-sites/checkout/composite-checkout/wpcom/hooks/use-shopping-cart.ts
- client/my-sites/checkout/composite-checkout/wpcom/lib/translate-cart.ts
- client/my-sites/checkout/composite-checkout/wpcom/test/shopping-cart-endpoint.js
- client/my-sites/checkout/composite-checkout/wpcom/test/translate-cart.js
- client/my-sites/checkout/composite-checkout/wpcom/types.ts
- client/my-sites/checkout/composite-checkout/wpcom/types/backend/shopping-cart-endpoint.ts
- client/my-sites/checkout/composite-checkout/wpcom/types/checkout-cart.ts
- client/my-sites/checkout/composite-checkout/wpcom/types/wpcom-store-state.ts
This PR refactors the `useShoppingCart` hook so that when its `addItem` function is used to add an item to the cart, it is added as a fully fleshed-out, but with null data, response cart object. This way, while the cart is being synchronized with the server, all the rendering machinery will still operate with the optimistically-added new cart item. 
Prior to this change, if a cart item was added with the typical data available for adding new cart items (generally just `product_id` and `product_slug`), the page would throw an error as it tried to convert the missing data into objects suitable for the UI. With this change, a placeholder item (with the label `…`) will be displayed instead. In a future PR we can improve the UI for these placeholder items.
This PR should not change anything, …
> composite-checkout: Allow adding temporary products to the cart

- client/my-sites/checkout/cart/cart-free-user-plan-upsell.jsx
- client/my-sites/checkout/composite-checkout/composite-checkout.js
- client/my-sites/checkout/composite-checkout/use-prepare-product-for-cart.js
- client/my-sites/checkout/composite-checkout/wpcom/components/wp-checkout.js
- client/my-sites/checkout/composite-checkout/wpcom/hooks/use-shopping-cart.ts
This adds the free/domain > personal plan upsell added in #39610 to composite checkout as well.
Requires:
**Regular checkout with the upsell**
**Composite checkout with the upsell**
Fixes #41430
Add a domain to your cart for an account that has no plan. Visit composite checkout and verify that you see the upsell in the sidebar (note that it will only display at wider resolutions; smaller widths will be handled in a separate PR which will collapse the sidebar into the main column). Verify that clicking the CTA button successfully adds the Personal Plan to the cart and verify that the upsell disappears.
> composite-checkout: Add personal plan upsell (3)

- client/my-sites/customer-home/cards/education/educational-content/index.jsx
This PR fixes a console warning about missing keys for the education content links.
* Open devtools, then load My Home for the upcoming i1 with the needed flag: http://calypso.localhost:3000/home/:site?flags=home/experimental-layout
* Notice the above console warning.
* Load again, and verify the message is not displayed.
> My Home: Use unique keys in educational links

- client/landing/jetpack-cloud/sections/backups/backup-activity-log/index.tsx
- client/landing/jetpack-cloud/sections/backups/backup-activity-log/style.scss
* Use section heading styling on the Jetpack Cloud Activity Log header when wide
2. Compare the heading that states "Find a backup or restore point" to the Jetpack Cloud Style Guide. Greater than ( or equal to ) 660px it should match "Desktop Page Heading",  less than should match "Mobile Section Heading"
> Jetpack Cloud: Fix Activity Log Header Styling

- client/lib/plans/features-list.js
- client/lib/plans/plans-list.js
* Removes "Enhanced Site-wide Search" from the Plans list, but keeps `FEATURE_SEARCH ` for the upsell nudges
It looks like https://jurassic.ninja/create/ isn't currently working, but try to spin up a Jetpack site so that you can access the Plans page, and verify that the feature has been removed from the "Professional" column.
cc @keoshi 
Fixes #41336
> Plans: Stop promoting enhanced search for Jetpack Professional

- client/my-sites/checkout/composite-checkout/composite-checkout.js
- client/my-sites/checkout/composite-checkout/wpcom/components/wp-checkout.js
- client/my-sites/checkout/composite-checkout/wpcom/components/wp-order-review-line-items.js
- client/my-sites/checkout/composite-checkout/wpcom/lib/translate-cart.ts
- client/my-sites/checkout/composite-checkout/wpcom/test/shopping-cart-endpoint.js
- client/my-sites/checkout/composite-checkout/wpcom/types/backend/shopping-cart-endpoint.ts
- packages/composite-checkout/src/lib/payment-methods/existing-credit-card.js
- packages/composite-checkout/src/lib/payment-methods/free-purchase.js
- packages/composite-checkout/src/lib/payment-methods/full-credits.js
- packages/composite-checkout/src/lib/payment-methods/paypal.js
- packages/composite-checkout/src/lib/payment-methods/stripe-credit-card-fields.js
This PR does three things to improve the UI when the cart is being updated in composite checkout:
- Temporary line items (items not yet verified on the server and for which we have no title or price data) now are hidden in the order review list (previously they had been shown as '…').
- The "Continue" buttons for each step now display "Updating cart…" when the cart is updating. Previously they had displayed "Please wait…" (which they still display if some other activity is pending).
- The submit button now displays "Please wait…" when the form is not in a ready state (including when the cart is being updated but also when validating the contact form). Previously the button was just disabled in those other states except for when the form was submitting. (It would be nice to change this to …
> composite-checkout: Improve UI when updating cart

- apps/wpcom-block-editor/src/calypso/features/legacy-preview-button.scss
We hide the Gutenberg preview dropdown list because the style overrides don't work on WordPress.com. See: https://github.com/Automattic/wp-calypso/pull/40388
In `v8.0.0-rc.1` the class name for this element has changed. Let's update the class and keep hiding it!
Check out this branch and build it:
`npx lerna run build --scope='@automattic/wpcom-block-editor' -- -- --watch`
Upload the files in `apps/wpcom-block-editor/dist` to your sandbox.
1. `YOUR_TEST_SITE_URL` should be running Gutenberg Edge (`8.0.0-rc.1`)
2. `YOUR_TEST_SITE_URL` should be sandboxed
3. 80s glam rock will make a come back one day, you'll see 🎸  
Try creating a post:
https://wordpress.com/block-editor/post/[YOUR_TEST_SITE_URL]
Check that the preview button in the editor always defaults always to the mobile version
Fixes …
> WPCOM Block Editor: hide Gutenberg preview button

- client/landing/gutenboarding/components/domain-picker/index.tsx
Searching for a specific domain in the domain picker (free or paid) returns a list of results complete with radio buttons. 
The confirm buttons stands ready to smash, though no input is select.
This change makes sure one of the radio buttons is selected after the domain search.
* `<DomainPickerPopover>` doesn't update the current domain until the user clicks "Confirm"
* After searching, the free domain is the default radio button selection https://github.com/Automattic/wp-calypso/issues/40885#issuecomment-610840787 (but it won't be confirmed yet)
* If the search results contain the confirmed domain (the one stored in the onboarding store) then that's the better default selection.
* Fire up the branch and head to `/new`
* Create a site, filling in the vertical _and_ title (see known issue) …
> Gutenboarding: don't allow empty confirm in domain picker

- client/state/help/ticket/actions.js
Simple update to add a Tracks event whenever the user's ticket support configuration is requested.
I'm working on a project that could add a Zendesk API call to this WPCOM API request, but before I do that I want an accurate representation of how often this endpoint is hit. This lets me know how it will affect our Zendesk API rate limit.
- Open Inline Help and click "Contact Us"
- The form should appear
- In Network dev tools you should see a request to `/help/tickets/kayako/mine`
- If you show Tracks debug in console, you'll see the `calypso_ticket_support_configuration_requested` event come through
> Support: Track how often ticket config is requested

- client/state/help/ticket/test/actions.js
Fixes the tests I broke in #41571 — I'm out of practice committing to Calypso and got overeager when the merge button was green.
These tests broke because I added Tracks analytics to the action, so the sinon match wasn't expecting the action it was watching for to have the extra `meta` properties.
> Fix failing tests on ticket config actions

- client/server/bundler/index.js
This PR changes the command that server bundler executes in order to build translation chunks from `node bin/build-languages` to `yarn run build-languages` as it also runs `yarn run translate` to ensure `calypso-string.pot` will be generated.
1. Clean up `chunks-map.{target}.json` and `calypso-strings.pot` if they exist in root directory. 
2. Boot Calypso with `ENABLE_FEATURES=use-translation-chunks yarn start`.
3. Confirm that translation chunks and language manifest and built successfully in `public/evergreen/languages`.
> i18n: Fix translation chunks build flow from server bundler

- client/blocks/site/index.jsx
- config/desktop-development.json
- config/desktop.json
- config/development.json
- config/horizon.json
- config/jetpack-cloud-development.json
- config/jetpack-cloud-production.json
- config/jetpack-cloud-stage.json
- config/production.json
- config/stage.json
- config/test.json
- config/wpcalypso.json
The site indicator doesn't work as expected for Jetpack Cloud.
Since the cloud section doesn't currently have any place to send user that want to update plugins etc. Lets turn it off for now.
* Make it so that we can update the site indicator and activate it we see it in the different calypso environments.  
* Load up Jetpack Cloud. Notice that the site indicator doesn't show up as expected. 
* Load up Calypso notice that the site indicator is there as expected.
> Jetpack Cloud: Don't display the site indicator

- client/landing/gutenboarding/onboarding-block/acquire-intent/site-title.tsx
- client/landing/gutenboarding/onboarding-block/acquire-intent/style.scss
- client/landing/gutenboarding/onboarding-block/acquire-intent/vertical-select/index.tsx
- client/landing/gutenboarding/onboarding-block/acquire-intent/vertical-select/style.scss
* Fix jumping text when entering the first letter in vertical input.
* Trigger input focus for both inputs when clicking/tapping on labels or placeholder.
* Trigger site title input focus on mobile when tapping below the label.
* Go to [/new](https://calypso.live/new?branch=fix/gutenboarding-intent-capture-input-jump).
* Make sure no user data is already entered.
* Type the first letter in _My site is about_ input and existing text characters shouldn't jump like in the [video](https://d.pr/v/lwB23B).
* Try focusing the inputs (empty and filled) by clicking on labels or placeholder on desktop.
* Try focusing the inputs (empty and filled) by tapping below the labels on mobile.
* Check both intent capture inputs for regressions in Firefox, Safari, Safari iOS.
Fixes #40917
> Gutenboarding: fix intent capture inputs visual glitches

- client/landing/gutenboarding/components/plans-button/index.tsx
* Show premium plan when paid domain is selected
* Go to /new.
* Advance to design step.
* When selecting a paid domain, _Premium Plan_ should be displayed in the top-right corner.
> Gutenboarding: update plans button

- client/landing/jetpack-cloud/components/backup-delta/index.jsx
- client/landing/jetpack-cloud/components/backup-delta/style.scss
- client/landing/jetpack-cloud/components/daily-backup-status/index.jsx
- client/landing/jetpack-cloud/components/daily-backup-status/style.scss
* Remove links for backup detail pages, will reintroduce on a case-by-case basis with proper logic for whether to show or not.
* Show meta again.
* Change messaging when there are no changes for a day.
* Misc style tweaks throughout to match latest Figmas.
* Take a look around for a daily backup site. Does everything match the Figmas? Is anything broken? Any console errors?
> Jetpack Cloud: Fix up misc design items for daily backups

- client/my-sites/checkout/composite-checkout/composite-checkout.js
- client/my-sites/checkout/composite-checkout/use-create-payment-methods.js
When coupon codes were added to composite checkout, there was a place that was missed: paypal transactions do not submit the coupon code which causes the full purchase price to be sent to paypal. This PR fixes that oversight by sending the coupon code to the WPCOM paypal url endpoint.
- Create a sandboxed coupon code.
- Visit composite checkout and add the coupon code.
- Verify that composite checkout displays a discounted price; remember this number for later.
- Choose PayPal as the payment method and press the submit button.
- Use your PayPal sandbox credentials (contact me if you don't know how to get these) to log in to PayPal when prompted.
- Verify that the price displayed on PayPal's site is the discounted price you saw before.
- Complete the form to complete …
> composite-checkout: Pass coupon code to paypal submit function

- client/landing/jetpack-cloud/components/activity-card-list/index.jsx
- client/landing/jetpack-cloud/components/activity-card/index.jsx
- client/landing/jetpack-cloud/components/activity-card/style.scss
* Update logic for showing content links
* make activity card actions a flex display
**BEFORE**
**AFTER**
Navigate the Activity Log, making sure that the content links ( "changes in this backup" and "See ontent" ) always appear where expected and the actions button is always on the right
> Jetpack Cloud: update logic for action buttons

- client/blocks/post-share/nudges.jsx
- client/blocks/post-share/test/nudges.jsx
* Swaps `Banner` for `UpsellNudge` in `UpgradeToPremiumNudge`
* See #38778
**Visuals**
WP.com - no visual changes
Jetpack Before
Jetpack After
* Switch to this PR on a free site. Make sure you have at least one connected social account.
* Go to Posts -> three-dots menu on a single post -> Share
* You should see an upsell like the one above.
* Switch to a Jetpack free site with at least one connected social account.
* Go to Posts -> three-dots menu on a single post -> Share
* You should see another upsell like the one above.
* Make sure there are no visual regressions.
* There are no Tracks events associated with these upsells.
> Posts: Update PostShare nudge to use UpsellNudge

- client/signup/main.jsx
- client/signup/steps/domains/index.jsx
This PR updates the signup code to use the PWPO flag instead of the DWPO flag.
After applying the change, you should be able to see the "Free" label next to the crossed out price, as well as the renewal price, both during signup and when adding a new site.
> Signup: Replace DWPO flag with PWPO flag

- client/my-sites/checkout/cart/cart-free-user-plan-upsell.jsx
- client/my-sites/checkout/cart/style.scss
- client/my-sites/checkout/composite-checkout/wpcom/components/wp-checkout-order-summary.js
- client/my-sites/checkout/composite-checkout/wpcom/components/wp-checkout.js
This increases the space between `CheckoutSummary` line items, and styles the up-sell added in #41456 to more closely match the rest of the sidebar items.
**Before:**
**After:**
**Legacy Checkout:**
**To test:**
- add a domain to a site without a plan
- visit checkout and verify that the screenshot matches the one above
- visit legacy checkout and verify that the up-sell isn't broken
> Checkout: update sidebar whitespace

- client/landing/jetpack-cloud/components/scan-badge/index.tsx
- client/landing/jetpack-cloud/sections/scan/main.tsx
- client/landing/jetpack-cloud/sections/scan/types.tsx
- client/state/data-layer/wpcom/sites/scan/index.js
- client/state/selectors/get-site-scan-is-initial.js
- client/state/selectors/get-site-scan-progress.js
* Make the progress bar display the current progress of the scanning process.
* Changed a bit the behavior of the `getSiteScanProgress` to fix a bug in which the Scan can be in the `scanning` state but at the same time, don't have a progress status yet. This usually happens when the first time the `/scan` endpoint reports the Scan is `scanning`. To fix this, now the `getSiteScanProgress` returns 0 is the Scan is `scanning` and there is no progress status.
**Screenshot of the bug**
* Run this PR
* Select a site (the biggest the better because we want a long scanning process)
* Start a Scan (run a backup)
* Reload the page until you see the scanning process has started
* Verify the progress bar reflects the current progress % (you can see it in the sidebar as well)
> Jetpack Cloud: update progress bar while scanning

- client/blocks/product-selector/index.jsx
* When accessing the canonical plans page at `jetpack/connect/store`, we do not have site information available. Thus, we cannot estimate record size to be indexed nor price of the Search product. Here, we remove the relevant parts from the copy.
After:
- go to `http://calypso.localhost:3000/jetpack/connect/store` for the local build
-  verify that the copy for Search agrees with the above design and does not affect the remaining product and plans
Fixes https://github.com/Automattic/wp-calypso/issues/41025
> Jetpack Connect: adapt the Search card copy on the plans page in the absence of site info.

- client/landing/jetpack-cloud/sections/backups/main.jsx
* I added the `TO_REMOVE_getSelectedDateString` method as a shim to `BackupsPage`, since it is only used once let's get rid of it.
1. Navigate to `/backups`
2. Verify nothing has changed vs production ( `cloud.jetpack.com` )
> Jetpack Cloud: Remove TO_REMOVE method from `BackupsPage`

- client/lib/cart-values/cart-items.js
- client/lib/cart-values/types.ts
- client/my-sites/checkout/checkout-system-decider.js
- client/my-sites/checkout/composite-checkout/add-items.ts
- client/my-sites/checkout/composite-checkout/test/composite-checkout.js
- client/my-sites/checkout/composite-checkout/use-prepare-product-for-cart.js
- client/my-sites/checkout/composite-checkout/wpcom/types/backend/shopping-cart-endpoint.ts
This PR adds support for adding premium themes via the special URL `/checkout/example.com/theme:themename`.
To improve the reliability of this process in the future, it also moves the `createItemToAddToCart` function to a Typescript file and cleans up quite a few incorrect or missing types in `lib/cart-items`.
- Visit a URL like this: http://calypso.localhost:3000/checkout/example.com/theme:ovation except with your site instead of `example.com`.
- Verify that you see composite checkout and not old checkout. If you see old checkout it may be because your user is not in the abtest; you can change that via the dev menu in the lower right. If you change the abtest setting, be sure to empty your cart and try the above URL again.
- Verify that the "Ovation" premium theme has been successfully …
> composite-checkout: Support adding premium themes via URL

- client/my-sites/checkout/checkout-system-decider.js
- client/my-sites/checkout/composite-checkout/add-items.ts
- client/my-sites/checkout/composite-checkout/test/composite-checkout.js
- client/my-sites/checkout/composite-checkout/use-prepare-product-for-cart.js
This PR adds support for adding concierge sessions via the special URL `/checkout/example.com/concierge-session`.
Note: old checkout includes a clause to prevent adding duplicate concierge sessions to the cart, but I think this logic belongs on the server, so that behavior has not been replicated here. Instead, see D42677-code
- Visit a URL like this: http://calypso.localhost:3000/checkout/example.com/concierge-session except with your site instead of `example.com`.
- Verify that you see composite checkout and not old checkout. If you see old checkout it may be because your user is not in the abtest; you can change that via the dev menu in the lower right. If you change the abtest setting, be sure to empty your cart and try the above URL again.
- Verify that the "Support Session" product …
> composite-checkout: Support adding concierge session via URL

- client/landing/gutenboarding/components/domain-picker/index.tsx
- client/landing/gutenboarding/hooks/use-on-unmount.ts
- client/landing/gutenboarding/hooks/use-track-modal.ts
- client/landing/gutenboarding/hooks/use-track-step.ts
- client/landing/gutenboarding/lib/analytics/index.ts
- client/landing/gutenboarding/lib/analytics/types.ts
- client/landing/gutenboarding/onboarding-block/acquire-intent/index.tsx
- client/landing/gutenboarding/onboarding-block/design-selector/index.tsx
- client/landing/gutenboarding/onboarding-block/style-preview/index.tsx
- client/landing/gutenboarding/stores/onboard/selectors.ts
Include extra properties in the tracks analytics calls based on this discussion in pbAok1-Ao-p2#comment-1316
I tried to use useEffect with values selected from the redux store. e.g.
```ts
let selectedStyle = useSelect( ( select ) => select( ONBOARDING_STORE ).getSelectedStyle() )
useEffect(()=> {
console.log(selectedStyle);
}, [selectedStyle] )
```
but with that method, the useEffect block is not re-evaluated when the value changes.
Now in the useEffect, it re-evaluates the redux selector each time using a reference to the store e.g.
```ts
const onboardingStore = useSelect( ( select ) => select( ONBOARD_STORE ) );
useEffect( () => {
console.log( onboardingStore.getSelectedStyle() );
}, [ ] )
```
This works but It doesn't feel as nice to have a direct reference to the onboarding store like …
> add extra props to GB analytics

- apps/wpcom-block-editor/src/calypso/features/iframe-bridge-server.scss
This ensures that on mobile the interface doesn't have the top clearance that it has in .org since we hide the masterbar on wpcom.
* Update class name used for the editor skeleton to match Gutenberg v8.0.0 class names
* Sandbox: D42609-code
* Set your site to use the Gutenberg Edge sticker
* Go to edit a page or post within Calypso and adjust the viewport to mobile width
* Confirm that there is no gap at the top of the screen
* Remove the Gutenberg Edge sticker from your site
* Reload the editor and ensure that there is still no gap at the top of the screen
Part of #41521
> Add updated Gutenberg v8.0.0 class names for interface skeleton

- client/lib/i18n-utils/switch-locale.js
- client/server/pages/index.js
- client/server/render/index.js
This PR addresses the issues with translation chunks on fallback target build, both of which were related to file paths resolve logic errors
1. Boot Calypso with `BUILD_TRANSLATION_CHUNKS=true DEV_TARGET=fallback yarn start.`
2. Open http://calypso.localhost:3000/start/user/pt-br?useTranslationChunks.
3. Confirm that translation chunks work as if it was evergreen dev target.
> i18n: Fix translation chunks for 'fallback' target build

- client/landing/gutenboarding/components/header/index.tsx
* Make plans button visible since the user lands on Gutenboarding.
* Go to [/new](https://calypso.live/new?branch=update/gutenboarding-plans-button-always-visible).
* Plans button should be in header (top-right) on every step.
Fixes #41577
> Gutenboarding: render plans button on every route

- client/blocks/upsell-nudge/docs/example.jsx
- client/blocks/upsell-nudge/index.jsx
- client/my-sites/current-site/notice.jsx
* Following up on #41453 this adds the `horizontal` prop and passes it through to match `Banner`'s functionality. This should only affect upsells that have dismiss functionality alongside a CTA.
* Also adds an example to `/devdocs` for parity
* The only example of this prop in active use is Jetpack JITMs, which are handled in #41419 and have not yet been deployed, so this change shouldn't have any impact on existing nudges.
**Before**
**After**
* Navigate to `/devdocs`, go to Blocks, find UpsellNudge
* Note the visual differences between an upsell with the `horizontal` prop vs. one without.
* Check other upsells across Calypso to make sure the changes did not cause visual regressions. Notably the sidebar nudges, anything under Marketing, Settings, Media/Video, …
> UpsellNudge: Add horizontal prop and example in devdocs

- client/blocks/domain-tip/index.jsx
- client/blocks/domain-tip/style.scss
* Swaps `UpgradeNudge` for `UpsellNudge` in the `DomainTip`, which appears on the Stats -> Insights page for free sites.
* Also removes the extra color in the domain name to match existing upsell nudges.
* See #38778 
**Before**
**After**
There's another variation of this nudge on that screen, but I'm unable to get it to appear. I think it only shows up for DWOP sites, and I haven't figured out how to set that flag aside from fudging it in the code.
* Switch to this PR on a free WP.com site
* Navigate to Stats -> Insights
* Note the upsell nudge; there should be no visual discrepancies and all Tracks events and props (impression and click) should be the same.
* To test the other nudge, switch to a domains-with-plans-only site (I think this means a site that has a custom domain but no …
> Stats: Update Domain Tip to UpsellNudge

- client/landing/jetpack-cloud/components/activity-card/index.jsx
* Hide Streams expand button if no streams media is available
1. find an example with no available stream content and verify it does not give the option to expand
2. find an example with some stream media content and verify if does give the option to expand
> Fix Empty Stream Content

- client/my-sites/checkout/composite-checkout/wpcom/components/wp-order-review-line-items.js
The product variation picker allows switching between one and two-year plan lengths in the review step of composite checkout. Prior to this PR, it was made visible only for products with variant pricing which were added to the cart during signup. This PR modifies the logic so that the picker will be visible for any product with variant pricing which is not a renewal, allowing new plan purchases to always choose a different variation.
Fixes #41459
- Add a plan renewal to your cart and visit composite checkout.
- Verify that you do not see the plan length picker.
- Remove the renewal from your cart.
- Add a plan upgrade to your cart and visit composite checkout.
- Verify that you do see the plan length picker.
- Choose the two-year plan length.
- Complete checkout and verify that the …
> composite-checkout: Show variation picker when purchase is not a renewal

- client/my-sites/marketing/tools/feature-button-with-plan-gate.tsx
This ensures that the nudge below works correctly; the feature is being registered, but not applied to the URL that redirects you to Plans. This prevents it from benefitting from #41044. 
https://github.com/Automattic/wp-calypso/blob/b24c6ceffc236ca57f7eb54b459a5f421c7d94ba/client/my-sites/marketing/tools/google-my-business-feature.tsx#L81
Click that nudge under `/marketing/tools/site` and verify that you're no longer offered the Premium plan.
cc @belcherj, @cbauerman
> Marketing: Fix Business Upgrade Nudge

- client/blocks/upsell-nudge/style.scss
* Following up on #41627, this tweaks the styles for dismissible compact nudges, repositioning the CTA and the dismiss icon for better visual balance.
**Before**
**After**
* Navigate to a site with a domain upsell nudge like the one shown above
* Also check out the UpsellNudge blocks in `/devdocs` to make sure there are no visual regressions for existing variations of UpsellNudge
> UpsellNudge: Tweak styles for dismissible compact nudges

- client/my-sites/domains/domain-management/edit/domain-types/registered-domain-type.jsx
This PR updated the domain card to hide the propagation message when the email verification message is showing, to avoid any confusion.
Register a domain with an email address that you haven't used before, so that the contact info is not verified.
Before the fix, you should see something like this:
After the fix, you should only see the verification message:
> Domains: Hide propagation message when email has not been verified

- client/my-sites/customer-home/cards/tasks/webinars/index.jsx
- client/my-sites/customer-home/locations/primary/index.jsx
This PR wires in the Webinars card to the API response that now includes it (with the recent merge of D42514-code). We also rename `webinar` instances to `webinars` for consistency.
* On this branch with an established site, load the new experimental My Home view at `/home/:site?flags=home/experimental-layout`.
* Verify the Webinars card shows up in the primary Tasks location.
> My Home: Wire in the Webinars card to the API response.

- client/my-sites/customer-home/cards/tasks/site-setup-list/get-task-data.js
- client/my-sites/customer-home/cards/tasks/site-setup-list/get-task.js
- client/my-sites/customer-home/cards/tasks/site-setup-list/index.jsx
- client/my-sites/customer-home/cards/tasks/site-setup-list/nav-item.jsx
- client/my-sites/customer-home/cards/tasks/site-setup-list/style.scss
- client/my-sites/customer-home/cards/tasks/style.scss
- client/my-sites/customer-home/locations/primary/index.jsx
Adds a Site Setup List component that visually works well with the new My Home Layout.
- Checkout this branch
- Create a new site
- Visit `http://calypso.localhost:3000/home/:siteId:?flags=home/experimental-layout`
- Verify that Site Setup Steps look visually good, no regressions in task behavior, and that analytics events still fire
> My Home: New site setup list for experimental layout

- config/desktop.json
- config/development.json
- config/horizon.json
- config/production.json
- config/stage.json
- config/test.json
- config/wpcalypso.json
Enables the new My Home layout in dev and horizon for easier testing.
- Verify that we see the new home layout on dev/horizon
- No changes to stage, production, or wpcalypso
> Home: try enabling new layout on dev and horizon

- client/my-sites/customer-home/cards/tasks/webinars/index.jsx
This PR fixes the dismissal behaviour of the Webinars card (fix found by @gwwar ).
* Load an established site on this branch with `/home/:site/?flags=home/experimental-layout`.
* Dismiss the Webinars task.
* Reload, and verify it does not display again right away.
> My Home: Fix dismissal settings of the Webinars card.

- client/lib/abtest/active-tests.js
- client/me/help/active-tickets-notice/index.jsx
- client/me/help/active-tickets-notice/style.scss
- client/me/help/help-contact/index.jsx
Creates `ActiveTicketsNotice` which shows on the Contact form when the customer has one or more active requests. The goal of this feature is to create a better customer experience by reassuring them we haven't forgotten about their email support request, and hopefully reduce the number of people re-asking for help on an open issue.
Since we don't have historic data to measure against, we're launching this in a 50/50 AB test. This will let us directly compare — what % of people who have an open ticket (`calypso_help_active_requests_notice_shown`, new in this PR) still end up asking for help (`calypso_help_contact_submit_with_active_tickets`), and how does that change if they're notified of their open requests?
For testing you need active tickets for the notice to show. If you'd like you …
> Help: Add Active Tickets notice in an AB test

- client/landing/gutenboarding/components/domain-categories/style.scss
- client/landing/gutenboarding/components/domain-picker-modal/style.scss
- client/landing/gutenboarding/components/domain-picker-popover/index.tsx
- client/landing/gutenboarding/components/domain-picker-popover/style.scss
- client/landing/gutenboarding/components/domain-picker/index.tsx
- client/landing/gutenboarding/components/domain-picker/style.scss
- config/development.json
* Fixed scrollbars showing unnecessarily on Firefox in popover view.
* Fixed X icon mispositioned in popover view.
* Fixed Search icon mispositioned in modal view.
* Domain suggestion loading placeholder should have borders around it in modal view.
* Hovering domain category item should underline the text, not bold the text.
* TODO text for domain connect has been removed. Both modal and popover view shows the same text for now. (Another PR for domain connect).
* Feature flag for modal view is now removed.
**Technical Notes:**
- Due to difficulty in getting Firefox scrollbars to play well with **Close button** and **More Options button** decorated from `DomainPickerPopover` component, which I originally intended it to live outside of the `DomainPicker` component, I moved these 2 buttons …
> Gutenboarding: Domain picker modal follow-up fixes + feature flag removal.

- client/landing/gutenboarding/components/domain-picker-modal/index.tsx
- client/landing/gutenboarding/components/domain-picker/index.tsx
- client/landing/gutenboarding/hooks/use-domain-suggestions.ts
* Show 10 domain suggestion items in domain picker in modal view.
* Open up domain picker in modal view, you should see 10 items for both placeholder loading items and actual items.
Fixes #41542
> Gutenboarding: Show 10 domain suggestions in domain picker modal.

- client/my-sites/customer-home/cards/tasks/style.scss
- client/my-sites/customer-home/cards/tasks/task.jsx
* Add props to display chip heading instead of time, dismiss instead of skip, and action callback instead of url for call to action button.
* Check out this PR - all existing cards should still works as expected - these changes should be backwards compatible so no changes to existing cards should be needed.
* Also check out  #41570 and check that a chip style heading displays at top of card instead of the time estimate, and a `Dismiss` link instead of the skip options
Also check that the 'Try now' button fires the callback to launch the editor
Additional config options needed initially for #41570
> Task Card: Adds additional config options

- client/my-sites/customer-home/cards/tasks/task.jsx
For any My Home card based on the `Task` component, let's collect bump and Track stats for when a user clicks on their primary call-to-action button. We already have stats that handle card dismissal/reminders.
Currently, this will apply to the `webinars`, `connect-accounts`, and `find-domains` cards.
* On this branch, load My Home for an established site that hasn't dismissed the above cards yet (`/home/:site/` – the URL flag is no longer needed).
* In the console, activate analytics visibility with `localStorage.debug='calypso:analytics*'` (be sure to reload the page).
* Click the call-to-action button for each card (dismissing if necessary to move on), and verify bump and Tracks stats are collected, with the correct task identified.
> My Home: Add stats for the CTAs of Task cards.

- client/blocks/post-item/index.jsx
- client/my-sites/pages/page/index.js
* Page list: Display a  un-clickable text (a <span/>) when the page item is deleted,. to prevent a 404 
* Go to page list
* Either when searching or in the "deleted" tab, page items cannot be clicked
*
Fixes #41640
cc @kwight
> Page list: Display a <span/> instead of a <a/> if the page is trashed

- client/landing/jetpack-cloud/sections/scan/main.tsx
* add a new provision state
* add Scan Header and Contact Us button render functions. 
Here are the different states right now:
**Provisioning**
**Idle** no threats
**Idle** with threats
**Scan Error**
**Scanning**
**Unavailable**
* I use a `true ||` so that I can replicae each of the scan states that are returned by the api. 
* Do the states look as expected?
> Jetpack Scan: Updates to the Main Scan component with wording. 

- client/landing/jetpack-cloud/sections/home.tsx
* Adds safeguards around redirecting to a user's primary site to exclude multisites and Atomic sites.
* Set your primary site to an Atomic site or multisite.
* Go to root of Cloud.
* Observe site picker appear.
Fixes 1143508703416848-as-1173582844580969.
> Safeguards for primary site redirection

- client/my-sites/checkout/checkout-system-decider.js
- client/my-sites/checkout/composite-checkout/record-analytics.js
When an error boundary is triggered due to a JS error in the code, it would be nice to be notified of it. We can do that by having the error in logstash.
This PR adds logstash calls to each of the error boundary errors. In production, these entries will have `severity: error`, and other environments will have `severity: debug`.
- Edit the code to cause an Error to be thrown inside composite checkout.
- Load the page to cause the error and verify that you see an error boundary.
- Visit logstash for the string `composite checkout load error` and verify that you see the error you triggered (and verify that its severity is `debug`).
> composite-checkout: Add logstash to error boundary errors

- client/my-sites/customer-home/cards/tasks/site-setup-list/get-task.js
- client/my-sites/customer-home/cards/tasks/site-setup-list/index.jsx
- client/my-sites/customer-home/cards/tasks/site-setup-list/style.scss
- client/my-sites/customer-home/cards/tasks/style.scss
- client/state/current-user/email-verification/actions.js
- client/state/current-user/email-verification/test/actions.js
- client/state/data-layer/wpcom/me/send-verification-email/index.js
- client/state/data-layer/wpcom/me/send-verification-email/test/index.js
* Removes the badge styles used in completed tasks and replaces it with the badge styles added to the generic task card in #41653. Margins have been adjusted to avoid jumping text when switching between pending and completed tasks.
* Ensures the current task data is updated whenever any of its dependencies changes. This is useful for example for disabling the "Resend email" button while the verification email is being sent.
* Adds global notices support to the action that sends a verification email. This allowed to remove the dynamic action text depending on the verification email status.
Before | After
--- | ---
- Go to `/start` and create a new user and site.
- Do not confirm your email (you'll need to test with a non-`@automattic.com` account).
- Select the "Confirm your email address" …
> My Home: Janitorial enhancements

- client/landing/gutenboarding/components/signup-form/index.tsx
- packages/data-stores/src/user/types.ts
This PR deliberately sends `null` for the property`extra.username_hint`, and therefore  an invalid value to `users/new`. 😱 
We're doing this to force the endpoint to designate an auto-generated username. 🛠
It's a quick fix to get things working. 👍
A cleaner solution would be to send a `generate_username`  flag to `users/new`, or some such thing. 🧹
Here's another emoji! 🍻
1. Head over to `/new`. 
2. Enter neither a vertical nor a site title.
3. Go on to create a new site.
You should be able to create a new site.
> Gutenboarding: sends null for extra.username_hint to users/new endpoint

- apps/full-site-editing/full-site-editing-plugin/dotcom-fse/editor/style.scss
- apps/full-site-editing/full-site-editing-plugin/dotcom-fse/plugins/close-button-override/style.scss
This PR updates the FSE plugin with class names to add support for Gutenberg v8.0.0.
* Update class names used for hiding the close button on mobile viewports
* Update class names for removing additional margins on full width blocks
Note: the whitespace at the top is dealt with separately in #41572 
| Mobile before | Mobile after |
| -------------- | ------------ |
| ![image](https://user-images.githubusercontent.com/14988353/80566393-447aff80-8a36-11ea-9661-0d380e657cbf.png) | ![image](https://user-images.githubusercontent.com/14988353/80566579-a0de1f00-8a36-11ea-8f3e-d3a8a7520c35.png) |
| Full width blocks before | Full width blocks after |
| ------------------------ | ---------------------- |
| ![image](https://user-images.githubusercontent.com/14988353/80566622-bf441a80-8a36-11ea-9c7a- …
> Update header button styling and full width block margins for Gutenberg v8.0.0

- client/me/purchases/manage-purchase/auto-renew-toggle/auto-renew-disabling-dialog/index.jsx
- client/me/purchases/manage-purchase/auto-renew-toggle/auto-renew-disabling-dialog/style.scss
This PR updates the button alignment on the dialog shown when disabling auto-renew. 
Also some styling update is included for the followup dialog when disabling auto-renew for Atomic sites:
* Find a purchase for which you have auto-renew enabled, and try to disable it. The buttons should now appear to the right, as shown in the screenshot above.
* Verify functionality of the dialog is intact
> Change button alignment on auto-renew disable dialog

- client/landing/jetpack-cloud/components/sidebar/index.jsx
- client/landing/jetpack-cloud/sections/backups/main.jsx
Rename the section from "Status" to "Latest Backups" (menu item and title):
**Asana card:** 1142395350490785-as-1173475308570809
- Check if the menu name change from "Status" to "Latest Backups" and also the title of the section (the tab title too) when we are on there.
> Rename the section from "Status" to "Latest Backups" (menu item and title)

- client/my-sites/customer-home/cards/tasks/webinars/index.jsx
* Updating copy on the webinar promo task card in the new My Home layout as per the comment in https://github.com/Automattic/wp-calypso/pull/41460#issuecomment-621377686
* Check out this branch on your local Calypso
* Return `<Webinars />` in `client/my-sites/customer-home/locations/primary/index.jsx` as a hack-y way to show the webinar promo
* Confirm the copy matches the screenshot above
> My Home: Update copy on webinar task card

- client/assets/images/customer-home/illustration--task-find-domain.svg
- client/my-sites/customer-home/cards/tasks/find-domain/index.jsx
* Update the illustration for the "Find a domain" task card in the new My Home layout.
Before | After
I'm sure there's a proper way to do it, but I just hacked my local branch:
* Return `<FindDomain />` in `client/my-sites/customer-home/locations/primary/index.jsx`
* Visit My Home on any site using the `home/experimental-layout` feature flag
* Confirm the correct illustration shows.
Fixes https://github.com/Automattic/dotcom-private/issues/49
> My Home: Update illustration for domain task card

- client/blocks/jitm/templates/default.jsx
- client/blocks/upsell-nudge/index.jsx
- client/blocks/upsell-nudge/style.scss
* Swap `Banner` for `UpsellNudge` for default JITM template
* `preventWidows()` on `UpsellNudge` CTA to prevent multi-word buttons breaking in odd places.
* This should also fix #41374 and #41001
* There may be more of these in Calypso that I'm unaware of; it's not clear in the API which upsells go where. Maybe @Automattic/martech has a better idea of which upsells need to be tested in this case?
| **Before** | After |
| ----- | ----- |
| <img width="1398" alt="Screen Shot 2020-04-23 at 4 45 09 PM" src="https://user-images.githubusercontent.com/2124984/80147645-d17b1000-8581-11ea-8976-3a6e84f24af7.png"> | <img width="1388" alt="Screen Shot 2020-04-23 at 4 41 24 PM" src="https://user-images.githubusercontent.com/2124984/80147353-63364d80-8581-11ea-9c04-c91edc525f66.png"> |
| <img …
> JITMs: Update JITM default template to use UpsellNudge rather than Banner

- client/state/home/reducer.js
- client/state/selectors/is-home-quick-links-expanded.js
Following feedback from p7DVsv-8zA-p2, this PRs ensures the quick links are expanded by default.
* Open My Home in an incognito/private window (to ensure you start off with a clean state).
* Make sure the quick links are expanded by default.
* Collapse them and reload the page.
* Make sure the quick links remain collapsed.
* Expand them and reload the page.
* Make sure the quick links remain expanded.
Part of https://github.com/Automattic/dotcom-private/issues/51
> My Home: Quick links expanded by default

- apps/full-site-editing/full-site-editing-plugin/dotcom-fse/helpers.php
Believe it or not, dotcom FSE is turned on by default. It made sense at the time -- anyone with the plugin installed would want to be seeing dotcom FSE, right!?
Wrong. The plugin is almost entirely _not_ for dotcom FSE any more.
Currently, the only thing stopping dotcom FSE showing up for people on Atomic sites is this code in wpcomsh:
```
function wpcomsh_maybe_disable_fse() {
// Always disable FSE if the site is not eligible:
return ! get_option( 'a8c-fse-is-eligible' );
}
add_filter( 'a8c_disable_full_site_editing', 'wpcomsh_maybe_disable_fse' );
```
(source: wpcomsh `feature-plugins/full-site-editing.php#L11-L15`)
These changes should not affect dotcom fse in production. This "disable FSE" filter currently always receives a result on both simple and atomic sites via mu plugins and …
> Disable dotcom FSE by default on local sites.

- client/lib/checkout/index.js
- client/my-sites/checkout/checkout/checkout-container.jsx
- client/my-sites/checkout/checkout/index.jsx
Here we pass down `returnToBlockEditor` to `<Checkout />` so we can redirect back to the block editor if the cart is empty for in Gutenboarding flows.
I'm open to alternatives for `returnToBlockEditor`.
1. From /new select a paid domain, create a site and head to checkout
2. Now empty your cart
3. You should be taken to the editor, where your new home page will be laid out bare before you, ready to succumb to your editing desires
4. Now that you're in the editor, click on **Launch** to launch your site <img width="326" alt="Screen Shot 2020-04-30 at 8 05 12 pm" src="https://user-images.githubusercontent.com/6458278/80698768-46b88900-8b1e-11ea-8bfc-ddb3b0a3254a.png">
5. Select a paid plan and let yourself be carried away to checkout
6. Empty your cart again.
7. Once again, you'll land on …
> Gutenboarding: redirect to editor after emptying checkout cart 

- packages/components/src/suggestions/item.jsx
* Fix vertical suggestions not matching/highlighting input with trailing spaces.
* Open `/new`.
* Enter a suggestion with trailing space, like `Travel ` or `Botanical `.
Fixes #41132
> Gutenboarding: Fix vertical suggestions not matching/highlighting input with trailing spaces. 

- client/lib/performance-tracking/api.js
* Prevent Lux logs to appear in the console:
More info: https://support.speedcurve.com/en/articles/867066-lux-api#luxdebug
* Checkout branch, start calypso and verify nothing appears in the console when you go to Stats, Plans or My Home
> Do not show console logs for lux operations

- apps/full-site-editing/full-site-editing-plugin/starter-page-templates/page-template-modal/components/block-preview.js
* Add class name to allow title to be centered in Gutenberg 8.0 (noted in [41719](https://github.com/Automattic/wp-calypso/issues/41719#issuecomment-623234636))
It seems the css rules for the margin of `.editor-post-title` is now nested under `.edit-post-visual-editor__post-title-wrapper` as opposed to `.edit-post-visual-editor`.  Meaning with 8.0 active the title for a starter page template preview looks off-center:
After changes:
* Build/sync FSE and test starter page templates on `gutenberg-edge`
* Verify title is now centered.
> Fix Starter Page Template title centration for Gutenberg 8.0

- client/landing/gutenboarding/index.tsx
- packages/data-stores/src/user/types.ts
This PR fixes two issues with translations chunks for Gutenboarding:
1. Adds missing build target parameter in language manifest and translation chunk files calls.
2. Adds fallback for `language` as `localeSlug`, and `locale_variant` as `localeVariant` that are used to get the locale from user object, because user object from `/me` is different from bootstrapped user object.
1. Boot Calypso with `BUILD_TRANSLATION_CHUNKS=true ENABLE_FEATURES=wpcom-user-bootstrap,use-translation-chunks yarn start`
2. http://calypso.localhost:3000/new 
3. Confirm that translation chunks are working as expected
> i18n: Fix translation chunks setup for Gutenboarding

- client/my-sites/domains/domain-management/edit/domain-types/wpcom-domain-type.jsx
- client/my-sites/domains/domain-management/edit/navigation/enhanced.jsx
This PR updates the free subdomain view to use the enhanced navigation view instead (use `domains/new-status-design/new-options` feature flag)
For a site you own, go to Domains, click on the free ".wordpress.com" subdomain, and you should see something similar to the screenshot above.
Make sure clicking the items will work as expected.
> Domains Use enhanced navigation for free subdomains

- client/landing/gutenboarding/components/plans-button/index.tsx
- client/landing/gutenboarding/lib/plans.ts
- client/landing/gutenboarding/path.ts
* Update path handling in Gutenboarding to include `plan` as an optional param.
* So it should be possible to set the plan via URL argument like so: `/new/PLAN_SLUG` where the slug is `beginner`, `personal`, `premium`, `business`, or `ecommerce`.
* The existing mechanism to set a Free / Premium Plan using the type of selected domain (free/paid) only if there isn't a valid plan param.
* Go to [/new/beginner](https://calypso.live/new/beginner?branch=add/gutenboarding-set-plan-using-url-param).
* _Free plan_ should be displayed in top-right corner.
* After entering a site title and choosing a paid domain using Domain picker, _Free plan_ should still be displayed.
* Go to [/new/business](https://calypso.live/new/business?branch=add/gutenboarding-set-plan-using-url-param).
* _Business Plan_ …
> Gutenboarding: get plan from URL param

- client/landing/jetpack-cloud/components/threat-item-subheader/index.tsx
* Translate the status of a fixed/ignored threat.
* Go to a site that has Scan and has fixed and ignored threats
* Go to the History section
* Verify the badges for `ignored` and `fixed` statuses look as before (nothing has changed)
> Jetpack Cloud: translate the status of a threat

- client/my-sites/customer-home/cards/tasks/site-setup-list/get-task.js
* Updates the action of the Menu task to redirect to the Customizer, with a support link in the description
Verify that the action redirects you to Menus in the Customizer, and the link brings open the "Site Menus" support dialog.
Fixes #41775
> My Home: Menu Task - Update Action

- apps/full-site-editing/full-site-editing-plugin/newspack-blocks/index.php
With newspack-blocks [version 1.4.0](https://github.com/Automattic/newspack-blocks/releases/tag/v1.4.0) released, we need to include the posts carousel view js again.
* With 1.4.0 applied, add Posts Carousel block to a page
* See if slider works in the frontend of the site
> FSE: readd posts carousel view js

- docs/monorepo.md
* Add documentation to include `check-npm-client` before each script in package.json files.
Addresses https://github.com/Automattic/wp-calypso/pull/41093#issuecomment-619876341
> Add note about check-npm-client to monorepo docs

- client/my-sites/customer-home/cards/tasks/site-setup-list/get-task.js
- client/my-sites/customer-home/cards/tasks/site-setup-list/index.jsx
We've been leaving the checklist items' CTAs as-is in the completed state, with the idea that users can go back and update the task afterwards if they want to. While this works for steps like changing the site title, it's confusing for one-time tasks like launching the site. In its current completed state, the "Launch site" CTA is an enabled primary button that does nothing.
This PR allows adding a `actionDisableOnComplete` flag on a checklist item to have its CTA disabled once it's complete.
> My Home: Disable the "launch site" action on completion.

- client/my-sites/customer-home/cards/features/quick-start/index.js
- client/my-sites/customer-home/cards/features/quick-start/style.scss
- client/my-sites/customer-home/controller.jsx
- client/my-sites/customer-home/locations/tertiary/manage-site/index.jsx
- client/my-sites/customer-home/style.scss
This is take two of #41112 .
This PR adds a Quick Start Sessions card to My Home. The card is only displayed if a session exists for the current site.
* Switch to this branch, and cherry-pick 8a2ee7505833f3423d67987862cac6af32b84231 from #41761 if it's not yet merged.
* On prod, take a test site with a Business plan and register for a Quick Start session at `/me/concierge/:site/book`. (Be sure to comment that we're just testing. 🙃)
* Back on this branch for the Business test site, load `/home/:business-site` and verify the card shows up, with the correct data.
* Verify the "View details" button goes to `/me/concierge/:site/book`.
* Verify the "Reschedule" link goes to `/me/concierge/:site/:sessionId/cancel`.
Fixes #38998
> My Home: Add a Quick Start card.

- client/my-sites/customer-home/cards/education/free-photo-library/index.jsx
Both the Mastering Gutenberg and Free Photo Library cards involve text links that open a modal to a video. The former has video icons before the links, the latter does not; this PR adds the same icon to the latter for consistency.
Before | After
--- | --- 
* Go to My Home either on this branch or via the calypso.live link (any site will do).
* Verify the video icon beside "Learn more" in the Free Photo Library card under Learn and Grow.
> My Home: Add a video icon beside the Free Photo Library prompt.

- client/my-sites/customer-home/main.jsx
The second line description of My Home notices is currently determined, among other things, by [whether or not the checklist is being displayed](https://github.com/Automattic/wp-calypso/blob/master/client/my-sites/customer-home/cards/notices/celebrate-notice/index.jsx#L41) – but is only aware of the production checklist card. This PR adds the new task-based checklist to the check, while we transition to the new i1 layout.
Before | After
--- | --- 
* On this branch, create a new site, and launch it.
* On the celebratory page load, verify the description in the celebratory card makes sense (it should match the screenshot above).
* Load the same URL on production, and verify the same content appears in the notice.
> My Home: Fix logic determining the description of notices in i1.

- client/landing/gutenboarding/lib/analytics/index.ts
* Renames gutenboarding events from `calypso_signup_*` to `calypso_newsite_*`
Gutenboarding may never perform well enough to replace `/start`, and therefore we might end up running both: `/start` for signup and `/new` for site building. In this case the events should be completely seperate since we're not trying to compare them.
Task inside #41838. Still need to register events.
* Go to `/new`
* Go forwards and backwards through steps, you should see the new names fired in the network tab
* Open and close popovers/modals, you should see the new names fired
* Try to signup with an invalid email, you should see the `calypso_newsite_error` event
> Gutenboarding: Prefix track event names with `calypso_newsite_`

- client/landing/gutenboarding/onboarding-block/acquire-intent/vertical-select/index.tsx
- client/landing/gutenboarding/onboarding-block/acquire-intent/vertical-select/style.scss
* Fix vertical select placeholder positioning to prevent visual glitches.
* Go to [wpcalypso.wordpress.com/new](https://wpcalypso.wordpress.com/new)
* While the vertical input is empty, resize the window until the grey line disappears and the blue cursor is on a different line like this:
* Now go to [/new](https://calypso.live/new?branch=fix/gutenboarding-acquire-intent-cursor-position) in the same window and it should be fixed.
Fixes #41795
> Gutenboarding: position vertical select cursor correctly

- client/gutenberg/editor/calypsoify-iframe.tsx
* The Gutenboarding launch flow does not assign user to the new checkout flow. Also, the checkout URL is incorrect - it looks like this to me `http://calypso.localhost:3000/checkout/176916103?signup=1&preLaunch=1`. The /176916103 part is the siteId which should not be there, and is wrongly assumed to be product ID in this line:
https://github.com/Automattic/wp-calypso/blob/e03f5098b80a372efd26e2a5f7fe69c6772b5cbf/client/my-sites/checkout/controller.jsx#L40
* This PR fixes the above issues.
* Proxy through US IP, , go through Gutenboarding at /new and reach the editor.
* Assign yourself to the "composite" variation of the showCompositeCheckout A/B test and click the Launch button
* Add a domain or plan item to cart, and verify that you are shown the new checkout.
> Show new checkout in the Gutenboarding launch flow

- client/landing/gutenboarding/components/domain-picker-modal/style.scss
- client/landing/gutenboarding/components/domain-picker/style.scss
* Show fixed footer on domain picker modal for mobile view.
* Open up domain picker modal in `/new`.
* Sticky footer should show in mobile view (iPhone devices).
* Also, test this in iOS simulator.
> Gutenboarding: Show fixed footer on domain picker modal for mobile view.

- client/landing/jetpack-cloud/sections/scan/main.tsx
Currently we don't show a real time for when the last scan happened. It always defaults to 2 hours ago. 
This PR fixes this by making sure that the scan most Recent scan results get used. 
Load up the scanner page. Notice that it doesn't break. 
Make sure that the new time looks as expected.
> Jetpack Cloud: Fix jetpack scanner last scan time

- client/landing/jetpack-cloud/components/threat-item-subheader/index.tsx
- client/landing/jetpack-cloud/components/threat-item/style.scss
* Fixes a bug in the translation arguments. 
* Fixes a minor css issue so that we now take up the full thread box if there is no button.
Before:
After:
* Create a bunch of different threats. 
* Navigate to the scanner page on the jetpack cloud. 
* Notice that the threats show up as expected. 
See before and after.
> Jetpack Cloud: Fix scanner threat name and width

- client/my-sites/customer-home/cards/tasks/task.jsx
- client/my-sites/customer-home/cards/tasks/webinars/index.jsx
AFAIK we don't have any way of identifying server-side users already registered for webinars, so we currently always display the webinars task card as long as it has not been dismissed, even if users started the task by clicking on "Register for free".
This PR ensures the task is marked as completed when clicking on that button (actually, it marks it as dismissed) so the task doesn't show up again.
* Go to My Home for an established site with the webinars task card not dismissed.
* The webinar task card should show up.
* Click on "Register for free".
* Make sure the browser opens `wordpress.com/webinars` in a new tab.
* Switch back to the tab with My Home open.
* Make sure the webinars task card has disappeared.
* Reload My Home.
* Make sure the webinars task card doesn't show up again.
> My Home: Mark webinars task as completed when clicking on action button

- client/landing/jetpack-cloud/components/daily-backup-status/index.jsx
Remove the summarized ActivityCard from DailyBackupStatus when the latest backup is a full backup.  It only shows redundant meta information.
* Load up backups view for a realtime site whose latest backup is a full backup. The summarized backup card should not appear in the `DailyBackupStatus` component.
Fixes 1142395350490785-as-1172046985906148
> Jetpack Cloud: Remove summarized backup card from real-time backup for some cases

- client/landing/jetpack-cloud/components/activity-card/action-bar.tsx
- client/landing/jetpack-cloud/components/backup-date-picker/index.jsx
- client/landing/jetpack-cloud/components/backup-date-picker/style.scss
- client/landing/jetpack-cloud/sections/backups/main.jsx
- static/images/illustrations/download.svg
* Renames the `DatePicker` component to `BackupDatePicker` to avoid (possible) namespace issues with the existing Date Picker component.
* Replaces all CSS classes accordingly
* Check out the Date Picker component for a backups site (the calendar icon at the top). Does it function normally with no console errors?
I would have done this sooner, but I foresee a time in the **_near future_** where we need to replace this component entirely with a custom component. Addressing this immediately to put the "issue" to rest for good :-)
> Jetpack Cloud: Re-namespace the DatePicker component to BackupDatePicker

- config/desktop-development.json
- config/desktop.json
- config/horizon.json
- config/production.json
- config/stage.json
- config/test.json
- config/wpcalypso.json
This PR add the Jetpack Scan to be available for purchase on 
Staging, desktop development, horizon, calypso.live, and wp-calypso.
The Jetpack Scan product will not be available on Production and the dasktop app.
Look at the code. Test out the new calypso live link.
> Plans: Make the Jetpack Scan Product available for purchase

- client/components/banner/README.md
- client/components/banner/docs/example.jsx
* Update `Banner` examples in /devdocs to indicate non-upsell use cases.
* Update `Banner` readme to point to `UpsellNudge` if one is trying to add an upsell.
**Before**
**After**
* Navigate to `/devdocs` and search for `Banner` under components.
* Look for visual issues or errors.
See #38778
> DevDocs: Update instances of Banner

- client/my-sites/people/role-select/constants.js
- client/my-sites/people/role-select/index.jsx
- client/my-sites/people/role-select/style.scss
Fixes https://github.com/Automattic/wp-for-teams/issues/172.
In this PR, we add descriptions to most common user roles for the `people/new` Calypso page. We also add a check if site is a WP for Teams one and if yes, modify the descriptions a bit to match them for WP for Sites needs.
Navigate to http://calypso.localhost:3000/people/new with a WP for Teams site and verify the role descriptions match the ones described in the above issue. Now, select a standard WP.com site and verify the role descriptions are more generic.
/cc @evilluendas for design improvements.
> WP for Teams: add descriptions to user roles and special handling for WP4Teams sites

- client/my-sites/earn/ads/wrapper.jsx
* `UpgradeNudgeExpanded` only appears at `/earn/ads-earnings/[site]`, which only appears to be accessible for free sites by going directly to the URL. 
* `UpgradeNudgeExpanded` included more information about the Premium plan, but I don't think this is necessary. Replacing it with `UpsellNudge` makes it behave like the rest of the upsells across Calypso, even though it changes the visual appearance.
**Before**
WP.com
Jetpack
**After**
WP.com
Jetpack
* Switch to this PR and go to `/earn/ads-earnings/[site]`
* Look with a site that has a WP.com free plan to see the ad. Make sure the behavior is the same (clicking the CTA goes to the checkout for the Premium plan) and the Tracks events are the same. (This PR adds a `cta_name` property that shouldn't affect the existing props)
* Look with …
> Earn: Swap UpgradeNudgeExpanded for UpsellNudge

- client/landing/jetpack-cloud/sections/scan/main.tsx
* Updates copy for scan error text to be more generic.
* Go to Scan in JP Cloud.
* Alter the state so `most_recent` has an `error` that's not falsey. Example event:
```json
{
"type":"JETPACK_SCAN_UPDATE",
"siteId":"[your site id here]",
"payload":{
"state":"idle",
"threats":[],
"credentials":["test"],
"mostRecent":{
"timestamp":"foo",
"progress":49,
"duration":25,
"error":"test"
}
}
}
```
* Observe copy.
**Note** that right now, the Scan API doesn't provide meaningful errors, so a generic error is displayed. Once we get more meaningful errors additional error messaging can be added.
Fixes 1143508703416848-as-1173255039677553.
> Cloud: Changes scan error text

- client/my-sites/domains/domain-management/list/index.jsx
Updates the Add domain button so that it more explicitly adds them to the site you're managing.
Before:
After:
* Use calpso.live and visit /domains/manage for any site. 
* The button should say "Add a domain to this site"
cc @eltongo @hambai
> Update domain button

- apps/full-site-editing/full-site-editing-plugin/block-patterns/patterns/call-to-action-02.php
I changed the markup of the buttons block section to match what is generated by core. This fixes the broken block error in the call-to-action pattern when:
- CoBlocks (full plugin) is active
- FSE is active
- Layout Grid is active
Fixes https://github.com/Automattic/wp-calypso/issues/41380
I've tested the pattern with both CoBlocks activated and deactivated, and the pattern works correctly.
| before  | after |
| <img width="1426" alt="Screen Shot 2020-05-06 at 9 59 05 AM" src="https://user-images.githubusercontent.com/967608/81192840-4ede5180-8f80-11ea-874d-673bd494070b.png"> | <img width="1426" alt="Screen Shot 2020-05-06 at 9 58 02 AM" src="https://user-images.githubusercontent.com/967608/81192848-50a81500-8f80-11ea-8a40-b87fdae3ebd7.png"> |
Start the …
> FSE: Fix Block Pattern markup on call-to-action-02 when CoBlocks is active

- client/my-sites/customer-home/cards/actions/quick-links-compact/style.scss
- client/my-sites/customer-home/cards/actions/quick-links/style.scss
- client/my-sites/customer-home/cards/education/educational-content/style.scss
- client/my-sites/customer-home/cards/features/support/style.scss
- client/my-sites/customer-home/cards/tasks/style.scss
- client/my-sites/customer-home/style.scss
Clean up some margins and typography on the new My Home layout for more consistency and balance. They're relatively minor things but the little things add up.
* Reduce the font size of the main primary task card a little bit for better balance.
* More consistent margins and padding between cards.
* Update secondary/tertiary card heading and copy font sizes for stronger hierarchy.
**Full page before**
**Full page after**
* Check out this branch or visit the calypso.live link
* Go to My Home for any site and make sure of the following:
* Bottom margin on task card now matches bottom margin of other sections.
* The links under Quick links are both smaller than the card header and the same size as the content in the other tertiary cards.
* Bottom margin on tertiary cards match the gutter …
> My Home: Clean up margins and typography

- client/my-sites/customer-home/cards/tasks/site-setup-list/index.jsx
We can see temporary fatals when completing the Home checklist – a refresh will not have the same result though, and will display fine, since it's operating from updated API results (this likely explains not seeing reports of this yet).
* On production, skip the menu step as the final step to complete the checklist.
* See the screen fatal on completion of the last item.
* On this branch, do the same with a new site.
* Verify the browser does a reload, and the celebratory banner and new task display properly.
> My Home: Avoid fatals when completing the checklist.

- client/my-sites/checkout/composite-checkout/record-analytics.js
- client/my-sites/checkout/composite-checkout/wpcom/components/wp-checkout-order-summary.js
- client/state/help/ticket/selectors.js
This adds a link to the Checkout Summary that triggers the inline help popover, where there are quick links to plan and purchase support, and the ability to contact support directly.
**To Test:**
- visit Checkout
- click the "Ask a Happiness Engineer" link in the sidebar
- verify that the inline help popover opens
- verify that the inline help links are plan- and purchase-related
- verify that clicking outside of the popover will close the popover
- verify that Checkout steps complete as expected
> Checkout: add support link to summary

- client/landing/gutenboarding/components/signup-form/index.tsx
Redirect passwordless users to create-site?new so that they keep their place in the flow if they use the same browser session to open the email link.
* Create a user with passwordless authentication.
* Go through the `/new` flow and select the `login` frankenflow 
* Enter the email address of the passwordless user
You will recieve a login link via email. Copy the link and try these two cases.
a) Open the link in a new incognito session:
*You will be on the `/new` aquire intent page. restarting the gutenboarding flow. However you will now be logged in and will not be prompted again
b) Open the link in the same browser session that you were previously using:
* You will be taken to the `create-site?new` endpoint. your site will be created with the details you entered earlier
Fixes #41771
>  redirect passwordless login users to /create-site?new
