Automattic/wp-calypso

apps/full-site-editing/full-site-editing-plugin/starter-page-templates/class-starter-page-templates.php
apps/full-site-editing/full-site-editing-plugin/starter-page-templates/index.js
apps/full-site-editing/full-site-editing-plugin/starter-page-templates/page-template-modal/components/sidebar-modal-opener.js
apps/full-site-editing/full-site-editing-plugin/starter-page-templates/page-template-modal/styles/starter-page-templates-editor.scss

For the reasons outlined in #41793
**Before**
**After**
* Page layout screenshot removed from document settings sidebar
* "Change Layout" button changed to secondary button style and margin removed
* removed `siteInformation` from the `window.starterPageTemplatesConfig` global sent from server (no longer used)
* Formatting changes from the pre-commit hook
The FSE plugin will need to be deployed after this is merged.
* Clone branch
* `cd apps/full-site-editing && yarn dev`
* `cd apps/full-site-editing && wp-env start` in another terminal
* `localhost:4013/wp-admin` and edit a page
* See changes in the document settings sidebar
You can also see changes as they would appear on wpcom by using `yarn wpcom-sync` and sandboxing a site.
Fixes #40766
Fixes #41793

Block editor: remove page layout preview from sidebar

---

client/blocks/inline-help/popover.jsx
client/state/data-layer/wpcom/sites/gutenberg/index.js
config/development.json

* Update the "Switch to Classic Editor" link for the context-sensitive help menu to redirect to the WP Admin classic editor.
- **WordPress.com editor has been deprecated.**
1. Set "editor/after-deprecation" feature flag to true
2. Start up local Calypso
3. Visit http://calypso.localhost:3000
4. Navigate to edit or add a new post
5. Switch to the block editor if it isn't the current editor
6. Click on the "?" help button in the bottom right 
7. Click on the "Switch to Classic Editor" button and confirm you wish to leave the page if asked
8. You should be taken to the WP Admin classic editor for the post you were editing

Editor: Update Switch to Classic Editor link

---

client/landing/gutenboarding/components/domain-picker-button/index.tsx
client/landing/gutenboarding/components/domain-picker-modal/style.scss
client/landing/gutenboarding/components/domain-picker/index.tsx
client/landing/gutenboarding/components/domain-picker/style.scss

I feel trapped when I enter domain picker modal, like there's no way out. This PR adds an experimental cancel button to see how it feels.
Also, when this other PR https://github.com/Automattic/wp-calypso/pull/41731 is merged, the cancel button will also appear on the sticky footer.
* Open up domain picker modal.
* Clicking on "Cancel" button will close the domain picker modal. (It no longer go back to popover.)
Fixes https://github.com/Automattic/wp-calypso/issues/41542#issuecomment-621879136

Gutenboarding: Added experimental cancel button on domain picker.

---

client/landing/gutenboarding/components/bottom-bar-mobile/index.tsx
client/landing/gutenboarding/components/bottom-bar-mobile/style.scss
client/landing/gutenboarding/mixins.scss
client/landing/gutenboarding/onboarding-block/style-preview/font-select.tsx
client/landing/gutenboarding/onboarding-block/style-preview/index.tsx
client/landing/gutenboarding/onboarding-block/style-preview/style.scss
client/landing/gutenboarding/variables.scss

This PR is a variant on PR #41732 where we added a preview to the mobile view of the Style step in Gutenboarding. In this variant, instead of listing all the buttons below the preview, we list a drop-down button _above_ the preview.
Because we need to display correctly rendered font pairs in the drop-down, I couldn't use the native `select` element or the pre-existing WordPress components for `SelectControl` or `Panel`/`PanelBody`. Instead, I've gone with a simple approach of a button that displays the selected fonts, and when you click it, we display the set of font buttons styled to look more like they're in a drop down list (similar to the domain categories drop down). Selecting a font then closes the drop down.
* Add preview to style step.
* Add drop-down button on mobile to show/hide …

Gutenboarding: Add preview to font selection page in mobile view (drop-down variant)

---

client/landing/gutenboarding/onboarding-block/style.scss

_2 mins review_
1. Simulate prefers-reduced-motion like this https://d.pr/v/RZZTBv
2. Move from page to page and see if the app honors your preference.
Fixes https://github.com/Automattic/wp-calypso/issues/41664

Disable page transitions when user prefers reduced motion

---

client/landing/jetpack-cloud/sections/backups/main.jsx

Hide the "More backups from today" block from the Main page when we don't have a backup today (Scheduled backup, no backup yet...), 
A day with backup:
Backup scheduled:
No backups yet:
**Asana card:** 1142395350490785-as-1173737050079912
- On a Backup Scheduled status, you shouldn't see "More backups from today" (Move your site timezone until match this scenario)
- Simulate the first time when you subscribe to a Backup product. With the same scenario as before, go to your React Chrome Devtool and go to the `DailyBackupStatus` component and set to null the `lastDateAvailable` property.

Hide "More backups from today" when we don't have backup today

---

client/landing/gutenboarding/components/domain-picker/suggestion-item.tsx
client/landing/gutenboarding/constants.ts
client/landing/gutenboarding/hooks/use-domain-suggestions.ts
client/landing/gutenboarding/stores/domain-suggestions/index.ts
client/landing/gutenboarding/utils/domain-suggestions.ts

Rather than hard coding the vendor id in constants, we'll pull in the existing method from Calypo (`getSuggestionsVendor()`) so the vendor values don't have to be updated in several places.
We are also centralizing fetching the return value of `getSuggestionsVendor()` in `getSignupDomainsSuggestionsVendor()`
Swing by `/new` on this branch and search for some domains. Check that:
1. We are sending `variation4_front` as the value of `vendor` to the `/domains/suggestions` API, e.g., https://public-api.wordpress.com/rest/v1.1/domains/suggestions?http_envelope=1&include_wordpressdotcom=true&include_dotblogsubdomain=false&only_wordpressdotcom=false&quantity=5&vendor=variation4_front&locale=en&vertical=p12v2&query=dfsdfsdf
2. We're sending the vendor id in the `fetch_algo` property to …

Gutenboarding: remove constant domain suggestions vendor

---

client/landing/gutenboarding/onboarding-block/edit.tsx
client/landing/gutenboarding/onboarding-block/plans/index.tsx
client/landing/gutenboarding/onboarding-block/plans/mock-data.ts
client/landing/gutenboarding/onboarding-block/plans/plan-details.tsx
client/landing/gutenboarding/onboarding-block/plans/plan-item.tsx
client/landing/gutenboarding/onboarding-block/plans/style.scss
client/landing/gutenboarding/path.ts

* Go to `/new/plans` to see the mockup.
Fixes https://github.com/Automattic/wp-calypso/issues/41787

Gutenboarding: Plans grid HTML mockup.

---

client/my-sites/domains/domain-management/components/email-verification/index.jsx
client/my-sites/domains/domain-management/components/email-verification/style.scss
client/my-sites/domains/domain-management/components/icann-verification/index.jsx
client/my-sites/domains/domain-management/edit-contact-info/form-card.jsx

This PR adds a link to change the email address when the domain is pending verification.
Change the email address for a domain you own. You should see something similar to the screenshot below:
Make sure clicking the link sends you to the contact info form.

Domains: Add link to change email when domain is pending verification

---

client/lib/checkout/index.js
client/my-sites/checkout/checkout/index.jsx

When renewing a domain from it's status card, and not from the purchases page, if the user then removes the renewal from the cart, we return the user to the domain's status page/card, instead of the purchase page.
I've deliberately kept the code simple, which means this might not work correctly if there are several items in the cart.
- Select a site on which you have a registered domain
- Go to Manage -> Domains, and select the registered domain to view it's status page/card
- Click the renew button, you will be redirected to the cart
- Remove the renewal from the cart
- Verify that you are redirected to the domain's status card, and not its purchase page
Also verify that when going to /me/purchases, choosing a domain registration, and clicking Renew Now, after removing the item from the …

Checkout: Return to domain status page from empty cart when removing renewal

---

client/my-sites/checkout/composite-checkout/wpcom/components/wp-checkout-order-summary.js
client/my-sites/checkout/composite-checkout/wpcom/components/wp-checkout.js
packages/composite-checkout/src/components/checkout-steps.js

Currently, the checkout summary (with plan features, cost summary, and happiness callout) is hidden on mobile devices. This allows it to be toggled on mobile devices, behind the "purchase details" header.
Changes from the design:
- I used `MaterialIcon` arrow component to match the sidebar toggle pattern in Calypso
- I left the cart total visible. I think this information will be valuable (especially with tax and coupon items) in steps after the review step
Collapsed | Expanded
**To test:**
- view Checkout with a viewport `<960px`
- verify that the "Purchase Details" header is visible with the current cart total
- verify that the checkout summary is collapsed by default
- verify that clicking on the "Purchase Details" header toggles the checkout summary
- …

Checkout: add ability to toggle summary on mobile

---

client/landing/gutenboarding/components/plans-button/index.tsx
client/landing/gutenboarding/stores/onboard/persist.ts
client/landing/gutenboarding/stores/persistance-config/index.ts
client/landing/gutenboarding/stores/persistence-config/index.ts
client/landing/gutenboarding/stores/plans/actions.ts
client/landing/gutenboarding/stores/plans/constants.ts
client/landing/gutenboarding/stores/plans/index.ts
client/landing/gutenboarding/stores/plans/persist.ts
client/landing/gutenboarding/stores/plans/reducer.ts
client/landing/gutenboarding/stores/plans/selectors.ts
client/landing/gutenboarding/stores/plans/types.ts

This PR is the first iteration for the store of our plans in Gutenboarding.
Note: I put the files under `stores` dir as opposed to `gutenboarding/lib/plans.ts` for consistency. Files under `gutenboarding/lib/plans.ts` can be removed after this. 
Related to https://github.com/Automattic/wp-calypso/issues/41787.

First iteration of plans store

---

client/landing/jetpack-cloud/style.scss

* Changes the color of the 404 page illustration to better match Jetpack green.
* Enter an invalid URL.

Changes colors of 404 illustration

---

client/landing/jetpack-cloud/components/daily-backup-status/style.scss

* Add a style rule to space out elements of ActivityActor on Daily Backup Summary
1. Navigate to `/backups` for a site with real-time backups
2. You may be able to find a backup that does not have "Jetpack" as the actor, but I ended up just modifying the props via React Dev Tools
a. ) Open React Dev Tools and Search for `ActivityActor`
b. ) Set the `actorType` to User and the `actorRole` to whatever ( I used "Administrator" in the example )
3. Verify the screen matched the "after" above

Jetpack Cloud: Add spacing to elements of ActivityActor on Real-Time Backup Summary

---

client/my-sites/site-settings/style.scss

* Found this while I was working on #41887; the button text for the "Add custom address" button in Site Settings was misaligned because the button width is forced to 45%. This PR centers the text inside the button.
**Before**
**After**
* Navigate to Settings on a free WP.com site
* Note the visual fix. Make sure it doesn't disrupt other buttons on the page.

Settings: Center align "Add custom address" button text

---

client/landing/jetpack-cloud/components/activity-card/style.scss

* Change styling of bottom of Activity Cards so that font attributes are always the same
2. Test that the text on the left of certain cards matched the font attributes of the "Actions" buttons on the right.

Jetpack Cloud: Use the same font attributes in ActivityCard bottom bar

---

client/my-sites/checkout/checkout-thank-you/header.jsx
client/my-sites/checkout/checkout-thank-you/index.jsx

This PR updates the Manage Domain button, so that when a single domain registration is purchased, the Manage Domain button should send the user to the domain management view for that specific domain, and not the whole list of domains.
- Purchase a single domain
- In the post checkout Thank You page, click the Manage Domain button
- The button should send you to the view for that specific domain (not the list of all domains)
- Repeat the same steps above, but this time purchasing something else along with the domain (e.g. another domain)
- The Manage Domain button should send you to the list of all domains for the site

Checkout: Update manage domain button for single domain registration purchases

---

apps/full-site-editing/full-site-editing-plugin/block-patterns/class-block-patterns.php

Adds ability to place block patterns at the beginning of the order, or remove patterns from showing up.
This code is a bit ugly. Recommendations to make it cleaner are very, very welcome. The pattern here is:
- Put all the .json or .php file paths from the patterns directory in an array
- Have a manually curated array of file paths to appear first in the block patterns
- Have a manually curated array of file paths to remove from the block patterns
Let the rest be sorted by however they happen to appear, rather than sorting by title, etc, since the title isn't shown in the list anyways. 
If grouping by title is helpful since it may give some kind of grouping to the patterns, we could rework it to include that.
Start the FSE dev build:
```
cd apps/full-site-editing
nvm use
yarn && yarn dev …
```

FSE: Manually Curate Block Patterns

---

client/landing/jetpack-cloud/lib/wrap-in-site-offset.tsx
client/landing/jetpack-cloud/sections/backups/controller.js
client/landing/jetpack-cloud/sections/backups/index.js
client/landing/jetpack-cloud/sections/scan/index.js
client/landing/jetpack-cloud/sections/scan/main.tsx
client/landing/jetpack-cloud/sections/scan/types.tsx
client/state/data-layer/wpcom/sites/scan/index.js

* This fixes a bug where the timezone of the last scan date was parsed as browser time instead of UTC. This code forces it to be parsed correctly, and uses the TZ offset from the site instead of the browser.
* Makes `wrapInSiteOffset` function a common library and implements it for Scan as well as Backup pages.
* On a site with a successful scan, go to JP cloud -> Scan.
* Compare `scanState.mostRecent.timestamp` prop to displayed time.
* Test downloading/restoring in Backups to ensure site offset is still correct. See #40782.
Fixes 1143508703416848-as-1174550638828321.

Updates display of scan to use site TZ

---

apps/full-site-editing/full-site-editing-plugin/premium-content/blocks/container/index.js
apps/full-site-editing/full-site-editing-plugin/readme.txt

* Adds the Premium Content Block SVG icon.
* Run the code and visually inspect the icon created. (In the block selector, the block menu and the block sidebar)
Fixes #41585

Premium Content Block: update Icon

---

client/my-sites/checkout/composite-checkout/wpcom/components/wp-contact-form.js

This add a description to the billing information step for carts without a domain.
**To test:**
- visit checkout without a domain in your cart
- verify that the second step has the following description: "Entering your billing information helps us prevent fraud."
- add a domain to your cart
- verify that the second step has the following description: "Registering a domain name requires valid contact information. Privacy Protection is included for all eligible domains to protect your personal information."

Checkout: add a step description to the default contact information step

---

client/landing/jetpack-cloud/components/backup-delta/index.jsx
client/landing/jetpack-cloud/components/backup-delta/style.scss
client/landing/jetpack-cloud/components/daily-backup-status/backup-changes.jsx
client/landing/jetpack-cloud/components/daily-backup-status/index.jsx
client/landing/jetpack-cloud/components/daily-backup-status/style.scss
client/landing/jetpack-cloud/sections/backups/main.jsx
client/landing/jetpack-cloud/sections/backups/style.scss

Improve styles in the main section to match the design:
- The backup status block should cover all the height with white background
- "Changes in this backup" should be inside of the backup status and with a border bottom
Before:
Now:
https://calypso.live/?branch=update/jetpack-cloud-fix-and-improve-styles-on-backupstatus-view&env=jetpack
- Apply these changes and check if it's the expected design.

Fix and improve the styles on Backup Status view

---

client/lib/media/constants.js
client/my-sites/media-library/content.jsx
client/state/media/reducer.js
client/state/media/test/reducer.js

When the Pexels external service returns an error response, this PR will show an appropriate error message to the end user.
* See D43080-code for testing instructions.

Media: Show an appropriate error when Pexels is unavailable.

---

client/landing/gutenboarding/onboarding-block/acquire-intent/vertical-select/index.tsx
client/landing/gutenboarding/onboarding-block/acquire-intent/vertical-select/style.scss

In Firefox, on `master`, the vertical placeholder animation doesn't have any whitespace between the text `My site is about ` and the placeholder. It looks like if the inline text isn't followed by any other text or inline-block elements, then Firefox ignores the trailing whitespace, whereas Chrome and Safari preserve it.
To fix the issue in Firefox, this PR replaces `{ ' ' }` with an empty span set to `inline-block` with visibility hidden and width and height of zero. While not the most elegant solution, the other approach I could think of (setting the suggestion wrapper to `inline-block`) would cause flow on issues to how the input of the vertical field worked, so this seemed a simpler fix to me.
* In the vertical select suggestions wrapper, replace the whitespace `' '` with an empty …

Gutenboarding: Fix vertical select placeholder spacing in Firefox

---

client/post-editor/editor-gutenberg-dialogs/index.tsx

Only assume that the editor deprecation notice is showing if the config is enabled.
In https://github.com/Automattic/wp-calypso/pull/41391 I assumed that the reducer would only return true if the editor deprecation notice config was true.
* We shouldn't assume that the reducer value is valid; we need to check the config is enabled first.
* Open the WP.com editor and try switching to the block editor.
* This should work regardless of whether the `editor/before-deprecation` config flag is set.

Editor deprecation: Allow users to switch to the block editor

---

client/my-sites/checkout/composite-checkout/composite-checkout.js
client/my-sites/checkout/composite-checkout/test/composite-checkout.js
client/my-sites/checkout/composite-checkout/wpcom/components/wp-checkout-order-review.js
client/my-sites/checkout/composite-checkout/wpcom/components/wp-checkout.js
client/my-sites/checkout/composite-checkout/wpcom/components/wp-order-review-line-items.js
client/my-sites/checkout/composite-checkout/wpcom/hooks/use-shopping-cart.ts
client/my-sites/checkout/composite-checkout/wpcom/lib/translate-cart.ts
client/my-sites/checkout/composite-checkout/wpcom/test/translate-cart.js

This started as a PR to highlight a purchased domain in the review step's summary, but ultimately incorporated the line item changes from our usability testing.
The PR does a few things:
- Attempts to consolidate how product labels and sub-labels are used between different products. Plans are given a sub-label of "Plan Subscription" with labels of the specific plan (i.e. "WordPress Personal"). Domains and domain-related purchases are given sub-labels of "{tld} Domain {Registration|Mapping|Transfer}" and labels of the domain in question (i.e. "example.com"). Some products, like support sessions and premium themes, return special cases and will require a follow-up backend diff with additional testing
- Introduces some messaging ("billed yearly") for the monthly/yearly price discrepancy from …

Checkout: update line item design

---

client/my-sites/domains/domain-management/components/domain/non-primary-domain-plan-upsell.jsx

* Use `UpsellNudge` rather than `Banner` for the non-primary domain upsell nudge. See #38778 
**Visuals**
* Create a new free site from `/start`, then go to Manage -> Domains -> Add a domain to this site
* When you get to checkout, remove the plan from your cart; you should only be purchasing the domain name. Check out. (Don't forget to cancel right after testing.) Wait for the domain to be fully active.
* Go back to Manage -> Domains and click on the domain name you've purchased. Note the upsell at the top of the screen.
* Double check the Tracks events to make sure they're the same as on master. Also make sure there are no visual regressions.

Domains: Update Banner to UpsellNudge

---

client/landing/gutenboarding/components/header/index.tsx
client/landing/gutenboarding/gutenboard.tsx
client/landing/gutenboarding/hooks/use-on-site-creation.ts

* If the user selects a paid plan using Plans Grid and confirm the selection, it will be added to cart (together with any paid domain) and there will be a redirect to `/checkout` after site creation in Gutenboarding.
* Go to `/new?flags=gutenboarding/plans-grid`
* Select a paid plan using Plans grid and complete Gutenboarding flow.
* After site creation you should be redirected to `/checkout` with the selected plan and any paid domain selected in Gutenboarding.
* Check if existing flows still work (free and paid domain which redirects to calypso signup flow).
* Check if [redirect to editor after emptying checkout cart](https://github.com/Automattic/wp-calypso/issues/41652) still works.
Part of #41787

Gutenboarding: show checkout if user selects a plan

---

client/landing/gutenboarding/onboarding-block/acquire-intent/site-title.tsx
client/landing/gutenboarding/onboarding-block/acquire-intent/style.scss

Note: this is a speculative PR to try to make it a bit clearer that there is a text input field for the site title in situations where a user might not see it (mobile and desktop if a user clicks away from the site title field) — it doesn't appear on the designs, so this is really just one idea for how to help solve part of this.
* Add a grey line site title placeholder on mobile
* Add a grey line site title placeholder on desktop when the field is not focused, so that it's clearer where to click to focus it again
When focused it'll look as it did previously:
When not focused (if a user clicks out of the field) then the line will show:
* Go to /new and test the line for the empty site title displays when you expect it would
Related to #https://github.com/Automattic/wp-calypso/issues/41923 …

Gutenboarding: Add site title placeholder

---

client/state/stats/lists/selectors.js

This fixes https://github.com/Automattic/wp-calypso/issues/41940 where the top post wasn't being reported correctly in the stats card. A stats selector did not implement [sort](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort) correctly.
- Visit /home with a site that has a good amount of traffic
- Compare the top post or page on Home with results on http://calypso.localhost:3000/stats/day/posts/siteSlug under the 7 day view
- Verify that top posts or page matches instead of a random result

Stats: implement top post sort properly

---

client/lib/abtest/active-tests.js

* Pausing Plans-Domains swap test (100% traffic goes to control). Check pbxNRc-cj-p2
* Domain step should appear first. Then Plans.

Pausing plans-domains swap test

---

client/components/phone-input/index.jsx
client/components/phone-input/phone-number.js
client/components/phone-input/test/test-phone-number.js

PhoneInput has input masking, but there was a fundamental data source problem: its input comes from a prop, and when you type, the number gets formatted before being sent upstream, but ContactDetailsFormFields then reformats that again to ICANN format when sending it further upstream. If the authorative state lives above ContactDetailsFormFields, then when the number is sent back downstream, it arrives in a different format than PhoneInput expects and can cause strange display formatting and even an infinite loop.
This change completely refactors PhoneInput so that it keeps its current number in three formats: raw (eg: '1234567899'), display (eg: '+1 (123) 456-7899'), and icann (eg: '+1.1234567899', I think?). When it receives a new value via props, it compares that value to all three old …

Rewrite PhoneInput to allow control with different formats

---

apps/wpcom-block-editor/src/wpcom/features/tracking/wpcom-inserter-menu-search-term.js

* Removes fallback code to track empty search results in block inserter search
1) Update your testing site with these changes (SB)
2) In your testing site, open the client dev console and set up the debug
```
> localStorage.setItem( 'debug', 'wpcom-block-editor*' )
```
A hard refresh is needed.
3) Open the Inserter Menu
4) Open the `Inserter Menu` selector
5) Generate event typing there
6) Confirm that it behaves as expected. It means when you get results, it should trigger a `wpcom_block_picker_search_term` event, as the screenshot shows below.
**blocks found** event
When there aren't blocks there, it also should trigger the `wpcom_block_picker_no_results` event too:
**blocks not found** event

Block Editor: Remove 7.8.1 fallback in search

---

client/landing/gutenboarding/hooks/use-domain-suggestions.ts

Stops sending vertical to paid domains suggestion API.
Context p99Zz8-Ps-p2/#comment-3463
We still use vertical as a backup search term if the user doesn't provide a site name.
We also keep sending the vertical to free `*.wordpress.com` domain suggestion API:
https://github.com/Automattic/wp-calypso/blob/2eaca4d1edffab898dd1d7002f0d2278a8fb6b39/client/landing/gutenboarding/hooks/use-free-domain-suggestion.ts#L28
* Remove vertical from domain suggestions API
- Enter `/new` flow
- Enter vertical
- Enter site title
- Observe from network tab that paid domains API is called without `vertical`

Gutenboarding: don't use verticalized TLDs

---

client/my-sites/checkout/composite-checkout/record-analytics.js
client/my-sites/checkout/composite-checkout/wpcom/lib/translate-cart.ts
client/my-sites/checkout/composite-checkout/wpcom/test/translate-cart.js

The changes in #41688 may have caused a regression that can cause fatal errors. Line items passed to `CheckoutProvider` _must_ have a `label` property. The logic in that PR, however, says that if a product is not a plan or a theme or a concierge session, its `label` is set to the `meta` returned from the cart endpoint. This is risky because `meta` is only defined for very specific products, like domains and domain-related items.
This PR refactors that logic so that it only uses `meta` if it exists and if it is a domain product.
- Visit composite checkout with plans in the cart and verify they display the plan name first.
- Visit composite checkout with domain reg products in the cart and verify they display the domain name first and the product name second.
- Visit composite checkout with …

composite-checkout: Make sure label is always set

---

client/landing/gutenboarding/components/plans/plans-table/plan-item.tsx

Until we move domains modal to a step-canvas or some other mechanics; let's hide the link for now. We'll add this back once rest of the plans grid is ready.
* Hide domain nudge from the plans grid.
- In `/new` flow (on live sites with `?flags=gutenboarding/plans-grid`) ...
- Open the plans grid from plan button
- Observe no domain nudge link
- Choosing domain doesn't work yet, but you can set the `prop` manually and see it show up in every plan

Gutenboarding: plans - hide domain nudge

---

apps/full-site-editing/full-site-editing-plugin/premium-content/blocks/container/controls.js
apps/full-site-editing/full-site-editing-plugin/premium-content/blocks/container/edit.js
apps/full-site-editing/full-site-editing-plugin/premium-content/blocks/container/index.js
apps/full-site-editing/full-site-editing-plugin/premium-content/blocks/container/inspector.js
apps/full-site-editing/full-site-editing-plugin/premium-content/blocks/container/plan.js
apps/full-site-editing/full-site-editing-plugin/premium-content/blocks/subscriber-view/edit.js
apps/full-site-editing/full-site-editing-plugin/premium-content/editor.css
apps/full-site-editing/package.json

This patch will try to fix the issues outlined here - https://github.com/Automattic/wp-calypso/issues/41587
The patch uses `formatCurrency` to format the plan price details correctly.
Apply the D43140-code and try this out on an FSE and simple site.
We have extra spacing between the fields of the Add subscription form. Removing it cleans up the layout.
Now if you remove all the blocks in subscriber view, you will see this;

Tidy up Premium Block Style and Behaviour

---

client/lib/abtest/active-tests.js

Now that the usability design updates are wrapping up, we're going to bump the AB test date to run a clean hypothesis of composite vs legacy Checkout eperiences.
**To test:**
- visual sanity check

Checkout: bump test date

---

apps/full-site-editing/full-site-editing-plugin/premium-content/premium-content.php
apps/full-site-editing/full-site-editing-plugin/premium-content/subscription-service/class-token-subscription-service.php
apps/full-site-editing/full-site-editing-plugin/premium-content/subscription-service/class-wpcom-offline-subscription-service.php
apps/full-site-editing/full-site-editing-plugin/premium-content/subscription-service/include.php

This PR adds a new subscription service that will be used when rendering post content when the token isn't available, but the user is logged in on WPCOM.
On WPCOM, the user can view post content in 2 places where the token is not available;
* New post email notification
* WPCOM Reader.
In both cases, WPCOM sets the current site ID to match where the post is from and the current user ID to match the viewer WPCOM user ID. This allows us to verify if that user has access to premium content on that post.
* Apply D43142-code
* Login to https://bestmemberships.wordpress.com
* Create a post with premium content block
* Open the post incognito and subscribe with an email address you have access to
* Follow the blog and click on the Manage subscriptions (should redirect you to …

Support premium content in email subscription and reader

---

apps/full-site-editing/full-site-editing-plugin/common/index.js
apps/full-site-editing/full-site-editing-plugin/common/index.php
apps/full-site-editing/full-site-editing-plugin/common/index.scss
apps/full-site-editing/package.json

As block patterns were recently moved, there have been a number of support requests from users that have not been able to find them.
This reintroduces the block patterns sidebar plugin to notify users of the change.  This is intended to be temporary and removed in the coming weeks after users have had a chance to adapt to this change.
* Build / Sync FSE plugin on this branch.
* Go to the editor, ensure the block patterns Icon is in the top-right toolbar and in the dropdown menu.
* Verify clicking the icon shows a message that block patterns have moved.
* Verify clicking the example icon opens the block patterns inserter.
<hr/>
<hr/>
<hr/>
<hr/>
Fixes #41930

Add notice for block patterns new location.

---

client/blocks/inline-help/contextual-help.js

* Update page ID to correct value for this support page: [Domain Mapping vs Domain Transfer](https://wordpress.com/support/domain-mapping-vs-domain-transfer/).
Fixes #42007
1. Using the live branch, go to Plans > Domains
2. Edit a domain
3. Click the ? icon on bottom right to show Inline Help menu
4. Click the "Connect an Existing Domain" link
5. Click "Read more" button
Verify the correct page appears now.

Fix Inline Help link for connecting existing domain

---

client/landing/gutenboarding/components/plans/plans-table/index.tsx
client/landing/gutenboarding/components/plans/plans-table/plan-item.tsx
client/landing/gutenboarding/components/plans/plans-table/style.scss
client/landing/gutenboarding/stores/plans/actions.ts
client/landing/gutenboarding/stores/plans/constants.ts
client/landing/gutenboarding/stores/plans/index.ts
client/landing/gutenboarding/stores/plans/plans-data.ts
client/landing/gutenboarding/stores/plans/reducer.ts
client/landing/gutenboarding/stores/plans/resolvers.ts
client/landing/gutenboarding/stores/plans/selectors.ts
client/landing/gutenboarding/stores/plans/types.ts

1. Use the Public API to fetch localized plans prices. 
2. Add a loading animation when the price is being loaded.
3. Add Types for the plans coming from the API (useless now but I typed it because I initially used it, and can be useful soon). 
1. Head /new?flags=gutenboarding/plans-grid
2. Click on the plan button on the top right corner and you should see the prices loading then appearing. 
Partially fixes https://github.com/Automattic/wp-calypso/issues/41787

Gutenboarding: fetch plans prices from API

---

client/components/phone-input/index.jsx

This fixes a bug introduced by #41783 when the `inputRef` prop is undefined.
Try checkout when `inputRef` is undefined on `PhoneInput`.

PhoneInput: Make sure to not throw when inputRef is undefined

---

client/landing/gutenboarding/components/header/index.tsx
client/landing/gutenboarding/hooks/use-on-site-creation.ts
client/landing/gutenboarding/onboarding-block/style-preview/index.tsx
client/landing/gutenboarding/path.ts
client/landing/gutenboarding/stores/onboard/actions.ts
client/landing/gutenboarding/stores/plans/constants.ts
client/landing/gutenboarding/stores/plans/plans-data.ts
client/landing/gutenboarding/stores/plans/reducer.ts
client/landing/gutenboarding/stores/plans/selectors.ts
packages/data-stores/src/site/types.ts

This PR changes how the site is created if the user has chosen an e-commerce plan: The site is created as public straight away, so the Atomic transfer after payment work and the user can be redirected to Woo NUX.

Gutenboarding: Create public sites when ecommerce

---

client/gutenberg/editor/calypsoify-iframe.tsx
client/landing/gutenboarding/index.tsx
client/landing/gutenboarding/onboarding-block/design-selector/index.tsx
client/landing/gutenboarding/onboarding-block/edit.tsx
client/signup/config/flows-pure.js
config/development.json
config/stage.json
config/wpcalypso.json

* Removes `gutenboarding` flag that stops the flow from being released to `wordpress.com/new` non-proxied
* Removes `gutenboarding/style-preview` flag that was used to gate out style/font picker during development. That flag isn't used anymore.
- Test `/new` flow
- Confirm font picker step still shows up

Remove gutenboarding feature flag

---

client/landing/gutenboarding/components/plans/plans-details/style.scss
client/landing/gutenboarding/components/plans/plans-grid/style.scss
client/landing/gutenboarding/components/plans/plans-modal/style.scss
client/landing/gutenboarding/components/plans/plans-table/plan-item.tsx
client/landing/gutenboarding/components/plans/plans-table/style.scss

This supports mobile devices and desktop.
Laptop size is slightly squashed because of the 5 plans now available
* Style changes to support mobile devices
Mobile
Desktop
Laptop
* ensure that the `gutenboarding/plans-grid` feature flag is turned on. Currently it is off for staging/prod
* open `/new` 
* In the top right corner of the page click *Free Plan*

Make the plan selector grid work on mobile devices

---

apps/full-site-editing/full-site-editing-plugin/common/index.js

Pull #41963 introduces an edge case where atomic sites not running Gutenberg will have a block pattern plugin pointing them to a feature that doesn't exist.
This PR should gates this plugin from being registered based [`__experimentalLibrary`](https://github.com/WordPress/gutenberg/blob/4830c2c2b95dc612b73efffbd3ed03cd93cd83fa/packages/edit-post/src/components/layout/index.js#L17-L20) export from `block-editor`, which [contains the patterns in their new location](https://github.com/WordPress/gutenberg/blob/4830c2c2b95dc612b73efffbd3ed03cd93cd83fa/packages/edit-post/src/components/layout/index.js#L185-L192).
#41963 would also introduce a duplicate sidebar item, one with patterns and one incorrectly indicating patterns had move.
This PR fixes both of these issues.
* Apply D43208-code
* …

Block Patterns have moved - gate registration to gutenberg being active.

---

client/landing/gutenboarding/components/plans/plans-details/index.tsx
client/landing/gutenboarding/components/plans/plans-details/style.scss
client/landing/gutenboarding/components/plans/plans-grid/index.tsx
client/landing/gutenboarding/components/plans/plans-grid/style.scss

* Ability to pan details table left & right on mobile.
* Open up plans grid in `/new`.
* Panning details table should not affect main body's scrollbar (well at least, until it reaches the end).
Fixes part of #41787

Added ability to pan & scroll plans details on mobile view.

---

client/landing/gutenboarding/components/domain-picker-button/style.scss
client/landing/gutenboarding/components/header/index.tsx
client/landing/gutenboarding/components/header/style.scss
client/landing/gutenboarding/components/plans/plans-button/style.scss

The problem is that long domain picker button pushing out plans grid button. Long domain picker button also affects panning of plans grid on mobile view.
This PR:
* Fixes domain picker button overflowing issues on mobile view.
However, it has caveats:
- This disables domain picker slide out animation on mobile view. To fix in another PR.
- This fix is quick & dirty.
* Enter a long domain on gutenboarding and ensure it doesn't break on mobile view.
Fixes #41435

Gutenboarding: Fix domain picker button overflow issues on mobile view.

---

client/landing/gutenboarding/stores/plans/plans-data.ts

All in the title. 
To test, make sure 'Remove WordPress ads' doesn't exist under the free plan in Gutenboarding.

Gutenboarding: Remove 'Remove WordPress ads' from free plan

---

client/landing/gutenboarding/components/plans/plans-table/plan-item.tsx
client/landing/gutenboarding/components/plans/plans-table/style.scss

While domain picker is disabled, show "Free Wordpress.com Subdomain" on plans grid for Free plan.
* Just open up plans grid in gutenboarding.

Gutenboarding: Show "Free Wordpress.com Subdomain" on plans grid for Free plan.

---

client/landing/gutenboarding/hooks/use-on-site-creation.ts
client/landing/gutenboarding/index.tsx
client/landing/gutenboarding/stores/onboard/actions.ts
packages/data-stores/src/site/selectors.ts
packages/data-stores/src/site/test/selectors.ts
packages/data-stores/src/site/types.ts

When Gutenboarding loads, redirect to the editor if a site was created recently (`selectedSite)` and the requested path is `create-site`, `plans`, or `style`. If the path doesn't match one of these, then we treat the flow as a "fresh" session and reset the `selectedSite`.
This change attempts to fix the issue where a user completes signup and then for whatever reason clicks "back" to get back to Gutenboarding — if we allowed them to do this, _another_ site would be created. Instead we want them to proceed to the editor. This should 🤞also resolve the issue where a user is in the checkout and clicks back — we also want to redirect them to the editor.
* When creating a site, after resetting the onboarding store (but before redirect) record the id of the newly created site in the …

Gutenboarding: redirect to editor if selectedSite is current

---

client/landing/gutenboarding/components/signup-form/index.tsx
client/landing/gutenboarding/components/signup-form/style.scss

By request of our Legal team, we are moving the TOS agreement copy on top of the signup button and making the text be the same size that the rest of the copy in that form.

Landing: update TOS text

---

client/landing/gutenboarding/_z-index.scss
client/landing/gutenboarding/onboarding-block/acquire-intent/vertical-select/style.scss

Add a `z-index` to the suggestions list. 
See p1589197593181500-slack-gutenboarding for details.
_I tried adding the value to [`client/assets/stylesheets/shared/functions/_z-index.scss`](https://github.com/Automattic/wp-calypso/blob/master/client/assets/stylesheets/shared/functions/_z-index.scss) but this files isn't being used for `z-index()` function and the build is failing._

Bring verticals suggestions list to the front

---

client/components/domains/contact-details-form-fields/custom-form-fieldsets/region-address-fieldsets.jsx
client/components/domains/contact-details-form-fields/index.jsx
client/components/domains/contact-details-form-fields/test/index.js
client/lib/form-state/index.js
client/my-sites/checkout/composite-checkout/composite-checkout.js
client/my-sites/domains/components/form/country-select.jsx
client/my-sites/domains/components/form/state-select.jsx

The (rather old) `ContactDetailsFormFields` component is currently being used in two ways. 
Its original incarnation, still used by old checkout and payment management screens, uses a state management object created by `lib/form-state` as a singleton form state manager that deals with updates, validation, etc.
For composite checkout, we have need to keep our form state external to the `ContactDetailsFormFields`, so we had added several props to make it more like a partially managed component. I say "partially" because the flow worked as follows: 
- On initial render, the props were used to set the state, which was used to set the field values.
- When a field changed, the state was changed, and a callback was called so the parent could receive the updated data.
- If the data in the props …

Add managed mode to ContactDetailsFormFields

---

client/landing/jetpack-cloud/components/daily-backup-status/index.jsx
client/landing/jetpack-cloud/components/server-credentials-form/style.scss
client/landing/jetpack-cloud/sections/backups/rewind-flow/download.tsx
client/landing/jetpack-cloud/sections/backups/rewind-flow/restore.tsx
client/landing/jetpack-cloud/sections/backups/rewind-flow/style.scss
client/landing/jetpack-cloud/style.scss
client/my-sites/activity/activity-log-item/index.jsx

* For scheduled backups in the next hour, say "In the next hour" as opposed to "In the next 1 hour"
* On the download creation confirmation page, remove superfluous "of" from instructions.
* On the Settings page, add a link to support for "Find your server credentials."
* On the "download creation failed" page, add supplementary text
* On the "restore failed" page, add supplementary instructions for what to do next
* Tweak styling on the "restore failed" page to more closely match mockups
* Check all the aforementioned pages to ensure verbiage has changed as described and matches mockups and design feedback.
Fixes 1151678672052943-as-1172722058616305.

Fix Jetpack Cloud verbiage

---

apps/full-site-editing/full-site-editing-plugin/wpcom-block-editor-nux/src/images/preview.svg
apps/full-site-editing/full-site-editing-plugin/wpcom-block-editor-nux/src/wpcom-nux.js

We're updating the copy and image based on the description in #41960
After unsuccessful attempts to render `<NuxPage />` inside `<Guide />` conditionally^, I went with a filtered collection approach.
All suggestions for improvement wanted. :)
Easiest way I found is to check out this branch
Sandbox a test site
Comment out [the following lines](https://github.com/Automattic/wp-calypso/blob/master/apps/full-site-editing/full-site-editing-plugin/wpcom-block-editor-nux/src/wpcom-nux.js#L47):
```
/* if ( ! isWpcomNuxEnabled || isSPTOpen ) {
return null;
} */
```
Run `cd apps/full-site-editing && yarn dev --sync`
Test Gutenboarding and non-Gutenboarding versions by setting `isGutenboarding` to `true/false`
Fixes #41960
^ The result of trying something like `{ isGutenboarding && <NuxPage { …

FSE: Update NUX slides

---

client/lib/ads/utils.js
client/my-sites/earn/ads/wrapper.jsx

* Making it a bit clearer that only site owners may sign up a site for WordAds even if the site is generally eligible.
* Add yourself as an admin to premiumtestsite2059103923893838.wordpress.com or spin up a new Premium site that your user isn't an admin of.
* Visit the earn page for the site, e.g. http://calypso.localhost:3000/earn/premiumtestsite2059103923893838.wordpress.com
* Clicking on the `Earn ad revenue` button should take you to a page that says "Only site owners are elegible to activate WordAds."
* Visit that same page as the owner and you should see the regular activation/upgrade/notices.

Update: Cleanup & clarify WordAds signup eligibility

---

client/my-sites/checkout/composite-checkout/wpcom/types/wpcom-store-state.ts

* The error object translated from the validation endpoint may have null properties, causing `undefined is not an object` and related errors in production.
TBD

composite-checkout: Add option chaining to conversion of validation error object

---

client/blocks/upsell-nudge/index.jsx
client/components/banner/index.jsx
client/my-sites/domains/domain-management/components/domain/new-domains-redirection-notice-upsell.jsx
client/my-sites/domains/domain-management/components/domain/new-domains-redirection-notice-upsell.scss
client/my-sites/domains/domain-search/index.jsx

This PR adds a plan upsell banner that explains new domains on a free site will redirect to the free subdomain.
For a site without a plan, go to Manage -> Domains, and then click on the 'Add a domain to this site' button.
You should see this banner above the results:
Verify that clicking the Upgrade button sends you to the checkout page with a Personal plan added to cart.
Also check that events are sent properly
Finally, make sure this banner won't show for sites with a plan, or for users that are exempt from PWPO

Domains: Add plan upsell that explains new domains cannot be primary

---

client/components/forms/README.md
client/components/section-header/README.md
packages/components/src/button/README.md

In a previous PR: https://github.com/Automattic/wp-calypso/pull/41647, we updated our form labels and card headings/section headings to use sentence case.
We want to add this information to Devdocs as a part of each component's guidelines to make sure we have consistent casing moving forward.
http://calypso.localhost:3000/devdocs/client/components/forms/README.md?term=form
http://calypso.localhost:3000/devdocs/client/components/section-header/README.md?term=sectionheader
I also just updated the `Button` component to separate sentence casing as its own item:
**Before:**
**After:**
http://calypso.localhost:3000/devdocs/packages/components/src/button/README.md?term=button

Devdocs: Update Forms, SectionHeader to include sentence-case in guidelines

---

client/my-sites/plans-features-main/index.jsx

This change hides the plan tabs if the Personal plan is hidden (only Premium showing in "personal" tab) and simply shows the three available plans without any tabs.
More info: pau2Xa-1de-p2
Related:
https://github.com/Automattic/wp-calypso/pull/41507
https://github.com/Automattic/wp-calypso/pull/41512
https://github.com/Automattic/wp-calypso/pull/41526
* Boot this branch locally.
* Sandbox `public-api.wordpress.com`.
* Add this filter to your `0-sandbox.php` file:
```
add_filter( 'get_user_marketing_price_group', function( $price_group ) {
return 'price_2020_q2_test_2';
}, 10, 1 );
```
* Visit http://calypso.localhost:3000/plans/[SITE]
* You should see the Premium, Business, and eCommerce plans, and no tabs.

Hide personal plans tab if only the Premium plan will be shown

---

client/lib/form-state/index.js
client/my-sites/domains/components/form/country-select.jsx
client/my-sites/domains/components/form/state-select.jsx

This was extracted from (the reverted changes in) #41723. It modifies some components which render very slowly (country list, state list) to be Pure, so they will not re-render when their props do not change. This should greatly speed up using these components.
Visit old checkout with a domain in your cart. Verify that the country and state select inputs behave as expected.

Improve rendering speed of contact details forms

---

client/state/lasagna/post-channel/middleware.js
config/_shared.json
config/development.json
config/horizon.json
config/stage.json
config/wpcalypso.json

* Make all environments connect to prod (our only in house instance).
* Enable real-time full post view comments for a12s
1. Boot the calypso.live branch below.
2. Click out of the Reader section. Click into the Reader section. Make sure it successfully connects to `rt-api.wordpress.com` (`101` response) in your web inspector.
3. Go to a post full view. Comment from wherever else you'd like (another tab in Calypso, the front of the blog, whatever). You should see the comments popping in live as you'd expect.

Enable real-time full post view comments for a12s

---

apps/full-site-editing/full-site-editing-plugin/global-styles/src/dom-updater.js

* Updates the class name(s) we are using when updating font selection.
Upon inspection, after selecting new font pairing (Work Sans/Rubik): 
it is overridden by the initial styles that were set when the editor was loaded:
These styles now have higher specificity, so I have added the `.edit-post-visual-editor` class to what we are using when we update the selection.
* Sync or patch this FSE build.
* Visit a sandboxed site with a global styles supporting theme activated (like Maywood)
* Test global styles in the editor and verify they update on selection.
Fixes #42073

Fix global styles not updating on selection.

---

client/blocks/post-share/index.jsx

The current `calypso_publicize_share_schedule` and `calypso_publicize_share_instantly` events do not currently track the blog ID or whether the current site is a Jetpack site. This PR adds that information so that we can run some analysis on how many sites with a paid Jetpack plan are using the scheduling functionality.
* Begin tracking blog_id and is_jetpack with the `calypso_publicize_share_schedule` and `calypso_publicize_share_instantly` events.
* Checkout patch
* Go to `/posts/$site`
* Click the `...` next to one of your posts
* Share a post
* Schedule a post
* Check tracks for `calypso_publicize_share_%` and your user ID and ensure that the events show up with the `blogid` set and with the `is_jetpack` value set in event props

Publicize: Begin tracking blog_id and is_jetpack when publicizing from the posts list

---

client/lib/plans/index.js
client/lib/plans/test/get-popular-plan-spec.js
client/my-sites/plans-features-main/index.jsx

This PR attempts to fix the issue that there is no primary button nor the popular badge when the one that is labeled as popular is hidden, first reported by @niranjan-uma-shankar here: https://github.com/Automattic/wp-calypso/pull/41676#pullrequestreview-407152120 .
The solution here is to make `getPopularPlanSpec()` function be aware of the available plans, so it won't report anything that is simply unavailable.
Before:
After:
1. `yarn test-client lib/plans/test/get-popular-plan-spec.js` should pass.
1. Follow the instructions in https://github.com/Automattic/wp-calypso/pull/41676 to set an account that falls into the price group 3.
1. Visit `/plans`, the business plan should be labeled as the popular choice.
1. Test the same for the site creation flow.
1. Test the same for the signup …

Enhance: getPopularPlanSpec() can now takes available plans into consideration.

---

client/lib/abtest/active-tests.js
client/me/help/active-tickets-notice/index.jsx
client/state/help/ticket/actions.js

Removes the A/B test for Active Tickets Notice (and an associated Tracks event that we no longer need to report on).
We are committing to the `showNotice` variant which performed better than the `control`. Full results and analysis of the test are posted at pbvpgB-lY-p2

Remove Active Tickets Notice AB test

---

client/my-sites/customer-home/cards/actions/wp-for-teams-quick-links/index.jsx

Fixes a small regression introduced in #41855 that causes the quick link to show with an extra padding for WP for Teams sites.
Before | After
--- | ---
* Switch to a WP for Teams site (you can create one in https://wordpress.com/start/wp-for-teams)
* Go to My Home.
* Verify the quick links are displayed correctly.

My Home: Fix quick links styles for WP for Teams sites

---

client/landing/gutenboarding/hooks/use-free-domain-suggestion.ts

- Remove vertical param from the free domain suggestions API request
- Think about what to snack on for brunch
p99Zz8-Ps-p2#comment-3464
- Enter the `/new` flow
- Enter a vertical and site title
- Observe from network tab that the free domains API is called without a vertical
- Make a sandwich
Here is a sandwich

Gutenboarding: Remove the vertical param when generating free domains

---

client/landing/jetpack-cloud/components/scan-badge/index.tsx
client/landing/jetpack-cloud/components/sidebar/index.jsx
client/landing/jetpack-cloud/components/sidebar/style.scss

* Adds a link to the scanner when the badge is showing.
* Load a site with Scan in Cloud.
* On Backup page with the Scan menu closed, create a threat or progress meter.
Example action:
```js
{
type: 'JETPACK_SCAN_UPDATE',
siteId: 12345,
payload: {
state: 'idle',
threats: [{ id: 123, signature: 'TEST', description: 'Test Threat', status: 'current', firstDetected: '2020-01-01', fixable: false }],
credentials: [],
mostRecent: {
timestamp: '2020-05-11T20:08:10+00:00',
duration: 220,
progress: 50,
error: false,
isInitial: false
}
}
}
```
* Click on the badge.
Fixes 1151678672052943-as-1174867022546273.

Adds link to scanner on badge

---

client/landing/jetpack-cloud/sections/backups/rewind-flow/download.tsx
client/landing/jetpack-cloud/sections/backups/rewind-flow/restore.tsx

* I got some warnings from @a8ci18n that translations for download and restore failures didn't have clarifying comments, so I'm adding those here.
* No expected changes to behavior. Do tests pass? Does everything still work in the UI?

Add translation comments for download/restore failures

---

client/lib/i18n-utils/browser.js
client/my-sites/checkout/checkout/bundled-domain-notice.jsx
client/my-sites/checkout/checkout/checkout-terms.jsx
client/my-sites/checkout/checkout/style.scss

* Shows information about bundled domains when a user purchases dotcom plans.
Requested in pau2Xa-18u-p2#comment-4655
* Add a dotcom paid plan to the cart.
* If the plan bundles a domain, a message about bundled domains should show up in the checkout page as follows:
_Note: Currently every dotcom plan provides a bundled domain._

Add: bundled domain notice to the checkout page

---

client/landing/jetpack-cloud/components/fix-all-threats-dialog/index.tsx
client/landing/jetpack-cloud/sections/scan/main.tsx
client/landing/jetpack-cloud/sections/scan/style.scss

Add Scan Retry Button to the error page. 
Before:
After: 
* Create a scan error. 
* Or fake it.

Jetpack Cloud: Add Retry Scan button.

---

client/landing/jetpack-cloud/components/threat-dialog/index.tsx

* Make the site name don't look isolated by removing the `:` and surrounding it with double quotes.
* Select a site that has Scan and at least one threat
* Go to Scan -> Scanner
* Open the threat card and click the `[Ignore threat]` button
* Verify the name of the site appears between double quotes
* Verify the `:` is no longer present in the sentence

Jetpack Cloud: put the site name between double quotes and make it part of the sentence

---

client/landing/jetpack-cloud/sections/scan/history/index.jsx
client/landing/jetpack-cloud/sections/scan/history/style.scss

* Remove the filter section when there are no threats to show in Scan -> History.
* Go to Scan and select a site that **doesn't have** threats that have been fixed or ignored
* Verify the filter section doesn't show up
* Go to Scan and select a site that **has** at least one threat that has been fixed or ignored
* Verify the filter section does show up

Jetpack Cloud: display the filter section only if there are threats to show

---

client/components/domains/registrant-extra-info/ca-form.jsx
client/components/domains/registrant-extra-info/fr-form.jsx
client/components/domains/registrant-extra-info/uk-form.jsx

* Adds new `isManaged` props to the `registrant-extra-info` component which override the internal state management.
This should have no observable effect in either old or new checkout or on the domain contact edit page. Verify this by proceeding through these flows with either a .ca, .uk, or .fr domain.

Add isManaged prop to registrant-extra-fields component

---

client/blocks/jitm/index.jsx
client/blocks/jitm/style.scss
client/layout/style.scss

* Set a max width on JITMs displayed within the `layout__column` class. Ideally we'd set these more specifically so we could always match the layout column width, but there aren't always screen-specific selectors available to know where we are this early in the layout. This is a compromise, using the same width as the wide-column layout.
**Before**
**After**
* Navigate to Plugins on a Jetpack site with the free plan; you'll see this upsell if you haven't dismissed it before. Check for visual issues.
* Click Install plugin on the same page. You'll see another upsell; it should be the same width as the wider column.
Fixes #41001

JITMs: Update width to better align with layout column

---

client/landing/gutenboarding/components/plans/plans-table/style.scss
client/landing/gutenboarding/components/titles.scss
client/landing/gutenboarding/onboarding-block/plans/index.tsx

This is just a small PR to add a few styling tweaks to the plans step in Gutenboarding following on from https://github.com/Automattic/wp-calypso/pull/42028:
* Add `gutenboarding-page` class to the plans step, so that it animates in using the `gutenboarding-page-appear` fade in.
* Set a maximum width for the Gutenboarding sub-title so that the text naturally wraps to look closer to the design. (This is the `Pick a plan that's right for you...` text on the `plans` step, but the change shouldn't adversely affect any other steps)
* Add an `:active` pseudo-class to the selected plans button so that if you click a selected plan, it doesn't make the text black (currently on `master` if you click and hold on a selected plan button, the text will go black).
* Checkout this branch locally so that …

Gutenboarding: tweak Plans page styling

---

client/blocks/inline-help/popover.jsx
config/development.json

* If an Atomic user chooses to switch to Classic after the Calypso editor is deprecated, add a check to see if classic editor enabled on the users Atomic site, if not enable it, and then redirect to the editor in wp-admin
* Check out PR to local Calypso dev enviroment.
* Open an Atomic sites plugin page and check that the Classic editor is not currently active
* In Calypso open the block editor for that Atomic site. Under the floating Help button bottom right click on the 'Switch to Classic Editor' button. 
* Check that you are redirected to the Classic Editor in wp-admin
* Go back to Calypso and check that when you choose to edit a page the editor preference has been changed so that you go into the classic editor and not the block editor (at this stage you will still go to the Calypso …

Editor: Add a check to see if classic editor enabled on Atomic sites 

---

client/blocks/login/social.jsx

The login page has a redirect_to feature; once login is complete the page will go to that page. However it doesn't work when the user uses social login.
By including the redirect_to param in the callback url we pass to oauth the redirect should be preserved.
This is difficult to test because Apple ID doesn't work in local environment. Hence the `a8c_testing_redirect_url` flag so it can be tested further in production.
Once this is on staging/production I'll be able to test whether it works. Main reason it wouldn't work is because `redirect_to` is double encoded and it might not get double decoded properly. Also need to test the Google login since it shares the same code.
This is a login page bug, but I'm addressing it to fix the Gutenboarding flow which needs the redirect_to feature to …

Gutenboarding: Forward login page's own redirect_to param to social logins

---

client/gutenberg/editor/calypsoify-iframe.tsx

* Add `editor-after-deprecation` feature flag to the editor's iframe url to allow for query string param check.
To check just the iframe URL change:
1. Visit http://calypso.localhost:3000
2. Edit a post
3. Open dev tools and inspect the editor's iframe
4. Confirm that there is no `editor-after-deprecation` query param in the iframe's URL
5. Add `?editor/after-deprecation` to the current URL and reload the page
6. Re-inspect the editor's iframe and confirm `editor-after-deprecation` query param present
While testing this you might want to test the WPCOM change D42788-code
1. Apply diff D42788 to your sandbox
2. Visit http://calypso.localhost:3000
3. Switch site to your sandbox
4. Edit a post and switch to block editor if needed
5. Open more tools menu from top right and confirm "Switch To …

Editor: Pass editor/after-deprecation feature flag to iframed editor

---

client/signup/config/steps-pure.js

* Adds `marketing_price_group` to oauth2 flows
* Go to crowdsignal.com -> Login -> Create WordPress account -> Verify the flow completes without errors in the console.
/cc @southp @CGastrell

Adds `marketing_price_group` dependency to oauth2 flows

---

client/landing/gutenboarding/onboarding-block/style-preview/preview.tsx

This PR proposes preloading all preview font pairings for a more seamless UX. People are likely to take a second and look around the page. It would be nice to have the fonts ready and get rid of the [FOUT](https://css-tricks.com/fout-foit-foft/) as shown here by p1589217382261500-slack-gutenboarding.
It's not enough to load the font in the browser cache. As even loading it from cache will still create a flash of fonts. It has to be in memory for it to appear. That's why this can't be solved by a service worker, `<link rel=preload"...` etc. I tried the preload way and the flash persisted. 
Go to the font picker, switch between fonts and the fonts should change once per click. Not `Previous font -> default font -> new font`.
I tested in Chrome, FF, and Safari.
The whole preview page will …

Preload all preview iframe font pairings

---

client/my-sites/customer-home/cards/tasks/go-mobile/index.js

We can get widows with the GoMobile task content on some phones, like the iPhone X. This PR tidies that up.
Before | After
--- | --- 
* Use devtools to load a site's My Home with an iOS or Android UA (you can use the Device Toolbar to select a device on either platform).
* Dismiss your tasks so that the Go Mobile card is displayed.
* Verify there are no widows in English in any content. Check with other devices.

My Home: Prevent widows in the Go Mobile task.

---

client/landing/gutenboarding/components/signup-form/index.tsx
client/landing/gutenboarding/components/signup-form/style.scss

This PR prevents zooming in on mobile when a user taps one of the signup input fields, and also sets the autocomplete attribute on the password field.
* Increase font size in input text fields in signup in Gutenboarding to 16px on mobile to prevent zooming in iOS
* Keep placeholder font sizes to 14px to match the design
* Add `autocomplete` setting of `new-password` to the password field to encourage browsers the support it to automatically generate a password
* Go to `/new` on an iOS device while signed out
* Complete the flow until you get to the signup form
* Enter any email address and an automatically generated password should be suggested for you
* Tap on the password field, and the browser should _not_ zoom in
* Test the signup form on desktop — it should work normally and the …

Gutenboarding: Increase size of input text size to avoid zooming in on iOS

---

client/landing/jetpack-cloud/sections/scan/main.tsx

Currently we show when the scan started but not when it finished. 
This PR fixes this by adding the duration to the scan started time
* On a site that has scan start a scan. 
* Does the scan time make sense?

Jetpack Scan: Fix timestamp to include duration

---

client/my-sites/site-settings/jetpack-credentials/credentials-configured/index.jsx
client/my-sites/site-settings/settings-security/main.jsx

* Currently for sites with managed credentials, no card is displayed in Settings -> Security to show that credentials have been provided. This PR ensures that card is shown as intended.
* Create a site with managed credentials (e.g., a Pressable site).
* Ensure Jetpack is installed and connected.
* Purchase a Jetpack plan, or Jetpack Backup, or Jetpack Scan.
* On WordPress.com, select this site in the site selector and go to Settings -> Security.
* Verify that you see a folded card saying that the site is connected, as shown in the screenshot below. The card should have an arrow at the end of it, which should be **horizontal**, not vertical. Clicking the arrow should bring up a prompt to revoke your credentials or stay connected.
Fixes #42112 / 1156570014567299-as-1175436329289321.

Credentials Card: Show folded card in Settings for sites with managed credentials

---

client/landing/gutenboarding/components/plans/plans-button/index.tsx
client/landing/gutenboarding/components/plans/plans-modal/index.tsx
client/landing/gutenboarding/hooks/use-selected-plan.ts
client/landing/gutenboarding/lib/analytics/index.ts
client/landing/gutenboarding/lib/analytics/types.ts
client/landing/gutenboarding/onboarding-block/acquire-intent/index.tsx
client/landing/gutenboarding/onboarding-block/acquire-intent/site-title.tsx
client/landing/gutenboarding/onboarding-block/acquire-intent/style.scss
client/landing/gutenboarding/onboarding-block/acquire-intent/vertical-select/index.tsx
client/landing/gutenboarding/stores/onboard/selectors.ts
client/signup/controller.js

* Add tracking for vertical input when moving the focus out of the field or selecting a vertical.
- `selected_vertical_slug` - The slug of the selected topic, defined only when the vertical is not free-form user input.
- `selected_vertical_label` - Translated label of vertical or free-form user input.
* Add tracking for site title input when moving the focus out of the field.
- `has_selected_site_title` - Whether site title has been entered on the acquire intent page.
* Add tracking for skipped vertical or site title inputs.
* Update `calypso_newsite_step_leave` event for IntentGathering step:
* add `selected_vertical_label` prop which can be free-form user input.
* change `selected_vertical` prop to `selected_vertical_slug` recording the same value as before
* change …

Gutenboarding: Add new tracking events

---

client/landing/jetpack-cloud/components/fix-all-threats-dialog/index.tsx
client/landing/jetpack-cloud/components/fix-all-threats-dialog/style.scss
client/landing/jetpack-cloud/components/threat-dialog/style.scss

* Make the buttons sections look the same (modal width, background color, buttons positioning, labels)
* Make the threats container scrollable
- Now the `<Dialog/>` manages how buttons are rendered (we pass them as a prop to the component as we do in the other modals).
- Is the scrollable container a good pattern for this? If yes, how can we make it obvious that it's scrollable? Currently, it doesn't look like it is.
* Select a site with as many threats you have [1]
* Go to Scan -> Scanner
* Click the `[Fix all]` button
* On another tab, go to the same section a click on any threat the `[Fix threat]` button
* Verify they both look the same (modal width, background color, buttons positioning, and labels)
* Verify the threats section is …

Jetpack Cloud: fix inconsistencies between modals

---

client/landing/jetpack-cloud/components/log-item/index.tsx
client/landing/jetpack-cloud/components/scan-threats/index.tsx
client/landing/jetpack-cloud/components/threat-item/index.tsx

* Remove the line break in the error copy.
* Make the button transparent.
* Make the whole header clickable.
* Select a site that has Scan and at least one threat
* From React devtools, find the `ScanThreats` component and set the `error` prop to `true` (that will make the error section appear below the threats section)
* Verify there is no longer line break (`<br />`) in the copy.
* Verify the `scan again` link/button has a transparent background
* Verify you can expand/open a threat from clicking anywhere in its header
* Verify clicking the `[Fix threat]` button opens up the modal but doesn't expand/open the threat element

Jetpack Cloud: improve the threats an error UI

---

client/landing/jetpack-cloud/components/upsell/index.tsx
client/landing/jetpack-cloud/sections/scan/upsell.jsx
client/state/data-layer/wpcom/sites/scan/index.js

* The current upsell state doesn't know about that multisite is not supported. 
* This PR fixes it by showing a more meaningful message and hiding the Upgrade now button. 
Before:
After:
* On a site multisite navigate to /scan section. Notice a message telling you that your site is not supported. 
* On a site without a plan notice the regular upsell component.

Jetpack Cloud: Add upsell state showing multisite is not supported

---

client/landing/jetpack-cloud/sections/backups/rewind-flow/index.tsx
client/landing/jetpack-cloud/sections/backups/rewind-flow/style.scss
client/landing/jetpack-cloud/sections/backups/style.scss
client/landing/jetpack-cloud/style.scss

Remove a margin-top between the masterbar and the content, visible on Backup section and it was introduced in a previous [PR](https://github.com/Automattic/wp-calypso/pull/41675). Add the correct margin-top to the Download/Restore section.
Before
Now:
https://calypso.live/?branch=fix/jetpack-cloud-backup-section-margin-top&env=jetpack
- Check if the margin-top on Backup section disappeared
- Check the Download/Restore view by clicking on Download or Restore button, and check if they have the expected margin:

JP Cloud: Fix a margin-top with the masterbar

---

client/landing/gutenboarding/onboarding-block/acquire-intent/index.tsx
client/landing/gutenboarding/onboarding-block/acquire-intent/style.scss
client/landing/gutenboarding/onboarding-block/acquire-intent/vertical-select/index.tsx
client/landing/gutenboarding/onboarding-block/acquire-intent/vertical-select/style.scss

As reported in https://github.com/Automattic/wp-calypso/issues/41923, because we're using `contenteditable` instead of an `input` field in the intent gathering steps, the browser default behaviour in iOS of opening the keyboard and moving the viewport so that the field is in the correct position, is not happening.
This PR is a workaround to keep the text in the intent gathering steps at the top of the screen on mobile, to see if that improves the UX when using Gutenboarding from a phone.
* Remove `margin-top: auto` so that the two sub-steps (vertical selection and site title) sit at the top of the page on mobile.
* Add "scroll to top" when `isSiteTitleActive` changes (when a user submits a vertical).
* In the site title wrap the arrow and `siteTitleInput` in a div so that they naturally …

Gutenboarding: Move intent gathering text to top of screen on mobile

---

client/my-sites/plans/current-plan/jetpack-checklist/index.tsx

* This updates the onboarding checklist to specify VaultPress instead of a more generic phrase, to avoid confusion with Jetpack Backup and Scan product.
* Set up a Jetpack site with a plan with VaultPress.
* Go to Plan > My Plan.
* Toggle the prop `vaultpressFinished` on the `JetpackChecklist` component and observe results.
Screenshots:
Fixes 1143508703416848-as-1174921179573827.

Updates wording of onboarding to specify VaultPress

---

apps/full-site-editing/full-site-editing-plugin/premium-content/blocks/container/edit.js

* "Logged Out View" is now "Non-Subscriber View"
Start the things
```
cd apps/full-site-editing
yarn dev
wp-env start
```
Open WordPress in the browser
```
open http://localhost:`cat .wp-env.json | jq .port`/wp-admin/post-new.php
```
Sign in with `admin`/`admin` or whatever you may have changed the password to.
Add a Premium Content block and observe the updated tab name:
Fixes #42049

Premium Content: Change tab name to "Non-Subscriber View"

---

client/lib/products-values/constants.js

* This rearranges the product listing to show it as Backup, Scan, and Search. Currently it is Backup, Search, and Scan.
* On a Jetpack site, go to Plan > Plans.
Fixes 1151678672052943-as-1174896175986483.

Changes order of product display

---

client/my-sites/customer-home/cards/tasks/site-setup-list/index.jsx
client/my-sites/customer-home/cards/tasks/site-setup-list/style.scss
client/my-sites/customer-home/cards/tasks/style.scss
client/my-sites/customer-home/cards/tasks/task.jsx

Adjust the styles used on My Home tasks so their content is better distributed. It also replaces the `ActionPanel` components with divs since we were overriding most of the styles, so they are now easier to maintain at the same time that we decrease a little bit the bundle size.
* Padding has been adjusted to be 24px in all sides.
Task | Before | After
--- | --- | ---
Site setup | ![image](https://user-images.githubusercontent.com/1233880/81818661-9d668f80-952e-11ea-93ec-4e92945ecb53.png) | ![image](https://user-images.githubusercontent.com/1233880/81818676-a192ad00-952e-11ea-89bd-ba24874ca6c5.png)
Classic editor deprecation | ![image](https://user-images.githubusercontent.com/1233880/81818722-ae170580-952e-11ea-856b-3e3552fc7243.png) | …

My Home: Tweak tasks styles

---

client/landing/gutenboarding/components/domain-picker/index.tsx
client/landing/gutenboarding/index.tsx
client/landing/gutenboarding/onboarding-block/acquire-intent/site-title.tsx
client/landing/gutenboarding/onboarding-block/acquire-intent/vertical-select/index.tsx

Adds Hotjar.com tracking to Gutenboarding.
We'll set up the actual tracking by `/new/*` URLs so here we just need to load the script.
* Add Hotjar script
* Whitelist a few inputs (https://help.hotjar.com/hc/en-us/articles/115015563287-Whitelisting-input-fields)
- In the console, set `localStorage.debug='calypso:analytics:hotjar'`
- Load `/new` and you should see this in console:
- In the network tab, you should see Hotjar script load once.
- Once you progress in Gutenboarding, the script goes away when you enter the editor.
- Confirm text inputs in Gutenboarding are whitelisted for Hotjar: 
- Vertical input, site name input, the domain name input
- I'm not sure if whitelisting matters for `contentEditable` fields actually, but it doesn't hurt to add these in case.
If these don't load, you …

Gutenboarding: add Hotjar

---

client/signup/controller.js

This PR adds an exception so all the onboarding flows about domains are not redirected to gutenboarding, even if the user is part of the test.
how to test:
========
0. Go to https://hash-a6db1f673be2f6d6c42691a6ca30c25eef48f75e.calypso.live
1. Make yourself part of the test (in the browser console, paste this `localStorage.setItem( 'ABTests', { "newSiteGutenbergOnboarding_20200501": "gutenberg" } )` )
2. Go to https://hash-a6db1f673be2f6d6c42691a6ca30c25eef48f75e.calypso.live/domains?site=domain-only . You shouldn't be redirected to the new flow

Gutenboarding: allow the domain-only legacy flow

---

client/me/help/help-teaser-button.jsx
client/me/help/main.jsx

* The `Courses` link from `/help` should open up the webinars page in a new tab.

Update the link on the help page to point to the webinars page.

---

apps/wpcom-block-editor/src/calypso/features/gutenboarding-editor-overrides.js

Fix the Publish button selector. 
1. In your sandbox, run `./bin/calypso/build-wpcom-block-editor.sh 728970`. This will copy the build files from Circle CI to your sandbox. 
3. Sandbox widgets.wp.com
4. The problem should disappear. 
Fixes https://github.com/Automattic/wp-calypso/issues/42084

wpcom-block-editor: fix Publish button selector

---

client/landing/gutenboarding/components/domain-picker-button/index.tsx
client/landing/gutenboarding/components/domain-picker-button/style.scss
client/landing/gutenboarding/components/header/index.tsx
client/landing/gutenboarding/components/header/style.scss

This PR brings support for domain names of any length (by ellipsing them) + slide out animation for any all breakpoints.
Previously, the issues on the domain picker button are:
- Mobile view has ellipsis but doesn't have the slide out animation.
- Non-mobile view doesn't have ellipsis (and layout may break in certain medium width viewport) but has the slide out animation.
* Test with long domains, resize browser window, refresh to see if slides out nicely.
Testing in all viewport width.
Animation on mobile viewport.
Fixes https://github.com/Automattic/wp-calypso/pull/42040#pullrequestreview-409132739
Related https://github.com/Automattic/wp-calypso/issues/42123 https://github.com/Automattic/wp-calypso/issues/41851

Gutenboarding: Fix responsive & animation issues on domain picker button.

---

client/landing/gutenboarding/components/signup-form/index.tsx
client/landing/gutenboarding/components/signup-form/style.scss
client/landing/gutenboarding/lib/analytics/index.ts
client/landing/gutenboarding/lib/analytics/recaptcha.ts
packages/data-stores/src/user/types.ts

Add reCAPTCHA to Gutenboarding signup form, with the same behaviour as found in the legacy signup flow at `/start`.
This uses the [reCAPTCHA "invisible" badge](https://developers.google.com/recaptcha/docs/versions#recaptcha_v2_invisible_recaptcha_badge) on desktop viewports, and paragraph text on mobile.
* Add reCAPTCHA code from Calypso to Gutenboarding, with minimal types (this isn't DRY, but I assume it's preferable to importing the existing code directly from Calypso)
* Add reCAPTCHA to signup form
* Tweak the signup form styling a little bit to include the text-based reCAPTCHA TOS notice, make the links grey and bring back the underline to get a bit closer to the designs.
* Re-use the same signup action name as is used in /start: `'calypso/signup/formSubmit'`
Note: the signup form …

Gutenboarding: Add reCAPTCHA to signup form

---

client/landing/jetpack-cloud/sections/scan/main.tsx
client/landing/jetpack-cloud/sections/scan/upsell.jsx

Removes the Stats footer plugin for now until we come up with something better. 
Before:
After:
* Go to the scanner page.
* Notice that the stats footer is gone.

Remove the stats footer component

---

client/landing/jetpack-cloud/sections/scan/history/index.jsx

Currently the Jetpack Scan history show placeholders everytime someone navigates to the section because everytime we fetch the latest history threats. This PR fixes this by showing threats that are already there if we have them.
It also fixes a case where the we hide the filters when no things to filter are there. 
* Go the /history section for a site that doesn't have any igored fixes. 
* Does it work as expected?

Jetpack Cloud: Fix history loading

---

client/landing/jetpack-cloud/components/backup-delta/index.jsx
client/landing/jetpack-cloud/sections/backups/main.jsx

On the backup status view, for the days other than today the copy "More backups from today" should be "More backups from this day"
The expected copy for today:
The expected copy for any other day:
- Check the expected copy for each one. You can change your timezone to match one where you can see "More backups from today"

JP Cloud: Add the new copy "More backups from this day"

---

client/landing/gutenboarding/onboarding-block/style-preview/preview.tsx

* Whitelist style preview iframe for HotJar recordings
https://help.hotjar.com/hc/en-us/articles/115011624347-Can-I-track-iframes-inside-Recordings-
- Style preview still works :-)
- The rest are hot jars

Gutenboarding: allow Hotjar to record style preview iframe

---

client/landing/gutenboarding/onboarding-block/acquire-intent/style.scss
client/landing/gutenboarding/onboarding-block/acquire-intent/vertical-select/style.scss

You can spend just 1min reviewing this :-)
* Adds text cursor to intent capture placeholder inputs, making it tad bit more clear that user can start typing in them
In vertical input(green area, animated text) would already have text-cursor, but now also rest of the area (orange area) has it:
Same treatment for title placeholder:
* in `/new`, hover intent capture inputs while you don't have focus in the inputs and they're empty

Gutenboarding: use text cursor in intent capture placeholders

---

config/horizon.json
config/production.json
config/stage.json

* We're enabling the enhanced domain navigation in production.
Related PRs:
https://github.com/Automattic/wp-calypso/pull/40737
https://github.com/Automattic/wp-calypso/pull/40811
https://github.com/Automattic/wp-calypso/pull/41019
https://github.com/Automattic/wp-calypso/pull/41023
https://github.com/Automattic/wp-calypso/pull/41297
https://github.com/Automattic/wp-calypso/pull/41452
https://github.com/Automattic/wp-calypso/pull/41494
https://github.com/Automattic/wp-calypso/pull/41643
https://github.com/Automattic/wp-calypso/pull/41743
* Just verify that in the production env you see the new navigation when you open a registered/mapped domain

Enable the new domain navigation in production

---

client/lib/purchases/index.js
client/lib/purchases/test/index.js
client/me/purchases/manage-purchase/index.jsx
client/me/purchases/manage-purchase/notices.jsx
client/me/purchases/manage-purchase/notices.scss
client/me/purchases/upcoming-renewals/style.scss
client/me/purchases/upcoming-renewals/test/upcoming-renewals-dialog.tsx
client/me/purchases/upcoming-renewals/upcoming-renewals-dialog.tsx
client/state/purchases/selectors.js
config/development.json
packages/format-currency/package.json
packages/format-currency/types/index.d.ts

* Adds a new Notice to the Manage Purchase page that will be displayed when other upgrades from the same site are available for renewal.
* Inside the new notice, a new dialog can be opened that will display the detail of each available renewal, the user will be able to select which ones they one to proceed with.
* Adds type definitions to format-currency
* Design discussion: pbOQVh-9b-p2
* Go to a site that has multiple purchases expiring soon (within the next 3 months) or that are already expired and still renewable. (Turn auto-renew off to make sure they are marked as "expiring").
* Go to Manage Purchases and open any of the purchases that are expiring soon.
* You should see the new notice telling you that there are other products also expiring.
* Click "renew all" inside the notice to …

Manage Purchase: Add notice to inform about available products for renewal

---

client/landing/jetpack-cloud/components/activity-card-list/index.jsx
client/landing/jetpack-cloud/components/activity-card-list/style.scss
client/landing/jetpack-cloud/components/activity-card/activity-card-streams-media-preview.tsx
client/landing/jetpack-cloud/components/activity-card/index.jsx
client/landing/jetpack-cloud/components/activity-card/style.scss

* Hide all "links" in Activity Card Toolbars except for stream expansion
* Only show actions on rewindable activities
* Add Multi-Image Preview for Media Activities with Streams
* Add Stream Expansion for non-Media Activities with Streams
* Fix console error ( React Keys ) when expanding Stream content
1. Navigate to `/backups/activity` for a site with Real-Time Backups
2. Verify that actions are gone from non-rewindable actions like logins
3. Verify the "changes in this backup" links are gone from Backup Activities
4. Test Stream expansion for non-Media types

Jetpack Cloud: Refine ActivityCard

---

config/horizon.json
config/stage.json

* Enables the experimentation platform on staging and horizon.
1. `yarn test-client` should pass.
2. Merging should be OK in staging, as it's not enabled in production.
3. Use production API, staging wpcom, and non a11n user.
4. Validate everything works correctly.

Turn on Experimentation Platform in staging/horizon

---

client/landing/jetpack-cloud/sections/scan/style.scss

* Adjust the margin for the **Retry scan** button so that it's centered for small-layout screens, and the space between buttons on mobile matches our style guide.
Fixes **1151678672052943-as-1175652872237329**.
* Open Jetpack Cloud for a site with Scan.
* Simulate or otherwise produce an error state on the **Scanner** page.
* Verify that buttons are placed as in the screenshots below, and that on mobile layouts, the **Retry scan** button is horizontally centered on the page.

Jetpack Cloud: Center 'Retry scan' button and reduce margin on mobile

---

client/landing/jetpack-cloud/sections/backups/style.scss

On desktop views, it shows unexpected scrollbars :
This update ensures that the overflow-y is active only for mobile view and in the Backup section.
- Check on a desktop view (an example: Setting section), you don't see the scrollbars

Fix overflow-y issue in desktop views

---

client/landing/jetpack-cloud/components/activity-card/activity-description.tsx
client/landing/jetpack-cloud/components/activity-card/index.jsx

* Copy `ActivityDescription` into new Jetpack Cloud component
* Remove any links from cards that go to `WordPress.com`
1. Navigate the Activity Log, making sure there are no broken links

Jetpack Cloud: Remove Broken Activity Card Links 

---

client/landing/jetpack-cloud/components/activity-card-list/style.scss
client/landing/jetpack-cloud/components/activity-card/style.scss

* Reduce size of Activity Card with various style tweaks
1. Check Activity Cards on `backups/activity`
2. Check Activity Cards on `backups` for a real-time backup day with activity

Jetpack Cloud: Reduce Activity Card Size

---

client/components/product-card/style.scss
client/jetpack-connect/plans-grid.jsx
client/jetpack-connect/plans.jsx
client/jetpack-connect/style.scss
client/jetpack-connect/test/__snapshots__/plans.js.snap
client/lib/abtest/active-tests.js

For backstory, see p1HpG7-8PX-p2.
* Adds an AB test that removes the personal plan from the Jetpack Connect plans grid shown after a user connects.
- Checkout this patch locally
- Start Calypso locally
- Create JN site
- Connect JN site
- After connecting the site, you should land on the plans grid. Replace `wordpress.com` in the URL with `calypso.localhost:3000`
- Ensure that you can force the variation with the following:
- `localStorage.setItem( 'ABTests', '{"jpcPlansOfferResetPersonal_20200513":"withPersonal"}' );`
- `localStorage.setItem( 'ABTests', '{"jpcPlansOfferResetPersonal_20200513":"withoutPersonal"}' );`
- After several minutes, view tracks events for your WP.com user and ensure that you see an event named `calypso_abtest_start` with an `abtest_name` property value of …

Jetpack: Test removal of personal plan as part of offer reset project

---

client/landing/gutenboarding/onboarding-block/acquire-intent/site-title.tsx
client/landing/gutenboarding/onboarding-block/acquire-intent/style.scss
client/landing/gutenboarding/onboarding-block/acquire-intent/vertical-select/index.tsx
client/landing/gutenboarding/onboarding-block/acquire-intent/vertical-select/style.scss

This is a small PR to get the cursor to show when the contenteditable fields in intent gathering in Gutenboarding are focused. This will hopefully help these fields to feel more like real editable fields on iOS.
* Ensure that the `.madlib__input` class when empty still has a width and height to ensure that the cursor flashes in mobile Safari
* Caret color matches the color of the text when the input has value and has default highlight color when empty.
* Placeholder grey line and coloured line when the user enters a value are in the same position, fixing the jumpy behaviour: https://cloudup.com/cRc12ecdjzH
**Caret color on iOS before:**
**Caret color on iOS after:**
* Empty field
* With value
* On a real iPhone go to `/new` and select the vertical input field. You should see the cursor …

Gutenboarding: Ensure empty fields in intent gathering show flashing cursor on iOS

---

client/components/domains/domain-product-price/index.jsx
client/components/domains/domain-registration-suggestion/index.jsx
client/components/domains/domain-search-results/index.jsx
client/components/domains/domain-suggestion/index.jsx
client/components/domains/featured-domain-suggestions/index.jsx
client/components/domains/free-domain-explainer/index.jsx
client/components/domains/register-domain-step/index.jsx
client/components/domains/register-domain-step/style.scss
client/lib/abtest/active-tests.js
client/lib/signup/step-actions/index.js
client/signup/config/flows-pure.js
client/signup/config/steps-pure.js
client/signup/config/steps.js
client/signup/steps/domains/index.jsx

Check pbxNRc-cj-p2/#comment-277 for context.
* This is a follow up to the test launched in https://github.com/Automattic/wp-calypso/pull/40879 that swaps the domain and plan step. The following changes are introduced:
- If a user in the variant group selects a paid plan, then don't show the domain step.
- If a user in the variant group selects a free plan, then show only the domain price without any "free with a paid plan text". Take them to checkout directly with only a domain in cart.
**Paid plan selected -> directly take to checkout with no domain step**
**Free plan selected -> show domain price -> directly take to. checkout with only domain in cart**
**Scenario 1**
* Proxy through a US IP address and begin the signup flow at /start.
* If you are in _variantShowSwapped_ of the …

Domain-plan-swap test: Don't show domain step if paid plan selected

---

client/landing/gutenboarding/available-designs.ts

This PR should update the design sort order to highlight blogs, followed by portfolio designs, followed by simple single-page designs.
Fixes #42221

Gutenboarding: Update design sort order

---

client/landing/gutenboarding/onboarding-block/plans/index.tsx
client/landing/gutenboarding/onboarding-block/style-preview/index.tsx
client/landing/gutenboarding/stores/onboard/actions.ts
client/landing/gutenboarding/stores/onboard/index.ts
client/landing/gutenboarding/stores/onboard/reducer.ts
client/lib/abtest/active-tests.js

Check for a selected plan to determine whether to show the plans grid. 
This doesn't yet take into account whether:
- a user has already seen the plans page, in which case we could allow it to be shown
Enter the `/new` flow and carry on without selecting a plan. You should see the plans page.
Enter the `/new` flow and select a paid domain. You should see the plans page.
Enter the `/new` flow and select a plan from the modal. You should NOT see the plans page.
Fixes #42218

Gutenboarding: Check for a selected plan to determine whether to show the plans grid

---

docs/monorepo.md

Running `lerna publish` without `npx` will throw "transpile script not found" error.

Docs: Update monorepo.md

---

client/landing/gutenboarding/components/plans/plans-details/index.tsx
client/landing/gutenboarding/components/plans/plans-details/style.scss
client/landing/gutenboarding/components/plans/plans-grid/index.tsx
client/landing/gutenboarding/components/plans/plans-grid/style.scss
client/landing/gutenboarding/components/plans/variables.scss
client/landing/gutenboarding/functions.scss
client/landing/gutenboarding/mixins.scss

**Note: This PR is branched off `fix/gutenboarding-plans-table-scrolling-ux`. See PR: https://github.com/Automattic/wp-calypso/pull/42118 for more details.**
**On Desktop**
* Use browser's horizontal scrollbar to scroll plans details.
* Plans details & more/less toggle button should have the same min width as plans table.
**On Mobile**
* Localized scrolling now supports edge-to-edge scrolling for all viewport sizes (test with portrait/landscape modes).
**On Both**
* Fix toggle button stealing focus causing user having to scroll back up to read the plans details.
* Note: This only fixes the first time user toggles the plans details. Subsequent toggling is currently a non-fix (it has to do with window scroll position) and should be looked into when adding slidedown effect.
Test the 4 points …

Gutenboarding: Plans details scrolling UX improvements.

---

client/landing/gutenboarding/_z-index.scss
client/landing/gutenboarding/components/action-buttons/style.scss
client/landing/gutenboarding/components/header/style.scss
client/landing/gutenboarding/components/plans/plans-details/index.tsx
client/landing/gutenboarding/components/plans/plans-details/style.scss
client/landing/gutenboarding/components/plans/plans-grid/index.tsx
client/landing/gutenboarding/components/plans/plans-grid/style.scss
client/landing/gutenboarding/components/plans/plans-table/style.scss
client/landing/gutenboarding/components/plans/variables.scss
client/landing/gutenboarding/functions.scss
client/landing/gutenboarding/mixins.scss
client/landing/gutenboarding/variables.scss

We seem to refer to the main plans table as the grid itself, but I just like to point out the technical differences just to make any further discussion clearer.
**Plans Grid** - The view containing the plans table & plans details.
**Plans Table** - The main table containing a summary of plans.
**Plans Details** - The extended table containing detailed comparison of plans.
**Plan Item** - Each of the column in plans table.
The current plans table hinders user experience for desktop users with narrow browser viewport as user has to scroll down to the end of the plans table to find the horizontal scrollbar then scroll left or right to inspect different plans.
In this PR, here are my proposals on how to fix this:
- **Desktop**
When plan items overflow, let user scroll using the browser's …

Gutenboarding: Plans table scrolling UX improvements.

---

client/landing/gutenboarding/available-designs.ts

Move Bowen design to be the last.
A follow-up to today's design re-ordering: https://github.com/Automattic/wp-calypso/pull/42237
cc @ianstewart 
This is due header being sub-optimal in the underlying theme "Coutoire", as it floats over the content as users scrolls on page:
See issue https://github.com/Automattic/themes/issues/1901

Gutenborading: move Bowen design to be the last in grid

---

client/landing/gutenboarding/components/header/index.tsx

* Added the calypso_newsite_select_domain event when a new domain name has been selected. (when clicking confirm on the modal)
* Navigate to /new
* Open the domain picker
* Select a domain
*  Press Confirm on the domain picker dialog
* A calypso_newsite_select_domain event should be fired

Gutenboarding: add select_domain event

---

docs/dependency-management.md

Updating the Dependency Management docs with a guide to adding an unpublished package as a dependency. This information can be useful as `yarn` does not resolve by default to a local dependency unless its exact version is specified. Please see [this comment](https://github.com/Automattic/wp-calypso/pull/41990#issuecomment-626758995) for more context.

Docs: Add "unpublished package as a dependency" guide

---

client/landing/jetpack-cloud/components/daily-backup-status/style.scss

* Replace now non-existent breakpoint mixing with breakpoint-deprecated
Verify Jetpack Cloud can boot in dev mode

Jetpack Cloud: The Last Breakpoint

---

client/components/domains/registrant-extra-info/ca-form.jsx
client/lib/wpcom-undocumented/lib/undocumented.js
client/my-sites/checkout/composite-checkout/composite-checkout.js
client/my-sites/checkout/composite-checkout/wpcom/components/wp-checkout.js
client/my-sites/checkout/composite-checkout/wpcom/components/wp-contact-form.js
client/my-sites/checkout/composite-checkout/wpcom/test/wpcom-store-state.ts
client/my-sites/checkout/composite-checkout/wpcom/types/backend/domain-contact-details-components.ts
client/my-sites/checkout/composite-checkout/wpcom/types/backend/domain-contact-validation-endpoint.ts
client/my-sites/checkout/composite-checkout/wpcom/types/wpcom-store-state.ts

This is the final PR to be broken out of #40482.
* Include the extra ccTLD-specific contact forms in composite checkout.
This PR only touches composite checkout, so should be easier to test.
For all cases really jerk test the validation especially -- there are a lot of invisible changes in how that works that were merged in previous patches but are only effective with this one.
- Run local calypso with `ENABLE_FEATURES=composite-checkout-force yarn start` to force composite checkout.
- Enter checkout with one of the following TLDs in your cart: (1) .ca, (2) .uk, (3) .fr. At the contact details step you should see extra form fields depending on which TLD you have.
Enter checkout with two or more of the above listed TLDs. You should see extra fields for each TLD.
- Enter checkout with a …

composite-checkout: Add ccTLD contact forms

---

apps/full-site-editing/full-site-editing-plugin/premium-content/blocks/container/edit.js
apps/full-site-editing/full-site-editing-plugin/premium-content/style.css

* Add Notice on successful plan creation (Premium Content Block).
* In the Block editor, add a recurring payment plan using the premium content block.  Succesful creation will show a notice.
Fixes #42048

Premium Content Block: Add success message on plan creation

---

client/landing/jetpack-cloud/components/scan-threats/index.tsx
client/landing/jetpack-cloud/components/scan-threats/style.scss
client/landing/jetpack-cloud/components/threat-item/index.tsx

* Add copy and a button to the bottom of the "threats found" page to allow the user to run a scan manually.
* Add copy to unfixable threat descriptions to inform the user they can run a manual scan after resolving the threat manually.
Fixes `1151678672052943-as-1175836339721209`.
Thinking out loud: would it make sense to move `dispatchScanRun` to a constant in file scope, since we're using it in two places now? If I recall, `dispatch` is guaranteed to be constant, but I'm not as certain about the dependency on `site.ID`.
* **Prerequisite:** have a site with Scan enabled and no pre-existing threats.
* **Note**: check styling in both mobile and desktop layouts.
* Create a threat that is unfixable (e.g., add the EICAR string to a plugin).
* Click **Scan now** and wait for the results.
* …

Jetpack Cloud: Allow user to manually re-run a scan after threats are found

---

client/landing/jetpack-cloud/sections/backups/rewind-flow/download.tsx

* In the case that we cannot know if a user requested a download use slightly different language
1. Pick a Backup to Download from `/backups`
2. Navigate through the steps without reloading the page
3. Verify the copy matches the "before" screenshot above
4. Reload the page
5. Verify the copy matches the "after" screenshot above

Jetpack Cloud: Change copy wording if user did not request backup download

---

client/my-sites/checkout/composite-checkout/record-analytics.js
packages/composite-checkout/src/components/checkout-steps.js

Composite checkout currently records a Tracks and Logstash event when its React Error Boundaries are hit. One of these errors is when a step has an error, and it records the error message in both of those places. However, it would be helpful to know which step had the error, so this changes the code such that it records the step ID as well.
- Modify the code to cause a fatal error inside a step. For example, add `throw new Error('testing')` inside `WPContactForm`.
- Load composite checkout and verify that the broken step is not shown and instead you see the error boundary with a brief message.
- Verify that the Tracks event `calypso_checkout_composite_step_load_error` contains both the error message and the step ID.
- Verify that the Logstash event contains both the error message and the …

composite-checkout: Record the step ID when recording a step load error

---

client/landing/jetpack-cloud/sections/backups/rewind-flow/restore.tsx

* Change wording on Restore Success Screen
Restore a site and verify it matches the above screenshot

Jetpack Cloud: Restore items, not files

---

client/lib/site/timezone.js

* Allow `0` gmtOffset to modify moment in `applySiteOffset`
1. Navigate to `/activity-log` for a Jetpack site with a `UTC+0` timezone setting
2. Verify that the activity dates are now in site time

Fix Zero GMT Offset Using Local Time Instead

---

client/signup/controller.js

* Added the `calypso_site_launch_start` event when the launch button is clicked after following the gutenboarding flow. This had to be done on the page after `launch` because the `launch` button is managed by the `wpcom-block-editor` app
* [ x ] Go through the existing signup flow from `/start`
* The `calypso_site_launch_start` event should not be triggered at any point 
* [ x ] Go through `/new` with a free domain
* Click the `Launch` button
* the `calypso_site_launch_start` event is triggered and you will be on the domain select page.
* [ x ] Go through `/new` with a paid domain
* Click on the `Launch` button
* the `calypso_site_launch_start` event is triggered and you will be on the domain select page.

add launch_site event immediately after the launch button is clicked

---

client/landing/gutenboarding/lib/analytics/index.ts

In this PR we're firing `calypso_signup_start|complete` events at the same time as our  `calypso_newsite_start|complete` events.
See pbmFJ6-95-p2 for context
Head over to the branch and to `/new` 
Filter your network traffic in the browser's console to check if both `calypso_signup_start` and `calypso_newsite_start` are called with the same props.
Complete the signup flow.
Check if both `calypso_signup_complete` and `calypso_newsite_complete` are called with the same props.

Gutenboarding: add `calypso_signup_start|complete` events

---

client/lib/plans/plans-list.js

This PR changes the plan labels to use sentence case. See #40107 for rationale.
* Visit `/plans/mysite.wordpress.com`
* Confirm that all of the plan "Best for..." labels use sentence case.
Fixes #40107.

Plans: Use sentence case for plan labels.

---

client/blocks/login/social.jsx

This was added in #42135 and didn't fix the issue as expected. It is no
longer needed.
* Remove test code for adding redirect_to param to social logins
* Test Google sign in works
* Test SSR of `/log-in` still works (#42135 broke it)
* Disable JS in dev tools
* `/log-in` should show a disabled log in form
* ***After deployment to staging*** test Apple sign in works

Gutenboarding: Remove forwarding of login page's own redirect_to param to social logins

---

client/landing/gutenboarding/hooks/use-on-site-creation.ts
client/landing/gutenboarding/lib/analytics/index.ts
client/landing/gutenboarding/lib/analytics/types.ts

This PR records a Gutenboarding flow complete tracking event (`calypso_newsite_complete`) **before** we redirect a user to the checkout, signalling that the Gutenboarding site creation is complete
We're doing this because the user never returns to any Gutenboarding step after checkout. 
This PR also adds a `has_cart_items` prop to the complete event, which features in the current `calypso_signup_complete` event.
Test over at `/new` with and without a paid plan. 
`calypso_newsite_complete` should fire once your site is complete. If you have something in your cart `has_cart_items` should be true.
Fixes part of https://github.com/Automattic/wp-calypso/issues/42311

Gutenboarding: track flow complete before checkout

---

client/my-sites/sidebar/index.jsx

Fixes https://github.com/Automattic/wp-for-teams/issues/243
For now, we decided to hide the "Activity & Backups" in the sidebar as we don't have plans what to do with it yet for p2 sites (formerly WP for Teams).
Using a p2 site, verify that you can't see the "Activity & Backups" under the "Tools" sidebar menu. Verify you can see it with a normal WP.com site.

p2: hide activity&backup in sidebar

---

client/landing/jetpack-cloud/sections/backups/rewind-flow/error.tsx

* Adjust the `Contact support` button in the `RewindFlowError` component to match our requirement that all buttons use sentence casing (see `p9Jlb4-1ly-p2`).
Fixes `1151678672052943-as-1175116466690897`.
Verify that the "Contact support" button is sentence-cased in all places by checking the following:
* Simulate an error state on the "Download backup" page
* Simulate an error state on the "Restore to this point" page
* Simulate trying to download or restore from a non-rewindable activity ID
* Simulate trying to download or restore from a non-existent activity ID

Jetpack Cloud: Make all buttons use sentence case

---

client/landing/jetpack-cloud/components/activity-card-list/index.jsx
client/landing/jetpack-cloud/components/activity-card/index.jsx
client/landing/jetpack-cloud/components/backup-delta/index.jsx
client/landing/jetpack-cloud/components/daily-backup-status/index.jsx
client/landing/jetpack-cloud/sections/backups/main.jsx
client/lib/site/timezone.js
client/state/selectors/get-allow-restore.js

* use `withApplySiteOffset` to make sure ActivityCards get everything they need to show the correct site times
* Simplify ActivityCard components to require fewer properties
* Add `getAllowRestore` selector
Navigate the Activity Log and Daily and Real-Time backups Backup Statuses to make sure nothing has changes

Jetpack Cloud: Refine Activity Cards

---

client/lib/wpcom-undocumented/lib/undocumented.js
client/my-sites/checkout/checkout/domain-details-form.jsx

This modifies `wpcom.undocumented.validateGoogleAppsContactInformation()` so that it accepts an array of domain names which it will then send to the validation server. When combined with D43415-code, this will allow the validation to check if the GSuite email addresses are correctly not using the domain name to which they are connected.
This also fixes the function so it sends its data as POST data (rather than GET data) and allows it to return a Promise (as its documentation suggests it might do).
This was extracted from the changes in #41705
- Apply D43415-code
- Visit old checkout (not composite checkout) with GSuite items in your cart, but without a domain in your cart (your site must already have a domain for this to work).
- Try entering invalid data into the fields or leaving them …

Refactor validateGoogleAppsContactInformation to accept domain names

---

client/landing/jetpack-cloud/sections/scan/main.tsx

* Adds better text for the `provisioning` state.
* Removes `unavailable` state as the `ScanUpsell` component covers it.
* On a site with Scan, alter the scan state to be `provisioning`.
Fixes 1151678672052943-as-1175196271951194.

Updates Scan page wording for states

---

client/my-sites/checkout/composite-checkout/test/composite-checkout.js
client/my-sites/checkout/composite-checkout/wpcom/components/wp-checkout-order-summary.js
client/my-sites/checkout/composite-checkout/wpcom/components/wp-checkout.js
client/my-sites/checkout/composite-checkout/wpcom/hooks/has-domains.js
client/my-sites/checkout/composite-checkout/wpcom/hooks/has-plan.js

Depending on the items in a user's cart, the features in the CheckoutSummary need to be updated.
- Domains should be bolded at the top, with a conditional "free with plan" bundle message
- Live Chat is only available with plans, email-only for all other products
- If the cart only has a plan in it, we offer a 30 day money back guarantee. If it only has a domain, the guarantee is 4 days. Any other combination should say "money back guarantee". (More detailed information about refund policies is available in the support link directly below the features, and as part of the terms of service the user agrees to before making a purchase)
**To Test:**
- from a free site, visit checkout with a domain only
- verify that the domain is displayed first without a bundled message, the support item is …

Checkout: add dynamic summary features (3)

---

client/landing/jetpack-cloud/sections/settings/main.jsx

* On the Settings page, the copy for 'Find your credentials' has been revised to match feedback from our call for testing (see `p1HpG7-9a5#comment-39218`).
Fixes `1169345694087188-as-1175858234531553`
* Prerequisite: have (or create) a Jetpack site with no saved server credentials.
* Navigate to the Settings page on Jetpack Cloud for that site
* Verify that you see the 'not connected' banner, and that the link to find your credentials says `Need some help? Find your server credentials`

Jetpack Cloud: Revise 'find your credentials' copy on settings page

---

client/me/memberships/main.jsx
client/me/memberships/subscription.jsx

* Fix UI to handle one-time payments for lifetime subscriptions (available on Longreads).
The issue is that the UI on calypso is expecting an active subscription to have an end date and a renewal interval. For users that signed up for a lifetime subscription, there is no end date or renewal interval and when the UI looks like this;
[](https://cdn-std.droplr.net/files/acc_854234/Azd4J0)
* Use SSP with the account user ID - 1114877
* Go to http://calypso.localhost:3000/me/purchases/other
* Verify the UI makes sense
* Click on the subscription to bring you to http://calypso.localhost:3000/me/purchases/other/19561319
* Verify the UI makes sense

Recurring Payments: Fix lifetime subscription UI

---

client/my-sites/earn/ads/form-settings.jsx
client/my-sites/earn/ads/style.scss

* Adds configuration settings for California Consumer Privacy Act (CCPA) for WordAds sites
* Create or choose a WordAds enabled site on a Premium or Personal plan
* Navigate to the Ads Dashboard -> Settings screen
* Verify you can enable/disable the CCPA option
* Verify you can enter/remove the site privacy policy URL

WordAds: Add configuration settings for California Consumer Privacy Act (CCPA)

---

client/landing/gutenboarding/onboarding-block/acquire-intent/vertical-select/index.tsx

* Fire vertical selection events only when user selects a new vertical.
* Go to /new
* Enable tracks debugging
* When refreshing the page or when clearing the existing vertical value `calypso_newsite_vertical_selected` event should not be fired.
* When selecting a new vertical the event should fire as before.
Fixes p1589809679209900-slack-gutenboarding

Gutenboarding: fire vertical selection events correctly

---

client/my-sites/checkout/composite-checkout/composite-checkout.js
client/my-sites/checkout/composite-checkout/payment-method-processors.js
client/my-sites/checkout/composite-checkout/use-create-payment-methods.js
packages/composite-checkout/src/lib/payment-methods/full-credits.js

This updates the `full-credits` payment method to use the payment processor function system added in #41767 
- Attempt a purchase using composite checkout when you have sufficient credits to cover the entire transaction.
- Verify that the transaction completes successfully.

composite-checkout: Convert full credits payment method to use processor function

---

client/blocks/login/index.jsx
client/login/magic-login/handle-emailed-link-form.jsx
client/state/login/actions/index.js
client/state/login/actions/reboot-after-login.ts

* Refactor `rebootAfterLogin()` component method to redux action
This fixes a `@TODO` to share this code between the login block and magic link form.
But more importantly it fixes redirecting to the correct place if the user is signing in with Apple. The broken flow goes like this:
1. When the user clicks "Sign in with Apple" we [stash the `redirect_to` param in session storage](https://github.com/Automattic/wp-calypso/blob/5076a5b0355409a4aedb8df28262fa05d3b414c0/client/blocks/login/social.jsx#L176)
2. After the user successfully logs in with apple, we [read the redirect url out of session storage](https://github.com/Automattic/wp-calypso/blob/5076a5b0355409a4aedb8df28262fa05d3b414c0/client/blocks/login/social.jsx#L124) and [fire a `loginSocialUser` …

Login: Honour `redirect_to` param after returning from Sign-in with Apple flow

---

client/my-sites/customer-home/cards/notices/celebrate-site-launch/index.jsx

Makes sure we use the right card UID when the site setup is completed after launching a site and the site setup complete notice is dismissed. Missed in #42331

My Home: Update missing notice id

---

client/lib/domains/index.js

* There are several occasions where users managed to map a domain with leading/trailing dot in them and that required support to help fix that. This PR strips leading/trailing dots from the domain input.
* Try to purchase mapped domain with leading or trailing dot in it - you should always get a trimmed version of the domain in the cart.

Trim dots from domain name when mapping/transferring domain

---

client/lib/wpcom-undocumented/lib/undocumented.js
client/state/sharing/keyring/test/actions.js
packages/wpcom.js/src/lib/me.js
packages/wpcom.js/src/lib/me.keyring-connection.js

* This replaces calls to /me/keyring-connections to /me/connections a new version of the same endpoint.
* Check that you can create/delete connections at /marketing/connections
* Check that you can still access your Google Photos from the Media Library
* Check that the Google My Business flow still works (/marketing/tools)
I this we'll need to update the wpcom.js package.
Fixes #41601

Update the API calls for keyring connections

---

client/state/lasagna/post-channel/middleware.js

In certain unload conditions, certain posts, that return empty `getSite` against Redux state, can induce a TypeError.
* Guard against Reader situations where `site` does not exist during unload.
On `master`:
1. Load an RSS only post in the Reader full view post.
2. Hard refresh it.
3. Click "Reader" in the nav at the top left a couple times.
You should see a `TypeError` in your browser console.
Now do the same on this branch.
You show see normal loads as you'd expect.

Lasagna: fix middleware topic TypeError

---

client/me/sidebar/index.jsx
client/my-sites/controller.js
client/my-sites/domains/index.js
client/my-sites/domains/paths.js
client/sections.js
config/stage.json

* This PR introduces the `/me/domains` route and make sure it works properly and no the bundle size is not affected. I believe we should be able to merge this as it's just changing the route and some other small details. Since it's feature flagged we can continue working on the rest of the routes in separate PRs.
I'm reusing the old feature flag `manage/all-domains`
Here's how the menu looks:
* Open your account and check the "Domains" menu or just go to /me/domains - it should show the old "all domains screen" as of now but this is just

Add /me/domains list routes

---

client/components/domains/registrant-extra-info/ca-form.jsx
client/my-sites/checkout/checkout-system-decider.js

As a follow-up to #41819, we can now allow ccTLDs that require special contact forms through to Composite Checkout. This PR enables that.
- Add a `.fr`, `.ca`, or `.co.uk` domain to your cart and visit checkout.
- Add `?flags=composite-checkout-testing` to the checkout URL.
- Verify you see composite checkout.

Allow TLDs with special contact forms through CheckoutSystemDecider

---

client/landing/jetpack-cloud/components/with-server-credentials-form/index.jsx

* Reset the form state every time the selected site has changed.
* Prerequisite: have at least two sites available to choose from
* Select any site from the site selector
* Go to Settings
* Verify the form is completed with the right information (server address, port number, server username, etc.)
* Go to the site selector and choose another site
* Verify the form information has been updated and matches the new selected site information
Fixes 1169345694087188-as-1173222819931609

Jetpack Cloud: reset server credentials form state on selected site change

---

client/my-sites/customer-home/cards/tasks/task.jsx

Currently, passing a custom action button to the `Task` component will not fire our task-specific stats. This PR wraps any custom `actionButton` component with the same click handler we use when given the standard action-related props.
The only task using the `actionButton` component so far is the Go Mobile task.
* Load this branch and go to My Home for a simple site.
* Open devtools and toggle the Device Bar.
* Enable stats logging by entering `localStorage.debug='calypso:analytics*'` in the console, and refresh the page (they should be showing in the log now).
* Select an iOS device and reload.
* Click the "Download on the App Store" button. Verify that Tracks stats fired for `calypso_customer_home_task_start` with `task: "home-task-go-mobile-ios"` props, and bump stats fired for …

My Home: Add task analytics for custom action buttons.

---

client/my-sites/plans/main.jsx
client/signup/steps/plans/index.jsx

* For the users in price test 2, move the popular badge to Business instead of Premium.
More info: pbBQWj-7J-p2#comment-555
* Boot this branch locally.
* Sandbox `public-api.wordpress.com`.
* On the backend, add this filter to your `0-sandbox.php` file:
```
add_filter( 'get_user_marketing_price_group', function( $price_group ) {
return 'price_2020_q2_test_2';
}, 10, 1 );
```
* Visit http://calypso.localhost:3000/plans/[SITE]
* Make sure you see the popular badge on the Business plan instead of Premium.
* Go through the flow to create a new site.
* On the plans step make sure you also see the popular badge on the Business plan.

Price test: show popular badge on Business plan for test 2 group

---

client/my-sites/pages/page/index.js

Let's remove the author field from the page exports JSON. It reveals identifying information such as email addresses, IDs and pant sizes.
At wordpress.com/pages/yoursweetsite, click the `...` menu next to a page and export that page.
In the JSON you just downloaded, you should see no trace of an `author` property.

Page export: Removing the author field 

---

client/signup/controller.js

* Forwards all query params from `/start` to `/new`
In particular this forwards the `ref` query param so we know what campaign the user came from. But I think it's worth forwarding everything in case we want to use it in the future.
* Replaces `/start` in the browser history with `/new`
Fixed this while I was here. If the user went to `/start` and was allocated to gutenboarding, then if they hit the back button in their browser they'd go back to `/start` again, only to be bounced back to gutenboarding. Which breaks the back button. By replacing `/start` in the history the user now goes back to what feels like the last page they were looking at.
* Assign yourself to the gutenboarding cohort
* Go to `/start?site_type=blog&vertical=food&ref=dotblog-landing`
(this is the link users would …

Gutenboarding: forward ref prop to gutenboarding

---

client/landing/gutenboarding/components/domain-picker-button/index.tsx
client/landing/gutenboarding/components/domain-picker-modal/index.tsx
client/landing/gutenboarding/components/domain-picker-popover/index.tsx
client/landing/gutenboarding/components/domain-picker/index.tsx

* Use a different `name` property for the domain picker popover and modal when sending `calypso_newsite_modal_*` events
The popover and modal being indistinguishable in events means we couldn't see how many people are asking for the advanced domain options during signup, making the open event for the modal pointless.
Heads up to @johnHackworth who owns all the funnels using these events.
* Filter the network tab for `calypso_newsite_modal_` events
* `/new`
* Use the domain picker popover and click the "more options" button in various orders.
* Check network tab for the correct open and close events

Gutenboarding: Domain popover and modal events are distinguishable in tracks

---

client/landing/jetpack-cloud/components/activity-card/style.scss

Fix left alignment and margins on Activity Card with a media stream.
- In a RT-Backup site, go to a date with media stream upload (small images) and check if the images are aligned to the left.

Fix left alignment and margins on Activity Card with media stream

---

client/my-sites/checkout/composite-checkout/wpcom/test/wpcom-store-state.ts
client/my-sites/checkout/composite-checkout/wpcom/types/backend/domain-contact-validation-endpoint.ts
client/my-sites/checkout/composite-checkout/wpcom/types/wpcom-store-state.ts

The `client/my-sites/checkout/composite-checkout/wpcom/types/wpcom-store-state.ts` file contains several Typescript errors involving the manage contact details it manipulates. This PR attempts to resolve those issues and fix any bugs that they predict.
This will require checking the contact details forms for domain, TLDs with special contact forms, and the GSuite contact form to make sure they work as expected. They should be able to be shown and edited correctly, as well as validated correctly.
```
yarn run test-client client/my-sites/checkout/composite-checkout/wpcom/test/wpcom-store-state.ts
```

composite-checkout: Clean up type errors

---

client/components/product-card/style.scss
client/jetpack-connect/plans-grid.jsx
client/jetpack-connect/plans.jsx
client/jetpack-connect/style.scss
client/jetpack-connect/test/__snapshots__/plans.js.snap
client/lib/abtest/active-tests.js

Reverts Automattic/wp-calypso#42177
While still a bit early, we're going to cancel this AB test for now as it has caused a negative impact on conversion and revenue. There are some other factors involved though, so we're not sure about how much impact there was. We hope that cancelling the test will help us get an idea of how much impact this test had itself.
See the post at p1HpG7-8Qm-p2 for more details. 
- Checkout this patch locally
- Start Calypso locally
- Create JN site
- Connect JN site
- After connecting the site, you should land on the plans grid. Replace `wordpress.com` in the URL with `calypso.localhost:3000`
- Ensure that after loading the connection view, that you see personal, premium, and professional plans

Revert "Jetpack: Test removal of personal plan as part of offer reset project"

---

apps/full-site-editing/full-site-editing-plugin/premium-content/blocks/logged-out-view/index.js
apps/full-site-editing/full-site-editing-plugin/premium-content/blocks/subscriber-view/index.js

* Remove the "Edit as HTML" options for the inner blocks of the Premium Content Block.
* Start up the FSE environment and create a premium content block.
* Under the "Non-subscriber View", click the Subscribe button.
* Click the kabob menu (i.e. More options/horizontal dots/ellipses) and verify that the "Edit as HTML" option has been removed.
Fixes #41834

Premium Content Block: disable "Edit as HTML" option

---

client/landing/jetpack-cloud/sections/settings/main.jsx
config/jetpack-cloud-development.json
config/jetpack-cloud-production.json
config/jetpack-cloud-stage.json

* Make it possible for users to log out from Jetpack Cloud.
This is a WIP. While we wait for the dropdown design for the log out button, I added the button in the settings section.
For the mean time, the current implementation does a client side session clean up. In other words, this doesn't log the user out from WP.com.
* What information should we track and how should we name the event?
* Where should we redirect the user to?
* Select any site
* Go to the Settings section
* Click the `[Log out]` button
* Verify you are no longer authenticated (WP.com requires you to log in)
Fixes # 1169345694087188-as-1174701142489163

Jetpack Cloud: add log out flow

---

client/landing/gutenboarding/gutenboard.tsx
client/landing/gutenboarding/hooks/use-page-view-tracks-events.ts

* Record `calypso_page_view` events when user navigates in gutenboarding
I added the hook for this high up in the React tree because
1. I don't want the component that does the recording to be re-mounted, otherwise there'll be a double recording of the event
2. It's recording changes for the entire react-router context, so I think it should be pretty close to `<BrowserRouter>` in the component tree.
The old signup framework (`/start`) also adds the flow name as an event property but I decided not to do that here. We aren't trying to differentiate between any different gutenboarding flows here. But I can add it if folks disagree.
* Open network tab and filter for `calypso_page_view`
* Go to `/new`
* Navigate around gutenboarding
* Inspect the events properties, they should look similar to …

Gutenboarding: Record `calypso_page_view` events in gutenboarding

---

apps/wpcom-block-editor/src/calypso/features/gutenboarding-editor-overrides.js

Create a site with Gutenboarding at `/new`
Now try to create and publish a new post or page. 
You can't, can you?
Do you see this?
It's because we're manipulating the buttons in the editor's header, specifically the text node in the publish button.
Let's not replace the text node as React does not like it at all. I'm not sure of the mechanism behind the error, but the page fails when React attempt to unmount components. It's looking for a precise node tree it appears.
props to @ianstewart for finding this bug and giving us something do 
Code to patch in D43745-code

Gutenboarding: remove save text node override in the block editor

---

client/jetpack-connect/controller.js
client/lib/products-values/constants.js

Since we are introducing Jetpack Scan realtime eventually. 
This PR updates calypso to use Jetpack Scan Daily instead of the current Jetpack Scan. 
Updated Screenshots
1. Apply this PR. 
2. but Jetpack Scan Daily. 
3. Notice that on the Plans Page, My Plan as well as the plan manage page shows Jetpack Scan Daily.

Jetpack Scan: Update Jepack Scan to Jetpack Scan Daily

---

client/components/domains/register-domain-step/index.jsx

* Update RegisterDomainStep to prevent crashing when trying to launch a site after a site change.
* Login to an account with at least 2 unlaunched sites. Sometimes the behaviour explained in #42515 is causing the launch flow to crash.
* Launching a site after switching to a new site should always work.
Fixes #42515
Unblocks #42513

Fix site launch flow after switching to a new site

---

apps/full-site-editing/full-site-editing-plugin/premium-content/premium-content-dom.php

Ensures the content of any premium content block is correctly decoded using the UTF-8 charset, so non-single byte UTF-8 characters are displayed correctly
Before | After
--- | ---
* Apply D43708-code, and sandbox the API and a testing site (make sure your sandbox doesn't have any FSE build in `plugins/full-site-editing-plugin/dev`, otherwise changes in D43708-code won't take effect).
* Set up a recurring payment plan on the testing site using the testing store. More info in PCYsg-lW4-p2 #sandbox-method.
* Create a post and insert a premium content block.
* Add some content that includes non-single byte UTF-8 characters such as emojis (🙂👾), accented characters (áèñôü) or chinese/japanese characters (漢字). 
* Make sure you add those characters in both the subscriber and non-subscriber views. …

Premium content: Decode UTF-8 characters

---

client/lib/abtest/active-tests.js
client/lib/domains/suggestions/index.js
client/signup/steps/domains/index.jsx

* Set up an A/B test to allow us to measure the impact of promoting `.jp` domains to users.
The actual test will only launch once we can support the TLD. Furthermore, this test depends on corresponding changes to the domain suggestions back end in D43045-code.
More context in https://wp.me/pbxNRc-hA
This needs to be tested in conjunction with D43045-code, which includes fairly extensive testing instructions.

Implement A/B test for showing `.jp` domains to users in Japan

---

client/landing/jetpack-cloud/sections/settings/main.jsx
client/landing/jetpack-cloud/sections/settings/style.scss

* On the Settings page, put server connection details inside a foldable card element with no background or border, per design documents (see referenced task).
* When Backup/Scan are **connected**, connection details are **hidden/folded** by default.
* When Backup/Scan are **not** connected, connection details are **shown/unfolded** by default.
Fixes `1169345694087188-as-1174867022546268`
* Prerequisite: have a Jetpack site with Backup/Scan, either connected or disconnected.
* For connected sites:
* On Jetpack Cloud, select the connected site.
* Go to Settings.
* As the page loads, observe placeholders for the connection status **and the connection details form.**
* When the page loads, a foldable card should display (as **collapsed**) with a transparent background, no border, and the …

Jetpack Cloud: Improve/collapse server creds form when connected

---

client/lib/products-values/index.js
client/my-sites/plans/current-plan/my-plan-card/style.scss
client/my-sites/plans/current-plan/purchases-listing.jsx

* This adds the capability for additional buttons for Scan and Backup to link to the Cloud.
* Navigate to Plan > My Plan page on a site with Scan or Backup purchased.
* Click relevant links.
Product Management
Plan Management
Fixes 1143508703416848-as-1164157450632305.

Adds additional product actions for Scan and Backup

---

client/landing/gutenboarding/components/header/index.tsx

* Show "Pick a domain" when user haven't entered site title and haven't decided on a domain.
* Go to `/new`
* Click "Skip for now".
* Domain picker button's label should be "Pick a domain".
* Open up domain picker, select a domain and click Confirm.
* Domain picker button's label should be the selected domain name.
Fixes #42524

Gutenboarding: Show "Pick a domain" when user haven't entered site title and haven't decided on a domain.

---

client/me/purchases/upcoming-renewals/test/upcoming-renewals-dialog.tsx
client/me/purchases/upcoming-renewals/upcoming-renewals-dialog.tsx
client/my-sites/checkout/cart/upcoming-renewals-reminder.tsx

*  In the upcoming renewals dialog, use the renew date if the product is autorenewing to determine the correct display order.
* Display a different message for autorenewing products in the checkout page:
* Make sure composite-checkout is enabled for your account (You may add the flag via URL using ?flags=+composite-checkout-force,+upgrades/upcoming-renewals-notices)
* Go to a site that has multiple purchases (at least 2) expiring soon (within the next 3 months). Turn on auto-renew for one of them and disable it in the rest.
* Go to Manage Purchases and open one of the purchases that has auto-renew off.
* Click in the "other purchases" link inside the notice, when the dialog opens, make sure all the purchases are ordered correctly by renew or expiration time, respectively,
* Select all the …

Purchases: Use correct dates for autorenewing products in upcoming renewals notices

---

client/my-sites/marketing/connections/service-action.jsx
client/my-sites/marketing/connections/service-connected-accounts.jsx
client/my-sites/marketing/connections/service.jsx
client/my-sites/marketing/connections/services/instagram.jsx
client/my-sites/marketing/style.scss
client/state/selectors/get-removable-connections.js
client/state/selectors/test/get-removable-connections.js

* Add proper support for multiple connections for the Instagram service. 
* Update the "Disconnect" button label to also cover non-Publicize services with multiple connections (e.g. Instagram).
Working on the new Latest Instagram Posts block, we eventually decided to support multiple Instagram accounts.
This is supported out of the box by Keyring, but the Marketing Connections page is not as thorough for non-Publicize connections.
While it showed all the connections, and let you disconnect them one by one, it also had some quirks:
- The "Disconnect" button label should have been "Disconnect All".
- Clicking on "Disconnect (All)" for the Instagram service should have deleted all connections, while instead it only deleted the most recent.
- The Instagram service didn't have a "Connect a …

Marketing Connections: Properly support for multiple Instagram accounts

---

client/landing/jetpack-cloud/components/with-server-credentials-form/index.jsx
client/landing/jetpack-cloud/components/with-server-credentials-form/test/index.js

* Pre-filling the server credentials form with rewind state stop working as expected which later broke a unit test. This PR improves the server credentials form and simplifies the unit test suite.
* Checkout this PR locally
* Run `yarn test-client:watch client/landing/jetpack-cloud/components/with-server-credentials-form/test/index.js`
* Verify the 5 tests pass
* Run this PR
* Select any site
* Perform regression test on the Settings section to verify everything works as before
Fixes #42394

Jetpack Cloud: fix server credentials form broken unit test

---

client/blocks/all-sites/index.jsx
client/state/sites/actions.js
config/jetpack-cloud-development.json
config/jetpack-cloud-production.json
config/jetpack-cloud-stage.json

* Add config option to count the number of sites available instead of using the value on the user info
* Use the new config option for Jetpack Cloud
**!!! Because this PR involves config changes you must stop and restart the build !!!**
1. Boot Jetpack Cloud and navigate to any page with any site
2. Click "Switch Site" and confirm the count matches the actual amount of sites available
3. Boot default Calypso and navigate to any page with any site
4. Click "Switch Site" and confirm the count matches production ( WordPress.com )

Jetpack Cloud: Use Actual Sites for Site Count 

---

client/lib/purchases/index.js
client/me/purchases/manage-purchase/index.jsx
client/me/purchases/manage-purchase/notices.jsx
client/me/purchases/purchase-item/index.jsx
client/state/purchases/selectors.js

Following up on https://github.com/Automattic/wp-calypso/pull/42076, which introduced a new feature (behind a feature flag) to show information on the manage purchase pages about other purchases on the same site in some cases where they are expiring soon, this pull requests adds more comprehensive notifications (including for purchases that are auto-renewing soon also), and ensures that the message always shows pertinent information about the current purchase too, when appropriate.
The basic goal is that when viewing one purchase, users always have a way of getting information about (and taking action on) other purchases on the same site that expire or renew soon.
See also internal discussion here: pbOQVh-bC-p2
The pull request handles many cases (too many to list all here) but here are a …

Manage Purchase: Expand the notices that inform about available products for renewal

---

client/blocks/reader-combined-card/index.jsx
client/blocks/reader-combined-card/post.jsx
client/blocks/reader-full-post/index.jsx
client/blocks/reader-post-card/index.jsx
client/blocks/reader-post-options-menu/index.jsx
client/reader/following/main.jsx
client/state/data-layer/wpcom/seen-posts/seen/all/delete/index.js
client/state/data-layer/wpcom/seen-posts/seen/all/new/index.js
client/state/data-layer/wpcom/seen-posts/seen/delete/index.js
client/state/data-layer/wpcom/seen-posts/seen/new/index.js
client/state/reader/posts/reducer.js
client/state/reader/seen-posts/actions.js
client/state/reader/seen-posts/reducer.js

**Built on top of https://github.com/Automattic/wp-calypso/pull/42153**
- Add `Mark as Seen` button to posts in Following
- Add `Mark as Unseen` button to posts in Following and highlight seen posts
- Add `Mark All as Seen` button to combined posts in Following
- Add `Mark All as Unseen` button to combined posts in Following
- Add `Mark All as Seen` button to Following section
**Known limitations**
- Seen data is persisted in cache for one hour, until we finalize the storage strategy
- When a section is "Mark all as Unseen" seen entries are not removed on refresh
More context: `p9lV3a-1jk-p2`
- Apply `D43321-code`
- Test "Mark as Seen/Unseen" for posts in Following
- Test "Mark All as Seen/Unseen" for Following Section, it should hide the section Bubble
- Open an unseen post from …

Add mark as seen/unseen

---

config/wpcalypso.json

This pull request enables the upcoming renewal notifications feature (added in previous pull requests such as https://github.com/Automattic/wp-calypso/pull/42076, https://github.com/Automattic/wp-calypso/pull/42240, and https://github.com/Automattic/wp-calypso/pull/42506) in the `wpcalypso` environment for testing purposes.

Turn on upcoming renewal notifications in the wpcalypso environment

---

client/landing/gutenboarding/components/signup-form/index.tsx

After checking the latest signup error ids in tracks, this commit adds handlers for some of the outliers. 
We want to return decent messaging to the frontend so the user has a hint of what is going on.
Some you won't be able to trigger as I can't find a reliable string. Just checking that signup works as expected and you get error messages for common errors, e.g., email exists,  emails from a banned domain, e.g., `asdasd.ru`, email invalid and so on.

Gutenboarding: extend our signup error messages

---

apps/wpcom-block-editor/src/calypso/features/gutenboarding-editor-overrides.scss

This PR adjusts the styling of the publish button in the block editor for sites created via Gutenboarding.
* Update CSS selectors so that the publish button in the slide out panel is _not_ overridden, and the publish button in the editor settings bar _is_ overridden.
Publish button in editor settings bar:
Publish button in slide-out sidebar:
Publish button in editor settings bar looks more like a link:
Publish button in slide-out sidebar is a big blue button:
Sandbox: D43817-code (a build of this PR)
* Go to `/new` and create a new site via Gutenboarding
* Do not launch the site
* Exit the editor and go to add a new post or page
* Note that the publish button in the editor settings bar at the top of the screen should be in the tertiary style (look like a link instead of a primary button) …

Gutenboarding: Update tertiary styling for publish button in editor

---

client/assets/stylesheets/shared/functions/_z-index.scss
client/my-sites/earn/memberships/products.jsx
client/my-sites/earn/memberships/style.scss
client/state/data-layer/wpcom/sites/memberships/index.js

Adds support for configuring through the Calypso UI the email settings of a Recurring Payment plan introduced in D43690-code.
* Set up Recurring Payments on a site using the testing store. More info in PCYsg-lW4-p2 #sandbox-method.
* Go to Tools > Earn > Collect recurring payments > Recurring Payments plans.
* Add or edit an existing recurring payment plan.
* Make sure the dialog displays a tab navigation menu.
* Make sure the "General" section displays the same form we currently show in production.
* Make sure the "Email" section displays a form for configuring the email settings.
* Enable the "Posts via email" checkbox.
* Enter some content in the "Custom confirmation message".
* Click on "Save".
* Publish a new post that contains a Premium Content block using the plan you saved above. …

Recurring Payments: Display email settings

---

client/landing/gutenboarding/components/plans/plans-button/index.tsx

Closes #42523
Replace "Free Plan" with "View plans" when no plan is selected.
Before
After
* [`/new`](https://calypso.live/new?branch=gutenboarding/42524-plans-copy)
* Go through the flow and ensure the plans button text is correct when a paid/free plan is selected or a domain has been selected.

Gutenboarding: Show "View plans" when free selected

---

client/landing/gutenboarding/components/plans/plans-modal/index.tsx

When no explicit change in the Plans Modal was made, when closing the modal by pressing _Confirm_ button the current selection isn't saved.
Demo: https://cloudup.com/cFW1u_wYljx
This PR is fixing this.
* Use _Confirm_ button to save whatever plan is displayed as current Plan.
* Open Plans modal when _View Plans_ label is displayed on the Plans Button.
* After pressing _Confirm_ the plan button should display _Free Plan_. 
* Plan Button label shouldn't be changed indirectly anymore (eg: when picking a paid domain).
* Plan step should be skipped.
Fixes https://github.com/Automattic/wp-calypso/pull/42525#pullrequestreview-416282301

Gutenboarding: Handle confirm in PlansModal

---

client/landing/jetpack-cloud/components/scan-threats/style.scss

Fix the outline.
Before: 
After:
* Go to a site with threats on the scanner page you should see the link.

Jetpack Cloud: Add more specificity to the run-scan-button

---

client/landing/gutenboarding/components/domain-categories/index.tsx
client/landing/gutenboarding/components/domain-picker-button/index.tsx
client/landing/gutenboarding/components/domain-picker-button/style.scss
client/landing/gutenboarding/components/header/index.tsx
client/landing/gutenboarding/components/plans/plans-details/index.tsx
client/landing/gutenboarding/components/signup-form/header.tsx
client/landing/gutenboarding/onboarding-block/create-site/index.tsx
client/landing/gutenboarding/onboarding-block/style-preview/font-select.tsx
client/landing/gutenboarding/onboarding-block/style-preview/style.scss
client/package.json

Replace icons with `@wordpress/icons`.
after / before
after / before
before / after
after / before
after/before
after / before
* [`/new`](https://calypso.live/new?branch=gutenboarding/wp-icons)
* *Seven* updates to icons were made here. Confirm they're working as expected (see screenshots):
- General Header
- Create site header
- Signup header
- Domain picker
- Domain categories mobile dropdown
- Font selection mobile dropdown
- Plan details

Gutenboarding: Use @wordpress/icons

---

apps/full-site-editing/full-site-editing-plugin/premium-content/subscription-service/class-wpcom-offline-subscription-service.php

* This updates the logic used when determining what paywal/subscription service to use when rendering content.
The logic currently checks to see if the request to render content is from a WPCOM source, using the define `IS_WPCOM`.
I don't think `IS_WPCOM` is set when jobs are running, which means that emails sent from jobs that should have premium content are not showing the premium content as the offline subscription service is appearing as not available.
For my tests I used the blog ID - 177049966 and post ID - 72
To make sure your test account will receive an email;
1. Go to https://eointestfse.wordpress.com/2020/05/21/a1/ and subscribe to the premium content
2. Also, follow the blog, making sure you are setup to receive new post emails instantly (check in manage subscriptions)
We need …

Update is available logic to only check if on WPCOM on API requests

---

client/landing/gutenboarding/available-designs.ts
client/landing/gutenboarding/components/badge/index.tsx
client/landing/gutenboarding/components/badge/style.scss
client/landing/gutenboarding/components/plans/plans-table/plan-item.tsx
client/landing/gutenboarding/components/plans/plans-table/style.scss
client/landing/gutenboarding/hooks/use-selected-plan.ts
client/landing/gutenboarding/lib/analytics/types.ts
client/landing/gutenboarding/onboarding-block/design-selector/index.tsx
client/landing/gutenboarding/onboarding-block/design-selector/style.scss
client/landing/gutenboarding/stores/onboard/selectors.ts
client/landing/gutenboarding/stores/onboard/types.ts
client/landing/gutenboarding/stores/plans/selectors.ts

Add premium designs flow in Gutenboarding.
- Note how title is in the middle, followed by the badge on the right
- Tooltip opens right-away (couldn't do, there's 700ms delay)
- Tooltip has space before badge (hence there's additional `min-height` in elements to achieve that)
- Tooltip is bottom+centered (couldn't do, tooltip seems to have its own life in this regard)
* Tag one of the designs as "premium"
* Show premium badge next to design name 
* When the premium design is selected, pre-select "premium" plan
- At Gutenboarding (start fresh with http://calypso.localhost:3000/new/?fresh)
- Confirm that selecting premium design chooses premium plan by default and that picking free design again goes back to free 
- Confirm that picking a paid domain does the same separately from design and …

Gutenborading: premium design flow

---

client/state/lasagna/post-channel/middleware.js

global_id is branched in ways that make it inappropriate for our use as a uid.
* Switch keying post channges from `global_id` to `post_id-blog_id` format.
1. Open a full view post in Calypso Reader.
2. Make a comment somewhere else on the same post.
3. You should see the comment pop into the page.
Ideally. do one for a WP.com blog and one for a JP blog.

Lasagna: switch to post id - blog id format

---

client/landing/gutenboarding/available-designs.ts
client/landing/gutenboarding/onboarding-block/acquire-intent/index.tsx
client/landing/gutenboarding/onboarding-block/design-selector/index.tsx

* Preload theme previews early on asynchronously for a better UX with no downside (that I could think of).
https://d.pr/v/R28xWF
https://d.pr/v/wsObfb
1. Go to /new
2. Name your site
3. Click "Choose design".
4. The screenshots should appear instantly.

Proposal: preload design thumbs for a nicer UX

---

client/lib/abtest/active-tests.js

This PR raises the ratio of users going through gutenboarding to 25% and adds Canada and Australia to the test.

Gutenboarding test: more users allocated to gutenboarding

---

client/landing/jetpack-cloud/components/sidebar/index.jsx

The Backup/Scan menu items in the sidebar shouldn't be translated, they are Jetpack product names.
**Asana:** 1169345694087188-as-1176670093007902
- Change the interface language to other different than English (https://wordpress.com/me/account), and then check that the menu items Backup and Scan aren't translated.

JP-Cloud: The Backup/Scan menu in the sidebar shouldn't be translated

---

client/my-sites/sidebar/index.jsx
client/my-sites/sidebar/test/sidebar.js

This branch adds in the `calypsoify=1` url param to the Store link on ecommerce plan sites. This ensures that when navigating to the Store feature, the calypsoify theme will always be loaded.
Using an ecommerce plan test site that has already completed the setup checklist on the remote AT site.
* Open up the home screen in calypso for the site, click on wp-admin in the sidebar. This will clear out the calypsoify option that is used to toggle the calypsoify theme off/on on the site.
* Go back to the wpcom homescreen for the site, click on the _Store_ link in the sidebar
* Verify you end up at `/wp-admin/edit.php?post_type=shop_order` and the Calypsoify theme is used:
Fixes #42296

Store: Add calypsoify param to ensure ecomm plan uses calypsoify.

---

client/my-sites/checkout/composite-checkout/record-analytics.js
client/my-sites/checkout/composite-checkout/wpcom/components/wp-checkout-order-summary.js
client/state/help/selectors.js
client/state/selectors/is-directly-failed.js
client/state/selectors/is-directly-ready.js
client/state/selectors/is-directly-uninitialized.js

In legacy Checkout, we allow "pre-sales" happy chat for users with a business or e-commerce plan in their cart. In new Checkout, we only allow chat in the checkout summary for users that have already purchased a plan. This allows for the same pre-sales chat when available.
**To test:**
Testing this is difficult, because it requires a chat to be available. You can check that the chat loads correctly by setting [`happyChatAvailable = true` here](https://github.com/Automattic/wp-calypso/compare/update/checkout-happiness-cta?expand=1#diff-1d892c5272ad36b273914f3c19b7a379R81) and [`isChatAvailable: true` here](https://github.com/Automattic/wp-calypso/blob/master/client/components/happychat/button.jsx#L110).
- if a chat is available and the user is either already eligible for chat support (via …

Checkout: use pre-sales chat button when available

---

client/my-sites/checkout/composite-checkout/wpcom/lib/translate-cart.ts
client/my-sites/checkout/composite-checkout/wpcom/test/translate-cart.js

* The "original price" display doesn't make sense for the credits line item. This PR sets it to the empty string.
Enter checkout with partial credits, and check that only the credit value is displayed in the line item (no crossed out "original price").
Note: the wonky minus sign is a separate issue.
```
yarn run test-client client/my-sites/checkout/composite-checkout/wpcom/test/translate-cart.js
```
Fixes #42168

composite-checkout: Do not show original price for credits line item (1)

---

apps/full-site-editing/full-site-editing-plugin/wpcom-block-editor-nav-sidebar/src/types.ts

Follow-up to https://github.com/Automattic/wp-calypso/pull/41703/files#r428944660.
`@wordpress/icons` comes [with typedefs included](https://github.com/WordPress/gutenberg/blob/16d1e41c3f3fe72446d00a2f25fbe34257ae1c48/packages/icons/CHANGELOG.md#new-feature) these days.
See #41703. (Do a `yarn distclean` first.)

FSE: Remove obsolete typedefs for @wordpress/icons

---

client/landing/gutenboarding/onboarding-block/acquire-intent/index.tsx
client/landing/gutenboarding/onboarding-block/acquire-intent/site-title.tsx
client/landing/gutenboarding/onboarding-block/acquire-intent/style.scss

* Position the next button immediately below input field on mobile for iOS users to find it easier.
* Always show skip button on mobile.
* Darken a bit the placeholder grey underline to be more visible.
* Reduce font-size on tablet / mobile landscape.
* Go to [/new](https://calypso.live/new?branch=update/intent-capture-next-button-position-mobile) on mobile.
* Tap the input and type some text.
* _Choose design_ button should be displayed on the right, immediately below the input.

Gutenboarding: update intent capture styles

---

client/landing/gutenboarding/components/plans/plans-button/index.tsx
client/landing/gutenboarding/components/plans/plans-button/style.scss

* When the users selects any plan, the button becomes blue.
* When a premium plan is selected by a side-effect (selecting a paid domain), the buttons should become blue.
By default, the button should have black text. If the user selects a plan it should become blue. If you refresh the page after selecting a plan, it should remain blue.

Highlight the plans button when user selects a plan

---

client/lib/abtest/active-tests.js

Gutenboarding: Slow down the test

---

client/reader/list-stream/README.md
client/reader/list-stream/header.jsx
client/reader/list-stream/index.jsx

When a user owns a existing  Reader list, they currently have the option to edit that list. The edit list page existed in our old Atlas/Newdash codebase and is no longer working. We are retiring the edit list feature until it is available in Calypso.
See p5PDj3-4Q5-p2.
Visit a Reader list that you own (if you don't have one, ask me for one to test). Verify that the 'cog' icon in the top right is gone.
Before:
After:

Reader: remove link to list editing

---

client/components/web-preview/toolbar.jsx
client/my-sites/customize/main.jsx
client/state/sites/selectors/get-customizer-url.js
client/state/sites/test/selectors.js

* The PR uses the `return` query parameter value to override the customizer back button.
* It validates the `return` query parameter against the API to ensure it's a valid URL to redirect to.
* Updates the fallback return path for the Customizer to be the customer home (if available).
Use case: https://github.com/Automattic/wp-calypso/pull/41854#issuecomment-632118363
Fire up the branch
Head to the editor and preview a post in the preview iframe
Click on Edit Header
Land on the customizer
Ensure that clicking the close button takes you back to the editor

Customizer: use return query param when available

---

client/my-sites/earn/memberships/products.jsx

Limits the max length of the Recurring payments' custom confirmation email messages to 2000 characters.
The "Save" button is disabled if the entered message exceeds the max length:
Note that "Save" button is now a primary button as per @sixhours's [suggestion](https://github.com/Automattic/wp-calypso/pull/42413#issuecomment-632307423).
* Set up Recurring Payments on a site using the testing store. More info in PCYsg-lW4-p2 #sandbox-method.
* Go to Tools > Earn > Collect recurring payments > Recurring Payments plans.
* Add or edit an existing recurring payment plan.
* Click on the Email tab.
* Make sure the "Custom confirmation message" field is limited to 2000 characters.
* Make sure the plan cannot be saved when the field exceeds the max length.
Part of #42536

Recurring payments: Limit welcome email content to 2000 characters

---

apps/full-site-editing/full-site-editing-plugin/premium-content/editor.css
apps/full-site-editing/full-site-editing-plugin/premium-content/premium-content.php
apps/full-site-editing/full-site-editing-plugin/premium-content/style.css

Currently when you activate the Full Site Editing plugin the style.css for the Premium Content Block gets loaded on ever page view.  This change adjusts it to only load on pages where that block is being used.
* Only load the Premium Content Block CSS when that block is in use
* Activate the FSE plugin
* Notice the Premium Content Block style.css being loaded on every page
* Apply patch
* Now style.css should only be loaded on pages that use the Premium Content Block
Fixes #

Only load Premium Block CSS when that block is being used

---

client/my-sites/domains/domain-management/edit/navigation/enhanced.jsx

This PR updates the privacy protection navigation item, to use on/off instead of yes/no to indicate whether privacy has been enabled for a domain.
For a registered domain you own which supports privacy protection (e.g. .blog), try enabling/disabling the privacy protection, and verify that on/off is shown accordingly.

Domains: Update privacy protection status copy

---

client/my-sites/site-settings/form-general.jsx

In German we need a different translation for the header but this appears in many other places, so we need to add a context:
cc @katinthehatsite

Site Settings: Add context to the Privacy header in Settings

---

client/landing/gutenboarding/available-designs.ts
client/landing/gutenboarding/onboarding-block/acquire-intent/index.tsx

In https://github.com/Automattic/wp-calypso/pull/42494, I implemented style preview preloading while the user is filling their site info. But I used 'preload' instead of 'prefetch'. While results in the previews loaded with higher prio; degrading the interim performance but still improving the style preview page performance.
Thanks @sgomes for catching my mistake.
Changing 'preload' to 'prefetch' is the achieves the desired results (best of both worlds). It loads the previews with low-prio while the user is filling their site name/vertical.
1. Open Chrome DevTools on the Network tab.
2. Navigate to [/new](https://calypso.live/new?branch=update/change-preload-to-prefetch).
3. The waterfall should look like this, the preview JPGs should be loaded **later**

Design previews: use prefetch instead of preload for better perf

---

client/my-sites/media-library/list-no-content.jsx
client/my-sites/post-type-list/empty-content.jsx

* Noticed a couple empty states where button labels were not sentence case. This PR updates the empty states for Posts and Media.
**Before**
**After**
* Switch to this PR on a site with no posts or media
* Visit Posts; note the change in button copy
* Visit Media; note the change in button copy

Posts & Media: Use sentence case button labels for empty states

---

client/landing/jetpack-cloud/components/masterbar/style.scss
client/landing/jetpack-cloud/sections/backups/backup-activity-log/index.tsx
client/landing/jetpack-cloud/sections/backups/backup-upsell/index.tsx
client/landing/jetpack-cloud/sections/scan/upsell.jsx

The Activity log section title should be translated. It fixes the translation problem in mobile views (small screens). Also, the title section when we are in "upselling" mode, should be the Jetpack product name Backup or Scan.
Before:
After:
Before (iPhone 5/SE):
After:
- Select a language non-English (Spanish)
- Go to Activity log section and check if the title is translated
- Go to Latest backups section and check if the title fits okay in the header (iPhone 5 mobile view)
- Switch to a site without Scan and Backup product, check if the title of the upsell view is the product name 'Backup' or 'Scan' instead of 'Backups' or 'Scanner'

Jetpack Cloud: fix issues of section titles (missing translation, mobile view)

---

client/landing/jetpack-cloud/components/masterbar/index.jsx
client/landing/jetpack-cloud/components/masterbar/style.scss
client/landing/jetpack-cloud/components/profile-dropdown/index.tsx
client/landing/jetpack-cloud/components/profile-dropdown/style.scss
client/landing/jetpack-cloud/sections/settings/main.jsx

* Move the log out functionality to the master bar. 
* Is "Log out of Jetpack Cloud" the right title for the avatar?
* Run this PR
* Select any site
* Click on the avatar on the top right corner of the screen (master bar)
* Verify the dropdown is closed when you press the Escape key
* Open the dropdown again
* Verify the dropdown is closed when you click outside of it
* Open the dropdown again and click Log out
* Verify you were logged out of the app
Fixes 1169345694087188-as-1176971703839350

Jetpack Cloud: move the log out functionality to the master bar

---

client/state/data-layer/wpcom-http/index.js

* conditionally attach on progress handler to prevent errors when wpcomXhrRequest has no `upload` property
* boot Jetpack Cloud and verify POST requests ( download, restore, scan now ) work

Fix On Progress Handler for XHR requests

---

config/horizon.json
config/production.json
config/stage.json

* This one is just turning on a feature flag for the new domain security screen on production
The actual PR that introduces the security screen is this one - https://github.com/Automattic/wp-calypso/pull/41643
* Verify that the security nav item and the security screen is shown for registered domains on production

Enable the new domains security screen on production

---

client/blocks/inline-help/contextual-help.js
client/lib/i18n-utils/test/utils.js
client/lib/i18n-utils/utils.js

Translate calls within contextual-help module were only called once with the declaration of the variable. Since we extend the translations table asynchronously with translation chunks, we need to re-evaluate contextual help objects in order to `translate` functions called again after required translations are loaded.
Before:
After:
* Keep contextual links in sync with i18n changes
1. Boot Calypso with `BUILD_TRANSLATION_CHUNKS=true ENABLE_FEATURES=use-translation-chunks,wpcom-bootstrap-user yarn start`
2. Confirm that contextual help links are properly translated and url are localized.

Update contextual help links when i18n changes

---

client/landing/jetpack-cloud/sections/scan/main.tsx

* Fixes incorrect wording in #42065.
* See #42065 for instructions.
Fixes 1169345694087188-as-1176944198537473.

Fixes incorrect wording

---

client/my-sites/marketing/traffic/index.js

Parent marketing page already has the document head component with the same title and having in both the main and traffic page was causing infinite set state loop when translate was firing a re-render, e.g. when community translator is being enabled.
* Remove unnecessary document head in marketing traffic page
* Boot Calypso
* Open http://calypso.localhost:3000/marketing/traffic
* Enable community translator and confirm it's not crashing the page

Remove unnecessary document head in marketing traffic page

---

client/landing/jetpack-cloud/components/fix-all-threats-dialog/index.tsx
client/landing/jetpack-cloud/components/server-credentials-form/index.jsx
client/landing/jetpack-cloud/components/server-credentials-wizard-dialog/index.tsx
client/landing/jetpack-cloud/components/threat-dialog/index.tsx
client/landing/jetpack-cloud/sections/scan/history/index.jsx

* Fix a bug that made the app ask for server credentials even when we had them. This happened when a user tried to fix a threat from the History section.
* Prerequisites: a site that has
* Jetpack Scan
* At least one fixable threat
* Server credentials
* Run this PR
* Select a site that fulfills prerequisites
* Go to Scan -> Scanner and ignore a fixable threat
* Go to History 
* Click `[Fix threat]` on the recently ignored threat
* Verify the app doesn't ask for server credentials
* Remove the server credentials (it can be done from WP.com)
* Refresh Jetpack Cloud
* Try to fix the same threat
* Verify you're asked for server credentials
Fixes 1169345694087188-as-1176908000483285

Jetpack Cloud: don't ask for server credentials when we have them (History section)

---

client/me/connected-applications/index.jsx
client/me/security-account-recovery/index.jsx
client/me/social-login/index.jsx
client/me/two-step/index.jsx

The sub-pages of `me/security` were missing the `security` class name on the main container, which was causing inconsistencies in the layout, e.g. different width of the dropdown.
* Add missing main container `security` className for security sub-pages
**Before:**
**After:**
1. Boot Calypso
2. Open http://calypso.localhost:3000/me/security
3. Confirm that the layout of the main security page is consistent with the sub-pages.
Fixes #42653

Add missing main container `security` className for security sub-pages

---

client/components/banner/index.jsx
client/components/banner/test/index.jsx
client/reader/following/main.jsx

* Update Banner to remove unused logic.
**Visuals**
Activity Log
Site Settings
Reader Voting
Stats privacy policy reminder
Pending payments notice
Test the following cases; most of which I've provided instructions to see the banner locally by manipulating the code, since these are set to display under very specific conditions.
- Activity Log backup notice - `client/my-sites/activity/activity-log/index.jsx` - set conditional on line 449 to `true` or have a site with a backup underway
- Activity Log - `client/my-sites/activity/activity-log/rewind-unavailability-notice.jsx` - set conditional on line 446 to `true` but can't find this one yet
- Site Settings - `client/blocks/jetpack-backup-creds-banner/index.jsx` - set conditional on line 40 to `true` or have a Jetpack site with an ongling …

Banner: Refactor to remove upsell-related functionality

---

client/my-sites/checkout/composite-checkout/composite-checkout.js
client/my-sites/checkout/composite-checkout/payment-method-processors.js
client/my-sites/checkout/composite-checkout/use-create-payment-methods.js
packages/composite-checkout/src/lib/payment-methods/existing-credit-card.js

This updates the "existing credit card" payment method to use the payment processor function system introduced in #41767 
See also previous conversion of free credits in #42348.
- Attempt a purchase using composite checkout with a saved card.
- Verify that the purchase is successful.

composite-checkout: Convert existing card payment method to use processor function

---

.github/workflows/full-site-editing-plugin.yml
apps/full-site-editing/full-site-editing-plugin/readme.txt

If we can speed up delivery of fusion builds to mc we can reduce the time developers need to wait.
Currently the longest part of the `build-fse-plugin` process is during the "Install Dependencies" step which tends to take over three minutes
By configuring GitHub's actions/cache we can reduce the amount of time it takes to deliver the FSE artifacts to MC _in most cases_.
* Uses GitHub's `actions/cache` to cache depedencies for lerna based projects.
- Confirm the `build-fse-plugin` GitHub action runs and functions as expected
- Observe the uncached build time is approximately the same in fse/action-cache builds ([uncached run](https://github.com/Automattic/wp-calypso/runs/650547526) vs [other branch](https://github.com/Automattic/wp-calypso/runs/650326922?check_suite_focus=true))
- Observe …

FSE GitHub action cache for lerna

---

.github/workflows/send-calypso-app-build-trigger.sh
apps/full-site-editing/full-site-editing-plugin/readme.txt

There were intermittent issues where the FSE GitHub action would fail for some PRs, claiming that some fields hadn't been sent to the endpoint.
We suspected this was related to how data was being manipulated and sent in the Github action, and this does appear to have been a problem.
There was a significant amount of string interpolation of JSON strings and bash commands which is generally error prone and fragile.
This PR changes the processing to:
- Make a JSON string from environment variables via JavaScript.
- Merge JavaScript objects in JavaScript.
- Write JSON output to a file from JavaScript.
- Read a `curl` form field input from a JSON file rather than string interpolation.
The sum of these changes should result in more robust and reliable processing.
- Was D43943-code updated as …

FSE: Fix workflow

---

client/reader/README.md
client/reader/controller.js
client/reader/index.js
client/sections.js

Reader used to have a section called 'Freshly Pressed' at `/read/fresh`. Until recently it was still possible to access it. In the last week we retired the old codebase and now all requests for `/read/*` go to Calypso. 
This PR adds a redirect for the old `/read/fresh` route to `/discover`.
It also fixes the `/recommendations` to `/read/search` redirect which was not working as intended.
Fixes 7760-wpcom.
Go to http://calypso.localhost:3000/read/fresh and ensure you are redirected to `/discover`.
Go to http://calypso.localhost:3000/recommendations and ensure you are redirected to `/read/search`.
Ensure your usual Reader streams work as normal.

Reader: redirect /read/fresh to Discover

---

client/landing/gutenboarding/available-designs.ts

Move Edison premium design to be 2nd from 1st position.
This will help on mobile where users might pick the first design without noticing it's premium.

Gutenboarding: move edison premium design to be 2nd from 1st position

---

client/me/sidebar/index.jsx
client/my-sites/controller.js
client/my-sites/domains/index.js
client/my-sites/domains/paths.js
client/sections.js

* Revert #42071 because in the end we're going for the all my sites view
* Go to /me - there should be no Domains menu
* Try /me/domains - again nothing should show
* Go to /domains/manage - if you're using your dev environment you should see a list of all sites domain management pages

Remove the /me/domains route

---

client/signup/main.jsx
client/signup/steps/user/index.jsx

* Update `subHeaderText` state in UserSignup step when `locale` prop changes
* Omit `locale` when passing props UserSignup to avoid overriding the prop from `i18n-calypso`'s `localize` HOC.
**Before:**
**After:**
1. Boot Calypso
2. Open http://calypso.localhost:3000/start/user
3. Switch to a different locale from the language suggestions component and confirm sub header text gets translated properly

i18n: Update sub header text state on signup page when locale changes

---

client/my-sites/checkout/composite-checkout/wpcom/lib/translate-cart.ts
client/my-sites/checkout/composite-checkout/wpcom/test/translate-cart.js
client/my-sites/checkout/composite-checkout/wpcom/types/checkout-cart.ts

* We need the monthly prices on the frontend, and the most reliable way to get them is to compute them on the backend. This PR is a companion to D43984-code which makes this part of the endpoint response available in calypso.
Unit test built in.
Manual test: apply D43984-code to your sandbox. Enter checkout and use the react dev tools to inspect the props of a line item. You should see `item_original_monthly_price_display` and `item_original_monthly_price_integer` in `item.wpcom_meta`.

composite-checkout: Add original monthly cost data to checkout cart

---

client/my-sites/checkout/checkout-system-decider.js
client/my-sites/checkout/composite-checkout/wpcom/components/wp-checkout-order-review.js
client/my-sites/checkout/composite-checkout/wpcom/components/wp-order-review-line-items.js

This modifies `CheckoutSystemDecider` so that shopping carts which contain GSuite products can be sent to composite checkout.
Requires #41705
- Visit checkout after adding a GSuite product to your cart and verify that you see composite checkout. (Add `?flags=composite-checkout-testing` to your URL if your user is not in the ab test.)

Allow GSuite plans through CheckoutSystemDecider

---

client/my-sites/checkout/composite-checkout/wpcom/components/wp-checkout-order-review.js
client/my-sites/checkout/composite-checkout/wpcom/components/wp-checkout.js

This PR is an experimental design change which modifies the first step of checkout so that it is always visible and active. This means that it no longer has a "Continue" button and will never be hidden when another step is active.
View composite checkout and make sure that it looks and works as expected. Notable things to try:
- Change the plan length for a newly added plan.
- Remove an item from the cart.
- Add a coupon to the cart.

composite-checkout: Make review step always visible

---

apps/full-site-editing/full-site-editing-plugin/dotcom-fse/editor/style.scss

In gutenberg 8.2.0-RC.1 the inserter is no longer hidden when FSE is enabled https://github.com/WordPress/gutenberg/pull/22115/files
This lead to this issue https://github.com/Automattic/wp-calypso/issues/42611
FSE adds its own inserter in https://github.com/Automattic/wp-calypso/blob/b6944b9c4f84459bc56463e0f8ebb01b2f9727e1/apps/full-site-editing/full-site-editing-plugin/dotcom-fse/editor/block-inserter/index.js
This change ensures that the original gutenberg inserter is hidden with CSS
Open up a site with FSE enabled
Apply the gutenberg edge sticker
Ensure that 8.2.0-RC.1 is the current gutenberg version
There should be only one inserter present
Fixes #42611

 hide duplicate inserter for gutenberg 8.2.0

---

client/my-sites/earn/memberships/add-edit-plan-modal.jsx
client/my-sites/earn/memberships/products.jsx

The "Add new plan" and "Edit" actions for payments plans (at `/earn/payments-plans/:site`) are coupled together through state and sharing a dialog in `MembershipsProductsSection`. This causes the "Add new plan" dialog to be briefly visible when dismissing the edit version of the dialog. By splitting out the dialog and handling dialog openings individually, we should end up with simpler payments plans components, and better rendering of each modal dialog.
* Load this branch with a site that has a Personal plan or higher.
* Go to `/earn/payments-plans/:site`.
* Add a new plan, and verify that everything works as expected.
* Load an existing plan (via the ellipsis menu Edit button), and verify initial data loads correctly, and saves correctly.
* Verify there is no flash of different modals …

Recurring Payments: Split out edit modal.

---

client/my-sites/checkout/composite-checkout/composite-checkout.js
client/my-sites/checkout/composite-checkout/payment-method-helpers.js
client/my-sites/checkout/composite-checkout/payment-method-processors.js
client/my-sites/checkout/composite-checkout/use-create-payment-methods.js
packages/composite-checkout/src/lib/payment-methods/paypal.js

This updates the "PayPal" payment method to use the payment processor function system introduced in #41767
See also previous conversion of full credits in #42348 and existing cards in #42633.
- Attempt a purchase using composite checkout with PayPal.
- Verify that the purchase is successful.

composite-checkout: Convert PayPal payment method to use processor function

---

client/server/pages/index.js

Currently when a user wants to see Jetpack Cloud production they get sent to jetpack.com
This PR removed that and make Jetpack cloud available to all customers. (Production stays on cloud.jetpack.com)
* Deploy and test that it works as expected.
* Does the code look good?

Jetpack Cloud: Send production traffic to cloud.jetpack.com

---

client/components/data/query-home-layout/index.js
client/my-sites/customer-home/controller.jsx
client/my-sites/customer-home/main.jsx
client/state/data-layer/wpcom/sites/home/layout/index.js
client/state/home/actions.js

Requires D43986-code.
Adds the ability to force displaying a particular view in My Home when the dev mode is turned on.
The forced view can be set in a `view` query param when visiting My Home.
The dev mode can be turned on either with the `home/layout-dev` feature flag (enabled by default in Calypo dev) or with a `dev` query param when visiting My Home.
- Apply D43986-code and sandbox the API.
- Visit My Home normally and verify you get the expected view for your current site's state.
- Add a `view` query param to the URL and verify the given view is displayed (i.e. `/home/:site/?view=VIEW_WEBINARS`).
- Make sure the view is not forced when the `home/layout-dev` flag is disabled (i.e. `/home/:site?view=VIEW_WEBINARS&flags=-home/layout-dev`).
- Make sure the view is forced when the …

My Home: Add support for forced views in dev mode

---

client/my-sites/checkout/composite-checkout/composite-checkout.js
client/my-sites/checkout/composite-checkout/payment-method-processors.js
client/my-sites/checkout/composite-checkout/use-create-payment-methods.js
packages/composite-checkout/src/lib/payment-methods/free-purchase.js

This updates the "free" payment method to use the payment processor function system introduced in #41767
See also previous conversion of full credits in #42348 and existing cards in #42633 and PayPal in #42662.
- Add a coupon to your cart that gives a 100% discount.
- Attempt a purchase using composite checkout with the "free" payment method.
- Verify that the purchase is successful.

composite-checkout: Convert free purchase payment method to use processor function

---

packages/composite-checkout/src/lib/form-status.js
packages/composite-checkout/src/lib/payment-methods/apple-pay.js
packages/composite-checkout/src/lib/payment-methods/existing-credit-card.js
packages/composite-checkout/src/lib/payment-methods/full-credits.js
packages/composite-checkout/src/lib/payment-methods/stripe-credit-card-fields.js

I realized that the error handling using the new processor functions duplicates some error handling. 
When an error happens, the event handler will save the error message in `useTransactionStatus`, and then a `useEffect` in each payment method's component will display the error, change the form status back to "ready", and trigger analytics. Prior to this PR, we were also doing those things manually in the event handler. This PR changes the reliance entirely to the `useEffect`.
What's exciting about this is that the process can be generalized so that we will be able to move all of those `useEffect`s to a custom hook (maybe `useHandleTransactionStatus`) in `CheckoutProvider` that handles all payment methods. 
We will need to test causing an error in each of these payment methods (apple pay, …

composite-checkout: Remove payment method duplicate error handling

---

client/blocks/conversation-caterpillar/style.scss

The conversation caterpillar block (used in Reader Conversations) shows the avatars of people who have commented on a post. I just noticed that the text was aligned to the top of the avatars rather than being centred, which I believe was the case when the feature launched.
This PR restores the vertical centering.
Before:
After:
Visit http://calypso.localhost:3000/devdocs/blocks/conversation-caterpillar and ensure the text next to the avatars is vertically centered.

Reader: fix alignment of conversation caterpillar button text

---

client/lib/gsuite/index.js
client/lib/gsuite/test/index.js
client/my-sites/checkout/controller.jsx
client/my-sites/domains/controller.jsx
client/my-sites/domains/domain-search/index.jsx
client/my-sites/email/email-management/index.jsx

This pull request simply renames the obscure `isGSuiteRestricted()` method into `canUserPurchaseGSuite()`. The more explicit name makes it clearer what the exact intent of this function is. The new name also plays nicely with `canDomainAddGSuite()`.
1. Run `git checkout update/gsuite-method` and start your server, or open a [live branch](https://calypso.live/?branch=update/gsuite-method)
2. Open the [`Domains` page](http://calypso.localhost:3000/domains)
3. Purchase a domain with G Suite
4. Assert that the G Suite account was provisioning succesfully

G Suite: Rename function that determines whether G Suite can be purchased by a user

---

client/landing/gutenboarding/components/plans/plans-table/plan-item.tsx
client/landing/gutenboarding/components/plans/plans-table/style.scss
client/landing/gutenboarding/onboarding-block/design-selector/style.scss
client/landing/gutenboarding/onboarding-block/style-preview/style.scss

1. [Price loading animation doesn't stop after the price is loaded](https://d.pr/v/KzYlTo).
2. [The gaps in design picker page are broken](https://user-images.githubusercontent.com/17054134/82670289-28393f80-9c3d-11ea-936e-48a1c18ade24.png).
3. [The "continue/pick other design" buttons are misaligned](https://user-images.githubusercontent.com/17054134/82670494-89f9a980-9c3d-11ea-9905-d7f3726d4ee8.png).
4. [The preview window doesn't use all the available space.](https://user-images.githubusercontent.com/17054134/82670690-e5c43280-9c3d-11ea-8eae-258bcdb9b1d0.png)
5. [The preview viewport isn't centered for mobile and tablet](https://user-images.githubusercontent.com/17054134/82670807-1dcb7580-9c3e-11ea-8711-a69b5cd0c007.png).

Gutenboarding IE improvements

---

client/my-sites/checkout/composite-checkout/wpcom/components/wp-order-review-line-items.js

`couponStatus` is one of [a number of strings](https://github.com/Automattic/wp-calypso/blob/master/client/my-sites/checkout/composite-checkout/wpcom/hooks/use-shopping-cart.ts#L334) when returned from the endpoint. This updates the relevant propTypes to reflect such.
**To test:**
- visit Checkout with `?flags=composite-checkout-force`
- verify there aren't any console errors regarding the couponStatus propType
- apply a coupon and verify that the correct discount is applied
- finish Checkout and verify that the purchase was successful

Checkout: update couponStatus propType

---

packages/composite-checkout/demo/index.js
packages/composite-checkout/src/components/checkout-steps.js

`CheckoutErrorBoundary` has a required `errorMessage` prop, but the same prop on `CheckoutStepBody` is optional, resulting in a console error when one isn't explicitly provided.
This adds a default `errorMessage` to `CheckoutStepBody`.
**To test:**
- view composite checkout with `?flags=composite-checkout-force`
- verify that there isn't a console error for the `errorMessage` prop
- throw an exception in one of Checkout's `CheckoutSteps`
- verify that you see the default 'There was an error with this step.' error message for the step

Composite Checkout: add default error message to CheckoutStepBody

---

client/my-sites/domains/domain-management/dns/txt-record.jsx

This PR updates the error shown when a user tries to enter a TXT record that is longer than 255 characters.
Try to add a TXT record with a value longer than 255 characters to your domain. You should see the following error:
You should see a similar error as well when the TXT record is empty.

Domains: Update TXT record error to be clearer

---

client/landing/jetpack-cloud/components/daily-backup-status/backup-changes.jsx
client/landing/jetpack-cloud/components/daily-backup-status/index.jsx
client/landing/jetpack-cloud/sections/backups/main.jsx
client/landing/jetpack-cloud/sections/backups/utils.js

The issue was breaking the Backup section for the non-English accounts. The problem is that our metaDiff calculation is based on the received text string which is translated, so it breaks the expected tokens (in English). To solve it, simply we disable temporally the metaDiff calculation for the daily backups and comment the code that uses it.
You can reproduce the current issue by changing your account languages to a non-English language. Select a site with a bunch of backups. Go to the Backup section and try to navigate to previous dates. You should have a Javascript error that freezes the app. It happens for Daily and Real-time Backup products.
**Next:**
To solve this issue well, we need a data object with all the info directly from the API, instead of trying to extract it from a text …

Jetpack Cloud: quick fix that disable the metaDiff information

---

client/landing/jetpack-cloud/components/activity-card-list/style.scss

* Modify a SCSS rule to account for change in React markup, so that timeline icons will have a background color again and not be interrupted by the timeline itself
Fixes `1169345694087188-as-1177681663771100`
* Open Jetpack Cloud for a site with Backup.
* Look through the **Activity log**. Verify that timeline icons sit "above" the timeline itself and are not obscured or intersected by it. (See screenshots for more detail.)

Jetpack Cloud: Make timeline icons obscure the 'timeline' around them and perfectly align with it

---

client/state/login/actions/reboot-after-login.ts

* We want to detect users visiting the authorize login page that are coming from the login page. For that purpose, we are adding a query parameter called `login_flow` to the redirect URL on that specific case.
* Run this PR with `yarn start` (we want to start Calypso, not Jetpack Cloud)
* Visit wordpress.com and log out from your current session
* Visit cloud.jetpack.com
* You should see Jetpack Cloud login page (stage enviroment)
* Copy everything after `https://wordpress.com/` of the URL
* Replace the current URL with `http://calypso.localhost:3000/` and paste what was copied in the previous step
* You should see Jetpack Cloud login page (dev environment)
* Log in (enter your credentials and the authentication code)
* You should have been redirected to …

Jetpack Cloud: Add a query parameter called 'login_flow' to the redirect url

---

packages/domain-picker/src/domain-picker/index.tsx
packages/domain-picker/src/domain-picker/suggestion-item.tsx
packages/domain-picker/test/suggestion-item.tsx

* This PR adds the category slug to the `fetchAlgo` that gets logged as part of the suggestions TrainTracks data, as we want to be able to track the behaviour for category-driven searches separately from "normal" searches in Gutenboarding.
* Open the network tab
* Start the Gutenboarding flow and pick a site title.
* As soon as it is visible, open the domain picker.
* Verify that you get a number of requests to `http://pixel.wp.com/t.gif` with `railcar` as the leading URL parameter, and that the `fetch_algo` parameter is set to `%2Fdomains%2Fsearch%2Fvariation4_front%2Fgutenboarding` (which is the same as it was before).
* Click on the "More Options" link
* Verify that you get a number of requests to the same URL with the same `fetch_algo` value as above. (11 requests in modal, 6 requests …

Track Gutenboarding domain searches that use a category

---

client/my-sites/earn/memberships/delete-plan-modal.jsx
client/my-sites/earn/memberships/products.jsx

When closing the Delete Plan dialog, the plan title flashes from the proper title to the `%s` argument placeholder of the `translate()` call. This PR refactors out the Delete Plan dialog and removes the flash of changing text.
* On this branch, go to `/earn/payments-plans/:site` on a site that can use Recurring Payments.
* Select the ellipsis menu for a plan and choose Delete.
* Click Delete in the dialog, and verify the dialog closes without exposing the `%s` text.

Recurring Payments: Remove flash of placeholder text on closing the delete dialog.

---

client/landing/jetpack-cloud/components/activity-card-list/style.scss
client/landing/jetpack-cloud/components/activity-card/style.scss

* Realign the activity time icons, use colors and sizes from design
1. Navigate to `/backup/activity-log` and check out the design

Jetpack Cloud: Refine ActivityCard Time Styles

---

packages/composite-checkout/src/lib/payment-methods/paypal.js

Fixes a bug wherein the paypal submit button isn't disabled when you click it.
Submit a paypal transaction and make sure that as soon as you click the button it becomes disabled. Then verify that the rest of the transaction works correctly.

composite-checkout: Disable the form when the paypal button is clicked

---

packages/composite-checkout/src/components/checkout-payment-methods.js
packages/composite-checkout/src/components/radio-button.js

When the checkout form is pending a cart update or when it is submitting, this PR disables the buttons that let you change the current payment method.
Complete composite checkout and when you click the submit button, verify that while the form is loading, you cannot change payment methods.

composite-checkout: Disable payment method buttons when form is not ready

---

client/blocks/login/login-form.jsx
client/blocks/login/social.jsx

* Add property to social form to suppress "Continue with Apple" login
* Use this property to restore "Continue with Google" social login for Jetpack Cloud authorization flow
* Run this PR with `yarn start` (we want to start Calypso, not Jetpack Cloud)
* Visit wordpress.com and log out from your current session
* Visit cloud.jetpack.com
* You should see Jetpack Cloud login page (stage enviroment)
* Copy everything after `https://wordpress.com/` of the URL
* Replace the current URL with `http://calypso.localhost:3000/` and paste what was copied in the previous step
* You should see Jetpack Cloud login page (dev environment), which should match the above screenshot
1. Continue with Google, create new Google account, verify you return to "Authorize your WordPress.com to sign into …

Jetpack Cloud: Restore Google Social Login

---

client/my-sites/checkout/composite-checkout/record-analytics.js
client/my-sites/checkout/composite-checkout/test/composite-checkout.js
client/my-sites/checkout/composite-checkout/use-create-payment-methods.js
packages/composite-checkout/README.md
packages/composite-checkout/src/components/checkout-provider.js
packages/composite-checkout/src/lib/payment-methods/apple-pay.js
packages/composite-checkout/src/lib/payment-methods/existing-credit-card.js
packages/composite-checkout/src/lib/payment-methods/free-purchase.js
packages/composite-checkout/src/lib/payment-methods/full-credits.js
packages/composite-checkout/src/lib/payment-methods/paypal.js
packages/composite-checkout/src/lib/payment-methods/stripe-credit-card-fields.js
packages/composite-checkout/src/lib/transaction-status.js
packages/composite-checkout/test/checkout.js

Each payment method in composite checkout uses the `useTransactionStatus` hook to keep track of the status of the current transaction (`not-started`, `pending`, `redirecting`, `complete`, etc.). The components of that payment method then react to the transaction status to do things like display error messages, disable/enable the form, and redirect if necessary. That logic is a side effect repeated in each payment method.
This PR moves all of those side effects into one place in `CheckoutProvider`.
We'll need to make sure that for each of the payment methods (free purchase, paypal, apple pay, credit card, existing card, and full credits), a successful purchase works correctly. For PayPal this just means redirecting to the PayPal url. For other payment methods this means completing a …

composite-checkout: Automate transaction status handling

---

client/my-sites/checkout/composite-checkout/composite-checkout.js
client/state/receipts/assembler.js
client/state/stored-cards/selectors.js

The `handleCheckoutCompleteRedirect()` function in old checkout performs a bunch of actions before redirecting away. This PR imports those actions more-or-less wholesale into `CompositeCheckout`.
Complete a purchase in composite checkout and be sure that there are no errors, and that the redirect works correctly.
Complete a plan purchase in composite checkout with a new site and be sure that you are redirected to the customer home page and that the plan you purchased is immediately visible in the sidebar. (Fixes #42711)
Complete a renewal purchase in composite checkout and verify that you see a special renewal notice appear after the redirect. Either "X has been renewed and will now auto renew in the future" or "Success! You renewed X for Y until Z. We sent your receipt to E." depending …

composite-checkout: Update local caches after purchase complete

---

apps/full-site-editing/full-site-editing-plugin/block-inserter-modifications/index.php
apps/full-site-editing/full-site-editing-plugin/event-countdown-block/index.php
apps/full-site-editing/full-site-editing-plugin/global-styles/class-global-styles.php
apps/full-site-editing/full-site-editing-plugin/jetpack-timeline/index.php

`require` should be used for asset files not `require_once`. See https://github.com/WordPress/gutenberg/pull/18599
Illustration of the issue, note the second `require_once` returns `true`.
```
php > var_export( require_once( __DIR__ . '/global-styles.asset.php' ) );
array (
'dependencies' =>
array (
0 => 'lodash',
1 => 'wp-api-fetch',
2 => 'wp-components',
3 => 'wp-compose',
4 => 'wp-data',
5 => 'wp-dom-ready',
6 => 'wp-edit-post',
7 => 'wp-element',
8 => 'wp-i18n',
9 => 'wp-keycodes',
10 => 'wp-plugins',
11 => 'wp-polyfill',
),
'version' => 'e53af81a8e55ea0235ea0da817d6aad4',
)
php > var_export( require_once( __DIR__ . '/global-styles.asset.php' ) );
true
```
Compare to `require`:
```
php > var_export( require( __DIR__ . '/global-styles.asset.php' ) );
array (
'dependencies' =>
array (
0 …
```

FSE: require asset files (not _once)

---

client/landing/gutenboarding/components/plans/plans-button/index.tsx
client/landing/gutenboarding/components/plans/plans-button/style.scss
client/landing/gutenboarding/hooks/use-on-site-creation.ts
client/landing/gutenboarding/onboarding-block/edit.tsx
client/landing/gutenboarding/onboarding-block/style-preview/index.tsx
config/development.json
config/horizon.json
config/production.json
config/stage.json
config/wpcalypso.json

* Remove `gutenboarding/plans-grid` feature flag no longer needed.
* Use actual disabled state for PlansButton on Plans step. Right now the button seems clickable but nothing happens when you click it.
* Fix redirects based on Gutenboarding persisted state.
* if Site Title has a value =>  redirect to Design Selector
* else => redirect to Intent Capture
* With an empty state, by going to `/new/style`, `/new/plans` or `/new/create-site` you should be redirected to `/new`.
* With an existing `siteTitle` value, any of the above should redirect to `/new/design`.
* Going to `/new/design` directly should still work (site title is optional).
* On `/new/plans` step, the Plans Button should be disabled.

Gutenboarding: small tweaks and cleanup feature flags

---

client/components/domains/register-domain-step/index.jsx

At present, the main domain search component only distinguishes between searches from  onboarding and from within Calypso. However, there is a third path, which is for domain-only searches triggered by starting from `https://wordpress.com/domains`.
This change updates the logic to keep the existing two searches as-is, while also introducing a new label for domain-only searches.
For each of the following flows, perform a domain search, and verify that we trigger network requests to `http://pixel.wp.com/t.gif` with the first URL parameter as `railcar=` and the `fetch_algo` parameter as specified below:
1. Start from `/start` and search for a domain. The `fetch_algo` parameter for the railcar requests should be 
`%2Fdomains%2Fsearch%2Fvariation4_front%2Fsignup%2Fdonuts`. (This should remain …

Ensure that we can distinguish TrainTracks data for domain-only searches

---

apps/full-site-editing/full-site-editing-plugin/premium-content/index.js

Appends a "paid" flag to the Premium Content block title displayed on the block inserter when the site requires a upgrade.
* Apply D44086-code or `cd apps/full-site-editing; yarn dev --sync`.
* Sandbox the API.
* Switch to a sandboxed site under a Free plan.
* Add a new post.
* Open the block inserter and search the Premium Content block.
* Make sure the title contains a "paid" flag at the end.
* Upgrade to a paid plan or switch to a sandboxed site under a paid plan.
* Add a new post.
* Open the block inserter and search the Premium Content block.
* Make sure the title does not contain a "paid" flag at the end.
Fixes #41584

Premium content: Add paid flag

---

client/my-sites/customer-home/cards/tasks/deprecate-editor/index.jsx
client/post-editor/editor-deprecation-dialog/index.jsx

* Use localized long date format `LL` from moment.js for post editor deprication date
**Before:**
**After:**
1. Boot Calypso
2. Open http://calypso.localhost:3000/home/{site} and http://calypso.localhost:3000/post/{site}/{postId}
3. Confirm that date in post editor deprication notice is using localized long date format
Ref: p1590682280002300-slack-i18n-chatter

i18n: Use localized date format for post editor deprication date

---

client/my-sites/checkout/composite-checkout/composite-checkout.js
client/my-sites/checkout/composite-checkout/wpcom/components/item-variation-picker.tsx
client/my-sites/checkout/composite-checkout/wpcom/components/wp-checkout-order-review.js
client/my-sites/checkout/composite-checkout/wpcom/components/wp-checkout.js
client/my-sites/checkout/composite-checkout/wpcom/components/wp-order-review-line-items.js

This hides the coupon field by default in composite checkout and instead shows a button that will make the field visible.
This also makes it so that when a coupon is removed, the field is cleared and hidden.
- Visit composite checkout and verify that you see the "Add a coupon" button (you will not see it if your purchase is free; that behavior remains the same).
- When you click the button, verify that the field appears.
- Enter a coupon value and press "Apply".
- Press the trash can icon next to the applied coupon and confirm removal.
- Verify that you see "Add a coupon" again and clicking it shows an empty coupon field.

composite-checkout: Hide coupon field behind button

---

client/my-sites/checkout/checkout-system-decider.js

This allows all the 2-year plan aliases through to composite checkout in `CheckoutSystemDecider`. These slug aliases (they are not real product slugs) are [defined here](https://github.com/Automattic/wp-calypso/blob/master/client/lib/plans/plans-list.js). This does not include jetpack plans because Jetpack sites are currently explicitly blocked, and we did not include `beginner` or `professional` or `professional-monthly`, since I don't believe those are enabled. Finally, we did not include `business-monthly` or `premium-monthly` because I'm not sure how those work (they seem to cause a fatal error in old checkout).
Visit `http://calypso.localhost:3000/plans/[your-site-here]/[slug-alias-here]` for the following aliases and be sure that you are taken to the composite checkout page _and_ …

Allow 2-years plan variants through CheckoutSystemDecider

---

client/reader/following/main.jsx

* Noticed as I was testing something else, we're standardizing all buttons to use Sentence case (rather than Title Case) - reference post is here: p9Jlb4-1ly-p2
* This updates the "Mark all as unseen" buttons to use sentence case.
**Before**
**After**
* Go to `/read`
* Note the buttons under Followed Sites; the copy should be sentence case rather than title case.

Reader: Sentence case button copy

---

client/lib/products-values/index.js
client/my-sites/checkout/checkout/index.jsx
client/my-sites/checkout/checkout/secure-payment-form.jsx

* Redirects users to the appropriate place after purchasing a Cloud product.
* Ensures external redirects work correctly for checkouts.
1. Check out with Jetpack Backup or Scan.
2. See where you are directed after checkout.

Redirect users to Cloud after checking out

---

apps/full-site-editing/full-site-editing-plugin/full-site-editing-plugin.php
apps/full-site-editing/full-site-editing-plugin/readme.txt
apps/full-site-editing/package.json

* Version bump and changelog.
**Update: Planning to release on Friday 2020-05-29 (pushed back from Thursday)**
Remaining PRs for this release:
- This change doesn't require any release notes. We're developing a new feature which is currently hidden behind a flag.
- Not including in Changelog since it's not user-visible.
- Not including in Changelog since it's not user-visible.
- Not including in Changelog since it's not user-visible.
- This change doesn't require any release notes. We're developing a new feature which is currently hidden behind a flag.
* Apply this build, test changes since the last release found at: https://github.com/Automattic/wp-calypso/commits/master/apps/full-site-editing.
*  Test on atomic sites as well as outlined here: PCYsg-ly5-p2
We can rebase this PR as more …

FSE Plugin: Update to v1.6

---

client/my-sites/checkout/composite-checkout/record-analytics.js

Remove duplicate reduxDispatch calls in createAnalyticsEventHandler.
Regression introduced in #42002.
Cause a fatal error at the top of `WPCheckout` and make sure you see the Error Boundary and not a blank page.

Remove duplicate reduxDispatch calls in createAnalyticsEventHandler

---

client/my-sites/media-library/list.jsx

This PR changes the group labels in media section from static date format to [locale aware format](https://momentjs.com/docs/#/parsing/string-format/).
The downside is that it will always display the year, even for dates from the current year.
As an alterntive approach, we can try switching to [Date.prototype.toLocaleString()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleString), which would allow us to exclude the year when not needed. We could fallback to moment.js for browsers that don't support `toLocaleString`.
* Use localized long date format `LL` for media section group labels
**Before:**
**After:**
* Open http://calypso.localhost:3000/media/ and cofirm group labels are in localized date format

i18n: Use localized long date format for media section group labels

---

config/jetpack-cloud-production.json

* This enables performing on-demand scans for prod in Cloud.
* Visit prod Jetpack Cloud and go to a site that has Scan.
* See that scan button appears.

Cloud: Enable on-demand scan for production

---

config/jetpack-cloud-development.json
config/jetpack-cloud-horizon.json
config/jetpack-cloud-production.json
config/jetpack-cloud-stage.json

* This PR replaces the relative `/connect` path with a full absolute URL for the login_url in our envirnoment configs.
* Attempt to connect/login in staging. If it works, this should be good to go.

Jetpack Cloud: Use full connect url for login_url in config

---

config/jetpack-cloud-development.json
config/jetpack-cloud-horizon.json
config/jetpack-cloud-production.json
config/jetpack-cloud-stage.json

Reverts Automattic/wp-calypso#42824
This breaks the domain root, unfortunately. Will need to look for a new solution.

Revert "Jetpack Cloud: Use full connect url for login_url in config"

---

client/my-sites/domains/domain-management/dns/txt-record.jsx

Reverts Automattic/wp-calypso#42721
The PR this reverts appears to be causing problems with adding SRV records to domains.
Note: this PR will need to be merged with failing lint checks, as #42721 was also merged with failing lint checks.

Revert "Domains: Update TXT record error to be clearer"

---

client/my-sites/earn/home.tsx

Similar to #41682, this fixes two nudges on the Earn page so that they display the plans necessary to access those features and highlight the features in the table. 
Visit `/earn/site` and click the "Collect one-time payments" and "Earn ad revenue" nudge, both of which are features that the boxes make clear require at least a Premium plan to access. 
Verify that this ensures the Plans page makes that clear too, as is the case with other nudges, and also highlights the feature.
cc @artpi, @mmtr

Earn: Fix Plans Displayed after Clicking Nudges

---

client/gravatar/types.ts
client/landing/gutenboarding/components/domain-picker-button/index.tsx
client/landing/gutenboarding/components/header/index.tsx
client/landing/gutenboarding/components/link/index.tsx
client/landing/gutenboarding/constants.ts
client/landing/gutenboarding/hooks/use-track-modal.ts
client/landing/gutenboarding/hooks/use-track-step.ts
client/landing/gutenboarding/index.tsx
client/landing/gutenboarding/onboarding-block/design-selector/index.tsx
client/landing/gutenboarding/onboarding-block/edit.tsx
client/landing/gutenboarding/onboarding-block/index.ts
client/landing/gutenboarding/onboarding-block/style-preview/index.tsx
client/landing/gutenboarding/onboarding-block/style-preview/preview.tsx
client/landing/gutenboarding/onboarding-block/style-preview/viewport-select.tsx
client/landing/gutenboarding/path.ts
client/landing/gutenboarding/stores/onboard/actions.ts
client/landing/gutenboarding/stores/onboard/index.ts
client/landing/gutenboarding/stores/onboard/reducer.ts
client/landing/gutenboarding/stores/onboard/selectors.ts
client/landing/gutenboarding/stores/onboard/types.ts
client/landing/gutenboarding/tsconfig.json
client/landing/gutenboarding/utils/domain-suggestions.ts
client/lib/interval/use-interval.ts
client/lib/url/url-parts.ts
client/lib/url/url-type.ts
client/types.ts

Make `importsNotUsedAsValues` error. This comes along with type only imports. [See the announcement post](https://devblogs.microsoft.com/typescript/announcing-typescript-3-8-beta/#type-only-imports-exports).
This change should help to encourage the use of `import type` to import types, and discourage `import { MyType }` otherwise. This is helpful for tree shaking and bundlers, as well as programmers 🙃 
`typecheck-strict` job passes
[`/new`](https://calypso.live/new?branch=gutenboarding/import-type) works without regressions

Gutenboarding: Standardize import type

---

client/components/domains/domain-search-results/index.jsx

* Adds a notice that displays when a domain is unavailable for domain-only search results
* When a domain isn't available, the display should resemble the following:

Display a notice that when a domain is unavailable for domain-only searches

---

client/my-sites/checkout/composite-checkout/wpcom/components/coupon.js

This PR fixes a spacing and orphan (single word on a line) issue for coupon errors in the new composite checkout. Thanks @nbloomf for finding this one.
**Before**
**After**
* Load up calypso or visit Calypso live.
* Add a product to your cart and go to checkout and append `?flags=composite-checkout-force` to the URL to see the new checkout.
* Add any string to the coupon field to see if the spacing is fixed.

Add spacing to coupon error

---

client/landing/jetpack-cloud/sections/auth/connect/index.tsx
client/landing/jetpack-cloud/sections/auth/connect/style.scss
client/landing/jetpack-cloud/sections/auth/controller.tsx

* If the Jetpack Cloud OAuth deny/approve prompt fails, add a separate prompt directing the user to authorize, instead of redirecting them to the same prompt over and over.
Fixes `1169345694087188-as-1177874941283937`
* Open a new browser window with no existing Jetpack Cloud auth data in storage (i.e., incognito or cleared storage) and an account that has not authorized Jetpack Cloud (previously revoked, or never authorized to begin with).
* Observe that you're asked to authenticate via WordPress.com credentials. Enter a valid WordPress.com username/email and password, then **Continue**.
* When presented with the Deny/Approve prompt, click **Deny**.
* Observe that you are forwarded to a page with copy that says "Welcome to Jetpack Cloud. Authorize with your WordPress.com credentials to …

Jetpack Cloud: Display a prompt to authorize if no access token is returned

---

apps/full-site-editing/full-site-editing-plugin/premium-content/blocks/container/edit.js
apps/full-site-editing/full-site-editing-plugin/premium-content/blocks/container/stripe-nudge.js
apps/wpcom-block-editor/src/wpcom/features/tracking/delegate-event-tracking.js
apps/wpcom-block-editor/src/wpcom/features/tracking/wpcom-block-premium-content-plan-upgrade.js
apps/wpcom-block-editor/src/wpcom/features/tracking/wpcom-block-premium-content-stripe-connect.js

Add particular Tracks events for user button clicks and actions related to the Premium Content and Recurring Payments blocks.
* Create a new free Simple site.
* Apply this branch to your local Calypso install. You do _not_ need Calypso running to test this PR.
* Sandbox the following: the API, `widgets.wp.com`, and your new test site.
* Sync the FSE plugin to your sandbox: run `yarn dev --sync` from `/apps/full-site-editing`.
* Build the WP.com block editor app: `npx lerna run build --scope='@automattic/wpcom-block-editor'`
* Sync the block editor app build to your sandbox (`scp -rp apps/wpcom-block-editor/dist/* <sandbox-hostname>:public_html/widgets.wp.com/wpcom-block-editor/` from the Calypso root should work – make sure to use a valid hostname or IP for your sandbox).
* Open a new tab …

Premium Content: Add Tracks events.

---

client/landing/jetpack-cloud/sections/auth/connect/index.tsx

* Removes a reference to Cloud in authorization screen, just using "Jetpack".
* In an incognito window, attempt to authorize Cloud but deny the request on WP.com.
* Screen should now be like this:
Fixes 1143508703416848-as-1178316841543721.

Remove reference to Cloud in auth screen

---

apps/full-site-editing/full-site-editing-plugin/block-inserter-modifications/contextual-tips/style.scss

This PR tweaks the margin of the contextual tip container to the new design of the blocks list
**before**
**after**
Apply these changes. Confirm that the margin of the contextual tip container looks as expected.
Fixes #

FSE: update tips to the new blocks list design

---

client/my-sites/checkout/composite-checkout/use-prepare-product-for-cart.js

Composite checkout's cart manager fetches plans and products if they are
not loaded when a URL comes in that contains a product to add. However,
due to the redirect on an empty cart, this check only takes place once.
In the same render cycle it may fail to find a matching plan (since
the plans are not loaded and not fetching quite yet) causing a redirect
and no product that ever gets loaded.
This change makes it so that an empty plans or products list is also
considered to mean that we should wait for those lists to load.
- Visit composite checkout with a url that adds a plan or product, like `/checkout/example.com/business`.
- Verify that you see the product added to your cart.

composite-checkout: Consider empty plans/products to be loading state when adding items

---

apps/wpcom-block-editor/README.md
apps/wpcom-block-editor/bin/npm-run-build.js
apps/wpcom-block-editor/bin/wpcom-watch-and-sync.sh
apps/wpcom-block-editor/package.json

To match the excellent workflow that we now have in the full site editing plugin, I've coppied/adapted the script to work in the wpcom-block-editor plugin as well.
Add sync and dev build scripts from full-site-editing plugin, adapt them to work in the wpcom-block-editor
* Following new Readme.md instructions, sandbox wordpress.com and a test website.
* run  `yarn dev --sync` in wpcom-block-editor
* Make changes to code in wpcom-block-editor
* Load the block-editor in a sandboxed site.
* You should see your changes!

Add `yarn dev --sync` script to the wpcom-block-editor plugin

---

client/landing/gutenboarding/components/plans/plans-button/index.tsx
client/landing/gutenboarding/components/plans/plans-details/index.tsx
client/landing/gutenboarding/components/plans/plans-grid/index.tsx
client/landing/gutenboarding/components/plans/plans-modal/index.tsx
client/landing/gutenboarding/components/plans/plans-table/index.tsx
client/landing/gutenboarding/hooks/use-on-site-creation.ts
client/landing/gutenboarding/hooks/use-selected-plan.ts
client/landing/gutenboarding/onboarding-block/style-preview/index.tsx
client/landing/gutenboarding/stores/plans/index.ts
packages/data-stores/README.md
packages/data-stores/src/plans/index.ts
packages/data-stores/src/plans/persist.ts
packages/data-stores/tsconfig-cjs.json
packages/data-stores/tsconfig.json

Instead of registering the plans store on module evaluation, now the Plans store module exports a registrar function that allows you to register it where you need it. This prevents the module from creating side effects unless they're explicitly asked for. 
Use Gutenboarding to create a site. All steps of the flow depend on the plans store in a way or another.

Make the plans store tree-shakable

---

client/me/help/help-teaser-button.scss

Should be a super quick and easy review to an issue which I just spotted on Calypso: the nudge for Courses has a poor colour contrast due to a wrong variable. 
The nudge appears on `/help`.
**Before:**
**After:**
cc @mmtr

Help: Courses Nudge - Improve Colour Contrast

---

client/landing/jetpack-cloud/components/sidebar/style.scss

* Truncate long translation strings in sidebar items and add ellipsis at the end.
Before | After
--|--
* Set your language in Calypso to Spanish (works better).
* Open Jetpack Cloud.
* Expand the Backup section.
* Make sure “Latest backups” appears truncated.

Jetpack Cloud: truncate long translation strings in sidebar items

---

client/signup/config/dotblog-verticals.js
client/signup/controller.js
client/signup/index.web.js
client/signup/steps/domains/index.jsx

* Fix the bug that `.blog` domain suggestions show unexpected results when originating signup from .blog landing pages.
* To resolve the issue #41110, both front-end and back-end of the domain suggestions should change. This PR is the front-end part.
* Visit any .blog landing page such as https://tech.blog and click the start button.
* ...or just try `https://wordpress.com/start?site_type=blog&vertical=[VERTICAL]&ref=dotblog-landing`. You should replace `[VERTICAL]` with a valid vertical such as `art` and `tech`.
* Open Network Panel in your browser and filter _XHR_ requests.
* Try searching any domain name.
* Make sure the last request for `suggestions` contains proper parameters.
* Both `include_dotblogsubdomain` and `only_wordpressdotcom` should be true.
* `vertical` should indicate …

Fix: unexpected .blog subdomain suggestions

---

client/my-sites/plans/current-plan/purchases-listing.jsx
client/state/data-layer/wpcom/sites/rewind/api-transformer.js
client/state/data-layer/wpcom/sites/rewind/schema.js
client/state/selectors/is-jetpack-cloud-eligible.js

* Pulls field added in D44110 into Redux state and switches the link URL based on that.
* Go to a site's My Plan page that has Backup or Scan.
* Check link for site that is and is not eligible.
Expected: Site that is eligible has an external link to Cloud, site that doesn't goes to Activity Log.
Fixes 1169345694087188-as-1177440981073469

Changes link in My Plan depending on Cloud eligibility

---

apps/wpcom-block-editor/src/calypso/features/gutenboarding-editor-overrides.js

Part of https://github.com/Automattic/wp-calypso/pull/42847.
Companion to https://github.com/Automattic/wp-calypso/pull/42850.
Details in https://github.com/Automattic/wp-calypso/pull/42847 and D44258-code.
Review D44258-code.

WPCOM-BE: Skip launch button when FSE handled

---

config/desktop.json
config/production.json

CUrrently Jetpack Scan is not a product that you can buy if you are on production or the desktop environments. 
This is intential since there was no interface in the wp-admin that would tell you that you had the product etc.
* Deploy and test unproxied buying experiance or Jetpack Scan.

Jetpack Scan: Make it available on production to purchase

---

client/my-sites/checkout/composite-checkout/composite-checkout.js
client/my-sites/checkout/composite-checkout/contact-validation.js
client/my-sites/checkout/composite-checkout/wpcom/components/wp-checkout-order-review.js
client/my-sites/checkout/composite-checkout/wpcom/components/wp-checkout.js
client/my-sites/checkout/composite-checkout/wpcom/types/backend/domain-contact-validation-endpoint.ts
client/my-sites/checkout/composite-checkout/wpcom/types/wpcom-store-state.ts

This PR refactors contact (domain, G Suite, and tax) validation to separate out the validation itself from the error saving and reporting. By itself, it should have no noticeable effect.
This was extracted from https://github.com/Automattic/wp-calypso/pull/42806 and will be useful there so that we can easily do the contact validation without also reporting errors.
Visit composite checkout with these carts:
Then verify that the contact details validation works correctly by checking the following:
- The form initially display no errors.
- If you press "Continue" with empty contact fields, all the empty contact fields display an error.
- If you press "Continue" with contact fields that contain invalid characters (eg: `$%^&*#@` in the name fields), all the invalid contact fields display an …

composite-checkout: Refactor contact validation to separate out side effects

---

client/landing/jetpack-cloud/components/log-item/index.tsx
client/landing/jetpack-cloud/components/masterbar/index.jsx
client/landing/jetpack-cloud/components/profile-dropdown/index.tsx
client/landing/jetpack-cloud/components/scan-threats/index.tsx
client/landing/jetpack-cloud/components/threat-item/index.tsx
client/landing/jetpack-cloud/lib/use-track-callback.ts
client/landing/jetpack-cloud/sections/backups/rewind-flow/download.tsx

* The goal is to track events that we aren't currently tracking.
New events:
- `calypso_jetpack_settings_masterbar_logout`: happens when a user logs out of Jetpack Cloud 
- `calypso_jetpack_masterbar_profile_toggle`: happens when a user clicks its profile avatar to open the log out dropdown 
- `calypso_jetpack_masterbar_profile_close`: happens when the profile dropdown gets closed because the user clicked outside of it or because it hit the Escape key 
- `calypso_jetpack_scan_threat_itemtoggle`: happens when the user clicks on the header of a threat item 
- `calypso_jetpack_backup_download_click`: happens when the user clicks the `[Create downloadable file]` button 
- `calypso_jetpack_backup_file_download`: happens when the user clicks the `[Download file]` button to actually download the …

Jetpack Cloud: track new events

---

client/my-sites/domains/domain-management/dns/txt-record.jsx

This PR updates the error shown when a user tries to enter a TXT record that is longer than 255 characters, or when the record is empty. 
Try to add a TXT record with a value longer than 255 characters to your domain. You should see the following error:
You should see a similar error when the TXT record is empty:
Also, verify you can add other records without issues, and nothing is broken (see: #42833)

Domains: Update TXT record error messages

---

client/my-sites/checkout/composite-checkout/wpcom/components/wp-checkout.js
client/my-sites/checkout/composite-checkout/wpcom/components/wp-contact-form.js
packages/composite-checkout/README.md
packages/composite-checkout/src/components/checkout-steps.js
packages/composite-checkout/src/public-api.js

This adds code such that if you load checkout when the contact details form fields are valid, we skip the contact details step and go directly to the review step (step 2 in the current flow).
- Enter checkout as an established user with stored domain details. Verify that the contact details step is collapsed on page load, displaying the summary and green checkmark, and that you can complete the purchase.
- Enter checkout as a user with an existing plan only (stored zip and country, but not complete domain details) to purchase a domain. Verify that the contact details step is not collapsed on page load and that you can complete the purchase.
- Enter checkout as a user with no previous purchases with a domain in the cart. Verify that the contact details step is not collapsed and that you …

composite-checkout: Jump to payment method step if contact details are prefilled

---

client/my-sites/checkout/composite-checkout/wpcom/components/wp-checkout-order-summary.js
client/my-sites/checkout/composite-checkout/wpcom/hooks/has-plan.js

This is a first step towards adding plan-specific features to the Checkout summary. It adds the following features to the summary when a 1- or 2-year business plan is in the cart:
- Free domain for one year (when a domain isn't in the cart)
- Install plugins and themes
- Drive traffic to your site with our advanced SEO tools
- Track your stats with Google Analytics
**To test:**
- add a business plan to your cart and visit Checkout with `?flags=composite-checkout-testing`
- verify that the checkout summary has the added features
- switch plan variation and verify that the features remain
- add a domain and verify that the "Free domain for one year" feature is removed (a separate domain item should be seen)

Checkout: add summary business plan features

---

apps/full-site-editing/full-site-editing-plugin/posts-list-block/class-posts-list-block.php

When the FSE plugin is activated a site will start loading posts-list-block.css on every page view, even when the block has never been used.
It should only do that on views where the block is in use.
* Check that the block is in use before loading extra CSS/JS
* Activate the plugin, note that posts-list-block.css starts getting loaded on every page view.
* After change, it should only load on views where the block is being used.
Fixes #

Only load styles and script if the block is in use

---

apps/full-site-editing/full-site-editing-plugin/newspack-blocks/index.php

This is the second part of https://github.com/Automattic/newspack-blocks/pull/494 - which changes the CSS/JS for the carousel and homepage-arcticle blocks to only load at render time.  Currently they are being loaded for every page view.
* Stop loading CSS/JS on every page view for newpack blocks
* Confirm that the CSS/JS load correctly for page views that use the block, and that they do not load on all other page views
Fixes #

Let CSS/JS load at render time

---

client/components/tinymce/plugins/insert-menu/menu-items.jsx
client/my-sites/media-library/data-source.jsx
client/post-editor/editor-html-toolbar/index.jsx

* Updates labels of media libraries to be standardized between Jetpack and WP.com.
* Navigate to `/media` and click on the top left logo to open the libraries dropdown
* Make sure that everything still works and the labels are updated.
* (Optional) Find a site that doesn't have the block editor active
* Create a post and click the "Add" media button to bring up the libraries dropdown with updated labels.
Fixes 66-gh-dotcom-manage

Standardize (external) media libraries labels

---

apps/full-site-editing/full-site-editing-plugin/editor-gutenboarding-launch/index.php

Remove a trailing comma in function arguments. This is valid PHP 7.3 but we should support at least 7.2.
Via @obenland / https://github.com/Automattic/wp-calypso/pull/42850#discussion_r434216848
From #42850
> Sandbox ~`widgets.wp.com` and~ `example.wordpress.com` (Simple site).
> 
> * Test D44327-code in isolation. It should result in no changes in the block editor.
> * [Already deployed ✅ ] ~Test in combination with D44258-code. It should result in no changes in the block editor.~
> 
> 1. https://wordpress.com/block-editor should work as before.
> 2. Starting from [`/new`](https://wordpress.com/new), follow the flow through site creation to the editor.
> 3. In the editor, the publish button should be replaced with "Launch."
> 4. The launch button should link to a URL like …

FSE: Remove function args trailing comma

---

client/blocks/product-purchase-features-list/business-onboarding.jsx
client/blocks/product-purchase-features-list/index.jsx

* Rename 'Quick Start' to 'one-on-one' in the plan features list in /plans page if the site is a white glove site.
* Assign yourself to the variant of the whiteGloveUpsell test, and go through signup flow. Select a free plan and free domain.
* Purchase via the white glove upsell offer page
* Go to /plans page and verify that "Quick Start" is not mentioned.

White glove: Rename 'Quick Start' in plan features.

---

client/blocks/product-purchase-features-list/business-onboarding.jsx
client/blocks/product-purchase-features-list/index.jsx
client/me/concierge/book/info-step.js
client/me/concierge/main.js
client/me/concierge/shared/no-available-times.js
client/me/concierge/shared/primary-header.js

* Rename 'Quick Start' to 'one-on-one' in the concierge booking form if the site is a white glove site i.e purchased via a white glove upsell offer.
* Assign yourself to the variant of the whiteGloveUpsell test, and go through signup flow. Select a free plan and free domain.
* Purchase via the white glove upsell offer page
* Now go to schedule session page at /me/concierge. Verify that the title says "one-on-one" scheduler instead of Quick Start scheduler.
Fixes #

White glove: Rename 'Quick Start' in the concierge booking form

---

client/lib/gsuite/index.js
client/lib/gsuite/test/index.js

The [email page](http://calypso.localhost:3000/email) is blank for sites with no custom domains after changes from D43447-code. This happens because no subscription information is sent for G Suite on subdomains. This is okay because sub-domains can't have G Suite for now.
* `hasGSuiteWithUs` now considers the scenario where no value is found for the subscription status. 
* Navigate to [domains/email](http://calypso.localhost:3000/email)
* Ensure that the page isn't blank
* It should show a G Suite upsell for a site with a custom ( i.e. G Suite compatible ) domain.
* It should an email management screen if a subscription already exists
* It should show empty content prompting custom domain purchase if none exists.

G Suite: Improves the logic for `hasGSuiteWithUs` to consider the default value as a negative case

---

client/blocks/product-purchase-features-list/business-onboarding.jsx
client/blocks/product-purchase-features-list/index.jsx
client/me/concierge/book/info-step.js
client/me/concierge/main.js
client/me/concierge/shared/no-available-times.js
client/me/concierge/shared/primary-header.js
client/my-sites/checkout/checkout-thank-you/business-plan-details.jsx
client/my-sites/checkout/checkout-thank-you/header.jsx
client/my-sites/checkout/checkout-thank-you/index.jsx
client/my-sites/checkout/checkout/index.jsx
client/my-sites/checkout/composite-checkout/composite-checkout.js
client/my-sites/checkout/composite-checkout/use-get-thank-you-url.js
client/state/selectors/is-site-white-glove.js
client/state/selectors/test/is-site-white-glove.js
client/state/sites/constants.js

* If a purchase is made from the white glove offer page,the Thank You page will mention the "white glove" product name.
Depends on D42624-code. Please apply patch in your sandbox.
* Assign yourself to the variant of the `whiteGloveUpsell ` test, and go through signup flow. Select a free plan and free domain. 
* Click No on the white glove offer page, you will be taken to Customer Home
* Click the sidebar nudge to see the offer page again. This time, complete the purchase.
* You will be shown a Thank You page. Verify that the product name is mentioned as "WordPress.com Business (White glove edition)", and the "Quick start"  is renamed to "one-on-one"
* Verify. that the email …

White glove: Modify Thank You page

---

client/blocks/product-purchase-features-list/business-onboarding.jsx
client/blocks/product-purchase-features-list/index.jsx
client/me/concierge/book/info-step.js
client/me/concierge/main.js
client/me/concierge/shared/no-available-times.js
client/me/concierge/shared/primary-header.js
client/my-sites/checkout/checkout-thank-you/business-plan-details.jsx
client/my-sites/checkout/checkout-thank-you/header.jsx
client/my-sites/checkout/checkout-thank-you/index.jsx
client/my-sites/checkout/checkout/index.jsx
client/my-sites/checkout/composite-checkout/composite-checkout.js
client/my-sites/checkout/composite-checkout/use-get-thank-you-url.js
client/my-sites/current-site/notice.jsx
client/state/selectors/is-site-white-glove.js
client/state/selectors/test/is-site-white-glove.js
client/state/sites/constants.js

* This PR implements a sidebar nudge for the white glove offer.
* Users who select a free plan and free domain and decline on the white glove offer page will see the sidebar nudge for the first 24 hours after signup.
Depends on D42624-code. Please apply this patch.
* Assign yourself to the whiteGloveUpsell test's variant and begin signup flow. 
* Select free plan and free domain, you should now see the offer page.
* Click "No thanks" on the offer should take you to Customer Home
* Notice the sidebar nudge. Verify it shows for the first 24 hours after site creation
* Click on the nudge and purchase a white glove product. The shopping cart and receipt email should mention white …

White glove: Show sidebar nudge

---

client/blocks/product-purchase-features-list/business-onboarding.jsx
client/blocks/product-purchase-features-list/index.jsx
client/me/concierge/book/info-step.js
client/me/concierge/main.js
client/me/concierge/shared/no-available-times.js
client/me/concierge/shared/primary-header.js
client/my-sites/checkout/checkout-system-decider.js
client/my-sites/checkout/checkout-thank-you/business-plan-details.jsx
client/my-sites/checkout/checkout-thank-you/header.jsx
client/my-sites/checkout/checkout-thank-you/index.jsx
client/my-sites/checkout/checkout/index.jsx
client/my-sites/checkout/composite-checkout/composite-checkout.js
client/my-sites/checkout/composite-checkout/payment-method-processors.js
client/my-sites/checkout/composite-checkout/types/paypal-express.ts
client/my-sites/checkout/composite-checkout/types/transaction-endpoint.ts
client/my-sites/checkout/composite-checkout/use-get-thank-you-url.js
client/my-sites/checkout/composite-checkout/use-prepare-product-for-cart.js
client/my-sites/checkout/composite-checkout/wpcom/components/wp-checkout-order-review.js
client/my-sites/checkout/composite-checkout/wpcom/components/wp-checkout.js
client/my-sites/checkout/composite-checkout/wpcom/components/wp-order-review-line-items.js
client/my-sites/current-site/notice.jsx
client/state/selectors/is-site-white-glove.js
client/state/selectors/test/is-site-white-glove.js
client/state/sites/constants.js

* This PR is similar to https://github.com/Automattic/wp-calypso/pull/42788, and makes the change for the new checkout.
* If a user clicks "Buy now" on the white glove offer page, then we add a Business plan in cart with the product name modified to indicate that it's a white glove product.
* Completing the purchase will send a receipt to the email inbox with the name "white glove" mentioned in the receipt.
* Rename "Quick Start" to "one-on-one" in the email that asks to schedule a concierge session:
**Note**: Make sure you only see the new checkout for testing this PR. For this, you need a US IP address and assigned to `composite` variation of the `showCompositeCheckout` A/B …

White glove: Modify product name in cart for the new checkout 

---

client/landing/jetpack-cloud/components/scan-badge/index.tsx
client/landing/jetpack-cloud/components/scan-badge/style.scss

* In the Scanner's side bar 'threats' badge, enclose all visible text in an ARIA-hidden span
* Re-add invisible text for screen readers, so the threats badge is always fully readable
* Enclose the visible word 'threats' in its own span; this span is hidden for screen widths between 661 and 960px, where the sidebar is too small for wording in some languages, but visible otherwise
Fixes #42756, `1169345694087188-as-1177874941247940`
(Note: In practice, testing each of these sets independently should be fine. For absolute 100% coverage, feel free to test all permutations.)
**Test cases (threat count):** no threats, singular threat, plural threats
**Test cases (screen width):** 660px or less, 661-960px, 961px or more
**Test cases (page state):** Scan menu open, Scan menu closed
**Most …

Jetpack Cloud: Collapse the sidebar 'threats' badge on narrower layouts

---

client/landing/gutenboarding/components/domain-picker-button/index.tsx
client/landing/gutenboarding/components/domain-picker-modal/index.tsx
client/landing/gutenboarding/components/domain-picker-popover/index.tsx
client/landing/gutenboarding/lib/analytics/index.ts
packages/calypso-analytics/src/index.ts
packages/calypso-analytics/src/train-tracks.ts
packages/domain-picker/package.json
packages/domain-picker/src/domain-picker/index.tsx
packages/domain-picker/src/domain-picker/suggestion-item.tsx

* Move `railcarId` generation and state handling to `DomainPicker`.
* Remove `railcarId` and `recordAnalytics` from `DomainPicker` props.
* Call `recordTrainTracksRender` from  `DomainPicker`
* Remove most of the analytics related props from `SuggestionItem`
* Call `recordTrainTracksInteract` from `SuggestionItem`
* Partial cleanup of `gutenboarding/lib`.
* Allow `ui_algo` to be set by the wrapper UI component.
* When recording `calypso_traintracks_render` event from DomainModal, `ui_algo` prop should have the value `/gutenboarding/domain_modal` instead of `/gutenboarding/domain_popover` which is the value recorded from DomainPopover.
* Nothing else should change in UI or Analytics events fired.
Part of https://github.com/Automattic/wp-calypso/issues/42639

Domain Picker: Extract train tracks to calypso-analytics

---

client/my-sites/current-site/notice.jsx

* This was reported by @jeherve in Slack
* We're setting `forceDisplay` on this nudge, but it still should not show for Jetpack sites. Make sure we check if we're seeing a Jetpack site and bail before calling `UpsellNudge` if so.
**Before**
**After**
* Make sure the additional domains nudge does not appear on a Jetpack site.
* Make sure the nudge correctly appears on a WP.com site

Sidebar: Don't show addtl domain upsell notice for Jetpack sites

---

client/lib/cart/store/index.js

This fixes a regression added in https://github.com/Automattic/wp-calypso/pull/42676 
The identity update triggered by the new "reload" action causes the cached version of the cart (which may be incorrect) to be sent to the server, replacing whatever is there. In this PR we change the "reload" action to simply fetch the current cart instead.
- Add a plan to your cart.
- Visit composite checkout and remove the plan.
- You should be redirected to the plans page.
- Verify that the cart icon in the upper-right does not display a number (it may display one very briefly before it updates).

CartStore: Replace reload update with fetch

---

client/me/purchases/manage-purchase/auto-renew-toggle/index.jsx
client/me/purchases/manage-purchase/purchase-meta.jsx

This PR fixes an issue with the add payment method button that shows when enabling auto renew for a purchase without a payment method.
* Go to /me/purchases
* Select a purchase made with credits
* Try to enable auto-renew
* Click on `Add a payment method`
* After applying the fix, you should be sent to the payment method form, whereas before the fix nothing happens
* Verify that existing functionality isn't broken

Fix add payment method button when no selected site

---

client/blocks/inline-help/index.jsx
client/blocks/inline-help/inline-help-forum-view.jsx
client/blocks/inline-help/inline-help-rich-result.jsx
client/blocks/inline-help/inline-help-search-card.jsx
client/blocks/inline-help/popover.jsx
client/my-sites/customer-home/cards/features/help-search/search-card.jsx

This PR improves recording tracks event from the Inline Help Popover component (currently working on prod) and also records the `search` event when a search occurs in the `<Support />` component.
~<Support /> isn't implemented yet. It's currently [handled on this PR](https://github.com/Automattic/wp-calypso/pull/42625). For this reason, this branch was been branched off from there.~
The primary goal here is to be able to compare where the events came from, segmenting them by the new `location` property, which could contain two different values so far: `inline-help-popover` and `customer-home`.
These values make reference to the location where the search was done by the user.
The suggested scope is _"Record track event when the user performs a search query in the customer home, and add the …

Inline Help: add `location` property to records tracks event

---

client/my-sites/earn/home.tsx

The site slug variable isn't being parsed in the premium content card introduced in #42541.

Earn Page: fix premium content link

---

client/my-sites/plans/current-plan/current-plan-thank-you/paid-plan-thank-you.js

* Makes the progress bar on the Jetpack checklist modal begin at 10%
I tested with these steps, but it's probably worth actually doing it properly with a purchase if possible!
1. Remove these lines
https://github.com/Automattic/wp-calypso/blob/d8079b0738117bda3c43ba7400196a26fa61491b/client/my-sites/plans/current-plan/index.jsx#L97-L99
2. Visit `/plans/my-plan/site.ninja?thank-you=` and verify the modal starts at 10%
3. Replace `getJetpackProductInstallProgress( state, siteId )` with a random number above 10
https://github.com/Automattic/wp-calypso/blob/d8079b0738117bda3c43ba7400196a26fa61491b/client/my-sites/plans/current-plan/current-plan-thank-you/paid-plan-thank-you.js#L172
4. Verify the Progress Bar status updates
cc @jeherve, @simison, @beaulebens 
Fixes #41685

Jetpack Checklist Modal: Start Progress Bar at 10%

---

client/my-sites/checkout/composite-checkout/test/composite-checkout.js
client/my-sites/checkout/composite-checkout/wpcom/components/wp-checkout.js
client/my-sites/checkout/composite-checkout/wpcom/test/shopping-cart-endpoint.js
client/my-sites/checkout/composite-checkout/wpcom/types/backend/shopping-cart-endpoint.ts

Purchases which use free payment methods (full-credits and free-payment) are not currently charged taxes for locations which require them. However, we still submit those locations to the shopping cart endpoint which means that if taxes should be shown for that location, they are shown regardless of if they will be charged.
This PR modifies the process so that:
1. The cart location is updated any time the active payment method changes.
2. When the cart location is updated, we set it to empty if the payment method is free.
Fixes #40016
- Add credits to your account sufficient to cover a plan completely.
- Visit composite checkout with a plan in the cart.
- Fill out the contact form with a non-taxable location (eg: 90210).
- When you reach the payment method step, the active payment method …

composite-checkout: Show/hide taxes when payment method is free

---

client/lib/abtest/active-tests.js

After our most recent bug-fixes and design updates around simplifying the new Checkout flow, this bumps the AB test date gauge the effect of the changes.
Ref: pbOQVh-fY-p2
**To test:**
- visual check to make sure the timestamp is correct

Checkout: bump the date for the composite checkout test

---

client/my-sites/earn/home.tsx

Fixing the Premium Content Block link for users who have access to Premium Content Blocks but aren't yet connected to Stripe.
* Confirm that the Premium Content block link works properly for users on any paid plan but who are not yet connected to Stripe.
Fixes #
* Pointing users to /earn/payments/${ selectedSiteSlug } rather than /earn/payments-plans/${ selectedSiteSlug }

Fixing premium content block link in Earn

---

client/landing/jetpack-cloud/sections/home.tsx

* Change the logic on `/` to redirect more reliably
* if non-eligible primary site, redirect to `/backup`
* if primary site has backups, redirect to `/backup/:siteSlug` 
* if primary site does not have backups and does have backups, redirect to `/scan/:siteSlug`
* finally if none of the above redirect to `/backup`
1. Navigate to `/` for various primary sites, testing the logic

Jetpack Cloud: Refine Logic for Home Redirect

---

client/my-sites/customer-home/cards/tasks/deprecate-editor/index.jsx
client/post-editor/editor-deprecation-dialog/index.jsx

* Removes the June 1 date from Editor deprecation notice and replaces it with a temporary 'In the near future' while new dates are finalised. Exact wording still to be finalised, feel free to comment on options.
* In a site with classic editor set check that deprecation notices displays on Customer home as follows:
and as dialog on loading editor as follows:

Editor: Remove 1 June date from deprecation notices

---

client/state/inline-help/actions.js

Currently, when interacting with the `HelpSearch` card on "My Home" (requires patching `code-D43941` to view) if you enter an empty string as the search query (ie: a load of `SPACE` chars) the UI will go into a "loading" state and stay that way.
This PR fixes the action creator to only dispatch the `INLINE_HELP_SEARCH_REQUEST` action if the search is considered valid -that is it should not be an empty string. 
One thing to note is that we do seem to be leaning heavily on actions happening in a certain order in order to have a valid UI state. I wonder whether:
* Dispatching actions one after another can cause UI components to become out of sync.
* This would be better fixed at the component level rather than changing the order of actions.
* Apply `code-D43941` to your sandbox.
* Sandbox …

My Home Help Search - fix to only show "searching" UI for valid queries

---

apps/full-site-editing/full-site-editing-plugin/editor-gutenboarding-launch/index.scss
apps/full-site-editing/full-site-editing-plugin/editor-gutenboarding-launch/index.ts

* This moves some Gutenboarding Style overrides into FSE so that the feature can be completely removed from wpcom-block-editor
Part of https://github.com/Automattic/wp-calypso/pull/42847
* Apply D44333-code (wpcom-block-editor changes to enable this change)
* Apply this patch D44334-code 
* Sandbox `example.wordpress.com` and `widgets.wp.com` - You'll need to sandbox your newly created site to test these changes.
* Starting from [`/new`](https://wordpress.com/new), go through the site creation flow.
* When you reach the editor, sandbox the new site and refresh (clear caches).
* You should see the launch button styled. Body classes from both wpcom-block-editor and this PR will be applied and they'll apply the same CSS overrides to a few elements. This is acceptable. The wpcom-block-editor …

FSE: Include style overrides for gutenboarding launch

---

apps/full-site-editing/full-site-editing-plugin/editor-gutenboarding-launch/index.php
apps/full-site-editing/full-site-editing-plugin/editor-gutenboarding-launch/index.ts

Trigger auto-save before navigating to the launch URL when clicking the "Launch" button as part of the [`/new`](https://wordpress.com/new) flow.
Known issues:
I've observed a warning in the browser about unsaved content when navigation occurs. This is a pre-existing issue.
* Sandbox `widgets.wp.com` and `example.wordpress.com`.
* Apply D44333-code (wpcom-block-editor changes to enable this change)
* Apply D44258-code (these changes to FSE plugin)
* https://wordpress.com/block-editor/post works without regressions.
* Go through the  [`/new`](https://wordpress.com/new) flow.
* When you reach the editor from the new flow, the `Launch` button should be injected.
* Modify the post content.
* Click the "Launch" button. The post should autosave (indicated in the header) then you should be …

FSE: Gutenboarding launch save on exit

---

client/landing/gutenboarding/onboarding-block/style-preview/style.scss

Fixes #42944 
Adds min-height to the preview container. Mobile view remains untouched (>600px vw).
The preview pane would previously scale down with the viewport. Now it has fixed minimums and will cause the window to scroll.
600px - 1280px
<kbd>![Screen Shot 2020-06-03 at 17 25 22](https://user-images.githubusercontent.com/841763/83656154-7ea06980-a5bf-11ea-8ac6-43c3d8c233c1.png)</kbd>
\>=1280px 
<kbd>![Screen Shot 2020-06-03 at 17 24 58](https://user-images.githubusercontent.com/841763/83656161-7fd19680-a5bf-11ea-81fc-77bb7ce31a2d.png)</kbd>
* [`/new`](https://calypso.live/new?branch=gutenboarding/desktop-preview-min-height)

Gutenboarding: Add desktop preview min-height

---

client/lib/abtest/active-tests.js

* Pausing Plans-Domains with domain-fwd swap test (100% traffic goes to control). Check pbxNRc-iQ-p2
* Domain step should appear first. Then Plans.

Pausing Plans-Domains swap AB test

---

client/my-sites/domains/controller.jsx
client/my-sites/domains/domain-search/index.jsx

This PR fixes the upgrade banner, adding the Personal plan to cart when the "Upgrade" button is clicked.
Depends on D44337-code
- Switch to a site on a free plan
- You should see the "Free domain with a plan" banner. Click on Upgrade
- Verify the Personal plan was added to cart

Domains: Add Personal plan to cart when upgrade is clicked

---

client/my-sites/customer-home/cards/constants.js
client/my-sites/customer-home/locations/tertiary/manage-site/index.jsx

Explores the approach suggested in paYJgx-GU-p2 #comment-899 as an alternative to D43941-code.
This way, we re-use the existing `FEATURE_SUPPORT` card UID so the new Support Search card will be also used in future versions of the desktop app while keeping backwards compatibility with current and previous versions.
Verify the Support Search shows up for all views, including the ones used on the desktop app. See https://github.com/Automattic/wp-calypso/pull/42752#issuecomment-635412097 for instructions about how to build a new desktop app version that includes the new Support Search card (I already generated it and confirmed it works as expected).

My Home: Try updating card mapping for Support card

---

apps/full-site-editing/full-site-editing-plugin/wpcom-block-editor-nux/src/style.scss

This PR fixes the welcome modal styling issues on Gutenberg 8.2.
This PR also fixes the welcome modal styling on mobile view. Following closely to this design https://github.com/Automattic/wp-calypso/issues/42141#issuecomment-627881326 but without the dots at the bottom (due to alignment issues on tight spaces) which I temporarily just hide it for now til design is finalized. See https://github.com/Automattic/wp-calypso/issues/42141#issuecomment-638884014.
This PR also adds a bit of UX improvement by ensuring the footer position always stay consistent. This is so user does not have to reposition the cursor to click on the Next/Previous button when user goes to a different slide on the welcome modal.
Run `yarn dev --sync` on folder `apps/full-site-editing` and test on the block editor on …

Gutenboarding: Fix welcome modal styling issues on Gutenberg 8.2.

---

client/lib/domains/get-selection-domain.js
client/my-sites/domains/domain-management/controller.jsx
client/my-sites/domains/domain-management/edit/site-redirect.jsx
client/my-sites/domains/domain-management/index.jsx
client/my-sites/domains/domain-management/list/index.jsx
client/my-sites/domains/index.js
client/my-sites/domains/paths.js

This is related to and works in concert with the fix implemented in D44220-code as a result of an issue that was raised in p2MSmN-7RI-p2.
The site specific domains list in [/domains/manage/](https://wordpress.com/domains/manage/) becomes confusing when you have both a mapping and a site-redirect with the same domain name.
* Adds a new route `/domains/manage/{domain-name}/redirect/{site}/` to differentiate for site-redirects
* Adds a new component `<SiteRedirect>` with prop `isSiteRedirect` to differentiate when rendering domain status for site redirects
* Follow test instructions in D44220-code
OR
* Create a site-redirect to a domain.
* Create a domain mapping/ register a custom domain with the same name as domain in previous step.
* Visit the domains list …

Domains: Adds mgmt routes that differentiates between domains of different types but same name

---

apps/full-site-editing/full-site-editing-plugin/full-site-editing-plugin.php
apps/full-site-editing/full-site-editing-plugin/readme.txt
apps/full-site-editing/package.json

FSE Verion bump - includes #42850
Part of Part of #42847
It's important to test with and without D44333-code patch applied to your sandbox.
From #42850:
Sandbox `widgets.wp.com` and `example.wordpress.com` (Simple site).
1. Apply D44298-code (these changes). It should result in no changes in the block editor.
1. https://wordpress.com/block-editor should work as before.
1. Starting from [`/new`](https://wordpress.com/new), follow the flow through site creation to the editor.
1. Make a change to the post content.
1. In the editor, the publish button should be replaced with "Launch."
1. The launch button should link to a URL like https://wordpress.com/start/new-launch?siteSlug=example.wordpress.com&source=editor
Repeat the steps with D44333-code (be sure to clear your browser caches). The …

FSE: Bump to 1.7

---

apps/full-site-editing/full-site-editing-plugin/full-site-editing-plugin.php

This is a follow up of https://github.com/Automattic/wp-calypso/pull/42895. It fixes a the plugin's version number in the PHP file so it matches the plugin's version.

FSE: Fix 1.7 version number

---

client/my-sites/customer-home/cards/constants.js
client/my-sites/customer-home/locations/tertiary/manage-site/index.jsx

The new Support Card feature opens a websocket connection to Happy Chat on a very prominent page. As a result, Happy Chat's connection volume has spiked well beyond tested levels and the system is unstable and crashing.
After a revert, we can look together at how we can implement this feature without impacting Happy Chat like this.

Revert "My Home: Try updating card mapping for Support card"

---

apps/full-site-editing/full-site-editing-plugin/block-patterns/class-block-patterns.php
apps/full-site-editing/full-site-editing-plugin/block-patterns/patterns/call-to-action-02.php
apps/full-site-editing/full-site-editing-plugin/block-patterns/patterns/collage-gallery.php
apps/full-site-editing/full-site-editing-plugin/block-patterns/patterns/contact-02.php
apps/full-site-editing/full-site-editing-plugin/block-patterns/patterns/contact-03.php
apps/full-site-editing/full-site-editing-plugin/block-patterns/patterns/contact.php
apps/full-site-editing/full-site-editing-plugin/block-patterns/patterns/description-and-image.php
apps/full-site-editing/full-site-editing-plugin/block-patterns/patterns/food-menu.php
apps/full-site-editing/full-site-editing-plugin/block-patterns/patterns/headline-02.php
apps/full-site-editing/full-site-editing-plugin/block-patterns/patterns/headline.php
apps/full-site-editing/full-site-editing-plugin/block-patterns/patterns/image-and-description.php
apps/full-site-editing/full-site-editing-plugin/block-patterns/patterns/image-and-text.php
apps/full-site-editing/full-site-editing-plugin/block-patterns/patterns/masonry-gallery.php
apps/full-site-editing/full-site-editing-plugin/block-patterns/patterns/numbers.php
apps/full-site-editing/full-site-editing-plugin/block-patterns/patterns/recent-posts-02.php
apps/full-site-editing/full-site-editing-plugin/block-patterns/patterns/recent-posts.php
apps/full-site-editing/full-site-editing-plugin/block-patterns/patterns/three-columns-and-image.php
apps/full-site-editing/full-site-editing-plugin/block-patterns/patterns/three-images-side-by-side.php
apps/full-site-editing/full-site-editing-plugin/block-patterns/patterns/two-images-and-quote.php
apps/full-site-editing/full-site-editing-plugin/block-patterns/patterns/two-images-side-by-side.php

Fixes #41936. That issue [categorized](https://github.com/Automattic/wp-calypso/issues/41936#issuecomment-625396787) block patterns as follows:
- Available block patterns seem to have changed since that image was created, so I had to apply my own best guess for some patterns. 
-  Keep [this comment](https://github.com/Automattic/wp-calypso/issues/41936#issuecomment-635243412) in mind:
> These categories were designed to afford overlaps, so I think some of the "images" and "list" ones should also be in "gallery", for example. The category navigation is going to eventually allow drilling down, so there will be less cases of seeing duplicated content.
- While [some pattern categories were readily available in Gutenberg](https://github.com/WordPress/gutenberg/blob/ac22829574d187b96773afb5e95ee …

FSE: Add Block Pattern Categories

---

client/landing/gutenboarding/components/plans-button/index.tsx
client/landing/gutenboarding/components/plans-modal/index.tsx
client/landing/gutenboarding/onboarding-block/plans/index.tsx
packages/data-stores/src/plans/selectors.ts
packages/plans-grid/src/plans-grid/index.tsx

* Without having a selected or implicit (because of paid domain/design selection) plan, when top-right _View plans_ button label is visible, PlansGrid shouldn't have any preselected column.
* Go to [/new](https://calypso.live/new?branch=update/plans-grid-remove-default-selection) with an empty state.
* Open Plans Grid (by using Plans Button or by advancing to Plans Step).
* No plan should be selected and Confirm/Continue button should be disabled.
* Plan selection, checkout and analytics should work as before.
Fixes #42328

Gutenboarding: update default plan pre-selection

---

client/lib/abtest/active-tests.js

Bump Gutenboarding A/B test date because of https://github.com/Automattic/wp-calypso/pull/42995

Active tests: new slug for gutenboarding

---

client/signup/config/flows.js

* Stop redirecting to editor after launching a site from editor and use the default redirect.
* Go to [/new](https://calypso.live/?branch=update/launch-destination) and create a site
* Launch the site straight from the editor
* You should land in customer home and see this celebration notice:

Gutenboarding: use default redirect after launch

---

client/my-sites/customer-home/cards/tasks/deprecate-editor/index.jsx
client/post-editor/editor-deprecation-dialog/index.jsx

Fixup for #42970 when old translations are used.
Since we continue to use fuzzy translations for the string `Get a head start before we activate it for everyone in the near future. {{support}}Read more{{/support}}.` we still have a `{{date/}}` string in the translation. In a case where a component appears in the string that is not accounted for in the `components` object, [`interpolateComponents` will return the string without any interpolated components](https://github.com/Automattic/interpolate-components/blob/master/src/index.es6#L53), thus we see the components displayed to the user:
In this particular instance I have fixed the translation [but other languages still use the old version](https://translate.wordpress.com/projects/wpcom/-all-translated/273185/), so we need to bring back …

Editor: Temporarily use a 1 July date in old translations of the deprecation notice

---

client/lib/wpcom-xhr-wrapper/index.js

Remove async loading of `lib/user/utils` because it triggers a webpack bug (https://github.com/webpack/webpack/issues/11005) in the `wp-desktop` build.
We'll need to break the circular dependency some other way.
Also, it keeps the issue mentioned by @ChaosExAnima in https://github.com/Automattic/wp-calypso/pull/42763#pullrequestreview-420493883 fixed: the problem with `require( 'lib/user/utils' ).logout` wasn't a circular dependency, but the fact we were `require`-ing (CJS) an ESM module with default export. `require( ... ).default.logout` is necessary in such case.
- verify that desktop app build is fixed
- verify that Jetpack Cloud behaves well when the OAuth token expires

Remove async loading of lib/user/utils as it confuses webpack

---

client/lib/wpcom-xhr-wrapper/index.js

Reverts Automattic/wp-calypso#43012

Revert "Remove async loading of lib/user/utils as it confuses webpack"

---

apps/full-site-editing/full-site-editing-plugin/readme.txt

This PR just fixes a typo for my username in the FSE Plugin. I'm iandstewart in core. :)

FSE: Fix typo in contributor usernames

---

client/my-sites/plans/current-plan/current-plan-thank-you/paid-plan-thank-you.js

From https://github.com/Automattic/wp-calypso/pull/42940#pullrequestreview-423941358:
> Personally, I think that I'd prefer something like Math.max( installProgress, 10 ) to improve readability. But, that's not a blocker.
@ebinnion Not sure by if "not a blocker", you meant it was worth following up in another PR, but I agree that's a more readable approach than the chiamus-like structure used previously. :) 
See #42940 - the detailed steps laid out there are identical.

Jetpack Checklist Modal: Improve ProgressBar Value Readability

---

client/landing/gutenboarding/components/action-buttons/style.scss
packages/plans-grid/src/plans-grid/style.scss

* Use grey background and white color for disabled button
* Go to [/new](https://calypso.live/new?branch=update/plans-grid-disabled-button-style) with an empty state
* Open plans grid using the plans button or advancing to plans step
* Continue/Confirm button should be grey until a plan selection is made

Gutenboarding: update disabled primary button style in plans grid

---

client/assets/stylesheets/gutenboarding.scss

* use `$font-body` variable on Gutenboarding body to get correct font-size when it is defined relatively.
**Before - intent capture**
**After - intent capture**
**Before - plans grid**
**After - plans grid**
* go to [/new](https://calypso.live/new?branch=fix/gutenboarding-font-size) and advance through the flow
* Open domain popover/modal
* Font should be consistent and not small as in _Before_ screens

Gutenboarding: fix font-size

---

client/blocks/comments/post-comment-content.scss

Recent changes to body font sizes in https://github.com/Automattic/wp-calypso/pull/42629 have led to comment excerpts being cropped at the bottom in comments. You can see this happening in Reader Conversations.
This PR changes the max-height to be based on the new body font variables.
Before:
After:
Check out http://calypso.localhost:3000/read/conversations and make sure comment excerpts are not clipped at the bottom.
You can also check the `PostComment` block in Devdocs and look for evidence of clipping:
http://calypso.localhost:3000/devdocs/blocks/post-comment

Comments: fix max height of excerpt and prevent clipping

---

client/my-sites/customer-home/cards/features/help-search/style.scss

Adjusts the design of the (yet to be launched) "Get help" support search card on Calypso "My Home" to [match Design by @olesyabrk](https://github.com/Automattic/wp-calypso/issues/42743#issuecomment-635606611).
~Until https://github.com/Automattic/wp-calypso/pull/42752 is merged you'll need to apply `D43941` to your sandbox in order to see the card.~ It's now merged and the card is enabled on production.
* ~Sandbox the API and your test site.~
* ~Ensure you have applied `D43941` (unless https://github.com/Automattic/wp-calypso/pull/42752 is merged).~
* Checkout this PR and build Calypso.
* Go to the "My Home" via the Calypso UI and look for the "Get help" card.
* You should see it match the design above. Specifically note the required changes:
- aligning the search results to the heading
- …

My Home Support search card - aligns search results and focus state to heading

---

client/reader/list-manage/index.jsx
client/reader/list-stream/index.jsx
client/reader/list/controller.js
client/reader/list/index.js
config/development.json

Adds in a new route handler for /read/list/:owner/:slug/edit, a config setting to control the feature, re-enables the settings cog and edit URL, and a small placeholder UI for the manage page

Add scaffolding for reader list editing

---

client/landing/jetpack-cloud/components/threat-item/index.tsx

* The name of the section isn't always being tracked correctly. This is because we are using [`window.location.href` to get the current section](https://github.com/Automattic/wp-calypso/pull/42819/files#diff-c23e1d50bbefb88d4546c95f5d3d902aR98). This PR fixes this by using a state selector to fetch the current section.
* Go to `http://jetpack.cloud.localhost:3000/` and select a site that has Scan (with at least one threat)
* Go to Scan -> Scanner 
* Click on the header of a threat item
* Verify the `calypso_jetpack_scan_threat_itemtoggle` event was tracked and that it included a property called `section` with `Scanner` as its value.
* Go to Scan -> History 
* Click on the header of a threat item
* Verify the `calypso_jetpack_scan_threat_itemtoggle` event was tracked and that it included a …

Jetpack Cloud: fix the section property of the threat toggle event

---

apps/full-site-editing/full-site-editing-plugin/full-site-editing-plugin.php
apps/full-site-editing/full-site-editing-plugin/mailerlite/subscriber-popup.js
apps/full-site-editing/full-site-editing-plugin/mailerlite/subscriber-popup.php

This introduces a Mailerlite (https://www.mailerlite.com/)  subscriber widget.
Mailchimp subscriber popup has issues (93-gh-dotcom-manage)
Mailerlite is a (cheaper and simpler) mailchimp competitor that I personally use on my blog https://deliber.at . My other blog - https://piszek.com is hosted on WPCOM simple (on purpose). I have no way of introducing mailerlite signup on that blog.
This solves this problem.
- Check out D44264-code 
- If you don't want to set up Mailerlite account, you can use my email list (continue)
- Go to widgets, select mailerlite subscriber popup and drop it into a widget area
- You can use my popup ( account 1726876 , uuid o6h6c1w0c9 )
- Publish the widget
- Go see it in incognito, Scroll a bit, observe popup as in the screenshot.
**Using your account**
- …

Mailerlite subscriber popup widget

---

client/state/media/reducer.js
client/state/media/test/reducer.js

We are currently using the error message to get the media upload error type, which doesn't work for non-English, because the error message in the response payload is localized.
* Use upload error code instead of error message matching to set the error state for media upload request failures.
* Added missing exceeded file size error handling
**Before:**
**After:**
* Boot Calypso and open http://calypso.localhost:3000/media
* Try to upload media for a site that exceeds plan storage limit
* Confirm that you get the storage limit error message instead of generic server error message.
* Confirm that error message gets translated for non-English UI
Related D44299-code

Use error code for media uploads instead of message matching

---

client/my-sites/checkout/composite-checkout/wpcom/components/wp-order-review-line-items.js

* Somehow I missed the warnings about this missing `key` prop when I refactored this component in #42908
* Enter checkout with a gsuite product; verify that no warnings are shown in the console.

composite-checkout: Add key prop to ListItemMeta inside GSuiteUsersList

---

client/my-sites/checkout/composite-checkout/payment-method-helpers.js

* Change the label on the full credits payment method from "WordPress.com Credits: X" to "WordPress.com Credits: X available", to help clarify what that number means.
At the moment it's easy to misunderstand the full credits payment method as changing the product price or using all credits on the account.
Enter checkout with enough credits to cover the purchase (to trigger the full credits payment method) and inspect the label:

composite-checkout: Clarify label for full credit payment method

---

client/my-sites/current-site/stale-cart-items-notice.js

`StaleCartItemsNotice` displays a message for abandoned carts to prompt the user to visit checkout. It currently is configured to disappear after a brief amount of time, but user testing has found this to be annoying because it's hard to get back (it will not display if it has shown up in the past 10 minutes) and some of the places it is shown do not have another easy way to get to checkout (this is a separate issue).
In this PR we make the notice remain until it is dismissed or a page navigation occurs.
- Add a product to your cart and visit checkout.
- Close calypso and wait 10 minutes.
- Visit the Plans page: http://calypso.localhost:3000/plans
- Hopefully the notice will appear. If it doesn't, wait longer and try again.
- Once the notice appears, make sure it does not disappear until …

Remove duration from StaleCartItemsNotice

---

client/lib/abtest/active-tests.js

* Dial up the allocation to 10% users for the white glove A/B test created in https://github.com/Automattic/wp-calypso/pull/42783
* Go through the signup flow, verify that you get assigned to the test.

Launch white glove offer A/B test to 10% EN-US

---

client/my-sites/people/edit-team-member-form/edit-user-form.jsx
client/my-sites/people/invite-people/index.jsx

In this PR, we remove the "This user is a contractor, freelancer, consultant, or agency." checkbox on user invitation screen for P2 sites.
Create a new P2 site through the wordpress.com/start/wp-for-teams signup flow. Go to the user invitation screen and select a role like "editor". You should not see the contractor checkbox. The same for editing a user. Now, using a non-P2 site, you should see that field in both places.

p2: remove ContractorSelect

---

client/lib/stripe/index.js
packages/composite-checkout/src/lib/payment-methods/stripe-credit-card-fields.js

This passes the current locale string to Stripe when initializing stripe.js which powers our Credit card forms in both old and new checkout.
This will localize the error messages that Stripe returns as well as the form field placeholders.
Fixes https://github.com/Automattic/wp-calypso/issues/38439
- Visit http://calypso.localhost:3000/me/account and change your language to French.
- Add a plan to your cart and visit old checkout. 
- Verify that the placeholder for the credit card expiration field reads `MM/AA`.
- Enter an invalid credit card number and press submit. Verify that the displayed error is localized to French.
- Visit new checkout. You'll need to add `?flags=composite-checkout-force` to the URL to override the locale detection that blocks it for now.
- Verify that the …

Checkout: pass locale to Stripe

---

apps/full-site-editing/bin/sync-newspack-blocks.sh
apps/full-site-editing/full-site-editing-plugin/editor-gutenboarding-launch/index.ts
apps/full-site-editing/full-site-editing-plugin/premium-content/index.js
apps/full-site-editing/full-site-editing-plugin/wpcom-block-editor-nav-sidebar/src/wpcom-block-editor-nav-sidebar.tsx
apps/full-site-editing/package.json

Unbreaks a yarn build with an empty cache.
```
@automattic/full-site-editing: $ check-npm-client && ./bin/sync-newspack-blocks.sh --nodemodules
@automattic/full-site-editing: Syncing files to FSE…
@automattic/full-site-editing: Oops! Something went wrong! :(
@automattic/full-site-editing: ESLint: 7.1.0
@automattic/full-site-editing: ESLint couldn't find the plugin "@wordpress/eslint-plugin".
```
Props @scinos 
Also adds some text domain modifications that should have maded it in via #42583

Fix missing yarn dependency for the eslint plugin

---

client/landing/gutenboarding/components/domain-picker-button/index.tsx
client/landing/gutenboarding/components/domain-picker-modal/index.tsx
client/landing/gutenboarding/components/domain-picker-popover/index.tsx

Depends on https://github.com/Automattic/wp-calypso/pull/43045. 
https://github.com/Automattic/wp-calypso/pull/43045 introduces some changes to DomainPicker API. This PR adapts Gutenboarding to those changes. 
1. Open [/new](https://calypso.live/new?branch=update/use-new-domain-picker-api) of this branch
2. Open [/new](http://wordpress.com/new) of production
3. Test as many interactions as possible with Domain Picker
4. UX should be 1:1 with no regressions

Adapt to new domain-picker API changes

---

client/my-sites/checkout/composite-checkout/test/composite-checkout.js

Fixes regression added in
https://github.com/Automattic/wp-calypso/pull/43026

Fix order of stripe hook provider in composite checkout test

---

packages/composite-checkout/src/lib/payment-methods/paypal.js

This modifies the PayPal submit button in composite checkout so that when the transaction is in the 'redirecting' status, it displays "Redirecting to PayPal…".
Attempt a PayPal transaction and make sure the text of the button changes as described above.

composite-checkout: Display "Redirecting to PayPal…" when paypal is redirecting

---

apps/full-site-editing/.eslintrc.js

Adds `dist` directories to eslint ignore in FSE plugin. I realized that the eslint command in the newspack sync script was taking a very long time to complete (>5 minutes) (since this is run during `yarn install`, I thought yarn was broken). After removing the error suppression code, I noticed it was reporting thousands of errors in the dist files. 
After making this fix, yarn install completes much more quickly.
1. `yarn install` should still work
2. `yarn run prepare` from apps/full-site-editing should be much more quick

FSE plugin: Ignore dist directories in eslint config

---

client/my-sites/checkout/composite-checkout/wpcom/components/wp-checkout-order-summary.js

In #42854 we added plan features to the Checkout summary for the business plan. This adds features for all active WordPress.com plans.
**All Plans:**
- "Free domain for one year" unless a domain is in the cart, then the bundling message will be on the domain line item
**Personal:**
- Remove WordPress.com ads
- Limit your content to paying subscribers
**Premium:**
- Unlimited access to our library of Premium Themes
- Subscriber-only content and simple payment buttons
- Track your stats with Google Analytics
**Business:**
- Install custom plugins and themes
- Drive traffic to your site with our advanced SEO tools
- Track your stats with Google Analytics
- Real-time backups and activity logs
**Ecommerce:**
- Install custom plugins and themes
- Accept payments in 60+ countries
- Integrations …

Checkout: add summary features for each of the WP.com plans

---

client/my-sites/people/invite-people/index.jsx

* For the Invite Links feature on P2 sites: show a loading indicator (by using `is-busy` button class) when user is generating invite links.
* Go to http://calypso.localhost:3000/people/new/< YOUR-P2-TEST-SITE > or **People > Invite**
* Click **Generate new link** and verify that the button has a "busy" animation, as the page waits to refresh

P2: Show loading indicator when generating invite links

---

client/my-sites/customer-home/cards/constants.js
client/my-sites/customer-home/cards/features/help-search/index.jsx
client/my-sites/customer-home/locations/tertiary/manage-site/index.jsx

Removes a Query component that I think isn't necessary. It looks like it was mistakenly held over from [the Inline Help component](https://github.com/Automattic/wp-calypso/blob/master/client/blocks/inline-help/popover.jsx#L169) this card was based on.
That `< QuerySupportTypes />` component is necessary in the Inline Help widget because it prepares the contact form by running a few API calls and loading some assets — e.g. it opens a Happy Chat connection to see if Chat is available, pulls in Directly JS/CSS so that's ready to go... But from what I can tell, this new Help Search card doesn't offer any direct access to the Contact form, it simply links to the Help page. So it doesn't need to make any of those API calls.
This change is necessary because Happy Chat is not set up to handle a …

Help Search: Don't query for available support types

---

client/components/jetpack/threat-history-list/index.jsx
client/components/jetpack/threat-history-list/style.scss
client/landing/jetpack-cloud/sections/scan/controller.js
client/landing/jetpack-cloud/sections/scan/history/index.jsx
client/landing/jetpack-cloud/sections/scan/history/style.scss
client/landing/jetpack-cloud/sections/scan/index.js
client/landing/jetpack-cloud/sections/scan/main.tsx
client/landing/jetpack-cloud/sections/scan/style.scss
config/development.json

* Extract scan history logic from scan page and create a new `ThreatHistoryList` component which can be used in multiple places
* If on WordPress.com instead of Jetpack.com, display the `ThreatHistoryList` component on the scan root page
* Adds a new `/scan/:site/:filter?` route to accommodate the history filter on the scan root page
* Move styles around as appropriate
* Boot this PR locally on jetpack cloud dev environment. Check that the scan page, and scan history page all works normally. Threats should be displayed and filterable as usual. Threats should be fixable as usual. A page for "Scan" and a page for "History" should still work normally.
* Now boot this PR locally in calypso dev environment. Check that the scan page contains the threat history list below the normal scan page …

Jetpack Cloud: Break out threat history list and use on scan page on wpcom

---

client/components/jetpack/activity-card/index.jsx
client/components/jetpack/daily-backup-status/index.jsx
client/components/jetpack/sidebar/index.jsx
client/landing/jetpack-cloud/sections/settings/index.js
client/lib/jetpack/is-jetpack-cloud.ts
client/lib/jetpack/paths.ts
client/my-sites/backup/paths.ts

* Use function to build settings path for jetpack components, conditionally linking to different places depending on if used in Jetpack.com or WordPress.com
* Update all settings path uses in jetpack components to use the new function
* New approach to detecting jetpack.com/jetpack cloud
1. Boot Jetpack Cloud
2. Navigate to `/backup`
3. Activate needs credentials state by setting the `doesRewindNeedCredentials` on the `DailyBackupStatus` component to true
4. Click "Activate restores" and verify you are taken to `/settings/:siteSlug`
5. Navigate to `/backup/activity-log`
6. Activate needs credentials state by setting the `doesRewindNeedCredentials` on a `ActivityCard` component to true
7. Click "Actions", then "Enter Server Credentials" on that Activity Card. Verify you are taken to …

Use function for Jetpack Components settings links

---

client/lib/analytics/utils/url-parse-amp-compatible.js

* Use `.get()` method of `URLSearchParams` object to acquire `tk_amp`.
* Fixes an issue first introduced in https://github.com/Automattic/wp-calypso/commit/b2cc20b1e854136a4d4b38f0ee898ef5114f3b10 by @sgomes. Property access on `URLSearchParams` object doesn't work as one would expect. Must use `.get()`.
Run Calypso locally and visit this URL: http://calypso.localhost:3000/start/user?ref=alp-lp&tk_amp=1*s4a2cn*amp_client_id*YW1wLWQzY3J6b2JOMmpXazhSZ3NkRnhJelE.*aff*MzAxMDI.*sid*RU4tMTU0NTkwMzg.&_gl=1*1ptehrf*_ga*YW1wLVRvYXBDT2R0WHZKVnV3WG0tQTlEc2c.
- Filter Network requests by `refer.wordpress.com` and confirm a 200 status.
---
Try without this fix and confirm broken w/ no `refer.wordpress.com` connection.

Fix AMP analytics URL parser.

---

client/my-sites/domains/domain-management/edit/navigation/enhanced.jsx

* For domain only sites the "Find similar domains" nav item wasn't working because there is no route to add new domain on the same site. We should open the domain-only flow when you click on this button
* Open a domain only status page and click on the "Find similar domains" nav item - it should open the domain-only flow with the search term populated

Fix Find similar domains nav item for domain only sites

---

client/me/security-checkup/index.jsx
client/me/security-checkup/style.scss
client/me/security-section-nav/index.jsx
client/me/security/controller.js
client/me/security/index.js
config/development.json

This PR sets the groundwork for a new Security Checkup feature (described [here](https://wp.me/p99Zz8-1gb)), which is currently set up behind the `security/security-checkup` feature flag, which is limited to dev environments for now.
The goal is to show a quick overview of a user's security and account recovery settings. For now, this initial PR does not represent a wrapped product, but a basic skeleton to support further iteration.
At present, this PR includes the following items:
* Create `SecurityCheckupComponent` with basic styling and wire it into the security nav
* Wire in the following links and basic assessments:
- Account email
- 2FA configuration
- Recovery email
- Recovery phone/SMS number
- Connected apps
I'll address these in subsequent iterations/PRs.
* The security nav is …

Initial work on a new Security Checkup feature.

---

client/my-sites/domains/domain-management/edit/card/notices/expiring-soon.jsx
client/my-sites/domains/domain-management/edit/domain-types/mapped-domain-type.jsx
client/my-sites/domains/domain-management/edit/domain-types/registered-domain-type.jsx
client/my-sites/domains/domain-management/edit/domain-types/site-redirect-type.jsx

* we should not display the delete/cancel nav item in the domains status screen if you're not the owner of the purchase
* we should also not show any of the renew buttons in the domain status screen if you're not the owner of the purchase
* add another user as admin to a site with some purchases and test that he's not displayed the delete/cancel and the renew buttons when he opens the domain status screen
This is how the screens should look like:

Don't show the renew and cancel/delete items if the subscription is owned by someone else

---

client/my-sites/site-settings/settings-security/main.jsx

* The goal is to remove the server credentials from the Security tab and add a Banner in its place. This Banner contains a CTA to the server credentials new location at the Jetpack tab (no yet implement).
* Run this PR with `yarn start`.
* Go to `http://calypso.localhost:3000/settings/security/<youSiteSlug>?flags=jetpack/features-section`.
* Verify that the server credentials aren't visible.
* Verify that there is a Banner with a CTA that points to `/settings/jetpack` (broken link for the moment).
* Go to `http://calypso.localhost:3000/settings/security/<youSiteSlug>`.
* Verify that the server credentials are visible.
* Verify that there is no Banner.
Fixes 1179060693083348-as-1179378358843971

Jetpack Cloud: replace the credentials with a Banner when Jetpack section is enabled

---

client/lib/signup/step-actions/index.js
client/signup/config/flows-pure.js
client/signup/config/step-components.js
client/signup/config/steps-pure.js
client/signup/steps/p2-site/index.jsx
client/signup/steps/p2-site/style.scss

Part of introducing the revamped signup flow for the P2 project.
In this PR, we refactor the `start/wp-for-teams` signup flow to `start/p2` to better match the product branding.
In an incognito window, navigate to `start/p2`. You should be able to go through the P2 (formerly WP for Teams) signup flow without a problem.

P2: signup: refactor start/wp-for-teams to start/p2

---

client/signup/steps/domains/index.jsx

This fixes the missing Back button on the Domain page when going through the site Launch flow. The button is also missing when adding a new site by, directly, accessing https://wordpress.com/start (while logged in).
The button appears on the other flows (Add New site, Getting started).
The fix relies on setting the Back button to be shown only when there's a `backUrl` set.
Previously, visibility depended on a `state.ui.siteSelectionInitialized` which is not being initialized for this flow.
1. Test that Launch flow now shows the `Back` button
- create a site
- go through the Launch flow
- At the domain step, click `Use a domain I own` link.
- `Back` button should be on the top left corner
2. Test that directly adding a new site to an account shows the `Back` button
- make sure you're …

Sets back button visibilty to depend on the back URL

---

apps/full-site-editing/full-site-editing-plugin/full-site-editing-plugin.php
apps/full-site-editing/full-site-editing-plugin/readme.txt
apps/full-site-editing/package.json

Bump FSE plugin for 1.9 release.
Includes:
- https://github.com/Automattic/wp-calypso/pull/43084 (@noahtallen)
- https://github.com/Automattic/wp-calypso/pull/42911 (@kwight)
- https://github.com/Automattic/wp-calypso/pull/39328 (@noahtallen)
- https://github.com/Automattic/wp-calypso/pull/43070 (@akirk)
- https://github.com/Automattic/wp-calypso/pull/42885 (@artpi)
- https://github.com/Automattic/wp-calypso/pull/42583 (@akirk)
- https://github.com/Automattic/wp-calypso/pull/42996 (@ianstewart)
- https://github.com/Automattic/wp-calypso/pull/42761 (@ockham / @p-jackson)
- https://github.com/Automattic/wp-calypso/pull/43116 (@sirreal)
Testing:
- Apply D44727-code to sandbox
- Test editor
- Check features in release notes are present

FSE: Release 1.9

---

apps/wpcom-block-editor/src/calypso/features/iframe-bridge-server.js
client/gutenberg/editor/calypsoify-iframe.tsx

* Fix media modal opened through inline image reopening when cancelled.
Explanation why this is happening in https://github.com/Automattic/wp-calypso/issues/40934#issuecomment-641460747.
* Follow the steps mentioned in https://github.com/Automattic/wp-calypso/issues/40934.
* The modal should not reopen again.
Fixes #40934

Gutenframe: Fix media modal opened through inline image reopening when cancelled.

---

client/blocks/reader-recommended-sites/index.jsx

In p5PDj3-4ML-p2, @hacchism reported that a user can click on a recommendation 'dismiss' icon before the recommendation has loaded. This results in an error because we don't have a site to dismiss yet.
This PR adds a check to see if we have a recommendation before displaying the dismiss icon.
Go to http://calypso.localhost:3000/following/manage and refresh the page.
While the recommendations are initially loading, there should be no dismiss icon visible. 
(The dismiss icon may still appear a moment or two before the text, but that's fine - the dismiss will work as it has a site ID.)
Loading - no dismiss icons:
After loading:

Reader recommended sites: only show dismiss button once we have a recommendation to show

---

client/lib/analytics/cart.js
client/my-sites/checkout/composite-checkout/composite-checkout.js
client/my-sites/checkout/composite-checkout/payment-method-helpers.js
client/my-sites/checkout/composite-checkout/record-analytics.js
client/my-sites/checkout/composite-checkout/wpcom/hooks/use-shopping-cart.ts
client/my-sites/checkout/composite-checkout/wpcom/index.js
client/my-sites/checkout/composite-checkout/wpcom/types.ts
client/my-sites/checkout/composite-checkout/wpcom/types/checkout-payment-method-slug.ts
packages/composite-checkout/src/components/checkout-payment-methods.js

* Includes three additional events from old checkout in composite checkout:
- `calypso_checkout_switch_to_{payment_method}`, which fires when the user selects a different payment method
- `calypso_checkout_page_view`, which fires exactly once, simultaneously with the `CHECKOUT_LOADED` event
- `calypso_cart_product_add`, which fires simultaneously with the `ADD_CART_ITEM` event
We need to verify that these events are recorded correctly to tracks. The relevant behavior is triggered by:
- Entering composite checkout, for `calypso_checkout_page_view`
- Switching between several different payment methods, for `calypso_checkout_switch_to_{payment_method}`. Also need to check that the payment method slugs here agree with those used in old checkout
- Entering checkout with a product added in the …

composite-checkout: add missing calypso checkout events

---

client/lib/abtest/active-tests.js
client/my-sites/checkout/checkout-system-decider.js

This removes the composite checkout abtest and sends 100% of page loads to new checkout versus old if they pass our other conditions, which are currently:
- Site is not jetpack (atomic sites are fine).
- Cart contains no jetpack plans.
- URL contains no unknown products (just to protect against things we haven't tested).
- Country code is US.
- Locale is EN.
- Currency is USD.
Visit checkout with the above conditions met, and verify that you see new checkout.

Stop composite checkout abtest and enable variant

---

client/lib/abtest/active-tests.js
client/my-sites/checkout/checkout-system-decider.js

Reverts Automattic/wp-calypso#43163
Also bumps the test date and changes the mix to 100% composite checkout. This should allow e2e tests to continue to run until we update them for composite checkout.

Revert "Stop composite checkout abtest and enable variant" but enable 100% variant

---

client/components/jetpack/sidebar-menu-items/index.jsx
client/components/jetpack/sidebar/index.jsx
client/components/jetpack/sidebar/menu-items/calypso.jsx
client/components/jetpack/sidebar/menu-items/index.jsx
client/components/jetpack/sidebar/menu-items/jetpack-cloud.jsx
client/lib/jetpack/paths.ts
client/my-sites/sidebar/index.jsx

**NOTE: Due to the nature of the changes involved, this PR is quite large. Review with care!**
* Create a common `JetpackSidebarMenuItems` component to hold sidebar menu items for both Jetpack Cloud and the Jetpack sidebar section in Calypso.
* Change the My Sites sidebar and Jetpack Cloud sidebar to use this new component.
* Slightly change Tracks event names for the following actions, to bring Cloud in line with Calypso and make unifying the two easier:
* Activity Log (event name change in both Calypso and Cloud)
* Backup (`menu_item` param change)
* Scan (`menu_item` param change)
* Settings (event name change in Cloud only)
Fixes `1179060693083348-as-1179545706707209`
* This is a pretty large PR, so I'm assuming there'll be lots of little revisions to make before it's ready to go.
* …

Jetpack Cloud: Unify sidebar items into one shared component

---

packages/composite-checkout/src/components/button.js

This PR fixes a missing border on the disabled checkout button.
Before:
After:
* Load up the new composite checkout
* Check that the pay button has a border when disabled.

Composite checkout: Fix missing border

---

client/blocks/comments/post-comment-list.jsx
client/blocks/comments/post-comment-list.scss

* This adds a link to the Comments page from the Reader
Verify that button's design is okay and that it appears only for sites which the user is able to manage comments for and on posts where there are actually comments to manage. 
cc @bluefuton, @gwwar, @jancavan (based on the initial issue - sorry if wrong people!)
Fixes #19720

Reader: Add Link to Manage Comments

---

client/my-sites/checkout/composite-checkout/composite-checkout.js
client/my-sites/checkout/composite-checkout/wpcom/hooks/product-variants.js

In https://github.com/Automattic/wp-calypso/pull/42723 I added a bunch of query components from old checkout to new checkout, including `QuerySitePlans`, but I accidentally added them to `renderContactDetails` instead of the output of `CompositeCheckout`. One result of this is that the `state.sites.plans` Redux state was not populated, which meant that the local data used to determine if a plan should receive a prorated discount was not available. In new checkout, that data is used only for the plan variant selector (all the rest of the prices come from the shopping cart endpoint) and so the selector is showing the un-discounted price for each plan variant.
This PR moves the Query components to their correct location, but even though that makes the data available, we were still not using …

composite-checkout: Fix discounted price in variant picker

---

apps/full-site-editing/full-site-editing-plugin/donations/donations-tabs.js
apps/full-site-editing/full-site-editing-plugin/donations/edit.js
apps/full-site-editing/full-site-editing-plugin/donations/fetch-status.js
apps/full-site-editing/full-site-editing-plugin/donations/index.js
apps/full-site-editing/full-site-editing-plugin/donations/loading-error.js
apps/full-site-editing/full-site-editing-plugin/donations/loading-status.js
apps/full-site-editing/full-site-editing-plugin/donations/upgrade-plan.js

This PR adds a check for a valid plan when inserting the Donations block, and displays a prompt to upgrade if the user is required to do so. Based on the Premium Content block process.
See: #42856 
* On this branch locally, run `yarn dev --sync` to sync the changes to your sandbox.
* Sandbox the API, and a test site that has no plan.
* On that test site, start a new post at `/wp-admin/post-new.php`.
* Add a Donations block.
* Verify the Donations block loads with a spinner while making a call to `https://public-api.wordpress.com/wpcom/v2/sites/:site_id/memberships/status`.
* When the API call completes, the block should display the upgrade prompt.
* Check the API error state by misspelling the endpoint – this should trigger it properly.
* Click the upgrade button and complete the upgrade …

Earn: Add a plans check to the Donations block.

---

apps/full-site-editing/full-site-editing-plugin/premium-content/editor.css
apps/full-site-editing/full-site-editing-plugin/premium-content/style.css

Fixes https://github.com/Automattic/wp-calypso/issues/43041 where buttons on small screens could push out page layout. This PR adds a media breakpoint to so we have smaller buttons on smaller screens.
| Published Before | Published After |
| <img width="984" alt="before" src="https://user-images.githubusercontent.com/1270189/84326047-f7a83f80-ab30-11ea-9d32-f32ae90ead61.png"> | <img width="1051" alt="after" src="https://user-images.githubusercontent.com/1270189/84326066-ff67e400-ab30-11ea-937e-08b629e5677c.png"> |
| Editor Breakpoint |
| ------------- | 
| ![breakpoint](https://user-images.githubusercontent.com/1270189/84325937-c2035680-ab30-11ea-801a-7ac4a0e3c13e.gif) |
- (Requires a sandbox) Checkout this branch and either apply the linked diff, or run …

Earn: When payment buttons are viewed on smaller screens allow for smaller button sizes

---

client/state/data-layer/wpcom/activity-log/update-credentials/index.js

This pull request fixes a bug where all credentials update errors would yield the same generic user-facing notice, and internal error codes weren’t correctly being recorded in the tracks event. I suspect the shape of the error objects changed at some point:
1. Try to save SSH credentials that are correct except for an incorrect password or private key.
2. Verify that the “couldn’t connect” error message (or localised equivalent) is shown.
Partially addresses 5409-gh-jpop-issues

Fix credentials update error response interpretation

---

client/me/security-checkup/account-email.jsx
client/me/security-checkup/account-recovery-email.jsx
client/me/security-checkup/account-recovery-phone.jsx
client/me/security-checkup/connected-applications.jsx
client/me/security-checkup/icons.js
client/me/security-checkup/index.jsx
client/me/security-checkup/navigation-item.jsx
client/me/security-checkup/two-factor-authentication.jsx
client/me/security-checkup/two-factor-backup-codes.jsx

In addition to the above, I pushed all the state/querying dependencies into the components themselves, as per @klimeryk's suggestion in [this comment](https://github.com/Automattic/wp-calypso/pull/43101#discussion_r437612292) on #43101.
The largest change in this area was for Two Factor Authentication, where we're now accessing user settings in a cleaner fashion instead of interacting directly with the passed-in UserSettings object.
I also added a check for Two Factor backup code verification that is only performed when 2FA is enabled.
* Move all the row-specific logic out of `SecurityCheckupComponent`, and push it into row-specific components
* Re-implement the 2FA row logic to use helper functions for the user settings
* Add a row/check for whether the user has verified their 2FA backup …

Refactor code to manage Security Checkup items in dedicated components

---

apps/wpcom-block-editor/src/wpcom/features/tracking/delegate-event-tracking.js
apps/wpcom-block-editor/src/wpcom/features/tracking/wpcom-block-donations-plan-upgrade.js

Let's add a Tracks event for when users of the Donations block click on the "upgrade plan" button.
* Create a new free Simple site, and sticker it with `fse-donations-block` (can also be done from the site's blog RC).
* Apply this branch to your local Calypso install. You do _not_ need Calypso running to test this PR.
* Sandbox the following: the API, `widgets.wp.com`, and your new test site.
* Sync the FSE plugin to your sandbox: run `yarn dev --sync` from `/apps/full-site-editing`.
* Build the WP.com block editor app: `npx lerna run build --scope='@automattic/wpcom-block-editor'`
* Sync the block editor app build to your sandbox (`scp -rp apps/wpcom-block-editor/dist/* <sandbox-hostname>:public_html/widgets.wp.com/wpcom-block-editor/` from the Calypso root should work – make sure to use …

Donations: Add a Tracks event for plan upgrades.

---

client/my-sites/checkout/composite-checkout/wpcom/components/coupon.js
client/my-sites/checkout/composite-checkout/wpcom/components/field.js
client/my-sites/checkout/composite-checkout/wpcom/components/wp-checkout-order-review.js
client/my-sites/checkout/composite-checkout/wpcom/components/wp-checkout-order-summary.js
client/my-sites/checkout/composite-checkout/wpcom/components/wp-checkout.js
client/my-sites/checkout/composite-checkout/wpcom/components/wp-order-review-line-items.js
packages/composite-checkout/src/components/checkout-steps.js
packages/composite-checkout/src/lib/payment-methods/stripe-credit-card-fields.js

This is extracted from https://github.com/Automattic/wp-calypso/pull/43223 which fixes the e2e tests for composite checkout. This is all the changes to composite checkout needed for those tests to pass.
- This should not cause any user-visible effects.
- Visit composite checkout and verify that everything works as expected. Notable changes: savings sublabels (eg: a coupon code), credit card fields.

composite-checkout: Add classNames and other attributes to make e2e testing easier

---

client/my-sites/checkout/composite-checkout/wpcom/components/wp-checkout-order-summary.js
client/my-sites/checkout/composite-checkout/wpcom/hooks/has-renewal.ts

* We added plan-specific feature lists in #43080 but forgot to prevent the free domain feature from being displayed on renewals; this PR fixes that.
* Enter composite checkout with a plan renewal in the cart, using `?flags=composite-checkout-force` if needed. Verify that the "free domain for one year" feature is not listed in the sidebar.
* Enter composite checkout with a new plan purchase in the cart, but not a domain; check that the "free domain for one year" feature is listed.
* Enter composite checkout with a new plan purchase and a domain in the cart. Check that the "$domain free for a year with your plan" feature is listed.

composite-checkout: Do not show free domain as a feature on renewals

---

client/my-sites/checkout/checkout/domain-refund-policy.jsx

* It is possible to have more than one domain refund policy, causing the `DomainRefundPolicy` component to throw a warning. This PR just uses the `index` parameter as a key attribute to avoid this.
* Enter composite checkout with domain items involving more than one refund policy and check the console for warnings. (I'm not sure exactly how to trigger this!)

fix: Add key to DomainRefundPolicy list items

---

client/me/account-close/confirm-dialog.jsx
client/me/account-close/confirm-dialog.scss

* Provides a series of alternatives in the dialog confirming the deletion of your account
Visit `/me/account/close` and trigger the dialog to close your account. Verify that the dialog looks okay, and that the links work for each option by either triggering a support dialog or redirecting you to the page where you can "try it". 
Clicking the "Proceed" primary button should take you to the current screen where you can enter your username to confirm account deletion. 
cc @bluefuton
Fixes #43211

Account Closure: Warn of Alternative Options

---

client/my-sites/people/invite-people/index.jsx

* Exclude updates to certain props (props for Invite Links we're sure are unrelated to the Invite People form) from triggering the `this.setState( this.resetState() );` inside `UNSAFE_componentWillReceiveProps( nextProps )`
* e2e tests should pass
* smoke test: Invite page should work the same
Fixes #43247

Invites: fix e2e fails

---

client/blocks/comments/post-comment-list.jsx
client/blocks/comments/post-comment-list.scss

Sorry, this is a defect caused by #43093 which I didn't spot: on a post with no comments, the Submit Comments form overlaps with the "Follow Conversation" button.
This PR reverts back to how it was before #43093; when there's a single action, keep things in the same line.
A second row is still necessary when there's two actions in order to prevent an overlap, and that should still work fine.
cc @gwwar, @bluefuton

Reader: Fix Comments Form Overlap with Button

---

client/lib/wpcom-undocumented/lib/undocumented.js
client/reader/list-manage/index.jsx
client/reader/list-manage/list-form.jsx
client/state/data-layer/wpcom/read/lists/index.js
client/state/reader/lists/actions.js
client/state/reader/lists/reducer.js
client/state/reader/lists/selectors.js
client/state/reader/lists/test/actions.js

* Implements data layer logic for updating reader lists.
* Removes a now-unused wpcom-undocumented function.
* Makes the update form at `/read/list/:user/:slug/edit` functional.
* Open a list at `/read/list/:user/:slug/edit`.
* Try updating the name, slug, privacy settings, and description.

Add reader list update form functionality

---

client/components/jetpack/log-item/style.scss
client/components/jetpack/server-credentials-wizard-dialog/style.scss
client/components/jetpack/threat-dialog/style.scss
client/components/jetpack/threat-history-list/index.jsx
client/components/jetpack/threat-history-list/style.scss
client/components/jetpack/threat-item-subheader/style.scss
client/components/jetpack/threat-item/style.scss
packages/calypso-color-schemes/src/shared/color-schemes/_jetpack-cloud.scss

* Normalize colors on Jetpack cloud components so that components are compatible with both the cloud and dotcom.
* Remove unsused variables from the Jetpack color scheme.
* Set Scan history segmentControl as primary and update its styling.
* Reduce the screen width needed to unwrap date/times on Scan history
Before | After
--|--
* Spin up this PR and open wordpress.com.
* Add `?flags=jetpack/features-section` to your URL.
* Select a Jetpack site.
* Inside the new Jetpack menu, select Scan.
* Ensure the layout looks good in all screen widths.
* Repeat the process above for the cloud and confirm that changes do not break the existing layout.

Jetpack: normalize colors on cloud components

---

client/components/promo-section/promo-card/cta.tsx
client/my-sites/scan/wpcom-upsell.tsx

The upsell links should be `self` target instead of `_blank`. This PR update the PromoCardCta component to allow us to select if the link is self target.
- Selected an AT site without Jetpack
- Go to the Jetpack Scan section and click on Upgrade to Business Plan. It'll take you to the checkout page in the same tab.

Jetpack: The upsell link should be self target

---

client/my-sites/checkout/checkout-system-decider.js
packages/composite-checkout/README.md
packages/composite-checkout/src/components/checkout-error-boundary.js
packages/composite-checkout/src/public-api.js

This adds a [React error boundary](https://reactjs.org/docs/error-boundaries.html) around the entire component tree of composite checkout starting at `CheckoutSystemDecider`. Hopefully this will never be hit because composite checkout already has several layers of error boundaries within `CheckoutProvider` but it will give us the opportunity to:
1. Prevent the user from seeing a blank screen if something at the top level fails.
2. Record such errors and report them to logstash where they will ping us in Slack.
- Trigger a fatal error inside the `CompositeCheckout` component itself.
- Verify that the logstash logs for the string `composite checkout load error` get a new entry.

composite-checkout: Add error boundary around top level

---

client/components/jetpack/what-is-jetpack/index.tsx
client/components/jetpack/what-is-jetpack/style.scss
client/my-sites/scan/style.scss
client/my-sites/scan/wpcom-upsell.tsx

Improve some styles on WPCOMScanUpsell component and add to the bottom WhatIsJetpack component.
Before:
After:
- Apply these changes and active Jetpack section with `?flags=jetpack/features-section`
- Select AT site without Jetpack
- Go to Scan section and see the new What is Jetpack block and the styles applied like the screenshot

Jetpack: Improve styles on WPCOMScanUpsell +added WhatIsJetpack

---

client/my-sites/checkout/composite-checkout/wpcom/components/wp-checkout-order-summary.js
packages/composite-checkout/src/components/checkout-steps.js

Some minor UI fixes which include:
- Remove unnecessary space at the top of the screen
- Cleanup some punctuation in the help text
- Add interactivity to help text link text
**Before**
**After**
You can review the screenshots or load up the checkout and inspect manually.

Composite checkout: layout design tweaks

---

client/lib/jetpack/paths.ts

* Updates paths for Backup and Scan to point to the new Jetpack settings page. 
* Get Backup for a Jetpack site.
* Go to WP.com with the section feature flag.
* In Jetpack -> Backup, click "Activate Restores".
Fixes 1179060693083348-as-1179705725205698.

Sets path to point to new Jetpack settings page

---

client/landing/gutenboarding/onboarding-block/design-selector/style.scss

This is a bit of a speculative PR based on my personal preference. It removes the `max-width: none` override on the Design step in Gutenboarding so that the step has the same width as all the other steps (currently `1440px`).
I found it a bit jarring at a wide screen width moving between the design step and other steps, so thought I'd whip this up. Happy to throw it away if the consensus is to go in another direction!
* Remove `max-width: none` override on the Design step in Gutenboarding
Note the wide Design step after selecting a domain:
Note the Design step is the same width as the other steps after selecting a domain:
* Go to `/new` in full screen on a large monitor (e.g. greater than 1440px wide).
* Enter a site title and select a domain.
* The width of the Design step should be the …

Gutenboarding: Remove max-width override on the Design step

---

client/my-sites/checkout/checkout/index.jsx
client/my-sites/checkout/composite-checkout/composite-checkout.js
client/state/receipts/assembler.js

There are three places in the code where `createReceiptObject` is called. One is in old `Checkout`, one is in `CompositeCheckout`, and one is in the Redux `fetchReceipt` action thunk which is used by `CheckoutThankYou` after checkout.
In the first two locations, the raw transaction endpoint data returned from the server for the `purchases` and `failed_purchases` properties is flattened from an object-of-arrays-of-objects keyed by blog_id into a single array. `createReceiptObject` expects both to be arrays which it then maps into a specific schema. (They were actually flattening `failed_purchases` into a new property called `failedPurchases` and leaving the old `failed_purchases` property untouched, which caused part of the confusion in my first attempt to fix this.)
In the third location, …

Receipts: Flatten purchases/failed_purchases inside createReceiptObject

---

apps/full-site-editing/.eslintrc.js
apps/full-site-editing/full-site-editing-plugin/wpcom-block-editor-nav-sidebar/src/attach-sidebar.tsx
apps/full-site-editing/full-site-editing-plugin/wpcom-block-editor-nav-sidebar/src/components/.eslintrc.js
apps/full-site-editing/full-site-editing-plugin/wpcom-block-editor-nav-sidebar/src/components/create-page/index.tsx
apps/full-site-editing/full-site-editing-plugin/wpcom-block-editor-nav-sidebar/src/components/create-page/style.scss
apps/full-site-editing/full-site-editing-plugin/wpcom-block-editor-nav-sidebar/src/components/nav-sidebar/index.tsx
apps/full-site-editing/full-site-editing-plugin/wpcom-block-editor-nav-sidebar/src/components/nav-sidebar/style.scss
apps/full-site-editing/full-site-editing-plugin/wpcom-block-editor-nav-sidebar/src/components/view-all-posts/index.tsx
apps/full-site-editing/full-site-editing-plugin/wpcom-block-editor-nav-sidebar/src/components/view-all-posts/style.scss
apps/wpcom-block-editor/src/calypso/features/iframe-bridge-server.js
client/gutenberg/editor/calypsoify-iframe.tsx

_**Note to anyone reading this while preparing a release of the FSE plugin**_
* Re-arrange files to make room for more components
* Add "View all posts" button
* `a8c.WpcomBlockEditorNavSidebar.allPostsLabel` hook so calypso can override label
* `a8c.WpcomBlockEditorNavSidebar.allPostsUrl` hook so calypso can send user back to calypso rather than wp-admin
* Add "Create new post" button
* `a8c.WpcomBlockEditorNavSidebar.createPostLabel` hook so calypso can override label
* `a8c.WpcomBlockEditorNavSidebar.createPostUrl` hook so calypso will create new post using iframe'd block editor
* `a8c.WpcomBlockEditorNavSidebar.linkTarget` hook so calypso can ensure links open in the …

Nav sidebar: Add "view all" and "create new" buttons to sidebar

---

client/landing/gutenboarding/components/signup-form/index.tsx

Raised in pbAok1-11X-p2#comment-2074. Broadly the idea is:
Autofocusing the email field on the signup step in Gutenboarding prevents the user from seeing the rest of the step / context for entering their info. This change only sets the `autofocus` attribute on the field if the user is in a larger than `small` viewport (e.g. desktop).
* Set `autoFocus: false` on the email field in the Gutenboarding signup form if the viewport is `<` than `small`.
* In an incognito / private browser window, go to `/new` and complete the flow until you get to the signup step
* On desktop, the email field should automatically be focused — you can start typing an email address without having to click the field
* On mobile, at this step the email field should not be focused, you will need to click the email to …

Gutenboarding: Prevent autofocus on email field in signup on mobile

---

client/landing/gutenboarding/onboarding-block/style-preview/style.scss

This PR fixes a CSS issue on Safari on mobile devices at narrow viewports where there is extra whitespace between the font options button and the preview on the style step in Gutenboarding.
* The `height: 100%` attribute was extending the font options area too far on mobile in Safari iOS, specifically, so this change moves it to only apply to the desktop layout.
* On Safari on iOS mobile:
* Go to `/new` and complete steps until you reach the font selection / style step.
* The preview should appear directly below the font selection button, as in the screenshots above
* Test that this doesn't introduce a visual regression: on desktop (e.g. Safari, FF, Chrome), ensure that the preview still extends to the bottom of the onboarding block.
Fixes #

Gutenboarding: Fix font style preview position on mobile by removing height attribute

---

client/my-sites/domains/domain-management/change-site-address/index.jsx
client/my-sites/domains/domain-management/contacts-privacy/index.jsx
client/my-sites/domains/domain-management/controller.jsx
client/my-sites/domains/domain-management/dns/index.jsx
client/my-sites/domains/domain-management/domain-connect-mapping/index.jsx
client/my-sites/domains/domain-management/edit-contact-info/index.jsx
client/my-sites/domains/domain-management/edit/navigation/enhanced.jsx
client/my-sites/domains/domain-management/index.jsx
client/my-sites/domains/domain-management/list/index.jsx
client/my-sites/domains/domain-management/manage-consent/index.jsx
client/my-sites/domains/domain-management/name-servers/index.jsx
client/my-sites/domains/domain-management/security/index.jsx
client/my-sites/domains/domain-management/site-redirect/index.jsx
client/my-sites/domains/domain-management/transfer/index.jsx
client/my-sites/domains/domain-management/transfer/transfer-out/index.jsx
client/my-sites/domains/domain-management/transfer/transfer-to-other-site/index.jsx
client/my-sites/domains/domain-management/transfer/transfer-to-other-user/index.jsx
client/my-sites/domains/index.js
client/my-sites/domains/paths.js

* In order to keep the context when managing your domain via the all sites view we need to duplicate every domain management route.
Don't panic - the PR looks bigger than it actually is.
From an all sites domains view (/domains/manage) you should be able to navigate all the domain management screens without this changing the left navigation bar. In more details this PR handles:
* Site redirect domain status page and it's back button
* Incoming transfer domain status page and the back button
* Dns settings for mapped domain and the back button
* Name servers and dns for registered domains and the back button
* Update your contact information, Edit contact info and Manage consent and all back buttons
* Connect your domain for mapped domain with Domain Connect
* Review your domain security
* …

Add the all sites domain management paths

---

client/my-sites/sidebar/index.jsx

Hides the site setup progress indication from the sidebar when accessed from the WP Desktop app.
Before | After
--- | ---
To help stabilize accidental breakages, @Automattic/serenity added a simplified Home view just for WP-Desktop that doesn’t show any primary tasks (including the Site Setup List, which is considered a primary task): pbAPfg-sx-p2
We likely forgot to hide the setup progress indicator from the sidebar for WP-Desktop that’s causing an inconsistency as reported in https://github.com/Automattic/wp-calypso/issues/43235  
This is more a temporary workaround, I think that in the long term we should support the site setup on the desktop app (cc @Automattic/Create).
- In the desktop repo, point the calypso submodule to this branch: `cd calypso && git fetch && git checkout …

Home: Hide setup progress on the desktop app

---

client/my-sites/backup/index.js
client/my-sites/backup/style.scss
client/my-sites/backup/wpcom-upsell.tsx
client/my-sites/scan/style.scss

Add Backup upsell from Free to Business plan in the Backup section. 
**Case:** from Free to Business plan
The design:
In Calypso:
- Apply these changes and select an AT without Jetpack
- Go to the Backup section and you will see the Upsell page. Click on the CTA button and it'll take you to the Business plan checkout.
- Review the copy.

Jetpack.Backup section: Add upsell from Free to Business plan

---

client/root.js

* Updates the landing page for Jetpack non-Atomic sites from Reader (`/read`) to Stats (`/stats`).
* Set your primary site as a Jetpack non-Atomic site on https://wordpress.com/me/account.
* Open wordpress.com.
* Ensure you see your site stats for your primary site.
* Confirm that the landing page doesn't change for other site types.
See full context on p6TEKc-3Jb-p2

Jetpack: makes stats the landing page for Jetpack non-Atomic sites

---

client/blocks/signup-form/index.jsx

This PR fixes an error when creating a Social (Google) account in the WooDNA flow. It probably also affects the existing WooCommerce onboarding flow.
- Go into the Woo DNA connection flow, logged out.
- Input a GMail email that you haven't used for WordPress.com.
- On the signup form, click "Continue with Google", and continue with the process.
- On `master`, you'll get [this error](https://cloudup.com/cXPGtrSWpIv). On this PR it will work.

Fix social account creation on the WooCommerce and WooDNA flows

---

client/blocks/signup-form/index.jsx
client/jetpack-connect/signup.js

I found some weird behaviours in the Woo DNA flow while doing further testing, this PR solves them.
- Use the Woo DNA flow as usual, logged out.
- Go create a new account.
- On the signup form, set your password to be the same as your username.
- On `master`, you'll see an error notice and you'll get back to the initial "screen" of the flow. On this branch, you'll see the error notice but you won't be moved from the signup form.
- Use the Woo DNA flow as usual, logged out.
- Input an existing username.
- On the full login form, instead of putting the password, click "Create new account". The username should be prefilled.
- Click "Create your account". Because the username is taken error will appear with a link to the "log in" form.
- Back on the "email-only" login form, put an username …

Fix the UI/state logic transitions on the WooDNA flow

---

client/my-sites/backup/style.scss
client/my-sites/scan/style.scss

Remove the space between the icon and the card title on the Upsell page
- Select a simple wpcom site without plans. Active `?flags=jetpack/features-section`
- Check if the odd space between the icon and the title is removed

Remove the space between the icon and the card title

---

client/landing/gutenboarding/hooks/use-domain-suggestions.ts
client/landing/gutenboarding/hooks/use-on-login.ts
client/landing/gutenboarding/onboarding-block/domains/index.tsx
client/landing/gutenboarding/stores/onboard/selectors.ts
packages/domain-picker/src/constants.ts
packages/domain-picker/src/domain-name-explanation/index.tsx
packages/domain-picker/src/domain-picker/index.tsx
packages/domain-picker/src/domain-picker/style.scss
packages/domain-picker/src/hooks/use-domain-suggestions.ts

**Note: It's much easier to review with whitespace ignored (add w=1 param to the diff URL).**
From https://github.com/Automattic/wp-calypso/issues/43133:
1. Visit [/new](https://calypso.live/new?branch=updte/handle-empty-state-gracefully). 
2. Test against the changes above.
Related to: https://github.com/Automattic/wp-calypso/issues/43133

Add empty state UI and "View more results" button and hide categories

---

client/blocks/reader-avatar/style.scss
client/blocks/reader-combined-card/style.scss
client/blocks/reader-post-card/style.scss

* I noticed after I deployed the changes to font sizing from 13px to 14px in #42941 that spacing around the bylines looked off. This PR fixes instances where descenders might get cut off due to max-height/overflow hidden on the container, and vertically aligns avatars and the tag icon.
| -------- | ------- |
| <img width="307" alt="Screen Shot 2020-06-05 at 1 13 04 PM" src="https://user-images.githubusercontent.com/2124984/83905653-0d33f880-a730-11ea-8542-e7005837623d.png"> | <img width="317" alt="Screen Shot 2020-06-05 at 1 12 48 PM" src="https://user-images.githubusercontent.com/2124984/83905654-0dcc8f00-a730-11ea-9ed5-9effd7bce148.png"> |
| <img width="327" alt="Screen Shot 2020-06-05 at 1 14 44 PM" src="https://user-images.githubusercontent.com/2124984/83905651-0c9b6 …

Reader: Tweak spacing and sizing around bylines

---

client/my-sites/checkout/checkout-thank-you/header.jsx

* Use snake case for tracks event property on the checkout thank you page.
Came across this console error while testing something else:
Complete a checkout and verify that the above error is not thrown on the thank you page.

Thank you page: Use snake_case in property name

---

client/my-sites/checkout/checkout-system-decider.js
packages/composite-checkout/src/components/checkout-provider.js

I missed a typo in the review of #43268. This updates the error boundary messages in Checkout for consistency (and shared translations).

Checkout: update error boundary messages for consistency

---

client/blocks/jetpack-backup-creds-banner/index.jsx
client/lib/jetpack/paths.ts
client/my-sites/activity/activity-log-item/index.jsx
client/my-sites/plans/current-plan/current-plan-thank-you/thank-you.js
client/my-sites/plans/current-plan/jetpack-checklist/index.tsx

* This PR updates the path we send users based on the `jetpack/features-section` flag in the following locations:
* Activity log item.
* Backup credentials banner.
* Scan thank you notice.
* Backup and Scan checklist item.
Load this PR and test the following on a Jetpack site with and without the `jetpack/features-section` flag enabled:
* Activity log item: Purchase Backup and wait for full backup to complete, then check Activity Log and click three dots next to backup item.
* Backup credentials banner: Same as above, but click the banner.
* Scan thank you notice: Purchase Scan and navigate to `/plans/my-plan/[site]?thank-you&product=jetpack_scan` then click Add Server Credentials Now.
* Backup and Scan checklist item: Purchase a non-free plan and navigate to `/plans/my-plan/[site]` and …

Updates settings page paths

---

client/my-sites/checkout/composite-checkout/wpcom/components/wp-order-review-line-items.js

* Add "Free with your plan" callout to domain mappings when added to a site with a plan.
- Enter checkout with a domain mapping on a site that already has a plan (Domains -> add a domain to this site -> I already own a domain -> Map a domain). Verify that in checkout there is a "Free with your plan" callout on the mapping line item.
- Enter checkout with a domain _registration_ on a site that already has a plan. Verify that there is a "First year free" callout on the registration line item - this is existing behavior that should not change.
Fixes #43329

composite-checkout: Add "Free with your plan" copy to (free) domain mapping line items

---

client/my-sites/backup/wpcom-upsell.tsx
client/my-sites/scan/wpcom-upsell.tsx

* Hide the AL promo card when the site has a Personal or Premium plan.
* Should we merge this two components into one?
* Prerequisite: 1) WPCOM site with a free plan, 2) Jetpack section enabled.
* Run this PR.
* Go to `http://calypso.localhost:3000/backup/<your-site-slug>?flag=jetpack/features-section`. 
* Verify that the Activity Log promo card appears at the bottom.
* Go to `http://calypso.localhost:3000/scan/<your-site-slug>?flag=jetpack/features-section`. 
* Verify that the Activity Log promo card appears at the bottom.
* Upgrade your site's plan to either Personal or Premium.
* Go to `http://calypso.localhost:3000/backup/<your-site-slug>?flag=jetpack/features-section`. 
* Verify that the Activity Log promo card **doesn't** appear at the bottom.
* Go to …

Jetpack section: hide Activity Log promo from the upsell page for Personal and Premium plan owners

---

client/lib/domains/tlds/wpcom-multi-level-tlds.json

Originally introduced in https://github.com/Automattic/wp-calypso/pull/18648. Looks like we did not update this list as we onboarded other second level TLDs. As a result, users buying domains via `/domains` got the wrong product assigned.
* Go to `/domains`. Search for a `.co.uk` domain. Verify that the `is-available` endpoint returns the correct product ID (327, product slug: `dotcodotuk_domain`).
* Now, select the domain and choose "Just buy a domain".
* A request to `https://public-api.wordpress.com/rest/v1.1/me/shopping-cart/no-site` should fire. Before the patch, the product ID would be wrong (ID 326), with the patch it should be correct.
Check other TLDs added to the list as well - plus double-check me if I missed any.

Domains: Update multi level TLD list

---

client/landing/gutenboarding/hooks/use-on-site-creation.ts
client/landing/gutenboarding/stores/onboard/actions.ts
client/state/sites/launch/actions.js

Reverts Automattic/wp-calypso#43246
I was [getting](https://app.circleci.com/pipelines/github/Automattic/wp-e2e-tests-canary/675/workflows/f15044af-fedc-4c64-a247-095598106c38/jobs/18583) `Looks like creating account is taking to long( 150000ms ). Please try again in a while. ` after merging #43246. I re-ran tests and still saw the same error. Reverting for now.

Revert "Gutenboarding: Add feature flag to redirect to Site Editor upon Site Creation"

---

client/blocks/comments/post-comment-content.scss

When a Gutenberg editor is used to create comments, image captions use the `figcaption` element without a class name. Currently no styling is applied to these captions. This PR adds the same styling as the caption would receive in Reader full post.
Before:
After:

Comments: style Gutenberg captions

---

apps/full-site-editing/full-site-editing-plugin/wpcom-block-editor-nav-sidebar/src/attach-sidebar.tsx
apps/full-site-editing/full-site-editing-plugin/wpcom-block-editor-nav-sidebar/src/components/nav-sidebar/index.tsx
apps/full-site-editing/full-site-editing-plugin/wpcom-block-editor-nav-sidebar/src/components/nav-sidebar/style.scss

**_Note to anyone reading this while preparing a release of the FSE plugin_**
* Show 10 most recently modified posts
* Only shows posts where the status has the `show_in_list` flag
* Highlight the item that's active in the editor
* Shows a label for the post status if the item is anything other than published (e.g. [Draft])
* Hide slug if the post doesn't have one yet (drafts that have never been published don't have slugs)
* Styling changes to make things a little closer to mock up (still not the whole way there yet)
* Create `apps/full-site-editing/.wp-env.override.json` and fill it with this content to opt-in to the feature
```
{
"config": { …
```

Nav Sidebar: show 10 most recently edited posts/pages in sidebar

---

client/landing/gutenboarding/hooks/use-selected-plan.ts
client/landing/gutenboarding/onboarding-block/plans/index.tsx
client/lib/abtest/active-tests.js
packages/data-stores/src/plans/selectors.ts
packages/plans-grid/src/plans-grid/index.tsx

* Automatically change the domain to be the wp.com subdomain when selecting _Free Plan_.
* Automatically switch to _Premium Plan_ if the selected plan is _Free Plan_ and user picks a paid domain.
Demo: https://cloudup.com/cz6txa0y85x
Note: This change has been made possible after the [Plans Grid design update](https://github.com/Automattic/wp-calypso/pull/43206) which clarify the direct relation between free/paid plans and free/paid domains. 
* Go to [/new](https://calypso.live/new?branch=update/gutenboarding-plans-and-domains-behaviour)
* Open Domains Modal and select a paid domain => plan = _Premium Plan_
* Open the Plans Modal and select _Free Plan_ => domain = wp.com subdomain
* Open Domains Modal and select a paid domain => plan = _Premium Plan_
Fixes #43253 and partly #42601 …

Gutenboarding: update plans and domains behaviour

---

client/components/search/index.jsx

This PR resolves #42656
* clicking the X button in the search component should focus back to the input field
**Before**
**After**
**Open State**
* Go to http://calypso.localhost:3000/read/search?q=test&focus=1
* Click the X button
* Input field should be focused and you should be able to write a term
**Pinned State**
* Go to http://calypso.localhost:3000/plugins?s=test
* Click the X button
* Input Field should collapse and lose focus

Search: focus back on input when clicking close

---

client/landing/gutenboarding/onboarding-block/acquire-intent/site-title.tsx
client/landing/gutenboarding/onboarding-block/acquire-intent/style.scss
client/landing/gutenboarding/onboarding-block/acquire-intent/tip.tsx

* Add the input hint "Don't worry, you can change it later." under the site title input.
* 3s fade-in delay, 1s fade-out delay.
* Go to `/new`
* After 3s delay, you should see the input hint "Don't worry, you can change it later." under the site title input.
* Enter a site title.
* After 1s delay from first keystroke, the message should fade out.
* Erase the site title.
* After 3s delay from the time site title is empty, the message should fade in.
Fixes https://github.com/Automattic/wp-calypso/issues/42943

Gutenboarding: Add hesitation nudge on intent gathering.

---

client/landing/gutenboarding/hooks/use-on-site-creation.ts
client/landing/gutenboarding/stores/onboard/actions.ts
client/state/sites/launch/actions.js

Take Two of #43246, which I accidentally reverted last night (when I really meant to revert #43345 after I got e2e errors in staging) :man_facepalming: 
Reverts Automattic/wp-calypso#43357

Gutenboarding: Add feature flag to redirect to Site Editor upon Site Creation (take two)

---

client/my-sites/sidebar/index.jsx
client/state/purchases/selectors.js

* When the `jetpack/features-section` flag is enabled, fill the **Plan** star icon in the sidebar for any site with a paid plan or active Jetpack product purchase; otherwise, leave it unfilled/outlined.
Fixes `1179060693083348-as-1179608945635681`
* Start Calypso and enable the `jetpack/features-section` feature flag.
* With respect to the star-shaped **Plan** icon in the sidebar, verify the following scenarios:
* For non-Jetpack sites, the icon is **unfilled**.
* For Jetpack sites with a Free plan and no purchased Jetpack products, the icon is **unfilled**.
* For Jetpack sites with a paid plan, the icon is **filled**. (This includes Atomic sites.)
* For Jetpack sites with no paid plan but an active purchase for Backup, Scan, or Search, the icon is **filled**.

Jetpack Cloud: Fill the Plan sidebar icon for paids plan or products

---

client/lib/domains/tlds/wpcom-multi-level-tlds.json

Reverts Automattic/wp-calypso#43351
Looks like there's a bigger issue going on - this change prevented the .uk-specific extra contact form from showing up for .co.uk domains.

Revert "Domains: Update multi level TLD list"

---

client/my-sites/backup/wpcom-upsell.tsx
client/my-sites/scan/wpcom-upsell.tsx

Remove` is-wide-layout` class from the Backup/Scan upsell pages
Before:
After:
- Apply the changes and activate the flag `?flags=jetpack/features-section`
- Select a simple site with Free plan
- Go to Backup/Scan section and see that both upsell pages aren't wide.

Remove is-wide-layout from the Backup/Scan upsell pages

---

apps/full-site-editing/full-site-editing-plugin/site-editor/index.php

We don't want demo templates to be active any longer since they might interfere with templates that Seedlet blocks theme provides.
1. Apply the FSE plugin sync patch to Dotcom.
2. Test with a site that has `core-site-editor-enabled` sticker.
3. Notice the change in front end rendering. Instead of demo template you should get "no templates found" message.

Site Editor: disable demo templates on stickered sites

---

client/components/domains/registrant-extra-info/index.jsx
client/lib/domains/tlds/wpcom-multi-level-tlds.json
client/my-sites/checkout/checkout/domain-details-form.jsx

This fixes what https://github.com/Automattic/wp-calypso/pull/43351 was aiming to, as well as the bug that was uncovered because of it (and probably dating all the way back to https://github.com/Automattic/wp-calypso/pull/20750?), which was the reason for the revert in https://github.com/Automattic/wp-calypso/pull/43384
Go to Domain Managment -> Add domain. Try with a regular gTLD, like .com and .blog, you should have normal checkout.
Now, try with a ccTLD that requires additional info, like `.uk`, `.co.uk`, `.ca`, `.fr` - you should have an additional step in the checkout process.
Please also follow the testing instructions from https://github.com/Automattic/wp-calypso/pull/43351 to make sure that issue is fixed as well.

Choose the correct additional info TLD form for second level TLDs

---

config/desktop.json
config/development.json
config/horizon.json
config/production.json
config/stage.json
config/test.json
config/wpcalypso.json

Part of https://github.com/Automattic/wp-calypso/issues/43249 this adds a feature flag to calypso so we can safely land rename PRs in Calypso
Once this lands, let's update https://github.com/Automattic/wp-calypso/pull/42848 and https://github.com/Automattic/wp-calypso/pull/43192 to use this feature flag.
No changes on development or production

Earn: add feature flag for safe rename of Simple Payments and Recurring Payments blocks

---

client/landing/gutenboarding/components/action-buttons/style.scss
client/landing/gutenboarding/onboarding-block/acquire-intent/site-title.tsx
client/landing/gutenboarding/onboarding-block/acquire-intent/style.scss

* Nudge hint text color should be `studio-gray-50`.
* Nudge hint font size should be `14px`.
* Nudge hint icon should be `18px`.
* "Skip for now" button should be `studio-gray-50` on border and text color.
* "Skip for now" button should be `studio-gray-60` on border and text color on hover.
* "Go back" text link color should be `studio-gray-50` (to make it consistent with Skip button).
*  The nudge hint appears after 3 seconds of delay after loading the page. Doesn't matter if the input is focused or blurred.
* The nudge hint will not disappear after entering a site title value.
Test if all the above requirements are met on `/new`.
Fixes https://github.com/Automattic/wp-calypso/issues/43383

Domain Picker: Nudge hint tweaking.

---

packages/components/src/button/style.scss

* Updates to flatten the buttons did not update the padding to vertically center the text; this PR addresses that by evening out the top and bottom padding.
Before
After
* Check out button styles across Calypso; top and bottom padding on buttons should be the same, text should be vertically centered

Buttons: Center text vertically

---

client/components/jetpack/sidebar/menu-items/index.jsx
client/my-sites/scan/index.js
client/state/selectors/is-site-wpcom.js

* Hide scan section in new jetpack menu for WPCOM sites
* Navigate to Calypso & activate the jetpack features section
* Verify the scan section does not appear for any WPCOM site

Remove jetpack/scan from WPCOM sites

---

client/landing/gutenboarding/components/action-buttons/style.scss

As raised in pbAok1-15f-p2 the skip buttons only show a subtle colour change if you tab to them via the keyboard. This change adds a more prominent blue box-shadow to show when it's focused.
* Add focus styling for the skip action button so that it uses a highlight colour box-shadow, using that same styling as we're using on the primary buttons (e.g. if you tab to the Continue button on the Style step)
* Go to `/new`.
* Don't enter a site title, but tab on the keyboard to the "Skip for now" button. It should be highlighted blue.
* Check across browsers that it looks okay.
Fixes #

Gutenboarding: Add separate style for focus state of skip buttons so that it's more visible

---

client/landing/gutenboarding/onboarding-block/acquire-intent/site-title.tsx
client/landing/gutenboarding/onboarding-block/acquire-intent/style.scss

- ✅  Safari and Chrome on iOS 13
- ✅  IE11
- ✅  FF desktop and FF Android
- ✅  Samsung Internet
Worth noting that this is pretty robust since it just uses "placeholder" prop that is natively supported pretty much everywhere.
Fixes https://github.com/Automattic/wp-calypso/issues/43191

Add placeholder to site title input

---

client/landing/gutenboarding/components/header/index.tsx
client/landing/gutenboarding/onboarding-block/colors.scss
client/landing/gutenboarding/onboarding-block/create-site-error/index.tsx
client/landing/gutenboarding/onboarding-block/create-site-error/style.scss
client/landing/gutenboarding/onboarding-block/create-site/index.tsx
client/landing/gutenboarding/onboarding-block/create-site/style.scss
client/landing/gutenboarding/onboarding-block/edit.tsx
packages/data-stores/src/site/actions.ts
packages/data-stores/src/site/reducer.ts

* Displays an error message if create site returns with an error.
Full flow:
* Apply D44621-code
* Attempt to create a site using http://calypso.localhost:3000/new
* Clicking `Continue` on the `/new/plans` step should begin showing `<CreateSite />` before transitioning to the error message showing a "Go Back" button to return to the last known good step.
Error only:
* `ENTRY_LIMIT=entry-gutenboarding yarn start`
* Visit http://calypso.localhost:3000/new/error (I'll remove this route before merge)
Mobile:
Desktop:
Fixes #41067

Add error handling for new site creation failure modes

---

client/me/security-checkup/index.jsx
client/me/security-checkup/social-logins.jsx

* This PR expands on the work from #43101 and #43142 and adds a basic list of the number of social logins that a user has enabled.
* Open the UI via a local build or calypso.live and navigate to `/me/security`.
* If you're using calypso.live, manually add `?flags=security/security-checkup` to the URL.
* Select the "Security Checkup" option in the nav dropdown/menu.
* Verify that the "Social Logins" item appears and shows the correct number of connected logins.
* Click on the "Social Logins" row and ensure that you end up in the Social Login UI.
Part of the work for #26874.

Add social login information to security checkup

---

apps/full-site-editing/full-site-editing-plugin/posts-list-block/blocks/posts-list/editor.scss

* FSE Post List Block is now deprecated. WordPress.com installations that have already used it are now getting a notice message to update to the new Block. In that case, this PR resolves #41658 by making sure that the button content doesn't get cut out.
**Before**
**After**
* In Calypso root folder run
```
cd apps/full-site-editing
yarn build
```
* Setup https://github.com/Automattic/ajax-env with FSE plugin
* Go to http://localhost:4759/wp-admin/admin.php?import=wordpress
* Import [sitetitle.wordpress.2020-06-17.001.xml.zip](https://github.com/Automattic/wp-calypso/files/4797222/sitetitle.wordpress.2020-06-17.001.xml.zip) (extract first)
* Edit the Homepage of the imported content
* Your editor should load with the imported content of a site that used the deprecated Post List Block …

Post List Block: make sure button doesn't shrink beyond its content

---

client/my-sites/domains/domain-management/edit/navigation/style.scss

* Update the font-size of the domain navigation item subtitle to be 14px
before:
after:
* Verify that the font-size of the domain navigation subtitles is smaller (14px)

Update the font size of the domain navigation item subtitle

---

client/blocks/signup-form/index.jsx
client/blocks/signup-form/passwordless.jsx
client/blocks/signup-form/social.jsx
client/blocks/signup-form/style.scss
client/components/social-buttons/apple.js
client/components/social-buttons/google.js
client/lib/abtest/active-tests.js
client/signup/config/flows-pure.js
client/signup/config/step-components.js
client/signup/config/steps-pure.js
client/signup/controller.js
client/signup/steps/domains/index.jsx
client/signup/steps/user/index.jsx

Check pbxNRc-m0-p2. The screens for the new flow can be seen in [Figma](https://www.figma.com/file/0hUWErRWnMytiVvViKAMLu/Simplified-Account-step-AB-test)
- change flow order and
- **Control** - right now the control funnel looks like:
**Account -> Domain -> Plans -> Checkout**
- **Variant** - in this variant, we want to test this:
**Domain -> Plans -> Simplified Account -> Checkout**
**Control** Account step
**Variant** Simplified account step (passwordless)
ℹ️ AB test is set to 50/50 chances and only for US. 
1. Go to /start
2. Select the 'variantPasswordless' AB test variant and make sure newSiteGutenbergOnboarding is on 'control' (the latter takes precedence):
or 
```
localStorage.setItem( 'ABTests', '{"newSiteGutenbergOnboarding_20200612":"control","passwordlessAfterPlans_20200608":"v …
```

Signup test: Use Passwordless signup after Plans step

---

config/desktop.json
config/horizon.json
config/production.json
config/test.json

We've forgot to enable the P2 signup flow and features for all platforms, especially prod!
In this PR, we enable it.
Unproxy yourself and navigate to `wordpress.com`. Select a P2 site. It should behave the same way as on a proxied `wordpress.com` (ie no upsell nudges, a few menu items are hidden, etc).

P2: enable the P2 signup flow on every platform

---

client/my-sites/backup/style.scss
client/my-sites/backup/wpcom-upsell.tsx
client/my-sites/scan/style.scss
client/my-sites/scan/wpcom-upsell.tsx

Heading in the _Scan > Scanner_ section didn't look like a heading anymore (both in Calypso and cloud). This PR fixes this issue. Additionally, it standardizes how headers and subheaders are displayed in the _Backup_ and _Scan_ sections (see screenshots below).
* The issue was introduced because the `scan__header` class was used to style headers (`FormattedHeader`) in the scan upsell section
* In this fix, we revert to the previous styles of `scan__header` and upsell headers are styled separately
* The PR reflects the changes in the scan section to backup as well
* This part of the code could benefit from some refactoring to avoid styles duplication and standardize class names according to the guidelines mentioned in [the components …

Jetpack: fix and standardize headings styles in backup and scan

---

packages/composite-checkout/src/lib/payment-methods/paypal.js

This may not be necessary, but we have seen strange errors where React
seems to be getting confused about the contents of the DOM when removing
nodes. It's possible this is because PayPalButtonContents sometimes
returns a string and sometimes returns a component.
- Visit composite checkout and choose the PayPal payment method.
- Verify that the submit button looks ok when loading/disabled, when enabled, and that it changes correctly when clicked.

Checkout: Make sure PayPalButtonContents always returns a component

---

client/state/media/reducer.js
client/state/media/test/reducer.js
client/state/media/utils/test/transientItems.js
client/state/media/utils/transientItems.ts
client/state/selectors/get-media-item-server-id-from-transient-id.js
client/state/selectors/get-media-item.js
client/state/selectors/get-transient-media-item.js
client/state/selectors/test/get-media-item-server-id-from-transient-id.js
client/state/selectors/test/get-media-item.js
client/state/selectors/test/get-transient-media-item.js

* Adds a new `transientItems` reducer which duplicates the transient media item handling in the `media/store` flux reducer while de-duplicating media item tracking which is handled by the `queries` reducer and the `MediaQueryManager`.
While there are changes to selectors, the reducer is not added to the store, so transient items will not be being tracked and the existing logic of the `getMediaItem` selector will continue to work, ignoring transient items. This is provable by the fact that the existing unit tests for that selector, which do not add transient items to the tested state, continued to work without modification.
* Ensure all unit tests pass
Note: This PR is part of an iteration to remove the `media/store` flux reducer. It is the first of a series of 4 PRs. Also, see #39379 for …

State: Add transient media items reducer

---

client/components/jetpack/sidebar/index.jsx
client/my-sites/activity/activity-log-v2/style.scss

* Always use new Jetpack Cloud menu
* Boot Jetpack Cloud and verify the new menu is there and works

Jetpack Cloud: Switch to New Menu

---

client/me/help/help-contact/index.jsx

Removes the "Limited Chat Availability" notice on the Contact page and the Inline Help widget.
Go to http://calypso.localhost:3000/help/contact — there shouldn't be a notice above the form.
Open the Inline Help widget and click Contact Us — there shouldn't be a notice above the form.

Remove Limited Availability notice for Chat

---

client/components/jetpack/business-at-switch/index.tsx
client/components/jetpack/business-at-switch/style.scss
client/components/jetpack/wpcom-business-at/index.tsx
client/lib/jetpack/wpcom-upsell-controller.tsx
client/my-sites/backup/index.js
client/my-sites/scan/index.js
client/state/automated-transfer/constants.ts

* Knowing if a site is eligible for Automated Transfer is key if we want to show users a screen to trigger the process. For that reason, this PR adds a switch component that controls when and which users should see the Automated Transfer page based on the result of querying the eligibility of the current site. While the query is in progress, we display a loading page using placeholder components.
* Prerequisite: non-Atomic Business site plan.
* Run this PR with the `jetpack/features-section` flag enabled.
* Go to Jetpack > Backup or visit `http://calypso.localhost:3000/backup/[site]`.
* Verify that you see the placeholder/loading page (you might not be able to see this if the eligibility query/request happens too fast).
* Verify that you see the Automated Transfer page.
Fixes …

Jetpack section: add switch to control when we display the Business AT

---

client/lib/abtest/active-tests.js
client/my-sites/checkout/checkout-system-decider.js
client/my-sites/checkout/checkout/checkout-container.jsx
client/my-sites/checkout/checkout/index.jsx
client/my-sites/checkout/composite-checkout/composite-checkout.js
client/my-sites/checkout/composite-checkout/test/composite-checkout-thank-you.js
client/my-sites/checkout/composite-checkout/use-get-thank-you-url.js
client/my-sites/checkout/controller.jsx
client/my-sites/checkout/upsell-nudge/index.jsx
client/my-sites/checkout/upsell-nudge/plan-upgrade-upsell/index.jsx
client/my-sites/checkout/upsell-nudge/plan-upgrade-upsell/style.scss

* This PR implements the test plan explained here pbxNRc-lW-p2
**Scenario 1** _(Testing behavior of `showBusinessPlanBump` A/B test)_
* Signup for a new account from http://calypso.localhost:3000/start.
* Add a Premium plan to cart and complete the purchase
* Verify the following:
- That you are shown the Business upgrade upsell if on the `variantShowPlanBump` variation of `showBusinessPlanBump` test.
- That you are shown the concierge upsell if on the `control` variation of `showBusinessPlanBump` test (no matter if you're in the `offer` or `noOffer`group for the `conciergeUpsellDial` test).
If on the plan upsell nudge, verify the following:
- Clicking the `No thanks ...` button should take you to the checklist page.
- Clicking the `Yes, I'd love to try ....` button should take you to the …

AB Test for Business bump offer

---

client/my-sites/domains/domain-management/list/index.jsx

This fixes a [development mode warning](https://github.com/Automattic/wp-calypso/pull/42954#discussion_r442379372) for the 'Manage all your domains' link.
Should be fairly trivial, but spin Calypso locally, go to /domains/manage/<site_slug> and verify no errors are shown in the console regarding the missing key.

Fix missing key attribute warning for Manage All Domains link

---

client/components/promo-section/docs/example.tsx
client/lib/plans/features-list.js
client/me/memberships/main.jsx
client/my-sites/earn/home.tsx
client/my-sites/earn/main.jsx
client/my-sites/earn/memberships/add-edit-plan-modal.jsx
client/my-sites/earn/memberships/index.jsx
client/my-sites/earn/memberships/products.jsx

This PR:
- Renames "Recurring Payments" to "Payments"
* I'll handle the one-time payment option in a seperate PR
* Modifying the copy in the following card, will be handled by the Simple Payments rename PR
- Sandbox, Set-up recurring payments
- Check out this PR
- Verify no copy changes in non-production environment, or add `?flags=-earn/rename-payment-blocks` and refresh
- Verify that copy changes make sense in development

"Recurring Payments" -> "Payments"

---

client/blocks/reader-list-item/README.md
client/blocks/reader-list-item/style.scss

Another small fix following the recent changes to body font size (including https://github.com/Automattic/wp-calypso/pull/42629). 
I noticed that the titles of Reader recommendations in Manage Following were too large and were being clipped when they went to two lines:
This PR fixes it:
Visit http://calypso.localhost:3000/following/manage and ensure the recommendation titles appear at the correct size.

Reader: fix recommendation title font size

---

client/me/purchases/remove-purchase/index.jsx
client/my-sites/domains/domain-management/edit/navigation/enhanced.jsx

* We want to track the use of the delete domain button in the domain status screen so we're adding a new tracks event to track it
* Click on the "Delete your domain permanently" button and verify that the tracks event is fired

Add tracks event to the delete domain button

---

client/my-sites/people/invite-people/index.jsx

In this PR, we make the `editor` role as default one for the P2 sites on the Invite People screen.
Navigate to `http://calypso.localhost:3000/people/new/` with a non-p2 site. You should get `follower` selected by default. Now, from the sidebar, select a P2 site. The default selection should switch to `editor`. Try switching to some other non-p2 site — it should change to `follower` again.

P2: preselect 'editor' role in Invite People

---

client/my-sites/site-settings/form-general.jsx

In this PR, we remove the "Change footer credit" section from the Settings page for P2 sites.
Navigate to `http://calypso.localhost:3000/settings/general/` with a non-p2 site. You should see the option to change footer credit. Now, switch to a P2 site. That section should disappear.

P2: remove Footer Credit option from Settings menu

---

client/blocks/reader-full-post/_content.scss
client/blocks/reader-full-post/style.scss

* Moves the Youtube and Vimeo classes to the `_content.scss`. The reason for this change is because the CSS for the native apps are grabbed from the `_content.scss`, not the `style.scss` (which contains a lot of other styles related to Calypso itself, not rendering content).
* Open the following post and compare to the current Reader in production, nothing should change: https://wordpress.com/read/blogs/159889361/posts/1025

Reader CSS: moves Youtube and Vimeo classes to _content.scss

---

client/my-sites/backup/controller.js
client/my-sites/backup/style.scss
client/my-sites/backup/wpcom-backup-upsell.tsx
client/my-sites/scan/controller.js
client/my-sites/scan/wpcom-scan-upsell.tsx

* Add Jetpack Backup/Scan upsell pages in WPCOM for Jetpack sites.
* Prerequisite: Jetpack site without Backup and Scan.
* Run this PR with `flags=jetpack/features-section'  enabled.
* Go to `http://jetpack.cloud.localhost:3000/backup/[site]`.
* Verify that you see the new Jetpack Backup upsell page.
* Verify that both CTAs take you to the right checkout pages.
* Go to `http://jetpack.cloud.localhost:3000/scan/[site]`.
* Verify that you see the new Jetpack Scan upsell page.
* Verify that the CTA takes you to the right checkout page.
* Make sure that you still see the Business upsell when the selected site is a Simple site.
* Make sure that Jetpack cloud upsell pages look the same as in cloud.jetpack.com.
Fixes 1179060693083348-as-1180644091306241

Jetpack section: add Jetpack Backup/Scan upsell pages in WPCOM for Jetpack sites

---

client/landing/gutenboarding/onboarding-block/domains/index.tsx
packages/domain-picker/src/domain-picker/index.tsx
packages/domain-picker/src/domain-picker/style.scss
packages/domain-picker/src/domain-picker/suggestion-item-placeholder.tsx
packages/domain-picker/src/domain-picker/suggestion-item.tsx

* Show select button when hovering on suggestion item.
* Show select button when focusing on (by tabbing) suggestion item.
* When select button is shown, hide price description.
* Price description is now has a comma "Included in paid plans, $15/year".
* On mobile view, "Free" text is hidden.
* On mobile view, price description "Included in paid plans, " is hidden.
* On mobile view, an arrow "→" is shown instead of the select button.
* Remove "Confirm" & "Skip for now" button on domain page.
* Go to `/new/domains`.
* Test all of the above on mobile & desktop view.
* Also test long domain names.
Domain suggestion items is now a list of `<button>` (used to be a list of `<label>`). The select button inside the `<button>` is mock button, it only looks like a button visually. The reason why it …

DomainPicker: Show select button on hover and other UX-related changes.

---

client/landing/gutenboarding/onboarding-block/domains/index.tsx
packages/domain-picker/src/domain-picker/index.tsx
packages/domain-picker/src/domain-picker/style.scss
packages/domain-picker/src/domain-picker/suggestion-item-placeholder.tsx
packages/domain-picker/src/domain-picker/suggestion-item.tsx

This reverts https://github.com/Automattic/wp-calypso/pull/43346.
Apparently E2E test needs to be updated (as Skip Button no longer exists). (Strangely it was passing before).
This reverts commit 36d1a223820144ec880600b09e4ffc4fcbe92959.

Revert "DomainPicker: Show select button on hover and other UX-related changes. (#43346)"

---

.github/workflows/full-site-editing-plugin.yml

Addresses https://github.com/Automattic/wp-calypso/pull/43458#discussion_r442757015: In #43458, we added a job to PHPCS lint any changed files in the FSE plugin directory. Additionally, we started triggering that action (that's also in charge of creating the FSE diff for WP.com) upon changes to `yarn.lock`.
Turns out that this is too broad a criterion, since `yarn.lock` will change everytime e.g. a Renovate PR is created -- thus creating those FSE diffs too often. While we can consider triggering diff generation upon npm dependency changes, that is an orthogonal change to adding PHPCS linting, so IMO it's fine to remove it -- it's not a regression over the GH Action's state prior to #43458.
Nothing to do really.

FSE: Don't run GitHub Action on yarn.lock change

---

client/components/promo-section/promo-card/cta.tsx

In `PromoCardCta`, a lingering `selfTarget` prop passed as an attribute to an DOM element triggered a React warning in the console (`selfTarget` not being a valid attribute).
This commit makes sure it's not passed anymore.
_Note: previously dealt with in #43354, but I had a git mishap and decided it was better to start a new PR_
1. Make sure you've got a WP site with a Free plan
2. Download the PR and boot Calypso
3. Make sure to enable Jetpack sections with the flag `jetpack/features-section`
4. Select the free plan site
5. Go to the _Jetpack > Backup_ section
6. Check there's no React error in the console
7. Click on the _Upgrade to business plan_ button and check that you're still in the same tab
8. Repeat the operation with the _Jetpack > Scan_ section

Promo card cta: remove DOM element invalid prop

---

client/my-sites/customer-home/cards/tasks/task.jsx

* Fixes issues with withAnalytics dispatch and /skip endpoint param
* Checkout PR in local Calypso dev env
* Go to Customer home that has a notice  'Remind Me' and another that has a 'Dismiss' link (eg. editor deprecation notice)
* Make sure the dismiss option works in both cases
There were two issues here - one with the withAnalytics dispatch that affected all uses of `skipTask` call, and a second issue with the Dismiss link that was setting `reminder` to `never` which was rejected by REST endpoint.
Before:
After:
Fixes #42815

Customer Home: Fix bug with notice not dismissing if option 'never' set

---

apps/full-site-editing/full-site-editing-plugin/wpcom-block-editor-nav-sidebar/src/components/create-page/index.tsx
apps/full-site-editing/full-site-editing-plugin/wpcom-block-editor-nav-sidebar/src/components/nav-item/index.tsx
apps/full-site-editing/full-site-editing-plugin/wpcom-block-editor-nav-sidebar/src/components/nav-item/style.scss
apps/full-site-editing/full-site-editing-plugin/wpcom-block-editor-nav-sidebar/src/components/nav-sidebar/index.tsx
apps/full-site-editing/full-site-editing-plugin/wpcom-block-editor-nav-sidebar/src/components/nav-sidebar/style.scss
apps/full-site-editing/full-site-editing-plugin/wpcom-block-editor-nav-sidebar/src/components/view-all-posts/index.tsx
apps/full-site-editing/full-site-editing-plugin/wpcom-block-editor-nav-sidebar/src/types.ts
apps/wpcom-block-editor/src/calypso/features/iframe-bridge-server.js

**_Note to anyone reading this while preparing a release of the FSE plugin_**
The last major piece of functionality, clicking a page/post opens that item in the block editor.
* Clicking nav item will open that item in the block editor
* If calypsoify is present then ensure item is opened in an iframe'd block editor
* Refactor `<NavItem>` component to its own file to make space for more complicated filtery things
* Small TypeScript tidyup
The navigation takes a long time when iframe'd, which I guess is pretty normal. We could potentially speed this up by only navigating the iframe and leaving the parent frame alone (we'd have to see if `<CalypsoifyIframe>` would support …

Nav Sidebar: clicking nav items opens that item in the block editor

---

client/components/gsuite/docs/new-user-list.tsx
client/components/gsuite/gsuite-new-user-list/index.tsx
client/components/gsuite/gsuite-new-user-list/new-user.tsx
client/lib/gsuite/new-users.ts

This pull request seeks to fix errors displayed in certain conditions when hitting the trash icon on the `Add G Suite` page:
The state of those input fields is indeed not reset because the `GSuiteNewUser` component is never unmounted: since the index used for the list of `GSuiteNewUser` components is a simple sequence of integers it is not possible to distinguish when the first element is cleared (the element to remove has the same index than the new element). This leads to displaying errors when the trash icon is clicked, or soon after. We need to pass a key that uniquely identifies such component in order to avoid that. Correctly unmounting this component will also be required if we want to focus a field on page load, or when a new use is added.
1. Run `git checkout fix/add-gsuite-form` …

G Suite: Fix errors triggered when removing user on Add G Suite page

---

client/components/language-picker/index.jsx
client/components/language-picker/modal.jsx
client/my-sites/site-settings/form-general.jsx

* Remove **Empathy mode** checkbox control from language picker modal in Site Settings section.
**Before:**
**After:**
1. Boot Calypso with `yarn start`
2. Confirm that language picker modal in [Account Settings](http://calypso.localhost:3000/me) shows **Empathy mode** checkbox.
3. Confirm that language picker modal in [Site Settings](http://calypso.localhost:3000/settings/general/) doesn't show **Empathy mode** checkbox.

i18n: Remove empathy mode control from site language picker

---

client/my-sites/backup/style.scss
client/my-sites/backup/wpcom-upsell.tsx

* The Business plan upsell page in Jetpack > Backup shows a promo card for Scan. We no longer need to show that card.
* Prerequisite: Simple site with a Free plan and Simple site with a Personal or Premium plan.
* Run this PR with the `jetpack/features-section` enabled.
* Select your Simple site with a Free plan.
* Go to the Jetpack > Backup section (url: `http://calypso.localhost:3000/backup/[site]`).
* Verify that you see only the Activity Log promo card at the bottom.
* Select your Simple site with a Personal or Premium plan (stay in the same page).
* Verify that there aren't promo cards at the bottom.
Fixes 1179060693083348-as-1180644091306255

Jetpack section: remove Scan promo card from Backup's Business upsell page

---

client/components/jetpack/backup-placeholder/index.jsx
client/components/jetpack/backup-placeholder/style.scss
client/components/jetpack/upsell-switch/index.tsx
client/my-sites/backup/controller.js
client/my-sites/backup/main.jsx
client/my-sites/backup/style.scss

* Create a new component called `BackupPlaceholder` that represents the way the Backup page should look while it is loading.
* Make the loading placeholder for the Backup page more closely match the elements of the loaded page.
* Add the loading placeholder to the children of the UpsellSwitch component in the Backup section controller, so that it's also shown while upsell logic is checked.
* Add `is_jetpackcom` conditional CSS class inside the UpsellSwitch component, so that Jetpack.com styles can be applied if needed or ignored if not.
Fixes `1179060693083348-as-1180955464399609`
**NOTE:** Before testing, ensure that the `jetpack/features-section` flag is enabled.
Repeat for **WordPress.com** and **Jetpack.com** on both desktop and mobile layouts:
* Hard-reload the Backup page (i.e., …

Jetpack Cloud: Make Backup loading placeholder more detailed

---

client/components/jetpack/wpcom-business-at/index.tsx

* Set our brand font to all headers in the Automated Transfer page.
Prerequisite: non-Atomic Business plan site.
* Run this PR with the `jetpack/features-section` flag enabled.
* Go to Jetpack > Backup.
* Verify that you see headers configured with the right font.
Fixes 1179060693083348-as-1181410879631281

Jetpack section: set brand font to headers in the Automated Transfer page

---

client/my-sites/domains/components/domain-warnings/pending-gsuite-tos-notice-action.js
client/my-sites/domains/components/domain-warnings/pending-gsuite-tos-notice.jsx
client/my-sites/domains/domain-management/edit/domain-types/mapped-domain-type.jsx
client/my-sites/domains/domain-management/edit/domain-types/registered-domain-type.jsx

This moves the GSuite TOS notice to the domain card to have a similar look and feel to the rest of domain notices.
Single email address:
Multiple email addresses:
* Purchase G Suite for a mapped or registered domain of yours
* Verify that one of the messages from the screenshots above is shown according to the number of email addresses
* Make sure the 'Get started' button works as expected

Domains: Move GSuite TOS notice to domain card

---

client/my-sites/domains/domain-management/components/domain-notice/index.jsx
client/my-sites/domains/domain-management/components/domain-notice/style.scss
client/my-sites/domains/domain-management/list/item.jsx
client/my-sites/domains/domain-management/list/style.scss

This PR adds a new component to use for domain notices, instead of the old `Notice` component.
For a domain of yours that has expired or is near expiration, a notice similar to the attached screenshot above should be shown.

Domains: Use new component for domain notices

---

client/landing/gutenboarding/available-designs-config.json
client/landing/gutenboarding/available-designs.ts

Subject says it all :slightly_smiling_face: 
Verify that Gutenboarding still works as before. Make sure to also test with the `gutenboarding/site-editor` and `gutenboarding/edge-templates` feature flags, respectively.

Gutenboarding: Infer design's src from theme and template attrs, drop src attr

---

client/my-sites/customer-home/cards/features/help-search/style.scss

* I noticed this while looking into #43169. Gridicons are designed to be displayed at 24px, or certain multiples of 6px in a pinch: https://github.com/Automattic/gridicons
* The help icon was sized at 25px; this PR resizes it and the surrounding circle container to 24px / 26px for a sharper icon.
**Before**
**After**
* Visit `/home` and note the visual changes in the icon next to "More help".

Customer Home: Resize help icon to use 24px size

---

client/my-sites/checkout/composite-checkout/wpcom/components/wp-checkout.js
client/my-sites/checkout/composite-checkout/wpcom/components/wp-contact-form.js

If the email field is not displayed because only the G Suite form is being used, and the alternateEmail is the same as the email value, the current logic hides the alternateEmail from the summary. This change shows it instead.
Before:
After:
- Add G Suite to your cart for an existing domain (you cannot have the domain in your cart for this to work).
- Complete the contact form, leaving the email address identical to your registered email address for that domain (it should be the default).
- Verify that the contact summary shows the email address.

Show alternateEmail in contact summary if email is not shown

---

client/blocks/inline-help/popover.jsx
config/development.json

* Reverts #41912 due to a change in approach to editor deprecation
* Check in PR in local Calypso dev env
* Try switching editor from block to classic and back again in Atomic and Classic sites and check that everything works as expected.

Revert: Editor - autoactivation of classic plugin on atomic sites

---

client/lib/abtest/active-tests.js

* Increases variant exposure to 50/50 for the test created in #42783.
* Verify that code looks okay.
* Set your locale and geo to EN-US. Select a free plan during signup and verify that you see the expert guidance offer when assigned to variant.

Expert guidance A/B test: Increase exposure to 50/50

---

client/components/jetpack/wpcom-business-at/index.tsx

When a user starts the automated transfer, to convert Simple site (Business plan) to Atomic site, we need to update the site data and redirect it to the new site slug.
- Apply this change. Active the flag `?flags=jetpack/features-section`
- Get a site with Business plan that is non-Atomic yet.
- Go to the Backup section, see the Upsell page, and "Activate Jetpack Backup now". The transfer process will start.
- When the transfer ends, it'll reload the Backup page with the new site slug.

Refresh the site data when the automated transfer ends and reload

---

client/state/inline-help/test/reducer.js

Previously the reducer for the `inline-help` state had no unit tests.
This PR adds basic tests to cover these.
* `cd tests/client`.
* Run tests `yarn run test-client:watch client/state/inline-help`
* Verify all pass.

Add unit tests to inline help reducer

---

client/my-sites/scan/style.scss

The sites selector was applied an unnecessary override in `scan/styles.css`
- Override: `margin-left: auto`
- Overridden rule: `margin: auto`
_Note that the removed style targeted an element outside of the component, namely the site selector. This should be avoided, since in this case you might have seen a different layout for the site selector page before and after visiting the Scan section._
- Download the PR and run Jetpack cloud
- Go to the site selector (e.g. `/backup/`)
- Notice it looks the same as in staging/production
- Go to the _Scan_ section
- Go back to the site selector
- Notice it still looks the same as in staging/production
Site selector

Jetpack cloud: remove outdated style in Scan section

---

packages/data-stores/src/plans/plans-data.ts

* Add upload themes & install plugins to Business & eCommerce plans.
* Go to `/new/plans-modal`.
* See if those "Upload themes" & "Install plugins" are there.
Fixes #43461

Gutenboarding: Add upload themes & install plugins to Business & eCommerce plans.

---

client/components/jetpack/backup-date-picker/style.scss
client/components/jetpack/daily-backup-status/style.scss

* Removes custom margins and paddings from the Backup card, making the transition between WordPress.com and Jetpack.com seamless and easier to maintain.
* Changes the Backup date picker a bit to make it match dotcom's styles.
Before | After
--|--
* Spin up this PR and open wordpress.com.
* Add `?flags=jetpack/features-section` to your URL.
* Select a Jetpack site.
* Inside the new Jetpack menu, select Backup.
* Ensure the layout looks good in all screen widths.
Fixes 1179060693083348-asana-1181590984715097

Jetpack: update backup section styling

---

client/my-sites/domains/domain-search/index.jsx

As suggested in #43118, we can do a better job with the default suggestions in Domains Management for sites with WPCOM subdomains with randomly generated numbers (which can come from a number of flows, but most notably Gutenboarding).
Create or rename a WPCOM site making sure to try to choose a very generic name, like `test`. You should get a suggestion like `test521265196`.wordpress.com. Now, on your site go to Manage -> Domains -> Add domain to this site. The default suggestion should be `test` (in this case):
Which are much more attractive than previously:
Fixes #43118

Domains: Strip random number from the WPCOM subdomain for suggestions

---

config/stage.json
config/wpcalypso.json

* This change enables the new menu/nav UI for `/me/security` from #43234 in the `stage` and `wpcalypso` environments so we can get broader testing and feedback on the changes.
* Verify that you get the new menu UI from #43234 shown when you navigate to `/me/security`. Verify that you can navigate to (and back from) the various items in the checklist and that the left nav updates appropriately.

Enable new menu structure for `/me/security` in `wpcalypso` and `stage`

---

client/components/jetpack/business-at-switch/index.tsx
client/components/jetpack/wpcom-business-at/index.tsx

* Remove everything Scan related from the Automated Transfer page, since Simple/Atomic sites won't have access to the Scan section.
Prerequisite: non-Atomic Business plan site.
* Run this PR.
* Go to Calypso.
* Make sure to activate the `jetpackSidebarSection` AB test to enable the Jetpack section.
* Go to Jetpack > Backup.
* Verify that the Scan promo card is gone and that the rest looks exactly as it looks now in wordpress.com.
Fixes 1179060693083348-as-1181470526836689

Jetpack section: remove Scan from Automated Transfer page

---

client/my-sites/site-settings/disconnect-site/down-flow.jsx

* Update copy on troubleshoot option as per the suggestion on p1HpG7-9wA-p2#comment-40220
* Remove trailing dots on option titles.
Before | After
--|--
* Go to `https://wordpress.com/settings/disconnect-site/SITE_URL?type=down`.
* Ensure the copy on the page looks good.

Cannot access site flow: update copy

---

client/landing/gutenboarding/components/header/index.tsx
client/landing/gutenboarding/onboarding-block/acquire-intent/index.tsx
client/landing/gutenboarding/stores/onboard/index.ts
client/landing/gutenboarding/stores/onboard/reducer.ts

* When logging in at site creation step in Gutenboarding, the redirect to `/new/plans` shouldn't happen. Mentioned in https://github.com/Automattic/wp-calypso/issues/43569#issuecomment-648102697.
* When the site title step is skipped and user selects a domain, if the page is refreshed, the domain and last domain search should be persisted. Demo with the current behaviour: https://cloudup.com/cQsWe7fNGRK)
* Domain search should be now automatically changed by entering a new site title value only when advancing from Intent Capture step with a valid site title (at least 2 characters).
* Go to [/new](https://calypso.live/new?branch=fix/gutenboarding-persist-domain-and-domain-search) as an existing logged out user.
* After skipping the site title step, at the end of the flow you enter a domain …

Gutenboarding: persist domain selection and search when site title is skipped

---

client/my-sites/site-settings/navigation.jsx
client/my-sites/site-settings/settings-jetpack/index.js
client/my-sites/site-settings/settings-jetpack/main.jsx
client/my-sites/site-settings/settings-security/main.jsx
client/state/purchases/selectors.js
client/state/selectors/is-rewind-active.ts

A Jetpack site with no Backup or Scan purchase has an empty _Manage > Settings > Jetpack_ section (see screenshot below). This PR removes the section altogether in such cases.
- Download the PR and run Calypso
- Make sure Jetpack sections are **not** enabled
- Select a Jetpack site with Backup and/or Scan
- Go to _Manage > Settings > Security_ and check that you see the credentials form
- Active Jetpack sections. The page refreshes.
- Still in _Settings > Security_, you should now see a banner with a link to _Settings > Jetpack_
- Click it and verify that you're brought to  _Settings > Jetpack_ and see the credentials form
- Select a Jetpack site with neither Backup nor Scan
- The _Jetpack_ item shouldn't be present in the tab navigation anymore
- `settings/jetpack/:site` should show a …

Jetpack: hide settings in Calypso if no Backup or Scan purchase

---

client/assets/stylesheets/shared/_typography.scss
client/devdocs/design/typography.jsx
client/devdocs/style.scss

* Update `/devdocs/typography` to address recent addition of brand font, font size variables.
* Also adds font size variables for larger font sizes to be converted in the future, as well as the code font size.
Before
After
* Navigate to `/devdocs/typography` and check out the changes

Typography: Update devdocs with recent changes

---

client/landing/jetpack-cloud/sections/settings/main.jsx

* Add the `clickableHeader` property to the **Show connection details** header in the Settings section on Jetpack.com, to make the entire header clickable to expand the connection details menu.
* Open the Jetpack.com interface to the Settings page.
* Verify that you can click anywhere along the span of the "Show/hide connection details" header, including the arrow on the right, to expand or collapse the section.

Jetpack Cloud: Make the header for connxn info clickable to expand

---

apps/full-site-editing/full-site-editing-plugin/block-patterns/patterns/call-to-action-02.php
apps/full-site-editing/full-site-editing-plugin/block-patterns/patterns/food-menu.php
apps/full-site-editing/full-site-editing-plugin/block-patterns/patterns/numbers.php
apps/full-site-editing/full-site-editing-plugin/block-patterns/patterns/three-columns-and-image.php

Fixes #43478. @Addison-Stavlo summed up the problem succintly [here](https://github.com/Automattic/wp-calypso/issues/43478#issuecomment-647722544).
> Some blocks in core have transitioned to the __experimentalFontSize hook. I think mainly paragraph and heading have this so far, but a handful of FSE blocks (site-title, post-author, etc.) will have these in the near future as well.
>
>Where these blocks may have had a customFontSize attribute, the custom sizes are now saved under what you noted: {"style":{"typography":{"fontSize":XX}}}. Named font sizes such as "large" etc. are still saved under the attribute fontSize as a string.
- Set up sandbox
- simple site with block pattern preview updates
1. Sandbox simple site
2. Checkout this branch in wp-calypso repo
3. Sync the local dev …

Fix block pattern previews with custom font size

---

client/my-sites/sidebar/index.jsx

* Move the Jetpack sidebar item below the Site sidebar item.
* Load Calypso for a Jetpack site. Enable the Jetpack  Ensure that the "Jetpack" sidebar item appears below the "Site" sidebar item.
Fixes #

Move Jetpack sidebar item below the Site sidebar item

---

client/gutenberg/editor/calypsoify-iframe.tsx

Reverts Automattic/wp-calypso#41920 due to a change in plan on how to deprecate editor
Apply PR to local calypso dev and test that redirection to iframe editor still works correctly for atomic and simple sites

Revert "Editor: Pass editor/after-deprecation feature flag to iframed editor"

---

client/me/security-checkup/account-recovery-email.jsx
client/me/security-checkup/account-recovery-phone.jsx

* Fix the `strong` element when the account recovery email is specified and verified
* Fix the account recovery phone number display
* Set up your WordPress.com account to have a recovery email and a recovery phone number, and ensure that both are verified.
* Visit `/me/security`, either locally or at https://calypso.live/?branch=fix/me-security-menu-typos.
* The "Recovery Email" item should show descriptive text that does not include `{{strong}}` or `{{/strong}}`. In English, that text should be: You have set **email@example.com** as your recovery email address.
* The "Recovery SMS Number" item should show descriptive text that includes your recovery number and not `[Object object]`.

Fix display of account recovery email and phone when specified

---

client/lib/abtest/active-tests.js
client/lib/domains/suggestions/index.js
client/signup/steps/domains/index.jsx

* This change removes the A/B test for showing `.jp` domain suggestions to some users in Japan, and allows all users to see those domains.
Note that this should be merged after the back end is updated to allow `.jp` domains for both of the vendor strings currently in use - D45271-code
* Verify that you can search for domains by starting the signup flows via `/start` and `/new`, as well as via the domains-only flow at `/domains`.

Remove AB test for .jp domains in Japan

---

client/signup/steps/p2-site/index.jsx

Fixes an error where if you left out the `site` field in the P2 signup flow (wp.com/start/p2), it would not show an error initially and "allow" you to create such site (the backend would actually prevent it).
In this PR, we fix the error messaging for those cases.
Go to `http://calypso.localhost:3000/start/p2` and input only site title and click Continue. You should be shown an error that you need to fill in the site address.
Props @klimeryk for the bug report!

P2 signup: fix error when site field is empty

---

client/components/language-picker/modal.jsx

* Prevent language picker search from opening on keydown while holding key modifier
* Open language picker from http://calypso.localhost:3000/me/account.
* Hold key modifier and press a printable character, for example `Cmd + R`.
* Confirm that language search doesn't open.

Prevent language picker search from opening on keydown while holding key modifier

---

client/blocks/inline-help/contextual-help.js

This updates the "All About Domains" link, following the existing pattern here, so that it works properly.
https://github.com/Automattic/wp-calypso/blob/931916f8f1fef0772577a18e23885f741cd4d090/client/blocks/inline-help/contextual-help.js#L1004-L1009
Click "All About Domains" in Customer Home and verify that the dialog appears correctly instead of just a blank screen! 
cc @gwwar, @mmtr  
Fixes #43220

Customer Home: Fix Support Link to Domains

---

client/components/jetpack/wpcom-business-at/index.tsx

This PR fixes the status transfer issue when you revert an Atomic site and then go to the Backup section and see the upsell page but with the "Active Jetpack Backup now" disabled with the spinner animation.
- Revert an Atomic site
- Reload the Backup section
- Check if you see the "Activate Jetpack Backup now" button enabled.

Jetpack: Fix the status transfer issue with the recent reverted Atomic sites

---

client/my-sites/domains/domain-management/components/header/index.jsx
client/my-sites/domains/domain-management/list/index.jsx

Update the domains header to reflect whether the user is managing domains on a site level or on a global level.
* Go to /domains/all
* Choose a domain
* Verify that the header title says "All Domains"
Then switch to a site:
* Navigate to Manage -> Domains
* Verify that the header title says "Site Domains"
* Verify the header title is the same after choosing a domain

Domains: Update header title depending on whether on a site or global level

---

client/my-sites/customer-home/main.jsx

* Renames the "View site" button to "Visit site" to avoid confusion with the site previewer, since this button goes directly to the site's front page.
* See p1592949321000800-slack-dotcom-manage-design for context
**Before**
**After**
* Visit `/home` and check out the button in the top right corner. It should say "Visit site"

Customer Home: Rename View site to Visit site to avoid confusion with the previewer

---

client/my-sites/activity/activity-log-item/style.scss
client/my-sites/activity/activity-log/style.scss

* Add a fixed width/height to circles that contain icons.
* Ensure the circles and timestamps are horizontally centered.
* Reorder styles for better readability.
Before | After
--|--
* Open the Activity Log on an active site.
* Confirm all circles are round and look consistent across multiple devices.
Fixes issue reported in p1HpG7-9xQ-p2#comment-40285

Activity log: make circle styles more robust

---

client/my-sites/checkout/checkout-thank-you/business-plan-details.jsx

* Removes Scan card from highlighted features in the post-purchase thank you page.
Before | After
--|--
* Start with a simple site.
* Go to `Jetpack > Backup` and purchase the Business plan.
* Confirm that you only see one Jetpack card (Backup) on the post-purchase thank you page.
Fixes issue reported in p1HpG7-9xQ-p2#comment-40305

Jetpack: remove Scan card from highlighted features in thank you page

---

client/lib/i18n-utils/test/utils.js
client/lib/i18n-utils/utils.js

The “Learn More” link on the Jetpack > Activity Log page 404’s when using a language that has a language WordPress.com blog.
Fails: https://wordpress.com/es/blog/2018/10/30/introducing-activity/
Works: https://wordpress.com/blog/2018/10/30/introducing-activity/
props for discovering @cathymcbride 
* `localizeUrl()` should not rewrite blog post URLs since we don't have all posts translated and currently no english-slug redirects in place.
* Covered by unit tests: `yarn run test-client lib/i18n-utils`
* Verify that the link above always links to the English blog post, no matter which language.

i18n: Don't rewrite blog post URLs

---

client/components/gsuite/gsuite-new-user-list/index.tsx
client/components/gsuite/gsuite-new-user-list/new-user.tsx
client/lib/gsuite/new-users.ts
client/my-sites/email/gsuite-add-users/index.jsx

This pull request seeks to refine the user experience on the `Add G Suite` page by:
* Moving the first and last name fields above the mailbox field
* Prefilling the mailbox from the first name
* Enforcing lowercase for the mailbox
* Putting focus on the first name field upon page loading, or when adding/removing a user
1. Run `git checkout update/gsuite-add-user-form` and start your server, or open a [live branch](https://calypso.live/?branch=fix/update/gsuite-add-user-form)
2. Open the [`Email` page](http://calypso.localhost:3000/email) for a site with a G Suite account
3. Click the `Add New User` button
4. Assert that the email field is now presented below the two other fields
5. Assert that the first name field has focus
6. Enter anything in that field
7. Assert that the email field is …

G Suite: Refine Add G Suite page

---

client/my-sites/marketing/tools/feature-button-with-plan-gate.tsx
client/my-sites/marketing/tools/google-adwords.tsx
client/my-sites/marketing/tools/index.tsx
client/my-sites/marketing/tools/style.scss

* Aiming for a more consistent look and feel between Earn and Marketing (since the screens look so similar), this PR moves the buttons to the left, makes them non-compact, and updates the font size/color of the explanatory copy in each card.
* Obviously there's more we can do to bring these two similar screens into alignment -- thinking we could right-align the illustration in the larger card at the top, and swap it out for one of our updated versions, and apply the same typography treatments. That could easily be another PR, though.
* I'd welcome thoughts from Marketing folks on this one!
**Before**
**After**
Earn screen for comparison
* Navigate to `/marketing` and note visual changes. Make sure there are no bugs or visual regressions.
See #42058

Marketing: Update marketing cards to use similar styling to Earn cards

---

apps/full-site-editing/full-site-editing-plugin/premium-content/blocks/container/index.js

Works with paragraphs, any any single blocks (group, image, etc). But needed https://github.com/WordPress/gutenberg/pull/22577 to handle mixed selection blocks (for example one paragraph and one header block in a selection). I'm unsure of the reasoning but currently only the group block is allowed to do this.
I also added checks for not transforming if there were premium content blocks in the selection, including parent blocks.
Note that we can further improve experimental `__experimentalConvert` in follow up core patches (for example don't display the transform option if we don't allow nested premium content blocks), but we'll leave that for a future follow up.
* `cd apps/full-site-editing;  yarn dev --sync`.
* Set up a recurring payment plan on a site using the testing store. More info …

Premium Content: add a general transform to premium content

---

apps/full-site-editing/full-site-editing-plugin/wpcom-block-editor-nux/src/disable-core-nux.js

Noticed this today while testing some unrelated FSE changes in Gutenberg. When this NUX code runs in `edit-site` context it breaks the site editor, since the `core/edit-post` store is not initialized there.
```
wpcom-block-editor-nux.js?ver=2abd647072b43030fb24f5d895691b61:1 Uncaught TypeError: Cannot read property 'isFeatureActive' of null
at wpcom-block-editor-nux.js?ver=2abd647072b43030fb24f5d895691b61:1
at registry.js:56
at Array.forEach (<anonymous>)
at globalListener (registry.js:56)
at index.js:93
at Object.dispatch (redux.js:221)
at e (<anonymous>:1:40553)
at promise-middleware.js:20
at Object.dispatch (resolvers-cache-middleware.js:52)
at Object.addFormatTypes (index.js:207)
```
1. Use a local test site with Gutenberg and FSE plugin activated.
2. Activate the FSE experiment.
3. …

FSE plugin: fix broken site editor page

---

client/my-sites/domains/domain-management/contacts-privacy/index.jsx
client/my-sites/domains/domain-management/edit/navigation/enhanced.jsx

This only allows the domain contact info to be viewed by the domain owners, and not other users of the same site.
* For a site you are a member of, go to a registered domain you do not own
* Click on 'Update your contact information' from the navigation menu
* You should see the error shown in the screenshot above

Domains: Do not show domain contact info for non owners

---

client/blocks/inline-help/popover.jsx
client/state/data-layer/wpcom/sites/gutenberg/index.js

* Removes the redirect to wpadmin for classic editor due to a change of approach for editor edpreication
* Apply PR to local calypso dev env and check that browser is redirected to calypso editor for simple and atomic sites when using the 'switch to classic/switch to block' links in the editor help popover

Editor: Revert the switch to classic redirect to wpadmin

---

apps/full-site-editing/full-site-editing-plugin/block-patterns/patterns/call-to-action-02.php
apps/full-site-editing/full-site-editing-plugin/block-patterns/patterns/call-to-action-03.php
apps/full-site-editing/full-site-editing-plugin/block-patterns/patterns/collage-gallery.php
apps/full-site-editing/full-site-editing-plugin/block-patterns/patterns/coming-soon.php
apps/full-site-editing/full-site-editing-plugin/block-patterns/patterns/contact-02.php
apps/full-site-editing/full-site-editing-plugin/block-patterns/patterns/contact-03.php
apps/full-site-editing/full-site-editing-plugin/block-patterns/patterns/contact-04.php
apps/full-site-editing/full-site-editing-plugin/block-patterns/patterns/contact.php
apps/full-site-editing/full-site-editing-plugin/block-patterns/patterns/description-and-image.php
apps/full-site-editing/full-site-editing-plugin/block-patterns/patterns/food-menu.php
apps/full-site-editing/full-site-editing-plugin/block-patterns/patterns/headline-02.php
apps/full-site-editing/full-site-editing-plugin/block-patterns/patterns/headline.php
apps/full-site-editing/full-site-editing-plugin/block-patterns/patterns/image-and-description.php
apps/full-site-editing/full-site-editing-plugin/block-patterns/patterns/image-and-text.php
apps/full-site-editing/full-site-editing-plugin/block-patterns/patterns/images-with-titles.php
apps/full-site-editing/full-site-editing-plugin/block-patterns/patterns/list.php
apps/full-site-editing/full-site-editing-plugin/block-patterns/patterns/masonry-gallery.php
apps/full-site-editing/full-site-editing-plugin/block-patterns/patterns/numbered-list.php
apps/full-site-editing/full-site-editing-plugin/block-patterns/patterns/numbers.php
apps/full-site-editing/full-site-editing-plugin/block-patterns/patterns/portraits-and-text.php
apps/full-site-editing/full-site-editing-plugin/block-patterns/patterns/recent-posts-02.php
apps/full-site-editing/full-site-editing-plugin/block-patterns/patterns/recent-posts.php
apps/full-site-editing/full-site-editing-plugin/block-patterns/patterns/three-columns-and-image.php
apps/full-site-editing/full-site-editing-plugin/block-patterns/patterns/three-images-side-by-side.php
apps/full-site-editing/full-site-editing-plugin/block-patterns/patterns/tiled-mosaic-gallery.php
apps/full-site-editing/full-site-editing-plugin/block-patterns/patterns/two-column-text-and-image.php
apps/full-site-editing/full-site-editing-plugin/block-patterns/patterns/two-images-and-quote.php
apps/full-site-editing/full-site-editing-plugin/block-patterns/patterns/two-images-side-by-side.php

Fixes #42165. Increase viewport width of block pattern previews for better preview scaling
- Set up sandbox
- simple site with block pattern preview updates
1. Sandbox simple site
2. Checkout this branch in wp-calypso repo
3. Sync the local dev environment with `cd apps/full-site-editing; yarn dev --sync` More info in PCYsg-ly5-p2 #build-scripts
- atomic site with block pattern preview updates
1. Create ephemeral atomic site
2. Checkout this branch in your local wp-calypso repo
2. Sync full site editing plugin updates with atomic site. More info in PCYsg-ly5-p2 #atomic-testng
- Navigate to my sites -> posts -> Add new post
- Open Gutenberg Inserter
- Click on Block Patterns Tab
- Review scaled block pattern previews
- Editor loads without white screen of death
- All block pattern previews …

Modify Block Pattern Preview Viewport

---

apps/full-site-editing/full-site-editing-plugin/full-site-editing-plugin.php

* Sidebar code is enabled if `a8c_enable_nav_sidebar` filter returns true
This leaves the `WPCOM_BLOCK_EDITOR_SIDEBAR` option so the plugin can still be run on dotorg sites.
**dotorg site**
* Run `npx wp-env start` in `apps/full-site-editing`
* Run `npx wp-env run cli wp config set WPCOM_BLOCK_EDITOR_SIDEBAR 0` to ensure feature is disabled
* Test site at `localhost:4013`, the sidebar shouldn't appear in the block editor
**dotcom site**
* Apply these changes `full-site-editing` changes to your sandbox
* Check `WPCOM_BLOCK_EDITOR_SIDEBAR` isn't defined in the sandbox
* Test that the nav sidebar isn't appearing in a sandboxed site (this is because no one is using this hook yet)
* Can do more testing if you follow instructions in D45264-code

Nav sidebar: sidebar can be enabled by a filter

---

client/gutenberg/editor/calypsoify-iframe.tsx

* If `editor/after-deprecation` feature flag is enabled and user belongs to the current editor deprecation group, pass on a query string param to the iframed block editor so it can adjust behaviour accordingly.
1. Checkout this PR branch
2. Turn on `config/development.json` feature flag for `editor/after-deprecation` if not already on.
3. Fire up Calypso locally and login with user matching editor deprecation group requirements from D44256-code
**OR**
Sandbox API, fudging `sites-gutenberg-v3.php` endpoint to return true for `in_editor_deprecation_group`
4. Edit post using block editor and ensure iframe url contains `in-editor-deprecation-group` query string param.
5. Logout and back in with user not matching the editor deprecation group requirements from D44256
**OR**
Undo changes to …

Editor: Pass user's editor deprecation group status to iframed editor

---

client/blocks/inline-help/popover.jsx
config/development.json

* Hide the Switch to Classic/Block Editor links in the inline help popover if the user is in the editor deprecation group. See D44256-code for details on this group.
1. Checkout this PR branch
2. Login with user matching editor deprecation group requirements in D44256-code 
**OR** 
Sanbox API and update `/wp-content/rest-api-endpoints/sites-gutenberg-v3.php` to return true for `in_editor_deprecation_group`
3. Ensure you see no switch editor buttons within the inline help popover when in either classic or block editor.
4. Logout then in with new user not matching the deprecation group requirements
**OR**
Undo changes to sandboxed API endpoint.
5. Ensure that you see the Switch to Classic Editor button in the popover while in the block editor and the Switch to Block Editor button while in …

Editor: Hide switch editor links if in editor deprecation group

---

client/components/jetpack/upsell-switch/index.tsx

This PR fixes the issue when the process of transferring a Simple site to an Atomic site ends. The server responds with a `no_connected_jetpack` state, but it's already connected. So, this change checks if it's an Atomic site in the `UpsellSwitch`. Address this fix on the server is a little bit more complicated because the states are cached and we'd need a temporary notice page.
- Select a Simple site with a Business plan. Or revert an Atomic site and reload the page.
- Go to Backup section and click on "Activate Jetpack Backup now"
- When the process ends, the Backup section will show up.

Fix the Jetpack activation issue when automated transfers ends

---

client/jetpack-connect/jetpack-connection.jsx

* Fixes a wrong URL in the Jetpack Connect language suggestion box.
1. Open an incognito browser window with a browser preferred language set to non-English.
2. Visit https://wordpress.com/jetpack/connect/scan
3. Look at the language suggestion box and confirm that they are https://wordpress.com/jetpack/connect/scan/{locale} instead of https://wordpress.com/{locale}
Fixes #43668

Jetpack Connect: fix wrong URL in LocaleSuggestions

---

client/my-sites/marketing/connections/services-group.jsx

* `scrollIntoView` should run only once to resolve #41424 and clicking an other tab doesn't result to a scroll
* used `[ expandedService, isFetching ]` as dependencies and not `[ expandedService, services ]` assuming that, while `isFetching === true`, there is not need to scroll and when `isFetching` changes to `false` we should only `scrollIntoView` once
- Starting at URL: /marketing/connection/facebook
- Scroll up page and click on traffic tab - notice that the page scrolls down to same point as on connections tab
**Before**
**After**

Marketing: Connections scrollIntoView only once

---

apps/full-site-editing/full-site-editing-plugin/full-site-editing-plugin.php

* Disables Blog Posts Block when request indicates the newspack-blocks plugins is being installed and activated from github so that it resolves https://github.com/Automattic/newspack-blocks/issues/324
* Setup https://github.com/Automattic/ajax-env with https://github.com/Automattic/newspack-blocks plugin (download the plugin from github and extract into your plugins folder)
* run `npm start`
* Visit http://localhost:4759/wp-admin/plugins.php
* You should not see any error like the below
```
Notice: Constant NEWSPACK_BLOCKS__BLOCKS_DIRECTORY already defined in /var/www/html/wp-content/plugins/full-site-editing-plugin/newspack-blocks/index.php on line 10 Notice: Constant NEWSPACK_BLOCKS__PLUGIN_DIR already defined in /var/www/html/wp-content/plugins/full-site-editing-plugin/newspack-blocks/i …
```

Blog Posts Block: allow newspack-blocks installation from github

---

packages/calypso-build/CHANGELOG.md
packages/calypso-build/webpack.config.js

Follow-up to https://github.com/Automattic/wp-calypso/pull/43619. Missing exports should fail the webpack build.

Calypso build: Set strictExportPresence

---

client/my-sites/sidebar/index.jsx

Since _Backup_ and _Scan_ sections are now accessible from the _Jetpack_ menu item, having a link to these sections in cloud (under the _Tools_ menu item) is redundant.
- Download the PR and run Calypso
- Make sure Jetpack sections are enabled
- Select a Jetpack site with Backup and Scan activated
- Check that in the _Tools_ menu item, The _Backup_ and _Scan_ items are not shown
Before
After

Menu: remove Backup and Scan links to cloud

---

client/components/domains/register-domain-step/utility.js
client/lib/domains/constants.js
client/lib/domains/get-tld.js
client/lib/domains/registration/availability-messages.js
client/lib/domains/registration/test/availability-messages.js
client/my-sites/current-site/domain-warnings.jsx
client/my-sites/domains/components/domain-warnings/index.jsx
client/my-sites/domains/components/domain-warnings/test/index.js
client/my-sites/domains/domain-management/edit/domain-types/registered-domain-type.jsx
client/my-sites/domains/domain-management/list/index.jsx
client/my-sites/domains/domain-management/name-servers/index.jsx
client/my-sites/plans/current-plan/index.jsx
packages/domain-picker/src/domain-picker/index.tsx

* Change various variable names to remove blacklist/whitelist
* Change `ruleWhiteList` prop to `allowedRules`
* Ensure all instances of `ruleWhiteList` are renamed to `allowedRules`
* Ensure unit tests pass
Addresses part of https://github.com/Automattic/wp-calypso/issues/43395

Domains: Remove problematic "blacklist"/"whitelist" language #43395

---

packages/composite-checkout/src/components/checkout-order-summary.js
packages/composite-checkout/src/components/checkout-steps.js

This just cleans up some minor i18n inconsistencies, wrapping fallback strings in translation functions and replacing a missed instance of `calypso-i18n` with `react-i18n`.
**To Test:**
- visual should suffice

Checkout: update translation strings and methods for consistency

---

client/my-sites/post-type-filter/index.jsx

* Updates `/posts` so that the "Scheduled" and "Trashed" tabs are visible regardless of whether any scheduled/trashed posts exist for the blog.
* Verify unit tests pass.
* Navigate to the `/posts` view for a blog on your account. Remove all scheduled and trashed posts. Verify that the tabs still appear with a "0" post count instead of disappearing.
Fixes #41413

Always show post type tabs for Scheduled and Trashed

---

client/lib/jetpack/paths.ts
client/my-sites/site-settings/settings-jetpack/index.js

* Fix the settings path when new jetpack sidebar enabled
* Remove the requirement that jetpack products be purchases to navigate to route
1. Navigate to `/settings/security` for a jetpack site with the `jepackSidebarSection` abtest set to `showJetpackSidebarSection`
2. Verify you can see the "Looking for Jetpack backups and security scans settings?" notice at the top of the page ( if not follow the steps below to unhide it ) <img width="930" alt="Screen Shot 2020-06-25 at 8 55 33 AM" src="https://user-images.githubusercontent.com/2810519/85754358-d82d1d00-b6c1-11ea-9e18-2217df14ad88.png">
3. Click "Take me there!"
4. Verify you are taken to `/settings/jetpack`
5. Reload the page, verify that it still works the same
6. Manually enter the route for a non-jetpack site to `settings/jetpack` …

Fix new Jetpack Settings Link

---

client/components/jetpack/daily-backup-status/index.jsx
client/lib/jetpack/backup-utils.js

* Recently, two new Backup related events were added: `rewind__backup_only_complete_full` and `rewind__backup_only_complete_initial`. This PRs includes them so we can make use of them in Backup's UI.
* Prerequisite: self-hosted Jetpack site with Backup product and a Free plan. 
* Visit `http://jetpack.cloud.localhost:3000/backup/[site]`.
* Verify that you see a backup for the day.
* Visit `https://cloud.jetpack.com/backup/[site]`.
* Verify that you don't see a backup for the day.
Fixes 1179060693083348-as-1182030255774641

Jetpack Backup: include new backup only events

---

client/my-sites/site-settings/navigation.jsx

* don't relay on site object in site-settings, it has lead to a critical error when using the clone tool
1. navigate to `/settings/general` for a jetpack site on production
2. click the Clone under site tools
3. verify you see a blank screen
4. repeat for this branch, verify you see the "Let's clone :siteTitle" on the blue screen

Fix blank screen for clone tool

---

client/components/jetpack/daily-backup-status/style.scss

* Restore space in backup views
1. Navigate to `/backup` for site with Daily Backups
2. Confirm there is now space between action buttons and "Changes in this backup"

Cleanup Daily Backup View

---

client/my-sites/checkout/checkout-system-decider.js
client/my-sites/checkout/composite-checkout/wpcom/components/wp-checkout.js
packages/composite-checkout/README.md
packages/composite-checkout/src/components/checkout-error-boundary.js
packages/composite-checkout/src/components/checkout-payment-methods.js
packages/composite-checkout/src/components/checkout-provider.js
packages/composite-checkout/src/components/checkout-steps.js

When a fatal error is thrown in composite checkout's rendering process, we catch and log that error using a React error boundary called `CheckoutErrorBoundary`. Previously, that component accepted an `onError` function prop that would be called with the `Error` object that was thrown by React. However, I wanted to also include the "component trace" that error boundaries provide. Furthermore, I wanted to include both the component trace and the stack trace itself to the message logged to Logstash.
There's various ways I could have done this but I decided that the simplest was probably to change the `onError` function provided to accept an error string instead of an `Error` object, and to create that string by concatenating the error message, stack trace, and component trace.
Another option …

Checkout: Add stack and component trace to error boundary logging

---

client/jetpack-connect/jetpack-connection.jsx
client/jetpack-connect/main.jsx

By moving the connection logic to an HoC we overrode the props passed to the wrapped component ( here, from the controller ). The props should be accessed via HoC.
* Also, we remove a redundant function definition and an own prop.
* go to  http://calypso.localhost:3000/jetpack/connect?url=:site
* verify that the input field is pre-filled and the connection processing gets initiated without any action after the page loads ( checking the URL, site status, initiating connection whenever applicable)

Jetpack Connect HoC: provide passed props to the wrapped component.

---

client/components/jetpack/backup-date-picker/style.scss
client/components/jetpack/daily-backup-status/style.scss
client/components/jetpack/scan-threats/style.scss
client/components/jetpack/server-credentials-wizard-dialog/style.scss
client/components/jetpack/stats-footer/style.scss
client/components/jetpack/threat-description/style.scss
client/components/jetpack/threat-dialog/style.scss
client/components/jetpack/threat-item/style.scss
client/my-sites/backup/style.scss
client/my-sites/scan/style.scss

* Update type scale on Jetpack Backup/Scan.
* Use typeface variable on Jetpack Backup/Scan upsell pages.
cc @sixhours so that you're aware of this change.
Before | After
--|--
**For Jetpack.com**
* Spin up this PR by running `yarn run start-jetpack-cloud`.
* Open `http://jetpack.cloud.localhost:3000/` and select any Jetpack site with Scan and Backup.
* Confirm you see the changes and that everything looks good.
**For WordPress.com, Jetpack sites**
* Spin up this PR by running `yarn start`.
* Open `http://calypso.localhost:3000/` and select any Jetpack site with Scan and Backup.
* Confirm you see the changes and that everything looks good.
**For WordPress.com, Simple sites**
* Spin up this PR by running `yarn start`.
* Open `http://calypso.localhost:3000/` and select any Simple site with a …

Jetpack: update type scale on Backup / Scan

---

client/my-sites/domains/domain-management/edit/navigation/enhanced.jsx

This undoes a change in #43579 which hides the contact info and the transfer navigation items for domains if the user cannot access those. 
For a domain on one of your sites which you do not own:
- Verify the contact info and the transfer items both show in the navigation menu
- Verify clicking on any of them gives you a permission related notice

Domains: Display transfer and contact info menu items even if the user has no permissions

---

client/jetpack-connect/index.js
client/jetpack-connect/jetpack-connection.jsx
client/jetpack-connect/main-header.jsx
client/jetpack-connect/site-url-input.jsx

* Add route handling for Jetpack Connect routes with type and locale parameters.
* Open http://calypso.localhost:3000/jetpack/connect/scan/{locale} in non-logged window (e.g. Incognito Tab)
* Confirm it renders requested locale.
* Open http://calypso.localhost:3000/jetpack/connect/scan/{locale} in logged window
* Confirm you get redirected to route without locale and page renders with the locale from your user's settings.

i18n: Add Jetpack Connect route with locale param

---

client/components/jetpack/daily-backup-status/backup-changes.jsx

* In the case of a `post__published` activity, the `activityDescription` content can be either a string or an object, thus, we need to handle both cases. Before, we assumed that they always were strings, but now we now that for some activities this is not true, they can be objects as well.
* Check that post published events still look fine in the Backup section.
* Check that the user with the problem now sees the Backup section.
Fixes 1179060693083348-as-1182184869996409

Jetpack Cloud: handle different 'post__published' activity objects

---

client/components/activity-card-list/index.jsx
client/components/activity-card-list/style.scss
client/my-sites/activity/activity-log-v2/index.tsx

* Add a placeholder to be shown while the ActivityCardList is loading on Jetpack.com (or on WordPress.com, if the `activity-log/v2` flag is enabled).
Fixes `1179060693083348-as-1181062906895905`.
* For both Jetpack.com and WordPress.com, load the Activity Log (v2). To do this with WordPress.com, enable the `activity-log/v2` feature flag.
* Verify that you see a pulsing placeholder while activity log items are loaded, and that the placeholder looks like a silhouette of a real Activity Log.

Jetpack Cloud: Add loading placeholder for ActivityCardList

---

client/my-sites/people/invite-people/index.jsx

* Fix SSO notice logic
* Explicitly fetch Jetpack modules info on render
Before this PR:
- Disable SSO on your site. Navigate to `invites/new` via sidebar: Manage > People > Invite. SSO notice would be hidden.
- Enable SSO on your site. Navigate to `invites/new` via the sidebar. SSO notice would be shown.
- Reload the page. SSO notice will disappear.
After applying this PR:
- Disable SSO on your site. Navigate to `invites/new` via sidebar: Manage > People > Invite. SSO notice would be shown.
- Reload the page. Make sure notice is still shown.
- Enable SSO on your site. Navigate to `invites/new` via the sidebar. SSO notice would be hidden.
- Reload the page. SSO notice still hidden.
Fixes #39573

Invites: Fix SSO Notice logic

---

client/my-sites/scan/history/index.tsx
client/my-sites/scan/main.tsx

* Remove `wideLayout` in Jetpack Scan sections:
* Scanner
* History
Before | After
--|--
* Select a Jetpack site with the Scan product.
* Head to `Jetpack > Scan`.
* Ensure the layout is narrow and that it matches the Jetpack Backup section.

Jetpack: don't use wideLayout in Jetpack Scan sections

---

client/components/data/query-media-storage/index.jsx
client/state/data-layer/wpcom/sites/media-storage/index.js
client/state/data-layer/wpcom/sites/media-storage/test/__snapshots__/index.js.snap
client/state/data-layer/wpcom/sites/media-storage/test/index.js
client/state/sites/media-storage/actions.js
client/state/sites/media-storage/test/actions.js

* Refactor `requestMediaStorage` to use data layer
1. Go to `/media` and make sure the storage block is shown
2. On a site with a paid plan go to _Settings_ > _Performance_ and make sure it's shown there as well
Found this while working on media reduxification and took the opportunity.

media-storage: use data layer

---

client/signup/steps/p2-site/index.jsx

In this PR, we fix a slight bug when creating a new P2 site through the `/start/p2` signup flow.
Props @klimeryk for the report:
Navigate to `/start/p2`. Fill in a random site name. Fill in an invalid site address like `my-site-address!!.p2.blog`. When you click outside of the input field, it should be corrected to `my-site-address.p2.blog` and the previously filled site name field should stay the same.

P2 signup: fix site sanitization

---

client/lib/abtest/active-tests.js
client/lib/jetpack/paths.ts
client/state/selectors/is-jetpack-section-enabled-for-site.ts

* Launch Backup Section for all users
* Launch Scan Section for all Jetpack users
* Move Activity Log into Jetpack Section
* Launch Separate Jetpack Settings for all users
1. Launch the branch, verify the `showJetpackSidebar` is not present in the abtest menu 
2. Verify the Backup Section is visible under the Jetpack Section, verify that it works as expected for simple sites, atomic sites, and Jetpack Sites
3. Verify the scan section is visible for Jetpack Sites
4. Verify the "Jetpack" Settings section is visible for Jetpack Sites

Launch Jetpack Sidebar Section for all Users

---

client/lib/cart-values/types.ts
client/my-sites/checkout/composite-checkout/contact-validation.js
client/my-sites/checkout/composite-checkout/types/paypal-express.ts
client/my-sites/checkout/composite-checkout/types/transaction-endpoint.ts
client/my-sites/checkout/composite-checkout/wpcom/components/wp-checkout.js
client/my-sites/checkout/composite-checkout/wpcom/components/wp-contact-form.js
client/my-sites/checkout/composite-checkout/wpcom/components/wp-order-review-line-items.js
client/my-sites/checkout/composite-checkout/wpcom/test/shopping-cart-endpoint.js
client/my-sites/checkout/composite-checkout/wpcom/types/backend/shopping-cart-endpoint.ts
client/my-sites/checkout/composite-checkout/wpcom/types/checkout-cart.ts
client/my-sites/checkout/composite-checkout/wpcom/types/wpcom-store-state.ts

When G Suite support was added to new checkout, I failed to add the `google_apps_registration_data` property to the `extra` object on each cart item submitted to the transactions endpoint. That property is supposed to include a duplicate of the domain details record. This PR corrects that oversight.
- Attempt to purchase a G Suite subscription using composite checkout.
- Submit the transaction and examine the endpoint request that is sent; verify that it includes `extra.google_apps_registration_data` for each product under `cart`.

composite-checkout: Add missing google_apps_registration_data property to G Suite transactions

---

client/my-sites/checkout/composite-checkout/wpcom/components/coupon.js
client/my-sites/checkout/composite-checkout/wpcom/components/field.js
client/my-sites/checkout/composite-checkout/wpcom/components/form-field-annotation.tsx
client/my-sites/checkout/composite-checkout/wpcom/components/radio-button.js
client/my-sites/checkout/composite-checkout/wpcom/components/summary-details.js
client/my-sites/checkout/composite-checkout/wpcom/components/wp-checkout-order-review.js
client/my-sites/checkout/composite-checkout/wpcom/components/wp-checkout-order-summary.js
client/my-sites/checkout/composite-checkout/wpcom/components/wp-checkout.js
client/my-sites/checkout/composite-checkout/wpcom/components/wp-order-review-line-items.js
client/my-sites/checkout/composite-checkout/wpcom/hooks/product-variants.js
packages/composite-checkout/src/components/checkout-modal.js
packages/composite-checkout/src/components/checkout-steps.js
packages/composite-checkout/src/components/error-message.js
packages/composite-checkout/src/components/field.js
packages/composite-checkout/src/components/loading-content.js
packages/composite-checkout/src/components/payment-request-button.js
packages/composite-checkout/src/components/radio-button.js
packages/composite-checkout/src/components/spinner.js
packages/composite-checkout/src/lib/payment-methods/apple-pay.js
packages/composite-checkout/src/lib/payment-methods/existing-credit-card.js
packages/composite-checkout/src/lib/payment-methods/giropay.js
packages/composite-checkout/src/lib/payment-methods/ideal.js
packages/composite-checkout/src/lib/payment-methods/payment-logo.js
packages/composite-checkout/src/lib/payment-methods/paypal.js
packages/composite-checkout/src/lib/payment-methods/stripe-credit-card-fields.js
packages/composite-checkout/src/lib/styled-components/payment-method-logos.js

This adds RTL styles to `@automattic/composite-checkout` and its Calypso integration layer. There's discussion about using a [stylis plugin](https://github.com/emotion-js/emotion/issues/793) to automate RTL conversion for emotion styled components, but this PR just does it manually.
* If you're not already using local calypso in an RTL mode: in your `config/development.json`, change the line `"rtl": false,` to `"rtl": true,` and set your language in `me/account` to an RTL language such as Hebrew or Arabic. See also https://github.com/Automattic/wp-calypso/blob/master/docs/rtl.md
* Visit Checkout with a number of items in your cart (bundled, not bundled, renewals, etc.) using `?flags=composite-checkout-force`
* Click around the interface and verify that RTL styles are applied. Note …

composite checkout: RTL support

---

client/state/media/thunks/add-external-media.js
client/state/media/thunks/add-media.js
client/state/media/thunks/index.js
client/state/media/thunks/serially.js
client/state/media/thunks/test/add-external-media.js
client/state/media/thunks/test/add-media.js
client/state/media/thunks/test/serially.js
client/state/media/thunks/test/upload-media.js
client/state/media/thunks/upload-media.js

* Refactor `addMedia` to call to separate `uploadMedia` thunks depending on file count
* Create `addExternalMedia` to do the same but with an external media uploader
* Create `serially` wrapper to serially call `uploadMedia` for a list of files. This allows us to upload files one by one as is done in flux.
* The following should continue to work:
* Adding a new media for site icon or cropping an existing one
* Adding a new media for podcast cover image or cropping an existing one
* adding a new image through the classic editor media modal
* adding a featured image via drag-and-drop in the classic editor
* Unit tests should pass
* No other functional changes were made so there should not be other areas to test
Part 1 of #43661

Media: Reduxify `addExternal` into `addExternalMedia` thunk

---

apps/full-site-editing/full-site-editing-plugin/donations/donations.js
apps/full-site-editing/full-site-editing-plugin/donations/edit.js
apps/full-site-editing/full-site-editing-plugin/donations/fetch-default-products.js
apps/full-site-editing/full-site-editing-plugin/donations/fetch-status.js

The Donations block will rely on membership products existing to give the site visitor options for donating. If the user inserts a Donations block but does not already have some USD subscription products set up, the block will call the new `POST /memberships/products` endpoint (https://github.com/Automattic/jetpack/pull/16242) to generate some default products.
Part of #42856 .
* `cd apps/full-site-editing; yarn dev --sync;`
* Sandbox the API and the store. More info in PCYsg-lW4-p2 #sandbox-method
* Sandbox a test site with a paid plan, and ensure the site has the `fse-donations-block` blog sticker applied (if not, it can be done from the site's Blog RC).
* At `/earn/payments-plans/:site`, delete any existing test products.
* With devtools open, add a Donations …

Donations: Fall back to default products if no products are already defined.

---

client/my-sites/checkout/composite-checkout/use-create-payment-methods.js

This moves a user's existing cards to the top of the payment method options, after free and full credits. The order should be:
- free
- full credits
- existing cards
- apple pay
- any available local methods
- new card
- paypal
ref: p1593269871323900-slack-payments-shilling

composite-checkout: display existing cards before any other method

---

client/my-sites/domains/domain-management/controller.jsx
client/my-sites/domains/domain-management/list/list-all.jsx

* This PR moves the `SidebarNavigation` component from within the `ListAll` component to the all sites controller.
* Visit the [all domains view ](http://calypso.localhost:3000/domains/manage)
* Use the "toggle device" toolbar in the browser developer console to view the `all domains view` in a mobile resolution.
* Confirm that the `SidebarNavigation` (which is actually just a toggle) is visible at the top of the screen below the `All Domains` title.

Move SidebarNavigation component to the all sites controller

---

client/my-sites/domains/domain-management/list/list-all.jsx

Reverts Automattic/wp-calypso#43699

Revert "Move SidebarNavigation component to the all sites controller"

---

apps/wpcom-block-editor/src/calypso/features/iframe-bridge-server.js

Attempt to fix #38928 - upon investigation this seems to be due to an outdated selector.
* Sync wpcom-block-editor build from this PR.
* Test a site with a reusable block (must create a reusable block to see the noted section of the inserter)
* Search for "Reusable" in the block inserter and click the 'Manage all reusable blocks' link.
* Verify this leads you to the blocks management page in calypso.
Fixes #38928

Fix - 'Manage all Reusable Blocks' link in the block inserter.

---

client/landing/gutenboarding/onboarding-block/acquire-intent/style.scss

* This PR just ensures there's no line-break on intent gathering label (at least on English language) in all sizes starting from > 320px.
See p1593098213010700-slack-CNMU1UHHB.
* Go to `/new` and resize browser width.

Gutenboarding: Ensure no line break on every size (at least for English).

---

client/components/promo-section/promo-card/style.scss
client/my-sites/backup/wpcom-backup-upsell.tsx
client/my-sites/backup/wpcom-upsell.tsx

* Prevents widows on Jetpack Backup upsells.
* Add minimal margin to the title in `PromoSection` to create a bit of separation.
cc @Automattic/dotcom-manage-design for the last item of the list above.
Before | After
--|--
* Select a simple site on a free plan and go to:
* `Jetpack > Backup`
* `Tools > Earn`
* Make sure the promo cards look good in both instances.

Jetpack: prevent widows on upsell cards

---

client/components/jetpack/upsell-switch/README.md
client/components/jetpack/upsell-switch/index.tsx
client/my-sites/backup/controller.js
client/my-sites/scan/controller.js
client/my-sites/scan/main.tsx
client/state/data-layer/wpcom/sites/scan/index.js
client/state/selectors/get-site-scan-request-status.ts

Visiting the _Scan_ section of a Jetpack site without Scan enabled shows the loading placeholder indefinitely instead of showing the upsell section (see screenshot below). This PR fixes this.
There are several things to not here:
- The `JETPACK_SCAN_REQUEST_FAILURE` action needed to be explicitly dispatched from the error handler.
- For the Scan use case, the component `UpsellSwitch` used `state.jetpackScan.scan` for the loading logic, while it should have used `state.jetpackScan.requestStatus` (`state.jetpackScan.scan` stays an empty object if the request fails and the loading state cannot be identified).
- `UpsellSwitch` is shared between Scan and Backup sections.
- The loading logic in `UpsellSwitch` had code specific to the Backup section. With the new update, it made sense to extract …

Scan: Jetpack site with no Scan purchase is shown a loading placeholder indefinitely

---

apps/full-site-editing/full-site-editing-plugin/premium-content/blocks/buttons/edit.js
apps/full-site-editing/full-site-editing-plugin/premium-content/blocks/logged-out-view/edit.js
apps/full-site-editing/full-site-editing-plugin/premium-content/editor.css

For some reason I couldn't find, the Recurring Payments block acting as a subscribe button for the Premium Content block is auto-selected when the Premium Content block component is mounted.
This was causing some confusion since the Recurring Payments block displays a plan selector in the sidebar making users to assume that selector can change the plan of the Premium Content block. But that plan selector is actually useless since the Premium Content block [forces its selected plan to any nested Recurring Payments block](https://github.com/Automattic/wp-calypso/blob/ea4003723293ba41b1d367891cf9de7102c1beb9/apps/full-site-editing/full-site-editing-plugin/premium-content/blocks/buttons/edit.js#L40-L45). 
To help solving that problem this PR ensures the Premium Content block is auto-selected …

Premium Content: Handle plans in the container block

---

client/my-sites/domains/domain-management/edit/navigation/enhanced.jsx
client/my-sites/domains/paths.js
client/my-sites/email/email-forwarding/index.jsx
client/my-sites/email/email-management/index.jsx
client/my-sites/email/gsuite-add-users/index.jsx
client/my-sites/email/gsuite-purchase-cta/index.jsx
client/my-sites/email/index.js
client/my-sites/email/paths.js
client/my-sites/sidebar/index.jsx

* Add email routes for the all sites views
* Open the all sites domains view and then click through the "Set up your email" nav item and sub items and verify that the sidebar is not changing to the site specific view

Add email routes for the all sites views

---

client/components/jetpack/threat-history-list/index.jsx
client/components/jetpack/threat-history-list/index.tsx
client/state/selectors/get-site-scan-history.js

* Currently, the initial state of the filter is not in sync with the URL. A user going to `/scan/history/[site]/fixed` won't see the `Fixed` option as the selected one because the filter always starts with `All` as the default option. This doesn't impact what threats users see, since the data is in sync with the URL, thus, in the previous example user will only see fixed threats.
I took the opportunity to transform the `jsx` into a `tsx` and to configure some basic types. Please feel free to suggests improvements in this regard.
* Prerequisite: self-hosted Jetpack site with Scan and threats in the History section.
* Run this PR (Calypso Blue or Calypso Green).
* Visit `/scan/history/content-cat.jurassic.ninja/fixed`
* Verify the filter highlights the `fixed` option.
* Verify the History …

Jetpack Scan: set initial filter option from URL

---

client/my-sites/checkout/composite-checkout/composite-checkout.js

* #43391 fixed a theretofore unnoticed bug that caused problems with multi level TLDs, like `me.uk`. This PR ports that fix to composite checkout. Note that composite checkout is not yet live in the countries and currencies most likely to have been affected by this.
Enter checkout with a domain having a multi-level TLD; there's a list of the [ones we support](https://github.com/Automattic/wp-calypso/blob/master/client/lib/domains/tlds/wpcom-multi-level-tlds.json). Choose one where the top level TLD has extra data requirements - `uk`, `ca`, and `fr`. Make sure that you are prompted to enter extra country specific information during checkout.

Get top level TLD before deciding which cctld forms to display

---

client/my-sites/domains/domain-management/list/domain-item.jsx
client/my-sites/domains/domain-management/list/list-all.jsx
client/my-sites/email/paths.js

* Load detailed domain data when rendering the all domains list
* Show the site title/URL in the domain item
* Fix the Add email URL
* Render the privacy/transfer lock checkmarks
* Open /domains/manage and verify that the detailed domain data is queried and loaded

Load detailed domain data when rendering the all domains list

---

test/e2e/run.sh

* This PR fixes an issue we were having when running Jetpack e2e tests. The issue is that because we were overriding the suite for the signup tests, we were overriding it for other configs as well.  This PR makes sure we only apply the override if we're using the default `magellan.json` config file.
To Test, you'll want to try and run some of the configs locally. 
Run All Default tests - `CIRCLE_NODE_TOTAL=2 ./run.sh -g`
Run All Default tests minus some signup tests - `CIRCLE_NODE_TOTAL=2 SUITE_TAG=parallel ./run.sh -g`
Run Jetpack tests with suite tag - `CIRCLE_NODE_TOTAL=2 SUITE_TAG=parallel ./run.sh -j`
Run Jetpack tests w/o suite tag - `CIRCLE_NODE_TOTAL=2 ./run.sh -j`
All three runs should start different numbers of tests (89, 77, 43, 43 )

E2E: Apply suite-tag override only on default magellan config

---

client/components/jetpack/upsell-switch/README.md
client/components/jetpack/upsell-switch/index.tsx
client/my-sites/backup/controller.js
client/my-sites/scan/controller.js
client/state/sites/selectors/get-site-plan.ts
client/state/sites/selectors/get-site-products.ts
client/state/sites/selectors/index.js

* Adds a `productSlugTest`, which allows testing if a given product is purchased for displaying the product upsell.
* Create a connected Jetpack site without Backup.
* Purchase Backup and go through the flow to arrive at Cloud.
* Verify the product upsell does not appear and check the state to see if it is `unavailable`.
* Verify the same for the WordPress.com Jetpack section.
* Break the Jetpack connection.
* Verify the above again.
* Run the same tests, this time with a plan that includes a Backup product.
Fixes 1179060693083348-as-1182126242633417.

Queries products associated with a site to hide upsell

---

client/components/global-notices/style.scss

* We'd added a second drop shadow with a 56px spread behind global notices, to very slightly darken the screen around the notice.
* Removing the second drop shadow fixes the graphics rendering issue for certain graphics cards in Chrome. This is a less drastic and more backwards-compatible solution than `filter`, but it means we lose the extra visual depth.
* Example of the rendering bug: 
* Here's what the notice looks like with the extra drop shadow and without. 
**Before**
**After**
Fixes #42003

Global Notices: Remove secondary drop shadow

---

client/my-sites/customer-home/cards/tasks/task.jsx

* Update strings from "Remind me" to "Hide this" to be clearer about how to dismiss a task card
**Before**
**After**
*  Switch to this PR on a site that has an active task card (must have gone through the checklist and launched)
* Go to `/home` and note copy changes
Fixes #43342

Customer Home: Change strings for dismissing a task

---

client/my-sites/checkout/composite-checkout/composite-checkout.js
client/my-sites/checkout/composite-checkout/payment-method-helpers.js
client/my-sites/checkout/composite-checkout/use-create-payment-methods.js
packages/composite-checkout/src/lib/payment-methods/sofort.js
packages/composite-checkout/src/public-api.js

* Implement Sofort payment method in composite checkout.
* Apply D45520-code to force this payment method to be available (or use a vpn to spoof a German IP address), and enter checkout with Euros as your currency.

composite-checkout: Implement Sofort payment method in composite checkout package and use it in calypso

---

client/my-sites/sidebar/index.jsx
client/my-sites/sidebar/test/sidebar.js

With some recent changes to the onboarding flow in WooCommerce for eCommerce plan sites, we need to update the target of the "Store" link in the Calypso sidebar. This branch updates that link.
To test you need to have a site that is on an active eCommerce Plan
* Open up My Sites, and select your site that is an eCommerce Plan.
* Verify the link target is updated to  `admin.php?page=wc-setup&calypsoify=1`
* Verify the tests are passing

eCommPlan: Update store link target.

---

apps/full-site-editing/full-site-editing-plugin/donations/donations.js
apps/full-site-editing/full-site-editing-plugin/donations/edit.js
apps/full-site-editing/full-site-editing-plugin/donations/index.js
apps/full-site-editing/full-site-editing-plugin/donations/style.scss

Add a settings panel to the Donation block so user can toggle monthly, annual, and “Other” amount options on or off.
* Generate a new FSE build and sync it to your sandbox: `cd apps/full-site-editing; yarn dev --sync`.
* Sandbox the API and the store. More info in PCYsg-lW4-p2 #sandbox-method.
* Sandbox a test site with a paid plan, and ensure the site has the `fse-donations-block` blog sticker applied (if not, it can be done from the site's Blog RC).
* Insert a Donations block in a new post with the block editor.
* Verify you can toggle all the settings in the right sidebar and the UI updates accordingly.
* Save the post and reload the editor.
* Make sure the block loads with the previous state.
* Switch to the code editor and confirm the attributes are correctly serialized. You should …

Donation block: Add block settings

---

client/my-sites/plans/main.jsx
client/signup/steps/plans/index.jsx
client/state/current-user/constants.js

Removes all references to marketing pricing tests 2 and 3.
Most changes from 4e3101b11641b79d8d2226a3bc0ee6661da5d65c are reversed, however the `marketingPriceGroup` selector and associated logic is preserved for future tests.
1. Enforce a test account to the test pricing group 2.
1. Go through the sign up flow and stop at the plans step.
1. The Personal plan should be visible. Earlier, it would have been hidden.
1. Stay logged-in, go through the site creation flow and stop at the plans step. The Personal plan should be visible. Earlier, it would have been hidden.
1. Stay logged-in, go to `/plans`. The Personal plan should be visible. Earlier, it would have been hidden.
1. Enforce a test account to the test pricing group 3.
1. Go through the sign up flow and stop at the plans step.
1. The …

Remove references to old pricing tests

---

packages/plans-grid/src/constants.ts
packages/plans-grid/src/plans-details/index.tsx
packages/plans-grid/src/plans-grid/index.tsx
packages/plans-grid/src/plans-table/index.tsx

* Use plans store key from constant instead of registering.
* Rebuild plans grid package (simply run `yarn` on local folder just to be sure everything is rebuilt).
* Test on `/new` and ensure plans grid still works.

PlansGrid: Use plans store key from constant instead of registering.

---

client/lib/invites/actions.js

In this PR, we add additional props to the `calypso_invite_accepted` Tracks event:
- `is_p2_site`
- `inviter_blog_id`
That should help us identify how many people are invited to P2 sites and to which sites if needed.
Using a P2 site, go to `http://calypso.localhost:3000/people/new` and invite some other email address which doesn't have a WP.com account yet (you can use any 10 minute email provider, for example). After accepting the invite link, head to the Tracks dashboard to "Live View" and input the `calypso_invite_accepted` event. You need to wait 5-10 minutes for your event to be shown. Now, expand the event (the chevron on the left to its name). It should contain the above properties.
Note: everybody will get these two new props, not just P2 sites. I guess that's okay or should we …

P2: add additional props to calypso invite accepted event

---

client/my-sites/customer-home/cards/features/help-search/style.scss

This PR tweak the `<HelpSearch />` component which renders the support card, rightly rendered in the customer home page.
* Detect these visual issues paying attention to the help search section:
* Apply these changes
Confirm it fixes:
* The horizontal line
* placeholder items margin/padding
Fixes https://github.com/Automattic/wp-calypso/issues/43753

InlineHelp: fix visual minor issues

---

client/my-sites/domains/domain-management/edit/navigation/enhanced.jsx

When navigating Calypso in pt_BR, I found an error on the message displayed for `HTTPS encryption: on`.
After some research, I noticed it is being caused by [an existing string on translate.WordPress.com](https://translate.wordpress.com/projects/wpcom/pt-br/default/?filters%5Bstatus%5D=either&filters%5Boriginal_id%5D=360&filters%5Btranslation_id%5D=133376):
> Comment:
> - translators: the word 'on' appears between the product name and the date of next renewal
> - Shows as "HTTPS encryption: on" in the nav menu 
I checked only pt-BR but I believe we will have the same issue with more languages too.
As we can't translate the same word twice, it would be better to use `active` instead of `on` here.
cc @carinapilar

Change sslStatusHuman ON to ACTIVE

---

client/landing/gutenboarding/hooks/use-on-site-creation.ts

After choosing a paid plan in Gutenboarding, if the cart has been abandoned, when choosing the same plan in Calypso, the same plan will be duplicated in cart. This is the visible result on the `/checkout` page: https://cloudup.com/cZ2FvOMUJVa.
There are 2 ways of reproducing this and the only difference would be the `extra.context` property on the plan product:
**1. through `/plans` page**
`extra.context: "calypstore"`
Demo: https://cloudup.com/czLS4SU_si5
*There is also a possible unwanted redirect to `/plans` reported in https://github.com/Automattic/wp-calypso/issues/43433 but the user can also manually abandon cart and then go to Plans in Calypso to upgrade as seen in demo.
**2. through the Launch flow**
`extra.context: "signup"`
Demo: https://cloudup.com/cELnJgu193E
From the screen …

Gutenboarding: remove meta from plan product when adding to cart

---

client/my-sites/backup/wpcom-backup-upsell.tsx
client/my-sites/scan/wpcom-scan-upsell.tsx

* add `redirect_to` args to the backup and scan upsells on WordPress.com
1. spin up a new Jetpack site and connect
2. navigate to `/scan/:siteSlug` on a WordPress.com instance of the branch
3. purchase scan via the "Get daily scan" upset
4. verify you are redirected back to the same WordPress.com scan page
5. Repeat steps 2-4 for `/backup/:siteSlug`
Fixes 1164141197617539-as-1182651032185545

Add redirects back to WordPress.com from Jetpack Product Upsell Pages

---

client/components/jetpack/threat-dialog/style.scss

* maintain the design ( 140px width buttons ) for short phrases, but otherwise let scan dialogs expand horizontally
1. Have a test site with threat
2. Navigate to `/scan/` on Jetpack Cloud UI w/ branch
3. Open the "fix threat" or "ignore threat" dialog by clicking either button 
4. Verify english leaves the buttons at 140px54. Use dev tools to drop long text into the buttons
6. Verify mobile screen sizes still expand buttons correctly 
fixes 1164141197617539-as-1178616538435396

Jetpack Scan Section: Expand long text in button dialogs horizontally

---

client/me/security-checkup/two-factor-authentication.jsx
client/me/security-checkup/two-factor-backup-codes.jsx

* This change restructures the two 2FA-related security nav items to include a `QueryUserSettings` element in all cases, instead of just when we're showing a placeholder.
* Visit `/me/security` and check the status of the "Two-Step Authentication" entry, and (if it's visible) the "Two-Step Backup Codes" entry.
* Click on the "Two-Step Authentication" item/row.
* If you had 2FA enabled already:
- Disable 2FA, and then hit the "Back" button.
- Verify that the main security nav reflects the change after navigating back. (We'll do this later if you didn't have 2FA enabled 😄.)
- Click on the "Two-Step Authentication" item/row to get back to the 2FA screen.
* Work through the process to enable 2FA using either your phone number or an app, _but don't verify the backup codes yet_. (You should …

Ensure security nav always triggers two factor queries

---

client/me/social-login/index.jsx

* This fixes the title for the Social Logins header and page title when using the new navigation in `/me/security`.
* Go to `/me/security/social-login` either on staging or on calypso.live.
* Verify that the top navigation bar and the overall tab/window both have "Social Logins" as the title.

Fix title for Social Logins when viewed using new security navigation

---

.circleci/config.yml
desktop/bin/github/add-review.js
desktop/bin/github/dismiss-review.js
desktop/bin/github/review-actions.js
desktop/package.json

This PR adds Slack and Github notifications for wp-desktop CI. Existing notification logic has been ported from the [canary bridge](https://github.com/Automattic/wp-desktop-gh-bridge/) and [wp-desktop Circle config](https://github.com/Automattic/wp-desktop/blob/ea4649bad1710cae42cefe8596a3ea5779762c6f/.circleci/config.yml#L267).
Github reviews have now been augmented to include a direct link to the failing job:
<p>
A failing commit was created in this branch in f1728fff582a32838c510a2774a89cb959ff69d4. Confirmed that a Slack notification was posted, and a Github review added by the `wp-desktop` account.

ci: add wp-desktop Slack + Github notifications

---

.eslintrc.js

* Demote inclusive language rule to a warning
There are currently too many places to fix that cause errors for people for whom fixing them is out of scope. Likewise, there is no way to exclude specific terms (like `masterbar`) which will probably take a lot longer time to fix.
We can upgrade this rule back to an error (the default) once the rule supports exclusion lists in its configuration. I'm planning on opening a PR for this in the rule.

ESLint: Demote inclusive language rule to a warning

---

client/landing/gutenboarding/index.tsx

Chunked translations were broken in gutenboarding after implementing https://github.com/Automattic/wp-calypso/pull/39624.
more context: p1592907262460500-slack-gutenboarding
`@wordpress/i18n` used to work as a singleton, the `setLocaleData` function was used to update the global singleton with new translation strings.
However, after https://github.com/Automattic/wp-calypso/pull/39624, a new instance of i18n is created by the `createI18n()` function https://github.com/Automattic/wp-calypso/blob/master/packages/react-i18n/src/index.tsx#L72 and exposed to the react app via the `I18nContext` Provider. https://github.com/Automattic/wp-calypso/blob/master/packages/react-i18n/src/index.tsx#L27
Therefore when the Chunked translations code called `setLocaleData`, it was setting the translations …

Fix chunked translations in the /new flow

---

apps/full-site-editing/full-site-editing-plugin/starter-page-templates/page-template-modal/components/block-iframe-preview.js

Fix for #43611 where the preview for layouts containing RichText components would fail on the first render, but if you then clicked on other layouts, it would render correctly. This appeared to only affect Firefox, as Chrome looked OK.
In Firefox, when first previewing a layout that contains RichText elements, the blocks would fail rendering when calling [`createElement` in Gutenberg](https://github.com/wordpress/gutenberg/blob/c6df2f4207959a517884cabce26134e78f8bec6c/packages/rich-text/src/to-dom.js#L126). I'm not 100% sure of the cause, but the issue only occurred when we append the `renderedBlocksDOM` to the iframe. My suspicion is that because `createElement` [re-uses a single document](https://github.com/wordpress/gutenberg/blob/4178f2da468fe85505acd659bbd8fd3c95dcd7c9/packages/rich-t …

Fix broken rich text blocks in layout picker preview in Firefox

---

client/blocks/reader-full-post/_content.scss

This change handles styling the button block in reader to match the website It is only part 1 of 8 of this issue:
https://github.com/Automattic/wp-calypso/issues/43595
Before:
Taken from: http://calypso.localhost:3000/read/blogs/159889361/posts/1363
Firefox After:

Reader: ensure button block matches main site styles

---

client/gutenberg/editor/calypsoify-iframe.tsx

* Increases the iframe timeout value by 2 seconds to see if this fixes random redirects of the editor in Simple sites
* Checkout this PR to local calypso dev env and check that editor is iframed correctly in Simple and Atomic sites.

Editor: increase iframe timeout

---

client/lib/url/support.js

* Remove the domain-helper support URL - we don't use it anymore. See p7zo6Z-li-p2
* search for `DOMAIN_HELPER_PREFIX` anywhere in the codebase

Remove the domain-helper support URL

---

client/state/all-domains/reducer.js

* add `withStorageKey` to the all-domains reducer so the state is persistent. I followed the instructions here - https://github.com/Automattic/wp-calypso/blob/master/docs/modularized-state.md
* Load the all domains management screen. Then refresh and verify that it'll first show you the domains before refreshing the data or comment out the `QueryAllDomains` component and check that the domain list will still render

Fix the all-domains redux state to use `withStorageKey` so the state is persistent

---

apps/full-site-editing/bin/sync-newspack-blocks.sh

In the current FSE release we have gettext calls with the wrong text domain: https://plugins.trac.wordpress.org/browser/full-site-editing/trunk/newspack-blocks/synced-newspack-blocks/blocks/homepage-articles/view.php#L218
* Fix the text domain of the synced newspack blocks
```
cd apps/full-site-editing
yarn run sync:newspack-blocks --branch=master
grep "post author" full-site-editing-plugin/blog-posts-block/newspack-homepage-articles/blocks/homepage-articles/view.php
```
If you receive an error message like `ERROR: Referenced sniff "PHPCompatibility" does not exist` either put your `vendor/bin` directory into the path or make sure that you have installed the sniff (for example with `composer global require phpcompatibility/php-compatibility`).
This should show gettext calls with a …

FSE: Run phpcbf on the synced files to fix text domain

---

apps/full-site-editing/full-site-editing-plugin/editor-site-launch/index.php
apps/full-site-editing/full-site-editing-plugin/editor-site-launch/index.ts
apps/full-site-editing/full-site-editing-plugin/editor-site-launch/src/launch-button/index.tsx
apps/full-site-editing/full-site-editing-plugin/editor-site-launch/src/launch-modal/index.tsx
apps/full-site-editing/full-site-editing-plugin/editor-site-launch/src/launch-modal/styles.scss
apps/full-site-editing/full-site-editing-plugin/editor-site-launch/src/launch-step/index.tsx
apps/full-site-editing/full-site-editing-plugin/editor-site-launch/src/launch-step/styles.scss
apps/full-site-editing/full-site-editing-plugin/editor-site-launch/src/launch-steps/domain-step/index.tsx
apps/full-site-editing/full-site-editing-plugin/editor-site-launch/src/launch-steps/plan-step/index.tsx
apps/full-site-editing/full-site-editing-plugin/editor-site-launch/src/launch-steps/privacy-step/index.tsx
apps/full-site-editing/full-site-editing-plugin/editor-site-launch/src/launch/index.tsx
apps/full-site-editing/full-site-editing-plugin/full-site-editing-plugin.php
apps/full-site-editing/package.json

This PR introduces a set of components for site launch.
* **Launch**
Main launch component that handles the logic of deciding which launch step to show.
* **LaunchModal**
Modal that shows the main launch component.
* **LaunchButton**
Button that is added to the block editor header to open the launch modal.
* **LaunchStep**
Base component used by all launch step.
* **PrivacyStep/PlanStep/DomainStep**
Individual step components.
**Note:** I decided to leave the `editor-gutenboarding-launch` component alone as it's already been used in production and create another plugin folder `editor-site-launch` for this.
* Add `define( 'A8C_FSE_SITE_LAUNCH_ENABLE', true );` to `./config/sandbox.php`.
* Run `yarn dev --sync` on your local `apps\full-site-editing` folder.
* Go to …

FSE: Add skeleton for editor site launch.

---

apps/full-site-editing/full-site-editing-plugin/editor-domain-picker/src/domain-picker-button/index.tsx
apps/full-site-editing/full-site-editing-plugin/editor-domain-picker/src/domain-picker-modal/index.tsx
client/landing/gutenboarding/onboarding-block/domains/index.tsx
packages/domain-picker/src/domain-picker/index.tsx
packages/domain-picker/src/domain-picker/style.scss
packages/domain-picker/src/domain-picker/suggestion-item.tsx

This changes two things:
1. Makes DomainPicker accept `currentDomain` as a string, being the domain name itself.
2. Changes FSE domain picker just to show that this works. 
3. Adds selected state for DomainSuggestionItem. UI-wise it looks like the hover state, I got the inspo from 0:20 [in this video](https://d.pr/v/4JXMgX). 
4. A by product is that Gutenboarding now highlights the selected domain when you go back to the domain picker by pressing back. I love this.
1. Go to Gutenboarding and name your site.
2. Pick a domain. No domain should be highlighted at this step.
3. Press back to see it highlighted. 
1. In root, run `yarn start` to run Calypso
2. In `apps/full-site-editing`, run `yarn dev --sync` to run the app and sync it with your sandbox.
3. Create and sandbox a simple site.
4. …

Accept currentDomain as a string in domain picker

---

client/lib/abtest/active-tests.js
packages/domain-picker/src/domain-picker/index.tsx
packages/domain-picker/src/domain-picker/style.scss
packages/domain-picker/src/domain-picker/suggestion-item.tsx

1. It separates domains into two subgroups, free and paid.
2. It fixes the empty state on mobile. Currently, it looks like this:
<kbd><img src="https://user-images.githubusercontent.com/17054134/86241695-b4774480-bba3-11ea-9bc1-6c9ac5fed441.png" width="300" /></kbd>
After the change, it looks like this:
<kbd><img src="https://user-images.githubusercontent.com/17054134/86242118-762e5500-bba4-11ea-94f7-b9e817c39e25.png" width="300" /></kbd>
1. Search for a domain, placeholders should have the same structure as results.
2. Search for a very long domain (50+ chars), the API will give only free option, results should look sane (the Custom domains subgroup shouldn't show up at all).
3. Test on mobile. It should look as you'd expect.
4. Test empty state by emptying the search field. On Desktop …

Separate free and paid domains in domain picker and fix empty state on mobile

---

client/blocks/image-selector/index.jsx
client/blocks/image-selector/test/index.jsx
client/components/tinymce/plugins/media/drop-zone.jsx
client/components/tinymce/plugins/media/plugin.jsx
client/components/tinymce/plugins/simple-payments/dialog/product-image-picker.jsx
client/gutenberg/editor/calypsoify-iframe.tsx
client/lib/media/actions.js
client/my-sites/media-library/index.jsx
client/my-sites/media-library/list.jsx
client/my-sites/media-library/test/list.jsx
client/my-sites/media/main.jsx
client/post-editor/editor-featured-image/index.jsx
client/post-editor/editor-html-toolbar/index.jsx
client/post-editor/media-modal/gallery/drop-zone.jsx
client/post-editor/media-modal/gallery/remove-button.jsx
client/post-editor/media-modal/index.jsx
client/post-editor/media-modal/test/index.jsx

* Remove `MediaActions.setLibrarySelectedItems` and replace all usages of it with the redux action `setMediaLibrarySelectedItems`
* For the following areas, manually check that selecting, deselecting, auto-selection of uploaded items all continue to work:
* Block editor media modal
* Classic editor media modal for add media
* Classic editor media modal for featured image
* Classic editor gallery dropzone, selection, removal, editing
* Site icon settings
* Podcast cover image
* General site media
* Classic block media
* Classic block simple payments
Addresses part of #43664

State: Replace media selection flux action with redux

---

client/my-sites/checkout/composite-checkout/composite-checkout.js
client/my-sites/checkout/composite-checkout/use-create-payment-methods.js
packages/composite-checkout/src/lib/payment-methods/eps.js
packages/composite-checkout/src/public-api.js

* Add EPS payments support to composite checkout.
- Use D45560-code to force this payment method to be available from the API
- Add a plan to your cart and visit checkout. 
- Add `?flags=composite-checkout-force` to the query string in the URL and reload the page because currently it is disabled for international currencies.
- Verify that "EPS e-Pay" is an option displayed in the final payment step.
- Verify that you cannot pay if the "Name" field is empty.
- Fill out the "Name" field and submit the payment.
- Verify that you are redirected to a Stripe test page.
- Click to accept the payment and verify that the payment completes successfully and that the plan is purchased.

composite checkout: Add EPS support

---

.github/workflows/full-site-editing-plugin.yml
apps/full-site-editing/full-site-editing-plugin/full-site-editing-plugin.php
apps/full-site-editing/full-site-editing-plugin/readme.txt
apps/full-site-editing/package.json

This PR bumps the FSE plugin version to v1.11.0 for rolling out another release. It includes a fair few changes based on looking at https://github.com/Automattic/wp-calypso/commits/master/apps/full-site-editing. I've cross-referenced these below:
Included changes:
* Run phpcbf on the synced files to fix text domain #43792
* Fix page layout picker preview in Firefox (broken RichText blocks) #43822
* Domain picker: cleanup and analytics fix #43796
* Donation block: Add block settings #43798
* Premium Content: Handle plans in the container block #43684
* Donations: Fall back to default products if no products are already defined #43665
* FSE: Add plans grid modal #43593
* Add domain picker to FSE #42951
* Blog Posts Block: allow newspack-blocks installation from github #43526
* Nav sidebar: …

Update FSE plugin to version 1.11.0

---

client/components/jetpack/scan-history-placeholder/index.tsx
client/components/jetpack/scan-history-placeholder/style.scss
client/my-sites/scan/history/index.tsx
client/my-sites/scan/history/style.scss
client/my-sites/scan/style.scss
client/my-sites/scan/upsell.jsx
client/my-sites/scan/wpcom-scan-upsell.tsx
client/my-sites/scan/wpcom-upsell.tsx

There's some discrepancy in the class names of the high-level pages of the Scan feature. This can cause layout glitches when switching from page to page. This PR fixes it.
It moves the styles of the history placeholder header closer to its component as well.
1. Download the PR and run Calyspo
2. With a Jetpack site that has Scan, go to _Scan > Scanner_ and check that everything looks good (loading and normal state)
3. Switch between Scanner and History and check there's no layout glitch
4. With a Jetpack site that doesn't have Scan, go to _Scan_ and check the upsell page (loading and normal state). An issue tackled in #43698 prevents the display of the upsell for now.
5. Run Jetpack cloud
6. Check that _Scan > Scanner_ and _Scan > History_ still look good

Jetpack Scan: standardize main components class names

---

client/components/jetpack/threat-history-list/style.scss

Hovering the environment badge (the floating button at the bottom right corner) with the mouse triggers the loading of CSS that overwrites some of the page specific styles, moving the filters to the left of the screen (see screenshots). This commit increases the specificity of the styles in question.
1. Download the PR and run Calypso
2. Select a site that has a security threat
3. Go to _Scan > History_
4. Hover the environment badge
5. Check that the filters are still centered in the page

Scan history: prevent a filter layout glitch when hovering the environment badge

---

client/jetpack-connect/jetpack-connection.jsx
client/jetpack-connect/search.jsx
client/my-sites/checkout/checkout/index.jsx

* Process purchases via `/jetpack/connect/jetpack_search/yearly` and `/jetpack/connect/wpcom_search/yearly` routes. 
At the moment inputting urls is disabled at those screens. We use `/jetpack/connect/jetpack_search` for yearly product type, but since /yearly had been defined as a route, we should keep it functional.
Also, here we adapt product type definition such that it is independent of the actual route.
Second fix is processing purchases for Jetpack sites- we correct the condition that moderated WP.com vs. JP site type of product at checkout. It was adding an empty product and as such, redirecting to /plans.
* Go to ` /jetpack/connect/(jetpack|wpcom)_search/yearly` and verify the purchase process. 
* Verify the purchase for a Jetpack site.

Jetpack Search: enable purchases via "...search/yearly" routes.

---

client/landing/gutenboarding/components/domain-picker-button/index.tsx
client/landing/gutenboarding/onboarding-block/domains/index.tsx
packages/domain-picker/src/domain-picker/index.tsx

* Add `calypso_newsite_domain_search` track events for domain searches on gutenboarding
* Differentiate between modal/popover ui's through a `where` property
* Search term is recoreded via the `query` property
* Visit http://calypso.localhost:3000/new
* Enable debugging `localStorage.setItem( 'debug','calypso:analytics');`
* Click the domain picker dropdown, enter a search term
* You should see the new events firing for `calypso_newsite_domain_search`
Fixes #42892 (partial)

Add tracks event to collect domain searches

---

client/my-sites/backup/main.jsx

When non-daily-backup activities in the API are reported to be rewindable when the site does not have realtime backups, there is a slight disconnect in the UI because we make some UI assumptions, and the API does not agree. This PR updates the `backupsFromSelectedDate` method and strictly checks if the site has realtime backups, instead of assuming that the API will be correct.
The original bug is not easily reproducible, so I suggest using whatever mechanism is comfortable for you to reproduce the issue below. Apply this patch locally and the issue should be fixed.
It's also strongly advisable to check a number of other sites and ensure that no unexpected unrelated breakages have occurred.
Fixes # 5525

Jetpack Backup: Ensure that backups in backupsOnSelectedDate are correct

---

apps/full-site-editing/full-site-editing-plugin/editor-gutenboarding-launch/index.ts
apps/full-site-editing/package.json

* Track when launch button is clicked.
* `yarn dev --sync` the `app/full-site-editing` folder to your sandbox.
* Create a new site until reach the editor stage, copy the url (so your can reopen later), point to that site on your sandbox, close & reopen your browser if you have to, then reopen the url you copied.
* On your network panel on developer tools, ensure Preserve Log is checked.
* Click Launch.
* Check for `t.gif` request.
Fixes #43828

Gutenboarding: Track when launch button is clicked.

---

apps/full-site-editing/full-site-editing-plugin/editor-plans-grid/src/hooks/use-selected-plan.ts
apps/full-site-editing/full-site-editing-plugin/editor-plans-grid/src/plans-grid-button/index.tsx
apps/full-site-editing/full-site-editing-plugin/editor-plans-grid/src/plans-grid-fse/index.tsx
apps/full-site-editing/full-site-editing-plugin/editor-plans-grid/src/plans-modal/index.tsx
apps/full-site-editing/full-site-editing-plugin/editor-site-launch/src/launch-steps/plan-step/index.tsx
packages/plans-grid/src/plans-grid/index.tsx

Note: This PR is based off `add/fse-editor-site-launch` from https://github.com/Automattic/wp-calypso/pull/43825. When `add/fse-editor-site-launch` is merged, we'll change the base branch of this PR to `master`.
- Created `PlansGridFSE` smart component.
- Refactored `PlansGridButton` & `PlansGridModal` (in FSE) to reuse `PlansGridFSE`.
- Use `PlansGridFSE` in launch plugin's `PlanStep` component.
**Other changes:**
- Refactored some logic to `useSelectedPlan` hook.
- The `header` param is made optional in `@automattic/plans-grid` package.
**Setup**
* Add `define( 'A8C_FSE_SITE_LAUNCH_ENABLE', true );` and `define( 'A8C_FSE_PLANS_GRID_ENABLE', true );` to `./config/sandbox.php`.
* Run `yarn` on root calypso folder make sure `@automattic/plans-grid` package is rebuilt.
* Run `yarn dev …

FSE: Plans Grid Smart Component

---

apps/full-site-editing/full-site-editing-plugin/editor-domain-picker/src/domain-picker-button/index.tsx
apps/full-site-editing/full-site-editing-plugin/editor-domain-picker/src/domain-picker-fse/index.tsx
apps/full-site-editing/full-site-editing-plugin/editor-domain-picker/src/domain-picker-modal/index.tsx
apps/full-site-editing/full-site-editing-plugin/editor-domain-picker/src/hooks/use-current-domain.ts
apps/full-site-editing/full-site-editing-plugin/editor-site-launch/src/launch-steps/domain-step/index.tsx
packages/domain-picker/src/domain-picker/index.tsx

Note: This PR is based off `add/fse-editor-site-launch` from https://github.com/Automattic/wp-calypso/pull/43825. When `add/fse-editor-site-launch` is merged, we'll change the base branch of this PR to `master`.
- Created `DomainPickerFSE` smart component.
- Refactored `DomainPickerButton` & `DomainPickerModal` (in FSE) to reuse `DomainPickerFSE`.
- Use `DomainPickerFSE` in launch plugin's `DomainStep` component.
**Other changes:**
- Refactored some logic to `useCurrentDomain` and `useSite` hook.
- The `header` param is made optional in `@automattic/domain-picker` package.
**Setup**
* Add `define( 'A8C_FSE_SITE_LAUNCH_ENABLE', true );` and `define( 'A8C_FSE_DOMAIN_PICKER_ENABLE', true );` to `./config/sandbox.php`.
* Run `yarn` on root calypso folder make sure `@automattic/domain-picker` …

FSE: Domain Picker Smart Component

---

client/blocks/reader-full-post/header-tags.jsx

While writing a support doc, I noticed that the display of tags is not consistent between Reader post cards and full post:
* post cards display 3 tags, sorted by tag popularity
* full post displays 5 tags, not sorted
I thought it'd be best to make the sort order consistent between the two.
Before:
Post card
Full post
After:
Full post
Verify that full post shows the same first 3 tags as the post card. A good example is:
Post cards
http://calypso.localhost:3000/read/feeds/36149739
Full post
http://calypso.localhost:3000/read/feeds/36149739/posts/2786929875

Reader: make tags displayed consistent between post card and full post

---

apps/full-site-editing/full-site-editing-plugin/wpcom-block-editor-nav-sidebar/src/actions.ts
apps/full-site-editing/full-site-editing-plugin/wpcom-block-editor-nav-sidebar/src/attach-sidebar.tsx
apps/full-site-editing/full-site-editing-plugin/wpcom-block-editor-nav-sidebar/src/components/nav-sidebar/index.tsx
apps/full-site-editing/full-site-editing-plugin/wpcom-block-editor-nav-sidebar/src/components/nav-sidebar/style.scss
apps/full-site-editing/full-site-editing-plugin/wpcom-block-editor-nav-sidebar/src/components/toggle-sidebar-button/index.tsx
apps/full-site-editing/full-site-editing-plugin/wpcom-block-editor-nav-sidebar/src/components/toggle-sidebar-button/style.scss
apps/full-site-editing/full-site-editing-plugin/wpcom-block-editor-nav-sidebar/src/store.ts

**_Note to anyone reading this while preparing a release of the FSE plugin_**
Changes to the sidebar to make it behave like a modal. Rather than shrinking the editing space so the sidebar can fit beside it, this opens the sidebar overtop. Matches the latest mockup.
The sidebar now does things like:
- keyboard focus (using TAB) is constrained to only inside the sidebar
- sidebar can be dismissed with ESC or clicking the dark background
- "dialog" aria role
This also removed the need of adding magic classes to the `<body>` so that we could shrink the editing space. We no longer need to touch DOM elements outside of our own plugin.
**Test on dotorg site**
* …

Nav sidebar: sidebar opens over the editor, behaves like a modal

---

apps/full-site-editing/full-site-editing-plugin/full-site-editing-plugin.php
apps/full-site-editing/full-site-editing-plugin/readme.txt
apps/full-site-editing/package.json

* Version bump
* Changelog
I didn't mention the changes to plans grid or domain picker (which are under development) in the changelog.
* Apply D45968-code to your sandbox
* Check the donation block content is editable (#43834)
* Check the launch button records a track event (#43885)
* Add the `nav-sidebar-enabled` sticker to your test site (or define `WPCOM_BLOCK_EDITOR_SIDEBAR`) and check that clicking the (W) opens the nav sidebar
If approving this could you please also approve D45968-code :)

Update FSE plugin to version 1.12.0

---

client/state/sites/selectors/is-site-previewable.js

* Skip preview for P2 (wpforteams) sites
* Click the _View \<site>_ link, under the _Switch Site_ button on the sidebar. 
- P2 sites: It should redirect to your site instead of displaying a preview.
- Normal WPCOM sites: It should display a preview.
Fixes 588-gh-p2

New P2: skip preview 

---

client/reader/components/favicon/index.js

As of D45259-code we are not sending a possible favicon url if we have no blavatar, this adds a fallback to use `W` gridicon if we have no site icon.
Go to Reader -> expand Following Sites -> Sites should either have their site icon or a `W` logo.

Fallback to gridicon for missing site icon

---

client/blocks/reader-full-post/index.jsx
client/blocks/reader-full-post/style.scss
client/reader/controller.js
client/reader/stream/index.jsx
client/state/reader-ui/reducer.js
client/state/reader-ui/selectors.js
client/state/reader-ui/sidebar/reducer.js
client/state/reader/watermarks/actions.js

- Reader sidebar expanded/collpased sections will be persisted
- Reader selected stream will also be persisted, that way if a user navigates outside of the Reader when they come back the previously selected stream with be showed
- Fixed https://github.com/Automattic/wp-calypso/issues/43309
- Go to reader, expand/collapse section, refresh, the same sections should be collapsed/expanded
- Go to reader select a stream, go to my sites, go back to Reader the previous stream should be selected

Remember reader feed and sidebar selection
