- client/my-sites/domains/domain-management/list/domain-item.jsx
* Render the auto-renew checkmark using the detailed domain data
* Open /domains/manage and verify that the auto-renew checkmark is rendered properly. For mapped domains bundled with plan I decided to render the minus since the auto-renew is not changeable.
> Render the auto-renew checkmark using the detailed domain data

- client/lib/domains/index.js
- client/lib/domains/resolve-domain-status.js
- client/my-sites/domains/domain-management/edit/domain-types/mapped-domain-type.jsx
- client/my-sites/domains/domain-management/edit/domain-types/registered-domain-type.jsx
- client/my-sites/domains/domain-management/edit/domain-types/site-redirect-type.jsx
- client/my-sites/domains/domain-management/edit/domain-types/transfer-in-domain-type.jsx
- client/my-sites/domains/domain-management/list/domain-item.jsx
- client/my-sites/domains/domain-management/list/style.scss
* Show a DomainNotice in the all domains list
* Highlight rows with expiring/expired domains
I decided to move the status resolving in a separate helper function so that we have consistency across different domain presentations (list vs status page).
* Open /domains/manage and verify that the notices for expiring/expired/activating domains are rendered. Also verify that the rows are highlighted with 3px left border.
Fixes #
> Show DomainNotice in the all domains list

- client/my-sites/checkout/composite-checkout/composite-checkout.js
Somehow, the required second argument to `useStoredCards` was never passed. This argument is only used if there is an error while loading stored cards, but it would cause a fatal error in that case since `undefined` is not a function.
This PR adds that argument.
- Modify the stored cards endpoint to return an error. This can be done on the server or more easily by modifying the definition of `wpcomGetStoredCards` in `client/my-sites/checkout/composite-checkout/composite-checkout.js` as follows:
```
--- a/client/my-sites/checkout/composite-checkout/composite-checkout.js
+++ b/client/my-sites/checkout/composite-checkout/composite-checkout.js
@@ -101,7 +101,9 @@ const wpcom = wp.undocumented();
// otherwise we get `this is not defined` errors.
const wpcomGetCart = ( ...args ) => …
```
> composite-checkout: Pass onEvent handler to useStoredCards

- client/lib/products-values/constants.js
- client/state/sites/products/conflicts.ts
- client/state/sites/products/test/conflicts.ts
- client/state/sites/selectors/has-site-product.ts
- client/state/sites/selectors/index.js
* This adds a new file to detect product purchase conflicts, with the only implementation so far for Anti-Spam.
* Also adds a selector `hasSiteProduct` to check if a given site has a product or products.
* Unit tests pass.
Fixes 1181531115069428-as-1182817583001067.
> Create selector to check for product conflicts

- client/lib/products-values/constants.js
- client/my-sites/checkout/checkout/index.jsx
- config/development.json
* Adds Jetpack Anti Spam to the Plans page.
Revision D45785-code is required for this to work (Anti Spam is include in `/products` response).
Prerequisites:
* D45785-code running in your sandbox (public-api.wordpress.com sandboxed).
* Jetpack site.
Instructions:
* Run this PR (you have to run `yarn start` since this adds a new config variable).
* Select your Jetpack site.
* Visit `http://calypso.localhost:3000/plans/my-plan/[site]`.
* Confirm that you see the Jetpack Anti Spam product card.
* Does the copy looks right?
* Does the design looks right?
Fixes 1181531115069428-as-1182646983386223
> Jetpack Anti Spam: add Anti Spam

- client/lib/products-values/constants.js
- config/development.json
Reverts Automattic/wp-calypso#43880
^ This PR introduced by mistake a constant that was already present in a file:
```
ERROR in ./client/lib/products-values/constants.js
/Users/nathan/code/local-a8c/wp-calypso/client/lib/products-values/constants.js: Identifier 'JETPACK_ANTI_SPAM_PRODUCTS' has already been declared (54:13)
> 54 | export const JETPACK_ANTI_SPAM_PRODUCTS = [
```
> Revert "Jetpack Anti Spam: add Anti Spam"

- client/components/promo-section/promo-card/style.scss
* Ensures the "New" pill isn't super distant from the text upon breaking to a new line
Check the "New" pill on the Earn page and verify that it looks better in both English and other languages where the text is lengthier. (Screenshots below are in French) 
**Before:**
**After:**
cc @sixhours 
Fixes #43158
> Earn: Improve Wrapping of "New" Pill

- client/blocks/conversations/list.scss
In Reader Conversations, the entire comment is using the 'pointer' cursor, even for areas that are not clickable.
This PR resets the cursor so only clickable areas of the comment should use 'pointer'.
Visit Reader Conversations at http://calypso.localhost:3000/read/conversations. If you can't see any posts there, try liking this post: https://jetpack.com/2019/04/02/jetpack-7-2/ and refresh Conversations after a few moments.
When hovering over the comment, you should have a normal cursor.
When hovering over linked areas, like the author name (where they have a website) or the comment date, you should see the pointer cursor.
> Reader Conversations: fix pointer state

- client/state/data-layer/wpcom/theme-filters/index.js
This PR hides the legacy full site editing filter from the `/themes` magic search card (the advanced search where you can select to search by feature, layout, etc), but reveals it for users with a selected site that is eligible for full site editing.
* Only show the `feature:full-site-editing` filter on legacy FSE sites, otherwise omit it from being stored in state.
In the above screenshot note that if you start typing `full` as the feature, `full-site-editing` does not appear in the list.
* While logged out, go to `/themes`, and from the search card, click "feature", and start typing in `fullsiteediting` — you should not see the option in the list
* While logged in, and with a site that doesn't have the FSE sticker, go to `/themes` and you still shouldn't see the full-site-editing filter …
> Hide full-site-editing filter when selected site is not legacy-FSE

- client/blocks/image-selector/preview.jsx
- client/components/tinymce/plugins/media/plugin.jsx
- client/gutenberg/editor/calypsoify-iframe.tsx
- client/lib/media/actions.js
- client/lib/media/test/actions.js
- client/post-editor/editor-featured-image/preview-container.jsx
- client/state/data-layer/wpcom/sites/media/index.js
- client/state/data-layer/wpcom/sites/media/test/index.js
- client/state/media/thunks/fetch-media-item.js
- client/state/media/thunks/fetch.js
- client/state/media/thunks/index.js
- client/state/media/utils/flux-adapter.js
* create a `fetch` thunk which requests a media item by id
* replace usages of `MediaActions.fetch` with `fetch` thunk
1. Open the Gutenberg Editor and place an image somewhere in your post / site
2. Hit reload and click on the image, then hit _Replace_
The second step should trigger a network request to fetch media data. I'm not exactly sure why this call is there because there's already a fetch triggered by only clicking on the item (step 1) and there's another request to `/media` as soon as the media library popup is shown. Here's what this cascade of requests looks for me (same on this branch and master):
1. Open a post in the classic editor which contains an image
2. Open the browser devtools and switch to the _Network_ tab
3. Reload the window
4. Make sure there's an XHR request to …
> state: add `fetch` thunk and replace usages of `MediaActions.fetch`

- client/lib/post-metadata/index.js
- client/post-editor/editor-location/index.jsx
Google maps static image urls should be generated with the signature url part. 
Currently we generate the image using just the coordinates and the api key. By including the signature we are making it images not have a limit.
1. Apply the following PR. D45918-code and sandbox the api. So that api request come from your sandbox.
* Go to the Classic Calypso editor add a location. Save the post
* Does location have a URL that has a signature in it? 
* Edit the location. Does it still work as expected. 
Note that in this PR we are not always make the URL have the signature since when the user sets the address we don't make a request to the api to be able to generate the proper URL.
> Update: Add google maps static URLs with the signature query parameter

- client/components/forms/form-text-input/index.jsx
* This PR fixes the bug that the text cursor moves to the end when editing. See the below video.
The text field triggers `onChange` event then an ancestor component passes updated `value` prop to the field component. This bug occurs because the `value` prop change takes longer than React tolerates. Eventually React resets the selection, sets the value to the field, and moves the cursor to the end of the new text.
* Purchase any plan to see the checkout form.
* Enter the card holder name and delete a letter in the middle.
* The text cursor should not move to the end.
> Fix: Cursor in FormTextInput moves to the end when editing

- client/blocks/inline-help/inline-help-compact-result.jsx
- client/blocks/inline-help/inline-help-search-results.jsx
- client/blocks/inline-help/style.scss
This PR aims to fix Inline Help issue https://github.com/Automattic/wp-calypso/issues/43616 by
* disabling tabbing on search results (arrow navigation instead)
* allowing the selected item to change style when hovered
Fixes https://github.com/Automattic/wp-calypso/issues/43616
For before state:
* Go to wordpress.com/home/{your-site}
* Locate `Get help` section
* Enter search input
* See how tabbing selects search results
* Enter search input again
* Use arrow down to select a search result
* Notice how hovering the selected result doesn't change the visual state
For after state:
* Repeat the steps above locally or on this PR's [calypso.live link](https://calypso.live/?branch=update/inline-help-disable-results-tabbing)
* Tabbing should skip search results
* Hovering a selected item, the …
> Inline Help: disable tabbing on search results and allow selected item to change style when hovered

- client/my-sites/domains/domain-management/list/domain-item.jsx
- client/my-sites/domains/domain-management/list/list-all.jsx
- client/my-sites/domains/domain-management/list/style.scss
* Adds the `isLoadingDomainDetails` to denote the loading status for `DomainItem` components.
* Uses placeholders for action items while `isLoadingDomainDetails` is true.
> Add loading state for the all domain list item component

- apps/full-site-editing/full-site-editing-plugin/editor-domain-picker/src/domain-picker-button/index.tsx
- apps/full-site-editing/full-site-editing-plugin/editor-domain-picker/src/domain-picker-fse/index.tsx
- apps/full-site-editing/full-site-editing-plugin/editor-plans-grid/src/hooks/use-selected-plan.ts
- apps/full-site-editing/full-site-editing-plugin/editor-plans-grid/src/plans-grid-button/index.tsx
- apps/full-site-editing/full-site-editing-plugin/editor-plans-grid/src/plans-grid-fse/index.tsx
- client/landing/gutenboarding/constants.ts
- client/landing/gutenboarding/hooks/use-free-domain-suggestion.ts
- client/landing/gutenboarding/hooks/use-on-login.ts
- client/landing/gutenboarding/hooks/use-on-signup.ts
- client/landing/gutenboarding/hooks/use-on-site-creation.ts
- client/landing/gutenboarding/hooks/use-selected-plan.ts
- client/landing/gutenboarding/hooks/use-step-navigation.ts
- client/landing/gutenboarding/onboarding-block/domains/index.tsx
- client/landing/gutenboarding/onboarding-block/plans/index.tsx
- client/landing/gutenboarding/stores/onboard/actions.ts
- client/landing/gutenboarding/stores/onboard/index.ts
- client/landing/gutenboarding/stores/onboard/reducer.ts
- client/landing/gutenboarding/stores/onboard/selectors.ts
- client/package.json
- packages/data-stores/src/plans/actions.ts
- packages/data-stores/src/plans/index.ts
- packages/data-stores/src/plans/reducer.ts
- packages/data-stores/src/plans/selectors.ts
- packages/domain-picker/src/constants.ts
- packages/plans-grid/package.json
- packages/plans-grid/src/plans-grid/index.tsx
* Update condition to trigger automatic domain update when selecting Free plan.
* Add `plan` to `ONBOARD` store and remove `selectedPlanSlug` from `@data-stores/plans`.
* go to [/new](https://wordpress.com/new?fresh) in production and try to reproduce #43927
* go to [/new](https://calypso.live/new?branch=fix/gutenboarding-persist-free-domain) and the free domain should be persisted
* the rest of domain and plan selection functionality and analytics events should remain the same.
Fixes #43927
> Gutenboarding: persist free domain when selecting free plan

- client/lib/post-metadata/index.js
Fixes an error introduced in https://github.com/Automattic/wp-calypso/pull/43912
That causes a JS error when a user tried to add a new geo coordinate. 
* Set a site to use the previous Editor.  
* Create a new post using the older calypso editor, set a title, set the location, in the sidebar. 
* Notice that it works as expected.
> Calypso Editor: Check it geo coordinates are not invalid

- config/desktop.json
- config/horizon.json
- config/production.json
- config/stage.json
- config/test.json
- config/wpcalypso.json
* This PR flips the `rename-payment-blocks` feature flag to true so that the feature will be enabled across all environments, not just dev.
* See the following issues for context:
* https://github.com/Automattic/wp-calypso/issues/42862
* https://github.com/Automattic/wp-calypso/issues/42861
* Verify code changes to enable flag in all environments.
> Earn: flip rename-payment-blocks feature flag to true for all envs

- .github/workflows/full-site-editing-plugin.yml
In many cases, `origin` just by itself is an alias for origin/HEAD.
When a specific branch name is needed, such as in the case of the
CI caches changed in this commit, we can use HEAD as a direct
alias for the primary branch, regardless of to what it is currently
set.
See `set-head` entry in `git remote` man page: https://mirrors.edge.kernel.org/pub/software/scm/git/docs/git-remote.html
Our repository is configured with `HEAD -> master`:
```
$ git branch -l -a | grep remotes/origin/HEAD
remotes/origin/HEAD -> origin/master
```
* Update GitHub Action references to `master` branch with references to `origin/HEAD` or just `origin` or `HEAD` when appropriate
* Check that GitHub actions on this PR continue to work
Part of https://github.com/Automattic/wp-calypso/issues/43939
> GitHub Actions: Replace master references with origin/HEAD

- client/my-sites/checkout/composite-checkout/use-create-payment-methods.js
Per our discussion in pbOQVh-kI-p2, this PR moves the Stripe redirect payment methods (iDEAL, Bancontact, etc.) to the bottom of the list of available payment methods to better mirror their order in old checkout.
- Visit composite checkout after forcing one of the Stripe redirect methods to be enabled (you can do this using a VPN for a country like `NL` or applying a diff on the server like D45029-code).
- Verify that the redirect payment method is shown after the other payment methods (existing cards, then new cards, then paypal).
> composite-checkout: Move stripe redirect payment methods to end of list

- client/jetpack-connect/constants.js
- client/jetpack-connect/jetpack-connection.jsx
- client/jetpack-connect/utils.js
* Fixes an issue where the `ALREADY_CONNECTED` state isn't handled.
* Visit `/jetpack/connect/pro` (or other product) and input the URL of a Jetpack site that is connected and you own.
* End up on the checkout page.
> Redirects the checkout for Jetpack already connected state

- client/my-sites/themes/thanks-modal.jsx
* Update the `/themes` `ThanksModal` to use sentence case for the buttons instead of title case
Part of p9Jlb4-1ly-p2, and raised in https://github.com/Automattic/wp-calypso/pull/43933#issuecomment-655043127
* While logged in, go to `/themes` on your test site and switch themes. After activating the theme, the buttons for "View site" and "Edit homepage" should be in sentence case instead of title case
Fixes #
> Update theme thanks modal buttons to use sentence case

- client/my-sites/sidebar/index.jsx
Remove Jetpack menu section for new P2 sites.
- Make sure you have a p2 site selected in My Sites
- Jetpack menu item should not be visible
> Remove jetpack menu for p2 sites

- apps/wpcom-block-editor/src/wpcom/editor.js
- apps/wpcom-block-editor/src/wpcom/features/convert-to-blocks-button.js
* Adds a convert to blocks button to block toolbar in iframed editor as alternative to convert to blocks dialog
- Check out this PR and build the wpcom block editor files with yarn build:prod in the apps/wpcom-block-editor/package.json folder.
- Sync the files created by the build in the '/dist' folder with your sandbox widgets/wpcom-block-editor folder
- Make sure that a 'Convert to blocks' button appears when adding/editing a Classic Block
- Sync a build of https://github.com/WordPress/gutenberg/pull/23704 to current gutenberg build folder on sandbox, then reload the editor and make sure only one 'Convert to blocks' button shows
Before:
After:
Part of #43626
> Add a convert to blocks button

- client/post-editor/controller.js
- client/state/selectors/should-load-gutenberg.js
This relates to #43803 part of the project to deprecate the Calypso editor.
If the `editor_deprecation_group` user attribute has been set for the
current user, then we should load Gutenberg as the editor regardless of
their editor preferences. This updates the `should-load-gutenberg`
selector to handle that.
From Calypso, with a site that has the editor preference set to classic, set the `editor_deprecation_group` user attribute to `true` and then pick a post to edit and/or create a new post/page.
No matter how you try to get to the Calypso editor, you should always be redirected to Gutenberg.
> Editor: Force Gutenberg For Users in the Deprecation Group

- docs/monorepo.md
This question has come up a few times, so just updating the documentation.
> Docs: Update devDependencies docs since yarn migration

- client/components/tinymce/plugins/media/plugin.jsx
- client/lib/media/actions.js
- client/lib/media/test/actions.js
- client/my-sites/media-library/content.jsx
- client/my-sites/media-library/drop-zone.jsx
- client/my-sites/media-library/upload-button.jsx
- client/my-sites/media-library/upload-url.jsx
* Replace usages of `MediaActions.clearValidationErrors` with `clearMediaItemErrors`
* Replace only usage of `MediaActions.clearValidationErrorsByType` with `clearMediaErrors`
* Ensure media library errors still appear as expected and clear when expected (when you click the "x" button on the error)
* Ensure google and pexels integrations still work
* Ensure guided tour still pauses when an error is introduced and unpauses when the error goes away (do this by manually toggling the `shouldPauseGuidedTour` in React devtools)
Part of #43664
> Media: Swap flux media error clearing actions for redux actions

- client/lib/cart-values/index.js
- client/lib/cart/actions.js
- client/lib/plugins/test/sanitize-section-content.js
- client/lib/plugins/test/utils.js
- client/lib/plugins/utils.js
- client/lib/products-values/index.js
- client/lib/safe-image-url/index.js
- client/lib/safe-image-url/test/index.js
- client/login/ssr.js
- client/my-sites/plugins/controller.js
- client/my-sites/plugins/jetpack-plugins-setup/index.jsx
- client/reader/stats.js
* Change some function-local variable names and update JSDoc comments to remove problematic language
* Rename `whitelist` prop on `PlanSetup` to `forSpecificPlugin`
* Ensure unit tests pass
* Ensure installing a plugin under Jetpack with and without the `only=plugin-name` query parameter behaves as expected
Addresses part of #43395
> Misc: Remove problematic "blacklist"/"whitelist" language #43395

- client/jetpack-connect/jetpack-connection.jsx
It is an Appendix to https://github.com/Automattic/wp-calypso/pull/43956, addressing[ the comment](https://github.com/Automattic/wp-calypso/pull/43956#issuecomment-655148024) regarding plan retrieval info.
* Clear the plan info to avoid reusing this information at the subsequent connection attempt.
For a connected JP site, within a single browser session:
* initiate plan purchase at `/jetpack/connect/pro`
* verify the presence of the plan in cart at `/checkout` 
* initiate connection without plan selection at `/jetpack/connect`
* verify redirect to the canonical JP plans grid
> Jetpack Connection: clear the plan selection cookie after redirect to checkout during JPC

- client/login/wp-login/login-links.jsx
* Add the OAuth client ID as query parameter when going to the `Lost password` page from Jetpack Cloud login flow. With this, the `Lost password` page, which lives in WPCOM codebase, can offer a better experience for users coming from Jetpack Cloud (links will point to Jetpack Cloud instead of to WordPress.com). Without this, the login flow is broken for users that need to reset their password.
* Run this PR locally, Calypso build (`yarn start`).
* Visit `cloud.jetpack.com` in an incognito window. You will be redirected to WordPress.com login page.
* In the browser URL, replace the first part of the URL that says `https://wordpress.com/` with `http://calypso.localhost:3000` (keep the rest of the URL). This will load the Login page from your local environment.
* Verify that the `Lost …
> Jetpack Cloud: Add OAuth client ID as query parameter

- client/blocks/inline-help/inline-help-search-results.jsx
This PR checks if there are results in the cache for the current search query. If so, it picks and shows them up immediately. Finally, it performs a request in the second step in order to keep the data synced.
Type different terms in the search box in order to populate the cache. Then, type the same terms and confirm that it renders faster.
Confirm that the app performs the requests even if the component renders the results before.
Switch between the customer home page and the other pages and confirm that the data is persistent between these two components.
*
Fixes InlineHelp: pick up results from cache #43990
> InlineHelp: renders results from cache

- client/jetpack-connect/controller.js
- client/jetpack-connect/index.js
- client/my-sites/checkout/checkout/index.jsx
- client/state/jetpack-connect/constants.js
* Adds Jetpack Anti-Spam as an option for checkout.
* Refactors checkout to use product constants instead of strings.
**Notes**
* ~Relies on D45785-code.~
* ~There is a bug in #43956 that would interfere with this.~
* Visit `/jetpack/connect/antispam`.
* Input a connected Jetpack site URL.
* Verify that Anti-Spam appears in the cart.
* Check out and verify the product is added.
Fixes 1181531115069428-as-1182685648881645.
> Adds Jetpack Anti-Spam to checkout flow

- client/blocks/inline-help/style.scss
- client/my-sites/customer-home/cards/features/help-search/style.scss
* This PR updates the icon colors in admin search results.
1. Open the Help FAB and/or Customer Home
2. Type in a query. Example: `domain`
3. Make sure the icon colors look like the following:
**Normal state:**
**Hover state:**
**Active state:**
**Normal state:**
**Hover state:**
**Active state:**
cc @retrofox
> InlineHelp: Update icon colors in admin results

- client/my-sites/themes/auto-loading-homepage-modal.jsx
* Update "Yes, Activate" button in AutoLoadingHomepageModal to use sentence case ("Yes, activate")
* While logged in, go to `/themes` and switch your test site to use one of the main template first themes that support AutoLoadingHomepageModal (e.g. Rivington or Dalston) or any Varia child theme
* The button should say `Yes, activate` followed by the theme name, instead of `Yes, Activate`
Fixes #
> Update activate button in AutoLoadingHomepageModal to use sentence case

- client/my-sites/checkout/composite-checkout/composite-checkout.js
- client/my-sites/checkout/composite-checkout/wpcom/hooks/wpcom-store.ts
- client/my-sites/checkout/composite-checkout/wpcom/types/wpcom-store-state.ts
* When a user enters checkout, prepopulate the country code field with the data detected by `getCurrentUserCountryCode`. Uses the same mechanism as loading domain contact details from cache, so will not overwrite manually entered data.
Unforgeable screenshots to definitely prove it works:
You'll need to trick calypso into thinking you are in some other countries, for instance by using a VPN, or by manually setting `detectedCountryCode` as defined in this PR to any ISO 3166-1 alpha-2 (that means two-letter) country code, like 'ca' or 'jp' or 'br'.
You'll also need to force composite checkout to load, for example using the `?flags=composite-checkout-force` query parameter.
1. Enter checkout as a brand new user and verify that the country field is prepopulated and that the data is close to …
> composite-checkout: Use detected country code

- client/my-sites/customer-home/cards/tasks/site-setup-list/get-task.js
- client/my-sites/customer-home/cards/tasks/site-setup-list/index.jsx
- client/state/data-layer/wpcom/checklist/index.js
- client/state/selectors/is-site-checklist-complete.js
While trying to test https://github.com/Automattic/wp-calypso/pull/43861 we saw that the PR is heavily dependent on the date that will be deployed D45830-code. That condition not only makes testing more difficult (we have to manually override it after patching) but also leaves legacy code behind `if ( $site_created_date > strtotime( '2020-07-09' ) ) {` 
**UPDATE**
As @getdave suggested,
> current PR will not preclude the need to conditionally serve the new "site created" task based on the date the site was registered. If we serve these tasks to sites that were created in the past before this task existed then Users who have previously completed the checklist will have the checklist re-shown to them.
> However, this PR does **make it easier to deploy new tasks to new sites on the server …
> Sites Checklist: transform api data 

- client/blocks/inline-help/inline-help-search-card.jsx
This PR focuses on the input element of the search card. I've had to add a timeout since there is a race condition that makes the flow lose the focus.
Also, it rewrites the component using a function instead of a class inherited from the react Component one.
* Apply these changes
* Click on the FAB icon on order to open the popover
* Confirm that it focuses on the input search element.
Fixes https://github.com/Automattic/wp-calypso/issues/43958
> InlineHelp: Make focus on the search input element once open

- client/my-sites/checkout/checkout/checkout-terms.jsx
- client/my-sites/checkout/composite-checkout/wpcom/components/wp-checkout.js
- client/my-sites/checkout/composite-checkout/wpcom/components/wp-order-review-line-items.js
- packages/composite-checkout/README.md
- packages/composite-checkout/src/components/checkout-steps.js
- packages/composite-checkout/src/components/loading-content.js
- packages/composite-checkout/src/components/payment-request-button.js
This adds a relative link to the Terms of Service when the submit button is active and `position: fixed`. It also cleans up two small visual bugs where the fixed submit button overlaps the "total" in the final step, and the ApplePay button wasn't the correct height.
Fixes #43954 
Before | After
**To Test:**
- visit Checkout (`?flags=composite-checkout-force`) on a mobile device (or using the web inspector)
- complete the billing/contact information step if it's not already complete
- when the payment method step is active, the submit button should become `position: fixed`
- verify that the fixed submit button has a link to the Terms of Service
- click the link and verify that the Terms of Service are visible
> Checkout: update mobile submit button

- client/signup/steps/p2-site/index.jsx
Point "Learn more about P2" to https://wordpress.com/p2
* spin up this branch
* navigate to /start/p2
* check that "Learn more about P2" now links to https://wordpress.com/p2
> P2 signup: Change learn more link

- client/my-sites/customer-home/cards/tasks/site-setup-list/get-task.js
- client/my-sites/customer-home/cards/tasks/site-setup-list/index.jsx
This PR works in conjunction with `code-D45830` to seek to address https://github.com/Automattic/wp-calypso/issues/42846 by:
* Removing the "Your site has been created" banner from the My Home page.
* Add the "Site Created" celebration as a checklist step which is automatically marked as completed.
Note this PR is responsible for the text of the new checklist task for "Site Created" only. All persistence is handled in `D45830-code`.
This PR also updates the  `<SiteSetupList>` component to only show "Action" buttons for the task if the text for these is provided in the task definition. This avoids having to show an action button for "Create your site" when this is not possible as the site is already created and it would make absolutely no sense whatsoever. 
* Apply D45830-code to your …
> My Home - remove "site created" banner and add to checklist.

- client/me/purchases/remove-purchase/index.jsx
* Enable removal of Search product for Atomic sites without the need to contact support.
* Buy Search for an Atomic site using e.g.  `wordpress.com/jetpack/connect/jetpack_search` when proxied
* remove the product at `/me/purchases` tab
* verify that what follows is the cancellation survey, not a nudge to contact HEs.
Fixes https://github.com/Automattic/wp-calypso/issues/43768
> Jetpack Search: enable product removal for Atomic sites

- client/my-sites/domains/domain-management/edit/navigation/enhanced.jsx
* We are now just displaying the site name for recently registered domains that haven't resolved yet.
* Purchase a domain
* Navigate to the domain management edit interface i.e. `domains/manage/<domain>/edit/<site>`
* Confirm that the site name is used when domain is `activating` ...
> Update destination for newly registered/activating domains

- apps/full-site-editing/full-site-editing-plugin/starter-page-templates/page-template-modal/index.js
In Gutenberg the `isLarge` prop was removed from the Button component in https://github.com/WordPress/gutenberg/pull/23239 — this PR removes the prop from our instance of the Button block in starter page templates, so that it doesn't error in the console
This it the button in question — it should look the same after applying this change.
* Remove isLarge prop from Button component
* Add translators line to keep linting happy!
You should not see the following error in the console:
* Spin up a local development environment (e.g. go to the apps/full-site-editing directory and run wp-env start
* Run the local dev environment for FSE (e.g. fo to the apps/full-site-editing directory and run yarn dev or if you want to sync to your sandbox, run yarn dev --sync)
* In your WP install, go to create …
> Remove isLarge prop from Button block in FSE starter-page-templates

- client/webpack.config.node.js
- package.json
- yarn.lock
* Update webpack-node-externals and remove one instance of problematic language 
* Verify the build still includes the `@automattic/components` package by verifying that places that use the components still work. For example the ImageSelector's button usage.
Part of https://github.com/Automattic/wp-calypso/issues/43395
Related: https://github.com/liady/webpack-node-externals/pull/75
> Deps: Update webpack-node-externals to 2.1.0

- client/my-sites/customer-home/cards/tasks/site-setup-list/get-task.js
- client/my-sites/customer-home/cards/tasks/site-setup-list/index.jsx
Affords ability to have custom text for checklist Nav items that differs from the `title` shown in the checklist card content.
This is part of a solution to realise the design shown in https://github.com/Automattic/wp-calypso/pull/43861#issuecomment-653317424 whereby the checklist "Nav" item for "Site Creation" has _different_ text to the title text "Your site has been created!" shown in the main task card body.
* Adds an optional `label` prop to all enhanced `task` objects.
* Updates `<SiteSetupList />` to prefer using the `label` text for Nav items if it is provided. 
* Continue to fallback to original `title` prop to ensure backwards compability.
* Build Calypso `yarn && yarn start` - wait...
* Apply the following patch to your local environment by saving it as a …
> Allow checklist to have different text for Nav Items and the task "card" 

- apps/full-site-editing/full-site-editing-plugin/wpcom-block-editor-nav-sidebar/src/components/nav-sidebar/index.tsx
- apps/full-site-editing/full-site-editing-plugin/wpcom-block-editor-nav-sidebar/src/components/nav-sidebar/style.scss
* Adds a scrollbar to the nav sidebar when it overflows
* Stick the "create post" and "view all posts" button to the bottom of the sidebar (matches new mockup)
* Apply 45973-code to sandbox
* Shrink browser window
* It should scroll, should probably check what the default scrollbar looks like on Windows 🤔
> Nav sidebar scrolls if the items don't fit on the screen

- client/my-sites/checkout/checkout-thank-you/blogger-plan-details.jsx
- client/my-sites/checkout/checkout-thank-you/business-plan-details.jsx
- client/my-sites/checkout/checkout-thank-you/domain-registration-details.jsx
- client/my-sites/checkout/checkout-thank-you/ecommerce-plan-details.jsx
- client/my-sites/checkout/checkout-thank-you/google-apps-details.jsx
- client/my-sites/checkout/checkout-thank-you/header.jsx
- client/my-sites/checkout/checkout-thank-you/personal-plan-details.jsx
- client/my-sites/checkout/checkout-thank-you/premium-plan-details.jsx
This pull request updates the copy of the `Thank You` page which currently doesn’t convey the asynchronous nature of the G Suite provisioning process - something that leads users to cancel their G Suite subscription if they haven’t received the email with their credentials soon after seeing this page. It also refines the headings which were misleading in some cases:
Before | After
------ | -----
Before | After
------ | -----
Before | After
------ | -----
I've disabled the brown heading in this case as the G Suite account would have already been activated successfully, so it's probably less important to catch the user's attention here. I'm happy to revert that if someone has strong opinion about it though.
1. Run `git checkout update/gsuite-thank-you-copy` and start your server, or open a …
> G Suite: Refine copy on Thank You page

- client/my-sites/post-type-list/index.jsx
The `UpsellNudge` component suggests an upgrade for WordPress.com sites.
Showing it on Jetpack sites is unnecessary, as we don't show ads on Jetpack sites.
It may even be harmful as somebody might get an impression that we are going to show ads on their Jetpack site, which isn't true.
The problem was reported by @csonnek directly to Jetpack Crew, no issue was created.
The PR adjusts the condition for the `UpsellNudge` so it would not be rendered on Jetpack sites.
1. Open Calypso and choose a Jetpack site with 11 or more posts.
2. Go to the "Site -> Posts" section and make sure that the "Upsell Nudge" **doesn't** show up among the posts.
3. Switch the site to a WordPress.com one with a free plan. It should also have at least 11 posts.
4. Go to the "Site -> Posts" section and make sure that …
> Posts: Do not show "Upsell Nudge" on Jetpack sites.

- client/my-sites/marketing/tools/index.tsx
This PR adds a new card that highlights the Earn features to the Marketing Tools page. Context behind the update is provided on pbMlHh-n1-p2.
Below are screenshots showing the before and after...
Before:
After:
* Checkout branch (git checkout update/marketing-add-earn-banner)
* Run calypso
* Navigate to the Marketing Tools page (/marketing/tools/:siteSlug)
* Confirm that the Earn banner displays properly
* Click the link and confirm that it takes you to the Earn page.
> Marketing tools: Adding an Earn card to the Marketing Tools page.

- client/components/jetpack/upsell/index.tsx
- client/my-sites/activity/activity-log-v2/index.tsx
- client/my-sites/activity/activity-log-v2/style.scss
On free plans the Activity Log limits the display to show 20 items, hides the filter options, and provides an upgrade path to  unlock the full functionality. Activity Log v2 is currently limited to 20 items for free plans, but there is no upgrade path or explanation of why only 20 items show, and filtering still works.
This PR updates the Activity Log v2 so that it hides the filter and provides an explanation along with an upgrade path. The copy comes from the upgrade prompt in WordPress.com, and the layout is the same as the Upsell pages but with the icon removed.
When eligible for upgrade:
When Activity Log is fully activated:
Visit `/activity-log/<SITE_SLUG>` for the following types of sites and verify that the behavior is correct:
1. Free plan: upgrade shows
2. Any backup product: …
> Jetpack Cloud: Add upgrade path and hide filter in Activity Log v2

- client/lib/plans/features-list.js
This PR tweaks the language that describes the Payments features in the Plans comparison section of Calypso. These changes match the current verbiage on the /pricing page of WPcom.
Before:
After:
And here's a picture of the new tooltip copy:
* Checkout the branch (git checkout update/plates-tweak-payments-wording)
* Start Calypso (yarn start)
* Navigate to /plans/:siteSlug
* Confirm that the Payments row contains the updated copy.
> Plans: Tweak Payments feature language in the Plans feature list.

- client/landing/jetpack-cloud/index.js
- client/state/sites/actions.js
* try to re-request site info from wpcom in the case that the site in question does not have it's JSON API module active.
1. Set primary site to a Jetpack site, deactivate JSON API Module for that site
2. Navigate to `/` on Jetpack Cloud
3. Verify you eventually are taken to `/backup` or `/scan` for that site
> Retry site request to WPCOM on JSON API Module-related Failure

- client/my-sites/checkout/checkout-thank-you/header.jsx
The `CheckoutThankYouHeader` component makes two faulty assumptions: 
- That the optional `selectedSite` prop is set and contains an object.
- That the optional `purchases` prop is an array with at least a single element if it is set.
This PR corrects those assumptions.
- Without this PR, visit https://wordpress.com/checkout/thank-you/no-site and verify that you see an error boundary message and that there is a fatal error in the console. (You can do this in production.)
- With this PR, visit http://calypso.localhost:3000/checkout/thank-you/no-site and verify that you see a "Congratulations" page.
> Checkout Thank-You: Remove assumption that site and purchases exist

- client/my-sites/checkout/composite-checkout/composite-checkout.js
- client/my-sites/checkout/composite-checkout/record-analytics.js
- client/my-sites/checkout/composite-checkout/use-get-thank-you-url.js
This adds logstash logging for every call to `getThankYouUrl` in composite checkout.
- Visit composite checkout.
- Choose PayPal.
- Press the submit button (no need to confirm the actual payment).
- Visit logstash and look for the string `"thank you url generated"` and verify that you see the event you caused and that the `message` key contains the `url` and `arguments` for the call to `getThankYouUrl`.
> Add logging for getThankYouUrl arguments and result

- client/my-sites/stats/site.jsx
This PR adds a promotional banner below the chart on the Stats page, featuring the Earn features. Additional context is at pbMlHh-mP-p2.
Clicking the banner takes the customer to the Earn page where they can learn more about the features. From there, the customer can either upgrade or activate the feature, depending on whether they have a paid plan.
Before:
After:
* Checkout branch (git checkout update/stats-add-earn-card-v2
* Run Calypso (yarn start)
* Click the Stats link in the Calypso left nav.
* Confirm that the Earn promo banner is displayed.
* Click the link and confirm that it navigates to the Earn page.
> Stats: Adding promotional banner to the stats page, featuring Earn

- client/my-sites/stats/site.jsx
The Earn banner on the Stats page should not be shown to users without admin privileges. This PR adds a check for both admin privileges and use of WordAds.
* Checkout branch (git checkout fix/stats-earn-baner)
* Start Calypso (yarn start)
* Load the Stats page with users that have a variety of permissions (including non-admin)
* Confirm that the banner is not displayed to non-admin users.
* Confirm that clicking the banner directs admin users to the earn page/
Fixes #
https://github.com/Automattic/wp-calypso/pull/43832
> Stats: Adding admin and WordAds check to the Earn banner on Stats.

- client/gutenberg/editor/calypsoify-iframe.tsx
This increases the recently added iframe timeout value to 25secs to account for the very slow loading of the iframe in some circumstances. 
- Try running Calypso against a sandboxed site and several hard refreshes of the editor iframe page against a sandboxed site, and you will more than likely end up redirected to wp-admin with some of these refreshes
- Apply this PR to local calypso dev env and try again, and check that you don't get redirected to wp-admin at all
> Editor: Increase iframe timeout to account for very slow connections

- client/blocks/signup-form/index.jsx
- client/blocks/signup-form/passwordless.jsx
- client/blocks/signup-form/social.jsx
- client/blocks/signup-form/style.scss
- client/components/social-buttons/apple.js
- client/components/social-buttons/google.js
- client/lib/abtest/active-tests.js
- client/signup/config/flows-pure.js
- client/signup/config/step-components.js
- client/signup/config/steps-pure.js
- client/signup/controller.js
- client/signup/steps/domains/index.jsx
- client/signup/steps/user/index.jsx
Rolls back changes for 'Passwordless signup after Plans step' experiment pbxNRc-m0-p2
1. Go to /start
2. There **shouldn't** be any 'variantPasswordless' AB test variant and flow **shouldn't** redirect to `/start/onboarding-plans-passwordless/domains`
3. You should be able to complete the flow without errors.
> Rollback Signup test: Use Passwordless signup after Plans step #43061

- client/lib/media/actions.js
- client/lib/media/test/actions.js
* Remove `MediaActions.delete`
* Ensure all unit tests pass
* Ensure `MediaActions.delete` isn't used anywhere throughout Calypso
related to #43662
> media state: remove `MediaActions.delete`

- apps/notifications/src/panel/boot/stylesheets/main.scss
* Explicitly set top and bottom margins to 0px on buttons in the notifications header. This helps to better vertically center the content.
| ![IMG_4230](https://user-images.githubusercontent.com/2124984/87071542-5d4b2280-c1e8-11ea-94d5-5e79eb767c39.PNG) | ![IMG_4229](https://user-images.githubusercontent.com/2124984/87071261-f75e9b00-c1e7-11ea-9803-fdf857a1aa5d.PNG)| 
* Switch to this PR and load it on a mobile device
* Open the notifications panel and click a specific notification
* Note the heading (Back, title, up/down arrows); they should be vertically centered and aligned
* Double-check the notifications panel on a desktop screen.
Fixes #43490
> Notifications: Set 0 margins on buttons in the notification header area on mobile

- .circleci/config.yml
In many cases, `origin` just by itself is an alias for origin/HEAD.
When a specific branch name is needed, such as in the case of the
CI caches changed in this commit, we can use HEAD as a direct
alias for the primary branch, regardless of to what it is currently
set.
See `set-head` entry in `git remote` man page: https://mirrors.edge.kernel.org/pub/software/scm/git/docs/git-remote.html
Our repository is configured with `HEAD -> master`:
```
$ git branch -l -a | grep remotes/origin/HEAD
remotes/origin/HEAD -> origin/master
```
* Replace some rereferences to master in CircleCI with `origin` by itself or `HEAD` when a specific branch name is needed.
* CircleCI should continue to work as expected with the correct caching behavior
Part of https://github.com/Automattic/wp-calypso/issues/43939
> CircleCI: Replace some references to master with origin or origin/HEAD

- client/blocks/inline-help/inline-help-search-results.jsx
- client/blocks/inline-help/popover.jsx
- client/blocks/inline-help/style.scss
This PR collects a handful of issues about the InlineHelp / HelpSearch components. Let's discuss in each issue and just use this PR for testing and handle the code.
~- [ ] InlineHelp: Anchor to appropriate sections from admin results #44059~
* All changes to achieve the issues list.
🖥️ [Live test](https://calypso.live/?branch=update/support-improvements)
Test that all issues listed above are properly handled by these changes:
Before | After
-------| -----
Confirm the Popover auto-collapses once the user clicks in an admin section link and the viewport is in the mobile width.
~### InlineHelp: Anchor to appropriate sections from admin results #44059~
Fixes #44060
> InlineHelp: improvements

- apps/full-site-editing/full-site-editing-plugin/wpcom-block-editor-nav-sidebar/src/components/nav-item/index.tsx
- apps/full-site-editing/full-site-editing-plugin/wpcom-block-editor-nav-sidebar/src/components/nav-item/style.scss
- apps/full-site-editing/full-site-editing-plugin/wpcom-block-editor-nav-sidebar/src/components/nav-sidebar/index.tsx
- apps/full-site-editing/full-site-editing-plugin/wpcom-block-editor-nav-sidebar/src/types.ts
* Remove slug from items in the nav sidebar
* Remove `slug` from the network response when loading page info
* Check out branch
* Define `WPCOM_BLOCK_EDITOR_SIDEBAR` in `.wp-env.override.json`
* `cd apps/full-site-editing && npx wp-env start && yarn dev`
* Open the block editor at `localhost:4013` and open the nav sidebar
* The page/post slug shouldn't appear in the sidebar
Fixes #43974
> Nav sidebar: Remove the page slug which was displayed below the page title

- client/components/data/media-list-data/index.jsx
- client/components/data/media-list-data/test/index.jsx
- client/lib/media/actions.js
- client/lib/media/test/actions.js
- client/my-sites/media-library/external-media-header.jsx
- client/state/data-layer/wpcom/sites/media/index.js
- client/state/data-layer/wpcom/sites/media/test/index.js
- client/state/media/thunks/fetch-next-media-page.js
- client/state/media/thunks/fetch-next-page.js
- client/state/media/thunks/index.js
- client/state/media/utils/flux-adapter.js
- client/state/selectors/is-fetching-next-page.js
- client/state/selectors/test/is-fetching-next-page.js
* Create `fetchNextMediaPage` thunk
* Replace usages of `MediaActions.fetchNextPage` with `fetchNextPage` thunk
1. Open the media library on `/media` on a site with more than 20 images
2. Make sure all the images load (> 20); you should see several network requests in devtools
3. Now switch to _Pexels_ (dropdown left to the search bar) and fill in the search with a random term
4. Make sure those images load as well (> 20; depending on the search term)
5. Select a few items and hit _"Copy to media library"_
6. Make sure you see the newly added items as well as the rest of your media items
7. Repeat from 3) but using _Google_ this time
related to #43660
> media state: create `fetchNextMediaPage` thunk and replace usages of `MediaActions.fetchNextPage`

- bin/get-circle-artifact-url.js
#43993 broke downloading our calypso-strings.pot, this fixes it by bringing back the branch name to the CircleCI URL.
Ensure that `bin/get-circle-string-artifact-url` outputs a CircleCI Artifact URL to a calypso-strings.pot.
> CircleCI Artifacts: Change branch name back

- client/state/initial-state.js
- client/state/test/initial-state.js
Signup state requires a special case, where state gets loaded from the logged-out persisted state when the logged-in one is empty. This is done to enable signup flows where the user starts out logged out, but logs in as part of the process.
When signup state was modularised, this special handling remained in the portion of code that handles legacy state, rather than being moved to the portion that handles modularised state. This caused the previously mentioned flows to break.
This PR fixes that.
* Move signup special case from legacy state handling to modularised state handling
IMPORTANT NOTE: Do not test this in development. Development has a 25% chance of clearing persisted state as a way of detecting some classes of bugs, a feature which interferes with the normal behaviour of this …
> Fix signup flows with a login step

- apps/wpcom-block-editor/src/wpcom/features/use-classic-block-guide.scss
Rename to `styles` from `sass` in this file. `apps/wpcom-block-editor/src/wpcom/features/use-classic-block-guide.scss`.
I should've rebased this PR https://github.com/Automattic/wp-calypso/pull/44077 before merging because seems like there is a new file that is using typography package in the last 24 hours.
> Use styles folder instead.

- client/my-sites/activity/activity-log-item/style.scss
* Hide text overflow for Activity Log thumbnails, so that their alt text doesn't create large chunks of confusing whitespace.
* Make the font size for Activity Log thumbnails small, so their alt text is sized consistently with the rest of the UI when highlighted/visible.
* On a Jetpack site with Activity Log (preferably one with a custom 404 page), attach at least two pieces of media to a post and make their alternative text very long.
* Make the URL for that media unreachable by our CDN, by deleting or moving it **outside the WordPress interface.**
* Visit the site's Activity Log and find the media attachment event for the media you added.
* Verify that broken image thumbnails do not take up any extra space.
* Verify that working image thumbnails still display as before.
> Activity Log: Hide alt-text overflow for broken images

- client/me/security-checkup/social-logins.jsx
* This change fixes the `propTypes` for the new Social Logins component added as part of the work to restructure `/me/security`. The prop was declared as required, but with the wrong name... 😬 This change brings the declaration into line with the rest of the code. 🤦
* Navigate to `/me/security` in the calypso.live branch, and verify that there aren't any console errors.
> Fix console error due to bad propTypes declaration

- client/jetpack-connect/auth-form-header.jsx
Fixes https://github.com/Automattic/woocommerce-payments/issues/761
On the Jetpack Connection screens, made the "Woo-branded" title/header/subtitle messages have a higher priority than partner-related messages. So, if a site is on Pressable **and** is connecting WooCommerce Payments, the messages used will be the WooCommerce Payments ones, not the Pressable-related ones.
- Create a Pressable site. Alternatively, if you have setup the whole flow including a `wpcom` sandbox, DM me and I'll give you an easier way to test this without having to create a Pressable site.
- Install WooCommerce Payments and go through the Jetpack connection flow. If you're testing this on a local Calypso environment, you'll need to add `define( 'WOOCOMMERCE_CALYPSO_ENVIRONMENT', 'development' );` to your …
> WooDNA: Use the correct Woo-branded messaging in the Jetpack Connection flow even if the connection comes from a partner host like Pressable

- client/my-sites/customer-home/cards/features/help-search/style.scss
* Safari has some rendering weirdness with the help SVG icon; it appears off-center at certain browser widths, and "wiggles" side to side when the browser is resized. This happens regardless of the size of the container, border, margins, padding, display type, etc. and is unique to Safari.
* Using `transform` rather than `margin` to center the icon seems to fix the problem. I'm not sure why, but suspect it has to do with browser rendering/painting and the benefits of using transforms over positioning for rendering performance.
**Before**
**After**
* Navigate to Customer Home and check out the "More help" section; the help icon should be centered in the blue circle. It shouldn't "wiggle" when you resize the browser window.
Fixes #43169
> Customer Home: Use transform rather than margin to center SVG

- bin/build-languages.js
* Rewrite paths for modules from packages when matching chunk with POT refs
Run `CALYPSO_ENV=production BUILD_TRANSLATION_CHUNKS=true yarn run build` and confirm translation chunks in `public/evergreen/languages` contain strings from `packages/**`, e.g. look for strings from `packages/composite-checkout`.
> i18n: Rewrite paths for modules from packages when matching chunk with POT refs

- client/landing/gutenboarding/onboarding-block/domains/index.tsx
- client/lib/abtest/active-tests.js
- packages/domain-picker/src/domain-name-explanation/index.tsx
- packages/domain-picker/src/domain-picker/index.tsx
- packages/domain-picker/src/domain-picker/style.scss
- packages/domain-picker/src/domain-picker/suggestion-item.tsx
- test/e2e/lib/pages/gutenboarding/domains-page.js
- test/e2e/specs/wp-gutenboarding-spec.js
(More context in pbAok1-1eE-p2)
* Radio buttons.
* Skip/continue button to move onwards.
* Green “included in plans” text.
* Change label next to the free domain back to “Free”
* Remove free/paid grouping and have the free domain on top
* Fix weird font on domain name explanation image.
* Go to `/new` and test the domain picker.
* Also test it on mobile view with long domain names.
Fixes pbAok1-1eE-p2
> Gutenboarding: Use V5 domain picker.

- client/my-sites/checkout/composite-checkout/wpcom/lib/translate-cart.ts
- client/my-sites/checkout/composite-checkout/wpcom/types/backend/payment-method.ts
`translateResponseCartToWPCOMCart()` is used to transform the `ResponseCart` object (the data from the shopping cart endpoint) into the data we use in new checkout. Part of this is the "available payment methods" array. That array is passed through `readWPCOMPaymentMethodClass` which transforms it to an object with a `name` property. However, if the latter function is passed an unknown payment method, it will throw an error. This doesn't leave much room for the server to add new experimental payment methods, and it also is a poor experience for the user.
In this PR we instead ignore unknown payment methods.
- Modify the shopping cart endpoint to return an unknown allowed payment method string _or_ remove some of the allowed payment method strings from `readWPCOMPaymentMethodClass`.
- Load …
> Composite Checkout: Filter out unknown payment methods in translateResponseCartToWPCOMCart

- client/my-sites/backup/main.jsx
- client/my-sites/backup/wpcom-backup-upsell.tsx
- client/my-sites/backup/wpcom-upsell.tsx
- client/my-sites/scan/history/index.tsx
- client/my-sites/scan/main.tsx
- client/my-sites/scan/wpcom-scan-upsell.tsx
- client/my-sites/sidebar/index.jsx
Currently, Jetpack Scan & Backup pretty easily allows non-admins to access places which they shouldn't be able to access, notably the Checkout, which causes Calypso to start breaking. This PR fixes this, taking precedence from the Earn section. 
This is only applicable to non-admins; everything should be the same for administrators.
Firstly, the Jetpack section should disappear in the sidebar.
Individual sections tend to also receive these changes in Calypso, such as to prevent people accessing them by switching sites. For nudges, a notice should appear informing the user that only administrators can upgrade, just as is the case in the Earn section. 
If, however, the nudge does not appear as the site already has access to the product, the usual authorisation error should occur.
> Jetpack Scan & Backup: Hide for Non-Admins

- client/components/tinymce/plugins/wpcom-view/views/simple-payments/index.jsx
- client/post-editor/editor-featured-image/preview-container.jsx
- client/state/data-layer/wpcom/sites/media/index.js
* EditorFeaturedImagePreviewContainer: call `this.props.fetchMediaItem` instead of `this.props.fetch` (the latter doesn't exist on that component)
* Fix property access in data layer handler `requestMedia`
* Ensures Pay with Paypal block uses `QueryMedia` with valid `mediaId`s.
* Open a post which has a featured image in the classic post editor and verify no `Uncaught TypeError: this.props.fetch is not a function` error appears in the console.
* Using the classic post editor try adding a Pay with Paypal block, this shouldn't cause any errors in the console.
Fixes #
> fix(featured image preview): call `fetchMediaItem` instead of `fetch`

- client/gutenberg/editor/calypsoify-iframe.tsx
The classic block welcome guide is set to display for any site when the
user is in the deprecation group. This change adds a check to make sure
that the user has their editor set to classic for the site that they are
loading the editor for.
If that's not the case, then we don't set the query parameter on the
iframe because it's not for this site that they have been flagged to
receive the deprecation email.
* Set a user attribute for your user using wpsh on a sandbox $ update_user_attribute( USER_ID, 'editor_deprecation_group', true )
* Open the block editor on a site and in the browser dev tools select `post-new.php` or `post.php` as the javascript context and in console run `wp.data.dispatch( 'core/edit-post' ).toggleFeature( 'welcomeGuide' );` - The classic block Welcome guide will …
> Editor: Set the deprecation parameter only if the editor is classic

- client/landing/gutenboarding/available-designs-config.json
- client/landing/gutenboarding/available-designs.ts
- config/development.json
- config/horizon.json
- config/wpcalypso.json
A small PR to remove the feature flag `is_alpha` for the new designs and fulfil their destiny of making it to prod.
You can view the new designs on horizon.wordpress.com/new right now.
Questions for the division:
(Optional) Apply D45183-code to your sandbox.
D45183-code pulls preview content/headstarts sites using the design sites themselves, instead of their parent themes'
Fire up this branch. Check that the designs show at the design step.
Check for each design:
- the design thumbnail and preview
- the created site reflects what was promised in the preview :)
Fixes #43420
> Gutenboarding: launch new designs

- client/my-sites/stats/site.jsx
This PR fixes the event tracking for clicks on the Earn banner on the Stats page.
Here's a console output showing the Tracks event firing when the banner is clicked:
* Checkout the branch (git checkout update/stats-earn-banner-tracking)
* Start Calypso
* Navigate to the stats page (/stats/day/:siteSlug)
* Click the banner with the dev console open.
* Confirm that you are directed to the Earn page
* Confirm that the Tracks event fires
Fixes #43832
> Fixing event tracking for Earn banner clicks on the Stats page

- client/my-sites/domains/domain-management/list/index.jsx
- client/my-sites/domains/domain-management/list/style.scss
* This PR adds a section for the primary domain to the sites domain manager. The click handler to change the primary domain is not hooked up yet.
* Should look like this when viewed:
> Adds a section header to make primary domains more prominent

- packages/babel-plugin-i18n-calypso/package.json
- packages/babel-plugin-i18n-calypso/src/index.js
`babel-plugin-i18n-calypso` has started crashing since Babel 7.10.x, as it started adding `#__PURE__` annotations (comment blocks) for `__`. These comments are missing `loc` property and because of that `getExtractedComment` is throwing an error as it's trying to access deep nested properties of it.
* Exit `getExtractedComment` earlier if comment node is missing `loc` property
* Run `NODE_ENV=build_pot yarn build`. POT files should be compiled in `build/i18n-calypso` without getting errors of `Cannot read property 'end' of undefined` type.
> babel-plugin-i18n-calypso: Fix translate calls comment extraction

- client/lib/domains/resolve-domain-status.js
- client/my-sites/domains/components/domain-warnings/pending-gsuite-tos-notice.jsx
* This PR updates email setup messaging and colours to make it more consistent with other notifications.
* Purchase a G Suite subscription. Do not login into the subsequent account, nor accept the TOS.
* Confirm that the domain status notice has a notification about completing the G Suite setup.
* Confirm that the following are true:
- The status message starts with: "Your email "
- The email address is **bold** in the message
- The CTA button says "Finish setup"
- The status icon and message are wrapped with the `status-error` class which makes the colour red.
> Update email setup messaging and colours in the domain status notices

- client/lib/abtest/active-tests.js
- client/my-sites/checkout/checkout-system-decider.js
Currently, the new Checkout flow is only shown to EN-locale/US-geo/USD-currency users. Now that RTL support, translations, and most of our local payment methods have been added to the flow, we can open it up to more users. 
This PR implements a 90/10 (new/old) AB test for users previously excluded from the new flow. The test and gating excludes the following:
- users from the EN/US/USD cohort (100% of these users should see the new flow)
- Brazilian and Indian geo (until Ebanx and Dlocal support is added)
**To test:**
- verify that a EN/US/USD user is shown composite checkout and that the `showCompositeCheckoutI18N` AB test is not assigned (debug: `calypso:abtests showCompositeCheckoutI18N: new variation:` )
- verify that a user in Brazil or India is shown legacy checkout
- verify that …
> Checkout: add AB test for non-US/non-USD users

- client/blocks/plan-storage/bar.jsx
- client/blocks/plan-storage/index.jsx
- client/blocks/plan-storage/test/plan-storage.jsx
* This partially addresses #40986 by updating the hit state on the media library PlanStorage component to encompass the whole block rather than just upgrade link.
**Before**
**After**
* Navigate to `/media` on a site that is free or has a plan less than Business; there should be an upgrade link as shown above
* You should be able to click anywhere within the plan storage block to get to the Plans page to upgrade. Setting focus on the link should outline the whole block.
* Check the Media Library on a Jetpack site; you should not see the plan storage block at all
* Check the Media Library on a Business site; you should not see the upgrade link at all, and you should not be able to click on the plan storage box
> Media Library: Wrap plan storage bar in a link if an upgrade is available

- client/jetpack-connect/help-button.jsx
See p1HpG7-9xU-p2 for context
* Add hpi=1 to support link that is displayed in the Jetpack connect flow
- Checkout patch
- Go to http://calypso.localhost:3000/jetpack/connect and ensure that support link includes `hpi=1` 
- Enter URL to connect a site
- Ensure support link here also has `hpi=1`
Fixes #
> Jetpack Connect: Adds &hpi=1 to URL to signify that the user is in a purchase flow

- config/production.json
* add and enable the Jetpack Search feature flag in production env.
* purchase a plan at `wordpress.com/purchase-product/jetpack_search` when not proxied
> Jetpack Search:  enable Jetpack Search in production

- client/lib/plans/plans-list.js
- client/my-sites/plans/current-plan/jetpack-checklist/index.tsx
* Removes "enhanced search" from Jetpack Professional plan descriptions.
* Removes "enhanced search" step from the post-purchase checklist.
1. Navigate to `/plans/:jetpackSiteSlug`
2. Ensure that Jetpack Professional plan description contains no mention of "search".
3. Purchase Jetpack Professional for your Jetpack site.
4. Ensure you are directed to `/plans/my-plan/:jetpackSiteSlug`.
5. Ensure that there's no checklist item for "enhanced search" or adding a search widget.
> Jetpack Professional: Remove mentions of "enhanced search"

- client/my-sites/marketing/traffic/index.js
- client/my-sites/site-settings/jetpack-ads.jsx
* Adds WordAds CCPA configuration settings to Marketing -> Traffic for Jetpack sites
* Enable WordAds on a Jetpack site
* Navigate to Marketing -> Traffic
* Verify you can enable/disable CCPA as well as set a Privacy Policy link
* Verify changes apply to your Jetpack site
* Verify settings sync with Jetpack -> Settings -> Traffic in `wp-admin`
> WordAds: Add CCPA configuration settings for Jetpack sites

- client/landing/gutenboarding/available-designs.ts
Fixes issue with https://github.com/Automattic/wp-calypso/pull/44165 throwing a 404 for webp images in Google Chrome
* Force Gutenboarding designs to use .jpg images instead of webP
* Go to `/new/design` in Chrome and make sure the design images load
* Confirm they still load in FF / Safari, etc.
Fixes #
> Force Gutenboarding designs to use jpg instead of webp while we investigate webp 404s

- client/my-sites/domains/domain-management/list/list-all.jsx
* Loading the all domains list sometimes rerenders the list and it looks like it's reordering the domains list. Turns out that's because the `currentUser` capabilities are not loaded in one pass so the list is rerendered multiple times on initial load. To fix this I've added a check if we've loaded the sites first so there is no rerendering/reordering of the domains list.
* Disable caching in the devtools and reload `/domains/manage` multuple times. The list should load in one pass without reordering (try without this PR to see how it looks).
> Check if the sites has loaded before rendering the all domains list

- client/components/domains/search-filters/style.scss
* Force LTR text direction for domain extension (TLD) buttons.
**Before:**
**After:**
* Boot Calypso with RTL language (e.g. Hebrew)
* Go to `/start/domains` and confirm domain extensions are using `ltr` direction
> i18n: Force LTR direction for domain extension buttons

- apps/full-site-editing/full-site-editing-plugin/wpcom-block-editor-nav-sidebar/src/components/nav-sidebar/style.scss
In IE 11, the WP logo we use to dismiss the sidebar seemed to... _disappear_...
To fix this, the click guards needs a z-index higher or equal to the `.interface-interface-skeleton__header` otherwise the edit post header will appear on top.
Enable the sidebar by defining `WPCOM_BLOCK_EDITOR_SIDEBAR` as `true` in your sandbox.
Apply D46468-code to sandbox
Find your favourite IE11 testing method (Browserstack?)
The WP logo button should be there. 
Ensure it still works in other browsers :)
Fixes #44067
> WPCOM Block Editor: show dismiss button in IE 11

- client/my-sites/domains/domain-management/list/list-all.jsx
* Only load the `QuerySiteDomains` component once per `DomainItem` in the all domains list
* Don't render a placeholder for the `DomainItem` component within the `LazyRenderer` - once the all domain data is available we don't need to do that
* Open the network tab in your devtools and verify that the detailed domain data is only loaded once per site
* When you scroll down the list you shouldn't see the general domain item placeholder component loaded at all
> Fix some lazy loading weirdnesses with the all domains list

- client/lib/media/actions.js
- client/lib/media/test/actions.js
- client/my-sites/media-library/content.jsx
- client/my-sites/media-library/external-media-header.jsx
- client/my-sites/media-library/test/content.jsx
- client/my-sites/media/main.jsx
- client/post-editor/media-modal/index.jsx
- client/post-editor/media-modal/test/index.jsx
* Replace calls to `MediaActions.sourceChanged` with the redux action
* Test that changing the "source" of the media library works (move to pexel, google photos, etc) in the main media page.
Part of https://github.com/Automattic/wp-calypso/issues/43664
> Media: Replace MediaActions.sourceChanged with redux action

- client/signup/steps/p2-site/index.jsx
Fixes various smaller validation issues.
In this PR, we validate the fields of the `p2-site` P2 signup flow only on hitting the "Continue" button instead of trying to validate on blur as well. This way it's simpler due to the site validation async nature.
Navigate to `http://calypso.localhost:3000/start/p2` and play with the form to see if you like the validation logic. Try empty sites, sites which are taken, malformed site names, etc.
> P2 signup: validate fields only on Continue

- test/e2e/lib/components/secure-payment-component.js
* Something changed in the secure payment component and the e2e tests couldn't find the remove item from cart button. I suspect it was related to https://github.com/Automattic/wp-calypso/pull/44043 because of the timing that the test started failing, the fact that it deals with checkout, and that the full suite of e2e tests weren't run against it prior to merging.
* ensure e2e tests pass
> e2e:Fix coupon test

- client/lib/checkout/constants.js
In order to improve the refund flow for OVO, we need to a pass a phone number associate with the account through to dLocal.
ref: pbOQVh-h-p2
**To Test:**
- apply D46370-code, sandbox store, and sandbox `public-api`
- set your currency to `IDR` (Indonesia)
- visit legacy Checkout
- verify that OVO is shown as a payment method
- verify that the phone input is shown (with Indonesia pre-selected)
- verify that all 3 fields are required
- submit a payment with any name, 16-digit NIK, and 10-digit phone number
- verify that you're redirected to dLocal's sandbox payment gateway
> Checkout: add phone number to field OVO wallet

- client/my-sites/checkout/checkout/domain-refund-policy.jsx
In our composite checkout logging, we're getting the following error for the `map` function in the `DomainRefundPolicy` component: `TypeError: Cannot convert object to primitive value`
Unfortunately, it's hard to reproduce and infrequent, but I think this happens because we use a translation object for the map `key`. This PR switches the `key` to the array item's index. Worst case, it shouldn't hurt.
ref: p1594878303422400-slack-payments-dev
**To test:**
- Add a domain or domain renewal to the cart and visit composite checkout with `?flags=composite-checkout-force`
- Verify that the correct domain refund policy is shown without any console errors
> Domain Refund Policy: use array index instead of translate object for map key

- client/devdocs/design/typography.jsx
- client/devdocs/style.scss
*  Add some general guidelines for using Recoleta; only for page titles and one major heading per page, not for UI elements.
* Adds a visual example of Recoleta to match the content and UI examples shown
**Before**
**After**
* Go to `/devdocs/typography` and check out the Recoleta section for changes.
> Typography: Update devdocs guidelines to be more specific about Recoleta usage

- client/components/web-preview/content.jsx
* Fix blank iframe issue after switching from SEO mode to other views like Desktop, Mobile, etc. 
1. Try to preview any post or page
2. Switch from Desktop to other devices
3. Now Switch to SEO mode
4. Switch back to Desktop or other devices than SEO
Before: 
https://cloudup.com/c9gyEV_TOq7
After:
https://www.loom.com/share/adf28ee1ec7f4d9b8059c1b35506b0a5
Fixes #44184 
@sixhours
> Preview: Fix Search & Social breaks other previews

- apps/full-site-editing/full-site-editing-plugin/premium-content/premium-content.php
Starting with https://github.com/WordPress/gutenberg/pull/22686/, the PHP `register_block_type` block arguments for `context` and `providesContext` were deprecated (replaced by `uses_context` and `provides_context` respectively). This PR updates the usage to quiet the `doing_it_wrong()` errors.
* Set up a JN test site that is connected to WP.com and has a JP Premium plan attached.
* Install the latest Gutenberg plugin.
* Use the build artifact from the `FSE plugin / Build FSE plugin (pull_request)` task below as a ZIP plugin that you can upload to the test site.
* Create a post, and add a Premium Content block for testing.
* Save the post, and check the front-end of the post: the above errors should not display.
> Premium Content: Tidy up deprecation errors.

- apps/full-site-editing/full-site-editing-plugin/wpcom-block-editor-nav-sidebar/class-wpcom-block-editor-nav-sidebar.php
- apps/full-site-editing/full-site-editing-plugin/wpcom-block-editor-nav-sidebar/src/components/nav-sidebar/index.tsx
- apps/full-site-editing/full-site-editing-plugin/wpcom-block-editor-nav-sidebar/src/components/nav-sidebar/style.scss
- apps/full-site-editing/full-site-editing-plugin/wpcom-block-editor-nav-sidebar/src/constants.ts
Adds the site title and a link to the site homepage to the top of the nav sidebar.
* Server renders a `wpcomBlockEditorNavSidebar` constant on the page that contains the site's home url (it wasn't readily available anywhere in the data store that I could see)
* Displays the site title at the top of the sidebar
* Displays a link to the site's homepage that will open in a new tab
* Sandbox your favourite test site
* Apply D46470-code to your sandbox
* Define `WPCOM_BLOCK_EDITOR_SIDEBAR` in your sandbox
* Go to the block editor and click the (W) to open the sidebar
Fixes #43973
> Nav sidebar: Add site title and link to the sidebar

- client/my-sites/sidebar/index.jsx
Fixes #42619
In this PR, we fix when we show or hide "Tools" and "Manage" sections in the sidebar based on user's capabilities in regards to the selected site or if it's an All Sites view based on whether the user has capabilities on at least a single site.
I think it's partly a regression introduced in #34676 but I might be wrong.
Create a new WP.com account. Invite that wpcom account to another wpcom site as a contributor.
When you select the site on which you are contributor, you shouldn't see Manage and Tools in the sidebar. When you select your primary site, you should see both. When you select All Sites view, you should also see both items since you have the capabilities on the primary site.
> Sidebar: fix showing Tools&Manage based on capabilities

- client/components/domains/search-filters/style.scss
* Add `!` at the beginning of the `rtl:ignore` comment to prevent it from being stripped in compressed mode (production build)
* Set your WordPress.com UI to any RTL language
* Open calypso.live with the branch from this PR and go to `/start/domains`.
* Confirm TLD buttons are using `ltr` direction.
Related https://github.com/Automattic/wp-calypso/pull/43934
> i18n: Preserve rtl:ignore directive comment for domain extensions direction

- client/components/formatted-header/index.jsx
- client/jetpack-connect/test/__snapshots__/auth-form-header.js.snap
- client/lib/formatting/prevent-widows.js
- client/my-sites/backup/wpcom-backup-upsell.tsx
- client/my-sites/scan/style.scss
- client/my-sites/scan/wpcom-scan-upsell.tsx
* Adds two new upsell designs mirroring the work done for cloud.jetpack.com and in #44187.
**Backup - VaultPress**
**Backup - Multi-sites**
**Scan - VaultPress**
**Scan - Multi-Sites**
- Create a Jetpack multisite and connect it.
- With this code, visit wordpress.com and navigate to the Backup nav for the site.
- Verify Backup matches the screenshot for multi-sites above.
- Do the same, but with Scan.
- Do the same but with a single site with VaultPress installed.
- Verify Backup & Scan matches the screenshot for VaultPress above.
**Note:** Jetpack Scan may not show the correct state for multisites. This is a known API issue. An alternative way to test would be to set the `reason` prop on the `WPCOMScanUpsellPage` component.
Fixes 1184358343400545-as-1184719508034178.
> Prevents upsell for Jetpack Backup & Scan for WP.com

- config/horizon.json
- config/stage.json
- config/wpcalypso.json
* This enables the Jetpack Anti-Spam product on staging and horizon environments.
* Either start stage/horizon or wait till the build of calypso.live finishes.
* Verify Jetpack Anti-Spam appears.
Fixes 1181531115069428-as-1184719508033177.
> Adds the Anti-Spam product on staging and horizon

- apps/full-site-editing/full-site-editing-plugin/premium-content/subscription-service/class-jetpack-token-subscription-service.php
The Premium Content block causes log errors by calling a non-static method statically to get tokens. This PR corrects the code usage to avoid the errors.
Discovered by @blackjackkent while testing #44192 .
* Set up a JN test site that is connected to WP.com and has a JP Premium plan attached.
* Sandbox the store and API. Set the JN site to use the sandboxed API (WP Admin > Settings > Jetpack Constants).
* Install the latest Gutenberg plugin.
* Use the build artifact from the `FSE plugin / Build FSE plugin (pull_request)` task below as a ZIP plugin that you can upload to the test site.
* Create a post, and add a Premium Content block for testing.
* Save the post, and open the front-end of the post in an incognito window.
* Subscribe to the content, using the test …
> Premium Content: Correct "non-static method call" errors.

- client/my-sites/domains/domain-management/list/domain-item.jsx
- client/my-sites/domains/domain-management/list/index.jsx
- client/my-sites/domains/domain-management/list/style.scss
This adds the ability to set domains as primary in the new site domains view.
- Go to /domains/manage/<site>
- Test 'Make primary domain' button works as expected
Also, set `state.changePrimaryDomainModeEnabled` to `true`, and:
- Verify the radio button shows correctly
- Verify on free sites, the plan upsell appears
- Make sure choosing any domain makes that domain primary (when eligible)
> Domains: Add make primary domain functionality to new site domains view

- client/my-sites/plans/current-plan/current-plan-thank-you/style.scss
* In Safari, the Thank You modal is broken because the image takes the whole height of the screen. This PR fixes this by setting, in the parent component, the `align-items` CSS prop to `center`. This bug is affecting the Jetpack Search Thank You modal as well.
* Run this PR and open **Safari**.
* Visit `http://calypso.localhost:3000/plans/my-plan/[site]?thank-you=&product=jetpack_anti_spam`.
* Verify that the modal looks fine.
* Visit `http://calypso.localhost:3000/plans/my-plan/[site]?thank-you=&product=jetpack_search`.
* Verify that the modal looks fine.
Fixes #
> Jetpack Anti-Spam: fix broken Thank You modal in Safari

- client/signup/steps/p2-site/index.jsx
In this PR, we fix invalid blog title validation in the P2 signup flow.
> If you put a HTML-like input in the site title field, like <img src, you'll get a validation error... but on the wrong field - the site URL 😅 Even if the site URL is actually valid:
Navigate to `/start/p2` and fill in the name of the P2. Try invalid names like `<img`. Fill in site address and hit "Continue". It should show correct validation. Verify you can create a P2 site by filling in valid inputs.
> P2: Signup: fix invalid blog title validation

- client/my-sites/email/email-forwarding/style.scss
Should be a super quick and easy review to an issue which I just spotted on Calypso: the count for Emailing Forward doesn't pass the colour contrast requirements. Most of these were updates ages ago, but I suspect this one was just missed.
Check the screenshots below (the page is `/email/**siteSlug**/forwarding/**domain**`).
**Before:**
**After:**
cc @sixhours, @cbauerman
> Email Forwarding Count: Improve Colour Contrast

- client/my-sites/customer-home/locations/primary/index.jsx
- client/my-sites/customer-home/locations/secondary/learn-grow/index.jsx
- client/my-sites/customer-home/locations/tertiary/manage-site/index.jsx
- client/state/preferences/schema.js
Fixes https://github.com/Automattic/wp-calypso/issues/43767 and https://github.com/Automattic/wp-calypso/issues/43984
This PR adds handling to automatically track home card impressions in primary, secondary and tertiary locations
I also relaxed schema validation for preferences. Previously we were throwing out persisted state in indexedDB, because home task cards were storing objects instead of the expected boolean value.
- Spin up this branch
- Visit calypso.localhost:3000/home
- In devtools set `localStorage.debug = 'calypso:analytics*';` in console
- Refresh home
- We should see the following card tracking events.
- Try completing or dismissing task cards. We should see additional impression events.
- We should see no warnings about schema validation errors for preferences persistence …
> Home: track card impressions and relax dismissable-card schema validation

- client/my-sites/checkout/composite-checkout/composite-checkout.js
- client/my-sites/checkout/composite-checkout/types/transaction-endpoint.ts
- client/my-sites/checkout/composite-checkout/use-get-thank-you-url.js
- client/my-sites/checkout/composite-checkout/wpcom/components/wp-checkout.js
- client/my-sites/checkout/composite-checkout/wpcom/hooks/use-shopping-cart.ts
This normalizes all the debug function keys used throughout the
composite-checkout section of calypso (not the package by the same name,
which has its own key) so that they all start with
`calypso:composite-checkout`.
- Visit composite checkout, set `localStorage.setItem('debug', 'calypso:composite-checkout:*')` and reload the page.
- Verify that you see a bunch of logs, notably that you see lines from `calypso:composite-checkout:shopping-cart-manager`.
> Make all composite-checkout debug lines in calypso start the same

- test/e2e/lib/components/secure-payment-component.js
This is a follow-up to https://github.com/Automattic/wp-calypso/pull/44213 just to make sure that the `SecurePaymentComponent.removeFromCart` function will work for both old and new checkout, following the pattern of the rest of the class.
Make sure e2e tests continue to pass.
> e2e tests: Make SecurePaymentComponent.removeFromCart work for both checkouts

- client/lib/abtest/active-tests.js
- client/me/concierge/shared/no-available-times.js
- client/my-sites/checkout/checkout-system-decider.js
- client/my-sites/checkout/checkout-thank-you/business-plan-details.jsx
- client/my-sites/checkout/checkout/checkout-container.jsx
- client/my-sites/checkout/composite-checkout/composite-checkout.js
- client/my-sites/checkout/composite-checkout/payment-method-processors.js
- client/my-sites/checkout/composite-checkout/types/transaction-endpoint.ts
- client/my-sites/checkout/composite-checkout/use-get-thank-you-url.js
- client/my-sites/checkout/composite-checkout/wpcom/components/wp-order-review-line-items.js
- client/my-sites/checkout/upsell-nudge/index.jsx
This PR is part of the effort of reverting all the changes introduced by #42783. 
For the reverting strategy applied here, please refer to the base branch: https://github.com/Automattic/wp-calypso/pull/44022
* Code review. Make sure the conflict resolution makes sense.
* Make sure you won't see the Expert Guidance offer even if you explicitly assign yourself to the variation group. There is an accompanied Playwright script below that can automate this.
* Run through a few purchasing flow and make sure they work.
1. Copy the script below into a file and put it in a folder. e.g. `sandbox/expert-guidance.js`
1. In `sandbox`, run `npm i -D playwright`
1. Run the script by `node expert-guidance.js`
On the master branch, running this script should lead you to the checkout page with the Expert …
> Revert "Create white glove AB test" - Resolving the revert conflicts

- client/landing/gutenboarding/available-designs.ts
**The news is in**: we can officially server [webp image files from production and stage environments](https://wordpress.com/calypso/page-templates/design-screenshots/rockfield_rockfield_rockfield.webp).
pMz3w-bHt-p2#comment-80676
This PR reverts the temporary fix in #44198, which reverted the original, failed attempt to dish up webp images in #44165. 
Take a look at the screenshots at the `/new/design` step in Chrome or Firefox.
How do they look?
Now check in Safari or IE11 (they don't support webp). Do the JPEGs load instead?
**Also, to the person that is merging**: how does stage look before you :shipit: ? After you've deployed, does prod look okay to you?
> Gutenboarding: show webp design screenshots

- client/my-sites/plans/current-plan/index.jsx
When a user buys the new Jetpack Anti-Spam product, they see the Anti-Spam Thank You message and when you click on the button they see for a second the Jetpack Free Welcome. The same happens with the Scan and Backup products. After a discussion, we decided to remove the Jetpack Free Welcome since it's a rare case and with the new Offer Reset project it'll change.
More info: 1181531115069428-as-1185305720915537
Before you saw:
and then, for a second:
Then with this PR, you see only the "Say goodby spam!"
- Go to a Jetpack free site
- Now go to this URL: `plans/my-plan/[your-site]?thank-you=&product=jetpack_anti_spam_monthly`
- Click on "Go back to your site". Now you don't see the Welcome message.
- Check the rest of the Thank you messages:
- `?thank-you=&product=jetpack_scan`
- …
> Don't show Welcome message for Free plan

- client/post-editor/editor-featured-image/preview-container.jsx
* EditorFeaturedImagePreviewContainer: Replace `MediaStore.get` with `getMediaItem` redux selector
* Use the classic post editor to create a new post
* Set a featured image (from the right sidebar) and make sure it loads in the preview container (above the post)
* Click on that preview container and change the image, make sure that loads as well
related to #43663
> EditorFeaturedImagePreviewContainer: replace `MediaStore.get` with `getMediaItem` redux selector

- client/components/tinymce/plugins/media/plugin.jsx
* Post Editor: replace `MediaStore.get` calls with `getMediaItem` redux selector
1. Open a post or page in the classic post editor and make sure the following cases load fine:
- **Gallery**: select a few items from the media library and place them in a gallery view
- **Edit**: place an image and then attempt to edit the image, make sure changes are applied
- **Caption**: place an image and then hit the _Caption_ button, if there's a caption stored with that item make sure it's applied 
- **Resize**: place an image and then attempt to resize it, make sure changes are applied
- **Resize controls**: place an image, click on that image and use the resize controls `- +`, make sure changes are applied
2. Now save that post and hit _Reload_, make sure all changes you made in 1) are still applied …
> TinyMCE: replace `MediaStore.get` with `getMediaItem` redux selector

- client/lib/abtest/active-tests.js
* This PR pauses the Premium to Business bump test by shifting all traffic to the control and setting a date in the future to prevent further assignment. More pbxNRc-lW-p2
* Signup for a new account using the calypso.live link below.
* Add a Premium plan to cart and complete the purchase
* Verify the following:
* That you are not shown the Business upsell and are assigned to control for `showBusinessPlanBump` test.
* This should be the same for new account, new site or upgrading an existing site.
> Pausing Premium to Business bump test

- client/my-sites/checkout/composite-checkout/wpcom/components/wp-contact-form.js
- client/my-sites/domains/components/form/state-select.jsx
This fixes the styles for the city, state, and zip code fields when they're all on the same row on non-mobile devices.
**Currently:**
This is partly due to an extra wrapper div in the return of the state field component, which prevents the flex styles from being applied properly. Additionally, the validation errors for those fields can be pretty illegible due to their widths, so this adjusts them to bring the icon inline and reduce the left/right padding:
**Before:** | **After:**
**To test:**
- visit checkout on a non-mobile device with a domain in your cart
- in the contact details, make sure that your country is set to "United States"
- verify that the field widths are equal
- try to submit invalid data
- verify that the validation errors are more legible
> Checkout: fix contact field and validation styles

- client/my-sites/checkout/checkout/domain-refund-policy.jsx
I introduced a code smell in #44272 by using the array index as the element key in a mapped return. This switches it to a keyed object literal.
Fixes #44272
props @nbloomf @sirbrillig 
**To test:**
- Add a domain or domain renewal to the cart and visit composite checkout with `?flags=composite-checkout-force`
- Verify that the correct domain refund policy is shown without any console errors
- Check legacy Checkout with `?flags=old-checkout-force`
> Domain Refund Policy: use a unique key for return

- client/lib/url/support.js
- client/my-sites/domains/domain-management/site-redirect/index.jsx
- client/my-sites/domains/domain-management/site-redirect/style.scss
To disable a site redirect users have to make it the *non* primary domain for the site.
Users trying to disable a site redirect, who might not know about this, may end up in the site redirect settings update dialog, trying to disable it. 
Users would benefit from more explicits ways to accomplish this task. As mentioned by @klimeryk in #42317, this could be addressed by the work @fditrapani and @hambai are doing around domain management. In the meantime, it would be helpful to put an explicit helper text in the site redirect settings update dialog with a link to the support docs, where there's a section that explains how to disable a site redirect.
* Added a helper text in the site redirect settings dialog with a localized link to the site redirect support docs.
* Create a site redirect …
> Domains: Add helper text in site redirect settings update dialog

- client/jetpack-connect/connection-notice-types.js
- client/jetpack-connect/jetpack-connect-notices.jsx
* Search is soft launched for WP.com sites. Here, we remove the "Good news! Jetpack Search is coming soon to WordPress.com sites." notice.
* start at `/purchase-product/jetpack_search` 
* select/type a WP.com site url
* verify redirect to Checkout without a notice being displayed
> Jetpack Search: remove WP.com purchase announcement notice when adding a WP.com site

- client/components/seo-preview-pane/index.jsx
- client/components/seo/search-preview/index.jsx
- client/components/seo/search-preview/style.scss
* Rename `SearchPreview` component references to use description instead of snippet variable
**On Master**
- Run yarn && yarn start to build all the things. Wait for Calypso to boot. Goto http://calypso.localhost:3000/.
- On a Business site, create a new Post with some content and a title and click "Preview".
- Toggle the Preview to "Search and Social" using the dropdown.
- You should see the post preview for Google Search
**On this PR branch**
- Checkout this branch.
- Run yarn && yarn start to build all the things. Wait for Calypso to boot. Goto http://calypso.localhost:3000/.
- On a Business site, create a new Post with some content and a title and click "Preview".
- Toggle the Preview to "Search and Social" using the dropdown.
- You should see the post preview for Google Search with …
> Search Preview: rename references to use description instead of snippet variable

- client/lib/products-values/index.js
- client/my-sites/checkout/checkout/index.jsx
- client/my-sites/plans/current-plan/current-plan-thank-you/anti-spam-thank-you.tsx
- client/my-sites/plans/current-plan/jetpack-checklist/index.tsx
- client/my-sites/plans/current-plan/jetpack-product-install/index.tsx
This change adds a progress bar to the Anti-Spam Welcome message. This checks the status of the installation triggered in the backend after the purchase.
While the process is running:
When the process ends, you will see:
And when you click on the button, you can check that the Anti-Spam installation is completed:
- Get a JN site and connect to your account
- Buy Anti-Spam product
- See the provisioning progress working, and at the end of the process, the button "Go back to your site" will appear
- Click on the button and see that the Anti-Spam installation is completed like you see in the screenshot.
> Show the provisioning progress bar when a user buys Anti-Spam

- client/reader/style.scss
- client/reader/tag-stream/header.jsx
- client/reader/tag-stream/main.jsx
- client/reader/tag-stream/style.scss
When attempting to load a non-existent tag in Reader, the error page that eventually appears has a grey background. This PR fixes the error state to display the standard white background.
Before:
After:
1. Visit a non-existent tag like http://calypso.localhost:3000/tag/dsgdsgdsgdsgsdsggsdg. 
2. Wait for the API requests to complete. 
3. Ensure that the displayed page has a white background.
> Reader: fix background color of tag stream when an error occurs

- client/blocks/reader-export-button/index.jsx
- client/reader/list-manage/index.jsx
For users with more than one list, it can be confusing to export lists as they all have the same filename. I found this when working on p5PDj3-4Q5-p2, in which the user has 15 lists.
This PR incorporates the slug (with some additional characters stripped out) in the export filename.
Visit one of your Reader lists, click the 'Edit' cog icon and go to the Export tab. Export the file. It should contain the current list slug.
> Reader Lists: include the list slug in the export filename

- apps/wpcom-block-editor/src/calypso/features/iframe-bridge-server.js
Fixes an issue introduced in #43313 and reported in Automattic/wp-desktop#941
#43313 removed the old code that overrode the click handler of the (W) in the blocked editor, and replaced it with a new method that used a slot API introduced in Gutenberg 8.2. I thought editors with GB versions < 8.2 would continue to work as we have other code that replaces the `href` attribute of the (W) button with a url back to Calypso. However changing the `href` isn't enough as that causes the navigation to happen within the editor iframe, not in the parent frame. 
I think ideally we would override the `href` _and_ `target` attributes of the (W) button here: https://github.com/Automattic/jetpack/blob/15294dbfe8ee61ca649fe5891b9e4d0cc8702091/modules/calypsoify/mods-gutenberg.js#L33
However that won't …
> Reinstate click override of the editor close button

- client/signup/steps/p2-site/index.jsx
@klimeryk originally reported:
> OK, this one is a "nice to have", but something we've done for Domain Search in WPCOM is to try to "recover" as much of the original string/query submitted by the user as possible - not just kill everything that is not a good, ol' ASCII character. So, zażółć would become zazolc instead of za (as it does in this flow).
> Thankfully, it's a very simple change if you have lodash available (which I assume you do if you're in Calypso... or working on JavaScript ;)). They have a super handy deburr method exactly to handle this case: https://lodash.com/docs/4.17.15#deburr
We implement that in this PR.
Navigate to `/start/p2` and input various non-ascii characters into the site address field (like čučoriedka, ďateľ, zażółć). Special characters should be stripped …
> P2 signup: use lodash deburr to strip non-ascii chars

- packages/plans-grid/src/plans-grid/style.scss
Change width to percentage for plans details comparison container to take into consideration the vertical scroll of the browser and prevent displaying an extra scrollbar at the bottom.
**Before**
**After**
* Go to[ /new](https://calypso.live/new?branch=fix/plans-grid-horizontal-scroll) on a screen below 1440px width.
* Open Plans grid.
* Scroll to bottom on the page and check the following:
* between ~850px and 1440px there shouldn't be any horizontal scrollbar at the bottom.
* between 600px and ~850px there should be only one scrollbar at the bottom.
Fixes https://github.com/Automattic/wp-calypso/pull/44087#pullrequestreview-450057630
> Plans Grid: fix double horizontal scrollbar

- test/e2e/magellan-canary.json
* This change extends the timeout for individual canaries. They were timing out when running on SauceLabs.
* Locally, run `./run.sh -C -l osx-chrome` and make sure tests pass
> e2e: Change timeout so that tests don't fail on sauce

- client/lib/wpcom-undocumented/lib/undocumented.js
- client/me/help/help-contact/index.jsx
- client/state/selectors/get-inline-help-support-variation.js
When Chat is full or unavailable, customers are sent to Tickets instead. We want to track how often this happens, so we can calculate the actual demand for live chat support.
This PR does a couple things to accomplish that:
- Adjusts `getInlineHelpSupportVariation` to add two new support types: `SUPPORT_CHAT_OVERFLOW` and `SUPPORT_UPWORK_TICKET` (which was created to make the logic clearer)
- Both of these new variations still end up creating tickets, but when it's `SUPPORT_CHAT_OVERFLOW` we pass that along to the API that creates the ticket (so it can be flagged in Zendesk)
- Also adds a new param to the Tracks event, so we can double-check overflow tickets in Tracks as well
And as an added bonus, now that we can clearly differentiate Upwork Tickets from normal Tickets, this remove the …
> Support: Identify tickets created from chat overflow

- client/my-sites/controller.js
* This pull request resolves an issue where a user with only one site on their account would see issues when navigating through certain redirects that caused an unintentional doubling of forward slashes in the redirecting URL. This occasionally broke functionality on the redirected page.
* For example, `/plans` would redirect correctly to `/plans/{siteDomain}`, but `/plans/` would redirect incorrectly to `/plans//{siteDomain}`, which would then break.
* Log into an account with only one site associated with it.
* While logged into Calypso, navigate to `wordpress.com/plans/`.
* Verify that you are navigated as expected to `wordpress.com/plans/{siteDomain}` for the site on the account.
Fixes #42628
> My Sites: prevent double slash in URL when performing redirects on single-site account

- client/blocks/reader-full-post/_content.scss
Part of #43595.
This resolves the visual differences with the tables in reader as requested in #43595
http://calypso.localhost:3000/read/blogs/165243437/posts/1717
**Before**
**After**
> Reader: ensure Gutenberg tables are visually similar to the original site

- apps/o2-blocks/package.json
`@yarnpkg/doctor` found a bunch of undeclared dependencies and missing peer dependencies:
```
➤ YN0000: ┌ /Users/sergio/src/automattic/wp-calypso2/apps/o2-blocks/package.json
➤ YN0000: │ User scripts prefixed with "pre" or "post" (like "prebuild") will not be called in sequence anymore; prefer calling prologues and epilogues explicitly
➤ YN0000: │ /Users/sergio/src/automattic/wp-calypso2/apps/o2-blocks/src/p2-autocomplete/editor.js:4:1: Undeclared dependency on @wordpress/api-fetch
➤ YN0000: │ /Users/sergio/src/automattic/wp-calypso2/apps/o2-blocks/src/p2-autocomplete/editor.js:5:1: Undeclared dependency on @wordpress/hooks
➤ YN0000: │ /Users/sergio/src/automattic/wp-calypso2/apps/o2-blocks/src/p2-autocomplete/editor.js:6:1: Undeclared dependency on lodash
➤ YN0000: │ …
```
> Adds missing dependencies to o2-blocks

- client/landing/gutenboarding/hooks/use-step-navigation.ts
- client/landing/gutenboarding/onboarding-block/domains/index.tsx
- client/landing/gutenboarding/stores/onboard/actions.ts
- client/landing/gutenboarding/stores/onboard/index.ts
- client/landing/gutenboarding/stores/onboard/reducer.ts
* Hide Domains step from the flow similar to how Plans step is hidden (prevent [early flow completion](https://cloudup.com/cuAsVwnz0yr)):
- if the step has been loaded once within the flow, always show it when navigating back/forward
- if the step hasn't been loaded yet but there is a value set through the modal, then hide it
* Show Domains step as the second step only if the site title entered is longer than 2 characters. This will make the navigation more stable preventing unwanted [position switch](https://cloudup.com/cK5FDWdR_KC) or [redirect](https://cloudup.com/cdBKS3II3n6).
**Scenario 1**
* go to [/new](https://calypso.live/new?branch=fix/gutenboarding-domains-step).
* type 1 character and press _Enter_ key to save site title and advance => Design step should appear.
* go back and …
> Gutenboarding: update domains step within site creation flow

- client/jetpack-connect/jetpack-connection.jsx
- client/my-sites/purchase-product/search.jsx
- client/state/jetpack-connect/actions/check-url.js
* remove the `calypso_jpc_error_wpdotcomsite` event when purchasing Search for WPCOM sites
* purchase Search for WP.com site  via `/purchase-product/jetpack_search`
* verify no `calypso_jpc_error_wpdotcomsite` event fired
* connect via `jetpack/connect` for a WP.com site 
* verify that the event fires as the notice around Jetpack being part of WP.com sites appears.
> Jetpack Connect: do not fire track events related to using wpcom site during the Search purchase flow.

- .github/workflows/full-site-editing-plugin.yml
- apps/full-site-editing/full-site-editing-plugin/full-site-editing-plugin.php
- apps/full-site-editing/full-site-editing-plugin/readme.txt
- apps/full-site-editing/package.json
Version bump and changelog.
This deploy includes quite a number of PRs, so I'm going to ask as many authors as possible to quickly re-test their changes against the release candidate to make sure there are no surprising interactions.
The detailed instructions are in the field-guide here: 
- (wpcom) https://wp.me/PCYsg-ly5/#viewing-the-fse-features
- (atomic) https://wp.me/PCYsg-ly5/#atomic-testing
But if you just need the short version:
* Apply code-D46328
* Test on a sandboxed simple-site with appropriate FSE-plugin flags
* Test on an atomic site with and without Gutenberg enabled
Here's the rc plugin link for your convenience [fse-build-archive](https://github.com/Automattic/wp-calypso/suites/939857407/artifacts/11616059) (2.23 MB) (updated to include fix by @akirk)
Please also add any …
> Update FSE plugin to version to 1.13

- test/e2e/lib/pages/stats/activity-page.js
Currently, a lot of e2e tests (eg: https://github.com/Automattic/wp-calypso/pull/44385) are failing on CI with
This warns of selector `.activity-log__wrapper` being missing.
If we dive into the code the presence of this selector is dependent on:
1. Activity items being present
2. Network conditions
To avoid potential timeout issues this PR updates the selector which determines whether we are on the Activirty _Page_  to use a selector which is independent of data/loading conditions. 
This is now `.is-section-activity`.
IMHO it would be better not to rely on the presence of the Activity _Log_ to determine whether we’re on the right _page_ as this is merely one component of the wider Activity page.
* Update CSS selector which determines whether we are on the Activity Page to target element …
> Fix intermitent e2e tests by using reliable CSS selector for activity page 

- apps/full-site-editing/full-site-editing-plugin/editor-gutenboarding-launch/index.ts
- apps/full-site-editing/full-site-editing-plugin/editor-site-launch/index.ts
- apps/wpcom-block-editor/src/calypso/features/iframe-bridge-server.js
Only show the launch button on gutenboarding created sites.
**Site created through `/start`**
- Create a site using `/start`.
- Once you have a hostname, point it to the sandbox.
- Go back to `https://wordp*ess.com/block-editor/page/your_unlaunched_start_site.wordpress.com`.
- You should NOT see the Launch button.
**Site created through `/new`**
- Create a site using `/new`.
- Once you have a hostname, point it to the sandbox.
- Go back to `https://wordp*ess.com/block-editor/page/your_unlaunched_gutenboarding_site.wordpress.com`.
- You should see the Launch button.
Fixes part of #43750
> Gutenboarding: Only show the new launch flow in gutenboarding created sites.

- client/my-sites/checkout/composite-checkout/wpcom/components/wp-checkout-order-summary.js
- test/e2e/lib/components/secure-payment-component.js
Tests are failing on CI for 
From the CI videos it looks like we might be assertion on the new total after the coupon has been removed too early (ie: before the cart has finished updating).
This PR tries to fix this by waiting until the loading state is no longer present before asserting on the new cost.
* Add `data-e2e` helper to determine whether cart total is still updating.
* Wait on this selector before proceeding to assertion on new total.
* Test on CI should not fail on Coupon step shown in screenshot above.
* Running test locally with `./node_modules/.bin/mocha specs/wp-plan-purchase-spec.js` should pass.
Fixes #
> Fix intermitent e2e coupon tests by using by force wait until cart has fully loaded before asserting on total update

- client/layout/sidebar/style.scss
- client/reader/sidebar/reader-sidebar-followed-sites/item.jsx
- client/reader/sidebar/reader-sidebar-organizations/list-item.jsx
- client/reader/sidebar/style.scss
* Small tweaks to the counters recently introduced in the Reader: if the site's name is very long, they could overlap. These changes keep them separated; they also make the counters a bit taller and adjust the colors so they work better with the different themes.
**Before**
**After**
* Switch to this PR and go to /read
* Does everything look fine in the sidebar? Is the layout breaking in any way?
> Reader: Update the styling of the counters

- client/my-sites/checkout/composite-checkout/composite-checkout.js
- client/my-sites/checkout/composite-checkout/wpcom/hooks/use-shopping-cart.ts
This PR has two effects:
1. If there is an error while fetching or updating the cart, save and display that error message.
2. If there are any errors from fetching or updating the cart, or if there are any errors returned in the `errors` part of the cart response, do not redirect to the plans page (which we would normally do because the cart may be "empty" if it did not load).
- Sandbox the API.
- Visit the `/plans` page in local calypso.
- Apply D46792-code on your sandbox. You must do this AFTER loading the plans page for this test to work.
- On the plans page (without reloading), click an "Upgrade" button to add a plan to your cart. This will redirect you to checkout.
- Verify that you see an error message that reads "User or Token does not have access to specified site."
- Remove …
> composite-checkout: Do not redirect to plans page if there are errors to display

- client/my-sites/checkout/checkout/style.scss
The current "Secure payment" text doesn't pass colour contrast requirements - it was probably accidentally missed when all the others were updated last year.
If you add a plan to the Checkout and go to it, you'll see it next to the Pay button!
**Before:**
**After:**
cc @sixhours
> Checkout: Improve "Secure Payment" Contrast

- packages/domain-picker/src/domain-picker/index.tsx
- packages/domain-picker/src/hooks/use-domain-suggestions.ts
* Single character search query doesn't return valid TLDs. With this change we'll display empty state for domain search when the search query has less than 2 characters.
* Go to [/new](https://calypso.live/new?branch=update/domain-picker-minimum-search-query-length).
* Reach the domain selection step or use the button from top bar.
* Enter a single character to search for a domain and empty state should be still visible.
* Enter two characters and valid domain suggestions should appear.
Fixes #43855
> Domain Picker: return empty state for single character query

- client/my-sites/checkout/composite-checkout/record-analytics.js
This adds logstash logging to cart load and save errors in addition to the existing Tracks logging for those issues.
- Sandbox the API.
- Visit the `/plans` page in local calypso.
- Apply D46792-code on your sandbox. You must do this AFTER loading the plans page for this test to work.
- On the plans page (without reloading), click an "Upgrade" button to add a plan to your cart. This will redirect you to checkout.
- Verify that you see an error message that reads "User or Token does not have access to specified site."
- Search logstash for "calypso_checkout_composite_cart_error" and verify that you see your error logged there.
> composite-checkout: Add logstash to cart load/save errors

- client/components/jetpack/upsell-switch/index.tsx
* Changes the logic in UpsellSwitch to account for sites that may have a product purchased but are not eligible to use it (e.g., sites with Jetpack Professional but which are using VaultPress).
Fixes `1164141197617539-as-1185661726673658`.
(Note: for examples, see screenshots below.)
* Check that VaultPress sites see a VaultPress notice/call-to-action when visiting the Backup or Scan page on Calypso.
* Check that multisite sites see a multisite notice when visiting the Backup page on Calypso.
* Verify that sites eligible for Backup and Scan see the correct upsell (if not purchased) or the actual Backup/Scan page (if purchased).
> Jetpack Cloud: Fix Backup/Scan upsell for sites that aren't eligible

- client/my-sites/checkout/composite-checkout/composite-checkout.js
Composite Checkout's `useShoppingCart` hook calls the `/me/shopping-cart` endpoint for the user's site using a "cart key" to identify the cart for that site. This cart key can be either the site's ID or the site's domain name. Currently we are using the site's domain name, but this may sometimes cause issues when the server tries to convert that domain name back into an ID.
In this PR, I modified the hook to use the site's ID as the cart key instead. For most sites, this should have no effect.
Add a product to your cart and visit composite checkout. Verify that you can add products and remove products as normal.
> composite-checkout: Use the siteId rather than the siteSlug for the cart key

- apps/full-site-editing/full-site-editing-plugin/wpcom-block-editor-nav-sidebar/class-wpcom-block-editor-nav-sidebar.php
- apps/full-site-editing/full-site-editing-plugin/wpcom-block-editor-nav-sidebar/src/components/nav-sidebar/index.tsx
- apps/full-site-editing/full-site-editing-plugin/wpcom-block-editor-nav-sidebar/src/constants.ts
Displaying the "Latest posts" page in the nav sidebar can be a bit misleading: pbAok1-1fU-p2#comment-2510
* Add a `postIdsToExclude` global the server can use to exclude pages/posts from the nav sidebar
* Exclude the "Latest posts" page from the nav sidebar
Notice in this change we're careful to check the state of the `show_on_front` setting before excluding the "Latest posts" page because the interpretation of the `page_for_posts` setting depends on the `show_on_front` setting (described in [the `is_home()` docs](https://developer.wordpress.org/reference/functions/is_home/#usage))
* `cd apps/full-site-editing && yarn build && npx wp-env start`
* `localhost:4013/wp-admin`
* In the customizer change the Homepage Settings to "A static page", and choose one of your pages to …
> Nav sidebar: exclude the latest posts page

- apps/wpcom-block-editor/src/calypso/features/iframe-bridge-server.js
Since #43313 the editor close button (the (W) button in the top-left) has been overridden in the calypso iframe using the official slot API added in GB 8.2. This is done in `wpcom-block-editor`. However `wpcom-block-editor` is included in many places, including places where GB is < 8.2. That's why in #44331 I re-introduced the legacy overrides, because it had introduced Automattic/wp-desktop#941. That way if GB < 8.2 the legacy override would be used, and in GB >= 8.2 the new override would be used.
The issue: if the nav sidebar is enabled then the legacy override interferes with the behaviour. That's because the legacy override uses a CSS selector that matches the overridden (W) too.
* Change the selector used by the close button override so that it:
* Doesn't match the button that opens …
> Block editor: Only add legacy handling for closing the editor when it's needed

- apps/wpcom-block-editor/src/calypso/features/iframe-bridge-server.js
- apps/wpcom-block-editor/src/utils.js
- client/gutenberg/editor/calypsoify-iframe.tsx
- client/gutenberg/editor/controller.js
* Adds an optional `parent_post` query arg to the block editor URL, so we can preselect the value in the Parent Page dropdown. If this argument is provided, the Parent Page attribute will be pre-set to its value.
* Sandbox `widgets.wp.com` and keep a sandbox connection open.
* Apply this PR's build diff D46720-code
1. Visit `http://calypso.localhost:3000/block-editor/page/<YOUR-TEST-BLOG>?parent_post=<THE-PARENT-PAGE-ID>`
2. Check **Page Attributes** on the side panel. It should be preselected to the parent page specified in the URL.
3. Check that saving the page persists the parent page attribute. Also check that the user can freely change the parent page attribute (i.e. we only preselect).
4. Check that `parent_post` is purely optional -- not setting it doesn't break the editor.
5. …
> Editor: add parent post query arg

- client/my-sites/domains/domain-management/edit/card/renew-button/index.jsx
* Adds `now` to the CTA text of the domain renew button.
* The renew button should have 'Renew now for ..' cta, to reduce confusion when auto-renew is set to true.
> Adds 'now' to the renew button to make it more specific

- apps/wpcom-block-editor/src/utils.js
* Specify `per_page: -1` in the call to `getEntityRecords()` inside `getPages()`, as the result set is used to validate the value passed in the `parent_post` param. Currently, only a subset of pages is returned, which causes the checker to incorrectly reject some of the values passed. This is a patch for [a recently committed feature](https://github.com/Automattic/wp-calypso/pull/44300).
* Sandbox `widgets.wp.com`
* Apply D46858-code (this is the diff containing this PR's build) to your sandbox.
* Navigate to `calypso.localhost:3000/block-editor/page/<your-test-site>?parent_post=<a-valid-page-id>`. Make sure your test site has more than 5 pages to effectively test this patch, e.g. LighthouseP2
* You should see under **Page Attributes > Parent Page** sidebar dropdown that the page is …
> Block editor: fix checker for parent page preselect feature

- client/components/domains/search-filters/style.scss
- client/my-sites/checkout/cart/style.scss
This change makes sure that the words for 'Filters' in domains search and 'Total:' in cart popover on the same page are not broken into multiple lines for CCJK characters (Chinese Traditional/Simplified, Japanese, Korean) and that longer texts would be broken on word boundary
Switch to Traditional/Simplified Chinese, Japanese and Korean, navigate to /domains/add and check the 'Filters' button next to the search field, then add a domain and click on the cart popover to test the 'Total' text. Test for regression issues with a Latin-based language, long amounts (using HUF / IDR currencies or by editing the html in the browser), RTL language.
***Before for Japanese/Simplified and Traditional Chinese/Korean:***
***After for Japanese/Simplified and Traditional Chinese/Korean:***
> Fix CCJK text wrapping in 'Filters' button in domains search and cart popover

- apps/full-site-editing/full-site-editing-plugin/wpcom-block-editor-nav-sidebar/src/components/nav-item/style.scss
- apps/full-site-editing/full-site-editing-plugin/wpcom-block-editor-nav-sidebar/src/components/nav-sidebar/style.scss
A tiny PR to ensure that the text in the buttons in the nav sidebar are white while clicked.
* Add `&:not( [aria-disabled='true'] ):active` selector to the `.wpcom-block-editor-nav-item` and `.wpcom-block-editor-nav-sidebar-nav-sidebar__home-button` classes. The `aria-disabled` specificity is required so that we override the `components-button:not([aria-disabled="true"]):active` selector in Gutenberg.
Screenshot while clicking an item in the nav sidebar list:
Screenshot while clicking an item in the nav sidebar list:
* `cd apps/full-site-editing && yarn build && npx wp-env start`
* `localhost:4013/wp-admin`
* Go to edit a post or a page
* Click the `W` button to open the nav sidebar
* Click and hold on any of the listed pages or the back button and the text should be …
> Nav sidebar: Add active style to sidebar nav items and home button to ensure text is white while clicked

- apps/wpcom-block-editor/src/wpcom/features/use-classic-block-guide.js
* Add a link to the block editor help pages in the classic block welcome guide
- Set a user attribute for your user using wpsh on a sandbox $ update_user_attribute( USER_ID, 'editor_deprecation_group', true )
- Check out this PR and build the wpcom block editor files with yarn build:prod in the apps/wpcom-block-editor/package.json folder.
- Sync the files created by the build in the '/dist' folder with your sandbox widgets/wpcom-block-editor folder
- Make sure site used above is sandboxed Load editor editor again and make sure the Classic block guide loads and that the 'block editor' text on first page of guide is hyperlinked to the help pages.
Part of #44328
> Editor: Add link to block editor help pages

- client/my-sites/domains/domain-management/list/index.jsx
* Conditionally renders the popover cart if there are items
* Navigate to the domains list for a site i.e. `/domains/manage/<site>`
* Open another tab/window whilst logged and add items to the cart
* Confirm that the cart disappears from the site list when all items are removed, or when it's empty
> Hide the cart in the site domains list when empty

- client/my-sites/domains/domain-management/list/list-header.jsx
* As requested by @fditrapani - we don't what to show the "Options" label in the domains list header. Here's how it looks now:
* Open the domains list view `/domains/manage` and verify that the "Options" label is missing
> Remove the options label from the domain list header

- client/my-sites/domains/domain-management/list/list-all.jsx
* We're using the wrong selector when rendering the all domains list which may hide some domains in case the site visibility is set to false.
Props to @ajaykj for reporting and helping me debug this
* Hide a site with a domain from the site selector. Then refresh /domains/manage - the domain should still be visible (without this PR it's not rendered)
> Use the proper selector to get all site items for the all domains list

- client/lib/domains/index.js
- client/lib/domains/is-domain-in-grace-period.js
- client/lib/domains/is-domain-updateable.js
- client/my-sites/domains/domain-management/edit/navigation/enhanced.jsx
- client/my-sites/domains/domain-management/list/domain-item.jsx
- client/my-sites/domains/domain-management/list/style.scss
* We're adding more shortcuts from the domain management list to domain management pages. To be more specific - we'll add shortcuts in the options menu to manage:
* Name servers
* DNS records
* Contact information
* Transfer
* Security
Here's how it looks (the menu items are different depending the the domain type and status):
* Open the all domains management list and click on the ellipsis menu on the right and try clicking on the different options
> Add more domains list options

- client/my-sites/controller.js
- client/my-sites/sidebar/index.jsx
* Turns out that if you open the all domains view and click on a domain purchased from the domain only flow it shows you the Loch Ness monster and 3 buttons instead of the domain management page. That's because of the special way we handle domain only purchases so here's a fix for that.
* Open /domains/manage and click on a domain purchased via the domain only flow. You should see the domain management page
> Fix the domain only management pages not working from the all domains view

- client/my-sites/activity/activity-log-item/style.scss
* Make preview thumbnails in the Activity Log explicitly `inline-block` so that their alt-text doesn't affect the rest of their corresponding card.
Follows up on #44116.
* **Prerequisite:** Open wp-calypso in Firefox.
* For any site with Activity Log, find or create an Activity Log entry where multiple images are attached to a post.
* Observe/verify that for such entries, a broken preview image with long alt text does not cause the rest of the layout to shift to the right. (**Tip:** To easily simulate this condition, open DevTools and inspect the preview image thumbnail. Change its `src` attribute to a non-existent URL and its `alt` attribute to a very long string.)
* To test for regression issues, verify behavior and appearance are unchanged for other browsers and for all other media …
> Activity Log: Hide alt-text overflow for broken images in Firefox

- client/my-sites/domains/domain-management/list/list-all.jsx
* Turns out we're not using the proper selector in #44362 which resulted in items not being clickable. Here's a fix for that
* Verify that the domain items and the option menu items are clickable and open the proper pages
> Use the proper selector for site items

- client/blocks/image-selector/index.jsx
- client/gutenberg/editor/calypsoify-iframe.tsx
Precendence for this approach:
https://github.com/Automattic/wp-calypso/blob/da4fd95d445bb77810888caafb721842006b0e6d/client/components/tinymce/plugins/simple-payments/dialog/product-image-picker.jsx#L64
We can do this because indeed the reducer for this action only
cares about the ID on the objects passed in.
* Remove `MediaStore.get` from `ImageSelector` block
* Open the `ImageSelector` block in devdocs/blocks and ensure that selecting items in the media modal and when uploading still works
Related to https://github.com/Automattic/wp-calypso/issues/43663
> Media: Remove unnecessary MediaStore.get from ImageSelector and Calypsoify

- client/components/data/media-list-data/README.md
- client/components/data/media-list-data/index.jsx
- client/lib/media/list-store.js
- client/lib/media/test/list-store.js
- client/my-sites/media-library/external-media-header.jsx
- client/my-sites/media-library/list.jsx
- client/state/selectors/is-fetching-next-page.js
* Replace `MediaListStore.isFetchingNextPage` with calls to redux selector for `isFetchingNextPage`
* Remove `MediaListStore.isFetchingNextPage` and related state
* Memoize `isFetchingNextPage`
* Using all three sources (uploaded, pexels, and google photos) ensure that when loading the next page of items, that placeholders are rendered in the same way as production
* Using the google photos source, ensure that the refresh button is disabled when:
* You have just pressed the refresh button
* A new page of media items is loading (you'll need a photos account with at least 50 or more photos for this to work)
Part of https://github.com/Automattic/wp-calypso/issues/43663
> Media: Use redux selector for next page fetching

- client/blocks/inline-help/contextual-help.js
- client/blocks/product-purchase-features-list/sell-online-paypal.jsx
- client/components/tinymce/plugins/insert-menu/menu-items.jsx
- client/components/tinymce/plugins/simple-payments/dialog/index.jsx
- client/components/tinymce/plugins/wpcom-view/views/simple-payments/index.jsx
- client/layout/guided-tours/docs/examples/tours/simple-payments-end-of-year-guide.js
- client/layout/guided-tours/tours/simple-payments-email-tour/index.js
- client/layout/guided-tours/tours/simple-payments-tour/index.js
- client/lib/discounts/active-discounts.js
- client/lib/plans/features-list.js
- client/me/memberships/main.jsx
- client/my-sites/earn/home.tsx
- client/my-sites/earn/main.jsx
- client/my-sites/earn/memberships/add-edit-plan-modal.jsx
- client/my-sites/earn/memberships/index.jsx
- client/my-sites/earn/memberships/products.jsx
- client/my-sites/feature-upsell/ads-upsell.jsx
- client/my-sites/feature-upsell/features.jsx
- client/my-sites/feature-upsell/plugins-upsell.jsx
- client/my-sites/feature-upsell/themes-upsell.jsx
- client/state/data-layer/wpcom/sites/simple-payments/index.js
- config/desktop.json
- config/development.json
- config/horizon.json
- config/production.json
- config/stage.json
- config/test.json
- config/wpcalypso.json
Follow up to https://github.com/Automattic/wp-calypso/pull/42848 this removes a feature flag that gated a block rename of (Simple Payments -> Pay with PayPal) and (Recurring Payments -> Payments) to align with a Jetpack release. We no longer need this.
Some visuals (not exhaustive)
| copy examples |  |  |  |  |
| --- | --- | --- | --- | --- |
| <img width="1122" alt="Screen Shot 2020-07-23 at 4 30 13 PM" src="https://user-images.githubusercontent.com/1270189/88348521-83051b00-cd02-11ea-90ac-a774d3965bd0.png"> | <img width="1103" alt="Screen Shot 2020-07-23 at 4 30 59 PM" src="https://user-images.githubusercontent.com/1270189/88348576-aa5be800-cd02-11ea-9d35-1c0766c65658.png"> | <img width="1115" alt="Screen Shot 2020-07-23 at 4 31 14 PM" …
> Earn: remove earn/rename-payment-blocks feature flag

- packages/social-previews/CHANGELOG.md
- packages/social-previews/package.json
This PR adds `css` and `scss` files as `sideEffects` in the `package.json` for the `@automattic/social-previews` package.
Without this webpack tree shaking will remove the CSS from the build and leave the package without styles.
See p1595490568480700-slack-ajax for some context on why this is important. Basically when we attempted to use this in Calypso build the CSS was stripped out in production build leaving us with unstyled components.
* Adds 
```js
"sideEffects": [
"*.css",
"*.scss"
],
```
to `package.json`
* Bumps package version to `1.0.1` in `package.json` and `CHANGELOG.md`.
* Open https://calypso.live/?branch=try/fix-social-previews-package-to-include-css-sideeffects.
* On a Business site, create a new Post with some content and a title and click "Preview".
* Toggle the Preview …
> Mark CSS and SCSS as a `sideEffect`s in `@automattic/social-previews`

- client/my-sites/checkout/checkout/domain-registration-agreement.jsx
This fixes a potential bug introduced in https://github.com/Automattic/wp-calypso/pull/31810 where an array index was used as a React key ([a classic but often poorly understood anti-pattern](https://stackoverflow.com/questions/59517962/react-using-index-as-key-for-items-in-the-list)). I believe that this is causing fatal rendering errors when removing a product from the cart causes the list of agreements to change in such a way that the elements are identified by the wrong key. Since the keys are not tied to the agreements, React attempts to modify the DOM with incorrect data and throws the error `Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.`.
In this PR I use the agreement url as the key instead, combined with the number of domains for …
> Checkout: Remove index-as-key in DomainRegistrationAgreement

- client/my-sites/checkout/composite-checkout/wpcom/components/wp-checkout-order-summary.js
This fixes a potential bug introduced in https://github.com/Automattic/wp-calypso/pull/42854 where an array index was used as a React key ([a classic but often poorly understood anti-pattern](https://stackoverflow.com/questions/59517962/react-using-index-as-key-for-items-in-the-list)). I believe that this is causing fatal rendering errors when removing a product from the cart causes the list of features to change in such a way that the elements are identified by the wrong key. Since the keys are not tied to the features, React attempts to modify the DOM with incorrect data and throws the error `Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.`.
In this PR I use the feature string as the key instead. I hope that these will be unique enough to …
> Checkout: Use feature string as key for CheckoutSummaryFeaturesListItem

- client/my-sites/earn/home.tsx
* Earn currently crashes for non-admins, who shouldn't be able to access this section anyway
Check Earn as a non-admin and verify that instead of crashing, an error message is displayed!
cc @mmtr, @blackjackkent, @artpi
> Earn: Prevent Crash by Disabling for Non-Admins

- client/lib/domains/constants.js
- client/lib/domains/registration/availability-messages.js
* Update the error message shown when attempting purchase a mapping for a subdomain that has a pre-existing conflicting CNAME record.
* Apply D46527-code
* Create a CNAME record for a domain that you own (ex. foo.example.com)
* Attempt to purchase a mapping for the subdomain
* Make sure that the correct error message is shown:
> Add new availability message

- client/my-sites/checkout/composite-checkout/wpcom/components/wp-order-review-line-items.js
- client/my-sites/checkout/composite-checkout/wpcom/types/backend/shopping-cart-endpoint.ts
- test/e2e/lib/components/secure-payment-component.js
- test/e2e/specs/wp-plan-purchase-spec.js
Every product in the `items` prop of `@automattic/composite-checkout`'s `CheckoutProvider` needs to have a unique `id`. Since the products returned from the shopping cart endpoint do not have unique IDs, we create them (as `uuid`) when the cart is fetched in `convertRawResponseCartToResponseCart()`.
Previously, we were using the item's array index as the `uuid`, but this is risky, since that id is used throughout the codebase for a React key. Indirectly, this creates [a classic but often poorly understood anti-pattern](https://stackoverflow.com/questions/59517962/react-using-index-as-key-for-items-in-the-list). I believe that this might be causing fatal rendering errors when removing a product from the cart causes the list of products to change in such a way that the elements are …
> Checkout: Make sure product uuid is never the same

- test/e2e/lib/gutenberg/blocks/contact-form-block-component.js
- test/e2e/lib/gutenberg/gutenberg-editor-component.js
* See https://github.com/Automattic/wp-calypso/pull/44416
*
Fixes #
> e2e: Update Gutenberg classes for 8.5 compat

- client/state/selectors/get-editor-close-config.js
When the (W) button in the block editor is going to take the user back to the customer home page, the button's tooltip says "Home". This could be easily confused with taking the user to their site's homepage.
Everywhere else in Calypso the customer home page is called "My Home". The tooltip should be consistent with that.
**Before**
**After**
p58i-9f7-p2#comment-47138
* Open the block editor from the My Home page in Calypso, the (W) tooltip should say "My Home"
* Open the block editor from the pages or posts page in Calypso, the tooltip should say "View Pages/Posts", or whatever it used to say
* Open the block editor on a site with the nav sidebar enabled (e.g. bAok1-p2) and check that the back button in the sidebar has the correct label
> Change editor close button label from "Home" to "My Home"

- client/my-sites/themes/controller.jsx
Block direct access to themes route for P2 sites.
- Select a regular site -> Accessing Themes should work
- Select a P2 site -> go to Home, change `/home/` to `/themes/` in the URL -> should be redirected back to Home.
> Block themes section for p2

- client/components/tinymce/plugins/wplink/dialog.jsx
- client/state/media/thunks/get-media-item.js
- client/state/media/thunks/index.js
* wp-link/dialog: use thunk to select media item from redux store (due to its programmatic usage, otherwise we'd use the `connect()` method)
* Open a post in the classic post editor which contains an image or create a new post and hit _Save_
* Reload your browser tab
* Now select the image and hit the link button
* Make sure the image URL is shown in the URL field
related to #43663
> wp-link/dialog: get media item from redux store

- packages/components/src/product-icon/config.js
* add the icons in the /manage-purchase section
* purchase a monthly version of the product for a WPCOM site
* verify that the icon is present in the /me/purchases section, as well as the subsequent manage purchase one
Fixes https://github.com/Automattic/wp-calypso/issues/44407
> Jetpack Search: Add product icon for the monthly version of the product.

- client/components/README.md
The existing description refers and links to an older structure/file that no longer exists (`assets/stylesheets/_components.scss`). This PR updates the text to reflect that each component has its own `styles.scss` inside the component's folder, and adds a link to the styles file of the Accordion component as an example.
> Docs: update loading of style files for components

- client/lib/signup/step-actions/index.js
The `url` module was recently added as a restricted import in #44041 with the recommendation to replace it with `lib/url`. This causes a lint error when files are touched that use the 'url' module. I ran into this lint error in the PR https://github.com/Automattic/wp-calypso/pull/44206, where `client/lib/signup/step-actions/index.js` uses this module. 
This PR replaces `parse` from url with `getUrlParts` from `lib/url`. I'm separating this change out to its own PR given that this affects the signup flow.
* Begin at /start logged out, go through the signup flow and verify that you are able to create a site. Try both free and paid plan sites.
* This also touches the WPForTeams workflow. I think the way to test it is to begin at /start/wp-for-teams logged out, go through the signup flow, and …
> Replace url module with lib/url to fix lint errors.

- client/components/domains/transfer-domain-step/index.jsx
* This PR adds a check for invalid content any time the transfer form is submitted, instead of preventing actions via the button we display. That prevents keyboard-driven submissions from triggering searches we can already tell are invalid.
* Navigate to `/domains/add/transfer/<your-site>`.
* Open the network tab in your tools.
* Type a string that is not a valid FQDN into the box and hit Enter/Return. (You can use a single word like "test" or "something".)
* Verify that we don't make any requests to the server for `inbound-transfer-status` or `is-available`.
* Add a valid TLD to the end of your query, e.g. `something.it`, `test.xyz`
* Verify that the "Transfer" button is enabled and hitting Enter and/or clicking the "Transfer" button triggers the two requests above.
> Add checks for invalid keyboard submissions in transfer domain UI

- client/my-sites/checkout/checkout/duplicate-product-notice-content.tsx
This PR adds some context to the copy of `DuplicateProductNoticeContent` for translation purpose.
The update is really straightforward. If you want to check that the notice still appears correctly, refer to the instructions in #44181.
> i18n: add context to copy in duplicate product notice

- client/layout/sidebar/style.scss
- client/reader/sidebar/style.scss
* See #43396 
* Trying another design for the Reader sidebar; the space between menu groups looked off compared to other areas of the Calypso sidebar. This removes the extra space and indents submenu items for an alternative approach to the hierarchy.
**Before**
**After**
* Switch to this PR and navigate to `/read`
* Note the changes in the sidebar layout; does anything break? Is the hierarchy clearer?
> Reader: Increase indentation on sidebar submenu items

- client/my-sites/checkout/composite-checkout/wpcom/components/wp-contact-form.js
This PR changes the behavior of the new checkout form's contact details so that it will not display if the cart contains only renewal items. This behavior should match [old checkout](https://github.com/Automattic/wp-calypso/blob/096d4759a964ebb19bcf0a068e51d438e9fab080/client/my-sites/checkout/checkout/index.jsx#L917) (with the small exception that it no longer checks `hasDomainDetails( transaction )` since we don't have a transaction but I don't think that's going to be an issue). Previously, we had been displaying the contact details form fields any time that there were domain products in the cart.
Before:
After:
- Add a domain product to your cart (we may want to test this with different domain products for completeness) and visit checkout.
- Verify that you see the full "Contact …
> Checkout: Do not display contact details form if the cart is only renewals

- client/lib/products-values/constants.js
- client/lib/products-values/products-list.ts
- client/me/purchases/manage-purchase/purchase-meta.jsx
Currently all Search WPCOM plans are marked yearly because plan's term has not been included in the `plans-list.js`.
Here I propose a variation, but we might prefer modifying the latter  /cc @DavidRothstein for thoughts.
* adapt period to product plan type for Search
* purchase a monthly Jetpack product for a WPCOM site at `purchase-product/jetpack_search_monthly`
* go `/me/purchases` and open your site's card
* verify that the price subscription corresponds to the correct period (e.g. 5.5usd/month) 
Fixes https://github.com/Automattic/wp-calypso/issues/44402
> Jetpack Search: include monthly period in the Search product details.

- apps/full-site-editing/README.md
- apps/full-site-editing/dev-plugin/dev.php
- apps/full-site-editing/full-site-editing-plugin/full-site-editing-plugin.php
- apps/full-site-editing/full-site-editing-plugin/readme.txt
- apps/full-site-editing/package.json
1. Change the display name of the plugin.
2. Update documentation and comments to use new name.
This does not change code or directories yet. (Separate PRs)
1. Install in a WordPress instance.
2. Verify that the plugin display name is "WordPress.com Editing Toolkit"
> Rename FSE plugin to WordPress.com Editing Toolkit plugin

- client/lib/analytics/track-affiliate-referral.js
This fix replaces the incorrect `withCredentials: true` option being passed to `fetch()` with the correct `credentials: 'include'` option, which fixes a bug where the `wp-affiliate-tracker` cookie was not being properly set.
With the incorrect option, the `wp-affiliate-tracker` cookie was being received in the headers but not being sent to the browser. This is because [`fetch()` won't send cookies unless the `credentials` init option is set.](https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/fetch#Parameters) 
To observe the bug:
- Visit https://wordpress.com/start/user?ref=alp-lp&tk_amp=1*s4a2cn*amp_client_id*YW1wLWQzY3J6b2JOMmpXazhSZ3NkRnhJelE.*aff*MzAxMDI.*sid*RU4tMTU0NTkwMzg.&_gl=1*1ptehrf*_ga*YW1wLVRvYXBDT2R0WHZKVnV3WG0tQTlEc2c
- In the Chrome Inspector, …
> Analytics: Fix bug preventing wp-affiliate-tracker cookie from being set

- apps/full-site-editing/full-site-editing-plugin/wpcom-block-editor-nav-sidebar/src/components/nav-sidebar/style.scss
Ensures that the text in the "Visit site" link in the nav sidebar is always readable.
* Make the "Visit site" link white when in the `:active`, `:focus` and `:hover` states.
* `cd apps/full-site-editing && yarn build && npx wp-env start`
* `localhost:4013/wp-admin`
* Go to edit a post or a page
* Click the `W` button to open the nav sidebar
* Hover over the link
* Tab to the link
* Click and hold on any of the link
* It should be readable
Fixes #44446
> Nav sidebar: Increase contrast for "Visit site" links active/hover/focus states

- client/my-sites/domains/domain-management/controller.jsx
- client/my-sites/domains/domain-management/list/domain-item.jsx
- client/my-sites/domains/domain-management/list/index.jsx
- client/my-sites/domains/domain-management/list/list-all.jsx
* Adds tracking mostly for events initially omitted:
- Add domain
- Add email
- Change primary domain
- Make Domain Primary option
* Adds page view analytics to `ListAll` to make it consistent with `List`
* Navigate to `/domains/manage` to bring up the all domains list.
* The `Redux` state profiler is the best way to see when event actions dispatched. 
* One can also enable analytics logging by doing: ```localStorage.setItem('debug', 'calypso:analytics:*');```
* Confirm that there is a corresponding event triggered by each of the actions listed above.
> Add tracking for new domain list features and events

- client/post-editor/editor-gutenberg-dialogs/index.tsx
- client/post-editor/post-editor.jsx
Allows users to try the Block editor by using the button in the sidebar. The editor deprecation dialog message was preventing this dialog from showing.
Make sure the conditions under which the editor deprecation dialog shows is reflected in the Gutenberg Opt In dialog, so that the Opt In dialog can show when the button is clicked.
- Clear local storage
- Set a site to use the classic editor: http://calypso.localhost:3000/post/[site]?set-editor=classic
- You should see the deprecation notice:
- Now visit http://calypso.localhost:3000/post/[site]?flags=desktop
- You should not see the deprecation notice
- Click on "Try the block editor" in the sidebar.
- You should see the opt in notice:
Fixes #
> Desktop: Fix the "try the block editor" dialog

- client/my-sites/customer-home/cards/tasks/site-setup-list/current-task-item.jsx
- client/my-sites/customer-home/cards/tasks/site-setup-list/index.jsx
- client/my-sites/customer-home/cards/tasks/site-setup-list/nav-item.jsx
- client/my-sites/customer-home/cards/tasks/site-setup-list/style.scss
* Checklist for a new site is on the right side which gives user more focus on the main cards and tasks vs list of items in the checklist.
- It can be tested by creating a new site and going to homepage of site where checklist can be seen.
Before:
After:
*
Fixes #44112
> Customer Home: Move checklist items from left to right

- config/horizon.json
- config/production.json
- config/stage.json
* Enable the feature flag for all domains view ( aka `/domains/manage` ) on production.
This feature flag introduces a central place to manage all domains across different sites that you manage. That includes a redesign of the site specific domain list and how the primary domain is displayed and changed in there.
The view was created in the following PRs: #42741, #42930, #42954, #43181, #43347, #43356, #43375, #43456, #43696, #43717, #43772, #43794, #43801, #43833, #43864, #43913, #43952, #43999, #44072, #44135, #44171, #44176, #44362, #44378, #44384, #44399
* Verify that `/domains/manage` is visible on staging/production.
> Enable all domains list on production

- client/my-sites/domains/domain-management/components/domain/new-domains-redirection-notice-upsell.scss
This change makes sure that the word for 'Upgrade' in plan upsell on domain search/purchase page is not split into multiple lines for CCJK languages (Chinese Traditional/Simplified, Japanese, Korean) and that translations with multiple words would be broken on word boundary
1. Switch to a site with a Free plan, go to /domains/add and make sure that the 'Domains purchased on a free site will get redirected to...' upsell is visible above the domain search box.
2. Switch to Chinese Simplified/Traditional, Japanese, Korean languages and test that the button text is not broken into multiple lines.
3. Test for regression issues with a Latin-based language (such as Italian) and some RTL language.
___Before for Chinese Simplified and Traditional / Japanese / Korean / Italian:___
___After for …
> Fix CCJK text wrapping in 'Upgrade' button on plan upsell card

- client/signup/main.jsx
- client/signup/reskinned-processing-screen/index.jsx
- client/signup/reskinned-processing-screen/style.scss
- client/signup/signup-header/index.jsx
* Adds redesigned signup processing screen to the reskinning signup flow project. More details can be found in #44223.
* Go to `/start/new`
* Make sure you're assigned to the `reskinned` group of `reskinSignupFlow` a/b test.
* Follow the signup flow.
* You should be able to see the redesigned signup processing screen as follows at the end of the signup flow. Note that the second step can be omitted when you pick a free domain.
> Add Reskinned Signup Processing Screen

- client/components/seo/facebook-preview/index.jsx
- client/components/seo/search-preview/index.jsx
- client/components/seo/twitter-preview/index.jsx
- packages/social-previews/src/facebook-preview/index.jsx
- packages/social-previews/src/search-preview/index.jsx
- packages/social-previews/src/twitter-preview/index.jsx
- packages/social-previews/test/index.js
* strip html tags from descriptions for social previews
**Manual for legacy components** 
- Run yarn && yarn start to build all the things. Wait for Calypso to boot. Goto http://calypso.localhost:3000/.
- On a Business site, create a new Post with some content and a title and click "Preview".
- Toggle the Preview to "Search and Social" using the dropdown.
- You should see the post previews and be able to toggle between each type with no errors.
- Edit your page to only include an html block with the following
```
<p>paragraph Test</p>
<p class="test">Class Test</p>
<p style="color:red;">Style Test</p><p>
</p><div>Div Test</div>
```
- Facebook, Google, Twitter previews should display their description without any html tags
**Automatic for social-previews npm package**
`>yarn run jest …
> Social Previews: strip html tags

- docs/monorepo.md
Update the monorepo documentation:
- elaborate on `sideEffects`
- add `dependencies` guidelines
- add `copy-assets` to prepare script (if needed)
- change `npm link` to `yarn link`
Fixes #44277
> Monorepo: updates package creation docs

- apps/full-site-editing/full-site-editing-plugin/common/data-stores/launch/actions.ts
- apps/full-site-editing/full-site-editing-plugin/common/data-stores/launch/reducer.ts
- apps/full-site-editing/full-site-editing-plugin/editor-domain-picker/src/domain-picker-fse/index.tsx
- apps/full-site-editing/full-site-editing-plugin/editor-site-launch/src/launch-steps/domain-step/styles.scss
- packages/domain-picker/src/domain-picker/index.tsx
- packages/domain-picker/src/domain-picker/style.scss
- packages/domain-picker/src/domain-picker/suggestion-item.tsx
When domain picker is used under FSE, the user already has an existing free subdomain. The domain picker should show the user's existing free subdomain.
* A new action `UNSET_DOMAIN` is added to launch store.
* DomainSuggestionItem component accepts `domain`, `cost` and `isFree` param instead of the whole `suggestion` object. This makes `<SuggestionItem>` component reusable to display existing free subdomain which doesn't have a `suggestion` object.
When the existing free subdomain is picked, the `UNSET_DOMAIN` action is called. The `domain` prop in the launch store is set to `undefined`.
**Note:**
1. Ignore the flow weirdness (radio button with missing continue button) …
> DomainPicker: Support for non-changeable existing subdomain.

- client/gutenberg/editor/calypsoify-iframe.tsx
* calypsoify-iframe: replace `MediaStore.get` with `getMediaItem` thunk
1. Open a post in Gutenberg which contains an image on a simple site
2. Hit reload
3. Open the browser devtools and change to the _Network_ tab, filter for `/media` XHRs
4. Click on that image and hit _Replace_ > _Open Media Library_
5. Make sure there's a request fetching that image `/media/<mediaId>`
6. Close the modal by clicking on _Cancel_ and do 4. again but make sure there's no such request like in 5.
related to #43663
> calypsoify-iframe: replace `MediaStore.get` with `getMediaItem` thunk

- config/horizon.json
- config/production.json
* Adds Jetpack Anti-Spam produce to production and horizon config files.
* Run a local copy of Calypso prod.
* Verify Jetpack Anti-Spam is visible and able to be purchased.
Fixes 1181531115069428-as-1185356281661171.
> Launch Jetpack Anti-Spam

- client/devdocs/design/typography.jsx
* Found this while I was working on linting for font sizes. I didn't update the rem units for 20px and 12px correctly in /devdocs; they still corresponded to the old type scale. 
**Before**
**After**
* Switch to this PR and navigate to `/devdocs/design/typography`
* Scroll to the bottom of the page
* Double-check my math 😅
> Typography: Fix incorrect REM values in typography standards in devdocs

- apps/full-site-editing/full-site-editing-plugin/common/data-stores/launch/actions.ts
- apps/full-site-editing/full-site-editing-plugin/common/data-stores/launch/data.ts
- apps/full-site-editing/full-site-editing-plugin/common/data-stores/launch/reducer.ts
- apps/full-site-editing/full-site-editing-plugin/common/data-stores/launch/types.ts
- apps/full-site-editing/full-site-editing-plugin/editor-site-launch/src/launch-menu/index.tsx
- apps/full-site-editing/full-site-editing-plugin/editor-site-launch/src/launch-menu/item.tsx
- apps/full-site-editing/full-site-editing-plugin/editor-site-launch/src/launch-menu/styles.scss
- apps/full-site-editing/full-site-editing-plugin/editor-site-launch/src/launch-modal/index.tsx
- apps/full-site-editing/full-site-editing-plugin/editor-site-launch/src/launch-modal/styles.scss
- apps/full-site-editing/full-site-editing-plugin/editor-site-launch/src/launch-sidebar/index.tsx
- apps/full-site-editing/full-site-editing-plugin/editor-site-launch/src/launch-sidebar/styles.scss
- apps/full-site-editing/full-site-editing-plugin/editor-site-launch/src/launch-step/styles.scss
- apps/full-site-editing/full-site-editing-plugin/editor-site-launch/src/launch-steps/domain-step/index.tsx
- apps/full-site-editing/full-site-editing-plugin/editor-site-launch/src/launch-steps/final-step/index.tsx
- apps/full-site-editing/full-site-editing-plugin/editor-site-launch/src/launch-steps/final-step/styles.scss
- apps/full-site-editing/full-site-editing-plugin/editor-site-launch/src/launch-steps/name-step/index.tsx
- apps/full-site-editing/full-site-editing-plugin/editor-site-launch/src/launch-steps/plan-step/index.tsx
- apps/full-site-editing/full-site-editing-plugin/editor-site-launch/src/launch/index.tsx
* Added launch sidebar.
**Note:**
* The "Name Step" is used as a demo to show how to mark a step as completed and move to the next step.
* The "Final Step" is used as a demo to show how to reveal the site content behind (This is not so usable. It should render a page preview in an iframe instead like that preview modal). 
* Run `yarn dev --sync` on `apps/full-site-editing`.
* Create an unlaunched site and point that hostname of the unlaunched site to your sandbox.
* Click "Launch site" button.
* Clicking on any step on the sidebar should jump to that particular step.
Fixes part of #43750
> Gutenboarding: Add launch sidebar

- client/components/card-heading/style.scss
- client/devdocs/style.scss
- client/my-sites/plan-features/style.scss
* Update once instance of 52px and two instances of 54px to use `$font-headline-large`
**Before**
**After**
* Check the plans part of onboarding from `/start` on a mobile device; the plan price will have gotten a teensy big larger as a result of this change
* Otherwise there should be no visual changes or breakage
> Typography: Update instances of 52px and 54px to use Sass variable

- client/components/card-heading/style.scss
- client/my-sites/migrate/section-migrate.scss
- client/signup/p2-processing-screen/style.scss
* Update font sizes 47px and 48px to `$font-headline-medium`
* Only one value gets changed here; the `CardHeading` component was using 47px instead of 48px. The others are just conversions from `48px` to the equivalent variable.
**Before**
**After**
* Check on extra large font sizes 48px across Calypso
> Typography: Update font sizes 47-48px to use Sass var

- client/my-sites/site-settings/main.jsx
- client/my-sites/stats/site.jsx
* Move the "Add your server credentials" banner below site navigation on the **Settings** and **Stats** pages, as it is on the **Activity** page.
* Select a Jetpack site with no stored server credentials, or invalid stored server credentials.
* On the **Activity**, **Stats**, and **Settings** pages, for mobile layouts, verify that the "Add your server credentials" banner appears directly *below* the site selection/navigation bar, instead of above it.
> My Sites: Put 'Add your credentials' banner below site nav on mobile

- client/components/jetpack/sidebar/menu-items/index.jsx
This PR disables backup in the wp-desktop app as a number of backup features do not work (see Automattic/wp-desktop#943). Until we can revisit how this feature is implemented in the desktop app in its entirety, let's disable it for now.
Requires a site with a purchased plan in order for the backup feature to be available.
1. Select Plan in the sidebar.
1. Select the Plans tab to view available plans.
1. Purchase a plan to get Jetpack backups.
- Desktop: verify that the backup menu item is hidden (for a site with a purchased plan)
</p>
- Web: verify the backup menu items continues to be shown as expected
</p>
> desktop: disable backup

- client/components/data/query-rewind-backups/README.md
- client/components/data/query-rewind-backups/index.js
- client/my-sites/activity/activity-log/index.jsx
* Change logic so that the "first backup underway" banner only shows during the first attempted backup of a site.
* Move the logic for the "first backup underway" banner into its own function. (We could later modify this code to show live backup status banners, if we want to.)
* Add a query component, `QueryRewindBackups`, to fetch data about the most recent backups for a site.
Fixes `1164141197617539-as-1181871794129033`.
* I wonder if it might be more accurate here to show "first backup underway" for *every* backup attempt until a successful backup is complete, but this approach looks like it would take significantly more work and put a lot more demand on the client, network traffic-wise. If this is something we're interested in, I encourage someone to create a new issue as an …
> Activity Log: Only show "Backup underway" banner during a site's first backup

- client/my-sites/checkout/composite-checkout/wpcom/components/wp-checkout.js
On non-mobile devices, the Checkout summary is displayed in the sidebar with features, total, and savings. This PR keeps the summary on the page as the user scrolls.
**To test:**
- add an item to your cart and visit the new Checkout flow (with `?flags=composite-checkout-force`)
- verify that when the sidebar is shown (landscape tablet and desktop devices), the summary scrolls with the page
- verify that when the sidebar is collapse (mobile devices), the summary behaves as normal
> Checkout: use fixed positioning for sidebar summary

- client/components/inline-support-link/index.jsx
- client/my-sites/site-settings/custom-content-types/index.jsx
* This PR updates WPCOM support links on `/settings/writing/{siteUrl}` to open in a dialog modal rather than navigating completely to the support site.
* In the Calypso sidebar for a site you own, click `Manage` -> `Settings`.
* Click the "Writing" tab.
* Click the "testimonials" and "portfolio projects" links under "Content Types" and verify that both of them open up a support site modal dialog.
Fixes #43789
> Site Settings - fix support links to open in modal dialog

- apps/full-site-editing/full-site-editing-plugin/wpcom-block-editor-nav-sidebar/src/components/nav-sidebar/index.tsx
- apps/full-site-editing/full-site-editing-plugin/wpcom-block-editor-nav-sidebar/src/components/nav-sidebar/style.scss
* Wrap site title using `word-wrap: break-word`. This will wrap very long words, but will also ensure that it will still prefer to wrap on spaces where possible.
* Decode html entities in the site title before rendering 
**Before**
**After**
* Apply the D47155-code to your sandbox
* Sandbox your favourite test site
* Give your test site a snazzy name that either has very long words or some totally reasonable symbols e.g. `&` or `'`
* You should also test it with a site title with shorter words, and the wrapping should still behave as you'd expect (wrapping on spaces)
* See how your title looks in the nav sidebar
> Nav sidebar: correctly format site titles correctly when they are long or have punctuation

- client/my-sites/site-settings/form-general.jsx
Hide `Coming Soon` site setting for P2 sites.
- Open Settings -> General for a regular site, there should be the option of Coming Soon under `Privacy`
- Open Settings -> General for a P2 site, there should be no option of Coming Soon under `Privacy`
> Remove coming soon

- client/lib/signup/step-actions/index.js
- client/signup/steps/p2-site/index.jsx
We need to switch back to using the `.wordpress.com` subdomain for P2 sites until we solve the 3rd party cookies issue.
Navigate to `/start/p2` and create a new P2 site. It should be in the `<site>.wordpress.com` format now.
> P2 signup: use .wordpress.com subdomain for p2 creation

- packages/social-previews/src/facebook-preview/index.jsx
- packages/social-previews/src/helpers.js
- packages/social-previews/src/search-preview/index.jsx
- packages/social-previews/src/twitter-preview/index.jsx
For the social previews npm package only:
* move strip code to a helper function
* use enhanced regex as proposed in issue
* run 
`>yarn run jest -c=test/packages/jest.config.js packages/social-previews/test/index.js`
Fixes #44521
> Social Previews: moved code to a helper function

- client/components/data/query-experiments/index.tsx
- client/components/experiment/index.tsx
- client/state/data-layer/wpcom/experiments/index.js
- client/state/experiments/reducer.ts
* Ensures that we call the API after we have an anonid.
* Visit http://calypso.localhost:3000/start/onboarding with no cookies
* Check the network pane and ensure the call to the API includes an anonID.
> Fix experiment component to always have an anonId if there is one.

- client/my-sites/plan-features/index.jsx
- client/my-sites/plans-features-main/index.jsx
- client/my-sites/plans-features-main/style.scss
- client/signup/style.scss
* Updates the plans step design to according to the new reskin
* More details in https://github.com/Automattic/wp-calypso/pull/44223
Changes:
Current Screenshot:
* Make sure you're assigned to `reskinned` group of `reskinSignupFlow` a/b test.
* Proceed to the plans step, the screen should look like this:
cc: @taggon
> Adds reskinned design for the plans step

- client/components/domains/domain-registration-suggestion/index.jsx
- client/components/domains/domain-search-results/index.jsx
- client/components/domains/domain-suggestion/style.scss
- client/components/domains/example-domain-suggestions/style.scss
- client/components/domains/free-domain-explainer/index.jsx
- client/components/domains/free-domain-explainer/style.scss
- client/components/domains/search-filters/style.scss
- client/components/domains/search-filters/tld-filter-bar.jsx
- client/signup/steps/domains/style.scss
- client/signup/style.scss
* Adds redesigned domains step screen to the reskinning signup flow project. More details can be found in #44223
* Go to /start/new
* Make sure you're assigned to the reskinned group of reskinSignupFlow a/b test.
* Follow the signup flow till you are on the domains step.
* The screens should look like these:
Domain (unfocused)
Domain (focused)
Filters
Domain (extensions)
Domain (options)
Domain (search)
Domain (selection hover)
> Adds reskinning signup flow for domains step

- client/blocks/signup-form/index.jsx
- client/blocks/signup-form/style.scss
- client/signup/steps/user/index.jsx
- client/signup/steps/user/style.scss
- client/signup/steps/user/test/index.js
* Adds reskinned user step to the reskinning signup flow project. More details can be found in #44223.
* Go to `/start/new` as a logged out user.
* Make sure you're assigned to the `reskinned` group of `reskinSignupFlow` a/b test.
* The user step should look like as follows and you should be able to complete the step:
_Desktop_ 
_Desktop with locale selector_ 
_Desktop with invalid fields_. 
_Mobile_
> Signup: Add reskinned user step

- apps/full-site-editing/full-site-editing-plugin/wpcom-block-editor-nav-sidebar/src/attach-sidebar.tsx
* hides the sidebar in the experimental site editor
Ideally we wouldn't enqueue the nav sidebar JS if it's not going to be used, but this is a quick fix for the broken close button in the site editor.
The `'core/edit-site'` store is being registered after this module loads, which means we can't check for the data store until much later. Unfortunately that means the nav sidebar plugin is still registered and starts rendering before we can bail out.
* Apply D47337-code to sandbox
* Sandbox a site that has the experimental site editor (you can create one at https://horizon.wordpress.com/new?flags=gutenboarding/site-editor)
* Navigate to https://horizon.wordpress.com/site-editor/YOUR_SITES_DOMAIN
* The (W) button should work as expected
* Open the post/page editor
* The (W) button should open …
> Nav sidebar: hide the sidebar in the experimental site editor

- client/blocks/reader-share/index.jsx
The share button shown in the bottom right corner of posts displayed in the Reader opens a popover menu with sharing options when clicked. If the user clicks on the search field (displayed when the user has more than 6 sites), the popover closes unexpectedly.
* Avoid closing the share popup menu when clicks are performed inside of it
Pre-condition: The user must have 7 sites or more for the search field to be displayed in the share menu.
* Go to Reader in the Masterbar and then select Discover in the sidebar
* Click the share icon in the bottom right corner of a post
* Verify that the share menu is displayed, with a search field
* Click on the search field
* Verify that the share menu is still visible
* Type a text in the search field
* Verify that the share menu is still visible
* Click …
> Reader: Fix clicking search field in the share popup menu of a post closes the popup

- client/layout/logged-out.jsx
Testing reverting #39979 to see if it fixes the layout bug in classic editor whereby the entire top toolbar styles are overwritten by `.card`. 
The current theory is that the deferred import causes the `.card` styles to be loaded later rather than early (in the split second before the app realizes the user is logged in), which is what we need in order for the editor styles to override them.
That's the theory anyway.
If this doesn't work, the fallback attempt is here: https://github.com/Automattic/wp-calypso/pull/44578
**Before**
**After**
Use https://calypso.live/?branch=try/revert-gdpr-async-to-fix-classic-editor-card-override
This currently can't be tested locally due to the config setting for `gdpr-banner`, which is false for development
Test using a site that has the classic editor …
> Classic editor: hotfix for classic editor toolbar

- client/lib/abtest/README.md
Small fix to the documentation for the part about `localeExceptions`.
> Fix in documentation for the abtests lib

- client/lib/plans/plans-list.js
- client/my-sites/plan-features/index.jsx
This PR removes the **Get personalized help** feature from the Business Plan on the /plans page. See pbBQWj-eI-p2 for more details.
* Go to [/plans](https://wordpress.com/plans)
* Under the Business Plans column (under 'Business sites and online stores' tab)
* There shouldn't be any **Get personalized help** feature
> Remove Quick Start from Bussiness feature on plans page

- client/my-sites/checkout/checkout-thank-you/business-plan-details.jsx
This PR changes **Get personalized help** section's CTA link on the Business Plan purchase. New link should now showcases a Quick Start session upsell.
See pbBQWj-eI-p2 for more details.
* Purchase a new Business plan or upgrade.
* The CTA button for the **Get personalised help** should be **Purchase a session** and should point to [https://wordpress.com/checkout/offer-quickstart-session](https://wordpress.com/checkout/offer-quickstart-session)
> Update Quick Start CTA link from the Business purchase Thank you page

- client/components/jetpack-bundle-card/README.md
- client/components/jetpack-bundle-card/docs/example.tsx
- client/components/jetpack-bundle-card/index.tsx
- client/components/jetpack-bundle-card/style.scss
- client/components/jetpack-product-card/README.md
- client/components/jetpack-product-card/docs/example.tsx
- client/components/jetpack-product-card/features-item.tsx
- client/components/jetpack-product-card/features.tsx
- client/components/jetpack-product-card/fixture/index.ts
- client/components/jetpack-product-card/index.tsx
- client/components/jetpack-product-card/lib/use-flexbox-wrap-detection.ts
- client/components/jetpack-product-card/style.scss
- client/components/jetpack-product-card/types.ts
- client/devdocs/design/index.jsx
This PR adds a new product card for Jetpack items. It's currently available from the _UI Components_ section of the live docs. 
A product can be a bundle (e.g. Security), a plan (e.g. All-in), or an individual product (e.g. Backup). The card can be used for all three of them.
The spacing values annotated in the mockups cannot always be directly transposed to padding/margin in CSS. I've followed the mockups closely but let me know if something looks off.
Product cards have a different color depending on the product (bundle, plan, and individual product). The `JetpackBundleCard` is a proof of concept of how that's handled.
The headings and the price are on the same row, the former being left aligned and the latter right aligned. However if the card is too small to display both side by side, …
> Jetpack: add new Jetpack product card

- client/landing/gutenboarding/hooks/use-step-navigation.ts
* To prevent Go Back button getting stuck in plans page.
* Click "Go Back" on the plans page.
> Gutenboarding: Temporarily remove feature step from use site navigation.

- client/my-sites/checkout/composite-checkout/composite-checkout.js
- client/my-sites/checkout/composite-checkout/test/composite-checkout.js
Reverts Automattic/wp-calypso#44572
This PR reapplies the changes of https://github.com/Automattic/wp-calypso/pull/44564 but updates a test in addition.
> Composite checkout: fix purchase link in duplicate notice

- packages/data-stores/src/auth/test/flows.ts
* Replace call to React Testing Library's `wait` with `waitFor` in the data stores auth package's flows test
* Checkout this branch, and run `yarn test-packages packages/data-stores`
* You should not see the `console.warn` warning about usage of the deprecated `wait` function
Fixes #44597
> Replace usage of deprecated wait call with waitFor in data-stores auth package flows test

- client/landing/gutenboarding/onboarding-block/acquire-intent/style.scss
* Remove `box-shadow` in site title input inherited from core component
Perhaps caused by some recent `@wordpress/*` packages update?
- Open `/new`
- Focus in site input
> Gutenboarding: remove outline from site title input

- client/blocks/reader-full-post/_content.scss
* This PR adds support for the social icon links to the `_content.scss`, so that Android, iOS, and the web will properly format the block while viewing the post in the Reader. 
The following github issues will provide more detail
[Android](https://github.com/wordpress-mobile/WordPress-Android/issues/12545)
[iOS](https://github.com/wordpress-mobile/WordPress-iOS/issues/14541)
Of note:
On the web, the social icons link adheres to all alignments - center, left, right and cases in which no alignment has been chosen. For the native clients, there is a prior rule that dictates whether or not left and right alignments will be respected based upon the screen size of the device. Devices smaller than 660px will not respect those settings.
* Open the following reader post in Production …
> Reader: add css for Gutenberg social link block

- client/components/jetpack/daily-backup-status/index.jsx
Fix the issue with the next backup schedule showing up with negative. Sometimes, depending on the site timezone and the next backup schedule, the Backup section shows up a negative hour scheduling:
This PR tries to fix that issue updating the code that probably was introducing it.
**Note:** I've not been able to replicate the issue, but with this fix should resolve the issue.
**More info:** 1164141197617539-as-1177475113319458
- Apply this PR
- Select a site with Backup subscription
- Change the hour site and check the scheduled time for the next backup. 
- See the last backup time, and calculate the remaining hours to the next backup, it should be 24+3 hours from the last backup and check it with what the Backup section says.
> Fix the issue with the backup schedule, it shows negative hour

- client/layout/masterbar/logged-in.jsx
- client/layout/masterbar/style.scss
- client/my-sites/checkout/checkout-system-decider.js
- client/my-sites/checkout/checkout/style.scss
- client/my-sites/checkout/composite-checkout/add-items.ts
- client/my-sites/checkout/composite-checkout/composite-checkout.js
- client/my-sites/checkout/composite-checkout/use-prepare-product-for-cart.js
- client/my-sites/checkout/composite-checkout/wpcom/components/wp-order-review-line-items.js
- client/my-sites/checkout/composite-checkout/wpcom/hooks/product-variants.js
- packages/calypso-color-schemes/src/shared/color-schemes/_default.scss
- packages/composite-checkout/README.md
- packages/composite-checkout/src/public-api.js
This adds Jetpack product and plan support to the new Checkout flow for all environments except production - allowing us to test purchase flows outside of Calypso.
ref: pbOQVh-l8-p2
In order to avoid adding additional complexity, this _does_ modify the current production Jetpack Checkout in the following ways:
- removes the dark background (and related box-shadow/border adjustments)
- shows the primary header (master) bar, with Jetpack branding and close button (with same behavior as removing items from cart)
**Production Before** | **Production After** | **Testing**
------------ | ------------- | -------------
**To Test Composite Checkout ("Testing" from screenshots):**
- with a Jetpack site (you can create a new one at jurassic.ninja), visit `/plans/`
- choose a plan or product (scroll …
> Checkout Redesign: add Jetpack support

- client/my-sites/checkout/checkout/index.jsx
- client/my-sites/checkout/composite-checkout/test/composite-checkout-thank-you.js
- client/my-sites/checkout/composite-checkout/use-get-thank-you-url.js
This disables the concierge upsell thank-you page that would appear after a Personal plan purchase if the order Id is set. This occurs when we would be showing a "Pending" page before the purchase completes. For example, when paying with a 3D Secure credit card.
There is probably a way to show the upsell even in the "pending" case, but this is a quick fix because the current experience results in an invalid URL that displays a broken page.
Fixes https://github.com/Automattic/wp-calypso/issues/44541 for both new and old checkout.
First make sure that the offer still works:
- Make sure that you're in the `offer` variant of the `conciergeUpsellDial` AB test.
- Visit checkout with a Personal plan in the cart.
- Using a non-3DS card, complete the purchase.
- Verify that you are redirected to …
> Checkout: Disable concierge upsell thank-you page for 3DS

- apps/full-site-editing/full-site-editing-plugin/premium-content/premium-content.php
When activating the 1.15 build of the editing toolkit, WordPress displays a "The plugin nodes not have a valid header" error.
* Remove the plugin header from `/premium-content/premium-content.php` because it is not a plugin.
It appears that Premium Content began development as a seperate plugin, but then before shipping it was rolled in to `full-site-editing`. When WordPress scans `plugins` it finds this plugin header and the real one in `full-site-editing-plugin.php`. Up until now this hasn't been a problem because "Full Site Editing" comes before "Premium Content" in the alphabet.
The plugin was renamed in #44499 to "WordPress.com Editing Toolkit". "Premium Content" comes first alphabetically so WordPress tries to use it during plugin activation.
It looks like the plugin header in …
> Remove the plugin header nested inside the editor toolkit

- packages/social-previews/CHANGELOG.md
- packages/social-previews/package.json
- packages/social-previews/src/search-preview/index.jsx
- packages/social-previews/src/search-preview/style.scss
- packages/social-previews/test/index.js
* Remove Search preview header as per design in https://github.com/Automattic/wp-calypso/issues/44489
* Remove i18n-calypso dependency
* Bump version to 1.0.2
| --- | --- |
| <img width="564" alt="Screenshot 2020-08-03 at 13 28 11" src="https://user-images.githubusercontent.com/1562646/89178625-523ca580-d58e-11ea-93ea-742a01149dae.png"> | <img width="560" alt="Screenshot 2020-08-03 at 13 28 29" src="https://user-images.githubusercontent.com/1562646/89178633-5668c300-d58e-11ea-8d36-0ef903b36c20.png">|
Check if all tests pass:
* run `yarn run jest -c=test/packages/jest.config.js packages/social-previews/test/index.js`
Fixes https://github.com/Automattic/wp-calypso/issues/44489
> Social Previews: Remove i18n-calypso dependency by removing search preview header

- client/my-sites/site-settings/form-general.jsx
Hide `Custom Address` from General settings for P2 sites
- Go to Manage Settings -> Custom Address should be there
- Switch to a P2 site -> Custom Address setting should not be visible
> Hide custom address setting for P2 sites

- config/horizon.json
- config/production.json
This PR removes the Jetpack Personal plan from production as part of the Jetpack offer reset project
Visually check that the config flags are changed appropriately, as there is no way to test without shipping this.
> Disable Jetpack Personal plan in prod

- client/devdocs/design/search-collection.jsx
- client/devdocs/docs-example/wrapper.jsx
Added autoscroll function to onClick and onKeyPress events.  Specifically, the issue pointed out that the component link would render at the bottom of the documentation page. I noticed that the same thing happened with other components within the parent, so I added a function that would cause the links to render at the top of the documentation page.
*
Go to : https://wpcalypso.wordpress.com/devdocs/design , scroll down to to view Popover docs (or any other link on the bottom half of the page). The documentation for Popover should be scrolled to the top of the page after following the link.
*
Fixes #24337
> Bug Fix: Scroll to top of page when link is clicked

- client/extensions/woocommerce/woocommerce-services/state/shipping-label/actions.js
WooCommerce Services 1.24 updated the API response for shipping rates which caused a backwards compatibility issue with the Store on WP.com label purchase flow.
* Retrieve `shipment_id` from new location if it cannot be found in old location
A similar change was made in the WCS plugin here so the wp-admin interface can accept the updated API: https://github.com/Automattic/woocommerce-services/pull/2046/files#diff-09d52b7e14fcd8c2a349cabb5e073666
* Test on a site with Store on WP.com
* Create a shippable order
* Go to order and try to purchase a shipping label
* Shipping label purchase should be successful
Fixes https://github.com/Automattic/woocommerce-shipping-issues/issues/81
> Fix shipping label purchase with WCS 1.24

- .circleci/config.yml
- client/desktop/app-handlers/printer/index.js
- client/desktop/app-handlers/updater/auto-updater/index.js
- client/desktop/lib/updater/index.js
- client/desktop/window-handlers/external-links/editor/index.js
- client/desktop/window-handlers/external-links/index.js
- desktop/bin/validate_tag.js
- desktop/package.json
This PR updates wp-desktop in the Calypso monorepo to the latest changes in the wp-desktop repo (in preparation for final deprecation of the separate repository).
The SHA of wp-desktop that was migrated was from Automattic/wp-desktop@e299749. This PR gathers all changes made to the wp-desktop source since then (including the "check version" CI helper).
> desktop: update desktop to latest

- client/my-sites/site-settings/manage-connection/site-ownership.jsx
- client/state/jetpack/connection/actions.js
- client/state/jetpack/connection/test/actions.js
- client/state/selectors/get-jetpack-connection-owner.js
- client/state/selectors/is-jetpack-user-connection-owner.js
- client/state/selectors/test/fixtures/jetpack-connection.js
- client/state/selectors/test/get-jetpack-connection-owner.js
- client/state/selectors/test/is-jetpack-user-connection-owner.js
Requires Automattic/jetpack#16327
This changes the wording of "Someone else" to a specific username in Site Settings. Although I have no strong views on the language of `master` either, as this PR involves touching those selectors, I've updated them as part of #43303 too.  
Apply the changes on the Jetpack side and visit `/settings/manage-connection/site` from an account which doesn't own the connection.
**Before:**
**After:**
_When not as owner:_
_When as owner (no changes):_
cc @joanrho, @ockham 
Fixes #25812
> Site Settings: Specify Jetpack Connection Owner

- client/components/inline-support-link/README.md
- client/components/inline-support-link/docs/example.jsx
- client/components/inline-support-link/index.jsx
- client/lib/importer/importer-config.js
- client/my-sites/customer-home/cards/education/educational-content/index.jsx
- client/my-sites/customer-home/cards/features/stats/index.jsx
- client/my-sites/customer-home/cards/tasks/site-setup-list/get-task.js
- client/my-sites/earn/memberships/add-edit-plan-modal.jsx
- client/my-sites/themes/thanks-modal.jsx
* This pull request follows up on the conversation had in https://github.com/Automattic/wp-calypso/pull/44473, specifically the idea of migrating `InlineSupportLink` to always get its text from the `children` prop rather than supporting both that and the `text` prop it was using previously.
* Verify behavior and appearance of existing updated links. Existing usages include:
* "Need help exporting your content?" link in (e.g.) Import -> Blogger.
* "Learn more" links under "Learn and Grow" section of "My Home"
* "Read more" link under "Stats" section of "My Home" (or "Learn about stats" if site is unlaunched)
* "Testimonials" and "portfolio projects" links on Settings -> Writing
> Inline support link: use children instead of text prop

- client/my-sites/checkout/composite-checkout/composite-checkout.js
- client/my-sites/checkout/composite-checkout/payment-method-helpers.js
- client/my-sites/checkout/composite-checkout/payment-method-processors.js
- client/my-sites/checkout/composite-checkout/types/paypal-express.ts
- client/my-sites/checkout/composite-checkout/types/transaction-endpoint.ts
- client/my-sites/checkout/composite-checkout/wpcom/components/wp-checkout.js
- client/my-sites/checkout/composite-checkout/wpcom/components/wp-contact-form-summary.js
- client/my-sites/checkout/composite-checkout/wpcom/components/wp-contact-form.js
- client/my-sites/checkout/composite-checkout/wpcom/hooks/use-is-cached-contact-form-valid.js
- client/my-sites/checkout/composite-checkout/wpcom/hooks/use-skip-to-last-step-if-form-complete.js
This is another attempt at https://github.com/Automattic/wp-calypso/pull/44468, which was reverted in https://github.com/Automattic/wp-calypso/pull/44506
This PR changes the behavior of the new checkout form's contact details so that it will not display if the cart contains only renewal items and the existing cached contact details are valid. This behavior should mostly match [old checkout](https://github.com/Automattic/wp-calypso/blob/096d4759a964ebb19bcf0a068e51d438e9fab080/client/my-sites/checkout/checkout/index.jsx#L917). Previously, we had been displaying the contact details form fields any time that there were domain products in the cart.
In addition, it prevents sending the `domain_details` property to the transactions endpoint (and to paypal, etc.) when the cart contains only …
> Checkout: Do not display contact details form if the cart is only renewals, take 2

- client/lib/abtest/active-tests.js
- client/lib/abtest/getters.ts
* Introduce an AB experiment so we can develop and test things easily in every environment.
```
import { shouldShowOfferResetFlow } from 'lib/abtest/getters';
if ( shouldShowOfferResetFlow() ) {
console.log( 'A/B showOfferResetFlow variant is running' );
}
```
* Run this PR.
* Go to `http://calypso.localhost:3000/`.
* Check that on the bottom-right corner of the screen the experiment can be found.
Fixes 1169247016322522-as-1187484764348889.
> Create AB experiment for the Offer Reset project

- client/my-sites/plans-v2/README.md
- client/my-sites/plans-v2/controller.tsx
- client/my-sites/plans-v2/details.tsx
- client/my-sites/plans-v2/index.ts
- client/my-sites/plans-v2/selector.tsx
- client/my-sites/plans-v2/types.ts
- client/my-sites/plans-v2/upsell.tsx
- client/my-sites/plans-v2/utils.ts
* Adds a new folder where components can be wired together.
* Creates the following components: `SelectorPage`, `DetailsPage`, and `UpsellPage`.
* Provides helper function to add paths.
* Starts typing.
* Review code- this isn't loaded anywhere yet. It is intended as a stub for future work.
Fixes 1169247016322522-as-1187480522520329.
> Adds root components for Offer Reset plan redesign pages

- client/my-sites/checkout/composite-checkout/wpcom/components/wp-checkout.js
This fixes a regression introduced by https://github.com/Automattic/wp-calypso/pull/44533 which caused domain contact validation to be used for G Suite purchases, instead of G Suite validation.
- Add a G Suite product to your cart for a domain you already own (the cart must not contain a domain for this to work).
- Visit checkout with your devtool network tab open.
- Verify that you see a network call to `https://public-api.wordpress.com/rest/v1.1/me/google-apps/validate` and that you do not see a network call to `https://public-api.wordpress.com/rest/v1.2/me/domain-contact-information/validate`.
> Composite checkout: Do not run domain validation for GSuite

- apps/full-site-editing/full-site-editing-plugin/full-site-editing-plugin.php
- apps/full-site-editing/full-site-editing-plugin/readme.txt
- apps/full-site-editing/package.json
* Bumps version of the editing toolkit
New Relase notes:
* Plugin display name changed to WordPress.com Editing Toolkit.
* The donation block has been removed from the plugin.
* Improved contrast of links in the navigation sidebar.
* Add a launch sidebar to the editor to walk the user through the launch flows.
* Fix formatting of the site title in the navigation sidebar.
Changes included in this release:
* #44299 
* #44418 
* #44412 
* #44499 
* #44507 
* #42835 
* #44146 
* #44278 
* #44508 
* #44546 
* #44549
* #44574
* #44582
* #44601
* Apply D47156-code to your sandbox
* Check the features included in this release appear in the editor as expected
* Smoke test the editor on Atomic with and without the Gutenberg plugin enabled
> Bump WordPress.com Editing Toolkit version to 1.15

- client/my-sites/checkout/composite-checkout/wpcom/components/wp-checkout-order-summary.js
* Breaks long domain names to the next line
**BEFORE**
**AFTER**
* Add a domain with a long name to cart and proceed to checkout (you need to be in US/USD to see it)
* Verify that the domain name wraps to the next line.
> Checkout: Break long domain name in the summary section

- client/components/domains/domain-registration-suggestion/index.jsx
- client/components/domains/domain-search-results/index.jsx
- client/components/domains/free-domain-explainer/index.jsx
- client/components/domains/register-domain-step/index.jsx
- client/layout/index.jsx
- client/my-sites/plans-features-main/index.jsx
- client/signup/steps/domains/index.jsx
- client/signup/steps/user/index.jsx
The current change ensures that:
1. User is assigned to the reskinned variant.
2. User is not an existing user. (User is in the signup flow)
3. User is in the onboarding flow.
This stops the reskin design from being displayed whenever the component is shared by multiple views.
https://github.com/Automattic/wp-calypso/blob/af5c8f9d9a01955728426083c8944cc0fb4c57a0/client/layout/index.jsx#L158
Happy Path:
* Make sure you're assigned to reskinned group of reskinSignupFlow a/b test.
Note: this test is intended to work only for non-EN and non-ES users. (p1596055144383000-slack-marketing-health).
* The screens should look like the ones in the description of #44223
Other Cases:
**Other signup flows should not show reskin elements.** From …
> Consolidates checks for reskin variation

- apps/full-site-editing/full-site-editing-plugin/premium-content/index.js
* We are removing the `paid` wording from the premium content block in favor of an updated icon indicator which will be addressed in an other PR
* `cd apps/full-site-editing`
* `yarn dev --sync`
* open your sandbox and go to the editor
* try adding the `Premium Content` block
* It should appear without the `(paid)` wording in the title
Before | After
-------|------
Fixes #44352
> Premium Content: remove Paid wording from title

- packages/babel-plugin-i18n-calypso/package.json
- packages/babel-plugin-i18n-calypso/src/index.js
* Merge plurals and extracted comments for strings with the same singular (`msgid`) within the same JS file.
Add the following code snippet to some JS component, e.g. `client/me/constants.js`:
```
i18n.translate( 'Test string extraction', { comment: 'comment1' } );
i18n.translate( 'Test string extraction', 'plural', {
comment: 'comment2',
} );
```
Run `NODE_ENV=build_pot yarn build` and confirm `build/i18n-calypso/client-me-constants.js.pot` (or the respective POT file if you've added the snippet to other module) contains the extracted string with both comments and plural.
> babel-plugin-i18n-calypso: Fix merging matching strings properties

- client/my-sites/checkout/checkout-system-decider.js
- client/my-sites/checkout/composite-checkout/add-items.ts
- client/my-sites/checkout/composite-checkout/composite-checkout.js
- client/my-sites/checkout/composite-checkout/test/composite-checkout.js
- client/my-sites/checkout/composite-checkout/use-prepare-product-for-cart.js
When a `jetpack_search` product is added to the cart,[ legacy Checkout maps the product to either `jetpack_` or `wpcom_` depending on the selected site](https://github.com/Automattic/wp-calypso/blob/master/client/my-sites/checkout/checkout/index.jsx#L318-L337). This does the same for the new Checkout flow.
**To test:**
- add Jetpack search to a simple site: `calypso.localhost:3000/checkout/[simple site]/jetpack_search_monthly`
- verify that composite checkout loads with the monthly search product
- empty the cart and add Jetpack search (yearly) to a simple site: `calypso.localhost:3000/checkout/[simple site]/jetpack_search`
- verify that composite checkout loads with the yearly search product
- repeat with a Jetpack site: `calypso.localhost:3000/checkout/[jetpack …
> Checkout: fix jetpack_search to wpcom_search mapping

- client/signup/p2-processing-screen/index.jsx
- client/signup/p2-processing-screen/style.scss
- client/signup/p2-step-wrapper/style.scss
- client/signup/steps/p2-site/style.scss
- client/signup/style.scss
* Small tweaks to the P2 signup flow so it looks better on mobile
* Tweaks to the site creation screen ("Hooray!") so it displays an animation and users know that something is happening.
- Switch to this branch
- Go to http://calypso.localhost:3000/start/p2/
- Complete the flow (ideally with a non-A8C user account)
- Make sure that nothing is broken visually.
> P2 Signup: Updates to styling

- client/landing/jetpack-cloud/sections/settings/main.jsx
- client/landing/jetpack-cloud/sections/settings/style.scss
**Asana: ** 1169345694087188-as-1173737050079927
Include the new copies for the Settings section, depending on the product subscriptions.
**Copy for need credentials:**
- BACKUP ONLY: "Enter your server credentials to enable one-click restores for backups."
- SCAN ONLY: "Enter your server credentials to enable Jetpack to auto fix threats."
- BOTH: "Enter your server credentials to enable one-click restores for backups and to auto-fix threats."
**Copy for has credentials:**
- BOTH: "One-click restores and auto-fix threats are enabled."
- BACKUPS ONLY: "One-click restores are enabled."
- SCAN ONLY: "Auto-fix threats are enabled."
- Select a site with Backup and check the copy for with and without credentials
- Select a site with Scan and check the copy for with and …
> Jetpack Cloud: Add new copies to the Setting section

- client/components/jetpack/daily-backup-status/index.jsx
* (Non-mobile layouts only) When the selected date isn't the same as the current calendar date, show "Latest backups on this day" instead of "Latest backups."
Fixes #44530, `1164141197617539-as-1186718228515397`.
* For a site with Jetpack Backup, go to the Backup page on either Jetpack.com or WordPress.com, using a non-mobile screen layout.
* Observe/verify that for the current calendar date, if a backup exists, the status header reads "Latest backup" (see screenshot for example).
* Observe/verify that for every other date with a backup, the status header reads "Latest backup on this day" (see screenshot for example).
> Jetpack Backup: Show 'Latest backup on this day' for dates before today

- client/my-sites/checkout/composite-checkout/contact-validation.js
- client/my-sites/checkout/composite-checkout/wpcom/components/wp-checkout.js
In #44533, we're hiding the full domain contact details form for renewals to prevent users from submitting invalid data that's already stored. Unfortunately, some old cached domain details might not conform to the validation required for renewals. 
This PR shows the full contact form, with highlighted invalid fields If the server returns an error on validating the cached details.
ref: p1596628478344100-payments-shilling
**To test:**
This is a hard one to test because it requires invalid data from the original domain registration (which was valid at the time). 
- Apply D47627-code which will return an invalid phone number for cached contact details.
- Add a domain renewal to your cart.
- Verify that you see the full contact details (zip/country).
- Attempt to submit …
> Checkout: show full domain contact details when invalid cached details exist

- client/my-sites/plans-v2/utils.ts
- client/my-sites/plans/index.js
* Loads the Offer Reset stub pages when the A/B test is correctly set.
Note: Ideally we'd find a way to dynamically load these pages to let Webpack properly code split. However, in the interest in time, this can be a future revision.
Note this is NOT supposed to follow mocks, this is an early implementation.
* Visit `/:site/plans` and verify old pages still appear.
* Set A/B test to `showOfferResetFlow`.
* Visit the following URLs:
- `/:site/plans` - Plan picker page.
- `/:site/plans/monthly` - Plan picker page with default duration of monthly.
- `/:site/plans/jetpack_backup/annual/details` - Product details page (daily vs real-time, for example).
- `/:site/plans/jetpack_backup/annual/additions` - Product upsell page.
Fixes 1169247016322522-as-1187530033739401.
> Loads new Offer Reset pages with A/B test set

- client/blocks/time-mismatch-warning/README.md
- client/blocks/time-mismatch-warning/docs/example.tsx
- client/blocks/time-mismatch-warning/index.tsx
- client/blocks/time-mismatch-warning/test/index.jsx
- client/devdocs/design/blocks.jsx
* Adds a new block, `TimeMismatchWarning`. This block displays a warning when the site time and user time do not match.
* Review devdocs to ensure block renders as expected.
Fixes 1143508703416848-as-1185886809463829. Ref p1596221587136600-slack-CQXNTE9K9.
> Adds a new block TimeMismatchWarning

- client/my-sites/checkout/composite-checkout/wpcom/hooks/use-skip-to-last-step-if-form-complete.js
In IE11, [HashChangeEvent](https://developer.mozilla.org/en-US/docs/Web/API/HashChangeEvent) does not exist. This adds a guard to prevent fatals if it does not exist.
Using IE 11, visit checkout with pre-filled contact details. This will validate the details and cause the URL to change to add `#step2` at the end. Verify that there are no fatal errors (although the step will not actually change).
> Checkout: Guard against nonexistent HashChangeEvent

- client/my-sites/checkout/composite-checkout/wpcom/components/wp-checkout.js
Since https://github.com/Automattic/wp-calypso/pull/44533 we do not send `domain_details` (full contact details) to the transactions endpoint when submitting a renewal purchase. However, we were still sending those details to the validation endpoints before purchase, which can cause odd bugs if cached contact details exist that are somehow invalid. 
This was attempted to be fixed by https://github.com/Automattic/wp-calypso/pull/44690 (and then reverted) by not allowing us to have invalid contact details, but it does not really solve the issue because it implies that we can change those contact details, when in fact they are not being used anywhere after validation.
This PR does not send contact details for validation at all if they are not going to be sent to the transactions endpoint.
- …
> Composite checkout: Prevent validating contact details for renewals

- client/components/domains/contact-details-form-fields/managed-contact-details-form-fields.jsx
- client/lib/postal-code/index.jsx
- client/my-sites/checkout/composite-checkout/composite-checkout.js
- client/my-sites/checkout/composite-checkout/payment-method-helpers.js
- client/my-sites/checkout/composite-checkout/payment-method-processors.js
- client/my-sites/checkout/composite-checkout/wpcom/components/wp-checkout.js
- client/my-sites/checkout/composite-checkout/wpcom/components/wp-contact-form-summary.js
- client/my-sites/checkout/composite-checkout/wpcom/components/wp-contact-form.js
- client/my-sites/checkout/composite-checkout/wpcom/types/wpcom-store-state.ts
This adds postal code formatting in composite checkout to be similar to the behavior in old checkout.
Old checkout modifies the postal code field value itself when the field is blurred. This PR instead formats only when the postal code value sending to the validation and transaction endpoints. This late formatting may be necessary since there are situations where the field is never edited (eg: initial validation on load to skip the step), or it might be edited before we know the country (which is required for the formatting).
Fixes https://github.com/Automattic/wp-calypso/issues/44622
- Add a domain to your cart and visit checkout.
- Choose The Netherlands as your country.
- Enter the postal code `2651BS` (do not type a space between the numbers and letters).
- Press "Continue".
- Verify …
> Composite checkout: Add postal code auto-formatting

- client/components/jetpack/daily-backup-status/action-buttons.jsx
- client/components/jetpack/daily-backup-status/index.jsx
- client/components/jetpack/daily-backup-status/test/action-buttons.jsx
- client/my-sites/backup/main.jsx
(Includes #44648.)
* Move `ActionButtons` from `DailyBackupStatus` into its own component file.
* Add unit tests to cover `ActionButtons`.
* Rely more on selectors than passed-in properties.
* Remove unused property references from `DailyBackupStatus`.
* Run all tests and check that they pass (especially `client/components/jetpack/daily-backup-status/test`).
* Check that the `DailyBackupStatus` card -- specifically the action buttons at the bottom -- work as they do in production. Be sure to cover all possible states, including:
* backup and restore both being available for a given date;
* backups being unavailable on a given date; and
* backup available on a given date but lack of credentials for Restores.
* When checking `DailyBackupStatus`, verify that:
* all Tracks events still …
> Jetpack Backup: Refactor ActionButtons, add test coverage

- bin/pre-commit-hook.js
In theory, we run the PHPCBF auto-formatter in our pre-commit hook. In practice, this has been failing, and I suspect has been the source of a number of PRs being submitted with PHP lint errors that PHPCBF could auto-fix -- see e.g. #43817.
The reason for this is that our pre-commit hook will preferably use a system-wide installed copy of those tools; however, there's no guarantee that dependencies, such as the WordPress Coding Standards, are also available globally. They will however be installed locally through a simply `compose install`, as will PHPCS and PHPCBF, and our pre-commit hook already has messaging to instruct the user to do so.
The fix is thus to never use the globally installed versions of PHPCS and PHPCBF, but always the locally installed ones, and if they can't be found, …
> Pre-commit hook: Only use local copies of phpcs and phpcbf

- .circleci/config.yml
- .github/workflows/editing-toolkit-plugin.yml
- apps/full-site-editing/README.md
1. Remove editing toolkit tests from circleCI
2. Rename from fse to editing toolkit
3. Add to GH actions.
test-unit JS tests should look good in CI
> Move Editing Toolkit JS tests to GitHub & rename

- packages/onboarding/src/action-buttons/index.tsx
The isLarge property was throwing a warning, as it was deprecated in Gutenberg Button component.
Issue: https://github.com/Automattic/wp-calypso/issues/44603
* remove the isLarge prop from [NextButton & SkipButton](packages/onboarding/src/action-buttons/index.tsx), it is no longer needed due to changes in Gutenberg Button component.
* Open URL: calypso.localhost:3000/new
* Check the console for warnings related to `isLarge` prop, there should not be warnings
* Continue to the Style step /new/style where the NextButton component is
* Check the console for warnings related to `isLarge` prop, there should be no warnings
> Remove isLarge prop from NextButton & SkipButton

- client/signup/navigation-link/index.jsx
- client/signup/style.scss
* Updates the "back" navigation text to "Go Back"
* Updates the position of the link according to the Figma design.
* Go to /start/new
* Make sure you're assigned to the reskinned group of reskinSignupFlow a/b test.
* Follow the signup flow steps
The top area should look like this:
Signup
Domains
Plans
> Updates the back navigation link for the signup reskinned flow

- client/components/jetpack/card/jetpack-product-card/style.scss
Updated styles of `JetpackProductCard` on desktop.
The difference between mobile and desktop seems minor in the mockups. On desktop:
- Card has a 4-side border
- Card has round corners
- Font size of the subheadline is the same as body text
- Visit `/devdocs/design/jetpack-product-card`, in a viewport > 660px
- Check the changes mentioned above
> Adjust styles for the new product cards on desktop

- client/blocks/reader-full-post/style.scss
- client/blocks/support-article-dialog/style.scss
- client/components/card-heading/style.scss
- client/components/jetpack/scan-history-placeholder/style.scss
- client/components/share/tumblr-share-preview/style.scss
- client/landing/jetpack-cloud/sections/settings/style.scss
- client/landing/jetpack-cloud/style.scss
- client/my-sites/checkout/upsell-nudge/white-glove/style.scss
* Updates all instances of 36px to the equivalent variable `$font-headline-small`
* I found no other instances of font sizes 37px - 46px (yay!) so there should be no visual changes.
**Visuals (not exhaustive)**
*  Switch to this PR
* Look for instances of large font size 36px across Calypso; note any visual regressions or bugs
> Typography: Update 36px font sizes to use Sass variable

- client/my-sites/earn/memberships/style.scss
* Similar to #44700 and Customer Home, we want to avoid overusing the brand font, Recoleta. In this case, using it on the larger heading in the primary card and for the page title is enough.
**Before**
**After**
* Switch to this PR and navigate to `/earn/payments/[site]`
* Note the small subheadings below the main card; they should be using the default system font rather than Recoleta
> Payments: Remove brand font from smaller section headings

- client/my-sites/checkout/composite-checkout/payment-method-helpers.js
Actual fix from @niranjan-uma-shankar
* This is a quick-fix to avoid destructuring errors due to `transactionOptions` not being an object
* Not sure how to test/reproduce - @niranjan-uma-shankar, did you get a good feel for the flow involved?
> Defend against undefined `transactionOptions`

- client/my-sites/sidebar/index.jsx
* This just adds a simple check for a siteId to remove the "Customize" tab from the All Sites View
Verify that at `/stats/day`, "Customize" no longer appears underneath the "Design" tab. 
cc @creativecoder 
Fixes #44663
> Sidebar: Remove Customizer Tab from All Sites View

- client/my-sites/domains/domain-management/list/list-all.jsx
- client/signup/config/flows-pure.js
- client/signup/config/flows.js
- client/signup/config/step-components.js
- client/signup/config/steps-pure.js
- client/signup/steps/domains/index.jsx
* Replaces the destination to `Add a domain` for the 'all domains' list with a modified NUX flow
* Click on the `Add a domain` button in the all domains list
* Verify that the NUX flow comes up to buy a domain and associates it to a site
> Modifies the domain-only nux flow for all domains

- client/landing/gutenboarding/onboarding-block/domains/index.tsx
* Reverting this commit: https://github.com/Automattic/wp-calypso/pull/44132/commits/528aadad86eced95b49855eb625852602d5ba236
* When writing [this comment](https://github.com/Automattic/wp-calypso/pull/44132#discussion_r454344115), I haven't realised we are removing all the primary buttons from this screen.
* Go to [/new](https://calypso.live/new?branch=update/gutenboarding-domains-modal-primary-button)
* Skip first step and then open domains modal.
* Go back and Continue buttons should be visible, both with the same action to close the modal.
Mentioned in pbAok1-1hJ-p2
> Gutenboaridng: re-add primary button to DomainsModal

- .github/CODEOWNERS
- Gutenboarding things are being re-used are split between here and there now (in packages, in landing and elsewhere)
- Data package should be considered more common ownership at this point
- We'll try to get more automated tests done so that we don't need to manually review when folks change things in these files
- Will help with notification fatigue when we know each request to review is intentional, and not automated
> Remove Luna as code owner

- apps/full-site-editing/full-site-editing-plugin/premium-content/style.css
* This pull request updates styling in the Editing Toolkit's premium content block to hide the "Connect to Stripe" nudge provided by Jetpack's payments block, since the PC block also has one and the user does not need to see two.
* Make sure your account is not connected to Stripe.
* Load the version of the full-site-editing plugin from this PR following one of the methods detailed in PCYsg-5Xx-p2.
* Create a new post or edit an existing one, and add a "Premium Content" block. 
* Verify that under the Edit view in the "Non-Subscriber View" section, the user is only presented with a single message indicating they should connect the account to Stripe.
Fixes #44332
> Premium Content: fix duplicate Connect To Stripe message

- client/blocks/inline-help/inline-help-rich-result.jsx
- client/blocks/inline-help/inline-help-search-card.jsx
- client/blocks/inline-help/popover.jsx
- client/blocks/inline-help/style.scss
There is currently a focus-loss that happens when clicking to the secondary content of the popover. In this case, the FAB -> Inline Search -> Contact. The focus is lost when clicking the Contact button.
* Open the FAB 
* Tab to the Contact button (or use a screen reader)
* Press Enter
* Focus should be on the hidden title. You will only notice this if using a screen reader.
* Press Tab
* You should be within the contact form
* Press Back
* Focus should be on the search input again
* Select a search result
* Focus should be on the search result title. You won't see the focus ring.
* Press Tab
* You should be on the Read more button
Fixes https://github.com/Automattic/wp-calypso/issues/41506
> Inline Help: FAB Focus Management

- client/components/domains/contact-details-form-fields/managed-contact-details-form-fields.jsx
- client/my-sites/checkout/composite-checkout/wpcom/components/wp-checkout.js
- client/my-sites/checkout/composite-checkout/wpcom/components/wp-contact-form-summary.js
- client/my-sites/checkout/composite-checkout/wpcom/components/wp-contact-form.js
- client/my-sites/checkout/composite-checkout/wpcom/types/backend/domain-contact-validation-endpoint.ts
- client/my-sites/checkout/composite-checkout/wpcom/types/wpcom-store-state.ts
Since the `alternateEmail` field is only used by G Suite (see https://github.com/Automattic/wp-calypso/pull/35920), there's no need to display it when a G Suite product is not currently in the cart. (See also https://github.com/Automattic/wp-calypso/pull/43403 which fixed a tangential issue.)
This PR does the following:
1. Hides the `alternateEmail` field from the contact form inactive step summary when a G Suite product is not in the cart. (Previously it would also be shown if a domain product was in the cart. This new behavior matches old checkout.)
2. Stops pre-populating the `alternateEmail` field. In order to pre-populate the `alternateEmail` field when G Suite is in the cart, we were setting its initial value to match the `email` field's value, if the latter was set and the former …
> Composite checkout: Hide alternate email when G Suite is not in cart

- client/my-sites/checkout/composite-checkout/composite-checkout.js
- client/my-sites/checkout/composite-checkout/payment-method-helpers.js
- client/my-sites/checkout/composite-checkout/payment-method-processors.js
* Registrationless checkout was introduced in https://github.com/Automattic/wp-calypso/pull/44206.
* This PR sends props to allow payments via Apple Pay to complete successfully on the logged out cart.
* On Safari, go to /start/onboarding-registrationless and add a plan to cart
* Pay with Apple Pay and verify if the purchase completes successfully
> Registrationless checkout: Send transactionOptions for apple pay

- client/landing/gutenboarding/hooks/use-typer.ts
- client/landing/gutenboarding/onboarding-block/acquire-intent/site-title.tsx
This PR fixes missing translations in the typer in the gutenboarding `/new` page:
The translations are in glotpress(*), but not being shown because they're evaluated in a `const` at load time before the user's translations are available.
This PR moves the translations inside the react component so they are effected by locale updates.
In order to do this, I've moved the randomization into useTyper (which is awesome, btw 👍 ), and changed the randomness somewhat out of expedience. `useTyper` now chooses the words randomly, rather than going through the whole list before repeating.
@alshakero: Is that ok? I actually liked your old logic better, and considered shuffling indexes to keep the same functionality, but my real concern here is getting the strings translated, so I went with …
> Fix gutenboarding /new placeholder translations

- client/components/jetpack/card/jetpack-product-card/style.scss
Minor colour updates to the features section of the product card component.
New colours:
- icon: #3C434A
- subheading: #646970
- Visit `/devdocs/design/jetpack-product-card`
- Find the instance "Expanded Jetpack Product Card with Features Categories and More Link"
- Check the new colours (see screenshot below)
> Product card: update colours in the features section

- packages/wp-babel-makepot/cli.js
- packages/wp-babel-makepot/package.json
- packages/wp-babel-makepot/utils/concat-pot.js
* Add option to filter extracted strings by their source reference. It requires passing path to JSON file that contains file names and line numbers that should only be included in the final POT output.
```
echo "{\"client/me/help/help-search/index.jsx\":[94]}" > lines-filter.json;
npx -d ./packages/wp-babel-makepot wp-babel-makepot "client/me/help/help-search/index.jsx" -l lines-filter.json -d build/tmp/strings -o build/tmp/filtered-strings.pot
```
Check `build/tmp/filtered-strings.pot` and confirm it contains only the filtered translatable string "WordPress.com Documentation" from line 94 of `client/me/help/help-search/index.jsx`
> wp-babel-makepot: Add option to filter extracted strings by their source reference

- client/state/route/last-non-editor-route/reducer.js
- client/state/route/last-non-editor-route/schema.js
- client/state/route/last-non-editor-route/test/reducer.js
- client/state/route/reducer.js
- client/state/selectors/get-last-non-editor-route.js
- client/state/selectors/test/get-editor-close-config.js
- client/state/selectors/test/get-last-non-editor-route.js
When closing the block editor, we take the user back to the last non-editor page they were on. We determine the last non-editor state by searching through the action log.
The problem is that the action log isn't saved to `localStorage`, so if the user refreshes the page then we lose where they came from and just go to a default location. This bug is made even worse by the navigation sidebar because navigating between items in the sidebar refreshes the page too.
We can't persist the whole action log because that's going to grow unbounded. Instead we'll store just the info we want as a new bit of state in the redux store. Unfortunately that means there's data duplication. 🤞 the redux pattern helps us keep it in sync.
* Add `lastNonEditorRoute` state to redux store
* Persist …
> Save the last-non-editor-route in redux instead of calculating it

- client/me/help/help-contact-form/index.jsx
cc: @sixhours
Changes proposed in this Pull Request
Change wording on support contact form to avoid duplicate wording. "How can we help?" was used twice.
*
Testing instructions
Starting at URL: /help/contact
Final field now says "Tell us more about the problem" instead of "How can we help?"
Before:
After:
Fixes #44287
> Support label fix

- client/my-sites/email/email-management/index.jsx
* Hides the `PlanNavigation` menu under a feature flag
* Navigate to the `/email` page
* Confirm that the plan navigation menu is no longer visible
> Hides the `PlanNavigation` menu under a feature flag

- apps/full-site-editing/full-site-editing-plugin/common/data-stores/launch/index.ts
- apps/full-site-editing/full-site-editing-plugin/editor-domain-picker/src/domain-picker-fse/index.tsx
- apps/full-site-editing/full-site-editing-plugin/editor-site-launch/src/launch-menu/index.tsx
- apps/full-site-editing/full-site-editing-plugin/editor-site-launch/src/launch-menu/item.tsx
- apps/full-site-editing/full-site-editing-plugin/editor-site-launch/src/launch-steps/domain-step/index.tsx
- apps/full-site-editing/full-site-editing-plugin/editor-site-launch/src/launch-steps/name-step/index.tsx
- apps/full-site-editing/full-site-editing-plugin/editor-site-launch/src/launch-steps/name-step/styles.scss
- apps/full-site-editing/full-site-editing-plugin/editor-site-launch/src/launch-steps/plan-step/index.tsx
- apps/full-site-editing/full-site-editing-plugin/editor-site-launch/src/launch/index.tsx
- apps/full-site-editing/full-site-editing-plugin/editor-site-launch/src/wp-core-data-types.d.ts
- packages/domain-picker/src/domain-picker/style.scss
- packages/onboarding/src/action-buttons/style.scss
* **Step completion status.** If Site name value is cleared, mark step as incomplete and disable Continue button.
* **Integration with the flow.** When updating Site name, if no custom domain is selected in _Choose a domain_ step, initial query for domain is updated with the new Site name.
* First iteration of Site name step doesn’t include Site preview. So current implementation 
would follow the design from Pre-launch i12 with copy from the latest iteration. 
* Follow instruction from Getting started section of #43750 to have the new launch flow enabled.
* Create a site using [wordpress.com/new](https://wordpress.com/new) and sandbox it.
* First step should be the Name …
> Gutenboarding launch flow: add Name your site step

- client/my-sites/domains/domain-management/list/domain-item.jsx
- client/my-sites/domains/domain-management/list/index.jsx
- client/my-sites/domains/domain-management/list/list-header.jsx
- client/my-sites/domains/domain-management/list/style.scss
* Hide the detailed domain information when the "Change primary domain" button is clicked 
* Change the "Abort primary domain change" button text to "Cancel primary domain change"
Here's how it looks (before clicking on the button):
After clicking on the button:
* Open the site domains view and click on "Change primary domain" button in the header section
* Verify that the detailed domain data is hidden
> Update how primary domain change affects the domain item row

- client/my-sites/domains/domain-management/list/style.scss
* We're adding one more pixel between the info icon in the domains list header
* The options title was removed in another PR
* Just verify that the left margin of the `info-popover` button is 2px and it still looks good and no lines are broken
> Update the domain list header styling

- client/lib/domains/resolve-domain-status.js
- client/my-sites/domains/domain-management/edit/style.scss
* Instead of hardcoding the status colors we can use the standard theme colors for warning/error/success
* Check domains in different statuses - expired, expiring soon and activating and verify that the colors look okay
> Use the Calypso theme standard colors for the domain statuses

- client/my-sites/exporter/style.scss
* This ensures that the expanded accordion also benefits from the custom padding overriding the default padding of the Foldable Card.
Visit `/export/site` and expand the first accordion. Verify that "Export content" and "Select specific content to export" are aligned!
cc @sixhours 
Fixes #44741
> Exporter: Balance Padding on Expanded Accordion

- client/my-sites/customer-home/style.scss
* Our guidelines suggest that we should not overuse the brand font, Recoleta, and using it for all section headings on Customer Home tips into "overuse" territory, IMO. Thoughts?
**Before**
**After**
* Navigate to Customer Home or `/home`
* Note the change in the secondary and tertiary section headings (Stats, Learn and Grow, etc.)
> Customer Home: Remove brand font from smaller subheads

- client/components/jetpack/card/jetpack-bundle-card/fixture/index.ts
- client/components/jetpack/card/jetpack-bundle-card/style.scss
- client/components/jetpack/card/jetpack-individual-product-card/fixture/index.ts
- client/components/jetpack/card/jetpack-individual-product-card/style.scss
- client/components/jetpack/card/jetpack-plan-card/style.scss
This PR updates the colours used for the new Jetpack product cards
- Colors are now all taken from the Color Studio
- Bundles are now purple
- Plans are now green
- Updated icons in the dev docs example for consistency
- purple: ` --studio-purple-50` / `#984a9c`
- green: `--studio-jetpack-green-40` / `#069e08`
- blue: `--studio-wordpress-blue-30 ` / `#3895ba`
1. Download the PR
2. For each product type, check that the header border, the price stroke, and the badge have the proper colour (see screenshots):
- `devdocs/design/jetpack-plan-card`
- `devdocs/design/jetpack-bundle-card`
- `devdocs/design/jetpack-individual-product-card`
> Update colours of the new Jetpack product cards

- client/lib/jetpack/use-threats.ts
- client/state/data-layer/wpcom/sites/scan/threats/ignore.js
This PR simply dispatches `requestJetpackScanHistory` after a threat fix or ignore request completes. This ensures that the history grid is updated with the latest threat.
Shortcoming, not necessarily fixable here - When a fix takes a long amount of time, it does not immediately show up in the history, since it's not yet in the proper MySQL table. There's no great way around this now, but due to possible changes to the API in the near future, I'm not putting a lot of thought into that scenario. For now, I think this is fine.
* Boot this branch in calypso dev and find your way to the scan page with `?flags=jetpack/features-section` on the end of the URL. Follow through with the "ignore threat" flow. Immediately after ignoring, a request should go to the history endpoint and the history …
> Jetpack Scan: Update history after ignore or fix

- client/components/jetpack/card/jetpack-product-card/README.md
- client/components/jetpack/card/jetpack-product-card/index.tsx
Products don't have a description or tagline/subheadline in the current copy. This PR reflects this in the code.
- Check that you can still see the subheadline and description in the Jetpack Plan Card (`/devdocs/design/jetpack-plan-card`)
> Product card: make subheadline and description optional

- client/blocks/inline-help/admin-sections.js
In the InlineHelp admin sections, it looks like some descriptions related to "Change my site's footer text" were copy and pasted and not changed. 
For example, it doesn't make sense for the description for "Install, manage, and search for site Plugins" to be "You can customize your website by changing the footer credit in customizer."   I talked to @retrofox who worked on the original addition of these and he confirmed that it's not something done on purpose, and that they're okay to remove.
This removes the non-matching descriptions from the code.  Not all entries have descriptions, so it should be okay.
There are no functional changes, so it just needs to be confirmed that the PR doesn't break existing functionality.
1. Click on the Help FAB
2. Type in a query - For example: `site …
> InlineHelp: Remove incorrect descriptions

- client/my-sites/sidebar/index.jsx
* Hides the "Plans" sidebar item in the WordPress iOS and Android apps – having it present can cause the app to be rejected.
- Switch to this branch, then view it in your browser of choice (or use Calypso.live)
- Note that by default, the "Plans" page is still visible
- Adjust your user agent string, adding `wp-iphone` anywhere in the string
- Refresh the page – the plans menu item should no longer be visible.
> Hide the “Plans” sidebar item in the WPMobile apps

- client/my-sites/checkout/checkout/country-specific-payment-fields.jsx
- client/my-sites/checkout/composite-checkout/payment-methods/credit-card/contact-fields.js
- client/my-sites/checkout/composite-checkout/payment-methods/credit-card/credit-card-fields.js
- packages/composite-checkout/src/theme.js
In https://github.com/Automattic/wp-calypso/pull/43841 we modified the credit card payment method to support showing additional contact fields within its box for specific payment partners, specifically Ebanx in Brazil. However, these contact fields are not styled to appear inside a box in this way, so they don't look very good. This PR attempts to fix those styles for composite checkout without breaking their styles in old checkout.
Before:
- Apply D45663-code to force Ebanx to be available and sandbox the API and the store.
- Visit composite checkout with a product in the cart.
- In the contact step, choose "Brazil" for the country.
- In the payment method step, choose "Credit or debit card".
- Verify that you see additional contact fields appear below the existing fields in the same …
> Composite checkout: Improve styling of ebanx contact fields

- client/blocks/inline-help/admin-sections.js
- client/me/account/main.jsx
- client/my-sites/site-settings/form-general.jsx
- client/my-sites/site-settings/podcasting-details/link.jsx
- client/my-sites/site-settings/site-tools/index.jsx
fixes #44059
* Some inline help results will now link to specific sections of a page, now using anchors.  For example, "Delete a site or site's content":
* Old link: `/settings/general/${ siteSlug }`
* New link: `/settings/general/${ siteSlug }#site-tools__header`
* In some cases, `id`s needed to be added for the links to have something to go to.
1. Click on the Help FAB
2. Type in a query - For example: `footer text`
3. Click on "Change my site's footer text" from the admin results:
4. You should be taken to `/settings/general/${ siteSlug }#site-settings__footer-credit-header`, which should scroll such that the footer section is visible.
5. All answers modified:
* Change my site's footer text
* Change my site's timezone
* Launch my site
* Delete a site or site's content
* Set up a …
> InlineHelp: Anchor to appropriate sections from admin results (#44059)

- client/state/users/suggestions/reducer.js
- client/state/users/suggestions/selectors.js
- client/state/users/suggestions/test/reducer.js
@ChaosExAnima discovered a blog post that caused a fatal JS error in Reader full post. The culprit was a call to the /users/suggest endpoint for username suggestions, which was returning `suggestions: null` rather than the expected suggestions array.
This PR checks for a null value at the reducer, and stores an empty array in Redux state if `suggestions` is null.
Internal users can check the following URL:
https://wordpress.com/read/blogs/177698830/posts/1743
With the PR applied locally, it should no longer cause a fatal error.
http://calypso.localhost:3000/read/blogs/177698830/posts/1743
You can also check other internal P2 posts and verify that you are able to use the user suggestions feature as normal in the comments section.
> User suggestions: improve resilience when API returns null for suggestions

- client/landing/gutenboarding/components/header/index.tsx
- client/landing/gutenboarding/hooks/use-step-navigation.ts
- client/landing/gutenboarding/onboarding-block/domains/index.tsx
- client/package.json
- test/e2e/specs/wp-gutenboarding-spec.js
- yarn.lock
This PR removes the mandatory domain step from the onboarding flow. It also puts back the "Continue" CTA to the domain step when it's voluntarily asked for by the user (by clicking the nudge on top).
Go to [/new](https://calypso.live/new?branch=remove/mandatory-domain-step) and you shouldn't be shown the domain step unless you click the nudge.
Fixes part of #44454
> Remove mandatory domain step

- client/signup/config/flows-pure.js
Set the showRecaptcha option as true for all flows that involve a user step. Effected flows are as follows.
<details><summary> Flows that contains / will contain the recaptcha </summary>
<p>
- business: Create an account and a blog and then add the business plan to the users cart.
- premium: Create an account and a blog and then add the premium plan to the users cart.
- personal: Create an account and a blog and then add the personal plan to the users cart.
- free: Create an account and a blog and default to the free plan.
- with-theme: Preselect a theme to activate/buy from an external source
- onboarding: Abridged version of the onboarding flow. Read more in https://wp.me/pau2Xa-Vs.
- onboarding-plan-first: Shows the plan step before the domains step. Read more in …
> Enable showRecaptcha in signup flows

- client/landing/gutenboarding/onboarding-block/acquire-intent/index.tsx
- client/landing/gutenboarding/onboarding-block/acquire-intent/site-title.tsx
- client/landing/gutenboarding/onboarding-block/acquire-intent/style.scss
- client/landing/gutenboarding/path.ts
* Show vertical input only when `/new?vertical` param exists.
* Open `/new` and `/new?vertical`.
* On `/new?vertical`, you should see **"My site is about..."** and **"It's called..."**.
* On `/new`, you should see only **"My site is called..."**.
* Test layout on both desktop & mobile view.
Fixes #
> Gutenboarding: Show vertical input only when ?vertical param exists.

- client/lib/domains/resolve-domain-status.js
- client/my-sites/domains/domain-management/list/index.jsx
* Instead of showing one big warning for mapped domains not pointing at us at the top of the domains list we'll show a "Complete setup" status notice in the DomainItem component with warning color.
It looks like this:
And we're removing this warning from the top of the list:
* Add domain mapping for a domain that doesn't point to WordPress.com site and verify that you see the "Complete setup" info notice and that the item is marked with a warning color (orange)
> Move `DomainWarning` message in the `DomainItem` component

- apps/full-site-editing/full-site-editing-plugin/common/data-stores/launch/reducer.ts
- apps/full-site-editing/full-site-editing-plugin/editor-site-launch/src/hooks/use-site.ts
- apps/full-site-editing/full-site-editing-plugin/editor-site-launch/src/launch-menu/index.tsx
- apps/full-site-editing/full-site-editing-plugin/editor-site-launch/src/launch-menu/item.tsx
- apps/full-site-editing/full-site-editing-plugin/editor-site-launch/src/launch-steps/final-step/index.tsx
- apps/full-site-editing/full-site-editing-plugin/editor-site-launch/src/launch-steps/final-step/styles.scss
- apps/full-site-editing/full-site-editing-plugin/editor-site-launch/src/stores/index.ts
- apps/full-site-editing/package.json
- packages/composite-checkout/src/components/checkout-steps.js
- packages/composite-checkout/src/public-api.js
* Add summary to final step of the launch flow
* Link to each of the previous step from summary items
* Show completion status of each step
* Enable _Launch_ button only if all steps are completed 
* Create a site using `/new` flow.
* Sandbox the site.
* Click _Complete Setup_ in editor,
* Check the last step in the sidebar with various combinations of completed steps,
* **No step completed (disabled sidebar button)**
* **Without a selected plan**
* **Without site name**
* **All steps completed (Custom domain and paid plan)**
* **All steps completed (sub-domain and Free plan)**
Fixes #44450
> Gutenboarding launch flow: add final step summary

- apps/full-site-editing/full-site-editing-plugin/full-site-editing-plugin.php
- apps/full-site-editing/full-site-editing-plugin/readme.txt
- apps/full-site-editing/package.json
* Bumps version of the editing toolkit to 1.16.
New Release notes:
* Enable site launch flow for dev & horizon environment.
* Premium Content: Remove Paid wording from title.
* Premium Content: Fix duplicate Connect To Stripe message.
Changes included in this release:
https://github.com/Automattic/wp-calypso/pull/44476
https://github.com/Automattic/wp-calypso/pull/44638
https://github.com/Automattic/wp-calypso/pull/44551
https://github.com/Automattic/wp-calypso/pull/43312
https://github.com/Automattic/wp-calypso/pull/44659
https://github.com/Automattic/wp-calypso/pull/44708
https://github.com/Automattic/wp-calypso/pull/44748
https://github.com/Automattic/wp-calypso/pull/44768
https://github.com/Automattic/wp-calypso/pull/44821
See also: …
> Bump WordPress.com Editing Toolkit version to 1.16.

- apps/full-site-editing/full-site-editing-plugin/editor-gutenboarding-launch/index.ts
* When on mobile, do not open launch sidebar.
* Resize to mobile view.
* Click "Complete setup" button.
* It should just launch the site.
Fixes https://github.com/Automattic/wp-calypso/issues/44692
> Gutenboarding Site Launch: When on mobile, do not open launch sidebar.

- client/state/data-layer/wpcom/activity-log/update-credentials/index.js
When a credentials update fails, we currently map the error code to a localised error message for a notice, throwing away the backend’s non-localised error message.
This pull request adds a property with the backend’s error message to calypso_rewind_creds_update_failure events, giving us more insight into which failure modes aren’t yet handled but ought to be.
1. Make sure extensions like uBlock Origin are disabled.
1. Open devtools and go to the Network tab.
1. Try to save SSH credentials that are correct except for an incorrect password or private key.
1. Verify that the t.gif request for calypso_rewind_creds_update_failure contains the following message:
> Could not open connection to [something] with given credentials
More details at https://wp.me/pbuNQi-uF-p2
> Add backend error messages to credentials update failure events

- client/lib/abtest/active-tests.js
- config/production.json
- config/stage.json
- config/wpcalypso.json
To be merged into https://github.com/Automattic/wp-calypso/pull/44820 and thus together with Gutenboarding V2 mechanic changes. 
* Enable new launch flow in Gutenboarding via feature flags
* Bump AB test slug
- Create site via `/new`
- If you go via `/new?vertical` instead, you'll see vertical input
- You should not see domain step
- Once in editor, you should have "complete setup" button in the header
- Clicking that and going through steps will launch your site
> Gutenboarding: enable new launch flow in production

- client/my-sites/domains/controller.jsx
- client/my-sites/domains/index.js
In this PR we prevent all access to the domain management section for P2 sites. @klimeryk suggested doing this so that users don't accidentally end up with a custom domain for their P2 site which is non-manageable and will expire in a year.
Using a non-P2 site, navigate to domain management screen (i.e. `/domains/manage/lamosty.com`). You should be able to manage the domain. Now, switch to a P2 site. You should be redirected to `/`.
> P2: prevent accessing the domain management section

- client/components/jetpack/card/jetpack-plan-card/README.md
- client/components/jetpack/card/jetpack-plan-card/fixture/index.ts
- client/components/jetpack/card/jetpack-plan-card/index.tsx
- client/components/jetpack/card/jetpack-plan-card/style.scss
- client/components/jetpack/card/jetpack-product-card/README.md
- client/components/jetpack/card/jetpack-product-card/index.tsx
- client/components/jetpack/card/jetpack-product-card/style.scss
- client/my-sites/plans-v2/plans-column/index.tsx
This PR adds an expiry date to the product card, and applies minor CSS updates.
- the `deprecated` prop has been renamed to `isDeprecated` to match the convention used for other props
- `isDeprecated` is now passed to `JetpackProductCard` instead of `JetpackPlanCard`, for better reusability
- the expiry date is shown using the `moment` local format for dates (i.e. `L`)
- Visit `/devdocs/design/jetpack-plan-card`
- Find the card for the deprecated plan at the bottom of the page
- Notice the stroke of the original price is now black (see screenshot)
- Check that the expiry date is displayed (see screenshot)
> Product card: handle deprecated state

- apps/full-site-editing/full-site-editing-plugin/readme.txt
* Leftover from https://github.com/Automattic/wp-calypso/pull/44817
> The new version (1.16) does not match the stable tag (1.15) in readme.txt.
> Version info:
>	Previous Version: 1.15
>	New Version (defined in plugin loader): 1.16
>	Stable Tag (defined in readme.txt): 1.15
Nothing to test. :-)
> Editing toolkit plugin: update version in readme.txt to 1.16

- apps/full-site-editing/full-site-editing-plugin/common/data-stores/launch/reducer.ts
- apps/full-site-editing/full-site-editing-plugin/editor-site-launch/src/hooks/index.ts
- apps/full-site-editing/full-site-editing-plugin/editor-site-launch/src/hooks/use-domain-suggestion.ts
- apps/full-site-editing/full-site-editing-plugin/editor-site-launch/src/hooks/use-on-launch.ts
- apps/full-site-editing/full-site-editing-plugin/editor-site-launch/src/launch-steps/final-step/index.tsx
- apps/full-site-editing/full-site-editing-plugin/editor-site-launch/src/launch-steps/final-step/styles.scss
- apps/full-site-editing/full-site-editing-plugin/editor-site-launch/src/stores/index.ts
- apps/full-site-editing/full-site-editing-plugin/editor-site-launch/src/wp-components-types.d.ts
- apps/full-site-editing/typings/fse/index.d.ts
* When a free domain is selected, add a domain suggestion to summary step and a link to domain selection step https://cloudup.com/cnYQcB85Vrm
* Add a link _Upgrade to premium_ on plan summary if Free plan is selected.
* Create a site starting from [horizon.wordpress.com/new](https://horizon.wordpress.com/new).
* Press Complete setup button to open launch flow.
* Choose a free domain and advance to Launch you site step. A custom domain suggestion should appear.
Fixes part of #43750
> Gutenboarding launch flow: add domain suggestion to summary step

- client/landing/gutenboarding/hooks/use-show-vertical-input.ts
- client/landing/gutenboarding/onboarding-block/acquire-intent/index.tsx
- client/landing/gutenboarding/onboarding-block/acquire-intent/site-title.tsx
- client/landing/gutenboarding/stores/onboard/actions.ts
- client/landing/gutenboarding/stores/onboard/index.ts
- client/landing/gutenboarding/stores/onboard/reducer.ts
* Make vertical input persistent by moving it to the data store.
* Go to `/new`.
* It should show **My site is called...**.
* Go to `/new?vertical`.
* It should show **My site is about...**.
* Go to `/new` again.
* It should still show **My site is about...**.
* Go to `/new?fresh`.
* It should show **My site is called...**.
> Gutenboarding: Persistent show vertical input.

- apps/full-site-editing/full-site-editing-plugin/full-site-editing-plugin.php
- apps/full-site-editing/full-site-editing-plugin/readme.txt
- apps/full-site-editing/package.json
* Bump editor kit/FSE plugin to 1.17
Includes:
- https://github.com/Automattic/wp-calypso/pull/44823
- https://github.com/Automattic/wp-calypso/pull/44840
Both from team Luna.
- See PRs
> Site editor kit 1.17

- client/landing/gutenboarding/components/header/index.tsx
- client/landing/gutenboarding/hooks/use-show-vertical-input.ts
- client/landing/gutenboarding/hooks/use-step-navigation.ts
- client/landing/gutenboarding/lib/analytics/index.ts
- client/landing/gutenboarding/onboarding-block/acquire-intent/acquire-intent-text-input/index.tsx
- client/landing/gutenboarding/onboarding-block/acquire-intent/acquire-intent-text-input/style.scss
- client/landing/gutenboarding/onboarding-block/acquire-intent/index.tsx
- client/landing/gutenboarding/onboarding-block/acquire-intent/site-title.tsx
- client/landing/gutenboarding/onboarding-block/acquire-intent/style.scss
- client/landing/gutenboarding/onboarding-block/acquire-intent/vertical-select/index.tsx
- client/landing/gutenboarding/onboarding-block/acquire-intent/vertical-select/style.scss
- client/landing/gutenboarding/onboarding-block/domains/index.tsx
- client/landing/gutenboarding/path.ts
- client/landing/gutenboarding/stores/onboard/actions.ts
- client/landing/gutenboarding/stores/onboard/index.ts
- client/landing/gutenboarding/stores/onboard/reducer.ts
- client/landing/gutenboarding/stores/onboard/selectors.ts
- client/landing/gutenboarding/variables.scss
- client/lib/abtest/active-tests.js
- client/package.json
- config/production.json
- config/stage.json
- config/wpcalypso.json
- packages/onboarding/styles/z-index.scss
- test/e2e/lib/pages/gutenboarding/acquire-intent-page.js
- test/e2e/specs/wp-gutenboarding-spec.js
- yarn.lock
After merging this PR, remember to also merge this PR to enable ab testing on verticals: https://github.com/Automattic/wp-calypso/pull/44256
This is a feature branch PR, including these PRs that were tested separately:
- https://github.com/Automattic/wp-calypso/pull/44655 remove domain as a step
- https://github.com/Automattic/wp-calypso/pull/44701 add vertical input
- https://github.com/Automattic/wp-calypso/pull/44822 https://github.com/Automattic/wp-calypso/pull/44837 vertical gating with `?vertical` URL arg
- https://github.com/Automattic/wp-calypso/pull/44833 enable launch flow in production and bump AB test slug
- https://github.com/Automattic/wp-calypso/pull/44837 persistent show vertical input
- https://github.com/Automattic/wp-calypso/pull/44256 A/B test for vertical
- A/B test …
> Gutenboarding: V2 Onboarding

- client/me/purchases/manage-purchase/index.jsx
- client/me/purchases/manage-purchase/notices.jsx
- client/my-sites/plans/current-plan/purchases-listing.jsx
- client/my-sites/plans/main.jsx
Note: This is a recreation of #44515; that PR was from a fork.
* Undo several changes from #36463 as we are re-allowing user cancellations and upgrades from partner-provisioned products. These purchases should still not be renewable or show price/billing period info.
`/me/purchases`:
***
`/me/purchases/:siteSlug/:purchaseId`:
***
`/plans/:siteSlug`:
***
`/plans/my-plan/:siteSlug`:
***
1. Provision a Jurassic Ninja site with a partner Jetpack plan. You can use the Jetpack Start tool in MC.
2. Visit each of this pages
* `/me/purchases`
* `/me/purchases/:siteSlug/:purchaseId`
* `/plans/:siteSlug`
* `/plans/my-plan/:siteSlug`
3. For each of these pages
* Your Partner Plan Site on Production - these should match the "Before" Screenshots
* Your Partner Plan Site on the branch - these should …
> Jetpack: Remove partner logic to allow some plan management again for partner-provisioned products

- client/my-sites/customer-home/cards/education/quick-start-video/index.jsx
This PR completes the client portion of the Quick Start video on My Home, by addressing [these comments](https://github.com/Automattic/wp-calypso/pull/44422#pullrequestreview-464991504) I missed in the [original PR](https://github.com/Automattic/wp-calypso/pull/44422#). 
* Start this branch on your machine
* Point API calls to your sandbox
* Patch your sandbox with D46859
* Confirm that API calls are hitting your sandbox
* Load My Home with a site that hasn't completed site setup (and loads the Site Setup view)
* Check your cookies to confirm that you're allocated to the 'quick-start' variant
* Confirm that the Quick Start card loads, and that inline support modal works properly when you click the video image.
> Tweaking the tracking names for the quick start video card on My Home

- apps/full-site-editing/full-site-editing-plugin/editor-gutenboarding-launch/index.ts
- client/gutenberg/editor/calypsoify-iframe.tsx
* Fix 404 on mobile when pressing _Complete Setup_
* Use _Launch_ label on mobile to prevent breaking the header layout.
* Create a site using `/new`
* Launching from editor should work for both desktop (new launch with the sidebar) and mobile (Calypso launch flow).
> Gutenboarding launch flow: fix mobile flow

- client/blocks/signup-form/index.jsx
- client/blocks/signup-form/style.scss
- client/components/domains/domain-registration-suggestion/index.jsx
- client/components/domains/domain-search-results/index.jsx
- client/components/domains/domain-suggestion/style.scss
- client/components/domains/example-domain-suggestions/style.scss
- client/components/domains/free-domain-explainer/index.jsx
- client/components/domains/free-domain-explainer/style.scss
- client/components/domains/register-domain-step/index.jsx
- client/components/domains/search-filters/style.scss
- client/components/domains/search-filters/tld-filter-bar.jsx
- client/layout/index.jsx
- client/lib/abtest/active-tests.js
- client/my-sites/plan-features/index.jsx
- client/my-sites/plans-features-main/index.jsx
- client/my-sites/plans-features-main/style.scss
- client/signup/main.jsx
- client/signup/navigation-link/index.jsx
- client/signup/reskinned-processing-screen/index.jsx
- client/signup/reskinned-processing-screen/style.scss
- client/signup/signup-header/index.jsx
- client/signup/steps/domains/index.jsx
- client/signup/steps/domains/style.scss
- client/signup/steps/user/index.jsx
- client/signup/steps/user/style.scss
- client/signup/steps/user/test/index.js
- client/signup/style.scss
This PR impldements an A/B test to show a different look of the `onboarding` signup flow to the variation group. See pau2Xa-1x4-p2 for more details.
cc @aneeshd16 
* Go to `/start/new`.
* Make sure you're assigned to `reskinned` group of `reskinSignupFlow` a/b test.
* Note: this test is intended to work only for non-EN and non-ES users. (p1596055144383000-slack-marketing-health).
* The signup flow should look as below.
> Signup: Add reskinSignupFlow a/b test

- apps/full-site-editing/full-site-editing-plugin/editor-gutenboarding-launch/index.ts
- apps/wpcom-block-editor/src/calypso/features/iframe-bridge-server.js
* Add `isNewLaunch` flag on `calypsoifyGutenberg` object to be used in editor.
* Apply patch D47997-code and follow its test plan.
* Testing instruction from #44850 still apply
> Gutenboarding launch flow: update calypsoifyGutenberg with flag 

- client/gutenberg/editor/calypsoify-iframe.tsx
Open post in new tab/window when clicking on "View Post" in publish panel & snackbar notification. See `openLinksInParentFrame()` in `iframe-bridge-server.js` for affected elements.
You can test this in local calypso. See https://github.com/Automattic/wp-calypso/issues/40061 for test instructions.
Fixes https://github.com/Automattic/wp-calypso/issues/40061
> Open post in new tab/window when clicking on "View Post" in publish panel & snackbar notification.

- client/lib/abtest/active-tests.js
- client/signup/controller.js
This PR adds a new A/B test that sends 50% the English-speaking existing users who are creating a new WordPress.com through the gutenberg-version of the onboarding experience.
How to test
=====
1. Go to  https://hash-136d7cddf698f5843f78ae2a3c839b273c9f963c.calypso.live/ and open the developer tools
2. Run this command:  `localStorage.setItem( 'ABTests', '{"existingUsersGutenbergOnboard_20200812":"gutenberg", "newSiteGutenbergOnboarding_20200811":"control"}' );` and reload the page;
3. Go to https://hash-136d7cddf698f5843f78ae2a3c839b273c9f963c.calypso.live/start
4. You should be redirected to https://hash-136d7cddf698f5843f78ae2a3c839b273c9f963c.calypso.live/new
5. Open https://hash-136d7cddf698f5843f78ae2a3c839b273c9f963c.calypso.live/start in an incognito window. You should be …
> Add gutenberg onboarding existing users test

- apps/full-site-editing/full-site-editing-plugin/full-site-editing-plugin.php
- apps/full-site-editing/full-site-editing-plugin/readme.txt
- apps/full-site-editing/package.json
* Bump WordPress.com Editing Toolkit plugin to v1.18
This change includes the changes from this PR:
https://github.com/Automattic/wp-calypso/pull/44850 (Gutenboarding launch flow: fix mobile flow)
https://github.com/Automattic/wp-calypso/pull/44855
Change log:
- Fixed a bug on mobile whereby the launch flow redirecting to `new-launch` and returning a 404 #44850
- Use _Launch_ label for the Launch button (desktop uses _Complete setup_) on mobile to prevent breaking the header layout #44850
* Apply the corresponding diff to this PR (D47993-code) and ensure that #44850 functions as expected.
Fixes #
> Bump WordPress.com Editing Toolkit plugin to v1.18

- client/components/jetpack/card/jetpack-product-card/style.scss
In the final copy, the taglines of some new products are longer than what initially thought, pushing the price on a new line in a strange way (see screenshots). This PR fixes it.
- Visit the _Plans_ page with the Offer Reset flow enabled
- Check that the tagline never takes the full width of the card, pushing the price on a new line
> Product card: prevent early price wrapping

- client/my-sites/plans-v2/controller.tsx
- client/my-sites/plans-v2/details.tsx
- client/my-sites/plans-v2/index.ts
- client/my-sites/plans-v2/plans-column/index.tsx
- client/my-sites/plans-v2/products-column/index.tsx
- client/my-sites/plans-v2/selector.tsx
- client/my-sites/plans-v2/style.scss
- client/my-sites/plans-v2/types.ts
- client/my-sites/plans-v2/upsell.tsx
- client/my-sites/plans-v2/utils.ts
* Wires up the details page, which allows users to select the plan/product subtype.
* Adds error catching for cases where the data is invalid for a given slug.
* Ensures picking a product on the selector page sends the user to the appropriate spot.
* Go to the new plans page.
* Select a product that has subtypes (Jetpack Security or Jetpack Backup).
* Verify you are directed to the details page and cards are correct products.
* Click on a product and verify you are taken to the correct upsell page.
* Alter the duration in the selector page and verify the details page has the correct duration.
* Alter a product slug in the URL and verify the details page responds correctly.
**Notes**
- Text for "Great choice! [...]" string is hard-coded and not translated as it's not clear what determines …
> Wires up details page

- client/my-sites/checkout/composite-checkout/wpcom/components/wp-checkout-order-summary.js
This hides the "live chat support" text for jetpack sites in the feature list that appears in the sidebar.
Fixes https://github.com/Automattic/wp-calypso/issues/44793
Note: in the future we should really see if we can reuse the code in `client/lib/plans/features-list.js`.
- Visit composite checkout with a plan in the cart for a simple site.
- Verify that you see "Email and live chat support" in the feature list in the sidebar.
- Visit composite checkout with a product that's not a plan (eg: just a domain) in the cart for a simple site.
- Verify that you see "Email support" in the feature list in the sidebar.
- Visit composite checkout with a plan in the cart for a Jetpack site.
- Verify that you see "Email support" in the feature list in the sidebar.
> Composite checkout: Hide "live chat" support feature item in sidebar for jetpack sites

- client/landing/gutenboarding/onboarding-block/acquire-intent/index.tsx
- client/landing/gutenboarding/onboarding-block/acquire-intent/site-title.tsx
- client/landing/gutenboarding/onboarding-block/acquire-intent/style.scss
- client/landing/gutenboarding/onboarding-block/acquire-intent/vertical-select/index.tsx
- client/landing/gutenboarding/onboarding-block/acquire-intent/vertical-select/style.scss
- test/e2e/lib/pages/gutenboarding/acquire-intent-page.js
* Remove extra vertical whitespace between site input label and site input when site input is on the next line.
* Use SkipButton & NextButton.
* Update E2E test to use SkipButton & NextButton.
* When on mobile, use "My site is called..." on the second page instead of "It's called..." to help user understand what to enter.
* Add `role=button` & styling adjustments on back and next arrow buttons for mobile.
* Remove extra spacing between acquire intent footer and acquire intent body on mobile.	
* Remove extra margin left on vertical suggestion on desktop.
* Test all of the above on `/new`.
> Gutenboarding: Some acquire intent post V2 fixes.

- test/e2e/lib/components/secure-payment-component.js
- test/e2e/lib/pages/signup/checkout-page.js
- test/e2e/specs/wp-signup-spec.js
When the e2e tests were updated to work with both old and new checkout in https://github.com/Automattic/wp-calypso/pull/43223 we never updated the `CheckOutPage` helper which is used on a few tests. Because we still have an AB Test which divides old and new checkout for non-USD currencies, those tests _sometimes_ continued to pass when they were using old checkout. 
This PR updates the `CheckOutPage` helper to handle new checkout as well as old checkout.
To do this, we had to separate out the concept of filling out the postal code and country fields that are part of the credit card form in old checkout versus the postal code and country fields that are part of the contact step in new checkout.
When running these tests locally, I always end up in old checkout, however, we can force new …
> e2e tests: Add composite checkout support to CheckOutPage helper

- client/state/selectors/is-site-checklist-complete.js
Currently if a user has not installed the mobile app the Site setup progress indicator shows as incomplete, but there is no indication why on the site home cards in some cases:
It doesn't seem like the installation of the mobile app should be considered part of site setup completion.
*  Flag the mobile app installation as true when calculating if site setup is complete.
* With a user that does not have mobile app installed, but other tasks complete, load a site homepage and see that the Setup progress bar displays as above
* Apply this patch and check that the site setup progress no longer displays
With this fix in place the 'Get the WordPress app' task still displays for the user, and can be dismissed, but the Site Setup progress indicator does not show if all other site setup tasks are …
> Site Setup: Stop the lack of mobile app setup from affecting the site setup indicator

- client/my-sites/checkout/composite-checkout/use-prepare-product-for-cart.js
The "No ads" product is old and it has an unusual product slug, `no-adverts/no-adverts.php` which is very difficult to put inside a URL since it contains URL-like elements. As a result, there is code in calypso to use the alias `no-ads` when serializing that product for renewals. In new checkout, I missed a place where that alias should have been used. This PR fixes that oversight.
Fixes https://github.com/Automattic/wp-calypso/issues/44890
- Add the "No ads" product to a site.
- Visit http://calypso.localhost:3000/me/purchases
- Click on the "No ads" product in the list.
- Click "Renew now".
- Verify that you are taken to the checkout page with the "No ads" product in your cart.
> Fix renewal of no-ads product in composite checkout

- apps/full-site-editing/full-site-editing-plugin/editor-site-launch/src/hooks/use-site.ts
- packages/data-stores/src/site/types.ts
This resolves an issue reported in p1597266153146700-slack-CRNF6A9DX CC: @ianstewart 
As a super admin, if you attempt to open the page editor for a site that you aren't a member of, it would cause a fatal error because the `plan` key isn't available on the `site` object, when checking for `is_free`.
* Check for the existence of the `plan` key on the site object before looking for the `is_free` sub-key (add optional chaining here)
* Verify that you can recreate the issue by (as a super admin) going to a site that you're not a member of, but still have access to e.g. casselstarter
* Open up the home page in the page editor
* Once the page has loaded, after a second or two, it'll throw a fatal error as in the screenshot above
* Apply the diff associated with this PR (D48052-code), and …
> In useSite add optional chaining to site?.plan as sometimes the plan key will not be available

- apps/full-site-editing/full-site-editing-plugin/full-site-editing-plugin.php
- apps/full-site-editing/full-site-editing-plugin/readme.txt
- apps/full-site-editing/package.json
This release includes only a single change (#44895)
In `editor-site-launch` add optional chaining for accessing the `plan` key on the `site` object as in some contexts the `plan` key will not be available (e.g. a super admin user accessing the editor on a site they are not a user of). Also update the type for that key to flag that it is potentially undefined.
* Bump editing toolkit plugin version, which includes: https://github.com/Automattic/wp-calypso/pull/44895
* Sandbox the diff associated with this PR (D48053-code) and double-check that the testing steps in https://github.com/Automattic/wp-calypso/pull/44895/
* If you're approving this PR, please also approve the corresponding diff 🙇‍♂️
Fixes #
> Bump WordPress.com Editing Toolkit plugin to v1.19

- client/state/sites/constants.js
This adds the site description back into the site seo preview. It was already implemented to read the `description` property of the site object as one of the sources for this, however, this `desription` was not pulled from the API and was completely missing from the object. 
I have added it to the list of fields we request from the API and now it automatically ends up in the preview.
- `yarn start`
- http://calypso.localhost:3000/view and pick a site
- once loaded, switch to the "Search & Social" preview and check if the site description aka tagline (configurable in http://calypso.localhost:3000/settings/general) is visible in previews:
| Before (WordPress.com produciton) | After (This PR) |
| - | - |
| <img width="413" alt="Screenshot 2020-08-12 at 12 17 06" …
> Fix incomplete site SEO previews

- client/components/language-picker/modal.jsx
* When using printf `%` signs need to be escaped with another `%`, thus `%%`. Because of GlotPress warnings, some languages have omitted the separate percentage sign.
> Language Switcher: Replace single percentage sign with double for printf

- client/my-sites/plans-v2/plans-column/index.tsx
- client/my-sites/plans-v2/products-column/index.tsx
Prepends _from_ to the price of a product if it has available options (i.e. Real-Time or Daily)
- Visit the _Plans_ section with the Offer Reset flow enabled.
- Check that the price of **Jetpack Backup** is prepended by _from_.
- If you want to check plans too, you'll have to run the PR locally and update `PRODUCTS_WITH_OPTIONS` in `
client/my-sites/plans-v2/constants.ts` with the plan you're testing.
> Product card: prepend price with 'from' when options available

- client/lib/abtest/active-tests.js
* For the registrationless checkout introduced in https://github.com/Automattic/wp-calypso/pull/44206, we are pausing the test. 
* Open an incognito or private browser window. Using a USA or Canada IP address in EN locale, navigate to the signup flow at https://wordpress.com/start. 
* Verify that you are not assigned to the `userlessCheckout` A/B test. In your browser console, `localstorage.ABTests` should not contain `userlessCheckout`.
> Registrationless checkout: Pause test

- client/my-sites/media/main.jsx
* Media library: only call `clearSite` action creator if filter actually changes
* Open the media library and apply a filter by clicking on _Images_ for example
* Click on _Images_ again and make sure media items aren't cleared
The following **shouldn't** happen:
discovered after merging #44790
> fix(media library): clear site only if filter actually changes

- client/landing/gutenboarding/components/domain-picker-button/index.tsx
- client/landing/gutenboarding/components/domain-picker-button/style.scss
- client/landing/gutenboarding/components/header/index.tsx
- client/landing/gutenboarding/components/header/style.scss
- client/landing/gutenboarding/onboarding-block/domains/index.tsx
- client/landing/gutenboarding/stores/onboard/selectors.ts
- client/package.json
- packages/plans-grid/src/plans-details/index.tsx
- packages/plans-grid/src/plans-table/plan-item.tsx
- yarn.lock
**Domain nudge and header updates**
* Show correct states of Domain Button with correct data fixing issues mentioned in https://github.com/Automattic/wp-calypso/pull/44655#issuecomment-671375706
* Refactor header and extract `DomainPickerButton` to load domain suggestion only after mounting the component and only if there is no selected domain. This means no more domain requests on Intent Capture step and also removing `useDebounce` dependency.
**Animation**
* Re-add loading status of domain button. 
* Re-add slide-in animation to highlight domain button until Domain Picker is used.
Demo: https://cloudup.com/c7ceOH98tvx
**Other**
* Use vertical as fallback for DomainPicker initial input value.
* Hide Plans button on Plans step and PlansModal (is causing a navigation bug).
* Go to /new
* …
> Gutenboarding: v2 improvements for header and domain search

- packages/calypso-build/CHANGELOG.md
- packages/calypso-build/package.json
Props to @scinos for compiling the list of changes.
Bump `calpyso-build` package version to 6.2.0.
> calypso-build: add missing changelog entries and publish 6.2.0

- client/my-sites/plans-v2/index.ts
- client/my-sites/plans/controller.jsx
- client/my-sites/plans/index.js
- client/my-sites/plans/test/index.js
* This alters controllers and routes to ensure that Jetpack sites get shown the Reset plans, and Simple and Atomic sites get shown the old versions.
* Load this PR and set A/B tests to show the offer reset.
* Navigate to a Simple site's plans page.
* Verify that plans page matches production.
* Repeat above two steps for Atomic sites.
* Navigate to a Jetpack site's plans page.
* Verify it matches the offer reset design.
Other paths to test:
* `/plans/yearly/:site` - Should work fine for non-JP sites, redirect to `/plans/:site` for JP sites.
* `/plans/:site/annual` - Should redirect to `/plans/:site` for non-JP sites.
* `/plans/:site/jetpack_backup/annual/details` - Should redirect to `/plans/:site` for non-JP sites.
* `/plans/:site/jetpack_backup_daily/annual/additions` - Should redirect …
> Reset: Ensure both old and new plan picker can appear

- client/lib/products-values/translations.js
* Remove extra whitespace surrounding some Jetpack product display names.
* Verify that anywhere `getJetpackProductDisplayName` is called, the resulting markup appears correct and does not have extra leading or trailing whitespace.
> Jetpack Cloud: Remove extra whitespace around Jetpack product display names

- client/my-sites/checkout/checkout/included-product-notice-content.tsx
- client/my-sites/checkout/checkout/owned-product-notice-content.tsx
* Update pre-purchase notices/warnings for Jetpack products to use their stylized "display" name instead of their plain-text product name.
* There's some extra whitespace around the product names. I'm investigating whether this is intentional, and if not, I'll create a new PR to address it.
* Attempt to check out with Jetpack Backup, for a site that has a plan with Jetpack Backup included.
* Verify that a pre-purchase notice appears, and that the product name is mentioned as **Jetpack Backup *Italic*** instead of **Jetpack Backup (Parentheses)**.
* Attempt to check out with a Jetpack plan that includes Backup, for a site that already owns Jetpack Backup individually.
* Verify that a pre-purchase notice appears, and that the product name is mentioned as **Jetpack Backup *Italic*** instead …
> Checkout: Use stylized display names for Jetpack products in notices

- client/my-sites/checkout/composite-checkout/wpcom/components/wp-checkout.js
- packages/composite-checkout/README.md
- packages/composite-checkout/src/components/checkout-steps.js
The "Pay" submit button in composite checkout is inserted by the `CheckoutStepArea` component from `@automattic/composite-checkout`. Its `disabled` status is currently controlled by two factors: the button is disabled if the active step is not the last step, or if the form status is not 'ready' (eg: loading, validating, etc.). However, the "active step" for this purpose is a step inside a `CheckoutSteps` step group, and if you manually create steps outside such a group, then it's possible for an "active step" to be hidden. For example, if you use the `areStepsActive` prop of `CheckoutSteps`, it will hide all the steps, but one of them may still be "active". The result is that the button may be enabled when it should not be enabled.
To handle this edge case, this PR adds a new optional …
> Composite checkout: Disable the submit button while the order review step is active

- client/components/language-picker/index.jsx
- client/components/language-picker/style.scss
- client/components/language-picker/test/index.jsx
The language picker used in the general settings and account settings screens is a custom dropdown. It has the word 'CHANGE' inside the box indicating it can be clicked, but as discussed in #41938 this doesn't seem necessary.
As proposed by @rickybanister we can make it look exactly like a standard dropdown, like the timezone picker just below in the general settings screen, for visual consistency.
* Matched the style of the language picker custom drop down to the style of standard drop downs (select elements), including focused and hovered states.
* The language code and subcode are now shown in one single line, instead of two lines, to allow the custom drop down to match the height of standard drop downs.
* Added a fade for long content
* In the sidebar, go to Manage > Settings
* Verify …
> Settings: simplify language picker component

- client/my-sites/checkout/checkout-system-decider.js
- client/my-sites/checkout/checkout/included-product-notice-content.tsx
- client/my-sites/checkout/checkout/jetpack-minimum-plugin-version-notice-content.jsx
- client/my-sites/checkout/checkout/owned-product-notice-content.tsx
- client/my-sites/checkout/checkout/style.scss
- client/my-sites/checkout/composite-checkout/wpcom/components/wp-checkout.js
* Add a new warning/notice to the checkout process to inform people that Jetpack Backup requires a Jetpack plugin version of at least 8.5. Sites with version 8.5 or higher will not see this message.
Fixes `1164141197617539-as-1185663038055927`.
* I've got a follow-up PR planned to make these notices more extendable and move the if-else logic into its own component.
* Create or select a site that has version 8.5+ of the Jetpack plugin, but that does not have Jetpack Backup or a plan that includes it.
* Attempt to purchase Jetpack Backup individually (any term or type) for this site.
* Verify that no minimum-version notice appears during checkout.
* Create or select a site that has a version of the Jetpack plugin prior to 8.5, but that does not have Jetpack Backup or a plan that includes …
> Checkout: Warn that Jetpack Backup requires plugin version >= 8.5

- apps/full-site-editing/full-site-editing-plugin/editor-gutenboarding-launch/index.ts
- apps/full-site-editing/full-site-editing-plugin/editor-site-launch/src/hooks/use-site.ts
- apps/full-site-editing/full-site-editing-plugin/editor-site-launch/src/launch-modal/index.tsx
- apps/full-site-editing/full-site-editing-plugin/full-site-editing-plugin.php
- apps/full-site-editing/full-site-editing-plugin/readme.txt
- apps/full-site-editing/package.json
- New version: 1.20
- Other changes included:
#44901
#44882 
* Handle save action async for the new launch flow so it won't keep the modal from opening.
* Fix possible race condition causing the site to be immediately launched when pressing _Complete Setup_ button. mentioned in https://github.com/Automattic/wp-calypso/pull/44909#pullrequestreview-466642142
* Create a site using /new
* Press Complete Setup button from editor top bar on desktop. Launch modal should open immediately
* On mobile the redirect to Calypso launch flow should be done after saving the page content
Fixes #44836
> Gutenboarding launch flow: remove delay when starting the flow

- apps/full-site-editing/full-site-editing-plugin/readme.txt
* Leftover from #44909 
> The new version (1.20) does not match the stable tag (1.19) in readme.txt.
> Version info:
Previous Version: 1.19
New Version (defined in plugin loader): 1.20
Stable Tag (defined in readme.txt): 1.19
* Same as #44838 🤦 
* Nothing to test.
> Editing toolkit: update stable tag to 1.20

- client/my-sites/checkout/checkout-system-decider.js
* Fix some faulty logic: when determining whether to show the "minimum plugin version" notice for Jetpack Backup, look at the current product in the cart instead of the selected site's purchased products.
* See instructions for #44886.
> Checkout: Look at product in cart for Jetpack Backup min-version check

- client/lib/cart-values/cart-items.js
- client/my-sites/checkout/composite-checkout/wpcom/components/wp-contact-form-summary.js
When a cart is only renewals, we do not show the domain contact fields (see https://github.com/Automattic/wp-calypso/pull/44533), but we still show those fields in the summary if they have been previously filled-out. This, however, is poor UX since those fields cannot be edited.
In this PR, we hide the domain contact details from the summary (the completed step) if the cart is only renewals.
Fixes https://github.com/Automattic/wp-calypso/issues/44867
Only postal code and country (renewal or plan):
Full contact details (non-renewal domain):
G Suite only details:
- Visit checkout with just a domain renewal in your cart.
- Verify that the contact details step summary shows only postal code and country.
- Visit checkout with just a plan in your cart.
- Verify that the contact details step …
> Composite checkout: Hide domain contact details summary for renewals

- client/components/jetpack/card/jetpack-plan-card/fixture/index.ts
- client/components/jetpack/card/jetpack-plan-card/style.scss
- client/components/jetpack/card/jetpack-product-card/index.tsx
I misinterpreted how product cards for legacy plans should be styled. Instead of all of them being yellow, they should take the colour of the corresponding icon.
- I added the code for the Free plan, though it's never shown in the _Plans_ page.
- Make sure the offer reset flow is enabled
- Visit the _Plans_ page with a Personal, Premium, and Professional plan successively (you can easily change plans in the store admin)
- For each plan, check that the coloured line has the same colour than the icon background
> Product card: update colours of legacy plans cards

- client/components/jetpack/card/jetpack-plan-card/style.scss
- client/components/jetpack/card/jetpack-product-card/index.tsx
- client/components/jetpack/card/jetpack-product-card/style.scss
- client/my-sites/plans-v2/constants.ts
- client/my-sites/plans-v2/plans-column/index.tsx
- client/my-sites/plans-v2/products-column/index.tsx
- client/my-sites/plans-v2/utils.ts
This PR adds the logic to build the button and badge labels of the product card.
Visit the _Plans_ page with the Offer Reset flow enabled.
- If you own a plan, the label should be "Manage Plan"
- If you own a product, the label should be "Manage Subscription"
- If you own a plan, the label should be "Your plan"
- If you own a product, the label should be "You own this"
- If a product is included in a plan you own, the label should be "Included in your plan"
> Product card: add logic to build labels

- client/landing/gutenboarding/onboarding-block/style-preview/preview.tsx
- client/landing/gutenboarding/stores/onboard/actions.ts
- config/development.json
- config/production.json
- packages/data-stores/src/site/types.ts
* Adds `gutenboarding/use_pattern` config setting. 
* Updates demo preview and create site params to use the setting to determine whether to switch on pattern api use.
* Apply D46797-code
* Temporarily enable the config with: [?flags=gutenboarding/use-patterns](http://calypso.localhost:3000/new/ko?flags=gutenboarding/use-patterns)
Fixes #43714
> Gutenboarding: Add use-patterns endpoint params

- client/me/concierge/shared/primary-header.js
- client/me/help/contact-form-notice/chat-covid-limited-availability.jsx
- client/me/help/contact-form-notice/chat-generic-closure.jsx
- client/me/help/contact-form-notice/chat-holiday-closure.jsx
- client/me/help/contact-form-notice/chat-reduced-availability.jsx
- client/me/help/contact-form-notice/index.jsx
- client/me/help/help-contact/index.jsx
Primary purpose: Add a few more general-purpose notices we can put on the Contact page in case we need to close chat or know our coverage won't be up to standards (for various reasons). I'm putting these up without being used yet, so that translations can be completed on them by the time we do need them.
Also done in this PR:
- Removes an expired notice from Quick Start
- Renames a few existing notices
- Makes `hideAt` optional for `ContactFormNotice`
- Updates the `isUserAffectedByLiveChatClosure` to hide Upwork as well (I missed this when I added that new support type)
Drop both notices [into the contact widget](https://github.com/Automattic/wp-calypso/blob/master/client/me/help/help-contact/index.jsx#L598), try both with and without `endsAt` params, and adjust your computer clock to …
> Support: Add generic chat closure notices

- client/landing/gutenboarding/style.scss
- client/login/wp-login/style.scss
- packages/onboarding/styles/mixins.scss
- packages/typography/README.md
Make use of the Recoleta font declaration in the @automattic/typography package
https://github.com/Automattic/wp-calypso/issues/44683
Background/Related:
p9Jlb4-1vU-pe#comment-2683
* Remove @font-face declarations in `wp-calypso/client/login/wp-login/style.scss` &
`client/landing/gutenboarding/style.scss`  and instead `@import` the typography package.
* ~Replace font variable with `@extend` in `packages/onboarding/styles/mixins.scss`~. See sass error posted below.
* Update the package README with usage instructions
* Ensure code changes are the desired font implementation
* Review areas of site affected by code changes to ensure Recoleta font is unchanged:
- /new
- /log-in/new
Fixes  https://github.com/Automattic/wp-calypso/issues/44683
> Recoleta font usage: source from typography package

- apps/full-site-editing/full-site-editing-plugin/editor-site-launch/src/launch-steps/final-step/styles.scss
- packages/plans-grid/src/plans-table/style.scss
* Use green-40 and orange-40 color studio variables where needed.
* Correct colors should appear for the cross / warning and checkmarks on Plans Grid and summary step of the Site setup flow.
> Gutenboarding: use color studio variables

- client/state/data-layer/wpcom/activity-log/update-credentials/index.js
#44737 adds a “message” property to calypso_rewind_creds_update_failure events, but “message” is on a blocklist for implementation reasons (see morphlines_master.conf in Automattic/nosara). This pull request renames the property to “error_message”.
1. Follow the testing instructions at #44737
2. Go to Tracks’ live view for calypso_rewind_creds_update_failure
3. Verify that your event has .eventprops.error_message
> Fix new property name in calypso_rewind_creds_update_failure

- client/components/jetpack/card/jetpack-product-card/index.tsx
This PR removes the features section in the product card when no feature is passed, in which case an annoying bottom padding appears. This should not be the case once the final copy is integrated, but it's an easy and quick fix.
- Visit the _Plans_ page
- Check that the cards don't have an odd bottom padding
> Product card: remove features section when no features

- apps/full-site-editing/full-site-editing-plugin/block-patterns/class-block-patterns.php
* Check the columns category is currently registered before calling unregister
```
PHP Notice:  WP_Block_Pattern_Categories_Registry::unregister was called <strong>incorrectly</strong>...
...Notice: WP_Block_Pattern_Categories_Registry::unregister was called <strong>incorrectly</strong>. Block pattern category "columns" not found...
```
For context, before applying the diff:
* Open the block editor on a simple site
* Take a look at the block patterns (click the (+) inserter button and switch to the patterns tab)
* Scroll down the list of patterns and see the COLUMNS heading, the purpose of the line that's causing this warning was to remove that category but it's stopped working for some reason.
Testing the warning has been fixed:
* Check out code and `npx wp-env start`
* Go to …
> Only call unregister on the columns category if currently registered

- client/my-sites/plans-v2/utils.ts
* This fixes a bug introduced in #44754 that used `context` instead of `comment`.
* Review code and ensure expected tests pass.
Ref: p1596898671053300-slack-C02AED43D
> Changes translation to use comment instead of context

- client/lib/abtest/active-tests.js
- client/my-sites/checkout/checkout-system-decider.js
- test/e2e/lib/components/secure-payment-component.js
- test/e2e/lib/pages/domain-map-checkout-page.js
- test/e2e/lib/pages/signup/checkout-page.js
- test/e2e/specs/wp-manage-domains-spec.js
- test/e2e/specs/wp-signup-spec.js
This removes the `showCompositeCheckoutI18N` abtest which was still segmenting a few i18n users to our old checkout flow. That test is long since complete so we can disable this now.
Fixes https://github.com/Automattic/wp-calypso/issues/44868
Visit checkout with a non-USD and/or non-EN account and be sure that you see new checkout.
> Remove showCompositeCheckoutI18N abtest

- client/blocks/inline-help/inline-help-search-results.jsx
- client/blocks/inline-help/style.scss
- client/package.json
Removes the aria-live region in order to make spoken announcements more concise and timely.
*This gif is edited to not take up as much bandwidth*
* Removes aria-live region
* Adds `@wordpress/a11y` package
* Uses `speak()` for search announcements
* Turn on a screen reader, such as VoiceOver (ask siri to turn on VoiceOver or Command + F5)
* Open up Safari (if using VoiceOver)
* Enter a search result that will return results
* A little after the results are loaded, you should hear "Search results loaded."
* If the results are taking awhile to return, you should hear "Loading search results." The loading message only appears on longer running searches and should not announce otherwise.
* Enter a search that will not return results from the API, such as "asdfkasdfjlaskdf"
* After 1.5s, you …
> Use speak for inline help with more concise announcements

- client/my-sites/plans-v2/plans-column/index.tsx
There was a deprecated prop (ironically, `deprecated`) passed to `CardComponent` in `client/my-sites/plans-v2/plans-column/index.tsx`. It must have been left here in a conflict solving.
Check in the code that `JetpackProductCard` doesn't take any `deprecated` prop anymore
> Remove unused prop passed to CardComponent in the plans page

- .stylelintrc
* Update stylelintrc with rem units and values corresponding to the new variables.
* Stylelint scales does not lint for Sass variable names, but this will still be useful to catch the use of ems or px or values outside the given scale. It's a step in the right direction.
* Also noted stylelint scales does not output the desired units in the error message if both values (scale and unit) are incorrect; only if the value is correct but the unit is not. I may open a ticket with them to suggest including that information since it could be useful (the difference between `.75px` and `.75rem` is pretty big. :D) 
**Visual output example**
* Switch to this PR and run `yarn build`
* Update a SCSS file with a `font-size` value you know to be outside the above scale (ie. `font-size: 18px`)
* Try to …
> Typography: Update stylelintrc to include correct font size rem values

- apps/full-site-editing/full-site-editing-plugin/common/index.php
_Note: this patch was applied directly to wpcom in our wpcom gutenberg loader files in D47818-code. This additionally makes the patch available for atomic sites. Once deployed, we can remove the existing wpcom patch._
Always enable the custom line-height setting. This overrides the default Gutenberg setting, which is to rely on theme support. We need this so that existing users on our wpcom simple and atomic infrastructure do not loose functionality when upgrading to the latest Gutenberg version.
1. on a test Atomic site with the latest version of the gutenberg plugin, you will not see line-height settings in the block sidebar.
2. With this update also applied, you will see line-height settings.
> Toolkit plugin: Always enable line-height in Gutenberg settings

- client/state/selectors/get-account-closure-sites.js
- client/state/selectors/test/get-account-closure-sites.js
This is an issue from #37505 which I only realised now: if you're a person who has been invited to be an administrator on a site, the Account Closure screen indicates that site will be instantly deleted as soon as your account is closed. In reality, this is not the case; that site would only be deleted if the owner closed their account. 
On a test account, invite yourself as an administrator of a site. On the Account Closure sites list, verify that the list no longer shows the site you are an administrator (but not an owner) on. 
Not sure how people feel about using `activate_wordads` for something that very clearly isn't related to WordAds, especially since the capability to activate WordAds could change in the future. However, it currently works and it's the only capability that does …
> Account Closure: Convey that Only the Owner's Site is Deleted

- client/lib/abtest/active-tests.js
- client/signup/controller.js
There's a race condition that allows users that have been allocated to the variant of the `existingUsersGutenbergOnboard` to end experiencing control instead because being allocated to a different test downstream. They shouldn't ever get to the point that allocation happens, but a `return;` was missing.
> A/b test: Fix race condition

- client/components/data/media-list-data/index.jsx
- client/lib/media/list-store.js
- client/lib/media/store.js
- client/lib/media/test/list-store.js
- client/lib/media/test/store.js
- client/state/data-layer/wpcom/sites/media/index.js
- client/state/media/reducer.js
- client/state/selectors/get-current-media-query.js
- client/state/selectors/get-next-page-handle.js
- client/state/selectors/get-next-page-query.js
- client/state/selectors/has-next-media-page.js
- client/state/selectors/test/get-next-page-handle.js
- client/state/selectors/test/get-next-page-query.js
- client/state/selectors/test/has-next-media-page.js
* Replace usages of `MediaListStore.hasNextPage` with the `hasNextMediaPage` selector
* Open the media library with enough media items to scroll through multiple pages using site media, google photos, and pexels.
* Ensure that you can scroll to the final page (compare with staging) of each one.
Note: There is a bug with pexels where if you get to the last page (you can do this easily by searching "blue car" and there are only a handful of results if you scroll far enough) where the final placeholder will always exist. I think this is because we can't necessarily currently tell when there is no next page for pexels. This is present in production so not something introduced by these changes.
Part of https://github.com/Automattic/wp-calypso/issues/43663
> Media: Use hasNextMediaPage selector

- client/my-sites/plans-v2/constants.ts
- client/my-sites/plans-v2/plan-renewal-notice/index.tsx
- client/my-sites/plans-v2/utils.ts
Some elements of the UI, such the expiry notice, show a different content whether or not the customer is eligible to renew their Jetpack legacy plan at the old rate. The eligibility logic was temporarily implemented in the frontend, but is now delegated to the backend. This PR reflects this change.
The `/purchase` endpoint returns a `isRenewable`, the value of which can be used directly to determine the eligibility.
I don't think it's possible to currently test that without editing the code locally. You'll need to update the return value of `isRenewable` in `client/lib/purchases/index.js`.
- Select a self-hosted Jetpack site with a legacy plan (Personal, Premium, or Professional)
- Visit the Plans section with the offer reset flow enabled
- Check that you see your plan in the plan column …
> Update logic to decide if customer can renew at old rate

- apps/full-site-editing/full-site-editing-plugin/editor-site-launch/src/hooks/use-on-launch.ts
- client/my-sites/checkout/checkout/index.jsx
- client/signup/config/flows.js
* Ensure gutenboarding checkout always lands in customer home.
**Setup** 
* For **old checkout**, set `"old-checkout-force": true` in `development.json` and run `yarn start`.
* Alternatively, you can add `return 'old-checkout';` on `getCheckoutVariant()` function in `checkout-system-decider.js` to avoid restarting yarn.
* For **composite checkout**, set `"composite-checkout-force": true` in `development.json` and run `yarn start`.
* Alternatively, you can add `return 'composite-checkout';` on `getCheckoutVariant()` function in `checkout-system-decider.js` to avoid restarting yarn.
* Go to `apps/full-site-editing` and run `yarn dev --sync`.
**Test twice, once with Old Checkout, once with Composite Checkout**
* Go through the `calypso.localhost:3000/new` flow.
* Be sure to choose Free plan …
> Gutenboarding: Ensure checkout always lands in customer home.

- client/my-sites/plugins/plugin-site-jetpack/style.scss
* It appears that the styling for the "Available Sites" section on Plugins is being overriden sometimes, but that often results in the page looking pretty broken. This just reworks the styling to what it was before (at least what it was in #39020), which is probably better. 
Visit `/plugins/under-construction-page` (or any slug - ideally one which you haven't installed and one which you have) and scroll to the bottom. 
**Before:**
**After - effectively reverting to what it was before:**
cc @sixhours, @arunsathiya 
Fixes #42400
> Plugins: Fix Styling for "Available Sites"

- client/my-sites/checkout/checkout-system-decider.js
This removes the gating that prevented Jetpack sites and purchases to use new ("composite") checkout in production. (Previously this was available in all non-production environments.)
This also removes the gating that only allowed specific product slugs in the url to end up in new checkout, since all products should now be supported.
There should be no obvious change when testing since non-production environments already had this available. Still, it's worth testing the gating:
- Visit checkout for a jetpack site.
- Verify that you see new checkout.
Fixes https://github.com/Automattic/wp-calypso/issues/44800
> Allow jetpack sites/purchases to access composite checkout

- client/my-sites/customer-home/cards/tasks/site-setup-list/style.scss
Fixes the `.nav-item` styles for Safari, so the button rendered does not apply the margin and color provided by default in Safari.
Before | After
--- | ---
* Go to  `/start` and create a new site.
* Check the Site setup list in My Home.
* Make sure the navigation items look like the after screenshot above in all browsers (the issue was specific to Safari).
Fixes https://github.com/Automattic/wp-calypso/issues/42369
> Site setup list: Fix nav item styles for Safari

- apps/full-site-editing/full-site-editing-plugin/full-site-editing-plugin.php
- apps/full-site-editing/full-site-editing-plugin/readme.txt
- apps/full-site-editing/package.json
This release's changelog is:
* Site setup: Redirect to user's home after checkout. For both composite and old checkouts. And for simple and atomic (e-commerce) sites. See (https://github.com/Automattic/wp-calypso/pull/44881).
* Block patterns: Only call unregister on the columns category if currently registered. See (https://github.com/Automattic/wp-calypso/pull/44903)
* Block editor: Always enable line-height in Gutenberg settings. See (https://github.com/Automattic/wp-calypso/pull/44772)
Other included PRs:
- https://github.com/Automattic/wp-calypso/pull/44935
> Bump WordPress.com Editing Toolkit plugin to v1.21

- client/components/jetpack/card/jetpack-product-card/index.tsx
- client/my-sites/plans-v2/constants.ts
- client/my-sites/plans-v2/details.tsx
- client/my-sites/plans-v2/plans-column/index.tsx
- client/my-sites/plans-v2/product-card/index.tsx
- client/my-sites/plans-v2/products-column/index.tsx
- client/my-sites/plans-v2/selector.tsx
- client/my-sites/plans-v2/types.ts
- client/my-sites/plans-v2/use-item-price.ts
- client/my-sites/plans-v2/utils.ts
- client/my-sites/plans/controller.jsx
* This extracts repeated code for wiring `SelectorProduct` data to cards into a new component, `ProductCard`.
* Logic around whether a given item is owned is extracted into the new component.
* Code review.
* Do regression testing on the new plans page.
Fixes 1169247016322522-as-1188698065630107
> Consolidates wiring for Jetpack product cards

- client/sections.js
* Remove the `enabledLoggedOut` attribute from the `/backup` and `/scan` sections in Calypso, so that users are required to log in before seeing those pages.
Fixes `1164141197617539-as-1188931267678623`.
NOTE: Because this pull request affects server code, you must restart any running instances of Calypso to test.
* From a private browsing window, attempt to access `calypso.localhost:3000/backup` and `calypso.localhost:3000/scan`.
* Verify that going to either route results in a redirect to the login page. (Previous behavior showed an empty site selector with no option to go elsewhere.)
> Jetpack Cloud: Require users to log in to reach /backup and /scan routes

- desktop/bin/validate_tag.js
Fixes an import path used in the release tag validation script.
> desktop: fix package import path for tag validation

- client/blocks/reader-post-card/style.scss
- client/blocks/reader-post-options-menu/style.scss
- client/blocks/reader-share/index.jsx
- client/blocks/reader-share/style.scss
As reported in #44417, users couldn't set the focus on the share button of Reader's posts using the Tab key, and couldn't open the share popup menu when pressing the Enter key.
The ellipsis button that opens the post options was working as expected (it could be focused and opened the options menu when pressing the Enter key), so I took `ReaderPostOptionsMenu` component as an example to follow, for fixing this issue.
* Changed the markup of the `ReaderShare` component to use a `button` element instead of a `span`. Used the `Button` component from `@automattic/components`.
* Took advantage of `accessible-focus` module to style the button when focused.
* Removed the reset on `box-shadow` in `ReaderPostOptionsMenu` so both the share post button and the post options button look the same when …
> Reader: Allow opening the share popup menu with the keyboard

- test/e2e/lib/gutenberg/gutenberg-editor-component.js
- test/e2e/lib/pages/cancel-domain-page.js
- test/e2e/lib/pages/domain-details-page.js
- test/e2e/specs/wp-signup-spec.js
* This PR fixes some broken e2e tests. 
- Somewhere along the way, there was a change made to closing the Gutenberg editor and it caused one test to break
- The flow to canceling a domain only plan changed so I updated and made sure the cleanup was working. 
* Ensure e2e tests pass
> e2e: Fixing some broken tests

- client/my-sites/checkout/checkout/payment-box.jsx
- client/my-sites/checkout/checkout/prepurchase-notices/style.scss
* Remove duplicated nested Notice boxes.
* On WordPress.com (do not run this PR yet), go to the checkout page with any product in the cart.
* Verify that you see an empty Notice box.
* On a site that has Jetpack Backup or a plan that includes it, visit `https://wordpress.com/checkout/:site/jetpack_backup_daily`.
* Verify that you see a nested Notice box.
* Run this PR.
* Go to the checkout page with any product in the cart.
* Verify that you don't see an empty Notice box.
* On a site that has Jetpack Backup or a plan that includes it, visit `https://calypso.localhost:3000/checkout/:site/jetpack_backup_daily`.
* Verify that you don't see a nested Notice box. You should only see one conflict Notice box.
Fixes 1169247016322522-as-1189567814793697
> Fix: remove duplicated Notice wrapper

- client/lib/cart-values/cart-items.js
* In #44954 I allowed users add multiple Jetpack products to the cart at the same time. Here I'm making that work only when the Offer Reset AB experiment is on because we don't want to inadvertently cause troubles to users or support.
* Run this PR.
* Make sure the Offer Reset AB experiment is off.
* Try to add more than one Jetpack product to the cart.
* Verify that is not possible to add more than one Jetpack product to the cart.
* Enable the Offer Reset AB experiment.
* Try to add more than one Jetpack product to the cart.
* Verify that is possible to add more than one Jetpack product to the cart.
> Offer Reset: allow multiple products only when in Offer Reset

- client/jetpack-connect/controller.js
- client/jetpack-connect/index.js
- client/jetpack-connect/store-header.tsx
- client/jetpack-connect/style.scss
- client/my-sites/plans-v2/controller.tsx
- client/my-sites/plans-v2/details.tsx
- client/my-sites/plans-v2/plans-header.tsx
- client/my-sites/plans-v2/selector.tsx
- client/my-sites/plans-v2/types.ts
- client/my-sites/plans-v2/upsell.tsx
- client/my-sites/plans/controller.jsx
* Moves new Jetpack plan design to Jetpack Connect.
**Notes**
- Currently locale cannot be set. A ticket will be made to rectify this.
- This is a best-guess design, and will need further iteration. Mobile has not been tested.
- Checkout does not work yet, as that will need logic to be pulled out like the header.
- The Free option is not visible yet. That will also be added in a later iteration.
* Enable A/B test for Offer Reset.
* Navigate to /jetpack/connect/store.
* Verify Offer Reset appears and works (with caveats above).
* Navigate to /jetpack/connect/plans/[site].
* Verify Offer Reset appears and works (with same caveats).
Fixes 1169247016322522-as-1189391103463219.
> Adds new Jetpack plans to Jetpack Connect

- client/my-sites/checkout/composite-checkout/components/wp-order-review-line-items.js
- client/my-sites/checkout/composite-checkout/composite-checkout.js
* When you have a plan and domain in cart, and then try to remove the plan item, the following message is shown:
```
When you press Continue, we will remove your plan from the cart and your site will continue to run with its current plan. Since your other product(s) depend on your plan to be purchased, they will also be removed from the cart and we will take you back to your site.
```
This messaging is not entirely correct, because PWPO users can remove the plan and still purchase only a domain. Also, removing the plan will not remove the domain item from cart and also does not redirect back to site.
* This PR checks if the user has PWPO flag enabled, and then removes the incorrect lines from the messaging. So now, the modal copy will look like this:
* On a free plan site, add a domain …
> Checkout: Remove cart message for PWPO users

- client/layout/index.jsx
- client/signup/main.jsx
The signup reskin (#44223) introduced a change in which the the entire signup state was downloaded & executed on almost all the pages. This change reverts the changes to the `layout/index.jsx`. However, it also introduced an issue where the `is-white-signup` class was not applied to the body element on refreshing the page. This change also fixes it.
* Make sure you're assigned to reskinned group of reskinSignupFlow a/b test. Note: this test is intended to work only for non-EN and non-ES users.
* The signup screens should look like the ones in the description of #44223.
* Refreshing the page on any of the steps should not change the design on the page.
cc: @sgomes
> Removes signup state from the main layout

- client/signup/main.jsx
- client/state/initial-state.js
In https://github.com/Automattic/wp-calypso/pull/44106, we restored persisted `signup` state tree after a user logged into Calypso so they can continue a signup process. However, part of the signup state tree is `progress`. It contains the various steps of the signup process, like `domains` or `user`. The `user` step only makes sense to be inside `progress` if we are creating a new user (like filling out the user form) or when the form is processing (being saved to the server).
When we log in to an unfinished signup flow which had the `user` step, I don't think it makes sense to preserve it and load it to the logged-in session. Let's remove it from the cached state before loading it. We also need to remove the `user` step because otherwise the `SignupFlowController` will reset the whole …
> Signup: remove persisted 'user' step after logging in

- apps/wpcom-block-editor/src/utils.js
- apps/wpcom-block-editor/src/wpcom/features/tracking/track-record-event.js
Sub PR of https://github.com/Automattic/wp-calypso/pull/41329. Accompanying diff D48009-code.
⚠️ **Note**: this PR contains the changes are to the _src_ files for the WPcom Editor. Therefore you will need to test against the built files which are in the accompanying diff D48009-code. The built files are what needs to be deployed to Dotcom Simple and they need to be generated from the Circle CI builds as per the FG.
These changes prepare the ground for introducing e2e tests that assert that certain tracking events are being fired within the Block Editor.
We add a "events stack" array on e2e envs only in order that the tests can assert that events are being fired. For the reasoning behind _why_ we need to introduce a stack like this please see [the parent …
> Adds tracking events stack to wpcom editor on e2e test envs only

- client/landing/gutenboarding/components/domain-picker-button/index.tsx
- client/landing/gutenboarding/components/domain-picker-button/style.scss
* As a follow up of #44983, re-enable slide-in animation of domain picker button if a site title has been entered and domain step was skipped. The animation has been re-introduced recently in #44864 
* Animation should run only the first time when going through the flow. Once a domain or a design is selected, animation is disabled.
* Go to [/new](https://calypso.live/new?branch=update/gutenboarding-domain-picker-slide-in)
* Enter a site title and advance.
* Skip domain selection step.
* After landing on design selection step, the domain picker button containing a suggestion derived from the site title should appear with a sliding animation.
Demo: https://cloudup.com/cZkTE_ONHE8
> Gutenboarding: re-enable domain picker button animation

- packages/plans-grid/src/plans-table/plan-item.tsx
- packages/plans-grid/src/plans-table/style.scss
When included in the Site setup flow, the free sub-domain is displayed in the plan column instead of a static text and this cause it to overflow because of the length.
* Prevent longer domain name overflowing from a plan column.
* When reaching the Plans step with a longer domain name selected, it should be wrapped at the end of the line.
* Everything else on the PlansGrid should stay the same. Static texts should be wrapped without breaking words.
**Before**
**After**
> PlansGrid: fix domain name overflowing from plan column

- client/lib/abtest/active-tests.js
- client/signup/controller.js
* update existingUsersGutenbergOnboard to target country codes 'US' and 'CA'.
* update datestamp
Check instructions from #44858 but with the updated test slugs:
`existingUsersGutenbergOnboard_20200812` => `existingUsersGutenbergOnboard_20200819`
`newSiteGutenbergOnboarding_20200811` => `newSiteGutenbergOnboarding_20200818`
> Gutenboarding: update existing users test

- client/blocks/inline-help/inline-help-search-results.jsx
- test/e2e/lib/components/support-search-component.js
- test/e2e/specs/wp-inline-help-support-search-spec.js
- test/e2e/specs/wp-my-home-support-search-spec.js
When we added the [admin section search results](https://github.com/Automattic/wp-calypso/pull/43862), we didn't update the e2e tests to account for them. This PR checks for the admin search results section as well as adds more assertions over what should and not be present at different times.
* Boot Calypso from the project root `yarn && yarn start`.
* Set-up e2e testing for Calypso
* `cd test/e2e`
* `yarn`
* `./node_modules/.bin/mocha specs/wp-inline-help-support-search-spec.js` <-- All should pass
* `./node_modules/.bin/mocha specs/wp-my-home-support-search-spec.js`<--- All should pass
* Manual for the `aria-label`: Go to https://calypso.live/?branch=add/admin-search-e2e
* Click "My Home"
* Inspect the search card component "results" and see the `aria-label` for the results says …
> Inline Help: Add e2e tests for inline help admin section

- client/lib/abtest/active-tests.js
* Changes the datestamp so that users are not assigned to either control or variant.
* Using private browsing mode, go to https://wordpress.com/start using a non EN/ES locale. You should not be assigned to the `reskinSignupFlow` abtest.
* `localstorage.ABTests` should not contain`reskinSignupFlow`.
> Pauses the reskin signup flow abtest

- bin/build-languages.js
It's no longer needed to remove the leading `packages/` path from the module reference, since Calypso has switched from `i18n-calypso` to `wp-babel-makepot` for string extraction as strings are currently being extracted with their full reference path.
* Remove `packages/` string replacement in `getModuleReference` of the build-languages script.
* Build Calypso locally and search for a translatable string from `packages/**` (e.g. `Pick a payment method`)  in the translation chunks output directory `public/evergreen/languages` and confirm it's included in the generated translation chunks. 
* Test calypso.live build with `?useTranslationChunks` flag and confirm it's now showing translations for strings that were previously rendered untranslated. E.g. **Pick a payment method** on …
> i18n: Fix module reference rewrite for building translation chunks

- client/gutenberg/editor/calypsoify-iframe.tsx
- client/gutenberg/editor/style.scss
This technically affects any iframed Block Editor, but since the _Post Editor_ uses custom previews, this is only testable with the _Site Editor_.
* Stop initializing the iframed Block Editor with `display: none`.
Gutenberg's own previews use the [`useResizeCanvas`](https://github.com/WordPress/gutenberg/blob/823e5d7dd2d319fea68cc7ca4480abb2fb7f5a33/packages/block-editor/src/components/use-resize-canvas/index.js) hook, which initializes the screen's `actualWidth` with `window.innerWidth`.
This hook is used to determine the visual editor size, so it's triggered very early during the first load, which works well in most cases.
The iframe complicates things, as the `window.innerWidth` doesn't refer to the browser anymore, but to the iframe element itself.
We used to [initialize the iframe …
> Block Editor: Stop initializing the iframe with `display: none`

- packages/social-previews/src/facebook-preview/index.jsx
- packages/social-previews/src/facebook-preview/style.scss
This PR aims to bring the Facebook Preview of Social Previews in line with the current look of Facebook's preview.
The related issue is https://github.com/Automattic/wp-calypso/issues/44799
**Website - Facebook Sharing Debugger**
**Website - Facebook Social Preview**
|Before|After|
|-|-|
| <img width="553" alt="Screenshot 2020-08-19 at 16 31 48" src="https://user-images.githubusercontent.com/1562646/90648591-04849600-e23a-11ea-853b-947b2bac0f64.png"> | <img width="591" alt="Screenshot 2020-08-19 at 16 29 26" src="https://user-images.githubusercontent.com/1562646/90648666-1b2aed00-e23a-11ea-8eba-23166923f777.png"> |
---
**Article - Facebook Sharing Debugger**
**Article - Facebook Social Preview**
|Before|After|
|-|-|
| ![Screenshot 2020-08-19 at 16 32 …
> Social Previews: update Facebook preview to reflect current look

- client/landing/gutenboarding/components/header/index.tsx
- client/landing/gutenboarding/gutenboard.tsx
- client/landing/gutenboarding/hooks/use-step-navigation.ts
- client/landing/gutenboarding/onboarding-block/edit.tsx
- client/landing/gutenboarding/onboarding-block/plans/index.tsx
- client/landing/gutenboarding/path.ts
- client/landing/gutenboarding/stores/onboard/actions.ts
- client/landing/gutenboarding/stores/onboard/index.ts
- client/landing/gutenboarding/stores/onboard/reducer.ts
- packages/plans-grid/src/plans-grid/index.tsx
- Add `isExperimental` property to Onboard store and enable it using `?latest` query param.
- Enable feature picker as experimental feature in development using feature flag.
- Pass `singleColumn` placeholder prop to PlansGrid preparing for #44201
* go to `/new?latest` on localhost
* feature picker step should appear after style preview
Fixes #44981
> Gutenboarding: enable experimental features

- client/signup/config/flows.js
In this PR, we remove the `P2Details` step if you are already logged in and you go to `/start/p2`
Log in and navigate to `/start/p2`. You should see only the first step where you fill in the site and then the Hooray screen.
Log out and do the same. You should see the `P2Details` step.
Also, try a completely different flow than the p2 one to see if it works as before.
> P2 signup: remove P2Details step if logged in

- client/lib/plans/constants.js
- client/lib/plans/features-list.js
- client/lib/plans/plans-list.js
- client/my-sites/plans-v2/constants.ts
- client/my-sites/plans-v2/style.scss
- client/my-sites/plans-v2/utils.ts
This PR includes the final copy for the Jetpack Security, Security _Daily_, and Security _Real-time_ product cards.
Jetpack Complete was handled in https://github.com/Automattic/wp-calypso/pull/45009.
I did some refactoring in `client/my-sites/plans-v2/utils.ts` to handle Jetpack Security that's not a plan, codewise. The diff is hard to read, check the file instead.
_Note: Missing icons will be added in a separate PR._
- Check the copy of the Jetpack Security product card against the copydeck
- Don't forget to check the descriptions and links in the tooltips
- Click on "Get Jetpack Security"
- Check the copy of the Security _Daily_ and _Real-time_ cards against the copydeck
Security
Security options
> Update copy for plans product cards

- test/e2e/specs/wp-inline-help-support-search-spec.js
- test/e2e/specs/wp-my-home-support-search-spec.js
Fixes e2e test failures (likely introduced in https://github.com/Automattic/wp-calypso/pull/44976) due to missing `.inline-help` selector. The error manifests as:
> Timed out waiting for element with css selector of '.inline-help' to be present and displayed
> Wait timed out after 22189ms
> TimeoutError: Timed out waiting for element with css selector of '.inline-help' to be present and displayed
> Wait timed out after 22189ms
Here is [an example of a failing e2e test](https://app.circleci.com/pipelines/github/Automattic/wp-e2e-tests-for-branches/35245/workflows/acf73858-1a9f-40ef-a175-9dc6bdd5c8ec/jobs/95469/tests).
The error was caused by not actually _selecting_ a page when logging in to the site. This is because the test was using `loginFlow.loginAndSelectMySite();` which doesn't …
> Fix failing inline help e2e tests

- test/e2e/specs/wp-post-editor-spec.js
* This PR will make it so that when the e2e tests can't find the tweet in the twitter feed, rather than fail the test it alerts in Slack. This will keep things from failing from an outside dependency
* ensure e2e tests pass
> e2e: Slack message when tweet doesn't show up

- apps/full-site-editing/full-site-editing-plugin/premium-content/premium-content.php
This PR changes the hook used to load the assets files for the premium blocks plugin.
It is not possible to hook a function when the app (block editor) registers the block, at least when the code lives in Jetpack.
```es6
const extendPremiumBlock = ( settings, name ) => {
// `premium-content` has registered before to this hook :-(
};
addFilter(
'blocks.registerBlockType',
'jetpack/extend-premium-content-block',
extendPremiumBlock
);
```
Changing the hook from `init` to `enqueue_block_editor_assets` fixes this issue. And also, in the end, [enqueue_block_editor_assets](https://developer.wordpress.org/reference/hooks/enqueue_block_editor_assets/) is the proper hook to use when we want to add these assets files.
Nothing should change after applying these modifications in terms of …
> Premium Content: load assets using proper hook

- packages/social-previews/src/search-preview/index.jsx
- packages/social-previews/src/search-preview/style.scss
- packages/social-previews/test/index.js
This PR aims to bring the Google Search Preview of Social Previews more in line with the current look of Google Search's preview.
Note: This goal here is to improve on what we currently have, rather than having a perfect representation of the final Google Search result. The preview is meant as an approximation of what the Google Search result will look like. The breadcrumb will differ for example. There are a lot of different variables that influence the URL breadcrumb. We're not replicating that complexity here but go for a simple approach of splitting the URL at each `/`. 
The related issue is https://github.com/Automattic/wp-calypso/issues/44799.
**Google Search Example Result**
**Google Search Social Preview**
|Before|After|
|-|-|
| <img width="683" alt="Screenshot 2020-08-20 at 18 30 …
> Social Previews: update Google Search preview to reflect current look

- packages/social-previews/src/twitter-preview/index.jsx
- packages/social-previews/src/twitter-preview/style.scss
- packages/social-previews/test/index.js
This PR aims to bring the Twitter Preview of Social Previews in line with the current look of Twitter's preview.
The related issue is https://github.com/Automattic/wp-calypso/issues/44799 and fixes https://github.com/Automattic/jetpack/issues/16896
Note: I've been getting different results between the [Twitter Card validator](https://cards-dev.twitter.com/validator) and testing in the Twitter interface directly. For this PR we'll use the Twitter Card validator as a reference as it's the tool Twitter provides to check how content will look like on their platform.
**Summary - Twitter Card Validator**
**Summary - Twitter Social Preview**
|Before|After|
|-|-|
| <img width="572" alt="Screenshot 2020-08-20 at 14 20 28" src="https://user-images.githubusercontent.com/1562646/90769341-5982e380-e2f0 …
> Social Previews: update Twitter preview to reflect current look

- apps/full-site-editing/full-site-editing-plugin/full-site-editing-plugin.php
- apps/full-site-editing/full-site-editing-plugin/readme.txt
- apps/full-site-editing/package.json
This release's changelog is:
* Premium Content: load assets using proper hook (https://github.com/Automattic/wp-calypso/pull/44825)                                                     
* EditingToolkit > GlobalStyles: Add new Google fonts (https://github.com/Automattic/wp-calypso/pull/44750)
> Bump WordPress.com Editing Toolkit plugin to v1.22

- client/components/jetpack/card/jetpack-product-card/style.scss
- client/my-sites/plans-v2/plans-column/index.tsx
- client/my-sites/plans-v2/product-card/index.tsx
- client/my-sites/plans-v2/products-column/index.tsx
- client/my-sites/plans-v2/selector.tsx
- client/my-sites/plans-v2/style.scss
**Visual Tweaks to the Jetpack Plans Page:**
(for Jetpack Offer Reset)
1. Page heading should be on top (in page heading font)
2. Sub heads (over columns should be 18px/1rem #3C434A
3. 40px vertical space between action bar (w/toggles) & plans sub heads
4. Price size should match product heading size, it looks like it's bigger at the moment.
5. Let's make the product card subhead match the subheads on the my plan page. I believe it's .9rem (see attached
**See Screenshots Below:**
1. Open your sandbox site
2. Enable the _Offer Reset Flow_ in A/B tests.
3. Visit the **Plans** section.
- Verify page heading is added (and in page heading font)
- Verify sub heads over columns are 18px/1rem #3C434A.
- Verify 40px vertical space between action bar & plans sub heads.
- Verify Price size is same …
> Jetpack Offer Reset: Plans Page visual tweaks

- client/signup/controller.js
*  Adds `pressable-nux` to exceptions list for .com `/start` flows
- Be logged in
- Set `existingUsersGutenbergOnboard` AB test to `gutenberg` (e.g. by `localStorage.setItem( 'ABTests', '{"existingUsersGutenbergOnboard_20200819":"gutenberg"}' );` ) — or try many enough times while in English locale in USA or Canada, 50% chance!
- Open `/start/pressable-nux`
- End up where you're supposed to, instead of `/new`
> Signup: add `pressable-nux` to exceptions list for .com Start flows

- client/my-sites/plans-v2/utils.ts
* There is an issue that prevents the "Included in your plan" from being displayed when users have a plan that include features provided by other products.
* Run this PR with the Offer Reset AB experiment on.
* Visit the Plans page and purchase Jetpack Security Daily/Real-time or Jetpack Complete.
* Verify that products included in any of those plans are labeled with "Included in your plan".
Fixes 1169247016322522-as-1189915727920768
> Offer Reset: fix issue that is preventing the "Included in your plan" label from being displayed

- client/my-sites/plans-v2/plans-filter-bar/index.tsx
- client/my-sites/plans-v2/plans-filter-bar/style.scss
- client/my-sites/plans-v2/style.scss
- client/my-sites/plans-v2/use-detect-window-boundary.ts
* We want to make the bar stick to the top to make it always visible.
* Created a hook called `useDetectWindowBoundary` which I pretend to use on the Cart bar to accomplish the same behavior.
* Run this PR with Offer Reset AB experiment on.
* Visit the Plans section/page.
* Verify that on mobile the `PlansFilterBar` components sticks to the top of the window when scrolling down.
* Verify that there is no noticeable jump in the UI when it goes from sticky to normal and the reverse.
* Verify that the same applies for the desktop version.
Fixes 1169247016322522-as-1187951765147441
> Offer Reset: make the PlansFilterBar stick to the top

- client/my-sites/checkout/composite-checkout/payment-methods/ebanx-tef.js
This fixes a bug in the Ebanx-TEF payment method store where masking and setting errors on fields would probably not work some of the time.
This store code was copied from a location where multiple reducers were merged together for different parts of the state, but in this store, there is only one reducer so every time we access the `state.fields` subtree, we need to be sure to do so explicitly. Instead, the data was sometimes being accessed as `state[key]` instead of `state.fields[key]`. This was probably easy to miss because it only happens for masking and for errors.
This PR also prevents `TOUCH_ALL_FIELDS` from erasing error messages.
Follow the testing instructions in #44752
> Checkout: Fix store actions for fields in ebanx-tef payment method

- client/my-sites/site-settings/sso.jsx
* Ensures the description for the toggle under SSO settings is translatable
Verify that this phrase still appears at `/settings/security` on a Jetpack site, and that it is now a translatable string (checking the code should be enough - I'm not sure it's possible to verify with the Community Translator yet). 
cc @scottsweb 
Fixes #45064
> SSO Settings: Ensure Description Toggle is Translatable

- client/blocks/user-mentions/add.jsx
In p5PDj3-4Uc-p2, @guarani discovered that a user mention inserted as the final text in a Reader comment would fail. For example, "hi @bluefuton" would save as "hi @". 
However, entering any text at all after the username (including punctuation) would mean the comment saved correctly.
It turns out that we weren't calling the onChange handler after inserting the username text. This wasn't noticed because it's very rare that the username is the last text in the comment.
This PR fixes the username insertion to call the onChange handler. This records the updated comment text correctly in the parent component's state.
On an existing testing site, invite a different test user to administer your site:
https://wordpress.com/people/team/<your_url>
Go through the process of accepting the invite. …
> User mentions: fix mentions at the end of comments

- client/landing/gutenboarding/available-designs.ts
- client/landing/gutenboarding/index.tsx
- client/landing/gutenboarding/onboarding-block/design-selector/index.tsx
- client/landing/gutenboarding/onboarding-block/style-preview/font-select.tsx
- client/landing/gutenboarding/stores/onboard/actions.ts
- client/landing/gutenboarding/stores/onboard/index.ts
- client/landing/gutenboarding/stores/onboard/reducer.ts
- client/landing/gutenboarding/stores/onboard/selectors.ts
* Randomize the list of available designs during gutenboarding /new/design step
* Persist the `randomizedDesigns` array in localStorage to maintain the same order of designs during a user's gutenboarding session
* on boot, verify that the cached list of designs is up to date with designs in available-designs-config.json
* Go to /new , proceed through flow
* When you arrive at http://calypso.localhost:3000/new/design
* note the oder of the designs
* check the WP_ONBOARD store 
* Continue on through flow for a page or two
* Click Go back link to go back to /new/design
* ensure that the design order is the same
* Refresh the page at /new/design
* ensure that the design order is the same
* Clear the WP_OBOARD store
* ensure that the design order is NOT the same, should be a new random order …
> Shuffle the list of available site designs during gutenboarding to prevent bias in user design selection

- client/my-sites/checkout/controller.jsx
- client/my-sites/controller.js
- client/signup/config/flows.js
* Fixes the issue of not being able to create a second domain-only site. This issue was reported in wp.me/p2MSmN-7Zp-p2.
* In registrationless checkout, we redirect /checkout/no-site URLs to /checkout/{SITE_SLUG} for logged in users. This PR will now redirect only if the user is not in the domain-only flow.
* While logged out, create a domain-only site by navigating to /start/domain
* After completing the purchase, navigate to /start/domain again, logged in, and try to purchase another domain-only site. You should be able to successfully complete purchase.
> Fix: Second domain-only site not created

- client/lib/query-manager/index.js
- client/lib/query-manager/paginated/index.js
- client/lib/query-manager/paginated/test/index.js
- client/lib/query-manager/test/index.js
Fixes a `QueryManager.getItems` memoization issue identified in https://github.com/Automattic/wp-calypso/pull/44963#discussion_r472069325
Adds a two-level memoization cache (`items` + `itemKeys`) when computing the `getItems` result.
That should make subsequent `getMedia` selector results `===` to each other more often.
**Todo:**
> QueryManager: memoize result of getItems, based on items and itemKeys

- client/components/domains/domain-search-results/index.jsx
- client/components/domains/domain-suggestion/style.scss
- client/components/domains/register-domain-step/index.jsx
- client/lib/abtest/active-tests.js
* As a part of the reskinning signup flow abtest (#44223), this change makes the "Select" CTA always visible in the domains step. Earlier it was shown only on hover.
* Also sets the font size of featured domain suggestions to `$font-title-medium` to adhere to the new stylelint rules.
* Make sure you're assigned to reskinned group of reskinSignupFlow a/b test.
Note: this test is intended to work only for non-EN and non-ES users.
* On the domains step, the "Select" button CTA for each domain suggestion should always be visible. Screenshot:
* There should be no changes to the mobile version of the page.
> Signup: Updates to the reskinned flow abtest

- client/my-sites/plugins/plugin-compatibility.js
Unblock WP Rocket.
- Go to plugins
- Search for WP-Rocket
- See plugin not blocket
> Atomic: Re-enable `wp-rocket`

- client/signup/navigation-link/index.jsx
- client/signup/step-wrapper/index.jsx
- client/signup/steps/domains/index.jsx
Landing on the [domain-only](https://wordpress.com/start/domain/domain-only?search=yes&new=Rightbrain%20Coffee) flow, (from [Domains](https://wordpress.com/domains/) or [Business Name Generator](https://wordpress.com/business-name-generator/) LP) shows as 'Back to sites' back button. Clicking on the button tries to take you to the [Sites page](https://wordpress.com/sites) instead of going to the previous page.
This PR fixes this by using a `source` parameter set to either 'domains' or 'business-name-generator' in order to override the default back link URL and label.
The `source` params have been added to the pages here:
- /domains:  D48184-code
- /business-name-generator: D48185-code
* Navigate to the domain-only step with `source` URL param set to …
> Domain-only flow: Set back button/action based on qurey parameter

- client/landing/gutenboarding/hooks/use-selected-plan.ts
- client/landing/gutenboarding/hooks/use-step-navigation.ts
- client/lib/abtest/active-tests.js
- client/signup/controller.js
Gutenboarding supports setting a custom flow via url params since https://github.com/Automattic/wp-calypso/issues/41576 but the param was never passed through the A/B test redirect.
If a new user goes to [wordpress.com](https://wordpress.com/) and choose to start with a plan, then they shouldn't be forced to make the plan selection again during the onboarding.
* Update `/new` redirect to include flow name in the route. eg: `/new/personal`, `/new/premium`, etc.
* Consider a paid plan passed from URL as selected plan in Gutenboarding and skip Plans step.
* Reverted A/B targeting change introduced in #45026 and updated slug.
* Go to https://calypso.live/?branch=fix/gutenboarding-plan-via-url-param
* Open console and run `localStorage.setItem( 'ABTests', …
> Gutenboarding: fix getting a plan via url param

- client/components/jetpack/upsell-switch/index.tsx
* Tweak the logic in `UpsellSwitch` so that the "show upsell" state variable can be set to either true or false depending on the current app state (especially after a product purchase or when the Rewind state changes).
Fixes `1164141197617539-as-1185831244882330`.
Before testing this PR, or in a different environment:
* Create or a select a site that does not have Jetpack Backup and/or Scan.
* From anywhere in Calypso *except* their respective upsell pages (e.g., from the **Plans** page), purchase one of these products.
* Without manually refreshing the browser at any point, go to **Jetpack > Backup** or **Jetpack > Scan** (depending on which you purchased).
* Observe that the product upsell is displayed on page load.
To test this PR:
* Remove any existing purchases, then follow the same …
> Jetpack Cloud: Don't show upsells after product purchase

- client/components/tinymce/plugins/media/plugin.jsx
* In `tinymce/plugins/media/plugin.jsx` replace usage of `MediaStore` change listener with redux `store.subscribe` and call `updateMedia` in case something in media state changed
1. Open the  classic post editor on a post which contains the same image at least twice
2. Edit that image (crop, flip, rotate, etc)
3. Make sure all copies of that image are updated
related #43663
> classic-post-editor(media): replace MediaStore listener with redux's store.subscribe

- client/my-sites/sidebar/index.jsx
- client/my-sites/sidebar/test/sidebar.js
If the `site.options.admin_url` is invalid (according to `getUrlParts`), it will return an object with empty properties. The code then passes those properties to `getUrlFromParts`, which throws if its object is missing any parts. This causes `MySitesSidebar` to throw an error during render.
This appears to be a regression added in https://github.com/Automattic/wp-calypso/pull/44688
This PR adds two guards to help with this situation: it prevents loading the wp-admin sidebar menu if `site.options.admin_url` is not set, and it also wraps the call to `getUrlFromParts` in a try/catch which will cause the wp-admin sidebar menu to also not be rendered if it fails to parse the url (rather than throwing an error).
Props to @desnum for reporting the bug and @automattic-ian for recording the …
> Sidebar: Prevent getUrlFromParts from throwing on an invalid jetpack url

- client/me/help/help-contact/index.jsx
Adds back the component that puts up a notice of our limited chat support availability.
> Support: Put up notice of limited chat availability

- client/my-sites/checkout/checkout-system-decider.js
- client/my-sites/checkout/composite-checkout/payment-methods/ebanx-tef.js
This removes the gating that prevented users with a Brazil country code to access new ("composite") checkout. The gating was in place because Brazil allows two payment methods that are unique: credit card processing through Ebanx and bank transfers with Ebanx-TEF. As those are both now implemented (see #44752 and #43812), it should now be possible to enable them.
Requires https://github.com/Automattic/wp-calypso/pull/44978 to be merged to fix the TEF method first!
- First you'll need to convince checkout that your country code is 'BR'. You can do this with a VPN or by sandboxing the API and applying the backend patch D48147-code.
- Set your currency to BRL.
- Visit checkout and verify that you see new checkout.
- When choosing your country, select "Brazil".
- Verify that when you get to …
> Allow Brazil countryCode to access composite checkout

- client/jetpack-connect/controller.js
- client/jetpack-connect/store-footer.tsx
- client/jetpack-connect/store-header.tsx
- client/jetpack-connect/style.scss
- client/my-sites/plans-v2/controller.tsx
- client/my-sites/plans-v2/details.tsx
- client/my-sites/plans-v2/plans-header.tsx
- client/my-sites/plans-v2/selector.tsx
- client/my-sites/plans-v2/types.ts
- client/my-sites/plans-v2/upsell.tsx
* This fixes some issues with Jetpack Connect plans page redesign:
- Made background of filters black.
- Add secure payment options.
- FAQ section.
- Text below Jetpack logo now only shows on selector page.
- Removed errant header.
Notes:
- Missing Free plan selector. That's dependent on #45101.
- FAQ section is not an accordion- investigated and that was too complex for the current time.
* Go to `/jetpack/connect/[site]` with appropriate A/B test.
* Compare design to comp provided in ticket.
* Verify functionality is intact.
Fixes 1169247016322522-as-1189798974271601.
> Offer Reset: Jetpack Connect Tweaks

- client/components/jetpack/card/jetpack-product-card/features-item.tsx
- client/lib/plans/features-list.js
- client/my-sites/plans-v2/constants.ts
- client/my-sites/plans-v2/types.ts
- client/my-sites/plans-v2/utils.ts
This PR adds missing icons to the Jetpack Complete and Security features.
Icons are a mix of `Gridicon`s and `MaterialIcon`s
- For Jetpack Complete, check that you see the icons under the "Security" features section
- Do the same for Jetpack Security
- Check that for products, you don't see any custom icon but only a checkmark
> Add missing icons to product card features

- client/components/jetpack/card/product-card-placeholder/index.tsx
- client/components/jetpack/card/product-card-placeholder/style.scss
- client/my-sites/plans-v2/details.tsx
This PR adds a loading state to the plans/products details page.
The PR also ensures the loading state is never shown once the products are loaded.
This PR is tricky to test, since products seem to be part of the initial page payload, or fetched quite early. With the fix, I never saw the loading state.
- Click on the Jetpack Security card and land on the details/options page
- You shouldn't have seen any loading state and the UI is displayed instantly
- Hard refresh the page
- Check that once the cards appear, they don't disappear
To check the actual loading state:
- Download the PR locally and in `client/my-sites/plans-v2/details.tsx`, update the `isLoading` declaration by `const isLoading = ! currencyCode || isFetchingProducts;` …
> Display a loading state while Details page is loading

- client/my-sites/checkout/composite-checkout/payment-methods/credit-card/credit-card-fields.js
The credit card form in new checkout displays a "loading" version of the fields (disabled fields and a spinner) while the Stripe fields finish rendering (this is done via stripe.js and iframes). However, if the user is in Brazil and using Brazilian currency, the credit card fields are rendered using Ebanx instead of Stripe, and therefore we don't need to wait for Stripe to load.
In this PR, we explicitly disable the loading state if using Ebanx.
- Apply D48147-code to your sandbox to pretend to be in Brazil and sandbox the API.
- Set your currency to `BRL`.
- In the contact information step, choose "Brazil" for the country.
- In the final step, choose "Credit or debit card".
- Verify that the form asks for all the Ebanx fields in addition to the credit card fields …
> Checkout: Prevent CC loading form if showing ebanx fields

- client/components/domains/domain-registration-suggestion/index.jsx
- client/components/domains/domain-search-results/index.jsx
- client/components/domains/domain-suggestion/index.jsx
- client/components/domains/domain-suggestion/style.scss
- client/components/domains/featured-domain-suggestions/index.jsx
- client/components/domains/premium-badge/index.jsx
- client/components/domains/premium-badge/style.scss
- client/components/domains/register-domain-step/index.jsx
- client/lib/wpcom-undocumented/lib/undocumented.js
We want to start selling premium domains to our users. The domain suggestion endpoint is capable of returning premium domains but we need to fetch the premium price and render a premium badge next to the domain name.
* render the "Premium domain" badge next to premium domains in the domain suggestions
* Implement the new price REST API and call it for premium domains
* render placeholder while the premium price is loaded
* override the default price for premium domains
* allow the `available_premium` domain status for the domain availability precheck and the availabilty check for FQDNs
Here's how it looks in NUX and Calypso:
* Depends on D48244-code which introduces a new REST API endpoint
* Search for anna/soda/dale and try limiting the results to .blog only
> Add premium domain support in the domain suggestions page

- client/gutenberg/editor/calypsoify-iframe.tsx
- client/gutenberg/editor/controller.js
https://github.com/Automattic/jetpack/pull/16935 and D48460-code will ensure that users are sent back to `wordpress.com/block-editor` after they connect to Stripe from a Donations block.
The URL they are redirected to includes a `stripe_connect_success=gutenberg` query param intended for displaying a success notice:
https://github.com/Automattic/jetpack/blob/2c734c944805aadd51e0e84dadab58b854e09e6a/extensions/shared/stripe-connection-notification.js#L16-L23
This PR passes down the `stripe_connect_success` query param (if present) to the `iframe` rendering the block editor so the success notice is displayed.
* Go to `/block-editor/post/:site?stripe_connect_success=gutenberg`.
* Make sure the success notice is displayed.
* Remove the `stripe_connect_success` query param from the URL.
* Make …
> Gutenberg: Display a success notice after connecting to Stripe

- client/landing/gutenboarding/onboarding-block/design-selector/index.tsx
- client/landing/gutenboarding/onboarding-block/design-selector/style.scss
* Changed the layout of the `.design-selector__option-meta` element from `inline-grid` to `inline-flex`
* This allows for its content to be always horizontally centered, regardless of the theme being premium or not
* Theme name and premium label allowed to wrap on more lines, in case they don't fit into one line
* Added the `font-family: inherit` rule on the `.design-selector__design-option` button element, in order to prevent User Agent stylesheet from overriding the font family used for the theme name and premium badge
* Other typography-related adjustments:
- Smaller font size for theme name
- Smaller font size for premium badge. _(Note: it's now 10px, which is not one of the [allowed font sizes](https://github.com/Automattic/wp-calypso/blob/master/packages/typography/styles/variables.s …
> Gutenboarding: Fix theme name + premium badge center alignment in design selection

- client/my-sites/domains/domain-management/dns/domain-connect-record.jsx
Currently, the user can click on the Domain Connect record toggle button on the DNS Records page rapidly which will send multiple requests to the back end in rapid succession without waiting for the previous request to complete. Under certain circumstances, this can cause a race condition which will cause the Domain Connect record status to be inconsistent across different parts of the back-end systems.
This diff disables the toggle control while an update is being performed and re-enables it once the request promise has been fulfilled. This helps to prevent additional requests from being sent before the first one has completed.
Before applying the PR, click the button rapidly and notice that multiple requests are sent rapidly.
After applying this PR, try clicking the button rapidly and …
> Prevent user from clicking on the domain connect toggle during an update

- client/components/jetpack/card/jetpack-product-card/index.tsx
- client/components/jetpack/card/jetpack-product-card/style.scss
Removes the bottom border radius of the product card when an upgrade nudge is shown.
- Purchase Security _Daily_
- Go back to the _Plans_ page
- Check that in the Security _Daily_ card, you see the upgrade to Real-time nudge
- Check that the corners below the "Show features" toggle are not round (see capture)
**Before**
**After**
> Style update in Security Daily card with upgrade nudge

- test/e2e/specs/wp-gutenboarding-spec.js
This is part of the onboarding process.
* Breaking intentionally tests in `test/e2e/specs/wp-gutenboarding-spec.js`
* `cd test/e2e && ./node_modules/.bin/mocha specs/wp-gutenboarding-spec.js`
* Tests should fail with error message `Forcing Gutenboarding e2e tests to fail`
cc @yansern
> Gutenboarding: Intentionally fail E2E gutenboarding tests

- client/landing/gutenboarding/onboarding-block/design-selector/style.scss
* Fixed tooltip on premium badge showing in uppercase.
* Go to design step in `/new`.
* Hover on premium badge.
* Tooltip text should not be uppercase.
Fixes #45179
> Gutenboarding: Fixed tooltip of theme premium badge showing in uppercase.

- test/e2e/specs/wp-gutenboarding-spec.js
Reverts Automattic/wp-calypso#45175
Part of the onboarding process
> Revert "Gutenboarding: Intentionally fail E2E gutenboarding tests"

- .circleci/config.yml
Amending circle config to ensure that e2e executables are persisted even when e2e tests fail (this is useful for being able inspect runtime errors more conveniently).
> desktop: always persist e2e executables

- client/components/jetpack/card/jetpack-free-card/index.tsx
- client/components/jetpack/card/jetpack-free-card/style.scss
- client/components/jetpack/card/jetpack-product-card/style.scss
- client/my-sites/plans-v2/selector.tsx
- client/my-sites/plans-v2/style.scss
This PR adds the Jetpack Free card to the Offer Reset Plans page.
1. Visit the Plans page.
2. Check that the Jetpack Free card shows and matches the Figma.
> Jetpack Offer Reset: Add Jetpack Free

- client/components/seo-preview-pane/style.scss
- packages/social-previews/CHANGELOG.md
- packages/social-previews/package.json
- packages/social-previews/src/twitter-preview/style.scss
* Fix the twitter preview having `width: 506px` and thus preview overflowed for viewports < 600px in width 
* Fixes are done only in respect to the package so that the problem is ultimately fixed in jetpack. Calypso itself **doesn't** show Social Previews for viewports < 600px (when clicking preview)
Before | After
-------|------
* check out branch 
* `cd packages/social-previews && yarn link` and then `cd ../.. && yarn && yarn start`
* Navigate to http://calypso.localhost:3000/view and pick a site on a business plan
* Now navigate to a post or page with adequate content and select Preview
* once loaded, switch to the "Search & Social" Twitter preview and check changes described above
Fixes https://github.com/Automattic/jetpack/pull/16950#pullrequestreview-473315779
> Social Previews package: fix twitter social preview overflow

- client/my-sites/domains/domain-management/list/style.scss
This PR adds a rollover colour for the domain listing to make it feel more interactive and more obvious that it's clickable. 
Before:
After:
Visit the domain listing screen, for a single site and all sites, and roll over a listing item to see the background colour change.
> Add rollover for domain list

- client/my-sites/domains/domain-management/edit/navigation/style.scss
This PR adds a rollover for the domains settings options.
Before:
After:
Visit the settings screen for any domain and roll over the settings options below. You should see the background colour change.
> Add rollover for domain setting screen options

- client/state/lasagna/connect/middleware.js
- client/state/lasagna/post-channel/middleware.js
- client/state/lasagna/user-channel/middleware.js
* Pass Redux actions onward immediately to complete the mw chain, reducers, etc before executing async Lasagna logic.
- Make sure the Lasagna websocket connects when opening any part of the Reader section.
- Make sure it disconnects when leaving the Reader section.
- Make sure channel joins happen when you open a post full view.
- Make sure channel leaves happen when you leave a post full view.
Fixes #43001
> Lasagna: make connect middleware behave like sync middleware

- client/lib/plans/constants.js
- client/lib/plans/plans-list.js
This PR removes the Security Real-time items when editing a cart that has Security Daily, and vice-versa.
Using two different types for Security Daily and Real-time doesn't seem to have any impact on the rest of the code, though conceptually it feels a bit odd. Another solution could be to update the logic in `useVariantPlanProductSlugs`, but it felt like a rabbit hole for the time being.
- Visit the _Plans_ section with the offer reset flow enabled
- Try to purchase one of the two Security options, _Daily_ or _Real-time_
- In the checkout page, edit the cart
- You should be able to select a different term, but not a different option
- Repeat these steps for the other option
Cart
Cart edition before
Cart edition after
> Remove extra Security options when editing cart

- apps/editing-toolkit/editing-toolkit-plugin/full-site-editing-plugin.php
- apps/editing-toolkit/editing-toolkit-plugin/readme.txt
- apps/editing-toolkit/package.json
- package.json
This release's changelog is:
* Rename directories from "full-site-editing*" to "editing-toolkit*" (#44501)
* Update/premium content loading assets code cleanup (#45052)
* FSE: Add Newspack assets unit tests (#43218)
> Bump WordPress.com Editing Toolkit plugin to v2.0

- client/components/jetpack/card/jetpack-product-card/style.scss
On Jetpack Product Cards, this PR prevent the prices from wrapping to second line below the title, unless the title is extra long or unless the product card width cannot fit both the title(on left) and prices(on right) on same line.
Here is a screenshot where the price has wrapped to the second line below the title. (When it isn't supposed to.)
Really small, simple CSS fix - Fixes the prices wrapping to the second line when they're not supposed to.
- Enable the Offer Reset Flow in A/B tests.
- Visit the Plans section.
View the plans page in desktop view. All the prices in the product cards should be displaying on the same line to the right of the product card title.
You can shrink the viewport and observe that the prices don't wrap to the second line until the product container is very …
> Jetpack Offer Reset: Prevent prices from wrapping to second line

- client/lib/plans/plans-list.js
The Jetpack Product Card for **Monthly** _Security Real-time_ is displaying info for _Security Daily_ (See screenshot).  This PR fixes this, to display the correct **Real-time** card/info.
1. Enable the Offer Reset Flow in A/B tests.
2. Visit the Plans section.
3. Select "**Monthly**" in the top filter bar.
4. On the **Security** product card, click "**Get Jetpack Security**" button.
5. You should then see the selection page with both options, _Security Daily_, and _Security Real-time_.  The _Security Real-time_ product card should display all real-time info.  (See screenshot):
> Fix Monthly Security Real-time card has wrong label (daily)

- client/my-sites/plans-v2/details.tsx
- client/my-sites/plans-v2/selector.tsx
- client/my-sites/plans-v2/upsell.tsx
- client/my-sites/plans-v2/utils.ts
This PR prevents a redirect loop when clicking on the back button of the checkout page.
- Click on the call-to-action of a product card that has no option, e.g. Jetpack Complete
- You should land in the checkout page with Jetpack Complete in the cart
- Click on the X button and notice you're back in the _Plans_ page
- Empty the cart
- Click on the call-to-action of a product card that has an option but no upsell, e.g. Jetpack Security
- You should land in the details page
- Select and option and check that the back button works
- Finally, click on the call-to-action of a product card that has an option and an upsell, e.g. Jetpack Backup
- You should land in the details page, then the upsell page
- Select the upsell or not, and …
> Offer Reset: fix redirect loop when clicking on checkout page back button

- client/my-sites/checkout/composite-checkout/use-get-thank-you-url.js
- client/my-sites/plans/current-plan/current-plan-thank-you/jetpack-complete.tsx
- client/my-sites/plans/current-plan/current-plan-thank-you/jetpack-security-daily.tsx
- client/my-sites/plans/current-plan/current-plan-thank-you/jetpack-security-realtime.tsx
- client/my-sites/plans/current-plan/index.jsx
* Add post-purchase Thank You notes/modals for Jetpack Security Daily/Real-time and Jetpack Complete.
* Instead of relying on what it's in the URL to get the purchased product, we inspect the current cart. If the cart doesn't have a Jetpack product or plan, we use what was passed in the URL.
* The ThankYou components have some repetition. We will fix that in a following PR.
* Run this PR with the Offer Reset AB test enabled.
* Visit the Plans page and purchase any of the new plans.
* Verify that you see a Thank You note that represents the purchased product.
* Repeat the process with an old Jetpack product (Backup or Scan) and verify they still work as before.
Fixes 1169247016322522-as-1189915727920775
> Offer Reset: custom post-purchase Thank You for Jetpack Security and Jetpack Complete

- client/components/jetpack/card/jetpack-free-card/index.tsx
- client/components/jetpack/card/jetpack-free-card/style.scss
- client/my-sites/plans-v2/selector.tsx
- client/my-sites/plans/current-plan/jetpack-checklist/index.tsx
- client/state/selectors/get-jetpack-wp-admin-url.js
This PR updates the Jetpack Free option to only show during the connect flow, and to have the appropriate href in the link going back to wp-admin.
1. Go through the connect flow on a Jetpack site.
2. When you come to the plans page, scroll down and verify that the Free card shows and that it links back to wp-admin.
3. Visit the plans page directly and verify that the Free plan does not show.
4. Visit `/plans/my-plan/:site` and verify that the "Return to WP Admin" link in the checklist still works.
5. Visit the plans page by navigating to it from in Calypso and verify that the Free plan does not show.
> Jetpack Offer Reset: Show Jetpack Free in the connect flow

- client/my-sites/customer-home/cards/tasks/site-setup-list/get-task.js
The 'Get started' was not translated on the user home in Calypso because the text was not wrapped in the translate function.
* This PR adds `translate ()` to the text that was not wrapped for translation.
* Go to https://wordpress.com/home/ for a newly created site with user language set to one of mag-16 languages
* Check that the 'Get started' button is translated.
> Add translate function to Get started text

- apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nux/src/wpcom-nux.js
Resolves https://github.com/Automattic/wp-calypso/issues/37279
From the issue:
> Please watch the "Making First Home Page Edits" testing video on this post: p58i-8d4-p2
>
> On first entry into the block editor, the sidebar is very distracting and doesn’t contain anything immediately relevant or useful to the user. We’ve seen this as an issue in almost all user tests. He goes through the sidebar and quickly realizes there is nothing there for him. “Move to trash?! I don’t want to do that!”
>
> As a secondary note, this hurts sidebar interactions later on when there are useful items in the sidebar for blocks. We’ve immediately set the expectation that the sidebar is something to avoid.
* When customer first time opens the editor, hide the editor sidebar.
* It's tied to showing the welcome …
> Hide editor sidebar first time users sees the editor

- client/reader/controller.js
- client/reader/conversations/index.js
- client/reader/discover/index.js
- client/reader/index.js
- client/reader/liked-stream/index.js
- client/reader/search/index.js
- client/reader/tag-stream/index.js
The `preloadReaderBundle` handler is always called from code in the `reader` chunk, so the operation is always noop (the bundle is already loaded).
The handler was added in #6974, at a time when `reader/discover` was a completely separate section, and when we used webpack 1 or 2 with a code splitting algorithm very different from today.
@blowery might know more details why this used to be useful.
I found this when looking for possible root causes of #45150. This is one of the places where the Reader router is in a somewhat messy state.
> Reader: remove the preloadReaderBundle handler

- client/reader/index.js
- client/reader/search/index.js
- client/sections.js
The section references the same module (`client/reader`) as the main `reader` section, and doesn't do anything useful. It was added in #25741 to support logged-out redirects, but these redirects were then implemented later at a framework level in #30537 and the Reader-specific redirect code was removed. After that, the section became an empty shell.
Also moves the `/recommendations` redirect handler to `reader/search`, potentially removing the need to load any other section than `reader/search` when handling the route.
This is another complexity-reducer PR inspired by debugging #45150.
Verify the Reader routes for reading feeds (`/read/feeds`, `/read/blogs`, `/read/a8c`) and verify that `/recommendations` continues to redirect to `/read/search`.
> Reader: remove redundant section for feed pages

- client/layout/masterbar/checkout.jsx
In #44746 we introduced a new `CheckoutMasterbar` component, but it's not properly connected to Redux, so it won't be recording events properly. This was likely caused by a bad rebase or something.
Luckily, it's not causing a fatal, so the only thing to fix here is the actual event recording.
* Fix syntax of `connect()` in the newly introduced `CheckoutMasterbar` component.
* Type `localStorage.debug='calypso:analytics:tracks'` in your browser dev console.
* Follow test instructions of #44206 to get to the logged out checkout page.
* Press the (x) on the logged out checkout page.
* Verify the `calypso_masterbar_close_clicked` event is being recorded.
> Masterbar: Fix redux connect in CheckoutMasterbar

- client/blocks/product-purchase-features-list/index.jsx
- client/lib/plans/constants.js
- client/me/concierge/main.js
- client/my-sites/plans/current-plan/index.jsx
This PR removes the **Quick Start session** feature from Business  My Plan page. See pbBQWj-eI-p2 for more details.
This doesn't apply to current plans (before 07-31-2020) until their next renewal.
* Subscribe to a new business plan.
* Go to [/plans/my-plan](https://wordpress.com/plans/my-plan)
* There shouldn't be any **Quick Start session** section
* Use a site with a new plan (created after 07-31-2020) with a pre-purchased QS (or purchase one [here](https://wordpress.com/checkout/offer-support-session))
* Go to [/plans/my-plan](https://wordpress.com/plans/my-plan)
* The **Quick Start session** section should now be visible
* Select a previously created business plan
* Go to [/plans/my-plan](https://wordpress.com/plans/my-plan)
* The **Quick Start session** section should be visible
> Remove Quick Start from Bussiness feature on My Plan page

- client/my-sites/checkout/composite-checkout/test/composite-checkout-thank-you.js
- client/my-sites/checkout/composite-checkout/use-get-thank-you-url.js
- client/my-sites/plans/current-plan/current-plan-thank-you/jetpack-complete.tsx
- client/my-sites/plans/current-plan/current-plan-thank-you/jetpack-security-daily.tsx
- client/my-sites/plans/current-plan/current-plan-thank-you/jetpack-security-realtime.tsx
- client/my-sites/plans/current-plan/index.jsx
* Add post-purchase Thank You notes/modals for Jetpack Security Daily/Real-time and Jetpack Complete.
This is a fixed version of #45196.
* Instead of relying on what it's in the URL to get the purchased product, we inspect the current cart. If the cart doesn't have a Jetpack product or plan, we use what was passed in the URL.
* I also added unit test to make sure getting the product from the cart works as expected in the cases we want it to.
* The ThankYou components have some repetition. We will fix that in a following PR.
* Run this PR with the Offer Reset AB test enabled.
* Visit the Plans page and purchase any of the new plans.
* Verify that you see a Thank You note that represents the purchased product.
* Repeat the process with an old Jetpack product (Backup or Scan) and verify they …
> Offer Reset: custom post-purchase Thank You for Jetpack Security and Jetpack Complete [v2]

- client/my-sites/checkout/composite-checkout/add-items.ts
- client/my-sites/checkout/composite-checkout/use-prepare-product-for-cart.js
Jetpack Search purchases on WordPress.com sites are currently mostly broken.
These purchase are typically initiated via a URL like `https://wordpress.com/checkout/[site]/jetpack_search_monthly`, but that is currently adding the wrong product to the shopping cart (it adds the one for Jetpack sites, not WordPress.com sites).
I think https://github.com/Automattic/wp-calypso/pull/44662 allowed the product to be added to the cart successfully, but it was still the wrong product.  Therefore, if you try to pay you get an error message because you can't buy a product intended for Jetpack sites on a WordPress.com site.  (Note that from just viewing the shopping cart, it's hard to tell the difference because the two versions of the product look the same and have the same prices.)
This pull request …
> Correctly add Jetpack Search or WPCOM Search products to the shopping cart, regardless of checkout URL

- client/my-sites/checkout/composite-checkout/record-analytics.js
This makes sure that any payment method ID strings being used as part of the "submit" Tracks event are lower-case and contain no hyphens, since upper-case letters and hyphens are disallowed by Tracks.
Fixes https://github.com/Automattic/wp-calypso/issues/45082
- Apply D47729-code and sandbox the store to make it appear that you are coming from Brazil.
- Load calypso and run `localStorage.setItem('debug', 'calypso:analytics')` in your browser console. Then reload the page (keep the console open).
- Visit checkout and proceed to the payment method step.
- Select "Transferencia bancaria".
- Fill in the fields using test data, available at https://developer.ebanx.com/docs/resources/testCustomerData/#brazilian-test-data. (Note that CEP is the postal code, and CPF is the tax ID.)
- Submit the …
> Checkout: Fix Tracks event string for ebanx-tef payment method

- client/my-sites/checkout/composite-checkout/composite-checkout.js
- client/my-sites/checkout/composite-checkout/hooks/use-shopping-cart-manager/index.ts
- client/my-sites/checkout/composite-checkout/hooks/use-shopping-cart-manager/types.ts
- client/my-sites/checkout/composite-checkout/hooks/use-shopping-cart-manager/use-initialize-cart-from-server.ts
- client/my-sites/checkout/composite-checkout/payment-method-helpers.js
- client/my-sites/checkout/composite-checkout/types/backend/shopping-cart-endpoint.ts
This is just a clean-up PR that fixes some broken types used by `useShoppingCartManager` and renames a couple of the properties of that hook (`productsToAdd`, `couponToAdd`) to make it clear that they only happen on init.
- Add products to cart via URL, like https://calypso.localhost:3000/checkout/example.com/business
- Verify that you are taken to checkout with that product in your cart.
- Add a coupon to your cart via URL, like https://calypso.localhost:3000/checkout/example.com?coupon=FOOBAR
- Verify that you are taken to checkout with that coupon applied to your cart.
> Composite checkout: clean up useShoppingCartManager props and types

- client/my-sites/checkout/checkout-system-decider.js
- client/my-sites/checkout/composite-checkout/payment-method-helpers.js
- client/my-sites/checkout/composite-checkout/payment-methods/netbanking.js
This removes the gating blocking `IN` country codes from accessing new ("composite") checkout. Previously this country was blocked because we had lacked support for the "Netbanking" payment method in new checkout, but as of https://github.com/Automattic/wp-calypso/pull/44952 that should now be available.
This is similar to https://github.com/Automattic/wp-calypso/pull/44944 which allowed access for Brazil.
As a side effect, this also removes the `composite-checkout-force` config flag, since it is no longer necessary. It _does_ leave the `old-checkout-force` flag for the time being, so that we can still test old checkout if needed until it is removed.
- Set your currency to INR.
- Apply D48222-code and sandbox the API; this will make it appear that you are in India.
- Visit checkout with a …
> Checkout: Allow India country codes to access new checkout

- apps/editing-toolkit/editing-toolkit-plugin/premium-content/blocks/container/edit.js
* This pull request updates the call which fetches information from the API used to generate the "Connect to Stripe" button in the Premium Content block if the user's account is not currently connected. It records whether the user is using the block editor on wordpress.com (iframed via Gutenframe) or whether they accessed it via WP-Admin, and causes the user to be redirected back to the appropriate place after connecting successfully.
* (This PR also contains a number of fixes to issues that ESLint was highlighting, preventing the main change from being committed. These have all been contained to the first commit of the PR.)
* Make sure your account is not connected to Stripe and that you have sandboxed the store. (see PCYsg-lW4-p2 #sandbox-method for detailed instructions).
* Load the …
> Premium Content: Fix redirect behavior after connecting to Stripe

- client/my-sites/plans-v2/use-item-price.ts
- client/my-sites/plans-v2/utils.ts
This PR introduces a change in how plans are shown in product cards, when the selected term is Yearly. The card now shows how it costs per month, with the mention "billed yearly".
- With a monthly term, check that nothing changed
- With a yearly term, check that the price shown is the price per month and that the "per month, billed yearly" mention is present
Yearly before
Yearly after
> Offer Reset: update displayed price in product cards for yearly term

- apps/editing-toolkit/README.md
See https://github.com/Automattic/wp-calypso/pull/45186#issuecomment-680407680
With #44501 we renamed _most_ of the FSE plugin to Editing Toolkit.
When merging, I've missed this readme mentioning the ongoing renaming process.
I'm aware that some of the "did not change" items are being worked on (e.g. #44552), but I think we can still say that the rename has been completed, as the phrasing in the readme is clear enough imho regarding what has and has not been done.
> Editing Toolkit: Update the readme to include a "rename info" section

- client/my-sites/plans-v2/details.tsx
- client/my-sites/plans-v2/selector.tsx
* Redirect the user directly to the checkout page if the site already owns the upsell product.
* Run this PR with the Offer Reset AB test enabled.
* With a site that has no plans or products visit the Plans page.
* Purchase Jetpack Scan Daily and go back to the Plans page.
* Select the Jetpack Backup generic/option card.
* In the Details page, select Jetpack Backup **Daily**.
* Verify that you landed in the checkout page without passing through the upsell page.
* Repeat the process by purchasing Jetpack Backup Daily first, and then purchasing Jetpack Scan.
Fixes 1169247016322522-as-1190551224035433
> Offer Reset: redirect to checkout if the site owns the upsell product

- client/assets/stylesheets/shared/functions/_z-index.scss
- client/blocks/plan-storage/index.jsx
- client/blocks/plan-storage/style.scss
- client/blocks/plan-storage/tooltip.jsx
- client/my-sites/media-library/style.scss
- client/package.json
- yarn.lock
This PR adds an accessible tooltip to the plan storage indicator in `/media`.
See paYJgx-WR-p2 for use of reakit and a11y considerations.
Fixes https://github.com/Automattic/wp-calypso/issues/40986
I also noticed that the plan storage block doesn't have a focus style that matches the rest of the buttons in the media library. I changed it to now match the other blocks.
* Using the [calypso.live](https://calypso.live/?branch=update/plan-storage-add-tooltip) link below, navigate to `/media`
* Hover over the storage indicator to show the new tooltip
* Verify it works as expected (see GIF above)
> Media plan storage indicator: add accessible tooltip

- client/me/purchases/manage-purchase/index.jsx
This is a complement to #39275 which deals with removing a purchase. This more specifically deals with canceling a refundable purchase. It handles another manifestation of the issue where refundable subscriptions associated with an AT site aren't allowed to cancel without support.
Where users should be able to cancel, instead they see:
* An AT side is needed for testing, with an associated G Suite subscription. The G Suite subscription should be within the refundable window. Ensure your site is launched/public, and that the hosting configuration is activated. 
* Create or access a  G Suite account in **Manage Purchases**
* Confirm that you are presented with a button to `Cancel Subscription and Refund`
* Confirm canceling the subscription is successful.
> G Suite: Enables self-cancelations for subscriptions attached to an AT site

- client/landing/gutenboarding/onboarding-block/design-selector/style.scss
* Ensures that the background colour of the popover is the same as the tooltip
Visit `/new` and hover over the "Premium" badge to verify that the colour is the same as the badge. If you want to Inspect the colour but the popover keeps disappearing, you may want to try pausing the script execution after hovering over the "Premium" badge. (`Command + F8 + \` )
cc @ciampo 
Fixes #45217
> Gutenboarding: Adjust Colour of Premium Tooltip

- client/my-sites/checkout/composite-checkout/components/wp-checkout.js
- client/my-sites/checkout/composite-checkout/composite-checkout.js
- client/my-sites/checkout/composite-checkout/hooks/use-cached-domain-contact-details.js
- client/my-sites/checkout/composite-checkout/hooks/use-shopping-cart-manager/types.ts
- client/my-sites/checkout/composite-checkout/hooks/use-shopping-cart-manager/use-shopping-cart-reducer.ts
- client/my-sites/checkout/composite-checkout/hooks/use-update-cart-location-when-payment-method-changes.js
This modifies the `useCachedDomainContactDetails()` React hook to also update the shopping-cart endpoint when it gets new cached details. Previously, if the user had cached contact details, those details would never be sent to the shopping-cart endpoint, with the result that taxes may not be displayed correctly.
In addition, this fixes an edge case bug which happened to be triggered by these changes. If you try to do most any cart action (eg: update the tax data, add a coupon, remove an item) while the cart is initially loading, it will trigger a race condition and can result in weird things happening (notably, a redirect to the plans page) since the cart will attempt to update and save the result while it's still waiting for the initial state.
To solve this, I added code such that if a …
> Checkout: update shopping-cart endpoint location when cached contact details change

- client/lib/products-values/translations.js
- client/my-sites/plans-v2/details.tsx
- client/my-sites/plans-v2/style.scss
- client/my-sites/plans-v2/upsell.tsx
This PR updates the copy of the page that prompts a user to buy Scan when they're purchasing Backup.
- There's no discount when buying both products.
- Updating the short names of the products wasn't straightforward. I needed to check that the parts of the code using them would still work with `TranslateResult` instead of just `string`. I tracked down the places in the codebase where it would be an issue, and the only one I found was `client/my-sites/plans-v2/details.tsx`.
- Make sure the site has no Jetpack plan or product
- Select Jetpack Backup
- Select Backup Daily
- Make sure the upsell page looks like the one in the capture
- Back to the _Plans_ page, select Scan and check the Backup upsell (see capture)
- Optionally, wander …
> Offer Reset: update copy in upsell page

- client/components/data/document-head/index.jsx
* Use `toString` method to compare prop updates in DocumentHead's title setter, as it will provide better and more sustainable comparison, when a value other than a string is provided to the `title` prop. A common example is the use of `translate` as a prop value, and the returned value from the call is a React component, instead of a string.
* Console log current and nextProps title value before the [document title setter action](https://github.com/Automattic/wp-calypso/blob/fix/document-head-title-setter/client/components/data/document-head/index.jsx#L52) - `console.log( this.props.title, nextProps.title )`
* Navigate through Calypso's pages and confirm that you are not getting the same current and next title prop logged in the console (e.g. the document title action setter is not being …
> Use `toString` method to compare prop updates in DocumentHead's title setter

- client/jetpack-connect/jetpack-remote-install-notices.jsx
For context, see p1HpG7-9YO-p2
This pull request removes the notice that WordPress 4.7 is the minimum. We are now at WP 5.5, 8 versions past 4.7. Further, that notice is also incorrectly shown any time that there is an error upon activation on the remote site.
* Spin up JN site
* SSH in
* Deactivate Jetpack
* Remove `wp-content/plugins/jetpack/load-jetpack.php` file
* Go to calypso.localhost:3000/jetpack/connect
* Enter in URL of JN site
* Enter in credentials
* Verify that you get a prompt to manually install Jetpack, as opposed to an incorrect WP 4.7+ notice
> Jetpack: Connect: Fix issue where incorrect WP 4.7 notice shows

- apps/editing-toolkit/editing-toolkit-plugin/premium-content/editor.css
- apps/editing-toolkit/editing-toolkit-plugin/premium-content/style.css
* This change addresses a regression which reintroduced the bug described at #44332, where a user would see multiple nudge notifications to connect their account to Stripe if editing a post with a premium content block while not connected. As a result of #44825, the premium content block's initialization code is now split into separate hooks for the edit and front-end views, and the style necessary to hide the duplicate notification needs to be in `editor.css`, which is loaded on the edit view, rather than `style.css`, which is loaded on the front-end view.
* Make sure your account is not connected to Stripe.
* Load the version of the full-site-editing plugin from this PR following one of the methods detailed in PCYsg-ly5-p2.
* Create a new post or edit an existing one, and add a "Premium …
> Premium Content: Fix duplicate Stripe nudge notification

- client/jetpack-connect/index.js
- client/my-sites/plans-v2/details.tsx
- client/my-sites/plans-v2/index.ts
- client/my-sites/plans-v2/selector.tsx
- client/my-sites/plans-v2/types.ts
- client/my-sites/plans-v2/upsell.tsx
- client/my-sites/plans-v2/utils.ts
- client/my-sites/plans-v2/with-redirect-to-selector.tsx
- client/my-sites/plans/controller.jsx
- client/my-sites/plans/index.js
- client/my-sites/plans/test/index.js
* Redirect users back to the Selector page if users are either in the Details page or the Upsell page and the selected site changes.
* I made the `:site` parameter optional in the URL. Some URLs didn't work at all when there was no site selected (Jetpack Connect flow without a selected site).
* I modev the `:site` to the end of the URL so the `SiteSelector` doesn't break the URL when the selected site gets changed. Also, this follow the implicit convention of having the site slug at the end of the URL.
* I created utility functions to construct URLs that target the Selector, Details, and Upsell pages so we can then change them in one central place.
* Run this PR with the Offer Reset AB test enabled.
* Move around the Plans page, following all paths you can image without purchasing any …
> Offer Reset: redirect to Selector page when selected site changes

- client/my-sites/plans-v2/style.scss
- client/my-sites/plans-v2/upsell.tsx
Adds a loading state to the upsell page. The PR also makes sure that the loading state is shown only once.
- Make sure the site has no Jetpack plan or product
- Select Jetpack Backup > Backup Daily
- The upsell page should be instantly displayed
- Hard refresh the page
- Note the loading state (see capture)
_Note that the first placeholder is slightly shorter than the loaded header. I already took into account the copy updates brought by https://github.com/Automattic/wp-calypso/pull/45231._
With loading placeholders
> Offer Reset: show loading placeholder in upsell page

- client/my-sites/plans-v2/controller.tsx
- client/my-sites/plans-v2/selector.tsx
This PR sets the Plans Page default duration to either "Monthly" or "Annually" based on the site's current Plan term.
1. Run this PR with Offer Reset A/B Test enabled.
2. Go to the Plans page.
3. In the top filter bar, notice the duration select (Monthly or Yearly), it should be defaulted to the selected site's subscription term.
4. Next, switch to another site that has a different subscription term, (Monthly or Yearly). It should always be defaulted to the sites's subscription term.  Or if free plan, defaulted to Yearly.
> Offer Reset: Set Plans page default duration to subscribed plan term/duration

- client/lib/abtest/active-tests.js
- client/signup/controller.js
* Pause `newSiteGutenbergOnboarding` test (100% traffic goes to control)
* Remove the redirect from code to prevent interference with `existingUsersGutenbergOnboard`
* Update `existingUsersGutenbergOnboard` datestamp
* Go to wordpress.com (production) and run `localStorage.setItem( 'ABTests', '{"newSiteGutenbergOnboarding_20200818":"gutenberg", "existingUsersGutenbergOnboard_20200824":"control"}' )` in browser console
* Go to [wordpress.com/start](http://wordpress.com/start) => you'll be redirected to `/new`
* Repeat the same thing on https://calypso.live/?branch=update/gutenboarding-new-site-abtest-pause => you'll continue the onboarding flow on `/start`
> Pause Gutenboarding all users A/B test

- client/components/domains/domain-product-price/index.jsx
Without context, free can be translated in different ways depending on whether it's an adjective, a verb, or the name of a plan. This change makes it so the translator can translate "Free" correctly in this context when referring to a free subdomain ('kostenlos' instead of 'free' (the translation for the plan name)).
> Add context to the word "Free" for translators

- client/state/activity-log/actions.js
- client/state/activity-log/init.js
- client/state/activity-log/package.json
- client/state/activity-log/reducer.js
- client/state/reducer.js
- client/state/selectors/get-activity-log-filter.js
- client/state/selectors/get-backup-progress.js
- client/state/selectors/get-requested-backup.js
- client/state/selectors/get-requested-rewind.js
- client/state/selectors/get-restore-error.js
- client/state/selectors/get-restore-progress.js
- client/state/selectors/is-rewind-activating.js
This PR is one of many working on modularising state in Calypso. This one handles activity log state.
For more details on state modularisation, see the [modularised state documentation](https://github.com/Automattic/wp-calypso/blob/master/docs/modularized-state.md) and p4TIVU-9lM-p2.
Note: I added all the reviewers that GitHub suggested. Please feel free to ignore the review request or pull in someone else if you're not comfortable reviewing this PR. Thank you!
Fixes #42420.
* Modularise activity log state
Activity log state gets automatically loaded on boot due to the navigation middleware, so it's difficult to test the automatic loading portion of this PR.
Smoke-testing activity log functionality should be enough to validate this PR, since no actual functional code changes to activity …
> Modularise activity log state

- client/lib/invites/actions.js
In this PR, we add `is_p2_site` and `inviter_blog_id` to the `calypso_invite_account_created` event. We need the `is_p2_site` flag to determine if the newly created invited account was thanks to a P2.
Open an incognito window and using a 10 minute email, invite the email to a P2 site. While creating a new account, inspect the network call to the events API or simply `console.log` the data next to the event definition.
The difference between `calypso_invite_account_created` and `calypso_invite_accepted`  is that `calypso_invite_accepted` is triggered at the last step when an invite is accepted for both users who created a new account and users who just logged in. `calypso_invite_account_created` is called just when an invited user is creating a new account.
> P2: add is_p2_site to calypso_invite_account_created

- client/my-sites/plans-v2/details.tsx
- client/my-sites/plans-v2/product-card/index.tsx
- client/my-sites/plans-v2/query-products/index.tsx
- client/my-sites/plans-v2/selector.tsx
- client/my-sites/plans-v2/upsell.tsx
- client/my-sites/plans-v2/use-is-loading.ts
- client/my-sites/plans-v2/use-item-price.ts
- client/state/sites/products/selectors.js
So far, offer reset pages have been consuming product data coming from the `/products/` endpoint. This is an issue as some prices (for Jetpack Search) depends on site stats (number of search records). This PR fixes that by making sure product data coming from the `/sites/<site id>/products/` endpoint is used when available.
The gist of the PR was to make sure that components in `client/my-sites/plan-v2/` were using data from `state.sites.products[id]` instead of `state.productsList`, when a site is selected. If no site is selected (e.g. at `/jetpack/connect/plans/`) it falls back to using `state.productsList`. This logic is extracted in a couple of components and hooks, so that offer reset pages don't have to deal with it. Namely: `QueryProducts`, `useItemPrice`, and `useIsLoading`.
The …
> Use product data coming from the site instead of the generic product list

- client/assets/stylesheets/_p2-vars.scss
- client/lib/wpcom-undocumented/lib/undocumented.js
- client/signup/p2-step-wrapper/style.scss
- client/signup/steps/p2-details/style.scss
- client/signup/steps/p2-site/index.jsx
- client/signup/steps/p2-site/style.scss
In this PR, we add a simple available domain suggestion to the P2 signup site step:
If you input a domain which is not available, it will suggest 3 alternatives if they are available:
- `<domain><petwo>.wordpress.com`
- `<domain>team.wordpress.com` 
- `<domain>work.wordpress.com`
/cc @evilluendas could you check the styling, please? :)
Open an incognito window and navigate to `/start/p2`. Input an already taken domain like `lamosty.wordpress.com`. It should suggest a few alternatives. Click on a suggestion and it should fill in the site input field. If you change the domain, it should clear previous suggestions and add new ones from the new domain.
> P2 signup: add domain suggestions

- client/my-sites/domains/domain-search/index.jsx
- client/my-sites/plans/navigation.jsx
This PR removes domains and emails from the plans navigation. 
**Before**
**After**
* Visit your plans and domians screens to make sure the domains and email menu items don't appear in the navigation.
* Preform a domain search and confirm that the plans navigation does not show.
> Remove domains, and emails, from plans navigation

- client/layout/masterbar/oauth-client.scss
* Use the `.wp-brand-font` class rather than enqueuing Recoleta directly for the Crowdsignal login form header
* Update WooCommerce login screen with new font-size vars, results in some minor visual changes.
**Before**
**After**
* In an incognito window or when logged out, visit the Crowdsignal.com login screen; replace the `wordpress.com` part of the URL with the URL to this test branch, or your local calypso host URL
* There should not be any visual changes to the Crowdsignal login form.
* In an incognito window or when logged out, visit the Woocommerce.com login screen; replace the `wordpress.com` part of the URL with the URL to this test branch or your local calypso host URL
* There should be minor visual changes to the Woocommerce login screen, shown above
> Typography: Update masterbar to use Recoleta package

- client/my-sites/domains/domain-management/list/index.jsx
- client/my-sites/domains/domain-management/list/style.scss
This PR updates the position of the all domains button to match some upcoming changes for the payments management screens. 
**Before**
**After**
Visit the domains screen and confirm positioning.
> Update position of all domains button

- client/my-sites/domains/domain-management/list/style.scss
This PR adds some spacing between the cart icon and add domain button on the domains screen.
**Before**
**After**
Add something to your cart and visit the domains screen. Check the plans screen to make sure that cart button isn't effected.
> Fix spacing of cart in domain header

- apps/editing-toolkit/editing-toolkit-plugin/mailerlite/subscriber-popup.php
*Changes the FSE Mailerlite translations namespacing from `jetpack` to `full-site-editing`
1. Check that the translations being used in Mailerlite are namespaced to `full-site-editing` and there are no occurrences namespaced under `jetpack`
Fixes #43700
> Fix FSE Mailerlite Translations Namespacing

- client/components/jetpack/card/jetpack-product-card/index.tsx
- client/components/jetpack/card/jetpack-product-card/style.scss
- client/components/jetpack/card/jetpack-product-card/upgrade-nudge.tsx
- client/my-sites/plans-v2/plans-column/index.tsx
- client/my-sites/plans-v2/product-card/index.tsx
- client/my-sites/plans-v2/products-column/index.tsx
Adds a loading placeholder while product prices are loading.
1. Run this PR with Offer Reset A/B Test enabled.
2. Go to the Plans page.
3. Verify that you see the loading placeholders while the product card prices are still loading.  Also verify that the positioning and size of placeholders looks good. 
_Loading state: Prices loading..._
.
.
**_Loading state: Prices loaded._**
> Jetpack Offer Reset: Add loading state for product card prices.

- config/development.json
- config/wpcalypso.json
Note: do not merge this until we have received translations for all of the Gutenboarding site designs.
* Enable the patterns lib in development and wpcalypso environments
* Checkout this PR locally and go to  calypso.localhost:3000/new/ko and ensure that the preview for Stratford is rendered using the Patterns lib (just testing that it's mostly in Korean will prove it)
* Complete creating your site, and confirm that the content in the editor is mostly in Korean (this will confirm that it's using the Patterns lib)
Fixes #
> Patterns API: Enable patterns lib in development and wpcalypso environments

- client/landing/gutenboarding/onboarding-block/features/style.scss
* It fixes the icons vertical alignment. Currently it looks like this:
**Before**:
**After**:
1. Using incognito mode, visit [`new/features?flags=gutenboarding/feature-picker&latest`](https://hash-f2fe5da3bd6ad847526450f3c76f1f3a9860fc17.calypso.live/new/features?flags=gutenboarding/feature-picker&latest)
2. Icons should be well-aligned.
Superseeds https://github.com/Automattic/wp-calypso/pull/45249
> Fix feature picker icon alignments

- client/my-sites/checkout/composite-checkout/record-analytics.js
* Wrap `recordEvent()` function body in try/catch. In case of exception, report to logstash.
Fixes https://github.com/Automattic/wp-calypso/issues/45226
> Checkout: Wrap analytics recording in try/catch

- client/boot/locale.js
- client/server/render/index.js
Initial translations setup on both the client and server side were not using the locale variant, which was causing parent locale translations to be bootstrapped to the page and not the locale variant ones. As a result, locale variant translations were fetched in the runtime which was causing some rendering glitches and additional network requests.
* Setup translations using `localeVariant` over `localeSlug` when available
* Change UI language to `es-mx`
* Check "My sites" label in the master bar and confirm it renders initially and remains as "Mi sitio"
* Inspect network requests and confirm only `es-mx-*` translation files and none of the parent `es-*` are being fetched
> i18n: Fix translations setup with locale variant

- client/components/jetpack/card/jetpack-product-card/style.scss
- client/components/jetpack/card/jetpack-product-card/upgrade-nudge.tsx
* Fixes Upgrade Nudge price to be left aligned when price is wrapped below the title.
1. Run this PR with Offer Reset A/B Test enabled.
2. Go to the Plans page.
3. Visually inspect the Upgrade Nudge price.  When the product card price is small enough to wrap to the second line, the price should be Left aligned, like shown in the screenshot labelled, "After".  (See screenshots)
_Before..._ 
.
.
**After.**
> Jetpack Offer Reset: Upgrade Nudge, align price left if price wrapped.

- client/landing/jetpack-cloud/sections/settings/controller.js
- client/landing/jetpack-cloud/sections/settings/flow.tsx
- config/jetpack-cloud-development.json
- config/jetpack-cloud-horizon.json
- config/jetpack-cloud-production.json
- config/jetpack-cloud-stage.json
**Motivation**: Create safe place to develop new Jetpack Server Credentials Project without affecting production
* Add `jetpack/server-credentials-advanced-flow` feature flag
* Add placeholder server credentials flow page 
1. boot Jetpack Cloud w/out new flag
2. verify `/settings/:siteSlug` matches production
3. boot Jetpack Cloud w/ new flag ( `env ENABLE_FEATURES=jetpack/server-credentials-advanced-flow yarn run start-jetpack-cloud`
4. verify the placeholder page appears at `/settings/:siteSlug`
> Jetpack Cloud: Add Jetpack Credentials Feature Flag

- client/my-sites/themes/theme-options.js
- client/state/selectors/get-customize-url.js
Ensures that the Customize button on the Themes page always navigates to Customizer.
1. Make a new site on WP.com as a new user with a Free Plan.
2. Navigate to Themes under Design in Calypso. Ensure your current theme is Hever.
3. Click the button labelled Customize. It should navigate you to Customizer instead of the Page Editor
Fixes #44429
> Customize button to always navigate to customizer

- apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nav-sidebar/class-wpcom-block-editor-nav-sidebar.php
- apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nav-sidebar/src/components/create-page/style.scss
- apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nav-sidebar/src/components/nav-sidebar/index.tsx
- apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nav-sidebar/src/components/nav-sidebar/style.scss
- apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nav-sidebar/src/constants.ts
- apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nav-sidebar/src/types.ts
Updating the sidebar to match the design in https://github.com/Automattic/wp-calypso/issues/45240
I left the draft/scheduled badges in there to distinguish between the two.
Tested in Chrome, Safari and IE Edge
Apply D48670-code to your sandbox
Sandbox a site and edit a page/post
Check that there is no regression in carried-over functionality 
Check that the design matches the updated screenshot in https://github.com/Automattic/wp-calypso/issues/45240
Tested with a long site title, e.g., 
Fixes #45240
> Editing Toolkit Sidebar: Update design

- client/components/domains/domain-registration-suggestion/index.jsx
- client/components/domains/premium-badge/index.jsx
- client/components/domains/register-domain-step/index.jsx
* We want to disable the "Add to cart" button (actually the "Select" button) while the premium domain pricing is loading because otherwise the user doesn't really know how much a premium domain would cost.
* Fixed a warning with the `PremiumBadge` passing string instead of numeric `iconSize` property
It should look like this while loading the price:
* Search for a premium domain and make sure the select button is disabled and can't be clicked while the premium price is loading. It might make sense to add some delay in the REST API endpoint in order to test this thoroughly.
* also verify that there is no warning about `iconSize` in the console
> Disable the add to cart button while premium pricing is pending

- client/my-sites/domains/domain-management/list/domain-item.jsx
- client/my-sites/domains/domain-management/list/index.jsx
* Adds "Change site address" ellipsis menu
* Fixed a bug to show the ellipsis menus in the site specific domains list
* Open a site specific list of domains and verify that there is a "Change site address" menu in the ellipsis menus for the wordpress.com subdomain
* Open a site specific list of domains and verify that you can see the ellipsis menus for all the items (before this PR only "Edit settings" was visible)
> Add "Change site address" menu in the domain list menus

- client/lib/signup/step-actions/index.js
- client/my-sites/invites/invite-accept-logged-out/index.jsx
- client/signup/config/flows-pure.js
- client/signup/main.jsx
In this PR, we refactor all the occurrences of `signup_flow_name` from `wp-for-teams` to `p2`. It's required for tracking purposes and we need to match the value (`p2`) with the `flow` event property for the `calypso-*` signup events.
See D48775-code for testing instructions as that patch is required for this to work.
> P2: refactor wp-for-teams to p2 in signup

- client/components/forms/form-text-input/index.jsx
The `FormTextInput` component is a controlled component, meaning that it has an `onChange` prop and a `value` prop, and when you type in the field, the change is absorbed by React and the field value is only updated when the `value` prop gets modified.
In https://github.com/Automattic/wp-calypso/pull/43838 this behavior was modified by adding a second `value` stored in local state. This second value is directly updated by changing the field, acting as a sort of local cache within the component that can then be updated to match the `value` prop when it changes to match using the `updateValueIfNeeded()` function.
The problem is that it's possible for the two `value`s to become out of sync if the controlling component changes the value before it returns to the `FormTextInput` (typically …
> FormTextInput: keep field value in sync with value prop

- client/jetpack-connect/style.scss
- client/my-sites/plans-v2/details.tsx
- client/my-sites/plans-v2/selector.tsx
- client/my-sites/plans-v2/style.scss
This PR does 3 things (see captures):
1. it standardizes the spacing above the payment methods amongst pages
2. it adds a bottom border to the filter bar, when docked to the top of the page
3. it displays the Jetpack Free card
Visit `/jetpack/connect/plans/:site` with the offer reset flow enabled
1. Check that the spacing above the payment methods is the same in the selector, details, and upsell pages
2. Check that the filter bar has a border when it's docked to the top of the page
3. Check that the Jetpack Free card is displayed
Payment methods
_Before_
_After_
Filter bar border
Jetpack Free card
> Fix styling issues in Jetpack connect-in-place page

- client/components/step-progress/README.md
- client/components/step-progress/docs/example.tsx
- client/components/step-progress/index.tsx
- client/components/step-progress/style.scss
- client/devdocs/design/component-examples.js
- client/devdocs/design/index.jsx
**Motivation:** Add a component as part of the Jetpack Server Credentials Project
* Add StepProgress component
* Add StepProgressExample Component
1. Navigate to `/devdocs/design/step-progress` on branch
2. Confirm the steps are swapped to primary color as they are reached
> Add Step Progress Component

- client/components/chart/bar-container.jsx
- client/components/chart/index.jsx
- client/components/chart/x-axis.jsx
- client/lib/track-element-size/index.ts
* Previously, despite entering the same startDate parameter in the URL, the x-axis labels would show inconsistent dates. The PR ensures that given the same startDate, the x-axis labels will show consistent date labels.
1. Starting at URL: https://wordpress.com/stats/day/{site-URL}
2. Take note of how the bar graph displays
3. Modify the URL to view the daily stats for a date that falls before the current range of the bar graph, e.g. by appending `?startDate=2019-06-23`
4. Reload the page with the same start date. The x-axis should always read the same after each reload.
**Screenshots**
x-axis labels for August 28
x-axis labels for August 27
Fixes #35230
> Stats: Display proper labels for x axis

- client/my-sites/customer-home/cards/features/stats/index.jsx
* Switches the wording of the Stats placeholder on My Home to the one in the original issue 
Verify that the text is updated for sites under a week old - there should also be no changes to sites that are any older. 
cc @mmtr 
Fixes #45327
> My Home: Update Stats Text for Sites Under a Week Old

- apps/editing-toolkit/editing-toolkit-plugin/full-site-editing-plugin.php
Fixes the broken site editor on Dotcom by making sure that experiment option is
overridden on time.
1. Make sure that you are using the site with Gutenberg edge sticker.
2. Apply the generated patch and make sure that the site editor loads.
> Site Editor: fix loading order on Dotcom after 8.9.0 update

- apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nav-sidebar/src/components/nav-sidebar/index.tsx
- apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nav-sidebar/src/components/toggle-sidebar-button/index.tsx
1. Open a site to edit in WP.com and navigate to edit a post or page:
2. Once in the editor, verify the (W) icon has the correct aria-label "Block editor sidebar)
3. click the (W) icon in the top left
3. Once the Block Editor Sidebar is open:
* verify the (W) icon has the focus 
* look in dev tools to verify aria-label/aria-description on (W) button (aria-description used for more descriptive info)
* look in dev tools to verify aria-label on "View pages/posts" link
* look in dev tools to verify Posts heading is an h2
Conversely, use a screen reader to verify the aria-labels and aria-descriptions mentioned above
Fixes # https://github.com/Automattic/wp-calypso/issues/45239
> Add aria label to WP-icon button to indicate that it opens sidebar.

- client/reader/sidebar/reader-sidebar-followed-sites/item.jsx
In the updated Reader sidebar, we are displaying the user's subscribed feeds:
The sidebar expects a feed ID to be present in each case, but unfortunately not all subscription records have that available. This has lead to broken links in the sidebar (to `/feeds/undefined`) for some of my subscriptions.
This patch improves the resilience of subscription display by:
* Falling back to the blog stream if there's a blog ID available
* Skipping the subscription altogether if there is neither a feed ID or blog ID (unfortunately this can happen)
* Falling back to the feed URL if there's no site title to show
Load Reader and try clicking on your subscriptions to ensure a stream of posts is loaded. You can try subscribing to the following:
http://calypso.localhost:3000/read/feeds/52656883 (doesn't …
> Reader sidebar: improve resilience when displaying subscribed feeds

- client/me/help/help-contact/index.jsx
On Contact form, only show the notice about limited availability for Personal support level.
Go to http://calypso.localhost:3000/help/contact with a user who's top paid plan is Personal. You should see the "Limited chat availability" notice.
Go to http://calypso.localhost:3000/help/contact with a user who's top paid plan is anything other than Personal. You should _not_ see the "Limited chat availability" notice.
> Support: Only show limited availability notice for Personal support level

- apps/editing-toolkit/editing-toolkit-plugin/full-site-editing-plugin.php
- apps/editing-toolkit/editing-toolkit-plugin/readme.txt
- apps/editing-toolkit/package.json
- package.json
Release 2.1 version of Editing Toolkit plugin.
1. Apply the generated diff to your sandbox.
2. Test new updates listed in the changelog.
> Bump WordPress.com Editing Toolkit plugin to v2.1

- client/components/jetpack/card/jetpack-free-card/index.tsx
- client/components/jetpack/card/jetpack-free-card/style.scss
- client/my-sites/plans-v2/selector.tsx
- packages/components/src/button/style.scss
This PR fixes a couple of styling issues in the Jetpack Free card. It also fixes the button link in Jetpack cloud.
Fixes 1169247016322522-as-1191767071741497
- Visit `/jetpack/connect/plans/:site/` with the offer reset flow enabled
- Check that the Jetpack Free card plan at the bottom of the page looks like the capture below, and that the button redirects to the WP admin
- Run Jetpack cloud and go to `/pricing/`
- Check that the Jetpack Free card plan at the bottom of the page looks like the capture below, and that the button redirects to the install page
Before
After
Before
After
> Fix Jetpack Free card styling issues

- client/my-sites/plans-v2/selector.tsx
* Add the `calypso_plans_type_change` event to the new Plans page, which triggers when someone changes the product type filter (i.e., Security, Performance, or All).
* Add the `calypso_plans_duration_change` event to the new Plans page, which triggers when someone changes the product duration (i.e., Monthly or Annual).
* Add the `calypso_product_subtypes_view` event to the new Plans page, which triggers when someone selects a product that has one or more sub-types (e.g., Backup, which has Daily and Real-time variants).
*Partially* fixes `1169247016322522-as-1191023234087521`.
* Ensure that your environment has enabled the `showOfferResetFlow` A/B test.
* Visit the **Plans** page.
* Open your browser's DevTools window to the **Network** panel and monitor for **Image** requests.
* Select …
> Plans: Add Tracks events for new filters and products with subtypes

- client/my-sites/plans-v2/selector.tsx
* Add the currently selected site ID to the set of parameters for Tracks events added in #45366.
Testing is the same as described in #45366, copied below for easy reference.
**!!! Important:** The only additional criteria is that the events described should include `site_id` as a parameter, and this parameter value should match the ID of the currently selected site.
* Ensure that your environment has enabled the `showOfferResetFlow` A/B test.
* Visit the **Plans** page.
* Open your browser's DevTools window to the **Network** panel and monitor for **Image** requests.
* Select different values in the Duration toggle. Verify that for each change in value, a request goes out to `t.gif` with the following properties in its query string:
* `_en`: `calypso_plans_duration_change`
* `duration`: …
> Plans: Add the selected site ID to new Tracks events from #45366

- client/lib/plans/features-list.js
This PR updates the copy of some features, in Jetpack Complete.
- Toggle on the features of the Jetpack Complete plan card
- Verify that you see the 4 updates below and that the links in the tooltips work
1.
_Before_
_After_
2.
_Before_
_After_
3.
_Before_
_After_
4.
_Before_
_After_
> Update the copy of some features in the Jetpack Complete plan card

- client/state/stats/chart-tabs/reducer.js
- client/state/stats/chart-tabs/test/reducer.js
* We render a new set of data instead of appending data to the store when the first data point from the API is different from the first data point from our store. The previous behavior resulted in potential data points outside the bounds of the graph range and undefined values which resulted in empty graph states. If the dataset length or period differs from what is in the store, we assume that the data received is a new set of data.
* Considerations for how to solve this problem were documented here: https://github.com/Automattic/wp-calypso/issues/45315
1. Starting at URL: `/stats/day/{site-URL}`
2. Take note of how the bar graph displays
3. Modify the URL to view the daily stats for a date that falls before the current range of the bar graph, e.g. by appending `?startDate=2019-06-23`
4. …
> Stats: Properly display new graph data when new data is received

- .gitignore
- package.json
Git ignores files in the `apps/editing-toolkit/.cache` directory. Not sure when these intermediary files became part of the build, but it might be here? #44861
* Build editing toolkit with something like `cd apps/editing-toolkit && yarn dev --sync`
* `git status`
* There shouldn't be ~100 files in a `apps/editing-toolkit/.cache` directory
> Ignore the editing toolkit build artifacts in `.cache`

- test/e2e/lib/gutenberg/gutenberg-editor-component.js
- test/e2e/lib/mocha-hooks.js
- test/e2e/specs/wp-calypso-gutenberg-coblocks-spec.js
- test/e2e/specs/wp-calypso-gutenberg-post-editor-spec.js
All embed blocks (the ones touched by our E2E tests at least) now follow a similar naming/classification standard. They now all have the same ariaLabel and embed prefix for the .editor-block-list-item CSS class. 
This fixes the selectors so that the elements can be found on the page.
* Is it a good idea to have identical `aria-labels` for these blocks? They are all "embed" blocks, but they serve different purposes.
> [E2E] Embed block fixes

- apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nav-sidebar/src/components/nav-sidebar/index.tsx
- apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nav-sidebar/src/components/toggle-sidebar-button/index.tsx
Tells assistive technology:
* that the (W) button that opens the navigation sidebar is controlling a dialog
* whether the dialog is visible or not
Also:
* returns focus back to the previous element after the sidebar is closed
Part of #45239
* Apply D48946-code to your sandbox
* Open the block editor in a sandboxed site
* Inspect the (W) button in the top left
* It should have the `aria-haspopup="dialog"` attribute
* It should have the `aria-expanded="false"` attribute
* Open the nav sidebar
* The same (W) button should have the `aria-expanded="true"` attribute
* Close the nav sidebar
* The keyboard focus should return to the (W) button in the header
If you try in VoiceOver it doesn't change too much, but it does say now say that the button is "collapsed" when you focus on it.
> Nav sidebar: improve the experience of opening and closing the sidebar for assistive technology users

- apps/editing-toolkit/editing-toolkit-plugin/full-site-editing-plugin.php
- apps/editing-toolkit/editing-toolkit-plugin/readme.txt
- apps/editing-toolkit/package.json
- package.json
* Bump to version 2.2
* Update release notes
* Apply generated diff to sandbox
* Test changes listed in release notes are present
* Install build on an atomic site
* Test that editor works on atomic with and without gutenberg plugin enabled
> Bump WordPress.com Editing Toolkit plugin to v2.2

- client/layout/sidebar/style.scss
While playing with the Gutenlypso prototype in #44801, I noticed a broken sidebar:
It's caused by missing styles that used to be directly on the `ul` and `h2` elements in the CSS reset. This PR adds them to the specific `.sidebar_...` rules.
On `master`, this change shouldn't have any observable effects. In the #44801 branch:
- the horizontal identation of sidebar items should be removed
- the vertical space between items should be smaller
- after clicking on an expandable item, e.g., "Site", you shouldn't see a blue focus ring (added by default on the `<h2 tabindex=0>` that has been made interactive by the `tabindex` attr)
> Sidebar: fixup styles to work without the CSS reset

- client/my-sites/activity/activity-log/index.jsx
- client/my-sites/comment/main.jsx
- client/my-sites/comments/main.jsx
- client/my-sites/types/main.jsx
- client/state/post-types/selectors.js
- client/state/post-types/test/selectors.js
- client/state/selectors/can-current-user.js
- client/state/selectors/can-site-view-atomic-hosting.js
- client/state/selectors/test/can-current-user.js
- client/state/sites/selectors/can-current-user-use-customer-home.js
- client/state/sites/selectors/can-current-user-use-earn.js
- client/state/sites/selectors/get-site-computed-attributes.js
- client/state/sites/test/selectors.js
Users have been [complaining about crashes around reusable blocks for some time](https://github.com/Automattic/wp-calypso/issues/40229), I think that this bug may have been the root cause.
It appears that normally when loading the reusable block list, the users permissions will be cached, and the page will load correctly.
However, if the user's permissions are not cached,  the page will attempt to load with `postType` and `userCanEdit` set to `null`. This will cause several errors which prevent the page from loading. This PR adds null handling to the reusable block list page.
Have two sites set up, one that you haven't logged into for a while (sorry it's a bit vague)
In site one, navigate to the reusable blocks page
https://wordpress.com/types/wp_block/<YOUR_SITE.wordpress.com>
while on …
> Fix fatal error loading the block list for the first time for a site

- apps/editing-toolkit/editing-toolkit-plugin/starter-page-templates/class-starter-page-templates.php
- apps/editing-toolkit/editing-toolkit-plugin/starter-page-templates/page-template-modal/components/block-iframe-preview.js
- apps/editing-toolkit/editing-toolkit-plugin/starter-page-templates/page-template-modal/components/template-selector-item.js
- apps/editing-toolkit/editing-toolkit-plugin/starter-page-templates/page-template-modal/components/test/__snapshots__/template-selector-preview.test.js.snap
- apps/editing-toolkit/editing-toolkit-plugin/starter-page-templates/page-template-modal/index.js
* Add Current layout option to page layout picker when a user is editing / updating a homepage
* Spin up a local development environment (e.g. go to the `apps/full-site-editing` directory and run `yarn wp-env start`
* Run the local dev environment for FSE (e.g. fo to the `apps/full-site-editing` directory and run `yarn dev` or if you want to sync to your sandbox, run `yarn dev --sync`)
* In your WP install, set a page to be the front page in the customizer
* Go to edit that page, and then add the `?new-homepage` query param so that you open up the page layout selector for a homepage, where you should then see the Current layout option. E.g. for my own local test site, the URL is `http://localhost:4013/wp-admin/post.php?post=2&action=edit&new-homepage`
* With Current layout selected, you …
>  FSE: Add Current layout to starter page templates page layout picker when editing a homepage

- client/my-sites/checkout/cart/header-cart.jsx
- client/my-sites/domains/domain-management/list/index.jsx
- client/my-sites/domains/domain-management/list/style.scss
- client/my-sites/domains/domain-search/index.jsx
- client/my-sites/domains/style.scss
Recently in #45265 we removed the horizontal navigation in the domain search screen. However that also removed the popover cart as it was inside the horizontal navigation. So here's a PR that will show the cart in the new header.
*  Move the header cart component that we show in the domain management screen in a separate component so we can reuse it in the domain search screen too.
It looks like this (the cart is rendered only when there are products inside it):
* Add a domain then go back to the site domains list - make sure the cart icon is shown
* Click on "Add a domain to this site" button
* Make sure the cart is rendered in the domain search screen too
> Show the cart in the domain search screen header

- client/lib/plans/features-list.js
This PR makes the links in the features tooltips external, in the product cards.
- For each plan card (Jetpack Security, Jetpack Complete, Security Daily, and Security Real-time), toggle on the features section, and make sure that the links in the tooltips are external.
_Before_
_After_
> Make links in product card tooltips external

- client/lib/wpcom-undocumented/lib/undocumented.js
This pull request just removes the method which is used to call the `apple-pay/merchant-validation` endpoint on the server.
It's no longer used in Calypso, and it hasn't been relevant for a while since we now do Apple Pay entirely via Stripe.
See also: D49069-code
> Remove no-longer-used Apple Pay merchant validation endpoint

- client/my-sites/checkout/composite-checkout/hooks/use-skip-to-last-step-if-form-complete.js
Sometimes, for reasons I don't fully understand, calling `window.history.replaceState` fails with an error like this:
```
A history state object with URL 'https://wordpress.com/checkout/example.com#step2' cannot be created in a document with origin 'https://wordpress.com' and URL 'https://www.username@wordpress.com/checkout/example.com'.
```
It's not critical that we skip the first step, so this PR wraps that call in a `try` block to prevent it from breaking all of checkout if that error occurs.
- Visit checkout when you have pre-filled contact details (you've already made a successful purchase).
- Verify that the first step is still skipped automatically.
> Checkout: Prevent history.replaceState errors from crashing checkout

- client/my-sites/earn/memberships/index.jsx
- client/state/memberships/earnings/selectors.js
In #45304, we discovered that eCommerce sites were showing an errant 10% commission, when it should be 0% – the cause is two-fold. First, #42955 introduces a `getEarningsWithDefaultsForSiteId` selector that [returns a default commission value](https://github.com/Automattic/wp-calypso/blob/master/client/state/memberships/earnings/selectors.js#L23) of `0.1` (10%) if `QueryMembershipEarnings` data hasn't been received yet (something that users just shouldn't ever see, considering how confusing it is – we don't even have plans that charge that high). Secondly, it appears `QueryMembershipEarnings` is also returning the same 10% commission rate from the API.
This PR addresses the first issue, by only displaying the commission data once we've received actual earnings information from the query …
> Earn: Only display commission rates once earnings data is received.

- client/my-sites/earn/memberships/index.jsx
Ecommerce plans on dotcom are charged a commission rate of 0%, which will not properly display with the recently-added #45373. This PR corrects the check to allow a `0` value for `earnings.commission`.
* Sandbox the API and apply D49085-code.
* Go to `/earn/payments/:site`, where the site has a plan other than eCommerce and a connected Stripe account.
* Verify the [commission amount](https://wordpress.com/support/wordpress-editor/blocks/payments/#related-fees) displayed is correct.
* Load the same page with a site on an eCommerce plan and Stripe connected.
* Verify the 0% commission is properly displayed.
Fixes #45304
> Earn: Properly display commission values of 0.

- client/blocks/support-article-dialog/dialog.jsx
- client/components/inline-support-link/index.jsx
* Fix post key memoizing problem in inline support articles link that results in all links opening a dialog with the same article as the firs link that was open
* Fix inline support link `onMouseOver` handler warning
* Can be tested on calypso.live build
* Open multiple inline support article links and confirm each link opens the article dialog with the correct article
Fixes p1599239124018500-slack-i18n-chatter
> Inline Support Articles: Fix memoizing issue

- client/extensions/woocommerce/app/dashboard/required-plugins-install-view.js
We had a report in Slack that the Store on WordPress.com setup flow was no longer functional. While the feature is not actively promoted, one can still enter in this UI for Woo through the following:
- On a Business Plan site, trigger transfer to AT by installing WooCommerce
- Then the "Store" link in the calypso sidebar directs users to the Store on WordPress.com UI.
- The Setup flow here requires that the site also has `woocommerce-services` installed, and that is what is currently broken.
From what I could see, it seems the data from the wp.org repository wasn't being returned in time for the call to install the `woocommerce-services` plugin, so for this fix I instead just created the object that is needed for the `installPlugin` flow. This remedies the problem, and seems like a valid …
> Store: Fix plugin install on Store/Woo feature.

- client/components/activity-card/style.scss
- client/components/jetpack/log-item/style.scss
- client/components/jetpack/threat-item-subheader/style.scss
- client/components/jetpack/threat-item/style.scss
- client/landing/jetpack-cloud/style.scss
* Implement sharp corners on all cards
* Implement 3px border radius on buttons
p6TEKc-3Pn-p2#comment-8096
* Use `yarn run start-jetpack-cloud`  and add `jetpack.cloud.localhost` to your hosts file
* Visit: http://jetpack.cloud.localhost:3000/
* Test the following changes:
**Before cards:**
**After cards:**
**Before badges:**
**After badges:**
**After buttons:**
Possible enhancement could be to move these to some CSS variables?
> Border radius changes for cloud.jetpack.com

- client/my-sites/checkout/composite-checkout/test/composite-checkout.js
- client/my-sites/checkout/composite-checkout/use-prepare-product-for-cart.js
* Make it possible to pass more than one product in the URL. Currently, our composite checkout module doesn't support a URL like `/checkout/:site/jetpack_backup_daily,jetpack_scan`. This PR attempts to change that by making the checkout logic work with multiple products separated by comma.
* Only multiple products can be added to the cart, not plans. Plans must be purchased individually.
* Run this PR.
* Pick a self-hosted Jetpack site.
**Single product in the URL**
* Visit `http://calypso.localhost:3000/checkout/:site/jetpack_backup_daily`.
* Verify that the cart contains Jetpack Backup Daily and nothing else. 
* Remove everything from the cart. 
**Two products in the URL**
* Visit `http://calypso.localhost:3000/checkout/:site/jetpack_backup_daily,jetpack_scan`.
* Verify that the cart …
> Composite Checkout: allow passing more than one product in the url

- .github/CODEOWNERS
Add experimentation platform paths to CODEOWNERS so that @Automattic/experimentation-platform would get pinged for review when these files change.
> Add experimentation platform paths to CODEOWNERS

- test/e2e/lib/gutenberg/gutenberg-editor-component.js
- test/e2e/specs/wp-calypso-gutenberg-coblocks-spec.js
- test/e2e/specs/wp-calypso-gutenberg-post-editor-spec.js
https://github.com/Automattic/wp-calypso/pull/45345 had been merged before we released Gutenberg 8.9 and it had GB 8.9-specific changes. We needed to revert here: Automattic/wp-calypso#45394. This basically "merges" https://github.com/Automattic/wp-calypso/pull/45345 again.
> Re-merge "[E2E] Embed block fixes"

- client/layout/masterbar/masterbar.jsx
- config/client.json
- config/desktop-development.json
- config/desktop.json
- config/development.json
- config/horizon.json
- config/production.json
- config/stage.json
- config/test.json
- config/wpcalypso.json
* adds the feature flag `nav-unification` which is `true` for Development and `false` for the rest of environments
* In local environment run the following in the console `window.configData.features["nav-unification"]` , it should return `true`
* In calypso live run the following in the console `window.configData.features["nav-unification"]`, it should return `false`
Fixes #45392
> Nav Unification: Add feature flag

- client/landing/gutenboarding/onboarding-block/plans/index.tsx
It causes inconsistent loading times between steps. We should load plans data asynchronously instead. 
Demo by (@razvanpapadopol): https://cloudup.com/c5GDAShZlNK
> Revert Plans step lazy loading

- apps/editing-toolkit/editing-toolkit-plugin/common/data-stores/launch/actions.ts
- apps/editing-toolkit/editing-toolkit-plugin/common/data-stores/launch/index.ts
- apps/editing-toolkit/editing-toolkit-plugin/common/data-stores/launch/reducer.ts
- apps/editing-toolkit/editing-toolkit-plugin/editor-gutenboarding-launch/index.ts
- apps/editing-toolkit/editing-toolkit-plugin/editor-site-launch/src/launch-steps/plan-step/index.tsx
- apps/wpcom-block-editor/src/calypso/features/iframe-bridge-server.js
- client/gutenberg/editor/calypsoify-iframe.tsx
- client/landing/gutenboarding/hooks/use-step-navigation.ts
- client/landing/gutenboarding/onboarding-block/plans/index.tsx
- client/landing/gutenboarding/stores/onboard/actions.ts
- client/landing/gutenboarding/stores/onboard/reducer.ts
- packages/plans-grid/package.json
- packages/plans-grid/src/plans-grid/index.tsx
D49228-code should be merged to publish `wpcom-block-editor` changes.
* Add support for experimental features in Site Setup.
* Use `debug` to log if the plans-grid is in experimental mode.
- Go to `/new?fresh&latest`
- Open browser console and run `localStorage.setItem( 'debug', 'plans-grid' )` and then refresh.
- When reaching Plans step (or by opening PlansModal), the following debug message should be logged: `plans-grid PlansGrid experimental version is active`
- Sync wpcom-block-editor and Editing toolkit to your sandbox
- Create a site starting from `/new`. You should land in the editor.
- Sandbox the site and widgets
- Run the same debug command in console for `page.php`  
- Add `?latest` query param to the URL and refresh the page.
- Click on Complete Setup button to start Site …
> Gutenboarding: add experimental features to Site setup

- apps/wpcom-block-editor/src/calypso/features/iframe-bridge-server.js
- client/gutenberg/editor/calypsoify-iframe.tsx
This PR passes the `ports` objects into the `data` object _and_ within the transferables array. I just learned that this is how [the API is meant to be used](https://developer.mozilla.org/en-US/docs/Web/API/Worker/postMessage#Main_thread_code:~:text=%2F%2F%20The%20array%20buffer%20that%20we%20passed%20to%20the%20transferrable%20section%203%20lines%20below).
The transerrables array elements are "neutered" (made unusable in the sender window) then their ownership is transferred to the target window, in order to access those elements, they still need to be passed within the `data` object. If you pass objects within the `data` object that are not neutered/transferred, you won't be able to access these objects in the target window. Neither transferring them only won't give you access to use …
> Pass ports within data for more predictable messaging API functionality

- client/landing/jetpack-cloud/sections/pricing/style.scss
- client/sections.js
- client/server/pages/index.js
- client/state/document-head/reducer.js
- client/state/document-head/test/reducer.js
This PR updates the styles of the pricing page in cloud, mostly to match jetpack.com typefaces.
Fixes 1169247016322522-as-1191918158300076
- Run Jetpack cloud and visit `/pricing`.
- For developers: check the code and that the page doesn't look broken.
- For designers: check that the page matches what's expected. Parts of the mockups seemed a bit outdated, so I used my best judgement.
-
> Update cloud pricing page styles

- client/components/search/style.scss
* Noticed by @sirreal, this fixes a visual bug introduced by #44939 where the child elements of a search input (search icon, text input, close icon) had rounded corners. This was most noticeable when using a color scheme with a dark sidebar background color, like Sunset.
**Before**
**After**
* Switch to this PR and change your dashboard color scheme under Me -> Account settings to something with a dark background, like Midnight or Sunset.
* Go to My Sites and open Switch sites at the top of the left sidebar.
* You should see a solid search input field. Type something into the field; it should remain one solid background color with no rounding of the icons or text input.
* Look at other instances of the search field across Calypso; Pages, Posts, Reader, etc. to make sure this doesn't cause …
> Search: Fix border radii on search inputs

- client/lib/wpcom-undocumented/lib/undocumented.js
In order to match changes made for the DNS update endpoint, we no longer want to filter out the deleted DNS records before posting the data to the endpoint. This will be handled within the endpoint code now.
See D49122-code
Apply the back-end patch and try making various DNS updates from the DNS management page. Double-check the DNS values on the server. Make sure the changes match.
Make sure you try adding/removing custom A records as well.
> Don't filter the deleted DNS records from the returned data

- client/my-sites/plans-v2/plans-header.tsx
- client/my-sites/plans-v2/style.scss
If user is coming to the plans page from the in-place flow, The plans page header shows:
1. A notification to the top of the page with check icon  and message "Jetpack is now connected. Next select a plan"
2. Main heading that reads, "Explore our Jetpack Plans" 
3. Subheading that reads, "Now that you're set up, pick a plan that suits your needs."
Otherwise, show the standard Plans page header.
Fixes: 1169247016322522-as-1189571103989169
1. Go to the Jetpack Dashboard in wp-admin of your Jurassic Ninja site.
2. Select the "Plans"  tab/link, this will take you to the 'Plans' page on wp.com. (Make sure you have _offerResetFlow A/B_ test enabled)  OR  You can just add `?source=jetpack-plans` to the plans page URL, for example: `http://calypso.localhost:3000/plans/:SITE/?source=jetpack-plans` …
> Jetpack Offer Reset: Show different plans page Header if coming from in-place connection flow.

- client/components/jetpack/card/jetpack-bundle-card/style.scss
- client/components/jetpack/card/jetpack-plan-card/style.scss
- client/components/jetpack/card/jetpack-product-card/index.tsx
- client/components/jetpack/card/jetpack-product-card/style.scss
* Make all badges look the same (gray) except the one used for a featured/highlighted product card.
* Run this PR.
* Visit the `/plans` section.
* Make sure all badges are gray except the one used for the featured Jetpack Security card.
* Try purchasing different plans and products to see all of them in action. The list of possible badges are: "Your Plan", "You own this", "Included in your plan", and "Best Value".
Fixes #
> Offer Reset: improvements to product card badges

- client/my-sites/checkout/composite-checkout/record-analytics.js
The `calypso_checkout_composite_error` Tracks event (added by https://github.com/Automattic/wp-calypso/pull/45241) is triggered when there is an unexpected error while trying to record an event (possibly an error report itself). However, the error reporting in that fallback event is very basic and doesn't necessarily let us find out what caused the issue.
This change adds additional data about the action being processed and also logs the error to Tracks, which collects additional data on its own.
- Cause an error by following the [instructions here](https://github.com/Automattic/wp-calypso/pull/45241#pullrequestreview-478956393).
- Verify that the error is reported with the action `type` and `payload` (the payload is likely to be unreadable but that's expected; it's hard to know how to …
> Checkout: Add the action data to `calypso_checkout_composite_error`

- client/blocks/reader-list-item/index.jsx
- client/blocks/reader-subscription-list-item/index.jsx
- client/reader/lib/feed-display-helper/index.js
While working on https://github.com/Automattic/wp-calypso/pull/45348, I noticed that in Reader we have three functions called `formatUrlForDisplay` and that they format things slightly differently (some with `www.`, some without).
For consistency's sake and to DRY things up, I have settled on a single implementation.
Ensure your subscriptions load correctly at http://calypso.localhost:3000/following/manage.
> Reader: consolidate use of formatUrlForDisplay

- apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nav-sidebar/src/components/create-page/index.tsx
- apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nav-sidebar/src/components/nav-item/index.tsx
- apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nav-sidebar/src/components/nav-sidebar/index.tsx
- apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nav-sidebar/src/components/toggle-sidebar-button/index.tsx
Adds tracking events for
* When the sidebar is opened
* When the user goes back to the dashboard, closing the editor
* When the user navigates to an existing post/page
* When the user clicks on "add a new post/page"
* When sidebar is dismissed
* Add diff D49173-code to your sandbox for testing
* open dev tools  and paste this in console: localStorage.setItem('debug', 'calypso:analytics');   this will allow verification of analytics in the dev tools console
* Some events can't be viewed in the console due to a page load, in this case verify the even in Tracks: 
**Open sidebar**
* click the (W)
* Verify `calypso:analytics Recording event "calypso_editor_sidebar_open" ` in dev tools console
**Close editor / back to dashboard** 
* When sidebar is open
* click All Posts (or All Pages)
*Verify …
> EditingToolkitSidebar: add tracking events

- apps/editing-toolkit/editing-toolkit-plugin/coming-soon/coming-soon.php
- apps/editing-toolkit/editing-toolkit-plugin/coming-soon/fallback-coming-soon-page.php
- apps/editing-toolkit/editing-toolkit-plugin/full-site-editing-plugin.php
* Gate feature behind a `WPCOM_PUBLIC_COMING_SOON` config flag
* Render coming soon page if `wpcom_public_coming_soon` is `1` and user isn't a logged in site user
* Render `wpcom_public_coming_soon_page_id` if it exists
* Render a fallback coming soon page if `wpcom_public_coming_soon_page_id` doesn't exist
Based off @simison's prototype #43831
What it doesn't do:
* check if the page is published
* check if it's a post vs. a page, maybe this doesn't matter?
* Checkout branch and `cd apps/editing-toolkit && yarn dev`
* Add `"WPCOM_PUBLIC_COMING_SOON": "1"` to your `.wp-env.override.json`
* `npx wp-env start`
* Visit `http://localhost:4013/wp-admin` and create a coming soon page in the block editor
* `npx wp-env run cli wp option add wpcom_public_coming_soon 1`
* Visit …
> Coming Soon: Render a coming soon page if the user is logged out

- client/components/domains/register-domain-step/index.jsx
- client/lib/domains/registration/availability-messages.js
There were some issues with how we handle the availability responses for premium domains we don't support so here's a fix.
* Updated the notification copy for available premium domains we don't support (see screenshot) because the old one imposed that we don't support any premium domains
* Properly handle `available_premium` status responsed from the availability endpoint for FQDNs searches and for the availability pre-check
* Apply D48991-code
* Enter a premium .blog domain in the search box in Calypso domain search - no notification should be shown and the domain should be displayed as suggestion. Try clicking on it - it should be added to your cart.
* Enter a premium domain that's not .blog - verify that we show the proper message.
* Try looking for premium that's not .blog but that's …
> Update how we handle premium domains for TLDs we don't support

- client/components/domains/domain-registration-suggestion/index.jsx
When there is domain sale we don't want that price to be applied to premium domain suggestions
* Update how we populate the `productCost` and `productSaleCost` for premium domain suggestions
* In order to test this you need to follow the instructions in D48774-code
> Fix how premium domain suggestions are rendered when there is domain sale active

- client/my-sites/plans-v2/product-card/index.tsx
The price at the top of the Search product card has initially been removed, since the pricing tier was displayed in the body of the card. However, when no site is selected, this pricing tier doesn't exist and the product card is left with no mention of the price. This PR fixes that.
- Download the PR and run Calypso locally
- Visit the _Plans_ page with the offer reset flow enabled, and select the _Performance_ option
- Check that you see the pricing tier in the body of the Search card (see capture)
- Visit `/jetpack/connect/store`
- Check that you see no pricing tier in the body of the Search card, and that you see that starting price at the top (see capture)
- Run Jetpack cloud (you can run it concurrently to Calypso with `yarn start-jetpack-cloud-p`) and visit `/pricing`
- Check that …
> Show the price in Search product card when no site is selected

- client/landing/jetpack-cloud/sections/pricing/style.scss
- client/my-sites/plans-v2/plans-filter-bar/index.tsx
Title sums it up. On desktop, the filter bar in the pricing page of Jetpack cloud is now sticky as you scroll.
- Run Calypso with this PR locally, with the offer reset flow enabled
- Visit `/plans` and check that the filter bar behaves as before, both on desktop and mobile
- Visit `/jetpack/connect/plans` and check that the filter bar behaves as before, both on desktop and mobile
- Run Jetpack cloud (you can run it concurrently to Calypso with `yarn start-jetpack-cloud-p`)
- Visit `/pricing` and check that the filter bar is sticky both on mobile and desktop as you scroll
> Make filter bar sticky in cloud pricing page on desktop

- client/my-sites/hosting/php-version-card/index.js
We're deprecating PHP 7.2, as it's EOL is 20th November 2020.
- Load an Atomic site with PHP version 7.2
- Make sure it shows as selected
- Update PHP version to 7.3/7.4
- Make sure no more 7.2 in the dropdown
> Atomic: Disable PHP 7.2

- packages/plans-grid/src/plans-table/plan-item.tsx
- packages/plans-grid/src/plans-table/style.scss
- packages/plans-grid/src/types-patch.ts
* Replace bulb icon with cross icon when displaying a message for disabled plan in Site setup flow.
* Build Editing Toolkit locally with the updated `@automattic/plans-grid` package and sync it to sandbox following guide at PCYsg-ly5-p2
* Create a site starting at [wordpress.com/new](https://wordpress.com/new)
* Sandbox the site.
* Click on _Complete Setup_ button to start Site setup flow.
* Pick a custom domain from _Select a domain_ step.
* Go to _Select a plan_ step and you should see the disabled message for the Free plan.
> Site setup: bulb with cross icon for disable plan message.

- client/landing/gutenboarding/gutenboard.tsx
- client/landing/gutenboarding/hooks/use-track-onboarding-start.ts
- client/landing/gutenboarding/lib/analytics/index.ts
- client/landing/gutenboarding/stores/onboard/actions.ts
- client/landing/gutenboarding/stores/onboard/index.ts
- client/landing/gutenboarding/stores/onboard/reducer.ts
- packages/data-stores/src/user/types.ts
* Add `site_count` prop to `calypso_signup_start` and `calypso_newsite_start` tracks events.
* Go to `/new` in a browser where you are logged in.
* Open console and run `localStorage.setItem('debug', 'calypso:analytics')` to log tracks events.
* Go to `/new?fresh`
* `calypso_signup_start` and `calypso_newsite_start` events should fire with prop `site_count: [your number of sites]`
* Refresh the page or open `/new` in another tab. No `*_start` event should fire unless local storage is cleared or a site is created.
* Repeat the steps above in a browser where there is no logged in user. `site_count` should be `0`.
> Gutenboarding: add site_count to signup start events

- client/my-sites/checkout/composite-checkout/payment-method-helpers.js
- client/my-sites/checkout/composite-checkout/payment-method-processors.js
- client/my-sites/checkout/composite-checkout/payment-methods/credit-card/credit-card-pay-button.js
- client/my-sites/checkout/composite-checkout/payment-methods/ebanx-tef.js
- client/my-sites/checkout/composite-checkout/record-analytics.js
- client/my-sites/checkout/composite-checkout/types/backend/shopping-cart-endpoint.ts
In addition to some new events of its own, new checkout duplicates the same analytics events as old checkout, including several events when a payment is complete that expect the cart total to be in the (now deprecated) decimal form. That is, USD $50 is now used internally as 5000, but these events would prefer it was 50.00. Originally we solved this by dividing the total by 100, and we planned to replace it when we opened up support in new checkout for international currencies, but it was overlooked.
This change replaces that calculation with the deprecated decimal data still returned by the shopping-cart endpoint.
Fixes https://github.com/Automattic/wp-calypso/issues/45415
- Run `localStorage.setItem('debug', 'calypso:analytics')` in your browser console and reload the …
> Checkout: Use the total_cost cart field for the PAYMENT_COMPLETE analytics

- client/my-sites/checkout/composite-checkout/record-analytics.js
If they have the key `type`, it will be overridden by the actual type.
This is a follow-up to https://github.com/Automattic/wp-calypso/pull/45471 which added new properties to the `calypso_checkout_composite_error` Logstash event so that we can determine the action type that caused the error. However, in that PR I used the key `type` for the action type, which is then immediately overridden by the `type` of the logstash event.
This PR renames the `type` to `action_type` so that it will be preserved.
- Cause an error by following the [instructions here](https://github.com/Automattic/wp-calypso/pull/45241#pullrequestreview-478956393).
- Verify that the error is reported with the action `action_type` and `action_payload` (the payload is likely to be unreadable but that's expected; it's hard …
> Checkout: Rename analytics action props for calypso_checkout_composite_error

- client/jetpack-connect/controller.js
- client/jetpack-connect/index.js
- client/my-sites/plans-v2/utils.ts
- client/state/jetpack-connect/constants.js
* Make it possible to purchase products from the new pricing page.
* I simplified, I believe, the Connect Flow by removing a couple of paths. Now Search products follow the same route that the rest of the products follow.
* I made the Connect Flow support two products in the URL (only for a specific set of them). In #45418, we made the Composite Checkout support passing two products in URL.
* In the Plans grid, if there is no site slug, instead of redirecting users to the checkout page, we redirect them to `jetpack/connect/:items`, since from there users will be asked for a site and to log in if needed.
* Run this PR in one terminal with `yarn start`. Once that finishes, open another terminal window/tab and run `yarn start-jetpack-cloud-p`. We need both builds working at the same time.
* …
> Offer Reset: integrate Pricing page with Jetpack Connect flow

- client/landing/jetpack-cloud/sections/pricing/jpcom-masterbar/style.scss
- client/my-sites/plans-v2/style.scss
This PR updates the styles of the menu and hides the divider in the pricing page on mobile.
- Run Jetpack cloud locally
- Visit `/pricing`
- Check that you see what's in the mockups below
_Before_
_After_
_Before_
_After_
_Before_
_After_
_Before_
_After_
> Minor style updates to cloud pricing page on mobile

- client/my-sites/checkout/composite-checkout/use-prepare-product-for-cart.js
`usePrepareProductsForCart` waits for all the required data to load before trying to generate its output, but it's possible for a render to occur when `isProductsListFetching` returns false but `getProductsList` is still empty (I think this is just because they are different parts of Redux state and sometimes one has updated before the other?). Most of the parts of `usePrepareProductsForCart` account for this and check that both `isProductsListFetching` is false and `getProductsList` is not empty, but that guard is not in place in `useAddRenewalItems`.
In this PR, we add that guard to `useAddRenewalItems` also.
props to @DavidRothstein for figuring out how to reproduce this bug!
- Start Calypso with `ENABLE_FEATURES=force-sympathy yarn start` to prevent caching.
- Make sure your shopping …
> Checkout: Wait for products to be fetched before preparing renewals

- client/lib/cart-values/types.ts
- client/my-sites/checkout/composite-checkout/add-items.ts
- client/my-sites/checkout/composite-checkout/composite-checkout.js
- client/my-sites/checkout/composite-checkout/hooks/use-fetch-products-if-not-loaded.ts
- client/my-sites/checkout/composite-checkout/hooks/use-prepare-products-for-cart.ts
- client/my-sites/checkout/composite-checkout/use-prepare-product-for-cart.js
This PR converts the `usePrepareProductsForCart` hook in checkout and its associated code to TypeScript. This should have no functional change, although it may indeed fix several edge case bugs since it adds more guards that were not present before.
Depends on https://github.com/Automattic/wp-calypso/pull/45518
- Visit checkout with a URL that includes a plan, eg: `/checkout/example.com/premium`
- Verify that checkout loads with that product in the cart and that there are no errors.
- Once a product is in the cart, visit checkout again with a URL that does not include a product, eg: `/checkout/example.com` and verify that the product remains and that there are no errors.
- Visit checkout with a URL that includes a non-plan product, eg: `/checkout/example.com/theme:ovation`
- Verify that …
> Checkout: Convert usePrepareProductsForCart to TypeScript

- docs/monorepo.md
- packages/social-previews/CHANGELOG.md
- packages/social-previews/README.md
- packages/social-previews/package.json
Version bump for the `@automattic/social-previews` package, to release the changes implemented in #44956.
> @automattic/social-previews 1.1.0

- apps/editing-toolkit/package.json
After the `build` script it checks the output files to make sure they are ES5 compatible.
Since IE11 doesn't support ES6 we need to make sure all the output files are ES5 compatible.
Make sure build doesn't fail.
> Editing Toolkit: Add ES5 check

- client/lib/abtest/active-tests.js
~* Changes the locale targets of the `reskinSignupFlow` test to `en, es`.~
* Pauses the test by setting the datestamp to the future.
* Make sure you're not assigned to reskinned group of reskinSignupFlow a/b test.
* Check this for EN/ES locale and any other locale.
> Signup Reskin: Pauses the test

- client/my-sites/plans-v2/selector.tsx
Follows up on #45384.
* For new Tracks events on the Plans page, set the `site_id` parameter to `undefined` if it's null, excluding it from the outgoing request.
Testing steps are similar to #45384. For the following scenarios on cloud.jetpack.com/pricing, verify that `site_id` is not included in the outgoing Tracks request, since no site is selected in that context.
* Visit the Pricing page on Jetpack Cloud in your testing environment.
* Open your browser's DevTools window to the **Network** panel and monitor for **Image** requests.
* Select different values in the Duration toggle. Verify that for each change in value, a request goes out to `t.gif`, and that `site_id` is not part of the query string parameters.
* Select different values in the Type dropdown. Verify that for each change …
> Plans: Exclude site_id in Tracks events when no site is selected

- client/landing/jetpack-cloud/sections/pricing/controller.tsx
- client/landing/jetpack-cloud/sections/pricing/index.ts
- client/sections.js
This PR allows to display the pricing page in the locale specified in its URL.
The goal is, as users navigate through jetpack.com in their language, to not break their experience and show them the new pricing page in the same language (the pricing page lives in cloud.jetpack.com, not jetpack.com).
Fixes 1169247016322522-as-1191918158300069
In jetpack.com, the locale is represented in URLs by a subdomain, e.g. `fr.jetpack.com`. The idea is to redirect the URL `fr.jetpack.com/pricing` to `cloud.jetpack.com/fr/pricing`.
- Download the PR locally and run Jetpack cloud
- Visit `/pricing`
- You should see the page in the language set in your Calypso preferences
- Visit `/fr/pricing`, or use any other locale you're familiar with
- Check that the page is displayed in this language (**note: all …
> Add locale to pricing page URL (in cloud)

- client/my-sites/customer-home/cards/tasks/site-setup-list/index.jsx
* Add a unique key to each return statement by using `Fragment`
Attempts to fix the following console error
* Check out this branch locally
* `yarn && yarn start`
* Create a new free site
* Go to https://wordpress.com/home for that site
* Open the console
* You should not get the following error
> SiteSetupList: add a unique key to each return statement

- client/landing/jetpack-cloud/sections/pricing/controller.tsx
- client/landing/jetpack-cloud/sections/pricing/index.ts
* When a locale is present in the `/:locale?/pricing` URL, set the locale in Calypso, and then redirect the user to `/pricing`. 
* Run this PR (Jetpack cloud version).
* Visit `http://jetpack.cloud.localhost:3000/pricing/` and move around the flows to verify that everything work as expected.
* Visit `http://jetpack.cloud.localhost:3000/:locale/pricing/`, where `:locale` can be any of the supported languages (e.g.: `en`, `de`, `fr`, `es`).
* Verify that you were redirected to `http://jetpack.cloud.localhost:3000/pricing/`.
* Verify that the app kept the locale and didn't revert to English.
* Move around the page and verify that you can see the details and upsells pages.
Fixes a small bug introduced in #45545
> Offer Reset: redirect to /pricing when locale is included in the URL

- client/signup/controller.js
* Do not redirect the `clone-site` flow to gutenboarding
See JPOP issue 5493
* Open WP.com in staging
* Hover over the bug in the bottom right, click on abtests, and ensure that `gutenberg` is selected for the `existingUsersGutenbergOnboard` test
* Go to wordpress.com/start/clone-site/$site, where $site is any connected Jetpack site
* Verify that you are redirected to wordpress.com/new
* Checkout PR
* Follow steps to make sure test is selected correctly
* Go to calypso.localhost:3000/start/clone-site/$site as above
* Ensure that you see some UI to start the cloning process
Fixes #
> Start: Do not redirect site-clone flow to gutenboarding

- apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nav-sidebar/src/attach-sidebar.tsx
The sidebar nav is active in the editor when fullscreen mode is off. It looks strange. We decided to disable it in that context. See the discussion over at: p1599758388052500-slack-CHN6J22MP
Current behaviour: https://d.pr/v/6Swgs8/dFhe2qqkHd
This change disables the sidebar when NOT in fullscreen mode.
Apply D49396-code and sandbox your test site.
From `{yourtestsite}/wp-admin/`, open a new post. 
Toggle Fullscreen mode and check that the sidebar is disabled when fullscreen mode is off.
Then look at this random photo:
Fixes #
> Editing Toolkit Sidebar: Disable if the editor is not in fullscreen mode

- client/my-sites/checkout/composite-checkout/components/wp-order-review-line-items.js
- client/my-sites/plan-features/header.jsx
- client/my-sites/plan-features/index.jsx
- client/my-sites/plan-features/style.scss
- client/my-sites/plan-features/test/header.jsx
- client/my-sites/plan-features/test/index.jsx
- client/my-sites/plans-features-main/style.scss
- client/state/plans/selectors/get-discounted-raw-price.js
- client/state/plans/selectors/index.js
- client/state/plans/selectors/test/index.js
I'm working on adding a first-year only promotional discount in 3 currencies. When a 1-st year discount is available, it should modify the discount fields and the plan prices, and display them on /plans, checkout, and the cart. A problem appeared while testing that this 1st-year discount causes `/plans` and `/sites/plans` to return different values for these discounts.
This change proposes a fix that would lead to reading both the price and the discount from /sites/plans as opposed to reading the price from /plans and the discount from /sites/plans if a `siteId` is available.
The plans and sites/plans selectors use inconsistent naming and inconsistent arguments. I didn't attempt to address that. I think it should be done with a separate change if time allows. These selectors should have …
> Adjust discount calculation in /plans

- client/components/search/index.jsx
Input component in the search bar of the language picker has been replaced with `FormTextInput` component in https://github.com/Automattic/wp-calypso/pull/45358. As a result, the `this.searchInput` reference is being set to the component instead of the input DOM element, which is throwing error when trying to access `this.searchInput.blur()`
* Use `inputRef` ref proxy prop to set reference to the input element in the language picker search bar.
**Before:**
**After:**
* Go to Account Settings `/me/account` and open language picker.
* Start typing text that would return language items, e.g. `French`
* Click on the close button next to the search field and confirm it blurs the field and closes the search bar.
> Language picker: Fix input element ref

- client/components/language-picker/modal.scss
* Use lighter link color for links in language picker items' tooltips to improve readability.
**Before:**
**After:**
* Go to Account Settings `/me/account` and open language picker.
* Hover over language item with tooltip.
* Confirm lighter link color reads better across different color schemes.
> Language Picker: Use lighter color for links in language item tooltip

- client/blocks/inline-help/admin-sections.js
- client/components/site-selector/add-site.jsx
- client/jetpack-connect/index.js
- client/me/account-close/confirm-dialog.jsx
- client/my-sites/sidebar/index.jsx
- test/e2e/specs/wp-signup-spec.js
* Change links that are pointing to `/jetpack/new` to link directly to the dotcom site creation flow without any intermediate steps
* Redirect from the `/jetpack/new` page to dotcom site creation flow (aka `/start`)
There are 4 places where the user can choose to create a new site and is currently sent to the `/jetpack/new` page:
* Log in to calypso (user needs to have more than 1 site)
* Click on "Switch site" at the top of the left sidebar
* Scroll the sidebar content all the way to the bottom
* Click on the "Add new site" link
* The button should take to the dotcom site creation flow without any intermediate steps (i.e. no Jetpack modal shown)
* Log in to calypso (user needs to have only 1 site)
* Click on the "Add new site" link at the bottom of the left sidebar
* The button should …
> Skip Jetpack "New Site" screen when creating a new site

- apps/editing-toolkit/package.json
- yarn.lock
Remove `swiper` dependency.
Swiper was added by https://github.com/Automattic/wp-calypso/pull/30352/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R194 but those blocks were moved to Jetpack in https://github.com/Automattic/wp-calypso/pull/31759/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2 .
We are still using `swiper` for building `newspack-blocks` in `editing-toolkit` but since we have `newspack-blocks` as a dependency (which has `swiper` as a dependency) we still have access to `swiper`. It doesn't need to be included in the `package.json`. This also makes sure we use the correct version of `swiper`.
I was thinking about adding it as a peer dependency, but then we should do it for every dependency of `newspack-blocks`.
> Editing Toolkit: Remove swiper dependency

- client/lib/abtest/active-tests.js
- client/my-sites/checkout/checkout/index.jsx
- client/my-sites/checkout/composite-checkout/test/composite-checkout-thank-you.js
- client/my-sites/checkout/composite-checkout/use-get-thank-you-url.js
* This PR implements the Plan offer tested here pbxNRc-lW-p2
- Signup for a new account.
- Add a Premium plan to cart and complete the purchase
- Verify the following:
- That you are shown the Business upgrade upsell
- That there's no `showBusinessPlanBump` test.
With other plans you should not see this offer, but either no offer or the QS offer.
> Implementing Business plan bump offer

- client/lib/abtest/active-tests.js
- client/signup/controller.js
- config/production.json
- config/stage.json
* Enable feature picker and PlansGrid accordion in production
* Update signup controller to run Gutenboarding test only for 'onboarding' flow
* Update `existingUsersGutenbergOnboard` A/B test datestamp
* Go to https://calypso.live/?branch=update/gutenboarding-enable-feature-picker
* Open console and run `localStorage.setItem( 'ABTests', '{"existingUsersGutenbergOnboard_20200910":"gutenberg"}' )`
* Go to `/start` => you should be redirected to /new
* Go to `/start/rewind-auto-config` or `/start/` + [[any other flow](https://github.com/Automattic/wp-calypso/blob/master/client/signup/config/flows-pure.js)] => no redirect
Fixes #45232
> Gutenboarding: release Feature picker and plan recommendation

- client/blocks/inline-help/popover.jsx
* Remove all editor switching related code from Inline Help Popover.
After the deprecation of the WordPress.com (Classic/Calypso) Editor, we can remove the ability to switch editors from the inline help popover. #41106
_Note: To see the switch editor button within the inline help popover prior to applying this PR branch, you need a user for whom the classic editor has not been deprecated. This can be done using WPSH to toggle the `editor_deprecation_group` user attribute to false. Just don't forget to set it back to true after testing._
* Checkout this PR
* Edit a post
* Open the inline help popover by clicking the FAB in the bottom right
* Confirm that there is no means within that popover to switch editors at all
* Confirm that searching and results still work
* Test that the contact …
> Editor Deprecation: Remove all editor switching from inline help popover

- test/e2e/README.md
- test/e2e/docs/miscellaneous.md
Document the workaround to fix the "`chromedriver` not found" error encountered when running e2e tests locally.
A separate PR will be opened to work on a better fix (as highlighted in https://github.com/Automattic/wp-calypso/issues/45537#issuecomment-690105075)
Partially covers #45537
> Docs: add "chromedriver not found" workaround

- client/landing/gutenboarding/stores/onboard/reducer.ts
* Reset feature selection after creating a site
* Go to [/new](https://calypso.live/new?branch=update/gutenboarding-feature-picker-reset-selection)
* Create a site after selecting some features
* Go to [/new](https://calypso.live/new?branch=update/gutenboarding-feature-picker-reset-selection) again
* When reaching Features step, no feature should be selected
> Gutenboarding reset selected features on site creation

- client/assets/stylesheets/_nav-unification.scss
- client/assets/stylesheets/style.scss
- client/layout/index.jsx
- config/development.json
This is PR is a first step towards implementing the changes to the masterbar suggested in https://github.com/Automattic/wp-calypso/issues/45393.
Current PR state compared to wp-admin (in code-D49342):
This is a prototype and it's hidden behind a feature flag. We'll continue iterating on it.
As the prototype uses an additional class for scoping some styles of other masterbar states like support session and jetpack will be overridden due to the increased specificity. This is expected for this prototype. 
When Calypso loads you'll see an initial flash of the app shell with the old nav styles. This is because we're using a feature flag to attach a class to the layout that gets processed once the client side JS kicks in. Once we move the styles to be the default, the app shell will look like …
> Nav Unification: Update masterbar

- client/lib/abtest/active-tests.js
- client/lib/cart-values/cart-items.js
- client/my-sites/checkout/composite-checkout/use-get-thank-you-url.js
Per the request in pbBQWj-hz-p2#comment-997, we are dialling up the concierge upsell offers. It will now be shown to 75% of EN.
Business user will now be added to the upsell offers.
Go through the signup flow at /start and purchase a:
- Personal or Premium plans to check for regression.
- Business plan to check that it now also show the upsell.
When in the "offer" variation, you should be shown the concierge upsell. When in "noOffer" variation, you should not be shown the upsell.
> Dial up concierge upsell offer and include Business plan

- client/my-sites/email/email-providers-comparison/index.jsx
We decided to use `Pick one of the options` instead of `Pick from one of the options`.
> Email: Update email provider comparison page copy

- client/lib/formatting/prevent-widows.js
- client/my-sites/customer-home/cards/features/stats/index.jsx
- client/post-editor/editor-deprecation-dialog/index.jsx
The card which warned users of the upcoming deprecation of the Calypso
editor had a message that ended with `<a...>Read more</a>.` The way we
were handling components when searching for spaces to replace with a
non-breaking space, meant we just took the last piece of text from the
array. In this case, that was a `.` and so a non-breaking space was never
added. If there was no `.` then the component would have been used,
but as it was not an array or a string, nothing would have happened.
This change reimplements the algorithm and recursively walks the tree of
strings and elements, working from the end, until the correct number of
substitutions have been made, or we run out of content.
There looks to be a possible bug in Firefox, that means in some
circumstances, word-wrap occurs still on …
> Prevent Widows: Handle interpolated components

- client/my-sites/plans-v2/upsell.tsx
* Fixes a small layout issue affecting the Upsell page. See the Demo section for a better representation of the problem.
* Run this PR with `yarn start-jetpack-cloud`.
* The error manifest when you move from the Details page to the Upsell, therefore, you need to select a product that has a both Daily and Real-time flavors, and includes an upsell to another product. At this moment, the only product that fits this description is Jetpack Backup.
* Move between the two pages and verify there is no change in the position of the master bar. You can repeat the exercise in production to see how the layout changes every time you visit the Upsell page.
Fixes 1169247016322522-as-1193281023077033
> Offer Reset: Move the header into the Upsell component

- client/layout/sidebar-unified/style.scss
- client/layout/sidebar/custom-icon.jsx
- client/my-sites/navigation/index.jsx
- client/my-sites/sidebar-unified/index.jsx
- client/my-sites/sidebar-unified/item.jsx
- client/my-sites/sidebar-unified/menu.jsx
- client/my-sites/sidebar-unified/switcher.jsx
- client/my-sites/sidebar/style.scss
- client/state/reducer.js
* My sites sidebar is driven off the state in admin-menu (see: #45495)
* WIP, But behind a feature flag (`nav-unification`)
* "My sites" sidebar acts the same if the feature flag is off
* Apply D49204-code
* Apply D49005-code
* Comment out the sticker check in admin-plugins/admin-menu.php
* Run calypso
* Visit http://calypso.localhost:3000/?flags=nav-unification
See: #45435
> My Sites sidebar: Show items from admin-menu state

- client/my-sites/pages/page/index.js
Following on from the bug identified in https://github.com/Automattic/wp-calypso/pull/45532, this is just a test to see if we can preload when the ellipses opens.
See #45532
> Pages: preloading editor when the ellipsis menu is opened

- apps/editing-toolkit/editing-toolkit-plugin/full-site-editing-plugin.php
Core patterns are added at `init` action.
https://github.com/WordPress/WordPress/blob/3dda74c3377243797ceffb429f94e0ea63ad6d75/wp-includes/default-filters.php#L304
We were using `plugins_loaded` action to add our patterns and remove core patterns. Since `plugins_loaded` runs before `init` action, core patterns weren't being removed.
This PR changes `plugins_loaded` to `init` with a priority of `20` so it runs after the core hook. Which means core patterns will be registered by this time and they will be removed successfully.
Testing locally
* run yarn dev
* cd to wp-calypso/apps/editing-toolkit
* run yarn wp-env start
* You should be able to access a WordPress instance at localhost:4013
* Make sure core patterns aren't present ( Except Two Columns of Text )
Fixes #44709
> Editing Toolkit: Load patterns after core patterns

- client/components/domains/domain-product-price/index.jsx
- client/components/domains/domain-product-price/style.scss
- client/components/domains/domain-registration-suggestion/index.jsx
- client/components/domains/domain-search-results/index.jsx
- client/components/domains/domain-suggestion/index.jsx
- client/components/domains/featured-domain-suggestions/index.jsx
- client/components/domains/register-domain-step/index.jsx
- client/lib/abtest/active-tests.js
- client/lib/signup/site-type.js
- client/signup/config/steps-pure.js
- client/signup/main.jsx
- client/signup/steps/domains/index.jsx
- client/state/signup/preview/selectors.js
* Remove all references to AB test initiated at #37661
1. In an incognito window, select a signup flow, for example the business flow : [/start/business](http://calypso.localhost:3000/start/business/)
2. Signup and go into the domain step
3. In another window login to an existing wordpress account and go to the [add domain page](http://calypso.localhost:3000/domains/add/dehan91.wordpress.com)
- An explanation on free domain should be visible only in the sign up flow
- Match indicator is a badge in the sign up flow while it is a progress bar  in the mysite flow with different texts as shown below
- Render match reasons should not be visible in the signup flow
- The renew text should be left or right aligned based on the flow 
- In the signup flow zeroes are removed from the domain price if …
> Remove variables and references to variables of the AB test parameter isEligibleVariantForDomainTest

- packages/domain-picker/jest.config.js
- packages/domain-picker/test/suggestion-item.tsx
When `domain-picker` was moved into packages it seems as though a `jest.config.js` was not moved/created with it. This means that existing tests in this package have become stale as the codebase has moved on whilst the tests have not been running.
Here I have skipped the existing test suite as they would fail anyway, and added a `jest.config.js` so any further work within this package can have working tests with it.
Another issue https://github.com/Automattic/wp-calypso/issues/45501 has been raised to refactor the existing stale tests.
* Adds `jest.config.js` to `domain-picker` package so tests are run on `npm run test-packages` in CI.
* Skips failing test suite as the tests in there are now stale as they've gone unmaintained for some time.
* Check out branch
* Run `npm run …
> Add jest.config.js to domain-picker package

- .circleci/config.yml
- desktop/bin/build-desktop-config.js
This PR restores the `CONFIG_ENV` variable, which was erroneously dropped during migration from the wp-desktop repo. Omitting this variable results in failure to create a valid auto-updater config. 
Unfortunately this part of the build process has been silently failing as the failure case in the `try/catch` logic of the supporting node script was not logged to the console (meaning that the auto-updater included in builds published to this repo so far have been invalid). 😞
> fix(ci): restore CONFIG_ENV variable

- client/my-sites/people/invite-people/index.jsx
- client/state/invites/reducer.js
* Fixes a bug that causes some invite links to display even when user has disabled all invites. (Reason: expired links were being loaded into state, when only unexpired links should be.)
* Fixes a small bug that fails to reset the busy state of the Generate button, which caused the button to appear busy even when not.
* Visit the **Invite People** section of a site with known expired invite links, like lighthousep2.
* If you see Invite Links, disable them using the `Disable invite link` link below the role selectors. Expected result: You should now see the Generate button again.
* If you don't see Invite Links, generate them, and then disable them. Expected result: You should always go back to the Generate button view when disabling links.
> P2 Invite Links: Filter out expired invites

- packages/components/CHANGELOG.md
- packages/components/package.json
- packages/components/src/button/README.md
- packages/components/src/button/docs/example.jsx
- packages/components/src/button/index.jsx
- packages/components/src/button/index.stories.jsx
- packages/components/src/button/style.scss
* Rename the `bare` prop to `plain` per the discussion in this PR: https://github.com/Automattic/wp-calypso/pull/45344
* Ensure plain button is working in the storybook
Fixes #
> Button: Rename bare button to plain

- apps/notifications/bin/wpcom-watch-and-sync.sh
- apps/notifications/package.json
* This PR adds a `yarn` script to the notifications app (`/apps/notifications/`) for syncing Calypso notification code changes to a WPCOM sandbox for server-side testing.
* Follow the prerequisite setup instructions for adding an SSH alias for your sandbox described in PCYsg-ly5-p2 "Editing Toolkit plugin and your WP.com sandbox"
* The process for this PR is roughly the same as that used for the Editing Toolkit plugin; this documentation will be adapted for the notification app once this change is approved.
* Make a change in `/apps/notifications/`
* CD into `/apps/notifications/` and run the command `yarn sync`.
* Verify that your change is reflected both in `/apps/notifications/dist` and on your sandbox in `~/public_html/widgets.wp.com/notifications/`.
> Adding script to sync notifications app to a sandbox wpcom installation

- client/components/notes-formatted-block/blocks.jsx
- client/components/notes-formatted-block/index.jsx
- client/components/notes-formatted-block/test/blocks.js
- client/components/notes-formatted-block/test/index.js
Relates to `1164141197617539-as-1192179611031378` (preliminary work).
* Refactor the `FormattedBlock` to make it more easily testable and extensible.
* Split specific block types into their own components, putting them all in `blocks.jsx`.
* Add unit tests to cover `FormattedBlock` and branching logic in the blocks for links, posts, and themes.
NOTE: This pull request lays groundwork that will make resolving `1164141197617539-as-1192179611031378` much easier for all block types, not just the one for plugin changes.
* Run all unit tests to make sure they still pass.
* For both Jetpack Cloud and Calypso, test that all behavior for Activity Log cards -- and specifically, all links -- matches the current production deployment. Here's a list of notable events that have their own cards:
* Post …
> Activity Log: Refactor and add test coverage for FormattedBlock et al

- client/my-sites/plans-v2/upsell.tsx
* Fixes a small layout issue affecting the Upsell page. See the Demo section for a better representation of the problem.
* Run this PR with `yarn start-jetpack-cloud`.
* The error manifest when you move from the Details page to the Upsell, therefore, you need to select a product that has a both Daily and Real-time flavors, and includes an upsell to another product. At this moment, the only product that fits this description is Jetpack Backup.
* Move between the two pages and verify there is no change in the position of the master bar. You can repeat the exercise in production to see how the layout changes every time you visit the Upsell page.
Fixes 1169247016322522-as-1193281023077033
> Offer Reset: fix Upsell page layout issue 

- client/reader/README.md
* Adds documentation at `client/reader/README.md` to test and develop rendering blocks in the Reader pages
* Specifically, there are testing instructions to follow a site, publish a post, and then test the block in your post in the two Reader views
* Documentation of files that represent the data flow for the two Reader views
* Relevant API endpoints in which these two Reader views consume data
Outstanding: Documentation for development on the API side for how we can send more rich data for the blocks used.
* You can test the documentation out by walking through it yourself :)
Fixes #45438
> [WIP] Reader: Block Rendering Testing and Development Documentation

- apps/notifications/src/doc/note-rendering.md
* Adds documentation at `apps/notifications/src/doc/note-rendering.md` giving a general overview of how notifications are processed to be rendered to users and the workflow and files necessary to modify the rendering logic.
Fixes #45439
> Adding documentation for code pipeline and workflow for rendering notifications in Calypso.

- client/my-sites/plans-features-main/jetpack-faq.jsx
* Update the link to contact support with a link specially created for Jetpack Free users.
* Remove Happychat alternative since it's no longer supported.
* Run this PR.
* Visit `jetpack/connect/store` and go to the FAQ section (at the bottom of the page).
* Make sure the contact link points to `https://jetpack.com/contact-support/?rel=support&hpi=1`.
Fixes 1169247016322522-as-1193677921810235
> Plans: FAQ update link to contact support

- apps/editing-toolkit/editing-toolkit-plugin/coming-soon/coming-soon.php
Adds wpcom_public_coming_soon to the setting endpoint GET and POST endpoints
Apply the generated diff, or checkout this branch and then run `yarn dev --sync` from `./apps/editing-toolkit/` to sync to your sandbox.
In a rest client calls the settings endpoint:
```
POST https://public-api.wordpress.com/rest/v1.4/sites/172971117/settings
Authorization: {{ authorization taken from browser }}
Cookie: {{ cookie taken from browser }}
{
"wpcom_public_coming_soon": 1
}
```
```
GET https://public-api.wordpress.com/rest/v1.1/sites/172971117/settings
Authorization: {{ authorization taken from browser }}
Cookie: {{ cookie taken from browser }}
```
You should see `"wpcom_public_coming_soon": 1` included in the response
> add setter and getter for comming soon setting to api

- apps/editing-toolkit/editing-toolkit-plugin/full-site-editing-plugin.php
- apps/editing-toolkit/editing-toolkit-plugin/readme.txt
- apps/editing-toolkit/package.json
- package.json
* https://github.com/Automattic/wp-calypso/pull/43980 (added to notes)
* https://github.com/Automattic/wp-calypso/pull/45280
* https://github.com/Automattic/wp-calypso/pull/45429 (added to notes)
* https://github.com/Automattic/wp-calypso/pull/44888
* https://github.com/Automattic/wp-calypso/pull/45423 (added to notes)
* https://github.com/Automattic/wp-calypso/pull/45502
* https://github.com/Automattic/wp-calypso/pull/45054 (added to notes)
* https://github.com/Automattic/wp-calypso/pull/45561 (added to notes)
* Apply generated diff to sandbox
* Test changes listed in release notes are present
* Install build on an atomic site
* Test that editor works on atomic with and without gutenberg plugin enabled
> Bump WordPress.com Editing Toolkit plugin to v2.3

- client/blocks/signup-form/index.jsx
- client/lib/abtest/active-tests.js
Check P2 post pbxNRc-rq-p2.
* A/B test to remove the username field in signup in the flows - `onboarding`, `personal`, `premium`, `business`, `ecommerce`.
Depends on D49474-code.
* Assign yourself to the variant, and go through the signup flow at `/start/user`. 
* Verify that signup completes successfully. A random username should have been assigned to you, and your activation email's subject line should contain your email address. 
* Verify the above two steps for the flows - `onboarding`, `personal`, `premium`, `business`, `ecommerce`.
* Verify that the `control` group experience is unaffected.
> Signup A/B test: Remove username field

- client/blocks/post-item/style.scss
- client/blocks/support-article-dialog/content.scss
- client/blocks/support-article-dialog/style.scss
- client/jetpack-connect/style.scss
- client/my-sites/comments/comment/style.scss
- client/my-sites/domains/domain-management/list/style.scss
- client/my-sites/draft/style.scss
- client/my-sites/email/email-management/gsuite-user-item/style.scss
- client/my-sites/invites/invite-accept-logged-in/style.scss
- client/my-sites/pages/style.scss
- client/my-sites/people/people-invite-details/style.scss
- client/my-sites/resume-editing/style.scss
- client/signup/steps/rebrand-cities-welcome/style.scss
* Remove instances of Noto Serif from our UI.
* Exception: The Reader remains in serif for the time being, to better align with iOS patterns.
Visuals
Before | After
----- | -------
* Check out the instances above in the visuals (comment if you need instructions for reproducing these screens and I'll add them!) look for regressions or general broken-ness.
* Make sure everything in the Reader still looks OK and uses the serif fonts for headings and body copy.
See #44970
> Typography: Remove use of Noto Serif except for Reader

- client/landing/gutenboarding/stores/onboard/actions.ts
- packages/data-stores/src/site/types.ts
* Save selected features as site options to use in Site setup flow.
* Apply D49420-code and sandbox public API
* Create a site starting from [/new](https://calypso.live/?branch=update/gutenboarding-save-selected-features)
* When landing in editor, open console, select the [iframed post.php window scope](https://cloudup.com/caRMFEKucA8) and run `wp.data.select( 'automattic/site' ).getSite(window._currentSiteId).options.selected_features` to get selected features. If the first call returns `undefined`, re-run the statement.
* `selected_features` should be saved in site options only for sites created in Gutenboarding.
Fixes #45148
> Gutenboarding: use selected_features when creating a site

- client/components/jetpack/card/jetpack-free-card/index.tsx
* The Jetpack Free CTA should redirect to WordPress.com when in Jetpack cloud.
* Run this PR with `yarn start-jetpack-cloud`.
* Visit `/pricing`.
* Click on the Jetpack Free CTA.
* Make sure you are redirected to wordpress.com/jetpack/connect.
* Make sure the CTA still works in the Jetpack Connect flow and in WordPress.com plans grid.
> Fix: Redirect to WordPress.com when in JP cloud

- apps/editing-toolkit/package.json
Remove no-inline-config from ES5 validation script. This is not required since we are checking minimized code which doesn't contain any comments.
`yarn build` should run without errors
> Editing Toolkit: Remove no-inline-config flag from es5 validation

- test/e2e/lib/gutenberg/blocks/file-block-component.js
- test/e2e/lib/gutenberg/gutenberg-editor-component.js
- test/e2e/lib/gutenberg/gutenberg-editor-sidebar-component.js
- test/e2e/lib/pages/media-page.js
- test/e2e/specs/wp-media-editor-spec.js
- test/e2e/specs/wp-media-upload-spec.js
* This change updates the media upload tests which were disabled when the classic editor was deprecated. They now use Gutenberg
* I also disabled one of the tests because it wouldn't pass in CI. I can revisit that one later.
* Ensure that all the tests pass in the CI
> e2e: Update media upload tests

- client/jetpack-connect/authorize.js
- client/my-sites/plans-v2/selector.tsx
* Fix incorrect redirection to the Plans page after the user has logged in. Now users are redirected to the checkout page.
* Fix loading state for prices. 
* Test the whole flow in every possible way you can imagine. Don't forget to test the flow for products such as Jetpack Scan, Jetpack Search, and others.
> Fix redirection to back to the Plans page at the end of the flow

- apps/editing-toolkit/editing-toolkit-plugin/block-patterns/patterns/multi-column-text-with-headline.php
A missing string was referenced in an incorrectly typed variable. This PR should correct both.
Fixes #45681
> Correct typo and missing string in mulit-column-text-with-headline.php

- client/my-sites/plans/current-plan/index.jsx
This PR fixes the [Object object] in the plan title, at the bottom of the Plans page in Calypso. (see screenshot).
Additional data:  This only happens with "Security _Daily_" or "Security _Realtime_" plans because of the way the i18n-calypso.translate() function handles the emphasized/italicized words (<em>daily</em> & <em>realtime</em>)
1. Select a site that has a Plan of Jetpack Security Daily or Realtime.
2. Go to My Plan tab on the Plans page and make sure you do Not see [Object object] in the plan title at the bottom of the page like shown in the screenshot above.
3. Next select a site with any plan other than Security Daily or Realtime and make sure the plan title at the bottom of the page displays correctly.
Fixes: 1169247016322522-as-1193991362792017/f
> Jetpack Offer Reset: Fix [Object object] in plan title
