client/lib/plans/plans-list.js
client/my-sites/earn/ads/wrapper.jsx
client/my-sites/earn/home.tsx
client/my-sites/marketing/tools/google-my-business-feature.tsx
client/my-sites/site-settings/form-analytics.jsx
client/my-sites/site-settings/jetpack-ads.jsx
client/my-sites/site-settings/media-settings-performance.jsx
client/my-sites/site-settings/seo-settings/form.jsx
client/my-sites/site-settings/spam-filtering-settings.jsx
client/my-sites/themes/single-site-jetpack.jsx
client/state/themes/selectors/get-jetpack-upgrade-url-if-premium-theme.js

In this PR, we make sure that when the offer reset flow is enabled, customers don't see legacy Jetpack plans upsells in Calypso.
Fixes 1169247016322522-as-1193712760461723
_Note: it's quite urgent to remove old plans mentions, so this PR just does that. I'll follow up with what we want to replace them with eventually_
Select a self-hosted site with Jetpack Free
- Go to `/themes/:site/`
- With the offer reset flow disabled, make sure you see the plan upsell (see capture below)
- With the OR flow enabled, make sure it's not there anymore
- Go to `/themes/premium/:site/`
- Click the "three dot menu" on a theme and "Upgrade to activate"
- Verify you are taken to checkout with a Real-time security plan
- Visit `/settings/performance/:site/`
- Check the _Media_ section
- Check that you see an …

Make sure new customers don't see old plans upsells

---

apps/editing-toolkit/editing-toolkit-plugin/premium-content/subscription-service/class-jwt.php

* Premium Content seems to be missing custom exceptions resulting in fatal errors experienced in Calypso. See this thread: p1599397148031300-slack-C4N88L95W. I synced up with @obenland about steps to reproduce, and we were unable to come up with a way to reproduce these fatal errors -- but we know it's happening per p1599397148031300-slack-C4N88L95W
* What we know is that in our code editors, there is a warning message whenever you hover over these exceptions used. Resolving these warning messages is considered a reasonable fix to this since the type is defined and hopefully prevents the fatal error, since we're not able to reproduce the fatal error messages another way
* A caveat here that could be encountered is if another plugin defines these exceptions, and they clash
* These errors …

Premium Content: Fix Fatal Error from Custom Exceptions

---

client/landing/gutenboarding/hooks/use-on-login.ts
client/landing/gutenboarding/hooks/use-on-signup.ts
client/landing/gutenboarding/hooks/use-on-site-creation.ts
client/landing/gutenboarding/hooks/use-selected-plan.ts
client/landing/gutenboarding/hooks/use-step-navigation.ts
client/landing/gutenboarding/onboarding-block/plans/index.tsx
client/landing/gutenboarding/stores/onboard/actions.ts
packages/data-stores/src/site/types.ts

* Opt-in to coming soon v2 behaviour if `?public-coming-soon` is present and on `wpcalypso.wordpress.com` or a development build
* Send `public_coming_soon` flag to `/sites/new` endpoint
* Disable private-by-default behaviour
* Set new coming-soon sites as non-indexable
The `public_coming_soon` API option was merged in D49202-code, and it just sets the `wpcom_public_coming_soon` site option.
Part of #45019
* Create a new site with `localhost:3000/new?flags=gutenboarding/public-coming-soon`
* The `?flags` query param will disappear as you go through the flow, but that's ok
* Open network tools and preserve log to make it easier to inspect the call to `/sites/new`
* Create a site with any plan other than ecommerce
* Check that the call to `/sites/new` included a `public_coming_soon=true` …

Coming soon: Send `public_coming_soon` site creation flag in development builds

---

packages/domain-picker/src/info-tooltip/style.scss

The editing toolkit build started failing due to #45490. One of the sass files that gets pulled in was missing a definition for the `$font-body-small` variable.
* `<InfoTooltip>` sass imports it's own dependencies
* `cd apps/editing-toolkit`
* `yarn clean`
* `node bin/npm-run-build.js --build`
* There should be no errors
* Test for no visual regressions in the domain picker

Editing toolkit: fix broken sass build

---

package.json
packages/domain-picker/src/domain-picker/index.tsx
packages/domain-picker/src/domain-picker/style.scss
yarn.lock

* Change "View more results" to a button in Gutenboarding, based on Rick's feedback at pbAok1-1lr-p2#comment-2734
These are just core component styles and you can see we've modified them to be grey-bordered at some places, which makes the default button style look a bit out of place.
* In `/new` flow, open button modal from header domain suggestion after entering the site name

Gutenboarding domains: view more results button

---

apps/editing-toolkit/editing-toolkit-plugin/full-site-editing-plugin.php
apps/editing-toolkit/editing-toolkit-plugin/readme.txt
apps/editing-toolkit/package.json
package.json

* https://github.com/Automattic/wp-calypso/pull/45492 (added to notes)
* https://github.com/Automattic/wp-calypso/pull/45499 (added to notes)
* https://github.com/Automattic/wp-calypso/pull/45571
* https://github.com/Automattic/wp-calypso/pull/45604
* https://github.com/Automattic/wp-calypso/pull/45651
* https://github.com/Automattic/wp-calypso/pull/45634
* https://github.com/Automattic/wp-calypso/pull/45682 (added to notes)
* https://github.com/Automattic/wp-calypso/pull/45656 (added to notes)
* Apply generated diff to sandbox
* Test changes listed in release notes are present
* Install build on an atomic site
* Test that editor works on atomic with and without gutenberg plugin enabled

Bump WordPress.com Editing Toolkit plugin to v2.4

---

client/my-sites/email/email-management/index.jsx

This PR adds a tracks event which is fired when the "Email Forwarding" button is clicked on the /email page.
* Go to your site domains
* Click "Add" under the Email column for one of your domains
* Click "Email Forwarding" which is below the G Suite upsell
* Verify the tracks event is fired

Email: Add tracks event for email forwarding click

---

client/assets/stylesheets/shared/_animation.scss
client/blocks/comments/index.jsx
client/blocks/comments/post-comment-list.jsx
client/blocks/comments/post-comment.jsx
client/blocks/comments/post-comment.scss
client/blocks/conversations/list.jsx
client/blocks/reader-full-post/index.jsx

Integrates, finally, #40858. All props @unDemian.
* Add highlight effect to new realtime comments 
Add a comment to one of your posts on the frontend, it should be highlighted in Calypso Reader full post view (anything other than Conversations AFAIK).

Add new comment highlights

---

client/my-sites/plans-v2/use-get-plans-grid-products.ts

Title sums it up.
Fixes 1169247016322522-as-1194011618084897
- Make sure the offer reset flow is enabled (should be by default)
- Visit the _Plans_ page and select the _All_ type
- Check that _Search_ appears first in the product column

Make Jetpack Search first item in product column in Plans page

---

client/jetpack-connect/main-header.jsx

This PR makes sure that the Jetpack connect page copy supports new plans and products.
Make sure the offer reset flow is enabled.
- Visit `/jetpack/connect/jetpack_complete`
- Check that the title and description represent _Jetpack Complete_
- Visit `/jetpack/connect/jetpack_anti_spam`
- Check that the title and description represent _Jetpack Anti-spam_
- Visit `/jetpack/connect/jetpack_search`
- Check that the title and description represent _Jetpack Search_
**Complete**
**Anti-spam**
**Search**

Jetpack connect: support new plans title and description

---

client/landing/gutenboarding/hooks/use-selected-plan.ts
client/landing/gutenboarding/stores/onboard/reducer.ts

* Pre-select custom domain feature when choosing a paid domain.
* Update logic to handle selected plan in Gutenboarding so PlansButton is updated when selecting features. Demo: https://cloudup.com/cQapnqXMVYL
* Go to [/new](https://calypso.live/new?branch=update/gutenboarding-preselect-domain-feature).
* Select a paid domain.
* Custom domain feature should be pre-selected when landing on Features step.
* Select and deselect features => Plans button (top-right corner) value should be updated as in [demo](https://cloudup.com/cQapnqXMVYL).
Fixes part of https://github.com/Automattic/wp-calypso/issues/45611

Gutenboarding: pre-select domain feature

---

client/lib/abtest/active-tests.js

This PR updates the datestamp of the Offer Reset experiment. Users that visited Calyspo since we initially launched this experiment might have the `control` variant stored, which could prevent them from seeing the new plans page now. Resetting the experiment by changing the datestamp will ensure that the `showOfferResetFlow` variant is default for everybody.
Here's the [A/B test documentation](https://github.com/Automattic/wp-calypso/tree/master/client/lib/abtest).
- Download the PR locally
- Open your browser console and run `localStorage.setItem('debug', 'calypso:abtests')`
- Hard refresh Calypso
- Make sure that you see `calypso:abtests offerResetFlow_20200916` printed in the console
- Open the ABTESTS menu in the debug menu at the bottom right of the screen, and check that **no** …

Update Offer Reset experiment datestamp

---

client/my-sites/plans-v2/controller.tsx
client/my-sites/plans-v2/details.tsx
client/my-sites/plans-v2/types.ts
client/my-sites/plans-v2/upsell.tsx

Fixes: 1169247016322522-as-1193933927242258/f
1. On the Jetpack Plans selection page, change "Bundle Options" text to "Plan Options".
2. On the Jetpack Plans selection pages and upsell pages, remove FAQ section at the bottom.
(See Screenshot)
- Go to http://calypso.localhost:3000/jetpack/connect/store
- Select a Plan that has options. (At this time, the only _Plan_ that offers daily and real-time options is Jetpack Security.)
- Verify that it no longer says "Bundle Options", and now it says: "Plan Options" (see image)
- Next, verify that the FAQ's are no longer showing on Plan or Product select pages (select daily or real-time options), and also on product upsell pages. For example, these pages:
http://calypso.localhost:3000/jetpack/connect/store/jetpack_security_monthly/monthly/details …

Remove faqs from plan select details page and upsell page.

---

client/my-sites/checkout/composite-checkout/payment-method-helpers.js

* Deactivate wechat payment method from calypso. We could also have done this on the backend, but updating the logic in calypso is much more straightforward. :/
* Use code-D45650 to force wechat to be returned by the API
* Enter checkout; verify that wechat is in the array of payment methods returned by the backend (this is in the response of the `me/shopping-cart` endpoint, you should see `"WPCOM_Billing_Stripe_Source_Wechat"` in `.body.allowed_payment_methods`)
* Verify that wechat is _not_ one of the payment method options
* Verify that the other appropriate payment methods are still available
Discussion is here: p2y3YZ-48E-p2

composite-checkout: Create filter for legally restricted payment methods

---

client/lib/plans/index.js
client/my-sites/plans/current-plan/jetpack-checklist/index.tsx

Video hosting doesn't work properly for new Jetpack plans for now. It will be fixed in the next Jetpack plugin release. In this PR, we show the Video Hosting item in the My Plan checklist for the future Jetpack releases.
Current Jetpack plugin version is 8.9.1
- Download the PR locally and run Calypso
- Make sure you have 3 self-hosted Jetpack site ready: with a Free plan, Premium plan, and a new plan
- Visit `plans/my-plan/:site/`
- For each of these 3 sites, make sure you only see the Video Hosting item (see capture) with the Premium plan
- Now in `client/my-sites/plans/current-plan/jetpack-checklist/index.tsx`, update the minimum version of Jetpack (`OFFER_RESET_VIDEO_MINIMUM_JETPACK_VERSION`) so that it's below the versions of your 3 sites
- Make sure you see the item in the checklist …

Show Video Hosting item in My Plan checklist for new Jetpack plans

---

client/my-sites/plans-v2/plans-header.tsx

This PR makes it so that the special notice and header on the Plans page is only displayed when coming from wp-admin and only if the user has not purchased any plans or products. (See screenshot)
1. Create a new JN site and activate Jetpack by either clicking "Setup Jetpack" button in the Dashboard, or by clicking "Jetpack" in the side menu.
2. Choose "Jetpack Free", or don't select any plan at all, either way.
3. Go back to to wp-admin, select "Jetpack" in the side menu to get to the Jetpack Dashboard and then select "Plans".
4. You will be directed to the Jetpack Plans page (in Calypso). Since no plans or products have been purchased (and you're coming from wp-admin) you should see the special notice and header at the top of the page.
5. Visit the Plans page in other scenarios where a …

Hide in-connect-flow notice and header if any plans or products owned

---

client/blocks/product-purchase-features-list/sell-online-paypal.jsx
client/my-sites/earn/home.tsx

* The reasoning behind this change is expressed in the original issue, along with approval of the copy, but this effectively just removes reference to "digital goods" 
Verify this touches the copy on the Earn page, along with the "My Plan" page.
cc @gwwar 
Fixes #45646

Earn: Remove Reference to "Digital Goods" with PayPal

---

client/landing/gutenboarding/hooks/use-selected-plan.ts

* After https://github.com/Automattic/wp-calypso/pull/45693 Free plan couldn't be selected after the user selected some features on `/new/features` step.
* Removed the overriding of explicitly selected _Free plan_ when paid features are selected.
* Go to [/new](https://calypso.live/new?branch=fix/gutenboarding-free-site-creation).
* On `/new/features` step select some features.
* You'll notice a plan is recommended, but select the _Free plan_.
* After site creation you should land in editor (no checkout).
1. Go to https://wordpress.com/new/design?fresh.
2. Open the Plans modal (using the top-right _View plans_ button) and select _Free plan_.
3. Advance to `/new/features` and select some features => Plans buttons value will change.
4. Go to …

Gutenboarding: remove free plan override

---

.stylelintrc

* Set a standard for border radii widths to 2px in the stylelint scales rules to better match Gutenberg styles.
* Switch to this branch and run `yarn` to make sure it builds
* Edit any `style.scss` file in Calypso and add an invalid `border-radius` (ie. `border-radius: 4px` or `border-radius: 2em`) to any element. Save, and try to add and commit your changes.
* The linter should throw an error like this, preventing you from committing:
* Fix the value to `border-radius: 2px` and try to commit again. The linter should pass and allow you to add a commit message.
See #44883

Update stylelint config to include border radius

---

.github/workflows/lighthouse-review-requested.yml

Github actions for PR, whenever Lighthouse team is requested as a reviewer it will automatically
- Add "Needs Review" label
- Add the PR to our "Productize P2" board under "Needs Review" column
- Assign the author to the PR
- Remove "Needs Review" label
- Remove PR from Project
- Unassign PR
- Remove "Lighthouse" from Reviewers and add it back

Add lighthouse team workflow

---

client/landing/gutenboarding/hooks/use-on-site-creation.ts
client/landing/gutenboarding/hooks/use-selected-plan.ts

* Use only selected features (on Features step) when suggesting a plan in top-right corner (Plans button).
* Keep using the Premium plan as popular on Plans step if no feature is selected.
Demo: https://cloudup.com/cVGGDgch0Zb
* Go to [/new](https://calypso.live/new?branch=update/gutenboarding-domain-feature-and-plan-recommendation)
* Pick a paid domain on Domains step => _Personal plan_ should appear in top-right corner instead of _View plans_.
* Deselect _Custom domains_ feature on Features step. _View plans_ should appear in top-right corner if no other feature is selected.
Fixes #45716

Gutenboarding: align domain feature and plan recommendation

---

client/my-sites/plans-v2/constants.ts

Pricing constant properties with translatable strings are being defined before the actual translations are loaded. In this case the result of individual `translate` calls will remain the original string and not the translation for the given locale.
* Define getters for pricing constants properties which use `translate` calls.
**Before:**
**After:**
* Boot Calypso with `CALYPSO_ENV=jetpack-cloud-development BUILD_TRANSLATION_CHUNKS=true ENABLE_FEATURES=use-translation-chunks,wpcom-user-bootstrap yarn start`
* Go to `/es/pricing`  and confirm all strings in the pricing blocks are in Spanish.
Fixes p1600269537067800-slack-C02AED43D

Jetpack Pricing: Use dynamic getters for translatable constants

---

client/my-sites/plans-v2/constants.ts

* Inadvertently we introduced a bug in #45727 which transformed an object with two properties into a translated string. This PRs fixes that.
* Run this PR.
* Visit `/plans/:site`.
* Make sure that the Product Type filter works as expected (try every option).
* Make sure that there are no errors in the console.
Fixes 1169247016322522-as-1194422915651802.

Plans: fix broken Product Type filter

---

client/layout/masterbar/style.scss

* This PR ensures that the profile picture in the masterbar is showing on mobile viewports.
* This PR also ensures that the profile picture in the masterbar is also always perfectly positioned across viewports.
|before|after|
|-|-|
|<img width="376" alt="Screenshot 2020-09-17 at 15 34 04" src="https://user-images.githubusercontent.com/1562646/93477411-436e4000-f8fb-11ea-91ab-3767f07ddca9.png">|<img width="377" alt="Screenshot 2020-09-17 at 15 33 35" src="https://user-images.githubusercontent.com/1562646/93477419-4701c700-f8fb-11ea-9eb1-f43ffec9a853.png">|
Currently in production the profile picture is not showing in the masterbar on mobile viewports.
This is caused by `.masterbar__item-content` being set to `display:none` on viewports <480px. This makes sense for all other instances of …

Masterbar: show profile picture on mobile

---

client/components/activity-card/activity-description.tsx
client/components/notes-formatted-block/blocks.jsx
client/components/notes-formatted-block/test/blocks.js

Fixes `1164141197617539-as-1192179611031378`.
* Add conditional logic and test coverage to ensure that Jetpack Cloud doesn't link out to WordPress.com from cards in the Activity Log.
As far as I know, the goal here is to not kick people out of Jetpack Cloud and back into WordPress.com when they're browsing their site's Activity Log. If we want to revisit this behavior later, it'll be easy enough to change because of the earlier refactor in #45591.
**IMPORTANT:** This pull request creates divergent behavior between Calypso and Jetpack Cloud. Each of these environments should be tested for correctness before approval.
As a rule, Activity Log entries should behave as follows:
* If you're using Calypso/WordPress.com, all links to WordPress.com should be rendered as relative links (i.e., …

Activity Log: Remove WordPress.com links from the Jetpack Cloud Activity Log

---

apps/editing-toolkit/editing-toolkit-plugin/full-site-editing-plugin.php
apps/editing-toolkit/editing-toolkit-plugin/readme.txt
apps/editing-toolkit/package.json
package.json

* https://github.com/Automattic/wp-calypso/pull/45718 (added to notes)
* https://github.com/Automattic/wp-calypso/pull/45691 (added to notes)
* Apply generated diff to sandbox
* Test changes listed in release notes are present
* Install build on an atomic site
* Test that editor works on atomic with and without gutenberg plugin enabled

Bump WordPress.com Editing Toolkit plugin to v2.5

---

client/layout/masterbar/style.scss

* This PR ensures that the reader unread bubble is positioned correctly across mobile viewports.
Currently in production the reader unread bubble is not positioned correctly across mobile viewports.
|before|after|
|-|-|
|<img width="371" alt="Screenshot 2020-09-17 at 15 49 35" src="https://user-images.githubusercontent.com/1562646/93480109-613ca480-f8fd-11ea-92f7-e954ea277ca7.png">|<img width="377" alt="Screenshot 2020-09-17 at 15 49 20" src="https://user-images.githubusercontent.com/1562646/93480144-6994df80-f8fd-11ea-88b1-ba738e53254f.png">|
* Locally: check out PR, `yarn && yarn start` and visit http://calypso.localhost:3000/
* Calypso.live: visit https://calypso.live/?branch=fix/masterbar-reader-bubble-on-mobile
Compare the masterbar on this branch to the masterbar in production. …

Masterbar: fix reader unread bubble positioning on mobile

---

.github/workflows/editing-toolkit-plugin.yml

* This PR updates the version of node used in the editing toolkit workflow
Currently, the Editing toolkit CI is failing:
> 2020-09-20T22:19:23.6584403Z error wp-calypso@0.17.0: The engine "node" is incompatible with this module. Expected version "^v12.18.4". Got "12.18.3"
This is because https://github.com/Automattic/wp-calypso/pull/45721 updated the required node version, but we're still using the default 12.18.3 provided by [ubuntu 18.04](https://github.com/actions/virtual-environments/blob/ubuntu18/20200914.1/images/linux/Ubuntu1804-README.md), so we need to pull in a newer version of node in line with our [other workflows](./.github/workflows/icfy-stats.yml). (Aside: there is a ubutu 20-04, but it's got the same node, so totally don't need to do that)
As a circle-CI update, we're …

Editing Toolkit: specify node version in github workflow

---

client/landing/gutenboarding/stores/onboard/actions.ts

When creating a new site, we're testing if site title is an empty string. 
If `siteTitle` is empty (the user has not entered a site title), we translate the default string of 'Site Title' **according to the Gutenboarding UI language**. 
If we don't do this, the corresponding create blog method in the backend will use the default locale.
**Before**
**After**
Create a site via `/new/{a_mag_16_locale}`
Make sure to skip the intent gathering step, i.e., don't specify a site title
The default site title should be a translation of "Site Title"

Gutenboarding: create site with translated default blog title

---

client/blocks/signup-form/index.jsx
client/lib/abtest/active-tests.js

* Stops the remove username test launched in https://github.com/Automattic/wp-calypso/pull/45609
* Launches a new AA test for the username field. Check pbxNRc-rq-p2/#comment-840.
* Visit the /start/user and /start/premium and confirm that you are not assigned to the `removeUsernameInSignup` test.
* Verify that in these flows, you are assigned to the `usernameAATest` and that the username field is visible in both control and variant.

Stop test and launch new AA test

---

client/me/concierge/cancel/index.js
client/me/concierge/shared/appointment-info.js
client/me/concierge/style.scss

* If the time left to start the session is less than one hour, then do not display the option to reschedule/cancel a session in the session dashboard.
**With more than one hour left for the session to begin, users can see the Reschedule/Cancel button:**
**With less than one hour to go, the reschedule/cancel button is hidden:**
Depends on D49790-code.
* Schedule a session and verify that the Reschedule/Cancel option in the session dashboard is not displayed if there's less than 1 hour for the session to begin
* If there's less than one hour for the session to begin, try visiting the direct cancel URL and check that you cannot cancel. You should see a notice like this:

Session dashboard: Do not allow last minute reschedule/cancel 

---

client/blocks/product-purchase-features-list/index.jsx

Fixes: 1169247016322522-as-1194230427737465/f
This PR displays the Plan Features for Jetpack Security and Jetpack Complete plans.
Currently there are no "Plan Features" showing at the bottom of the "My Plan" page for the new Offer Reset plans (Jetpack Security and Jetpack Complete). Only the title is showing. Plan features should display under the title.  See screenshot below.
Per the [plans comparison page](https://jetpack.com/features/comparison/), JetPack Security and Jetpack Complete offer the same overall features, except that Complete offers CRM on an 'Enterprise' level, so therefore in this PR, the features displayed for Jetpack Security and Complete will be the same.
Also, this PR only displays the feature components that are currently available within Calypso (and that are …

Offer Reset: Show Plan Features on My Plans page for Jetpack Security and Complete.

---

client/desktop/app-handlers/updater/manual-updater/index.js

This PR fixes the Linux manual updater to ensure that it resolves Github releases and redirects to the WordPress Desktop landing page.
Auto-updating in Linux is not supported by Electron. Instead, the open-source community submits Linux builds to the Snap store. However, as an in-app alternative, the `Manual Updater` pings Github for latest release information and redirects the user to download the `.deb` installer accordingly.
Build this branch with a version number less than officially deployed (edit in `desktop/package.json`). Verify that a prompt to update is displayed when the app is booted, and redirects to the WordPress Desktop landing page when clicked.
</br>
</p>

fix(linux): manual updater

---

client/lib/wpcom-undocumented/lib/undocumented.js
client/my-sites/email/email-management/index.jsx
client/my-sites/email/email-providers-comparison/email-provider-details/index.jsx
client/my-sites/email/email-providers-comparison/index.jsx
client/my-sites/email/email-providers-comparison/style.scss

This PR updates the email comparison page by accounting for the possibility of two instead of three columns (i.e. when G Suite is not supported), as well as makes the buttons work.
- Verify for a domain that doesn't support G Suite that we show only email forwarding and Titan (you can force this by passing `false` to `isGSuiteSupported`)
- Verify that the buttons work correctly for all providers (with Titan it should load a link from the backend)
- The label for the email forwarding button should say `Manage email forwarding` when the user has set up forwarding for that domain

Email: Add functionality to email comparison page

---

client/components/domains/contact-details-form-fields/managed-contact-details-form-fields.jsx
client/my-sites/checkout/composite-checkout/components/wp-contact-form-summary.js
client/my-sites/checkout/composite-checkout/components/wp-contact-form.js
client/my-sites/checkout/composite-checkout/types/backend/domain-contact-validation-endpoint.ts
client/my-sites/checkout/composite-checkout/types/wpcom-store-state.ts

* When checking out with gsuite in the cart, but _not_ any domain products, (1) only show the alternate email field in the summary contact details and (2) allow the user to update this field.
Note that GSuite can only be tested in the live environment, with a domain that was purchased in the live environment - so you'll need to turn off store sandbox and use a real domain that does not already have gsuite added to test this.
* Enter checkout with a new gsuite subscription in your cart, but no domain products. You can do this on an account with an existing domain through `Manage > Domains` or directly with `/email/$siteurl/manage/$siteurl`.
* Verify that your "alternate email" is displayed in summary view, if it has already been saved for your user. If not (e.g. your test account doesn't …

Checkout: only use alt email in gsuite contact form

---

apps/editing-toolkit/editing-toolkit-plugin/premium-content/blocks/buttons/edit.js
apps/editing-toolkit/editing-toolkit-plugin/premium-content/blocks/buttons/index.js
apps/editing-toolkit/editing-toolkit-plugin/premium-content/blocks/container/edit.js
apps/editing-toolkit/editing-toolkit-plugin/premium-content/blocks/logged-out-view/edit.js
apps/editing-toolkit/editing-toolkit-plugin/premium-content/blocks/subscriber-view/edit.js
apps/editing-toolkit/editing-toolkit-plugin/premium-content/premium-content.php
apps/editing-toolkit/editing-toolkit-plugin/premium-content/subscription-service/class-token-subscription-service.php

* Fix the token subscription service of the Premium Content block so the subscriber view is rendered for logged in users who are subscribed to the plan used in the block, even if the token/auth cookie is missing.
* The block has been completely broken since changes from https://github.com/WordPress/gutenberg/pull/24155 and https://github.com/Automattic/jetpack/pull/15915 landed in WP.com. The first dropped support for the `context` property when registering a block in favor of a new `usesContext`, while the latter dropped support for the `submitButtonText` attribute of the `jetpack/recurring-payments` block in favor of the inner `jetpack/button` block's `text` attribute. This PR updates the code so block is usable again:
Before | After
--- | ---
* Modify your `/etc/hosts` file and point …

Premium Content: Display subscriber view to logged in users who have subscribed

---

client/desktop/app-handlers/preferences/index.js
client/desktop/lib/desktop-analytics/index.js
client/desktop/lib/settings/index.js
client/desktop/lib/settings/settings-file.js
client/desktop/window-handlers/get-logs/index.js

This PR removes noisy settings logging, and adds the `settings.json` file to the zip archive for inspection. (This information is useful, but unnecessary to log whenever a setting is fetched (which occurs in a number of places).
</p>
- Build and run the app (or run the built executable from this PR)
- Verify that the archive created with the `Get Application Logs` actions also includes `settings.json`

chore(logging): add logging refinements

---

apps/editing-toolkit/editing-toolkit-plugin/full-site-editing-plugin.php
apps/editing-toolkit/editing-toolkit-plugin/readme.txt
apps/editing-toolkit/package.json
package.json

Bump the Editing Toolkit plugin to version 2.6. This version includes fixes for Premium Content block regressions, corrected in https://github.com/Automattic/wp-calypso/pull/45777

Editing Toolkit: Bump to version 2.6.

---

client/components/domains/premium-badge/index.jsx

* Update the premium badge popover text and make it translatable
* Search for a premium domain in the dev/wpcalypso environment and check the premium badge info popover text

Update the premium badge popover text

---

packages/plans-grid/src/plans-accordion-item/style.scss

Fixes messy plans grid on iOS.
I think `display: inline-flex` was a remnant from the multi column plans table. `display: block` will work just fine.

Gutenboarding: Fix messed up plans grid on iOS.

---

apps/wpcom-block-editor/src/wpcom/features/tracking.js

* With the new metadata additions given to the insertBlocks and replaceBlocks actions, we can determine when a block pattern is being inserted and record a Track event for this.
68-gh-view-design
* Checkout this PR
* Build `wpcom-block-editor`
* Sync the built files to your sandbox's widget directory
* Also sync a build of Gutenberg `add/pattern-meta-to-replace-blocks` branch to the folder on your sandbox of the version the site is running, eg. `wp-content/plugins/gutenberg-core/9.0.0`
* Ensure you have `widgets.wp.com` sandboxed
* Visit a sandboxed site's block editor:
`https://YOUR-SANDBOX-DOMAIN/wp-admin/post.php?post=YOUR-POST-ID&action=edit`
* Open dev tools console and turn on tracking debugging via localStorage value:
`localStorage.setItem( 'debug', 'wpcom-block-editor:*' );`
* …

Block Patterns: Track pattern insertion events

---

client/my-sites/sidebar-unified/index.jsx
client/state/admin-menu/actions/index.js
client/state/admin-menu/selectors/index.js

Fixes and error with the Nav Unification modularized state which was loading the `inline-help/init` file rather than the `admin-menu/init` file. I have no idea how this happened or how this has ever worked. This PR resolves things to use the correct init.
* Apply D49005-code
* Apply blog sticker
* Run calypso
* You should see left hand Nav rendered so match API output as generated by D49005-code.
Basically nothing should change. It should be "as is".

Fix nav unification to load the correct state module init

---

client/landing/gutenboarding/lib/analytics/types.ts
client/landing/gutenboarding/onboarding-block/features/index.tsx
packages/data-stores/src/wpcom-features/features-data.tsx

* Update copy for "Store" feature to better reflect what customers will get.
* Recommend eCommerce plan when "Store" feature is selected.
* Fire tracks events when landing and advancing from Features step.
* `calypso_newsite_step_enter` event called with props `{flow: "gutenboarding", step: "Features"}`
* `calypso_newsite_step_leave` event called with props `{flow: "gutenboarding", step: "Features", has_selected_features: true}`
* Go to [/new](https://calypso.live/new?branch=update/gutenboarding-features-store)
* Advance to /features step and check the copy for Store feature. Then select it and advance
* On Plans step, the recommended plan should be _eCommerce plan_
* Go to [/new](https://calypso.live/new?branch=update/gutenboarding-features-store)
* Open console and execute …

Gutenboarding: update store feature and track Features step

---

client/my-sites/checkout/cart/cart-free-user-plan-upsell.jsx

It's currently not possible for a call like `planItem(PLAN_PERSONAL, {})` to return `null`, but the function is allowed to do so, so for safety and future-proofing, let's just guard against that possibility here.
- Add a domain to your cart for an account that has no plan. 
- Visit composite checkout and verify that you see the upsell in the sidebar. 
- Verify that clicking the CTA button successfully adds the Personal Plan to the cart and verify that the upsell disappears.

CartFreeUserPlanUpsell: Only add a planItem to the cart if it exists

---

packages/material-design-icons/README.md

This PR fixes all markdown errors in `packages/material-design-icons`
Run `./node_modules/.bin/eslint --ext .md --ext .md.js --ext .md.javascript --ext .md.jsx packages/material-design-icons`, there should be no errors

[markdown] Fix lint errors in `packages/material-design-icons`

---

packages/media-library/.eslintrc.js

This PR fixes all markdown errors in `packages/media-library`
Run `./node_modules/.bin/eslint --ext .md --ext .md.js --ext .md.javascript --ext .md.jsx packages/media-library`, there should be no errors

[markdown] Fix lint errors in `packages/media-library`

---

packages/photon/.eslintrc.js

This PR fixes all markdown errors in `packages/photon`
Run `./node_modules/.bin/eslint --ext .md --ext .md.js --ext .md.javascript --ext .md.jsx packages/photon`, there should be no errors

[markdown] Fix lint errors in `packages/photon`

---

packages/popup-monitor/README.md

This PR fixes all markdown errors in `packages/popup-monitor`
Run `./node_modules/.bin/eslint --ext .md --ext .md.js --ext .md.javascript --ext .md.jsx packages/popup-monitor`, there should be no errors

[markdown] Fix lint errors in `packages/popup-monitor`

---

packages/react-i18n/.eslintrc.js
packages/react-i18n/README.md

This PR fixes all markdown errors in `packages/react-i18n`
Run `./node_modules/.bin/eslint --ext .md --ext .md.js --ext .md.javascript --ext .md.jsx packages/react-i18n`, there should be no errors

[markdown] Fix lint errors in `packages/react-i18n`

---

packages/request-external-access/README.md

This PR fixes all markdown errors in `packages/request-external-access`
Run `./node_modules/.bin/eslint --ext .md --ext .md.js --ext .md.javascript --ext .md.jsx packages/request-external-access`, there should be no errors

[markdown] Fix lint errors in `packages/request-external-access`

---

packages/social-previews/README.md

This PR fixes all markdown errors in `packages/social-previews`
Run `./node_modules/.bin/eslint --ext .md --ext .md.js --ext .md.javascript --ext .md.jsx packages/social-previews`, there should be no errors

[markdown] Fix lint errors in `packages/social-previews`

---

packages/viewport/.eslintrc.js

This PR fixes all markdown errors in `packages/viewport`
Run `./node_modules/.bin/eslint --ext .md --ext .md.js --ext .md.javascript --ext .md.jsx packages/viewport`, there should be no errors

[markdown] Fix lint errors in `packages/viewport`

---

packages/viewport-react/.eslintrc.js

This PR fixes all markdown errors in `packages/viewport-react`
Run `./node_modules/.bin/eslint --ext .md --ext .md.js --ext .md.javascript --ext .md.jsx packages/viewport-react`, there should be no errors

[markdown] Fix lint errors in `packages/viewport-react`

---

packages/webpack-extensive-lodash-replacement-plugin/.eslintrc.js
packages/webpack-extensive-lodash-replacement-plugin/README.md

This PR fixes all markdown errors in `packages/webpack-extensive-lodash-replacement-plugin`
Run `./node_modules/.bin/eslint --ext .md --ext .md.js --ext .md.javascript --ext .md.jsx packages/webpack-extensive-lodash-replacement-plugin`, there should be no errors

[markdown] Fix lint errors in `packages/webpack-extensive-lodash-replacement-plugin`

---

packages/webpack-inline-constant-exports-plugin/.eslintrc.js
packages/webpack-inline-constant-exports-plugin/README.md

This PR fixes all markdown errors in `packages/webpack-inline-constant-exports-plugin`
Run `./node_modules/.bin/eslint --ext .md --ext .md.js --ext .md.javascript --ext .md.jsx packages/webpack-inline-constant-exports-plugin`, there should be no errors

[markdown] Fix lint errors in `packages/webpack-inline-constant-exports-plugin`

---

packages/wpcom.js/History.md
packages/wpcom.js/README.md
packages/wpcom.js/docs/comment.md
packages/wpcom.js/docs/me.md
packages/wpcom.js/docs/media.md
packages/wpcom.js/docs/post.md
packages/wpcom.js/docs/site.md
packages/wpcom.js/docs/users.md
packages/wpcom.js/docs/wpcom.md

This PR fixes all markdown errors in `packages/wpcom.js`
Run `./node_modules/.bin/eslint --ext .md --ext .md.js --ext .md.javascript --ext .md.jsx packages/wpcom.js`, there should be no errors

[markdown] Fix lint errors in `packages/wpcom.js`

---

packages/wpcom-proxy-request/.eslintrc.js

This PR fixes all markdown errors in `packages/wpcom-proxy-request`
Run `./node_modules/.bin/eslint --ext .md --ext .md.js --ext .md.javascript --ext .md.jsx packages/wpcom-proxy-request`, there should be no errors

[markdown] Fix lint errors in `packages/wpcom-proxy-request`

---

client/my-sites/plans-v2/plans-header.tsx

* Now, users coming from the in-place connection flow will be identified by the `source=jetpack-connect-plans` and not by 
`source=jetpack-plans`.
* Run this PR.
* Visit http://calypso.localhost:3000/plans/:site?source=jetpack-connect-plans.
* Verify that a banner that says "Jetpack is now connected. Next select a plan." appears at the top of the page.
* Visit http://calypso.localhost:3000/plans/:site?source=jetpack-plans.
* Verify that there is no banner at the top of the page.
Fixes 1169247016322522-as-1195150225960508

Plans: change the source query parameter that triggers the banner

---

client/my-sites/themes/auto-loading-homepage-modal.jsx

* Removes the `.isRequired` annotation from the `AutoLoadingHomepageModal`'s `installingThemeId` prop
The `installingThemeId` prop isn't actually required because `<AutoLoadingHomepageModal>` is designed to be mounted and hidden as soon as you navigate to the themes page; before any install process starts.
The `getPreActivateThemeId` selector which provides the value for this prop returns `undefined` when there's no theme install in progress. So even the store considers `undefined` a valid value for this prop.
* open dev console
* go to `/themes/:siteId` in a development build
* see that there is no React warning about a missing `installingThemeId` prop in the `AutoLoadingHomepageModal` component

Fix warning about a missing prop that isn't technically required

---

client/components/domains/domain-registration-suggestion/index.jsx
client/components/domains/premium-badge/index.jsx
client/components/domains/premium-badge/style.scss
client/components/domains/register-domain-step/index.jsx

* We need to limit certain premium domain price points, so we'll get an extra property in the domain pricing API response. We should also not allow premium domains over that price point to be added to the cart.
**when loading the price:**
**when the price is loaded and it's above the price limit:**
**what you see if you click on the info badge:**
see: p99Zz8-1qh-p2
* in the dev or wpcalypso env search for a premium domain that costs above 6000 (search for image.blog for example). Make sure that once the price is loaded the badge changes to "Restricted premium". Verify that the info popover text also changes.

Limit premium domain purchases that exceed the price limit

---

packages/wp-babel-makepot/cli.js
packages/wp-babel-makepot/package.json
packages/wp-babel-makepot/test/__snapshots__/index.js.snap
packages/wp-babel-makepot/test/examples/filter-lines.json
packages/wp-babel-makepot/test/index.js

* Fix handling for multiple file or glob pattern inputs separate by single space character.
* Add missing unit test for filter option.
* Check `localci-new-strings.pot` artifact from `translate` CircleCI job and confirm it contains the newly added and updated strings proposed in this PR. Note that these string updates are only used for testing and **should be dropped** before merging the PR.
* Run with multiple file inputs, e.g. `npx @automattic/wp-babel-makepot "./client/signup/steps/about/*.jsx ./client/signup/steps/domains/*.jsx ./client/signup/steps/plans/*.jsx"` and confirm `./build/bundle-strings.pot` contains the extracted strings from all source files.
* Confirm existing CLI calls are working as they were before, e.g. `yarn run translate`.
Drop …

wp-babel-makepot: Handle multiple file inputs

---

config/horizon.json
config/production.json
config/stage.json

* This will enable premium domain purchases in production (it's enabling the `domains/premium-domain-purchases` feature flag in the production env.
* Just verify that you can see premium domains on staging. Once it's deployed premium domains should be visible when you're not proxied too

Enable premium domain purchases on production

---

client/landing/gutenboarding/constants.ts
client/landing/gutenboarding/onboarding-block/domains/index.tsx
client/landing/gutenboarding/onboarding-block/domains/wait-for-domain-availability.ts
packages/data-stores/src/domain-suggestions/selectors.ts
packages/domain-picker/src/constants.ts
packages/domain-picker/src/domain-picker/index.tsx
packages/domain-picker/src/domain-picker/style.scss
packages/domain-picker/src/domain-picker/suggestion-item.tsx
packages/domain-picker/src/hooks/use-domain-availabilities.ts
packages/domain-picker/test/suggestion-item.tsx

* Using the `.isAvailable` store selector created here https://github.com/Automattic/wp-calypso/issues/41220 to check for domain availability on the UI when on the domain suggestions step of Gutenboarding.
**Available domain testing steps:**
* Go to [/new](https://hash-368cdb6a2ee41916c2f6a2dda24552149e61b319.calypso.live/new)
* Enter a site name you know will generate domains that are available (e.g. "This Domain Should Be Avaialble")
* Select one of the suggested domains when it takes you to `/new/domains`
* Loading spinner should appear and button should be in a disabled state, once the request resolves it should take you to the next step without any issues
* _Optional_ Now follow process through to the end to create a site.
Demo: https://cloudup.com/iNp-8K4y_5r
**Unavailable domain …

Check domain availabilities for domain suggestions on the UI

---

client/my-sites/sidebar-unified/index.jsx
client/my-sites/sidebar-unified/use-domains-view-status.js
client/my-sites/sidebar-unified/use-site-menu-items.js
client/state/admin-menu/selectors/index.js

* Remove left over debugging.
* Modernize tests for presence of menu item props.
* Extract menu items fetch to Hook.
* Extract selector for all domains.
The key is checking that the UI output on `master` and this branch as the same.
* Apply D49005-code
* Apply blog sticker
* Run calypso
* You should see left hand Nav rendered so match API output as generated by D49005-code.
* Apply D49005-code
* Apply blog sticker
* Run calypso
* You should see left hand Nav rendered so match API output as generated by D49005-code. 
* There should be no change!

Nav Unification: DRY up and extract reusable code

---

client/components/theme/more-button.jsx

* Currently, two different `<PopoverMenuItem />` components have the same `key = { option.label }` inside `<ThemeMoreButton />`
* The `key` values are changed to `${ option.label }-geturl` and `${ option.label }-action` to avoid duplicate keys
* open dev console
* go to `/themes/:siteId` in a development build
* on any Theme card, click on the `⋮` button
* see that there is no React warning about duplicate keys

Fix warning about duplicate React keys in ThemeMoreButton

---

packages/data-stores/src/domain-suggestions/actions.ts
packages/data-stores/src/domain-suggestions/constants.ts
packages/data-stores/src/domain-suggestions/reducer.ts
packages/data-stores/src/domain-suggestions/resolvers.ts
packages/data-stores/src/domain-suggestions/selectors.ts
packages/data-stores/src/domain-suggestions/test/reducer.ts
packages/data-stores/src/domain-suggestions/test/selectors.ts
packages/data-stores/src/domain-suggestions/types.ts
packages/domain-picker/src/domain-picker/index.tsx
packages/domain-picker/src/domain-picker/style.scss
packages/domain-picker/src/hooks/use-domain-suggestions.ts

- Refactor the `@wordpress/data` store in `packages/data-stores/src/domain-suggestions` so that it handles (in the store's state) the different errors that can happen while calling the Domain Suggestion APIs:
- network failure
- malformed JSON response from the APIs
- JSON response containing an error message (eg. when the query contains non-latin characters)
- empty string response (which is also a sign of a server error)
- Show an error message to the user, together with a "Retry" button which re-triggers the call to the APIs
- I applied a minor refactor to the logic behind showing different parts of the UI (e.g. show error message vs show domain suggestion results)
- I also refactored the return value `useDomainSuggestion()` hook — it now returns an object with all the variables and …

Gutenboarding: Handle Domain Suggestion APIs failures

---

client/my-sites/sidebar-unified/use-site-menu-items.js
client/state/admin-menu/reducer.js
client/state/admin-menu/test/fixture/menu-fixture.js

With the merge of the REST API endpoint the endpoint now returns data as an array. Thus we need to update the state and component to expect that format.
* Update reducer state shape to expect array data.
* Update `useSiteMenuItems` hook to default to empty array of data.
* No need to apply diffs as they are now merged.
* Apply blog sticker.
* Run calypso
* You should see the Unified Nav loaded as per `master`.
* In the console check the state:
```js
state.adminMenu
```
It should have a shape of:
```js
{
123456: [
// array of menu data (NOT an object!)
]
}
```
Fixes https://github.com/Automattic/wp-calypso/issues/45868

Update unified nav to expect array data from REST API

---

client/jetpack-connect/constants.js
client/jetpack-connect/controller.js
client/jetpack-connect/index.js
client/jetpack-connect/plans.jsx

* With the introduction of Offer Reset, we didn't account for the Atomic reconnection flow. Because of this, we are sending Atomic site owners to the Jetpack Plans page instead of to wp-admin after they reconnect to Jetpack. This PRs changes that by reintroducing a set of redirections we had in the past, including one that solves this issue.
95% of these changes come directly from here: https://github.com/Automattic/wp-calypso/blob/master/client/jetpack-connect/plans.jsx#L74-L94. Make sure to read that piece of code so you understand what redirections are being introduced here.
Prerequisite: Atomic site (Business or eCommerce plan).
* Run this PR.
* Manually disconnect Jetpack via the CLI (go to `:siteDomain/_cli` and type `jetpack disconnect blog` or use Jetpack Debugger - under the Blog …

Jetpack Connect: fix Atomic reconnection flow

---

apps/editing-toolkit/editing-toolkit-plugin/premium-content/subscription-service/class-token-subscription-service.php

We shouldn't decode a token if, well, we don't have a token to decode. Otherwise that will result in fatal errors as reported in p1600868752006200-slack-C0Q664T29.
This PR adds a guard so `decode_token` is only executed if the given token is not empty, which hopefully will stop the fatal errors from happening.
I have not been able to replicate the fatal errors in my sandbox, so not sure how can we test this, but I'm quite confident that this will stop the fatals.

Premium Content: Decode token only if present

---

client/desktop/app-handlers/updater/auto-updater/index.js
client/desktop/app-handlers/updater/index.js
client/desktop/lib/menu/app-menu.js
client/desktop/lib/updater/index.js

This PR adds a manual "Check for Updates" menu item. If an update is available, this feature will follow the established updater flow for each platform (download and install on Mac, Windows; and navigate to WordPress Desktop homepage for Linux). If an update is not available, an "Update not available" dialog is displayed to the user.
<br>
<br>
</p>
Build and run this branch and amend the version number in `desktop/package.json` to verify behavior for update available/not available. (When testing locally, don't forget to set `CONFIG_ENV === release`.),

Desktop manual check for updates

---

apps/editing-toolkit/editing-toolkit-plugin/full-site-editing-plugin.php
apps/editing-toolkit/editing-toolkit-plugin/readme.txt
apps/editing-toolkit/package.json
package.json

Bump the Editing Toolkit plugin to version 2.6.1 that includes a fix for a regression in the Premium Content block (https://github.com/Automattic/wp-calypso/pull/45878)

Editing Toolkit: Bump to version 2.6.1

---

client/assets/stylesheets/shared/_variables.scss
client/blocks/site/index.jsx
client/components/domains/trademark-claims-notice/style.scss
client/components/jetpack/masterbar/style.scss
client/components/tinymce/style.scss
client/layout/sidebar/style.scss
client/layout/style.scss
client/my-sites/sidebar-unified/index.jsx
client/my-sites/sidebar-unified/style.scss
client/post-editor/editor-confirmation-sidebar/style.scss
client/post-editor/editor-ground-control/style.scss
client/post-editor/editor-html-toolbar/style.scss
client/post-editor/editor-sidebar/style.scss
client/post-editor/editor-visibility/style.scss
client/post-editor/style.scss

* Make all the changes needed so that left nav looks (not works) like the wp-admin (spacing, margin, padding perspective) and basic colors
* Apply D49204-code
* ~Apply D49005-code~ Now merged.
* Apply sticker to your sandbox `wp blog-stickers add --sticker=nav-unification --who=<username> --blog_id=<blog_id>`
* Run calyspo and add `?flags=nav-unification` to the url
* Go to your sandboxed site, it should look like per spacing, margin, padding perspective
Fixes #45460

Nav Unification: left nav geometries 

---

client/lib/purchases/types.ts
client/my-sites/plans/current-plan/jetpack-checklist/index.tsx

In cases where a user comes to the Jetpack checklist from the connect flow, it was happening fast enough that the checklist would load before Rewind was available on the site. This was causing the checklist to show the VaultPress checklist task instead of the Jetpack Backup one.
This PR handles this as a special case where if a user has purchased Jetpack Backup within the past 5 minutes and Rewind is unavailable, then the Jetpack Backup task will be shown and the VaultPress task will not be shown.
1. Set up a new Jurassic Ninja site.
2. In the Jetpack plugin code, edit [the plansPromptUrl](https://github.com/Automattic/jetpack/blob/master/class.jetpack-connection-banner.php#L198) to be http://calypso.localhost:3000/jetpack/connect/plans/[SITE_SLUG]/. This will ensure you can test coming …

Jetpack Offer Reset: Update Jetpack checklist Backup item to show for recent purchases

---

client/boot/common.js

This makes all the translated versions of the Jetpack Cloud pricing page available to logged out users.
In an incognito window, visit `http://jetpack.cloud.localhost:3000/[LANGUAGE_SLUG]/pricing` for any language slug. Verify that you are taken to the pricing page for the locale if it is translated, and to the EN version if it is not.
Fixes #1169247016322522-as-1194966372177489

Jetpack Cloud: Make non-EN locales of Jetpack Cloud pricing available when logged out

---

apps/notifications/src/panel/indices-to-html/index.js
apps/notifications/src/panel/templates/functions.jsx
apps/notifications/style.scss

* This pull request begins to address the issues in the web-based notification app, specifically the rendering of blockquotes and horizontal rules in a post detail view, by refactoring some of the formatting logic used to wrap segments of a post in `div`/`p` blocks for display.
* PR also includes some changes required to placate ESLint in the touched files.
* **WIP: Need to finalize styling choices, particularly for `cite` tag, but should be functionally testable.**
* Apply D49621-code in your sandbox and make sure the API is sandboxed.
* Apply this change to calypso, navigate to your Calypso dashboard and open a notification for a post with a blockquote and horizontal rule in its contents. Verify that the blockquote and HR are styled distinctly from surrounding paragraphs.
Fixes #45649 / …

[WIP] Updating parsing logic to account for blockquotes and horizontal rules in notifications

---

client/my-sites/checkout/composite-checkout/hooks/use-shopping-cart-manager/use-initialize-cart-from-server.ts

useInitializeCartFromServer can be provided with two arguments that are used for initialization: `productsToAddOnInitialize` and `couponToAddOnInitialize`. However, it's expected that neither argument will change once the cart has initialized because after that point the hook will not use those arguments.
This change adds a console warning if either of those arguments change (note that for `productsToAddOnInitialize` this is a referential equality check, so it may be incorrect if the array is regenerated).
- Start Calypso with `ENABLE_FEATURES=force-sympathy yarn start` to prevent caching.
- Make sure your shopping cart is empty.
- Visit a renewal URL directly (not by following a link).
- Verify that you see no warnings about `couponToAddOnInitialize` or `productsToAddOnInitialize` and …

Checkout: Add warnings when useInitializeCartFromServer is used incorrectly

---

client/webpack.config.js

Adds a check for the `CHECK_DUPLICATE_PACKAGES=true` environment variable.
If true, `duplicate-package-checker-webpack-plugin` will be enabled.
else, disabled.
* This will disable the plugin during `yarn start` runs by default.
* `yarn start`
* `CHECK_DUPLICATE_PACKAGES=true yarn start`
* `CHECK_DUPLICATE_PACKAGES=false yarn start`

Disable duplicate package checks by default

---

client/document/domains-landing.jsx
client/state/document-head/actions.js
client/state/document-head/reducer.js

* Update document head `link` reducer to accept either a link object, or an array of link objects
* This change also avoids nesting arrays of links into the the global redux state, and avoids a warning being displayed in the browser's console when in development mode
* open dev console
* go to `/themes/:siteId` in a development build
* refresh the page (this warning would only show when rendering the page on the server)
* See that there are no schema State validation errors regarding the document head links (there may be other unrelated warnings)
* Also, open Redux devtool and observe that the `documentHead.links` property in the global state object doesn't have nested arrays as children (but has objects instead)

Fix: avoid nesting arrays of link objects in documentHead redux state

---

client/lib/post-normalizer/test/index.js
client/lib/post-normalizer/test/mocks/lib/safe-image-url.js
client/lib/post-normalizer/utils/max-width-photonish-url.js
client/lib/safe-image-url/index.js
client/lib/safe-image-url/test/index.js

Before this patch, if an image contains any parameter, we just don't display it since we can't route it through Photon. Often images, though, already contain some "size parameters"  (like `w`), either because it already uses a Photon site that we cannot detect (like an Atomic site) or some other internal service to resize the image. 
Part of the problem is also that we attach URL parameters to URLs that we think might be Photon URLs, causing the non-action down the stream (since the URL now has URL parameters).
With this patch, we attempt to remove the size URL parameters and also only modify known Photon URLs.
Find a site through a search that has image URLs (see p5PDj3-4Up-p2) and verify that the images now show.

Reader: Enable photon on external images with size parameters

---

client/my-sites/plan-features/header.jsx

It was suggested that we keep the old billing timeframe copy for plan upgrades because in that case the discount comes from plan credits and is not a discount.
This change will only display the `Save %d` timeframe to users on a free plan.
1. On an existing site, change the currency to PHP, MXN, or INR
2. When the plan is free, the user should see the Save ... copy
3. Add a Personal plan
4. The copy is now the default discount copy, no "Save %d":
5. Change the currency to EUR or USD or another that's not with 1st year discounts. Same copy
6. If the currency is EUR and there's no plan, there should be no discount copy whatsoever.

Update discount copy for bundle upsells

---

client/my-sites/backup/style.scss

Fixes `1164141197617539-as-1195587518788493`.
* Add style rules to make the Actions pop-out/button visible for rewindable activities on sites that have Backup Real-time.
These styling changes are scoped specifically to Calypso via the `.wordpressdotcom` class, so in theory, there's no way anything in Jetpack Could would be affected. They're also scoped to the `.backup__page` class, so no other pages should be affected, either.
**Prerequisite:** To test this PR, you must be able to view the Backup page for a site that has Backup Real-time and a history of rewindable activities.
* Start Calypso in your testing environment and select a site that has Backup Real-time.
* Navigate to the Backup page and find a day that has rewindable activities.
* For all rewindable activities, verify that the …

Backup: Make activity card 'Actions' button visible again for Backup Real-time

---

client/my-sites/sidebar-unified/fallback-data.js
client/my-sites/sidebar-unified/index.jsx
client/my-sites/sidebar-unified/use-site-menu-items.js
client/state/admin-menu/test/selectors.js

The aim of this PR is to ensure that users always see a menu appear immediately in the sidebar without any noticeable delay. To do this, if the menu state is not populated we render a basic menu from a static JSON snapshot. Once the REST API request returns we then hydrate the state and update the UI to use the dynamic data.
This is very much an edge case experience, as once the endpoint data is cached in browser storage users will rarely see the fallback experience. Nonetheless this is an important safe guard to ensure a user never receives an empty menu.
* Update ~`getAdminMenu` selector~ `useSiteMenuItems` hook to return static data from JSON in the event the `getAdminMenu()` selector returns a falsey value due to the state is not yet beingpopulated with menu data from the REST API.
* …

Nav Unification - add scaffolding for admin menu experience from static data

---

client/layout/sidebar/custom-icon.jsx
client/my-sites/sidebar-unified/index.jsx
client/my-sites/sidebar-unified/item.jsx
client/my-sites/sidebar-unified/menu.jsx
client/my-sites/sidebar-unified/style.scss

* Adds dashicons import for nav unification
It seems that they are not in the critical path
- There might be some inconsistencies with `wp-admin` in spacing. They will be handled in a follow up PR
- Feedback icon is served as html `<img src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIyNCIgaGVpZ2h0PSIyNCIgdmlld0JveD0iMCAwIDI0IDI0Ij48cGF0aCBmaWxsPSJub25lIiBkPSJNMTMgNy41aDV2MmgtNXptMCA3aDV2MmgtNXpNMTkgM0g1Yy0xLjEgMC0yIC45LTIgMnYxNGMwIDEuMS45IDIgMiAyaDE0YzEuMSAwIDItLjkgMi0yVjVjMC0xLjEtLjktMi0yLTJ6bTAgMTZINVY1aDE0djE0ek0xMSA2SDZ2NWg1VjZ6bS0xIDRIN1Y3aDN2M3ptMSAzSDZ2NWg1di01em0tMSA0SDd2LTNoM3YzeiIvPjwvc3ZnPg==" alt="" />` we will fix it server side
* Run calyspo 
* Add ?flags=nav-unification to the url
Before | After
-------|------
Fixes #45844

Nav Unification: Adds dash-icons

---

client/lib/analytics/utils/save-coupon-query-argument.js
client/lib/cart/actions.js
client/my-sites/checkout/composite-checkout/composite-checkout.js
client/my-sites/checkout/composite-checkout/hooks/use-redirect-if-cart-empty.ts
client/my-sites/checkout/composite-checkout/hooks/use-shopping-cart-manager/use-shopping-cart-reducer.ts
client/my-sites/checkout/composite-checkout/payment-method-helpers.js

Calling `JSON.parse()` (for invalid JSON) and trying to access `window.localStorage` (eg: private browsing in Safari, browsers that don't support it, when quota is full, etc.) can both throw fatal errors in various circumstances. In most cases, the use of localStorage is not critical to the functioning of the page. 
This PR wraps those uses in `try/catch` to allow checkout to continue functioning even if localStorage is not available or fails to work.
Not all these changes are in the checkout code explicitly, but they are all connected to checkout in some way.
- Start checkout with forced sympathy mode: `ENABLE_FEATURES=force-sympathy yarn start`
- In your purchase management pages, click to renew an existing subscription.
- Verify checkout loads without any errors.

Checkout: guard uses of localStorage and JSON.parse

---

client/my-sites/checkout/cart/upcoming-renewals-reminder.tsx
client/my-sites/checkout/composite-checkout/composite-checkout.js
client/my-sites/checkout/composite-checkout/hooks/use-effect-on-change.ts
client/my-sites/checkout/composite-checkout/hooks/use-shopping-cart-manager/index.ts
client/my-sites/checkout/composite-checkout/hooks/use-shopping-cart-manager/types.ts
client/my-sites/checkout/composite-checkout/hooks/use-shopping-cart-manager/use-cart-update-and-revalidate.ts
client/my-sites/checkout/composite-checkout/hooks/use-shopping-cart-manager/use-initialize-cart-from-server.ts
client/my-sites/checkout/composite-checkout/hooks/use-shopping-cart-manager/use-shopping-cart-reducer.ts

This PR refactors `useShoppingCartManager` to remove the `onEvent` prop. The prop was added as a general side-effect event dispatcher, but it's not typed and it's a leaky abstraction on the hook. Checkout uses it to record analytics events for things like when the shopping cart loads and when new products are added. We can use the hook's returned state in order to record these events rather than forcing the hook to be aware of the API of our analytics handler.
Right now the handling of these events is moved to the `CompositeCheckout` component, as it is the only place where `useShoppingCartManager` is used. In the future, the hook can be moved to a parent context wrapper, and the analytics hooks can be moved there as well, which will keep them bundled with the cart manager without needing …

Checkout: Remove onEvent from useShoppingCartManager

---

client/landing/gutenboarding/onboarding-block/style-preview/preview.tsx
client/landing/gutenboarding/stores/onboard/actions.ts
config/development.json
config/production.json
config/wpcalypso.json

This commit removes the use patterns toolkit feature flag and sets the default value of the API query parameter to `true`. 
In short, we're turning on the patterns toolkit for Gutenboarding in all environments. 
This enables translations of starter designs.
Sweet.
Translations are available for our mag 16 languages: ` 'es', 'pt-br', 'de', 'fr', 'he', 'ja', 'it', 'nl', 'ru', 'tr', 'id', 'zh-cn', 'zh-tw', 'ko', 'ar', 'sv'`
Test at:
`/new/{locale_slug}`
Check the previews for all designs in your locale. Create a site and check that the post and page content is translated.

Gutenboarding: enable patterns toolkit in all environments

---

client/webpack.config.node.js

The server build currently doesn't transpile or bundle the `@automattic/calypso-polyfills` module. Therefore, the `@babel/preset-env` doesn't get a chance to convert the `core-js/stable` import to a cherry-picked list of `core-js` polyfills that the current Node.js really needs. The whole `core-js` package is included instead.
The Node.js version we use needs only two polyfills: `Math.hypot` and `String.matchAll`.
This PR fixed that by:
- adding the "transpile dependencies" Babel loader from `calypso-build`, which already includes `@automattic/calypso-polyfills` on the list
- forcing bundling of `@automattic/calypso-polyfills` and `core-js` instead of externalizing them.
Spinoff of #45774 where I discovered these packages are unwanted externals.
@scinos I'm also fixing the `^calypso/` …

Server build: transpile Calypso polyfills and bundle core-js modules

---

client/lib/safe-image-url/index.js
client/lib/safe-image-url/test/index.js

* `getUrlFromParts` throws an error if there is no protocol, but in the reader we use that function to get a safe image url. So if the reader item url is without a protocol `//example.com/image.png` it breaks the reader. I think we should not throw an error if there is a missing protocol but that might be more complicated than I can do right now so let's un-break the reader by always providing a protocol to the `safeImageUrl` for now.
* You'll have to find a reader post with image that's without protocol `//example.com/imsdisd.png`
* I actually added a test case too

Don't throw an error if there is a missing protocol in `safeImageUrl`

---

client/lib/safe-image-url/index.js
client/lib/safe-image-url/test/index.js

* In #45942 I deployed a fix to `safeImageUrl` but when I think about it - we should force https only if the protocol is missing so here's a PR to fix my fix :(
* Added a new test case for that case too - `safeImageUrl` should properly transform url with http protocol to a photon url without ssl param

Fix `safeImageUrl` to force protocol only if it's missing

---

client/lib/plans/features-list.js

This PR is just a small tweak, changing the line "Subscriber-only Content" to "Subscriber-only content":
Here's a screenshot highlight the line that will change:
* Checkout this PR and start Calypso
* Navigate to the plans page and confirm that the line of copy has changed.

Correcting incorrect case on the plans page.

---

client/my-sites/domains/domain-management/edit/domain-types/mapped-domain-type.jsx
client/my-sites/domains/domain-management/edit/domain-types/registered-domain-type.jsx
client/my-sites/domains/domain-management/edit/domain-types/wpcom-domain-type.jsx
config/development.json
config/horizon.json
config/production.json
config/stage.json
config/wpcalypso.json

* Clean up the old domain management navigation component and feature flag. We're going to use only the new enhanced navigation so no need to keep the old code around.
* Open mapped/registered or wpcom domain and verify that you see the new enhanced domain management nav

Clean up the old domain management navigation component

---

client/my-sites/domains/domain-management/edit/navigation/enhanced.jsx
config/development.json
config/horizon.json
config/production.json
config/stage.json
config/wpcalypso.json

* Clean up the domain management security option feature flag - that's basically it. We're keeping the page and the nav item so no need to keep the feature flag.
* Make sure that you can see the "Security" nav item for registered domain

Clean up the domain management security option feature flag

---

client/my-sites/domains/domain-management/edit/domain-types/mapped-domain-type.jsx
client/my-sites/domains/domain-management/edit/domain-types/registered-domain-type.jsx
client/my-sites/domains/domain-management/edit/domain-types/site-redirect-type.jsx
config/development.json
config/horizon.json
config/production.json
config/stage.json
config/wpcalypso.json

* We'll always show the auto-renew toggle so no need to keep the domain status auto-renew flag - so here's a cleanup
* Make sure that the auto-renew toggle in the domain status screen is shown for mapped/registered or site-redirect types (same as on production).

Clean up the domain management auto-renew feature flag

---

client/my-sites/plans-v2/controller.tsx
client/my-sites/plans-v2/details.tsx
client/my-sites/plans-v2/selector.tsx
client/my-sites/plans-v2/types.ts
client/my-sites/plans-v2/upsell.tsx
client/my-sites/plans-v2/utils.ts

The Jetpack plugin contains URLs that brings users to the pricing page in Jetpack cloud, with their site slug in a query parameter. When they select a product in this page, we want them to land on the checkout page directly, instead of having to see the Jetpack connect site input.
Fixes 1169247016322522-as-1195589446987737
- Download the PR locally and start Calypso
- Start Cloud concurrently with `yarn start-jetpack-cloud-p`
- Check that the selector, details, and upsell pages still work as expected in Calypso, and that you can checkout with an item in your cart
- In Jetpack cloud
- Visit `/pricing` and select a product that has no option, such as Anti-spam. Check that you land on `wordpress.com/jetpack/connect/:product-slug`.
- Visit `/pricing?site=:site-slug` and `/pricing/:site-slug`, …

Consider the site slug passed to the pricing page URL in Jetpack cloud

---

client/my-sites/sidebar-unified/fallback-data.js
client/state/admin-menu/reducer.js
client/state/admin-menu/test/reducer.js

Also updates default data little bit.
* Changes reduce to not append menus but replacing them.
* Run calyspo
* Add `?flags=nav-unification` to the url.
* Switch between multiple sites.
* Makes sure menus don't get appended but rather replaced.

Nav Unification: Don't add menus but replace them.

---

client/my-sites/checkout/checkout/payment-chat-button.jsx
client/my-sites/checkout/composite-checkout/components/wp-checkout-order-summary.js

We have a help link on the checkout form, which opens Chat if the user is purchasing a Business or eCommerce plan (or if they're eligible for live chat anyways). This PR enables presales chat on _all_ plan purchases.
You'll need to make sure Happy Chat has availability for the "Chat with us" button to show. By default Calypso hooks up to our staging Happy Chat environment, so you should be able to sign in at https://hud-staging.happychat.io/ and make sure:
- Your status is 🟢 All Chats
- Preferences > General > Throttle is more than 0
- Preferences > Skills > English is checked
- Preferences > Skills > WordPress.com is checked
Then sign into your dev WordPress.com with a free user (you can create a new throwaway account) and test the following product purchases:
- …

Presales Chat: Open to all plan purchases

---

test/e2e/lib/mocha-hooks.js

* The if statement wasn't correct and was only checking for existence of the variable.
* Locally run `LIVEBRANCHES=true ./node_modules/.bin/mocha specs` and tests should fail
* Run `LIVEBRANCHES=false ./node_modules/.bin/mocha specs` and tests should kick off and run

e2e: Update variable for livebranches check

---

client/my-sites/plans-v2/details.tsx
client/my-sites/plans-v2/upsell.tsx

* On mobile, if you move across pages, the scroll position doesn't get reset, which makes the experience confusing. This PR adds a reset in both the Details and the Upsell pages.
* Run this PR.
* Configure your browser in mobile mode. We want a screen with a small viewport.
* Visit the Plans page `/plans/:site`.
* Test the flows of the following products (without going to checkout): Jetpack Security, Jetpack Backup, and Jetpack Scan.
* Verify that every time you visit the Details page the scroll is reset to the top of the page.
* Verify that every time you visit the Upsell page the scroll is reset to the top of the page.
Fixes 1169247016322522-as-1193973893888697

Plans: scroll to the top when moving across pages

---

client/components/jetpack/card/jetpack-free-card/index.tsx
client/jetpack-cloud/sections/pricing/controller.tsx
client/me/purchases/paths.js
client/my-sites/plans-v2/controller.tsx
client/my-sites/plans-v2/details.tsx
client/my-sites/plans-v2/selector.tsx
client/my-sites/plans-v2/types.ts
client/my-sites/plans-v2/upsell.tsx
client/my-sites/plans-v2/utils.ts
client/my-sites/plans-v2/with-redirect-to-selector.tsx

This PR allows url query parameters to carry over through the plans page product selection flow over to wordpress.com.  This behavior is required for affiliate tracking, such that affiliate traffic starting at `cloud.jetpack.com/pricing?aff=12345&cid=22&sid=33` (notice the affiliate query parameters in the url) will select their plan and have their affiliate cookie set and tracking recorded upon reaching the wordpress.com domain. 
There is a P2 discussion about this here:  p7JFn6-BX-p2#comment-1631
1. Go to wordpress.com, open the console, and enter: `localStorage.setItem('debug', 'calypso:analytics:refer');`
- (This turns on analytics event reporting in the console for wordpress.com, we'll look at the output in a later step)
2. Checkout this PR and run `yarn start-jetpack-cloud`
3. Go to …

Jetpack Cloud: Pricing - carry over url query params to wpcom connect

---

client/lib/abtest/active-tests.js

Resumes signup reskin test  in EN locale
* Go to /start/new. Confirm that you are opening this in the EN locale.
* Make sure you're assigned to reskinned group of reskinSignupFlow a/b test.
* Complete the signup steps, you should be able to complete signup and create a site.

Resumes signup reskin test in EN locale

---

client/my-sites/sidebar-unified/item.jsx

* Change the method that `<MySitesSidebarUnifiedItem>` uses to detect "selected" items
Example
```:
path = "/posts/example.com?flags=nav-unification"
url = "/posts/example.com"
```
`path === url` was not true in this case, but `itemLinkMatches(url, path)` is.
* Visit http://calypso.localhost:3000/plans/example.com?flags=nav-unification
* The purchases menu item should be darker than the rest
Related to #45435

Nav Unification: Improve 'selected' detection

---

client/me/concierge/shared/available-time-card.js
client/me/purchases/concierge-banner/index.jsx
client/my-sites/checkout/upsell-nudge/concierge-quickstart-session/index.jsx
client/my-sites/checkout/upsell-nudge/concierge-support-session/index.jsx

More info: pbBQWj-kR#comment-1156-p2
This PR changes the hardcoded copy to match the new 30 minute duration of the Purchased Concierge session.
It uses a hardcode variable as we don't have access to the real duration until after purchasing a session.
There are 4 locations where this has been replaced:
* Go to /me/concierge
* Select a site with QS session
* Fill in form and submit
* Open any of the days and it should mention that the session has lasts 30mins
* Make sure you have at least 1 QS session (included or purchased) -  this is to make sure the proper banner appears
* Go to /me/purchases
* QS upsell banner should not mention the duration of the QS
* Make sure you have a site {SITE_NAME} without QS sessions 
* Go to /checkout/offer-quickstart-session?site={SITE_NAME}.wordpress.com
* …

Change concierge upsell offer with the new 30 minute duration

---

client/layout/sidebar/custom-icon.jsx
client/my-sites/sidebar-unified/style.scss

This will bring parity with WP Admin's menu, that accepts image URLs, SVGs, and dashicon slugs.
* Expands `SidebarCustomIcon` to also render image URLs in `<img>` tags.
* Apply D50296-code
* Visit http://calypso.localhost:3000/?flags=nav-unification and select an a8c-internal site, like your team p2.
* Make sure the VIP cloud shows up as expected.

Menu Icon: Account for image URLs as icons.

---

client/my-sites/sidebar-unified/index.jsx
client/my-sites/sidebar-unified/menu.jsx

* No functional changes
Sometimes we would get back menu specifications like:
```
{ "1": {MenuItem},
"2": {MenuItem},
"3": {MenuItem},
}
```
Now it's always
`[ {MenuItem}, {MenuItem}, {MenuItem} ]`
We already dropped support for it, but I found two extra places it can
be simplified.
* Visit http://calypso.localhost:3000/plans/example.com?flags=nav-unification
* Ensure the unified sidebar continues to render and also displays children elements as appropriate (for example, Posts should expand to show sub-menu-items under)
related to #45435

Nav Unification: Drop support for "object of objects" adminMenu state shape

---

client/lib/abtest/active-tests.js
client/my-sites/checkout/checkout/index.jsx
client/my-sites/checkout/upsell-nudge/index.jsx
client/my-sites/checkout/upsell-nudge/purchase-modal/constants.js
client/my-sites/checkout/upsell-nudge/purchase-modal/content.jsx
client/my-sites/checkout/upsell-nudge/purchase-modal/index.jsx
client/my-sites/checkout/upsell-nudge/purchase-modal/placeholder.jsx
client/my-sites/checkout/upsell-nudge/purchase-modal/style.scss
client/my-sites/checkout/upsell-nudge/purchase-modal/util.js
client/my-sites/checkout/upsell-nudge/style.scss

* Adds oneClickUpsell A/B test. See pcbrnV-aX-p2 for more details. 
* Make sure you're assigned to `test` group of `oneClickUpsell` abtest.
* Purchase Personal or Premium dotcom plan for your website.
* You may need to remember the receipt ID.
* Visit `/checkout/offer-quickstart-session/RECEIPT_ID/YOUR_SITE_SLUG`. Please replace RECEIPT_ID and YOUR_SITE_SLUG with your owns. It would look like `/checkout/offer-quickstart-session/1234567/testblog.woordpress.com`.
* Ensure you have one or more stored credit cards.
* Click the "Yes, I want a WordPress Expert by my side!" button.
* You should be able to see a modal dialog as below:
* Click on the Pay button and the transaction of purchasing Concierge Session is going to be _automatically_ processed.
* When everything goes okay, a sucess …

Add oneClickUpsell A/B test

---

client/lib/abtest/index.js

* Send a request with `bumpStat` when a a/btest is assigned to a user. Since the Tracks shows delayed data only, it is not possible to watch early data to check if a specific a/b test properly works. This PR will record ad hoc stats in addition to Tracks so we can see early stats as well as Tracks analytics. Check pbxNRc-pJ-p2#comment-673 for more details.
* Set `mc_analytics_enabled` to `true` in `config/development.local.json` to override the flag. (create the file if it doesn't exist) The feature currently is enabled only in production.
* Open the browser console.
* Visit `/start/new` without loggen in user. Also, your locale should be neither EN nor ES.
* Make sure there's a request for bumping stats of the ongoing a/b tests. For example, the following request records a stat for …

ABTest: Call bumpStat when abtest starts.

---

client/my-sites/checkout/checkout/payment-chat-button.jsx

Corrects the Tracks naming convention for properties, so this event stops getting rejected.

Presales chat button: Fix Tracks property naming

---

client/state/admin-menu/reducer.js
client/state/admin-menu/schema.js
client/state/admin-menu/test/reducer.js

This PR addresses https://github.com/Automattic/wp-calypso/issues/45876 by adding the required schema and HO reducer to enable browser persistence for `menus` portion of the `adminMenu` state slice.
This ensures that once the initial API response is cached in the browser IndexDB there is no (less of a) perceivable lag between Calypso UI "load" and the admin menu being "ready" and "available".
~**Note**: this will require that https://github.com/Automattic/wp-calypso/pull/45939 is merged before we can merge this PR.~ Now merged 🥳 
* Adds a `schema.json` for the `menus` portion of the `adminMenu` state.
* Wraps the `menus` portion of the `adminMenu` state with the schema validation reducer to enable browser peristence of state.
* Apply blog sticker ` nav-unification` to …

Add admin menu browser persistence (via schema)

---

client/my-sites/sidebar-unified/fallback-data.js

Updates menu item `Ad Control` to be `AdControl` in the static data in order to better match the menu text in the WPCom code which will create the real menu.
See https://github.com/Automattic/wp-calypso/issues/45995
cc @davemart-in - just an FYI this is happening and why.
* Updates `Ad Control` in the static menu data to match the canonical `AdControl` title from WPCom.
* Comment out this line of code 
https://github.com/Automattic/wp-calypso/blob/ebde236ec9b21ea9621c0b0523bd5ea185523731/client/my-sites/sidebar-unified/use-site-menu-items.js#L24
* Apply blog sticker - see `paYJgx-Zj-p2`
* Build calypso - yarn && yarn start.
* You should see the menu rendered from the static fallback data.
* Click "Settings" and see the menu …

Nav Unification - updates Ad Control in static data to match canonical WPCom menu item name

---

client/layout/sidebar/custom-icon.jsx

* if icon is undefined or not supplied, doesn't return an icon
* Apply blog sticker `nav-unification` to test site.
* Run calypso - `yarn && ENTRY_LIMIT=entry-main SECTION_LIMIT=home yarn start`
* Submenus should not have an icon either visually or in the html
Before | After
-------|------

Nav Unification: don't return icon if not supplied

---

.stylelintrc
client/assets/stylesheets/_nav-unification.scss
client/assets/stylesheets/shared/_variables.scss
client/components/mobile-back-to-sidebar/index.jsx
client/components/sidebar-navigation/index.jsx
client/layout/masterbar/logged-in.jsx
client/my-sites/sidebar-unified/item.jsx
client/my-sites/sidebar-unified/style.scss

* When a section is not active, clicking that section icon shows the section. Actually switches sections.
* When a section is active, clicking that section icon opens the sidebar and subsequent click closes the sidebar while the sidebar shows corresponding content depending on that section. Actually switches sidebar visibility.
D50265-code has to be reviewed too
* Apply sticker to your sandbox `wp blog-stickers add --sticker=nav-unification --who=<username> --blog_id=<blog_id>`
* Apply D50265-code
* UI should be like https://www.figma.com/file/9cy0DIowQkPAu0rodb9jsL/WP-Admin-for-Dotcom?node-id=343%3A986&viewport=-14159%2C2498%2C2.3297765254974365
* Check that clicking reader and back to my sites behaves as it should
**Calypso**
* Run calyspo and load your sandboxed site
* Add …

Nav Unification: responsive

---

test/e2e/lib/gutenberg/gutenberg-editor-component.js
test/e2e/specs/wp-inline-help-support-search-spec.js
test/e2e/specs/wp-my-home-support-search-spec.js

* The publish panel is now closing on it's own after publishing. The test wants to close it so I made it so that it won't fail if the publish panel isn't there when it tries to close it. 
* It also adjust the item count in inline help after this change https://github.com/Automattic/wp-calypso/pull/45408
* Make sure tests pass in CI

e2e: Fix publish panel and inline help tests

---

test/e2e/config/default.json
test/e2e/lib/driver-helper.js

* This change makes it so that the console logs will only print when we want them to. They are too noisy.
* Make sure tests pass and that console logs don't print out when you run the tests locally.

e2e: Only print console logs when configured to

---

client/me/purchases/cancel-purchase/button.jsx
client/me/purchases/cancel-purchase/index.jsx
client/me/purchases/cancel-purchase/loading-placeholder.jsx
client/me/purchases/controller.jsx
client/me/purchases/manage-purchase/index.jsx
client/my-sites/purchases/controller.js
client/my-sites/purchases/index.js
client/my-sites/purchases/main.tsx

This implements the site-level view for a single subscription cancelation flow at the route ` /purchases/subscriptions/:site/:purchaseId/cancel`, mirroring the account-level route for a single subscription which exists at the route `/me/purchases/:site/:purchaseId/cancel`.
The new route will be available only with the feature flag `site-level-billing`, which is enabled for development and horizon only.
Related to (and builds upon) the site-level purchases list added in https://github.com/Automattic/wp-calypso/pull/45601 and the subscription view from https://github.com/Automattic/wp-calypso/pull/45922
- Visit `/purchases/subscriptions`.
- If you have multiple sites, verify that you see a site picker and that picking a site adds the site slug to the URL.
- …

Site-level billing management: Add cancel payment method page (2)

---

apps/editing-toolkit/editing-toolkit-plugin/block-inserter-modifications/new-blocks-showcase.js
apps/editing-toolkit/editing-toolkit-plugin/premium-content/blocks/container/index.js

* Currently, the Premium Content block does not show up in the "Earn" category whenever you search for "Earn" or "Premium Content" in the block search. However, it shows up in the "New" category.
* This PR removes the Premium Content block from the "New" category, and adds it to the "Earn" category.
* Go to https://wordpress.com/block-editor and select a site
* Click on the "+" button at the top left corner of the block editor to search for available Blocks you can use
* Type in "Earn" or "Premium Content". You should see the Premium Content block under the "Earn" category
Fixes 232-gh-dotcom-manage

Change Premium Content Block Category

---

client/me/purchases/cancel-purchase/button.jsx
client/me/purchases/cancel-purchase/index.jsx
client/me/purchases/confirm-cancel-domain/index.jsx
client/me/purchases/controller.jsx
client/my-sites/purchases/controller.js
client/my-sites/purchases/index.js
client/my-sites/purchases/main.tsx
client/my-sites/purchases/paths.ts

This adds a missing piece of the cancel flow to the work committed in https://github.com/Automattic/wp-calypso/pull/45974.
This implements the site-level view for a single domain subscription cancelation flow at the route `/purchases/subscriptions/:site/:purchaseId/confirm-cancel-domain`, mirroring the account-level route for a single subscription which exists at the route `/me/purchases/:site/:purchaseId/confirm-cancel-domain`.
The new route will be available only with the feature flag `site-level-billing`, which is enabled for development and horizon only.
- Visit `/purchases/subscriptions`.
- If you have multiple sites, verify that you see a site picker and that picking a site adds the site slug to the URL.
- Click on a recent domain purchase in the …

Site level payment management: Add cancel domain page

---

client/my-sites/sidebar-unified/index.jsx
client/my-sites/sidebar-unified/menu.jsx

* redirect user when clicking a top level menu if link exists
* Run calyspo 
* Add ?flags=nav-unification to the url
* Click on `Posts` or `Pages` UI should load `posts` and `pages` accordingly
* Click on Setting, you should be redirected to wp-admin
Fixes #45963

Nav Unification: redirect to url when clicking a top level menu

---

client/my-sites/email/email-providers-comparison/index.jsx

This PR adds tracks events for the email providers comparison page.
* Load Calypso with the `email/titan-mvp` flag enabled
* Click add email for a domain
* When the comparison page appears, verify an event is sent
* Verify events are sent on clicks for each provider

Email: Add tracks events to email providers page

---

client/blocks/credit-card-form/helpers.js
client/me/purchases/controller.jsx
client/me/purchases/manage-purchase/index.jsx
client/me/purchases/payment/add-card-details/index.jsx
client/my-sites/purchases/controller.js
client/my-sites/purchases/index.js
client/my-sites/purchases/main.tsx
client/my-sites/purchases/paths.ts

This implements the site-level view for a single subscription add-payment-method flow at the route `/purchases/subscriptions/:site/:purchaseId/payment/add`, mirroring the account-level route for a single subscription which exists at the route `/me/purchases/:site/:purchaseId/payment/add`.
The new route will be available only with the feature flag `site-level-billing`, which is enabled for development and horizon only.
Related to (and builds upon) the site-level purchases list added in https://github.com/Automattic/wp-calypso/pull/45601 and the subscription view from https://github.com/Automattic/wp-calypso/pull/45922
Fixes #45679
To view the new route directly, navigate to /purchases/subscriptions/:site/:purchaseId, where :site is the site URL and …

Site level payment management: Add change payment method route

---

apps/notifications/src/panel/indices-to-html/index.js

This pull request, combined with D50382, updates the notifications app to allow divs marked as spacer blocks to be rendered as allowed tags in web notification previews of posts.
* Apply D50382-code in your sandbox and make sure the API is sandboxed.
* Apply this change to calypso, navigate to your Calypso dashboard and open a notification for a post with a spacer block in its content. Verify that the spacer is displayed in the notification post preview. 
Before:
After:

Notifications: Adding support for spacer blocks to web notification rendering

---

client/me/purchases/manage-purchase/index.jsx
client/me/purchases/manage-purchase/notices.jsx
client/me/purchases/manage-purchase/plan-details/billing-period.jsx
client/me/purchases/manage-purchase/plan-details/index.jsx
client/me/purchases/manage-purchase/plan-details/test/billing-period.jsx
client/me/purchases/manage-purchase/purchase-meta.jsx
client/my-sites/plan-features/actions.jsx

This makes the subscription settings screen read-only for non-owners. 
**Before**
**After**
* Enable the `site-level-billing` flag
* Visit a product (plan, domain, Jetpack) where you're not the original purchaser
* Confirm that no renew, add/change payment methods, or cancel/delete subscription buttons are visible
Fixes # https://github.com/Automattic/wp-calypso/issues/45838

Purchases: Hide plan controls for non-owners at site and account-level

---

client/my-sites/checkout/composite-checkout/components/wp-order-review-line-items.js

`WPOrderReviewList` uses a `map` to render each line item, but that callback function has an early `return` if the item shouldn't be displayed. That returned value (`undefined`) will still return from the `map`, and React will attempt to render it. React cannot render `undefined`, though; it can only render a component, a string, or `null`.
This doesn't actually cause an error, though, for reasons I don't fully understand; possibly related to [the ability to use false in JSX](https://react-cn.github.io/react/tips/false-in-jsx.html).
In this PR, I change that early return to a `filter` so that items that should not be included will be removed from the list.
- Visit checkout when there are line items that include at least one line item with the `tax` type (should be any checkout in a …

Checkout: Make sure WPOrderReviewList never renders undefined

---

client/my-sites/media/main.jsx

Fixes a bug that I believe was introduced in #41961.
**Steps to reproduce:**
1. Go to `/media/site.blog` for any of your sites.
2. In the sidebar, click "Switch Site" and then "Add New Site" at the bottom
Expected result: Calypso navigates to the new site flow at `/start`
Actual result: Calypso crashes during the navigation:
The crash happens because the navigation to signup dispatches a `setSelectedSite( null )` action, triggering a rerender of the Media page -- the Signup UI is rendered only a while later, in one of the following _page.js_ handlers. Then, the `mapStateToProps` tries to access `site.ID` property of the `site` prop, but the `MediaComponent` never gets a `site` prop from its parent.
@tyxla @saramarcondes do you remember why the `{ site }` prop and `site.ID` were added in …

Media: fix runtime TypeError when navigating to page with null selected site

---

client/my-sites/sidebar-unified/index.jsx
client/my-sites/sidebar-unified/item.jsx
client/my-sites/sidebar-unified/menu.jsx
client/my-sites/sidebar-unified/style.scss

As described in [this Issue](https://github.com/Automattic/wp-calypso/issues/46039) it is possible to arrive at a state whereby several menu items appear to be "selected" at once.
This PR adjusts things so that only one menu item ever appears in the "blue" selected state. Moreover the logic for deciding which item is "selected" is moved upward in order that:
* We can apply a class to style the _parent_ menu item if a _child_ is selected.
* We can _automatically_ toggle open the menu section if a child of that section is selected.
Moreover, an appropriate "selected" style is added to child selected links to match WPAdmin.
📺 You can [watch this demo video](https://d.pr/v/2YTV3I).
* Apply blog sticker.
* Run calypso
* Visit …

Avoid multiple selected menu items

---

apps/notifications/style.scss
client/assets/stylesheets/_nav-unification.scss
client/assets/stylesheets/shared/_variables.scss
client/blocks/reader-full-post/style.scss
client/components/back-button/style.scss
client/components/global-notices/style.scss
client/components/tinymce/style.scss
client/extensions/woocommerce/components/action-header/style.scss
client/extensions/woocommerce/style.scss
client/layout/masterbar/style.scss
client/layout/style.scss
client/lib/directly/style.scss
client/me/happychat/style.scss
client/my-sites/plans-v2/plans-filter-bar/style.scss
client/post-editor/editor-sidebar/style.scss
client/reader/search-stream/style.scss
packages/components/src/dialog/style.scss

There are many parts that depend on masterbar height and they are hardcoded, making the testing and implementation of nav unification difficult. This PR attempts to alleviate this by using a global var for masterbar
* introduces `--masterbar-height: 46px` var
* adds `box-sizing: border-box` so that the 1px border is calculated to masterbars height
* replaces all instances of elements being `fixed` with `top: 47px` to `var (--masterbar-height )
* edits `apps/notifications/style.scss` accordingly by removing not needed rules anymore
Repeat below steps with both the flag `?flags=nav-unification` and without it
* load calypso check that sidebar, notifications panel etc appear correctly both in desktop and responsive
**Known Issue** with `?flags=nav-unification` 
This type of gaps will be …

Use masterbar height var instead of explicit values

---

client/landing/gutenboarding/hooks/use-selected-plan.ts
client/landing/gutenboarding/stores/onboard/actions.ts

Somewhere along the line, the feature flag became `coming-soon-v2` in other commits. This just standardizes it for Gutenboarding.
Question: does it make sense? 
Follow the test instructions in https://github.com/Automattic/wp-calypso/pull/45428 but instead of using `/new?flags=gutenboarding/public-coming-soon` use the new flag: `/new?flags=coming-soon-v2`

Coming Soon: update Gutenboarding coming soon flag

---

client/layout/masterbar/logged-in.jsx

Clicking `me` should:
- focus on the sidebar when already focused to me sections
- focus to me content
- fixed bug when clicking my sites after me wasn't working
- also removed unneeded flag in read url
* run `yarn && yarn start`
* add `?flags=nav-unification` 
* navigate between my-sites, reader, me
* clicking the section icon should open / close the sidebar of the current section or redirect to section if not already there

Nav Unification: Me section routing

---

client/assets/stylesheets/_nav-unification.scss
client/my-sites/sidebar-unified/style.scss

This PR adds a flyout menu that appears on hover to the Calypso sidebar.
For details and design see issue https://github.com/Automattic/wp-calypso/issues/45676
This is an initial prototype implementation for the flyout. It's meant to give us an initial feel for how the flyout in Calypso.
There are two known issues, that we'll have to address next:
- Right now in Calypso the sidebar container is `position:fixed` and it's content is scrollable. The `overflow:auto` on the sidebar prevents the flyout from being visible. We're deactivating it here but this has two side effects: a) the sidebar container isn't scrollable anymore and b) when using the site switcher, the overflow is visible when selecting a site. wp-admin gets around the first issue by not having a scrollable sidebar container but …

Nav unification: add flyout menu to sidebar

---

client/me/purchases/manage-purchase/notices.jsx
client/me/purchases/upcoming-renewals/upcoming-renewals-dialog.tsx

This PR updates the links in the upcoming renewals modal so that they retain the site or account context depending on where they were clicked.
**Before** 
**After**
For this PR to work, you are going to need multiple products on a site with one of them close to expiry. 
* Make sure you have the `site-level-billing` flag enabled.
* Navigate to the site-level billing screen for a site that has multiple subscriptions and at least one of them about to expire.
* Click on the "Other upgrades" link in the notice.
* Click on the "Manage product" link in the modal and make sure you retain the site context. 
* Now go to the account section and try the same — making sure you retain the account level context. 
Related to: https://github.com/Automattic/wp-calypso/issues/45181

Purchases: update upcoming renewal link

---

client/my-sites/checkout/composite-checkout/payment-method-helpers.js

This pull request reactivates WeChat as an allowed payment method on WordPress.com (see #45706 for where it was disabled).  Recent court injunctions in the United States mean that there are no restrictions on WeChat payments, at least for now.
Internal discussion: p2y3YZ-48E-p2
- Use D45650-code (internal server-side change) to force WeChat to be returned by the API
- Enter checkout and confirm that WeChat is one of the available payment methods
- Select it, then go through the process of paying with it (in store sandbox mode) using the "To open and pay with the WeChat Pay app directly, click here" link that appears on the page.
- Make sure the purchase is successful.

Reenable WeChat as a payment method

---

client/lib/titan/has-titan-mail-with-us.js
client/my-sites/email/email-management/gsuite-users-card/index.jsx
client/my-sites/email/email-management/index.jsx
client/my-sites/email/email-management/titan-control-panel-login-card/index.jsx
client/my-sites/email/email-management/titan-control-panel-login-card/style.scss

This PR updates the email management page to show domains with Titan subscription alongside G Suite ones. The component name was not changed to keep it simple since we'd have to update the CSS as well – we can do that in a separate PR.
When a domain has been selected:
When a domain has not been selected:
* Ensure that existing functionality is not broken, i.e. G Suite users/domains are properly shown
* Hack `hasTitanMailWithUs()` to return `true` for a specific domain, and verify that the Titan auto login card is shown for that domain

Email: Display domains with Titan when managing email

---

test/e2e/lib/driver-helper.js
test/e2e/specs/wp-calypso-gutenberg-editor-tracking-spec.js

Update E2E helper so that when opening new windows they have the same viewport set. This is mainly for mobile suites where a new window is open in desktop size:
From mpg artifact (before):
| Original viewport  | New window |
| <img width="1440" alt="Screenshot 2020-10-01 at 15 38 15" src="https://user-images.githubusercontent.com/1451471/94817535-67527b00-03fd-11eb-9b34-7a3b2a941dc7.png"> | <img width="1440" alt="Screenshot 2020-10-01 at 15 38 37" src="https://user-images.githubusercontent.com/1451471/94817251-1e022b80-03fd-11eb-9685-e1ff66f13ed7.png"> |
* Run a (mobile) spec where a new window is being open, i.e. `BROWSERSIZE=mobile ./node_modules/.bin/mocha specs/wp-calypso-gutenberg-editor-tracking-spec.js `;
* Notice how new window, when open, is …

E2E: Keep viewport size when switching to new window

---

client/my-sites/plans-v2/plans-column/index.tsx
client/my-sites/plans-v2/products-column/index.tsx
client/my-sites/plans-v2/utils.ts

In the Plans page, when updating the duration, there's some unnecessary DOM updates of the plans/products cards. This is noticeable because of the icons briefly flashing.
Fixes 1196341175636977-as-1191784463854089
The card React components used to have a key with a value equal to the exact product slug, e.g. `jetpack_security` or `jetpack_security_monthly`. Having a different key makes the card DOM element to re-render completely. I've replaced the value of the key by the more generic product slug (which is the slug of the yearly product) so that it's the same whether the selected duration is monthly or yearly. Because the key is now the same, React doesn't re-render the whole element during the commit phase.
- Visit the _Plans_ page
- Switch the duration from Yearly to Monthly and …

Prevent unnecessary DOM updates when toggling duration the Plans page

---

client/components/jetpack/card/jetpack-free-card/index.tsx
client/components/jetpack/card/jetpack-product-card/features.tsx
client/components/jetpack/card/jetpack-product-card/index.tsx
client/my-sites/plans-v2/details.tsx
client/my-sites/plans-v2/product-card/index.tsx
client/my-sites/plans-v2/selector.tsx
client/my-sites/plans-v2/types.ts
client/my-sites/plans-v2/upsell.tsx

Fixes 1169247016322522-as-1196341175625977
* This PRs add missing tracks to events triggered from Calypso Plans page, Jetpack Connect Plans page, and Calypso Green Plans page (the events are basically the same between these pages).
* Page views are tracked using the `PageViewTracker` component.
* Other events are tracked dispatching an action with `recordTracksEvent`.
This is the list of all events (minus page views), and their names, that are being tracked:
- `calypso_cart_product_add`: dispatched when checkout adds a product to the cart (not controlled by us).
- `calypso_plans_duration_change`: dispatched when users change the duration filter (annually vs monthly).
- `calypso_plans_type_change`: dispatched when users change the product type filter (All, Security, Performance).
- …

Track missing events in WordPress.com, Jetpack Connect and Cloud's Pricing page

---

.circleci/config.yml

* This PR schedules the e2e tests for Gutenberg edge. I had to add in support for some env vars that will be passed so that the script knows that it is for Gutenberg edge and doesn't run domain tests
* Ensure CI tests pass
* Ensure that the test build passes the variables to the Run tests steps- https://app.circleci.com/pipelines/github/Automattic/wp-calypso/75637/workflows/729cb776-a1c9-4f61-8b73-dab2c94df652/jobs/912891

e2e: Schedule gutenberg edge tests

---

client/my-sites/backup/controller.js
client/my-sites/backup/index.js
client/my-sites/scan/controller.js
client/my-sites/scan/index.js

Fixes a regression.
* Add route middlewares to the controllers for both Backup and Scan, so that multi-sites are shown the "unavailable" message regardless of what products or bundles have been purchased.
* Open either Jetpack Cloud or Calypso and select a non-multisite with a bundle or plan that includes Jetpack Backup.
* Go to the **Backup** page.
* Verify that you see the normal, fully-functional Backup page.
* Open either Jetpack Cloud or Calypso and select a non-multisite with a bundle or plan that includes Jetpack Scan.
* Go to the **Scan** page.
* Verify that you see the normal, fully-functional Scan page.
* For both Jetpack Cloud and Calypso, select a multi-site with a bundle or plan that includes Jetpack Backup.
* Go to the **Backup** page.
* Verify that you see the "WordPress …

Jetpack Cloud: Make Backup and Scan unavailable for multi-sites

---

apps/notifications/src/panel/boot/stylesheets/main.scss
apps/notifications/src/panel/indices-to-html/index.js
apps/notifications/style.scss

* This pull request, combined with D50168, updates the notifications app to allow heading elements (h1, h2, etc) to be rendered as allowed tags in web notification previews of posts.
* Apply D50168-code in your sandbox and make sure the API is sandboxed.
* Apply this change to calypso, navigate to your Calypso dashboard and open a notification for a post with various heading levels in its content. Verify that the headings are styled distinctly from surrounding paragraphs (for now, just in bold text) and reflected in the markup.
Before:
After:
Fixes #45649

Notifications: Adding parsing of heading elements to web notifications

---

client/components/data/query-site-purchases/index.jsx
client/my-sites/purchases/subscriptions/index.tsx
client/my-sites/purchases/subscriptions/subscriptions-content.tsx

This modifies site-level subscriptions list (added in https://github.com/Automattic/wp-calypso/pull/45601 and still behind the `site-level-billing` feature flag) so that it only loads data for the site rather than for the user.
Fixes https://github.com/Automattic/wp-calypso/issues/46012 (I hope)
- Visit `/purchases` and verify that you see the "Plan" menu in the sidebar, that it shows the currently active plan (unless it's a Jetpack site, where the active plan will be empty), and that its submenu includes "Plans" and "Billing".
- If you have multiple sites, verify that you see a site picker and that picking a site adds the site slug to the URL.
- Verify that if you have no purchases on that site, you see the "Upgrade now" upsell.
- Verify that if you have purchases on that site, you see …

Site level billing: Only load site-level purchases

---

client/my-sites/checkout/composite-checkout/composite-checkout.js
client/my-sites/checkout/composite-checkout/record-analytics.js

* Adds a new tracks event that fires when the term length of a cart item is changed.
First, enable debug logs in the JS console using `localStorage.setItem('debug', 'calypso:composite-checkout:*,composite-checkout:*')` and refresh the page.
1. Enter checkout with a new purchase that has multiple term length options - the simplest is a plan. (Changing the term length is not available for renewals.)
2. Click to `Edit` the cart contents and change the term length of a product, e.g. from 1 year to 2 years.
3. Watch the JS console for a `heard checkout event` notice with type `CART_CHANGE_PLAN_LENGTH`.
4. Watch for your event named `calypso_checkout_composite_plan_length_change` to appear in tracks; this will take a few minutes.
5. Verify that changing the term length works as expected in …

Checkout: Add calypso_checkout_composite_plan_length_change event and use it (1)

---

client/my-sites/themes/thanks-modal.jsx
client/state/themes/actions/activate.js

This change updates the logic when switching to a template first theme, so that the page layout picker is opened when clicking the Edit Homepage link.
* Open page layout picker when clicking Edit homepage after activating an auto loading homepage theme
* Gate this feature behind Atomic & Jetpack sites, as this is designed to compensate for those environments not supporting auto loading homepages.
* Go to `/themes` while logged in and switch themes in an Atomic or Jetpack site
* You shouldn't see a warning about the homepage automatically changing
* Click "Edit Homepage" and you should be redirected to the editor, with the page layout picker opened
Your Jetpack test site needs to have the Editing Toolkit installed if you want to see the layout picker open. Even without it installed you'll …

FSE: When switching to an auto loading homepage theme, ensure Edit Homepage link opens up the page layout picker in Atomic / Jetpack sites

---

client/blocks/credit-card-form/loading-placeholder.jsx
client/me/purchases/components/loading-placeholder/index.jsx
client/me/purchases/controller.jsx
client/me/purchases/manage-purchase/auto-renew-toggle/index.jsx
client/me/purchases/manage-purchase/index.jsx
client/me/purchases/manage-purchase/notices.jsx
client/me/purchases/manage-purchase/purchase-meta.jsx
client/me/purchases/payment/add-card-details/index.jsx
client/me/purchases/payment/edit-card-details/index.jsx
client/my-sites/purchases/controller.js
client/my-sites/purchases/index.js
client/my-sites/purchases/main.tsx
client/my-sites/purchases/paths.ts
client/my-sites/purchases/utils.js

* In any component which uses the `getEditCardDetailsPath` helper function, turn that function into a prop. This allows us to use the same components in either a site-level or account-level context depending on the caller's preference.
Start by enabling the `site-level-billing` flag.
**Turn on auto-renew**
- Visit a subscription setting screen at the site-level for a product purchased with credits.
- Click the Auto-renew toggle to on and confirm the credit card field shows in the site-level context.
- Add your credit card and save.
- On the settings screen, click the credit card icon to see the add credit card field again in the site-level context.
- Try this at the account level.
**Expiring card notice**
- Visit a subscription setting screen at the site-level for a product purchased with …

Site level billing management: Update links to add/edit card route

---

client/me/purchases/manage-purchase/index.jsx
client/me/purchases/remove-purchase/index.jsx

This PR makes the hardcoded base url a prop so we can pass it from the site-level billing screens. 
**To test the page redirect fix:**
* With the `site-level-billing` flag enabled and store _not_ sandboxed
* Add a plan to your site via Store Admin
* In Calypso, visit Plan > Billing > click on the purchase > click "remove {product}"
* Fill out the pre-removal prompts and click "remove now"
* Verify that the plan is removed, the dialog closes, and you remain on the same screen
**To test the closeDialog fix:**
* In either calypso or on the backend, edit the `/me/purchases/{purchaseId}/delete` endpoint to return an error
* With the `site-level-billing` flag enabled
* On a site with a purchase, visit Plan > Billing > click on the purchase > click "remove {product}"
* Fill out the pre-removal …

Purchase: update remove product base url

---

apps/editing-toolkit/editing-toolkit-plugin/coming-soon/coming-soon.php

Hooks into the `subscription_changed` action to add the coming soon page to new sites when the user purchases a paid subscription. This event is used because the site is always created as a free site and then the plan is added to the free site in a later step.
* Sync this branch to your sandbox with `yarn dev --sync`
* Enable `    define('WPCOM_PUBLIC_COMING_SOON', true);` in your `0-sandbox.php`
* Create a new site with a paid plan
The coming soon page should be added.
If the site uses a free plan or if the WPCOM_PUBLIC_COMING_SOON is false or undefined, the coming soon page should not be added.

Add coming soon page to new sites

---

client/my-sites/pages/page-card-info/index.jsx
client/my-sites/pages/page/index.js
client/state/data-layer/wpcom/sites/homepage/index.js
client/state/pages/selectors.js
client/state/sites/constants.js
client/state/sites/reducer.js
client/state/sites/selectors/get-coming-soon-page-id.js
client/state/sites/selectors/index.js
client/state/sites/selectors/is-coming-soon-mode-active.js

This PR splits out the page selector functionality in https://github.com/Automattic/wp-calypso/pull/45606.
We're adding a coming soon page selector to the ellipsis menu for **sites with a paid plan**. 
We're also showing a coming soon badge to indicate that a page has been selected as coming soon.
Make sure your test site as a paid upgrade, e.g., a personal plan.
Ensure that the new coming soon mode is activated on your test site, e.g., 
```
wp option --url=your_site add wpcom_public_coming_soon 1
```
Go to http://calypso.localhost:3000/pages/{your_site}?flags=coming-soon-v2
Assign a site to be your coming soon page
Check that we're firing the coming soon page set toggle tracks event `calypso_coming_soon_set_page`:
Check that the badge is assigned
Also make sure the network request to …

Coming soon: add coming soon page selector

---

client/me/help/help-contact/index.jsx
client/my-sites/checkout/composite-checkout/components/wp-checkout-order-summary.js
client/state/selectors/get-support-level.js

Makes a few small behind-the-scenes updates in Support pathways:
- Adds new support level for changes to Personal plan
- Updates the chat availability notice to expire when we re-staff for Personal chat
- Adjusts the Tracks plan label sent on presales so it uses consistent labels instead of user-translated labels

Minor support changes

---

apps/editing-toolkit/editing-toolkit-plugin/common/index.scss

In Calypso, when working with certain themes (Seedlet and Balasana so far) and editing the homepage in the block editor, the toolbar is not shown to the user when editing the first block on the page.
This issue is the result of a combination of factors:
- in Calypso, [if the theme requires it, the title of a post is hidden for the homepage](https://github.com/Automattic/wp-calypso/blob/720b5dad4f5217adc9c1de3e2d706b56f6bb7cf9/apps/editing-toolkit/editing-toolkit-plugin/common/index.php#L50-L90). Normally the post/page title adds enough space before the first editor block; but when the title is hidden, there isn't enough space left
- Calypso is currently using version 9.0 of Gutenberg. The upcoming [version 9.1 contains a change](https://github.com/WordPress/gutenberg/pull/25527/files) …

Add vertical space above the first content block when the page title is hidden

---

client/components/domains/domain-registration-suggestion/index.jsx
client/my-sites/domains/domain-search/index.jsx
client/signup/steps/domains/index.jsx
client/state/domains/actions.js

Recently we introduced premium domain purchases in Calypso but we never added any tracking to those so we don't know how often those are suggested or clicked on so here's a small update to fix that.
* ~Add railcar suffix for premium domains~
* Add is_premium property to the `calypso_domain_search_add_button_click` tracks event
* Add `domain_type` property to the traintracks event
* Verify that when premium domains are rendered there is a `#premium` railcar suffix
* Verify that when you click on a premium domain you'll get `is_premium` set to `true` in `calypso_domain_search_add_button_click`

Add premium domain tracking

---

client/blocks/signup-form/index.jsx
client/lib/abtest/active-tests.js

For context, please check pbxNRc-rq#comment-959
* The remove-username test that was launched in https://github.com/Automattic/wp-calypso/pull/45609 came out a winner for the control group in the `onboarding` flow, and we've stopped the test. This PR relaunches the test for the plan-specific flows - /personal, /premium, /business, /ecommerce
* Remove the A/A test that was launched in https://github.com/Automattic/wp-calypso/pull/45770
* Begin signup at the plan-specific flows - http://calypso.localhost:3000/start/personal, http://calypso.localhost:3000/start/premium, http://calypso.localhost:3000/start/business, and http://calypso.localhost:3000/start/ecommerce. 
* Verify that you are assigned to the test `removeUsernameInSignup`.
* If in `control, you should see the username field; if in …

Remove username test: Re-launch test for plan-specific flows

---

client/my-sites/checkout/checkout-thank-you/business-plan-details.jsx
client/my-sites/checkout/checkout-thank-you/personal-plan-details.jsx
client/my-sites/checkout/checkout-thank-you/premium-plan-details.jsx

Updating the checkout Thank You pages to include Earn cards on the Personal, Premium, and Business plan flows. The card describes Earn features and points users to the Earn page to learn more about the features.
Here are screenshots showing the current versions of the Personal, Premium, and Business plan thank you pages:
And here are the screens after edits:
* Checkout this PR and build it.
* Select a site on the Free plan and upgrade it to the Personal, Premium, and Business plans to view the checkout Thank You page.
* Confirm that the updated Earn card appears and that it points users to the Earn page.

Updating thank you page with Earn links.

---

apps/wpcom-block-editor/src/wpcom/features/tracking.js

This patch adds a global handler to be able to pick up information from blocks at a global level, to populate track-event properties, before recording it.
Instructions in D50097-code
Fixes #

Tracking: add a global handler to track embed variations

---

client/my-sites/sidebar-unified/menu.jsx

* use the framework function externalRedirect() as discussed here https://github.com/Automattic/wp-calypso/pull/46008#discussion_r498697080
* run `wp blog-stickers add --sticker=nav-unification --who=<username> --blog_id=<blog_id>` to a site
* load calypso with `?flags=nav-unification` and select the above site
* try navigating to Settings, it should redirect to `wp-admin` withouth any errors in the console

Uses framework function for external redirect

---

client/me/purchases/index.js
client/my-sites/purchases/index.js
client/my-sites/sidebar/index.jsx
config/development.json
config/horizon.json
test/e2e/lib/components/sidebar-component.js
test/e2e/lib/driver-helper.js

This PR removes the site-level-billing flag.
* Test cases documented here: https://github.com/Automattic/wp-calypso/issues/46014#issuecomment-702488897
**To test legacy redirects:**
- visit the site-level view for purchases (`/purchases/subscriptions/:siteName`), remove `/subscriptions` from url, make sure the page is redirected to the one you're currently on
- repeat for a purchase (`/purchases/subscriptions/:siteName/:purchaseId`)
- repeat for a cancellation (`/purchases/subscriptions/:siteName/:purchaseId/cancel`)
- repeat for a domain cancellation (`/purchases/subscriptions/:siteName/:purchaseId/confirm-cancel-domain`)
- repeat for adding a payment method (`/purchases/subscriptions/:siteName/:purchaseId/payment/add`)
- repeat for editing a payment method …

Purchases: Remove site level billing flag

---

client/my-sites/purchases/subscriptions/subscriptions-content.tsx
client/state/purchases/reducer.js

The client/state/purchases reducer has actions to set four boolean variables: `isFetchingSitePurchases`, `isFetchingUserPurchases`, `hasLoadedSitePurchases`, and `hasLoadedUserPurchases`. These are changed when fetching starts and ends. However, if there is an error during fetching, they are left in their previous state. This can cause components that rely on their data to think they never finish fetching.
This PR changes the reducer's error actions such that all those booleans are reset when an error occurrs.
- Visit http://calypso.localhost:3000/purchases/subscriptions/:siteSlug for a site that you are an Editor for.
- Verify that you see the "Looking to upgrade" upsell and that the page finishes loading.

Purchases: unset isLoading and set hasLoaded when an error occurs

---

client/my-sites/sidebar/index.jsx

This PR hides the plans navigation from non site-owners and non-admins. 
**Before**
**After**
* Login as any non admin or non site-owner user type and confirm the Plan navigation is not there.

Hide plan nav  from non site owners or admins (1)

---

apps/editing-toolkit/editing-toolkit-plugin/premium-content/editor.css
apps/editing-toolkit/editing-toolkit-plugin/premium-content/style.css

* Set inline block styles on the jetpack Recurring Payments block from within Premium Content styles.
* Add a right margin to the button on both front end and back end.
* I went back and forth on where this change should live, but ended up in Premium Content because it appears to be specific to this block, I can't test the Premium Content block on a Jetpack site, and I don't want to conflict with existing uses of Recurring Payments. 😥 
* I tested the styles in a bunch of different themes and did not notice any issues, but it's probably worth taking the block for a spin.
**Before**
**After**
* For local development, you'll need to follow the instructions for Editing Toolkit Development in the FG, but it's much easier if you can test the block with calypso.live
* Add a Premium Content block …

Premium Content: Fix logged-out view button alignment 

---

client/my-sites/earn/home.tsx
client/my-sites/earn/refer-a-friend/index.tsx

* Also localize the referral link on the stand-alone /earn/refer-a-friend page
In the Earn section of Calypso, there is a card for referring a friend and an option to copy the link. The link goes to the English version of the page instead of the localized versions.
The referral link should include the locale subdomain. For example, French should be
http://fr.wordpress.com/refer-a-friend/6kvPP1RioVR730bbl0AZ
instead of
http://wordpress.com/refer-a-friend/6kvPP1RioVR730bbl0AZ
The same applies to the stand-alone page https://wordpress.com/earn/refer-a-friend
Testing Instructions
Change user language to a mag-16 language
Scenario 1 
Go to https://wordpress.com/earn and find the referral card
Copy the referral link and paste in a browser
Link should redirect to localized version the …

Earn: Change the referral link to the localized version

---

client/components/domains/premium-badge/style.scss
client/my-sites/domains/domain-management/edit/style.scss
client/my-sites/domains/domain-management/list/style.scss
packages/calypso-color-schemes/src/shared/color-schemes/_contrast.scss
packages/calypso-color-schemes/src/shared/color-schemes/_default.scss

* Add a premium domain color variable in the calypso color scheme and use that for premium badge and premium status color
* @fditrapani will propose color overrides for the different color schemes
* Visually nothing will change, but this will allow us to override the color if you chose another Calypso color scheme
Update: 
Here's how the premium badge and a premium domain status screen looks with the updated colors:

Unify the premium domain color

---

client/landing/gutenboarding/components/signup-form/index.tsx
client/landing/gutenboarding/components/signup-form/style.scss

* Add the fieldset styles into the Gutenboarding signup form as they were removed globally in PR https://github.com/Automattic/wp-calypso/pull/45577 and because we are unable to use `<Fieldset>` component from `client` in Gutenboarding.
**Before**
**After**
* Head over to `/new` for Gutenboarding experience in Incognito or unauthenticated.
* Go through the process until you reach Plans step, and click "Free".
* This should trigger the Signup Form modal to appear.
* Form should not have border.
Fixes https://github.com/Automattic/wp-calypso/issues/46137

Gutenboarding: Add fieldset styles to signup form.

---

client/my-sites/plans-v2/utils.ts

This PR fixes an unfortunate merging error. The original issue is #45936.
_Instructions copied from the original issue_
- Download the PR locally and start Calypso
- Start Cloud concurrently with `yarn start-jetpack-cloud-p`
- Check that the selector, details, and upsell pages still work as expected in Calypso, and that you can checkout with an item in your cart
- In Jetpack cloud
- Visit `/pricing` and select a product that has no option, such as Anti-spam. Check that you land on `wordpress.com/jetpack/connect/:product-slug`.
- Visit `/pricing?site=:site-slug` and `/pricing/:site-slug`, and select the same product. Check that you land on `wordpress.com/checkout/:site-slug/:product-slug`.
- Repeat these steps for the details and upsell pages (e.g. with Backup).

Add products to the checkout URL in Jetpack cloud

---

apps/notifications/src/panel/indices-to-html/index.js

This pull request, combined with D50168, updates the notifications app so that it respects line breaks when rendering text content from posts.
Fixes https://github.com/Automattic/wp-calypso/issues/46106.
* Apply D50582-code in your sandbox and make sure the API is sandboxed.
* Apply this change to calypso, navigate to your Calypso dashboard and open a notification for a post with line breaks within paragraphs in its content. Verify that the line breaks are respected in the display of the post in the notification.
Before:
After:

Notifications: adding support for rendering line breaks

---

client/my-sites/checkout/composite-checkout/components/wp-checkout.js
packages/composite-checkout/src/components/loading-content.tsx

This PR updates the loading placeholder to reflect the two column design.
**Before**
**After**
Nothing changes from a mobile perspective. I tested these changes in Chrome, Firefox, and Safari. 
Load up checkout and confirm that you're seeing a two column preloader that matches the layout of the loaded checkout.

Checkout: Update loading placeholder

---

test/e2e/lib/reporter/magellan-reporter.js
test/e2e/specs/wp-calypso-gutenberg-upgrade-spec.js

* Currently the way we run tests, the output shows skipped tests as having passed. I looked in to how to change that, but it would involve modifying the package. That creates maintenance issues and it isn't that big  of a deal, so as I workaround, I am printing out in the test results when a test is skipped. It will print in magenta.
* In testing this I realized that all tests were showing passed but none were actually running. I moved a before block in to the test block to fix it.
* Ensure tests pass in CI and that skipped tests are shown in the test run log.

e2e: Print out when a test is skipped and Fix all tests showing passed

---

apps/notifications/src/panel/indices-to-html/index.js
apps/notifications/style.scss

*Currently, `p` elements, or paragraphs that are customized with certain styles are not reflected in specific notifications when a user clicks on the notifications button at the top right of the screen on the Home page.
*This PR supports the following styling made in the block editor (and applied to a post), when viewed as a notification
1. Left alignment
2. Center alignment
3. Right alignment
4. Justified paragraphs
5. Italics
6. Strikethrough
7. Text color
8. Underline
9. Subscript
10. Superscript
11. Uppercase
12. Drop cap paragraphs
1. Body font color in the body of the post is inconsistent with the body of the notification
2. Paragraph background color is applied via a single class, but the style varies
3. Paragraph text color is applied via a single class, but the style varies
Can …

Notifications: Support more elements and styling from block editor customizations

---

client/landing/gutenboarding/onboarding-block/style-preview/preview.tsx

This is a tiny janitorial PR: now that D50472-code has landed, remove the `use_patterns` flag from the url for the `template/demo` endpoint since it is no longer needed. (The `use_patterns` flag on the sites/new endpoint is still needed)
* Remove `use_patterns` flag from `template/demo` endpoint design preview in Gutenboarding
* Go to calypso.localhost:3000/new/ko and preview a few of the Gutenboarding designs (e.g. select Cassel or Stratford), and on the `style` step, make sure that the translated preview is loaded.
Part of #46118

Remove use_patterns flag on template/demo endpoint for Gutenboarding preview

---

client/blocks/eligibility-warnings/has-localized-text.js
client/blocks/eligibility-warnings/hold-list.tsx
client/blocks/eligibility-warnings/index.tsx
client/blocks/eligibility-warnings/warning-list.tsx
client/my-sites/site-settings/form-general.jsx

We were using a `hasLocalizedText()` helper function so we could show the updated Coming Soon copy to English speakers before it was available in all languages. All these strings have been translated now so we can remove the now unused strings from the code.
The strings were changed as part of the coming soon v1 work done by Zelda.
Edit: also removed old AT eligibility copy which was also updated as part of the coming soon work. Did it all in one PR to make it easier to then delete the now unused `hasLocalizedText` helper.
* Check that the new strings are available in all languages now (I used translate.wordpress.com)

Coming Soon: Remove old coming-soon copy now that translations are complete

---

client/blocks/eligibility-warnings/has-localized-text.js
client/blocks/eligibility-warnings/hold-list.tsx
client/blocks/eligibility-warnings/index.tsx
client/blocks/eligibility-warnings/warning-list.tsx
client/my-sites/site-settings/form-general.jsx

Reverts Automattic/wp-calypso#46168
Discovered a regression on staging. Some of the coming soon text in the general settings form disappeared. Getting the change off `master` while I figure it out.
Revert was created with GitHub.

Revert "Coming Soon: Remove old coming-soon copy now that translations are complete"

---

client/state/data-layer/http-data.ts

The `fromApi` function is supposed to convert the REST response to an array of `ResponsePair`s, i.e., `[ key, data ]` tuples that are used to store cached pieces of data under corresponding keys. The `ResponseParser` type is pretty clear about that.
The default implementation, however, is simply an identity function that returns the `apiData` unchanged. That doesn't make much sense, and will crash the code that iterates the `fromApi` result with `data.forEach`.
So far, we were lucky that almost all `requestHttpData` usages supply their own `fromApi` implementation and that the default one is almost never used.
This patch changes the default `fromApi` to save the response under the supplied request ID key.
The only usage of the default `fromApi` I found is in …

http-data: fix the default implementation of fromApi

---

bin/install-if-deps-outdated.js
package.json

Our packages.json file is very hard to parse for humans. I try to follow scripts then I get caught by "pre" and "post" hooks, JS files in bin, and so on. Makes it very hard to track repetitive script runs.
I built a dirty tool parse it for us and generate the scripts' dependency graph, and then checks and warns you if any of the scripts calls a script more than once. My tool is fairly complicated and dirty, hence prone to error. But I verified two of these outputs, and they seem accurate:
```sh
"build" has extraneous calls
"build-css" has extraneous calls
"build-desktop:app" has extraneous calls
"build-client-both" has extraneous calls
"build-client-if-prod" has extraneous calls
"start" has extraneous calls
"start-fallback" has extraneous calls
```
In this PR, I'm mostly concerned with …

Cleanup package.json part 1: build packages exactly once

---

client/my-sites/themes/single-site-jetpack.jsx

* Re-enable video premium themes upsell and update its copy.
- Run this PR.
- Select a site with Jetpack Free.
- Visit `/themes/:site`.
- Verify that you see an upsell (see capture below) titled "Get unlimited premium themes".
- Verify that the upsell's copy look like the one in the capture.
- Click the upsell.
- Verify that you end up in checkout with Jetpack Security Real-time in the cart.
- Do the same with a site that has either Jetpack Security Real-time or Jetpack Complete.
- Verify that you don't see the upsell.
Fixes 1196341175636977-as-1196925364225706

Settings: re-enable premium themes upsell and update its copy

---

client/my-sites/site-settings/search.jsx

* Update Jetpack Search upsell copy and target destination.
* The behavior for non-Jetpack sites remains untouched.
- Run this PR.
- Select a site with Jetpack Free.
- Visit `/settings/performance/:site`.
- Verify that you see an upsell (see capture below) in Jetpack Search panel.
- Verify that the upsell's copy look like the one in the capture.
- Click the upsell.
- Verify that you end up in checkout with Jetpack Search in the cart.
- Do the same with a site that has either Jetpack Search or Jetpack Complete.
- Verify that you don't see the upsell.
Fixes 1196341175636977-as-1197426524966355

Settings: update Jetpack Search upsell copy and target

---

client/components/jetpack/daily-backup-status/index.jsx
config/development.json
config/horizon.json
config/jetpack-cloud-development.json
config/jetpack-cloud-horizon.json
config/jetpack-cloud-production.json
config/jetpack-cloud-stage.json
config/production.json
config/stage.json

This PR adds a feature flag in order to enable/disable upcoming features proposed in: 
Project thread: p1HpG7-amG-p2
1. Checkout this branch and start calypso & jetpack cloud.
a. First open terminal and run `yarn start` and wait for calypso to build and start.
b. Then in a new terminal run `yarn start-jetpack-cloud-p`
2. In browser, go to: `http://jetpack.cloud.localhost:3001/backup`
3. Select a site that has backups. (a site with Jetpack Security, Complete, or Backup product)
4. In the Backup Status Card, verify you can see the red text, "Feature Flag: jetpack/backup-simplified-screens is ON" (See Screenshot)
6. Next, test the feature flag in Calypso:
a. Go to: `http://calypso.localhost:3000/backup/:SITE`  (replace :SITE with your site)
7. Verify you can see the red text, "Feature Flag: …

Add Jetpack backup-simplified-screens Feature Flag.

---

client/my-sites/purchases/main.tsx

In https://github.com/Automattic/wp-calypso/pull/46069 a route and page was added for editing stored payment details at the site-level. However, there's a bug in that code wherein the `cardId` prop from the URL is not being passed to the component that requires it. This PR fixes that oversight.
- Visit a subscription setting screen at the site-level for a purchase that has a credit card.
- Click the Change Payment Method button and confirm you're taken to the change credit card form.
- Enter a different card and verify that it changes the card associated with the subscription.

Site level billing: Fix missing `cardId` prop in site-level EditCardDetails

---

client/components/jetpack/daily-backup-status/index.jsx

This removes text that says, "Feature Flag: jetpack/backup-simplified-screens is ON" in Jetpack -> Backup
(`https://wordpress.com/backup/:site`)
1. Run this PR
2. Go to: `http://calypso.localhost:3000/backup/:site` with a site that has backup as product or included in plan.
3. Verify that you don't see the text, "Feature Flag: jetpack/backup-simplified-screens is ON" in the backup card.

Fix/Remove feature flag text.

---

client/my-sites/customer-home/cards/tasks/site-setup-list/style.scss

* Fix #46206 with a temporary bandaid hack using `!important` on styles that are no longer being respected.
* Create a new site starting from `/start` and check that the checklist is rendered correctly
Fixes #46206

Fix site setup checklist styles not applying

---

client/my-sites/backup/main.jsx
client/my-sites/backup/style.scss

As part of the cleaning of some Backup screens (see #46162 and #46165), this PR adds a banner that prompts the user to set up server credentials.
- Run Calypso with `yarn start`
- Run Jetpack cloud concurrently with `yarn start-jetpack-cloud-p`
- Pick a self-hosted Jetpack site with Backup, and server credentials not set yet
- Visit `/backup/:site`
- Check that you see the banner in both environments, and that the copy matches the captures below
- Check that clicking the button redirects you to the credentials form
- Fill the credentials form
- Check that you don't see the banner anymore
_Desktop_
_Mobile_
_Desktop_
_Mobile_

Add  banner that prompts user to enable restores

---

client/layout/logged-out.jsx
client/my-sites/customer-home/cards/tasks/site-setup-list/style.scss

Reverts Automattic/wp-calypso#46133
And https://github.com/Automattic/wp-calypso/pull/46208 that was caused by it.
Looks like it might the culprit behind https://github.com/Automattic/wp-calypso/issues/46206 and https://github.com/Automattic/wp-calypso/issues/46211
Same as for https://github.com/Automattic/wp-calypso/pull/46212 (which will then be not needed)
Visit `/domains/manage/` and make sure the layout is correct:

Revert "Layout: AsyncLoad GdprBanner in LayoutLoggedOut"

---

client/my-sites/post-relative-time-status/index.jsx

On the Posts page, we previously were only displaying the year in a post's displayed timestamp if the post was scheduled to be published more than a year in the future.
This PR changes this so that the year will always display unless the post's (or page's) publish date is within today's calendar year. This includes published posts and posts that are scheduled to be published. Concretely this results in two changes from what's happening today:
* Posts or pages scheduled to be published within 365 days of today, but not in this calendar year, will now include the year in the display date
* _Example, today is 05-10-20, a post scheduled for 01-10-21 will display the year_
* Posts or pages that were published earlier than this calendar year will display the year
* _Example, today is 05-10-20, …

Only omit year from post date when published within a year

---

client/my-sites/plans-v2/utils.ts
client/my-sites/site-settings/media-settings-performance.jsx

* Re-enable video hosting upsell and update its copy. 
- Run this PR.
- Select a site with Jetpack Free.
- Visit `/settings/performance/:site`.
- Verify that you see an upsell (see capture below) in the Media panel.
- Verify that the upsell's copy look like the one in the capture.
- Click the upsell.
- Verify that you are redirected to Jetpack Security Options page (you should be able to see both Daily and Real-time option cards).
- Do the same with a site that has either Jetpack Security or Jetpack Complete.
- Verify that you don't see the upsell.
Fixes 1196341175636977-as-1196942190681395

Settings: re-enable video hosting upsell and update its copy

---

client/my-sites/site-settings/form-analytics.jsx
client/my-sites/site-settings/test/form-analytics.jsx

Currently there is not Google Analytics Upsell banner showing for jetpack sites without a paid plan (Jetpack Free)
Upsell banner should be showing like this:
1. Before checkout out his PR, in Calypso select a site without a purchased plan (Jetpack Free), go to: **Tools** > **Marketing** > **Traffic** > Google Analytics, and observe that Google Analytics Upsell banner is not showing.  (This is the undesired behavior)
2. Checkout this PR, in Calypso select a site without a purchased plan (Jetpack Free), go to: **Tools** > **Marketing** > **Traffic** > Google Analytics, and observe that Google Analytics Upsell banner is now showing:
- verify that the upsell banner links to: `/plans/:site?feature=google-analytics&plan=jetpack_security`
- Verify that the copy matches: …

Update: GA upsell banner for Jetpack Security.

---

client/my-sites/site-settings/form-general.jsx
client/my-sites/site-settings/test/form-general.jsx

* Re-enables coming soon toggle option if v2 is enabled. 
* Effectively rolls back #46034 simultaneously enabling v2 support.
* If `coming-soon-v2` is enabled, the Coming Soon option will set the site option `wpcom_public_coming_soon = 1` (v2 opt) and `wpcom_coming_soon = 0` (v1 opt).
* All other options will set both coming soon options `= 0`
* If `coming-soon-v2` is not enabled, the Coming soon option will set the reverse `wpcom_public_coming_soon = 0` (v2 opt) and `wpcom_coming_soon = 1` (v1 opt).
This means, if we enable `coming-soon-v2` in calypso, anyone with v1 site option will stay on v1. To migrate they will need to flip between public / coming soon again in order to change to v2. The reverse process is also true, if we enable it and then disable it, people will remain on the v2 …

Make Coming Soon option always show regardless of v1/v2

---

client/server/middleware/logger.js
client/server/middleware/test/logger.js

In server logs, rename `version` to `appVersion`. `version` was too generic.
Start the server with COMMIT_SHA=1234 NODE_ENV=production yarn start and go to local calypso. In the console verify there is a field `appVersion:1234`

Rename version to appVersion

---

client/my-sites/earn/memberships/index.jsx

* Remove unused Notice code that showed a message to a user coming to `/earn/payments` from Gutenberg after a successful Stripe connection. We no longer send users from the editor to `/earn/payments` as of #45204 so this Notice is unnecessary.
* Follow the instructions in the FG for sandboxing the store
* Go to `/earn/` and connect to Stripe. You should be redirected back to `/earn/payments` with a successful notice like this:
* Disconnect Stripe
* Go to a Post or Page and add a premium block that requires a Stripe connection, like the Donations block
* Connect to Stripe again; you should be redirected back to the post/page editor after a successful connection.
Fixes #45018

Payments: Remove unused notice code

---

client/me/billing-history/billing-history-table.jsx
client/me/billing-history/main.jsx
client/me/billing-history/style.scss
client/me/billing-history/transactions-header.jsx
client/me/billing-history/transactions-table.jsx
client/my-sites/purchases/controller.js
client/my-sites/purchases/index.js
client/my-sites/purchases/main.tsx
client/state/selectors/get-billing-transaction-app-filter-values.js
client/state/selectors/get-billing-transaction-date-filter-values.js
client/state/selectors/get-filtered-billing-transactions.js

This adds the "Billing history" page to the site-level billing section (initially added by https://github.com/Automattic/wp-calypso/pull/45601), at the URL `http://calypso.localhost:3000/purchases/billing-history/:siteSlug`.
This PR does not link to that page or link back from it in any way. That navigation will be added by the solution to https://github.com/Automattic/wp-calypso/issues/46210.
Also note that the "View receipt" links still go to the account-level pages. That will be handled in the solution to https://github.com/Automattic/wp-calypso/issues/46203.
Requires D50680-code (now merged) to allow filtering receipts by site ID.
Fixes https://github.com/Automattic/wp-calypso/issues/45598
- Visit …

Site level billing: Add billing history page

---

client/my-sites/theme/main.jsx

I should prefix this by saying that the list of bugs with displaying WP.org themes through Calypso is extensive, and I suspect people may run into others while testing this PR. 
This change is _very_ limited in dealing with just one of these bugs: when a user sees a theme that they'd need a Business plan for, warn them of that and hide the "Activate" button. 
Discussion of this is in **p8HJWS-vD-p2**
Things should only change for a non-WordPress.com theme when there is a site without a Business or eCommerce Plan. You can test this by going to `/theme/petals/` and `/theme/petals/site`.
**Before:**
Note: clicking "Activate" would just cause an error - it's probably better to hide the button now because clicking the screenshot links to the demo instead of opening the usual modal. 
**After:** …

Themes: Display Nudge for WP.org Themes for Non-Business Sites

---

client/my-sites/site-settings/seo-settings/form.jsx
client/my-sites/site-settings/seo-settings/test/form.jsx

* Re-enable SEO upsell from Marketing > Traffic section and update its copy.
* Copy for non-Jetpack sites remains untouched.
* Clicking the upsell (Jetpack site only) takes users to Jetpack Security Options page.
- Run this PR.
- Select a site with Jetpack Free.
- Visit /marketing/traffic/:site.
- Verify that you see an upsell (see capture below) in "Search engine optimization" panel.
- Verify that the upsell's copy look like the one in the capture.
- Click the upsell.
- Verify that you are redirected to Jetpack Security Options page (you should be able to see both Daily and Real-time option cards).
- Do the same with a site that has Jetpack Complete.
- Verify that you don't see the upsell.
Fixes 1196341175636977-as-1197426524966358

Marketing: re-enable SEO upsell and update its copy

---

client/my-sites/plans/current-plan/jetpack-product-install/index.tsx
client/state/data-getters/wpcom/jetpack-blogs/keys/index.ts

The `requestPluginKeys` function is called imperatively from the `JetpackProductInstall` component, which handles all the retry and refetch logic. The declarative `freshness` is not really used here.
This patch removes the `options` argument and sets `freshness` to `-Infinity`, asking `http-data` to issue the request on every call, and not try to be smart about it :)
Also simplifies the types, removing complicated declarations like `Parameters< typeof requestHttpData >[ 2 ]`
This patch doesn't change any behavior not fix any bug -- just a cleanup opportunity I found while auditing usages of the `http-data` library.

Jetpack Product Install: simplify the requestPluginKeys code

---

client/components/async-loader/README.md
client/reader/controller.js
client/signup/controller.js
client/state/data-getters/index.js
client/state/data-layer/http-data.ts

Changes the name of the `waitForData` function to `waitForHttpData`, making it consistent with `getHttpData` and `requestHttpData`.
Also changes the shape of the first argument from:
```js
( {
a: () => requestA(),
b: () => requestB(),
} )
```
to
```js
() => ( {
a: requestA(),
b: requestB(),
} )
```
i.e., instead of a "lazy requestor" function for every field, the whole argument
is one "lazy" function that calls all the `request*` function at one.
This new API is more similar to things like Redux `useSelector`:
```js
useSelector( ( state ) => ( {
a: getA( state ),
b: getB( state ),
} );
```
or `@wordpress/data` and its `useSelect`:
```js
useSelect( ( select ) => ( {
a: select( 'a' ).get(),
b: select( 'b' ).get(),
} );
```
It hints at some deeper analogies between all these libraries 💭 …

http-data: rename the waitForData function and modify its API

---

client/my-sites/email/email-providers-comparison/index.jsx

This PR updates the price and features of Titan in the email providers comparison page.
* Load Calypso with the `email/titan-mvp` flag enabled (append `?flags=email/titan-mvp` to the URL)
* Go to your site domains, and click "Add" under the email column for one of your domains
* Confirm you see the same thing as the screenshot above

Emails: Update features and pricing on email providers comparison page 

---

test/e2e/lib/gutenberg/gutenberg-editor-sidebar-component.js

Running again as we recently updated v9.1.0 to v9.1.1.
Tracking issue: https://github.com/Automattic/wp-calypso/issues/45772

Trigger E2E tests for Gutenberg edge (v9.1.1)

---

client/my-sites/plans-v2/controller.tsx
config/desktop-development.json
config/desktop.json
config/development.json
config/horizon.json
config/jetpack-cloud-development.json
config/jetpack-cloud-horizon.json
config/jetpack-cloud-production.json
config/jetpack-cloud-stage.json
config/production.json
config/stage.json
config/test.json
config/wpcalypso.json

Fixes `1196341175636977-as-1198071178569625`.
* Add a new feature flag, `plans/alternate-selector`, to allow for development of an alternate product selector page.
* Set aforementioned feature flag to `true` in all development and horizon environments.
* No visible changes as yet. Verify that everything looks the same on the product selector page whether the flag is enabled or disabled. (Add the query parameter `flags=plans/alternate-selector` to manually enable, or `flags=-plans/alternate-selector` to manually disable.)

Plans: Add feature flag to facilitate work on a new product selector page

---

client/lib/domains/get-domain-type-text.js
client/lib/domains/get-selection-domain.js
client/my-sites/domains/domain-management/edit/navigation/enhanced.jsx

When a domain is pending transfer (pending_registry), we automatically add a domain mapping to ensure the domain starts working with the WPCOM site ASAP. However, that leads to a confusing UX:
It's also causing an unnecessary alert in the sidebar:
In this PR, I'm trying to get rid of the extra mapping row and instead let the transfer one take over some of its functions. Most importantly: setting the DNS records.
This patch requires backend changes: D50440-code.
Find a domain pending transfer (see the backend patch for details). Make sure you only see the transfer domain in Calypso:
There should be no alerts (unless related to the transfer-in).
When viewing details of the transfer-in, you should have the option to manage DNS records:
This should give them a clear idea where to migrate …

Domains: Group mapping and transfers together to reduce confusion

---

client/me/billing-history/billing-history-table.jsx
client/me/billing-history/main.jsx
client/me/billing-history/receipt.jsx
client/me/billing-history/transactions-header.jsx
client/my-sites/purchases/billing-history/index.tsx
client/my-sites/purchases/billing-history/use-redirect-to-history-page-on-invalid-transaction.tsx
client/my-sites/purchases/billing-history/use-redirect-to-history-page-on-wrong-site-for-transaction.tsx
client/my-sites/purchases/controller.js
client/my-sites/purchases/index.js
client/my-sites/purchases/main.tsx
client/my-sites/purchases/paths.ts
client/my-sites/purchases/utils.js

This adds the site-level version of the receipt page at the url `/purchases/billing-history/:siteSlug/:receiptId` building on the site-level billing-history section added in https://github.com/Automattic/wp-calypso/pull/46175.
Fixes https://github.com/Automattic/wp-calypso/issues/46203
First, because this modifies the account-level receipt page (for easier re-use), we should test that to be sure it is not broken.
- Visit `http://calypso.localhost:3000/me/purchases/billing`.
- Click on "View receipt" for any purchase.
- Verify that you see the correct receipt.
- Verify that the sidebar remains at the account-level.
- Click the "Back" link in the header and verify that you're taken back to the account-level billing history page.
Then we can test the …

Site-level billing: Add receipt view

---

client/my-sites/checkout/composite-checkout/components/wp-checkout-order-review.js
client/my-sites/checkout/composite-checkout/components/wp-checkout.js
client/my-sites/checkout/composite-checkout/components/wp-order-review-line-items.js
client/my-sites/checkout/composite-checkout/composite-checkout.js
client/my-sites/checkout/composite-checkout/hooks/use-add-products-from-url.ts
client/my-sites/checkout/composite-checkout/hooks/use-prepare-products-for-cart.ts
client/my-sites/checkout/composite-checkout/hooks/use-shopping-cart-manager/cart-functions.ts
client/my-sites/checkout/composite-checkout/hooks/use-shopping-cart-manager/index.ts
client/my-sites/checkout/composite-checkout/hooks/use-shopping-cart-manager/types.ts
client/my-sites/checkout/composite-checkout/hooks/use-shopping-cart-manager/use-shopping-cart-reducer.ts

When adding products from the URL, if the products are renewals, old checkout [replaced the cart items with the new items](https://github.com/Automattic/wp-calypso/blob/2da3281420d335f95d78a315af0bb6eb7c7e76b2/client/my-sites/checkout/checkout/index.jsx#L273). That behavior was not copied into new checkout. This PR adds that behavior.
- You'll need a site that already has an existing purchase, like a plan.
- Visit checkout with a URL that includes a new plan like `/checkout/example.com/premium` (you can do this by clicking to purchase a product from the `/plans` page).
- Verify that checkout loads with the newly added product displayed.
- Now that there is a plan in the cart, add another product, like a domain mapping (the url would be something like …

Checkout: Replace existing cart products when adding renewals from URL

---

client/lib/post-normalizer/rule-keep-valid-images.js
client/lib/post-normalizer/test/index.js
client/lib/post-normalizer/test/mocks/lib/safe-image-url.js
client/lib/safe-image-url/index.js

Discussed in p5PDj3-4Up-p2.
As of https://github.com/Automattic/wp-calypso/pull/45503, Reader's image filtering discards any image that has a query string _after_ we’ve taken off known Photon size parameters like `w` and `quality`.
However, we don't do this check until quite late in the rendering process, after we've chosen what type of card to display. If there are images that don't meet the standard, they remain in `post.images` and we end up with missing images displayed like this:
This PR adds an earlier `safeImageUrl` check to the 'keep valid images' rule, so any URL that we can't make safe is removed from `post.images` and `post.content_images` before we choose a post card type.
Visit https://wordpress.com/read/feeds/98993195.
Without the PR, there'll be a bunch of empty images (all …

Reader: if an image URL can't be made safe, discard it before the post card type is chosen

---

client/components/language-picker/modal.jsx
client/components/language-picker/test/modal.js

* Add a new event, `calypso_language_picker_language_picked` with the `searched` prop indicating whether search was used to make the language selection. We only emit the event when the language is changed from the initially selected language.
* Ensure new and existing unit tests pass
* Put a breakpoint in the `recordNewLanguagePickedEvent` and `recordSearchTracksEvent` and verify that they are called when expected, under the following conditions:
* for `recordNewLanguagePickedEvent`:
* the following should have `searched === true`
* If you search for a valid language and then close the search box and then close the modal, ensure that the tracks event is fired
* If you search for a valid language and type Enter, ensure that the tracks event is fired
* If you search for a valid language and …

LanguagePicker: Record tracks event for search vs. non-search selection

---

client/blocks/nps-survey/style.scss

* Fixes an issue caused by our `FormLabel` migration in the NPS survey options.
Before:
After:
* Go to `/posts/:site`, And dispatch `{ type: 'NPS_SURVEY_SET_ELIGIBILITY', isSessionPicked: true }` in your Redux console, and the survey will appear
Fixes #

Fix NPS survey label class specificity

---

client/jetpack-cloud/sections/settings/advanced-credentials/host-selection/index.tsx
client/state/data-getters/index.js

The `requestHostingProviderGuess` code is used at only one place, so let's move it there. Makes the global `data-getters` module smaller, and the Jetpack Cloud specific code is not shared with any other entrypoints or chunks.
Fixes typo in naming: hosing -> hosting.
Also patches the `fromApi` function to store only the `guess` response field in the cache, instead of the entire response. Makes the later destructuring (`const { data: guess } = ... `) easier.
The affected Jetpack Cloud flow is not enabled in production: the `jetpack/server-credentials-advanced-flow` is off in all environments.
After enabling it, verify that the hosting provider guess flow is working correctly.

Jetpack Cloud hosting selection: inline the requestHostingProviderGuess handler

---

client/my-sites/checkout/checkout/wechat-payment-box.jsx

Use the `resetHttpData` function to reset the WeChat payment box's redirect state. The function probably didn't exist back when the code was first written.
I have no idea how to test this 🙁

WeChat Payment Box: use the resetHttpData function

---

apps/o2-blocks/src/editor-notes/editor.js

* Editor notes block used `array` as an attribute type instead of string, `RichText` doesn't accept an array, this caused the attributes to be lost on parse.
* Insert a new editor notes block.
* Write some text.
* Save the page.
* Refresh, the text should still be there.
Fixes #40173

Change Editor notes block to use the correct attributes type

---

client/my-sites/plans-v2/controller.tsx
client/my-sites/plans-v2/selector-alt.tsx
client/my-sites/plans-v2/style.scss

* Adds a copy of the current Selector page to be the basis of the new Plans grid.
* Run this PR.
* Check that the current plans page has not been affected.
* Activate the `plans/alternate-selector` flag.
* Make sure the new Selector page is visible (see capture below).
Fixes 1196341175636977-as-1198071178569627

Plans: create an alternative Selector Page

---

client/my-sites/activity/activity-log-tasklist/index.jsx

Removes a redundant `fromApi` argument from the `requestHttpData` calls that upgrade theme or Core on a Jetpack site.
The code uses only the plain response that's [automatically stored by the `http-data` module](https://github.com/Automattic/wp-calypso/blob/e8e3fed4056b9f3da100876592a0e992577cdf90/client/state/data-layer/http-data.ts#L176) under the `core-update-*` and `theme-update-*` keys. The keys stored by the `fromApi` handlers are not used, and are rather weird anyway: the "theme ID" and "Core version" values are used as keys, with no prefix, which can lead to conflicts in a global key-value store.
Test on a Jetpack site with outdated Core and/or theme version. Attempt to trigger upgrade from the Activity Log Task List.

Activity Log: remove redundant fromApi options from theme/core upgrade requests

---

client/my-sites/purchases/billing-history/index.tsx
client/my-sites/purchases/main.tsx
client/my-sites/purchases/navigation.tsx
client/my-sites/purchases/subscriptions/account-level-purchase-links.tsx
client/my-sites/purchases/subscriptions/index.tsx

This adds a sectionsNav to the new site-level billing screens. It includes #46175, which adds a second "section" (Billing History) to site-level billing. Those commits will be rebased out after #46175 merges.
We should hold on merging this until #46224 is complete.
Fixes: #46210 
**To test:**
- Navigate to the new site-level billing section: _Plan > Billing_ in the sidebar
- Verify that the sectionNav is displayed
- Verify that the "Purchases" item is selected by default
- Verify that clicking "Billing History" takes you to the site-level billing history screen
- Verify that clicking "Purchases" takes you back to the subscriptions screen
- Verify that you don't see a link to "View all billing history" at the bottom of the subscriptions screen

Billing: add site-level billing section nav

---

client/me/billing-history/billing-history-table.jsx
client/my-sites/purchases/subscriptions/subscriptions-content.tsx

* Update the copy in the empty purchases component and the billing history components at the site level.
- Visit the site level subscription page for a site with no upgrades (`purchases/subscriptions/:siteurl`). Verify that the copy in the no-purchases component is updated and that there are no errors in the console (since this also includes some relative import fixes).
- Visit the site level billing history page for a site with no upgrades (`purchases/billing-history/:siteurl`). Verify that the copy in the history list component is updated.
- Visit the account level billing history page. Verify that the copy is _not_ updated.
Site-level subscriptions:
Site-level billing history:
Account-level billing history:

Site level billing: Update copy in no purchases component

---

client/my-sites/backup/style.scss

This PR fixes the layout of the top banner in the _Backup_ section.
Fixes 1197351014149633-as-1198169024171322
I'm not sure about the purpose of the rule I removed. It didn't change anything in the rest of the page. Anyway, this kind of selector must be avoided.
- Select a Jetpack site that has Backup and no server credentials set
- Visit `/backup/:site`
- Check that the button in the banner is aligned to the right (see capture)

Fix spacing of the "enable restores" banner

---

client/components/forms/form-text-input-with-affixes/style.scss
client/components/gsuite/gsuite-new-user-list/index.tsx
client/components/gsuite/gsuite-new-user-list/new-user.tsx
client/components/gsuite/gsuite-new-user-list/style.scss
client/lib/gsuite/new-users.ts
client/my-sites/email/email-management/gsuite-users-card/index.jsx
client/my-sites/email/gsuite-add-users/index.jsx
client/my-sites/email/gsuite-add-users/style.scss

This pull request updates the `Add G Suite` page in order to refine a few things, and fix several display issues. More specifically, it:
* Fixes margin and alignment issues on small viewports
* Renames section and page titles to make the user experience more consistent with the previous page
* Fixes a wrong height of input fields with affixes (e.g. the one for the email address)
* Reduces the width of the button with the trash icon
* Temporarily hides this button on small viewports instead of displaying it in the middle of the form
* Changes the placeholder of the email input field to be more descriptive
These changes are preliminary work for #46204.
Before | After
------ | -----
Before | After
------ | -----
1. Run `git checkout update/gsuite-add-user-page` and start your server, or open …

G Suite: Refine Add G Suite page and fix display issues

---

packages/composite-checkout/src/components/button.tsx

This PR fixes a visual bug with the processing animation in checkout.
**Before**
**After**
* Visit checkout in Safari and any other browser you can test.
* Complete a purchase and make sure the animation doesn't have zig-zags.

Checkout: Fix Safari processing animation

---

client/blocks/credit-card-form/index.jsx
client/lib/stripe/index.js
client/me/billing-history/main.jsx
client/me/purchases/credit-cards/index.jsx
client/my-sites/purchases/controller.js
client/my-sites/purchases/index.js
client/my-sites/purchases/navigation.tsx
client/my-sites/purchases/paths.ts
client/my-sites/purchases/payment-methods/index.tsx
client/my-sites/purchases/subscriptions/account-level-purchase-links.tsx

This adds new routes to site-level billing for listing payment methods (all of them, since there's no such thing as site-level payment methods) and adding a new credit card.
Fixes https://github.com/Automattic/wp-calypso/issues/45599
- Visit any site-level billing page (eg: click Plan > Billing in the site-level sidebar).
- Click "Payment Methods" in the page navigation.
- Verify that you see all saved payment methods you have on your account.
- Verify that the sidebar remains at the site-level.
- Click "Add credit card".
- Verify that you see the "Add credit card" form.
- Verify that the sidebar remains at the site-level.
- Click the "Back" button in the page header.
- Verify that you return to the site-level payment methods list.
- Click "Add credit …

Site-level billing: Add payment methods page

---

client/components/jetpack/card/jetpack-product-card-alt/features-item.tsx
client/components/jetpack/card/jetpack-product-card-alt/features.tsx
client/components/jetpack/card/jetpack-product-card-alt/index.tsx
client/components/jetpack/card/jetpack-product-card-alt/style.scss
client/jetpack-cloud/sections/pricing/style.scss
client/my-sites/plans-v2/plans-column/index.tsx
client/my-sites/plans-v2/product-card-alt/index.tsx
client/my-sites/plans-v2/products-column/index.tsx
client/my-sites/plans-v2/records-details-alt/index.tsx
client/my-sites/plans-v2/style.scss
client/my-sites/plans-v2/use-item-price.ts
client/my-sites/plans-v2/utils.ts

* Introduce the new simplified version of the `JetpackProductCard` component.
There are still things to do, but I prefer to get this merged so others can start contributing as well. The things we are missing are:
* Make sure the copy is up-to-date.
* Use new icons for features.
* Make single product icons darker blue (`#2271B1`).
* This PR doesn't deal with the layout of the page so don't expect to see the 3 columns yet. The size of the cards might be affected by this.
* We still have options cards instead of daily ones (you can navigate to the Options page) because this PR won't deal with that.
* Upsell are still in place. We will deal with them in another PR.
* Run this PR locally (run both Calypsos).
* Replace line 17 of `client/my-sites/plans-v2/plans-column/index.tsx` with `import …

Plans: new Jetpack Product card UI

---

desktop/Makefile
desktop/bin/build-desktop-secrets.js
package.json

This PR adds some a script to generate application secrets more conveniently when developing/testing locally.
1. Export the correct value of `CALYPSO_SECRETS_ENCRYPTION_KEY`
2. Generate application secrets with `yarn run build-desktop:secrets` or `make -f desktop/Makefile secrets` from repo root

chore: make secrets convenience script

---

client/my-sites/plans-v2/plans-filter-bar/index.tsx
client/my-sites/plans-v2/plans-filter-bar/style.scss
client/my-sites/plans-v2/selector-alt.tsx

* In the filter bar, hide the product type filter and show a discount message.
* Run this PR locally (both envs).
* Visit `http://calypso.localhost:3000/plans/:site`.
* Verify that nothing has changed.
* Add `flags=plans/alternate-selector` to the URL.
* Verify that the filter bar no longer shows the product type filter and that there is a discount message.
* Repeat the exercise in `http://jetpack.cloud.localhost:3001/pricing`.
Fixes 1196341175636977-as-1198055517794771
Calypso Blue
Calypso Green

Plans: add discount message to filter bar (new UI)

---

client/my-sites/plans-v2/plans-filter-bar/style.scss
client/my-sites/plans-v2/products-grid-alt/index.tsx
client/my-sites/plans-v2/products-grid-alt/style.scss
client/my-sites/plans-v2/selector-alt.tsx
client/my-sites/plans-v2/utils.ts

Fixes `1196341175636977-as-1198071178569633`.
All of the following is visible on `SelectorPageAlt`, but only if the `plans/alternate-selector` feature flag is enabled:
* Rename `SelectorAltPage` to `SelectorPageAlt`, for consistency with other `Alt`-suffixed components on this project.
* Remove the product type dropdown.
* Show plans and products of every type.
* Remove the `Alternative` debug text now that it's visibly different from `SelectorPage`.
* Create `ProductsGridAlt` component to handle showing all products and plans on the new product selector page.
* Use `ProductsGridAlt` to render the product listing instead of `PlansColumn` and `ProductsColumn`.
* In `utils.js`, make `getAllOptionsFromSlug` return an empty array instead of null if a product slug does not have any options.
* …

Plans: Create three-column grid layout for new product selector page

---

apps/notifications/src/panel/indices-to-html/index.js
apps/notifications/src/panel/templates/functions.jsx
apps/notifications/style.scss

* This PR, along with D50949-code, updates web notifications to properly render list items with appropriate list style and indentation.
* Apply D50949-code in your sandbox and make sure the API is sandboxed.
* Apply this change to calypso, navigate to your Calypso dashboard and open a notification for a post with both ordered and unordered lists of multiple depths. Verify that all lists are displayed with correct numbering/discs and appropriate indentation.
Before:
After:
Fixes #46113

Notifications - fix list item rendering

---

client/lib/post-normalizer/utils/iframe-is-allowed.js

We just added support for loom.com blocks in our editor:
https://twitter.com/wordpressdotcom/status/1314254687420383233
This PR adds loom.com iframes to the allowed list, so we can display them in Reader too.
Visit http://calypso.localhost:3000/read/feeds/40474296/posts/2955447786. Ensure that the loom.com embed loads and that you can play and pause the video.

Reader: support loom.com embeds

---

client/blocks/comments/comment-likes.jsx
client/blocks/comments/post-comment-list.jsx
client/blocks/like-button/button.jsx
client/state/data-layer/wpcom/comments/index.js
client/state/data-layer/wpcom/comments/test/index.js
client/state/data-layer/wpcom/read/following/mine/index.js

We're were recently experiencing an issue displaying comments from Jetpack sites in the Reader (see https://github.com/Automattic/wp-calypso/issues/46284), which is being worked on separately. When comments are unable to load due to a 400 response, @mreishus observed we were still displaying the 'load more' link in the comment section (p9dueE-1Zi-p2):
This PR adds some logic to only display that link if we've actually got comments to display.
Sandbox the API and roll back your working copy to r214867-wpcom (before the fix was deployed).
Try this post, which will fail to load comments:
http://calypso.localhost:3000/read/feeds/107218703/posts/2952355248
Check that the 'load more' link is absent:
Now go to a post with lots of comments. Ensure you still see the load more link, and that it …

Comments: hide 'load more' if we don't have comments loaded to display

---

apps/wpcom-block-editor/src/calypso/features/iframe-bridge-server.js

(Note: We're doing this because the previous PR https://github.com/Automattic/wp-calypso/pull/46241 was merged too early without rebase so we are triggering a new phab patch and merge the new one instead.)
* Add a comment to explain the conditional registration of the hook added for the checkout overlay.
* Enable Sandbox.
* Run `yarn dev --sync` on `apps/wpcom-block-editor`.
* Open block editor of the free site with the feature flag `?flags=post-editor/checkout-overlay`, e.g. `calypso.localhost:3000/block-editor/post/your_sandboxed_free_site.wordpress.com?flags=post-editor/checkout-overlay`
* Open up developer tools > console, change the frame to `post.php` and run the following snippet in your console `wp.hooks.hasAction( 'a8c.wpcom-block-editor.openCheckoutModal' );` this should return …

Add a comment to registering hook

---

client/my-sites/domains/domain-management/edit/navigation/enhanced.jsx
client/my-sites/domains/domain-management/list/domain-item.jsx

This PR shows Titan Mail in the enhanced navigation menu of a domain, as well as in the domains list, when a domain has an active Titan Mail subscription.
- Hack `hasTitanMailWithUs()` to return `true` for a specific domain
- Ensure Titan Mail shows under the Email column for that domain in the domains list like the screenshot below
- Verify that Titan Mail appears in the enhanced navigation menu when viewing a specific domain
In the enhanced navigation menu:
In the domains list:

Email: Show Titan Mail indicator in enhanced navigation and domains list

---

client/me/purchases/remove-purchase/remove-domain-dialog/index.jsx

This PR adds a warning when canceling a domain with an active Titan Mail subscription, like in the screenshot below:
* Hack `hasTitanMailWithUs()` to return true for a specific domain
* Turn off auto renew for that domain if it's on
* Try to cancel the domain by clicking the `Delete your domain permanently` button
* Verify that the email warning is shown as in the screenshot attached
* Verify that this is not shown for non Titan domains

Email: Add warning that Titan email will stop working when canceling domain

---

client/signup/steps/domains/index.jsx

When visiting a `*.wordpress.com` subdomain that does not exist, you get a landing page like this:
Link goes to https://wordpress.com/start?ref=typo&new=stgstgsnerkgjneg
But it has stopped working at some point. There's two reasons for that:
- The `initialState` is `undefined` in this case which leads to the wrong path in the code - fixed in this patch.
- The URL is missing the `search=yes` parameter - requires backend changes, patch (already merged) in D50861-code.
Visit https://calypso.localhost:3000/start?ref=typo&search=yes&new=examplenonexistingwpcomsubdomain
Verify that `examplenonexistingwpcomsubdomain` was searched for automatically.
Fixes #45750

Signup: Fix automatic domain search from the typo landing page

---

client/jetpack-cloud/sections/pricing/header/index.tsx
client/my-sites/plans-v2/constants.ts
client/my-sites/plans-v2/products-grid-alt/index.tsx
client/my-sites/plans-v2/selector-alt.tsx
client/my-sites/plans-v2/use-get-plans-grid-products.ts

* Instead of showing option/generic cards for Jetpack Security and Jetpack Backup, show the daily version of them.
* Remove upsell step from the flow.
* Update Pricing page header.
* Run this PR locally (both envs).
* Visit the Pricing page `http://jetpack.cloud.localhost:3001/pricing`.
* Verify that the header looks like the capture below (we removed the subtitle).
* Verify that Jetpack Security is no longer an option/generic card and instead it is Jetpack Security Daily.
* Verify that Jetpack Backup is no longer an option/generic card and instead it is Jetpack Backup Daily.
* Click on the Jetpack Backup Daily CTA.
* Verify that you were redirected to the checkout page and that you didn't see the upsell page.
* Repeat the steps in Calypso Blue.
Fixes #

Plans: replace option cards with daily products

---

client/components/jetpack/card/jetpack-product-card-alt/style.scss
client/jetpack-cloud/sections/pricing/style.scss

* Make the background of the cards white by default and gray in the Pricing page.
* Run this PR locally (both envs).
* Visit `http://jetpack.cloud.localhost:3001/pricing?flags=plans/alternate-selector`.
* Verify that the background of the cards is gray (see capture below).
* Visit `http://calypso.localhost:3000/jetpack/connect/plans/:site?flags=plans/alternate-selector`.
* Verify that the background of the cards is white (see capture below).
* Visit `http://calypso.localhost:3000/plans/:site?flags=plans/alternate-selector`.
* Verify that the background of the cards is white (see capture below).
Fixes 1196341175636977-as-1198173394037049

Plans: make the background JetpackProductCard white by default

---

client/lib/products-values/translations.js

* In the new 3 columns grid, we want to display a shorter version of Jetpack Search card tagline.
* Run this PR.
* Visit the Plans page (in any environment). Activate the `flags=plans/alternate-selector` flag if necessary.
* Verify that the Jetpack Search card tagline looks like in the capture below.
Fixes 1196341175636977-as-1198189456928793

Plans: update Jetpack Search card tagline

---

client/components/jetpack/card/jetpack-product-card-alt/index.tsx
client/components/jetpack/card/jetpack-product-card-alt/style.scss
client/my-sites/plans-v2/product-card-alt/index.tsx
client/my-sites/plans-v2/records-details-alt/index.tsx
client/my-sites/plans-v2/style.scss

* Instead of using an inline box to display the site's records details use a popover.
* Instead of using the generic `children` property to pass an instance of `RecordDetailsAlt`, now we use a new prop called `searchRecordsDetails`. The main reason for this is that the `RecordDetailsAlt` is displayed in a very specific location of the card which is not going to be used by any other purpose (I believe).
* Run this PR in both Calypso Blue and Green.
* Visit the Plans page in each environment.
* Verify that in Calypso Blue, the Jetpack Search card features a popover icon to the left of its price. 
* Click the icon.
* Verify that the content of the popover looks like the capture below.
* Verify that in Calypso Green the popover icon doesn't appear (there is no site in context).
Fixes …

Plans: in Jetpack Search card show RecordsDetailsAlt as a popover

---

client/components/jetpack/card/jetpack-free-card-alt/index.tsx
client/components/jetpack/card/jetpack-free-card-alt/style.scss
client/my-sites/plans-v2/products-grid-alt/index.tsx
client/my-sites/plans-v2/products-grid-alt/style.scss

This PR implements the alternate free card for Offer Reset^2.
1. Visit cloud.localhost:3001/pricing. Verify that the free card shows and resize the page to test responsiveness. Verify that the CTA link is correct and fires a Tracks event.
2. Test the connect flow and verify that the CTA link returns you to wp-admin.
3. Visit calypso.localhost:3000/plans/:site. Verify that the free card shows and resize the page to test responsiveness. Verify that the CTA link is correct and fires a Tracks event.
Fixes #1196341175636977-as-1198071178569631

Jetpack Offer Reset^2: Add JetpackFreeCardAlt

---

client/components/jetpack/card/jetpack-product-card-alt/style.scss
client/jetpack-cloud/sections/pricing/style.scss
client/jetpack-connect/style.scss
client/my-sites/plans-v2/style.scss

* Give buttons a darker version of Jetpack Green color.
* Give the Features section header a lighter gray color.
* Use Jetpack Green as the primary color in Wordpress.com.
* Run this PR in both environments.
* Visit the three Plans pages: wordpress.com/plans, wordpress.com/jetpack/connect/store, and cloud.jetpack.com/pricing (in your local environment).
* Make sure that all three pages look like in the captures below.
* Remove the flag with `?flags=-plans/alternate-selector`.
* Make sure that all Plans pages look like in production.
Fixes 1196341175636977-as-1198189456928801

Plans: color tweaks for the new 3 columns Plans grid

---

client/lib/wpcom-undocumented/lib/undocumented.js
client/my-sites/themes/auto-loading-homepage-modal.jsx
client/my-sites/themes/auto-loading-homepage-modal.scss
client/state/themes/actions/activate-theme.js
client/state/themes/actions/activate.js
client/state/themes/actions/install-and-activate-theme.js

When user clicks on the **Activate Theme** button, it will:
- Show a popup telling user _"XXX will automatically change your homepage layout. Your current homepage will become a draft. Would you like to continue?"_ <sup>[Screenshot 1]</sup>
When user continues activating the theme, the following happens behind the scenes:
- Existing homepage is moved into **Draft**.
- A new homepage **might** <sup>[3]</sup> be created by the theme and set to **Published**.
- This new homepage **is set immediately** as your homepage. <sup>[2]</sup>
After the theme is activated:
- A popup is shown with the button **"Edit Homepage"** as the next step for the user. <sup>[Screesnhot 2]</sup>
- The homepage setting remains **"A Static Page"**. <sup>[1]</sup>
- No change. Keep everything the way it is.
When user …

Fix theme activation homepage confusion.

---

client/reader/following/main.jsx

We often add a 'vote' banner to the top of Reader for the US election. I thought it'd be good to do the same for the upcoming NZ election on 17th October.
As a user in NZ, ensure that the vote banner appears at the top of your Following feed: http://calypso.localhost:3000/read. Internal users may need to unproxy because your proxied IP address may show you as being in Australia, not New Zealand.
As a user outside NZ, ensure you do not see the banner at all.

Reader: add NZ vote banner

---

test/e2e/localization-data.json

With the recent introduction of subdirs for locales instead of subdomains and fully enabling SV, the e2e tests should be updated to use wordpress.com/sv instead of sv.wordpress.com.
1. Follow the steps at https://github.com/Automattic/wp-calypso/blob/master/test/e2e/README.md and https://github.com/Automattic/wp-calypso/blob/master/test/e2e/docs/running-tests.md#getting-started to prepare for running e2e tests locally
2. Within local Calypso instance `cd test/e2e` and run `./run.sh -I`
3. Confirm that logged-out-redirect-i18n-spec.js e2e test (should redirect to the correct url for wordpress.com (sv)) has passed successfully

Update the test data to use subdir instead of subdomain for SV

---

client/components/jetpack/threat-item-subheader/index.tsx
client/components/jetpack/threat-item-subheader/style.scss
client/state/data-layer/wpcom/sites/scan/index.js

* Add a `Number.isFinite` check to `fixed_on` and `first_detected` API response properties, so that we don't create invalid dates for the UI to display.
* In either Jetpack Cloud or Calypso, select a site that has Jetpack Scan and at least one fixed or ignored threat.
* Navigate to **Jetpack > Scan > History**.
* In React DevTools, check the `status` and `fixedOn` properties of any `ThreatItem` component.
* Verify that if `fixedOn` is a numeric value, text is displayed to show when action was taken on the threat (see reference screenshots).
* Verify that if `fixedOn` is undefined or non-numeric, no "<action taken> on <date>" text is displayed.
* Inspect different fixed/ignored threats to ensure behavior is correct in all cases (i.e., fixed and ignored threats, both with and without "fixed …

Jetpack Scan: Don't show '<action> on <date>' if no date is available

---

client/my-sites/plans-v2/products-grid-alt/style.scss

Fixes `p1602520630011400-slack-CQXNTE9K9`.
* Adjust screen size breakpoint from `$break-small` to `>660px` (deprecated), so that it meshes correctly with Calypso's `Layout` component.
* Move screen size-specific rules to the bottom of the SCSS file for `ProductsGridAlt`, to keep them all together.
* In your testing environment, open the Plans page in Calypso and the Pricing page on Jetpack.com.
* Use your browser's development console to switch to responsive design mode, or view these pages on devices with various screen sizes; specifically, target mobiles, tablets, and desktops.
* Verify that for mobile layouts, only one column is displayed. Product cards should span the full width of the screen (excluding the site navigation panel, if it's visible), with no exterior padding.
* Verify …

Plans: Adjust screen breakpoints to play nicely with existing legacy breakpoints

---

.teamcity/settings.kts

TeamCity is triggering build every time a branch changes (expected) and when a Pull Request changes (unexpected). We don't want to trigger changes when the Pull Request changes to avoid running tests automatically for external contributors.
Broken since #46391
Do not trigger automatic builds on changes to open Pull Requests.
- Can't be tested until merged in master.
- As a sanity check, verify the TC build for this branch doesn't throw syntax errors when parsing the DSL

Do not automatically run builds on changes to Pull Requests

---

config/jetpack-cloud-production.json
config/production.json

This PR applies updates made in #46173, #46165, and #46162 to production (both Calypso and Jetpack cloud)
Fixes 1197351014149633-as-1197406866147385
Just review code changes.

Enable simplified backup screens in production

---

client/components/jetpack/card/jetpack-product-card-alt/index.tsx
client/components/jetpack/card/jetpack-product-card-alt/style.scss
client/my-sites/plan-price-free/index.tsx
client/my-sites/plan-price-free/style.scss
client/my-sites/plans-v2/constants.ts
client/my-sites/plans-v2/product-card-alt/index.tsx
client/my-sites/plans-v2/use-item-price.ts

* Add support for free products.
* Hardcode Jetpack CRM price at -1 (to enable the free price section).
* I will address the technical debt in a follow-up.
* Run this PR (any environment).
* Visit the Plans page.
* Verify that the Jetpack CRM card looks like the capture below.
Fixes 1196341175636977-as-1198189456928808

Plans: support free products in the JetpackProductCard

---

client/components/jetpack/card/jetpack-product-card-alt/style.scss

This PR updates the icon colors for the main features of a Plan.  Single product features remain the same (default checkmark)
- Run this PR locally (both Calypso and Jetpack Cloud)
- Go to the new Plans grid page (`/plans/:site`).
- Turn **off** the feature flag (append `?flags=-plans/alternate-selector` to the url.) and verify the feature icons are grey, without color. (See "Before" images below).
- Next, turn **on** the feature flag (append the `?flags=-plans/alternate-selector` to the url.) and verify the Plans feature lists now have circular icons matching their product and product icon color. (See "After" images below). 
- Verify the circular colored icons are showing in both Calypso(blue) and Jetpack Cloud(green).
Jetpack Security
Jetpack Complete
Jetpack Cloud (Calypso green) …

Add colored icons to features list.

---

client/components/jetpack/card/jetpack-product-card-alt/index.tsx
client/lib/plans/plans-list.js
client/lib/products-values/translations.js
client/my-sites/plans-v2/product-card-alt/index.tsx

* Update Security and Backup product cards with a better name and tagline. Now Jetpack Security is featured as `Jetpack Security` instead of `Security Daily`, and Jetpack Backup is featured as `Jetpack Backup` instead of `Backup Daily`. 
* Run this PR.
* Visit the Plans page (any environment will work).
* Verify that the name in Jetpack Security and Jetpack Backup cards looks like the capture below.
* Verify that the tagline in Jetpack Security and Jetpack Backup cards looks like the capture below.
Fixes 1196341175636977-as-1198202253926309

Plans: new name and tagline for Jetpack Security and Jetpack Backup

---

client/my-sites/plans-v2/product-card-alt/index.tsx

* In the case of products with options, we show the name of the option instead of the name of the product. This doesn't work well when the product is owned (we don't want to say `Jetpack Backup` when a site has `Jetpack Backup Real-time`). With this PR, we take into account if the product is owned by the site.
* Run this PR.
* Select a site with Jetpack Backup Real-time or Jetpack Security Real-time (any product with options works).
* Visit the Plans page in Calypso Blue.
* Make sure that the card of the product displays the real the of the product. In the case of Jetpack Security, it should say `Security Real-time` and not `Jetpack Security`. In the case of Jetpack Backup, it should say `Backup Real-time` and not `Jetpack Backup`.

Plans: show the real name of the product if it's owned

---

client/my-sites/checkout/composite-checkout/payment-methods/credit-card/credit-card-pay-button.js
client/my-sites/checkout/composite-checkout/payment-methods/wechat.js
packages/composite-checkout/README.md
packages/composite-checkout/src/lib/checkout-context.ts
packages/composite-checkout/src/lib/payment-methods/existing-credit-card.js
packages/composite-checkout/src/lib/payment-methods/stripe-credit-card-fields.js
packages/composite-checkout/src/lib/transaction-status.ts
packages/composite-checkout/src/types.ts

The transaction status manager in the composite-checkout package has several statuses for the lifecycle of a transaction, and each one has a semantic meaning which triggers some generalized behavior. For example, the "completed" status redirects to the thank-you page, the "error" status displays an error, and the "redirect" status redirects to an external URL. However, there is one status with no specific meaning, "authorizing".
The "authorizing" status was added originally to represent the need to display 3D Secure authentication for a Stripe credit card. However, since composite-checkout is agnostic to payment methods, it was created instead as a generic "doing something" status that a payment method could use for its own purposes. This allowed the credit card payment method to use it …

Checkout: Remove AUTHORIZING transactionStatus

---

client/my-sites/plan-features/actions.jsx
client/my-sites/plan-features/index.jsx
client/my-sites/plans/current-plan/purchases-listing.jsx
client/state/selectors/get-current-plan-purchase-id.js

* Update the links in `/plans` and `/plans/my-plan` to use site-level routes `/purchases/subscriptions/:siteUrl/:purchaseId` when appropriate
- Select a site with at least one upgrade
- Visit `/plans` and verify that all the "Manage plan" links use the correct site-level route
- Visit `/plans/my-plan` and verify that all the "Manage plan" links use the correct site-level route (watch out- there are two of them!)
Fixes #46219

Link to site level page in purchases listing action button

---

client/components/domains/register-domain-step/index.jsx

Fixes #43304
Fixes #46403
Looks like there's a bug in signup's domains step where the first character is lost when replacing search term.
Kudos to @pottedmeat in https://github.com/Automattic/wp-calypso/issues/43304#issuecomment-673629485 where he did amazing sleuthing 🕵️ 👏 
Start a new site:
http://calypso.localhost:3000/start/domains
On the domains step try different search queries - make sure that when you replace a whole query (select it all and type something else) no characters are lost, especially the first one.
Make sure there are no regressions - only 2 and more character queries should trigger the search.
Be sure to check domain search in Domain Management _and_ in the launch flow for regressions as well.

Domains: Prevent first character from being lost when replacing search term in signup

---

client/my-sites/plans-v2/product-card-alt/index.tsx
client/my-sites/plans-v2/utils.ts

* In the case of product with options, we want to show the generic name of the product in the CTA's label and not the variant.
* Run this PR.
* Visit the Plans page in any environment.
* Make sure that the CTAs of Jetpack Backup and Jetpack Security doesn't mention `Daily` and look like the capture below.

Plans: synchronize the name of the product with the CTA's label

---

client/state/domains/dns/actions.js

* Instead of sending all dns records during an update, we should just send the records that the user is intending to add or remove since there may be other browser instances with an out of sync dns record list.
See testing instructions on D51075-code

Specify added or removed dns records on dns update

---

client/blocks/domain-to-plan-nudge/index.jsx
client/lib/plans/constants.js
client/lib/plans/features-list.js
client/lib/plans/plans-list.js
client/my-sites/checkout/composite-checkout/components/wp-checkout-order-summary.js

Update plans comparison chart, onboarding plan listing and checkout summary to list 'Unlimited email support' and remove mentioning of Live Chat support.
**Request:** pbBQWj-ne-p2
_**IMPORTANT NOTE:** This PR should not be merged before Oct. 13th. Will rebase and merge on that date, once approved. See pbBQWj-ne-p2#comment-1180 for context._
Make sure the following changes are reflected:
**Calypso - Site Admin (/plans)**
Changes:
- Replace “Get access to high-quality….” with “Unlock unlimited, expert email support.”
- Replace “email & live chat support” with “Unlimited email support”
- Replace copy in info box with “Email us any time, any day of the week for personalized, expert support.”
**Onboarding (/start/plans)**
Changes:
- Replace “Get access to high-quality….” with “Unlock …

Plans: Remove Live Chat mentions from Personal plan

---

client/jetpack-cloud/sections/pricing/jpcom-footer/index.tsx
client/jetpack-cloud/sections/pricing/jpcom-masterbar/index.tsx
client/my-sites/plans-features-main/jetpack-faq.jsx

This PR adds Tracks events to the links in the Jetpack footer, header, and faq on the Plans page.
1. Visit http://cloud.localhost:3001/pricing.
2. Open the network tab, filter for `t.gif`, and check "Preserve log".
3. Click all links in the header and footer and verify that each one fires an appropriate Tracks event with appropriate properties.
Fixes #1196341175636977-as-1198189456928811

Jetpack Plans: Add Tracks events to Jetpack footer, header, and faq

---

client/my-sites/plans-v2/products-grid-alt/style.scss

* Avoid having product cards stretch to entire available height.
* Visit the Jetpack pricing pages.
* Ensure you can expand any product on desktop without affecting other columns on their sides.
Before
After

Plans: avoid having product cards stretch vertically

---

config/desktop.json
config/jetpack-cloud-production.json
config/jetpack-cloud-stage.json
config/production.json
config/stage.json
config/test.json
config/wpcalypso.json

* Set to `true` the `plans/alternate-selector` feature on all environments.
* Code review since you won't be able to test this in prod without deploying it.
Fixes 1196341175636977-as-1198189456928818

Plans: launch the new 3 column Plans page

---

client/jetpack-cloud/sections/settings/advanced-credentials/credentials-form/index.tsx

When selecting FTP for credentials, I don't believe we need to provide key verification as an option.
**Before:**
**After:**
* Visit cloud.jetpack.com and use the flag `flags=+jetpack/server-credentials-advanced-flow`

Jetpack Cloud credentials, hide key verification for FTP

---

client/jetpack-cloud/sections/settings/advanced-credentials/credentials-form/index.tsx
client/jetpack-cloud/sections/settings/advanced-credentials/credentials-form/style.scss

Update typography on new Jetpack credentials flow.
**Before:**
**After:**
* Test with flag: `?flags=+jetpack/server-credentials-advanced-flow` on cloud.jetpack.com

Jetpack cloud credentials typography

---

apps/editing-toolkit/editing-toolkit-plugin/full-site-editing-plugin.php
apps/editing-toolkit/editing-toolkit-plugin/readme.txt
apps/editing-toolkit/package.json
package.json

Bump the Editing Toolkit plugin to version 2.7.
* Added coming soon page.
* Added vertical space above the first content block when the page title is hidden
* Added launch flow mobile layout (hiding behind feature flag).
* Removed the Premium Content block from the "New" category, and add it to the "Earn" category.
* Styling fixes to Recurring Payments block.
* Styling fixes to Premium Content block.

Editing Toolkit: Bump to version 2.7.

---

apps/editing-toolkit/editing-toolkit-plugin/global-styles/class-global-styles.php

Fixes translations of Global Styles inside the editing toolkit.
1. Checkout the diff mentioned below on your sandbox (D51081) and sandbox a test website.
2. Change your account language to one of Mag-16. 
3. Choose one of the new block-based themes.
4. Create a new post or page
5. Click on the A icon in the top right corner to open the Global Styles panel
6. Make sure the Global Styles panel is translated in the selected language
Before:
After:

Editing toolkit: Fixes Global Styles plugin translation

---

test/e2e/test/mocha.env.js

* Force-install  `chromedriver` when running e2e tests
* This is achieved by triggering the install process (and overriding certain `env` variables when doing so) in `test/e2e/test/mocha.env.js` — a file that is automatically run by `mocha` during its setup
1. Clear the `./node-modules` folder
2. Run `yarn calypso-doctor` and make suggested amends to your `env` variables
3. Run `yarn install`
4. Setup e2e tests locally, including using the encrypted configuration (refer to the field guide for detailed instructions)
5. Run a test, e.g. `cd test/e2e && ./node_modules/.bin/mocha specs/wp-signup-spec.js`
6. Terminal should show an error about missing `chromedriver` dependency
1. Same instructions from 1 to 5
6. Tests should run correctly, no error in the terminal about missing `chromedriver` …

[e2e] Installchromedriver before running e2e tests

---

test/e2e/specs/wp-plan-purchase-spec.js

* The e2e tests for coupon codes are failing because of a difference in calculation rounding. This change fixes that
* Make sure e2e tests pass in CI

Fix the rounding for coupons

---

test/e2e/test/mocha.env.js

* This PR makes changes to a recently added piece of the mocha script that installs ChromeDriver since yarn doctor was suggesting changes that make it so Chromedriver isn't installed. This was fine, but when ChromeDriver was already installed, it prints out an error that isn't really needed and makes you think something is wrong when it isn't. I am now only logging if the error is something other than "ChromeDriver is already available"
* Make sure tests pass in CI. 
* Run mocha test locally and make sure that the error isn't printed if ChromeDriver is already installed.

E2E: Don't log error for Chromedriver already being available.

---

client/lib/cart-values/types.ts
client/my-sites/checkout/checkout/index.jsx
client/my-sites/checkout/composite-checkout/composite-checkout.js
client/my-sites/checkout/composite-checkout/hooks/use-get-thank-you-url/get-thank-you-page-url.ts
client/my-sites/checkout/composite-checkout/hooks/use-get-thank-you-url/index.ts
client/my-sites/checkout/composite-checkout/hooks/use-shopping-cart-manager/shopping-cart-endpoint.ts
client/my-sites/checkout/composite-checkout/hooks/wpcom-store.ts
client/my-sites/checkout/composite-checkout/test/composite-checkout-thank-you.js
client/my-sites/checkout/composite-checkout/types/wpcom-store-state.ts
client/my-sites/checkout/composite-checkout/use-get-thank-you-url.js
client/state/selectors/is-eligible-for-signup-destination.js
client/state/ui/selectors/get-selected-site.js

In this PR we convert `useGetThankYouUrl` and `getThankYouPageUrl` (which the hook uses) to TypeScript. The logic behind these functions is pretty complex, so this will help to prevent bugs in the future.
This was extracted from https://github.com/Automattic/wp-calypso/pull/46375
This should not have any user-facing changes. 
- Make sure the tests pass for the `getThankYouPageUrl` function.
- `yarn run test-client client/my-sites/checkout/composite-checkout/test/composite-checkout-thank-you.js`
- Visit checkout and complete a purchase. Make sure you are redirected to a thank-you page of some sort.

Checkout: Convert getThankYouUrl to TypeScript

---

client/lib/products-values/translations.js
client/my-sites/plans-v2/constants.ts

* Make all CTAs follow the same naming convention.
* Run this PR (any environment).
* Visit the Plans page.
* Make sure that all CTAs follow the same pattern: `Get Jetpack [product-name]"`.
Fixes 1196341175636977-as-1198217247616085

Plans: make CTAs consistent across JetpackProductCard components

---

client/components/jetpack/card/jetpack-free-card-alt/style.scss
client/jetpack-cloud/sections/pricing/style.scss

The Jetpack Free card had a background of `--studio-gray-0` instead of `--color-surface`. This resulted in an improper display in Calypso. This PR fixes that.
Before:
After:
1. Spin up this PR.
2. In Calypso, visit `/plans/:site?site=:site&source=jetpack-connect-plans`.
3. Verify that the background color of the Free card is the same as the rest of the product cards.
4. In Jetpack Cloud, visit `/pricing`.
5. Verify that the background color of the Free card is the same as the rest of the product cards.
Fixes #1196341175636977-as-1198217247692085

Jetpack Plans: Fix Jetpack Free card background color

---

client/my-sites/checkout/composite-checkout/hooks/use-get-thank-you-url/get-thank-you-page-url.ts
client/my-sites/checkout/composite-checkout/test/composite-checkout-thank-you.js

This is a follow up to https://github.com/Automattic/wp-calypso/pull/44623 which disabled the `offer-quickstart-session` URL for 3DS cards. This PR disables the `offer-plan-upgrade`, which was added last month in https://github.com/Automattic/wp-calypso/pull/44590 and is currently broken for 3DS cards.
Fixes https://github.com/Automattic/wp-calypso/issues/46409
- Add a premium plan to your cart.
- Complete checkout using a 3D Secure card.
- Verify that you are redirected to the thank-you page.

Checkout: Disable business upsell for 3DS

---

client/my-sites/site-settings/podcasting-details/index.jsx

Apple has deprecated and dropped support for the `itunes:keyword` tag. This just adds a notice for the user - we can handle removing the field (if empty) in a different change.
ref: p1602699974038200-slack-podcasting-async-workshop-content
**To test:**
- on a site with podcasting enabled
- visit the podcast settings page, Settings > Writing > Podcasting
- verify that the following explanation is shown for the keywords setting: "The keywords setting has been deprecated. This field is for reference only."

Podcasting: add deprecation notice to podcast keywords field

---

client/landing/gutenboarding/onboarding-block/features/index.tsx
packages/data-stores/src/wpcom-features/features-data.tsx
packages/data-stores/src/wpcom-features/types.ts

Here's an idea for how to quickly translate the features step.
The data store was attempting to use the `i18n-calypso` package to translate the feature copy, but it doesn't seem to work in gutenboarding. By moving the feature copy into the component, it's able to make use of the `useI18n()` hook which is what the rest of gutenboarding uses for translations.
I suspect the reason the copy was in the data store was to model what it would be like if the feature list was served by the back end. In which case we'd get a localised API response back. But given that's not how it works, I actually personally prefer keeping the copy in the view layer anyway.
The code in the data store that's actually shared between gutenboarding and the ETK is the logic about deciding the minimum plan needed given …

Gutenboarding i18n: Move feature copy from data store to component

---

apps/wpcom-block-editor/src/calypso/features/iframe-bridge-server.js

This function seems to be causing issues on Atomic sites. Specifically this code:
```
Object(F.subscribe) ((function () {
var t = Object(F.select) ('automattic/launch').getState().isSidebarOpen;
e.postMessage({
action: 'toggleInlineHelp',
payload: {
hidden: t
}
})
}))
```
with the accompanying error `Object(...)(...) is null`. Since this code runs within a subscribe callback, it will run _every time any data changes in any gutenberg data store._ So I imagine this failure both prevents a lot of things from happening, and also could theoretically make the page unresponsive. 
This code can only be tested after deploying. Thankfully, this simply removes a function call. Therefore, it should be very safe, since nothing is really "expecting" the calypso `toggleInlineHelp` action to be called …

Remove problematic callback from wpcom-block-editor

---

client/lib/abtest/active-tests.js

* Changes the datestamp so that users are not assigned to either control or variant.
* Using private browsing mode, go to https://wordpress.com/start using a EN locale. You should not be assigned to the `reskinSignupFlow` abtest.
* `localstorage.ABTests` should not contain`reskinSignupFlow`.

Pauses the signup reskin test

---

client/jetpack-cloud/sections/settings/advanced-credentials/credentials-form/style.scss
client/jetpack-cloud/sections/settings/advanced-credentials/index.tsx
client/jetpack-cloud/sections/settings/advanced-credentials/style.scss

* Use correct breakpoint syntax
* Make heading font smaller
* Use compact card
**Before:**
**After:**
* Use `flags=+jetpack/server-credentials-advanced-flow` on cloud.jetpack.com

Typography improvements to credential card in Jetpack Cloud

---

client/lib/abtest/active-tests.js

For context, check p5uIfZ-af9-p2
* The new onboarding flow will be rolled out to 100% EN existing users. 
* All such users will see the new onboarding flow when they add a new site from an existing account.
**EN locale**
* Log in to a wpcom account in EN locale and navigate to /start in your browser. 
* Verify that you are redirect to /new and that you see the new onboarding flow.
**Non-EN locale**
* Log in to a wpcom account in non-EN locale and navigate to /start in your browser. 
* Verify that you are _not_ shown the new onboarding flow.
* Type `localStorage.ABTests;` in your browser console and confirm that you don't get freshly assigned to the `existingUsersGutenbergOnboard` test.

New onboarding: Roll out to 100% EN existing users

---

client/my-sites/email/email-providers-comparison/index.jsx

This updates the billing frequency label for Titan, from "Monthly billing" to "Annual or monthly billing".
* Go to /email with the `email/titan-mvp` flag enabled
* Verify that the label has been updated

Email: Update billing frequency label for Titan

---

client/components/jetpack/card/jetpack-free-card-alt/style.scss

* Increase Jetpack Free CTA font-size to 16px to make it consistent with the rest of the cards.
* Run this PR in any environment.
* Visit the Plans page (add `?source=jetpack-connect-plans` to the URL if you're in Calypso Blue, otherwise you won't see the Jetpack Free card).
* Verify that the CTA font-size is 16px.
Fixes 1196341175636977-as-1198219469159093

Plans: increase Jetpack Free CTA font-size to 16px

---

client/components/jetpack/card/jetpack-product-card-alt/index.tsx
client/components/jetpack/card/jetpack-product-card-alt/style.scss

* When a currency is composed of more than one character, it overlaps with the price featured in the card. This is because we are using absolute positioning.
* Run this PR.
* Visit the Plans page in any environment.
* In Store Admin, change your default currency to other than USD (you can also change the currency code directly in the HTML with dev tools).
* Verify that if you have a currency code with more than one character, it doesn't overlap with the price of the product.
Fixes 1196341175636977-as-1198217247616087

Plans: fix currency code position in JetpackProductCard

---

client/blocks/editor-checkout-modal/index.tsx
client/blocks/editor-checkout-modal/style.scss
config/development.json
config/wpcalypso.json

* Update UI for the over-the-editor checkout modal.
* Go to https://calypso.live/?branch=update/checkout-over-editor-ui
* Open the editor for a page or a post of a free site.
* Open up dev console, change the frame to `post.php`, and run the following code.
```js
let cartData = { products: [{
product_id: 1009,
product_slug: 'personal-bundle',
}] };
window.wp.hooks.doAction('a8c.wpcom-block-editor.openCheckoutModal', cartData);
```
* Checkout modal should appear.
Fixes https://github.com/Automattic/wp-calypso/issues/46363

Checkout: Update editor checkout modal UI

---

client/my-sites/hosting/php-version-card/index.js

Change recommended PHP version for Atomic. We default creation to 7.4 now.
- Should see `7.4 (recommended)` instead of `7.3 (recommended)`

Update recommended PHP version to 7.4

---

apps/editing-toolkit/editing-toolkit-plugin/editor-gutenboarding-launch/index.ts
apps/wpcom-block-editor/src/calypso/features/iframe-bridge-server.js
client/gutenberg/editor/calypsoify-iframe.tsx
config/development.json
config/horizon.json
config/production.json
config/stage.json
config/wpcalypso.json

The flag is currently enabled in every environment, and can therefore be assumed as a stable feature.
This is the first of a series of PRs looking at implementing the Persistent launch button in the editor (see pbAok1-1y7-p2 for details)
Related phab patches:
- D51131-code (editing-toolkit)
- D51140-code (wpcom-block-editor)
* Removed `gutenboarding/new-launch` from all environments configuration files
* Removed checks in code, assuming the check would always evaluate to `true`
In theory, **the changes introduced by the PR should only remove code that is not needed anymore**, without causing any changes to the behavior of the "Complete setup" buttons. The following testing instructions are meant to **check for regressions**.
* On root folder, run `yarn start`.
* On …

Remove "gutenboarding/new-launch" feature flag and checks

---

client/my-sites/checkout/composite-checkout/payment-method-processors.js
packages/composite-checkout/src/lib/payment-methods/free-purchase.js
packages/composite-checkout/src/lib/payment-methods/full-credits.js

This is a follow-up to #46337 which converts the Free and Full Credits payment processors to use the new system.
- Test free payment method
- Add a coupon to your cart that gives a 100% discount.
- Attempt a purchase using composite checkout with the "free" payment method.
- Verify that the purchase is successful.
- Test full credits payment method
- Attempt a purchase using composite checkout when you have sufficient credits to cover the entire transaction.
- Verify that the transaction completes successfully.

Checkout: Update Free and Full credits payment processors to use automated responses

---

client/my-sites/checkout/composite-checkout/payment-method-processors.js
packages/composite-checkout/src/lib/payment-methods/paypal.js

This is a follow-up to #46337 which converts the PayPal payment processor to use the new system.
- Test making a purchase using the PayPal payment method. Be sure you are correctly redirected to PayPal (the rest of the transaction is less important to test because this really only changes the redirect).

Checkout: convert PayPal payment processor to use automated response

---

client/blocks/editor-checkout-modal/index.tsx
client/gutenberg/editor/calypsoify-iframe.tsx
client/my-sites/checkout/composite-checkout/composite-checkout.js
client/my-sites/checkout/composite-checkout/hooks/use-get-thank-you-url/get-thank-you-page-url.ts
client/my-sites/checkout/composite-checkout/hooks/use-get-thank-you-url/index.ts
client/my-sites/checkout/composite-checkout/payment-method-processors.js
client/my-sites/checkout/composite-checkout/test/composite-checkout-thank-you.js

This PR sets the block editor URL as a post-checkout redirect URL. It doesn't however try to fix the stale cookie problem explained in pbOQVh-lb-p2.
* Enable Sandbox.
* Run `yarn dev --sync` on `apps/wpcom-block-editor`.
* Open block editor of the free site with the feature flag `?flags=post-editor/checkout-overlay`, e.g. `calypso.localhost:3000/block-editor/post/your_sandboxed_free_site.wordpress.com?flags=post-editor/checkout-overlay`
* Open up developer tools > console, and run the following code:
```js
let cartData = { products: [{
product_id: 1009,
product_slug: 'personal-bundle',
}] };
window.wp.hooks.doAction('a8c.wpcom-block-editor.openCheckoutModal', cartData);
```
* Finish the payment process
* You should be redirected back to the editor.
Fixed: #46362 and supersedes …

Set the redirect URL back to the editor when users finish the plan purchase

---

client/my-sites/checkout/composite-checkout/hooks/use-prepare-products-for-cart.ts

* The `usePrepareProductsForCart` hook has an implicit invariant: at most one of the child hooks which add products to the cart based on URL parameters will run. Currently each child hook needs to know enough about its siblings do decide when _not_ to proceed. This PR centralizes that logic in a single function, `chooseAddHandler`, so these hooks are less dependent on the others behaving well.
Test that the various means of adding cart items from the URL work. These are:
- Renewals, using URLs of the form `checkout/$product_slug/renew/$subscription_id/$site_url`
- Adding a plan, using URLs like `checkout/$site_url/premium` (or `personal` or `business`)
- Adding a product, using URLs like `checkout/$site_url/domain-mapping:example.com`

Checkout: centralize hook selection logic in usePrepareProductsForCart

---

client/components/jetpack/sidebar/menu-items/index.jsx
client/lib/plans/constants.js
client/lib/plans/index.js
client/lib/plans/plans-list.js
client/my-sites/sidebar/index.jsx

In this PR, we add Jetpack's Activity Log menu item to P2+ sites.
With a non-P2 site, you should see the Calypso sidebar unchanged. With a P2 site without P2+ plan, you shouldn't see the Jetpack section at all (unchanged). Now, upgrade to the P2+ plan on that P2 site. You should see Jetpack in the sidebar with Activity Log. When you open Activity Log, it should work (filtering, etc).

P2+: add Activity Log in menu

---

client/my-sites/plans-v2/constants.ts

* Make the Jetpack CRM CTA redirect users to `https://jetpackcrm.com/pricing/` (Reverts #46417).
* Run this PR.
* Visit the Plans page.
* Click on the Jetpack CRM CTA.
* Verify that you are redirected to `https://jetpackcrm.com/pricing/`.
Fixes 1196341175636977-as-1198302756679926

Plans: set Jetpack CRM CTA link to https://jetpackcrm.com/pricing/

---

apps/notifications/src/panel/indices-to-html/index.js

* Currently, notifications parser contains specific logic that restricts the first element to contain any nested elements. This prevents appropriate styling and ordering of elements to be applied, which results in the content of a notification to render differently than in a post.
1. See the"Creating post notification" section in the README at https://github.com/Automattic/wp-calypso/blob/master/apps/notifications/src/doc/note-rendering.md
2. Use the "Follow" button that appears in the bottom right corner of the blog to add it to your Reader subscriptions:
3. Then navigate to https://wordpress.com/following/manage and enable "Notify me of new posts" for the blog. With this enabled, future posts on that blog will appear as notifications in your masterbar.
4. Create a post for the blog …

Notifications: Remove Restriction that First Element Cannot Be Nested

---

apps/editing-toolkit/editing-toolkit-plugin/coming-soon/fallback-coming-soon-page.php

This PR adds localized login and default marketing page links to the buttons.
1. Sync this PR to your sandbox by running `yarn dev --sync` in `apps/editing-toolkit` (you might have run `composer install` beforehand
2. Add `define('WPCOM_PUBLIC_COMING_SOON', true)` to 0-sandbox.php
3. Create a new site  at wordpress.com/new?flags=coming-soon-v2
4. Sandbox your new site
5. Visit your new site in an incognito window
6. Click on the **Start your website** button. It should take you to https://wordpress.com/?ref=coming_soon
7. Check that the **Log in button** link takes you to the login page
8. Logging in with a different account should redirect you back to the site's coming soon page
9. Logging in with the same account with which you used to create the site, should redirect you back to a …

Coming Soon v2: adding links to default page

---

client/my-sites/pages/main.jsx

See https://github.com/Automattic/wp-calypso/pull/46507 for full details.
This has been approved but the PR wasn't working from my fork so I've included it here.

Add evergreen A/A test to /pages

---

client/components/gsuite/gsuite-new-user-list/new-user.tsx
client/components/gsuite/gsuite-new-user-list/style.scss
client/components/upgrades/gsuite/gsuite-upsell-card/style.scss
client/lib/gsuite/new-users.ts
client/my-sites/email/gsuite-add-users/style.scss

This pull request updates the Add G Suite page to allow users to specify passwords for their G Suite users. This new flow will only be available for now when the `gsuite/passwords` feature flag is enabled. You'll be able to find more context about that change in D50561-code.
1. Run `git checkout add/gsuite-passwords` and start your server, or open a [live branch](https://calypso.live/?branch=add/gsuite-passwords)
2. Apply D50561-code, and follow its testing instructions to set up your environment
3. Open the [`Email` page](http://calypso.localhost:3000/email?flags=gsuite/passwords) with the new flow enabled
4. Proceed to the Add G Suite page
5. Assert that the page is displayed correctly on small viewports
6. Assert that validation rules are correctly enforced for the new `Password` field …

G Suite: Update Add G Suite page to support passwords

---

client/lib/titan/get-titan-mail-order-id.js
client/my-sites/email/email-management/titan-control-panel-login-card/index.jsx

This PR updates the Titan control panel login component to use the actual order id for a domain.
- Hack the backend to return a Titan subscription for a domain
- Verify the same ID is used when generating the auto login link

Email: Update control panel login component to use actual order ID

---

client/my-sites/importer/uploading-pane.jsx
client/my-sites/importer/uploading-pane.scss

* Adds a hover state and cursor styles to the importers file uploader to indicate the file upload panel is click-able.
* This mimics the hover styles for the plugin and theme uploaders for slightly better consistency. Ideally, I think we should use the same component for both elements, but this is a quick stylistic fix.
**Before**
**After**
* Switch to this PR and navigate to `/import`
* Click on Blogger, Medium, or Squarespace
* Note the style changes on the file upload panel
Fixes #44319

Importers: Add hover and cursor styles to importer file upload

---

apps/editing-toolkit/editing-toolkit-plugin/full-site-editing-plugin.php
apps/editing-toolkit/editing-toolkit-plugin/readme.txt
apps/editing-toolkit/package.json
package.json

* Coming Soon v2: adding links to default page (https://github.com/Automattic/wp-calypso/pull/46441)
* Remove "gutenboarding/new-launch" feature flag and checks. (https://github.com/Automattic/wp-calypso/pull/46453)
* Fixes Global Styles plugin translation (https://github.com/Automattic/wp-calypso/pull/46421)

Editing Toolkit: Bump to version 2.7.1.

---

client/components/jetpack/sidebar/index.jsx

* don't assume adminUrl exists 
1. introduce a delay to the `me/sites` endpoint ( I added a `sleep(3);` in the appropriate place in my sandbox )
2. navigate to `/settings/:siteSlug` on production for an offline site. It may require a reload to get crash to appear
3. try from branch, verifying settings no longer crashes

Jetpack Cloud: Fix crash to white screen on settings page for off-line site

---

client/my-sites/checkout/composite-checkout/payment-method-processors.js
packages/composite-checkout/src/lib/payment-methods/apple-pay.js

This is a follow-up to #46337 which converts the Apple Pay payment processor to use the new system.
- Test an Apple Pay purchase. Verify that you get the apple pay dialog. Testing the actual purchase is less important.

Checkout: convert apple pay payment processor to use automated response

---

client/my-sites/checkout/composite-checkout/composite-checkout.js
client/my-sites/checkout/composite-checkout/payment-method-processors.js
client/my-sites/checkout/composite-checkout/payment-methods/ebanx-tef.js
client/my-sites/checkout/composite-checkout/payment-methods/id-wallet.js
client/my-sites/checkout/composite-checkout/payment-methods/netbanking.js
client/my-sites/checkout/composite-checkout/payment-methods/wechat.js
packages/composite-checkout/README.md
packages/composite-checkout/src/components/checkout-submit-button.tsx
packages/composite-checkout/src/lib/payment-methods/alipay.js
packages/composite-checkout/src/lib/payment-methods/bancontact.js
packages/composite-checkout/src/lib/payment-methods/eps.js
packages/composite-checkout/src/lib/payment-methods/giropay.js
packages/composite-checkout/src/lib/payment-methods/ideal.js
packages/composite-checkout/src/lib/payment-methods/p24.js
packages/composite-checkout/src/lib/payment-methods/sofort.js
packages/composite-checkout/src/lib/payment-processors.ts
packages/composite-checkout/src/public-api.ts
packages/composite-checkout/src/types.ts

This is a follow-up to https://github.com/Automattic/wp-calypso/pull/46337 which converts all the Stripe redirect payment processors to use the new system.
It also splits the WeChat payment processor into its own processor because on desktop it has quite a different behavior. That behavior remains mostly encoded into the WeChat button, but in order to use the `onClick` handler, we need to tell the processor function to do nothing with the response. (I also made a mistake in the original PR where I assumed that a NOOP response would be sufficient for a payment method to do its own success/failure handling, but it's not because we also need the transaction response, so this PR replaces NOOP with MANUAL.)
Since all these payment methods use the same payment processor function, they will all …

Checkout: Convert all stripe redirect payment processors to use automated responses

---

client/components/forms/form-password-input/index.jsx

* setting the React state directly in the `componentDidMount` is consider worthy of a console warning. This refactor moves the logic to the constructor and uses the `withMobileBreakpoint` component to correctly render there.
1. Navigate to a a screen with `FormPasswordInput`, such as `/devdocs/design/form-fields`, on a development branch
2. Confirm the following error does not appear in the console
3. Verify starting the page at a mobile width ( <=660px ) the password form starts visible, and at wide widths it starts hidden.

Fix FormPasswordInput bug

---

apps/editing-toolkit/editing-toolkit-plugin/full-site-editing-plugin.php

Coming soon v2 sites will only be created using the coming-soon-v2 flag from the frontend
In slack, we had discused using is_automattician rather than is_proxied_request.
I went with is_proxied_request because we also want to be able to test what a non-authenticated user, or a non-blog-owner user sees (only they see the coming soon page).
With the proxy active, and this code `yarn dev --sync`ed to your sandbox:
Create a test site (without enabling the coming-soon-v2 flag)
It should be created in the private, unlaunched state.
Note that `wpcom_coming_soon` is not set for new sites, this is existing behavior.
You can check the settings on the site like so: 
```
wp option --url=https://your-testing-site.wordpress.com/ get wpcom_coming_soon
wp option …
```

Enable coming soon v2 for all proxied automatticians.

---

apps/editing-toolkit/editing-toolkit-plugin/editor-gutenboarding-launch/index.php
apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nav-sidebar/class-wpcom-block-editor-nav-sidebar.php

So turns out we were missing something simple to get the low-hanging fruit of l10n going.
Plugins are supposed to call `wp_set_script_translations` when enqueueing internationised scripts:
https://developer.wordpress.org/apis/handbook/internationalization/#internationalizing-javascript
When you call `wp_set_script_translations` it will (by default) grab the translations from `translate.wordpress.org`, which has already translated the ETK: https://translate.wordpress.org/locale/es/default/wp-plugins/full-site-editing/
I then realised I hadn't included a to `wp_set_script_translations` when enqueueing the editor sidebar either, so I added that too.
If you look at other scripts that are enqueued by ETK they're already doing this. So it was just us that had forgotten :D
* Call …

Gutenboarding and nav sidebar use translations from translate.wordpres.org

---

apps/wpcom-block-editor/src/calypso/features/iframe-bridge-server.js
client/gutenberg/editor/calypsoify-iframe.tsx
config/development.json

This is part of a series of PRs looking at implementing the Persistent launch button in the editor (see pbAok1-1y7-p2 for details).
This PR adds a new `gutenboarding/persistent-launch-button` flag, which will be used in a later PR.
Related phab patch: D51268-code
* Adds `gutenboarding/persistent-launch-button` feature flag (only enabled in dev for now)
* Passes the value of the flag to gutenframe and makes it available to the Editing Toolkit plugin (this part will be added via a future PR)
In theory, **the changes introduced by the PR should only add unused code**, without causing any changes to the behavior of the "Complete setup" buttons. The following testing instructions are meant to **check for regressions**.
* On root folder, run `yarn start`.
* On `apps/wpcom-block-editor`, run …

Add "gutenboarding/persistent-launch-button" feature flag

---

client/blocks/editor-launch-modal/index.tsx
client/blocks/editor-launch-modal/style.scss
client/gutenberg/editor/calypsoify-iframe.tsx
client/package.json
config/development.json
packages/launch/README.md
packages/launch/package.json
packages/launch/src/index.tsx
packages/launch/src/launch/index.tsx
packages/launch/src/launch/style.scss
packages/launch/tsconfig-cjs.json
packages/launch/tsconfig.json

* Added boilerplate for launch packages.
* `packages/launch`
* `@automattic/launch`
* Added `EditorLaunchModal` which renders the boilerplate launch component on the parent calypso frame.
* Run `yarn` on root folder to install/rebuild packages (you will see an entry for `@automattic/launch` in the build log).
* Run `yarn start`.
* Open `calypso.localhost:3000/block-editor/post/YOUR_SITE_HERE.wordpress.com?flags=post-editor/launch-overlay`.
With the feature flag on the URL, the launch overlay will display.

Launch: Boilerplate for launch package.

---

client/my-sites/site-settings/delete-site/index.jsx

* Clears the input in the Site Deletion dialog whenever it's closed
Visit `/settings/delete-site/` and click the "Delete Site" button. Enter the site's address in the prompt that appears (see below) and click "Cancel". Click "Delete Site" again, and unlike before, the site's address shouldn't already be entered from when you initially typed it in. 
cc @ramonjd
Fixes #46512

Site Deletion: Clear Input Upon Closing Dialog

---

client/components/gsuite/gsuite-new-user-list/new-user.tsx
client/lib/gsuite/new-users.ts

This pull request is a follow-up of https://github.com/Automattic/wp-calypso/pull/46204 which enables the `Password` input field on the `Add G Suite` page.
1. Run `git checkout enable/gsuite-passwords` and start your server, or open a [live branch](https://calypso.live/?branch=enable/gsuite-passwords)
2. Open the [`Email` page](http://calypso.localhost:3000/email)
3. Proceed to the `Add G Suite` page
4. Assert that a `Password` field is displayed for every G Suite user
5. Purchase G Suite
6. Assert that you are able to log into the accounts of the G Suite users

G Suite: Enable password fields for G Suite users

---

client/jetpack-connect/style.scss
client/login/wp-login/style.scss

* Updates styles for JP Connect and JP Login, gets rid of dark color scheme.
* This PR touches on files that are used in the Woo onboarding flows, though we expect no differences. cc @josemarques @LevinMedia 
- Ensure that all views on all possible flows show the light color scheme.
- Ensure that all views are consistent and display no visual errors.
* Starting in an incognito browser, go to wp-admin.
* Click “Set up Jetpack”.
* Replace `wordpress.com` by `calypso.localhost:3000` on the URL.
* Fill out details to create a new account.
* Head to the Plans page.
* Starting in an incognito browser, go to http://calypso.localhost:3000/jetpack/connect.
* Enter your site URL and hit Continue.
* Enter your WP username and password, and hit Install Jetpack.
* Enter your username and hit Continue. …

Jetpack: Update styles for JP Connect and JP Login

---

client/root.js

Reverts Automattic/wp-calypso#46561 because it broke `wp-desktop` e2e tests and my attempt at fix in #46567 doesn't work.

Revert "Root redirect: ensure that the primary site info is fetched before making decisions"

---

apps/notifications/src/panel/indices-to-html/index.js

* This PR updates handling of links opening in a new window to include `rel="noopener noreferrer"` as well. (https://web.dev/external-anchors-use-rel-noopener/)
* Ensure you have the API sandboxed.
* Open a Calypso web notification containing a link that opens in a new window.
* Verify that in the HTML for the notification, the link has the attribute `rel="noopener noreferrer"` applied to it.

Notifications: Ensure all links opening with target=_blank have a rel attribute as well

---

client/me/purchases/manage-purchase/index.jsx

Fixes a user-reported issue.
* On the purchase details page, for sites with old Jetpack plans that need to see the "We launched new plans" notice, use `siteSlug` instead of `site.slug` to build the `View plans` link.
**Implementation note:** It appears that the `site` object wasn't available, since the site was no longer in the user's sites list.
**Prerequisite:**  Purchase a legacy Jetpack plan (i.e., Personal, Premium, or Professional) for a non-WordPress.com site, then completely remove that site from your WordPress.com account. It should no longer be associated with any site owner.
* From the account that originally purchased the upgrade, go to your account profile and then to **Manage Purchases**.
* Click on the upgrade for the disconnected site to see its details.
* Before applying …

Purchases: Fix purchase details page crash for deleted/disconnected sites w/ old Jetpack plans

---

client/me/purchases/controller.jsx
client/me/purchases/manage-purchase/index.jsx
client/my-sites/purchases/main.tsx

This updates where the page view tracking is called for the Subscription Setting page, now that site-level billing management is available.
**To test:**
- debug the analytics component with `localStorage.setItem('debug', 'calypso:analytics:*');`
- on a site with purchases
- visit the site-level settings page for a subscription: _Plans > Billing > Click on a purchase_
- verify that the page tracking for the page has the `/purchases/subscriptions/:site/:purchaseId` path
- visit the account-level settings page for a subscription: _Me > Manage Purchases > Click on a purchase_
- verify that the page tracking for the page has the `/me/purchases/:site/:purchaseId` path

Billing: fix "Manage Purchase" page tracking

---

client/my-sites/site-settings/podcasting-details/index.jsx

Apple has deprecated and dropped support for the `itunes:keyword` tag. In #46467, I quickly added a notice to the podcasting keywords field before we recorded a podcasting tutorial video. In D51182-code I removed the output from the podcasting feed, and per @nbloomf's request, this makes the field read-only.
ref: p1602699974038200-slack-podcasting-async-workshop-content
**To test:**
- on a site with podcasting enabled (ping me if you need a site/user)
- visit the podcast settings page, _Settings > Writing > Podcasting > Manage Details_
- verify that the keywords field is read-only

Podcasting: make deprecated keywords field read-only

---

client/my-sites/plans/navigation.jsx
client/my-sites/sidebar/index.jsx
test/e2e/lib/components/sidebar-component.js
test/e2e/specs/wp-plan-purchase-spec.js

As part of upcoming navigation and IA changes to the Plan/Purchases section, this PR makes the `/plans/:site` route the default for the "plans" item (previously, it was "My Plan" for sites with a purchase). It additionally cleans up some of the render logic and makes use of the `SidebarItem` component, instead of a custom list item and link.
ref: p1HpG7-asg-p2
**Before:**
**After:**
**To test:**
- first off, apologies for the plan-splosion in these instructions
- visit a Jetpack or WPcom site with a purchase
- navigate to _Plan_ section in the sidebar
- verify that the _Plans_ link in the _Plan_ section is visually unchanged
- click the _Plans_ link
- verify that you are taken to the _Plans_ screen and that _My Plan_ is the secondary item in the tabbed navigation

Billing: make `/plans/` default route for the plans item

---

client/me/billing-history/main.jsx
client/me/billing-history/receipt.jsx
client/me/billing-history/upcoming-charges.jsx
client/me/memberships/main.jsx
client/me/memberships/subscription.jsx
client/me/payment-methods/README.md
client/me/payment-methods/controller.js
client/me/payment-methods/main.tsx
client/me/pending-payments/index.jsx
client/me/purchases/add-credit-card/index.jsx
client/me/purchases/controller.jsx
client/me/purchases/index.js
client/me/purchases/paths.js
client/me/purchases/purchases-list/header/index.jsx
client/me/purchases/purchases-list/index.jsx

In #46300, we moved the payment methods from the site-level billing history to its own tab. This PR does the same for the account-level view. It additionally makes all of the account-level purchase screens full-width, to both accommodate the number of items in the nav and match the site-level views. If we need to, we can break the width changes into their own PR @fditrapani.
Fixes: #46324 
**To test:**
- visit `/me/purchases`
- verify that the different screens in this section are all full-width
- verify that "payment methods" exist as a section nav item
- visit "billing history"
- verify that the payment methods are no longer shown below the billing history table
- visit "payment methods"
- verify that your payment methods are shown
- click "add credit card"
- verify that you're taken to …

Billing: Add account-level payment methods tab

---

apps/notifications/src/panel/indices-to-html/index.js
apps/notifications/src/panel/templates/functions.jsx
apps/notifications/style.scss

* Currently, Button blocks created in a post, and subsequently rendered in a notification in the master bar renders as a stacked links. To enhance the user experience, this change makes it so that the button block is rendered to look like a button, aligning with the styles from the original post.
* `a` tags are now rendered as the appropriate tags, and `div` tags can now have nested elements.
Note that this branches from https://github.com/Automattic/wp-calypso/pull/46471 and depends on D51180-code
1. Apply this diff D51180-code and ensure you are sandboxed
2. See the"Creating post notification" section in the README at https://github.com/Automattic/wp-calypso/blob/master/apps/notifications/src/doc/note-rendering.md
3. Use the "Follow" button that appears in the bottom right corner of the …

Notifications: Support Button Styling

---

client/blocks/reader-featured-image/index.jsx
client/lib/post-normalizer/rule-pick-canonical-image.js
client/lib/post-normalizer/rule-pick-canonical-media.js
client/lib/post-normalizer/rule-safe-image-properties.js

A user reported seeing a blank image with the background-image src `null` in their Reader. You'll need to set your interface language to Japanese to see it:
https://wordpress.com/read/search?q=%E3%81%AA%E3%81%9C%E5%A4%A7%E6%9D%91%E6%84%9B%E7%9F%A5%E7%9C%8C%E7%9F%A5%E4%BA%8B%E3%82%92%E3%83%AA%E3%82%B3%E3%83%BC%E3%83%AB%E3%81%99%E3%82%8B%E5%BF%85%E8%A6%81%E3%81%8C%E3%81%82%E3%82%8B%E3%81%AE%E3%81%8B
The image has a query string containing non-resizing parameters (notably `authuser`) so we're not able to resize it with Photon. The image should never have made it to the ReaderFeaturedImage block.
This PR adds a `safeImageUrl` check when selecting the canonical media for a post.
Similar to https://github.com/Automattic/wp-calypso/pull/46144.
Visit …

Reader: check images can be resized with Photon before selecting them as canonical media

---

packages/domain-picker/src/domain-name-explanation/index.tsx

Small PR that wraps the text in `<DomainNameExplanationImage>` in a `__()`.
More work needs to be done to support RTL languages because the image is oriented to assume LTR. But we're prioritising LTR at the moment (see pbxlJb-ry-p2).
* Wrap `'example.com'`, like `__( 'example.com' )`
* Go to `/new/domains` or `/new/domains/ro`
* Ensure the search field is empty
* The `https://example.com` example should appear like it used to, but now it'll be queued for translation.
Like this:

Internationalise the text in <DomainNameExplanationImage>

---

apps/editing-toolkit/editing-toolkit-plugin/full-site-editing-plugin.php
apps/editing-toolkit/editing-toolkit-plugin/readme.txt
apps/editing-toolkit/package.json
package.json

This just releases one change which will allow us to activate coming soon v2 for a12s (#46434)
https://github.com/Automattic/wp-calypso/commits/master/apps/editing-toolkit

bump editing toolkit version to 2.7.2

---

client/desktop/window-handlers/notifications/index.js
desktop/package.json

This is part of the release process for the desktop app.

desktop: Merge version 6.2.0

---

apps/editing-toolkit/editing-toolkit-plugin/editor-site-launch/index.php

Just like #46552, we were missing something simple to get the low-hanging fruit of l10n going for the launch modal.
Plugins are supposed to call `wp_set_script_translations` when enqueueing internationised scripts:
https://developer.wordpress.org/apis/handbook/internationalization/#internationalizing-javascript
When you call `wp_set_script_translations` it will (by default) grab the translations from `translate.wordpress.org`, which has already translated the ETK: https://translate.wordpress.org/locale/es/default/wp-plugins/full-site-editing/
If you look at other scripts that are enqueued by ETK they're already doing this. So it was just us that had forgotten :D
* Call `wp_set_script_translations` after enqueueing the launch JS
* Checkout branch, yarn dev --sync, and sandbox an unlaunched …

Localise the launch sidebar and final launch step

---

client/components/forms/form-text-input/style.scss

The `direction` property introduced in https://github.com/Automattic/wp-calypso/pull/45358 for search type inputs is causing Search component alignment problems with RTL languages.
* Remove `input[type='search']`selector from rule-set that forces direction for certain input types in FormTextInput's styles. 
**Before:**
**After:**
* Change your UI to RTL language (e.g. Hebrew)
* Test different sections and confirm search input inherits the direction from the page, e.g. `/read`, `/pages`, `/media/`, `/devdocs`, etc.
* Test domain search component at `/domains/add` and confirm it's using the `dir` attribute to render in LTR all languages.
Fixes 164-gh-i18n-issues

Components: Fix search input direction

---

apps/notifications/src/panel/indices-to-html/index.js

* Currently, Button blocks and YouTube embeds created in a post, and subsequently rendered in a notification in the master bar renders as a unclickable. This change makes it so that they redirect to the appropriate content.
* `a` tags are now rendered with the appropriate `href`.
1. Use the Calypso live link, or checkout this branch
2. See the"Creating post notification" section in the README at https://github.com/Automattic/wp-calypso/blob/master/apps/notifications/src/doc/note-rendering.md
3. Use the "Follow" button that appears in the bottom right corner of the blog to add it to your Reader subscriptions:
4. Then navigate to https://wordpress.com/following/manage and enable "Notify me of new posts" for the blog. With this enabled, future posts on that blog will appear as notifications …

Notifications: Buttons and YouTube Preview Image Clickable

---

client/lib/plans/plans-list.js
client/me/purchases/purchase-item/index.jsx

This PR adds a missing space in the Jetpack product descriptions.
**Before**
**After**
* Since we don't offer these Jetpack plans any longer, you'll need to go into Store Admin and add any of the old Jetpack plans to a Jetpack site and check the subscriptions settings screen to confirm a space has been added in the description.
Fixes https://github.com/Automattic/wp-calypso/issues/46240

Purchases: fix jetpack descriptions

---

desktop/e2e/mocha.opts
desktop/e2e/run.js

Try to fix mocha "No such session error", which has only recently appeared and been occurring relatively frequently, recently.
- Despite all tests passing, an e2e error is reported when mocha fails with a "no such session" message
- Attempting to address this by ensuring mocha exits with the `--exit` flag:
> By default, Mocha will no longer force the process to exit once all tests complete. This means any test code (or code under test) which would normally prevent node from exiting will do so when run in Mocha. Supply the --exit flag to revert to pre-v4.0.0 behavior
- Ran the Mac job 10 times and did not encounter this failure. (There was 1 failure, but this was due to an intermittent failure with the logout test, which is unrelated).
Hopefully this works! 🤞

desktop e2e: "no such session" error

---

client/my-sites/domains/paths.js
client/my-sites/email/email-management/index.jsx

This PR fixes the back button under the email management page, to send the user to the page they were visiting before, when applicable.
There are 4 scenarios you need to test:
- Clicking the "Setup your email"/"Manage your email" button from the domain enhanced navigation
- Same as above, but from the all domains context (i.e. `/email/all/<DOMAIN>/manage/<SITE>`)
- Clicking the "Add" email button from site domains list
- Clicking the "Add" email button from all domains list
In all those cases, then clicking the back button should send you back to where you were before, after applying the changes.

Email: Fix back button on email management page

---

client/components/rewind-credentials-form/index.jsx
client/jetpack-cloud/sections/settings/main.jsx
client/my-sites/site-settings/jetpack-credentials/index.jsx

* Fixes a regression with #46501 where the API was returning an empty object and Javascript treats that as true.
1. Create a Jetpack site and purchase Backup.
2. In Calypso, view the Settings -> Jetpack page and verify form shows the site as needing credentials.
3. Fill out credentials and save.
4. Verify credentials now appear and backend reports them present.
5. Delete credentials from system and do 2-4 in Jetpack Cloud.
6. Reset or create new site and verify with Jetpack Scan.

Checks credentials for empty object

---

apps/notifications/src/panel/indices-to-html/index.js

* This PR, along with D51415-code, updates web notifications to properly render formatting available in the "Classic block".
* (Note that some of the bugs described in the issue have been addressed by previous recent notifications fixes; this PR/diff combo only actively fixes strikethrough formatting and a bug that was preventing style attributes on paragraphs from being applied. But all bugs mentioned in the issue are included here for testing purposes.)
* Apply D51415-code in your sandbox and make sure the API is sandboxed.
* Apply this change to calypso, navigate to your Calypso dashboard and open a notification for a post with a classic block as part of its content. Make sure the classic block includes the following:
* Some bulleted text with a nested bullet.
* Indented text
* …

Notifications - adding support for classic block formatting

---

client/components/domains/domain-search-results/index.jsx

The TLD_NOT_SUPPORTED case needs a better message - in D50792-code we are precising it as "TLD that we don't support registrations for, but you can probably map it if you purchased the domain somewhere else".
Easiest to test with D50792-code.
Before:
After (whether the mapping is free or not depends if the site has paid plan):

Domains: Improve the TLD not supported message

---

client/lib/cart-values/cart-items.js
client/my-sites/checkout/composite-checkout/hooks/has-renewal.ts
client/my-sites/checkout/composite-checkout/lib/translate-cart.ts

* Update `isLineItemARenewal` to work before `extra` is moved behind `wpcom_meta`
* Replace "Subscription" with "Renewal" if item is a renewal
* Add "Renewal" after product name if item is a renewal
* Renew a plan and verify it says "Plan Renewal" under the plan name (see screenshot)
* Renew a domain name and verify it says "Renewal" after "Domain Registration"
Fixes #44877

Checkout: Add renewal text to renewal items

---

client/components/activity-card/activity-actor.tsx
client/components/activity-card/activity-description.tsx
client/components/activity-card/style.scss
client/components/jetpack-logo/index.jsx
client/components/jetpack/backup-card/index.tsx
client/components/jetpack/backup-card/style.scss
client/components/jetpack/daily-backup-status/index-alternate.tsx
client/lib/jetpack/backup-utils.js
client/my-sites/backup/enable-restores-banner.tsx
client/my-sites/backup/main.jsx
client/my-sites/backup/style.scss
client/state/activity-log/types.ts

This PR adds a new backup card and updates the successful backup screen in Calypso and Jetpack cloud, according to the new iteration of this screen. See mockups labelled `i4` (link is in the board).
Note that it doesn't modify the activity log in Jetpack cloud, which is what you see when you click the search icon in the _Backup_ section in cloud.
Fixes 1197351014149633-as-1197888024354846
- Extracted `Activity` types in own file
- Extracted enable restores banner in its own file
- Fixed some TS import errors by prepending paths with `calypso`
- Made `ActivityActor` support multiple avatar sizes and added the possibility to hide the actor info
- Refactored the structure of the Backup page for the new iteration
- Created an alternate component for `DailyBackupStatus` (named …

Integrate new backup cards in Backup section

---

client/landing/gutenboarding/components/header/index.tsx
client/landing/gutenboarding/components/header/style.scss

WIP: see CSS issue
https://d.pr/i/XC3MIo
* In Gutenboarding head Make (W) logo clickable and send user to wordpress.com ("home")
* Go to /new
* Click on (W) in header:
- in logged-in state check user is routed to thier primary site: e.g.  `/home/myprimarysite.wordpress.com`
- in logged-out state, user is simply routed back to `/`
Fixes https://github.com/Automattic/wp-calypso/issues/41065

Gutenboarding Header: make (W) icon link back to root path  /  

---

client/me/privacy/main.jsx
client/me/privacy/style.scss

This PR adds a page title and makes the screen full width to match the updates we're making on the Payments Methods screens.
**Before**
**After**
* Visit the Privacy screens in `/me` and confirm the title and width match the screenshots.

Privacy: Add title

---

client/me/notification-settings/comment-settings/index.jsx
client/me/notification-settings/main.jsx
client/me/notification-settings/reader-subscriptions/index.jsx
client/me/notification-settings/wpcom-settings/index.jsx

This PR adds a page title and increases the layout width to match our updates to the Payments Management screens. 
**Before**
**After**
* Visit the Notification Settings screen in `/me` and checkout all the child pages to confirm the title and layout width match the screenshot.

Notifications: Add title and increase width

---

client/me/connected-applications/index.jsx
client/me/security-account-recovery/index.jsx
client/me/security-account-recovery/style.scss
client/me/security-checkup/index.jsx
client/me/security/main.jsx
client/me/social-login/index.jsx
client/me/two-step/index.jsx

This PR updates Adds the page title to all the Security related screens and makes them full width to match the upcoming changes to the Manage Purchases screen.
**Before**
**After**
* Visit the Security screen in `/me` and navigate through all the child screens to confirm the title is there and the screens are all full width.

Security: Add page title

---

client/me/account/main.jsx

This PR adds a title to the Account setting screens and increases the screen width to match the changes in the Managed Purchases section.
**Before**
**After**
* Visit the Account Settings screen in `/me`

Account settings: Add title

---

client/me/profile/index.jsx

This PR adds a title to the My Profile screen and makes it full width to match the upcoming changes in the Managed Purchases screen.
**Before**
**After**
* Visit the My Profile screen in `/me`.

Profile: Add title to profile screen

---

client/me/billing-history/main.jsx
client/me/billing-history/receipt.jsx
client/me/billing-history/upcoming-charges.jsx
client/me/memberships/main.jsx
client/me/memberships/subscription.jsx
client/me/payment-methods/main.tsx
client/me/purchases/add-credit-card/index.jsx
client/me/purchases/cancel-purchase/index.jsx
client/me/purchases/confirm-cancel-domain/index.jsx
client/me/purchases/manage-purchase/index.jsx
client/me/purchases/payment/add-card-details/index.jsx
client/me/purchases/payment/edit-card-details/index.jsx
client/me/purchases/purchases-list/index.jsx
client/me/purchases/titles.js

This PR adds the Manage Purchases page title to all the manage purchases screens. The title has been centralized as a string in a central location so that when we update it, it can be updated in one place. 
**Before**
**After**
* Visit the Managed Purchases section in `/me` and confirm the title appears on all the tabs and sub pages.
* Visit the site level billing section and confirm there are no unintended artifacts.

Purchases: add title to add manage purchases screen

---

client/me/purchases/cancel-purchase/loading-placeholder.jsx
client/me/purchases/controller.jsx

This PR fixes some width issues in the Purchase management sections.
**Before**
**After**
- Visit the account view for Manage Payments.
- View a subscription with an existing credit card associated with it.
- Click on "Change credit card".
- Confirm that the pre-loader and edit credit card forms are the same width as the previous screen.
- Return back to subscription screen and ensure you have a payment method attached to the subscription.
- Click Cancel subscription and confirm the cancel subscription screen is the same width as the previous screen.

Purchases: Fix screen width

---

client/my-sites/sidebar-unified/index.jsx
client/my-sites/sidebar-unified/item.jsx
client/my-sites/sidebar-unified/menu.jsx
client/my-sites/sidebar-unified/sparkline.js

Initial pass at optimising some of the rendering of the component tree for the unified nav. Specifically this focuses on the `MySitesSidebarUnifiedItem` component and friends.
This is part of breaking up this PR https://github.com/Automattic/wp-calypso/pull/46448.
Address part of https://github.com/Automattic/wp-calypso/issues/46091
* Optimize `MySitesSidebarUnifiedItem` to avoid unnecessary renders - important as it will render many items in the tree.
* Optimize Stats Sparkline so only re-renders where necessary. Move out of `MySitesSidebarUnifiedItem` to stop hook change (ie: `useSelector( getSelectedSiteId );`) causing that component to re-render.
* Allow expanded state of items to be determined by Redux state.
* `yarn && yarn start`. Wait for Calypso to boot.
* Goto …

Nav Unification performance - optimize unified item nav components

---

client/me/purchases/cancel-purchase/index.jsx
client/me/purchases/controller.jsx
client/me/purchases/manage-purchase/index.jsx
client/me/purchases/payment/add-card-details/index.jsx
client/me/purchases/payment/edit-card-details/index.jsx
client/my-sites/purchases/main.tsx

https://github.com/Automattic/wp-calypso/pull/46602 introduced a bug on our site-level billing screens where we now see a duplicated title. This PR cleans that up. 
**Before**
**After**
Needs to be tested locally
* Visit the subscription screen at the site and account level and confirm you only see a single title for the following screens:
* Subscription settings
* Change payment method
* Add payment method (from subscription screen)
* Cancel purchase

Purchases: fix duplicated manage purchases title

---

apps/editing-toolkit/editing-toolkit-plugin/block-inserter-modifications/contextual-tips/tip-link.js

* Remove the `/block-editor` string from the contextual tips.
A visual check should be enough, but in case you want to test completely
* Apply this patch
* Test with the editor sandboxed and Not Simple site
* Open the block inserter
* Type a string that raises up a tip, for instance, `CSS` (1)
* Confirm the return value in the URL (2) shouldn't contain the `/block-editor` string.
Fixes #

Contextual Tips: remove `/block-editor` from URL

---

apps/notifications/src/panel/indices-to-html/index.js

* This PR, along with D51523-code, fixes formatting for code blocks when displayed in Calypso notifications.
* Apply D51415-code in your sandbox and make sure the API is sandboxed.
* Apply this change to calypso, navigate to your Calypso dashboard and open a notification for a post with a code block as part of its content. 
* Verify that the code block is styled as a block rather than inline, and maintains whitespace formatting.
Before:
After:
Fixes #45126

Notifications - fix formatting for code blocks

---

client/jetpack-cloud/sections/pricing/header/index.tsx
client/lib/abtest/active-tests.js
client/lib/plans/plans-list.js
client/lib/products-values/translations.js
client/my-sites/plans-v2/abtest.ts
client/my-sites/plans-v2/constants.ts
client/my-sites/plans-v2/controller.tsx
client/my-sites/plans-v2/use-get-plans-grid-products.ts
client/my-sites/plans-v2/utils.ts
config/desktop-development.json
config/desktop.json
config/development.json
config/horizon.json
config/jetpack-cloud-development.json
config/jetpack-cloud-horizon.json
config/jetpack-cloud-production.json
config/jetpack-cloud-stage.json
config/production.json
config/stage.json
config/test.json
config/wpcalypso.json
packages/components/src/product-icon/config.js

* Replace the `plans/alternate-selector` feature flag with an AB test experiment. We need this because we might have to maintain multiple variants of the page at the same time.
* I introduced three variants: `v0 - Offer Reset`, `v1 - 3 cols layout`, and `v2 - slide outs`. The first one corresponds to the plain new Offer Reset Plans page. The second one is the current version of the page. The latter corresponds to next iteration with slide outs cards.
* Removed from the `ProductIcon` component all traces of the feature flag and moved the logic that decides which icon to use back to Calypso. I did this mainly because I believe this package might be used externally where feature flags don't exist.
* I tried to give variants a name that explain what is behind each one of them (for internal …

Jetpack CRO: add AB test to switch between different variant of the Plans page

---

client/layout/utils.ts

The change in #42164 appears to have resulted in a larger-than-expected drop in the number of mobile app banner impressions. It seems that while the original intent of that change was to delay banner display until a user was able to complete onboarding. That change however blocked the loading of the banner anywhere that not site is selected for all users.
* Show the App install banner when no site is selected. This could occur when you are in the Reader, Settings, etc.
* Create a site using /new
* The app banner shouldn't appear.
* Go to reader
* Banner should appear

Display app banner when no site is selected

---

client/layout/utils.ts

The change in #42164 appears to have resulted in a larger-than-expected drop in the number of mobile app banner impressions. It seems that while the original intent of that change was to delay the banner display to 1 hour, the final implementation resulted in a delay of 1 week. This PR implements the 1-hour delay and makes a couple of other logical changes.
* Change the delay for showing the App install banner from one week to one hour
* Create a site using /new
* The app banner shouldn't appear.
* Wait for one hour
* Banner should appear

Change app banner delay from a week to an hour

---

docs/routing.md

In https://github.com/Automattic/wp-calypso/pull/38190 the `server` directory was moved into the `client` directory. This tiny PR updates a link to a document to point to the correct place (it currently 404s because it was still pointing to the old location).
* Update the link to bundler/README.md
* Just make sure that I've linked to the correct location, please!
Fixes #

Docs: Update path for link to the bundler documentation in routing.md

---

.eslintrc.js
apps/editing-toolkit/editing-toolkit-plugin/editor-site-launch/src/launch-steps/name-step/index.tsx
client/landing/gutenboarding/onboarding-block/acquire-intent/acquire-intent-text-input/index.tsx
packages/domain-picker/src/domain-picker/index.tsx

* Stop HotJar capturing input fields in gutenboarding
* Remove exception for HotJar from our list of allowed terms as [they now use `data-hj-allow`](https://help.hotjar.com/hc/en-us/articles/115015563287-How-to-Whitelist-Elements-and-Keystrokes)
Discussion: pbAok1-1CF-p2
* Run through the gutenboarding flow and see that the "site name" and "domain" fields still work as usual
* To test that the name and domain fields in the launch modal no longer have the `data-hj-whitelist` attribute you will need to apply D51533-code and test a sandboxed, unlaunched site, that was created with gutenboarding.
HotJar isn't currently recording so unfortunately you can't look at any sessions to verify that the fields are now obfuscated.

Gutenboarding: stop HotJar capturing input fields in gutenboarding

---

client/landing/gutenboarding/components/locale-context/index.tsx

This PR updated eliminates the flash of English text by updating the `LocaleContext` to render `null` until after `setLocale()` is called for the first time.
I've also moved the `loadInitalLocale()` call up into the `setState()` in order to have it trigger a fraction of a second earlier, as `useEffect()` waits for the first render to finish before it even starts fetching the translations. `setState()` provides the consuming function, so it's a natural limit within `LocaleContext`. (We have options to load it sooner than this, but we should do it in a separate performance-focused PR if we decide we need to).
- load up a localized site (e.g. http://calypso.localhost:3000/new/ko) and watch for the flicker.
- load up the en site http://calypso.localhost:3000/new and make sure that it still …

Gutenboarding: Load translations before render

---

client/components/social-buttons/google.js

* Add instructions to the disabled "Continue with Google" button on how to enable third-party cookies by directing them to the support page.
* Removed the "onMouseOut" call back to hide the error so users can hover over the pop over and click the link.
* In Incognito mode go to [http://calypso.localhost:3000/log-in](http://calypso.localhost:3000/log-in).
* Hover over the disabled "Continue with Google" button and a popover should appear with a "learn more here" link in.
* Clicking the link should take you to [https://wordpress.com/support/third-party-cookies/](https://wordpress.com/support/third-party-cookies/).
* Clicking elsewhere on the `/log-in` page should make the popover disappear.
Fixes https://github.com/Automattic/wp-calypso/issues/39758

Add instructions to Google login popover to enable third-party cookies

---

client/blocks/signup-form/index.jsx
client/lib/abtest/active-tests.js

* The remove username field test was initiated in https://github.com/Automattic/wp-calypso/pull/45609, and then re-launched for the plan-specific flows in https://github.com/Automattic/wp-calypso/pull/46038.
* We are wrapping up the test and retaining control experience for all users. Check pbxNRc-rq-p2 for context.
**Depends on D51547-code**
* Apply D51547-code.
* Visit signup at /start/personal and verify that you are not assigned to the test. For this, `localStorage.ABTests` in your browser console should not return `removeUsernameInSignup`. Also verify this in the other plan-specific flows - /start/premium, /start/business, /start/ecommerce.
* Verify that signup works correctly.

Wrap up the remove username A/B test

---

client/lib/abtest/active-tests.js
client/lib/signup/step-actions/index.js
client/lib/signup/test/step-actions.js
client/signup/config/steps-pure.js
client/signup/config/steps.js
client/signup/steps/domains/index.jsx
client/signup/utils.js

* Switches flow to the secure-your-brand onboarding flow if a custom domain is selected.
* Assigns to the A/B test only if a custom domain is selected
* Fixes the issue described in [this comment](https://github.com/Automattic/wp-calypso/pull/46078#pullrequestreview-511510074) that caused the domain bundle upsell to not show in the following sequence: 
select a free *.wordpress.com subdomain -> go back from the plans step -> select a custom domain -> No upsell offer
* Restricts A/B test to EN-US
* Follow the testing instructions in https://github.com/Automattic/wp-calypso/pull/46078

Fix: Domain bundle upsell not shown bug

---

client/my-sites/current-site/notice.jsx

This is a minor PR to reduce the size of other PRs which are working on [the `SiteNotice` component](https://github.com/Automattic/wp-calypso/blob/691522b1bbbe64eb0d9bd28937f73a3a18d3a1c5/client/my-sites/current-site/notice.jsx).
* Replaces deprecated `url` usage with recommended lib alternative.
* Checkout PR.
* `yarn && yarn start` - waiting and open calypso in browser.
* Set up a fresh test site at `https://wordpress.com/start`. Use a free plan and choose a free `wordpress.com` domain name.
* [Set up a new redirect for your new site](https://wordpress.com/support/site-redirect/) - https://wordpress.com/domains/add/site-redirect/
* Verify redirect works.
* In your **_local_** Calypso (http://calypso.localhost:3000/) go to the Calypso my home for your new site.
* You should see a Notice …

Remove deprecated use of Node URL in Site Notices

---

client/blocks/reader-post-card/compact.jsx
client/blocks/reader-post-card/gallery.jsx
client/blocks/reader-post-card/index.jsx
client/blocks/reader-post-card/photo.jsx
client/blocks/reader-post-card/standard.jsx
client/blocks/reader-post-card/style.scss

* Change to `h2` elements for card titles. Only one `h1` should be on the page at a time.
* Push the byline lower so a11y software associates it with the correct card
* See #46648 
Fixes #46648 
relevant slack convo p1603290552059600-slack-C029GN3KD

Some a11y improvements to Reader cards

---

client/lib/abtest/active-tests.js
client/my-sites/checkout/upsell-nudge/index.jsx

* As the variant wins, we're going to roll out to the one-click upsell to 100% users. See  pcbrnV-aX-p2 for more details on the preceding test.
* Purchase Personal or Premium dotcom plan for your website.
* You may need to remember the receipt ID.
* Visit `/checkout/offer-quickstart-session/RECEIPT_ID/YOUR_SITE_SLUG`. Please replace RECEIPT_ID and YOUR_SITE_SLUG with your owns. It would look like `/checkout/offer-quickstart-session/1234567/testblog.woordpress.com`.
* Ensure you have one or more stored credit cards.
* Click the "Yes, I want a WordPress Expert by my side!" button.
* You should be able to see a modal dialog as below:
* Click on the Pay button and the transaction of purchasing Concierge Session is going to be _automatically_ processed.
* When everything goes okay, a sucess …

Marketing: roll out one-click upsell to 100% users.

---

client/me/purchases/credit-cards/credit-card-delete.tsx

This PR adds an event for when someone removes a payment method.
* Visit the account-level or site-level billing section.
* Delete a payment method and confirm the `calypso_purchases_delete_payment_method` event fires. 
Fixes https://github.com/Automattic/wp-calypso/issues/46605

Purchases: Add delete payment method event

---

client/me/purchases/manage-purchase/purchase-meta.jsx

During a support rotation, I saw people getting confused with the payment method still showing when auto-renew has been disabled. In this PR, I hide the payment method when auto-renew is disabled.
**Before**
**After**
* Visit a subscription that has a payment method attached. 
* Turn off auto-renew and confirm that there is no payment method.
* Visit a subscription that was purchased with credits to make sure it says "Credits" under payment method.
* Add a payment method and confirm the payment method displays
* Disable auto-renew once again to confirm that the payment method isn't showing anymore.

Payments: update payment methods display when auto-renew is disabled

---

client/components/activity-card/activity-actor.tsx
client/components/jetpack/daily-backup-status/action-buttons.jsx
client/components/jetpack/daily-backup-status/status-card/backup-successful.jsx
client/components/jetpack/daily-backup-status/status-card/no-backups-yet.jsx
client/components/jetpack/daily-backup-status/status-card/style.scss
client/components/jetpack/daily-backup-status/test/action-buttons.jsx
client/my-sites/backup/main.jsx
config/development.json
config/horizon.json
config/jetpack-cloud-development.json
config/jetpack-cloud-horizon.json
config/jetpack-cloud-production.json
config/jetpack-cloud-stage.json
config/production.json
config/stage.json

The flag was implemented for development/deployment purpose. This PR removes it since it's not necessary anymore, and make the code less readable.
- Run the PR
- Create a new self-hosted Jetpack site that has Backup Daily, and server credentials **not** set up
- Check that the _Backup_ section looks and behaves like production
- Wait for or force a backup, then check again
- Check again with server credentials set up
- Repeat these steps with Backup Real-time

Remove `jetpack/backup-simplified-screens` feature flag

---

client/components/jetpack/backup-card/style.scss

The tooltip that describes the _Restore to this point_ button in the new backup card is made visible when hovering the whole card instead of the button. This PR fixes this.
A CSS rule was unfortunately removed.
- Select a self-hosted Jetpack site that has Backup, and no server credentials set up
- Visit `/backup/:site?flags=jetpack/backup-simplified-screens-i4`
- Hover a backup card and check that you don't see any tooltip
- Hover the restore button and notice the tooltip
_Before_
_After_

Backup card: fix restore button tooltip target area

---

client/me/purchases/confirm-cancel-domain/index.jsx
client/me/purchases/confirm-cancel-domain/loading-placeholder.jsx
client/me/purchases/controller.jsx

This PR fixes a duplicate title for folks deleting domains purchased with a payment method.
**Before**
**After**
* If you don't have a domain purchased with a payment method, go ahead and buy one.
* Visit `me/purchases` and go try delete a domain. 
* Continue past the first step and confirm the screen is full width and there isn't a duplicate title. 
* Try the same steps from the site level by visiting `/purchases/subscriptions/:site`

Fix duplicate headers and layout widths

---

client/components/jetpack/daily-backup-status/action-buttons.jsx
client/components/jetpack/daily-backup-status/style.scss

This PR center aligns the "Restore to this point" button on mobile screens.
**BEFORE: (Restore button is left aligned)**
1. Run this PR (Calypso Blue and Calypso Green builds)
2. Go to jetpack.cloud.localhost:3001/backup/:site
3. Trigger mobile view in developer tools and verify that the "Restore to this point" button text is center aligned.
4. Repeat the same check in Calypso blue.

Jetpack Backup: Center align restore button on mobile.

---

client/my-sites/purchases/billing-history/index.tsx
client/my-sites/purchases/main.tsx
client/my-sites/purchases/payment-methods/index.tsx
client/my-sites/purchases/site-level-purchases-error-boundary.tsx

* Add an error boundary around purchase management routes so we can surface errors here in our usual reporting channels. Touches routes under `/purchases`, `/purchases/billing-history`, and `/purchases/payment-methods`.
* Throw an error right before the render function of some component under `Purchases`. For example, [SubscriptionsContent](https://github.com/Automattic/wp-calypso/blob/d43a26ff471af93cae27882580aca2eb2584d084/client/my-sites/purchases/subscriptions/subscriptions-content.tsx#L24).
* Use `localStorage.setItem('debug', 'calypso:site-level-purchases-error-boundary:*')` in your console to see these errors.
* Load the component where the error is thrown and verify that you see it in the console.
Fixes #46432

Billing Management: Add error boundary to site-level purchase routes

---

client/lib/purchases/index.js
client/lib/purchases/types.ts
client/me/memberships/subscription.jsx
client/me/purchases/membership-item/index.tsx
client/me/purchases/membership-item/style.scss
client/me/purchases/membership-site/header.tsx
client/me/purchases/membership-site/index.tsx
client/me/purchases/membership-site/style.scss
client/me/purchases/purchases-list/index.jsx
client/me/purchases/purchases-list/style.scss
client/state/memberships/subscriptions/selectors.js

This adds membership subscriptions to the purchase list under `/me/purchases`.
Fixes #46604
**To do:**
**To test:**
- On a site with membership subscriptions (ping me if you need one):
- Visit _Me > Manage Purchase_
- Verify that membership subscriptions are shown on the same screen (at the bottom) as your own site's purchases
- Click on a membership subscription
- Verify that the subscription details page is unchanged
- Click "back"
- Verify that you're taken back to `/me/purchases` (I'm not making this conditional, since we'll be removing Other Sites as part of the next PR)

Billing: add membership subscriptions to purchase data

---

client/my-sites/plans-v2/plans-filter-bar/index.tsx

* This PR updates the advertised discount percentage from 17% to 20%.
* Ensure the discount percent text has been updated in the Yearly/Monthly filterbar in both Calypso Green & Calypso Blue.

Jetpack: Update plan/product discount percentage from 17% to 20%

---

desktop/e2e/tests/lib/driver-helper.js
test/e2e/lib/components/secure-payment-component.js
test/e2e/lib/driver-helper.js

Some e2e tests are failing (with the cryptic error `TimeoutError: Timed out waiting for element with undefined of 'undefined' to be clickable`) which is thrown by `clickWhenClickable` [if the selector does not exist](https://github.com/Automattic/wp-calypso/blob/08a46585106b1a4981b166217372b68b99358d88/desktop/e2e/tests/lib/driver-helper.js#L39). This is because the checkout cardholder name field is slightly too high on the page and cannot be selected. The test code in `enterTestCreditCardDetails` already accounts for this on mobile by scrolling, but on desktop it did not. This PR changes that behavior so it is always scrolled into view.
If you're set up for running e2e tests, then do:
`env BROWSERSIZE=desktop ./node_modules/.bin/mocha --grep "Sign up for a domain only purchase coming in …

e2e tests: Always scrollIntoView in enterTestCreditCardDetails

---

client/my-sites/earn/memberships/index.jsx

* This PR adds extra text to a user's list of active subscribers, indicating which subscription plan the subscription applies to. This makes it easier to distinguish between subscribers of different plans with the same price.
* Sandbox the store and connect your account to Stripe via the steps described in PCYsg-lW4-p2, "Sandbox method"
* Navigate to `/earn/payments-plans/{siteId}` and add two new monthly payment plans with the same price but different descriptions.
* Create a post with two Premium Content blocks, each associated with one of the new payment plans.
* From another account, visit the post and subscribe to both payment plans.
* Use one of the test credit card numbers from the above FG page.
* On your original account, navigate to `/earn/payments/{siteId}`. You should see both …

Earn: show title of subscriber plans

---

client/me/memberships/controller.js
client/me/purchases/index.js
client/me/purchases/paths.js
client/me/purchases/purchases-list/header/index.jsx
client/me/sidebar/index.jsx

* Remove the Upcoming Charges tab from the account level billing management pages and delete any newly unused code.
* Navigate to `/me/purchases` and verify that there is no "Other Sites" tab in the nav bar.
* Manually load `/me/purchases/upcoming` and verify that you are redirected to `/me/purchases`.

Billing management: deprecate the "Other Sites" tab

---

client/blocks/time-mismatch-warning/README.md
client/blocks/time-mismatch-warning/index.tsx
client/blocks/time-mismatch-warning/test/index.jsx
client/my-sites/activity/activity-log-v2/index.tsx
client/my-sites/activity/activity-log/index.jsx
client/my-sites/backup/main.jsx
client/my-sites/scan/main.tsx

Implements `TimeMismatchNotice` block to Activity Log, Scan, and Backup pages in both Calypso and Jetpack sites.
This notice appears when a person's browser clock is different from the timezone set for the site. It notifies people about the discrepancy so they are aware when a time appears "in the future".
Note the link in the screenshot goes to the site settings page to set the timezone.
* Connect to a Jetpack site and set the timezone to one not your own.
* Visit the Activity Log, Scan, and Backup pages (purchasing plans if needed) to verify notice appears.
* Verify link is correct.
Fixes 1164141197617539-as-1185886809463829.

Adds notice for users who are visiting from a different timezone

---

client/my-sites/purchase-product/search.jsx

* Fixes #46702, a bug where the user gets stuck unable to submit a site URL.
* Navigate to `/purchase-product/jetpack_search/monthly` while having the browser's network console open.
* While the `https://public-api.wordpress.com/rest/v1.2/me/sites` request is still in transit, enter a site URL into the input and submit the form.
* Ensure that you are redirected to the checkout page (`/checkout/<siteSlug>/jetpack_search_monthly`).

Jetpack Search: Remove race condition from purchase process

---

client/me/concierge/shared/primary-header.js
client/me/help/help-contact/index.jsx

Adds closure notices for Christmas and New Year's Day to the contact form and Quick Start signup form.
Open both http://calypso.localhost:3000/me/concierge and http://calypso.localhost:3000/help/contact. Adjust your system clock to the following dates and refresh both pages to ensure the results match up:
- **2020-12-16 23:00 UTC** — No notices appear
- **2020-12-17 0:00 UTC** — "____ will be closed for Christmas"
- **2020-12-24 0:00 UTC** — "____ closed for Christmas"
- **2020-12-26 7:00 UTC** — "____ will be closed for New Year's Eve"
- **2020-12-31 0:00 UTC** — "____ closed for New Year's Eve"
- **2021-01-02 7:00 UTC** — No notices appear

Support: Holiday closure notices for Chat and Quick Start

---

client/layout/body-section-css-class.js
client/layout/index.jsx
client/layout/logged-out.jsx
client/login/index.web.js
client/my-sites/checkout/controller.jsx
client/my-sites/controller.js
client/sections-middleware.js

Fixes https://github.com/Automattic/wp-calypso/issues/46684 (issue brought up by @sirbrillig in https://github.com/Automattic/wp-calypso/pull/46086#issuecomment-714634933)
Whenever some route handler sets a custom section name/group with `dispatch( setSection() )`, make sure that the new section value is also set in the `RouteContext`. This PR does that by using `setSectionMiddleware` for setting the section.
The suggestion by @tyxla in https://github.com/Automattic/wp-calypso/pull/46086#discussion_r510069167 became urgent much faster than I expected! 🙂 
It turns out that the work in #46086 wasn't really finished, so this PR contains some additional fixes like converting `LoggedOutLayout` to the route context, too.
Also fixes the `BodySectionCssClass` component to remove the `bodyClass` …

Make sure that current section is always set in router context when changing it

---

client/me/memberships/subscription.jsx
client/me/memberships/subscription.scss

This PR updates the detail view of individual membership subscription details to look more like the detail pages for other purchases. In #46683, we're combining the two into a single screen.
This includes the changes from #46683 (they'll be rebased out after it merges). The changes specific to this PR are all in 8611ab1.
Fixes #46723
**Before:**
**After:**
**To test:**
- On a site with membership subscriptions (ping me if you need one):
- Visit _Me > Manage Purchases_
- Click on membership subscription
- Verify that the details page matches the screenshot above (depending on the type of subscription)

Billing: update membership subscription detail design

---

client/components/jetpack/card/jetpack-product-card-alt-2/assets/ribbon.svg
client/components/jetpack/card/jetpack-product-card-alt-2/features-item.tsx
client/components/jetpack/card/jetpack-product-card-alt-2/features.tsx
client/components/jetpack/card/jetpack-product-card-alt-2/index.tsx
client/components/jetpack/card/jetpack-product-card-alt-2/style.scss
client/components/jetpack/card/jetpack-product-card-alt-2/types.ts
client/my-sites/plans-v2/product-card-alt-2/index.tsx
client/my-sites/plans-v2/products-grid-alt/index.tsx

This PR implements the new product card for the last iteration of the pricing page. See board for details and mockups.
Fixes 1196341175636977-as-1198514641268269
- I created a new chain of components (card + features section) altogether, similarly to the other versions.
- Text in the ribbon is dynamic to support internationalization and copy updates.
- The features section will be tackled in a separate PR.
- Download the PR locally
- Run Calypso and cloud concurrently
- Visit the plans page in both Calypso and cloud, and compare it to the mockups (or screenshots below)
_Mockups_
_Implementation_
_Mockups_
_Implementation_

Create product card for i2 version of pricing page

---

packages/composite-checkout/src/lib/payment-methods/apple-pay.js

When checkout loads the Apple Pay payment method, it's possible (although I'm still not sure how, exactly) for there to be no currency in the shopping cart's line items; this may be because the shopping cart's item list is empty (unlikely since checkout does not load the payment methods until the shopping cart is loaded), or because the items have no `currency` set (unlikely since the currency is required and validated by the composite-checkout package). It _might_ happen if the cart key changes after checkout has already loaded (the issues we are seeing started with #46532 so it's likely that something happened there).
In any case, the code already allows for an empty currency, but it sends that empty currency to Stripe's `stripe.paymentRequest()` function, causing that function to throw …

Checkout: Do not create Apple Pay stripe.paymentRequest if there is no currency set

---

client/blocks/comment-button/style.scss
client/blocks/like-button/style.scss
client/blocks/reader-post-actions/index.jsx
client/blocks/reader-post-actions/style.scss

As reported in #44852, users couldn't use the keyboard to focus on the comments and like buttons shown at the bottom of a post card.
Both the component that renders the comments button and the one that renders the like button receive the tag name as a prop. It seems that the most cost-effective alternative is to specify a `button` tag instead of a `div` to render the buttons and to adjust the styles when focused, so they match the other card buttons. However, in the long term, it would be a good idea to consider refactoring these two components to use the `Button` component from `@automattic/components`, as the options and share buttons do.
* Changed the tag used to render the comments and like buttons. Now a `button` element is used instead of a `div`.
* Took advantage of …

Reader: Allow using the post card comment and like buttons with the keyboard

---

client/my-sites/plans-v2/utils.ts

This is a bug that only affects users visiting the Checkout page that came from the Jetpack's Plans page.
* Fix the behavior of the Checkout's cancel button to redirect users back to where they came from. The problem is that we were redirecting users to `/checkout/:site/` instead of to `/checkout/:site` (notice the `/` at the end of the path). That `/` at the end of the path made the app do a double redirect to the Checkout page, which overrode the stored previous path.
* Run this PR (horizon is fine).
* Visit the Plans page with a Jetpack site.
* Select any plan or product.
* Once in the Checkout page, click on the cancel button located at the upper-left corner of the screen.
* Make sure you are redirected back to the Plans page.
* Repeat the process in production to make sure you …

Fix broken Checkout's cancel button when coming from Jetpack's Plans page

---

client/reader/following/main.jsx
client/reader/following/style.scss
client/reader/following/vote-banner.jsx

Following on from the recent banner for the NZ election (https://github.com/Automattic/wp-calypso/pull/46377), this PR adds a vote banner at the top of Reader's Following stream for the US election on 3rd Nov, 2020.
It also refactors the vote banner into its own component.
As a user in the US, ensure that the vote banner appears at the top of your Following feed: http://calypso.localhost:3000/read.
As a user outside the US, ensure you do not see the banner at all.

Reader: add vote banner for US election 2020

---

client/state/selectors/get-customize-or-edit-front-page-url.js

Don't use front page editor for Atomic sites yet
- Create an atomic site with `brompton` theme
- Visit `/themes/tooloom.jp`
Before:
- Errors in console.
After:
- No errors in console, and page is shown
Reference: p9F6qB-63w-p2

Atomic: Don't use front page editor for Atomic sites yet

---

client/landing/gutenboarding/onboarding-block/style-preview/preview.tsx
config/stage.json
config/wpcalypso.json

Prior to this PR, if you set your logged-in user locale to a non `en` language, the style preview in Gutenboarding would not use the locale for generating the url for the design preview as it depended on the path param value. This PR swaps out the `useLangRouteParam()` for `i18nLocale` from `useI18n` in `@automattic/react-i18n` to get the current locale.
* Change the Gutenboarding style preview step to use `i18nLocale` to grab the current locale for use in generating the preview url
* Remove the `'gutenboarding/style-preview-verticals'` config flag and conditional block in constructing the template/demo url since we are unlikely to implement verticals here any time soon and the endpoint doesn't currently support it.
* Change your user's locale to a non-EN locale
* Go to …

Update Gutenboarding style preview to use i18nLocale instead of path language param

---

client/jetpack-cloud/sections/settings/advanced-credentials/credentials-form/index.tsx
client/jetpack-cloud/sections/settings/advanced-credentials/form.ts

Default to FTP as this is the most common on the new credentials form
* Head to cloud.jetpack.com
* Use the flag ` ?flags=+jetpack/server-credentials-advanced-flow`
* Test the new credentials flow and ensure FTP is the default

Default to FTP for new Jetpack credentials form

---

client/gutenberg/editor/controller.js

While testing some changes to the state we made after deprecating the
Calypso editor, we noticed that Atomic sites would not redirect properly
in the editor iframe when accessed on a version of Calypso not on
wordpress.com or calypso.localhost.
This occurred because these are the domains that are allowed by
`wp_safe_redirect` and for Atomic sites we were always redirecting to
`wp-login.php` with a return address of the iframe in Calypso. This
could be on hosts like calypso.live, or horizon.wordpress.com. In those
cases the `wp_safe_redirect check would fail, and we would be sent to
the `wp-admin` dashboard.
Jetpack sites did not exhibit the same behaviour, and it was because we
were treating those like simple sites, assuming we were authenticated or
could authenticate via SSO.
There are a …

Editor Controller: Update authentication check logic

---

apps/editing-toolkit/editing-toolkit-plugin/editor-site-launch/src/attach-launch-sidebar.tsx
apps/wpcom-block-editor/src/calypso/features/iframe-bridge-server.js
client/gutenberg/editor/calypsoify-iframe.tsx

* Hide inline help button when launch modal opens using WP actions.
* `toggleInlineHelp` renamed to `toggleInlineHelpButton` to prevent confusion with existing function `toggleInlineHelp` in `client/blocks/inline-help`.
* `yarn start` on root calypso.
* `yarn dev --sync` on `apps/editing-toolkit`.
* `yarn dev --sync` on `apps/wpcom-block-editor`.
* sandbox `widgets.wp.com`.
* create and sandbox an unlaunched site.
* test on the block editor via the local calypso url with the `gutenboarding/new-launch-mobile` feature flag, e.g. `http://calypso.localhost:3000/post/YOUR_UNLAUNCHED_SITE.wordpress.com/home?flags=gutenboarding/new-launch-mobile`
* opening launch modal, the inline help button should be hidden.
* close the launch modal, the inline help button should be visible.
Fixes …

Launch: Hide inline help button when launch modal opens.

---

client/state/experiments/reducer.ts
client/state/experiments/schema.js

* Adds a schema so experiment state will be persisted.
- Go to a page with a running experiment
- Verify you have assignments by looking in `state.experiments` on your console
- Refresh the page
- `nextRefresh` should not update.

Explat: Add schema so state is saved in cache

---

config/jetpack-cloud-development.json
config/jetpack-cloud-horizon.json
config/jetpack-cloud-production.json
config/jetpack-cloud-stage.json

* Toggle `jetpack/server-credentials-advanced-flow` in all jetpack cloud configs
1. navigate to `/settings/:siteSlug`
2. verify new host-specific site flow is visible

Launch Jetpack Cloud Host-Specific Credentials Project

---

client/layout/sidebar/style.scss

* Fix vertical alignment of the sidebar's comment count. Fixes #45097
**Before**
**After**
* Navigate to a site that has unmoderated comments
* Check out the comment count bubble in the sidebar
* Make sure other instances of the count are not negatively affected (I think the only other instance is in the Reader but I'll do another sweep to double check)

Sidebar: Nudge the comment count down 1px for better alignment

---

config/development.json
config/horizon.json
config/production.json
config/stage.json
config/test.json
config/wpcalypso.json

* This sets the `gutenboarding/new-launch-mobile` feature flag to true on all WP environments.
* Launch flow should be testable without flags on calypso.live and other places as we deploy.

Launch: Enable launch flow mobile.

---

apps/editing-toolkit/editing-toolkit-plugin/editor-gutenboarding-launch/index.ts
apps/editing-toolkit/editing-toolkit-plugin/full-site-editing-plugin.php
apps/editing-toolkit/editing-toolkit-plugin/readme.txt
apps/editing-toolkit/package.json
apps/wpcom-block-editor/src/calypso/features/iframe-bridge-server.js
client/gutenberg/editor/calypsoify-iframe.tsx
config/wpcalypso.json

- Adds persistent launch button (as spec'd in pbAok1-1y7-p2 and p9Jlb4-1SN-p2)
- All un-launched sites should now see this button — when clicked, users will be taken to one of two possible launch flows:
- "Complete setup" if the site was created through Gutenboarding (this flow opens a modal on top of the editor)
- "Control launch flow" otherwise (this flow redirects the user to a new page)
Related phab patches:
- FSE plugin: D51379-code
- WBE widget: D51381-code
1. Apply FSE and WBE phab patches to the sandbox (see above for phab patches links)
2. **First flow: a site created via the _control_ flow should display the launch button behind a flag**
* Create a new site via `/start`
* Add the newly created site to the sandbox
* Edit homepage in the calypso block editor — persistent launch …

Launch: Add persistent launch flow button in the block editor

---

apps/editing-toolkit/editing-toolkit-plugin/common/index.php

In https://github.com/WordPress/gutenberg/pull/25738, Gutenberg moved the lineHeight setting to a new place in the settings object. It also introduced a (sort of?) bug where even though it has a mechanism to use the deprecated location for the setting, it is never used because the default value is returned instead.
This simply updates our existing filter to enable line height in the new location if the new location exists. I left the old setting in place as well, just in case we still need to support older gutenberg versions. 
1. Sandbox a site on wordpress.com
2. Sync these changes with `yarn dev --sync`
3. Open the post editor.
4. Select a paragraph block
5. Verify that line height is an option in the settings.

Support new line height setting

---

client/blocks/jitm/index.jsx
client/my-sites/theme/main.jsx

Fixes a little bug where the sidebar shows a placeholder while the `blocks/jitm` component is async-loading:
Notice the horizontal bar that looks like a scrollbar that appears for a moment.
This PR removes that by setting `placeholder={ null }`. There's one more similar instance in Themes.

Don't show placeholder when loading JITM UI

---

client/my-sites/checkout/composite-checkout/hooks/use-get-thank-you-url/get-thank-you-page-url.ts
client/my-sites/checkout/composite-checkout/hooks/use-get-thank-you-url/index.ts
client/my-sites/checkout/composite-checkout/test/composite-checkout-thank-you.js

* As mentioned in https://github.com/Automattic/wp-calypso/pull/44590#discussion_r487009202, the business plan bump offer will not be seen by Premium plan customers if they paid with redirect payments like PayPal or Giropay. This PR fixes the issue.
* Purchase a premium plan during signup and purchase the plan with PayPal. Verify that after payment is successful, you are shown the business plan bump offer.

Business plan bump: Show offer for PayPal and other redirect payments

---

client/components/domains/domain-registration-suggestion/index.jsx
client/components/domains/domain-search-results/index.jsx
client/components/domains/featured-domain-suggestions/index.jsx

* With the roll out of the domain step test variant to all users in https://github.com/Automattic/wp-calypso/pull/45618, the CTA on a domain changed to "Upgrade" in the domain only flow and site launch flow, as described in [this comment](https://github.com/Automattic/wp-calypso/pull/45618#pullrequestreview-515253379). This PR fixes the issue.
You should now the CTA as "Select" in the following cases:
* the domain search results in the domain only flow
* The initial suggestions in the launch site flow.
* the domain search results in the launch site flow
* Go through the domain only flow at /start/domain and confirm that the CTA on each domain in the domain search results is "Select", check [screenshot](https://d.pr/i/IsqXMG). Verify the same for add-domain flow too.
* Go to the launch …

Fix: Domain step CTA should be "Select" instead of "Upgrade"

---

client/server/api/index.js
client/server/api/integration/index.js
client/server/api/oauth.js
client/server/api/sign-in-with-apple.js
test/integration/jest.config.js

The `test-integration` CI job we run nightly on `master` has been failing recently, like here: https://app.circleci.com/pipelines/github/Automattic/wp-calypso/78586/workflows/ac645fbe-5f0a-4891-8901-54919252facd/jobs/935506
It's caused by the ambiguous `import 'config'` and `import 'calypso/config'` statements. Some modules that are imported by the integration tests were using the old import, some the new one. But the `integration/jest.config.js` was defining only an alias for the old `config` import. That leads to importing the client version of the `config` module rather than the server one.
This patch solves that by defining the `calypso/config` alias in Jest config, and making all the imports in involved modules consistent.
Run `yarn run test-integration` and verify …

Fix integration tests by using calypso/config import path and updating the alias

---

client/jetpack-connect/controller.js
client/jetpack-connect/jetpack-connection.jsx
client/jetpack-connect/utils.js

* The goal is to carry over query parameters throughout the whole flow til the checkout step. This is necessary if we want to include discount coupons on our marketing emails are not linked to a specific site (no site URL is present in links).
* 90% of the changes are related to making `eslint` checks pass.
* Run this PR (horizon works fine).
* Visit `http://calypso.localhost:3000/jetpack/connect/jetpack_security_daily?coupon=<COUPON_CODE>` (see ticket to get a valid coupon code).
* Enter a valid site URL.
* Verify that you are redirected to `http://calypso.localhost:3000/checkout/:site/jetpack_security_daily?coupon=<COUPON_CODE>` and that the coupon code was applied to your cart.
Fixes 1164141197617539-as-1198936119067523

Jetpack Connect: carry over query parameters to the checkout page

---

client/signup/config/flows-pure.js

* A follow up to Automattic/wp-calypso#44786, enabling recaptcha for the wpcc and crowdsignal flows.
Check `wpcc` flow:
* Go to gravatar.com and click "Create your own gravatar" button.
* In the signup page, replace wordpress.com in the address bar with `http://calypso.localhost:3000/` or the hash URL if you are using calypso.live. 
* Verify that you can see the recaptcha logo in the bottom right screen, and that you can complete signup.
Check `crowdsignal` flow:
* Go to crowdisgnal.com and click on "Get started". 
* In the signup page, replace wordpress.com in the address bar with `http://calypso.localhost:3000/` or the hash URL if you are using calypso.live. 
* Verify that you see the recaptcha logo in the bottom right screen.
* Verify that you can complete signup.
Fixes # …

Add showRecaptcha for wpcc and crowdsignal flows

---

client/components/jetpack/card/jetpack-product-card-alt-2/index.tsx
client/components/jetpack/card/jetpack-product-card-alt-2/style.scss

This PR aligns the InfoPopover to the right of the product Price (**allowing the Price to be center aligned**) in the Jetpack Search Card.
I don't think the Jetpack Scan Price ($4.14) is correct. I think it should be a flat **$4** and will be handled in a different PR.  So therefore, disregard the price amount in testing this PR as well as any other copy differences, etc.  We are only testing to make sure the **price is now centered and the info pop-over is aligned to the right of the price**.
1. Checkout this PR
2. Start Calypso visit the Plans page
3.  In the jetpackConversionRateOptimization A/B test, select `v2 - slide outs` 
4. Scroll down to the Jetpack Search product card and verify that:
1. The product price is centered.
2. The info pop-over is aligned to the right of the price …

CRO i.2: Jetpack search card - align Info Popover

---

client/my-sites/plans-v2/plans-filter-bar/index.tsx
client/my-sites/plans-v2/plans-filter-bar/style.scss

Fixes discount message overlapping term filter in some languages:
1. First do a regression test by going to wordpress.com (not localhost) and set your Calypso interface language to French.
- Go to [https://wordpress.com/me/account](https://wordpress.com/me/account), and change the **Interface Language** to `Français du Canada` (_Français du Canada_ is a good testing example) and be sure to click "Save Account Settings" button.
- Next go to https://wordpress.com/plans/:site and verify you can see the discount message overlapping problem (Like in the screenshot above)
2. Next run this PR (both Calypso blue and Cloud green)
4. Go to calypso.localhost:3000/plans/:site (Calypso interface should still be set to _Français du Canada_) and verify that the discount message overlapping problem is no …

Jetpack Plans: Fix discount message overlapping term filter in some languages 

---

client/my-sites/checkout/composite-checkout/components/wp-order-review-line-items.js

* Update wording for free domain in cart checkout to mitigate confusion.
*BEFORE*
[![Screenshot](https://d.pr/i/a5CwD6+)](https://d.pr/i/a5CwD6)
*AFTER*
[![Screenshot](https://d.pr/i/fEf3iX+)](https://d.pr/i/fEf3iX)
Fixes #46769

Update free domain checkout wording

---

client/components/jetpack/threat-item-subheader/index.tsx
client/state/data-layer/wpcom/sites/scan/index.js

* Remove `Number.isFinite` check since dates come as strings and `Number.isFinite` always returns false on string inputs. This is making the `firstDetected` field undefined regardless of what comes from the API.
* This won't fix wrong dates in the History section immediately since there is still a bug on the backend side that is preventing us from showing the right ones.
* Run this PR (Calypso Blue works fine).
* Select a Jetpack site that has active threats.
* Visit the Jetpack > Scan section.
* Open the Components (React) panel in Developer Tools, search for a `ThreatItem` component, and make sure that threats have a valid `firstDetected` date property (see capture below).
Fixes 1164141197617539-as-1198954012346061

Jetpack Scan: fix API's response transform function

---

apps/editing-toolkit/editing-toolkit-plugin/full-site-editing-plugin.php
apps/editing-toolkit/editing-toolkit-plugin/readme.txt
apps/editing-toolkit/package.json

* Make sure that the line-height UI option appears (see: https://github.com/Automattic/wp-calypso/pull/46873)

Update EDT to version 2.8.2

---

apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nav-sidebar/src/attach-sidebar.tsx
apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nav-sidebar/src/test/attach-sidebar.test.ts
apps/wpcom-block-editor/src/calypso/features/iframe-bridge-server.js
test/e2e/specs/wp-gutenberg-experimental-features-spec.js

Context: pc9Uba-96-p2
* Don't attach block editor nav sidebar if `__experimentalMainDashboardButton` is unavailable
* If `__experimentalMainDashboardButton` is unavailable then `wpcom-block-editor` will revert to the legacy way of overriding the (W) button to take the user back to Calypso.
* Add a unit test that fails if `__experimentalMainDashboardButton` is unavailable
If the nav sidebar isn't attached then the (W) button in the top-left will do what it used to do: clicking it will return the user to Calypso.
From pc9Uba-96-p2, the unit test is so that it forces us to have a conversation about what to do if this export disappears in a GB update.
* Clone branch
* Sandbox a test site and `widgets.wp.com`
* Build Editing Toolkit plugin and sync to sandbox PCYsg-ly5-p2
* Build …

Editor close button should deal with situation where experimental GB feature is unavailable

---

client/my-sites/sidebar-unified/style.scss

* Themes notices according to figma designs https://www.figma.com/file/9cy0DIowQkPAu0rodb9jsL/WP-Admin-for-Dotcom?node-id=325%3A2792&viewport=2516%2C-103%2C5.115475654602051
* Allow text-content to wrap if it is too long
Before | After
-------|------
Text wrapping
Before | After
-------|------
- add `?flags=nav-unification` 
- Go to a site with domain warning or edit `client/my-sites/domains/components/domain-warnings/index.jsx` to force show some 
Fixes #46732

Fix notices styles in unified sidebar

---

client/components/step-progress/style.scss
client/jetpack-cloud/sections/settings/advanced-credentials/credentials-form/index.tsx
client/jetpack-cloud/sections/settings/advanced-credentials/credentials-form/style.scss
client/jetpack-cloud/sections/settings/advanced-credentials/style.scss

**Improve stepper component number size**
Before:
After:
**Fix button alignment in older versions of Chrome**
Before:
After:
**Fix text on OK state**
Before:
After:
* Pull this branch
* Use the `http://jetpack.cloud.localhost:3000/` entry point
* Check for CSS regressions

CSS fixes for Jetpack credentials form

---

client/my-sites/sidebar-unified/style.scss

The arrow was missing from active menu items that were not menus
Before | After
-------|------
* add `?flags=nav-unification`
* test that menu items that don't have a submenu show the arrow on the right
* test that menu items with submenus continue showing the arrow on the right
* repeat the above for collapsed state
Relates to #45435

Fix menu-item active state

---

apps/notifications/src/panel/indices-to-html/index.js

Adds support for `figure` elements so blocks using them (like the Media & Text block) are rendered correctly in the notifications.
It also fixes an issue in the logic that decides which range should be the next to enter so empty ranges (like the ones used by images) have higher priority in order to render them in the correct DOM level.
Frontend | Notification (before) | Notification (after)
--- | --- | ---
* Apply D51931-code and sandbox the API.
* Add `define( 'BLOCK_FALLBACKS_DEBUG', true );` to your `/wp-content/mu-plugins/0-sandbox.php` file.
* Publish a post that contains Media & Text blocks.
* Check the post in the masterbar notifications.
* Make sure the Media & Text blocks are rendered correctly.
* Make sure there are no regressions in other notifications.

Notifications: Render figure elements

---

client/lib/abtest/active-tests.js

This change will pause the Secure Your Brand test for the duration of the Monthly price 
1. Set country_code cookie to US
2. Sign up with a new user and make sure the user is assigned to `control` with secureYourBrand

Pause Secure Your Brand

---

client/my-sites/sidebar-unified/style.scss

- set `min-height` of notice so that it has the same height as the rest of the menu items when collapsed
Before | After
-------|------

Fix notice height when sidebar is collapsed

---

client/layout/masterbar/style.scss

This PR fixes the Secure checkout title on small screens.
**Before**
**After**
* Add a product to your cart and go to checkout
* Confirm that the secure checkout title doesn't look busted on screens smaller than 400px wide.
* Then check on a wide screen to make sure it still looks good.

Checkout: fix secure checkout title for small screens

---

client/gutenberg/editor/calypsoify-iframe.tsx

* Redirect to frontend after publishing a post, if the site is a P2 site.
- Publish a post to a P2 site. It should redirect you to the post on the front.
- Save a post draft for a P2 site. Nothing new should happen.
- Publish a post to not a P2 site. Nothing new should happen.

P2: redirect to frontend after publishing post

---

client/layout/index.jsx
client/my-sites/current-site/notice.jsx

Followup to #46770 -- there's still one unwanted placeholder 🙂

Don't show placeholder when loading JITM UI part 2

---

client/my-sites/backup/main.jsx

* Updates backup page to link to last successful backup.
1. Open Backups screen on a site with a failed backup yesterday and a scheduled one today.
2. Verify date shown is the last date before the failed backup.
3. Click link and verify it takes you to the correct backup date.
Note: creating this state is possible with altering Activity Log API response via proxy rewrite or similar.
Fixes 1164141197617539-as-1189970976408145

Backup: Updates logic to show last successful backup instead of any last

---

client/blocks/time-mismatch-warning/README.md
client/blocks/time-mismatch-warning/index.tsx
client/blocks/time-mismatch-warning/test/__snapshots__/index.jsx.snap
client/blocks/time-mismatch-warning/test/index.jsx
client/my-sites/activity/activity-log/index.jsx
client/my-sites/backup/main.jsx
client/my-sites/scan/main.tsx
client/state/selectors/get-settings-url.ts

* Creates a new selector, `getSettingsUrl`, which returns either a Calypso or wp-admin path based on environment.
* Wires up selector to `TimeMismatchWarning` component to send users to correct path in all envs.
Note: right now the selector only handles the general settings, as there's no map between wp-admin and Calypso settings paths that I could leverage.
1. Set up a JP site with a timezone not in yours.
2. Check activity log, backup, and scan pages in Calypso environment.
3. Verify notice appears and link takes you to the Calypso settings page.
4. Check again, this time with Jetpack environment.
5. Verify notice appears and link takes you to the wp-admin settings page.

Use admin URL for time mismatch warning in Jetpack env

---

packages/data-stores/src/site/actions.ts
packages/data-stores/src/site/reducer.ts
packages/data-stores/src/site/resolvers.ts
packages/data-stores/src/site/selectors.ts

* Adds a clean isomorphic (Calypso & wp-admin friendly) way to get and set the site title. 
```js
wp.data.select('automattic/site').getSiteTitle()
wp.data.dispatch('automattic/site').setSiteTitle( 'new title' );
```
1. Sandbox testingfocusedflow.wordpress.com.
2. in `apps/editing-toolkit`, run `yarn dev --sync`.
3. Go to https://testingfocusedflow.wordpress.com/wp-admin/post-new.php.
4. In Chrome DevTools console, type 
```js
// get the title
wp.data.select('automattic/site').getSiteTitle(window._currentSiteId);
// set the title
wp.data.dispatch('automattic/site').setSiteTitle(window._currentSiteId, 'new title');
// get it again, refresh the page, and do this again, should get the same title
wp.data.select('automattic/site').getSiteTitle(window._currentSiteId);
```
Fixes #46872

Data stores: add site title getter and setter

---

client/components/jetpack/card/jetpack-product-card-alt-2/index.tsx
client/lib/plans/plans-list.js
client/lib/plans/types.ts
client/lib/products-values/translations.js
client/my-sites/plans-v2/plans-filter-bar/index.tsx
client/my-sites/plans-v2/utils.ts

This PR  updates the copy in the last pricing page according to the mockups.
Fixes 1196341175636977-as-1198514641268292
- Versions checks are not scalable. We'll need to find a proper way of handling versioning.
- The Jetpack CRM card will be handled in a separate PR.
- Run Calypso
- Visit the plans page
- Check the copy against the mockups (see board)
- Make sure there's no error in the copy
- Switch back to the v1 variant and check that the page looks like production

Update copy of pricing page i2

---

client/root.js
client/server/config/parser.js

This patch addresses a bug reported by several Desktop users where the error message `"You need to set `oauth_client_id` in your config file"` is displayed on the login page. (At least - it's been very hard to repro and I hope it fixes the root cause! 🤞).  
</p>
At runtime, various config files are parsed (see [here](https://github.com/Automattic/wp-calypso/blob/f025fdec6e95e9a61625f47164adcc08231600c9/client/server/config/parser.js#L27)) and ultimately made available in the Desktop app via the `window.configData` object (see [here](https://github.com/Automattic/wp-calypso/blob/f025fdec6e95e9a61625f47164adcc08231600c9/client/document/desktop.jsx#L70) and [here](https://github.com/Automattic/wp-calypso/blob/f025fdec6e95e9a61625f47164adcc08231600c9/client/config/index.js#L …

Fix Oauth Client ID Resolution

---

package.json
packages/launch/src/focused-launch/index.tsx
packages/launch/src/focused-launch/styles.scss
packages/launch/src/launch/index.tsx
packages/launch/src/launch/styles.scss
yarn.lock

💡  Merges into https://github.com/Automattic/wp-calypso/pull/46686
* ~~This PR adds Recoleta font weight 500 (MediumBold) to our font mixins. This is to stick with the Figma spec.~~
* ~~Then modifies stylelint rules to allow weight 500~~.
* It makes numerous UI changes to make sure every typography in the focused launch is ready for all the upcoming changes. 
* Implements mobile layout. Now mobile layout is ready. 
* Makes all the gaps and spaces exactly like the spec.
1. Sandbox a site (say `MY_SITE.wordpress.com`). The site needs to be:
- unlaunched
- created via Gutenboarding (`/new`)
2. Run `yarn start` in the repo root. At the same time, in a different terminal window, go inside `apps/editing-toolkit` and run `yarn dev --sync`
3. Edit the home page in the block editor
4. Click on the …

Focused Launch: Typography and Mobile Support

---

client/lib/cart-values/cart-items.js
client/my-sites/checkout/composite-checkout/hooks/use-get-thank-you-url/get-thank-you-page-url.ts
client/my-sites/checkout/composite-checkout/test/composite-checkout-thank-you.js
client/my-sites/checkout/upsell-nudge/index.jsx
client/my-sites/checkout/upsell-nudge/plan-upgrade-upsell/index.jsx

0. Make sure you're in `treatment` group for the a/b test
1. Apply D51830-code and D51847-code
2. Buy Monthly Premium and make sure the refund period and the prices are fine
3. Continue to checkout and make sure Business Monthly is there
4. Cancel the subscriptions
5. Buy the annual plan
Note: This is technically broken for 2-year plans. However, despite being broken, it works quite smoothly as it offers a transition from 2-year Premium to 1-year Business for just $120. I don't want to fix such a bug that can be a feature.

Fix Upgrade to Business Nudge for Monthly Plans

---

client/components/jetpack/card/jetpack-product-card-alt-2/features.tsx
client/components/jetpack/card/jetpack-product-card-alt-2/style.scss

This PR aligns "See all features" links in pricing page.
Fixes 1196341175636977-as-1198950642531518
- Run Calypso
- Visit the plans page with the 3 plan cards in a single row
- Check that "See all features" links are positioned just below the features lists (see captures)
_Before_
_After_

Align "See all features" links in pricing page i2

---

client/lib/abtest/active-tests.js

* This sets the start date for the monthly pricing experiment to a far-future date, which effectively disables the test for now, while we continue to research an issue with this test that's causing the final loading screen in the signup flow, just prior to checkout, to hang indefinitely.
- Open: https://calypso.live/start?branch=update/monthly-pricing-exp-date in an incognito window.
- Register, choose domain, select plan, and confirm that you're forwarded to checkout.
Repeat again for each plan, and confirm no issues with the redirection to checkout at the end of signup.

Disable monthly pricing experiment while we research a bug.

---

client/blocks/site/index.jsx
client/state/selectors/is-site-coming-soon.js
client/state/selectors/test/is-site-coming-soon.js

This commit adds a Coming Soon badge to the site in the sidebar when coming soon v2 is enabled.
We're also checking if coming soon v2 is enabled in the is-coming-soon selector so we can return the correct value. 
⚠️ This only works on Simple Sites :)
Apply D51626-code (this ensures that `is_coming_soon` is `true` for coming soon v2 in the `me/sites` response)
Create a site at `/new?flags=coming-soon-v2`
Check that the new site has the correct badge in the sidebar (Coming Soon)
To test that the selector is returning the correct value, head over to `/settings/general/{your_new_site}?flags=coming-soon-v2`
You should see the following:
If you remove ?flags=coming-soon-v2 from the URL, you'll see the v1 message (private ) 
Fixes #46628

Coming Soon v2: add site badge and ensure we show the correct launch message on the settings page

---

client/blocks/editor-checkout-modal/style.scss

* Add a lower z-index to the checkout modal to avoid notices getting hidden behind it when the modal is open and an incorrect coupon code gets entered.
* On a site that is on the free plan, open the editor and add a premium block.
* Click "Upgrade" which should display the checkout modal
* Once the modal successfully loads, click "Add a coupon code" to reveal the input field.
* Add a random set of characters and hit "Apply"
* Error notice should successfully appear over the checkout modal.
* It is also worth checking no other unwanted elements within the editor overlay the checkout modal when its open as we've lowered the `z-index`
Alternatively, [watch here](https://www.loom.com/share/62176fddf1394f61b8870e4fcf38a9ef) for testing steps.
Fixes …

Lower z-index to checkout modal to reveal notice element

---

.teamcity/settings.kts

Enables the global setting `calypso.run_full_eslint` with value "false". Otherwise TeamCity expect that to be defined on each agent, and it will refuse to start the Code Style build if it is not.
It is used in https://github.com/Automattic/wp-calypso/blob/master/.teamcity/settings.kts#L529 to lint all files in branches (as opposed to only lint changed files)
Check the Code Style job is running for this branch

Declare param run_full_eslint

---

client/controller/index.node.js
client/controller/index.web.js
client/controller/web-util.js
client/login/index.node.js
client/login/index.web.js
client/login/redirect-logged-in/index.node.js
client/login/redirect-logged-in/index.web.js
client/login/redirect-logged-in/package.json

When redirecting `/log-in/link` to `/` in a logged-in session, use the Node.js/Express.js handler to do that.
The handler in `web-util` uses `page.js` to do the redirect, probably crashing the server. It can't ever work. The `page.js` router works with `window.history` etc.
Unfortunately testable only with user bootstrapping. Check that `/log-in/link` in logged-in session is redirected by server.
Fixes #46652

Use Node.js version of redirectLoggedIn on server

---

client/layout/utils.ts

- reading scrollHeight is potentially slow
https://stackoverflow.com/questions/45960181/what-is-the-fastest-way-to-get-height-width-of-unstyled-element-in-javascript
- So stop before scrollHeight is read if currently ticking
This is more of a theoretical optimization than anything, I couldn't find a situation where it makes a difference on my computer, but maybe on slower computers?
* Same as #46689

handleScroll() doesn't run at all if waiting on requestAnimationFrame

---

client/blocks/editor-checkout-modal/index.tsx
client/blocks/editor-checkout-modal/style.scss

* Use Modal component so it looks less cramped and does not hide important information such as the total price.
* This also takes care of existing accessibility issues for this feature.
Before:
After:
* Go to a website with a free plan.
* Add a premium block in the editor for one of the posts/pages. (e.g. `/premium content`) whilst ensuring you are on a mobile device.
* Click the "Upgrade" button to reveal the modal and ensure that it's not cramped, or similar to `/checkout`
Fixes https://github.com/Automattic/wp-calypso/issues/46904
Fixes https://github.com/Automattic/wp-calypso/issues/46487
Fixes https://github.com/Automattic/wp-calypso/issues/46486

Fix editor checkout modal layout on small devices

---

client/components/jetpack/card/jetpack-product-card-alt-2/features-product-slide-out.tsx
client/my-sites/plans-v2/constants.ts
client/my-sites/plans-v2/product-card-alt-2/index.tsx
client/my-sites/plans-v2/types.ts
client/my-sites/plans-v2/use-item-price.ts

This PR updates the copy of the Jetpack CRM card and slide-out.
Fixes 1196341175636977-as-1198877504751357
- Slide-out doesn't look like the mockups. There's a separate PR for this.
- Time frame in slide-out says "per month, billed yearly", instead of "per month".
- CRM is not considered as a regular product and price must be harcoded for the time being.
- Price is only shown in USD for the time being.
- Added 3 news properties to `SelectorProduct` to handle this specific case: `displayTerm`, `displayPrice`, `displayCurrency`.
- Run Calypso
- Visit the plans page
- Check the CRM card and the CRM slide-out inside the Complete card against the mockups (see captures …

Update CRM cards in pricing page i2

---

client/components/jetpack/card/jetpack-product-card-alt-2/index.tsx
client/components/jetpack/card/jetpack-product-card-alt-2/style.scss
client/my-sites/plans-v2/product-card-alt-2/index.tsx

This PR updates the style of an owned product, for legacy and current plans.
- I made the "You own this" mention absolute, so that main buttons are still aligned (given the tagline is a oneliner)
- Run Calypso
- Select a site that has a legacy Jetpack plan
- Visit the plans page
- Make sure the legacy plan card has no ribbon, and padding at the bottom
- Check that plans and products owned or included in the plan are marked as such
- Switch back to the v1 variant and check that the page looks like production
_Before_
_After_

Update cards for owned products in pricing page i2

---

client/my-sites/plans-v2/product-card-alt-2/index.tsx
client/my-sites/plans-v2/use-item-price.ts

This PR fixes a bug that displayed monthly prices when the yearly option was selected.
- Run Calypso and cloud concurrently
- Visit the plans page
- Check that yearly prices are lower than monthly prices (except for Jetpack CRM Entrepreneur)

Show discounted yearly price in pricing page i2

---

client/components/activity-card-list/index.jsx
client/my-sites/activity/activity-log-v2/index.tsx

* Adds link to settings page in Activity Log v2. Based off of #46874.
* Fixes a few TS issues.
* Set up a JP site with a timezone different from yours and a paid plan.
* Visit Jetpack Cloud -> Activity Log and verify link correctly goes to wp-admin settings page.

Adds correct settings link to Activity Log v2

---

client/components/jetpack/scan-threats/index.tsx

As proposed in a [JPOP issue](https://github.com/Automattic/jpop-issues/issues/6085), the wording of on the Jetpack Scan screen might not line up with our [new scope of support](https://jpophappy.wordpress.com/2020/10/15/scans-scope-of-support/), so after a conversation in Slack this PR tweaks the copy to clarify that support can answer questions rather than suggesting we could help resolve threats. It changes the wording on the page from:
> Please review them below and take action. We are here to help if you need us.
To instead:
> Please review them below and take action. If you have any questions, we are here to help.
Testing requires a WordPress site with a Jetpack plan that includes Scanning.
- Use [jurassic.ninja](https://jurassic.ninja/create/?shortlived) to create a temporary …

Jetpack scan: Update copy on scan screen regarding contacting support.

---

client/lib/signup/step-actions/fetch-sites-and-user.js

Without this PR, test in production first:
https://wordpress.com/start
- Enter signup flow in an incognito window.
- Register new account and make your way to the plans page.
- Reload the page.
- Choose a plan.
Do you get stuck on this page?
**Now test with this PR. Still an issue?**
https://calypso.live/start?branch=try/fetch-site-user-fix
---
@jaswrks writes...
This resolves the issue for me. I don't understand why, though. It's definitely cleaner this way, but the promise chain in `user.fetch()` was already triggering `user.handleFetchSuccess()`, which was emitting the change event every time. Why does this fix it? https://github.com/Automattic/wp-calypso/blob/d682d34136b055b7c392ab3586f94c77de6a6411/client/lib/user/user.js#L134
@taggon writes...
> There’s a kind of race condition. So …

WIP: Uses the promise version of user fetch

---

client/boot/common.js
client/desktop/lib/cookie-auth/index.js
client/desktop/server/index.js
client/lib/desktop/index.js

Attempting to fix the broken admin bar stats graphic of the "Stats" menu item on the main Calypso landing page.
- At application boot, the graphic is displayed as a broken link due to a forbidden URL request:
</p>
Console error: `status 403 (forbidden): https://<site_name>.wordpress.com/wp-includes/charts/admin-bar-hours-scale-2x.php?masterbar=1&s=<site_id>`
On a refresh triggered through the console, the graphic displays correctly.
</p>
Closer inspection of headers sent with the bad/good requests indicate that the bad request is missing the `wordpress_logged_in` cookie in the `Cookie` header. TL;DR: it appears the `wordpress_logged_in` cookie has not yet been parsed and set in Electron by the time the request for the `admin-bar-hours` graphic is …

Fix Broken Admin Stats Graphic on Desktop App Boot

---

client/lib/abtest/active-tests.js

* Re-enable monthly pricing test.
* Set to start at midnight tonite, UTC time. 🎃
- Open in incognito window: https://calypso.live/start?branch=update/monthly-pricing-test
- Register, make your way to the plans page, and add yourself to the monthly pricing test.
- When you arrive at checkout, add paid credits to the test account and complete checkout w/ a monthly plan.
Repeat the test in both `control` and `treatment` groups. Just a spot-check is OK. This has already been looked at by many in the previous release of this test.

Re-enable monthly pricing test.

---

client/boot/common.js

Whoops. In an earlier PR I erroneously deleted the desktop renderer `init` method as I was refactoring ([link](https://github.com/Automattic/wp-calypso/pull/46621/files#diff-a63ee371c7bc2ee8a7642920f46f27318abb705b367cd6fd5512739a832388ecL383-L386)). 🤦 Putting it back.
To emphasize: the intent of the original PR wasn't even to delete that piece of code - I was moving things around and totally spaced out on deleting this in its entirety.

desktop: fix mistaken init removal

---

client/lib/safe-image-url/index.js
client/lib/safe-image-url/test/index.js

Photon, our image resizing service, will not process images with a query string. We only serve Photon-processed images on the Reader post card.
A user contacted us wanting to know why their post isn't shown as a gallery card, when there are several large images in the post:
Several images in the post were hosted on googleusercontent.com (Google Photos) and had a query string of `authuser=0`. Since this parameter seems make no difference to the rendering of the image, this PR adds stripping of authuser when the value is 0. This allows Photon to process the image and the result is:
P2 reference: p5PDj3-4Up-p2
Visit https://wordpress.com/read/blogs/146448168. Scroll down to 18th May 2020. Note that it only displays one image on the post card.
Apply the PR and visit …

Reader: drop authuser=0 from image URLs before passing to Photon

---

desktop/package.json

* Bumps the desktop app version to 6.3.0-beta1
* Given this is just a version change, green CI should be enough. In fact, the whole reason to open this PR in the first place is to have the tests run in CI

desktop: Bump version to 6.3.0

---

client/blocks/reader-export-button/index.jsx
client/blocks/reader-export-button/style.scss
client/reader/list-manage/index.jsx
client/state/data-layer/wpcom/read/lists/index.js
client/state/data-layer/wpcom/read/lists/items/index.js

* Fetch up to 2000 list items in the initial pass
* Refactor the list edit components into functional components and add a loading indicator for the list items
* Always show the export tab, disable the button if we have not loaded the list items yet
* Load a list with more than 10 items. Verify that all 10 items appear. 
* Verify that a loading indicator appears on the `/items` section while loading the items
* Verify the export tab appears instantly along with the Sites and Details tabs
* Load the export tab directly on a long list and a slow network. Verify that the button is disabled while the list items load and enabled once loaded if there are items in the list.

Fetch up to 2000 list items, refactor list edit components

---

client/blocks/editor-checkout-modal/index.tsx

* When we open the editor checkout it appends a step hash to the URL e.g. `#step2`. Currently this stays in the URL when we close the checkout modal so this change cleans up the URL and removes the hash when the component is going to unmount.
* Open the editor for a page or a post of a free site.
* Add a premium block (e.g. `/premium content`).
* Click "Upgrade" above the newly added premium block.
* When the modal opens, take note of the newly added hash `#step2` in the URL.
* Closing the modal should now remove this hash.
Fixes https://github.com/Automattic/wp-calypso/issues/46485

Remove hash from URL when EditorCheckoutModal unmounts

---

apps/editing-toolkit/editing-toolkit-plugin/editor-gutenboarding-launch/index.ts

* Add a comment in the code to hint that the "Launch" button should have an explicit, different translation from the "Publish" button
N/A

Persistent Launch Button: add translators hint for button label

---

client/my-sites/plans/current-plan/purchases-listing.jsx

* Currently, monthly versions of Jetpack Security are being displayed with an unintelligible name. This is because the name of these products are composed of React components and we are trying to print them as they were strings.
* Run this PR (horizon is enough since we only care about Calypso Blue).
* Visit `/plans/my-plan/:site` with a Jetpack Site that has the monthly version of Jetpack Security Daily.
* Make sure that the name of the plan looks correct and that there is no trace of `[Object object]`.
* Visit `/plans/my-plan/:site` with a Jetpack Site that has the monthly version of Jetpack Security Real-time.
* Make sure that the name of the plan looks correct and that there is no trace of `[Object object]`.
Fixes 1164141197617539-as-1198981849134413
> ##### Jetpack Security Daily
> …

My Plan: fix broken Jetpack Security product name

---

client/my-sites/checkout/composite-checkout/components/wp-checkout-order-summary.js
client/my-sites/checkout/composite-checkout/lib/get-plan-features.ts

For reasons I don't fully understand, [this line](https://github.com/Automattic/wp-calypso/blob/1fd266531b3ff3ed8d34ab2d2a92f1901a192a2f/client/my-sites/checkout/composite-checkout/components/wp-checkout-order-summary.js#L283) (added in https://github.com/Automattic/wp-calypso/pull/46466) seems to be throwing a fatal error for some people of the form `e.startsWith is not a function. (In 'e.startsWith(\"~~\")', 'e.startsWith' is undefined)`. This seems to me like it shouldn't happen since that the value passed to that function [passes through `Boolean()`](https://github.com/Automattic/wp-calypso/blob/1fd266531b3ff3ed8d34ab2d2a92f1901a192a2f/client/my-sites/checkout/composite-checkout/components/wp-checkout-order-summary.js#L282), but the fatal errors are still there. It may be that somehow …

Checkout: Convert getPlanFeatures to TypeScript

---

.circleci/config.yml

Limit cache to `.cache/evergreen/css-loader`.
|   | Cache Restore Time  | Cache Save Time   | Source Build Time | Total Build Time  | link |
|---|---|---|---|---|---|
| All .cache (1.6 GB)  | 3m 37s  | 7m 11s   | 4m 2s | 19m 17s | [example](https://app.circleci.com/pipelines/github/Automattic/wp-calypso/79063/workflows/29ae8b4a-c061-4d04-b411-4eb8d994963f/jobs/939010) |
| css-loader only (1.1 mb)  |  0s | 1s ([link](https://app.circleci.com/pipelines/github/Automattic/wp-calypso/79066/workflows/c0b75af6-ee97-490a-8aff-d0496232c60d/jobs/939027))   | 7m 31s  |  11m 40s | [example](https://app.circleci.com/pipelines/github/Automattic/wp-calypso/79066/workflows/e64e5f3c-3dcd-4dc9-8621-59ac9adda3b4/jobs/939040) | 
Looks like the `.cache` folder has become rather bloated (1.6 GB!), to the …

desktop ci: use css-loader cache only

---

packages/shopping-cart/src/types.ts
packages/shopping-cart/src/use-shopping-cart-manager.ts
packages/shopping-cart/src/use-shopping-cart-reducer.ts

This differentiates the `@automattic/shopping-cart` cache status of 'pending' (when a cart update is pending) versus a new status, 'fresh-pending', which is when the cart has not loaded at all, but has made a request. This allows the `isLoading` property of `useShoppingCart` to stay true while the cart has made a request but has not yet received it. This used to be the case but was accidentally changed by https://github.com/Automattic/wp-calypso/pull/46532/commits/b17921046062678f25120271e4b70fd835d51442 in https://github.com/Automattic/wp-calypso/pull/46532 (I believe this was the actual cause of the bug mentioned in https://github.com/Automattic/wp-calypso/issues/46753).
- Visit checkout with a product in the URL and be sure that the loading animation displays.
- Verify that when the …

Shopping Cart: Use 'fresh-pending' cacheStatus for initial loading

---

client/components/jetpack/card/jetpack-product-card-alt-2/features-item.tsx
client/components/jetpack/card/jetpack-product-card-alt-2/features-product-slide-out.tsx
client/components/jetpack/card/jetpack-product-card-alt/features.tsx

Adds Tracks tracking events to the "Learn more"(open) and "Close" actions of the product slide-outs in the features-list of all plans. 
- Add the `calypso_product_slideout_open` Tracks event to fire when product slide-outs are opened and `calypso_product_slideout_close` when they are closed, with parameters for the current site ID and the specific product_slug that was opened.
- Refactored & cleaned up code a little bit`:
- Added `useOpenClose()` custom hook in `features-item.tsx`
- Moved the slide-out open/close functionality into `FeaturesProductSlideOut` component by adding an `isOpen` prop.
- Checkout this branch, yarn start Calypso and jetpack.cloud concurrently.
- make sure `v2` is selected from the `jetpackConversionRateOptimization` A/B test.
Open and close all the slide-out …

CRO i2: Add tracking events to plans slide-out products.

---

client/my-sites/plans/current-plan/jetpack-checklist/index.tsx

* Update copy for Downtime Monitor on Jetpack checklist.
* Fire up with PR, possibly creating a [new JN site in the process](https://jurassic.ninja/create/).
* Connect your site, purchase a plan, wait to get redirected to the checklist.
* Alternatively, connect your site and head directly to http://calypso.localhost:3000/plans/my-plan/SITE_URL
Before
After

Jetpack Checklist: Update copy for Downtime Monitor on Jetpack checklist

---

client/me/purchases/manage-purchase/index.jsx
client/me/purchases/manage-purchase/purchase-meta.jsx

This PR adds an upgrade button, and some tracking events, to the plan settings screen.
**Before**
**After**
- Pick a plan and manage your subscription. Confirm there is an upgrade button and that it takes you to the plans, and fires an event, when you click on it.
- Manage a subscription for an eCommerce plan and confirm there is no upgrade button.
- Pick a domain or any non-plan product and confirm that there's no upgrade button.

Purchases: Add upgrade button

---

client/lib/products-values/get-product-yearly-variant.ts
client/lib/products-values/index.js
client/my-sites/plans-v2/selector-alt.tsx

This PR fixes a bug that prevented upgrading a single product to its yearly variant from the pricing page.
- The issue should occur in any variant of the pricing page
- Select a self-hosted Jetpack site that has a paid monthly plan, and a monthly subscription to a single product
- Visit the pricing page with the Yearly term selected
- For both your plan and single product, check that the CTA in the card reads "Upgrade to Yearly"
- Verify that clicking on the button redirects you to the checkout page with the yearly variant in the cart, without errors
_Product card with yearly upgrade CTA_
_Error seen before the fix_

Enable single product yearly upgrade from pricing page

---

client/my-sites/domains/domain-management/dns/cname-record.jsx

Improves the DNS editor when editing/creating CNAME records by adding `(Host)` after the `Name` label and `(Points to)` after `Alias of` label. This makes it easier for users that are already used to these descriptions at other providers.
- Checkout this branch
- Navigate to the DNS editor for a domain
- Confirm the before and after images.
| -------|--------|
| <img width="355" alt="Screenshot 2020-10-30 at 5 05 16 PM" src="https://user-images.githubusercontent.com/277661/97728785-418ac580-1ad2-11eb-8d89-4aba3951cd7e.png"> | <img width="347" alt="Screenshot 2020-10-30 at 5 04 35 PM" src="https://user-images.githubusercontent.com/277661/97728748-3768c700-1ad2-11eb-815f-4d18397508ce.png"> |

Adds `(Host)` and `(Points to)` to the CNAME DNS editor

---

client/lib/abtest/active-tests.js

This PR configures the a/b test experiment for pricing page i2. Though the implementation is technically an a/b test, i2 will be shipped to everyone.
Once deployed, users who are not eligible to participate in the test ([see docs](https://github.com/Automattic/wp-calypso/blob/ba85297f6f21d08cd2c693040b8c2c3b2ac03185/client/lib/abtest/README.md)) will see i2. All eligible users will see i2 as well.
- Code review
- Test once deployed

Configure experiment for pricing page i2

---

client/reader/list-manage/index.jsx

Extracted from https://github.com/Automattic/wp-calypso/pull/43236.
Previously, we hid the export tab entirely if the list was empty, or we hadn't loaded the list items yet.
It feels better to make the user aware the feature exists.
Open Reader and edit an existing list. The 'Export' tab should always be present, even if there are no list items.

Reader Lists: always show list export button, but disable if there are no list items

---

client/my-sites/checkout/composite-checkout/lib/translate-cart.ts
packages/shopping-cart/src/cart-functions.ts
packages/shopping-cart/src/empty-carts.ts
packages/shopping-cart/src/shopping-cart-endpoint.ts
packages/shopping-cart/src/types.ts
packages/shopping-cart/src/use-cart-update-and-revalidate.ts
packages/shopping-cart/src/use-shopping-cart-manager.ts
packages/shopping-cart/src/use-shopping-cart-reducer.ts
packages/shopping-cart/test/shopping-cart-endpoint.js

This PR adds a new type inside the shopping-cart package, `ResponseCart<RequestCartProduct>`. This type is used internally within the package and allows us to remove the `TempResponseCartProduct` type that was previously required outside the package, as it was a leaky abstraction.
Previously `TempResponseCartProduct` was used as a way to add new products, missing important properties like their price, to the local cache of the cart so that they could be stored with the other products retrieved from the server until the updated cart could be sent to the server, at which point the updated cart (probably) will return the full version of those products. However, this presented a lot of challenges for consumers of the package that want to safely manipulate the data of the products in the cart …

Shopping Cart: Remove TempResponseCartProduct

---

packages/shopping-cart/src/cart-functions.ts
packages/shopping-cart/test/shopping-cart-endpoint.js

In https://github.com/Automattic/wp-calypso/pull/46532/commits/c773d18666010afe0e6ddb6b3f524c0fe54188a5 (part of https://github.com/Automattic/wp-calypso/pull/46532), I added a bug into `convertRawResponseCartToResponseCart` in the shopping cart code which broke the saving of tax information from the shopping cart.
This PR fixes the regression and adds unit tests so that it won't happen again.
Before this fix:
After this fix:
- Start with an empty shopping cart.
- Visit checkout with a URL that adds a product to the cart, like `/checkout/example.com/business`.
- If you do not have a country and postal code set, set them to something.
- Verify that you see taxes displayed at the bottom (even if they are $0).
- Click "Edit" on the order step to edit the order and change the plan length from …

Shopping cart: Fix tax location calculation

---

client/components/jetpack/card/jetpack-product-card-alt-2/style.scss

This PR fixes a CSS issue occurring in the new pricing page in production. See capture below.
I noticed this bug in production, but not in staging. It seems that some CSS are not loaded in the same order depending on the environment. This PR fixes this by increasing the specificity of the CSS rule.
- In Jetpack cloud, visit the pricing page
- In one of the plan cards, open a product slide-out by clicking "Learn more"
- Notice that the slide-out is the same width as the card
Before
After

Update pricing page slide-out margins in Jetpack cloud

---

client/components/jetpack/card/jetpack-product-card-alt-2/features-product-slide-out.tsx

This PR adds "Upgrade to Yearly" functionality to the product 'slide-outs' if the product is upgradable (owned as an individual product with a monthly billing-term).
1. Checkout this PR, visit the Plans page.
2. First test with any site that has individual products owned on a 'Monthly' billing-term basis. Open/expand the owned product slide-out:
- Verify that the "Upgrade to Yearly" button label appears when it should. (only on owned _monthly-billing_ products, when the "Yearly" billing-term filter is selected.
- Verify that clicking "Upgrade to Yearly" button takes you to checkout with the _Yearly_ variant of the product in the cart.
3. Verify that the other button states ("Manage Subscription", "Get _Product_Name_") in the product slide-outs have not been affected by this change and are …

Add "Upgrade to Yearly" functionality to slide-out products.

---

client/components/jetpack/card/jetpack-product-card-alt-2/style.scss

This PR aligns the cards content in Jetpack cloud, see capture.
- Run Jetpack cloud
- Notice CTA buttons of the first row of cards are aligned
Before
After

Pricing page: align CTA button in Jetpack cloud

---

client/my-sites/checkout/checkout-system-decider.js
client/my-sites/checkout/controller.jsx

This PR removes the option to enter old checkout from the `CheckoutSystemDecider` (making the name of that component a little less semantic; it should probably later be changed to something like `CheckoutWrapper`).
This should have no effect since old checkout is already unused.
This also removes the major use of the `CheckoutContainer` component, although it is still in-use by the GSuite and plan upsell pages, so it cannot yet be removed completely.
Visit checkout and be sure that it still shows up.

Checkout: Disable old checkout completely

---

client/reader/sidebar/reader-sidebar-lists/index.jsx
client/reader/sidebar/reader-sidebar-lists/list-item-create-link.jsx
client/reader/sidebar/reader-sidebar-lists/list-item.jsx
client/reader/sidebar/reader-sidebar-lists/list.jsx
client/reader/sidebar/reader-sidebar-lists/style.scss
client/state/data-layer/wpcom/read/lists/index.js
client/state/reader/lists/reducer.js
client/state/reader/lists/test/reducer.js

* Adds a `Create new list` link in the sidebar.
> <img width="269" alt="Screen Shot 2020-11-02 at 3 40 00 PM" src="https://user-images.githubusercontent.com/4044428/97927226-d33c4200-1d21-11eb-9abb-7f2ba426945c.png">
* Tweaks data-layer and state handling to work properly with our ListForm.
* Spin this up locally or enable the `reader/list-management` feature flag in the environment of your choice.
* Ensure that you can see the new `Create new list` link in the Reader sidebar. It should be within the Lists dropdown folder.
* Ensure that clicking the link takes you to a working create form.
* Ensure that creating a list takes you directly to the list edit page (`/read/list/:user/:listSlug/edit`).

Reader Lists: Enable list creation

---

client/reader/list-manage/index.jsx
client/reader/list-manage/list-delete.jsx
client/reader/list/controller.js
client/reader/list/index.js
client/state/data-layer/wpcom/read/lists/delete/index.js
client/state/notices/constants.js

Create a new tab in List Management for deleting an existing list.
New tab:
Confirmation dialog:
...and it's gone!
On an existing Reader list that you own and are happy to delete, press the 'cog' icon at the top right, then navigate to the 'Delete' tab.
Press the 'delete' button. If you choose 'keep it', you should return to the delete tab without any changes made.
Press the 'delete' button again, and this time, go through with the deletion. The list should be deleted and you should be navigated to /read with a success notice displayed.

Reader Lists: add new tab for list deletion

---

apps/editing-toolkit/editing-toolkit-plugin/global-styles/src/font-pairings-panel.js

* https://github.com/Automattic/wp-calypso/pull/46927 failed to remove some unused variables, which is breaking the code style build step. This PR removes them.
I re-ran through the testing from the original PR, which was updating global font styles:
Check out the branch and sync to your sandbox using yarn dev --sync
Create a new post and open the Global Styles editor.

Remove unused vars from global styles font pairings

---

desktop/README.md
desktop/docs/development.md
desktop/docs/notarization.md
desktop/docs/release.md
desktop/docs/secrets.md
desktop/docs/troubleshooting.md

Add (and update) desktop docs that weren't part of the initial migration from wp-desktop repo.

docs: add docs

---

client/reader/list-manage/index.jsx
client/reader/list-manage/list-form.jsx
client/state/data-layer/wpcom/read/lists/index.js
client/state/reader/lists/actions.js

* Removes duplicate code introduced by a rebase error.
* Disables the slug text input for the update form.
* Slightly tweaks the `READER_LIST_UPDATE_FAILURE` action to propagate the list object causing the update failure.
* Spin this up locally or enable the `reader/list-management` feature flag in the environment of your choice.
* Navigate to `/read/list/new` and ensure that the form works as expected.
* Navigate to `/read/list/:user/:listSlug/edit` and ensure that the form works as expected.

Reader Lists: Remove duplicate ListForm component

---

client/reader/list/index.js

@blowery spotted that, although we gate the display of the list edit button behind the `reader/list-management` feature flag, we don't actually prevent the user from accessing the tools via their URLs. For example, you can currently add `/edit` to any list URL in production and access the editing tools.
Since this is still a work in progress, this PR hides those pages when the feature flag is set to false.
In development.json, set the `reader/list-management` feature flag to `false`. Run `yarn start`.
Ensure that you can't reach 'Edit List' by adding `/edit` to a list URL.

Reader Lists: hide list editing routes behind feature flag

---

apps/editing-toolkit/editing-toolkit-plugin/coming-soon/fallback-coming-soon-page.php
client/blocks/site/index.jsx

This PR swaps the WP logo image with the relative path so it will display on all sites (think Atomic), and namespaces the class names.
We're also removing the test copy for v2. We can tell v2 from v1 by the class names in the source.
As an aside, I also noticed the appearance of two coming soon badges on the site bar. This will happen hopefully only during testing, when you're toggling coming soon v2 on an existing site, but I added a small safeguard to prevent that.
While sandboxing, run `yarn dev --sync` in `apps/editing-toolkit`
Create a new site over at wordpress.com/new?flags=coming-soon-v2
Take a look at the new site in an incognito window. You should see the coming soon page (the class names should be prefixed with `wpcom-coming-soon-*` and the WordPress logo should be an SVG)
On …

Coming Soon: updating the fallback page

---

client/boot/locale.js
client/lib/i18n-utils/switch-locale.js

- Move require chunk listener setup for translation chunks in `client/lib/i18n-utils/switch-locale.js`
- Remove duplicated code in `client/boot/locale.js` related to translation chunks setup
- Boot Calypso locally with `BUILD_TRANSLATION_CHUNKS=true ENABLE_FEATURES=use-translation-chunks yarn start` or use calypso.live build. For calypso.live, you'll need to enable translation chunks by adding `?useTranslationChunks`  flag to the URL
- Change UI language to a Mag-16 one.
- Add Navigate through Calypso screens and confirm translations display properly.
- Additionally, inspect the Network tab in DevTools to confirm translation chunks are being fetched. Translation chunk JSON file names should be prefixed with the selected locale slug, e.g. `de-{chunkId}.json`.
- Go to `/start/{localeSlug}`, …

i18n: Refactor translation chunks setup

---

client/me/help/help-contact/index.jsx

Adds the plan name and subscription term to the ticket plain text. For example, if the user is on a monthly Business plan, the text `Plan: Business (Monthly subscription)` will be added to the ticket.
* Login as a user with a valid plan.
* Create a ticket by clicking on the "?" icon in the bottom right and select "Contact Us".
* Inspect the network response for the request sent to create the ticket.
* The plan name and term should be present in the message body.

Adds the plan name and term to ticket plain text

---

client/my-sites/sidebar-unified/style.scss

* Fixes the state (not-active / active) of the icons that are rendered as images
* add `?flags=nav-unification`
* check that Jetpack icon behaves the same as in `wp-admin`
Before | After
-------|------

Fix sidebar menu item image icon states (for icons which are images)

---

client/state/sites/domains/assembler.js

Fixes a typo introduced in #37073 where we attempt to call `toIsoString` instead of `toISOString`.
Inspect the code 👀

Domains: Fix transfer end date parsing

---

client/landing/gutenboarding/gutenberg-types-patch.ts
client/landing/gutenboarding/index.tsx
packages/domain-picker/src/domain-picker/index.tsx
packages/domain-picker/src/domain-picker/style.scss
packages/domain-picker/src/domain-picker/suggestion-item.tsx
packages/domain-picker/src/index.tsx
packages/domain-picker/src/types-patch.ts

* Add select button to domain picker.
* Make domain price aligned in the middle (2:1 ratio between domain name and domain price).
**Selected Label**
Currently the select button behaves like radio button because it is the role of the implementor to decide what to do once a domain is selected by listening to the `onSelect` event, e.g. go back to the main focused launch page.
So for now, when select button is clicked, the button label turns from "Select" to "Selected". This is not part of the design but is necessary.
**Mobile**
There is no mobile version implemented for this one as this is only intended for desktop. We will decide how to switch between Select button and tapping the entire row for mobile in another PR.
**Usage**
The usage would look like this when integrated with focused …

DomainPicker: Add select button.

---

client/me/purchases/titles.js
client/my-sites/purchases/main.tsx
client/my-sites/purchases/subscriptions/account-level-purchase-links.tsx

This PR updates the titles for the purchase settings screens and standardizes the terminology.
**Before**
**After**
Review the screenshots or: 
* Visit the billing screen at the site level and confirm the "View all subscriptions" button has been changed to "View all purchases".
* Click on a purchase and confirm the title in the header cake is "Purchase Settings" instead of "Subscription Settings".
* Visit the account level manage purchases screen and visit a purchase. Confirm the header cake says "Purchase Settings" instead of "Manage Purchase".
Fixes https://github.com/Automattic/wp-calypso/issues/46239

Payments: Update titles for purchases

---

client/blocks/credit-card-form/helpers.js

This PR adds a new event every time a new credit card is saved. 
* If you're testing this locally, you'll need to sandbox to use the credit card form.
* Visit the purchase settings form for any subscription.
* Click on Change Payment Method.
* Confirm the `calypso_purchases_save_new_payment_method` event fires after a credit card is successfully added.

Purchases: Add new save credit card event

---

.teamcity/settings.kts

* Add three new scripts to the unit test CI in TeamCity to smoke test storybook.
Adding these should help prevent us from mysteriously breaking storybook with dependency updates or other changes. (see https://github.com/Automattic/wp-calypso/pull/47098, for example where we have to fix these things without knowing what caused them)
* Verify that unit test TeamCity passes
Fixes #

Add storybook scripts to unit test CI

---

packages/domain-picker/src/constants.ts
packages/plans-grid/src/constants.ts

* Instead of hardcoding the store keys, those packages now also try to register the store
* This fixes a bug where the `@automattic/domain-picker` and the `@automattic/plans-grid` packages would not be able to correctly use the required data-stores, if those stores were not already registered somewhere else in the code
* This change ultimately makes these packages more independent 
* Create a new site with `/new`
* Domain picker and Plans grid should work as usual
Fixes #46870

Register required data stores in Domain Picker and Plans Grid packages

---

client/jetpack-cloud/sections/settings/advanced-credentials/credentials-form/index.tsx
client/jetpack-cloud/sections/settings/advanced-credentials/credentials-form/style.scss
client/jetpack-cloud/sections/settings/advanced-credentials/index.tsx

* Currently, the Advanced Server Credentials doesn't work well when a site has only Jetpack Scan. The real credentials status is not correct and we always show the `disconnected` state. This PR solves this issue by using the new `QuerySiteCredentials` component which fetches the real status of the credentials.
* I removed everything Rewind related since `QuerySiteCredentials` offers everything we need to know the state of the credentials.
* Run this PR, Calypso Green build.
* Visit Jetpack Cloud with a site that only has Jetpack Scan.
* Visit the Settings section and complete the Server Credentials flow.
* Make sure that the form shows the `Connected` state.
* Delete the credentials.
* Make sure that you are back to step 1.
* Complete the credentials again.
* Make sure that the form shows …

Jetpack Cloud: make the Advanced Server Credentials form support sites that only have Jetpack Scan

---

client/blocks/reader-export-button/index.jsx
client/blocks/reader-export-button/style.scss
client/blocks/reader-import-button/index.jsx
client/blocks/reader-import-button/style.scss
client/reader/following-manage/style.scss
client/reader/following-manage/subscriptions.jsx

* Updates our custom button component to use `Button` from `@automattic/components`.
Before (disabled and enabled are visually identical):
After (disabled and enabled):
* Navigate to `/read/list/:userId/:listSlug/export`. Ensure that the button renders as expected.

Reader Lists: Update export button styling

---

client/lib/wpcom-undocumented/lib/undocumented.js
client/state/data-layer/wpcom/read/lists/index.js
client/state/reader/lists/actions.js
client/state/reader/lists/test/actions.js

Modernize the code used to fetch a single Reader list, using data layer instead of thunks and `wpcom.undocumented()`.
* Load Reader at http://calypso.localhost:3000/read. Click on one of your subscribed lists in the Reader sidebar.
Ensure that a request to /read/lists/:owner/:slug was fired off during list load:

Reader Lists: move single list request to use data layer

---

client/reader/list-manage/feed-item.tsx
client/reader/list-manage/list-delete.jsx
client/reader/list-manage/site-item.tsx
client/reader/list-manage/tag-item.tsx

* Use the same style for all buttons
* Translate button text 
Edit one of your existing Reader lists. Ensure the buttons look consistent across all tabs.

Reader Lists: make buttons consistent

---

client/reader/sidebar/reader-sidebar-lists/list.jsx

* Hides the list creation link in the sidebar behind a feature flag.
* Ensure that the list creation link is shown according to the `reader/list-management` feature flag. (Enabled in development, disabled everywhere else.)

Reader Lists: Hide list creation link behind feature flag

---

test/e2e/localization-data.json

With the recent introduction of subdirs for locales instead of subdomains and fully enabling el/he/ro/ko locales, the e2e tests should be updated to use wordpress.com/he instead of he.wordpress.com and wordpress.com/ko instead of ko.wordpress.com
1. Follow the steps at https://github.com/Automattic/wp-calypso/blob/master/test/e2e/README.md and https://github.com/Automattic/wp-calypso/blob/master/test/e2e/docs/running-tests.md#getting-started to prepare for running e2e tests locally
2. Within local Calypso instance `cd test/e2e` and run `./run.sh -I`
3. Confirm that `logged-out-redirect-i18n-spec.js e2e test (should redirect to the correct url for wordpress.com (he))` and `logged-out-redirect-i18n-spec.js e2e test (should redirect to the correct url for wordpress.com (ko))` have passed …

Update the test data to use subdir instead of subdomain for HE and KO

---

client/state/data-layer/wpcom/read/lists/sites/delete/index.js
client/state/reader/lists/actions.js

Requires D44927-code.
Somewhat confusingly, the current way to remove a site from a Reader list is to call the feed delete endpoint with a $feed_id of 'site:$site_id'. This doesn't feel intuitive and does not match the behaviour of the add endpoints.
This PR switches to use the new `/read/lists/:owner/:slug/sites/:site/delete` endpoint instead for site deletions.
`yarn test-client client/state/reader/lists`

Reader Lists: set up /read/lists/:owner/:slug/sites/:site/delete endpoint in data layer

---

client/document/index.jsx

* Remove masterbar from loading state until we have shipped Nav Unification to 100% of users
* load calypso
* make sure masterbar doesn't appear in loading state
* check both without `?flags=nav-unification` and with `?flags=nav-unification`
Before | After
-------|------
Relates to https://github.com/Automattic/wp-calypso/issues/47044#issuecomment-721821286

Masterbar: remove from loading state

---

client/my-sites/sidebar-unified/style.scss

* changes the width to 272, as agreed in the issue #46912
* load calypso with `?flags=nav-unification`
* check the sidebar menu and make sure it is wider and still works in breakpoints etc…
* please check the same work done for wp-admin D52281-code
Fixes #46912

Nav Unification: New menu width

---

client/me/purchases/concierge-banner/index.jsx

More info: p7DVsv-9JV-p2#comment-32376
This changes the duration of the purchasable QS upsell banner on /me/purchased.
* Create a new site (lower than eCommerce), or use a site without any purchased QS sessions
* Go to /me/purchases
* QS upsell banner should read: 
Used a variable instead of hardcoded 30 for the included QS session banner.
* Create a new site (eCommerce), or use a site with an included QS session
* Go to /me/purchases
* QS upsell banner should be unchanged:

Update QS upsell duration on purchases page

---

packages/domain-picker/tsconfig.json
packages/launch/tsconfig.json
packages/onboarding/tsconfig.json
packages/plans-grid/tsconfig.json

List monorepo dependencies as references in the `tsconfig.json` file of the following packages:
- `@automattic/launch`
- `@automattic/onboarding`
- `@automattic/plans-grid`
- `@automattic/domain-picker`
In the project's root folder, run these commands. They should all run without errors:
- `yarn clean:packages; ./node_modules/.bin/tsc --build packages/launch`
- `yarn clean:packages; ./node_modules/.bin/tsc --build packages/onboarding`
- `yarn clean:packages; ./node_modules/.bin/tsc --build packages/plans-grid`
- `yarn clean:packages; ./node_modules/.bin/tsc --build packages/domain-picker`

Add monorepo dependencies to tsconfig.json for Launch, Domain Picker, Plans Grid and Onboarding packages

---

client/my-sites/domains/domain-management/components/domain/main-placeholder.jsx
client/my-sites/domains/domain-management/controller.jsx
client/my-sites/domains/domain-management/edit/navigation/enhanced.jsx
client/my-sites/domains/domain-management/transfer/index.jsx
client/my-sites/domains/domain-management/transfer/transfer-to-other-site/confirmation-dialog.jsx
client/my-sites/domains/domain-management/transfer/transfer-to-other-site/index.jsx
client/my-sites/domains/domain-management/transfer/transfer-to-other-site/test/index.jsx

The time is now: self-serve domain mappings 🎉 Splitting the work - this patch adds the ability to move domain mapping to a different site (it's simply easier to adjust this case than the user one).
Requires D51163-code, but it's already been merged 🎉 
Go to Domain Management where you have a mapping you want to transfer. You should see a new action for it - Transfer mapping.
You need to be an admin on at least one other site to be able to transfer the mapping anywhere, of course.
And you need to be the owner of the mapping subscription - so be sure to check that case as well (probably need to adjust the copy there).
Step by step via screenshots:
For a PWPO user where the target site is not on a paid plan:
PWPO-exempt user where the target site is not a paid plan:
When the target site is …

Domains: Self-serve domain mapping transfers to other site

---

client/my-sites/customer-home/cards/tasks/style.scss

* Reduce the font size of the body copy on the main card element on My Home.
* We may revisit the card design in a future PR, but this is a quick adjustment to bring the body copy in line so it doesn't appear huge.
**Before**
**After**
* Navigate to `/home` on your test site
* Note the difference in size on the body copy text. Check on a site that has a checklist, as well as a site that has completed the checklist.
Fixes #45084

My Home: Update font size for title and body text on task cards

---

packages/launch/src/focused-launch/summary/index.tsx

* Refactor `<Summary />` component and split it into different steps.
* Introduce the concept of `activeSteps`(steps that require user interaction)  vs `disabledSteps` (steps that are not interactive, and only serve as a summary to the user)
These changes are part of the preparation work that facilitates the changes required by #46858
Since this PR is a refactor, it's important to test that the Focused Launch modal as a whole still works like in production.
* Make sure you have an active connection to your sandbox, and that your sandbox is clean and up to date
* In two separate terminal windows, from the root of the project, run:
- `yarn start`
- `cd apps/editing-toolkit && yarn dev --sync`
* Sandbox an unlaunched WordPress site created via `/start` by adding it to your host file
* Visit …

Focused Launch: Split Summary into modular Steps

---

client/my-sites/domains/domain-management/controller.jsx
client/my-sites/domains/domain-management/transfer/index.jsx
client/my-sites/domains/domain-management/transfer/transfer-to-other-user/index.jsx

Follow-up to #46418. This time allowing users to transfer domain mapping subscriptions to other admins on the same site. This should bring feature parity between mappings and registrations.
Note that this is based on work from #46418 (don't want to merge during US elections). So the only new changes are in this one commit: https://github.com/Automattic/wp-calypso/pull/47060/commits/eb6f9a1033d347c6f40b3fc59280374d7806dfb6
Requires D52223-code on the backend.
You need a site where you own a mapping subscription and there's at least one more admin on the site (preferably your other test user ;)).
Go to Domains -> yourmappeddomain.com -> Transfer mapping -> Transfer to another user.
Make sure the copy you see is mapping-specific and makes sense in the context of mapping (as opposed to domain …

Domains: Allow transfer of mappings to other administrators on site 

---

.github/CODEOWNERS

This adds two new checkout-related packages, `@automattic/shopping-cart` and `@automattic/calypso-stripe` to CODEOWNERS for the Shilling Payments team.
Fixes https://github.com/Automattic/wp-calypso/issues/47064
Fixes https://github.com/Automattic/wp-calypso/issues/47129
None

Add calypso-stripe and shopping-cart to CODEOWNERS

---

client/components/olark-chat/index.jsx
client/jetpack-cloud/sections/pricing/header/index.tsx
config/_shared.json
config/jetpack-cloud-development.json
config/jetpack-cloud-horizon.json
config/jetpack-cloud-production.json
config/jetpack-cloud-stage.json

* This PR adds a new component, `OlarkChat`, and uses that component on the non-logged-in Jetpack.com pricing page.
* This will enable customers to chat with HE's to ask questions before purchasing a product or plan.
1. Load the PR locally and do `npm run start-jetpack-cloud`.
2. In one browser tab, head to Olark (check with me for creds).
3. In another browser tab, head to the pricing page at `jetpack.cloud.localhost:3000/pricing`.
4. After a few moments, the "Chat with us" bubble should appear at the bottom right. Click on it and ensure the chat works.

Jetpack: Add Olark pre-sales chat to Jetpack pricing page

---

client/my-sites/checkout/composite-checkout/components/empty-cart.tsx
client/my-sites/checkout/composite-checkout/composite-checkout.tsx
client/my-sites/checkout/composite-checkout/hooks/use-redirect-if-cart-empty.ts
client/my-sites/checkout/composite-checkout/record-analytics.js

This adds a new view that renders in checkout when the cart is empty. Since typically a customer will be redirected to the plans page when the cart is empty, this should normally never be seen. However, if there is an error displayed on the screen which prevents the redirect, then this view will be shown instead of the loading animation.
Before:
After:
Fixes https://github.com/Automattic/wp-calypso/issues/45182
- Add a plan to your cart and visit checkout. Verify that you see the loading animation until the cart finishes loading, and that it then renders checkout with the plan in the cart. Verify that you never see the empty cart view.
- Remove the product from your cart. Verify that you see the pending state on the form's buttons until the change completes, and that you are redirected to …

Checkout: Show empty cart view when cart is empty

---

config/jetpack-cloud-production.json

* This PR ensures that the pre-sales chat is not present in production Calypso Green yet.

Calypso Green: Don't show pre-sales chat in production

---

apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nux/class-wpcom-block-editor-nux.php

This one, magic line ensures that the NUX modal content is translated:
`wp_set_script_translations( 'wpcom-block-editor-nux-script', 'full-site-editing' );`
🧙  IT'S MAGIC!
Check out the branch
Get your sandbox running
Run `cd apps/editing-toolkit && yarn dev --sync` from your Calypso root
Create a new site at `wordpress.com/new{de|es|fr|mag16 locale of your choice}`
Check that the NUX modal is translated 👍 
The other quick way (if you don't want to create a new site) is to comment out the [following lines](https://github.com/Automattic/wp-calypso/blob/master/apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nux/src/wpcom-nux.js#L62) in [wpcom-nux.js](https://github.com/Automattic/wp-calypso/blob/master/apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nux/src/wpco …

Editing Toolkit: set translations for NUX modal

---

client/my-sites/plans/main.jsx

* This PR fixes the bug that plans page doesn't show the prices to the Brazilian users on the Business monthly plan.
* You should be a Brazilian user who's using the `BRL` currency.
* The current site should be on the Business monthly plan.
* Go to the `/plans` page of your site.
* The plans page should show _yearly_ plans instead of _monthly_ plans and all the prices should be displayed.

Fix: BR users on Business monthly cannot see the plan prices

---

client/my-sites/checkout/composite-checkout/components/item-variation-picker.tsx

* This PR fixes the bug that BR users aren't able to pick Business monthly on the checkout page.
* Buy a Business plan as a Brazil users who's using the `BRL` currency.
* Note that you may need sandboxed `public-api.wordpress.com`. The checkout page might be stuck in the _loading_ status.
* Go to the checkout page and you should be able to select the monthly term.

Fix: BR users aren't able to pick business monthly on the checkout page

---

packages/calypso-build/CHANGELOG.md

Fixes a regression from https://github.com/Automattic/wp-calypso/pull/47002/files#r518539663 by adding backticks. Prevents `*` being treated as Markdown syntax rather than a real star.

Fix broken MD formatting in calypso-build/CHANGELOG.md

---

client/lib/plans/features-list.js
client/lib/plans/plans-list.js

* In the signup flow with the monthly pricing test, the first feature of Premium Plan should be "Live chat support" instead of "Email & Live chat support".
* Make sure you're not in the `monthlyPricing` test or you're in the `control` of the test.
* The Premium features in the `onboarding` signup flow look as below:
* Assign yourself to the `treatment` and the Premium plan would look as following:

Fix premium plan features for monthly pricing test

---

apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nux/src/wpcom-nux.js

Updating copy to emphasis the hidden nature of new sites rather than the private by default aspect, which we'll be rolling back with coming soon v2 (by default new sites will be in coming soon mode, but public (not indexable)
We're also showing all steps now that the Launch button is persisting in p9Jlb4-1SN-p2 and https://github.com/Automattic/wp-calypso/pull/46817
Context p1603330128417000-slack-C9EJ7KSGH
The quick and dirty way of checking the changes is to comment out the following lines in [wpcom-nux.js](https://github.com/Automattic/wp-calypso/blob/205c3bd/apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nux/src/wpcom-nux.js#L52)
```
/*	
if ( ! isWpcomNuxEnabled || isSPTOpen ) {
return null;
}
*/
```
Run `yarn dev --sync` from `apps/editing-toolkit`
Create a new site …

Editor Toolkit: update slide copy in NUX

---

client/components/domains/free-domain-explainer/index.jsx

This change will only add the word annual if the locale is 'en' to prevent the string from appearing non-updated
See 671-gh-martech
1. Sign up with a new user, with an 'en' locale (the locale can be changed by adding /en to the signup URL)
2. Domain step should display the word 'annual' in the Free domain explainer component
3. Change the locale to something else. The screenshot is with Spanish
4. Old copy, no annual, should be there

Add the word annual to free domain explainer

---

client/my-sites/controller.js
client/my-sites/domains/controller.jsx
client/my-sites/domains/index.js
client/my-sites/plans/index.js
client/my-sites/plans/test/index.js

In this PR, we fix a bug with the P2 project in which we allow interacting with the Plans page when navigated to it directly.
We enable using the plans page if the P2+ (P2 paid plan) is enabled. So far it's enabled only on dev and staging so a12s will be able to use it.
We also fix a bug in which if you navigate to the Manage Domains page with a P2 site you are redirected to `/` instead of the site's home as it's very closely related.
1. Locally, with the config flag `"p2/p2-plus"` set to whatever as it shouldn't affect this one: Navigate to a non-p2 site's Manage Domains page (under Manage in sidebar). Now, switch to a P2 site. You should be redirected to the site's Home page.
2. Locally, with the config flag `"p2/p2-plus"` set to `true`: Navigate to a non-p2 site's Plans page. Now, …

P2: redirect to Home when trying to access Plans

---

client/jetpack-cloud/sections/settings/advanced-credentials/host-selection/index.tsx

Small copy change on the new Jetpack credentials flow to make it clear we have guessed the host:
**Before:**
It looks like your host is ___
**After:**
It looks like your host may be ___
* Pull this PR
* Test the cloud.jetpack.com entry point and head to settings
* Test with a guessed host (e.g. Bluehost)

Jetpack Credentials: Make it clearer in the heading that we have guessed the host

---

client/signup/steps/user/index.jsx

* Subscribe UserStep component from the signup process to i18n changes, so it re-computes the sub header title when translations get updated asynchronous (e.g. from translation chunks require hook).
**Before:**
**After:**
- Boot Calypso locally with `BUILD_TRANSLATION_CHUNKS=true ENABLE_FEATURES=use-translation-chunks yarn start` or use calypso.live build. For calypso.live, you'll need to enable translation chunks by adding `?useTranslationChunks`  flag to the URL
- Set your browser primary language to any of the Mag-16, and go to `/start` (w/o the locale slug) in an incognito tab
Fixes 171-gh-i18n-issues

i18n: Fix signup sub header title remaining untraslated with async translations

---

client/components/promo-section/index.tsx
client/components/promo-section/promo-card/index.tsx
client/my-sites/earn/home.tsx
client/my-sites/earn/style.scss

* Add support for Gridicons in the `PromoSection PromoCard` component.
* Replace images with Gridicons on the `/earn` screen for a cleaner, more flexible look.
* We don't have exact matches for the custom images in our icon set; feel free to dispute my alternatives with [something else from Gridicons](https://github.com/Automattic/gridicons).
* The color in the old PNGs was also different, so I used a close approximation from Color Studio.
**Before**
**After**
* Switch to this PR and navigate to `/earn` on your site
* Note the icon changes
* Make sure this screen for different types of sites (Business, Premium, Free, Jetpack) appears as expected
* Make sure other instances of the `PromoSection PromoCard` component outside the `/earn` screen are unaffected (these include but are not …

Earn: Replace images with Gridicons

---

client/blocks/editor-checkout-modal/style.scss

This was reintroduced by https://github.com/Automattic/wp-calypso/pull/46942
* Add a lower z-index to the checkout modal to avoid notices getting hidden behind it when the modal is open and an incorrect coupon code gets entered.
* On a site that is on the free plan, open the editor and add a premium block.
* Click "Upgrade" which should display the checkout modal
* Once the modal successfully loads, click "Add a coupon code" to reveal the input field.
* Add a random set of characters and hit "Apply"
* Error notice should successfully appear over the checkout modal.
* It is also worth checking no other unwanted elements within the editor overlay the checkout modal when its open as we've lowered the `z-index`
Alternatively, [watch here](https://www.loom.com/share/62176fddf1394f61b8870e4fcf38 …

Update z-index value for editor-checkout-modal to reveal notice.

---

client/my-sites/backup/rewind-flow/progress-bar.tsx
client/my-sites/backup/rewind-flow/restore.tsx
client/my-sites/backup/rewind-flow/style.scss
client/state/data-layer/wpcom/sites/rewind/api-transformer.js
client/state/data-layer/wpcom/sites/rewind/schema.js
client/state/data-layer/wpcom/sites/rewind/type.ts
client/state/selectors/get-in-progress-rewind-entry-details.js

This PR adds more details to the restore progress screen, so that users have a better understanding of what's happening in real-time. See captures below.
- @elliottprogrammer did the initial worked in #47071. I rebased the branch and updated the UI accordingly.
- The API doesn't return the type of the entry, so I needed to adjust the copy a little bit (`Currently restoring: [entry]`).
Note: the back-end returns _Unknown_ for the entry while it's being finalized. This should never be the case once done.
- Apply this patch D52234-code to your wpcom sandbox and point `public-api.wordpress.com` to it
- Run this PR in Calypso or Jetpack cloud
- Select a self-hosted Jetpack site that has a Backup product, and more than one backup
- Make sure you have set server credentials to enable restores
- …

Add details to restore progress screen

---

apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nux/src/style.scss

* Smaller font size for heading in NUX modal when locale is German
* This is to avoid text clipping
* Follow instructions from https://github.com/Automattic/wp-calypso/pull/47136 but pick german as the language
* When the NUX modal is showing, go through the steps, the text should not be clipped

Editor NUX modal: Temporarily make text smaller in editor welcome modal for german language

---

client/my-sites/backup/rewind-flow/restore.tsx
client/state/activity-log/restore/reducer.js
client/state/data-layer/wpcom/activity-log/rewind/restore-status/index.js
client/state/data-layer/wpcom/activity-log/rewind/restore-status/test/index.js
client/state/data-layer/wpcom/activity-log/rewind/restore-status/type.ts
client/state/selectors/get-restore-progress.ts

This PR is a sequel of #47153. It retrieves data from a different endpoint in order to show more granular percentage and to display the entry being restored.
- Run this PR in Calypso or Jetpack cloud
- Select a self-hosted Jetpack site that has a Backup product, and more than one backup
- Make sure you have set server credentials to enable restores
- Visit the _Backup_ section, select a backup to restore, and click _Restore to this point_, the _Confirm restore_
- Check that you see the message and current entry returned by the API, respectively above and below the progress bar
- Make sure the order of messages makes sense and that there's no big jump in the progress bar

Fetch restore progress details from `/restore` endpoint

---

apps/editing-toolkit/editing-toolkit-plugin/full-site-editing-plugin.php
apps/editing-toolkit/editing-toolkit-plugin/readme.txt
apps/editing-toolkit/package.json

* Editor NUX modal: Temporarily make text smaller in editor welcome modal for german language (#47193)
* Editor Toolkit: update slide copy in NUX (#46674)
* Focused Launch: fix domain picker not showing in summary page in Calypso (#47141)
* Reinstating condition (#47136)
* Make text of Premium Content's Subscribe button editable (#46983) 
* Remove premium content block placeholder. (#47068)
* Focused Launch: use site title hook in the name step (#46921)
* Add block pattern dom validation tests (#45747)
* For the coming soon fallback page: namespace the class names, add an svg for the wp logo (#46994)
* Remove unused vars (#47072)
* Update global font pairings (#46927)
* Add recordTracksEvent for Editor NUX modal (#46796)
1. Load the diff on your sandbox …

Editing Toolkit: Update to 2.8.4

---

packages/composite-checkout/src/components/loading-content.tsx

This PR fixes a bug on the tablet version of checkout where we show the two column loader layout instead of a single column.
**Before**
**After**
Load checkout at different screen widths and confirm that the number of columns in the loader matches the final loaded state.
Fixes https://github.com/Automattic/payments-shilling/issues/42

Checkout: Fix checkout loader for tablet devices

---

client/me/purchases/credit-cards/index.jsx

This PR adds event tracking on the `add credit card` button on our payment method screen.
* Visit payment method screen (At the site and account level)
* Click "Add credit card" button. 
* Confirm `calypso_purchases_click_add_new_payment_method` event fires.

Purchases: add button event for adding payment method

---

client/my-sites/checkout/composite-checkout/components/wp-order-review-line-items.js

The order review step of checkout displays a list of email addresses being purchased for a new G Suite subscription, but it does not display them when buying extra licenses for an existing subscription. This PR corrects that oversight.
Fixes https://github.com/Automattic/wp-calypso/issues/45787
- Add a G Suite extra license product to your cart (I don't actually know how to do this. 😅  Please help, @stephanethomas !)
- Verify that you see the list of new email addresses displayed in the "Your order" section of checkout.

Checkout: Show G Suite user list for extra license products

---

client/my-sites/checkout/composite-checkout/composite-checkout.tsx
client/my-sites/checkout/composite-checkout/hooks/use-cached-domain-contact-details.ts
client/my-sites/checkout/composite-checkout/hooks/use-country-list.ts
client/my-sites/checkout/composite-checkout/hooks/use-is-apple-pay-available.ts
client/my-sites/checkout/composite-checkout/hooks/use-prepare-products-for-cart.ts
client/my-sites/checkout/composite-checkout/hooks/use-stored-cards.ts
client/my-sites/checkout/composite-checkout/lib/filter-appropriate-payment-methods.ts
client/my-sites/checkout/composite-checkout/payment-method-helpers.js
client/my-sites/checkout/composite-checkout/record-analytics.js
client/state/selectors/get-contact-details-cache.js
client/state/selectors/get-countries.js
packages/composite-checkout/src/public-api.ts

This is a follow-up to https://github.com/Automattic/wp-calypso/pull/46758 which converts the main `CompositeCheckout` component to TypeScript.
In this PR we convert some of the smaller dependencies of `CompositeCheckout` to TypeScript as well, specifically:
- useIsApplePayAvailable
- filterAppropriatePaymentMethods
- useStoredCards
- useCachedDomainContactDetails
- useCountryList
- Make sure Apple Pay loads when it should (testing instructions are beyond the scope of this PR).
- Make sure you see the payment methods you expect when paying with or without full credits.
- Make sure that stored cards are listed as payment methods.
- Make sure that cached contact details load as expected.
- Make sure that all the counties you'd expect are listed in the contact details form.

Checkout: Convert smaller composite checkout dependencies to TypeScript

---

client/my-sites/email/email-management/index.jsx

Fix email page when there is no custom domain. When there are no custom domains, show the prompt to purchase domains:
For a site without a custom domain:
- Go to /email/<site>
- Before the patch you should see the email comparison page
- After applying the patch, you should see the same view as in the screenshot above

Email: Fix email page when no custom domain

---

apps/notifications/src/doc/note-rendering.md

Now that we have solid processes and the inline styles library for improving block rendering in notifications, let's update the docs.
* View https://github.com/Automattic/wp-calypso/blob/ced4875ba8b4dd4c0b19ec9c4ead9823f5c0f364/apps/notifications/src/doc/note-rendering.md.
Fixes https://github.com/Automattic/wp-calypso/issues/46832

Notifications: Update docs with block rendering details.

---

packages/domain-picker/src/domain-picker/index.tsx
packages/domain-picker/src/domain-picker/style.scss
packages/domain-picker/src/domain-picker/suggestion-item.tsx
packages/launch/src/focused-launch/summary/index.tsx

* Connects the domain step to the launch store
1. In apps/editing-toolkit run `yarn dev --sync`.
2. Sandbox testingfocusedflow.wordpress.com.
3. Visit https://testingfocusedflow.wordpress.com/wp-admin/post-new.php.
4. In console, type `wp.data.dispatch('automattic/launch' ).openFocusedLaunch()`.
5. Play with domain picker. You should be able to pick a paid and a free domain.
Partially fixes #46862

Focused Launch: Connect domain picker step with the launch store

---

packages/composite-checkout/src/lib/payment-methods/full-credits.js

This PR updates the copy of the credits pay button to work better on smaller screens.
**Before**
**After**
* Make sure you have credits on your account and visit checkout.

Checkout: update credits pay button for mobile screens

---

client/devdocs/sidebar.jsx
client/extensions/woocommerce/store-sidebar/index.js
client/layout/sidebar/expandable-heading.jsx
client/layout/sidebar/expandable.jsx
client/layout/sidebar/heading.jsx
client/layout/sidebar/index.jsx
client/layout/sidebar/region.jsx
client/me/sidebar/index.jsx
client/my-sites/sidebar-unified/index.jsx
client/my-sites/sidebar/index.jsx
client/my-sites/sidebar/site-menu.jsx
client/my-sites/sidebar/tools-menu.jsx
client/reader/sidebar/index.jsx
client/reader/sidebar/reader-sidebar-lists/index.jsx
client/reader/sidebar/reader-sidebar-tags/index.jsx
client/reader/sidebar/reader-sidebar-tags/list.jsx

* Remove duplicate `ul` wrappers
* Replace all `ul` children with `li` elements
* Propagate ...props further down to the components
* Load Calypso Sites, Reader, Me and make sure nothing has changes UI / UX wise
* Repeat for mobile viewports
Fixes #46095

Fix html invalid markup, propagate react extra props

---

packages/composite-checkout/src/components/checkout-steps.tsx

This PR updates the location of the edit button to make it clearer to people where to go if they want to edit their cart. 
**Before**
**After**
* Add a product to your cart and visit checkout. 
* Make sure edit button appear on the right and are still functional.

Checkout: update edit button position

---

config/jetpack-cloud-production.json

* Revert the Olark identity in Jetpack Cloud production to its "real" value, so that pre-sales chat is re-enabled. (see: #47166)

Reset Olark identity to re-enable pre-sales chat for Jetpack Cloud

---

client/my-sites/sidebar-unified/style.scss

* When the nav unification flag is on, the submenus (covers both flyout menus and expandable menus) will have colors controlled by their own theme variables, instead of hard coded colors.
* Wp-admin color themes can specify submenu colors.  This will allow wp-admin ported themes to be more accurate, providing a seamless experience when switching between calypso and wp-admin.  
* When calypso themes are ported to wp-admin, we will have to add submenu colors to both calypso and wp-admin sides. 
* With nav unification on ( http://calypso.localhost:3000/?flags=nav-unification ), check both expandable and flyout menus.  There should be no change before and after the PR is applied (but the PR applied allows for more flexibility).
Flyout
Expandable

Nav-unification: Submenu colors are controlled by variable

---

client/my-sites/checkout/composite-checkout/composite-checkout.tsx
client/my-sites/checkout/composite-checkout/hooks/use-record-checkout-loaded.ts
client/my-sites/checkout/composite-checkout/lib/translate-cart.ts
client/my-sites/checkout/composite-checkout/payment-method-helpers.js
client/my-sites/checkout/composite-checkout/record-analytics.js
client/my-sites/checkout/composite-checkout/test/composite-checkout.js
client/my-sites/checkout/composite-checkout/types/backend/payment-method.ts
client/my-sites/checkout/composite-checkout/use-create-payment-methods.js

In calypso's implementation of new checkout, `useCreatePaymentMethods` creates all the payment method objects and their necessary stores. Some payment methods are not created because of certain conditions (eg: if there is a stripe loading error, we don't bother trying to create apple pay which relies on stripe). Those payment methods are then filtered later by `filterAppropriatePaymentMethods` based on what the server has told us we can display.
This works fine in production, but when running unit tests, if we try to create all the payment methods we will get errors. Therefore, in order to get tests working I added an argument to `useCreatePaymentMethods` called `onlyLoadPaymentMethods` which is empty in production but used for tests to be able to prevent certain payment methods from …

Checkout: Remove onlyLoadPaymentMethods from CompositeCheckout

---

client/my-sites/sidebar-unified/style.scss

* When using nav unification, the "flyout menu arrow indicator" will use the submenu background color, instead of the menu hover background color.
On ported themes from wp-admin, this makes the arrow match wp-admin:
Calypso, Nav unification, Ectoplasm theme, before change (Arrow is green):
Calypso, Nav unification, Ectoplasm theme, after Change (Arrow is dark purple):
Calypso, default theme, before change:
Calypso, default theme, after change (same as before):
* Visit calypso.localhost:3000/?flags=nav-unification , ensure flyout menu arrow still works with no apparent changes.
* Can also try change on `add/color-scheme-ectoplasm-alt` if desired (screenshots above).

Nav Unification: Flyout indicator arrow uses submenu background color

---

client/blocks/editor-checkout-modal/index.tsx

* Add `shouldCloseOnClickOutside` prop to `<Modal />` component inside the Editor Checkout
* Since the modal is full screen anyway, users should not be able to click "outside" the modal and only be able to close via the keyboard or clicking the "X" in the corner.
The easiest way to test this is...
1. Checkout this branch and on your _local environment_, open a post in the editor for a site with a free plan
2. Add a premium block such as PayPal
3. Click on the "Upgrade" button to open the checkout modal
3. When you see the Stripe HTTPS notice, click it
4. The modal should _not_ close.
* Before [video](https://www.loom.com/share/d5e38562aa8f49bb857787f0a66b08af)
* After [video](https://www.loom.com/share/be29b71e23fe4d5e8846b739fa58f16c)
Fixes …

Editor Checkout: Prevent the modal from closing when clicking outside of it

---

client/my-sites/checkout/composite-checkout/components/wp-checkout-order-review.js
client/my-sites/checkout/composite-checkout/components/wp-checkout.js
client/my-sites/checkout/composite-checkout/components/wp-order-review-line-items.js

* Sets the `originalAmountDisplay` (string) variable only if the `originalAmountInteger` var exists and is non-zero.
* Shows the monthly plan only if the user is on a free or monthly plan. This effectively hides the monthly plan if upgrading from a yearly/biyearly plan.
* Assign yourself to `treatment` variant of the `monthlyPricing` AB test.
* Purchase the Premium annual plan
* From `/plans`, upgrade to the Business plan
* On the checkout screen, the original price (striked out) should be the original cost of the plan
* On clicking "Edit", the monthly plan should not be visible.
* Assign yourself to `treatment` variant of the `monthlyPricing` AB test.
* Proceed with any paid plan
* The original price (striked out) should be the (cost of the monthly plan * 12) for yearly and (cost of the …

Restrict upgrade from annual to monthly plans

---

client/state/document-head/reducer.js
config/_shared.json
config/jetpack-cloud-development.json
config/jetpack-cloud-horizon.json
config/jetpack-cloud-production.json
config/jetpack-cloud-stage.json

This is a part of the overall push to improve Jetpack.com metadata and search engine placement since cloud.jetpack.com/pricing is crawlable.
Context: pbNhbs-hL-p2
* Introduce a new `meta` property in config files which holds data that is rendered as `<meta>` tags.
* Add `description`, `og:description`, and `og:image` meta tags to Calypso Green in accordance with marketing needs.
* Update the meta title of Calypso Green in accordance with marketing needs.
* Confirm Calypso Green meta title, description, og:description and og:image are rendered server side and contain the required messages as described in the doc linked in pbNhbs-hL-p2.
* Confirm the meta changes do not affect Calypso Blue.

Jetpack Cloud: Update html meta for SEO purposes

---

client/my-sites/checkout/composite-checkout/components/field.js
packages/composite-checkout/src/lib/theme.ts

This PR fixes the field height in checkout to match the fields being imported by Calypso.
**Before**
**After**
* Add only a plan to your cart and checkout. 
* Confirm that the fields in the billing info step have the same heights.
* Check fields in payment step to confirm they look right as well. 
Fixes https://github.com/Automattic/wp-calypso/issues/47158

Checkout: fix form field height

---

client/lib/abtest/active-tests.js
client/my-sites/plans-v2/abtest.ts
client/my-sites/plans-v2/controller.tsx
client/my-sites/plans-v2/products-grid-alt-3/index.tsx
client/my-sites/plans-v2/products-grid-alt-3/style.scss
client/my-sites/plans-v2/selector-alt.tsx

Add new AB test variation for the Jetpack Plans page.
I pointed the new AB test variation to a new `products-grid-alt-3` folder & component.
Additional note:  The features list in top 3 plans in this new products-grid-alt-3 page are not working correctly on this page. I didn't take the time to repair this because we will be changing these things in upcoming PR's.
1. Run this PR
2. Visit the Plans page: `http://calypso.localhost:3000/plans/:site`
3. Verify there is a new `jetpackConversionRateOptimization` AB test option labelled: `i5 - Saas table design`
4. Select the `i5 - Saas table design` variant.
5. Verify you can see the text "`i5 - Saas table design`" (See screenshot) - This means you are on the variant plans grid page (`ProductsGridAlt3`)
6. Select the other A/B test variants to …

CRO i5: Add i5 AB test

---

client/layout/sidebar/expandable.jsx
client/layout/sidebar/menu.jsx
client/my-sites/sidebar-unified/menu.jsx
client/my-sites/sidebar-unified/style.scss
client/my-sites/sidebar/test/sidebar.js

Builds on https://github.com/Automattic/wp-calypso/pull/47198
We need to use JS instead of CSS for 2 reasons :
1) Reposition flyout in case it overflows to the bottom of the page
2) Prevent closing of the flyout when making a diagonal mouse movement (hover intent)(will be fixed in next PR) 
* Use JS instead of CSS to trigger hover of flyouts
* Reposition flyout to `bottom:0` if it is off the screen
* Load Calypso and hover the sidebar items that have submenu it should feel exactly the same as in production except than when flyout was supposed to be off the screen, it now appears correctly.
* Repeat for mobile viewports
Before | After
-------|------
Fixes https://github.com/Automattic/wp-calypso/issues/46094

Use JS to trigger hover and reposition the flyout

---

client/my-sites/sidebar-unified/style.scss

* When the nav unification flag is on, the expandable submenu will have customizable colors for its currently selected item.  Previously, they were hardcoded to white fg and transparent bg.
* This works fine for most themes, except **light** from wp-admin.  It already has a white background so I need to be able to override the text cleanly.
* Very similar to #47249, which covered unselected and hovered items.  This adds selected (or active) items.
* With nav unification on ( http://calypso.localhost:3000/?flags=nav-unification ), check the colors of the selected item in an expandable menu.  It should look the same before and after.

Nav-unification: Selected submenu color is chosen by variable

---

apps/editing-toolkit/editing-toolkit-plugin/editor-site-launch/src/attach-focused-launch.tsx
apps/editing-toolkit/editing-toolkit-plugin/editor-site-launch/src/launch-steps/domain-step/index.tsx
client/blocks/editor-launch-modal/index.tsx
client/landing/gutenboarding/onboarding-block/domains/index.tsx
packages/domain-picker/src/domain-picker/index.tsx
packages/launch/src/context.ts
packages/launch/src/focused-launch/summary/index.tsx
packages/launch/src/launch/index.tsx

The `<DomainPicker>` was using the `useI18n()` hook from `@automattic/react-i18n` to get the current locale. The `<DomainPicker>` is a shared component with it's own package, so every use of the component depended on `@automattic/react-i18n` working.
The problem is that the component is used in the launch flow (within the editing toolkit), and `@automattic/react-i18n` isn't being correctly set up to work in that environment. It'd need to to have a `<I18nProvider localeData={ ... }>` component somewhere near the root of the React tree and to have the server render `localeData` as part of the payload. But core already injects translations into the payload to make it available to `@wordpress/i18n`; doing it twice would be wasteful.
`@automattic/react-i18n` might progress enough to the point …

Gutenboarding i18n: i18n for domain picker in the launch flow

---

client/state/data-layer/wpcom/read/lists/feeds/new/index.js
client/state/data-layer/wpcom/read/lists/index.js
client/state/data-layer/wpcom/read/lists/items/index.js
client/state/data-layer/wpcom/read/lists/sites/delete/index.js
client/state/data-layer/wpcom/read/lists/tags/new/index.js
client/state/notices/actions.js

* Display success notices for all CRUD actions.
* Always auto-vanish success notices after 5 seconds.
* Use consistent punctuation in success notices.
* Don't auto-vanish error notices.
`yarn test-client client/state/reader/lists`

Reader Lists: standardize success notices

---

client/reader/list-manage/README.md
client/reader/list-manage/index.jsx
client/reader/list-stream/README.md

Prevent a user from accessing list management UI unless they own the Reader list.
* Go to a Reader list you don't own, like http://calypso.localhost:3000/read/list/blowery/comics. Try editing the list using:
http://calypso.localhost:3000/read/list/blowery/comics/edit
http://calypso.localhost:3000/read/list/blowery/comics/edit/items
http://calypso.localhost:3000/read/list/blowery/comics/delete
http://calypso.localhost:3000/read/list/blowery/comics/export
Ensure that you see this message:
Try the same on a list you own and ensure you can access all the management functionality.

Reader Lists: Prevent list management unless user is owner

---

test/e2e/lib/pages/cancel-purchase-page.js

* Update the main views selector for the purchase cancellations page so the tests can find the correct elements.
1. If you haven't already, configure your local environment to run the E2E tests here PCYsg-7p3-p2
2. Once you have done the above. `cd test/e2e`.
3. `./node_modules/.bin/mocha specs/wp-signup-spec.js`.
4. The tests should successfully delete the plans and the following error should not be output to the console
`There was an error in the hooks that clean up the test account (delete plan) but since it is cleaning up we really don't care: 'TimeoutError: Timed out waiting for element with css selector of '.cancel-purchase.main' to be present and displayed
Wait timed out after 22216ms'`
Fixes https://github.com/Automattic/wp-calypso/issues/47284

E2E Tests: Fix .deletePlan() flow

---

packages/launch/package.json
packages/launch/src/focused-launch/summary/index.tsx

* Implement the logic described in #46862 and #46865 for the commentary text shown alongside the domain and plan summary steps
* Check out this branch on your machine, and run `yarn start` in the project root
* Visit `calypso.localhost:3000/page/UNLAUNCHED_SITE_ID/home?flags=create/focused-launch-flow-calypso`
* By changing the `hasPaidDomain` and `hasPaidPlan` variables in the code, check that the commentary shows as follow:
- Domain step:
- When site doesn't have a pre-purchased domain:
- When site already has a pre-purchased domain:
- Plan step:
- When site doesn't have a pre-purchased plan:
- When site already has a pre-purchased plan:
While working on the commentary logic, I also marked all currently available strings for translations
Please refer to #46862 and #46865 for screenshots …

Focused Launch: steps commentary logic

---

client/my-sites/marketing/connections/service-action.jsx
client/my-sites/marketing/connections/service-description.jsx
client/my-sites/marketing/connections/service.jsx
client/my-sites/marketing/style.scss
client/state/sharing/keyring/schema.js
client/state/sharing/keyring/selectors.js

Instagram, Facebook and possibly other, tokens need to be refreshed on a
regular basis. If we aren't able to, we should indicate that the
connection will break after the token expiry date.
This is the front end changes to D52030-code, which sets adds the
`refresh-failed` status to the API endpoint. As such this PR should be
merged before the backend changes.
If the connection is returned as having the `refresh-failed` status then
we treat it like a broken connection, displaying the 'Reconnect' button,
and a message about when the connection is due to expire.
* Apply D52030-code to your sandbox, and follow the instructions there to place your Instagram connection in the required state.
* Using this branch, check the display of the connection in `/marketing/connections`. It should look …

Marketing Connections: Make the UI aware of the refresh-failed status

---

apps/notifications/src/panel/indices-to-html/index.js

Refactors how the empty ranges are handled by notifications in order to properly display the text nodes.
Before | After
--- | ---
- Sandbox the API and apply D52453-code and D52422-code.
- Create a variety of posts containing blocks affected by the issues noted in https://github.com/Automattic/wp-calypso/issues/46961:
- File block.
- Blocks with `figcaption` elements (e.g. Gallery block).
- Separator block.
- HTML block.
- Posts without title.
- Make sure they are displayed correctly.
Fixes https://github.com/Automattic/wp-calypso/issues/46961

Notifications: Fix orphan text nodes

---

client/components/activity-card-list/index.jsx

* Currently, the date format we use is not localized, which means that it only works fine for English. This PR conditionally selects a format depending on whether users use English as their language. Users that use English won't see any change, while the rest of the users will see a localized format.
* Run this PR (Calypso Green version is required).
* Select a Jetpack site that has some activity in the Activity Log.
* Make sure that your account language is English.
* Visit `http://jetpack.cloud.localhost:3001/activity-log/:site`.
* Verify that dates look like the capture for English in the demo section.
* Change your account language to a different one.
* Refresh the Activity Log page.
* Make sure that dates are formatted in a way that makes sense for the selected language. You can do …

Jetpack Cloud's Activity Log: Set date format according to user locale

---

client/lib/abtest/active-tests.js
client/lib/analytics/sem.js
client/my-sites/checkout/composite-checkout/components/wp-checkout-order-review.js
client/my-sites/checkout/composite-checkout/components/wp-checkout-order-summary.js
client/my-sites/checkout/composite-checkout/components/wp-checkout.js
client/my-sites/checkout/composite-checkout/hooks/product-variants.js
client/my-sites/checkout/composite-checkout/test/composite-checkout.js
client/my-sites/plans-features-main/plan-type-selector.tsx
client/signup/steps/domains/index.jsx
client/signup/steps/plans/index.jsx
client/state/marketing/selectors.ts

* Apply ExPlat to the monthly pricing test 2nd phase. The first phase of the same test was based on the old a/b test framework but the current phase is going to adopt the new experiment platform.
* Ensture that you're proxied.
* Make sure you're in the `treatment` variation of any following experiments: `monthly_pricing_test_phase_2_us_en`, or `monthly_pricing_test_phase_2_eu`
* Or the value of the `country_code` cookie should be either `AR`, `CL`, or `CO`.
* Try to sign up through the `onboarding` flow.
* You should be able to see the monthly plans in the plans step.
* When you choose a paid plan, you should be able to see the monthly plan option in the checkout page too.
_Note: In the above screenshot, the annual/biennial plan options don't show the monthly price x 12 next to the own …

Apply ExPlat to the monthly pricing test 2nd phase

---

client/my-sites/sidebar-unified/style.scss
packages/calypso-color-schemes/src/shared/color-schemes/_blue.scss
packages/calypso-color-schemes/src/shared/color-schemes/_ectoplasm.scss
packages/calypso-color-schemes/src/shared/color-schemes/_light.scss
packages/calypso-color-schemes/src/shared/color-schemes/_modern.scss
packages/calypso-color-schemes/src/shared/color-schemes/_sunrise.scss

This is relatively straightforward and an easy change with no downsides, in my opinion.
* This is considering the color of text when hovering over sidebar items.
* Before we started the nav-unification project, calypso color schemes used `color-sidebar-menu-hover-text`.
* When we first added nav unification styles, we defined two variables, with the same color value:
* `color-sidebar-menu-hover-text`
* This matches the calypso variable, but wasn't used anywhere.
* `color-sidebar-menu-hover`
* This was a new variable that only existed in nav unification.
* Change all references of `color-sidebar-menu-hover` to `color-sidebar-menu-hover-text`.
* Remove all theme definitions of `color-sidebar-menu-hover`.
* The existing definitions of `color-sidebar-menu-hover-text` will work in their place. …

Nav unification: consolidate color-sidebar-menu-hover and -text variable

---

packages/data-stores/src/launch/actions.ts
packages/data-stores/src/launch/index.ts
packages/data-stores/src/launch/reducer.ts
packages/data-stores/src/launch/selectors.ts
packages/launch/src/focused-launch/summary/index.tsx
packages/launch/src/hooks/use-domain-search.ts
packages/launch/src/hooks/use-title.ts
packages/launch/src/utils.ts

* Ensure that steps in the summary view of the Focused Launch flow always appear in the correct order within the disabled/active group:
1. Site name
2. Domain
3. Plan
* Show "Name Your Site" step only if the site title contains the string "Site Title"
* If the "Name Your Site" step is shown to the user, that step should _always_ be shown in the Focused Launch flow for that site, even if the user changes the site title to a different value from the initial one
* Check out the branch on your machine and run in two parallel terminal windows:
- `yarn && yarn start`
- `cd apps/editing-toolkit && yarn dev --sync`
* Create two different sites by visiting `calypso.localhost:3000/start` (`SITE_ID_1` and `SITE_ID_2`)
* Add both `SITE_ID_1` and `SITE_ID_2` to your sandbox, and refresh your hosts/DNS …

Focused Launch: ensure summary steps order

---

client/my-sites/checkout/composite-checkout/components/payment-method-step.tsx
client/my-sites/checkout/composite-checkout/components/wp-checkout.js
client/my-sites/checkout/composite-checkout/components/wp-order-review-line-items.js
client/my-sites/checkout/composite-checkout/composite-checkout.tsx
client/my-sites/checkout/composite-checkout/lib/does-purchase-have-full-credits.ts
client/my-sites/checkout/composite-checkout/lib/filter-appropriate-payment-methods.ts
client/my-sites/checkout/composite-checkout/lib/translate-cart.ts

This PR adds a "Credits" line item to the review step of checkout just before the final payment button, if any credits are available. That way, the math of that step adds up. Previously, the credits were implied (they are shown with the individual line items near the top of the page) and it made the math seem incorrect.
In addition, when the customer has enough credits to fully cover the purchase price before taxes, we do not charge taxes on the purchase (I don't know why this is, but it's how the backend appears to work); this PR corrects a bug wherein if you have enough credits to fully cover the purchase but the taxes would bump it above that amount, the review step would display a strange total of the difference, but still allow you to pay with credits.
Fixes …

Checkout: Add credits to order review

---

client/my-sites/checkout/composite-checkout/components/wp-checkout.js

This adds a React error boundary around the contents of the `CheckoutSummaryArea` (the information sidebar) in new checkout. This will catch any fatal errors thrown inside the sidebar and prevent them from breaking the rest of checkout.
Fixes https://github.com/Automattic/wp-calypso/issues/47020
Without an error:
With an error:
First, visit checkout and be sure that you see the sidebar (which is collapsed to the top of the main column at small widths) and that it includes some information on the purchase you're making.
Next, modify the code in `WPCheckoutOrderSummary` to throw an Error. Load checkout and verify that you see the error boundary in the sidebar (`Sorry, there was an error loading this information.`) but that the rest of checkout is unaffected.

Checkout: Add CheckoutErrorBoundary around CheckoutSummaryArea

---

client/me/payment-methods/main.tsx

This PR fixes a bug when you navigate from plans > the account level payment methods.
Before
**After**
* Start at /plans for any site
* Navigate to the Payment Methods page (Me => Manage Purchases => Payments Methods)
* Confirm nothing is broken on desktop or mobile.
Fixes https://github.com/Automattic/wp-calypso/issues/47335

Purchases: fix payment method screen

---

client/components/jetpack/card/jetpack-product-card-alt-2/index.tsx

This PR displays decimals in i2 of the pricing page.
- Make sure v2 of the pricing is selected (ping me if you don't know how)
- Notice the decimals (see capture)

Enable price decimals in pricing page i2

---

client/blocks/color-scheme-picker/constants.js

* Color scheme order on `/me/account` is alphabetical.
* Visit `/me/account`
* See the color scheme order
* Main Issue #45435
* Color Schemes Issue + Direction  #45675

Display color schemes in alphabetical order

---

client/my-sites/sidebar-unified/style.scss

* Adjust the colour of site notices as @sfougnier suggests https://github.com/Automattic/wp-calypso/pull/46819#issuecomment-719000053
Before | After
-------|------
* Please follow the same instructions https://github.com/Automattic/wp-calypso/pull/46819#issue-510954125

Updates sidebar site notices color

---

client/blocks/site-icon/index.jsx
client/blocks/site-icon/style.scss
client/my-sites/sidebar-unified/style.scss

Update site icon to globe to match the new nav-unification [figma designs ](https://www.figma.com/file/9cy0DIowQkPAu0rodb9jsL/WP-Admin-for-Dotcom?viewport=0%2C0%2C1)
Note: **this change will affect all users immediately** 
* Updates default site icon to globe and makes it smaller
Before | After
-------|------
* load a site without icon in http://calypso.localhost:3000/
* Please also test D52653-code which fixes the icon color in wp-admin

Updates default site icon to globe and makes it smaller

---

client/components/jetpack/backup-date-picker/index.jsx
client/components/jetpack/backup-placeholder/index.jsx
client/components/jetpack/daily-backup-status/backup-changes.jsx
client/lib/jetpack/backup-utils.js
client/lib/jetpack/test/backup-utils.js
client/my-sites/backup/date-picker.jsx
client/my-sites/backup/hooks.js
client/my-sites/backup/main.jsx
client/my-sites/backup/search-results.jsx
client/my-sites/backup/status/hooks.js
client/my-sites/backup/status/index.jsx
client/my-sites/backup/status/simplified-i4.jsx
client/my-sites/backup/status/style.scss
client/my-sites/backup/style.scss
client/state/activity-log/utils.js
client/state/data-getters/index.js

Fixes `1164141197617539-as-1186890594349665`, `1184358343400545-as-1190849472047377`.
* Split the Backup page into several discrete components, like `DatePicker`, `BackupStatus`, and `SearchResults`.
* Create separate status components for daily and real-time backups, because the information they display is fairly diverged.
* Preserve feature flag behavior for `jetpack/backup-simplified-screens-i4`, but move it under `backup/status/simplified-screens-i4.jsx`.
* Create new custom hooks `useDailyBackupStatus` and `useRealtimeBackupStatus`, to simplify the process of getting the information to display the backup status for a particular site on a given date.
* Try to make all the logic -- and there's so much of it -- more self-contained and easy to reason about.
* Move a couple styles to get …

Jetpack Backup: Correctly display backup status and navigation for sites with lots of activities

---

client/components/jetpack/card/jetpack-product-card-i5/assets/checkmark.svg
client/components/jetpack/card/jetpack-product-card-i5/assets/chevron.svg
client/components/jetpack/card/jetpack-product-card-i5/assets/star.svg
client/components/jetpack/card/jetpack-product-card-i5/features-item.tsx
client/components/jetpack/card/jetpack-product-card-i5/features.tsx
client/components/jetpack/card/jetpack-product-card-i5/index.tsx
client/components/jetpack/card/jetpack-product-card-i5/style.scss
client/components/jetpack/card/jetpack-product-card-i5/time-frame.tsx
client/components/jetpack/card/jetpack-product-card-i5/types.ts
client/jetpack-cloud/sections/pricing/style.scss
client/my-sites/plans-v2/product-card-i5/index.tsx
client/my-sites/plans-v2/products-grid-i5/index.tsx
client/my-sites/plans-v2/products-grid-i5/style.scss
client/my-sites/plans-v2/utils.ts

This PR integrates the product cards of the new pricing page.
Fixes 1196341175636977-as-1199149328812562
Fixed in later PRs:
- Icon of CRM has a wrong colour
- Plan cards don't show features
- Spacing between description and price must be refined once copy is validated
- Run Calypso and Jetpack cloud concurrently
- Compare the page with the mockups (see task) in both Calypso and cloud, and a various viewport widths
- Check that the feature toggle of a product card works
_3 card layout_
_2 card layout_
_1 card layout_

Implement product card of pricing page i5

---

client/components/jetpack/card/jetpack-product-card-alt-2/index.tsx

* https://github.com/Automattic/wp-calypso/pull/47343 brought back decimal pricing, but it was supposed to be only for USD. This PR ensures that we are only showing decimal pricing for the USD currency.
* Check the pricing page with currencyCode set to USD. You should see pricing with `.95`. 
* Now check the pricing page with a currencyCode set to something other than USD. You should see whole-number pricing.

Jetpack Pricing: Don't display decimal prices for non-USD currencies

---

client/jetpack-cloud/sections/pricing/jpcom-masterbar/index.tsx
client/jetpack-cloud/sections/pricing/jpcom-masterbar/style.scss
client/my-sites/plans-v2/plans-filter-bar/style.scss

This PR removes the jpcom masterbar fixed on scroll behavior, making it static full-time - But only for jetpackConversionRateOptimization A/B test variant: `i5 - Saas table design`.
- In the `JetpackComMasterbar` component, I removed the `useDetectWindowBoundary()` hook and `ref` to go along with it.  This hook was detecting when the masterbar reaches the top of the viewport (which is immediately on page load) and makes the element "sticky", however the same behavior was already being accomplished with css so there was no need for this hook here, or the overhead to go along with it.
- I also fixed an issue with previous iterations (`v1 - 3 cols layout` & `v2 - slide outs`) where the plans grid UI was "jumping up" every time the plans-filter-bar goes to 'sticky' position. Scrolling the …

CRO i5: Remove jpcom masterbar fixed behavior on desktop.

---

client/my-sites/plans-v2/product-card-i5/index.tsx

Remove icons of individual products in pricing page i5
Fixes 1196341175636977-as-1199169204272054
- Check that individual product cards don't show any icon

Pricing page i5: remove all products icons

---

client/lib/cart-values/index.js
client/my-sites/checkout/composite-checkout/payment-methods/credit-card/credit-card-fields.js
client/my-sites/checkout/composite-checkout/payment-methods/credit-card/credit-card-pay-button.js

`lib/cart-values` contains several functions for querying the list of payment methods returned by the shopping-cart endpoint. Notably, it has functions for translating between the "long" versions of the names on the server (aka "class names", eg: `WPCOM_Billing_Ebanx_Redirect_Brazil_Tef`) into the "short" versions on the client (eg: `brazil-tef`). As new checkout has its own updated functions for this purpose, it makes sense to prevent keeping lists of these strings in two places. This PR removes or replaces uses of the old functions in favor of the new ones.
Depends on https://github.com/Automattic/wp-calypso/pull/47258
Depends on https://github.com/Automattic/wp-calypso/pull/47259
Fixes https://github.com/Automattic/wp-calypso/issues/44998
This is part of a chain of related PRs. The …

Checkout: Remove paymentMethodClassName and PAYMENT_METHODS

---

client/my-sites/checkout/composite-checkout/lib/filter-appropriate-payment-methods.ts
client/my-sites/checkout/composite-checkout/lib/is-payment-method-enabled.ts
client/my-sites/checkout/composite-checkout/lib/translate-payment-method-names.ts

The `upgrades/redirect-payments` config option, disabled in the desktop app, is supposed to control if redirect payment methods are available. It does not do so in new checkout. This PR fixes that oversight.
Fixes https://github.com/Automattic/wp-calypso/issues/47214
Depends on https://github.com/Automattic/wp-calypso/pull/47260
This is part of a chain of related PRs. The next one is https://github.com/Automattic/wp-calypso/pull/47261
- Visit checkout in a browser. Verify that the PayPal payment method is listed.
- Visit checkout in a desktop app. Verify that the PayPal payment method is _not_ listed. You can simulate this by changing the `upgrades/redirect-payments` config option to be `false` in `config/development.json`.

Checkout: Disallow redirect payment methods in desktop app with new checkout

---

client/lib/cart-values/index.js
client/my-sites/checkout/checkout/index.jsx

This removes the `getEnabledPaymentMethods` function from `lib/cart-values`. As we are working on removing that library and migrating all its functionality to new checkout, this is a major piece and completes a process started with https://github.com/Automattic/wp-calypso/pull/47258.
Depends on https://github.com/Automattic/wp-calypso/pull/47262
Verify calypso loads.

Checkout: Remove getEnabledPaymentMethods

---

apps/editing-toolkit/editing-toolkit-plugin/editor-site-launch/index.php
apps/editing-toolkit/editing-toolkit-plugin/editor-site-launch/src/constants.ts
apps/editing-toolkit/editing-toolkit-plugin/editor-site-launch/src/launch-steps/final-step/index.tsx
apps/editing-toolkit/editing-toolkit-plugin/editor-site-launch/src/launch-steps/plan-step/index.tsx
client/landing/gutenboarding/onboarding-block/plans/index.tsx
packages/data-stores/src/plans/index.ts
packages/data-stores/src/plans/resolvers.ts
packages/data-stores/src/plans/selectors.ts
packages/data-stores/src/plans/test/resolvers.ts
packages/plans-grid/src/plans-accordion/index.tsx
packages/plans-grid/src/plans-details/index.tsx
packages/plans-grid/src/plans-grid/index.tsx
packages/plans-grid/src/plans-table/index.tsx

Fixes a number of i18n issues with the plans grid. It was already localised in gutenboarding but should now also work in the launch flow in ETK. Also fixed bug where the currency of the plans for logged in users was being guessed rather than using the currency that's set for that specific user.
* Send current locale to client as `wpcomEditorSiteLaunch.locale` global in ETK
* Plans store requests plan data using the `?locale` query param
* Requests made in the ETK use `wpcomEditorSiteLaunch.locale` to set the locale param
* Requests make in gutenboarding use the `useI18n()` hook to set the locale param
* Plan store no longer uses the `apiFetch()` from `@wordpress/data-controls` to request data, that way it's not running through WP core specific middleware that adds an unused `?_locale` …

Gutenboarding: plans grid requests data in the correct locale

---

client/my-sites/backup/rewind-flow/index.tsx

* Switch to using `applySiteOffset` manually as is done elsewhere in Calypso (as opposed to using `useApplySiteOffset` or `withApplySiteOffset`), which does not require timezone info to be loaded before it is callable.
* If we're unable to retrieve timezone information, the UI defaults to displaying everything in UTC. We may address this in the future, but for now it's at least consistent with everything else in Calypso.
**TIP:** You can simulate a broken connection by re-writing API responses with a debugging proxy. Alternatively, try using Redux DevTools to find and re-send a modified version the action responsible for retrieving/storing site settings with null `gmt_offset` and `timezone` option fields.
1. In Calypso Blue or Green, select a site with Jetpack Backup and at least one …

Jetpack Cloud: Load Download/Restore Backup pages in UTC if timezone isn't available

---

packages/composite-checkout/tsconfig.json

Similar to #47140
* List monorepo dependencies as references in the `tsconfig.json` file of `@automattic/composite-checkout` package.
* In the project's root folder, run this command. It should run without errors:
`yarn clean:packages; ./node_modules/.bin/tsc --build packages/composite-checkout`

Add monorepo dependencies to tsconfig.json for Composite Checkout package

---

client/server/api/integration/index.js

Removing the `add-module-exports` Babel plugin in #47312 broke the integration tests that are run only nightly on `master`. This patch fixes them.
I added some eslint ignores to cover for the fact that assertions are done with the `.expect` method that the `supertest` library adds to the `superagent` request API. The `jest/expect-expect` rule doesn't recognize that.
Run `yarn test-integration` locally and verify it passes now.

Server API integration tests: use default property of require() result

---

client/components/jetpack/card/jetpack-free-card-i5/index.tsx
client/components/jetpack/card/jetpack-free-card-i5/style.scss
client/my-sites/plans-v2/products-grid-i5/index.tsx
client/my-sites/plans-v2/products-grid-i5/style.scss

This PR updates the styles of the Jetpack Free product card.
Fixes 1196341175636977-as-1199149328812615
- Run Calypso
- Visit `/jetpack/connect/plans/<site>`
- Check that the Jetpack Free card matches the mockups (see board)

Pricing page i5: update free card styles

---

client/components/notes-formatted-block/blocks.jsx
client/components/notes-formatted-block/index.jsx
client/components/notes-formatted-block/test/index.js

* Move the mapping for `FormattedBlock` types into `index.jsx`.
* Get rid of `getBlockByType`, which introduced side effects and is unnecessary with the above change.
Follows up on #45591.
* Make sure all unit tests pass.
* Follow instructions for #45591, copied here for convenience:
* For both Jetpack Cloud and Calypso, test that all behavior for Activity Log cards -- and specifically, all links -- matches the current production deployment. Here's a list of notable events that have their own cards:
* Post changes (created, modified, deleted)
* Comment changes (modified, deleted, etc.)
* People changes (added to/removed from your site's team, etc.)
* Plugin changes (installed, removed, etc.)
* Theme changes (for WordPress.com, but also for other sites like WordPress.org)

Activity Log: Refactor FormattedBlock to remove top-level side effects

---

packages/launch/src/focused-launch/summary/index.tsx

* If there is only one active step, that step shouldn't show a step index before its title
* This is achieved by making the `stepIndex` prop optional for each step component, and by adding some simple logic in the Summary view component
* Check out the branch on your machine and run `yarn && yarn start`
* Visit`calypso.localhost:3000/page/UNLAUNCHED_SITE_ID/home?flags=create/focused-launch-flow-calypso`
* By changing in code the values of `isSiteTitleStepVisible`, `hasPaidDomain` and `hasPaidPlan`, simulate all the combinations of these steps being in the "disabled" or in the "active" groups
* Make sure that the step index is _never_ shown for _disabled_ steps
* Make sure that the step index is only shown for _active_ steps when there are _at least_ 2 active steps
If there are at least 2 …

Focused Launch: hide step index in active steps if there are less than 2 active steps

---

packages/launch/src/focused-launch/summary/index.tsx

* When the site has already both a purchased domain and a purchased plan associated, the title/subtitle of the Summary view of the Focused Launch modal should change from the ones that normally shown
* Note that there is no need to store this option in the `automattic/launch` data store, as these conditions (site has purchased domain and plan) can't change while the user is interacting with the summary step
* Check out this branch on your machine and run `yarn && yarn start`
* Visit`calypso.localhost:3000/page/UNLAUNCHED_SITE_ID/home?flags=create/focused-launch-flow-calypso`
* By changing in code the values of `hasPaidDomain` and `hasPaidPlan`, simulate all the combinations (refreshing the page each time)
* is both variables are `true`, the title of the modal should read _"You're ready to …

Focused Launch: Show different title/subtitle if site has already a paid plan AND a paid domain

---

client/components/activity-card-list/style.scss

* We want to use the default style which is used in WordPress.com and in the Scan History section.
* Run this PR (you need to build Calypso Green).
* Visit `http://jetpack.cloud.localhost:3001/activity-log/:site` with a Jetpack Site.
* Make sure that the Pagination component looks like in the after capture.
Fixes 1164141197617539-as-1198830230995148

Jetpack Cloud: remove custom styles from Activity Log's pagination component

---

client/my-sites/activity/activity-log-item/index.jsx

* In the `ActivityLogItem` component, replace an undefined reference to `this.cancelBackupIntent` with the correct method, `this.cancelDownloadIntent`.
* Select a site in Calypso Blue that has Jetpack Backup.
* Open the Activity Log page.
* Find an activity that allows downloading or restoring from a backup.
* Click the three-dot menu button next to the activity and select 'Download backup.'
* When the backup details panel is displayed, click the Cancel button that appears at the bottom.
* Verify that the details panel is correctly dismissed.

Activity Log: Fix method typo to allow backup downloads to be canceled

---

client/my-sites/plans-v2/plans-filter-bar-i5/index.tsx
client/my-sites/plans-v2/plans-filter-bar-i5/style.scss
client/my-sites/plans-v2/plans-filter-bar/index.tsx
client/my-sites/plans-v2/use-detect-window-boundary.ts

This PR finalizes the correct scroll behavior for the CRO i5 pricing page.  For Jetpack cloud, this means that the top navigation bar (Masterbar is no longer sticky, and the Plans filter bar becomes sticky when it reaches the top of the viewport.  For Calypso, scroll behavior remains the same where the Masterbar remains sticky, and the Plans filter bar becomes sticky when it reaches the bottom of the masterbar.
- Refactored the `useDetectWindowBoundary()` hook.  Prior to refactor, there was a bug which is now resolved.
- Steps to produce the bug were:
- Go to https://cloud.jetpack.com/pricing
- Scroll down
- Click on a card
- Go back in history
- Scroll up. The filter bar remains stuck at the top, covering up the headline.
- Run both Calypso and Jetpack cloud …

CRO i5: Implement new scroll behavior

---

client/my-sites/plans-v2/more-info-box/index.tsx
client/my-sites/plans-v2/products-grid-i5/index.tsx

This PR updates the behaviour of the "Compare all product bundles" button.
Fixes 1196341175636977-as-1199175792010023
- Scroll to the "Need more info?" box
- Check that clicking on the button redirects you to https://jetpack.com/features/comparison/
- Make the the "Bundle comparison" section at the end of the page is not visible

Pricing page i5: update more info link

---

client/jetpack-cloud/sections/pricing/header/style.scss
client/my-sites/plans-v2/more-info-box/style.scss
client/my-sites/plans-v2/products-grid-i5/style.scss

This PR updates the style of pricing page i5 on mobile.
Fixes 1196341175636977-as-1199149328812622
- Run Calypso and Jetpack cloud
- Visit the pricing page on desktop and check that it still looks like staging
- Check the page on mobile against the mockups (see link in task)

Pricing page i5: tweak styles on mobile

---

client/components/jetpack/card/jetpack-product-card-i5/style.scss
client/jetpack-cloud/sections/pricing/header/index.tsx
client/lib/plans/features-list.js
client/lib/plans/plans-list.js
client/lib/products-values/translations.js
client/my-sites/plans-v2/constants.ts

This PR updates the copy of pricing page i5.
Fixes 1196341175636977-as-1199149328812578
- Iteration checks are not ideal, it's gonna be dealt with later in another PR
- Case of features is not consistent in the mockups, don't mind it
- Don't check the FAQ
- First feature in _Anti-spam_ should probably be "Always-on spam protection" to match the feature in _Security Daily_
- Check that the copy matches  the mockups (link attached in task). Specifically:
- Check the titles of the plans and products cards
- Check that _Search_ has been replaced by _Site Search_ …

Pricing page i5: update copy

---

client/jetpack-cloud/sections/pricing/header/style.scss
client/my-sites/plans-v2/more-info-box/index.tsx
client/my-sites/plans-v2/more-info-box/style.scss
client/my-sites/plans-v2/products-grid-i5/style.scss

This PR updates the style of pricing page i5 in Calypso.
Fixes 1196341175636977-as-1199156455145573
_Note: don't mind the copy and missing features_
- Run Calypso and Jetpack cloud
- Visit the pricing page in Jetpack cloud check that it still looks like staging (note that the _Compare all product bundles_ has been updated in Cloud as well)
- Check the page in Calypso against the mockups (see link in task)

Pricing page i5: tweak styles for Calypso

---

client/gutenberg/editor/calypsoify-iframe.tsx

Fix p1605290793102800-slack-CRNF6A9DX by sending users with a paid plan to Calypso launch flow.
1. Go to [/new](https://calypso.live/new?branch=fix/gutenboarding-launch-from-editor-on-paid-plan) 
2. Create a site with a paid plan and complete purchase
3. When clicking _Launch_ button from the top bar in editor, you should be redirected to `/start/launch-site` which is the default Launch flow in Calypso.

Gutenboarding: show Launch modal in editor just on free sites

---

client/my-sites/plans-v2/products-grid-i5/index.tsx
client/my-sites/plans-v2/types.ts

* Remove check that hides the Jetpack Free card.
* Run this PR (Calypso Blue and Green).
* Visit the Pricing page in `http://jetpack.cloud.localhost:3001/pricing`.
* Verify that the Jetpack Free card appears at the bottom of the page.
* Visit the Pricing/Plans page in `http://calypso.localhost:3000/plans/:site`.
* Verify that the Jetpack Free card doesn't appear at the bottom of the page.

Jetpack Cloud: make the Jetpack Free card appear on the Pricing page

---

desktop/package.json

This is part of the desktop client release process.

desktop: Bump version to 6.4.0

---

apps/editing-toolkit/editing-toolkit-plugin/coming-soon/coming-soon.php
apps/editing-toolkit/editing-toolkit-plugin/coming-soon/fallback-coming-soon-page.php

This PR:
- disables wp head/footer scripts
- cookie banner (we don't set any)
- og tags
for the Coming Soon page.
Create a new site at `/new?flags=coming-soon-v2`
Sandbox your new site
Checkout this branch and from `apps/editing-toolkit`, run `yarn dev --sync`
Visit the site in a logged-out state.
You **shouldn't** see the following:
The cookie banner. 
The og tags
Fixes: #46630

Coming Soon: disable wp head/footer scripts

---

client/my-sites/plans-v2/more-info-box/index.tsx
client/my-sites/plans-v2/more-info-box/style.scss

This PR opens the comparison table link in a new tab, and fixes some CSS on the same button.
Fixes 1196341175636977-as-1199186408618269
- Check that the button labelled _Compare all product bundles_ looks good (see captures) and opens a new tab
_Before_
_After_

Pricing page i5: open comparison table in new tab

---

client/my-sites/plans-v2/more-info-box/index.tsx

This PR adds a Tracks event to the button labelled _Compare all product bundles_ in pricing page i5.
Fixes 1196341175636977-as-1199149328812583
Event name is `calypso_plans_comparison_table_link_click`.
- Run Calypso and Jetpack cloud concurrently
- Enabled analytics debug mode (run `localStorage.setItem('debug', 'calypso:analytics');` in your browser's console) and refresh the page
- Check that the button labelled _Compare all product bundles_ tracks the event mentioned above
- Check that all interactions in the plans page in both Calypso and Jetpack cloud are still tracked

Pricing page i5: add Tracks event to the comparison CTA

---

client/lib/plans/features-list.js

Copy update in pricing page i5.
Fixes 1196341175636977-as-1199200712773362
- Check in the _Back UP Real-time_ card that the copy for the AL feature is: **Activity log: 1-year archive**
_Before_
_After_

Pricing page i5: update activity log feature copy

---

client/components/marked-lines/index.jsx

The MarkedLines component wouldn't properly render a line if the content was an empty string, this caused an issue where the line numbers were slightly misrepresented.
* Fix the MarkedLines component by replacing empty strings with a string with a single space in it.
* Create a Jurassic Ninja site at https://jurassic.ninja/create/?shortlived
* Create a file named test.php with the following content:
```
X5O!P%@AP[4\PZX54(P^)7CC)7}$EICAR-STANDARD-ANTIVIRUS-TEST-FILE!$H+H*
X5O!P%@AP[4\PZX54(P^)7CC)7}$EICAR-STANDARD-ANTIVIRUS-TEST-FILE!$H+H*
X5O!P%@AP[4\PZX54(P^)7CC)7}$EICAR-STANDARD-ANTIVIRUS-TEST-FILE!$H+H*
```
* Connect the site to Jetpack and purchase a plan that includes scan with credits
* Scan the site and verify that a threat was added.
* Go to …

Fix the Jetpack Scan file threat representation.

---

client/my-sites/plans-v2/plans-filter-bar-i5/index.tsx
client/my-sites/plans-v2/plans-filter-bar-i5/style.scss

This PR updates the "Save 20%" discount message on the Plans filter bar to no longer look like it is a green "button".
Fixes 1196341175636977-as-1199200712773353
- Verify that the 20% discount message no longer has the appearance of a "button" (See screenshots below)
**BEFORE**
Desktop
Mobile
**AFTER**
Desktop
Mobile

Pricing page i5: Update 20% discount message.

---

client/components/jetpack/card/jetpack-product-card-i5/assets/chevron.svg
client/components/jetpack/card/jetpack-product-card-i5/features.tsx
client/components/jetpack/card/jetpack-product-card-i5/index.tsx
client/components/jetpack/card/jetpack-product-card-i5/style.scss
client/my-sites/plans-v2/product-card-i5/index.tsx
client/my-sites/plans-v2/products-grid-i5/style.scss

This PR removes the "Show all features" toggle in the product cards, and align cards properly.
Fixes 1196341175636977-as-1199200712773351
- In the _Individual Products_ section, check that you see all features, that the "Show all features" toggles have been removed, and that cards of the same row all have the same height
- In the _Product Bundles_ section, check that the featured card is not flush with the other cards (see captures)
_Before_
_After_

Pricing page i5: remove feature toggle and align cards

---

client/blocks/credit-card-form/index.jsx
client/components/credit-card-form-fields/index.jsx
client/my-sites/purchases/payment-methods/index.tsx
packages/calypso-stripe/src/index.tsx

When creating a `StripeHookProvider` (used for displaying and submitting Stripe credit card fields and other Stripe operations), you can pass in a request to create a "setup intent". We need a setup intent if we want to submit a new credit card to Stripe without making a purchase (eg: when updating credit cards for an existing subscription). That request is sent to the `/me/stripe-configuration` HTTP API endpoint, but there are certain cases where this process could fail.
For example, if the customer's account does not have its email address verified, then the API endpoint will return the configuration without the setup intent included. There are other reasons why it might fail, but this is the easiest to reproduce. In such a case, the `StripeHookProvider` will unknowingly save the …

Purchases: Show Stripe configuration errors

---

apps/editing-toolkit/editing-toolkit-plugin/coming-soon/fallback-coming-soon-page.php

Let's make sure we don't allow caching for the Coming Soon pages. 
~~We'll also set the html and char types from bloginfo~~
Create a coming soon v2 site over at wordpress.com/new?flags=coming-soon-v2
I used Firefox, which seems to have a fairly aggressive caching approach.
With your new site in coming soon mode, open it in Firefox (logged out) and take a look at the network tab in the console for the HTML page.
Now run `yarn dev --sync` on this branch, and sandbox your new site.
Refresh and make sure you can see expiry headers (in the past so as to invalidate the cache)

Coming Soon: Set the headers to prevent caching for the different browsers.

---

client/state/data-layer/wpcom/read/lists/feeds/delete/index.js
client/state/data-layer/wpcom/read/lists/sites/delete/index.js
client/state/data-layer/wpcom/read/lists/tags/delete/index.js

Eagle-eyed @jsnmoon noticed that, in a few cases, we're returning the successNotice invocation instead of a function that invokes successNotice.
This PR adds the missing `() =>` where needed.
Try removing a feed, tag and site from an existing Reader list and ensure that a success notice appears.

Reader Lists: fix success notices in data layer

---

apps/editing-toolkit/editing-toolkit-plugin/full-site-editing-plugin.php
apps/editing-toolkit/editing-toolkit-plugin/readme.txt
apps/editing-toolkit/package.json

- ~~[ ] Persistent Launch Button: enable in all environments (#46817)~~ (was just a code comment change)
1. Load the diff (D52773-code) on your sandbox and confirm that the above changes work correctly
2. Test that the new version of the plugin doesn't break Atomic sites by following the instructions in the "Atomic Testing" section at PCYsg-ly5-p2.

Editing Toolkit: Update to 2.8.5

---

packages/domain-picker/src/domain-picker/style.scss

* Use the font-size variable instead of hardcoded value.
* Check out this branch on your machine and run `yarn && yarn start`;
* Open a new browser tab and navigate to http://calypso.localhost:3000/new/domains;
* Open another browser tab and navigate to https://wordpress.com/new/domains;
* Search for a domain name in both tabs;
* Inspect the "Recommended" badge's font-size;
* Verify that the font size of the domain picker suggestion item badge is the same on both pages.
Fixes #47232

Gutenboarding: Use font-size variable for domain picker suggestion item badge.

---

client/jetpack-connect/remote-credentials.js

* Check if there is a site in context before rendering the WordPress.org credentials form, otherwise, and error will be thrown in the console.
* Run this PR (Calypso Blue).
* Open the JavaScript console in DevTools.
* Visit `/jetpack/connect/install`.
* Make sure that there is no error thrown in the console (you will be redirected to `/jetpack/connect`).
Fixes 1164141197617539-as-1196859229849752

Jetpack Connect Install: show the WordPress.org credentials form only if there is a site in context

---

apps/editing-toolkit/editing-toolkit-plugin/editor-gutenboarding-launch/index.ts
client/gutenberg/editor/calypsoify-iframe.tsx

***Editing Toolkit release notes**: N/A (this PR is just cleaning up some unused code)
* Improve the fix added in https://github.com/Automattic/wp-calypso/pull/47421/files#diff-94cbcc079892f7f8fb113398707b6a9b6394766e051b1f2c28f98334ad25015fR375 to cover also the case when there is a plan value in store but that plan is free.
* Cleanup unused code and add comments.
1. Go to `/new`
2. Create a site with a paid plan and complete purchase
3. When clicking _Launch_ button from the top bar in editor, you should be redirected to `/start/launch-site` which is the default Launch flow in Calypso.
1. Go to `/new`
2. Create a site on a Free plan
3. Go to My Home and navigate to editor
4. Check if there is a plan object in store by executing `wp.data.select( 'automattic/site' ).getSite( …

Launch: use step-by-step launch flow after new onboarding with free plan

---

apps/editing-toolkit/editing-toolkit-plugin/editor-site-launch/src/launch-steps/plan-step/index.tsx
client/landing/gutenboarding/hooks/use-step-navigation.ts
client/landing/gutenboarding/onboarding-block/edit.tsx
client/landing/gutenboarding/onboarding-block/plans/index.tsx
packages/plans-grid/src/plans-grid/index.tsx

***Editing Toolkit release notes**: N/A (package API update)
- Rename `isExperimental` prop to `isAccordion` for `PlansGrid`.
- update usages in Step by Step launch and New Onboarding.
- cleanup `gutenboarding/feature-picker` flag from the New Onboarding.
* Go to `/new` and reach plans step or open [Plans modal](https://wordpress.com/new/plans-modal)
* Accordion view should be displayed, as in production

Plans Grid: enable accordion view as non-experimental

---

client/my-sites/pages/main.jsx

For users with a large number of hidden blogs (automatticians), the All Sites > Pages list is effectively broken. This passes the `site_visibilty: visible` query argument when in all sites mode ([like we do for All Sites > Posts](https://github.com/Automattic/wp-calypso/blob/master/client/my-sites/posts/main.jsx#L68)).
**To test:**
- with an a11n account, visit wordpress.com/pages
- verify that no pages are listed
- visit calypso.localhost:3000/pages
- verify that you can see visible pages

Pages: filter for blog visibility

---

client/me/purchases/purchase-item/index.jsx

This PR adds the renewal price to the purchase listing screen.
**Before**
**After**
* Visit the purchase listing screens at the site and account level. 
* Confirm you see a renewal price for products that have auto-renew enabled.
Fixes https://github.com/Automattic/wp-calypso/issues/46724

Purchases: Add price to subscription listing

---

apps/editing-toolkit/tsconfig.json
packages/format-currency/tsconfig.json

**Editing toolkit release notes**: This PR can be ignored
Similarly to what done in #47140 and #47308, add monorepo package references to tsconfig.json for the following packages:
- `@automattic/calypso-analytics`
- `@automattic/composite-checkout`
- `@automattic/domain-picker`
- `@automattic/format-currency`
- `@automattic/onboarding`
- `@automattic/launch`
- `@automattic/plans-grid`
- `@automattic/react-i18n`
Notes:
- The `@automattic/data-stores` package was already listed
- In order to be able to reference the `@automattic/format-currency` package, the `"composite": true` compiler option was added to the package's `tsconfig.json` file
Build the project and make sure that everything builds and works as expected:
* Run `yarn clean:packages; yarn && yarn start` in the project root
* In a …

Editing Toolkit: add monorepo package references to tsconfig.json

---

client/lib/abtest/active-tests.js

This PR updates the `jetpackConversionRateOptimization` config to display i5 in production.
Fixes 1196341175636977-as-1199178309577119
- Before deployment: code review
- After deployment: test page in production

Pricing page i5: update abtest config for production

---

packages/launch/src/focused-launch/summary/index.tsx
packages/onboarding/src/action-buttons/index.tsx
packages/onboarding/src/types.d.ts

Found a few more strings that weren't providing a text domain to the `__()` function.
The `react-i18n` package doesn't yet translate strings in the ETK environment, so switching to using `@wordpress/i18n` instead. We want strings in components to be reactive, so ideally component strings would use `react-i18n`, but we're not quite there yet (see #47352)
* Strings in `@automattic/launch` provide a text domain (that can be swapped for a real value at build time)
* Strings in `@automattic/onboarding` provide a text domain
* Switch strings in `@automattic/onboarding` from using `react-i18n` to `@wordpress/i18n`
* Define the `__i18n_text_domain__` constant which is provided at build time
* Run launch and onboarding flows and they shouldn't crash and strings should still be visible.

Gutenboarding: strings in onboarding and launch packages should be translatable

---

apps/editing-toolkit/editing-toolkit-plugin/editor-gutenboarding-launch/index.ts
client/gutenberg/editor/calypsoify-iframe.tsx

***Editing Toolkit release notes**: New Onboarding Launch: open launch modal only for free sites
* Replace the check for Free plan in Calypso with a similar check in ET plugin.
* Pass `isGutenboarding` through the iframe correctly everytime.
* Create a site using `/new` on a Free plan
* Sandbox the site and sync ET plugin
* Clicking Launch in editor should open step-by-step launch modal
* Repeat the process but this time select a paid plan and complete purchase
* Clicking Launch in editor should redirect to Calypso default launch flow
Fixes #47504 (solution B)

Launch: check if site is on Free plan after rendering editor Launch button

---

client/signup/main.jsx
client/signup/processing-screen/index.jsx

The BizX question appeared at the end of other flows, confusing results. We would like to display it at the end of the onboarding flow only so that we can optimize that flow based on the survey results.
There's no question set up at the moment so in order to make sure this code works, you'll need to set a breakpoint.
1. In a new incognito window, open /start/user in English
2. Make sure the gdpr cookie is set to yes ( sensitive_pixel_option = yes )
3. Place the breakpoint on line 74 from the sources tab to `signup/processing-screen/index.jsx` ( <- cmd+p and copy/paste this)
4. Sign up, the breakpoint should be triggered after plan selection
5. Repeat steps 1-3 with "/start/business/user" instead, that would be the "business flow"
6. Sign up, the breakpoint should not be triggered
7. …

Update the signup hotjar code to not be used outside of onboarding flow

---

client/jetpack-cloud/index.js

When visiting cloud.jetpack.com, users that have only one site end up seeing a blank screen. This happens because the `siteSelection` controller redirects these types of users to `cloud.jetpack.com/:site` which is a path that doesn't exist in the cloud.
* Remove the `siteSelection` controller from the `/` route. This will make the app rely on the primary site first, and then use the `siteSelection` controller if necessary (if there is no primary site).
**Prerequisite: a WordPress.com account with only one site.**
* Run this PR locally (you need Calypso Green).
* Visit cloud.jetpack.com.
* Verify that you are redirected to `cloud.jetpack.com/:site` and that you see a blank screen.
* Visit `jetpack.cloud.localhost:3001` (the base route of your local Calypso Green env).
* Verify that you are …

Jetpack Cloud: fix broken landing UX for accounts with one site

---

client/layout/index.jsx

@evilluendas pointed out that there's the Help icon during the P2 signup. Since clicking that icon might take the user away from the P2 signup flow, we are going to hide it for the P2 signup flow.
Navigate to `/start/p2` as logged in and make sure you don't see the Help icon in the bottom right corner of your screen. Try using incognito window and do the same. Last but not least, please verify the help icon is not hidden for any other signup flow than the P2 one and is not hidden anywhere else. The code also should make sense.

P2 signup: remove help icon

---

client/blocks/upsell-nudge/style.scss

* The vertical alignment was a teensy bit off, so I'm nudging the button down 1px.
* There was also a visual regression with compact dismissible upsell nudges, so I've updated the CSS to fix that.
See #47161
Before | After
---- | -------
| <img width="311" alt="Screen Shot 2020-11-13 at 3 17 50 PM" src="https://user-images.githubusercontent.com/2124984/99117391-9e52a980-25c3-11eb-9fc3-aca510575c32.png"> | <img width="314" alt="Screen Shot 2020-11-13 at 2 40 55 PM" src="https://user-images.githubusercontent.com/2124984/99117399-a1e63080-25c3-11eb-9965-41aa64c2ba45.png"> |
| Dismissable variant |  After |
| <img width="343" alt="Screen Shot 2020-11-13 at 3 23 20 PM" src="https://user-images.githubusercontent.com/2124984/99117699-2c2e9480-25c4-11eb-9c71-da6746c735d0.png"> | <img width="332" …

Upsell Nudge: Fix vertical alignment of button on compact variant

---

client/jetpack-cloud/index.js

The app throws an error when it hit the line because `context` is not defined. This breaks the `Switch to User (in Jetpack Cloud)` tool.
* Remove the `context` variable from the `debug` call site.
* Code review.

Jetpack Cloud: fix OAuthOverride controller

---

client/components/jetpack/card/jetpack-free-card-alt/index.tsx
client/components/jetpack/card/jetpack-free-card-i5/index.tsx
client/components/jetpack/card/jetpack-free-card/index.tsx

* add `data-e2e-product-slug` to all iterations of "Free" plan cards
* Go through Jetpack connection
* Once redirected to the plans page, make sure that `data-e2e-product-slug="free"` attribute is present in the Free plan card.

Jetpack Plans: Add data attributes to "Free" plan card

---

client/my-sites/plans-v2/test/utils.js

Some failing tests prevented from deploying #47532, which needed to be online quickly. This PR adds the tests back and mock the modules that caused them to fail.
Check that the tests pass in the CI

Pricing page: add temporarily disabled tests back

---

apps/editing-toolkit/editing-toolkit-plugin/editor-site-launch/src/launch-steps/domain-step/index.tsx
apps/editing-toolkit/editing-toolkit-plugin/editor-site-launch/src/launch-steps/final-step/index.tsx
packages/data-stores/src/site/actions.ts
packages/data-stores/src/site/reducer.ts
packages/data-stores/src/site/resolvers.ts
packages/data-stores/src/site/selectors.ts
packages/data-stores/src/site/test/resolvers.ts
packages/data-stores/src/site/types.ts
packages/domain-picker/src/domain-picker/index.tsx
packages/domain-picker/src/domain-picker/suggestion-item-placeholder.tsx
packages/launch/src/focused-launch/summary/index.tsx
packages/launch/src/hooks/use-domain-search.ts
packages/launch/src/hooks/use-domain-suggestion.ts
packages/launch/src/hooks/use-site.ts
packages/launch/src/hooks/use-title.ts
packages/launch/src/utils.ts

* This PR changes the domain picker a bit to show an accurate loading state in the focused launch. 
I realize it's a backlog issue, but the loading was terribly janky that it might make the upcoming CfT look bad.
**Before:**
https://cloudup.com/c5uPXDg7x6l
**After:**
1. In apps/editing-toolkit run `yarn dev --sync`.
2. Sandbox YOUR_SITE.wordpress.com.
3. Visit https://YOUR_SITE.wordpress.com/wp-admin/post-new.php.
4. In console, type `wp.data.dispatch('automattic/launch' ).openFocusedLaunch()`.
5. You should see loading similar to the one in the GIF above.
Fixes https://github.com/Automattic/wp-calypso/issues/47410

Focused Launch: Pixel perfect loading state

---

client/jetpack-connect/controller.js
client/jetpack-connect/store-footer.tsx
client/my-sites/plans-features-main/jetpack-faq.jsx
client/my-sites/plans-v2/iterations.ts

This PR fixes the FAQ being show twice in the connection flow.
- Run both Calypso and Jetpack cloud concurrently
- In Calypso, visit `/plans/:site` and `/jetpack/connect/store`, and check that you see the FAQ once
- In Jetpack cloud, visit `/pricing`, and check that you see the FAQ once

Pricing page i5: prevent duplicate FAQ in connection flow

---

client/state/selectors/get-editor-close-config.js

This is a very small PR to resolve #47054 making it slightly clearer how a user can get to their dashboard.
* Change the default back button label text in the editor from "My Home" to "Dashboard".
* Go to create a new site from calypso.localhost:3000/new and once you land in the editor, click on the W icon in the top left. The back button should now say "Dashboard" instead of "My Home"
* Go to the dashboard / Calypso and select Pages and a page of your site. Make sure that the back button still says View Pages.
Note: you don't need to sandbox the editing toolkit plugin for this change, as the text is generated on the Calypso side.
Fixes #47054

Rename close label from My Home to Dashboard

---

client/reader/sidebar/reader-sidebar-lists/index.jsx
client/reader/sidebar/reader-sidebar-lists/list-item.jsx
client/state/reader/lists/selectors.js
client/state/reader/lists/test/selectors.js

Reader Lists are currently sorted by slug in the sidebar. This worked fine until the title of lists could be edited. Now that functionality has been added, this PR switches to sort by title instead (case-insensitive).
(Note: ideally, it'd be good if the edited list name scrolls into view. For example, if I have 30 lists and rename "Aaaa" to "Zzzz" it should scroll me to the bottom. I've noted this and will pick it up in a future PR.)
Update the title of an existing list. Make sure the sidebar position is updated correctly to reflect the updated title.

Reader Lists: order lists by title in sidebar

---

client/lib/i18n-utils/test/utils.js
client/lib/i18n-utils/utils.js
client/package.json

Reverts localizeUrl to its state prior to the move to i18n-utils package.
This is an intermediate PR, to make deploying the changes needed in #47492 a bit easier.
* Follow #46998

Revert calypso localizeUrl's move to i18n-utils package

---

packages/i18n-utils/README.md
packages/i18n-utils/package.json
packages/i18n-utils/src/index.ts
packages/i18n-utils/src/locale-context.tsx
packages/i18n-utils/src/test/locale-context.tsx
yarn.lock

Split out from #47446 to make the changes easier to review
* Add `<LocaleProvider>` to `@automattic/i18n-utils`
* Add `useLocale()` and `withLocale()` to consume the locale supplied by `<LocaleProvider>`
The `react-i18n` library currently supplies the current locale slug, however that package is trying to do things in a way that will work for any Gutenberg user, and there is no standard way to access the current locale slug in Gutenberg/core WP.
Having an i18n util that's Calypso specific allows us to do things we know will work in an a8c specific environment.
The locale slug defaults to `'en'` because that seems to be the current practice in Calypso, and this is an a8c specific utility. Another option was to error if `useLocale()` or `withLocale()` is used when `<LocaleProvider>` hasn't …

Add `<LocaleProvider>` and `useLocale()` to `@automattic/i18n-utils`

---

client/my-sites/sidebar-unified/style.scss

* Add a missing variable for selected menu text
The text color for selected menu items varies between color schemes. We need to account for this in the nav unification styles. 
I noticed this one as I was working on some further adjustments to Aquatic in Calypso in parallel to porting Aquatic to wp-admin in https://github.com/Automattic/jetpack/pull/17828
|Before|After|
|-|-|
|<img width="272" alt="Screenshot 2020-11-19 at 12 28 23" src="https://user-images.githubusercontent.com/1562646/99662244-486b7f00-2a65-11eb-9684-40b34dcfd47f.png">|<img width="273" alt="Screenshot 2020-11-19 at 12 40 40" src="https://user-images.githubusercontent.com/1562646/99662253-4b666f80-2a65-11eb-977d-7f43cb267778.png">|
|Before|After|
|-|-|
|<img width="272" alt="Screenshot 2020-11-19 at 12 52 12" …

Nav Unification: add missing variable for selected menu text

---

packages/calypso-color-schemes/src/shared/color-schemes/_aquatic.scss

* update Aquatic color scheme to be compatible with nav unification
While working on porting Aquatic to wp-admin in Automattic/jetpack#17828, I noticed we will need a few more changes to the color scheme in Calypso to work with Nav Unification.
|Before|After|
|-|-|
|<img width="463" alt="Screenshot 2020-11-19 at 13 37 50" src="https://user-images.githubusercontent.com/1562646/99667274-74d6c980-2a6c-11eb-8b67-3bad6ca91e1a.png">|<img width="450" alt="Screenshot 2020-11-19 at 13 24 04" src="https://user-images.githubusercontent.com/1562646/99666668-92effa00-2a6b-11eb-95d0-9757339a8af7.png">|
* Visit the Calypso live link below
* Navigate to /me/account and select the color scheme
* Add `?flags=nav-unification` to the URL
* Compare to `?flags=nav-unification` in production

Nav unification: update Aquatic color scheme to be compatible with nav unification

---

client/blocks/inline-help/contextual-help.js
client/blocks/inline-help/inline-help-search-results.jsx

This PR adds contextual inline help for the site-level purchase screens.
**Before**
**After**
* Visit the site and account level purchase screens and confirm that they both have the same contextual help links when you expand the help.
Fixes: https://github.com/Automattic/wp-calypso/issues/47359

Purchases: Add contextual inline help for site-level purchases

---

test/e2e/specs/wp-gutenboarding-spec.js

This REALLY reverts the failing E2E tests.

Revert "Simulate E2E failure (part of onboarding process) (#47588)"

---

client/my-sites/plans-v2/plans-filter-bar-i5/index.tsx
client/my-sites/plans-v2/plans-filter-bar-i5/style.scss
client/my-sites/plans-v2/product-grid/utils.ts

This PR fixes the plans-filter-bar to stick at top:0 when scrolling.  Prior to this, the plans-filter-bar was sticking 47px down the page.  (See "Before" screenshots)
- Run both Calypso and Jetpack cloud concurrently
- In Calypso, visit `/jetpack/connect/store`, scroll down the page and verify that the plans-filter-bar sticks to the top:0 when it reaches top:0.
- In Calypso, visit `/plans/:site`, scroll down the page and verify that the plans-filter-bar sticks just below the blue masterbar (top: 47px).
- In Jetpack cloud, visit `/pricing`, and verify that the plans-filter-bar sticks to the top:0 when it reaches top:0.
- Verify the scroll behavior works correctly on mobile viewport sizes also.
**BEFORE**
(on `/jetpack/connect/store`)
**AFTER**
( on …

Pricing page i5: Fix sticky filter-bar on connection flow pricing page 

---

client/blocks/inline-help/index.jsx
client/blocks/inline-help/style.scss
client/my-sites/customer-home/cards/features/help-search/index.jsx
client/my-sites/customer-home/cards/features/help-search/style.scss

* Use the non-border version of the help/info icon for a cleaner look. Also update the same icon on My Home for consistency.
* Use a border color change rather than a box-shadow to avoid the form focus overhanging the container.
**Before** | **After**
--------|-----------
| <img width="349" alt="Screen Shot 2020-11-17 at 3 28 43 PM" src="https://user-images.githubusercontent.com/2124984/99444116-c3a82600-28e9-11eb-804a-5bf0c9ba112a.png"> | <img width="349" alt="Screen Shot 2020-11-18 at 11 06 36 AM" src="https://user-images.githubusercontent.com/2124984/99555380-3d91eb00-298e-11eb-9702-b1a41d0bc1ae.png"> |
| <img width="372" alt="Screen Shot 2020-11-17 at 3 17 45 PM" src="https://user-images.githubusercontent.com/2124984/99444154-d3c00580-28e9-11eb-85b9-3e94c4108adf.png"> | <img …

Inline Help: Update icon, fix focus state outline

---

config/horizon.json
config/production.json
config/stage.json

* After the integration between Premium blocks and editor checkout has been tested internally (p58i-9C7-p2) and is currently covered by E2E tests (https://github.com/Automattic/wp-calypso/pull/47231), we can proceed to enable `"post-editor/checkout-overlay"` feature flag in all environments.

Editor Checkout: enable in all environments

---

client/me/purchases/manage-purchase/index.jsx
client/me/purchases/manage-purchase/purchase-meta.jsx

We're currently using the user level purchase query component in ManagePurchase in both the site-level and account-level contexts, which for users with a lot of sites is extremely slow.
* Conditionally use the site level query component for loading purchases. The first 4 commits handle this; the rest are refactoring `PurchaseMeta` to a functional component.
We need to test for two things: that performance improves in the site-level context, and that the behavior is preserved in the account-level context.
Site-level:
- Navigate to `/purchases/subscriptions/:site_url`.
- Wait for your list of purchases to load.
- Select a purchase to navigate to the Purchase Settings screen, and check that this screen loads correctly.
- In the network tab, check that you do not see an api request to …

Manage Purchase: use site level query component in site level context

---

client/my-sites/checkout/composite-checkout/components/payment-method-step.tsx
client/my-sites/checkout/composite-checkout/composite-checkout.tsx
client/my-sites/checkout/composite-checkout/lib/does-purchase-have-full-credits.ts
client/my-sites/checkout/composite-checkout/lib/filter-appropriate-payment-methods.ts
client/my-sites/checkout/composite-checkout/lib/get-contact-details-type.ts
client/my-sites/checkout/composite-checkout/lib/translate-cart.ts
client/my-sites/checkout/composite-checkout/payment-method-processors.js
client/my-sites/checkout/composite-checkout/payment-methods/full-credits.js
client/my-sites/checkout/composite-checkout/test/composite-checkout.js
client/my-sites/checkout/composite-checkout/use-create-payment-methods.js
packages/shopping-cart/src/empty-carts.ts
packages/shopping-cart/src/shopping-cart-endpoint.ts
packages/shopping-cart/test/shopping-cart-endpoint.js

The shopping-cart endpoint, prior to D52836-code, will report the total without _any_ credits applied if the number of credits equals or exceeds the cart subtotal. With the above diff, those inconsistencies are no longer present.
Because of this, we can remove some of the hacks that were in place on the front-end (many of which were added in https://github.com/Automattic/wp-calypso/pull/47305). This PR does that. We also will need to more clearly differentiate between "free" and "full credits" because now with a 0 total, full credits will also be free. Because we want to always display full credits differently, this PR modifies the logic where free purchases are concerned and makes it more explicit.
Fixes 56-gh-Automattic/payments-shilling
Before, with full credits (enough to completely …

Checkout: fix full credits payment method behavior

---

client/landing/gutenboarding/components/domain-picker-button/index.tsx
client/landing/gutenboarding/components/header/index.tsx
client/landing/gutenboarding/components/locale-context/index.tsx
client/landing/gutenboarding/components/window-locale-effect-manager/index.tsx
client/landing/gutenboarding/hooks/use-on-login.ts
client/landing/gutenboarding/hooks/use-on-signup.ts
client/landing/gutenboarding/hooks/use-selected-plan.ts
client/landing/gutenboarding/hooks/use-step-navigation.ts
client/landing/gutenboarding/onboarding-block/domains/index.tsx
client/landing/gutenboarding/onboarding-block/plans/index.tsx
client/landing/gutenboarding/onboarding-block/style-preview/preview.tsx
package.json

Split from #47446
* Switch gutenboarding from getting the locale slug from `react-i18n` to `i18n-utils`
For the reasons outlined in #47566 the locale slug shouldn't come from `react-i18n`. This PR migrates gutenboarding away from that package.
Test that all the gutenboarding locale features are working just like before
* The UI at `/new` should be in the current users language
* `/new/fr` should show the UI in french
* The plans grid and domain picker should be translated correctly
* Using an incognito window, go throught the flow starting from `/new/fr` and create a new user. The language of the new account should be set to French

Update Gutenboarding to use new <LocaleProvider>

---

client/my-sites/site-settings/delete-site-warning-dialog/index.jsx

"Premium Upgrades" is outdated and confusing, since we have a premium plan. This updates the site deletion modal to use "Paid Upgrades" instead.
ref: c/TN2RtIjw-tr/406-replace-premium-upgrades-with-paid-upgrades
**To test:**
- On a site with an active subscription, visit Manage > Settings
- Click "Delete your site permanently"
- Verify that the modal title and text says "paid upgrades"

Site Deletion: use "paid upgrades" instead of "premium upgrades"

---

client/components/section-nav/index.jsx
client/components/section-nav/style.scss
client/my-sites/pages/controller.js
client/my-sites/pages/index.js
client/my-sites/pages/main.jsx
client/my-sites/pages/page-list.jsx
client/my-sites/post-type-filter/author-segmented.jsx
client/my-sites/post-type-filter/index.jsx
client/my-sites/post-type-filter/style.scss
client/my-sites/posts/main.jsx
client/my-sites/posts/style.scss

This adds an author filter to the Pages and All Sites > Pages lists, and makes use of the `PostTypeFilter` component for post status filtering and searching.
**To test:**
- visit a site's page list (`/pages/{siteSlug}`) on a site with multiple authors
- verify that all published pages for the site are shown by default
- verify that the post status tabs, author filter, and search functionality work as expected
- visit the all sites page list
- verify that all published pages for all of the user's sites are shown by default
- verify that the post status tabs, author filter, and search functionality work as expected

Pages: add author filter
