Automattic/wp-calypso

- config/stage.json
> Reader: Turn on recs for staging

- README.md
> Added space in README.md

- client/components/post-schedule/README.md
> post-schedule: fix README header

- docs/guide/tech-behind-calypso.md
Various grammar and spelling fixes
> Documentation: Tech Behind Calypso

- assets/stylesheets/README.md
- docs/coding-guidelines/css.md
Just having a quick look over the docs and noticed this minor inconsistency.
> SASS => Sass

- client/components/infinite-list/README.md
> DevDocs: Fix link to infinite scroll mixin

- docs/coding-guidelines/css.md
> Docs: typo on CSS coding guidelines

- client/lib/menu-data/test/test-menu-data.js
This PR replaces lodash-deep's `deepGet` with lodash's `_.get`.
> Use lodash.get instead of deepGet.

- client/accept-invite/actions.js
- client/accept-invite/logged-in-accept/index.jsx
- client/accept-invite/logged-out-invite/signup-form.jsx
- client/accept-invite/main.jsx
*  pull `add/accept-invite-for-logged-in`
* invite a user to a blog and get the key from the email
* go to `calypso.dev:3000/accept-invite/_blog_id_/_invite_key`
* log in
* accept the invite and confirm that everything flows
Closes #673
> People: Invites: Implement accept invite for logged in flow

- docs/coding-guidelines/javascript.md
I think it would be better to understand with this fix
> Docs: change variable name with function name in the function section

- docs/coding-guidelines/css.md
> Docs: fixing .is-modifyer -> .is-modifier

- client/devdocs/controller.js
Fixes this problem in main devdocs list:
> Devdocs: remove "noSidebar" state.

- assets/stylesheets/sections/_billing-history.scss
> Billing receipt: fix layout padding.

- client/devdocs/controller.js
> Devdocs: declare layouts with and without sidebar.

- assets/stylesheets/sections/_sites.scss
- client/my-sites/sites/sites.jsx
> Sites: use <Main> and cleanup classNames.

- shared/components/gridicon/docs/example.jsx
- shared/components/gridicon/index.jsx
This PR adds the following icons:
- book
- briefcase
- institution
- speaker
> Framework: Adding 4 new gridicons: book, briefcase, institution, speaker

- client/auth/auth-code-button.jsx
- client/auth/login.jsx
- client/auth/style.scss
- client/lib/auth-code-request-store/Makefile
- client/lib/auth-code-request-store/README.md
- client/lib/auth-code-request-store/actions.js
- client/lib/auth-code-request-store/constants.js
- client/lib/auth-code-request-store/index.js
- client/lib/auth-code-request-store/test/auth-code-request-store-test.js
- config/empty-secrets.json
- server/api/oauth.js
When the user is prompted for a 2nd factor the form will now display a link that allows them to request an auth code via text message.
Follows the same UX as the Android and iOS apps.
> Desktop: Request 2nd factor auth code as text message.

- client/my-sites/pages/page-list.jsx
> Pages: fix no-results message when you search.

- client/components/plans/plan-actions/index.jsx
- client/components/plans/plan-actions/style.scss
- client/my-sites/upgrades/cart/cart-item.jsx
- client/my-sites/upgrades/checkout/free-trial-confirmation-box.js
- client/my-sites/upgrades/checkout/pay-button.jsx
- client/my-sites/upgrades/checkout/secure-payment-form.jsx
- client/my-sites/upgrades/checkout/supporting-text.jsx
- client/my-sites/upgrades/checkout/thank-you.jsx
- client/my-sites/upgrades/checkout/transaction-steps-mixin.jsx
- config/development.json
Free trials, now without a CC and with some updated designs.
> Upgrades: No Credit Card Free Trials

- client/components/plans/plan-actions/index.jsx
Used same buttons in signup as in the plans page erroneously.
> Free Trials Signup: Fix signup

- client/lib/post-normalizer/index.js
See http://calypso.localhost:3000/read/post/id/3393579/6085 for a test.
> Reader: Add 8tracks.com to the embed whitelist.

- client/auth/auth-code-button.jsx
- client/components/email-verification/email-verification-notice.jsx
- client/components/notice/index.jsx
- client/components/upgrades/google-apps/dialog/index.jsx
- client/me/profile-links-add-other/index.jsx
- client/me/profile-links-add-wordpress/index.jsx
- client/me/profile-links/index.jsx
- client/me/security-2fa-backup-codes-list/index.jsx
- client/me/security-2fa-backup-codes-prompt/index.jsx
- client/me/security-2fa-code-prompt/index.jsx
- client/me/security-2fa-enable/index.jsx
- client/me/security-2fa-sms-settings/index.jsx
- client/me/security-checkup/manage-contact.jsx
- client/my-sites/media-library/content.jsx
- client/my-sites/people/people-notices/index.jsx
- client/my-sites/plugins/plugin-meta/index.jsx
- client/my-sites/upgrades/domain-management/add-google-apps/add-email-addresses-card.jsx
- client/notices/delete-site-notices.jsx
- client/notices/notices-list.jsx
- client/post-editor/editor-location/index.jsx
- client/post-editor/media-modal/gallery/preview.jsx
- client/post-editor/post-editor.jsx
- client/reader/following-edit/index.jsx
- client/signup/locale-suggestions/index.jsx
This is a part of big notice refactor series:
#888 #1094 
This prop is changing in order to make it more clear what is going on
> Notices: change prop from onClick to onDismissClick

- client/signup/steps/dss/index.jsx
Fixes #1323
Load http://calypso.localhost:3000/start/dss and verify that searching for `wedding` and `WEDDING` return the same results.
> Signup: DSS: Lowercase all search terms

- client/signup/steps/dss/style.scss
> Signup: DSS: Keep DSS theme previews onscreen at narrow screen widths.

- client/lib/abtest/active-tests.js
- client/signup/config/flows.js
This AB test compares DSS against the default `main` flow, with the latest improvements in curated images, improved stats collecting, related terms, and general performance.
This PR relies on #811 being merged first.
> Signup: DSS: Add DSS AB test i2.

- client/lib/abtest/active-tests.js
- client/signup/config/flows.js
Reverts Automattic/wp-calypso#1219
> Revert "Signup: DSS: Add DSS AB test i2."

- client/my-sites/plugins/plugin-remove-button/index.jsx
> Plugins remove: remove ; fixes typo

- client/lib/post-normalizer/index.js
- client/lib/post-normalizer/test/post-normalizer-test.js
Vevo doesn't always work, and spotify is a bit weird sandboxed.
> Reader: Add Spotify to the embed whitelist, trust it

- assets/stylesheets/sections/_devdocs.scss
- client/devdocs/main.jsx
> Devdocs: use Cards for search results, cut down on css.

- client/my-sites/upgrades/checkout/paypal-payment-box.jsx
- client/my-sites/upgrades/checkout/secure-payment-form.jsx
Whew. I just started to work.
Reverts Automattic/wp-calypso#1418
> Revert "Checkout: Panic mode disable credit cards"

- docs/code-reviews.md
Changed the typo of 'mindet' to 'mindset'.
> Fixed a typo

- client/lib/signup/Makefile
- client/signup/Makefile
Sometimes the signup tests timeout in Circle CI. I don't have time to investigate why right now, so bumping the timeout for now.
cc @nb
> Signup: Increase the timeout for signup tests

- client/components/section-header/docs/example.jsx
Refer issue : 461
Card component in SectionHeader DevDocs example was removed. 
cc : @apeatling, @mtias , @alisterscott  for code review.
> Devdocs/Components : Removed Card Component from SectionHeader Example

- docs/troubleshooting.md
> Additional troubleshooting tips for `ulimit` on versions of OS X

- client/components/domains/domain-registration-suggestion/index.jsx
- client/components/domains/domain-suggestion-flag/index.jsx
- client/components/domains/domain-suggestion/style.scss
- client/components/flag/README.md
- client/components/flag/index.jsx
- Add a flag to be shown for new TLDs
- Refactor the current Flag component, and set icon to not be required
> Domains: Add flag to domain register suggestions

- client/components/sites-dropdown/index.jsx
- client/my-sites/site/index.jsx
> Framework: fix site errors in devdocs with empty cache.

- assets/stylesheets/sections/_menus.scss
- client/my-sites/menus/menu-editable-item.jsx
Rebased version of https://github.com/Automattic/wp-calypso/pull/729
Props @sendilkumarn
> Menus: Update edit form to use Gridicons

- client/components/domains/domain-suggestion-flag/index.jsx
- client/lib/followers/store.js
- client/lib/users/store.js
> Fix usage of string.endsWith, which IE11 hates

- client/my-sites/plugins/plugins-browser/index.jsx
Plugin browser is disabled when manage is on and enabled when is off!
> Plugins-browser: Fix manage detection

- client/my-sites/invites/invite-message/index.jsx
__How to test__
* Decline a notice
* Assert the notice is dismissible
> People: Invites: Fix dismiss decline notice

- server/pages/index.jade
Added smiley stylesheet.
https://github.com/Automattic/wp-calypso/issues/710
> Reader: Fix emoji support is missing

- shared/components/gridicon/docs/example.jsx
- shared/components/gridicon/index.jsx
- Status
- Add Image
- Thumbs up
> Framework: Adding 3 new gridicons: status, add image, thumbs up

- client/signup/steps/dss/index.jsx
- client/signup/steps/dss/screenshot.jsx
- client/signup/steps/dss/theme-thumbnail.jsx
Go through the DSS flow at http://calypso.localhost:3000/start/dss and be sure no errors appear (does not fix #1890 but this is one piece of the fix).
> Signup: DSS: Prevent unnecessary preview fetching

- client/lib/abtest/active-tests.js
- client/signup/config/flows.js
- client/signup/steps/email-signup-form/index.jsx
This removes the AB test introduced in #1446.
> Signup: remove Nux Trampoline AB test i2

- client/lib/abtest/active-tests.js
- client/signup/config/flows.js
> Signup: Disable DSS i2 test

- client/lib/abtest/active-tests.js
- client/signup/config/flows.js
> Signup: Disable verticals test i2

- client/signup/steps/survey/index.jsx
> Signup: Remove remaining reference to verticals survey abtest

- index.js
> [Linting]: fix space warnings in index

- config/wpcalypso.json
Soon after merging this, we should should merge phabricator diff D779
Also, #1877 should be merged before merging this.
cc: @lezama
> People: Enabling the new accept invite flow in wpcalypso environment.

- client/analytics/index.js
- client/reader/comments/form.jsx
- client/reader/controller.js
- client/reader/full-post/index.jsx
- client/reader/like-button/index.jsx
- client/reader/list-gap/index.jsx
- client/reader/list-stream/index.jsx
- client/reader/sidebar/sidebar.jsx
- client/reader/tag-stream/index.jsx
Adds in a blog_id where relevant, and some additional properties where relevant.
> Reader: Fixup lots of tracks stats.

- client/my-sites/stats/nux/insights.jsx
Found this unused bit of code while investigating #247 (unfortunately wasn't able to find an easy fix for that issue though).  cc @timmyc
> Stats: Remove some dead code

- client/my-sites/stats/follows/index.jsx
This PR moves `/client/my-sites/stats/follows.jsx` to `/client/my-sites/stats/follows/index.js`. No CSS was moved for this PR as this component doesn't seem to have anything custom.
> Stats: Update Follows component directory

- shared/components/themes-list/index.jsx
- shared/lib/themes/constants.js
> Themes: clean up an unused constant

- client/my-sites/site/index.jsx
Add attribute title with site name to link in site-picker
> Site Picker: add title attribute (fixes #6)

- config/stage.json
It doesn't seem to have caused problems in horizon, but there's very little data there so I wanted to give it a shot in staging.
> Enable perfmon in staging

- client/me/account/index.jsx
> Me: fix react unique key warning in console

- client/components/button/style.scss
- client/my-sites/current-site/index.jsx
- client/my-sites/current-site/style.scss
Uses `Button compact borderless` to estandardice.
> Sidebar: use <Button> for "switch site" action.

- client/components/progress-indicator/index.jsx
- client/components/progress-indicator/style.scss
- client/my-sites/site-indicator/site-indicator.jsx
- client/my-sites/site-indicator/style.scss
> Site Indicator: use Gridicon and other improvements.

- client/post-editor/drafts-button/index.jsx
- client/post-editor/drafts-button/style.scss
- client/post-editor/post-editor.jsx
- client/post-editor/style.scss
Simplify styling, better alignment of items.
Before:
After:
cc @aduth @kellychoffman @folletto
> Editor: use <Button borderless> for sidebar-header items.

- client/boot/index.js
- client/lib/olark/index.js
Reverts Automattic/wp-calypso#1720
> Revert "Help: Track page views while users are chatting with olark operators."

- client/components/site-selector/index.jsx
> Sites: allow searching hidden sites when only a few visible ones.

- client/lib/mixins/i18n/index.js
Just a little test patch for #2395
> Add in some stats for tracking translations, ignore uncacheable options

- client/components/comment-button/docs/example.jsx
- client/components/follow-button/docs/example.jsx
- client/components/like-button/docs/example.jsx
- client/components/post-schedule/docs/example.jsx
- client/components/sites-dropdown/docs/example.jsx
- client/components/theme/docs/example.jsx
- client/devdocs/controller.js
- client/devdocs/design/app-components.jsx
- client/devdocs/design/index.jsx
- client/devdocs/index.js
- client/devdocs/sidebar.jsx
- client/lib/sites-list/docs/example.jsx
- Adds a new section to the sidebar "app components".
- Moves components that rely on application state outside of UI components.
- Fixes missing links to permalinks.
> Devdocs: separate UI components from App components

- config/development.json
- config/horizon.json
- config/production.json
- config/stage.json
- config/wpcalypso.json
- server/pages/index.js
Enabled in all environments except stage and production.
> SSR: Enable server side rendering based on feature flag

- client/my-sites/posts/post-list.jsx
> Posts: only display one post placeholder instead of arbitrary number.

- client/my-sites/upgrades/domain-management/email-forwarding/email-forwarding-details.jsx
Improve wording on email forwarding page, fixes #2492.
> Domain Management: minor wording improvement props @designsimply

- client/lib/translator-jumpstart/index.js
This aims to be fix for #2455 (where `[object Object]` is printed in the title) without reverting to the old behavior where a `textOnly` property in the `translate()` call is needed to indicate that the string value needs to be returned.
Originally (pre #2457 which brings back the old behavior), we modified the `ReactElement.prototype.toString` in order to have control over how the object is converted to a string. This hack ceased to work when we switched to React 0.14 (because ReactElements [became plain old objects](https://github.com/facebook/react/commit/750338ef4794af164d452d7560cb97a558c56d3c#diff-55695b0adf2e9955d50160f0aa0cd234L235)). The quick fix to bring back the `textOnly` property only works for the `translate()` calls that still have the `textOnly` attribute from the time …
> Translator Jumpstart: reinstate toString overriding

- client/reader/full-post/index.jsx
Adds a `blog-$blog_ID` and a `feed-$feed_ID` class to the full post container. This will let us target styles at specific feeds and blogs.
> Reader: Add a class based on the feed and blog id.

- server/pages/index.js
Try memoizing the costly renderToString call.
> Themes: Cache renderToString output & add stats

- client/lib/upgrades/actions/cart.js
1. Add anything to the cart.
2. Try to remove.
There should be no error. It should work properly for renewals and new purchases.
> Checkout: Fix remove from cart broken by #2608

- client/components/data/query-posts/README.md
> QueryPosts: fix typo in readme.

- config/stage.json
Once we have some WPT stats, we'll enable it in production.
> Themes: Enable server-side-rendering in staging

- config/desktop-mac-app-store.json
- config/desktop.json
We use `127.0.0.1`, not `localhost`.
> Update hostname for desktop config to IP

- client/my-sites/upgrades/cart/cart-item.jsx
> Checkout: shows website URL instead of theme slug as item description

- client/components/pulsing-dot/index.jsx
- client/layout/index.jsx
- client/state/ui/reducer.js
- server/bundler/loader.js
- Expose chunk name in ui state.
- Track waiting event for each chunk.
> Framework: track stats on chunk loading.

- client/my-sites/site-settings/form-analytics.jsx
- client/my-sites/site-settings/form-discussion.jsx
- client/my-sites/site-settings/form-writing.jsx
- client/my-sites/site-settings/style.scss
This PR is a continuation of #1920 - and should finish off updating Site Settings to use the shared form components instead of straight html tags.
Closes #88
CC: @dmsnell for review ( I'm off until Dec. 28, please review after you enjoy your holidays. see you then! )
> Settings: use form components

- client/reader/comments/index.jsx
Also push new tracks events for clicking on reply links and canceling a reply.
Fixes #2669
> Reader: Add a stat when a user clicks on a comment author's link.

- client/my-sites/themes/main.jsx
No visual changes. To test -- verify that the Theme Showcase still works (especially when logged-out).
> Themes: Determine if isLoggedOut from current-user Redux store

- client/reader/controller.js
- client/reader/following-stream/_style.scss
- client/reader/following-stream/index.jsx
- client/reader/following-stream/post.jsx
Also use this to style afk posts in the automattic team stream in a new way that reduces their visual importance. Scope it to the a8c stream to prevent the tag override from leaking out.
> Reader: Add classes to post cards that reflect the tags for that post.

- client/reader/following-edit/index.jsx
Also show the loading cards when searching while we're still loading.
Fixes #2707
> Reader: Fix indexOf call to use search, which takes a regex.

- config/production.json
Enable server-side-rendering in production.
> SSR: Enable in production

- assets/stylesheets/_components.scss
- client/components/app-promo/README.md
- client/components/app-promo/index.jsx
- client/components/app-promo/style.scss
- client/post-editor/editor-drawer/index.jsx
- config/desktop.json
- config/development.json
- config/production.json
- config/wpcalypso.json
Create a promo spot for the Desktop app, initial display is within the Editor
> Add Promo for Desktop

- client/auth/login.jsx
Make sure there is a different link to sign up depending on config value.
Part of #291.
I'm not aware how to test it. I should open different sign up flow for desktop up.
@scruffian could you review this one?
> NUX: Update signup url in login form

- client/components/domains/register-domain-step/index.jsx
Fix unmatched propType 
To test:
1. Go to domains/add/site
2. Search for something
There shoudln't be any warnings
> Domains: fix warnings

- client/my-sites/invites/controller.js
> Invites: Do not display "verify email" notice

- client/components/like-button/_style.scss
- client/components/like-button/icons.jsx
- client/reader/comments/style.scss
Updating the like-button component to use Gridicons rather than its own SVG elements.
> Reader: Update like button to use Gridicons

- assets/stylesheets/layout/_detail-page.scss
Sometimes the action bar gets a little “overloaded” and wraps strangely. This PR fixes that.
`master`
`fix/2799-full-post-top-bar`
#2799
> Reader: Fix full post actionbar overflow

- client/lib/sites-list/list.js
> Guard against missing recent-sites key.

- client/components/site-selector/index.jsx
- client/lib/sites-list/list.js
- Show AllSites at the top always cc @rickybanister @folletto 
- Clean up code verbosity.
- Bail early when constructing recent sites array if sites list lacks data.
cc @rralian I think this should fix the error you were seeing.
> Sites: update site selector to es6 and general cleanup

- client/reader/following-stream/_style.scss
These were missed when we added the afk style.
cc @gwwar as she noticed it
> Reader: Add in hover and selected styles for afk posts

- client/reader/full-post/index.jsx
Fixes #2676
See the linked bug report for a good test case.
> Reader: Remove the size requirement on featured images in full post view

- client/components/theme/docs/example.jsx
Incorrect prop format was breaking the whole devdocs/app-components page.
Change props to new theme object format.
> DevDocs: Fix theme example

- client/my-sites/upgrades/domain-management/edit/registered-domain.jsx
- client/my-sites/upgrades/index.js
- config/production.json
- config/stage.json
- config/wpcalypso.json
This removes the domains transfer feature flag and enables it everywhere
> Domains: Transfer: Remove domain transfer flag and deploy everywhere

- client/my-sites/plugins/main.jsx
Fixes #414 
After: 
cc: @MichaelArestad
> Plugins: Reword Jetpack Plugins to Plugins

- client/lib/user/user.js
Reverts Automattic/wp-calypso#2730
> Revert "User: Fix bug where fetch error prevents any further attempts"

- docs/guide/hello-world.md
Spelling mistake fixed - `asyncronously` > `asynchronously`
> Docs: Fix typo in guide/hello-world.md

- client/components/site-selector/index.jsx
- client/lib/sites-list/list.js
Makes the display of valid data more robust when localStorage gets cleared.
> SiteSelector: use preferences data component to trigger re-renders.

- client/me/account-password/index.jsx
- client/me/account/index.jsx
- client/me/application-password-item/index.jsx
- client/me/application-passwords/index.jsx
- client/me/billing-history/billing-history-table.jsx
- client/me/connected-applications/index.jsx
- client/me/credit-cards/credit-card-delete.jsx
- client/me/notification-settings/comment-settings/index.jsx
- client/me/notification-settings/wpcom-settings/index.jsx
- client/me/purchases/payment/edit-payment-method/credit-card.jsx
- client/me/purchases/payment/edit-payment-method/paypal.jsx
- client/me/security-2fa-disable/index.jsx
- client/me/security-2fa-setup/index.jsx
- client/my-sites/upgrades/domain-management/controller.jsx
- client/my-sites/upgrades/domain-management/dns/dns-add-new.jsx
- client/my-sites/upgrades/domain-management/dns/dns-list.jsx
- client/my-sites/upgrades/domain-management/edit-contact-info/form-card.jsx
- client/my-sites/upgrades/domain-management/email-forwarding/email-forwarding-add-new.jsx
- client/my-sites/upgrades/domain-management/email-forwarding/email-forwarding-item.jsx
- client/my-sites/upgrades/domain-management/name-servers/index.jsx
This PR continues work from #1496 
Here, simple use cases of notice calls are converted to redux store in 
- `/me`
- `/domain-management`
This PR requires #2009 for the notices to disappear upon route change
Just click around and see if notices in changed files appear properly
> Notices Reduxification: Simple cases in /domain-management and /me

- client/components/button-group/makefile
- client/components/button-group/test/test.js
This PR adds a small test suite to `button-group`.
How to test
=========
1. In your CLI of choice, go to `/client/components/button-group` and run `make test`
> Framework: Small test suit for button-group

- client/components/site-selector/index.jsx
- config/development.json
- config/horizon.json
- config/wpcalypso.json
Enable recent-sites group in all environments.
> Sites: enable site-groups in all environments.

- client/my-sites/sidebar/sidebar.jsx
We have been encouraged to fix linting issues in separate PRs, so here's a PR that just fixes lint :)
To test, ensure that the sidebar on My Sites still loads.
> Linting: Fix sidebar lint

- client/components/plans/plan-discount-message/index.jsx
- client/lib/abtest/active-tests.js
Adds a test to validate the social proof teaser at the top of the Premium Plan on plans page
> adds the social proof test on the premium plan teaser

- docs/coding-guidelines/javascript.md
We find we rather like them to return inside case statements for reducers. /cc @ockham
> Documentation: soften opinions about switch statements

- client/lib/importer/actions.js
- client/lib/importer/common.js
- client/lib/importer/store.js
- client/my-sites/importer/importing-pane.jsx
This takes possible progress values from the server and renders them in
the progress bar. It additionally writes a message below the progress
bar to indicate how many resources are still importing to give a better
indication to the user that things are still moving.
Currently this depends on the server reporting that progress. You can **test** by applying D971 to your sandbox, sandboxing `public-api.wordpress.com`, and then conducting an import.
Without the patch the imports should only show a spinner in Calypso. With both patches applied, you should see a progress bar and get updates. A message should appear below the progress bar to indicate how many resources still need to be imported.
Because attachments take significantly longer to import than posts, pages, and comments, I have …
> Importer: Report progress

- docs/shrinkwrap.md
Matching shrinkwrap readme for #2947
> Framework: add readme to show how to use shrinkwrap

- client/components/feature-example/makefile
- client/components/feature-example/test/test.js
This PR adds a small test suite to `feature-example`.
How to test
=========
1. In your CLI of choice, go to `/client/components/feature-example` and run `make test`
> Feature-example: Add tests

- client/components/site-selector/docs/example.jsx
- client/components/site-selector/index.jsx
- client/devdocs/design/app-components.jsx
- client/my-sites/index.js
- client/my-sites/site/index.jsx
Add a site selector example to app components devdocs page.
Testing path: http://calypso.localhost:3000/devdocs/app-components/site-selector
> Devdocs: add site selector example

- client/reader/full-post/_style.scss
Adding some margin to accommodate the follow button on full post.
> Reader: Fix long site title overflow issue on full post

- client/lib/network-connection/index.js
- client/state/application/Makefile
- client/state/application/actions.js
- client/state/application/test/actions.js
- client/state/application/test/reducer.js
Add tests for https://github.com/Automattic/wp-calypso/pull/2587
> Add tests for redux global state

- client/lib/menu-data/menu-data.js
This PR doesn't affect the menu-data behavior. It just improves the jsdoc documentation, applies es6 in some part of the code, and in general adds some minor code improvements.
> menu-data: Improve jsdoc, es6ify, tidying

- client/my-sites/navigation/navigation.jsx
* minor jsdoc improvements
* es6ify
> my-sites: tidyng my-sites/navigation

- client/components/domains/domain-registration-suggestion/index.jsx
- client/lib/abtest/active-tests.js
This reverts commit 2904b80814415686944dc01583e8b2fe60c8b4a8.
The hypothesis was not validated, hence the revert.
cc @lucasartoni
> Revert "Domains: A/B test for using Select as CTA during domain registration"

- client/components/post-list-fetcher/index.jsx
- client/lib/posts/actions.js
Reverts Automattic/wp-calypso#2965
> Revert "Posts: ensure a fetch on mounting for post-list-fetcher"

- docs/shrinkwrap.md
`dependences` → `dependencies`
> Docs: Fix a typo

- client/reader/list-stream/index.jsx
- client/reader/stream-header/style.scss
Replaces the usage of the author, which always seemed odd.
> Reader: Use the description for a list, if provided.

- client/my-sites/plugins/plugins-browser/index.jsx
> Plugins: fix case of section header text.

- client/my-sites/importer/author-mapping-item.jsx
- client/my-sites/importer/style.scss
- client/my-sites/importer/uploading-pane.jsx
> Importer: replace noticon with gridicon

- client/state/sites/reducer.js
- client/state/sites/test/reducer.js
Navigate to My Sites, then click on themes. The themes page should render normally
> Framework: themes expected decorated sites in the redux tree

- config/desktop.json
- config/horizon.json
- config/production.json
- config/stage.json
- config/wpcalypso.json
> need to add these configs or else we get errors in the environments

- client/my-sites/stats/geochart/index.jsx
A quick es6 update to the component that wraps the Google Geo Viz in stats.
__To Test__
Open a site stats page and verify the Google Map Viz renders properly.
Resize your browser window and verify it looks fine at the different breakpoint widths.
> Stats: Update geochart to es6 syntax.

- client/components/site-selector/style.scss
- client/my-sites/all-sites-icon/index.jsx
- client/my-sites/all-sites-icon/package.json
- client/my-sites/all-sites-icon/style.scss
Trying:
cc @jasmussen @folletto
> All Sites: update icon composition

- client/components/plans/plan-price/index.jsx
- client/lib/abtest/active-tests.js
> removes the plans free vs adv test

- client/components/button-group/docs/example.jsx
Before:
After:
cc @rickybanister
> Devdocs: clean up example of ButtonGroup with compact variations.

- client/components/plans/plan-discount-message/index.jsx
- client/lib/abtest/active-tests.js
removes the social proof test on plans
> Plans: remove the social proof test

- client/state/notices/README.md
In my notices reduxification efforts, I missed few doc items
CC @ebinnion
> Notices Reduxification: missing docs

- client/components/section-nav/docs/example.jsx
- client/devdocs/design/index.jsx
Improve searching of some components by adding keywords, and clean the weird gaps a bit.
> Devdocs: remove random margins from components, add search keywords.

- client/lib/menu-data/menu-data.js
Mainly this PR replaces functions by arrow functions which allows getting rid of use of bind.
Run the application and then test the menus page for a site: `http://calypso.localhost:3000/menus/<your-testing-site>`
> menu-data: ES6ify. Tidying code.

- client/lib/abtest/active-tests.js
- client/signup/config/flows.js
- client/signup/test/lib/abtest/index.js
> Revert "A/B test for a free by default signup flow"

- client/me/help/help-contact/index.jsx
In general chat messages shouldn't be sent/received while on the contact form without the chatbox being inlined. This pull request adds event handlers that track the occurrence of these messages and adds information about the state of olark.
Testing this is tricky since the issue that this pull request aims to track is not generally reproducible.
> Help: Track eroneous sent/received chat messages

- config/horizon.json
Just like the title says.
cc: @roundhill @lancewillett @dllh @apeatling
> Enable the importer on horizon

- client/my-sites/themes/controller.js
Fixes #3469
For now, remove the element check around the render that was causing
search results not to show.
> Themes: fix theme search

- ISSUE_TEMPLATE.md
* More friendly
* Moved the wordier bits to the bottom
* Made it clear you can ignore the comments (they won't appear) — or delete them
* Added help section for making screenshots
> Improve the issue template, see #3392

- npm-shrinkwrap.json
- package.json
Take two at updating wpcom-unpublished - this time with more clingwrap :+1:
> Framework: Updating wpcom-unpublished.

- client/my-sites/upgrades/checkout/domain-details-form.jsx
Go try to purchase a domain (from any starting point), you should be able to see the final checkout screen (cc).
> Fix domain checkout

- client/me/help/help-contact/index.jsx
This pull request adds more details to the tracks ping added in #3238 and also adds a second ping with olark details.
I add a second tracks ping with details received directly from the olark api. if `olark_is_conversing` appears to be `false` then the problem is somewhere in the olark api and most likely can only be resolved by clearing cookies.
Just like in the previous pull request the changes here aren't really testable.
> Help: extend erroneous chatbox display pings

- client/lib/posts/utils.js
- client/my-sites/post/post-image/style.scss
- client/my-sites/posts/post.jsx
Filter based on the attributes on the dom node instead of trying to load them and then filtering.
> Posts: Don't wait for images to load when picking a feature

- client/reader/comments/index.jsx
Size is a number. No functional changes.
> Reader: Fix usage of Gridicon

- client/reader/full-post/_style.scss
The side class changed to alignleft and alignright for recent articles
> Reader: Fix styles for Discover sidenotes

- client/lib/recommended-sites-store/store.js
- client/lib/recommended-sites-store/test/store-tests.js
Resolves immutable.js deprecation warning.
Closes #3493
> Use count property instead of length

- client/my-sites/site/index.jsx
- client/my-sites/site/style.scss
> Site: add external icon to "Edit icon" link.

- client/components/site-selector/index.jsx
- client/lib/sites-list/list.js
- client/my-sites/current-site/index.jsx
- client/my-sites/site/index.jsx
Let's test recent sites in isolation for a little longer as it just hit desktop app.
> Framework: disable starred sites while we keep testing recent sites.

- docs/shrinkwrap.md
This updates our shrinkwrap doc to clarify different use cases.
cc @timmyc
> Framework: update shrinkwrap docs to be clearer

- client/my-sites/current-site/style.scss
- client/my-sites/site/index.jsx
- client/my-sites/site/style.scss
> Site: add "lock" badge to private sites.

- client/my-sites/site/index.jsx
- client/my-sites/site/style.scss
> Reader: fix display of site lock badge in header.

- client/my-sites/upgrades/checkout-thank-you/business-plan-details.jsx
- client/my-sites/upgrades/checkout-thank-you/chargeback-details.jsx
- client/my-sites/upgrades/checkout-thank-you/domain-mapping-details.jsx
- client/my-sites/upgrades/checkout-thank-you/domain-registration-details.jsx
- client/my-sites/upgrades/checkout-thank-you/generic-details.jsx
- client/my-sites/upgrades/checkout-thank-you/google-apps-details.jsx
- client/my-sites/upgrades/checkout-thank-you/header/index.jsx
- client/my-sites/upgrades/checkout-thank-you/header/style.scss
- client/my-sites/upgrades/checkout-thank-you/index.jsx
- client/my-sites/upgrades/checkout-thank-you/jetpack-business-plan-details.js
- client/my-sites/upgrades/checkout-thank-you/jetpack-premium-plan-details.jsx
- client/my-sites/upgrades/checkout-thank-you/premium-plan-details.jsx
- client/my-sites/upgrades/checkout-thank-you/purchase-detail.jsx
- client/my-sites/upgrades/checkout-thank-you/site-redirect-details.jsx
- client/my-sites/upgrades/checkout-thank-you/style.scss
This pull request adds the designs from #2484. We will do the copy changes in separate PRs
The original mockups look like this.
1. Run `git checkout update/checkout-thank-you-page-redesign` and start your server
2. Purchase the a product and assert that the thank you page:
3. Has the correct placeholders on mobile
3. Has the correct placeholders on desktop
3. Has the correct design on mobile
3. Has the correct design on desktop
It will be worth purchasing a few different products to see how the page looks with different content.
> Checkout: Thank you: Redesign

- client/my-sites/site/style.scss
- client/reader/following-stream/_style.scss
The new font stack looks a bit worse with the italics.
> Site: remove italics for URL line.

- client/my-sites/sites/sites.jsx
> Sites: update path for "/sites" url so that people land in stats.

- config/horizon.json
- config/wpcalypso.json
Enable `SyncHandler` in horizon.
> SyncHandler: enable in horizon

- npm-shrinkwrap.json
- package.json
Version bumping ( again - hopefully not again for sometime ) wpcom-unpublished and wpcom-xhr-request using the excellent new shrinkwrap docs.
/cc @gwwar
> Framework: Update wpcom-unpublished and wpcom-xhr-request

- client/lib/abtest/active-tests.js
- client/signup/config/flows.js
- client/signup/config/step-components.js
- client/signup/config/steps.js
The test was enabled in #3284.
> Signup: Disable Alt Theme Selection Test i1

- assets/stylesheets/layout/_main.scss
- server/pages/index.jade
So it won't get in the way of SEO for server-side rendered pages.
/cc @folletto for styling
Closes #3346
> Framework: Move noscript tag to the very bottom

- client/lib/domains/index.js
Fixes Google Apps offering.
1. Have an existing site
2. Add a domain to cart
3. You should the Google Apps offering
@klimeryk
> Google Apps: Fix Google Apps Offering

- docs/install.md
- package.json
This adds an npm entry to the engine section so we know what version our build machines are using.
cc @blowery @belcherj
> Build: update npm requirements

- client/components/purchase-detail/README.md
- client/components/purchase-detail/index.jsx
- client/components/purchase-detail/style.scss
- client/my-sites/upgrades/checkout-thank-you/domain-registration-details.jsx
- client/my-sites/upgrades/checkout-thank-you/google-apps-details.jsx
- client/my-sites/upgrades/checkout-thank-you/index.jsx
- client/my-sites/upgrades/checkout-thank-you/style.scss
This PR updates the thank you page that users see when purchasing a domain registration to use the copy from [this document](https://docs.google.com/document/d/1GmR-hw3gv63Lj8VT7hXirgneRHQ-Awyy19x2X3zLOA8/edit#).
**Testing**
- With a new site that does not yet have any custom domains, visit `/domains/add/:site` and purchase a domain without Google Apps.
- Assert that the header on the thank you page reads "Your new domain [example.com] is being set up. Your site is doing somersaults in excitement!"
- Assert that two `PurchaseDetail` components are [rendered below](https://cloudup.com/cbtjzfYRDnk)
- Visit `/domains/add/:site` for the same site and purchase another domain, with Google Apps this time.
- Assert that four `PurchaseDetail` components are rendered below …
> Checkout: Thank You: Update page for domain registrations

- client/lib/user/support-user-interop.js
- client/lib/user/user.js
- client/support/support-user/index.jsx
This change fixes the issue in #3587 that broke staging.
Commit d4118c0 contains the original PR content, while the changes in 066e263 solve the issue that broke staging.
To confirm that this fixes the issue, test with both:
```
make run
```
and
```
DISABLE_FEATURES=support-user make run
```
cc @dllh @gwwar
> Support User: Refactor to remove singleton class, use individual fn exports instead (fixed)

- client/reader/feed-header/index.jsx
It's generally more up to date than the feedbag subs count.
> Reader: Prefer the subscriber count on the site info.

- client/my-sites/upgrades/domain-management/name-servers/custom-nameservers-form.jsx
- client/my-sites/upgrades/domain-management/name-servers/index.jsx
- client/my-sites/upgrades/domain-management/style.scss
Fixes #2468
/cc @aidvu @umurkontaci
> Domains: Add loading placeholders for Nameservers page

- .gitignore
Missed in #3793, caught by @aduth
> Framework: Ignore eslintcache

- config/stage.json
No testing, just enables this in staging. It's already in production.
cc: @roundhill
> Enable the importer in staging

- Dockerfile
> Framework: Copy npmrc after Node extraction step

- README.md
Per [current data recommendations](https://github.com/Automattic/wp-calypso/blob/master/docs/our-approach-to-data.md#current-recommendations) this PR updates the project's main readme as follows:
```diff
- built with ... Flux ... and many other wonderful libraries
+ built with ... Redux ... and many other wonderful libraries
```
> Readme: Remove Flux, add Redux

- client/lib/user/test/utils.js
- client/test/quick-mock.js
- client/test/use-mockery.js
Tests should pass. No functional changes to the site.
> Framework: Make quick-mocks async, add async support to use-mockery

- client/components/tinymce/plugins/media/plugin.jsx
Fixes #1040 
This pull request seeks to offer a potential solution to the flickering which occurs between the time that an image finishes uploading and the persisted image is shown in the editor. The flicker is caused by a switch in the image source between the temporary copy known to the browser, and the final version of the image that is saved to the server.
__Implementation notes:__
This is a rather naive solution, which simply preloads the image before making the swap. It has a few notable downsides:
- There can still be a very brief flash of white before the image is rerendered, though the duration is much more instant than previous
- There is no effect if the browser has disabled cache for any reason (e.g. developer tools disabled caches)
- Post saving will continue to be blocked …
> Editor: Preload uploaded images before swapping

- client/lib/post-normalizer/index.js
To test, try http://calypso.localhost:3000/tag/chris-hedges vs prod. The post with the title `Chris Hedges: Open-pit Uranium Mining Spreading Nuclear Contaminants in Sacrifice Zones` should now have a featured image
> Reader: Try loading images sans-querystring when we can't make them safe otherwise

- docs/shrinkwrap.md
Tweak the summary of the shrinkwrapping process a bit.
- Avoid stating a specific command that we don't use, which might mislead people into running `npm shrinkwrap` directly
- Provide a summary of the approach we've taken and the reasons for it
Open to suggestions for better / more concise wording as this is based on my non-expert reading of the document.
> Documentation: Update shrinkwrapping summary

- test/README.md
Updates paths to configuration file and some explanation that we have now 2 json file configs.
Adds some examples how to run test runner.
/cc @blowery @mtias
> Documentation: Update test folder REAMDE file

- client/me/controller.js
- client/me/index.js
- client/me/paths.js
- client/me/purchases/index.js
- client/sections.js
This almost halves the size of the "me" bundle.
> Framework: separate "purchases" into its own bundle

- client/reader/controller.js
Should be helpful for analytics.
> Reader: Add a track when loading following

- client/lib/abtest/active-tests.js
- client/lib/abtest/index.js
- client/reader/following-stream/_style.scss
- client/reader/following-stream/post.jsx
Adds in a new A/B test that can try out various limits on featured image height. Doesn't affect embeds, as they're much harder to work with and predict with max heights like these.
Also changes A/B test a bit to allow folks that are already in an A/B test to continue being in that test, even if they're not eligible. This lets us debug A/B tests that most devs are not eligible for.
> Reader: A/B various height limits on featured images.

- client/me/sidebar/index.jsx
Enables preloading functionality for all the sub-sections of "Me".
> Preload "Me" sections from the sidebar.

- client/my-sites/sidebar/sidebar.jsx
Clean up custom markup and add preloading functionality.
> Convert "My Sites" sidebar links to sidebar-item and add preloading.

- client/components/payment-logo/docs/example.jsx
- client/components/select-dropdown/docs/example.jsx
- client/components/spinner/docs/example.jsx
A few of the component headers on the DevDocs page were missing the link elements.
> Fixed devdocs inconsistencies per issue #4079

- client/my-sites/invites/invite-accept/index.jsx
Closes #4065.
After being pinged me a few times due to confusing invalid invite error messages, it's time that we make the messages reflect why the invite is invalid, instead of returning a generic message.
To test:
- Checkout `update/invite-accept-errors` branch
- Proxy and send an invite to yourself
- Unproxy and try to accept the invite
- Send an invite to a test user
- In the invite URL, change the blog ID
- On a blog that you're already a member of, send an (editor | author | admin) invite to an email you control
- Open that invite while logged in
- Follow the same step for a site you're already following with a follower invite
> Invites: Improve invalid invite messages

- client/my-sites/sidebar/sidebar.jsx
Regression introduced in #4071
> Domains: Restore domains' 'Add' button

- client/lib/abtest/active-tests.js
- client/reader/controller.js
- client/reader/following-stream/post.jsx
- client/reader/index.js
And spin this up as a new abtest name. Didn't re-use the name because I want folks in the previous test to be in this test too, potentially.
> Reader: Init ABTest earlier, before we fire page load events

- client/components/tinymce/plugins/wpcom-view/views.js
- client/components/tinymce/plugins/wpcom-view/views/contact-form/index.jsx
- client/components/tinymce/plugins/wpcom-view/views/contact-form/preview-fields.jsx
- client/components/tinymce/plugins/wpcom-view/views/contact-form/preview-fieldset.jsx
- client/components/tinymce/plugins/wpcom-view/views/contact-form/preview-legend.jsx
- client/components/tinymce/plugins/wpcom-view/views/contact-form/preview-required.jsx
- public/tinymce/skins/wordpress/wp-content.css
> Editor: Contact Form Preview

- client/reader/share/index.jsx
Some sites have admin in a spot that doesn't correspond directly with site URL. 
Fixes the bug reported by @m in #2619
> Reader: Fix sharing to some Jetpack sites

- client/components/card/compact.jsx
- client/components/section-header/index.jsx
- client/my-sites/themes/sheet.jsx
- client/my-sites/themes/style.scss
- client/state/themes/actions.js
- client/state/themes/theme-details/reducer.js
- client/state/themes/theme-details/test/reducer.js
Addresses #3163
Work in progess.
@mendezcode: This would be a good task for you to continue.
> Themes: Add feature list to theme sheets

- assets/stylesheets/_components.scss
- client/mailing-lists/main.jsx
- client/mailing-lists/style.scss
The current un/subscribe screen for logged out users is in need of a little love:
This PR cleans things up a bit to make it more focused:
> Mailing List: Update un/subscribe screen

- client/lib/domains/email-forwarding/index.js
- client/my-sites/upgrades/domain-management/email-forwarding/email-forwarding-add-new.jsx
- client/my-sites/upgrades/domain-management/style.scss
- Add inline validators
- Refactor Email Forwarding component to use form state
> Domain Management: Improve email forwarding validation

- client/lib/domains/assembler.js
- client/lib/domains/test/assembler.js
- client/my-sites/upgrades/domain-management/edit/mapped-domain.jsx
- client/my-sites/upgrades/domain-management/edit/registered-domain.jsx
- client/my-sites/upgrades/domain-management/edit/site-redirect.jsx
- Change expiry format for moment.js
- Use moment.js object to display date
Needs D1382-code.
> Domain Management: Use moment.js to display dates

- docs/coding-guidelines/javascript.md
> Docs: Coding guidelines: JS: Multiple minor fixes

- client/components/select-dropdown/index.jsx
> SelectedDropdown: Fix usage of find

- client/lib/abtest/active-tests.js
- client/signup/config/flows.js
- client/signup/config/steps.js
- client/signup/steps/survey/index.jsx
Work in Progress. Needs to avoid stepping on other tests in the same way as #3367
Also needs actual theme choices added (the ones in there now are just an example).
> Signup: Add Business Vertical Themes A/B Test i1

- client/my-sites/plugins-wpcom/README.md
> Create intro README for wpcom plugin panel

- client/sections.js
Reverts Automattic/wp-calypso#4290
Should fix wpcalypso.
/cc @blowery
> Revert "Fix desktop app"

- client/lib/mixins/i18n/README.md
* fixed link for “interpolate-components module”
* fixed minor typos
> Docs: Coding guidelines: I18n: minor tweaks

- docs/components.md
Consistent formatting FTW! 8-)
> Docs: Coding guidelines: Components: minor tweaks

- client/my-sites/upgrade-nudge/docs/example.jsx
> UpgradeNudge: fix devdocs permalink.

- npm-shrinkwrap.json
> Framework: Regenerate shrink-wrap for unpublished ansi-styles

- server/bundler/loader.js
#4148 was merged before I could fix nitpicks hinted by @ockham due to personal reasons. This PR fixes that.
> Fix nitpicks in bundler/loader hinted by @ockham in #4148 PR

- client/components/embed-container/index.jsx
- client/lib/post-normalizer/index.js
- client/reader/following-stream/post.jsx
- client/reader/full-post/index.jsx
Load up the instagram platform when we see an instagram post and let it process the content when it loads.
> Reader: Make instagram embeds work.

- client/components/domains/map-domain-step/index.jsx
- client/components/domains/map-domain/index.jsx
- client/components/domains/register-domain-step/index.jsx
- client/my-sites/upgrades/controller.jsx
- client/signup/steps/domains/index.jsx
Pre-fill the domain mapping input field with the last searched domain.
This should be tested in both the signup flow and in an already existing site, on the Domains page.
Fixes #2442
/cc @aidvu @umurkontaci
> Signup: Domains: Prefill domain mapping with the last searched domain

- npm-shrinkwrap.json
- package.json
Reported by @gwwar since the update to component-tip@3
> Framework: Upgrade to tip 3.0.1 to fix bad positions.

- client/components/embed-container/index.jsx
- client/lib/load-script/index.js
- client/lib/post-normalizer/index.js
- client/lib/post-normalizer/test/index.js
- client/reader/following-stream/post.jsx
- client/reader/full-post/_style.scss
This teaches the normalizer and the embed container how to process twitter and facebook "embeds" which are not normal iframe oembeds.
To test, try http://calypso.localhost:3000/read/feeds/25320833
> Reader: Detect and load platform for twitter, facebook, tumblr

- assets/stylesheets/_components.scss
- assets/stylesheets/shared/functions/_z-index.scss
- client/guidestours/README.md
- client/guidestours/config.js
- client/guidestours/index.js
- client/guidestours/style.scss
- client/layout/index.jsx
- client/layout/masterbar/item.jsx
- client/layout/masterbar/logged-in.jsx
- client/layout/sidebar/item.jsx
- client/my-sites/sidebar/sidebar.jsx
Closes #4377 
This is the initial framework surrounding GuidesTours, including:
- Basic step progression
- Step positioning
- Bullseye pointer
Current state:
(previously: [#](https://cloud.githubusercontent.com/assets/215074/14174052/dea79c60-f739-11e5-85ba-6c4b39015973.gif))
To test:
- `ENABLE_FEATURES=guidestours make run`
- Check that the steps and bullseye work in different browsers and devices
> Guidestours: Initial step and positioning framework

- Dockerfile
Yesterday I needed to install calypso in a local Docker container and I entered in a world of pain. I've implemented these fixes:
* Prevent the build from failing if there is no `npmrc` file.
* Prevent `npm install` from failing when running the build for the first time in a clean VM.
* And the original reason why I needed to install using Docker: copy the `npm_shrinkwrap.json` file to the container before installing the dependencies. Before this fix, we are effectively ignoring `shrinkwrap` in all the builds that use Docker (which can lead to unexplainable bugs).
@blowery @gwwar 
Note: with this PR, https://github.com/Automattic/wp-calypso/pull/4373 is no longer needed.
> Various improvements to the Dockerfile

- docs/coding-guidelines/css.md
Wrong link added in #4249 (my fault).
> DevDocs: fix link to CSS mixins file

- client/components/date-picker/README.md
onSelect should be onSelectDay in the README, this commit fixes the docs to match the code.
cc @apeatling @blowery
> Components: Correct onSelect in DatePicker README

- npm-shrinkwrap.json
- package.json
Containing fixes for node compat. Will come in handy with SSR.
No visual changes. To test -- check that everything still works as before.
> Framework: Bump component-classes and -tip dependencies

- client/components/domains/register-domain-step/index.jsx
- client/components/domains/register-domain-step/style.scss
- client/lib/abtest/active-tests.js
- client/signup/steps/domains/index.jsx
removes the test "domainSearchPlaceholderText" started on #3728 and restores the original
Review:
cc @breezyskies
> removes the test and restores the original

- client/lib/abtest/active-tests.js
- client/reader/controller.js
- client/reader/following-stream/post.jsx
Kills the ABTest that alters featured image size.
> Reader: Turn off the featured image size abtest

- assets/stylesheets/sections/_checkout.scss
- client/lib/abtest/active-tests.js
- client/lib/cart-values/index.js
- client/my-sites/upgrades/cart/cart-coupon.jsx
- client/my-sites/upgrades/cart/secondary-cart.jsx
- client/my-sites/upgrades/cart/style.scss
- client/my-sites/upgrades/checkout/checkout.jsx
- client/my-sites/upgrades/checkout/credit-card-payment-box.jsx
- client/my-sites/upgrades/checkout/credits-payment-box.jsx
- client/my-sites/upgrades/checkout/paypal-payment-box.jsx
> Checkout: Revert A/B test for hiding cart when handling only one product

- client/components/domains/register-domain-step/index.jsx
- client/lib/abtest/active-tests.js
removes the test "domainSearchResultsCount" introduced with #3505 and applies the variation
Review:
cc @breezyskies
> removes the test and applies the variation

- client/my-sites/stats/stats-countries/index.jsx
- client/my-sites/upgrade-nudge/docs/example.jsx
- client/my-sites/upgrade-nudge/index.jsx
- client/my-sites/upgrade-nudge/style.scss
> UpgradeNudge: make Card version as the default, button as optional.

- client/lib/plans/constants.js
- client/lib/plans/index.js
- client/my-sites/upgrade-nudge/index.jsx
Plans utils to handle the features data
@gwwar @mtias @rodrigoi
> Upgrades: Add plans utils

- client/lib/plans/index.js
- client/my-sites/plans/controller.jsx
Passes feature to plans compare page from a nudge
CC @mtias @gwwar
> Plans: pass feature name to plans compare page

- client/components/site-selector/style.scss
- client/my-sites/all-sites-icon/index.jsx
- client/my-sites/all-sites-icon/style.scss
- client/my-sites/all-sites/index.jsx
- client/my-sites/all-sites/style.scss
The icon composite never quite worked alright. This updates the component to a simpler design that scales better.
> AllSites: update visual representation of the component to a simpler one.

- client/components/sidebar-navigation/index.jsx
- client/my-sites/sidebar-navigation/style.scss
> SidebarNavigation: use flex and Gridicon, clean up layout issues.

- client/my-sites/stats/stats-countries/index.jsx
- client/my-sites/stats/stats-module/style.scss
- client/my-sites/upgrade-nudge/index.jsx
Uses query string to bypass controller to compare rows
Needed for testing
CC @mtias
> Upgrades: change route for nudges + CSS tweaks in nudges

- client/lib/feed-post-store/actions.js
- client/lib/feed-post-store/constants.js
- client/lib/feed-post-store/index.js
- client/lib/feed-stream-store/test/analytics/index.js
- client/reader/following-stream/post.jsx
- client/reader/full-post/index.jsx
- client/reader/like-button/index.jsx
- client/reader/stats.js
Solves a long-standing question from folks who ask 'why do I have more likes than page views?'. Consider a like to be enough to push a page view.
cc @nbradbury @aerych
> Reader: Push a page view when someone likes a post in the stream

- client/components/tinymce/plugins/contact-form/dialog/field-header.jsx
- client/components/tinymce/plugins/contact-form/dialog/settings.jsx
- client/my-sites/themes/controller/index.node.js
- client/my-sites/themes/sheet.jsx
- client/my-sites/upgrades/checkout-thank-you/domain-registration-details.jsx
These strings are hard to translate, this improves them.
> i18n: Fix translatable strings as discovered by our translators (Week 12)

- client/my-sites/stats/stats-countries/index.jsx
- client/my-sites/stats/stats-module/index.jsx
> Plans: simple fix because analytics is business only

- assets/stylesheets/_components.scss
- client/my-sites/plan-card/style.scss
- client/my-sites/plans/features/google-analytics.js
- client/my-sites/plans/features/style.scss
- client/my-sites/plans/index.js
This PR introduces Google Analytics feature page
The page describes the feature and nudges user to upgrade to the feature that he is is interested in.
This is a part of new checkout flow originating from google analytics 404 drake
Needed for #4564
> Start Google analytics page

- client/components/plans/plan-actions/index.jsx
- client/components/plans/plans-compare/index.jsx
- client/my-sites/plans/controller.jsx
- client/my-sites/plans/index.js
- client/my-sites/upgrades/checkout/checkout.jsx
- client/my-sites/upgrades/controller.jsx
- client/my-sites/upgrades/index.js
Selected feature query string parameter is passed down the checkout chain to the thank you page.
> Plans/Checkout: Selected Feature

- client/lib/abtest/active-tests.js
- client/my-sites/site-settings/form-analytics.jsx
- client/my-sites/site-settings/section-analytics.jsx
- client/my-sites/upgrade-nudge/index.jsx
- client/my-sites/upgrade-nudge/style.scss
> Analytics Settings: remove EmptyContent and show nudge

- client/my-sites/plans/features/google-analytics.js
> Plans: show better differentiation between the premium and business plans

- client/my-sites/sidebar/sidebar.jsx
> Domains: Directly link to the manage domains page instead of redirect

- client/lib/media/constants.js
- client/lib/media/utils.js
- client/lib/media/validation-store.js
- client/lib/plans/constants.js
- client/my-sites/media-library/content.jsx
- client/my-sites/media-library/upload-button.jsx
This is in regard to #4236 
This PR will enable selecting video file and then nudge to upgrade to actually load it.
To be honest, I have no idea how to track impressions/clicks here
1. Pick a free site
2. Upload a video file to media
3. Upgrade to premium
4. Profit
> Upgrades: enable video upload in media and nudge

- server/devdocs/index.js
This PR is actually a place for me to experiment with statuses and github webooks hooks for #hackday, but I figured I may as well fix some eslint errors while I'm at it.
> Fix eslint errors

- client/guidestours/config.js
> Guided Tours: Use weighted font in copy where appropriate

- docs/troubleshooting.md
I added a note for an issue I ran into: If you aren't seeing changes in your dev environment, look at webpack's watchers and the OS-specific fixes.
> Documented a webpack issue I was having and a pointer to the fix

- assets/stylesheets/_components.scss
- client/lib/plans/constants.js
- client/lib/plans/index.js
- client/my-sites/plans/index.js
- client/my-sites/plans/plan-feature/footer.jsx
- client/my-sites/plans/plan-feature/google-analytics.js
- client/my-sites/plans/plan-feature/style.scss
This PR refactors "Google Analytics" standalone Feature page to make it match any coding standard
Some of the code is moved to utils for re-use
Basically, functionally nothing should change, but feature page should behave like before
Route:
calypso.localhost:3000/plans/features/google-analytics/
CC @mtias @gwwar @rralian @adambbecker
> Upgrades: standalone feature page refactor

- client/my-sites/pages/page-list.jsx
> Pages: only show blog-posts page in published filter.

- client/me/sidebar/index.jsx
There's already a "Help" link in the sidebar itself.
> Me: do not render SidebarFooter in the sidebar.

- client/me/sidebar-navigation/style.scss
Fix placement of user gravatar in "Me" sidebar navigation component:
> Me: fix sidebar-navigation gravatar.

- client/components/site-selector/index.jsx
- client/my-sites/all-sites/README.md
- client/my-sites/all-sites/index.jsx
- client/my-sites/all-sites/style.scss
- client/my-sites/current-site/index.jsx
- client/my-sites/plugins/plugin-site-network/index.jsx
- client/my-sites/plugins/plugin-site-network/style.scss
Tweaks <AllSites> component to support multisite-networks.
> Plugins: use <AllSites> component

- assets/stylesheets/layout/_main.scss
One of the notices is inheriting `#404040` from this bit of CSS in `_main.scss`
```
body {
color: #404040;
font-size: 15px;
line-height: 1.5;
}
```
This color should be using a color variable.
I also went ahead and updated the rest of the colors in the file.
cc @shaunandrews
> General: Update body text color

- webpack.config.node.js
> Framework: Fix analytics NMR path

- client/my-sites/media-library/content.jsx
- client/post-editor/media-modal/secondary-actions.jsx
- server/pragma-checker/index.js
> Framework: add new analytics path to ssr ignore

- npm-shrinkwrap.json
- package.json
Obsolete as of #4699.
/cc @dmsnell for review :smile:
> Framework: Remove redux-analytics dependency

- client/lib/analytics/page-view-tracker/README.md
> Fix reference to analytics module in readme file.

- client/components/infinite-list/index.jsx
- client/reader/following-stream/index.jsx
Need to clean out the sizing cache.
> Reader: Fix up how the Infinite List resets across queries.

- server/pages/index.js
Fixes #4766, i.e. the deskop app.
/cc @gwwar
> server/pages: Make 'render' import relative

- client/components/follow-button/docs/example.jsx
> FollowButton: simplify example display in devdocs.

- client/lib/sites-list/docs/example.jsx
> Devdocs: wrap Site and AllSites in Cards for better display.

- client/layout/sidebar/style.scss
Fixes layout bugs with internal elements (like Site toggle for actions).
(Toggle button disappears in master)
> Sidebar: fix generic targetting of divs inside the component.

- client/reader/full-post/_style.scss
Restores scss but in the full-post folder.
> Reader: still needs details-page scss.

- client/components/tooltip/style.scss
- client/my-sites/site/index.jsx
- client/my-sites/site/style.scss
And adjust display of "edit icon".
> Site: add action to go to settings

- client/my-sites/plugins-wpcom/plugin-panel.jsx
Adds page-view tracking to new wpcom plugins page. No visual changes.
> Add page view tracking to wpcom plugins page

- client/lib/analytics/page-view-tracker/index.jsx
- client/my-sites/plugins-wpcom/plugin-panel.jsx
Stupid mistake on my part. Those responsible have been sacked.
> Fix typos in analytics lib references

- client/me/profile-link/style.scss
> ProfileLinks: update design to match <Site> component.

- client/post-editor/post-editor.jsx
Addresses function binding in `render`, as mentioned in #3883. Also fixes lint warnings in post-editor.jsx.
> Fix post editor function binding

- config/desktop-mac-app-store.json
- config/desktop.json
- config/horizon.json
- config/production.json
- config/stage.json
- config/test.json
- config/wpcalypso.json
This PR turns on the display of monthly plan pricing. This is a follow up to #4724
cc @rralian @retrofox @artpi @drw158
> Plans: show monthly pricing on all environments

- .github/CONTRIBUTING.md
The internal links in CONTRIBUTING.md are broken as it was written expecting to be in root.
Fixes issue #4764
> Update broken links in CONTRIBUTING.md

- client/components/tinymce/index.jsx
- client/components/tinymce/plugins/wpcom-view/views.js
- config/development.json
- config/test.json
- config/wpcalypso.json
:triangular_flag_on_post:
This closes #4683, #1404 and #344
> Editor: Remove Contact Form Feature Flag

- client/my-sites/plans/plan-feature/google-analytics.js
This is a very small PR that fixes one typo.
> General: fixed a typo in the word 'server'.

- client/lib/reader-sidebar/actions.js
- client/reader/tag-stream/index.jsx
Also fix how bad sidebar batches are processed.
> Reader: Fix missing follow button on tag streams

- client/lib/post-normalizer/index.js
This allows the me.sh iframe to work.
> Reader: Whitelist me.sh

- client/lib/plans/index.js
- client/my-sites/themes/single-site.jsx
> Themes: add nudge for custom design feature.

- npm-shrinkwrap.json
- package.json
Update wpcom to [@4.9.7](https://github.com/Automattic/wpcom.js/blob/master/History.md#497--2016-04-19)
cc @timmyc
> Framework: bump wpcom@4.9.7

- client/lib/scroll-to/Makefile
- client/lib/scroll-to/test/index.js
- client/tests.json
part of #3942 
Test works in isolation
**Testing**
npm run test-client
npm run test-client client/lib/scroll-to/test/index -- -w
cc @gziolo @blowery
> Tests: port lib/scroll-to to single test runner

- assets/stylesheets/sections/_posts.scss
- client/my-sites/posts/post.jsx
> Posts: add "comments" stream with reply funcitonality

- client/my-sites/site-settings/form-general.jsx
> Settings: move timezone to the bottom of general settings.

- client/components/tinymce/iframe.scss
Also update the font used.
Before:
After:
cc @aduth
> Editor: update visual display of "code" block.

- client/lib/abtest/active-tests.js
- client/signup/config/flows.js
- client/signup/config/steps.js
- client/signup/steps/survey/index.jsx
> Signup: Remove Vertical Themes A/B Test i1 (Business & Services)

- client/layout/sidebar/style.scss
> Editor: fix drafts-button styles in the editor.

- client/my-sites/upgrades/domain-management/controller.jsx
- client/my-sites/upgrades/domain-management/list/index.jsx
> domain-management: fix eslint warnings

- client/lib/feed-stream-store/index.js
- client/lib/feed-stream-store/paged-stream.js
Also pick up perPage from the creator and use it consistently.
Fixes #4842
> Reader: Calculate page stream offets correctly

- client/reader/comments/form.jsx
Fixes #4913.
cc @blowery there may be something else here to fix, but this at least prevents the general breakage.
> Comments: fix reference error on comment form lifecycle.

- client/guidestours/config.js
- client/guidestours/index.js
- client/guidestours/positioning.js
- client/guidestours/steps.js
- client/guidestours/style.scss
- client/lib/scroll-to/index.js
- client/state/ui/selectors.js
> GuidedTours: Implement mobile styling & positioning

- config/stage.json
> GuidedTours: Enable on staging

- docs/shrinkwrap.md
This PR clarifies when we should modify package.json
cc @aduth
> Build: clarify shrinkwrap steps

- client/signup/config/flows.js
> Signup: Remove unused module in flows.

- server/pages/index.jade
- server/pages/index.js
- webpack.config.js
This gets the commons chunk down to the browser faster and should speed up page loads a bit. It also gives the commons chunk a filename so it's more obvious what it is and why it's being included.
> Webpack: Load the commons chunk in a script tag.

- client/components/like-button/docs/example.jsx
- client/my-sites/plan-storage/docs/example.jsx
> Devdocs: cleanup presentation of plans-storage and likes components.

- client/notifications/index.jsx
> Notifications: Bust cache once again

- client/components/domains/register-domain-step/index.jsx
This pull request deduplicates the tracking of the domain search events to reduce the number of noise in our stats.
If a user types the query slowly, every character they type will constitute as a search, skewing our stats.
This change proposes a solution where the queue the searches completed, and after 10 seconds passed or the user navigates, it will process the queries and reports only the longest query that starts with the same string.
i.e if we made 3 searches: `h`, `hel`, `hello`, it will only report `hello`.
Testing
-
1. Add a debug point in client/components/domains/register-domain-step/index.jsx:61 (`reportSearch` function)
2. Search for domains with different typing speeds
3. Wait 10 seconds / Click add
4. Confirm the debug point gets hit only with the full query
/cc: @klimeryk …
> Domains: Queue tracking of searches to unify them

- client/my-sites/site-settings/controller.js
- client/my-sites/site-settings/main.jsx
This PR doesn't change the behavior of the site settings page. It just implement some ES6 style-code and other minor improvements.
Go to site settings page `http://calypso.localhost:3000/settings/general/<your-testing-blog>` and everything should work without issues.
> SiteSettings: ES6ify - Tidy and Clean code

- test/README.md
We merged the latest update of test folder documentation without paying too much attention. I would like to re-phrase it a bit and add some language corrections. I'm not a native speaker, so please let me know if there is still something that can be stated better :)
/cc @aduth @blowery @rralian
> Docs: Improve test folder documentation

- client/my-sites/posts/post-list.jsx
- client/my-sites/sharing/main.jsx
> Plans: show no-ads feature available in WP.com premium plan

- client/my-sites/posts/post-controls.jsx
- client/my-sites/posts/post.jsx
Was being redirected to "insights" before.
> Posts: fix single stats link in posts-controls.

- client/my-sites/current-site/style.scss
- client/my-sites/site/index.jsx
- client/my-sites/site/style.scss
Also removes some CSS from current site.
> Site: use gridicon for redirect badge instead of noticon.

- client/my-sites/stats/stats-chart-tabs/index.jsx
As in title. I touched this file in #4887 and I promised I will take care of this.
@rralian
> ES6ify imports in stats-chart-tabs

- client/layout/guided-tours/config.js
- client/layout/guided-tours/steps.js
Addresses some feedback.
See commits for more details.
> GuidedTours: Fix simple typos & wording

- client/lib/abtest/active-tests.js
- client/lib/plans/constants.js
- client/my-sites/themes/single-site.jsx
Introduces ABtest to notice introduced in #4859 using copy inspired by #4888 
CC @mtias @rralian
> Upgrades: introduce ABtests to Themes nudge

- client/components/notice/docs/example.jsx
- client/components/notice/style.scss
> Notice: simplify CSS, fix inline links and weights.

- client/my-sites/all-sites-icon/style.scss
> AllSites: fix icon alignment when sites have no icon set.

- client/lib/menu-data/menu-data.js
This PR fixes #4871
Which is a bug created by a mess I introduced in #4034
Problem was, I forgot menus have a tree-like structure.
CC @mcsf @mtias @chad1008 @ockham @lancewillett @rralian
> Add page while creating menu fix

- assets/stylesheets/_components.scss
- client/components/domains/domain-mapping-suggestion/index.jsx
- client/components/domains/domain-product-price/index.jsx
- client/components/domains/domain-product-price/style.scss
- client/components/domains/domain-registration-suggestion/index.jsx
- client/components/domains/domain-search-results/index.jsx
- client/components/domains/domain-suggestion/index.jsx
- client/components/domains/domain-suggestion/test/index.js
- client/components/domains/example-domain-suggestions/index.jsx
- client/components/domains/example-domain-suggestions/style.scss
- client/components/domains/map-domain-step/index.jsx
- client/components/domains/map-domain/index.jsx
- client/components/domains/register-domain-step/index.jsx
- client/components/plans/premium-popover/index.jsx
- client/components/plans/premium-popover/style.scss
- client/lib/abtest/active-tests.js
- client/lib/cart-values/cart-items.js
- client/lib/products-values/index.js
- client/lib/signup/cart.js
- client/lib/signup/step-actions.js
- client/lib/upgrades/actions/cart.js
- client/my-sites/upgrades/controller.jsx
- client/my-sites/upgrades/domain-search/domain-search.jsx
- client/my-sites/upgrades/domain-search/site-redirect-step.jsx
- client/signup/config/flows.js
- client/signup/steps/domains/index.jsx
This PR adds the "Domains with plans only A/B test" on both NUX and Domain Management -> Domain Search.
`localStorage.setItem('ABTests','{"domainsWithPlansOnly_20000101":"plansOnly"}')`
- NUX flow (/start) (Registration and Mapping)
- Domain Management -> Domain Search (Registration and Mapping)
- You should not see any price details for a domain / mapping, only Premium plan information.
- Any time you add a domain registration / mapping to your cart, Premium plan should be automatically added.
- Any time you remove Premium Plan from your cart, domain registrations / mappings should be removed as well.
- The test should not change the behaviour when it is not active.
- The test should not change the behaviour if you already have a plan.
/cc: @breezyskies @p3ob7o @klimeryk @wensco …
> Domains: Plans only test

- client/components/notice/style.scss
Fixes a regression in notices.
> Notices: fix colored links.

- client/my-sites/posts/post-list.jsx
- client/my-sites/sharing/main.jsx
> Plans: tweak copy on no-ads feature to be more informative.

- client/layout/sidebar/button.jsx
- client/layout/sidebar/item.jsx
- client/layout/sidebar/style.scss
- client/my-sites/sidebar/publish-menu.jsx
- client/my-sites/sidebar/sidebar.jsx
- client/reader/sidebar/_style.scss
- client/reader/sidebar/index.jsx
And remove `prop` overload in sidebar item. Also adds preloading to post-editor and customizer as secondary actions.
> Sidebar: create button sub-component

- client/lib/abtest/active-tests.js
- client/my-sites/site-settings/form-analytics.jsx
> Plans: remove google analytics tests and deploy disabled page version.

- client/my-sites/controller.js
* ES6ify
* replace `var` with `const` or `let`.
* replace `require` by `import`
* use string templates when it's possible
* Use arrows functions when it's possible
Navigate my-sites pages. Everything should be ok.
> MySites: Tidy controller.js code.

- client/my-sites/plugins/controller.js
* ES6ify
* replace `var` with `const` or `let`.
* replace `require` by `import`
* use string templates when it's possible
* Use arrows functions when it's possible
Navigate MySites plugins pages: http://calypso.localhost:3000/plugins/. Everything should be ok.
> MySites: Tidy plugins controller.js code

- client/signup/jetpack-connect/jetpack-connect-notices.jsx
Typo in  a text (and missing semicolons)
/cc @oskosk
> Jetpack Connect: Correct notice text

- client/components/header-cake/back.jsx
- client/components/header-cake/docs/example.jsx
- client/components/header-cake/index.jsx
- client/my-sites/plugins/controller.js
* ES6ify
* replace `var` with `const` or `let`.
* replace `require` by `import`
* use string templates when it's possible
* Use arrows functions when it's possible
This component can be tested from devdocs page: http://calypso.localhost:3000/devdocs/design/headers
Also it's used other places like http://calypso.localhost:3000/plans/features/google-analytics/<your-testing-site>
> HeaderCake: ES6ify - Tidy and clean code

- client/lib/domains/dns/index.js
- client/lib/domains/dns/reducer.js
- client/lib/domains/dns/test/data/index.js
- client/lib/domains/dns/test/reducer.js
- client/my-sites/upgrades/domain-management/dns/a-record.jsx
Reverts Automattic/wp-calypso#3711
This broke VIP, deleted their A records, backend changes have been already reverted.
> Revert "Domain Management: DNS: Allow root A records to be updated"

- client/lib/abtest/active-tests.js
Updating test to 50/50 split to better measure impact.
> Plugins: Update AB Test to 50/50 Split

- client/lib/abtest/active-tests.js
- client/my-sites/site-settings/form-analytics.jsx
- client/my-sites/stats/stats-chart-tabs/index.jsx
- client/my-sites/stats/stats-countries/index.jsx
- client/my-sites/stats/stats-insights/index.jsx
- client/my-sites/stats/stats-module/index.jsx
Rendered at the bottom of the full-width blocks:
> Plans: show domain feature notice in stats insights.

- client/boot/index.js
- client/lib/abtest/test-helper/TestList.jsx
- config/wpcalypso.json
- server/pages/index.jade
- server/pages/index.js
Cleans up some stuff in #5183 
- adds in wpcalypso
- removes empty label when not enabled (on staging)
- moves more stuff to component
CC @rralian @gwwar @klimeryk
> Developer experience: cleanup of abtest badge

- client/signup/config/flows.js
Additionally, removes unused flows and adds more robust descriptions for existing flows
> Updates main signup flow to include survey steps

- client/components/plans/plans-compare/index.jsx
- client/lib/abtest/active-tests.js
A test for a smaller amount of storage space displayed for the free plan on the plans comparison page.
> Plans: Test Smaller Storage Amount on Comparisons Page

- npm-shrinkwrap.json
- package.json
Reverts Automattic/wp-calypso#5213
> Revert "Framework: Upgrade TinyMCE to 4.3.11"

- client/lib/abtest/active-tests.js
- client/my-sites/themes/single-site.jsx
As in title.
Tests are going to be performed via #5073 
CC @mtias @rralian
> Remove themes_premium_theme_more_traffic and themesHeaderNudge test

- client/components/tinymce/plugins/media/plugin.jsx
- client/post-editor/media-modal/index.jsx
- config/desktop-mac-app-store.json
- config/desktop.json
- config/development.json
- config/horizon.json
- config/production.json
- config/stage.json
- config/test.json
- config/wpcalypso.json
Closes #3676 by removing the last feature flag for the editor that is `true`thy in all envs.
__To Test__
Open the editor and add some media to a post
/cc @aduth
> Editor: remove live-image-update feature flag.

- client/my-sites/posts/posts-navigation.jsx
- client/my-sites/posts/style.scss
> Posts: display user's gravatar in author segmented control.

- client/my-sites/plans/current-plan/main.jsx
- client/my-sites/plans/current-plan/style.scss
Fixes #5238 
Shows premium plan features alongside business plan in "my plan" page
CC @rralian @gwwar @adambbecker 
Also:
@mtias who probably will change my copy
> Upgrades: show premium features in business plan "my plan" page

- client/signup/config/flows.js
This new flow is essentially a copy of the `desktop` flow, and is used as a control to test that flow but on the web environment.
cc @meremagee @michaeldcain @bisko
> Add the "app" signup flow

- client/lib/push-notifications/service-worker.js
This PR builds off #4987 
This PR implements the display of Web Push notification titles and icons.
> [Notifications] Web Push: Show title and icon

- client/components/theme/index.jsx
- client/components/theme/more-button.jsx
Missed when filing #5315. Hopefully the last non-ES6 Themes bit.
To test -- make sure everything works as before.
> Theme: ES6ify Theme component

- client/components/follow-button/button.jsx
- client/components/follow-button/style.scss
- client/components/gridicon/index.jsx
- client/my-sites/stats/stats-list/action-follow.jsx
- client/my-sites/stats/stats-list/style.scss
- client/reader/feed-header/style.scss
- client/reader/following-edit/style.scss
- client/reader/following-stream/_style.scss
- client/reader/full-post/_style.scss
- client/reader/list-item/style.scss
- client/reader/post-options/_style.scss
- client/reader/stream-header/style.scss
This addresses: https://github.com/Automattic/wp-calypso/issues/3121
**Before:**
**After:** 
Changed in several different places: https://github.com/Automattic/wp-calypso/pull/5256#issuecomment-218915631
> Reader: make Follow/Following button more buttony

- client/lib/shortcode/README.md
Updates import and variable declaration syntax - README only changes.
cc: @aduth
> Update README for shortcode lib

- client/components/plans/plans-compare/index.jsx
- client/lib/abtest/active-tests.js
Remove the 150MB plans storage AB test.
> AB Test: Remove the 150MB plans storage test

- client/my-sites/site-settings/form-general.jsx
> Site Settings: Updated copy for Visibility settings

- client/lib/abtest/active-tests.js
- client/my-sites/upgrade-nudge/index.jsx
- Introduces global abtest for all nudges
- refactors some areas of #5151 
CC @mtias @rralian
> Upgrades: Nudge global test

- client/reader/comments/post-comment.jsx
This PR fixes the improper usage of pluralisation.
> I18n: use correct pluralisation mechanism.

- client/lib/abtest/active-tests.js
- client/my-sites/plugins/main.jsx
- client/my-sites/sidebar/sidebar.jsx
- config/development.json
- config/horizon.json
- config/production.json
- config/stage.json
- config/wpcalypso.json
🚀 Plugins!
@dmsnell care to take a look?
> Removes plugins AB test and enables sidebar item for all sites.

- client/state/jetpack-connect/actions.js
- client/state/jetpack-connect/reducer.js
It was added again by a bad rebase and shouldn't be there
ping @ebinnion !
> Jetpack connect: Remove some old code 

- client/auth/test/login.jsx
- client/components/gravatar/test/index.jsx
- client/components/root-child/test/index.jsx
- client/components/token-field/test/index.jsx
- client/lib/mixins/i18n/test/index.jsx
- client/post-editor/editor-ground-control/test/index.jsx
These are solely test related changes branched from #5116 that we can apply already, to keep that PR leaner.
To test -- verify that this only affects test, and that CircleCI gives us a green light :-)
/cc @gwwar @aduth
> Framework: Some preparatory changes for the React 15 upgrade

- client/my-sites/resume-editing/index.jsx
Fixes #4700 
This pull request seeks to reset the last editor draft state if the post is modified such that it is no longer a draft. This can occur on posts screens when trashing or publishing the post from the post action buttons, or when trashing a post while in the editor.
__Implementation notes:__
Hopefully the sight of `Dispatcher.register` makes you cringe. Rightfully so, but other existing Flux stores for tracking posts are either used in the context of (a) tracking queries for specific sites (`PostListStore`) or (b) tracking edited posts (`PostEditStore`) which is cleared upon leaving the editor.
Using `Dispatcher` is temporary and seemed the most fool-proof approach for capturing all changes to posts globally without littering calls to reset the last edited draft at each instance …
> Editor: Reset last draft when published or trashed

- client/components/domains/domain-suggestion/test/index.js
The AB test was causing this to this introduced in #5409 to randomly
fail in CI.
> Fix the domain-suggestion unit test

- client/components/tinymce/index.jsx
- client/components/tinymce/plugins/insert-menu/menu-items.jsx
- client/components/tinymce/plugins/insert-menu/plugin.jsx
- client/components/tinymce/plugins/insert-menu/style.scss
- client/components/tinymce/style.scss
- config/development.json
- config/horizon.json
- config/stage.json
- config/wpcalypso.json
Fixed version of #5071 
Includes the missing config flag check so TinyMCE doesn't try to load the new plugin if the feature is disabled.
cc: @aduth + @nylen
> Add editor insert plugin

- client/signup/config/flows.js
- client/signup/config/steps.js
The survey step was missing in some of the flows. Made it to be the default step in all the web flows.
cc @michaeldcain @meremagee @umurkontaci
> Signup: Survey step as a default step in all flows.

- client/lib/abtest/active-tests.js
- client/my-sites/sidebar/sidebar.jsx
Reverts Automattic/wp-calypso#5011
> Revert "Remove ab test sidebar button swap"

- client/components/follow-button/style.scss
- client/me/purchases/cancel-purchase/style.scss
- client/my-sites/themes/multi-site.jsx
- client/reader/start/style.scss
- client/signup/jetpack-connect/style.scss
Fixes indentation to use tabs instead of spaces to make `make eslint` happy.
> Fix indentation to use tabs instead of spaces in a few places

- client/components/post-excerpt/index.jsx
- client/reader/start/card-footer.jsx
- client/reader/start/card-header.jsx
- client/reader/start/card.jsx
- client/reader/start/main.jsx
- client/reader/start/post-preview.jsx
- client/reader/start/style.scss
- client/state/reader/sites/selectors.js
- client/state/reader/start/reducer.js
- client/state/reader/start/selectors.js
- config/wpcalypso.json
We added Cold Start recommendations to the Redux tree in #5257, and created the new recommendation UI cards in #5264. 
This PR combines the two, rendering the recommendations from the Redux state in the new cards.
> Reader: add cold start recommendations to cards

- client/components/domains/map-domain-step/index.jsx
- client/components/domains/register-domain-step/index.jsx
This PR adds a notice with a link to dotblog.wordpress.com when the user tries to search to a .blog domain for registration or mapping.
- Go to My Domains -> Add Domain
- Type a .blog domain
- See the notice, click the link, ensure the form is prefilled with your email and the domain name you have entered
- Go to Add Mapping and follow the steps above
- Go to /start w/o an account and follow the steps up to domain search
- Type a .blog domain 
- See the notice, click the link, ensure the form is prefilled with the domain name you've entered but no email. 
- Confirm no console errors
/cc @breezyskies @klimeryk @aidvu
> Domains: Redirect .blog requests to dotblog.wordpress.com

- docs/install.md
> DevDocs: add mention of Calypso Bootstrap as alternate install

- client/state/jetpack-connect/actions.js
_waiting on server merge_ phab diff D1915
> Jetpack connect: Use new redirection endpoint

- client/signup/jetpack-connect/sso.jsx
- client/state/jetpack-connect/actions.js
- client/state/jetpack-connect/reducer.js
- client/state/jetpack-connect/test/actions.js
- client/state/jetpack-connect/test/reducer.js
Adds site specific details to the `/jetpack/sso` route.
> Jetpack SSO: Update SSO component to use blog details

- client/lib/abtest/active-tests.js
- client/my-sites/upgrade-nudge/index.jsx
> Plans: deploy nudges and remove test.

- client/components/domains/register-domain-step/index.jsx
- client/components/search-card/index.jsx
- client/components/search/README.md
- client/components/search/index.jsx
- client/components/search/style.scss
Reverts Automattic/wp-calypso#5649
Caused some breakage, will need to investigate more
> Revert "Fix/domain search box writing direction"

- client/signup/main.jsx
- client/signup/processing-screen-i18n/index.jsx
This is needed in order to merge #5023, as discussed with the i18n team.
We add the code to the new signup processing screen, and reference it (but not actually use it yet) so that the string extraction script can pick it up.
For more info, check #5023.
> Bootstrap new signup processing screen for i18n

- client/post-editor/editor-ground-control.i18n/index.jsx
- client/post-editor/post-editor.jsx
- client/post-editor/verify-email-dialog.i18n.jsx
This adds the code for bootstrapping localization for #5475. The classes are not actually instantiated, but are included so that the translation tools pick up the strings.
> Bootstrap localization for #5475

- client/signup/steps/domains/index.jsx
Skip plans when a domain mapping upgrade is selected on the new user signup flow.
Fixes #5706
> Domains: Plans step with domain mapping fix

- config/desktop.json
- config/production.json
- config/stage.json
cc @aduth after we merge the trashing-a-post PR.
> Enable "resume editing" functionality in production and desktop.

- config/desktop-mac-app-store.json
- config/desktop.json
- config/production.json
Enables SEO settings in production 🚀 
I also added the flag for the desktop app, although I'm not 100% certain on what is needed to be done there ❓
> Site Settings SEO: Enable in Production

- client/lib/plugins/notices.jsx
- client/lib/plugins/test/store.js
- client/my-sites/plugins/plugin.jsx
> Plugins: fix `exists` typos

- client/lib/post-normalizer/rule-create-better-excerpt.js
- client/lib/post-normalizer/test/index.js
> Reader: Strip styles and scripts when building excerpts.

- client/lib/post-normalizer/rule-wait-for-images-to-load.js
Basic mistake, the array is of URLs, not image objects.
> Reader: Fix how we map content images out of loaded images.

- assets/stylesheets/_components.scss
- client/components/post-card/docs/example.jsx
- client/components/post-card/small.jsx
- client/components/post-card/style.scss
- client/devdocs/design/app-components.jsx
- client/lib/resize-image-url/index.js
See http://calypso.localhost:3000/devdocs/app-components at the bottom for tests
> Reader: Add in small post cards for related posts and features

- server/pages/404.jade
> 404: Change wording to 'Return Home'

- client/my-sites/themes/index.node.js
- server/pages/404.jade
- server/pages/index.js
Reverts Automattic/wp-calypso#4632
Signup is broken -- likely because of this PR.
/cc @aduth
> Revert "Server-side Rendering: Route based on sections whitelist, fall back to 404"

- client/lib/push-notifications/service-worker.js
- client/notifications/index.jsx
With push notifications enabled, clicking on a notification now causes Calypso to be loaded and the notes pane to be opened.
> Push Notifications: Clicking on a note loads Calypso with opened note pane

- client/lib/abtest/active-tests.js
Should allow us to reach significance faster.
Would Dr @lsinger please come to the service desk?
> GuidedTours: Update MVP tour variants to 15% each

- client/signup/jetpack-connect/authorize-form.jsx
- client/state/jetpack-connect/actions.js
This PR fixes some event naming and adds extra info to some error logs to be able to get more info about some errors we are getting in production
Test live: https://calypso.live/?branch=fix/jetpack-connect-error-logging
> Jetpack connect: Log complete errors

- client/mailing-lists/main.jsx
These strings are hard to translate, this improves them.
> i18n: Fix translatable strings as discovered by our translators (Week 13)

- assets/stylesheets/shared/functions/_z-index.scss
- client/layout/community-translator/launcher.jsx
- client/layout/community-translator/style.scss
Test live: https://calypso.live/?branch=update/community-translator
> CommunityTranslator: rename classes, clean CSS, use gridicon.

- config/desktop.json
/cc @mkaz for review
Test live: https://calypso.live/?branch=update/theme-sheets-enable-in-desktop
> Themes: Enable Theme Details sheets in desktop

- docs/our-approach-to-data.md
We merged in #4805 changes to use new `createReducer` util, but we haven't update docs yet. This PR tries to fix that. I did my best to refresh our docs, but I'm not a native speaker so please let me know if we should rephrase some sentences. Feel free to update them also yourself :)
/cc @apeatling @blowery @gwwar
> Docs: Update our approach to data after adding create reducer util

- client/components/seo/search-preview/index.jsx
- client/components/seo/style.scss
Closes #5910
- Removes box shadow
- Adds margin to preview box
- Changes color of header text
cc: @drw158 
Test live: https://calypso.live/?branch=update/seo-preview
> SEO Search Preview: Style updates

- client/devdocs/welcome.jsx
Right not left.
Test live: https://calypso.live/?branch=fix/devdocs-welcome-instruction
> Devdocs: fix welcome instruction regarding env badge.

- client/my-sites/ads/main.jsx
- client/my-sites/ads/style.scss
CC @rralian @apeatling @gwwar 
Test live: https://calypso.live/?branch=update/wordads-wording
> Upgrades: Change wording in wordads success message

- client/my-sites/theme/main.jsx
Fixes #5764
**To Test**
Follow instructions in #5764 
Test live: https://calypso.live/?branch=fix/theme-sheet-scroll-top
> Themes: Scroll to top of theme sheet on opening

- config/stage.json
- config/test.json
First stage towards #5887  
Test live: https://calypso.live/?branch=new/wordads-instant-stage
> Enable wordadsinstant on stage and test

- config/stage.json
Enables Push Notifications in Staging. See #4987, #5748 for fuller context.
Test live: https://calypso.live/?branch=add/push-notification/staging
> Push Notifications: Enable for Staging

- client/lib/service-worker/service-worker.js
- client/notifications/index.jsx
- client/state/push-notifications/actions.js
Moved from #5993 in order to make this PR against master.
Test live: https://calypso.live/?branch=add/push-notification/track
> Push Notifications: Add Tracks events

- client/lib/wporg/index.js
Fixes #5003 
(Now possible thanks to #5688)
> Plugins / i18n: add wporg locale code to the plugin details request

- client/lib/translator-jumpstart/index.js
Change from #6140  requires new version
Test live: https://calypso.live/?branch=fix/bumpCTScriptVersion
> Community Translator: bump script version

- client/state/plans/schema.js
Add missing features to the plans schema to prevent validation errors.
cc: @retrofox @eoigal 
Test live: https://calypso.live/?branch=fix/adding-missing-features-to-plans-schema-validations
> Jepack Monthly Plans: Schema Validations

- client/components/post-card/small.jsx
- client/components/post-card/style.scss
- client/components/related-posts/index.jsx
Use a layout with the title on top, site name, author below
Test live: https://calypso.live/?branch=update/small-post-layout
> Reader: Update small post layout to put title first, simpler style

- assets/stylesheets/shared/_colors.scss
- client/components/button/style.scss
- client/layout/masterbar/style.scss
- client/layout/sidebar/style.scss
- client/my-sites/current-site/style.scss
Groundwork for flexible color schemes. There should be no visual changes besides some subtle color shifts.
Test live: https://calypso.live/?branch=add/color-scheme-cleanup
> Framework: color definitions cleanup

- client/state/themes/current-theme/reducer.js
Fixes #5699.
To test: 
> 1. Visit /design
> 2. Click thumbnail to open preview
> 3. Click Try and Customize
> 4. Click Save and Publish
> 5. Note ~~missing author https://cloudup.com/cw5UGlCeugh~~~
Note author is now displayed!
/cc @ianstewart @alisterscott 
Test live: https://calypso.live/?branch=update/themes-show-author-in-thanks-modal-after-customizer
> Themes: Display author in Thanks modal if activated from customizer

- client/my-sites/posts/main.jsx
- client/my-sites/posts/style.scss
cc @aduth
Test live: https://calypso.live/?branch=update/drafts-column-all-sites
> Posts: disable drafts column for All Sites view.

- client/my-sites/posts/main.jsx
- client/my-sites/posts/style.scss
Test live: https://calypso.live/?branch=update/use-drafts-panel-for-recent-only
> Posts: refine drafts column as recent drafts only.

- client/components/domains/domain-search-results/index.jsx
Update copy to properly reflect the price.
Test live: https://calypso.live/?branch=update/mappable-domain-notice
**Before:**
**After:**
cc @umurkontaci @klimeryk
> Domains: Mappable domain notice copy

- client/components/post-card/docs/example.jsx
- client/components/post-card/small.jsx
Also move to ES6 imports, fix var usage, clean up the examples
Test live: https://calypso.live/?branch=fix/devdocs/plan-cards
> PostCard: Fix the devdocs display for PostCard

- client/reader/start/main.jsx
- client/reader/start/style.scss
This fixes: https://github.com/Automattic/wp-calypso/issues/6182
**Before (in FF):**
**After (in FF):**
/cc @bluefuton
> Reader: fix line-clamp not working in FF

- client/components/plans/plan-list/index.jsx
- client/components/plans/plans-compare/index.jsx
- client/lib/abtest/active-tests.js
- client/lib/plans/index.js
- client/lib/plans/personal-plan.js
- client/state/sites/plans/assembler.js
- config/development.json
Adds a feature flag to improve control over the Personal Plan visibility.
cc: @apeatling @roundhill 
Test live: https://calypso.live/?branch=add/personal-plan-feature-flag
> Personal Plan: Feature Flag

- config/production.json
_DO NOT MERGE YET!_
Closes #556 :-)
Test live: https://calypso.live/?branch=update/theme-sheet-enable-in-production
> Themes: Enable Theme Details Sheets in production

- client/lib/post-normalizer/rule-content-word-count.js
- client/lib/post-normalizer/rule-keep-valid-images.js
- client/me/notification-settings/push-notification-settings/style.scss
- client/my-sites/theme/style.scss
- client/reader/full-post/_style.scss
- client/reader/post-excerpt-link/index.jsx
- client/reader/start/style.scss
Brought up in #6116, there seem to be a lot of mixed indentation warnings in the code base. This fixes those that exist.
Testing: run `make lint` to be sure there are no errors.
Test live: https://calypso.live/?branch=fix/indentation-warnings
> Framework: Fix more indentation warnings

- config/production.json
- config/stage.json
This switches on the Calypso exporter 🎉 
Test live: https://calypso.live/?branch=update/exporter/launch
> Export: Launch in staging and production

- client/lib/query-manager/post/key.js
- client/lib/query-manager/post/test/key.js
- client/lib/query-manager/term/key.js
- client/lib/query-manager/term/test/key.js
- client/my-sites/posts/main.jsx
This makes it more connected with the rest of the posts UI.
cc @aduth @apeatling 
Test live: https://calypso.live/?branch=update/respect-author-in-recent-drafts
> Posts: respect author filter for recent drafts display.

- client/my-sites/theme/main.jsx
- client/my-sites/theme/style.scss
- client/my-sites/theme/theme-download-card/index.jsx
- client/my-sites/theme/theme-download-card/style.scss
- client/my-sites/theme/themes-related-card/index.jsx
- client/my-sites/theme/themes-related-card/style.scss
Reverts Automattic/wp-calypso#6353
Test live: https://calypso.live/?branch=revert-6353-fix/linter-css-warnings-in-theme-sheet
> Revert "Fix linter warnings."

- client/my-sites/theme/main.jsx
This is a PR addressing issue #6326 .
Test live: https://calypso.live/?branch=fix/missing-free-txt-on-theme-sheet-button
> Add Free txt to Theme Sheet picker button for free themes.

- client/my-sites/draft/index.jsx
Fixes images form Jetpack sites potentially not being displayed.
cc @aduth 
Test live: https://calypso.live/?branch=fix/images-in-drafts
> Drafts: update imageUrl generation to avoid https issues.

- client/my-sites/draft/index.jsx
Handle images from WP.com and Jetpack better.
Test live: https://calypso.live/?branch=fix/images-drafts-2
> Drafts: use separate solutions for images from WP.com.

- client/reader/controller.js
- client/reader/index.js
- config/client.json
…old start
Test live: https://calypso.live/?branch=alternate/wait-on-sub-counts-for-cold-start
> Wait for sub counts to come in before redirecting

- client/my-sites/plugins-wpcom/default-plugins.js
- client/my-sites/plugins-wpcom/plugin-panel.jsx
Show more items and adjust copy.
cc @rralian 
Test live: https://calypso.live/?branch=update/wpcom-plugins
> WPcom Plugins: show more by default, adjust Polls and Surveys title.

- client/components/domains/register-domain-step/index.jsx
- client/my-sites/upgrades/checkout/privacy-protection.jsx
- client/my-sites/upgrades/checkout/style.scss
- Update copy for checkbox privacy variation
- Add privacy by default if it's free
**Testing:**
1. Need a blog w/o a plan
_- case DWPO:_
2a. Go to Add Domain
2b. Select one domain
_- case no DWPO_
2a. Buy a plan
2b. Go back to Add Domain
2c. Add a domain
3. Make sure privacy is added to cart for the free domain
4. Add another domain
5. Make sure there's no privacy in the cart for the domain
cc @umurkontaci @klimeryk
> Domains: Update/add privacy checkbox test

- client/lib/abtest/active-tests.js
- client/signup/steps/user/index.jsx
This PR updates the variations used by the Cold Start A/B test and removes the code used by the removed variation.
Test live: https://calypso.live/?branch=update/coldstart-abtest
> updated with new variation and removed unused code

- client/reader/start/main.jsx
- client/reader/start/style.scss
Originally, the Cold Start's "Done" button was using a fixed-positioned bar. 
In an effort to not introduce new components and use already existing ones, this PR attempts to use the global notice component. However, after playing with it further, I honestly don't think this is the ideal solution for it: https://cloudup.com/cmi0wsV2PEe
It's obtrusive and feels like it's in the wrong location since it's a non-standard in general. Normally, elements floating somewhere at the top of the page are dismissible notifications.
Even if we reduced the number of words/padding, it still feels obtrusive: https://cloudup.com/cfy36ChzTb8. Most of all, you'd be scrolling from top to bottom so it seems like an illogical path to make the user go back up to complete the task.
However, I think we could make …
> Reader: update Cold Start "Done" button

- client/components/ellipsis-menu/docs/example.jsx
- client/devdocs/style.scss
cc @aduth 
Test live: https://calypso.live/?branch=add/ellipsis-menu-permalink
> EllipsisMenu: add link to permalink and title.

- client/state/reader/sites/schema.js
Properly clone out the pattern object before adding in the new property
Test live: https://calypso.live/?branch=fix/state/reader-sites-schema
> State: Stop altering the original site schema in reader/sites

- client/signup/steps/pressable-store/index.jsx
@mcsf: Sorry for missing your comment about this on #6350
Test live: https://calypso.live/?branch=remove/go-to-next-step
> Remove goToNextStep from propTypes

- config/desktop.json
- config/production.json
- config/stage.json
Simple update to turn the survey on for production. Please refer to #4838 for full testing instructions.
> Purchases: Ship Survey

- .stylelintrc
- package.json
#6142 
@belcherj 
Just added stylelint here. Let me know if you have any comments :) 
Test live: https://calypso.live/?branch=stylelint
> Framework: Add stylelint to lint SCSS files

- client/lib/domains/dns/index.js
- client/lib/domains/dns/reducer.js
- client/lib/upgrades/actions/domain-management.js
- client/my-sites/upgrades/domain-management/dns/delete-email-forwards-dialog.jsx
- client/my-sites/upgrades/domain-management/dns/dns-list.jsx
- client/my-sites/upgrades/domain-management/dns/dns-record.jsx
- client/my-sites/upgrades/domain-management/style.scss
**P2 Post:** p2MSmN-534-p2
Resolves #5752.
Test live: https://calypso.live/?branch=add/delete-mx-record-confirmation/main
>  	Domain Management: DNS: Prompt the user about Email Forwards before deleting the last MX record

- client/devdocs/style.scss
> Devdocs: fix headings.

- config/production.json
🚢
Test live: https://calypso.live/?branch=add/reader/cold-start-on-production
> Enable Reader Cold Start on production

- client/my-sites/stats/controller.js
- client/my-sites/stats/follows/index.jsx
- client/my-sites/stats/site.jsx
- client/my-sites/stats/stats-insights/index.jsx
- client/my-sites/stats/stats-list/style.scss
- client/my-sites/stats/stats-module/expand.scss
- client/my-sites/stats/stats-module/style.scss
- client/my-sites/stats/stats-post-detail/index.jsx
- client/my-sites/stats/style.scss
- client/my-sites/stats/summary/index.jsx
This PR will cleanup the ESLint warnings currently present in many of the stats files (in preparation for functional changes to those files in #6174).
No functional changes are expected from these changes, so testing should focus on making sure that the stats section still works as before.
Test live: https://calypso.live/?branch=update/stats-eslint-cleanup
> Stats: ESLint cleanup for stats

- assets/stylesheets/_main.scss
- client/components/comment-button/index.jsx
- client/components/like-button/button.jsx
- client/components/like-button/index.jsx
- client/components/post-card/author-and-site.jsx
- client/components/post-card/docs/example.jsx
- client/components/post-card/search.jsx
- client/components/post-card/small.jsx
- client/components/post-card/style.scss
- client/lib/post-normalizer/rule-create-better-excerpt.js
- client/reader/search-stream/index.jsx
- client/reader/stream/index.jsx
New Search Cards for reader search.
Test live: https://calypso.live/?branch=add/reader/search-i2
> Reader: Search Cards from i2

- client/post-editor/post-editor.jsx
Fixes #6615
Test live: https://calypso.live/?branch=update/add-footer-sidebar-to-editor
> Editor: render SidebarFooter with help link.

- client/my-sites/site-settings/form-general.jsx
Fix typo
CC @lamosty
Test live: https://calypso.live/?branch=update/footer-credit-typo
> Footer credit nudge: typo

- client/lib/menu-data/menu-data.js
- client/lib/promises/index.js
Refactors #4034 and #4937 trying to keep Menus code as tidy as possible.
- Go to menus
- Create new nested Menu Item
- Choose `Create a new page for this menu item` as the item
- Save
CC @mcsf @rralian
> Menus: refactor of 'create page while menu'

- client/reader/search-stream/index.jsx
Just removes the "what do you want to find" text.
> Reader: Remove extra text from blank slate search screen

- client/reader/search/index.js
- config/horizon.json
- config/stage.json
Also redirect traffic to search to `/` if search is not enabled
> Reader: Enable search for staging and horizon

- client/components/search/style.scss
Add 1px border to search box
Test live: https://calypso.live/?branch=update/reader/search-borders
> search box border

- client/components/post-card/search.jsx
- client/lib/feed-stream-store/index.js
- client/reader/follow-button/index.jsx
- client/reader/search-stream/index.jsx
- client/reader/stats.js
WIP. Currently only handles interactions and needs more testing.
Test live: https://calypso.live/?branch=add/reader-search-traintracks
> Reader Search: Add train tracks

- client/reader/search-stream/index.jsx
- client/reader/search-stream/style.scss
match up the color with the card borders used by other search components around the site
Test live: https://calypso.live/?branch=add/reader/border-on-search-input
> Add in a border to the search input

- config/production.json
Search in prod. Woo!
Test live: https://calypso.live/?branch=deploy/reader/search
> Reader: Release Search :party:

- client/my-sites/themes/themes-site-selector-modal.jsx
Follow-up to #6349
No visual changes. To test -- ensure the showcase still works, particularly the site selector modal (multi-site showcase and sheet).
Test live: https://calypso.live/?branch=update/themes-post-refactor-cleanup
> ThemesSiteSelectorModal: Cleanup

- client/components/plans/plan-list/index.jsx
- client/components/plans/plans-compare/index.jsx
- client/lib/abtest/active-tests.js
- client/lib/plans/index.js
- client/my-sites/plans-features-main/index.jsx
- client/my-sites/plans/main.jsx
- client/signup/steps/plans/index.jsx
This PR removes all the references to the A/B test and keeps the feature flag.
cc: @apeatling @roundhill @gwwar 
Test live: https://calypso.live/?branch=update/personal-plan-ab-test-cleanup
> Personal Plan: A/B Test Cleanup

- client/state/ui/guided-tours/selectors.js
Fixes bugs in older browsers
Test live: https://calypso.live/?branch=fix/native-find
> Replace native `find` with lodash implementation

- client/devdocs/design/index.jsx
Fixed typo and header link for Ribbon component, and put it in alphabetical order in the main list.  This makes it easier to manage the visual diff tests.
@artpi it's your component, can you take a quick look? 
Test live: https://calypso.live/?branch=fix/ribbon-component-devdocs
> Minor DevDocs updates to Ribbon component

- client/lib/feed-stream-store/index.js
- client/reader/recommendations/controller.js
- client/reader/recommendations/index.js
- client/reader/sidebar/index.jsx
We need a page for evaluation of the cold start and warm start algorithms side by side. This should make it easier to find problems and discuss what needs to be improved.
Test live: https://calypso.live/?branch=add-reader-coldstart-demo
> Reader: Add reader coldstart demo page

- client/lib/post-normalizer/rule-content-safe-images.js
> Reader: Don't feature smileys in reader cards

- client/components/first-view/index.jsx
- client/my-sites/stats/stats-first-view/index.jsx
The text for the Stats First View is updated in this PR.
Test live: https://calypso.live/?branch=update/stats-first-view-text
> Update Stats First View text

- client/my-sites/upgrades/navigation.jsx
cc @rickybanister 
Test live: https://calypso.live/?branch=update/render-my-plan-for-jetpack
> Jetpack Plans: display "My Plan" in navigation.

- client/layout/guided-tours/config.js
- client/state/current-user/selectors.js
- client/state/ui/guided-tours/selectors.js
- client/state/ui/guided-tours/test/selectors.js
- client/state/users/selectors.js
Test live: https://calypso.live/?branch=add/guided-tours-new-user-context
> Guided Tours: Add context selector isNewUser

- client/devdocs/style.scss
Fixes #6740.
Test live: https://calypso.live/?branch=fix/spinner-line-example
> Devdocs: remove "hr" css code that was making SpinnerLine invisible.

- client/components/comment-button/docs/example.jsx
- client/components/happiness-support/docs/example.jsx
- client/components/like-button/docs/example.jsx
- client/components/post-card/docs/example.jsx
- client/components/post-schedule/docs/example.jsx
- client/components/sites-dropdown/docs/example.jsx
- client/components/theme/docs/example.jsx
- client/components/themes-list/docs/example.jsx
- client/devdocs/design/blocks.jsx
- client/devdocs/index.js
- client/lib/sites-list/docs/example.jsx
- client/my-sites/domain-tip/docs/example.jsx
- client/my-sites/feature-comparison/docs/example.jsx
- client/my-sites/plan-compare-card/docs/example.jsx
- client/my-sites/plan-storage/docs/example.jsx
- client/my-sites/post-selector/docs/example.jsx
- client/my-sites/upgrade-nudge/docs/example.jsx
cc @ehg 
Test live: https://calypso.live/?branch=fix/paths-to-blocks
> Devdocs: fix paths to blocks.

- client/components/follow-button/docs/example.jsx
- client/devdocs/design/blocks.jsx
- Fixes the 'Follow Button' title link from http://calypso.localhost:3000/devdocs/app-components
- Fixes the FollowButton component preview on http://calypso.localhost:3000/devdocs/app-components/follow-button
Thanks to @mtias for spotting these.
Test live: https://calypso.live/?branch=fix/devdocs/follow-button-example
> Devdocs: fix follow button example in devdocs

- client/components/popover/docs/example.jsx
Before:
After:
Test live: https://calypso.live/?branch=update/popover-example
> Popover: update example to make it look less broken.

- client/components/reader-full-post/README.md
- client/components/reader-full-post/index.jsx
- client/reader/controller.js
- client/reader/full-post/controller.js
- client/reader/full-post/index.js
to test, you have to enable the feature flag at runtime:
`ENABLE_FEATURES=reader/refresh-2016-07 make run`
This is _really_ basic. It just loads up the new skeleton for the full post view and not much more.
This is just to get the basics in place so we can start fleshing out the new full post.
> Reader: New Full Post skeleton

- client/components/comment-button/docs/example.jsx
- client/components/comment-button/style.scss
- client/components/like-button/style.scss
- client/components/post-card/style.scss
Before:
After:
Test live: https://calypso.live/?branch=update/comment-button-component
> CommentButton: improve CSS construction and update devdocs example.

- client/lib/catch-js-errors/index.js
This enables JS Error logging rest API for every user, so scales it 100x. Currently we have around 1600 errors/24h, so that would mean 160 000/24h
I talked with @bazza and he thinks, we should try it. If I get :+1:, I will deploy it around 6PM GMT, so that we can revert if need be.
Requests are rate-limited per user to 30/hr
- Build with ENABLE_FEATURES=catch-js-errors make run
- `localStorage.clear()` to de-assign yourself from the logging group
- Reload
- Go to http://calypso.localhost:3000/plugins . IF you have a Jetpack site, you will get an error there.
- You should see a call going to https://public-api.wordpress.com/rest/v1.1/js-error in inspector
- See that data is passed in request
- If you want to see this data captured, see differential D2353
CC @rralian @gwwar 
Test live: …
> JS Errors: Enable rest API for Everyone

- client/blocks/author-selector/docs/example.jsx
- client/devdocs/design/blocks.jsx
- client/lib/user/shared-utils.js
Test live: https://calypso.live/?branch=add/author-selector-example
> AuthorSelector: render example in devdocs.

- client/wordpress-com.js
Sections match in order, so both sections match. Make full post later so it can override secondary.
Test live: https://calypso.live/?branch=update/reader/new-full-post-tweaks
> Reader: Move full post section after /read so it gets picked up.

- client/lib/analytics/ad-tracking.js
We discovered a situation in the NUX where the `retarget` function would be called multiple times very close together. This caused a problem because the first call would cause the scripts to start loading, but then the second call would try to call the tracking functions (because it thought the scripts were finished loading). This caused an undefined function error in the NUX for users who restarted it after a certain point.
To fix this, this PR adds a new `hasFinishedFetchingScripts` function which we set to `true` after all of the scripts have finished loading. We only call the tracking functions when this is set.
To test:
1. Set `ad-tracking` to `true` in `development.json`
2. Run through the NUX, refreshing the page on the domain step
3. Verify there aren't any console errors
See …
> Ad Tracking: Make retargeting code more robust

- client/my-sites/pages/controller.js
A bad auto merge resulted in a non-loading pages section.
Test live: https://calypso.live/?branch=fix/broken-pages-section-load
> Fix broken pages section load

- client/blocks/site/style.scss
Test live: https://calypso.live/?branch=update/site-home-icon-mobile
> Site: do not hide site icon on mobile.

- client/lib/catch-js-errors/index.js
This introduces hard limit for trace field. Sometimes this field gets out of control and reaches up to 92KB!
This sets hard limit of 8KB so it does not use too much user bandwith and also our computation.
Continues changes from #7187 .
- Build with ENABLE_FEATURES=catch-js-errors make run
- Go to http://calypso.localhost:3000/plugins . IF you have a Jetpack site, you will get an error there. If you dont have error in console, just introduce one somewhere else and navigate
- You should see a call going to https://public-api.wordpress.com/rest/v1.1/js-error in inspector
- See if it worked
Test live: https://calypso.live/?branch=update/js-errors-trace-limit
> Hard limit for trace

- client/components/post-card/docs/example.jsx
- client/components/post-card/search.jsx
- client/components/post-card/style.scss
- client/devdocs/style.scss
- client/lib/abtest/active-tests.js
- client/reader/search-stream/index.jsx
- client/reader/start/card-header.jsx
- client/reader/start/controller.js
- client/reader/start/main.jsx
- client/reader/start/search.jsx
- client/reader/start/style.scss
- client/reader/stream/index.jsx
This PR adds the ability for a new user to search for sites by keyword whilst in the Cold Start experience.
Test live: https://calypso.live/?branch=add/reader/search-to-cold-start
> Reader: add search to Cold Start

- client/reader/start/main.jsx
**Before:**
**After:**
/cc @fraying 
Test live: https://calypso.live/?branch=update/reader/cold-start-intro-copy
> Reader: update Cold Start intro copy

- client/components/web-preview/toolbar.jsx
See #7291 for bug introduction
cc: @aduth
Test live: https://calypso.live/?branch=fix/seo-plans-null
> Fix bug where we were trying to access property of null plan object

- client/components/button/README.md
- client/components/button/index.jsx
This pull request is the first of a series of pull requests aimed at optimization and updates to commonly used components which could benefit from performance review.
The aim of this component is to make small improvements to the `<Button />` component. Specifically:
- Render as a pure component
- Use ES6 Component class
- Avoid an unnecessary second call to `classNames`
- Remove most default props
- Unset `type` from anchor tag rendering, in preparation for [warnings in React 15.2+](https://github.com/facebook/react/blob/master/CHANGELOG.md#1521-july-8-2016)
- Update documentation
__Testing Instructions:__
Verify that no regressions occur in button rendering.
[See DevDocs Design Buttons for most component variations](http://calypso.localhost:3000/devdocs/design/buttons)
Can you think of …
> Components: Optimize rendering of Button component

- client/my-sites/plan-features/index.jsx
This adds a tracks call whenever plans is seen.
- Set `localStorage.debug = 'calypso:analytics'` in the console
- Navigate to /plans
- We should see a `calypso_wp_plans_test_view` fire.
- Go through the signup flow, and follow steps until you get to plan selection.
- We should see a `calypso_wp_plans_test_view` fire.
cc @rralian 
Test live: https://calypso.live/?branch=add/track-plans-view
> Plans: track when plans are seen for crosssite test

- client/components/card/index.jsx
- client/my-sites/themes/current-theme/index.jsx
In `CurrentTheme`, and in `Card`.
Test live: https://calypso.live/?branch=fix/themes-react-warnings
> Themes: Fix a couple of React warnings

- config/production.json
Closes #588
__WARNING:__ DO NOT MERGE until intended launch time.
This pull request seeks to enable custom post types management in production. This includes new post type list screens and editor compatibility.
__Testing instructions:__
PCYsg-5YE-p2
cc @Automattic/io 
Test live: https://calypso.live/?branch=update/cpt-production
> CPT: Enable custom post types feature in production

- client/components/accordion/index.jsx
- client/components/accordion/test/index.jsx
Mostly var instead of const.
Test live: https://calypso.live/?branch=fix/accordion-eslint-errors
> Accordion: fix ESLint warnings

- client/components/bulk-select/index.jsx
Fix a line too long warning
Test live: https://calypso.live/?branch=fix/bulk-select-eslint-errors
> Bulk Select: Fix ESLint warnings

- client/components/card/index.jsx
Props @aduth, see https://github.com/Automattic/wp-calypso/pull/7407#discussion_r74842627
Test live: https://calypso.live/?branch=update/component-card-tighten-omit
> Card Component: Tighten Child Props Omissions

- client/reader/daily-post/index.jsx
cc @akirk 
Test live: https://calypso.live/?branch=fix/reader/daily-post-i18n
> Fix i18n string interpolation 

- client/signup/steps/design-type-with-store/bluehost-store/index.jsx
Removes unused `abtest` variable from Bluehost store step.
> Remove unused variable

- client/components/card/compact.jsx
Fixes the `no-var` warning.
Test live: https://calypso.live/?branch=fix/card-eslint-errors
> Card: fix ESLint warnings

- client/components/track-interactions/test/index.js
Thus simpler and less error-prone.
Test live: https://calypso.live/?branch=update/track-interactions-test-idiomatic
> TrackInteractions: Make tests more idiomatic

- client/components/app-promo/index.jsx
- client/components/app-promo/style.scss
Mostly vars and line lengths.
Test live: https://calypso.live/?branch=fix/app-promo-eslint-errors
> App Promo: Fix ESLint warnings

- client/blocks/reader-full-post/style.scss
Fixes @fraying's spacing concerns from #7417 - see the original issue for details.
Fixes #7417.
Test live: https://calypso.live/?branch=fix/reader/full-post-header-spacing-issues
> Reader: fix new full post header spacing issues

- client/components/site-selector/index.jsx
- client/components/site-selector/style.scss
- client/lib/sites-list/list.js
- client/mailing-lists/controller.js
- client/my-sites/controller.js
- client/my-sites/drafts/controller.js
- client/my-sites/media/controller.js
- client/my-sites/menus/controller.js
- client/my-sites/plans/controller.jsx
- client/my-sites/upgrades/controller.jsx
- client/state/preferences/constants.js
- client/state/preferences/test/reducer.js
- client/state/ui/reducer.js
- client/state/ui/test/reducer.js
Reverts Automattic/wp-calypso#7478
Test live: https://calypso.live/?branch=revert-7478-update/site-selector-preferences
> Revert "Sites: Use Redux state preference for recent sites"

- client/components/post-schedule/docs/example.jsx
This PR adds corrections to ESLint warnings and at the same time implement ES6 syntax.
Go to PostSchedule devdocs page and then _play_ taking a look to these changes. Everything should be ok.
Test live: https://calypso.live/?branch=update/post-schedule-example
> PostSchedule: minor improvements in example

- client/state/stored-cards/reducer.js
- client/state/stored-cards/schema.js
- client/state/stored-cards/test/reducer.js
Part of #7329. Added a schema for stored cards items so we can persist them.
/cc @gwwar 
Test live: https://calypso.live/?branch=add/persist-stored-cards
> Persist stored cards Redux state

- client/state/jetpack-connect/test/reducer.js
This PR adds tests for the Jetpack Connect `jetpackConnectSite()` reducer. 
To test:
* Get this branch going at your Calypso development environment.
* In your command line terminal, navigate to your Calypso directory and run the following command: `npm run test-client -- --grep "state jetpack-connect reducer"`. Verify all tests are passing ✅ .
/cc @roccotripaldi 
Test live: https://calypso.live/?branch=add/jetpack-connect-site-reducer-tests
> Jetpack Connect: Add tests for jetpackConnectSite() reducer

- assets/stylesheets/_components.scss
- client/components/animate/README.md
- client/components/animate/index.jsx
- client/components/animate/style.scss
- client/my-sites/site-indicator/site-indicator.jsx
- server/pages/index.jade
This PR adds a simple component that works as a wrapper to add transition effects to children.
It also applies the effect to site-indicator as an example: https://cloudup.com/c2BIpXewXGL
Test live: https://calypso.live/?branch=add/animate-component
> Components: <Animate>

- config/_shared.json
- config/client.json
- config/development.json
- config/horizon.json
- config/production.json
- config/stage.json
happychat_url - the url the happychat client connects to
feature.happychat - wether or not the happychat client is configured
For more context this is part of a bigger Happychat feature (#7757)
Test live: https://calypso.live/?branch=add/happychat-config
> Adding happychat configuration values

- assets/stylesheets/_components.scss
- client/components/happychat/README.md
- client/components/happychat/agent-w/index.jsx
- client/components/happychat/agent-w/style.scss
- client/components/happychat/autoscroll.js
- client/components/happychat/composer.jsx
- client/components/happychat/functional.js
- client/components/happychat/helpers.js
- client/components/happychat/index.jsx
- client/components/happychat/page.jsx
- client/components/happychat/scrollbleed.js
- client/components/happychat/style.scss
- client/components/happychat/timeline.jsx
- client/state/happychat/selectors.js
Happychat client UI
Depends on #7759 
Parte of a larger feature: #7757 
Test live: https://calypso.live/?branch=add/happychat-component
> Happychat component

- client/me/profile-gravatar/index.jsx
- client/me/profile-gravatar/style.scss
- client/me/sidebar/index.jsx
- client/me/sidebar/style.scss
Before:
After:
Also trying a transition effect.
Test live: https://calypso.live/?branch=update/me-gravatar
> Me: GravatarProfile and sign out button

- client/components/domains/register-domain-step/index.jsx
- client/components/search-card/index.jsx
- client/components/search/index.jsx
- More strict validation for search term
- Add maxLength field to SearchCard
Test live: https://calypso.live/?branch=update/fix-suggestion-queries
> Domains: Don't check availability if input isn't a domain

- client/lib/analytics/ad-tracking.js
This PR adds Quantcast purchase conversion tracking to Calypso so that we can measure our return on ad spend for [Quantcast's advertising platform](https://www.quantcast.com/advertise/).
For reference when reviewing this implementation, here is the documentation I was provided on how to set up the tracking:
```-----------------------------------------------------------------------
Purchase Confirmation Tag
***Add this tag to the Purchase Confirmation page and update INSERT+PRODUCT+CATEGORY, INSERT+ORDER+ID and INSERT+REVENUE place holders with variables/macros to pass corresponding dynamic data***
<script type="text/javascript"> 
var _qevents = _qevents || [];
(function() {
var elem = document.createElement('script');
elem.src = (document.location.protocol == "https:" ? "https://secure" : …
```
> Ad Tracking: Add Quantcast conversion tag

- client/lib/abtest/active-tests.js
... to synchronize it with the server-side test and so we have more
time to fix errors that will come up during testing.
Test live: https://calypso.live/?branch=update/paid-nux-ab-test
> NUX: update paid NUX A/B test date

- client/lib/abtest/active-tests.js
- client/signup/steps/theme-selection/signup-themes-list.jsx
<del>WIP.</del> I'll add the test details shortly.
Test live: https://calypso.live/?branch=add/vertical-screenshot-test
> Signup: Add Vertical Screenshots A/B Test

- client/lib/analytics/ad-tracking.js
After discussing which Calypso pages we should fire Quantcast tracking events on with the Quantcast folks, we determined that firing them on all Calypso pages makes the most sense:
> In order to ensure that we do not deliver an ad to cookie who has already been to the site (retargeting) we need have the tag firing on every part of the site. Further, having the entire site tagged will allow Quantcast to provide additional campaign metrics aside from just the conversions we drove like time to convert from first impression to conversion and number of cookies driven to a first site visit.
This PR implements that by adding Quantcast tracking to the ad-tracking module's `retargeting` function.
It also updates that function so that it fires on each page view, not just once when the scripts are …
> Ad Tracking: Fire retargeting events on all Calypso pages

- client/blocks/reader-related-card-v2/docs/example.jsx
- client/blocks/reader-related-card-v2/index.jsx
cc @jancavan this should fix the devdocs display
Test live: https://calypso.live/?branch=fix/busted-devdocs
> Fix up devdocs

- client/blocks/post-status/style.scss
Test live: https://calypso.live/?branch=update/post-status-pending-review
> PostStatus: use the yellow color for pending review.

- client/components/title-format-editor/index.jsx
Resolves #7885 
cc: @rodrigoi @roundhill
> Start title format editor cursor location at end

- client/blocks/upgrade-nudge-expanded/style.scss
Fixes layout issues with the Advanced SEO Settings Nudge on Safari.
cc: @roundhill @lancewillett 
Fixes #7932
> Advanced SEO: Settings Nudge layout issues

- client/components/credit-card-form-fields/index.jsx
- client/my-sites/upgrades/checkout/credit-card-payment-box.jsx
- client/my-sites/upgrades/components/form/input.jsx
> Checkout: disable autocomplete in credit card fields of checkout form

- client/components/title-format-editor/parser.js
Resolves #7886 
Previously, the parer from the API representation of the title format
into the Calypso native representation would generate a single entry in
the entity map for each unique token type.
When multiple tokens of the same type were adjacent, their entity keys
were also adjacent, and being identitical, the editor combined these
tokens into one.
Now, during the parsing process we simply generate a unique entity for
each token regardless of whether or not one of the same type has
previously appeared. This keeps entity keys separate and prevents the
merging behavior.
**Before**
**After**
**Testing**
On master, add multiple tokens of the same type to the end of a title format. Save the results and then refresh the browser. Because the race condition on save isn't completely …
> SEO: Custom title: stop merging adjacent tokens

- client/blocks/reader-related-card-v2/style.scss
> Reader: Fix links causing cards to display incorrectly

- client/blocks/reader-full-post/index.jsx
But only if they're not also in the content.
Fixes #7822
> Reader: Add in featured images above the post

- client/blocks/reader-full-post/index.jsx
- client/blocks/reader-related-card-v2/style.scss
More from WPCOM where getting cut off prematurely. Also switch to 'on WPCOM' not 'from WPCOM'.
> Reader: Fix up styles on wpcom related posts, wording in title

- client/components/follow-button/button.jsx
It's not really just a tagName, it's also a tag or a function that can be a tag.
No functional change, just silences a warning in the console when opening the Post Options
> Reader: Expand proptypes for tagname

- client/blocks/comments/style.scss
> Reader: Make timestamp color in Comments darker

- client/components/rating/test/index.js
- Add tests for the Rating component, as part of the advanced Calypso course at the GM
> Components: Add <Rating /> Tests

- docs/server-side-rendering.md
Some updates to reflect current state and best practices, plus some minor fixes (especially the link to the iso docs).
/cc @aduth @ehg
> Docs: Update server-side-rendering.md

- client/me/help/help-contact/index.jsx
> Fix a typo in the help post-submit view.

- client/blocks/reader-related-card-v2/style.scss
This PR fixes a few indentation errors found by mixedindentlint through make lint.
To test:
- check out `master` and run `make lint`, see that there are indentation errors
- check out this branch and run `make lint`, see that the indentation errors are gone
> Framework: indentation fixes

- client/lib/stats/stats-list/index.js
- client/lib/stats/stats-list/stats-parser.js
- client/lib/wpcom-undocumented/lib/site.js
- client/my-sites/stats/controller.js
- client/my-sites/stats/site.jsx
- client/my-sites/stats/stats-strings.js
- client/my-sites/stats/summary/index.jsx
- config/development.json
Reverts Automattic/wp-calypso#8109
Wait until the endpoint is deployed to prevent 404s
> Revert "Stats: Podcast stats"

- client/components/social-logo/index.jsx
- client/my-sites/posts/post-share.jsx
Fixes minor issues with Publicize feature introduced in #8104
> GM16/Publicize: minor fixes

- client/blocks/reader-full-post/index.jsx
We missed `l` as a keyboard shortcut in the full post refresh. This hooks it up.
Fixes #8121
> Reader: Add l to toggle to likes in new full post view

- client/reader/full-post/_style.scss
> Reader: Fix alignnone outside captions

- client/lib/wpcom-undocumented/lib/undocumented.js
This PR return the promise for the `getAvailableUpdates()` undocummented method.
> WPCOM: return the Promise for for getAvailableUpdates()

- client/components/progress-bar/test/index.jsx
To test:
`npm run test-client client/components/progress-bar`
> Adding tests for ProgressBar component (fixed #7945)

- client/boot/index.js
- client/lib/catch-js-errors/README.md
- client/lib/catch-js-errors/index.js
- client/lib/catch-js-errors/log.js
This resolves #8061.
Introduces `log` function to be used for tracking hard-to-replicate actions
Imagine you have:
- A piece of code you suspect is dead
- Function that is triggered by weird parameters
- Place you dont know how many people reach
Than this solution is for you!
* Start local dev with `ENABLE_FEATURES=catch-js-errors make run`
```
import log from 'lib/catch-js-errors/log';
//Something unusual happened
log( 'This is unexpected', { additionalData: 'data' } );
```
It should appear in Kibana: fdab46b5d265c5d7d442b5293a0b1a17-logstash
CC @gwwar @lamosty @aduth
> JS Errors: Log arbitrary data

- client/blocks/comments/style.scss
**Before:**
Expanded:
Collapsed:
No comments:
**After:**
Expanded:
Collapsed:
No comments:
> Reader: Fix comment heading spacing

- client/components/section-nav/style.scss
- client/components/select-dropdown/docs/example.jsx
- client/components/select-dropdown/index.jsx
- client/components/select-dropdown/item.jsx
- client/components/select-dropdown/style.scss
- client/devdocs/design/style.scss
This PR fix some visual issues of the `<SelecDropdown />` component. Please take a look to #4971 to read more about these ones.
#4971 
**devdocs testing page**
http://calypso.localhost:3000/devdocs/design/select-dropdown
---------------------------
**posts count - english**
---------------------------
**posts count - spanish**
---------------------------
**posts count - no idea**
cc @lancewillett @mtias
> SelectDropdown: fix visual issues

- client/components/popover/README.md
- client/components/popover/index.jsx
* Update the popover documentation - `Readme.md`
* ~~Re-write the component instance using ES6 and class~~ already done in #7866 
* ~~Remove some examples~~ already done in #7866 
1. Open the devdocs popover page: http://calypso.localhost:3000/devdocs/design/popover
2. Play with the instances. everything should be ok.
Test live: https://calypso.live/?branch=update/popover-doc
> Popover: doc and example improvements

- docs/our-approach-to-data.md
Dan Abramov's article about React components has a new title. Updating docs to reflect that change.
> Documentation: Our Approach to Data - update link to article from Dan Abramov

- client/components/forms/form-text-input/test/index.jsx
Add tests for the form text input component. 
Closes: #7944 
Test: `npm run test-client client/components/forms/form-text-input/test/index.jsx`
> Components: Add <FormTextInput /> tests

- Makefile
- README.md
- npm-shrinkwrap.json
- package.json
- webpack.config.js
Reverts Automattic/wp-calypso#8272
> Revert "Add/webpack dashboard"

- client/blocks/reader-related-card-v2/style.scss
**Before (with image):**
**Before (text only):**
**After (with image):**
**After (text only):**
> Reader: Fix excerpt cut off in More on wpcom

- client/components/happychat/timeline.jsx
You can see the welcome message by clicking the Support Chat link at the bottom of the sidebar.
Screenshot:
> Support Chat: Improve welcome message.

- client/components/tinymce/plugins/wplink/dialog.jsx
> Editor: Recognise emails in the link editor #8088

- client/my-sites/site-settings/seo-settings/form.jsx
- client/my-sites/site-settings/style.scss
Do not merge - requires API changes to be deployed first.
Allow non-business users that have already set Website Meta to
continue viewing and editing it on SEO settings page.
Test live: https://calypso.live/?branch=update/seo-front-page-meta
> Advanced SEO: grandfather Website Meta

- assets/stylesheets/shared/_extends.scss
This is not in use. No visual changes. :)
> Removed unused %status @extends

- config/horizon.json
- config/production.json
- config/stage.json
- config/wpcalypso.json
Add the preview seo nudge to other environments (including production)
> Advanced SEO: Show Preview nudge in Production

- client/blocks/reader-full-post/style.scss
> Reader: Clear the action links so they always fall after post content

- client/lib/abtest/active-tests.js
- client/signup/steps/theme-selection/signup-themes-list.jsx
> Signup: Remove Vertical Screenshots A/B Test

- client/my-sites/themes/theme-filters.js
Add the new theme feature tag:
cc: @folletto for review
> Themes: Add fixed-menu term to theme filters

- client/my-sites/upgrades/domain-management/transfer/unlocked.jsx
When a domain is not pending transfer, we would try to cancel the transfer through the API, which would result in an error.
> Domains: Do not try to cancel transfer if domain is not pending transfer

- client/components/search/README.md
- client/components/search/index.jsx
- client/components/search/style.scss
- client/my-sites/themes/theme-filters.js
- client/my-sites/themes/themes-magic-search-card/index.jsx
- client/my-sites/themes/themes-magic-search-card/style.scss
#8395 again, with fix for `Uncaught TypeError: Cannot read property 'scrollLeft' of undefined`
**To Test**
* See #8395 
* Go to http://calypso.localhost:3000/posts/my, click on a blog post, should not see the error:
`Uncaught TypeError: Cannot read property 'scrollLeft' of undefined`
> Search styling overlay, take two

- server/render/index.js
Lo and behold.
Fixes https://github.com/Automattic/wp-calypso/pull/8421#issuecomment-251923967
cc @sendhil @seear @ehg
> Desktop: Fix

- client/my-sites/themes/themes-magic-search-card/index.jsx
- client/my-sites/themes/themes-magic-search-card/style.scss
Ripped from @budzanowski's M5 spike, #8282.
> Themes: Add Pills Styling to Search

- .dockerignore
- Dockerfile
Reverts Automattic/wp-calypso#8516
Breaks images.
> Revert "Update the Dockerfile for building and testing Calypso"

- .eslintrc.js
- client/lib/plugins/notices.jsx
- client/my-sites/invites/utils.js
- client/my-sites/media-library/index.jsx
- client/my-sites/media-library/list-plan-promo.js
- client/my-sites/plugins/plugins-list/index.jsx
- client/state/reader/feeds/reducer.js
- client/state/sites/vouchers/reducer.js
- client/state/wordads/approve/reducer.js
Related: #8562
This pull request continues the crusade to upgrade all ESLint rules to errors by resolving remaining issues with [`no-unreachable` rule](http://eslint.org/docs/rules/no-unreachable).
__Testing Instructions:__
That CircleCI passes is indication that the changes included are working as intended.
> Framework: Upgrade ESLint no-unreachable to error

- webpack.config.node.js
Introduced in #7636 
cc @aduth
> Fix eslint error

- client/components/gridicon/docs/example.jsx
- client/components/gridicon/index.jsx
This version includes a new Chat icon.
See also: https://github.com/Automattic/gridicons/pull/182
To test:
- `make run`
- Verify that gridicons across the board still appear.
Screenshot:
The fact that we're updating the entire gridicons react component every time a new icon is added isn't ideal. Perhaps we can get some code-help to [bring home the NPM package](https://github.com/Automattic/gridicons/issues/98)? ;)
> Gridicons: Update to latest version.

- client/lib/abtest/active-tests.js
Update the Verticals V2 AB test percentages to 50/50 from 80/20.
cc @meremagee @michaeldcain @coreh
> Signup: Update Verticals V2 AB test percentages.

- client/my-sites/pages/blog-posts-page.jsx
- client/my-sites/pages/page-list.jsx
- client/my-sites/pages/style.scss
- config/development.json
*Note: This PR is part of a larger epic to bring the ability to set the homepage from the Pages screen. For now, it is behind the `manage/pages/set-homepage` feature flag, which is only enabled in `development`.*
In a typical site setup your Front Page has static content, and there is an actual page behind the front page. Your recent blog posts are not accessible.
In the dashboard (wp-admin), this setup looks like this:
As long as your front page displays your latest posts, there is an entry indicating this in Calypso Pages:
However, after setting a page as your front page, right now this Blog Posts page disappears in Calypso Pages. We will make it stay (this PR), giving the user a way to revert to the state of displaying the recent posts on the Front Page (future PR).
While an actual …
> Pages: Show placeholder for Blog Posts page

- client/components/card/test/index.js
Introduce tests for the <Card/> component. Tests include:
**Card**
* should have `card` class
* should have custom class of `test__ace`
* should render children
* should be linkable
**CompactCard**
* should have `is-compact` class
* should have custom class of `test__ace`
* should render children
* should use the card component
Closes #7939
To run these tests use:
```
npm run test-client client/components/card
```
cc @jeremeylduvall
> Components: Add <Card /> tests

- client/my-sites/themes/theme-filters.js
Generated using https://github.com/seear/theme-taxonomies/pull/1
See #7226
> Themes: Add theme-picks to filters

- client/components/notice/index.jsx
- client/components/notice/test/index.js
The intention of this is to fix #7941. This is my first unit test and also part of a Calypso class, so would eyes on this. The test looks for the output of the component itself, dismiss buttons, compact looks and status classes. CC: @aduth
To test, `npm run test-client client/components/notice/test/index.js`.
Screenshot:
> Notice: Add unit tests

- assets/stylesheets/_components.scss
- client/blocks/reader-post-card/docs/example.jsx
- client/blocks/reader-post-card/index.jsx
- client/blocks/reader-post-card/style.scss
- client/devdocs/design/blocks.jsx
- client/reader/_style.scss
- client/reader/controller.js
- client/reader/following/main.jsx
- client/reader/stream/index.jsx
- config/development.json
- **Card with thumbnail and excerpt:**
- **Mobile:**
> Reader: Add new thumbnail and excerpt component for Refresh

- client/reader/_style.scss
> Reader: Fix stray red line that slipped in

- client/my-sites/plans/current-plan/header.jsx
- client/state/sites/plans/assembler.js
Reverts Automattic/wp-calypso#8677
> Revert "Plans/My-Plan : better auto renew information"

- client/blocks/domain-to-plan-nudge/index.jsx
- client/blocks/plan-thank-you-card/index.jsx
- client/blocks/upgrade-nudge-expanded/index.jsx
- client/lib/plans/constants.js
- client/lib/plans/index.js
- client/my-sites/plans/current-plan/index.jsx
This broke staging. Don't know why, will investigate further
> Revert "Fix/plans screaming case"

- client/blocks/reader-post-card/index.jsx
No functional changes. Just whitespace.
> Reader: Fix indentation on reader-post-card

- client/blocks/reader-post-card/index.jsx
Also comment the regexp to explain what it does.
No effective functional changes.
> Reader: Use whitespace pattern instead of plain space

- client/my-sites/theme/test/main.jsx
> Themes: Add renderToString() test for theme info page

- assets/stylesheets/shared/_extends.scss
- client/my-sites/stats/stats-module/style.scss
It was only used once and @extends are bad. :) No visual changes.
> Removed %placeholder-icon @extend from CSS

- client/blocks/author-compact-profile/index.jsx
- client/blocks/reader-author-link/index.jsx
- client/blocks/reader-post-card/byline.jsx
- client/blocks/reader-post-card/index.jsx
- client/blocks/reader-post-card/style.scss
This PR adds the real author, site, relative post time and primary tag to the header of the new Reader stream cards:
> Reader Stream Refresh: add PostByline sub-component

- client/post-editor/media-modal/index.jsx
> Media: Default to showing list when view unknown

- client/lib/feed-stream-store/index.js
- client/reader/recommendations/controller.js
- client/reader/recommendations/index.js
- client/reader/sidebar/index.jsx
First mostly working attempt at this. Still need to finish adjusting the api side.
> Add Reader Test Streams for testing variations of cold start post recommendations

- client/blocks/reader-full-post/index.jsx
Piggy-backs on how we're doing this for new style streams.
No real functional changes, but fewer network requests if you're using the refreshed streams.
> Reader: Use redux state for feeds and sites in full post

- client/lib/analytics/ad-tracking.js
This PR adds a different bing track code for jetpack plans purchases. I'm not 100% sure about it working as I expect (and it's hard to test without testing in production), so I would love some review from someone with experience in the matter ( @drewblaisdell  ? ).
> Tracking: Adds a new bing tracking code for jetpack

- client/my-sites/upgrades/domain-search/domain-search.jsx
Privacy was added as a separate item and would result in 2 dispatcher fires
> Domains: Push all cart items together in domain search

- client/layout/style.scss
This is a fix for bug #353 and it prevents the sidebar and top navbar (masterbar) from displaying on media print.
This is my first pull request for this project so please correct me in anything I did wrong :)
> #353 prevented sidebar and master bar from displaying when printing a page.

- .dockerignore
- Dockerfile
Reverts Automattic/wp-calypso#8603
The build failed…
> Revert "Update Dockerfile adding back in `public` directory"

- client/lib/signup/step-actions.js
- client/signup/config/steps.js
- client/signup/steps/plans/index.jsx
Auto add privacy protection if a non-free plan is purchased during NUX
> NUX & Domains: Auto Add Privacy Protection if plan is bought

- client/blocks/post-status/index.jsx
- client/post-editor/editor-post-type/index.jsx
- client/post-editor/editor-post-type/style.scss
Give a quick visual indication of the current status of a post you are editing:
> Editor: display current status of post in the header.

- config/development.json
- config/wpcalypso.json
Since it mostly works, start showing it to folks.
> Reader: Turn on the refresh stream in dev and wpcalypso.

- assets/stylesheets/shared/functions/_z-index.scss
- client/blocks/reader-full-post/index.jsx
- client/blocks/reader-full-post/style.scss
This addresses: https://github.com/Automattic/wp-calypso/issues/8791
/cc @fraying
> Reader: Add Visit Site link to Refresh full-post

- client/components/happychat/composer.jsx
- client/me/happychat/main.jsx
Addresses some issues around accessibility for Happychat
> Add accessiblity helpers for Happychat

- client/blocks/reader-full-post/style.scss
Fixes warning being thrown when building calypso's css
> Reader: Add missing units on breakpoint

- client/components/suggestions/style.scss
- client/my-sites/themes/themes-magic-search-card/style.scss
- client/my-sites/themes/themes-magic-search-card/taxonomy-styling.js
- client/my-sites/themes/themes-magic-search-card/welcome.jsx
Updated the suggestions styling. Still not identical to the designs, but incrementally closer.
PR status:
> Themes: update search suggestions styling

- client/blocks/reader-avatar/index.jsx
- client/blocks/reader-post-card/byline.jsx
- client/blocks/reader-post-card/style.scss
- client/reader/start/style.scss
Suppress the rss icon from the stream and add some logic to pick either the site icon or the gravatar, leaning towards the site icon.
> Reader: Suppress the rss icon and add some logic to pick the 'best' icon

- client/lib/abtest/active-tests.js
- client/signup/steps/domains/index.jsx
Please see this discussion: p6qnuF-3qk-p2
> Add new AB test for removing G Suite from the signup flow.

- client/components/suggestions/index.jsx
- client/my-sites/themes/themes-magic-search-card/index.jsx
- client/my-sites/themes/themes-magic-search-card/taxonomy-styling.js
- client/my-sites/themes/themes-magic-search-card/welcome.jsx
Fix bad code found in reviews for #8282
Use ES6 when possible.
Use functional style when possible.
Fix sloppy code.
> Fix bad code style found in Suggestions. 

- config/production.json
PR in case when we need to disable Happychat
> Disable Happychat config

- config/wpcalypso.json
No code changes, just turns on refresh streams on wpcalypso.
> Reader: Turn on refreshed streams on wpcalypso

- client/components/seo/meta-title-editor/index.jsx
Copy update to the SEO site title tag. Fixes #8254 
Needs review! @dmsnell
> SEO: Copy change of Site Name -> Site Title

- client/signup/config/steps.js
> Add privacyItem to the list of dependencies for the get-dot-blog-plans step

- client/blocks/reader-post-card/style.scss
Shrink the title to 25px
Give the features some room when they go above the title
> Reader: Tweaks to spacing in streams

- .eslintrc.js
- client/components/domains/domain-search-results/index.jsx
- client/components/tinymce/plugins/wpcom-view/plugin.js
- client/components/tinymce/plugins/wpeditimage/plugin.js
- client/lib/mixins/pageable/index.js
- client/my-sites/posts/post-controls.jsx
- client/my-sites/sharing/buttons/preview.jsx
- client/my-sites/stats/stats-list/stats-list-item.jsx
Related: #8562
This pull request continues the crusade to upgrade all ESLint rules to errors by resolving remaining issues with [`no-lonely-if` rule](http://eslint.org/docs/rules/no-lonely-if).
__Testing Instructions:__
That CircleCI passes is indication that the changes included are working as intended.
Verify that no regressions have been introduced to affected sections.
> Framework: Upgrade ESLint no-lonely-if to error

- client/components/domains/map-domain-step/index.jsx
We no longer need this notice/error, as there are .blog domains in the wild. :)
> Remove `dotblog_domain` error from `MapDomainStep`

- client/my-sites/people/invite-people/index.jsx
- client/my-sites/plans/current-plan/index.jsx
- client/state/ui/first-view/actions.js
Fixes events rejected by tracks. Tracks events prop names have to be snake case.
Event names also have to be snake case.
Problem was first reported by @lucasartoni in p4TIVU-4VF-p2
Since we know these events are rejected, there is no harm in fixing these.
Once they are fixed, the'll stop occupying space in rejected view so we can see what other events are rejected also.
CC @gwwar @lamosty @lucasartoni  @rralian
> Fix tracks events

- client/blocks/reader-post-card/gallery.jsx
- client/blocks/reader-post-card/index.jsx
- client/blocks/reader-post-card/style.scss
- client/state/reader/posts/normalization-rules.js
Fixes #8520.
A feed with several gallery posts: http://calypso.localhost:3000/read/feeds/15197253
> Reader Stream Refresh: add gallery card

- client/components/data/document-head/README.md
* Remove note about being WIP
* Remove `description` prop since this doesn't exist anymore.
cc @aduth
> DocumentHead: Update README.md

- assets/stylesheets/_components.scss
- client/my-sites/media/main.jsx
- client/my-sites/media/style.scss
- client/my-sites/sidebar/publish-menu.jsx
- client/post-editor/media-modal/detail/index.jsx
- client/post-editor/media-modal/index.jsx
- client/post-editor/media-modal/test/index.jsx
- config/wpcalypso.json
Reverts Automattic/wp-calypso#8619
We had to revert media section V1 because the sidebar item was showing on environments it wasnt supposed to.
CC @gwwar
> Revert "Media Section: v1"

- client/me/help/help-contact/index.jsx
In dev environment you can not tell what chat service you will get when launching "Chat with us"
So to avoid launching unnecessary Olark chats, explicitly label the button with Happychat
> Happychat - add explicit label in dev env to chat button

- .dockerignore
- .eslintignore
> vscode ignored by all-the-things (as requested in #9029)

- client/me/help/help-happiness-engineers/index.jsx
- client/state/happiness-engineers/selectors.js
- client/state/happiness-engineers/test/selectors.js
- Add selector to check if we have loaded the happiness engineers
from network
- Add tests
Test:
Make sure the happiness engineer icons are loaded on the Help screen: http://calypso.dev:3000/help
Make sure they are loaded only once from network
> Happiness Engineers: Add selector to check if we received HEs

- client/my-sites/themes/controller.jsx
- client/my-sites/themes/single-site.jsx
- client/my-sites/themes/themes-selection.jsx
Reverts Automattic/wp-calypso#9196
Turns out  switching the theme showcase between individual sites was broken by this PR :-(
> Revert "Themes (single-site): Fix siteId/siteSlug mixup"

- client/me/help/help-contact/index.jsx
Staging environment is not called staging, nor uses the env config.
To show "Happychat" on button in staging need to check: env_id === stage
> Fix label for Happychat button in staging environment

- client/lib/cart-values/cart-items.js
- client/lib/products-values/index.js
Reverts Automattic/wp-calypso#9216
> Revert "Domains: Improve free subdomain handling in domain suggestion screen"

- config/production.json
Deploys SEO Tools feature for Jetpack sites to production.
> SEO Tools: enable feature flag in production

- client/post-editor/editor-drawer/index.jsx
> SEO Tools: Update min version to support current Jetpack beta name.

- client/signup/jetpack-connect/authorize-form.jsx
Quick fix for a botched deploy
> JPC: Fix for approve button

- config/development.json
- config/stage.json
Development and staging configs connect to non-production version of the happychat server.
> Happychat: development and stage environments use a staging happychat server

- client/reader/_style.scss
Fade in, position bottom right. Less obtrusive this way.
Test live: https://calypso.live/read/feeds/25801/posts/1050231304?branch=fix/reader/tiled-gallery-overlay
> Reader: Fancy up the tiled gallery overlay

- client/components/domains/register-domain-step/index.jsx
Add a different message when someone searches for .blog
> Domains: Add coming soon message for `.blog`

- client/blocks/reader-full-post/_content.scss
> Reader: Center twitter embeds in the full post view

- client/components/domains/map-domain-step/index.jsx
- client/components/domains/register-domain-step/index.jsx
Add message when we have an ongoing TLD maintenance
Needs: D3366-code
> Domains: Add message for TLDs in maintenance

- client/components/reader-main/index.jsx
- client/reader/following-edit/index.jsx
- client/reader/stream/index.jsx
Move to FollowingEdit, where it belongs.
> Reader: Pull config check out of ReaderMain

- client/signup/jetpack-connect/plans.jsx
During today's merge of personal plan, I rebased away some changes that were on master's jpc plans version. This PR is just for restoring the old file (And yeah, I should pull before rebase, I know, I know, I'm sorry)
> JPC: restore plans page rebased away

- client/my-sites/theme/controller.jsx
This is a super small change born from @seear's comment on https://github.com/Automattic/wp-calypso/pull/8942#issuecomment-257555213
As with the Theme Showcase, we unfortunately still have to track a `timestamp` to use as a unique version identifier for `renderCacheKey`, but at least this prevents us from screwing up some important math when deciding whether to use cached data. This also gives us an upper limit on theme cache size — set right now to 500, which is still bigger than the max 371 themes I could load in the Theme Showcase.
Validate correctness with `DEBUG=calypso:themes make run` and check that on first server-request for a theme detail page such as http://calypso.localhost:3000/theme/label, you see the theme data cached with a `caching` console debug message, and subsequent …
> Theme Details: Use Lru for SSR data cache

- client/state/themes/selectors.js
Just a name change.
This code is not connected yet.
> Correct name of isRequestingSiteTheme selector to isRequestingTheme

- client/components/domains/register-domain-step/index.jsx
Add a dismissible mesesage on domain search saying that .blog is a new and available TLD
> Domains: Add a persistent message for .blog on domain search

- config/desktop.json
- config/production.json
- config/test.json
Not a lot to see here... this PR adds jetpack personal plan to our jetpack plans offer, in production (it was already available if you were using staging)
> Jetpack Personal Plan: open in production

- client/reader/post-time/index.jsx
No functional changes, just moving to es6.
To test, pull up the main reader stream and wait a few minutes. The humane dates on the posts should change over time.
> Reader: Convert PostTime to an es6 class

- client/state/ui/first-view/selectors.js
- client/state/ui/guided-tours/selectors/find-ongoing-tour.js
- client/state/ui/guided-tours/selectors/index.js
- client/state/ui/guided-tours/test/fixtures/config.js
- client/state/ui/guided-tours/test/selectors.js
Second attempt at merging #9241 after timing issues in unit tests broke the test suite.
> Guided Tours: Avoid collisions with First View (take 2)

- client/reader/sidebar/_style.scss
- client/reader/sidebar/expandable-add-form.jsx
- client/reader/sidebar/expandable.jsx
- client/reader/sidebar/index.jsx
- client/reader/sidebar/reader-sidebar-lists/index.jsx
- client/reader/sidebar/reader-sidebar-lists/list-item.jsx
- client/reader/sidebar/reader-sidebar-lists/list.jsx
- client/reader/sidebar/reader-sidebar-tags/index.jsx
- client/reader/sidebar/reader-sidebar-tags/list-item.jsx
- client/reader/sidebar/reader-sidebar-tags/list.jsx
- client/reader/sidebar/reader-sidebar-teams/index.jsx
- client/reader/sidebar/reader-sidebar-teams/list-item.jsx
- Turn off lists sidebar for folks who do not have any lists
- Turn off add / manage links in general
Originally #9269
Fixes #9195
> Reader: Work in changes to lists for upcoming refresh

- client/reader/stream/index.jsx
To test, pull up all of the Reader streams and make sure common actions work. Keyboard shortcuts / like / share / comment link / open article / etc.
> Reader: ES6ify the Reader Stream

- client/me/purchases/remove-purchase/index.jsx
This pull request adds tracks pings for precancellation chat on the purchase removal survey
If precancellation chat is not enabled in network admin you can sandbox the public api and apply the diff at 16e6b
1. Navigate to http://calypso.localhost:3000/me/purchases/
2. Select a product to cancel
3. Click the "Remove WordPress.com Business" (or whatever the product is)
4. If operators are available you should see the chat with us link
5. Click the chat with us link
6. Clicking the link should have pinged tracks with `calypso_precancellation_chat_click`
7. Notice that the olark chatbox appears in the lower right corner.
8. Enter some text in the chatbox and send it.
9. The action of starting the chat here should have pinged tracks with `calypso_precancellation_chat_begin`
Related to #9261
> Add tracks pings to the precancellation chat feature

- client/blocks/reader-post-card/byline.jsx
> Reader: Show the author if we're forcing the sitename hidden

- client/state/themes/selectors.js
- client/state/themes/test/selectors.js
This PR adds selectors from the PR title with accompanying them unit tests.
Not connected yet.
> Add isRequestingActiveTheme, getActiveTheme, isActiveTheme selectors.

- config/wpcalypso.json
Enable the upload route/page added in #9575 
cc @folletto
> Themes: Turn on upload feature on wpcalpyso env

- client/components/data/query-active-theme/README.md
- client/components/data/query-active-theme/index.jsx
Add a new QueryTheme query component for use with the new themes Redux state architecture.
Uses actions from #9604, but can be merged independently.
This PR is similar as #9520 and #9536
Not covered by tests -- will be wired with #8785.
> QueryActiveTheme Add

- client/components/themes-list/index.jsx
How did this even not break? :facepalm:
To test -- verify that the showcase still works.
> ThemesList: Fix shouldComponentUpdate() method

- client/my-sites/posts/post-share.jsx
- client/my-sites/posts/style.scss
Fixes #9687 
Fixes google plus icon in publicize actions, which stopped displaying some time ago.
CC @gwwar @gziolo
> Publicize: Fix google plus icon

- client/reader/stream/_style.scss
- client/reader/stream/recommended-posts.jsx
This fixes: https://github.com/Automattic/wp-calypso/issues/9695 as well as spacing issues.
**Before:**
**After:**
> Reader: Fix in-stream recs alignment and spacing

- client/reader/tag-stream/style.scss
> Reader: Uncap the tag name in the tag stream header

- client/my-sites/posts/post-share.jsx
- client/my-sites/posts/style.scss
This resolves #8291 and redesigns re-publicize window according to @drw158 design.
No functional changes
CC @gwwar @gziolo @bikedorkjon @enejb
> Publicize: redesign

- client/my-sites/posts/post-share.jsx
- client/my-sites/posts/style.scss
Improves the derign of publicize window when no services are connected, according to @drw158 design #8256
CC @gwwar @drw158 @enejb @gziolo
> Publicize: Improve disabled state design

- assets/stylesheets/_components.scss
- client/my-sites/stats/stats-navigation/index.jsx
> Stats: refactor navigation to use latest ES6.

- client/lib/checkout/index.js
- client/my-sites/upgrades/checkout/checkout.jsx
- client/my-sites/upgrades/controller.jsx
Reverts Automattic/wp-calypso#9429
Looks like the image failed to build, reverting.
> Revert "Sites-list: Remove dependency from upgrades/checkout"

- assets/stylesheets/_components.scss
- client/my-sites/stats/stats-navigation/index.jsx
Reverts Automattic/wp-calypso#9758
> Revert "Stats: refactor navigation to use latest ES6."

- assets/stylesheets/_components.scss
- client/my-sites/stats/stats-navigation/index.jsx
> Stats: refactor navigation to use latest ES6 (again)

- client/reader/stream/index.jsx
Now 30, was 49. At the request of @fraying
> Reader: Turn down the max distance between recs

- client/reader/tag-stream/header.jsx
- client/reader/tag-stream/main.jsx
- client/reader/tag-stream/style.scss
> Reader: Update Back button in Tag streams

- client/lib/post-normalizer/rule-create-better-excerpt-refresh.js
- client/lib/post-normalizer/test/index.js
Fixes #9523
use the URLs from the bug report to test.
> Reader: Trim the better excerpt

- assets/stylesheets/shared/functions/_z-index.scss
- client/blocks/reader-post-card/style.scss
> Reader: Fix photo card overlay overlapping with sidebar

- client/my-sites/plugins-wpcom/jetpack-plugins.js
Fixes: https://github.com/Automattic/wp-calypso/issues/9607
Moved up paid upgrades.
> Plugins: Jetpack features listed by importance

- client/lib/feed-stream-store/feed-stream.js
Prep for dismissable recs.
No feature changes.
> Reader: es6ify the feed-stream

- client/my-sites/sidebar/sidebar.jsx
This change refreshes the logic in sidebar for showing WP Admin link to legacy users.
To match WordPress.com front-end navigation, any user registered on WordPress.com before September 7, 2015 should see a "WP Admin" link at the bottom of their site's sidebar.
Removes the need to call the deprecated (and unused anywhere as far as I can see) user meta `flags` that are a holdover from Atlas (Newdash). I created a separate janitorial type PR could clean out the way that's pulled into the user data object, see #9765.
To test:
1. Log in with various users, bonus if you know the registration date of the user and can test 1 before and 1 after September 7, 2015.
2. If the user registered before that date, make sure the WP Admin links shows up at the bottom of the sidebar. <img width="320" …
> Sites: show WP Admin link in sidebar to legacy users only (including VIP)

- client/reader/tag-stream/header.jsx
- also removed the blog title in favor of only displaying author
See #9734
> Reader Refresh: Tag Headers Link To Post

- client/reader/_style.scss
> Reader: Fix Drake in empty Search

- client/blocks/reader-full-post/index.jsx
> Reader: Reduce initial comment fetch to 10

- client/lib/plans/constants.js
- config/development.json
Adds a 6GB storage option for the Personal Plan behind a feature flag.
cc: @roundhill
> Personal Plan: 6GB Storage option

- client/components/domains/register-domain-step/index.jsx
- client/signup/config/flows.js
- client/signup/steps/domains/index.jsx
Reverts Automattic/wp-calypso#8935
> Revert "Signup: Improve the `developers` signup flow for simplicity and speed."

- assets/stylesheets/shared/functions/_z-index.scss
- client/blocks/reader-feed-header/index.jsx
- client/blocks/reader-feed-header/style.scss
- client/blocks/reader-post-card/style.scss
- client/reader/_style.scss
- client/reader/feed-stream/index.jsx
- client/reader/site-stream/index.jsx
- client/reader/tag-stream/header.jsx
- client/reader/tag-stream/main.jsx
The "Back" button should look like this in wider viewports:
> Reader: Update Back button to match Refresh mockup

- client/lib/wpcom-undocumented/lib/undocumented.js
Undocumented implementation of call to 
// POST  /sites/%s/themes/%s/install
Used by action implementation in #9924
> Undocumented: Install WP.com theme on Jetpack

- client/reader/search-stream/style.scss
This fixes: https://github.com/Automattic/wp-calypso/issues/9783 and card spacing inconsistencies.
**Before:**
**After:**
> Reader: Fix Search recs card spacing inconsistencies

- client/layout/guided-tours/README.md
This PR adds descriptions for the existing tours to the Guided Tours README. 
To test:
- check copy
> Guided Tours: add descriptions for existing tours to docs

- client/components/sites-dropdown/README.md
- client/me/help/help-contact-form/index.jsx
I just noticed a mistake in this #9754 PR of mine.
The error does not seems to cause any visual regression on master, however it's important that we fix it, cause it breaks the sites-dropdown component in the contact form on the PR #9624.
> Fix state property name

- client/reader/_style.scss
- client/reader/feed-error/index.jsx
- client/reader/feed-stream/empty.jsx
- client/reader/following-edit/empty.jsx
- client/reader/site-stream/empty.jsx
- client/reader/stream/empty.jsx
Recommendations is going away, so link to search instead.
> Reader: Rework empty content placeholders to link to search

- client/blocks/reader-full-post/_content.scss
- client/lib/wpcom-undocumented/lib/undocumented.js
- client/reader/_style.scss
- client/reader/lib/content-width/index.js
Helps tiled galleries render correctly. This pretty much assumes that folks don't resize their browser window.
~~more info coming shortly.~~
todo:
> Reader: Pass a content_width to the API

- config/horizon.json
- config/stage.json
enables the new look on stage and horizon.
new look:
was:
> Reader: Release the refresh to staging and horizon

- client/blocks/reader-post-card/style.scss
> Reader: Let post-details grow to fit the space

- config/production.json
Just like #10044, but for production too.
`<insert appropriate gif here>`
> Reader: Release Reader Refresh to Production

- client/state/themes/selectors.js
- client/state/themes/test/selectors.js
- client/state/themes/utils.js
Removing stuff that has become obsolete as of #8785
> Themes: Remove old isPremiumTheme util, use isThemePremium selector instead

- client/blocks/reader-post-card/featured-video.jsx
- client/components/data/query-reader-thumbnails/README.md
- client/components/data/query-reader-thumbnails/index.jsx
- client/lib/post-normalizer/rule-content-detect-media.js
- client/lib/post-normalizer/rule-pick-canonical-media.js
- client/state/reader/reducer.js
- client/state/reader/thumbnails/actions.js
Reverts Automattic/wp-calypso#10070
> Reader Refresh: Vimeo support, take two

- client/blocks/reader-post-card/index.jsx
- client/blocks/reader-post-card/style.scss
- client/state/reader/posts/normalization-rules.js
> Reader: Try out excerpts with line breaks in them

- client/me/notification-settings/settings-form/locales.js
- client/me/notification-settings/wpcom-settings/index.jsx
- client/me/sidebar/index.jsx
This updates the text to be consistent with iOS. Just some simple string updates!
> Me: update notification settings text

- client/lib/domains/whois/protected-contact-information.js
Change the address for our privacy service.
Test:
- Domains -> Add
- Pick a `.com` domain
- Go to checkout
- Click `Learn More About Privacy Protection`
before:
after:
> Domains: Update KKWNT address

- docs/guide/hello-world.md
I bumped into this and wanted to let a novice not get stuck.
> Made render() code insertion wording clearer.

- client/my-sites/themes/theme-upload/index.jsx
- client/state/notices/middleware.js
- client/state/themes/actions.js
Reverts Automattic/wp-calypso#10118
> Revert "Theme Upload: Move error handling to notices middleware"

- client/blocks/reader-full-post/style.scss
This fixes: https://github.com/Automattic/wp-calypso/issues/9455
**Before:**
**After:**
> Reader: Fix overlap if Author name is long

- client/my-sites/posts/post-share.jsx
Publicize feedback messages may be a bit too flamboyant for some :)
This makes them a bit more bland
CC @gziolo @enejb
> Make copy more bland

- client/my-sites/posts/post-share.jsx
- client/my-sites/posts/style.scss
Presents notices about broken connections in republicize window
1. Set up publicize, set up accounts (ex: twitter)
2. Log in to twitter and break the connection [Revoke access] here: https://twitter.com/settings/applications
3. Go to /sharing/ to see if indeed there is trouble connecting
4. Go to publicize and see notice about twitter being disconnected
5. Would be nice to check for other services :)
CC @enejb @gziolo @bikedorkjon @gwwar @drw158
> Publicize: Notify about broken connections

- docs/guide/hello-world.md
Hi all!
I saw a PR ping up from @johnmaeda that made an improvement to this guide and noticed that there were other areas that looked like they needed a little updating.
I wanted to address the pre-ES6 vestiges, React.createClass etc. to bring the guide up to the current guideline standards.
I also felt a few slight improvements could be made to the wording & grammar. For the non-obvious I'll add comments inline.
I followed through the guide with the new wording & new code and everything went hunky dory!
Would love to hear some feedback though - this was basically just a skim and update, there may be more fundamental changes in the project that could also be echoed out here that I'm just not aware of!
> Update hello-world guide

- client/reader/stream/_style.scss
- client/reader/stream/x-post.jsx
This fixes: https://github.com/Automattic/wp-calypso/issues/9486
**Before:**
**After:**
> Reader: Update styles in x-posts

- client/components/forms/form-country-select/index.jsx
- client/components/forms/form-input-validation/index.jsx
Refactoring FormCountrySelect. It had a bug with duplicate keys in options array. Fixes that and cleans it up.
Shouldn't have any other side effects.
/cc: @klimeryk @aidvu @dzver
> Forms Country Select: Refactor

- .github/CONTRIBUTING.md
Updates to celebrate our PR count!
> Update contribution document with nudge about PR count

- client/my-sites/site-settings/site-icon-setting/index.jsx
This pull request seeks to change the behavior of the site icon settings modal to use an existing media item as the site icon setting if there are no cropping changes to the image. In other words, if a user selects an image that is already square and does not crop it any further, there's no need to upload a new media item; we can simply reuse the existing item.
__Testing instructions:__
1. Navigate to [site settings](http://calypso.localhost:3000/settings)
2. Select a site
3. Click "Change" under Site Icon
4. Select a media item
5. Click Continue
6. (Optional) Crop the image
7. Click Done
8. After settings save, click Change again
9. Note that...
- If no cropping was performed in step 6 and the image was already square, there is no new media uploaded
- If cropping was performed in step 6 …
> Site Settings: Use existing media for site icon if crop unchanged

- .github/CONTRIBUTING.md
- docs/isomorphic-routing.md
> Use relative links in docs for wpcalypso

- client/my-sites/theme/main.jsx
- npm-shrinkwrap.json
- package.json
Reverts Automattic/wp-calypso#10084
> Revert "Framework: Upgrade to react-redux v5, take two"

- npm-shrinkwrap.json
- package.json
Reverts Automattic/wp-calypso#10409
> Revert "Framework: Update to Redux 3.6.0"

- client/lib/application-passwords-data/README.md
- client/lib/connected-applications-data/README.md
- client/lib/detect-history-navigation/README.md
- client/lib/products-list/README.md
- client/lib/scroll-to/README.md
- client/lib/two-step-authorization/README.md
- client/lib/viewport/README.md
- client/my-sites/jetpack-manage-error-page/README.md
As part of #10334 this PR brings the code from a number of readme files up to scratch with es6 and current standards :)
These were very simple and straight forward so I thought I'd batch them up in this case.
> Documentation: Minor updates to a number for readme files

- client/lib/abtest/README.md
As part of #10334 brings the code featured in abtest/README.md up to scratch with es6 and current standards :)
> Documentation: Refactor code blocks in abtest/README.md

- client/lib/plugins/wporg-data/README.md
As part of #10334  this PR brings the code featured in wporg-data/README.md up to scratch with es6 and current standards :)
> Documentation: Refactor code blocks in wporg-data/README.md

- client/layout/guided-tours/config-elements/continue.js
- client/layout/guided-tours/tours/design-showcase-welcome-tour.js
- client/layout/guided-tours/tours/site-title-tour.js
- client/layout/guided-tours/tours/theme-sheet-welcome-tour.js
This PR addresses feedback on themes / design / site title tours (cf. p3Ex-22R-p2). 
To test:
- Go through the respective tours and see whether the copy is good to go.
> Guided Tours: address feedback on themes / design / site title tours

- client/lib/analytics/ad-tracking.js
This PR adds Twitter conversion tracking to Calypso so we can precisely measure the revenue we bring through Twitter.
We fire two events:
- "PageView" from the `retarget()` function, for retargeting purposes.
- "Purchase" from the `recordProduct()` function in order to track conversions.
The implementation is based on the guide in p5uIfZ-4aY-p2
And is also based on Twitter's "universal website tag" code that looks like this (once unminimized):
```
<script>
! function(e,t,n,s,u,a) {
e.twq || ( s = e.twq = function() { 
s.exe ? s.exe.apply(s,arguments) : s.queue.push(arguments);
},
s.version='1.1',
s.queue=[],
u=t.createElement(n),
u.async = ! 0,
u.src = '//static.ads-twitter.com/uwt.js',
a = t.getElementsByTagName(n)[0],a.parentNode.insertBefore(u,a) );
} ( window, document, 'script'); …
```
> Analytics: Add Twitter Conversion Tracking

- client/state/reader/posts/normalization-rules.js
No longer needed as we no longer let images bleed in full post for discover
> Reader: Remove discoverFullBleed rule

- client/my-sites/plugins/plugin-install-button/index.jsx
- client/my-sites/plugins/plugin-meta/index.jsx
Similar to #10223
I am just updating the code to be more in line with the activate toggle component. 
Install a plugin from single plugin view and the single plugin single site view.
> Plugins: Update the Install Plugin component to match the activate toggle component

- client/layout/guided-tours/README.md
`docs/ARCHITECTURE.md` is changed in #10536.
> Guided Tours: remove "in progress" phrase from docs

- client/reader/following-edit/list-item.jsx
Not just the icon object. It can be mostly empty.
> Reader: Verify that the icon URL exists

- client/components/count/docs/example.jsx
- client/components/count/index.jsx
- client/components/count/test/index.jsx
- client/components/section-nav/item.jsx
- client/state/themes/utils.js
This PR was triggered by #10515. Current `Count` implementation fails with SSR. 
1. Change `Count` into pure stateless component
2. localize component
3. add default values for i18n function to prevent SSR issues.
> Es6ify Count and make it SSR friendly.

- client/my-sites/current-site/index.jsx
Related: #10481
This pull request seeks to resolve an issue where confirming a cropped image to be used as the site icon will never save. See comments starting at https://github.com/Automattic/wp-calypso/pull/10481#issuecomment-272008076 for an explanation of the flow which results in an error being thrown by the re-fetching of domains in the `<CurrentSite />` component. The changes here revise the behavior to compare the site ID _after_ the component has updated, comparing on site ID of the current and previous props. Since it's not expected that triggering a domain fetch has any impact on the render behavior, it should be fine to react to the change having happened rather than in advance of it.
__Testing instructions:__
Verify expected behavior of domain fetching when switching site …
> Sites: Fetch domains upon update using previous ID as reference

- client/lib/abtest/active-tests.js
After verifying the User First signup flow is working correctly, we're ready to bump the test percentage higher.
cc @michaeldcain
> Signup: Bump UserFirst AB test to 95/5

- client/my-sites/posts/post-share.jsx
This PR changes phrasing out of confusing "Scheduling" to "Share" per @ryanboren suggestion
> Publicize: Copy improvements

- client/signup/steps/theme-selection/index.jsx
This PR brings the Theme selection step code to ES6. This is a part of an ongoing PRs that will bring the whole Signup code to ES6. 
To test:
1. Start Signup
2. Verify the Themes step is working correctly
3. Verify there are no JS errors in the console.
4. Finish Signup
5. Verify the chosen theme is applied to the registered site.
Bonus checks: Verify the Upload theme option and the following Perssable flow is working as expected.
cc @drewblaisdell @vindl as you worked with the step lately.
> Signup: ES6ify the Theme selection step

- client/reader/stream/recommended-posts.jsx
A tiny one - addresses this error:
> Fix recommended post proptype

- client/state/reader/posts/normalization-rules.js
- client/state/reader/posts/test/normalization-rules.js
Incomplete, more needed for full coverage.
No functional changes (I hope). Just tests.
> Reader: Add tests for classifyPost

- client/my-sites/menus/menu-item-list.jsx
#10551 introduced a regression for adding/editing sub menus.
closes #10614 
The required probs were not passed on recursion.
* Try creating/editing menus with more than one sublevel
> Menus: Fix adding/editing sub menus

- client/my-sites/posts/post-controls.jsx
- client/my-sites/posts/post-share.jsx
- client/my-sites/posts/style.scss
Before
After
Turns out, that issue is only for internal sites, private sites are behaving as usually
> Publicize: Change design for disabled publicize

- client/lib/analytics/ad-tracking.js
This PR adds post-purchase tracking for DoubleClick Manager (DCM) Floodlight.
To test:
1. Set `ad-tracking` to `true` in `development.json`.
2. On a test account, make a purchase.
3. In the network console, search for `fls.doubleclick.net`. You should see a request to a URL such as:
> https://6355556.fls.doubleclick.net/activityi;src=6355556;type=wpsal0;cat=wpsale;qty=1;cost=99;u2=WordPress.com%20Premium;u3=USD;u4=115436266;dc_lat=;dc_rdid=;tag_for_child_directed_treatment=;ord=18554515?
This gets 302 redirected and will load a similar URL such as:
> https://6355556.fls.doubleclick.net/activityi;dc_pre=CI7_uo6DvdECFUoFgQodfBkLuA;src=6355556;type=wpsal0;cat=wpsale;qty=1;cost=99;u2=WordPress.com%20Premium;u3=USD;u4=115436266;dc_lat=;dc_rdid=;tag_for_child_directed_treatment=;ord=18554515
4. …
> Ad Tracking: Add DCM Floodlight purchase tracking

- docs/guide/hello-world.md
I found that there is no instruction for styling a component in Hello World example, it makes new users confused especially who new to React (I saw people asking about it).
I could add a small section here about creating a `style.scss` file for the component, and importing it in to the main style file with example code. It's simple and mentioned in the Sass/CSS coding guidelines but it's naturally if we could say about it here for newcomers.
> Docs: Add instruction for creating Hello World's style.scss file

- assets/stylesheets/README.md
> Update Stylesheet README re: component styles

- client/lib/analytics/ad-tracking.js
- client/lib/analytics/index.js
When a visitor clicks an ad and lands on our site initially, the user get assigned an anonymous user id (like `I5gcq0szNly4FDMd3Ot4x%2F11`) that is stored in a `tk_ai` (Tracks anonymous user id) cookie. If that user then signs up or signs in, the Calypso's analytics module calls the Tracks JavaScript client's `identifyUser` method so that the anonymous user id gets tied to the WordPress.com user id (like `115436266`).
For our new DCM Floodlight integration, we need to do the same so that actions that users take while logged out (like visiting the marketing landing page) can easily be tied what they do while logged in.
This PR adds a new DCM Floodlight alias event to tie the logged out anonymous user id to the logged in WordPress.com user id.
1. As always, set `ad-tracking` to `true` in …
> Ad Tracking: Add a DCM Floodlight user aliasing

- client/layout/guided-tours/config.js
At least while #10568 is being debugged.
> Disable EditorInsertMenuTour

- client/layout/guided-tours/docs/ARCHITECTURE-FUTURE.md
I wanted to gather some thoughts and put them somewhere accessible, as reducing any [bus factor](https://en.wikipedia.org/wiki/Bus_factor) is always good.
> Guided Tours: Documentation on future architecture work

- client/my-sites/themes/single-site.jsx
Update label wording to match updated design.
> Update themes list label to match new design.

- Makefile
> Build: Easter egg, mostly for me

- client/lib/signup/themes-data.js
Swap Libre for its new replacement, Libre 2.
> Update themes in signup

- client/my-sites/menus/controller.js
- client/my-sites/menus/index.js
aka the most boring PR in the world 😴 
To test: Verify that the damn thing still works.
(I need this for something.)
> Menus: ES6ify Route Defs

- bin/build-metadata.js
- client/components/forms/docs/example.jsx
- client/components/forms/form-phone-media-input/index.jsx
- client/components/phone-input/data.js
- client/components/phone-input/index.jsx
- client/components/phone-input/phone-number.js
- client/components/phone-input/test/test-phone-number.js
This PR (part of #7453) attempts to do two things:
1. Simplify the data flow in the component
2. Fixes an edge case bug that happens when the user deletes the country dial code after selecting a country from the dropdown in the input. It mostly happens when the country dial code is 3-digits, but it's the result of us trying to format a number when the country dial code in the input doesn't match the actual dial code.
This PR is my first attempt at the problem and although I think it could be considered an improvement, I'm not super happy with it, yet.
I wanted to get an opinion from @aidvu and @klimeryk and see what you think and whether you can help with make this better.
> Phone Input: Improve data flow

- .github/CONTRIBUTING.md
- docs/coding-guidelines.md
s/SASS/Sass/
http://sass-lang.com/
> Docs: fix Sass spelling

- client/my-sites/upgrades/cart/cart-plan-ad.jsx
move isDomainOnlySite to destructuring const above
> Checkout: Small refactor to use destructuring

- client/layout/guided-tours/docs/ARCHITECTURE-FUTURE.md
Motivated by the interesting work in #10436.
> Guided Tours: Docs: Future state-aware capabilities

- client/post-editor/editor-action-bar/index.jsx
- client/post-editor/editor-action-bar/style.scss
This PR closes #10368.
**Before**
**After**
1. Navigate to [/post](http://calypso.localhost:3000/post)
2. Select a site
3. Change the author 
/cc @aduth, @DanReyLop
> Editor: Fix jumping of post type label

- client/signup/config/step-components.js
- client/signup/steps/user/index.jsx
- client/signup/steps/user/test/index.js
This PR brings the User step code to ES6. This is a part of an ongoing PRs that will bring the whole Signup code to ES6.
To test:
1. Start Signup
2. Go through Signup
3. Verify there are no JS errors in the console.
4. Finish Signup
5. Verify the user and site are created correctly
> Signup: ES6-ify the user step

- assets/stylesheets/_components.scss
I dind't include a changed file in my last pr and it's breaking the build. Merging this right away
> Jetpack plans: fix broke css build

- client/lib/plans/constants.js
Updates the copy of the Personal Plan storage information bubble to remove video.
> Personal Plan: Update information bubble.

- client/lib/analytics/index.js
Nested props are not supported by Tracks. Warn when not in production that we're trying to send them.
Also clean up analytics. Commits split to make the review easier.
Test live: https://calypso.live/?branch=update/tracks/detect-nested-props
> Analytics: Clean up analytics, warn when sending nested props

- client/my-sites/themes/theme-upload/index.jsx
Prevent theme uploads if jetpack plugin is not at required version, and render a button for updating.
**To Test**
* Requires a site with Jetpack plugin < 4.4.2, or modify [this selector](https://github.com/Automattic/wp-calypso/blob/ca5c540f13141a7a203d7509f26b145a4cf74b21/client/state/sites/selectors.js#L760) to always `return false`
* Go to http://calypso.localhost:3000/design/{jp site < 4.4.2}
* Hit the _Upload theme_ button at the top of the theme list
* **Expected** A notice should show (as screenshot above) with button for updating
* For sites > 4.4.2, the theme upload page should work as normal
* For wpcom sites, the Automated Transfer eligibility panel should display as normal
> Themes: Add jetpack version check/notice to upload page

- client/lib/analytics/index.js
This breaks out the debug calls by tracking environment. This makes it much easier to figure out which system is generating the debug calls, and limit the debug calls to a particular system.
To test, try setting `localStorage.debug` to `calypso:analytics:*`, `calypso:analytics:ga`, `calypso:analytics:tracks` and `calypso:analytics:mc` and see how the output changes on reload.
> Analytics: Break up the debugs

- server/bundler/bin/bundler.js
This turns on uglify's mangling, which can significantly reduce bundle sizes.
To test, spin up a docker instance with a production install and use Calypso.
```
docker build -t wp-calypso .
sudo vim /etc/hosts # add an entry for 127.0.0.1 wpcalypso.wordpress.com
docker run -it --name wp-calypso --rm -p 80:3000 -e NODE_ENV='production' -e CALYPSO_ENV='wpcalypso' wp-calypso
open http://wpcalypso.wordpress.com
```
You'll need to make sure you're not proxying to hit the pretend wpcalypso.wordpress.com
Size changes:
```
130K accept-invite.js						130K accept-invite.js
102K accept-invite.min.js				      |	66K accept-invite.min.js
241K account.js							241K account.js
179K account.min.js					      |	114K account.min.js
67K ads.js							67K ads.js
51K ads.min.js						      |	36K ads.min.js
236K …
```
> Build: Turn on mangling with Uglify

- config/stage.json
Staging environment will now use the production server that is staffed.
> Happychat: staging uses happychat.io

- docs/server-side-rendering.md
Add some explanation of how and why the two layers of server-side-rendering caching works the way it does. And some debugging info.
> Docs: Update SSR doc

- server/bundler/bin/bundler.js
- server/bundler/plugin.js
- server/pages/index.js
Reverts Automattic/wp-calypso#11005
Attempt number two at turning mangling on. The first try didn't seem to result in mangled variable names in production. Further investigation required.
Originally https://github.com/Automattic/wp-calypso/pull/10978
The alternative is https://github.com/Automattic/wp-calypso/pull/10634
----
This turns on uglify's mangling, which can significantly reduce bundle sizes.
To test, spin up a docker instance with a production install and use Calypso.
```
docker build -t wp-calypso .
sudo vim /etc/hosts # add an entry for 127.0.0.1 wpcalypso.wordpress.com
docker run -it --name wp-calypso --rm -p 80:3000 -e NODE_ENV='production' -e CALYPSO_ENV='wpcalypso' wp-calypso
open http://wpcalypso.wordpress.com
verify that the JS bundles have been mangled. 
- function …
```
> Build: Turn on mangling with Uglify, Take 2

- client/lib/analytics/README.md
Just an update to the Readme to reflect changes from #10964
> Analytics: Update Readme to reflect new debug

- client/lib/post-normalizer/rule-create-better-excerpt.js
- client/lib/post-normalizer/test/index.js
- client/state/reader/posts/normalization-rules.js
Right now we only expose the number in the better excerpt. This exposes the count for the whole post and updates the PHOTO_ONLY rule to use that count.
Fixes #11062
> Reader: Expose the number of characters in the post

- client/notifications/index.jsx
> Update notes client to latest production build

- client/lib/cart-values/cart-items.js
- client/lib/domains/index.js
- client/lib/wpcom-undocumented/lib/undocumented.js
- client/my-sites/upgrades/checkout/checkout.jsx
- client/my-sites/upgrades/checkout/domain-details-form.jsx
- client/my-sites/upgrades/checkout/style.scss
- client/my-sites/upgrades/domain-management/email/index.jsx
Reverts Automattic/wp-calypso#10843
> Revert "Allow adding G Suite to mapped domains"

- client/lib/feed-lookup/index.js
- client/lib/feed-store/actions.js
- client/lib/inflight/index.js
- client/lib/inflight/test/index.js
- client/lib/reader-feed-subscriptions/actions.js
- client/lib/recommended-sites-store/actions.js
Expose more of the lifecycle of `lib/inflight`, add tests, update callers.
To test, run the tests (CI will do this for you) and use the Reader.
> Framework: Update lib/inflight and clients
